### ISSUE TITLE
GLOBAL IN with subqueries very slow

### ISSUE THREAD

**Issue by DeanThompson** [ClickHouse/ClickHouse#27269] opened 2021-08-06 03:25 UTC
**Describe the situation**
Executing queries against the distributed table, with a GLOBAL IN and subquery, the performance is unexpectedly slow.

**How to reproduce**

Having a distributed table `t_table_all`, with about 1 billion rows in total.

```
SELECT count(1)
FROM t_table_all
WHERE category_id_3 GLOBAL IN (
  SELECT category_id_3
  FROM t_table_all
  WHERE brand_name = '1234'
    AND ((month >= '2020-01-01') AND (month <= '2021-06-01'))
  GROUP BY category_id_3
)
AND ((month >= '2021-05-01') AND (month <= '2021-06-01'))
```

This query takes 20s, but only 2s after replacing the subquery with constant values.

We are using 21.6.5 revision 54448, CentOS 7

Found a post (in Chinese) related to this issue [https://mp.weixin.qq.com/s/Dv7N_td9t5RfhuymkQlPug](https://mp.weixin.qq.com/s/Dv7N_td9t5RfhuymkQlPug). The original author thinks that the subquery produces too many small blocks, he modified the source code of `addExternalStorage` to [use `SquashingTransform` to compact the small blocks](https://github.com/kindred77/ClickHouse/blob/21.3-squashblock-for-globalsubquery/src/Interpreters/GlobalSubqueriesVisitor.h#L154) and get huge performance improvement: ~1 hour to 6 seconds!

**Comment by den-crane** [comment] 2021-08-06 03:33
Please share `show create table category_id_3` at least partition by / order by.
How many shards?

**Comment by DeanThompson** [comment] 2021-08-06 03:39
DDLs:

```sql
-- The underlying local table
CREATE TABLE t_table_local
(
  product_id              UInt64,
  category_id             UInt64,
  ...,
  brand_name              Nullable(String),
  category_id_3           LowCardinality(String),
  month                   Date
)
  ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/t_table_local', '{replica}')
    PARTITION BY month
    ORDER BY (category_id, product_id)
    SETTINGS index_granularity = 8192;

-- The distributed table
CREATE TABLE t_table_all
(
  product_id              UInt64,
  category_id             UInt64,
  ...,
  brand_name              Nullable(String),
  category_id_3           LowCardinality(String),
  month                   Date
)
  ENGINE = Distributed('current_cluster', 'db', 't_table_local', toYYYYMMDD(month));
```

There are 3 shards, 2 replicas to each shard.

**Comment by amosbird** [comment] 2021-08-06 04:45
>  the subquery produces too many small blocks

It's likely not related to your case because the subquery you give contains aggregation which will generate blocks with reasonable size. But it worths optimization.

**Comment by DeanThompson** [comment] 2021-08-06 05:51
Is there any workaround (i.e. change some settings values) to speed up before the official fix?

**Comment by amosbird** [comment] 2021-08-06 05:54
> Is there any workaround (i.e. change some settings values) to speed up before the official fix?

It's unclear what slows down your query. What do you mean by "replacing the subquery with constant values."?

**Comment by DeanThompson** [comment] 2021-08-06 06:03
> What do you mean by "replacing the subquery with constant values."?

Just split the query into two steps:

1. execute the subquery, get a list of `category_id_3` (["12", "123", "23"...])

```sql
  SELECT category_id_3
  FROM t_table_all
  WHERE brand_name = '1234'
    AND ((month >= '2020-01-01') AND (month <= '2021-06-01'))
  GROUP BY category_id_3
```

2. Replace the subquery with the values got from the last query

```sql
SELECT count(1)
FROM t_table_all
WHERE category_id_3 IN ("12", "123", "23"...)
AND ((month >= '2021-05-01') AND (month <= '2021-06-01'))
```

----

This approach needs much effort to rewrite all the queries.

**Comment by amosbird** [comment] 2021-08-06 06:06
How long does the query execution of first step take? And what's the size of the result?

**Comment by DeanThompson** [comment] 2021-08-06 06:10
> How long does the query execution of first step take? And what's the size of the result?

added to the last thread.

**Comment by amosbird** [comment] 2021-08-06 06:19
It makes little sense to me. Please share the TRACE LOG of these two runs.
```
set send_logs_level = 'trace';

-- slow run
SELECT count(1)
FROM t_table_all
WHERE category_id_3 GLOBAL IN (
  SELECT category_id_3
  FROM t_table_all
  WHERE brand_name = '1234'
    AND ((month >= '2020-01-01') AND (month <= '2021-06-01'))
  GROUP BY category_id_3
)
AND ((month >= '2021-05-01') AND (month <= '2021-06-01'));

-- fast run
SELECT count(1)
FROM t_table_all
WHERE category_id_3 IN ("12", "123", "23"...)
AND ((month >= '2021-05-01') AND (month <= '2021-06-01'));
```

**Comment by DeanThompson** [comment] 2021-08-06 06:47
The trace logs are quite long, so I paste to Gist, please [follow this link](https://gist.github.com/DeanThompson/95348685e69fe488d2f2910db2637fa8)

**Comment by amosbird** [comment] 2021-08-06 07:23
```
[ym7201] 2021.08.06 14:40:32.542796 [ 467350 ] {8ddaad74-56fc-4ff6-b9dc-5303ac09b4b5} <Debug> AggregatingTransform: Aggregated. 45330 to 147 rows (from 59.45 MiB) in 17.403244353 sec. (2604.687 rows/sec., 3.42 MiB/sec.)
```

Need to figure out why this aggregation took so long.

**Comment by jason-cognitiv** [comment] 2022-02-16 23:39
I don't have a repro I can drop here yet, as it is very related to the size of the sub query (working on it).  

But effectively, any GLOBAL IN or GLOBAL JOIN we do, once the subquery set reaches "some size based on unique keys", it crawls to a halt, looking at the server usage, it seems to be serialized on a single thread.  It seems related to the size of the hash table it needs to build, below a certain threshold its ok, but then stops.

If you take the subquery, lift it into a temporary table, and join against that, all is well.

**Comment by jason-cognitiv** [comment] 2022-02-22 07:04
@amosbird I think this repros the issue.  The profile looks like what happens on our production machines.  Only a couple cores are used to build the inner tables, then the whole thing uses all the available cores once that is done.

I can't get traces from our production machines where we see this. I used some exaggerated counts because our identifiers that cause this in production are strings that are larger than the ints here.  We see the same issue when doing GLOBAL JOINS.  I have seen instances where if I throw a GROUP BY {all_the_fields}, it improves performance quite a bit, when the number of rows is relatively small.

create table lotta_numbers(num UInt32) ENGINE=MergeTree() ORDER BY num as select * from numbers(100000000)

create table whole_lotta_numbers(num UInt32) ENGINE=MergeTree() ORDER BY num as select * from numbers(1000000000)

create table more_lotta_numbers(num UInt32) ENGINE=MergeTree() ORDER BY num as select * from numbers(300000000)

select count(*) from whole_lotta_numbers where num GLOBAL IN (select num from more_lotta_numbers where num GLOBAL IN (select num from lotta_numbers))

**Comment by nickitat** [comment] 2024-04-21 20:47
@DeanThompson  does it reproduce on the current release?

**Comment by DeanThompson** [comment] 2024-04-22 02:07
> @DeanThompson does it reproduce on the current release?

Hi @nickitat, thank you for the update. However, I am no longer involved in that project.

**Comment by nickitat** [comment] 2024-04-22 09:46
my attempt to reproduced failed, so closing until reproduced again

**Closed** 2024-04-22 09:46 UTC
Labels: performance, st-need-info, st-need-repro
