### ISSUE TITLE
Avoid sort block for MergeJoin when the join key is "sorted by" key

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#33326] opened 2021-12-30 13:36 UTC
### Discussed in https://github.com/ClickHouse/ClickHouse/discussions/33290

<div type='discussions-op-text'>

<sup>Originally posted by **Alex-Cheng** December 29, 2021</sup>
When choose MergeJoin instead HashJoin by setting `join_algorithm='prefer_partial_merge'` and the join key is actually sort key (declared in create table SQL `create table ... order by <the key used for join operator>`) , I see the sortBlock() function is always invoked. As the column is sort key it is not necessary to sort it again.

![image](https://user-images.githubusercontent.com/1518453/147669830-9e3fe9ce-f288-4b47-9d9e-394415a68f79.png)
</div>

**Comment by den-crane** [comment] 2021-12-30 13:45
>As the column is sort key it is not necessary to sort it again.

It's not true?
Each part has sorted set of rows, it needs to merge them.
Many parallel threads read sorted set of rows from many granules it needs to merge their results.
Many shards yield their sorted sets it needs to merge their results.

**Comment by den-crane** [comment] 2021-12-30 13:46
duplicate of https://github.com/ClickHouse/ClickHouse/discussions/33290

**Closed by den-crane** 2021-12-30 13:46 UTC

**Comment by Alex-Cheng** [comment] 2022-01-04 10:20
Does the block here contain rows from more than one parts or granule? If the join key is the only sort key, can we assume that the block is always sorted by joined key? Thank you.
