### ISSUE TITLE
Possible deadlock avoided

### ISSUE THREAD

**Issue by zzl-wy** [ClickHouse/ClickHouse#13873] opened 2020-08-19 02:53 UTC
We have met a problem that clickhouse deadlock.clickhouse recovered after a few minitues.
Our proccess halt when clickhouse deadlock.
ClickHouse server version is 20.3.15.133

![微信图片_20200819102407](https://user-images.githubusercontent.com/34508173/90586536-0171b180-e20a-11ea-81d1-56458ed30f31.png)
![微信图片_20200819102413](https://user-images.githubusercontent.com/34508173/90596344-5836b580-e221-11ea-8920-7184fb9f98a3.png)

**Comment by mjodeh** [comment] 2020-08-19 05:46
We faced this issue and we solved by controlling the insertion rate to be `1 bulk insertion per 2 seconds`
and we faced it only `system database`

**Comment by filimonov** [comment] 2020-08-19 09:53
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/9637

Fixed in 20.4 (fix can't be backported)

**Closed by filimonov** 2020-08-19 09:53 UTC
Labels: bug

**Comment by zzl-wy** [comment] 2020-08-20 02:42
we can reproduce this problem by insert data and remove partition on same table at same time. 
we have tested on version 20.4.8.99 (official build)),and the problem will occur.
![33](https://user-images.githubusercontent.com/34508173/90710812-bc18b700-e2d1-11ea-823e-74fdeba38ba4.png)

**Comment by den-crane** [comment] 2020-08-24 22:32
@zzl-wy try to upgrade to 20.4.9.110

Can also show "show create table".
I failed to reproduce this issue.

```
create table deadlocktest(A Int64, D Date, S String) Engine=MergeTree  partition by D order by A;

insert into deadlocktest select number, '2020-02-01', toString(cityHash64(number)) from numbers(10000000);

session1: 
for i in `seq 1 50000`; do echo $i; clickhouse-client -q "select uniqExact(S) from deadlocktest where D='2020-01-01'"; sleep .05; done;

session2: 
for i in `seq 1 50000`; do echo $i; clickhouse-client -q "alter table deadlocktest drop partition '2020-01-01'"; sleep .05; done; 

session3:
for i in `seq 1 50000`; do echo $i; clickhouse-client -tq "insert into deadlocktest select number, '2020-01-01', toString(cityHash64(number)) from numbers_mt(100000000)"; sleep .05; done;

```
