### ISSUE TITLE
Crash when ENGINE = PostgreSQL

### ISSUE THREAD

**Issue by yurayko** [ClickHouse/ClickHouse#26125] opened 2021-07-09 12:48 UTC
Debian PostgreSQL 11 

CREATE TABLE sche.pt (
        ts TIMESTAMP WITH TIME ZONE                DEFAULT NOW()                NOT NULL,
...
) PARTITION BY RANGE (ts);

ClickHouse

CREATE TABLE pt.d
(
	`ts` TIMESTAMP
)
ENGINE = PostgreSQL( 'srv', 'db', 'pt', 'logi', 'pass', 'sche' );

Crashed when `select ts from pt.d limit 1`

2021.07.09 15:28:52.786507 [ 20552 ] {aa35704a-4624-4259-9ead-ac45cc7ec015} <Debug> executeQuery: (from [::1]:47094, using production parser) select ts from pt.d limit 1
2021.07.09 15:28:52.786956 [ 20552 ] {aa35704a-4624-4259-9ead-ac45cc7ec015} <Trace> ContextAccess (default): Access granted: SELECT(ts) ON pt.d
2021.07.09 15:28:52.811011 [ 20550 ] {} <Trace> BaseDaemon: Received signal 11
2021.07.09 15:28:52.811356 [ 20624 ] {} <Fatal> BaseDaemon: ########################################
2021.07.09 15:28:52.811587 [ 20624 ] {} <Fatal> BaseDaemon: (version 21.6.6.51 (official build), build id: 2CCABC523E0F820656F456F7AA36FAE26195A55F) (from thread 20552) (query_id: aa35704a-4624-4259-9ead-ac45cc7ec015) Received signal Segmentation fault (11)
2021.07.09 15:28:52.811733 [ 20624 ] {} <Fatal> BaseDaemon: Address: 0x2000000000 Access: read. Address not mapped to object.
2021.07.09 15:28:52.811888 [ 20624 ] {} <Fatal> BaseDaemon: Stack trace: 0x14474985 0x14450da8 0x1444eaf1 0x144579f8 0x14452b88 0xf022a28 0xf0206b8 0xff02b1c 0xfe06117 0xf921a2f 0xf919463 0xf918520 0xfa888de 0xfa899b1 0xfc44781 0xfc42e03 0x10468bb2 0x1047bab9 0x12a7a50f 0x12a7bf9a 0x12bb52f9 0x12bb12ea 0x7f2078bb8fa3 0x7f2078ae94cf
2021.07.09 15:28:52.812082 [ 20624 ] {} <Fatal> BaseDaemon: 1. scram_HMAC_init @ 0x14474985 in ?
2021.07.09 15:28:52.812265 [ 20624 ] {} <Fatal> BaseDaemon: 2. pg_fe_scram_exchange @ 0x14450da8 in /usr/bin/clickhouse
2021.07.09 15:28:52.812412 [ 20624 ] {} <Fatal> BaseDaemon: 3. pg_fe_sendauth @ 0x1444eaf1 in /usr/bin/clickhouse
2021.07.09 15:28:52.812557 [ 20624 ] {} <Fatal> BaseDaemon: 4. PQconnectPoll @ 0x144579f8 in /usr/bin/clickhouse
2021.07.09 15:28:52.812693 [ 20624 ] {} <Fatal> BaseDaemon: 5. ? @ 0x14452b88 in /usr/bin/clickhouse
2021.07.09 15:28:52.812832 [ 20624 ] {} <Fatal> BaseDaemon: 6. pqxx::connection::connection(char const*) @ 0xf022a28 in /usr/bin/clickhouse
2021.07.09 15:28:52.812944 [ 20624 ] {} <Fatal> BaseDaemon: 7. postgres::PoolWithFailover::get() @ 0xf0206b8 in /usr/bin/clickhouse
2021.07.09 15:28:52.813037 [ 20624 ] {} <Fatal> BaseDaemon: 8. DB::StoragePostgreSQL::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xff02b1c in /usr/bin/clickhouse
2021.07.09 15:28:52.813134 [ 20624 ] {} <Fatal> BaseDaemon: 9. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfe06117 in /usr/bin/clickhouse
2021.07.09 15:28:52.813258 [ 20624 ] {} <Fatal> BaseDaemon: 10. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0xf921a2f in /usr/bin/clickhouse
2021.07.09 15:28:52.813384 [ 20624 ] {} <Fatal> BaseDaemon: 11. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0xf919463 in /usr/bin/clickhouse
2021.07.09 15:28:52.813504 [ 20624 ] {} <Fatal> BaseDaemon: 12. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf918520 in /usr/bin/clickhouse
2021.07.09 15:28:52.813599 [ 20624 ] {} <Fatal> BaseDaemon: 13. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0xfa888de in /usr/bin/clickhouse
2021.07.09 15:28:52.813676 [ 20624 ] {} <Fatal> BaseDaemon: 14. DB::InterpreterSelectWithUnionQuery::execute() @ 0xfa899b1 in /usr/bin/clickhouse
2021.07.09 15:28:52.813759 [ 20624 ] {} <Fatal> BaseDaemon: 15. ? @ 0xfc44781 in /usr/bin/clickhouse
2021.07.09 15:28:52.813849 [ 20624 ] {} <Fatal> BaseDaemon: 16. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0xfc42e03 in /usr/bin/clickhouse
2021.07.09 15:28:52.813945 [ 20624 ] {} <Fatal> BaseDaemon: 17. DB::TCPHandler::runImpl() @ 0x10468bb2 in /usr/bin/clickhouse
2021.07.09 15:28:52.814020 [ 20624 ] {} <Fatal> BaseDaemon: 18. DB::TCPHandler::run() @ 0x1047bab9 in /usr/bin/clickhouse
2021.07.09 15:28:52.814108 [ 20624 ] {} <Fatal> BaseDaemon: 19. Poco::Net::TCPServerConnection::start() @ 0x12a7a50f in /usr/bin/clickhouse
2021.07.09 15:28:52.814212 [ 20624 ] {} <Fatal> BaseDaemon: 20. Poco::Net::TCPServerDispatcher::run() @ 0x12a7bf9a in /usr/bin/clickhouse 
2021.07.09 15:28:52.814329 [ 20624 ] {} <Fatal> BaseDaemon: 21. Poco::PooledThread::run() @ 0x12bb52f9 in /usr/bin/clickhouse
2021.07.09 15:28:52.814417 [ 20624 ] {} <Fatal> BaseDaemon: 22. Poco::ThreadImpl::runnableEntry(void*) @ 0x12bb12ea in /usr/bin/clickhouse
2021.07.09 15:28:52.814487 [ 20624 ] {} <Fatal> BaseDaemon: 23. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
2021.07.09 15:28:52.814572 [ 20624 ] {} <Fatal> BaseDaemon: 24. clone @ 0xf94cf in /lib/x86_64-linux-gnu/libc-2.28.so
2021.07.09 15:28:52.940750 [ 20624 ] {} <Fatal> BaseDaemon: Checksum of the binary: BF3DA53F388FDAA6D8D9EB94B7353E63, integrity check passed.

**Comment by kssenii** [comment] 2021-07-09 12:58
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/24516. Was fixed in https://github.com/ClickHouse/ClickHouse/pull/25906.

**Closed** 2021-07-09 13:03 UTC
Labels: bug, st-fixed

**Comment by yurayko** [comment] 2021-09-28 09:14
Which version it is fixed?
Right now:
2021.09.28 12:04:32.084810 [ 6931 ] <Fatal> BaseDaemon: ########################################
2021.09.28 12:04:32.085052 [ 6931 ] <Fatal> BaseDaemon: (version 21.7.11.3 (official build), build id: 46A1DAE06173C184128BE296ED1C49DFDFA05904) (from thread 6747) (query_id: d2821122-4d75-4569-989b-a5e084c1f7c9) Received signal Segmentation fault (11)
2021.09.28 12:04:32.085120 [ 6931 ] <Fatal> BaseDaemon: Address: 0x2000000000 Access: read. Address not mapped to object.
2021.09.28 12:04:32.085199 [ 6931 ] <Fatal> BaseDaemon: Stack trace: 0x14f87045 0x14f63468 0x14f611b1 0x14f6a0b8 0x14f65248 0xf1fe348 0xf1fbf3a 0xf0023d7 0xf001f1d 0xf65f0ae 0xf742011 0xfcaa271 0xfaf17a1 0xfaf0e1e 0xfc6e9da 0xf8dc977 0xfe315d5 0xfe2ff03 0x106b43e2 0x106c7319 0x1339e6cf 0x133a015a 0x134d2fd9 0x134cf26a 0x7fa4066fafa3 0x7fa40661c4cf
2021.09.28 12:04:32.085292 [ 6931 ] <Fatal> BaseDaemon: 1. scram_HMAC_init @ 0x14f87045 in /usr/bin/clickhouse
2021.09.28 12:04:32.085356 [ 6931 ] <Fatal> BaseDaemon: 2. pg_fe_scram_exchange @ 0x14f63468 in /usr/bin/clickhouse
2021.09.28 12:04:32.085389 [ 6931 ] <Fatal> BaseDaemon: 3. pg_fe_sendauth @ 0x14f611b1 in /usr/bin/clickhouse
2021.09.28 12:04:32.085446 [ 6931 ] <Fatal> BaseDaemon: 4. PQconnectPoll @ 0x14f6a0b8 in /usr/bin/clickhouse
2021.09.28 12:04:32.085492 [ 6931 ] <Fatal> BaseDaemon: 5. ? @ 0x14f65248 in /usr/bin/clickhouse

**Comment by kssenii** [comment] 2021-09-28 09:17
@yurayko  Starting from 21.8, yours is 21.7.
