### ISSUE TITLE
done  MaterializeMySQL，however  clickhouse server abort，The error log is as follows

### ISSUE THREAD

**Issue by yizhipingnew** [ClickHouse/ClickHouse#14795] opened 2020-09-14 10:11 UTC
2020.09.14 15:51:41.314157 [ 4218 ] {} <Fatal> BaseDaemon: ########################################
2020.09.14 15:51:41.314215 [ 4218 ] {} <Fatal> BaseDaemon: (version 20.9.1.4571 (official build), no build id) (from thread 9653) (no query) Received signal Segmentation fault (11)
2020.09.14 15:51:41.314247 [ 4218 ] {} <Fatal> BaseDaemon: Address: 0x100 Access: read. Address not mapped to object.
2020.09.14 15:51:41.314267 [ 4218 ] {} <Fatal> BaseDaemon: Stack trace: 0x165ce35f 0xe5ff0ad 0x157ffcbf 0x15801242 0x157fa426 0x1580bb91 0x15819267 0x15816cc1 0x157ef830 0x157efc36 0xe641547 0xe63fb83 0x7f948bfaee25 0x7f948b8ccbad
2020.09.14 15:51:41.314316 [ 4218 ] {} <Fatal> BaseDaemon: 3. sallocx @ 0x165ce35f in /usr/bin/clickhouse
2020.09.14 15:51:41.314360 [ 4218 ] {} <Fatal> BaseDaemon: 4. operator delete(void*, unsigned long) @ 0xe5ff0ad in /usr/bin/clickhouse
2020.09.14 15:51:41.314395 [ 4218 ] {} <Fatal> BaseDaemon: 5. std::__1::__shared_ptr_emplace<DB::MySQLReplication::FormatDescriptionEvent, std::__1::allocator<DB::MySQLReplication::FormatDescriptionEvent> >::__on_zero_shared() @ 0x157ffcbf in /usr/bin/clickhouse
2020.09.14 15:51:41.314423 [ 4218 ] {} <Fatal> BaseDaemon: 6. std::__1::shared_ptr<DB::MySQLReplication::EventBase>::~shared_ptr() @ 0x15801242 in /usr/bin/clickhouse
2020.09.14 15:51:41.314444 [ 4218 ] {} <Fatal> BaseDaemon: 7. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x157fa426 in /usr/bin/clickhouse
2020.09.14 15:51:41.314463 [ 4218 ] {} <Fatal> BaseDaemon: 8. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x1580bb91 in /usr/bin/clickhouse
2020.09.14 15:51:41.314483 [ 4218 ] {} <Fatal> BaseDaemon: 9. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x15819267 in /usr/bin/clickhouse
2020.09.14 15:51:41.314501 [ 4218 ] {} <Fatal> BaseDaemon: 10. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x15816cc1 in /usr/bin/clickhouse
2020.09.14 15:51:41.314524 [ 4218 ] {} <Fatal> BaseDaemon: 11. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x157ef830 in /usr/bin/clickhouse
2020.09.14 15:51:41.314552 [ 4218 ] {} <Fatal> BaseDaemon: 12. ? @ 0x157efc36 in /usr/bin/clickhouse
2020.09.14 15:51:41.314574 [ 4218 ] {} <Fatal> BaseDaemon: 13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe641547 in /usr/bin/clickhouse
2020.09.14 15:51:41.314591 [ 4218 ] {} <Fatal> BaseDaemon: 14. ? @ 0xe63fb83 in /usr/bin/clickhouse
2020.09.14 15:51:41.314615 [ 4218 ] {} <Fatal> BaseDaemon: 15. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
2020.09.14 15:51:41.314672 [ 4218 ] {} <Fatal> BaseDaemon: 16. clone @ 0xfebad in /usr/lib64/libc-2.17.so
2020.09.14 15:58:37.068724 [ 4635 ] {} <Warning> Application: Listen [::1]:8123 failed: Poco::Exception. Code: 1000, e.code() = 99, e.displayText() = Net Exception: Cannot assign requested address: [::1]:8123 (version 20.9.1.4571 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2020.09.14 15:58:37.069343 [ 4635 ] {} <Warning> Application: Listen [::1]:9000 failed: Poco::Exception. Code: 1000, e.code() = 99, e.displayText() = Net Exception: Cannot assign requested address: [::1]:9000 (version 20.9.1.4571 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2020.09.14 15:58:37.069890 [ 4635 ] {} <Warning> Application: Listen [::1]:9009 failed: Poco::Exception. Code: 1000, e.code() = 99, e.displayText() = Net Exception: Cannot assign requested address: [::1]:9009 (version 20.9.1.4571 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2020.09.14 15:58:37.070418 [ 4635 ] {} <Warning> Application: Listen [::1]:9004 failed: Poco::Exception. Code: 1000, e.code() = 99, e.displayText() = Net Exception: Cannot assign requested address: [::1]:9004 (version 20.9.1.4571 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2020.09.14 15:58:37.078140 [ 4719 ] {} <Fatal> BaseDaemon: ########################################
2020.09.14 15:58:37.078288 [ 4719 ] {} <Fatal> BaseDaemon: (version 20.9.1.4571 (official build), no build id) (from thread 4675) (no query) Received signal Segmentation fault (11)
2020.09.14 15:58:37.078359 [ 4719 ] {} <Fatal> BaseDaemon: Address: 0x100 Access: read. Address not mapped to object.
2020.09.14 15:58:37.078424 [ 4719 ] {} <Fatal> BaseDaemon: Stack trace: 0x165ce35f 0xe5ff0ad 0x157ffcbf 0x15801242 0x157fa426 0x1580bb91 0x15819267 0x15816cc1 0x157ef830 0x157efc36 0xe641547 0xe63fb83 0x7f43bada6e25 0x7f43ba6c4bad
2020.09.14 15:58:37.078541 [ 4719 ] {} <Fatal> BaseDaemon: 3. sallocx @ 0x165ce35f in /usr/bin/clickhouse
2020.09.14 15:58:37.078668 [ 4719 ] {} <Fatal> BaseDaemon: 4. operator delete(void*, unsigned long) @ 0xe5ff0ad in /usr/bin/clickhouse
2020.09.14 15:58:37.078783 [ 4719 ] {} <Fatal> BaseDaemon: 5. std::__1::__shared_ptr_emplace<DB::MySQLReplication::FormatDescriptionEvent, std::__1::allocator<DB::MySQLReplication::FormatDescriptionEvent> >::__on_zero_shared() @ 0x157ffcbf in /usr/bin/clickhouse
2020.09.14 15:58:37.078862 [ 4719 ] {} <Fatal> BaseDaemon: 6. std::__1::shared_ptr<DB::MySQLReplication::EventBase>::~shared_ptr() @ 0x15801242 in /usr/bin/clickhouse
2020.09.14 15:58:37.078951 [ 4719 ] {} <Fatal> BaseDaemon: 7. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x157fa426 in /usr/bin/clickhouse
2020.09.14 15:58:37.079019 [ 4719 ] {} <Fatal> BaseDaemon: 8. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x1580bb91 in /usr/bin/clickhouse
2020.09.14 15:58:37.079086 [ 4719 ] {} <Fatal> BaseDaemon: 9. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x15819267 in /usr/bin/clickhouse
2020.09.14 15:58:37.079158 [ 4719 ] {} <Fatal> BaseDaemon: 10. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x15816cc1 in /usr/bin/clickhouse
2020.09.14 15:58:37.079226 [ 4719 ] {} <Fatal> BaseDaemon: 11. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x157ef830 in /usr/bin/clickhouse
2020.09.14 15:58:37.079287 [ 4719 ] {} <Fatal> BaseDaemon: 12. ? @ 0x157efc36 in /usr/bin/clickhouse
2020.09.14 15:58:37.079354 [ 4719 ] {} <Fatal> BaseDaemon: 13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe641547 in /usr/bin/clickhouse
2020.09.14 15:58:37.079411 [ 4719 ] {} <Fatal> BaseDaemon: 14. ? @ 0xe63fb83 in /usr/bin/clickhouse
2020.09.14 15:58:37.079480 [ 4719 ] {} <Fatal> BaseDaemon: 15. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
2020.09.14 15:58:37.079556 [ 4719 ] {} <Fatal> BaseDaemon: 16. clone @ 0xfebad in /usr/lib64/libc-2.17.so
2020.09.14 16:00:21.810977 [ 4839 ] {} <Warning> Application: Listen [::1]:8123 failed: Poco::Exception. Code: 1000, e.code() = 99, e.displayText() = Net Exception: Cannot assign requested address: [::1]:8123 (version 20.9.1.4571 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2020.09.14 16:00:21.811611 [ 4839 ] {} <Warning> Application: Listen [::1]:9000 failed: Poco::Exception. Code: 1000, e.code() = 99, e.displayText() = Net Exception: Cannot assign requested address: [::1]:9000 (version 20.9.1.4571 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2020.09.14 16:00:21.812155 [ 4839 ] {} <Warning> Application: Listen [::1]:9009 failed: Poco::Exception. Code: 1000, e.code() = 99, e.displayText() = Net Exception: Cannot assign requested address: [::1]:9009 (version 20.9.1.4571 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2020.09.14 16:00:21.812696 [ 4839 ] {} <Warning> Application: Listen [::1]:9004 failed: Poco::Exception. Code: 1000, e.code() = 99, e.displayText() = Net Exception: Cannot assign requested address: [::1]:9004 (version 20.9.1.4571 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2020.09.14 16:00:21.819912 [ 4918 ] {} <Fatal> BaseDaemon: ########################################
2020.09.14 16:00:21.820107 [ 4918 ] {} <Fatal> BaseDaemon: (version 20.9.1.4571 (official build), no build id) (from thread 4847) (no query) Received signal Segmentation fault (11)
2020.09.14 16:00:21.820211 [ 4918 ] {} <Fatal> BaseDaemon: Address: 0x100 Access: read. Address not mapped to object.
2020.09.14 16:00:21.820282 [ 4918 ] {} <Fatal> BaseDaemon: Stack trace: 0x165ce35f 0xe5ff0ad 0x157ffcbf 0x15801242 0x157fa426 0x1580bb91 0x15819267 0x15816cc1 0x157ef830 0x157efc36 0xe641547 0xe63fb83 0x7f73130b3e25 0x7f73129d1bad
2020.09.14 16:00:21.820411 [ 4918 ] {} <Fatal> BaseDaemon: 3. sallocx @ 0x165ce35f in /usr/bin/clickhouse
2020.09.14 16:00:21.820508 [ 4918 ] {} <Fatal> BaseDaemon: 4. operator delete(void*, unsigned long) @ 0xe5ff0ad in /usr/bin/clickhouse
2020.09.14 16:00:21.820591 [ 4918 ] {} <Fatal> BaseDaemon: 5. std::__1::__shared_ptr_emplace<DB::MySQLReplication::FormatDescriptionEvent, std::__1::allocator<DB::MySQLReplication::FormatDescriptionEvent> >::__on_zero_shared() @ 0x157ffcbf in /usr/bin/clickhouse
2020.09.14 16:00:21.820678 [ 4918 ] {} <Fatal> BaseDaemon: 6. std::__1::shared_ptr<DB::MySQLReplication::EventBase>::~shared_ptr() @ 0x15801242 in /usr/bin/clickhouse
2020.09.14 16:00:21.820756 [ 4918 ] {} <Fatal> BaseDaemon: 7. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x157fa426 in /usr/bin/clickhouse
2020.09.14 16:00:21.820835 [ 4918 ] {} <Fatal> BaseDaemon: 8. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x1580bb91 in /usr/bin/clickhouse
2020.09.14 16:00:21.820904 [ 4918 ] {} <Fatal> BaseDaemon: 9. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x15819267 in /usr/bin/clickhouse
2020.09.14 16:00:21.820970 [ 4918 ] {} <Fatal> BaseDaemon: 10. DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x15816cc1 in /usr/bin/clickhouse
2020.09.14 16:00:21.821045 [ 4918 ] {} <Fatal> BaseDaemon: 11. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x157ef830 in /usr/bin/clickhouse
2020.09.14 16:00:21.821122 [ 4918 ] {} <Fatal> BaseDaemon: 12. ? @ 0x157efc36 in /usr/bin/clickhouse
2020.09.14 16:00:21.821189 [ 4918 ] {} <Fatal> BaseDaemon: 13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe641547 in /usr/bin/clickhouse
2020.09.14 16:00:21.821252 [ 4918 ] {} <Fatal> BaseDaemon: 14. ? @ 0xe63fb83 in /usr/bin/clickhouse
2020.09.14 16:00:21.821328 [ 4918 ] {} <Fatal> BaseDaemon: 15. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
2020.09.14 16:00:21.821402 [ 4918 ] {} <Fatal> BaseDaemon: 16. clone @ 0xfebad in /usr/lib64/libc-2.17.so

**Comment by BohuTANG** [comment] 2020-09-15 09:34
From the root cause, this issue duplicated with https://github.com/ClickHouse/ClickHouse/issues/14786

**Comment by zhang2014** [comment] 2020-09-30 10:46
Maybe we can close this issue?

**Closed** 2020-09-30 15:53 UTC
Labels: bug, comp-mysql, crash
