### ISSUE TITLE
How to get rid of Stale Merge Processes: No active replica has part...

### ISSUE THREAD

**Issue by luck143** [ClickHouse/ClickHouse#6311] opened 2019-08-03 05:05 UTC
How to merge stale parts like .
Example below are almost one month old parts which have no hope of getting merged.

i tried to merge manually using 
```
OPTIMIZE TABLE clicks_32 PARTITION 201907 FINAL;
```
but they wont merge at all.

```
SELECT  name,partition,table FROM system.parts WHERE partition='201907' and active;
```
![Screenshot of result](https://i.gyazo.com/8f8da964df67b261c93fdb20b5b5827b.png)

i can see in the system.replication_queue table that that are stuck with the error reason `No active replica has part...`

```
select table,create_time,is_currently_executing,num_tries,last_exception,last_attempt_time,last_postpone_time from system.replication_queue where last_exception like '%No active replica has part%';
```
![Screenshot of result](https://i.gyazo.com/3afb020f4cdaecc61e06864260083bea.png)

such stale process keeps piling up our cluster and become reason for the Error `Too many parts (300). Merges are processing significantly slower than inserts`

**Comment by filimonov** [comment] 2019-09-09 22:11
Most probably duplicate of https://github.com/yandex/ClickHouse/issues/2755

**Comment by blinkov** [comment] 2020-04-01 16:30
@luck143, do you have any further questions?

**Closed** 2020-04-01 17:01 UTC
Labels: comp-replication, feature, question, usability
