### ISSUE TITLE
Add view function support to mysql/postgresql/odbc table functions.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#19320] opened 2021-01-20 14:47 UTC
Just like in https://github.com/ClickHouse/ClickHouse/pull/12567 But for mysql, postgresql and odbc table functions.

**Use case**
Run arbitrary queries in external databases with support of their sql syntax and functions.

**Describe the solution you'd like**
```
SELECT * FROM mysql('localhost',view(SELECT GROUP_CONCAT FROM table),'user','password')
```
**Describe alternatives you've considered**
Create an view on external database side, but it wouldn't work when we have per tenant tables, so we need to use different tables for each query.

**Additional context**
Loosely related to https://github.com/ClickHouse/ClickHouse/issues/19288

**Comment by filimonov** [comment] 2021-03-11 07:55
Also #1270

**Comment by pavelnemirovsky** [comment] 2021-04-18 10:59
+1

**Comment by alexey-milovidov** [comment] 2021-04-18 13:52
The drawback is that MySQL, Postgres have different lexers than ClickHouse.
And they are also different from each other.

Examples:

```
SELECT 'Hello\'
SELECT e'Hello\\'
$$ SELECT 1 $$
```

**Comment by alexey-milovidov** [comment] 2021-04-18 13:58
This feature can be postponed until we will add heredocs.
The examples of heredocs:

Postgres:

```
$here$ 
doc
$here$
```

Perl, PHP, sh:
```
<<<HERE
doc
HERE
```

Python (incomplete):
```
'''
doc
'''
```

C++:
```
R"here(
doc
)here"
```

XML (incomplete):
```
<[CDATA[
doc
]]>
```

Most likely we will take the syntax from Postgres.

**Comment by siradjev** [comment] 2021-08-17 12:20
> The drawback is that MySQL, Postgres have different lexers than ClickHouse.
> And they are also different from each other.
> 
> Examples:
> 
> ```
> SELECT 'Hello\'
> SELECT e'Hello\\'
> $$ SELECT 1 $$
> ```

Can't we simply pass quoted string with some inner single-quote escaping support as a simpler solution? Heredoc seems to be quite fundamental for complex queries, while majority of use-cases would be around primitive select/where/group/order queries... 
```
SELECT * FROM mysql('localhost',view('SELECT GROUP_CONCAT FROM table where AA=''dqdqwd'' '),'user','password')
```

**Comment by UnamedRus** [comment] 2021-08-17 13:29
Heredoc was already introduced https://github.com/ClickHouse/ClickHouse/pull/26671
I guess now this feature can be implemented.

**Comment by alexey-milovidov** [comment] 2022-01-18 01:19
Yes, it can be implemented.

**Comment by UnamedRus** [comment] 2023-04-14 21:03
Related https://github.com/ClickHouse/ClickHouse/issues/12478

**Comment by alexey-milovidov** [comment] 2024-01-01 16:39
Duplicate of #46758.

**Closed by alexey-milovidov** 2024-01-01 16:39 UTC
Labels: feature
