### ISSUE TITLE
A significant inserts slowdown in MacOS aarch64 version for tables with Map

### ISSUE THREAD

**Issue by pufit** [ClickHouse/ClickHouse#52097] opened 2023-07-13 20:49 UTC
**Describe the situation**
A significant inserts slowdown in MacOS aarch64 version (tested with v23.3.2.37-lts, but probably affects other versions)
Each inserted row takes ~0.25s

**How to reproduce**
```
CREATE TABLE kubernetes_efficiencies
(
    `service_costs_import_id` Int32,
    `service_costs_import_version` Int32,
    `integration_id` Int32,
    `date` Date,
    `cluster_id` String,
    `efficiency` Decimal(26, 10),
    `idle_cost` Decimal(26, 10),
    `amount` Decimal(26, 10),
    `category` String,
    `pod` String,
    `namespace` String,
    `labels` Map(String, String),
    `metadata` Map(String, String)
)
ENGINE = MergeTree
ORDER BY (integration_id, service_costs_import_id, service_costs_import_version, date, cluster_id, namespace)
SETTINGS index_granularity = 8192
```

```
INSERT INTO kubernetes_efficiencies
VALUES (1044195902, NULL, 980190963, '2023-07-13', 'bar', 0.7139223236, 18.0457798252, 63.08, 'cpu',
        '7fbf59fd-bd5b-45f1-9374-9251bac106fd', 'ns1', '{''app'':''foo'',''team'':''delivery''}', NULL)
```

```
Ok.

1 row in set. Elapsed: 0.252 sec.
```

**Additional context**
Reproduced with:
MacBook Pro Apple M2 Pro (13.2.1)
MacBook Air Apple M2 (13.4.1)

**Comment by pufit** [comment] 2023-07-14 03:57
I was about to collect stack traces of clickhouse-server but accidentally ran these queries with x86-64 (+rosetta) client and aarch64 server, and it executes instantly. I switched architectures (aarch64 client and x86-64 server) and still got lags. 

Here is a stack trace sample for aarch64 client
https://pastila.nl/?001cc7d8/5144f15c8f8521f0b0bb241fab4c5845

And a slightly more obscure stack trace, but with CPU times, collected by Xcode Instruments
https://pastila.nl/?00a48655/eae791ff1d1e5efd946feeac9cfb8f62

It seems that throwing an exception takes an absurd amount of time (hundreds of milliseconds)

**Comment by alexey-milovidov** [comment] 2023-07-14 18:47
Yes, it's normal for throwing an exception to take an arbitrarily long time. The reason - it has to read unwind tables that have to be loaded from the disk. Unwind tables are represented by a mini-virtual machine code (DWARF) that is interpreted. If you are running under Rosetta, it can be amplified... but I'm not sure.

**Comment by alexey-milovidov** [comment] 2023-07-14 18:48
Just in case - why it throws an exception?

**Comment by pufit** [comment] 2023-07-14 19:32
> If you are running under Rosetta, it can be amplified... but I'm not sure.

But it's strange because under Rosetta, I **don't** have any lags. But I see this significant slowdown with native arm architecture.

> Just in case - why it throws an exception?

For example, in this stack trace https://pastila.nl/?0119855a/dd5501902ee5a0bf6b41d7e2db85fec1 it throws this exception https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/ReadHelpers.cpp#L101

`out.str()` == `'{' before: '\'{"app":"foo","team":"delivery"}\', NULL)'`

**Comment by pufit** [comment] 2023-07-14 19:34
It also uses 100% of CPU, so probably it's not due to loading from disk.

**Comment by pufit** [comment] 2023-07-18 02:27
I discovered that our aarch64 binary has x33 more DWARF frames in it, so this should be the reason for such a slowdown. Now it makes sense why it loads 100% of CPU - it parses and interprets a significant amount of instructions.
![image](https://github.com/ClickHouse/ClickHouse/assets/19871338/4f42d332-15fe-48cf-b4fa-e5f7e4636852)

**Comment by al13n321** [comment] 2023-07-20 18:35
(I don't have a mac right now, but fwiw:)
 * Does the binary have .eh_frame_hdr section? It's an index that's supposed to make .eh_frame lookups fast.
 * Are exceptions similarly slow without ClickHouse collecting stack traces using libunwind? Afaiu, the exception mechanism itself (__cxa_throw or whatever) uses .eh_frame too. If it can do it quickly then the problem is probably in libunwind.
 * Moreover, your sample of stack traces, which says "every 1 millisecond" at the top - it's presumably collected using .eh_frame too! If it can keep up with the "every 1 millisecond" pace, that's interesting.
 * The stack traces are full of "parseCIE" and "findFDE". CIE and FDE are the entries in .eh_frame section. You only need one FDE per stack frame when unwinding, and I don't think individual entries can be very big. So if libunwind spends a lot of time parsing them, I think it means it does a lot of linear searching in .eh_frame, which means it's not using .eh_frame_hdr as it's supposed to.

**Comment by pufit** [comment] 2023-07-20 22:04
Yes, you are right. The `.eh_frame_hdr` section is absent in the macos-aarch64 version. However, it's missing in macos-x86-64 version too.

**Comment by pufit** [comment] 2023-07-20 22:29
We can probably remove `-fasynchronous-unwind-tables` for macos-aarch64, but this will also turn off backtraces for queries. https://github.com/ClickHouse/ClickHouse/blob/master/CMakeLists.txt#L260

**Comment by alexey-milovidov** [comment] 2023-12-20 07:11
It might be fixed in https://github.com/ClickHouse/ClickHouse/pull/57221.

**Closed by alexey-milovidov** 2023-12-20 07:11 UTC
Labels: performance, st-need-info

**Comment by nikitamikhaylov** [comment] 2024-02-07 20:06
With recent changes from https://github.com/ClickHouse/ClickHouse/pull/59690 it takes `0.01` seconds to insert the data into the table provided in the example https://pastila.nl/?0105287a/b0faf844675a05f30a14ab750d8733e2#JNOGfsz6fj7SlXa/epjLiw==
