### ISSUE TITLE
how to rewrite this SQL in clickhouse

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#28517] opened 2021-09-02 11:46 UTC
```sql
with 
s as (select number+1 n from system.numbers limit (6)),
p as (select 0 d,0 r
union all select 1,pi()/3*i from s
union all select 2,pi()/3*i from s
union all select sqrt(3),pi()/6+pi()/3*i from s),
t as(select p.*,row_number()over() rn from p),
e as(
select row_number()over() n,p1.rn p1,p2.rn p2,(p1.d*p1.d+p2.d*p2.d-2*p1.d*p2.d*cos(p1.r-p2.r))::int d from t p1,t p2 
where p1.rn>p2.rn),
tri as(
select e1.d from e e1,e e2
where e1.n>e2.n and e1.d=e2.d and e1.p1=e2.p1 and exists(select 1 from 
e e3 where e3.d=e2.d and(e3.p1,e3.p2) in((e1.p2,e2.p2),(e2.p2,e1.p2))))
select count(*)cnt,d from tri group by rollup(d);
```
it raised
```
Code: 62. DB::Exception: Syntax error: failed at position 494 ('1') (line 13, col 65): 1 from 
e e3 where e3.d=e2.d and(e3.p1,e3.p2) in((e1.p2,e2.p2),(e2.p2,e1.p2))))
select count(*)cnt,d from tri group by rollup(d);

. Expected one of: DoubleColon, LIKE, GLOBAL NOT IN, AS, DIV, IS, UUID, OR, QuestionMark, BETWEEN, NOT LIKE, MOD, AND, Comma, alias, IN, ILIKE, Dot, NOT ILIKE, NOT, Arrow, token, NOT IN, GLOBAL IN. (SYNTAX_ERROR) (version 21.10.1.7972 (official build))
```

**Comment by den-crane** [comment] 2021-09-02 22:29
What's this formulas?

CH does not support `exists` and correlated sub-queries.

`select 1,pi()/3*i from s` What is `i` here ?

**Comment by l1t1** [comment] 2021-09-03 01:50
my typo.
i should be n
it's answer puzzleup.com 2021 question no 1

**Comment by l1t1** [comment] 2021-09-03 02:07
```
with 
s as (select number+1 i from system.numbers limit (6)),
p as (select 0 d,0 r
union all select 1,pi()/3*i from s
union all select 2,pi()/3*i from s
union all select sqrt(3),pi()/6+pi()/3*i from s),
t as(select p.*,row_number()over() rn from p),
e as(
select row_number()over() n,p1.rn p1,p2.rn p2,(p1.d*p1.d+p2.d*p2.d-2*p1.d*p2.d*cos(p1.r-p2.r))::int d from t p1,t p2 
where p1.rn>p2.rn)
,
tri as(
select e1.d from e e1,e e2,e e3
where e1.n>e2.n and e1.d=e2.d and e1.p1=e2.p1 and e3.d=e2.d and(e3.p1,e3.p2) in((e1.p2,e2.p2),(e2.p2,e1.p2)))
select count(*)cnt,d from tri group by rollup(d);
```
rasied
```
Code: 47. DB::Exception: Missing columns: '--e2.p2' '--e1.p2' while processing query: '(`--e1.p2`, `--e2.p2`)', required columns: '--e1.p2' '--e2.p2' '--e1.p2' '--e2.p2': While processing (`--e1.n` > `--e2.n`) AND (`--e1.d` = `--e2.d`) AND (`--e1.p1` = `--e2.p1`) AND (d = `--e2.d`) AND ((p1, p2) IN ((`--e1.p2`, `--e2.p2`), (`--e2.p2`, `--e1.p2`))). (UNKNOWN_IDENTIFIER) (version 21.10.1.7972 (official build))
```

**Comment by l1t1** [comment] 2021-09-03 03:04
```sql
with 
s as (select number+1 i from system.numbers limit (6)),
p as (select 0 d,0 r
union all select 1,pi()/3*i from s
union all select 2,pi()/3*i from s
union all select sqrt(3),pi()/6+pi()/3*i from s),
t as(select p.*,row_number()over() rn from p),
e as(
select row_number()over() n,p1.rn p1,p2.rn p2,round(p1.d*p1.d+p2.d*p2.d-2*p1.d*p2.d*cos(p1.r-p2.r))::int d0 from t p1,t p2 
where p1.rn>p2.rn)
,
tri as(
select e1.d0 d0 from e e1,e e2,e e3
where e1.n>e2.n and e1.n>e3.n and e1.d0=e2.d0  and e1.p1=e2.p1 and e3.d0=e2.d0 and((e3.p1=e1.p2 and e3.p2=e2.p2) or(e3.p1=e2.p2 and e3.p2=e1.p2)))
select count(*)cnt,d0 from tri group by rollup(d0);
```
many running return different result. such as
```

cnt	d0
6	4
6	3
11	1
6	7
29	0

and

cnt	d0
2	3
12	1
14	7
2	13
30	0

```

**Comment by l1t1** [comment] 2021-09-03 03:05
is it a bug?

**Comment by l1t1** [comment] 2021-09-03 03:10
use over(order by d,r) instead of over() 

```sql

with 
s as (select number+1 i from system.numbers limit (6)),
p as (select 0 d,0 r
union all select 1,pi()/3*i from s
union all select 2,pi()/3*i from s
union all select sqrt(3),pi()/6+pi()/3*i from s),
t as(select p.*,row_number()over(order by d,r) rn from p),
e as(
select row_number()over() n,p1.rn p1,p2.rn p2,round(p1.d*p1.d+p2.d*p2.d-2*p1.d*p2.d*cos(p1.r-p2.r))::int d0 from t p1,t p2 
where p1.rn>p2.rn)
,
tri as(
select e1.d0 d0 from e e1,e e2,e e3
where e1.n>e2.n and e1.d0=e2.d0  and e1.p1=e2.p1 and e3.d0=e2.d0 and((e3.p1=e1.p2 and e3.p2=e2.p2) or(e3.p1=e2.p2 and e3.p2=e1.p2)))
select count(*)cnt,d0 from tri group by rollup(d0);
```
returns the right result
```
cnt	d0
12	4
14	3
24	1
12	7
2	9
2	12
66	0
```

**Comment by maxknv** [comment] 2024-06-05 12:46
I'm glad you made query working!
> many running return different result
> use over(order by d,r) instead of over()

UNION ALL does not guarantee the same order in resulting table, it's not a bug, you need `order by` to ensure the correct order. You figured this out already.

Im closing this issue. If you have other questions left, feel free to open new issue.
P.S.: Sorry for waiting so long, still less than 3 years though :)

**Closed by maxknv** 2024-06-05 12:46 UTC
Labels: question
