### ISSUE TITLE
Backup `ON CLUSTER` fails: Lock file .lock suddenly disappeared

### ISSUE THREAD

**Issue by vrfn** [ClickHouse/ClickHouse#49506] opened 2023-05-04 12:43 UTC
Backing up to an S3 disk using the ON CLUSTER clause always fails with the following error: 
`DB::Exception: Lock file .lock suddenly disappeared while writing backup Disk('minio_backup', 'my_backup_new'). (FAILED_TO_SYNC_BACKUP_OR_RESTORE)`

**Does it reproduce on recent release?**
Yes, v22.8.16.32-lts

**How to reproduce**
I have attached an S3 bucket as disk as described in the documentation [here](https://clickhouse.com/docs/en/operations/backup#backuprestore-using-an-s3-disk). 

In the the HTTP interface, create the `events` and `events_local` tables as described [here](https://github.com/Altinity/clickhouse-operator/blob/master/docs/replication_setup.md#create-replicated-table).

Then run `BACKUP TABLE <table> ON CLUSTER clustername TO Disk('minio_backup', 'my_backup_new')` on either the `events` or `events_local` table.

**Expected behavior**

A backup is created for all shards and replications of the table that was specified in the `BACKUP TABLE` query.

**Error message and/or stacktrace**

In the HTTP interface, the following error is returned:
`Code: 655. DB::Exception: Got error from service%2Dclustername%2D0%2D1:9000. DB::Exception: Lock file .lock suddenly disappeared while writing backup Disk('minio_backup', 'my_backup_new'). (FAILED_TO_SYNC_BACKUP_OR_RESTORE) (version 22.8.16.32 (official build))`

In the Clickhouse container logs:
```
2023.05.04 12:30:13.989203 [ 255 ] {4d012033-b4d6-444b-9d99-0a7e648a55c5} <Error> BackupsWorker: Failed to make internal backup Disk('minio_backup', 'my_backup_new'): Code: 655. DB::Exception: Lock file .lock suddenly disappeared while writing backup Disk('minio_backup', 'my_backup_new'). (FAILED_TO_SYNC_BACKUP_OR_RESTORE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa40285a in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1251f873 in /usr/bin/clickhouse
2. DB::BackupImpl::checkLockFile(bool) const @ 0x13ee9dca in /usr/bin/clickhouse
3. DB::BackupImpl::open(std::__1::shared_ptr<DB::Context const> const&) @ 0x13ee86df in /usr/bin/clickhouse
4. DB::BackupImpl::BackupImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::BackupImpl::ArchiveParams const&, std::__1::optional<DB::BackupInfo> const&, std::__1::shared_ptr<DB::IBackupWriter>, std::__1::shared_ptr<DB::Context const> const&, bool, std::__1::shared_ptr<DB::IBackupCoordination> const&, std::__1::optional<StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> > const&) @ 0x13ee911c in /usr/bin/clickhouse
5. ? @ 0x13f29f95 in /usr/bin/clickhouse
6. ? @ 0x13f2830c in /usr/bin/clickhouse
7. DB::BackupsWorker::doBackup(std::__1::shared_ptr<DB::ASTBackupQuery> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::BackupSettings, DB::BackupInfo const&, std::__1::shared_ptr<DB::IBackupCoordination>, std::__1::shared_ptr<DB::Context const> const&, std::__1::shared_ptr<DB::Context>, bool) @ 0x13ebbe8e in /usr/bin/clickhouse
8. ? @ 0x13ec2fa2 in /usr/bin/clickhouse
9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa4c6ae6 in /usr/bin/clickhouse
10. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xa4c8437 in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4c4408 in /usr/bin/clickhouse
12. ? @ 0xa4c761d in /usr/bin/clickhouse
13. ? @ 0x7fddb5c75609 in ?
14. clone @ 0x7fddb5b9a133 in ?
 (version 22.8.16.32 (official build))

```

**Additional context**

- When running the same backup query without `ON CLUSTER`, it works fine. The data is written to the bucket and I can restore it without problems.
- Running `BACKUP DATABASE` (instead of `TABLE`) with `ON CLUSTER` fails with the same error
- Clickhouse is deployed using the clickhouse-operator (version  0.20.3) on an on-premise Kubernetes cluster.
- Minio is used to host the S3 bucket. 

It seems that the same issue is mentioned [here](https://github.com/ClickHouse/ClickHouse/pull/39254), but there has been no follow-up.

**Comment by tavplubix** [comment] 2023-05-04 12:55
Looks like a duplicate of https://github.com/ClickHouse/ClickHouse/issues/47729

**Comment by vrfn** [comment] 2023-05-04 13:11
Yes, looks exactly like my issue. Will monitor that issue and see if it resolves my issue as well. Thanks!

**Closed** 2023-05-04 13:11 UTC
Labels: potential bug
