### ISSUE TITLE
toDate() returns ambiguous results for non-existent dates 

### ISSUE THREAD

**Issue by romansivolobtsev** [ClickHouse/ClickHouse#39628] opened 2022-07-26 20:27 UTC
Hello! I'm confused by the logic of handling non-existent dates. Some of them converts to `1970-01-01` another to future dates.

Let's take an example:
 ```
SELECT
    toDate('2022-02-28'),
    toDate('2022-02-29'),
    toDate('2022-02-30'),
    toDate('2022-02-31'),
    toDate('2022-02-32')

┌─toDate('2022-02-28')─┬─toDate('2022-02-29')─┬─toDate('2022-02-30')─┬─toDate('2022-02-31')─┬─toDate('2022-02-32')─┐
│           2022-02-28 │           2022-03-01 │           2022-03-02 │           2022-03-03 │           1970-01-01 │
└──────────────────────┴──────────────────────┴──────────────────────┴──────────────────────┴──────────────────────┘

```
It looks like there is a separate processing logic for cases when day of the month greater than 31.
Is it possible to return `1970-01-01` for all non-existing dates? 

ClickHouse server/client 22.7.1.2484

Thanks

**Comment by den-crane** [comment] 2022-07-26 20:31
https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#tostartofmonth

The behavior of parsing incorrect dates is implementation specific. ClickHouse may return zero date, throw an exception or do “natural” overflow.

duplicate of

https://github.com/ClickHouse/ClickHouse/issues/21782
https://github.com/ClickHouse/ClickHouse/issues/8031
https://github.com/ClickHouse/ClickHouse/issues/7633

**Closed by den-crane** 2022-07-26 20:31 UTC
Labels: question
