### ISSUE TITLE
Error occurs when using distinct select with where filter on certain distributed table

### ISSUE THREAD

**Issue by fangyc** [ClickHouse/ClickHouse#2373] opened 2018-05-16 02:35 UTC
The SQL is like this:

    select distinct OriginCityName from on_time.ontime_all t where t."OriginStateName" = 'California'

where 'on_time.ontime_all' is a distributed table with column OriginCityName, OriginStateName and some others (same as its underlying local MergeTree tables). And the error is a follows:

    Received exception from server (version 1.1.54381):
    Code: 171. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Block structure mismatch in UNION stream: different number of columns:
    OriginCityName String String(size = 0)
    OriginCityName String String(size = 0), OriginStateName String String(size = 0). 

    0 rows in set. Elapsed: 0.186 sec. 

However, if I do one of the following to the SQL, the error dissapears:

- remove distinct
- remove the where clause
- replace where with prewhere
- add the "OriginStateName" column in the where clause to the select part as well
- change select part to select distinct *

**Comment by fangyc** [comment] 2018-05-29 12:37
The issue cannot be reproduced with very simple MergeTree and Distributed tables. The case where I found this problem is the OnTime test data on ClickHouse documentation. I changed it to cluster version with the following statements: 

    CREATE TABLE test.`ontime` on cluster test_shard (   `Year` UInt16,   `Quarter` UInt8,   `Month` UInt8,   `DayofMonth` UInt8,   `DayOfWeek` UInt8,   `FlightDate` Date,   `UniqueCarrier` FixedString(7),   `AirlineID` Int32,   `Carrier` FixedString(2),   `TailNum` String,   `FlightNum` String,   `OriginAirportID` Int32,   `OriginAirportSeqID` Int32,   `OriginCityMarketID` Int32,   `Origin` FixedString(5),   `OriginCityName` String,   `OriginState` FixedString(2),   `OriginStateFips` String,   `OriginStateName` String,   `OriginWac` Int32,   `DestAirportID` Int32,   `DestAirportSeqID` Int32,   `DestCityMarketID` Int32,   `Dest` FixedString(5),   `DestCityName` String,   `DestState` FixedString(2),   `DestStateFips` String,   `DestStateName` String,   `DestWac` Int32,   `CRSDepTime` Int32,   `DepTime` Int32,   `DepDelay` Int32,   `DepDelayMinutes` Int32,   `DepDel15` Int32,   `DepartureDelayGroups` String,   `DepTimeBlk` String,   `TaxiOut` Int32,   `WheelsOff` Int32,   `WheelsOn` Int32,   `TaxiIn` Int32,   `CRSArrTime` Int32,   `ArrTime` Int32,   `ArrDelay` Int32,   `ArrDelayMinutes` Int32,   `ArrDel15` Int32,   `ArrivalDelayGroups` Int32,   `ArrTimeBlk` String,   `Cancelled` UInt8,   `CancellationCode` FixedString(1),   `Diverted` UInt8,   `CRSElapsedTime` Int32,   `ActualElapsedTime` Int32,   `AirTime` Int32,   `Flights` Int32,   `Distance` Int32,   `DistanceGroup` UInt8,   `CarrierDelay` Int32,   `WeatherDelay` Int32,   `NASDelay` Int32,   `SecurityDelay` Int32,   `LateAircraftDelay` Int32,   `FirstDepTime` String,   `TotalAddGTime` String,   `LongestAddGTime` String,   `DivAirportLandings` String,   `DivReachedDest` String,   `DivActualElapsedTime` String,   `DivArrDelay` String,   `DivDistance` String,   `Div1Airport` String,   `Div1AirportID` Int32,   `Div1AirportSeqID` Int32,   `Div1WheelsOn` String,   `Div1TotalGTime` String,   `Div1LongestGTime` String,   `Div1WheelsOff` String,   `Div1TailNum` String,   `Div2Airport` String,   `Div2AirportID` Int32,   `Div2AirportSeqID` Int32,   `Div2WheelsOn` String,   `Div2TotalGTime` String,   `Div2LongestGTime` String,   `Div2WheelsOff` String,   `Div2TailNum` String,   `Div3Airport` String,   `Div3AirportID` Int32,   `Div3AirportSeqID` Int32,   `Div3WheelsOn` String,   `Div3TotalGTime` String,   `Div3LongestGTime` String,   `Div3WheelsOff` String,   `Div3TailNum` String,   `Div4Airport` String,   `Div4AirportID` Int32,   `Div4AirportSeqID` Int32,   `Div4WheelsOn` String,   `Div4TotalGTime` String,   `Div4LongestGTime` String,   `Div4WheelsOff` String,   `Div4TailNum` String,   `Div5Airport` String,   `Div5AirportID` Int32,   `Div5AirportSeqID` Int32,   `Div5WheelsOn` String,   `Div5TotalGTime` String,   `Div5LongestGTime` String,   `Div5WheelsOff` String,   `Div5TailNum` String ) ENGINE = MergeTree(FlightDate, (Year, FlightDate), 8192)

and 

    CREATE TABLE test.`ontime_all` (   `Year` UInt16,   `Quarter` UInt8,   `Month` UInt8,   `DayofMonth` UInt8,   `DayOfWeek` UInt8,   `FlightDate` Date,   `UniqueCarrier` FixedString(7),   `AirlineID` Int32,   `Carrier` FixedString(2),   `TailNum` String,   `FlightNum` String,   `OriginAirportID` Int32,   `OriginAirportSeqID` Int32,   `OriginCityMarketID` Int32,   `Origin` FixedString(5),   `OriginCityName` String,   `OriginState` FixedString(2),   `OriginStateFips` String,   `OriginStateName` String,   `OriginWac` Int32,   `DestAirportID` Int32,   `DestAirportSeqID` Int32,   `DestCityMarketID` Int32,   `Dest` FixedString(5),   `DestCityName` String,   `DestState` FixedString(2),   `DestStateFips` String,   `DestStateName` String,   `DestWac` Int32,   `CRSDepTime` Int32,   `DepTime` Int32,   `DepDelay` Int32,   `DepDelayMinutes` Int32,   `DepDel15` Int32,   `DepartureDelayGroups` String,   `DepTimeBlk` String,   `TaxiOut` Int32,   `WheelsOff` Int32,   `WheelsOn` Int32,   `TaxiIn` Int32,   `CRSArrTime` Int32,   `ArrTime` Int32,   `ArrDelay` Int32,   `ArrDelayMinutes` Int32,   `ArrDel15` Int32,   `ArrivalDelayGroups` Int32,   `ArrTimeBlk` String,   `Cancelled` UInt8,   `CancellationCode` FixedString(1),   `Diverted` UInt8,   `CRSElapsedTime` Int32,   `ActualElapsedTime` Int32,   `AirTime` Int32,   `Flights` Int32,   `Distance` Int32,   `DistanceGroup` UInt8,   `CarrierDelay` Int32,   `WeatherDelay` Int32,   `NASDelay` Int32,   `SecurityDelay` Int32,   `LateAircraftDelay` Int32,   `FirstDepTime` String,   `TotalAddGTime` String,   `LongestAddGTime` String,   `DivAirportLandings` String,   `DivReachedDest` String,   `DivActualElapsedTime` String,   `DivArrDelay` String,   `DivDistance` String,   `Div1Airport` String,   `Div1AirportID` Int32,   `Div1AirportSeqID` Int32,   `Div1WheelsOn` String,   `Div1TotalGTime` String,   `Div1LongestGTime` String,   `Div1WheelsOff` String,   `Div1TailNum` String,   `Div2Airport` String,   `Div2AirportID` Int32,   `Div2AirportSeqID` Int32,   `Div2WheelsOn` String,   `Div2TotalGTime` String,   `Div2LongestGTime` String,   `Div2WheelsOff` String,   `Div2TailNum` String,   `Div3Airport` String,   `Div3AirportID` Int32,   `Div3AirportSeqID` Int32,   `Div3WheelsOn` String,   `Div3TotalGTime` String,   `Div3LongestGTime` String,   `Div3WheelsOff` String,   `Div3TailNum` String,   `Div4Airport` String,   `Div4AirportID` Int32,   `Div4AirportSeqID` Int32,   `Div4WheelsOn` String,   `Div4TotalGTime` String,   `Div4LongestGTime` String,   `Div4WheelsOff` String,   `Div4TailNum` String,   `Div5Airport` String,   `Div5AirportID` Int32,   `Div5AirportSeqID` Int32,   `Div5WheelsOn` String,   `Div5TotalGTime` String,   `Div5LongestGTime` String,   `Div5WheelsOff` String,   `Div5TailNum` String ) ENGINE = Distributed(test_shard, test, on_time, Month)

after creating the 2 tables, execute the select statement, and the problem will be produced.

**Comment by Ouriel** [comment] 2018-09-27 16:03
Seems duplicate of this one : #2156

**Comment by alexey-milovidov** [comment] 2020-04-20 08:25
Fixed some time ago.

**Closed** 2020-04-20 08:24 UTC
Labels: st-fixed
