### ISSUE TITLE
How to query Live View when ClickHouse server restart?

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#8936] opened 2020-01-31 15:24 UTC
I have read the article [Using Live View Tables with a Real Dataset](https://www.altinity.com/blog/2019/11/14/using-live-view-tables-with-a-real-dataset) ,get the usage of Live View table.But I have a question,when I restart the ClickHouse server,my lv table is empty.So if my query is queried Live View table directly,it would be wrong.
I cant find the information of Live View table in official document.Is it a propose of Live View table?

**Comment by vzakaznikov** [comment] 2020-02-01 13:24
Hi @byx313, the Live View table supposed to work as expected after restart. I will recreate the tables in the article and will check what is going on.

**Comment by vzakaznikov** [comment] 2020-02-01 14:04
Hi @byx313, I can't reproduce the issue that you are seeing. Here is my test case.

1. I enable live views and create a live view table.
```
ClickHouse client version 20.2.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.2.1 revision 54432.

:) SET allow_experimental_live_view = 1

SET allow_experimental_live_view = 1

Ok.

0 rows in set. Elapsed: 0.007 sec. 

Ubuntu-1804-bionic-64-minimal :) CREATE LIVE VIEW lv AS SELECT OriginCityName, count(*) AS flights FROM ontime_live GROUP BY OriginCityName ORDER BY flights DESC LIMIT 10

CREATE LIVE VIEW lv AS
SELECT 
    OriginCityName, 
    count(*) AS flights
FROM ontime_live
GROUP BY OriginCityName
ORDER BY flights DESC
LIMIT 10

Ok.

0 rows in set. Elapsed: 0.018 sec. 
```

2. I run WATCH on it 

```
:) watch lv limit 0

WATCH lv
LIMIT 0

┌─OriginCityName────────┬─flights─┬─_version─┐
│ Chicago, IL           │ 5952506 │        1 │
│ Dallas/Fort Worth, TX │ 4523513 │        1 │
│ Atlanta, GA           │ 4430940 │        1 │
│ Los Angeles, CA       │ 3171155 │        1 │
│ Houston, TX           │ 3048146 │        1 │
│ Phoenix, AZ           │ 2691026 │        1 │
│ New York, NY          │ 2669917 │        1 │
│ St. Louis, MO         │ 2451168 │        1 │
│ Denver, CO            │ 2422209 │        1 │
│ Washington, DC        │ 2408547 │        1 │
└───────────────────────┴─────────┴──────────┘

10 rows in set. Elapsed: 0.008 sec. 
```

3. I restart the server, re-enable live view tables and run the same statement

```
:) SET allow_experimental_live_view = 1

SET allow_experimental_live_view = 1

Ok.

0 rows in set. Elapsed: 0.007 sec. 

Ubuntu-1804-bionic-64-minimal :) watch lv limit 0

WATCH lv
LIMIT 0

┌─OriginCityName────────┬─flights─┬─_version─┐
│ Chicago, IL           │ 5952506 │        1 │
│ Dallas/Fort Worth, TX │ 4523513 │        1 │
│ Atlanta, GA           │ 4430940 │        1 │
│ Los Angeles, CA       │ 3171155 │        1 │
│ Houston, TX           │ 3048146 │        1 │
│ Phoenix, AZ           │ 2691026 │        1 │
│ New York, NY          │ 2669917 │        1 │
│ St. Louis, MO         │ 2451168 │        1 │
│ Denver, CO            │ 2422209 │        1 │
│ Washington, DC        │ 2408547 │        1 │
└───────────────────────┴─────────┴──────────┘

10 rows in set. Elapsed: 5.978 sec. 

Ubuntu-1804-bionic-64-minimal :) 
```
So I see the same result as before restarting the server.

Could you provide detailed steps of what you trying to do? Thanks!

**Comment by vzakaznikov** [comment] 2020-02-01 14:15
So the expected behaviour is that if the Live View table did not execute the stored query it will execute it on the first access. Either when you run the first `SELECT` or the first `WATCH` query. After that the Live View stays synced via INSERT "trigger" to the source table that is specified in the query. If for some reason you want to re-execute the stored query you can use ` ALTER LIVE VIEW [db.]table REFRESH` statement. It will force the Live View to drop its cached blocks and re-execution the stored query against the source table. There is also `max_live_view_insert_blocks_before_refresh` setting that forces stored query re-execution after the specified amount of new inserted blocks. This is due to the current limitation of how Live View table is implemented and is used to collapse the number of accumulated blocks.

**Comment by byx313** [comment] 2020-02-02 03:30
> Hi @byx313, I can't reproduce the issue that you are seeing. Here is my test case.
> 
> 1. I enable live views and create a live view table.
> 
> ```
> ClickHouse client version 20.2.1.1.
> Connecting to localhost:9000 as user default.
> Connected to ClickHouse server version 20.2.1 revision 54432.
> 
> :) SET allow_experimental_live_view = 1
> 
> SET allow_experimental_live_view = 1
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.007 sec. 
> 
> Ubuntu-1804-bionic-64-minimal :) CREATE LIVE VIEW lv AS SELECT OriginCityName, count(*) AS flights FROM ontime_live GROUP BY OriginCityName ORDER BY flights DESC LIMIT 10
> 
> CREATE LIVE VIEW lv AS
> SELECT 
>     OriginCityName, 
>     count(*) AS flights
> FROM ontime_live
> GROUP BY OriginCityName
> ORDER BY flights DESC
> LIMIT 10
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.018 sec. 
> ```
> 
> 1. I run WATCH on it
> 
> ```
> :) watch lv limit 0
> 
> WATCH lv
> LIMIT 0
> 
> ┌─OriginCityName────────┬─flights─┬─_version─┐
> │ Chicago, IL           │ 5952506 │        1 │
> │ Dallas/Fort Worth, TX │ 4523513 │        1 │
> │ Atlanta, GA           │ 4430940 │        1 │
> │ Los Angeles, CA       │ 3171155 │        1 │
> │ Houston, TX           │ 3048146 │        1 │
> │ Phoenix, AZ           │ 2691026 │        1 │
> │ New York, NY          │ 2669917 │        1 │
> │ St. Louis, MO         │ 2451168 │        1 │
> │ Denver, CO            │ 2422209 │        1 │
> │ Washington, DC        │ 2408547 │        1 │
> └───────────────────────┴─────────┴──────────┘
> 
> 10 rows in set. Elapsed: 0.008 sec. 
> ```
> 
> 1. I restart the server, re-enable live view tables and run the same statement
> 
> ```
> :) SET allow_experimental_live_view = 1
> 
> SET allow_experimental_live_view = 1
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.007 sec. 
> 
> Ubuntu-1804-bionic-64-minimal :) watch lv limit 0
> 
> WATCH lv
> LIMIT 0
> 
> ┌─OriginCityName────────┬─flights─┬─_version─┐
> │ Chicago, IL           │ 5952506 │        1 │
> │ Dallas/Fort Worth, TX │ 4523513 │        1 │
> │ Atlanta, GA           │ 4430940 │        1 │
> │ Los Angeles, CA       │ 3171155 │        1 │
> │ Houston, TX           │ 3048146 │        1 │
> │ Phoenix, AZ           │ 2691026 │        1 │
> │ New York, NY          │ 2669917 │        1 │
> │ St. Louis, MO         │ 2451168 │        1 │
> │ Denver, CO            │ 2422209 │        1 │
> │ Washington, DC        │ 2408547 │        1 │
> └───────────────────────┴─────────┴──────────┘
> 
> 10 rows in set. Elapsed: 5.978 sec. 
> 
> Ubuntu-1804-bionic-64-minimal :) 
> ```
> 
> So I see the same result as before restarting the server.
> 
> Could you provide detailed steps of what you trying to do? Thanks!

thx for the reply.I will do the test again and see what's wrong in my environment/

**Comment by vzakaznikov** [comment] 2020-02-06 00:37
@byx313, can we close the issue?

**Comment by qoega** [comment] 2020-02-12 15:17
Fell free to reopen issue or make another one if problem remains

**Closed** 2020-02-12 15:16 UTC
Labels: question

**Comment by byx313** [comment] 2020-04-25 23:30
> Hi @byx313, I can't reproduce the issue that you are seeing. Here is my test case.
> 
> 1. I enable live views and create a live view table.
> 
> ```
> ClickHouse client version 20.2.1.1.
> Connecting to localhost:9000 as user default.
> Connected to ClickHouse server version 20.2.1 revision 54432.
> 
> :) SET allow_experimental_live_view = 1
> 
> SET allow_experimental_live_view = 1
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.007 sec. 
> 
> Ubuntu-1804-bionic-64-minimal :) CREATE LIVE VIEW lv AS SELECT OriginCityName, count(*) AS flights FROM ontime_live GROUP BY OriginCityName ORDER BY flights DESC LIMIT 10
> 
> CREATE LIVE VIEW lv AS
> SELECT 
>     OriginCityName, 
>     count(*) AS flights
> FROM ontime_live
> GROUP BY OriginCityName
> ORDER BY flights DESC
> LIMIT 10
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.018 sec. 
> ```
> 
> 1. I run WATCH on it
> 
> ```
> :) watch lv limit 0
> 
> WATCH lv
> LIMIT 0
> 
> ┌─OriginCityName────────┬─flights─┬─_version─┐
> │ Chicago, IL           │ 5952506 │        1 │
> │ Dallas/Fort Worth, TX │ 4523513 │        1 │
> │ Atlanta, GA           │ 4430940 │        1 │
> │ Los Angeles, CA       │ 3171155 │        1 │
> │ Houston, TX           │ 3048146 │        1 │
> │ Phoenix, AZ           │ 2691026 │        1 │
> │ New York, NY          │ 2669917 │        1 │
> │ St. Louis, MO         │ 2451168 │        1 │
> │ Denver, CO            │ 2422209 │        1 │
> │ Washington, DC        │ 2408547 │        1 │
> └───────────────────────┴─────────┴──────────┘
> 
> 10 rows in set. Elapsed: 0.008 sec. 
> ```
> 
> 1. I restart the server, re-enable live view tables and run the same statement
> 
> ```
> :) SET allow_experimental_live_view = 1
> 
> SET allow_experimental_live_view = 1
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.007 sec. 
> 
> Ubuntu-1804-bionic-64-minimal :) watch lv limit 0
> 
> WATCH lv
> LIMIT 0
> 
> ┌─OriginCityName────────┬─flights─┬─_version─┐
> │ Chicago, IL           │ 5952506 │        1 │
> │ Dallas/Fort Worth, TX │ 4523513 │        1 │
> │ Atlanta, GA           │ 4430940 │        1 │
> │ Los Angeles, CA       │ 3171155 │        1 │
> │ Houston, TX           │ 3048146 │        1 │
> │ Phoenix, AZ           │ 2691026 │        1 │
> │ New York, NY          │ 2669917 │        1 │
> │ St. Louis, MO         │ 2451168 │        1 │
> │ Denver, CO            │ 2422209 │        1 │
> │ Washington, DC        │ 2408547 │        1 │
> └───────────────────────┴─────────┴──────────┘
> 
> 10 rows in set. Elapsed: 5.978 sec. 
> 
> Ubuntu-1804-bionic-64-minimal :) 
> ```
> 
> So I see the same result as before restarting the server.
> 
> Could you provide detailed steps of what you trying to do? Thanks!

I do the test again and it works well.I remember I created the source table is `Buffer` at the last time so the data is lost.
lol.
Futher more,is this feature have been removed experimental tag?My CH version is 19.17.

**Comment by vzakaznikov** [comment] 2020-04-28 00:12
Hi @byx313, no, live views are still experimental. We still working on fully defining the feature and its implementation.
