### ISSUE TITLE
MaterializedPostgreSQL table isn't updated with new data.

### ISSUE THREAD

**Issue by kozlovalex** [ClickHouse/ClickHouse#40262] opened 2022-08-16 09:44 UTC
MaterializedPostgreSQL table isn't updated with new data.

After creating a MaterializedPostgreSQL table in ClickHouse, the table loads existing data, but does not take new data. After restarting ClickHouse, replication starts working.

ClickHouse version 22.7.3.5 (official build)
Ubuntu 22.04.1 LTS

PostgreSQL 11.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
CentOS Linux 7 (Core)

Postgres:

```
CREATE TABLE public.a1 (
	id bigserial NOT NULL,
	c1 int4 NULL,
	c2 int4 NULL,
	CONSTRAINT a1_pk PRIMARY KEY (id)
);

INSERT INTO a1 (c1, c2) VALUES( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1);

table a1;

 id | c1 | c2 
----+----+----
  1 |  1 |  1
  2 |  1 |  1
  3 |  1 |  1
  4 |  1 |  1
  5 |  1 |  1
  6 |  1 |  1
  7 |  1 |  1
  8 |  1 |  1
  9 |  1 |  1
(9 rows)

```

ClickHouse:
```

CREATE TABLE a1 (id Int64, c1 Int64, c2 Int64) 
ENGINE = MaterializedPostgreSQL('10.20.30.184:5432', 'test_db', 'a1', 'admin', 'password') 
PRIMARY KEY id;

SELECT * FROM a1

┌─id─┬─c1─┬─c2─┐
│  1 │  1 │  1 │
│  2 │  1 │  1 │
│  3 │  1 │  1 │
│  4 │  1 │  1 │
│  5 │  1 │  1 │
│  6 │  1 │  1 │
│  7 │  1 │  1 │
│  8 │  1 │  1 │
│  9 │  1 │  1 │
└────┴────┴────┘

9 rows in set. Elapsed: 0.005 sec. 

```

Postgres log:
```
2022-08-16 11:48:53.509 +03 [10.20.30.185(51854) (27035)] LOG:  logical decoding found consistent point at D43/2B545330
2022-08-16 11:48:53.509 +03 [10.20.30.185(51854) (27035)] DETAIL:  There are no running transactions.
2022-08-16 11:48:53.510 +03 [10.20.30.185(51854) (27035)] LOG:  exported logical decoding snapshot: "00000009-00005A86-1" with 0 transaction IDs
2022-08-16 11:48:53.867 +03 [10.20.30.185(51856) (27046)] LOG:  starting logical decoding for slot "test_db_a1_ch_replication_slot"
2022-08-16 11:48:53.867 +03 [10.20.30.185(51856) (27046)] DETAIL:  Streaming transactions committing after D43/2B545368, reading WAL from D43/2B545330.
2022-08-16 11:48:53.867 +03 [10.20.30.185(51856) (27046)] STATEMENT:  SELECT end_lsn FROM pg_replication_slot_advance('test_db_a1_ch_replication_slot', 'D43/2B545368')
2022-08-16 11:48:53.867 +03 [10.20.30.185(51856) (27046)] LOG:  logical decoding found consistent point at D43/2B545330
2022-08-16 11:48:53.867 +03 [10.20.30.185(51856) (27046)] DETAIL:  There are no running transactions.
2022-08-16 11:48:53.867 +03 [10.20.30.185(51856) (27046)] STATEMENT:  SELECT end_lsn FROM pg_replication_slot_advance('test_db_a1_ch_replication_slot', 'D43/2B545368')
```

Postgres:

```
INSERT INTO a1 (c1, c2) VALUES( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1),( 1, 1);

table a1;
 id | c1 | c2 
----+----+----
  1 |  1 |  1
  2 |  1 |  1
  3 |  1 |  1
  4 |  1 |  1
  5 |  1 |  1
  6 |  1 |  1
  7 |  1 |  1
  8 |  1 |  1
  9 |  1 |  1
 10 |  1 |  1
 11 |  1 |  1
 12 |  1 |  1
 13 |  1 |  1
 14 |  1 |  1
 15 |  1 |  1
 16 |  1 |  1
 17 |  1 |  1
 18 |  1 |  1
(18 rows)
```

ClickHouse:
```
SELECT * FROM a1

┌─id─┬─c1─┬─c2─┐
│  1 │  1 │  1 │
│  2 │  1 │  1 │
│  3 │  1 │  1 │
│  4 │  1 │  1 │
│  5 │  1 │  1 │
│  6 │  1 │  1 │
│  7 │  1 │  1 │
│  8 │  1 │  1 │
│  9 │  1 │  1 │
└────┴────┴────┘

9 rows in set. Elapsed: 0.005 sec. 

```

After restarting ClickHouse, replication starts working.
There are no errors in the ClickHouse log and nothing unusual appears.

Periodic entries begin to appear in the Postgres log:
```
2022-08-16 12:18:32.159 +03 [10.20.30.185(51942) (7332)] LOG:  starting logical decoding for slot "test_db_a1_ch_replication_slot"
2022-08-16 12:18:32.159 +03 [10.20.30.185(51942) (7332)] DETAIL:  Streaming transactions committing after D43/2B5A9808, reading WAL from D43/2B5A9808.
2022-08-16 12:18:32.159 +03 [10.20.30.185(51942) (7332)] STATEMENT:  COPY (select lsn, data FROM pg_logical_slot_peek_binary_changes('test_db_a1_ch_replication_slot', NULL, 65536, 'publication_names', 'test_db_a1_ch_publication', 'proto_version', '1')) TO STDOUT
2022-08-16 12:18:32.159 +03 [10.20.30.185(51942) (7332)] LOG:  logical decoding found consistent point at D43/2B5A9808
2022-08-16 12:18:32.159 +03 [10.20.30.185(51942) (7332)] DETAIL:  There are no running transactions.
2022-08-16 12:18:32.159 +03 [10.20.30.185(51942) (7332)] STATEMENT:  COPY (select lsn, data FROM pg_logical_slot_peek_binary_changes('test_db_a1_ch_replication_slot', NULL, 65536, 'publication_names', 'test_db_a1_ch_publication', 'proto_version', '1')) TO STDOUT
```

**Comment by jpchev** [comment] 2023-12-05 10:06
I've tested this with the following ch version and can't reproduce it.
This has been fixed by https://github.com/ClickHouse/ClickHouse/pull/40511 
so can we close this issue?

_ClickHouse client version **23.10.5.20 (official build)**.
Connecting to localhost:9000 as user default.
Connected to ClickHouse **server version 23.10.5 revision 54466._**

**Comment by kssenii** [comment] 2023-12-05 11:21
Another possible reason - a year ago (when this issue was created), there was one place where an exception could be thrown and not caught or logged anywhere resulting in replication being stopped, but it was fixed since then.

**Closed by kssenii** 2023-12-05 11:21 UTC
Labels: experimental issue
