### ISSUE TITLE
HTTP Query response in Native format does not return timezone information 

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#46176] opened 2023-02-08 17:38 UTC
**Describe the issue**
A query over HTTP using Native format that includes a DateTime or DateTime64 column does not include timezone information.

**How to reproduce**
I think this is true on any ClickHouse version:

```
clickhouse-client --query="SELECT toTimezone(now(), 'America/Chicago') as tz_dt, now() as naive_dt FORMAT Native" | xxd

00000000: 0201 0574 7a5f 6474 0844 6174 6554 696d  ...tz_dt.DateTim
00000010: 65d0 cfe3 6308 6e61 6976 655f 6474 0844  e...c.naive_dt.D
00000020: 6174 6554 696d 65d0 cfe3 63              ateTime...c
```

(The HTTP response contains the same binary data as the clickhouse-client output shown here).  Note that the column types for both columns are bare `DateTime`

**Expected behavior**
The column type (including timezone) should be preserved -- i.e., the returned leb128 string should be `DateTime('America/Chicago')` This happens correctly over the native protocol.

**Comment by alexey-milovidov** [comment] 2023-02-09 06:17
This is needed for backward compatibility - not every client has support for DateTime with the timezone.

**Comment by genzgd** [comment] 2023-02-09 09:52
I thought that might be the case -- is there some way we could have apply a setting on the query?  And are there any active clients that can't actually handle this we know of?

**Comment by alexey-milovidov** [comment] 2023-02-09 19:29
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/40397

**Closed by alexey-milovidov** 2023-02-09 19:29 UTC
Labels: usability
