### ISSUE TITLE
Slow query when PK low_cardinality(String) in WHERE condition with IN 

### ISSUE THREAD

**Issue by mikhno-s** [ClickHouse/ClickHouse#45423] opened 2023-01-18 22:43 UTC
Query `WHERE artifact_id in ('artifactid')` works much slower than  `WHERE artifact_id = 'artifactid'`

* CH 22.12.3
```sql
CREATE TABLE logs_db.app_logs_shard
(
    `timestamp` DateTime64(3, 'Zulu'),
    `request_id` String DEFAULT '-',
    `artifact_id` LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (artifact_id, timestamp, request_id)
TTL toDate(timestamp) + toIntervalDay(30)
SETTINGS index_granularity = 8192
```
### Queries to run that lead to unexpected result
Took 3.5 sec and read a lot of data (with IN)

```sql
SELECT * FROM logs_db.logs
WHERE artifact_id in ('artifactid')
AND timestamp >= toDateTime64(1674069403, 3) AND timestamp <= toDateTime64(1674073003, 3)
ORDER BY timestamp DESC limit 100 format Null
...
[chlogs] 2023.01.18 19:58:55.913426 [ 62602 ] {9f9d59c0-2fe2-41f9-8d21-28616bd83ab5} <Debug> logs_db.logs_shard (9f2304cb-4a4a-4577-ac38-e02244c44ef0) (SelectExecutor): Key condition: (column 1 in ['1674068234', +Inf)), (column 1 in (-Inf, '1674071834']), and, unknown, (column 0 in 1-element set), and, and
[chlogs] 2023.01.18 19:58:55.914073 [ 62602 ] {9f9d59c0-2fe2-41f9-8d21-28616bd83ab5} <Debug> logs_db.logs_shard (9f2304cb-4a4a-4577-ac38-e02244c44ef0) (SelectExecutor): MinMax index condition: (column 0 in ['1674068234', +Inf)), (column 0 in (-Inf, '1674071834']), and, unknown, and, (column 0 in ['1674068234', +Inf)), (column 0 in (-Inf, '1674071834']), and, and
[chlogs] 2023.01.18 19:58:55.915556 [ 62602 ] {9f9d59c0-2fe2-41f9-8d21-28616bd83ab5} <Debug> logs_db.logs_shard (9f2304cb-4a4a-4577-ac38-e02244c44ef0) (SelectExecutor): Selected 18/333 parts by partition key, 18 parts by primary key, 4035/43263 marks by primary key, 4035 marks to read from 18 ranges
[chlogs] 2023.01.18 19:58:55.916777 [ 62602 ] {9f9d59c0-2fe2-41f9-8d21-28616bd83ab5} <Debug> logs_db.logs_shard (9f2304cb-4a4a-4577-ac38-e02244c44ef0) (SelectExecutor): Reading approx. 28149255 rows with 48 streams
...
0 rows in set. Elapsed: 3.623 sec. Processed 581.70 million rows, 1.01 TB (160.57 million rows/s., 279.65 GB/s.)

```

same with `=` took 0.1 sec
```sql
SELECT * FROM logs_db.logs
WHERE artifact_id = 'artifactid'
AND timestamp >= toDateTime64(1674069403, 3) AND timestamp <= toDateTime64(1674073003, 3)
ORDER BY timestamp DESC limit 100 
...
[chlogs] 2023.01.18 20:03:38.221264 [ 62602 ] {4ba9df42-e5c7-45e3-a800-230b5b38bcc5} <Debug> logs_db.logs_shard (9f2304cb-4a4a-4577-ac38-e02244c44ef0) (SelectExecutor): Key condition: (column 1 in ['1674068234', +Inf)), (column 1 in (-Inf, '1674071834']), and, unknown, (column 0 in ['artifactid', 'artifactid']), and, and
[chlogs] 2023.01.18 20:03:38.221955 [ 62602 ] {4ba9df42-e5c7-45e3-a800-230b5b38bcc5} <Debug> logs_db.logs_shard (9f2304cb-4a4a-4577-ac38-e02244c44ef0) (SelectExecutor): MinMax index condition: (column 0 in ['1674068234', +Inf)), (column 0 in (-Inf, '1674071834']), and, unknown, and, (column 0 in ['1674068234', +Inf)), (column 0 in (-Inf, '1674071834']), and, and
[chlogs] 2023.01.18 20:03:38.223493 [ 62602 ] {4ba9df42-e5c7-45e3-a800-230b5b38bcc5} <Debug> logs_db.logs_shard (9f2304cb-4a4a-4577-ac38-e02244c44ef0) (SelectExecutor): Selected 17/332 parts by partition key, 17 parts by primary key, 4036/46043 marks by primary key, 4036 marks to read from 17 ranges
...
0 rows in set. Elapsed: 0.198 sec. Processed 822.84 thousand rows, 1.09 GB (4.16 million rows/s., 5.54 GB/s.)
```

- Why does `WHERE artifact_id = 'artifactid'` work much faster?
- What is the proper way to run such queries if I need multi-condition like `WHERE artifact_id in ('artifactid1','artifactid2')`

Thanks a lot for your support!

**Comment by nickitat** [comment] 2023-02-14 23:18
duplicate of #43968

> What is the proper way to run such queries if I need multi-condition like WHERE artifact_id in ('artifactid1','artifactid2')

do exactly this, e.g. `WHERE artifact_id in ('artifactid1','artifactid2')`. CH can handle function `in` properly during PK analysis. so if you really have multiple values to match against there should be no perf problems.

**Closed by nickitat** 2023-02-14 23:18 UTC
Labels: unexpected behaviour
