### ISSUE TITLE
Index condition not deduced for joined table

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#10913] opened 2020-05-14 09:59 UTC
```
/4/ :) set force_index_by_date = 1


/4/ :) select count(*) from hits l join hits r using EventDate where l.EventDate < today();

Received exception from server (version 20.5.1):
Code: 277. DB::Exception: Received from localhost:9000. DB::Exception: MinMax index by columns (EventDate) is not used and setting 'force_index_by_date' is set: While executing CreatingSetsTransform. Stack trace:
```

The fix should probably start with adding a general understanding of transitive equality to the query planner.

Also, the error message could be better -- it doesn't tell the table name.

**Comment by akuzm** [comment] 2020-05-14 10:02
```
/4/ :) select count(*) from hits l join hits r using EventDate where l.EventDate < today() and r.EventDate < today();

Received exception from server (version 20.5.1):
Code: 277. DB::Exception: Received from localhost:9000. DB::Exception: MinMax index by columns (EventDate) is not used and setting 'force_index_by_date' is set: While executing CreatingSetsTransform. Stack trace:
```
O__O

**Comment by akuzm** [comment] 2020-05-14 10:07
See https://github.com/ClickHouse/ClickHouse/issues/10914 as well

**Comment by 4ertus2** [comment] 2020-05-14 17:21
The reason is right table is not rewritten to subquery:
```
ANALYZE SELECT count(*)
FROM hits AS l
INNER JOIN hits AS r USING (EventDate)
WHERE (l.EventDate < today()) AND (r.EventDate < today())

┌─explain───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ SELECT count()
FROM hits AS l
ALL INNER JOIN hits AS r USING (EventDate)
WHERE (EventDate < today()) AND (r.EventDate < today()) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by 4ertus2** [comment] 2020-07-15 15:53
Need rechek. It could be fixed in PR with join with dictionary optimisation.

**Comment by 4ertus2** [comment] 2020-08-24 10:14
Reproduced
```
drop table if exists t;
create table t (dt Date) engine = MergeTree ORDER BY dt PARTITION BY dt;
insert into t values (0);

set force_index_by_date = 1;

select count(*) from t l join t r
using dt
where l.dt < today();

drop table t;
```

**Comment by 4ertus2** [comment] 2020-09-22 18:18
Probably related #7593

**Comment by UnamedRus** [comment] 2024-03-12 10:23
PR https://github.com/ClickHouse/ClickHouse/pull/61216

**Closed** 2024-04-24 13:09 UTC
Labels: performance, comp-joins
