### ISSUE TITLE
alter table local_ods.dwd_mjh01 drop PARTITION today();  clickhouse version 20.3.12.112

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#15370] opened 2020-09-28 04:59 UTC
(you don't have to strictly follow this form)

**Describe the bug**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

-----------------------------------------------------------------------------------------
Test delete partition using today() function in clickhouse version 20.3.12.112 Error as follows

dev-hadoop-test01 :) alter table local_ods.dwd_mjh01 drop PARTITION today();

Syntax error: failed at position 55 (end of query):

alter table local_ods.dwd_mjh01 drop PARTITION today();

Expected one of: AND, OR, token, NOT, BETWEEN, LIKE, IS, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, QuestionMark

I tested the same statement in clickhouse 19.17.4.11 to be able to delete partition operations

**Comment by filimonov** [comment] 2020-09-28 10:08
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/10212#issuecomment-612676750

**Closed by filimonov** 2020-09-28 10:08 UTC
Labels: unexpected behaviour
