### ISSUE TITLE
problem with repositories: 503 - Service Unavailable 429 Too Many Requests

### ISSUE THREAD

**Issue by alexeyrusnak** [ClickHouse/ClickHouse#41676] opened 2022-09-22 09:22 UTC
Downloading packages:
clickhouse-common-static-22.8. FAILED
https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-22.8.5.29.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable  ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
clickhouse-server-22.8.5.29.x8 FAILED
https://packages.clickhouse.com/rpm/stable/clickhouse-server-22.8.5.29.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable         ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
clickhouse-common-static-22.8. FAILED
https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-22.8.5.29.x86_64.rpm: [Errno 14] HTTPS Error 429 - The requested URL returned error: 429 Too Many Requests
Trying other mirror.
clickhouse-server-22.8.5.29.x8 FAILED
https://packages.clickhouse.com/rpm/stable/clickhouse-server-22.8.5.29.x86_64.rpm: [Errno 14] HTTPS Error 429 - The requested URL returned error: 429 Too Many Requests-- ETA
Trying other mirror.

---
screenshot
https://monosnap.com/file/3oGrSvOf8MPeqJsi3SBQIEjaWD4OWl

**Comment by Borks** [comment] 2022-09-22 09:35
Also hitting the same issue.

**Comment by schorsch** [comment] 2022-09-22 09:36
same here for the deb version at 
 https://packages.clickhouse.com/deb/pool/stable/clickhouse-common-static_22.8.5.29_amd64.deb via https://packages.clickhouse.com/deb stable/main amd64

**Comment by Algunenano** [comment] 2022-09-22 09:38
Seems a duplicate of https://github.com/ClickHouse/ClickHouse/issues/41420

**Comment by Felixoid** [comment] 2022-09-22 14:06
Thank you. Yes, it was definitely firefighting, but now it should work. I not, please, report the issues in https://github.com/ClickHouse/ClickHouse/issues/41420

**Closed by Felixoid** 2022-09-22 14:06 UTC
Labels: potential bug
