### ISSUE TITLE
Lightweight DELETE causes error "Number of rows ... differs from ... rows_sources"

### ISSUE THREAD

**Issue by WillMeng** [ClickHouse/ClickHouse#41399] opened 2022-09-16 05:22 UTC
version: 22.8.4.7

**table schema**

```

-- pub_summary_db_sem_baidu.pub_setting_sem_keyword definition

CREATE TABLE pub_summary_db_sem_baidu.pub_setting_sem_keyword
(

    `channel_id` Int32,

    `publisher_id` Int32,

    `pc_left_price_guide` Float64,

    `pc_reason` Int32,

    `pc_reliable` Int32,

    `delete_time` Nullable(DateTime),

    `pc_business_relationship` Int32,

    `pub_keyword_id` Int64,

    `pc_quality` Int32,

    `phrase_type` Int32,

    `keyword_length` Int32,

    `wap_destination_url` String,

    `wap_reason` Int32,

    `deeplink_url` String,

    `price` Float64,

    `pause` Int32,

    `wap_business_relationship` Int32,

    `pc_estimated_click_rate` Int32,

    `wap_reliable` Int32,

    `pc_landpage_experience` Int32,

    `wmatch_prefer` Int32,

    `pc_destination_url` String,

    `pub_account_name` String,

    `wap_landpage_experience` Int32,

    `pub_keyword` String,

    `wap_estimated_click_rate` Int32,

    `pub_account_id` Int64,

    `chan_pub_id` Int64,

    `match_type` Int32,

    `wap_quality` Int32,

    `status` Int32,

    `pub_campaign_id` Int64,

    `pc_left3_price_guide` Float64,

    `wap_price_guide` Float64,

    `tabs` String,

    `pub_adgroup_id` Int64,

    `pub_adgroup_name` String,

    `pub_campaign_name` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/pub_summary_db_sem_baidu/new_keyword_738e2afa34f611ed8098fa163e676c73_20220915231022',
 '{replica}')
PRIMARY KEY (chan_pub_id,
 pub_campaign_id,
 pub_adgroup_id,
 pub_keyword_id)
ORDER BY (chan_pub_id,
 pub_campaign_id,
 pub_adgroup_id,
 pub_keyword_id)
SETTINGS index_granularity = 8192;
```

**settings**: 
```
{'max_threads':'24','max_query_size':'33554432','use_uncompressed_cache':'1','load_balancing':'random','distributed_aggregation_memory_efficient':'1','distributed_product_mode':'local','max_concurrent_queries_for_user':'500','join_use_nulls':'1','max_bytes_before_external_group_by':'82463372083','max_bytes_before_external_sort':'82463372083','max_execution_time':'3600','max_ast_depth':'1000','max_ast_elements':'5000000','max_expanded_ast_elements':'5000000','max_memory_usage':'164926744166','mutations_sync':'2','allow_experimental_lightweight_delete':'1'}
```

**error**:
```
select * from system.replication_queue\G

database:               pub_summary_db_sem_baidu
table:                  pub_setting_sem_keyword
replica_name:           cluster01-01-1
position:               0
node_name:              queue-0000000118
type:                   MERGE_PARTS
create_time:            2022-09-16 08:14:09
required_quorum:        0
source_replica:         cluster01-01-2
new_part_name:          all_923_1825_4_1833
parts_to_merge:         ['all_923_1100_3_1833','all_1101_1284_3_1833','all_1285_1486_3_1833','all_1487_1657_3_1833','all_1658_1691_2_1833','all_1692_1725_2_1833','all_1726_1755_2_1833','all_1756_1791_2_1833','all_1792_1825_2_1833']
is_detach:              0
is_currently_executing: 1
num_tries:              99
last_exception:         Code: 49. DB::Exception: Number of rows in source parts (359204021) differs from number of bytes written to rows_sources file (357428579). It is a bug. (LOGICAL_ERROR) (version 22.8.4.7 (official build))
last_attempt_time:      2022-09-16 13:11:14
num_postponed:          0
postpone_reason:
last_postpone_time:     1970-01-01 08:00:00
merge_type:             Regular
```

We deleted zookeeper node 
`delete /clickhouse/tables/01/pub_summary_db_sem_baidu/new_keyword_738e2afa34f611ed8098fa163e676c73_20220915231022/replicas/cluster01-01-1/queue/queue-0000000118`, it dosen't work.

Please help us, thanks.

**Comment by filimonov** [comment] 2022-09-16 07:53
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/40486 

Fixed in https://github.com/ClickHouse/ClickHouse/pull/40559 

Workaround is disabling vertical merges

**Comment by filimonov** [comment] 2022-09-16 07:54
Duplicate of #40486

**Closed by filimonov** 2022-09-16 07:54 UTC
Labels: potential bug
