### ISSUE TITLE
S3 zero copy bug

### ISSUE THREAD

**Issue by coulsonm** [ClickHouse/ClickHouse#47548] opened 2023-03-14 03:25 UTC
**Describe what's wrong**

Newly added replica downloads all data to default disk regardless of its location on other replicas.

**Does it reproduce on recent release?**

Experienced in our production on version 23.1

**How to reproduce**
https://github.com/ClickHouse/ClickHouse/issues/46465 
I can reproduce this bug.
https://github.com/ClickHouse/ClickHouse/pull/47010 fixed this bug,but haven't merged on version 23.2.
Which version can be used? ^_^

**Comment by coulsonm** [comment] 2023-03-14 06:11
When will the s3 zero copy function be ready for production? ^_^

**Comment by tavplubix** [comment] 2023-03-14 12:57
> Which version can be used?

The issue is fixed in 23.3 (current master branch). But we do not recommend using experimental features (including "s3 zero copy") in production at all.

> When will the s3 zero copy function be ready for production? ^_^

Nobody knows :(

**Closed by tavplubix** 2023-03-14 12:57 UTC
Labels: question
