### ISSUE TITLE
Calculating per second peak values after summing up individual values in a distributed and replicated table

### ISSUE THREAD

**Issue by keerthana-kannan-ch** [ClickHouse/ClickHouse#14266] opened 2020-08-31 10:25 UTC
I am currently using Clickhouse cluster (2 shards, 2 replicas) to read transaction logs from my server. The log contains fields like timestamp, bytes delivered, ttms, etc. The structure of my table is as below:

```
CREATE TABLE db.log_data_local ON CLUSTER '{cluster}' (
  timestamp DateTime,
  bytes UInt64,
  /*lots of other fields */
  ) ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/db/tables/logs/{shard}','{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY timestamp
TTL timestamp + INTERVAL 1 MONTH;

CREATE TABLE db.log_data ON CLUSTER '{cluster}'
AS cdn_data.http_access_data_local
ENGINE = Distributed('{cluster}','db','log_data_local',rand());
```

I am ingesting data from Kafka and using materialized view to populate this table. Now I need to calculate the peak throughput per second from this table. So basically I need to sum up the bytes field per second and then find the max value for a 5 minute period.

I tried using ReplicatedAggregatingMergeTree with aggregate functions for the throughput, but the peak value I get is much less compared to the value I get when I directly query the raw table.

The problem is, while creating the material view to populate the peak values, querying the distributed table directly is not giving any results but if I query the local table then only partial data set is considered. I tried using an intermediary table to compute the per-second total and then to create the materialized but I faced the same issue.

This is the schema for my peaks table and the materialized view I am trying to create:

```
CREATE TABLE db.peak_metrics_5m_local ON CLUSTER '{cluster}'
(
  timestamp DateTime,
  peak_throughput AggregateFunction(max,UInt64),
)
ENGINE=ReplicatedAggregatingMergeTree('/clickhouse/{cluster}/db/tables/peak_metrics_5m_local/{shard}','{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp)
TTL timestamp + toIntervalDay(90);


CREATE TABLE db.peak_metrics_5m ON CLUSTER '{cluster}'
AS cdn_data.peak_metrics_5m_local
ENGINE = Distributed('{cluster}','db','peak_metrics_5m_local',rand());

CREATE MATERIALIZED VIEW db.peak_metrics_5m_mv ON CLUSTER '{cluster}'
TO db.peak_metrics_5m_local
AS SELECT
        toStartOfFiveMinute(timestamp) as timestamp,
        maxState(bytes)*8 as peak_throughput,
    FROM (
        SELECT 
            timestamp,
            sum(bytes) as bytes,
        FROM db.log_data_local
        GROUP BY timestamp
    )
    GROUP BY timestamp;
```
Please help me out with a solution to this.

**Comment by den-crane** [comment] 2020-08-31 13:46
It's impossible to implement with MV. MV is an insert trigger. 

` sum(bytes) as bytes, ... GROUP BY timestamp` works against inserted buffer and does not read data from `log_data_local` table.

Probably you could partially emulate this behavior with TTL/rollup https://github.com/ClickHouse/ClickHouse/pull/10537

**Comment by keerthana-kannan-ch** [comment] 2020-09-01 05:26
@den-crane I think I can try this out. May I know which version will it be available in? I am currently using 20.3.12.112

**Comment by keerthana-kannan-ch** [comment] 2020-09-01 08:30
@den-crane Thanks for the reply. 
The problem I am facing now is that though I am summing up the per second values, the peak should be for a longer time range, like an hour. This is the DDL I am trying to use:

```
CREATE TABLE cdn_data.derived_metrics_local ON CLUSTER '{cluster}'
(
  timestamp DateTime,
  org_name LowCardinality(String) DEFAULT '-',
  title LowCardinality(String) DEFAULT '-',
  s_dns LowCardinality(String) DEFAULT '-',
  pop LowCardinality(String) DEFAULT '-',
  region LowCardinality(String) DEFAULT '-',
  country LowCardinality(String) DEFAULT '-',
  isp LowCardinality(String) DEFAULT '-',
  bytes UInt64,
  requests UInt64,
  unique_clients UInt64
)
ENGINE=ReplicatedSummingMergeTree('/clickhouse/{cluster}/cdn_data/tables/derived_metrics_local/{shard}','{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp,org_name,title,pop,s_dns,region,country,isp)
TTL toStartOfHour(timestamp) + INTERVAL 1 HOUR GROUP BY toStartOfHour(timestamp),org_name,title,pop,s_dns,region,country,isp 
SET bytes=max(bytes), requests=max(requests), unique_clients=max(unique_clients);
```

When I try to create the table, I am getting the following error:
```
Received exception from server (version 20.5.4):
Code: 450. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on [server1:9000]: Code: 450, e.displayText() = DB::Exception: TTL Expression GROUP BY key should be a prefix of primary key (version 20.5.4.40)
```

Any thoughts on how to fix this?

**Comment by den-crane** [comment] 2020-09-01 14:35
try `ORDER BY (toStartOfHour(timestamp), timestamp)`

**Comment by den-crane** [comment] 2020-09-01 14:45
```
CREATE TABLE derived_metrics_local 
(
  timestamp DateTime,
  timestamp_h DateTime materialized toStartOfHour(timestamp),
  bytes UInt64
)
ENGINE=SummingMergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp_h, timestamp)
TTL toStartOfHour(timestamp) + INTERVAL 1 HOUR GROUP BY timestamp_h
SET bytes=max(bytes);


insert into derived_metrics_local values('2020-01-01 00:00:00', 1);
insert into derived_metrics_local values('2020-01-01 00:00:00', 1);
insert into derived_metrics_local values('2020-01-01 00:00:00', 1);
insert into derived_metrics_local values('2020-01-01 00:59:02', 10);
insert into derived_metrics_local values('2020-01-01 00:59:02', 1);

optimize table derived_metrics_local final;

select timestamp, timestamp_h, bytes  from derived_metrics_local
┌───────────timestamp─┬─────────timestamp_h─┬─bytes─┐
│ 2020-01-01 00:59:02 │ 2020-01-01 00:00:00 │    11 │
└─────────────────────┴─────────────────────┴───────┘
```

**Comment by keerthana-kannan-ch** [comment] 2020-09-02 04:39
This works fine when timestamp is the only dimension. However, if I add another field in the table and as part of the primary key, I get the same error as above. For example,

```
CREATE TABLE db.derived_metrics_test 
(
  timestamp DateTime,
  timestamp_h DateTime materialized toStartOfHour(timestamp),
  host LowCardinality(String),
  bytes UInt64
)
ENGINE=ReplicatedSummingMergeTree('/clickhouse/{cluster}/db/tables/derived_metrics_test/{shard}','{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp_h, timestamp,host)
TTL toStartOfHour(timestamp) + INTERVAL 1 HOUR GROUP BY timestamp_h, host
SET bytes=max(bytes);
```

```
Received exception from server (version 20.5.4):
Code: 450. DB::Exception: Received from localhost:9000. DB::Exception: TTL Expression GROUP BY key should be a prefix of primary key.

0 rows in set. Elapsed: 0.002 sec.
```

**Comment by keerthana-kannan-ch** [comment] 2020-09-02 09:45
I was able to get it to work after changing the order of the keys. One more issue I am facing is that the roll-up is happening on the individual shards and not on the whole table. As a result, I am getting two results for every hour. Is there a way I can ensure that the roll-up happens collectively?

**Comment by keerthana-kannan-ch** [comment] 2020-09-02 11:55
I was able to fix it by changing the order of my primary keys. The roll-ups are actually happening internally in each shard and not collectively. I fixed this by editing the sharding key of the distributed table so that all the inserts for one hour happens in the same shard and writing into the distributed table from the materialized view. The values I am getting are still different from what I expect. I am using a simulator to insert 1000 rows per second, so my peak request rate should be 1000. However, after the roll-up the value for the max(requests) comes around 6000.

Any idea what could be going wrong?

**Comment by den-crane** [comment] 2020-09-02 12:38
>The roll-ups are actually happening internally in each shard and not collectively. 

I don't understand what you mean.

>However, after the roll-up the value for the max(requests) comes around 6000.

Need reproducible example.

**Comment by keerthana-kannan-ch** [comment] 2020-09-10 13:03
I am unable to create a reproducible example. The roll-up works perfectly when I try to insert data into the table directly or through another ReplicatedMergeTree table using materialized view. However, my actual scenario is this:

I have 4 clickhouse servers running as a cluster (2 shards with 2 replicas)

 I am ingesting data from kafka using a kafka consumer table. 
```
CREATE TABLE db.kafka_consumer ON CLUSTER '{cluster}'
(
	timestamp String,
	metadata  String,
	filename  String,
	message   String
)
ENGINE=Kafka()
SETTINGS
   kafka_broker_list = 'kafka:9092',
   kafka_topic_list = 'topics',
   kafka_format = 'JSONEachRow',
   kafka_group_name = 'default',
   kafka_max_block_size = 1048576;
```
From there, I have a materialized view to populate a ReplicatedMergeTree table. 
```
CREATE TABLE db.http_access_data_local ON CLUSTER '{cluster}' (
  timestamp DateTime,
  c_ip LowCardinality(String),
  sc_bytes UInt64,
..................60 other fields..............
) ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/db/tables/raw_data_local/{shard}','{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp)
TTL toStartOfDay(timestamp) + INTERVAL 1 MONTH;

CREATE TABLE db.raw_data ON CLUSTER '{cluster}'
AS db.raw_data_local
ENGINE = Distributed('{cluster}','db','raw_data_local',(toUnixTimestamp(timestamp)%4));

CREATE MATERIALIZED VIEW cdn_data.http_access_data_mv ON CLUSTER '{cluster}'
TO db.raw_data AS
SELECT
.........................
FROM db.kafka_consumer
```
I have another materialized view to populate the table containing the roll-up. 
```
CREATE TABLE db.derived_metrics_local ON CLUSTER '{cluster}'
(
  timestamp DateTime,
  timestamp_hour DateTime MATERIALIZED toStartOfHour(timestamp),
  k1 LowCardinality(String) DEFAULT '-',
  k2 LowCardinality(String) DEFAULT '-',
  k3 LowCardinality(String) DEFAULT '-',
  k4 LowCardinality(String) DEFAULT '-',
  k5 LowCardinality(String) DEFAULT '-',
  k6 LowCardinality(String) DEFAULT '-',
  k7 LowCardinality(String) DEFAULT '-',
  bytes UInt64,
  requests UInt64,
  unique_clients UInt64
)
ENGINE=ReplicatedSummingMergeTree('/clickhouse/{cluster}/db/tables/derived_metrics_local/{shard}','{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp_hour,k1,k2,k3,k4,k5,k6,k7,timestamp)
TTL timestamp_hour + INTERVAL 1 HOUR GROUP BY timestamp_hour,k1,k2,k3,k4,k5,k6,k7 
SET bytes=max(bytes), requests=max(requests), unique_clients=max(unique_clients);

CREATE TABLE db.derived_metrics ON CLUSTER '{cluster}'
AS db.derived_metrics_local
ENGINE = Distributed('{cluster}','db','derived_metrics_local',toUnixTimestamp(toStartOfHour(timestamp))%4);

CREATE MATERIALIZED VIEW db.derived_metrics_time_mv ON CLUSTER '{cluster}'
TO db.derived_metrics
AS SELECT 
timestamp,
sum(sc_bytes) as bytes,
count() as requests,
uniq(c_ip) as unique_clients
FROM db.raw_data
GROUP BY timestamp;
```
Currently, I am using a data simulator to ingest 1000 records per second into kafka which is correctly ingested into the first raw_data table. The summing aggregation happens correctly throughout the hour but after the roll-up I am ending up with incorrect values. As I am ingesting 1000 records constantly every second, my max(requests) value should be 1000. However, after the roll-up, I am ending up with values around 6 or 7K. 

Please point me to where I'm going wrong.

**Comment by keerthana-kannan-ch** [comment] 2020-09-21 11:06
In addition to my previous observation, if I change the rollup from max() to avg(), this is the result I get:

```
clickhouse-server1 :) select timestamp, max(requests) from derived_metrics group by timestamp order by timestamp;

SELECT
    timestamp,
    max(requests)
FROM derived_metrics
GROUP BY timestamp
ORDER BY timestamp ASC

┌───────────timestamp─┬───────max(requests)─┐
│ 2020-09-21 10:59:59 │ 4877649991644229405 │
│ 2020-09-21 11:00:00 │                1000 │
│ 2020-09-21 11:00:01 │                1000 │
│ 2020-09-21 11:00:02 │                1000 │
│ 2020-09-21 11:00:03 │                1000 │
│ 2020-09-21 11:00:04 │                1000 │
│ 2020-09-21 11:00:05 │                1000 │

```

**Comment by Krithiga93** [comment] 2024-05-23 13:29
Hi ,
Any update on the above problem.Please provide a suggestion to handle this

**Comment by den-crane** [comment] 2024-05-23 13:36
@Krithiga93 where is no problem here. Everything here works as expected. Open your own issue and explain your problem.

**Comment by Krithiga93** [comment] 2024-05-23 13:42
@den-crane Avg(requests) solves the problem. But in my case , I want to find the max which should result the correct value.
For Example , I have a column for bytes and duration , I am calculating a field with max(bytes)/avg(duration) for a second. 
I dont think the above method works for this.

**Comment by den-crane** [comment] 2024-05-23 13:46
@Krithiga93 I am begging you, please, please don't spoil other issues. Open a question in https://github.com/ClickHouse/ClickHouse/discussions

**Comment by tbragin** [comment] 2024-05-25 15:04
Closing this issue, since the question from four years ago appears answered. I agree, for new questions it would be better to file a new issue or discussion. It is helpful to specify version in use, schema, problematic query, and any errors in logs.

**Closed by tbragin** 2024-05-25 15:04 UTC
Labels: question
