### ISSUE TITLE
CREATE TABLE with SETTINGS clause accepts invalid settings without ENGINE specification

### ISSUE THREAD

**Issue by fm4v** [ClickHouse/ClickHouse#68026] opened 2024-08-08 08:29 UTC
Table with user setting is created, but it shouldn't be
```
CREATE TABLE user_setting (id Int32) ORDER BY id SETTINGS final = 1;
show create user_setting;
/*
CREATE TABLE default.user_setting\n(\n    `id` Int32\n)\nENGINE = MergeTree\nORDER BY id\nSETTINGS index_granularity = 8192
*/
```

Unable to create table with table setting
```
CREATE TABLE table_setting (id Int32) ORDER BY id SETTINGS index_granularity = 1;
show create table_setting;
/*
Received exception from server (version 24.8.1):
Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Setting index_granularity is neither a builtin setting nor started with the prefix 'SQL_' registered for user-defined settings. (UNKNOWN_SETTING)
(query: CREATE TABLE table_setting (id Int32) ORDER BY id SETTINGS index_granularity = 1;)
*/
```
----

**Correct behavior**
Table is created with table setting
```
CREATE TABLE table_setting (id Int32) ENGINE=MergeTree ORDER BY id SETTINGS index_granularity = 11;
show create table_setting;
/*
CREATE TABLE default.table_setting\n(\n    `id` Int32\n)\nENGINE = MergeTree\nORDER BY id\nSETTINGS index_granularity = 11
*/
```
Unable to create table with unknown setting
```
CREATE TABLE incorrect_setting (id Int32) ENGINE=MergeTree ORDER BY id SETTINGS finalx = 1;
/*
Received exception from server (version 24.5.1):
Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Unknown setting 'finalx': for storage MergeTree. (UNKNOWN_SETTING)
(query: CREATE TABLE incorrect_setting (id Int32) ENGINE=MergeTree ORDER BY id SETTINGS finalx = 1;)
*/
```
Unable to create table with user setting
```
CREATE TABLE user_setting (id Int32) ENGINE=MergeTree ORDER BY id SETTINGS final = 1;
/*
Received exception from server (version 24.5.1):
Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Unknown setting 'final': for storage MergeTree. (UNKNOWN_SETTING)
(query: CREATE TABLE user_setting (id Int32) ENGINE=MergeTree ORDER BY id SETTINGS final = 1;)
*/
```

Tested since `24.5.1`, maybe earlier

**Comment by antaljanosbenjamin** [comment] 2024-08-08 11:14
I think this is not a bug. If you don't specify the engine, then you cannot specify settings for the engine, thus the settings are interpreted as query settings. Basically
`CREATE TABLE user_setting (id Int32) ORDER BY id SETTINGS final = 1;` [is the same as](https://fiddle.clickhouse.com/0de44b95-2e79-4f97-88b7-014dc23e12aa) `CREATE TABLE user_setting_2 (id Int32) ENGINE=MergeTree ORDER BY id SETTINGS index_granularity = 8192 SETTINGS final = 1;`

**Comment by fm4v** [comment] 2024-08-08 11:23
> [is the same as](https://fiddle.clickhouse.com/0de44b95-2e79-4f97-88b7-014dc23e12aa) CREATE TABLE user_setting_2 (id Int32) ENGINE=MergeTree ORDER BY id SETTINGS index_granularity = 8192 SETTINGS final = 1;

And it doesn't make any sense so why it implicitly works like this.

When a user omits the table engine, he expect the default engine to be used and the syntax for settings to remain the same.

The inability to set table settings with an omitted engine makes this feature incomplete
```
CREATE TABLE table_setting (id Int32) ORDER BY id SETTINGS index_granularity = 1;
show create table_setting;
/*
Received exception from server (version 24.8.1):
Code: 115. DB::Exception: Received from localhost:9000. DB::Exception: Setting index_granularity is neither a builtin setting nor started with the prefix 'SQL_' registered for user-defined settings. (UNKNOWN_SETTING)
(query: CREATE TABLE table_setting (id Int32) ORDER BY id SETTINGS index_granularity = 1;)
*/
```

**Comment by tavplubix** [comment] 2024-08-08 13:17
See also https://github.com/ClickHouse/ClickHouse/pull/11804 and linked issues/PRs

**Comment by alexey-milovidov** [comment] 2024-08-12 18:07
Duplicate of #63154.

**Closed by alexey-milovidov** 2024-08-12 18:07 UTC
Labels: duplicate, usability
