### ISSUE TITLE
MongoDB engine question - how to query to schemaless

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#36119] opened 2022-04-11 07:16 UTC
Hi, I am testing mongodb engine to get data from mongodb.

As you know, Mongodb is schemaless.
so, some documents don't have all fields. 
but, I want to get data from the document with blank or null.

below is an example.

mongo
```
db.chu.find()
{ "_id" : ObjectId("6253d4e4fe1ad41d94d9f04c"), "id" : 1, "c1" : "abc" }
{ "_id" : ObjectId("6253d4ecfe1ad41d94d9f04d"), "id" : 2, "c2" : "hello" }
{ "_id" : ObjectId("6253d502fe1ad41d94d9f04e"), "id" : 2, "c1" : "efg", "c2" : "hi" }
```

CH
```sql
CREATE TABLE mongo_table
(
    `id` UInt64,
    `c1` String,
    `c2` String
)
ENGINE = MongoDB('127.0.0.1:30002', 'test', 'chu', 'yhchu', '123456')

select * from mongo_table;

SELECT *
FROM mongo_table

↑ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) 
Received exception from server (version 20.6.4):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Column `c2` is absent in MongoDB collection: While executing SourceFromInputStream. 
```
how can I query that table?
Could you give me any clues?

**Comment by kssenii** [comment] 2022-04-11 07:46
duplicate of https://github.com/ClickHouse/ClickHouse/issues/26490, not fixed yet.
Though for dictionary source it would work.

**Closed** 2022-04-20 15:54 UTC
Labels: question
