### ISSUE TITLE
Aggregation function that respects the order of data

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#62777] opened 2024-04-19 03:13 UTC
> (you don't have to strictly follow this form)

**Use case**

There is a task that consume and aggregate a bunch of rows in order, i.e. given rows **R** = {r1,r2,...,r_n} and a stateful function(similar to aggretion) a(x), I need to invoke a(r1), a(r2), ..., a(r_n) and then populate a final aggregation result.  The result is impacted by the order of invocations. For getting a stable result, I have to make sure the invocations of a(r1), a(r2), ..., a(r_n) are strictly in order.

**Describe the solution you'd like**

I may need a setting to force AggregationTransform working on an strictly ordered data. Actually I had achieved this by the SQL pattern like:
```
select functionA(x) from (select `x` from `R_table` order by `x`) settings max_threads=1;
```
However, the solution does no longer work in the latest ClickHouse.

**Comment by canhld94** [comment] 2024-04-19 04:43
This can be done in several ways.

1. groupArray -> arraySort -> arrayReduce

```sql
SELECT arrayReduce('functionA', arraySort(groupArray(x))) FROM R_table; 
```

2.  materialized CTE https://github.com/ClickHouse/ClickHouse/pull/61086

```sql
WITH t AS MATERIALIZED (SELECT x FROM R_table ORDER BY x) SELECT functionA(x) FROM t;
```

**Comment by den-crane** [comment] 2024-04-19 12:36
@Alex-Cheng  which aggregate function? https://fiddle.clickhouse.com/88a7eba5-01f5-41d9-9577-4865ca007def

Modern optimizer removes excessive order by if result of a query does not depend on it.
You may use `limit` to overcome optimizer.

>select functionA(x) from (select `x` from `R_table` order by `x` limit toUInt64(-1)) settings max_threads=1;

**Comment by Algunenano** [comment] 2024-04-19 12:42
CH is not designed to do this, and you will face multiple problems and changes in the future because of this:
* CH is multithreaded by design, without any order guarantees. You can use `max_threads=1`
* CH does not guarantee in which order it will read the data.
* CH does not guarantee the size of the batches. It's usually max_block_size, but it's also not guaranteed.
* CH also does not guarantee in which order the aggregation states will be merged.

You can try the suggested workarounds, but they might stop working at any time.

The only similar thing to what you are describing are window functions.

**Closed by Algunenano** 2024-04-19 12:42 UTC
Labels: question, question-answered

**Comment by den-crane** [comment] 2024-04-25 13:16
@Alex-Cheng check the code of `groupArray`.
I think there is (or was) some trait which allows to mark a function as dependent of data order. 
Earlier groupArray 100% respected the order of input blocks. And even now it's mentioned in the doc: https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/grouparray

**Comment by UnamedRus** [comment] 2024-05-07 05:47
> Earlier groupArray 100% respected the order of input blocks. 

With important exception of GROUP BY in external memory AFAIK

**Comment by Alex-Cheng** [comment] 2024-05-21 12:42
> @Alex-Cheng check the code of `groupArray`. I think there is (or was) some trait which allows to mark a function as dependent of data order. Earlier groupArray 100% respected the order of input blocks. And even now it's mentioned in the doc: https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/grouparray I think this trait forbids the optimizer to change a plan (remove orderbys) or something like this.

The document says, "Creates an array of argument values. Values can be added to the array in **_any (indeterminate) order_**." And it also explains some cases where can still rely on the order of execution, but it requires "the subquery result is small enough."
> In some cases, you can still rely on the order of execution. This applies to cases when SELECT comes from a subquery that uses ORDER BY if the subquery result is small enough.
