### ISSUE TITLE
Users created by RBAC /access_management,  use "show databases" to return no data  

### ISSUE THREAD

**Issue by FanWuu** [ClickHouse/ClickHouse#26306] opened 2021-07-14 10:24 UTC
### this is user.xml
    <yandex>
    <users>
        <default>
            <password>TEST123</password>
            <networks>
                <ip>::/0</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
            <databases>
                <system>
                    <tables>
                        <filter>database != 'system'</filter>
                    </tables>
                    <databases>
                        <filter>name != 'system'</filter>
                    </databases>
                </system>
            </databases>
        </default>
    </users>
    </yandex>

### create user  by  RBAC /access_management
echo "CREATE USER admin IDENTIFIED WITH PLAINTEXT_PASSWORD BY '123' " | clickhouse-client -u default
echo "GRANT ALL ON . TO admin WITH GRANT OPTION " | clickhouse-client -u default

### show database , show tables 
echo "show databases " | clickhouse-client -u admin
echo "show tables " | clickhouse-client -u admin

#### sql returns empty results

![8a11c627fb3f50441fc75e79a6fb3b6](https://user-images.githubusercontent.com/41465662/125605336-ae48a4ee-3c40-4321-bfb2-39ae53299bd2.png)

### remove /user/databases in  user.xml
      <databases>
              <system>
                      <tables>
                          <filter>database != 'system'</filter>
                      </tables>
                      <databases>
                          <filter>name != 'system'</filter>
                      </databases>
                  </system>
         </databases>

Users "admin"  created by RBAC /access_management    
when  database filter  in user.xml   , echo ''show databases ‘' |clickhouse-client   -u admin   returns empty results
when remove  database filter  in user.xml  ,  echo ''show databases ‘' |clickhouse-client   -u admin    Can return the result normally .
Is This a bug,？ or other configurations need to be modified

**Comment by alexey-milovidov** [comment] 2021-07-14 10:37
`SHOW DATABASES` query require access to the `system.databases` table. But you have filtered it with row-level filters.

**Comment by aoowuu** [comment] 2021-07-14 10:49
> `SHOW DATABASES` query requires access to the `system.databases` table. But you have filtered it with row-level filters.

So how can I make the "admin" account have the same permissions as the "default" account, but also block the system database, because the "default" account blocks the system database and can  show  other databases  normally

**Comment by aoowuu** [comment] 2021-07-14 10:51
@alexey-milovidov

**Comment by aoowuu** [comment] 2021-07-15 07:11
@vitlibar

**Comment by e-mars** [comment] 2022-02-24 16:16
closing.
duplicate of this one: https://github.com/ClickHouse/ClickHouse/issues/26238

**Closed by e-mars** 2022-02-24 16:16 UTC
Labels: invalid, question
