### ISSUE TITLE
After upgrading ClickHouse from 20.4 to 21.3 PARTITION key stops working because it's wrongly counted as float

### ISSUE THREAD

**Issue by artem-pershin** [ClickHouse/ClickHouse#23700] opened 2021-04-27 16:15 UTC
I have the following table in ClickHouse 20.4:
```
CREATE TABLE FileRecord
(
       fileId UInt64,
       sourceRecord String
) ENGINE = MergeTree()
Partition by (ceil(fileId / 1000) % 1000)
settings index_granularity = 4096
```
and it worked just fine, until i'be upgraded to 21.3, where we have following PR-feature:
https://github.com/ClickHouse/ClickHouse/pull/18464
which disallows to use floating point keys as partition key. No problem, but if i run
`toTypeName((ceil(fileId / 1000) % 1000))` 
it returns `Int16`, which seems like a bug in typeName or in the newly introduced feature with `allow_floating_point_partition_key`. I do not show my stacktrace, since it's obvious and simply shows error

`Donot support float point as partition key: (ceil(fileId / 1000) % 1000)`

**Comment by alexey-milovidov** [comment] 2021-06-15 00:34
The issue is fixed in #24157.
The fix is backported to versions 21.5 and 21.6.

**Closed by alexey-milovidov** 2021-06-15 00:34 UTC
Labels: backward compatibility, bug, v21.3-affected
