### ISSUE TITLE
test_checking_s3_blobs_paranoid/test.py::test_query_is_canceled_with_inf_retries is flaky

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#55931] opened 2023-10-23 09:18 UTC
It seems it started failing since a few days ago.

https://play.clickhouse.com/play?user=play#U0VMRUNUCiAgY2hlY2tfbmFtZSwKICB0ZXN0X25hbWUsCiAgdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIGFzIHQsCiAgY291bnQoKSBhcyBydW5zLAogIGNvbmNhdChyb3VuZCgxMDAgKiAoY291bnRJZih0ZXN0X3N0YXR1cyAhPSAnT0snIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcpIEFTIGYpIC8gcnVucywgMSk6OlN0cmluZywgJyUnKSBhcyBmYWlsdXJlX3BlcmNlbnRhZ2UsCiAgYW55SWYocmVwb3J0X3VybCwgdGVzdF9zdGF0dXMgIT0gJ09LJyBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnKSBhcyByZXBvcnQKRlJPTSBjaGVja3MKV0hFUkUKICAgIHRlc3RfbmFtZSBMSUtFICcldGVzdF9xdWVyeV9pc19jYW5jZWxlZF93aXRoX2luZl9yZXRyaWVzJScKICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPiB0b2RheSgpIC0gaW50ZXJ2YWwgMzAgZGF5CkdST1VQIEJZIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdApIQVZJTkcgZiA+IDAKT1JERVIgYnkgY2hlY2tfbmFtZSwgdGVzdF9uYW1lLCB0

**Comment by rschu1ze** [comment] 2024-05-29 09:47
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/64451

**Closed by rschu1ze** 2024-05-29 09:47 UTC
Labels: flaky test
