### ISSUE TITLE
AMQP-CPP issues

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#26116] opened 2021-07-09 06:22 UTC
- [ ] ***crash 1:***
```
1. AMQP::TcpConnection::onData(AMQP::Connection*, char const*, unsigned long) @ 0x12456274 in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
2. AMQP::ConnectionImpl::send(AMQP::Frame const&) @ 0x1244bbff in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
3. AMQP::ConnectionImpl::ConnectionImpl(AMQP::Connection*, AMQP::ConnectionHandler*, AMQP::Login const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1244ba4b in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
4. AMQP::TcpConnection::TcpConnection(AMQP::TcpHandler*, AMQP::Address const&) @ 0x12455b80 in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
5. DB::StorageRabbitMQ::restoreConnection(bool) @ 0xfb21872 in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
6. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<**DB::StorageRabbitMQ::StorageRabbitMQ**(DB::StorageID const&, DB::Context const&, DB::ColumnsDescription const&, std::__1::unique_ptr<DB::RabbitMQSettings, std::__1::default_delete<DB::RabbitMQSettings> >)::$_2, void ()> >(std::__1::__function::__policy_storage const*) @ 0xfb2cec1 in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xf0cbf80 in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
8. DB::BackgroundSchedulePool::threadFunction() @ 0xf0cdf77 in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::\'lambda\'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xf0ced42 in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x88372bf in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
11. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::\'lambda1\'()> >(void*) @ 0x883ade3 in /usr/lib/debug/.build-id/cf/d133a618715680c43aa5458cc9782f35c3b1e7.debug',
12. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so','13. clone @ 0x12171f in /lib/x86_64-linux-gnu/libc-2.27.so']
```

- [ ]  ***crash 2:***
```
1. std::__1::vector<char, std::__1::allocator<char> >& std::__1::deque<std::__1::vector<char, std::__1::allocator<char> >, std::__1::allocator<std::__1::vector<char, std::__1::allocator<char> > > >::emplace_back<char const*&, char const*>(char const*&, char const*&&) @ 0x12445fc9 in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
2. AMQP::TcpResolver::send(char const*, unsigned long) @ 0x124437ad in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
3. AMQP::ConnectionImpl::send(AMQP::Frame const&) @ 0x124384cf in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
4. AMQP::ConnectionImpl::ConnectionImpl(AMQP::Connection*, AMQP::ConnectionHandler*, AMQP::Login const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1243831b in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
5. AMQP::TcpConnection::TcpConnection(AMQP::TcpHandler*, AMQP::Address const&) @ 0x12442450 in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
6. DB::StorageRabbitMQ::restoreConnection(bool) @ 0xfb0fb92 in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
7. DB::StorageRabbitMQ::streamingToViewsFunc() @ 0xfb17dfd in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
8. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xf0b5870 in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
9. DB::BackgroundSchedulePool::threadFunction() @ 0xf0b7867 in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
10. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::\'lambda\'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xf0b8632 in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x882883f in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug',
12. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::\'lambda1\'()> >(void*) @ 0x882c363 in /usr/lib/debug/.build-id/77/51a440c37cde5f9e50cfeb03e7cb14f6dc1109.debug','13. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so','14. clone @ 0x12171f in /lib/x86_64-linux-gnu/libc-2.27.so']
```

- [ ] ***crash 3:***
```
1. AMQP::ConnectionImpl::ConnectionImpl(AMQP::Connection*, AMQP::ConnectionHandler*, AMQP::Login const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11e2a7a0 in /usr/lib/debug/.build-id/93/5a293066a3b70bc15412a2ac994369bdf672a9.debug',
2. AMQP::TcpConnection::TcpConnection(AMQP::TcpHandler*, AMQP::Address const&) @ 0x11e34ae0 in /usr/lib/debug/.build-id/93/5a293066a3b70bc15412a2ac994369bdf672a9.debug',
3. DB::StorageRabbitMQ::restoreConnection(bool) @ 0xf521d82 in /usr/lib/debug/.build-id/93/5a293066a3b70bc15412a2ac994369bdf672a9.debug',
4. DB::StorageRabbitMQ::streamingToViewsFunc() @ 0xf529dcd in /usr/lib/debug/.build-id/93/5a293066a3b70bc15412a2ac994369bdf672a9.debug',
5. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xeaf2050 in /usr/lib/debug/.build-id/93/5a293066a3b70bc15412a2ac994369bdf672a9.debug',
6. DB::BackgroundSchedulePool::threadFunction() @ 0xeaf4047 in /usr/lib/debug/.build-id/93/5a293066a3b70bc15412a2ac994369bdf672a9.debug',
7. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::\'lambda\'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xeaf4e12 in /usr/lib/debug/.build-id/93/5a293066a3b70bc15412a2ac994369bdf672a9.debug',
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x86579af in /usr/lib/debug/.build-id/93/5a293066a3b70bc15412a2ac994369bdf672a9.debug',
9. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::\'lambda1\'()> >(void*) @ 0x865b443 in /usr/lib/debug/.build-id/93/5a293066a3b70bc15412a2ac994369bdf672a9.debug',
10. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so','11. __clone @ 0x12171f in /lib/x86_64-linux-gnu/libc-2.27.so']
```

**Comment by filimonov** [comment] 2022-10-03 13:07
There is a chance that it was caused by
https://github.com/CopernicaMarketingSoftware/AMQP-CPP/issues/474

should be fixed in 
https://github.com/CopernicaMarketingSoftware/AMQP-CPP/commit/c273d936253ed08ff15642d6874406a564b8f9b5

So upgrade of AMQP-CPP to the latest [release](https://github.com/CopernicaMarketingSoftware/AMQP-CPP/releases/) may help

**Closed** 2022-10-05 10:06 UTC
Labels: crash, comp-message-queues, unexpected behaviour
