### ISSUE TITLE
In a table, 20,000 columns were created, and then when Insert, an exception was reported. How many columns can you support in the largest table?

### ISSUE THREAD

**Issue by v-zhaozy** [ClickHouse/ClickHouse#6943] opened 2019-09-15 08:34 UTC
![image](https://user-images.githubusercontent.com/55344414/64918867-a2741300-d7d6-11e9-89c6-85bf25e47329.png)

**Comment by filimonov** [comment] 2019-09-16 07:57
Hundreds of columns are ok.
Starting from let's say 1.5-2K columns performance degradation is expected, but rather should still work. 

I've tried you case, and the problem reproduces easily.
```
laptop5591.local :) insert into schema_20K_columns(id) values (1);

INSERT INTO schema_20K_columns (id) VALUES

Received exception from server (version 19.15.1):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 9.32 GiB (attempt to allocate chunk of 4217620 bytes), maximum: 9.31 GiB. Stack trace:

0. 0x5624f5002770 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x5624f5002545 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x5624f4bb5355 ? /usr/bin/clickhouse
3. 0x5624f50013cc MemoryTracker::alloc(long) /usr/bin/clickhouse
4. 0x5624f81a1365 DB::CompressedWriteBuffer::CompressedWriteBuffer(DB::WriteBuffer&, std::shared_ptr<DB::ICompressionCodec>, unsigned long) /usr/bin/clickhouse
5. 0x5624f8ae73b3 DB::IMergedBlockOutputStream::ColumnStream::ColumnStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, unsigned long, unsigned long) /usr/bin/clickhouse
6. 0x5624f8ae9781 ? /usr/bin/clickhouse
7. 0x5624f8ae40ed DB::IMergedBlockOutputStream::addStreams(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::IDataType const&, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, bool) /usr/bin/clickhouse
8. 0x5624f8697b0b DB::MergedBlockOutputStream::MergedBlockOutputStream(DB::MergeTreeData&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::NamesAndTypesList const&, std::shared_ptr<DB::ICompressionCodec>, bool) /usr/bin/clickhouse
9. 0x5624f865dff3 DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&) /usr/bin/clickhouse
10. 0x5624f85f2394 DB::MergeTreeBlockOutputStream::write(DB::Block const&) /usr/bin/clickhouse
11. 0x5624f88fc921 DB::PushingToViewsBlockOutputStream::write(DB::Block const&) /usr/bin/clickhouse
12. 0x5624f8906cc3 DB::SquashingBlockOutputStream::finalize() /usr/bin/clickhouse
13. 0x5624f8906ef1 DB::SquashingBlockOutputStream::writeSuffix() /usr/bin/clickhouse
14. 0x5624f50cf5d2 DB::TCPHandler::processInsertQuery(DB::Settings const&) /usr/bin/clickhouse
15. 0x5624f50d0aad DB::TCPHandler::runImpl() /usr/bin/clickhouse
16. 0x5624f50d0d3b DB::TCPHandler::run() /usr/bin/clickhouse
17. 0x5624f8f41c10 Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
18. 0x5624f8f4232d Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
19. 0x5624fa538e71 Poco::PooledThread::run() /usr/bin/clickhouse
20. 0x5624fa536c1c Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
21. 0x5624facac460 ? /usr/bin/clickhouse
22. 0x7fdc25a506db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
23. 0x7fdc2536d88f clone /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97


1 rows in set. Elapsed: 20.786 sec. 
```

`Perf top` look like that during insert attempt:
```
  57,89%  clickhouse          [.] boost::multi_index::multi_index_container<DB::ColumnDescription, boost::multi_index::indexed_by<boost::multi_index::sequenced<boost::multi_index::tag<mpl_::na, mpl_::n◆
     6,19%  clickhouse          [.] std::__introsort_loop<boost::multi_index::detail::copy_map_entry<boost::multi_index::detail::sequenced_index_node<boost::multi_index::detail::ordered_index_node<boost:▒
     3,85%  clickhouse          [.] DB::MergedBlockOutputStream::MergedBlockOutputStream                                                                                                                   ▒
     3,44%  clickhouse          [.] arena_tcache_fill_small                                                                                                                                                ▒
```

[schema_20K_columns.sql.gz](https://github.com/yandex/ClickHouse/files/3615183/schema_20K_columns.sql.gz)

**Comment by filimonov** [comment] 2019-09-16 08:38
Execution time before exception:
```
18.14 
1 rows in set. Elapsed: 0.716 sec. 

19.11
1 rows in set. Elapsed: 19.155 sec. 
```

**Comment by nicelulu** [comment] 2019-09-16 09:52
@alexey-milovidov Can be removed when inserting ```AddingDefaultBlockOutputStream```, because there may be 2000 columns, but only 100 column has a value.

**Comment by alexey-milovidov** [comment] 2019-09-16 10:08
@nicelulu That's great idea. We should not write unspecified columns at all (except that are in primary key). (They will be materialized in background merges, but if vertical merge algorithm is performed, it should not require too much memory.)

**Comment by nicelulu** [comment] 2019-09-16 10:17
> except that are in primary key

Maybe also need all the ```Dependencies``` columns.

**Comment by filimonov** [comment] 2019-09-17 08:20
>  It looks like buffers for all columns are allocated at once, and 20 000 columns lead to about 40 GB of buffers.

So for single insert we need  
1 column = 2 Mb.
100 column = 200 Mb, 
500 columns = 1Gb
1000 columns = 2 Gb 

Beside @nicelulu proposition (which is great): maybe we can decrease the size of preallocated buffers when number of columns participating in insert is big?

Or preallocate only part of buffers - anyway it doesn't have sense to pack & write 500 files simultaneously in parallel.

I can easily imagine the table with 500 columns, and 10 concurrent inserts that means they will "eat" 10 Gb.

**Comment by zhang2014** [comment] 2019-09-17 08:38
In https://github.com/yandex/ClickHouse/pull/6814, column stream has been modified to lazy create. If destroyed the column stream after a column was written, I think this might solve this problem?

**Comment by alexey-milovidov** [comment] 2019-09-17 08:52
@zhang2014 It should work (if you know that the stream was ended).

**Comment by cyfdecyf** [comment] 2019-10-14 07:31
@alexey-milovidov @filimonov We limit query memory limit to 4GB and encounter memory limit exception when inserting into tables with more than 2000 columns. Our current workaround is to create multiple tables to reduce columns per table.

It would be nice to reduce pre-allocated column buffer size when number of columns is large.

**Comment by nicelulu** [comment] 2019-12-06 03:13
> It would be nice to reduce pre-allocated column buffer size when number of columns is large.

Do you have any practices? How much is more appropriate. Will the reduction result in more frequent IO requests?

**Comment by alexey-milovidov** [comment] 2019-12-31 06:55
@CurtizJ This issue should be addressed in your PR with implementation of compact data parts.

**Comment by alexey-milovidov** [comment] 2020-02-27 22:51
Compact data parts has been merged to master but not enabled by default (until the next release and including it).

**Comment by hzruandd** [comment] 2020-07-14 06:09
> @alexey-milovidov @filimonov We limit query memory limit to 4GB and encounter memory limit exception when inserting into tables with more than 2000 columns. Our current workaround is to create multiple tables to reduce columns per table.
> 
> It would be nice to reduce pre-allocated column buffer size when number of columns is large.

Hello, you said"encounter memory limit exception when inserting into tables with more than 2000 columns", can I think it is hard-coded restrictions in the clickhouse? But it doesn't seem to be the case, please tell me more, thx!

We need to deal with multiple tenants, such as 1k+, each tenant has 2k+ columns and each table has 100 million to 1 billion data. Can clickhouse manage and process those tables/data well?

**Comment by alexey-milovidov** [comment] 2020-08-31 11:37
@hzruandd It's not a hardcoded restriction, it depends on the actual memory amount and needs.

**Comment by alexey-milovidov** [comment] 2020-11-03 18:43
> Compact data parts has been merged to master but not enabled by default (until the next release and including it).

Compact data parts has been enabled by default since version 20.10.

**Closed by alexey-milovidov** 2020-11-03 18:43 UTC
Labels: performance
