### ISSUE TITLE
Main PID:   (code=killed, signal=SEGV)

### ISSUE THREAD

**Issue by thiningsun** [ClickHouse/ClickHouse#17128] opened 2020-11-17 11:00 UTC
When I executed this sql, clickHouse server crashed directly, and I encountered a serious production accident

SQL ：
select count(1) from  system.query_log          -------->    Ten million  count
select '1111' as count from system.query_log order by count limit 10000;

![image](https://user-images.githubusercontent.com/45502167/99382208-22c86380-2907-11eb-866d-93d179ea0cdb.png)

![image](https://user-images.githubusercontent.com/45502167/99381952-bf3e3600-2906-11eb-8f2b-dcd8c4e98677.png)

![image](https://user-images.githubusercontent.com/45502167/99382757-f2cd9000-2907-11eb-9593-d659e5c68248.png)

Can anyone help me，thanks

When I sort the constants, it will not be a problem if the amount of data is small. Once the amount of data is large, the clickHouse service will be directly killed by the system OS.

**Comment by filimonov** [comment] 2020-11-17 12:03
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/17088

It's a bug. We will fix it in next releases. Please avoid sorting the constants till the fix will pop up. 

As another alternative workaround you can wrap your constant in the `materialize()`

I.e. 
```
select materialize('1111') as name from numbers_mt(1000000) order by name limit 10000;
```

**Closed** 2020-11-17 12:04 UTC
Labels: bug

**Comment by thiningsun** [comment] 2020-11-17 12:13
> materialize

ok，I test the method  is PASS ！thanks for your help ，GOOD
