### ISSUE TITLE
Caught exception while loading metadata，Unable to launch clickhouse

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#45048] opened 2023-01-09 03:49 UTC
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* version: 22.8.11

2023.01.09 11:29:28.773278 [ 20812 ] {} <Error> Application: Caught exception while loading metadata: Code: 49. DB::Exception: Least common type for object can be deduced only from tuples, but Object('json') given: Cannot attach table `tq_log`.`ods_client_report_log_success_local` from metadata file /data1/clickhouse/data/store/1b3/1b3689c2-2b68-4f73-ad37-079a612e0d33/ods_client_report_log_success_local.sql from query ATTACH TABLE tq_log.ods_client_report_log_success_local UUID 'e189112f-df85-466c-bda6-ecc4290b2092' (`token` String COMMENT '用户唯一标识' CODEC(ZSTD(1)), `version` LowCardinality(String) COMMENT 'app 版本号', `appcode` LowCardinality(String) COMMENT '应用标识', `cloned` LowCardinality(String) COMMENT '应用分身ID', `network` LowCardinality(String) COMMENT '网络情况', `ip` String COMMENT 'ip地址' CODEC(ZSTD(1)), `platform` LowCardinality(String) COMMENT '手机平台 ', `channel` LowCardinality(String) COMMENT '渠道', `city` LowCardinality(String) COMMENT '用户当前定位城市ID', `model` LowCardinality(String) COMMENT '手机型号', `track_id` UInt64 COMMENT '事件行为唯一标识', `event_time` DateTime64(3, 'Asia/Shanghai') COMMENT ' 事件时间', `event_id` LowCardinality(String) COMMENT '事件ID', `content` Object('json') COMMENT '事件属性', `ot` LowCardinality(String) COMMENT '网络服务商', `platform_ver` LowCardinality(String) COMMENT '手机系统版本', `session_id` UInt64 COMMENT '会话' CODEC(T64), `is_front` LowCardinality(String) COMMENT ' 是、否', `seq` LowCardinality(UInt32) COMMENT '顺序', `_timestamp` DateTime64(3, 'Asia/Shanghai') COMMENT '上报时间' CODEC(LZ4HC(5)), `content_str` String ALIAS toJSONString(content), `content_type` String ALIAS toTypeName(content), INDEX token_index token TYPE bloom_filter(0.001) GRANULARITY 1) ENGINE = ReplicatedMergeTree('/clickhouse/tables/replicated/reportlog/{shard}', '{replica}') PARTITION BY toStartOfHour(event_time) ORDER BY (platform, event_id, event_time) TTL toDateTime(event_time) + toIntervalDay(45) SETTINGS index_granularity = 8192. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @0xa3f9b5a in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xa43e858 in /usr/bin/clickhouse
2. DB::getLeastCommonTypeForObject(std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, bool) @ 0x141f87f5 in /usr/bin/clickhouse
3. DB::MergeTreeData::getObjectColumns(boost::iterator_range<boost::multi_index::detail::bidir_node_iterator<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > > > > >, DB::ColumnsDescription const&) @ 0x158d4c7c in /usr/bin/clickhouse
4. DB::MergeTreeData::resetObjectColumnsFromActiveParts(std::__1::unique_lock<std::__1::mutex> const&) @ 0x158739ac in /usr/bin/clickhouse
5. DB::MergeTreeData::loadDataParts(bool) @ 0x15871ca0 in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageIDconst&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, DB::StorageReplicatedMergeTree::RenamingRestrictions) @ 0x154e3229 in /usr/bin/clickhouse
7. ? @ 0x15b00242 in /usr/bin/clickhouse
8. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15436b23 in /usr/bin/clickhouse
9. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0x1426f135 in /usr/bin/clickhouse
10. DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel) @ 0x1431d129 in /usr/bin/clickhouse
11. ? @ 0x1454d16a in /usr/bin/clickhouse
12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa4bdd86 in /usr/bin/clickhouse
13. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xa4bf6d7 in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4bb6a8 in /usr/bin/clickhouse
15. ? @ 0xa4be8bd in /usr/bin/clickhouse
16. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
17. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by alexey-milovidov** [comment] 2023-01-09 04:38
This happens due to the usage of the Object data type, which is under development.
When you've enabled the `allow_experimental_object_type` setting, you admitted that you are using a non-production feature.

**Comment by onine007** [comment] 2023-01-09 04:44
> allow_experimental_object_type

yes, I set allow_experimental_object_type=1 in users.xml , and  also   Unable to launch clickhouse .

**Comment by CurtizJ** [comment] 2023-01-09 19:46
Data type `Object` is an experimental functionality. Please update to the most fresh version in which support of type `Object` is still experimental, but much more stable. This bug should be fixed in 22.11.

**Closed by CurtizJ** 2023-01-09 19:46 UTC
Labels: unexpected behaviour

**Comment by liubo-it** [comment] 2024-08-08 06:41
How did I solve the same problem later? @onine007

**Comment by dongjiyan** [comment] 2024-08-09 06:36
We solved the issue, suspecting that the problem was caused by Zookeeper (ZK) going down while transmitting data, which led to incomplete column data files in some parts. It might also be due to data loss in the ZK nodes. I'll outline the steps we took to resolve the issue, assuming the problematic table is `abc`. All operations were performed in the ClickHouse data storage directory.

1. **Stop all ClickHouse servers**: To prevent further data writing and corruption.

2. **Mark the problematic table as detached**: By creating a `abc.sql.detached` file in the `data/metadata` directory, the table will not automatically load upon startup, thus avoiding loading incorrect data.

3. **Create a new table `abc_new` on a single server**: On one ClickHouse server, create a new table to gradually recover the data while ensuring its integrity.

4. **Selectively copy complete parts**: Copy parts larger than 10M from the `data/data/{db}/abc/detached` directory to the `data/data/{db}/abc_new/detached` directory, ensuring the copied parts are relatively complete.

5. **Gradually attach parts to the new table**: Use the `ALTER TABLE abc_new ATTACH PART ''` command to attach the copied parts one by one to the new table, allowing it to gradually recover the data.

6. **Clean up the old table's Zookeeper data and local data**: Delete the UUID directory of the old table `abc` in Zookeeper, as well as the `data` and `metadata` files of the `abc` table on all ClickHouse nodes, ensuring the old table's data is completely removed.

7. **Create the new table at the cluster level**: After starting all nodes, use the `ON CLUSTER` command to recreate the `abc_new` table across the cluster and synchronize the data, ensuring consistency across the entire cluster.

8. **Rename the new table to the original table name**: Finally, use the `RENAME TABLE abc_new TO abc` command to rename the new table back to the original name so it can continue to be used.
