### ISSUE TITLE
Reading from s3 (Cannot read from istream at offset 0)

### ISSUE THREAD

**Issue by stasDomb** [ClickHouse/ClickHouse#25052] opened 2021-06-07 13:29 UTC
Hello, I try to read about 100 files from s3 bucket( 35-40 mln rows).
I create s3_engine table and a general table(**test_table**). When I try to insert in the last one the data I get the error.

> INSERT INTO test_table (field1,
> ......
> field10)
>  SELECT
>     field1,
> ......
> field10
> FROM s3_test_table
> 
> ↘ Progress: 30.01 million rows, 22.01 GB (95.87 thousand rows/s., 70.30 MB/s.)
> 0 rows in set. Elapsed: 315.812 sec. Processed 30.01 million rows, 22.01 GB (95.03 thousand rows/s., 69.69 MB/s.)
> 
> Received exception from server (version 21.3.3):
> Code: 23. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read from istream at offset 0: While executing S3.

So, it's about 90% of my data.
When I separated the process: at first, I created 2 s3_tables, one for first 50% of data, and second for another part. Step by step I inserted the data into table, and everything is OK.
It is some buffer issue or timeout issue.
When I increased **onnect_timeout_ms** - the same error.
Any ideas or advices?

From the **/var/log/clickhouse-server/clickhouse-server.err.log**

> 2021.06.07 12:50:36.653185 [ 303362 ] {e5813926-c05c-4479-887c-b8bf5a7a48fe} <Error> TCPHandler: Code: 23, e.displayText() = DB::Exception: Cannot read from istream at offset 0: While executing S3, Stack trace:
> 
> 0. DB::ReadBufferFromIStream::nextImpl() @ 0xd00ccd7 in /usr/bin/clickhouse
> 1. DB::ReadBufferFromS3::nextImpl() @ 0xea41667 in /usr/bin/clickhouse
> 2. DB::ZlibInflatingReadBuffer::nextImpl() @ 0xe5c53aa in /usr/bin/clickhouse
> 3. DB::InputStreamReadBufferAdapter::next(unsigned char const**, unsigned long*) @ 0xf968334 in /usr/bin/clickhouse
> 4. avro::BoundedInputStream::next(unsigned char const**, unsigned long*) @ 0x1297f13b in /usr/bin/clickhouse
> 5. avro::DataFileReaderBase::readDataBlock() @ 0x1297d02c in /usr/bin/clickhouse
> 6. avro::DataFileReaderBase::hasMore() @ 0x1297de69 in /usr/bin/clickhouse
> 7. DB::AvroRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0xf95364c in /usr/bin/clickhouse
> 8. DB::IRowInputFormat::generate() @ 0xf969ef8 in /usr/bin/clickhouse
> 9. DB::ISource::tryGenerate() @ 0xf8f8995 in /usr/bin/clickhouse
> 10. DB::ISource::work() @ 0xf8f858a in /usr/bin/clickhouse
> 11. DB::InputStreamFromInputFormat::readImpl() @ 0xd00026f in /usr/bin/clickhouse
> 12. DB::IBlockInputStream::read() @ 0xe8ab0a5 in /usr/bin/clickhouse
> 13. ? @ 0xf45c8a6 in /usr/bin/clickhouse
> 14. DB::ISource::tryGenerate() @ 0xf8f8995 in /usr/bin/clickhouse
> 15. DB::ISource::work() @ 0xf8f858a in /usr/bin/clickhouse
> 16. DB::SourceWithProgress::work() @ 0xfaab02a in /usr/bin/clickhouse
> 17. ? @ 0xf93297d in /usr/bin/clickhouse
> 18. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xf92f5a1 in /usr/bin/clickhouse
> 19. DB::PipelineExecutor::executeImpl(unsigned long) @ 0xf92d4f6 in /usr/bin/clickhouse
> 20. ? @ 0xf93acf2 in /usr/bin/clickhouse
> 21. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x864ed1f in /usr/bin/clickhouse
> 22. ? @ 0x86527b3 in /usr/bin/clickhouse
> 23. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
> 24. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

UPD: I used  **SET max_insert_threads = 4** . And the insert was successful. But I am not sure that it's a good way.

**Comment by stasDomb** [comment] 2021-06-10 05:45
Also I tried to change the settings **receive_timeout** and **send_timeout**. I increased them to 1000 sec. And I was surprised when I saw that it didn't help

**Comment by PauloHFM** [comment] 2022-07-14 01:41
@stasDomb 
Maybe fixed by [this](https://github.com/ClickHouse/ClickHouse/pull/24885). 

But I would try these things (maybe concurrently):
- Check for schema errors/corrupted lines in the last files;
- Compressing the files with supported compressions in [S3 Engine Docs](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3#creating-a-table);
- Reading the files and storing them in partitions in S3;
- Reading the files externally and inserting in ClickHouse:
    - Assuming CSV with bash and `clickhouse-client` using the [Input Docs](https://clickhouse.com/docs/en/sql-reference/table-functions/input/), could be something like this almost pseudo-code here:
```bash
for FILE in $(aws s3 ls s3://path/ | awk '{print $4}'):
    aws s3 cp s3://path/$FILE local_path/$FILE
    cat $FILE | clickhouse-client --query="INSERT INTO test_table FORMAT CSV"
    rm local_path/$FILE
```

**Comment by alexey-milovidov** [comment] 2022-10-19 22:13
Retries have been added while reading from s3 and now the issue is fixed.

**Closed by alexey-milovidov** 2022-10-19 22:13 UTC
Labels: question
