### ISSUE TITLE
Can't build on Mac because of objcopy

### ISSUE THREAD

**Issue by guxiaobo** [ClickHouse/ClickHouse#15841] opened 2020-10-11 14:01 UTC
**Operating system**
macOS Catalina 10.15.7

**Cmake version**
cmake version 3.18.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Ninja version**
1.10.1

**Compiler name and version**
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Full cmake and/or ninja output**
linda@LindadeMacBook-Air build % cmake .. -DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`which clang`
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IPO/LTO not enabled.
CMake Warning at cmake/find/ccache.cmake:17 (message):
  CCache is not found.  We recommend setting it up if you build ClickHouse
  from source often.  Setting it up will significantly reduce compilation
  time for 2nd and consequent builds
Call Stack (most recent call first):
  CMakeLists.txt:86 (include)

-- CMAKE_BUILD_TYPE is not set, set to default = RelWithDebInfo
-- CMAKE_BUILD_TYPE: RelWithDebInfo
CMake Error at CMakeLists.txt:186 (message):
  Cannot find objcopy.

-- Configuring incomplete, errors occurred!
See also "/Users/linda/Documents/Github/ClickHouse-master/build/CMakeFiles/CMakeOutput.log".
[CMakeOutput.log](https://github.com/ClickHouse/ClickHouse/files/5361212/CMakeOutput.log)

**Comment by guxiaobo** [comment] 2020-10-11 14:14
After install ccache using brew install cache, there is only the objcopy problem.

**Comment by filimonov** [comment] 2020-10-13 05:18
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/13597#issuecomment-680464522

**Closed by filimonov** 2020-10-13 05:18 UTC
Labels: build, comp-darwin
