### ISSUE TITLE
Query failures started to get reported following upgrade from 23.3 to 23.7 & 23.8 

### ISSUE THREAD

**Issue by shawel** [ClickHouse/ClickHouse#54897] opened 2023-09-21 16:42 UTC
After upgrading ClickHouse from version 23.3.2.37 to 23.7.5.30, some specific queries unexpectedly fails, and this behavior persists in version 23.8. The failure in the example below seems some combination of conditions in the WHERE clause:

    - Removing any part of the WHERE condition allows the query to run successfully.
    - Changing the last occurrence of source_id to campaign_id fixes the issue.
    - Removing the event_name condition also results in a successful query.

```
SELECT
    account_id,
    source_id
FROM s_events
WHERE (event_name IN ('commerce_order_context', 'commerce_item_context', 'action')) AND ((account_id = '2f542') OR (source_id IN ('01bc2'))) AND (source_id IN ('01bc2'))
LIMIT 1

Received exception from server (version 23.8.2):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column in(source_id, '01bc2') in block: while executing 'INPUT : 1 -> in(source_id, '01bc2') LowCardinality(UInt8) : 2': While executing MergeTreeThread. (NOT_FOUND_COLUMN_IN_BLOCK)
```

Successful query additionally tested in version [clickhouse/clickhouse-server:23.5.5.92 and clickhouse/clickhouse-server:23.4.1.1943

```
SELECT
    account_id,
    source_id
FROM s_events
WHERE (event_name IN ('commerce_order_context', 'commerce_item_context', 'action')) AND ((account_id = '2f542') OR (source_id IN ('01bc2'))) AND (source_id IN ('01bc2'))
LIMIT 1

Query id: 76d8d124-2e6b-4e68-bc91-8e8272d507e2

┌─account_id─┬─source_id─┐
│ 2f542      │ 01bc2     │
└────────────┴───────────┘
```

the columns in question are 
```
...
`advertiser_id` LowCardinality(String) DEFAULT CAST('0', 'LowCardinality(String)'),
`campaign_id` String DEFAULT '0',
`event_name` LowCardinality(String) DEFAULT CAST('0', 'LowCardinality(String)')
`source_id` LowCardinality(String) MATERIALIZED campaign_id,
`account_id` LowCardinality(String) MATERIALIZED advertiser_id
...
ENGINE = ReplicatedReplacingMergeTree
```

I did not test in 23.6.

**Comment by den-crane** [comment] 2023-09-21 16:45
Check with `set move_all_conditions_to_prewhere=0;`

probably duplicate of https://github.com/ClickHouse/ClickHouse/issues/53237

**Comment by shawel** [comment] 2023-09-21 16:46
ok @den-crane i will try that!

**Closed** 2024-05-07 14:18 UTC
Labels: st-need-repro, potential bug
