### ISSUE TITLE
Random crashesh

### ISSUE THREAD

**Issue by gigul77** [ClickHouse/ClickHouse#20609] opened 2021-02-17 08:31 UTC
Hello,

Server is sitting in LXD container and this is one of random crashes:
Create table and then after connection timeout (1h) crash:

```
2021.02.15 16:05:58.521301 [ 36975 ] {3ad195ec-c64a-4ab5-a3d7-506094048faf} <Debug> executeQuery: (from [::ffff:127.0.0.1]:35030, using production parser) create table ingest ( `timestamp` DateTime, `msec` UInt32, `name` String, `publisher` String, `crypto` String, `user_id` String, `message` String ) ENGINE = Null
2021.02.15 16:05:58.521458 [ 36975 ] {3ad195ec-c64a-4ab5-a3d7-506094048faf} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON stat.ingest
2021.02.15 16:05:58.522884 [ 36975 ] {3ad195ec-c64a-4ab5-a3d7-506094048faf} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2021.02.15 16:05:58.523055 [ 36975 ] {} <Debug> TCPHandler: Processed in 0.00212946 sec.
2021.02.15 17:06:01.790833 [ 36975 ] {} <Trace> TCPHandler: Closing idle connection
2021.02.15 17:06:01.790958 [ 36975 ] {} <Debug> TCPHandler: Done processing connection.
2021.02.15 17:06:01.874636 [ 36973 ] {} <Trace> BaseDaemon: Received signal 11
2021.02.15 17:06:01.875058 [ 12833 ] {} <Fatal> BaseDaemon: ########################################
2021.02.15 17:06:01.875228 [ 12833 ] {} <Fatal> BaseDaemon: (version 21.1.3.32 (official build), build id: 63BC1671E8C217170F9B6C6346099FD1F76E784F) (from thread 36975) (no query) Received signal Segmentation fa
2021.02.15 17:06:01.875354 [ 12833 ] {} <Fatal> BaseDaemon: Address: 0x691cb50 Access: read. Attempted access has violated the permissions assigned to the memory area.
2021.02.15 17:06:01.875439 [ 12833 ] {} <Fatal> BaseDaemon: Stack trace: 0x87c128d 0x7fdfe8aed980
2021.02.15 17:06:01.875565 [ 12833 ] {} <Fatal> BaseDaemon: 0. ? @ 0x87c128d in /usr/bin/clickhouse
2021.02.15 17:06:01.875653 [ 12833 ] {} <Fatal> BaseDaemon: 1. ? @ 0x12980 in /lib/x86_64-linux-gnu/libpthread-2.27.so
```

Is there is some extra work to do that ClickHouse work in LXD container ? 

Other "strange" things in logs:
```
2021.02.16 13:10:27.491675 [ 1351 ] {} <Error> ZooKeeper: Cannot use ZooKeeper host uk-gr-b-1.us-hadoop.l:2181, reason: Host not found: uk-gr-b-1.us-hadoop.l
```
But host name IS: `zk-gr-b-1.us-hadoop.l` not `uk-gr-b-1.us-hadoop.l.` Sometime it also somehow change 1 latter (first letter) in table names also.  

Yes. Memory in server is working fine. It's ECC memory type and no error are logged.

**Comment by filimonov** [comment] 2021-02-17 11:33
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/20608

**Closed by filimonov** 2021-02-17 11:33 UTC
Labels: v21.1-affected
