### ISSUE TITLE
add the commands of postgres?

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#13545] opened 2020-08-09 14:04 UTC
eg.  ```\d``` to show all tables' names and other info 

(you don't have to strictly follow this form)

**Use case**
A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by filimonov** [comment] 2020-08-10 06:44
Duplicate of #9339

**Closed by filimonov** 2020-08-10 06:44 UTC
Labels: feature
