### ISSUE TITLE
Can't insert data from mysql in 19.16.14.65

### ISSUE THREAD

**Issue by gglinux** [ClickHouse/ClickHouse#10391] opened 2020-04-21 05:38 UTC
**Describe the bug**
SQL:
 ```
INSERT INTO test.demo (`id`,`created`) FROM mysql('host', 'mysql_test', 'demo', 'XXX', 'XXX')
```
response:
```
Ok.
0 rows in set. Elapsed: 0.016 sec
```
The mysql table 'mysql_test.demo' is not empty, but after insert into ClickHouse, the ClickHouse test.demo table is empty. No any exception throw when execute the insert SQL

When I use the 19.16.14.65 version of ClickHouse. the insert SQL is bad.
But When I use the 20.1.5.26 version of ClickHouse. the insert SQL is ok. Unfortunately,  the 20.1.5.26 version of ClickHouse occured #9860. 

**How to reproduce**
* Which ClickHouse server version to use:  19.16.14.65
* Which interface to use, if matters: HTTP and clickhouse-client
* Non-default settings, if any: http port,tcp port,timezone
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
Insert data from mysql is ok

**Error message and/or stacktrace**

![image](https://user-images.githubusercontent.com/7273957/79829334-58d75080-83d5-11ea-8d78-c7b73a63ec7b.png)

**Comment by gglinux** [comment] 2020-04-21 06:43
Which version can solve the above two problems? #9860 , #10391

**Comment by filimonov** [comment] 2020-04-21 21:28
It is a duplicate of  #7885

Workaround: `create table (...) engine=MySQL(...)` and use that instead.

**Comment by filimonov** [comment] 2020-04-21 21:33
> Which version can solve the above two problems? #9860 , #10391

The latest 20.3, or the latest 20.1 (20.1.10 currently)

**Closed** 2020-04-21 23:31 UTC
Labels: bug, comp-foreign-db, duplicate, obsolete-version, st-fixed

**Comment by gglinux** [comment] 2020-04-22 09:57
The 20.3.5.21 version fixed. Thx~

But there's another problem in the latest 20.3. #10436
