### ISSUE TITLE
possibly incorrect parsing of chunked RowBinary requests (CANNOT_READ_ALL_DATA)

### ISSUE THREAD

**Issue by ruslandoga** [ClickHouse/ClickHouse#44167] opened 2022-12-12 15:41 UTC
When sending data in `RowBinary` format with `transfer-encoding: chunked` and a chunk starting with a string of length 13 (= `\r` in ascii), clickhouse raises an exception: 

```
Code: 33. DB::Exception: Cannot read all data. Bytes read: 12. Bytes expected: 101.: (at row 1)\n: While executing BinaryRowInputFormat. (CANNOT_READ_ALL_DATA) (version 22.10.1.1175 (official build))
```

Sending a chunk starting with a string of different length avoids this problem.

Example request:

```
0000   50 4f 53 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d   POST / HTTP/1.1.
0010   0a 74 72 61 6e 73 66 65 72 2d 65 6e 63 6f 64 69   .transfer-encodi
0020   6e 67 3a 20 63 68 75 6e 6b 65 64 0d 0a 68 6f 73   ng: chunked..hos
0030   74 3a 20 6c 6f 63 61 6c 68 6f 73 74 3a 38 31 32   t: localhost:812
0040   33 0d 0a 75 73 65 72 2d 61 67 65 6e 74 3a 20 6d   3..user-agent: m
0050   69 6e 74 2f 31 2e 34 2e 32 0d 0a 78 2d 63 6c 69   int/1.4.2..x-cli
0060   63 6b 68 6f 75 73 65 2d 64 61 74 61 62 61 73 65   ckhouse-database
0070   3a 20 70 6c 61 75 73 69 62 6c 65 5f 74 65 73 74   : plausible_test
0080   0d 0a 0d 0a 33 34 0d 0a 49 4e 53 45 52 54 20 49   ....34..INSERT I
0090   4e 54 4f 20 22 73 65 73 73 69 6f 6e 73 22 28 22   NTO "sessions"("
00a0   68 6f 73 74 6e 61 6d 65 22 29 20 46 4f 52 4d 41   hostname") FORMA
00b0   54 20 52 6f 77 42 69 6e 61 72 79 20 0d 0a 45 0d   T RowBinary ..E.
00c0   0a 0d 65 78 61 6d 70 6c 65 2d 30 2e 63 6f 6d 0d   ..example-0.com.
00d0   0a 30 0d 0a 0d 0a                                 .0....
```

**Does it reproduce on recent release?**

Yes. I'm using version 22.10.1.1175.

**How to reproduce**

```console
$ echo 'CREATE TABLE sessions (hostname String) ENGINE = Memory' | curl 'http://localhost:8123/' --data-binary @-
```
```console
$ echo -ne 'POST / HTTP/1.1\r\ntransfer-encoding: chunked\r\nhost: localhost:8123\r\n\r\n30\r\nINSERT INTO sessions(hostname) FORMAT RowBinary \r\nE\r\n\rexample-0.com\r\n0\r\n\r\n' | nc localhost 8123
HTTP/1.1 500 Internal Server Error
Date: Mon, 12 Dec 2022 16:18:21 GMT
Connection: Keep-Alive
Content-Type: text/plain; charset=UTF-8
X-ClickHouse-Server-Display-Name: mac3.local
Transfer-Encoding: chunked
X-ClickHouse-Exception-Code: 33
Keep-Alive: timeout=10
X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0"}

C7
Code: 33. DB::Exception: Cannot read all data. Bytes read: 12. Bytes expected: 101.: (at row 1)
: While executing BinaryRowInputFormat. (CANNOT_READ_ALL_DATA) (version 22.10.1.1175 (official build))

0

```
And here's a successful request with a shorter (~~10~~ 11 bytes) string:
```console
$ echo -ne 'POST / HTTP/1.1\r\ntransfer-encoding: chunked\r\nhost: localhost:8123\r\n\r\n30\r\nINSERT INTO sessions(hostname) FORMAT RowBinary \r\nC\r\n\vexample.com\r\n0\r\n\r\n' | nc localhost 8123
HTTP/1.1 200 OK
Date: Mon, 12 Dec 2022 16:36:12 GMT
Connection: Keep-Alive
Content-Type: text/plain; charset=UTF-8
X-ClickHouse-Server-Display-Name: mac3.local
Transfer-Encoding: chunked
Keep-Alive: timeout=10
X-ClickHouse-Summary: {"read_rows":"1","read_bytes":"20","written_rows":"1","written_bytes":"20","total_rows_to_read":"0","result_rows":"1","result_bytes":"20"}

0

```

**Comment by LGDHuaOPER** [comment] 2022-12-14 07:53
I had the same problem.

```
2022.12.14 07:31:23.343654 [ 2926 ] {a5e8398b-cede-4967-8687-641b766ea51a} <Error> executeQuery: Code: 33. DB::Exception: Cannot read all data. Bytes read: 23. Bytes expected: 82. (CANNOT_READ_ALL_DATA) (version 22.11.2.30 (official build)) (from 10.195.152.30:43395) (in query: INSERT INTO aaa_buffer ( `insert_time`,`x_request_id`,`pool_1_name`,`pool_1_time`,`pool_1_ret`,`pool_2_name`,`pool_2_time`,`pool_2_ret`,`pool_3_name`,`pool_3_time`,`pool_3_ret`,`pool_4_name`,`pool_4_time`,`pool_4_ret`,`pool_5_name`,`pool_5_time`,`pool_5_ret`,`pool_6_name`,`pool_6_time`,`pool_6_ret`,`pool_7_name`,`pool_7_time`,`pool_7_ret`,`pool_8_name`,`pool_8_time`,`pool_8_ret`,`pool_9_name`,`pool_9_time`,`pool_9_ret`,`pool_10_name`,`pool_10_time`,`pool_10_ret`,`pool_11_name`,`pool_11_time`,`pool_11_ret`,`pool_12_name`,`pool_12_time`,`pool_12_ret`,`pool_13_name`,`pool_13_time`,`pool_13_ret`,`pool_14_name`,`pool_14_time`,`pool_14_ret`,`pool_15_name`,`pool_15_time`,`pool_15_ret`,`pool_16_name`,`pool_16_time`,`pool_16_ret`,`pool_17_name`,`pool_17_time`,`pool_17_ret`,`pool_18_name`,`pool_18_time`,`pool_18_ret`,`pool_19_name`,`pool_19_time`,`pool_19_ret`,`pool_20_name`,`pool_20_time`,`pool_20_ret`,`pool_21_name`,`pool_21_time`,`pool_21_ret`,`pool_22_name`,`pool_22_time`,`pool_22_ret`,`pool_23_name`,`pool_23_time`,`pool_23_ret`,`pool_24_name`,`pool_24_time`,`pool_24_ret`,`pool_25_name`,`pool_25_time`,`pool_25_ret`,`pool_26_name`,`pool_26_time`,`pool_26_ret`,`pool_27_name`,`pool_27_time`,`pool_27_ret`,`pool_28_name`,`pool_28_time`,`pool_28_ret`,`pool_29_name`,`pool_29_time`,`pool_29_ret`,`pool_30_name`,`pool_30_time`,`pool_30_ret`,`pool_31_name`,`pool_31_time`,`pool_31_ret`,`pool_32_name`,`pool_32_time`,`pool_32_ret`,`pool_33_name`,`pool_33_time`,`pool_33_ret`,`pool_34_name`,`pool_34_time`,`pool_34_ret`,`pool_35_name`,`pool_35_time`,`pool_35_ret`,`pool_36_name`,`pool_36_time`,`pool_36_ret` ) VALUES), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xda0fa9a in /usr/bin/clickhouse
1. ? @ 0xda6acca in /usr/bin/clickhouse
2. ? @ 0x1276c2f1 in /usr/bin/clickhouse
3. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const @ 0x1272e66b in /usr/bin/clickhouse
4. DB::NativeReader::readData(DB::ISerialization const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, DB::ReadBuffer&, unsigned long, double) @ 0x14399ce0 in /usr/bin/clickhouse
5. DB::NativeReader::read() @ 0x1439a595 in /usr/bin/clickhouse
6. DB::TCPHandler::receiveData(bool) @ 0x143791f0 in /usr/bin/clickhouse
7. DB::TCPHandler::receivePacket() @ 0x1436ec0e in /usr/bin/clickhouse
8. DB::TCPHandler::readDataNext() @ 0x14371f16 in /usr/bin/clickhouse
9. DB::TCPHandler::processInsertQuery() @ 0x1436f93e in /usr/bin/clickhouse
10. DB::TCPHandler::runImpl() @ 0x14367ec3 in /usr/bin/clickhouse
11. DB::TCPHandler::run() @ 0x1437b079 in /usr/bin/clickhouse
12. Poco::Net::TCPServerConnection::start() @ 0x171b0e14 in /usr/bin/clickhouse
13. Poco::Net::TCPServerDispatcher::run() @ 0x171b27bb in /usr/bin/clickhouse
14. Poco::PooledThread::run() @ 0x173415c7 in /usr/bin/clickhouse
15. Poco::ThreadImpl::runnableEntry(void*) @ 0x1733effd in /usr/bin/clickhouse
16. ? @ 0x7f15331cd609 in ?
17. __clone @ 0x7f15330f2133 in ?

2022.12.14 07:31:23.345074 [ 2926 ] {a5e8398b-cede-4967-8687-641b766ea51a} <Error> TCPHandler: Code: 33. DB::Exception: Cannot read all data. Bytes read: 23. Bytes expected: 82. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xda0fa9a in /usr/bin/clickhouse
1. ? @ 0xda6acca in /usr/bin/clickhouse
2. ? @ 0x1276c2f1 in /usr/bin/clickhouse
3. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>>*) const @ 0x1272e66b in /usr/bin/clickhouse
4. DB::NativeReader::readData(DB::ISerialization const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, DB::ReadBuffer&, unsigned long, double) @ 0x14399ce0 in /usr/bin/clickhouse
5. DB::NativeReader::read() @ 0x1439a595 in /usr/bin/clickhouse
6. DB::TCPHandler::receiveData(bool) @ 0x143791f0 in /usr/bin/clickhouse
7. DB::TCPHandler::receivePacket() @ 0x1436ec0e in /usr/bin/clickhouse
8. DB::TCPHandler::readDataNext() @ 0x14371f16 in /usr/bin/clickhouse
9. DB::TCPHandler::processInsertQuery() @ 0x1436f93e in /usr/bin/clickhouse
10. DB::TCPHandler::runImpl() @ 0x14367ec3 in /usr/bin/clickhouse
11. DB::TCPHandler::run() @ 0x1437b079 in /usr/bin/clickhouse
12. Poco::Net::TCPServerConnection::start() @ 0x171b0e14 in /usr/bin/clickhouse
13. Poco::Net::TCPServerDispatcher::run() @ 0x171b27bb in /usr/bin/clickhouse
14. Poco::PooledThread::run() @ 0x173415c7 in /usr/bin/clickhouse
15. Poco::ThreadImpl::runnableEntry(void*) @ 0x1733effd in /usr/bin/clickhouse
16. ? @ 0x7f15331cd609 in ?
17. __clone @ 0x7f15330f2133 in ?
```

`My ClickHouse version is 22.11.2.30`

Timeout config is:

```
<connect_timeout>20</connect_timeout>
<connect_timeout_with_failover_ms>100</connect_timeout_with_failover_ms>
<connect_timeout_with_failover_secure_ms>200</connect_timeout_with_failover_secure_ms>
<receive_timeout>600</receive_timeout>
<send_timeout>600</send_timeout>
<idle_connection_timeout>1800</idle_connection_timeout>
```

**Comment by yakov-olkhovskiy** [comment] 2022-12-15 17:02
From my preliminary investigation:
there is a general bug in parsing chunk data for HTTP chanked encoding.
Initial implementation PR:
https://github.com/ClickHouse/ClickHouse/pull/30178
offending code:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Formats/Impl/BinaryRowInputFormat.cpp#L62
```
    serialization->deserializeBinary(column, *in, format_settings);
```
Explanation:
the HTTP chank data is not a raw binary string, prepended by its size, but just a string emplaced into buffer

**Comment by yakov-olkhovskiy** [comment] 2022-12-15 21:08
not a bug

**Comment by ruslandoga** [comment] 2022-12-16 03:17
Plus it's not like all chunked RowBinary requests don't work. It's this particular case with a chunk starting with a string of 13 bytes that doesn't work.

**Comment by yakov-olkhovskiy** [comment] 2022-12-16 03:22
@ruslandoga 
>do you mean there shouldn't be any chunking

no, it has nothing to do with chunked encoding - chunked encoding just a way to transfer data, possibly of different content-types, in a single HTTP request
>Then it makes RowBinary incompatible with HTTP spec

not necessary - it's only makes it very inconvenient - that you request with "a shorter (10 bytes) string" worked just by sheer luck - the string "\vexample.com" - consist of first byte '\v' - which is vertical tab - code 11 decimal - and rest of the string "example.com" - is 11 symbols length - so, you can encode data in binary in HTTP body for RowBinary, but everything must be binary according to docs - it's very inconvenient.
>The clients do that just fine when ClickHouse responds in RowBinary with transfer-encoding: chunked for SELECT queries

sure - because client treats this data as binary - according to aforementioned doc
>Can you please take another look at this? It's an important use-case for INSERTing data efficiently over HTTP

I'm quite certain regarding this issue - I hope my explanation is good enough. If you still not sure that it's a correct behavior, we can discuss specific use case and find a solution you are looking for.

**Comment by yakov-olkhovskiy** [comment] 2022-12-16 03:33
ok, give me a second, I will explain with an example... or, if you think it's appropriate, we can discuss it in slack?

**Comment by ruslandoga** [comment] 2022-12-16 03:33
Whatever's is more convenient for you :)

**Comment by yakov-olkhovskiy** [comment] 2022-12-16 03:37
hm... I'm not sure on our policy of inviting outsiders to company slack... do you have some online contact we can talk?

**Comment by ruslandoga** [comment] 2022-12-16 03:38
I can start a zoom call if you'd like :)

**Comment by yakov-olkhovskiy** [comment] 2022-12-16 03:39
sure

**Comment by ruslandoga** [comment] 2022-12-16 03:40
https://us05web.zoom.us/j/2149173235?pwd=cm9KK1cwdWdKaThjeUl1UXdkK3dJZz09

**Comment by yakov-olkhovskiy** [comment] 2022-12-16 08:50
after talking with @ruslandoga I was able to verify, that bug exists
offending code is in INSERT query parser:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ParserInsertQuery.cpp#L242-L251

fix will provided shortly

**Comment by yakov-olkhovskiy** [comment] 2022-12-16 10:23
After some consultation with team this situation is identified as deficiency in documentation - since it is a problem of ambiguity, delimiter between expression `FORMAT RowBinary` and actual data should be specified exactly, and currently delimiter is the new line ("\r\n" sequence) - i.e. after `FORMAT RowBinary` can follow any number of whitespaces followed by "\r\n" sequence followed by binary data.
This ticket will be later closed by appending documentation with appropriate clause, no code change is required.
@ruslandoga thank you for bringing up this issue.

**Comment by LGDHuaOPER** [comment] 2022-12-16 10:44
I have a question. I think you are talking about HTTP.

But my problem is that when TCP inserts data, I use C++ SDK.

Is this bug the cause of my `CANNOT_READ_ALL_DATA` error?

**Comment by ruslandoga** [comment] 2022-12-16 10:55
I've been able to verify that [using `\r\n` instead of `\s` after `FORMAT RowBinary`](https://github.com/ruslandoga/ch/pull/2) fixes my original issue :)

@yakov-olkhovskiy thank you for bearing with my confusing reports!

@LGDHuaOPER I think it might be helpful for the maintainers if you provide the table schema and the data that's being inserted.

**Comment by yakov-olkhovskiy** [comment] 2022-12-16 14:57
@LGDHuaOPER issue of this topic is not specific for HTTP per se - the same rule of delimiting would apply, for example, to INSERT from client:
```
ubuntu@ip-172-31-42-195:~/ClickHouse/build/programs$ echo -ne 'INSERT INTO sessions(hostname) FORMAT RowBinary \rexample-0.com' | clickhouse client
Code: 33. DB::Exception: Cannot read all data. Bytes read: 12. Bytes expected: 101.: (at row 1)
example-0.com). (CANNOT_READ_ALL_DATA): data for INSERT was parsed from query: (in query: INSERT INTO sessions(hostname) FORMAT RowBinary

ubuntu@ip-172-31-42-195:~/ClickHouse/build/programs$ echo -ne 'INSERT INTO sessions(hostname) FORMAT RowBinary \r\n\rexample-0.com' | clickhouse client
ubuntu@ip-172-31-42-195:~/ClickHouse/build/programs$
```

As @ruslandoga mentioned above, it would be helpful if you provide some specifics on your problem.

**Closed** 2022-12-17 00:57 UTC
Labels: potential bug
