### ISSUE TITLE
PREWHERE breaks CTE clause with arrayJoin(arrayEnumerate())

### ISSUE THREAD

**Issue by yard** [ClickHouse/ClickHouse#37190] opened 2022-05-13 13:42 UTC
**Describe what's wrong**
Before going into description I must warn that the issue seems to be quite random and magically heals itself with even subtle changes to the original setup.

TLDR is `arrayJoin(arrayEnumerate())` (and probably other functions) cannot be used when specified in a CTE block if the query involves `PREWHERE` section or optimisation. The error returned says something like:
```
DB::Exception: Illegal column Function of first argument of function arrayEnumerate: while executing 'FUNCTION arrayEnumerate(arr : 5) -> arrayEnumerate(arr) Array(UInt32) : 7'. (ILLEGAL_COLUMN)
```

Disabling `PREWHERE`, moving CTE block to `SELECT` clause, removing the usage of `arrayEnumerate` results or removing `arrayJoin` function makes the issue go away.

**Does it reproduce on recent release?**
We were able to reproduce on several versions starting with 21.9, including latest-and-greatest 22.3 and 22.4 releases (using official Docker Hub images).

**How to reproduce**
Run the following SQL in Clickhouse:
```
CREATE TABLE test (a Int32, b Int32) ENGINE = MergeTree() ORDER BY a;
INSERT INTO test SELECT number, 1 FROM numbers(3);
WITH
    transform(a, [0], [1]) as t,
    [[1]][t] as arr,
    arrayJoin(arrayEnumerate(arr)) as i,
    arr[i] as v
SELECT 
    a, b
FROM 
    test
PREWHERE b >= 0
WHERE v IN (1);
```

If `PREWHERE` section is removed or `arr` expression is replaced with inline value, the query starts to work:
```
WITH
    transform(a, [0], [1]) as t,
    [[1]][t] as arr,
    arrayJoin(arrayEnumerate([[1]][transform(a, [0], [1])])) as i,
    arr[i] as v
SELECT 
    a, b
FROM 
    test
PREWHERE b >= 0
WHERE v IN (1);
```

**Expected behavior**
Two rows of (0, 1) and (1, 1) are returned.

**Error message and/or stacktrace**
```
Received exception from server (version 22.4.5):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Illegal column Function of first argument of function arrayEnumerate: while executing 'FUNCTION arrayEnumerate(arr : 5) -> arrayEnumerate(arr) Array(UInt32) : 7'. (ILLEGAL_COLUMN)
```

**Additional context**
We have obtained this example by itertively simplifying a real-world query from our codebase. I do appreciate the provided example looks like Frankenstein's monster, but in our setup all parts (CTE, `transform`, `arrayJoin(arrayEnumerate)` etc) do make sense and cannot be easily replaced without loosing flexibility or performance.

**Comment by KochetovNicolai** [comment] 2022-05-16 13:08
```
WITH
    transform(a, [0], [1]) AS t,
    [[1]][t] AS arr,
    arrayJoin(arrayEnumerate([t])) AS i,
    arr[i] AS v
SELECT
    a,
    b
FROM test
PREWHERE b >= 0
WHERE v IN (1)

```
this one crashes ClickHouse to me

**Comment by yard** [comment] 2022-05-17 11:01
Oh, wdym by "crash"? Like a literal crash (segfault or smth) or just the error similar to the one I posted?

**Comment by alexey-milovidov** [comment] 2022-06-14 19:03
@KochetovNicolai It does not reproduce on fresh build.

**Comment by SaltTan** [comment] 2022-06-29 20:45
It seems to be fixed by https://github.com/ClickHouse/ClickHouse/pull/37336

**Closed** 2022-06-30 23:37 UTC
Labels: bug, crash, v22.3-affected
