### ISSUE TITLE
FR: count unique values only locally if it is known that they do not overlap between servers

### ISSUE THREAD

**Issue by re-action** [ClickHouse/ClickHouse#332] opened 2017-01-13 13:02 UTC
Clickhouse has an ability to limit scope of IN/JOIN constructions while querying clustered tables: you could either use local tables or pass result set to  querying server and do IN/JOIN there depending on your sharding scheme.

It will be nice to have same functionality for uniq* family of functions. The idea is: If you know that particular column contains only specific range of values on each shard of you cluster you could use local version of uniq functions avoiding final aggregation phase (actually replacing it with summing of values received from different shards).

**Comment by alexey-milovidov** [comment] 2017-01-13 19:52
Nice idea!

We have related setting: `distributed_group_by_no_merge`.
If you set it to 1, then intermediate results from remote servers will not be merged.

Example: https://gist.github.com/alexey-milovidov/b097ac3baa210b7743d046e438bf2831
Also it shows, that settings could be specified in subquery, using SETTINGS clause. (Not every setting could be specified that way.)

`distributed_group_by_no_merge` is experimental, and its usage is cumbersome.

Specific aggregate function for this purpose will be more usable.
But there are some implementation problems.
In aggregate function interface, we have `serialize`, `deserialize` and `merge` methods.
Of course, we could write single "total" value in `serialize` method and just sum that values in `merge` methods - it will work as expected.
But serialize/deserialize is used not only during distributed query execution, but also for another purposes: for external aggregation (when intermediate results are dumped to disk), for storing aggregation states in tables (in materialized views). 
It means, that modifying just implementation of aggregate function is not enough to achieve desired result.

We still may introduce some strange aggregate function, that will work as expected during distributed query execution, but will work incorrectly while using external aggregation or storing in tables.

**Comment by re-action** [comment] 2017-01-16 18:35
Yeap, you're right, separate function will be more straight forward and understandable approach. However it looks like distributed_group_by_no_merge setting do it's job. Is there any limitations on it's usage?

**Comment by alexey-milovidov** [comment] 2017-01-16 20:40
I remember some issues with building query plan involving ORDER BY or LIMIT.
(like ordered results don't get merged or you get more data than limit)
That is understandable and consistent with behaviour of this option, but may be surprising.

**Comment by alexey-milovidov** [comment] 2020-04-16 20:52
@azat If we do GROUP BY injective function of sharding key, we can set `distributed_group_by_no_merge` setting automatically.

**Comment by azat** [comment] 2020-04-16 21:05
>If we do GROUP BY injective function of sharding key

Indeed, I already though about that kind of optimization (automatically set `distributed_group_by_no_merge`, this can speedup distributed queries a lot in such cases)

>and the setting skip_unavailable_shards is active

Am I understand this correctly, the problem is that if this setting will be ignored, in case of server is unavailable the server will send all rows from all shards except unavailable while it should just give an error? Nice catch!

**Comment by azat** [comment] 2020-04-16 21:10
>If we do GROUP BY injective function of sharding key

Although brief look at `isInjective` shows that it is not set correctly for some useful stuff (module, consistent hashing), so this also should not be forgotten.

**Comment by alexey-milovidov** [comment] 2020-04-16 21:13
> Am I understand this correctly, the problem is that if this setting will be ignored, in case of server is unavailable the server will send all rows from all shards except unavailable while it should just give an error? Nice catch!

No, I messed it with skip_unused_shards :)

**Comment by alexey-milovidov** [comment] 2020-04-16 21:15
> Although brief look at isInjective shows that it is not set correctly for some useful stuff (module, consistent hashing), so this also should not be forgotten.

But modulo and consistent hashing are not injective.
Example of injective function is `toString`.

Suppose we write:
```
SELECT ... GROUP BY toString(sharding_key)
```

**Comment by azat** [comment] 2020-04-16 21:26
>No, I messed it with skip_unused_shards :)

Now I got it!

>server is unavailable ... it should just give an error?

Too smart :)

>But modulo and consistent hashing are not injective.

Indeed, my mistake.
Optimization for GROUP BY and for WHERE (optimize_skip_unused_shards) mixed in my head

**Closed** 2020-04-20 05:30 UTC
Labels: feature
