### ISSUE TITLE
How does the HDFS engine use kerberos authentication?

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#14676] opened 2020-09-10 01:44 UTC
Recently, our HADOOP cluster has added kerberos authentication. When using the hdfs engine, when reading hdfs data, an exception will be thrown:
SIMPLE authentication is not enabled.Available:[TOKEN,KERBEROS],
Is there any good solution?

**Comment by filimonov** [comment] 2020-09-10 07:54
https://github.com/ClickHouse/ClickHouse/issues/5747

**Comment by filimonov** [comment] 2020-09-10 07:55
Duplicate of #5747

https://github.com/ClickHouse/ClickHouse/blob/7edb911e9179563aa4b8b8e7127fd9b605e70a16/contrib/libhdfs3-cmake/CMakeLists.txt#L20

**Closed by filimonov** 2020-09-10 07:55 UTC
Labels: duplicate, question, comp-object-storage
