### ISSUE TITLE
IN operator much slower on 23.6.1 than on 23.4.2.11

### ISSUE THREAD

**Issue by whitemay** [ClickHouse/ClickHouse#51846] opened 2023-07-05 14:35 UTC
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I have a merge table (say) t_merge, and a memory table t_memory.
on version 23.4.2.11, I use IN operator to query records from t_merge, by "where (xx, xxx) in t_memory). It is really quick than "t_merge left semi join t_memory". that is 100ms vs 6s.
but when upgrade to version 23.6.1, the IN operator slow down to 6s, almost same as "left semi join".
what is wrong?

**How to reproduce**
* Which ClickHouse server version to use - 23.6.1
* Which interface to use, if matters - JetBrains DataGrip with http
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
IN operator performance better.

**Error message and/or stacktrace**

**Additional context**
there is some signal may related:
that seems clickhouse server return rows quickly just as former version, (not sure all or just part of them). then after several seconds it show query finished. 
maybe server finished work already, but block for a while then finish the query process?

**Comment by Algunenano** [comment] 2023-07-05 14:43
Without table definition or queries it's impossible to know, but it might be related to https://github.com/ClickHouse/ClickHouse/issues/51507, fixed in https://github.com/ClickHouse/ClickHouse/pull/51610

Can you try with prewhere or provide a full reproducible test case?

**Comment by den-crane** [comment] 2023-07-05 14:50
Please provide from 23.4 and 23.6


```
set send_logs_level = 'debug';

select .... from t_merge, by "where (xx, xxx) in t_memory format Null
```

**Comment by whitemay** [comment] 2023-07-06 05:04
I tried, move IN to PREWHERE really fix the problem. thx a lot.

**Comment by whitemay** [comment] 2023-08-01 11:26
I have to reopen the issue. 
after i update to 23.6.2, the issue occured again. and prewhere not work this time.
I down to 23.6.1, prewhere not worked.
I downgrade to 23.3.8, then issue resolved.

Any other suggestion about this issue?

**Comment by nickitat** [comment] 2023-08-01 12:05
you need to find what is different. prewhere decisions visible in logs, you could also check for difference in query plan.

**Comment by whitemay** [comment] 2023-08-01 12:48
Now I use prewhere only, so there is no different of query between versions.
i checked query plan and AST, on 23.6.2 vs 23.3.8. they are identical.
but pipeline is much different. pipeline on v23.3.8 is
```
(Expression)
ExpressionTransform
  (Sorting)
  MergingSortedTransform 24 → 1
    MergeSortingTransform × 24
      LimitsCheckingTransform × 24
        PartialSortingTransform × 24
          (Expression)
          ExpressionTransform × 24
            (Aggregating)
            Resize 8 → 24
              AggregatingTransform × 8
                StrictResize 8 → 8
                  (Expression)
                  ExpressionTransform × 8
                    (ReadFromMerge)
```
pipeline on v23.6.2 is
```
(CreatingSets)
DelayedPorts 2 → 1
  (Expression)
  ExpressionTransform
    (Sorting)
    MergingSortedTransform 24 → 1
      MergeSortingTransform × 24
        LimitsCheckingTransform × 24
          PartialSortingTransform × 24
            (Expression)
            ExpressionTransform × 24
              (Aggregating)
              Resize 96 → 24
                AggregatingTransform × 96
                  StrictResize 96 → 96
                    (Expression)
                    ExpressionTransform × 96
                      (ReadFromMerge)
  (CreatingSet)
  CreatingSetsTransform
    (Expression)
    ExpressionTransform
      (Distinct)
      DistinctTransform
        (Distinct)
        DistinctTransform
          (Expression)
          ExpressionTransform
            (ReadFromMemoryStorage)
```

**Comment by SaltTan** [comment] 2023-08-01 15:42
I found that primary key conditions are not recognized for subqueries.
```
┌─version()─┐
│ 23.6.2.18 │
└───────────┘

executeQuery: (from [::1]:42964) select count() from table1 where cmp_key in (1) (stage: Complete)
db.table1 (SelectExecutor): Key condition: (column 2 in 1-element set)
db.table1 (SelectExecutor): MinMax index condition: unknown
db.table1 (SelectExecutor): Selected 59/59 parts by partition key, 59 parts by primary key, 15183/213384 marks by primary key

executeQuery: (from [::1]:42964) select count() from table1 where cmp_key in (SELECT 1) (stage: Complete)
db.table1 (SelectExecutor): Key condition: unknown
db.table1 (SelectExecutor): MinMax index condition: unknown
db.table1 (SelectExecutor): Selected 58/58 parts by partition key, 58 parts by primary key, 213382/213382 marks by primary key
```

**Comment by nickitat** [comment] 2023-08-01 15:54
yep, it depends on type: https://fiddle.clickhouse.com/f68019b8-6788-43a9-89b6-47920e8efdd9

**Comment by SaltTan** [comment] 2023-08-01 16:09
It's because of PREWHERE
23.6 https://fiddle.clickhouse.com/328cc4c9-89c0-4986-a598-428a332f3374
23.5 https://fiddle.clickhouse.com/58e44697-7e9b-40ec-a589-f2de0294b8db
It seems to be fixed in 23.7: https://fiddle.clickhouse.com/09e9e066-8da4-4145-a9b2-c9b7404801ec

**Comment by nickitat** [comment] 2023-08-01 16:13
@whitemay could you pls try update further )

**Comment by whitemay** [comment] 2023-08-07 05:48
@nickitat I checked on 23.7.3, not fixed.

**Comment by whitemay** [comment] 2023-08-08 05:13
I tried to save the log. the query is :
```
select jz_id, zddm, zdmc, max(zd.weight) as weight
from zhenduan zd
prewhere (jz_id, rybh, sjfq) in (
    select distinct jz_id, rybh, sjfq from tp_find_user1
)
group by jz_id, zddm, zdmc
order by jz_id, weight desc;
```
logs on version 23.3:
```
[71b182c921d1] 2023.08.08 13:00:43.028155 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> executeQuery: (from 127.0.0.1:36538, user: aston) select jz_id, zddm, zdmc, max(zd.weight) as weight from zhenduan zd prewhere (jz_id, rybh, sjfq) in ( select distinct jz_id, rybh, sjfq from tp_find_user1 ) group by jz_id, zddm, zdmc order by jz_id, weight desc; (stage: Complete)
[71b182c921d1] 2023.08.08 13:00:43.029028 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_changzhou (e9914ba2-eb1b-41f2-9207-e616c5b4df9b) (SelectExecutor): Key condition: (column 1 in 100-element set)
[71b182c921d1] 2023.08.08 13:00:43.030333 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_changzhou (e9914ba2-eb1b-41f2-9207-e616c5b4df9b) (SelectExecutor): Selected 2/2 parts by partition key, 2 parts by primary key, 135/16016 marks by primary key, 135 marks to read from 115 ranges
[71b182c921d1] 2023.08.08 13:00:43.030399 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_changzhou (e9914ba2-eb1b-41f2-9207-e616c5b4df9b) (SelectExecutor): Reading approx. 1099466 rows with 6 streams
[71b182c921d1] 2023.08.08 13:00:43.030626 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_nanjing (300694cd-d39b-4d1f-b0f1-9365d1565a62) (SelectExecutor): Key condition: (column 1 in 100-element set)
[71b182c921d1] 2023.08.08 13:00:43.031226 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_nanjing (300694cd-d39b-4d1f-b0f1-9365d1565a62) (SelectExecutor): Selected 3/3 parts by partition key, 2 parts by primary key, 49/50452 marks by primary key, 49 marks to read from 15 ranges
[71b182c921d1] 2023.08.08 13:00:43.031273 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_nanjing (300694cd-d39b-4d1f-b0f1-9365d1565a62) (SelectExecutor): Reading approx. 394337 rows with 3 streams
[71b182c921d1] 2023.08.08 13:00:43.031449 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_suzhou (80edf077-64a3-43a3-851f-9cbe189244e0) (SelectExecutor): Key condition: (column 1 in 100-element set)
[71b182c921d1] 2023.08.08 13:00:43.031631 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_suzhou (80edf077-64a3-43a3-851f-9cbe189244e0) (SelectExecutor): Selected 2/2 parts by partition key, 2 parts by primary key, 16/27805 marks by primary key, 16 marks to read from 5 ranges
[71b182c921d1] 2023.08.08 13:00:43.031666 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_suzhou (80edf077-64a3-43a3-851f-9cbe189244e0) (SelectExecutor): Reading approx. 127582 rows with 2 streams
[71b182c921d1] 2023.08.08 13:00:43.031808 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_wuxi (0811cc18-4d76-49aa-9a52-bfcddb9a7f8d) (SelectExecutor): Key condition: (column 1 in 100-element set)
[71b182c921d1] 2023.08.08 13:00:43.032120 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_wuxi (0811cc18-4d76-49aa-9a52-bfcddb9a7f8d) (SelectExecutor): Selected 5/5 parts by partition key, 3 parts by primary key, 28/24842 marks by primary key, 28 marks to read from 11 ranges
[71b182c921d1] 2023.08.08 13:00:43.032160 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> fk_jiangsu.zhenduan_wuxi (0811cc18-4d76-49aa-9a52-bfcddb9a7f8d) (SelectExecutor): Reading approx. 229106 rows with 3 streams
[71b182c921d1] 2023.08.08 13:00:43.060136 [ 316 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> MergingSortedTransform: Merge sorted 2 blocks, 101 rows in 0.027999832 sec., 3607.164500129858 rows/sec., 424.56 KiB/sec
...
[71b182c921d1] 2023.08.08 13:00:43.060715 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> executeQuery: Read 1850591 rows, 123.46 MiB in 0.032623 sec., 56726573.2765227 rows/sec., 3.70 GiB/sec.
[71b182c921d1] 2023.08.08 13:00:43.061225 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> MemoryTracker: Peak memory usage (for query): 14.88 MiB.
[71b182c921d1] 2023.08.08 13:00:43.061228 [ 32 ] {03da7fd7-f12f-4a7b-a595-1a292771b1a0} <Debug> TCPHandler: Processed in 0.033238661 sec.

101 rows in set. Elapsed: 0.033 sec. Processed 1.85 million rows, 129.46 MB (56.60 million rows/s., 3.96 GB/s.)
```
logs on version 23.7.3:
```
[71b182c921d1] 2023.08.08 13:04:36.659466 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> executeQuery: (from 127.0.0.1:44236, user: aston) select jz_id, zddm, zdmc, max(zd.weight) as weight from zhenduan zd prewhere (jz_id, rybh, sjfq) in ( select distinct jz_id, rybh, sjfq from tp_find_user1 ) group by jz_id, zddm, zdmc order by jz_id, weight desc; (stage: Complete)
[71b182c921d1] 2023.08.08 13:04:36.660142 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_changzhou (e9914ba2-eb1b-41f2-9207-e616c5b4df9b) (SelectExecutor): Key condition: unknown
[71b182c921d1] 2023.08.08 13:04:36.660355 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_changzhou (e9914ba2-eb1b-41f2-9207-e616c5b4df9b) (SelectExecutor): Selected 2/2 parts by partition key, 2 parts by primary key, 16016/16016 marks by primary key, 16016 marks to read from 2 ranges
[71b182c921d1] 2023.08.08 13:04:36.660425 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> MergeTreeReadPool: min_marks_for_concurrent_read=24
[71b182c921d1] 2023.08.08 13:04:36.660464 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_changzhou (e9914ba2-eb1b-41f2-9207-e616c5b4df9b) (SelectExecutor): Reading approx. 130014500 rows with 24 streams
[71b182c921d1] 2023.08.08 13:04:36.660836 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_nanjing (300694cd-d39b-4d1f-b0f1-9365d1565a62) (SelectExecutor): Key condition: unknown
[71b182c921d1] 2023.08.08 13:04:36.661129 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_nanjing (300694cd-d39b-4d1f-b0f1-9365d1565a62) (SelectExecutor): Selected 3/3 parts by partition key, 3 parts by primary key, 50452/50452 marks by primary key, 50452 marks to read from 3 ranges
[71b182c921d1] 2023.08.08 13:04:36.661209 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> MergeTreeReadPool: min_marks_for_concurrent_read=24
[71b182c921d1] 2023.08.08 13:04:36.661256 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_nanjing (300694cd-d39b-4d1f-b0f1-9365d1565a62) (SelectExecutor): Reading approx. 401331374 rows with 24 streams
[71b182c921d1] 2023.08.08 13:04:36.661619 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_suzhou (80edf077-64a3-43a3-851f-9cbe189244e0) (SelectExecutor): Key condition: unknown
[71b182c921d1] 2023.08.08 13:04:36.661819 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_suzhou (80edf077-64a3-43a3-851f-9cbe189244e0) (SelectExecutor): Selected 2/2 parts by partition key, 2 parts by primary key, 27805/27805 marks by primary key, 27805 marks to read from 2 ranges
[71b182c921d1] 2023.08.08 13:04:36.661880 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> MergeTreeReadPool: min_marks_for_concurrent_read=24
[71b182c921d1] 2023.08.08 13:04:36.661923 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_suzhou (80edf077-64a3-43a3-851f-9cbe189244e0) (SelectExecutor): Reading approx. 224964492 rows with 24 streams
[71b182c921d1] 2023.08.08 13:04:36.662314 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_wuxi (0811cc18-4d76-49aa-9a52-bfcddb9a7f8d) (SelectExecutor): Key condition: unknown
[71b182c921d1] 2023.08.08 13:04:36.662446 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_wuxi (0811cc18-4d76-49aa-9a52-bfcddb9a7f8d) (SelectExecutor): Selected 5/5 parts by partition key, 5 parts by primary key, 24842/24842 marks by primary key, 24842 marks to read from 5 ranges
[71b182c921d1] 2023.08.08 13:04:36.662527 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> MergeTreeReadPool: min_marks_for_concurrent_read=24
[71b182c921d1] 2023.08.08 13:04:36.662566 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> fk_jiangsu.zhenduan_wuxi (0811cc18-4d76-49aa-9a52-bfcddb9a7f8d) (SelectExecutor): Reading approx. 202925119 rows with 24 streams
[71b182c921d1] 2023.08.08 13:04:36.664125 [ 337 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> CreatingSetsTransform: Created Set with 100 entries from 100 rows in 8.696e-06 sec.
[71b182c921d1] 2023.08.08 13:04:41.017005 [ 301 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> MergingSortedTransform: Merge sorted 2 blocks, 101 rows in 4.351974027 sec., 23.207859094146198 rows/sec., 2.73 KiB/sec
...
[71b182c921d1] 2023.08.08 13:04:41.017811 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> executeQuery: Read 959235585 rows, 56.62 GiB in 4.358404 sec., 220088726.28604415 rows/sec., 12.99 GiB/sec.
[71b182c921d1] 2023.08.08 13:04:41.019751 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> MemoryTracker: Peak memory usage (for query): 100.12 MiB.
[71b182c921d1] 2023.08.08 13:04:41.019756 [ 31 ] {1b63122f-6634-4f0d-ba91-b42568facd90} <Debug> TCPHandler: Processed in 4.360485727 sec.

101 rows in set. Elapsed: 4.359 sec. Processed 959.24 million rows, 60.79 GB (220.08 million rows/s., 13.95 GB/s.)
```
it seems that key conditions not figout in Select_Executor on version 23.7.3. so all rows have to be read, which makes query slows down.

**Comment by nickitat** [comment] 2023-08-08 12:42
looks like problem with `merge` engine.

23.5.4.25
https://fiddle.clickhouse.com/883a0551-415e-4965-a062-4423a16419f7

latest
https://fiddle.clickhouse.com/737c3507-2ae4-411d-826b-c0fc7c4f392b

**Comment by nickitat** [comment] 2023-08-08 12:57
@whitemay just to double-check, have you seen this problems with tables of other engine (not `merge`)?

**Comment by SaltTan** [comment] 2023-08-08 21:17
It seems there are several cases when CreatingSetsTransform runs after the PK analysis and the 'Key condition' is 'unknown' in such cases.
This happens with the Merge engine and also if the data type of the PK column does not match the subquery column (which did not work at all in 23.4).
https://fiddle.clickhouse.com/e5dca0e4-ea80-4fdc-81d8-34e9dfe7f7e8

**Comment by whitemay** [comment] 2023-08-09 00:17
@nicktat I checked. It seems really a problem only with merge engine.

**Comment by nickitat** [comment] 2023-08-09 11:38
got it, thanks. if you need a workaround right now you may consider replacing `merge` table with a view that does `select * from t1 union all select * from t2 ...`.

**Comment by nickitat** [comment] 2023-08-18 19:01
this pr #51455 introduced the problem

**Comment by nickitat** [comment] 2023-08-18 22:48
first three commits are enough to see the issue.
cc @KochetovNicolai

**Comment by nickitat** [comment] 2023-09-15 19:35
the reason is that `ReadFromMerge::applyFilters` does nothing currently. if I unconditionally would build sets here - problem will be fixed. now trying to figure out how to fix properly. maybe build child plans here and manually call `applyFilters` at this point.

**Closed** 2023-11-09 13:52 UTC
Labels: performance, v23.6-affected, v23.8-affected

**Comment by whitemay** [comment] 2023-11-27 06:05
23.10.5 still had this issue.
