### ISSUE TITLE
Usability issue if there is data represented by whitespaces after FORMAT and the `input()` table function

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#16652] opened 2020-11-04 01:05 UTC
```
clickhouse-client --query "select 'aa', 'bb' format TSV" | clickhouse-client --query "                      
       drop table if exists t;
       create table t(a text) engine Log;
       insert into t select b from input('a text, b text') format TSV
    "

Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected '\t' at end of stream.: (at row 1)
Buffer has gone, cannot extract information about what has been parsed., Stack trace (when copying this message, always include the lines below):

0. /home/akuzm/ch4/ch/contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x109032c0 in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
1. /home/akuzm/ch4/ch/src/Common/Exception.cpp:38: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x786807d in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
2. /home/akuzm/ch4/ch/src/IO/ReadHelpers.cpp:99: DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) (.cold) @ 0x78aadc5 in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
3. /home/akuzm/ch4/ch/src/IO/ReadHelpers.h:184: DB::TabSeparatedRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0xe1a2587 in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
4. /home/akuzm/ch4/ch/src/Processors/Formats/IRowInputFormat.cpp:64: DB::IRowInputFormat::generate() @ 0xe0805d1 in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
5. /home/akuzm/ch4/ch/contrib/libcxx/include/vector:1003: DB::ISource::work() @ 0xdff4f6b in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
6. /home/akuzm/ch4/ch/src/Processors/Formats/InputStreamFromInputFormat.h:49: DB::InputStreamFromInputFormat::readImpl() @ 0xdfb87bd in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
7. /home/akuzm/ch4/ch/contrib/libcxx/include/vector:1003: DB::IBlockInputStream::read() @ 0xd10785d in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
8. /home/akuzm/ch4/ch/contrib/libcxx/include/vector:1003: DB::ParallelParsingBlockInputStream::parserThreadFunction(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long) @ 0xdfbcc40 in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
9. /home/akuzm/ch4/ch/contrib/libcxx/include/memory:4206: std::__1::__function::__func<DB::ParallelParsingBlockInputStream::scheduleParserThreadForUnitWithNumber(unsigned long)::'lambda'(), std::__1::allocator<DB::ParallelParsingBlockInputStream::scheduleParserThreadForUnitWithNumber(unsigned long)::'lambda'()>, void ()>::operator()() @ 0xdfbd8c4 in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
10. /home/akuzm/ch4/ch/contrib/libcxx/include/functional:1853: ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x7896437 in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
11. /home/akuzm/ch4/ch/src/Common/ThreadPool.h:177: ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x7896c3e in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
12. /home/akuzm/ch4/ch/contrib/libcxx/include/functional:1853: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7895907 in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
13. /home/akuzm/ch4/ch/contrib/libcxx/include/memory:2615: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0x7893ea3 in /home/akuzm/ch4/build-gcc9-rel/programs/clickhouse
14. start_thread @ 0x9609 in /lib/x86_64-linux-gnu/libpthread-2.31.so
15. /build/glibc-ZN95T4/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97: __GI___clone @ 0x122293 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.31.so
 (version 20.11.1.1)
Error on processing query: insert into t select b from input('a text, b text') format TSV
```

What??? 

This one works as expected:

```
clickhouse-client --query "select 'aa', 'bb' format TSV" | clickhouse-client --query "                      
       drop table if exists t;
       create table t(a text) engine Log;
       insert into t select b from input('a text, b text') format TSV"
```

Apparenty the reason is that the empty line after `format TSV` is treated as the input, despite me specifying explicitly that I want to use the standard input.

**Comment by Avogar** [comment] 2023-06-05 20:28
It won't be fixed. The problem is that all data after `\n` after format is parsed as data. In the example we have spaces after `\n`. Just skip/don't allow any data after format is not possible, because when we send query with `input` over http, we just append data from stdin to the query and parse it from it.

**Closed by Avogar** 2023-06-05 20:28 UTC
Labels: duplicate, unexpected behaviour
