### ISSUE TITLE
abort in 00041_aggregating_materialized_view.sql (stress test)

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#37439] opened 2022-05-23 09:43 UTC
https://s3.amazonaws.com/clickhouse-test-reports/37426/fcd317a64264b690cedea6697194d0fa1378abdc/stress_test__undefined__actions_.html
```
2022.05.22 16:17:39.019438 [ 625 ] {} <Trace> BaseDaemon: Received signal 6
2022.05.22 16:17:39.189077 [ 22887 ] {} <Fatal> BaseDaemon: ########################################
2022.05.22 16:17:39.205257 [ 22887 ] {} <Fatal> BaseDaemon: (version 22.6.1.1, build id: 024D73CD25683D8F) (from thread 1756) (query_id: e4b4126e-ad91-4e76-bd64-ac1fe271f85c) (query: INSERT INTO test.visits_null
2022.05.22 16:17:39.224999 [ 22887 ] {} <Fatal> BaseDaemon:
2022.05.22 16:17:39.241364 [ 22887 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f4ad999803b 0x7f4ad9977859 0xfa7a260 0xfa7a562 0x2201a4c4 0x2201821c 0x22177db3 0x22197289 0x2310b531 0x235a309d 0x2359fcaa 0x24550418 0x2456d436 0x2640f1cc 0x2640f6a5 0x2658d1e7 0x2658aacc 0x7f4ad9b4f609 0x7f4ad9a74163
2022.05.22 16:17:39.253480 [ 22887 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x7f4ad999803b in ?
2022.05.22 16:17:39.257395 [ 22887 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7f4ad9977859 in ?
2022.05.22 16:17:39.356510 [ 22887 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/Exception.cpp:48: DB::handle_error_code(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool, std::__1::vector<void*, std::__1::allocator<void*> > const&) @ 0xfa7a260 in /usr/bin/clickhouse
2022.05.22 16:17:39.398564 [ 22887 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/Exception.cpp:0: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xfa7a562 in /usr/bin/clickhouse
2022.05.22 16:17:39.555734 [ 22887 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Core/Block.cpp:35: void DB::onError<void>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2201a4c4 in /usr/bin/clickhouse
2022.05.22 16:17:39.845361 [ 22887 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Core/Block.cpp:0: void DB::checkBlockStructure<void>(DB::Block const&, DB::Block const&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, bool) @ 0x2201821c in /usr/bin/clickhouse
2022.05.22 16:17:39.987028 [ 22887 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/QueryPipeline/Pipe.cpp:0: DB::Pipe::addChains(std::__1::vector<DB::Chain, std::__1::allocator<DB::Chain> >) @ 0x22177db3 in /usr/bin/clickhouse
2022.05.22 16:17:40.005863 [ 22887 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/QueryPipeline/QueryPipelineBuilder.cpp:0: DB::QueryPipelineBuilder::addChains(std::__1::vector<DB::Chain, std::__1::allocator<DB::Chain> >) @ 0x22197289 in /usr/bin/clickhouse
2022.05.22 16:17:40.032851 [ 22887 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Interpreters/InterpreterInsertQuery.cpp:0: DB::InterpreterInsertQuery::execute() @ 0x2310b531 in /usr/bin/clickhouse
2022.05.22 16:17:40.081533 [ 22887 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x235a309d in /usr/bin/clickhouse
2022.05.22 16:17:40.240850 [ 22887 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Interpreters/executeQuery.cpp:1068: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x2359fcaa in /usr/bin/clickhouse
2022.05.22 16:17:40.307051 [ 22887 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../src/Server/TCPHandler.cpp:332: DB::TCPHandler::runImpl() @ 0x24550418 in /usr/bin/clickhouse
2022.05.22 16:17:40.674966 [ 22887 ] {} <Fatal> BaseDaemon: 15. ./build_docker/../src/Server/TCPHandler.cpp:1783: DB::TCPHandler::run() @ 0x2456d436 in /usr/bin/clickhouse
2022.05.22 16:17:40.683672 [ 22887 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x2640f1cc in /usr/bin/clickhouse
2022.05.22 16:17:40.703748 [ 22887 ] {} <Fatal> BaseDaemon: 17.1. inlined from ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:54: std::__1::default_delete<Poco::Net::TCPServerConnection>::operator()(Poco::Net::TCPServerConnection*) const
2022.05.22 16:17:40.705390 [ 22887 ] {} <Fatal> BaseDaemon: 17.2. inlined from ../contrib/libcxx/include/__memory/unique_ptr.h:315: std::__1::unique_ptr<Poco::Net::TCPServerConnection, std::__1::default_delete<Poco::Net::TCPServerConnection> >::reset(Poco::Net::TCPServerConnection*)
2022.05.22 16:17:40.717056 [ 22887 ] {} <Fatal> BaseDaemon: 17.3. inlined from ../contrib/libcxx/include/__memory/unique_ptr.h:269: ~unique_ptr
2022.05.22 16:17:40.723347 [ 22887 ] {} <Fatal> BaseDaemon: 17. ../contrib/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x2640f6a5 in /usr/bin/clickhouse
2022.05.22 16:17:40.734002 [ 22887 ] {} <Fatal> BaseDaemon: 18. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x2658d1e7 in /usr/bin/clickhouse
2022.05.22 16:17:40.743423 [ 22887 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
2022.05.22 16:17:40.744538 [ 22887 ] {} <Fatal> BaseDaemon: 19.2. inlined from ../contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
2022.05.22 16:17:40.749388 [ 22887 ] {} <Fatal> BaseDaemon: 19. ../contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x2658aacc in /usr/bin/clickhouse
2022.05.22 16:17:40.750338 [ 22887 ] {} <Fatal> BaseDaemon: 20. ? @ 0x7f4ad9b4f609 in ?
2022.05.22 16:17:40.750658 [ 22887 ] {} <Fatal> BaseDaemon: 21. clone @ 0x7f4ad9a74163 in ?
2022.05.22 16:17:41.425042 [ 22887 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 97EEEDF3E78E7A5E80F55F949FE3CAC4. There is no information about the reference checksum.
```

**Comment by tavplubix** [comment] 2022-05-23 10:46
Duplicate of  #35902

**Closed by tavplubix** 2022-05-23 10:46 UTC
Labels: testing
