### ISSUE TITLE
Error " Invalid number of rows in Chunk column" in MaterializedPostgreSQLConsumer

### ISSUE THREAD

**Issue by bykof** [ClickHouse/ClickHouse#44453] opened 2022-12-20 18:08 UTC
**Describe what's wrong**

I am connected to a database via MaterializedPostgreSQLConsumer and every time something changes in the Postgres database, Clickhouse tries to sync data from the Postgres Database, it fails and does not sync rest data anymore.
Therefore I always have to remove the clickhouse_data directory, restart the container, init the databases again, so that Clickhouse syncs everything properly again. 

**Does it reproduce on recent release?**

yes

**How to reproduce**

* Version: 22.9.7.34-alpine docker image
* Connecting to database tables via: 

```
SET allow_experimental_database_materialized_postgresql=1;

CREATE DATABASE IF NOT EXISTS database1
ENGINE = MaterializedPostgreSQL('0.0.0.0', 'first', 'first', '')
SETTINGS materialized_postgresql_tables_list = 'table1,table2,....,tableN';

CREATE DATABASE IF NOT EXISTS database2
ENGINE = MaterializedPostgreSQL('0.0.0.0', 'second', 'second', '')
SETTINGS materialized_postgresql_tables_list = 'table1,table2,....,tableN';

CREATE DATABASE IF NOT EXISTS database3
ENGINE = MaterializedPostgreSQL('0.0.0.0', 'third', 'third', '')
SETTINGS materialized_postgresql_tables_list = 'table1,table2,....,tableN';
```

**Expected behavior**

Clickhouse syncs the data without problems.

**Error message and/or stacktrace**

```
2022.12.20 15:24:00.672780 [ 213 ] {} <Error> void DB::MaterializedPostgreSQLConsumer::syncTables(): Code: 49. DB::Exception: Invalid number of rows in Chunk column Nullable(String) position 2: expected 96, got 84. (LOGICAL_ERROR)
, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0xd1f0f3a in /usr/bin/clickhouse
1. ? @ 0x80b1a4d in /usr/bin/clickhouse
2. DB::Chunk::checkNumRowsIsConsistent() @ 0x13ce0323 in /usr/bin/clickhouse
3. DB::MaterializedPostgreSQLConsumer::syncTables() @ 0x123f20b2 in /usr/bin/clickhouse
4. DB::MaterializedPostgreSQLConsumer::readFromReplicationSlot() @ 0x123f3999 in /usr/bin/clickhouse
5. DB::MaterializedPostgreSQLConsumer::consume(std::__1::vector<std::__1::pair<int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<int, std::__1::basic_str
ing<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>&) @ 0x123f42f9 in /usr/bin/clickhouse
6. DB::PostgreSQLReplicationHandler::consumerFunc() @ 0x123d80e5 in /usr/bin/clickhouse
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x11dffcc1 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePool::threadFunction() @ 0x11e0328a in /usr/bin/clickhouse
9. ? @ 0x11e041ac in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xd2b9eaa in /usr/bin/clickhouse
11. ? @ 0xd2bef41 in /usr/bin/clickhouse
12. ? @ 0x7feec4263609 in ?
13. clone @ 0x7feec4188133 in ?
 (version 22.13.1.242 (official build))
```

**Comment by ricardovj** [comment] 2023-08-04 16:39
I have the same issue. What is strange is that _some_ data is sync'ed properly, while some rows remain unupdated after a postgres update, leaving my clickhouse data partially sync'ed. My table has a `jsonb` field and I wonder if this is causing the problems due to TOAST.

```
2023.07.20 13:36:04.659055 [ 239734 ] {} <Warning> PostgreSQLReplicaConsumer(slangapp.user_activities): Got TOAST value, which is not supported, default value will be used instead.
2023.07.20 13:36:04.669610 [ 239681 ] {} <Error> void DB::MaterializedPostgreSQLConsumer::syncTables(): Code: 49. DB::Exception: Invalid number of rows in Chunk column String position 9: expected 6, got 5. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xb9fcc64 in /usr/bin/clickhouse
1. ? @ 0x80851a8 in /usr/bin/clickhouse
2. DB::Chunk::checkNumRowsIsConsistent() @ 0x1107d678 in /usr/bin/clickhouse
3. DB::MaterializedPostgreSQLConsumer::syncTables() @ 0xfadde20 in /usr/bin/clickhouse
4. DB::MaterializedPostgreSQLConsumer::consume() @ 0xfadf48c in /usr/bin/clickhouse
5. DB::PostgreSQLReplicationHandler::consumerFunc() @ 0xfacd02c in /usr/bin/clickhouse
6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xf5520b4 in /usr/bin/clickhouse
7. DB::BackgroundSchedulePool::threadFunction() @ 0xf554adc in /usr/bin/clickhouse
8. ? @ 0xf555858 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xbab1cd0 in /usr/bin/clickhouse
10. ? @ 0xbab6bc8 in /usr/bin/clickhouse
11. ? @ 0x7d5c8 in /usr/lib/aarch64-linux-gnu/libc.so.6
12. ? @ 0xe5d1c in /usr/lib/aarch64-linux-gnu/libc.so.6
 (version 23.2.3.17 (official build))
```

At the same times I see these entries in my AWS RDS:

```
2023-07-20 13:36:04 UTC:10.0.11.237(36098):slangapp@slangapp:[20255]:STATEMENT:  SELECT end_lsn FROM pg_replication_slot_advance('slangapp_users_ch_replication_slot', '127F7/EA8CE8D8')                      
2023-07-20 13:36:04 UTC:10.0.11.237(36098):slangapp@slangapp:[20248]:FATAL:  out of relcache_callback_list slots     
```

**Comment by kssenii** [comment] 2023-10-12 11:18
Should be fixed by https://github.com/ClickHouse/ClickHouse/pull/54844 and https://github.com/ClickHouse/ClickHouse/pull/55297. Currently the fix is available in master, but will also be available for previous releases after next patch release is made.

Please reopen the issue if the issue still reproduces on the server version with the fix.

**Closed by kssenii** 2023-10-12 11:18 UTC
Labels: experimental issue
