### ISSUE TITLE
Support CAST()ing strings into Nullable(Enum) and Nullable(Array(Enum))

### ISSUE THREAD

**Issue by depressed-pho** [ClickHouse/ClickHouse#12451] opened 2020-07-13 05:02 UTC
**Use case**

We want to import a CSV file which may contain malformed column values
(like non-numeric characters in an Int32 column). While doing that we
want to skip invalid rows and continue inserting valid rows, and also
gather information about rows that have been skipped (such as line
numbers).

If we directly use the regular INSERT statement for inserting data,
the entire statement fails once it encounters an erroneous row. So we
tried inserting them as String into a temporary table, and copying
only valid rows to the final table.

To filter valid rows we tried doing something like `CAST(x, 'Nullable(Int32)')`,
but it turned out the following two cases throw
exceptions as opposed to returning NULL values:

1. SELECT cast('CCC', 'Nullable(Enum(\'AAA\'=1,\'BBB\'=2))')
2. SELECT cast('[\'AAA\',\'BBB\']', 'Nullable(Array(Enum(\'AAA\'=1,\'BBB\'=2)))')

**Describe the solution you'd like**

For (1) returning NULL would be the expected behavior.

For (2) `Nullable(Array(X))` being prohibited (#1062) is the source of
the problem. The most intuitive solution would be to allow `CAST(x,
'Nullable(Array(Enum(...)))')`
and return `NULL` when the conversion fails.

**Describe alternatives you've considered**

Adding another function ``tryCast(value, type)`` which is like
``cast()`` but has a special case on ``tryCast(x, 'Array(...)')``. In
case of error it returns an empty array if the destination type is
`Array(...)`, but for any other types it returns `NULL`.

**Comment by azat** [comment] 2020-07-23 21:37
Looks like a duplicate of #5818

**Comment by azat** [comment] 2020-07-23 21:49
FWIW as a workaround `multiIf` can be used:

```sql
WITH 'CCC' AS value_
SELECT CAST(multiIf(value_ = 'AAA', 1, value_ = 'BBB', 2, NULL), 'Nullable(Enum(\'AAA\'=1,\'BBB\'=2))')
```

instead of

```sql
SELECT cast('CCC', 'Nullable(Enum('AAA'=1,'BBB'=2))')
```

**Closed** 2020-07-29 17:23 UTC
Labels: feature
