### ISSUE TITLE
s3 reports non-informative errors and does unnecessary retries

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#36764] opened 2022-04-28 19:17 UTC
OK
```sql
select _path, _file, count() from s3('https://s3.us-east-1.amazonaws.com/test/numbers.tsv', 
'xxx', 'xxxx', 'TSV', 'A String') group by  _path, _file;

DB::Exception: Unable to parse ExceptionName: PermanentRedirect Message: 
The bucket you are attempting to access must be addressed using the specified endpoint. 
Please send all future requests to this endpoint.: 
While executing ParallelParsingBlockInputFormat: While executing S3. (S3_ERROR)
```

Not OK

```sql
select _path, _file, count() from s3('https://s3.us-east-1.amazonaws.com/test/numbers.tsv', 
'xxx', 'xxxx', 'Parquet', 'A String') group by  _path, _file;

DB::Exception: Cannot find out size of file: 
While executing ParquetBlockInputFormat: While executing S3. (UNKNOWN_FILE_SIZE)


select _path, _file, count() from s3('https://storage.googleapis.com/qqq/aaa', 
'xxx', 'xxxx', 'TSV', 'A String') group by  _path, _file;

DB::Exception: The request signature we calculated does not match the signature you provided. 
Check your Google secret key and signing method.


select _path, _file, count() from s3('https://storage.googleapis.com/qqq/aaa', 
'xxx', 'xxxx', 'Parquet', 'A String') group by  _path, _file;

DB::Exception: Cannot find out size of file: 
While executing ParquetBlockInputFormat: While executing S3. (UNKNOWN_FILE_SIZE)
```

**Comment by tavplubix** [comment] 2022-05-02 12:57
> DB::Exception: Cannot find out size of file

Looks related to #30936. It would be better to return error message from `S3::getObjectSize`/`ReadWriteBufferFromHTTPBase::getFileSize` to `getFileSizeFromReadBuffer`, cc: @kssenii.

> DB::Exception: The request signature we calculated does not match the signature you provided. 
> Check your Google secret key and signing method.

What's wrong with this error? Looks like the text is returned from Google API:
https://github.com/ClickHouse/ClickHouse/blob/4a5e4274f03f4d320b9e3d0c6315b38084255c8e/src/IO/ReadBufferFromS3.cpp#L307

Also I noticed that `ReadBufferFromS3` retries even when it gets non-retriable error like 403: https://gist.github.com/tavplubix/51c775d3c2acc74c6948d3873eafd7b8
It should not work this way.
cc: @excitoon

**Comment by alexey-milovidov** [comment] 2024-01-28 19:26
No reproducible example. Closing.

**Closed by alexey-milovidov** 2024-01-28 19:26 UTC
Labels: unexpected behaviour, comp-s3
