### ISSUE TITLE
[MaterializedPostgreSQL] how to hidden the secret column

### ISSUE THREAD

**Issue by Zkuns** [ClickHouse/ClickHouse#44701] opened 2022-12-29 06:54 UTC
Hi 
I use MaterializedPostgreSQL to sync the data from the PG database. I have a user table. The user's table has a phone and email column. I don't want it to show in clickhouse. Is there any way can do this?

I try to use the PG view. I create a view without the phone and email. But the view in PG does not have primary key. It will return this error.
```
DB::Exception: Table pgs.user_des has no primary key and no replica identity index. (BAD_ARGUMENTS)
```

I try to hide those columns by clickhouse policy. But I only found the row policy,  no the column policy.

**Comment by kssenii** [comment] 2022-12-29 12:10
Currently there is no such way. But it is not difficult to implement. There is already an issue for that: https://github.com/ClickHouse/ClickHouse/issues/33748. But this feature is not being implemented currently, and will not be done soon. If you would like to contribute and implement - would be cool :) I can help.

> I try to use the PG view. I create a view without the phone and email. But the view in PG does not have primary key. It will return this error.

yes, because this engine has a requirement that the table must have either primary key or a replica identity index.

I will close this issue as it is a duplicate of https://github.com/ClickHouse/ClickHouse/issues/33748.

**Closed by kssenii** 2022-12-29 12:10 UTC
Labels: question
