### ISSUE TITLE
Cannot cancel queries

### ISSUE THREAD

**Issue by daledude** [ClickHouse/ClickHouse#34397] opened 2022-02-08 00:35 UTC
Clickhouse server version: 21.8.13

Not sure if there is a config option or if this is a bug or, hopefully not, expected behaviour.

Running simple SELECT's using clickhouse-client takes a very long time to cancel after CTRL-C and `Cancelling query.` is output. Query continues to run to completion.

```
SELECT *
FROM journald_log
WHERE CONTAINER_ID = '9aed59e2301b'
LIMIT 1

Query id: 731d16bd-be9f-44fb-a4dc-7b9a39ec8ee4

^CCancelling query.
Ok.
Query was cancelled.

0 rows in set. Elapsed: 132.414 sec. Processed 11.23 thousand rows, 464.87 KB (84.82 rows/s., 3.51 KB/s.)
```

Did this 56 secs into query and about 40 seconds after I hit CTRL-C
```
Row 1:
──────
is_initial_query:     1
user:                 default
query_id:             731d16bd-be9f-44fb-a4dc-7b9a39ec8ee4
address:              ::ffff:127.0.0.1
port:                 51024
initial_user:         default
initial_query_id:     731d16bd-be9f-44fb-a4dc-7b9a39ec8ee4
initial_address:      ::ffff:127.0.0.1
initial_port:         51024
interface:            1
os_user:              root
client_hostname:      logserver4n1
client_name:          ClickHouse
client_revision:      54450
client_version_major: 21
client_version_minor: 11
client_version_patch: 4
http_method:          0
http_user_agent:
http_referer:
forwarded_for:
quota_key:
elapsed:              56.319998401
is_cancelled:         0
read_rows:            2240
read_bytes:           197017
total_rows_approx:    1641664746
written_rows:         0
written_bytes:        0
memory_usage:         17280588
peak_memory_usage:    17280588
query:                select * from journald_log where CONTAINER_ID='9aed59e2301b' limit 1;
thread_ids:           [257,82,110,149,87,157,155,167,90,106,100,124,164,83,85,60,112,156,150,165,155,150,161,165,87,164,164,87,87,164,167,165,165,165,85,150,150,150,161,112,112,112,112,112,155,149,149,149,149,149,149,149,149,149,149,149,98,81,196,103,77,168,61,206,64,84,63,89,88,121,114,190,104,62,66,158,68]
ProfileEvents:        {'Query':1,'SelectQuery':1,'FileOpen':919,'Seek':399,'ReadBufferFromFileDescriptorRead':918,'ReadBufferFromFileDescriptorReadBytes':24073456936,'ReadCompressedBytes':237824,'CompressedReadBufferBlocks':111,'CompressedReadBufferBytes':7379518,'IOBufferAllocs':1029,'IOBufferAllocBytes':25109527605,'FunctionExecute':11,'MarkCacheHits':112,'MarkCacheMisses':399,'CreatedReadBufferOrdinary':919,'DiskReadElapsedMicroseconds':650510984,'NetworkReceiveElapsedMicroseconds':4008,'NetworkSendElapsedMicroseconds':8140,'NetworkReceiveBytes':1,'NetworkSendBytes':3919,'SlowRead':5,'ReadBackoff':2,'SelectedParts':55,'SelectedRanges':2740,'SelectedMarks':51313035,'SelectedRows':2240,'SelectedBytes':197017,'ContextLock':171,'RWLockAcquiredReadLocks':1,'RealTimeMicroseconds':219953202,'UserTimeMicroseconds':47794306,'SystemTimeMicroseconds':5408055,'SoftPageFaults':1253972,'HardPageFaults':3,'OSIOWaitMicroseconds':164730000,'OSCPUWaitMicroseconds':838344,'OSCPUVirtualTimeMicroseconds':53202335,'OSReadBytes':2765012992,'OSWriteBytes':16384,'OSReadChars':3338966410,'OSWriteChars':49194,'QueryProfilerSignalOverruns':488}
Settings:             {'load_balancing':'random','max_memory_usage':'10000000000','send_logs_level':'debug'}
current_database:     logs

```

**Comment by HeenaBansal2009** [comment] 2022-02-09 15:37
I also observed this issue. When the query is cancelled and if we try to create a same user again, Clickhouse throwing "user already exist" error. This indicates CreateUserquery went to completion even after timeout & cancel.

**Comment by Algunenano** [comment] 2022-02-09 15:43
There have been several improvements in query cancelation and KILL'ing (they are 2 different things) in the last few releases. Can you test it with 22.1? Also, can you try (also with a recent version) to KILL instead of Ctrl+C and see if that works?

**Comment by HeenaBansal2009** [comment] 2022-02-09 15:52
> There have been several improvements in query cancelation and KILL'ing (they are 2 different things) in the last few releases. Can you test it with 22.1? Also, can you try (also with a recent version) to KILL instead of Ctrl+C and see if that works?
@Algunenano  , I am using ClickHouse client version 22.2.1.1. 
I didn't cancel/kill the query, Client received timeout to receive the response from server because I was debugging the clickhouse server and my server was paused on the gdb breakpoint. This is the scenario I observed.

**Comment by Algunenano** [comment] 2022-02-09 15:55
I was talking about the original issue, which has nothing to do with user creation. Sorry

**Comment by alexey-milovidov** [comment] 2022-02-09 18:16
I'm observing this issue with INSERT SELECT queries,
AFAIR @novikd started looking at it.

**Comment by alexey-milovidov** [comment] 2022-02-09 18:24
@daledude Please do the following:

1. Install version 22.1 across your cluster.
2. If the issue still reproduces, check this:

```
SET allow_introspection_functions = 1;
SELECT arrayJoin(arrayMap(x -> demangle(addressToSymbol(x)), trace)) FROM system.stack_trace WHERE query_id != '';
```
```

**Comment by alexey-milovidov** [comment] 2022-02-09 18:32
@daledude It can also happen if:
- your system is grind to halt (overloaded);
- you have faulty disks that continue to work but do it extremely slow;
- your table have very large records.

**Comment by filimonov** [comment] 2022-02-09 22:26
I observe that sometimes on wide tables (pre 22 versions) with queries like `SELECT *`. I thought it's just reading lot of marks / columns by several threads from different parts. And kill happen only when full block read.

**Comment by novikd** [comment] 2022-02-10 13:09
Stable reproduction case:
```
SELECT * FROM system.numbers WHERE sleepEachRow(0.05) LIMIT 10
```

**Comment by daledude** [comment] 2022-02-11 08:35
Upgraded to 22.1.3. Sorry for delay because I had to do this during a slow time. Query dies a bit faster but 40-50secs still seems to long. I used KILL. Added log of query in case it helps.

```
Row 1:
──────
is_initial_query:     1
user:                 default
query_id:             fd54c39c-b34b-4525-81f2-73e65798609e
address:              ::ffff:127.0.0.1
port:                 58564
initial_user:         default
initial_query_id:     fd54c39c-b34b-4525-81f2-73e65798609e
initial_address:      ::ffff:127.0.0.1
initial_port:         58564
interface:            1
os_user:
client_hostname:      logserver4n1
client_name:          ClickHouse
client_revision:      54450
client_version_major: 21
client_version_minor: 11
client_version_patch: 4
http_method:          0
http_user_agent:
http_referer:
forwarded_for:
quota_key:
elapsed:              41.326691246
is_cancelled:         1
read_rows:            4183083
read_bytes:           73766619
total_rows_approx:    601766113
written_rows:         0
written_bytes:        0
memory_usage:         5211719
peak_memory_usage:    5211719
query:                SELECT *
FROM journald_log
WHERE CONTAINER_ID = '9aed59e2301b'
LIMIT 1;
thread_ids:           [282,252,255,263,248,246,256,254,261,262,247,299,303,251,301,297,250,257,259,258,302,302,257,259,299,247,258,247,256,301,247,247,247,247,247,300,260,245,298,247,301,256,262,246,258,259,299,302,254,252,257,248,303,251,263,261]
ProfileEvents:        {'Query':1,'SelectQuery':1,'FileOpen':757,'Seek':15240,'ReadBufferFromFileDescriptorRead':15650,'ReadBufferFromFileDescriptorReadBytes':16131174746,'ReadCompressedBytes':1090634,'CompressedReadBufferBlocks':631,'CompressedReadBufferBytes':41481493,'OpenedFileCacheHits':489,'OpenedFileCacheMisses':757,'IOBufferAllocs':1263,'IOBufferAllocBytes':476817773,'FunctionExecute':7746,'MarkCacheHits':489,'MarkCacheMisses':378,'CreatedReadBufferOrdinary':1246,'DiskReadElapsedMicroseconds':175863707,'NetworkReceiveElapsedMicroseconds':346,'NetworkSendElapsedMicroseconds':3057,'NetworkSendBytes':1422,'SelectedParts':34,'SelectedRanges':2688,'SelectedMarks':18809030,'SelectedRows':4183083,'SelectedBytes':73766619,'ContextLock':158,'RWLockAcquiredReadLocks':1,'RealTimeMicroseconds':428335857,'UserTimeMicroseconds':24867195,'SystemTimeMicroseconds':9979483,'SoftPageFaults':2289666,'OSIOWaitMicroseconds':136110000,'OSCPUWaitMicroseconds':120833,'OSCPUVirtualTimeMicroseconds':34846644,'OSReadBytes':8509390848,'OSWriteBytes':4096,'OSReadChars':12506429282,'OSWriteChars':120863,'QueryProfilerSignalOverruns':2,'QueryProfilerRuns':694}
Settings:             {'load_balancing':'random','max_memory_usage':'10000000000'}
current_database:     logs
```
```
2022.02.11 08:28:51.080319 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Debug> executeQuery: (from [::ffff:127.0.0.1]:58564) SELECT * FROM journald_log WHERE CONTAINER_ID = '9aed59e2301b' LIMIT 1;
2022.02.11 08:28:51.081174 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "CONTAINER_ID = '9aed59e2301b'" moved to PREWHERE
2022.02.11 08:28:51.081784 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> ContextAccess (default): Access granted: SELECT(timestamp, message, host, PRIORITY, SYSLOG_IDENTIFIER, XEC_ID, XEC_ID_SHORT, CONTAINER_NAME, CONTAINER_ID, CONTAINER_ID_SHORT, CONTAINER_ID_FULL, CONTAINER_TAG, REGION, DATACENTER, PODMAN_TIME, PODMAN_ID, PODMAN_EVENT, PODMAN_TYPE, PODMAN_NAME, PODMAN_IMAGE, PODMAN_LABELS, NOMAD_ALLOC_ID, NOMAD_ALLOC_ID_SHORT, NOMAD_DC, NOMAD_REGION, NOMAD_JOB_NAME, NOMAD_GROUP_NAME, NOMAD_TASK_NAME, SERVICE_NAME, SERVICE_PORT, _PID, _UID, _GID, _SYSTEMD_UNIT, __MONOTONIC_TIMESTAMP, _SYSTEMD_INVOCATION_ID, _EXE, _COMM, _BOOT_ID, _CAP_EFFECTIVE, _CMDLINE, _SYSTEMD_CGROUP, _SYSTEMD_SLICE) ON logs.journald_log
2022.02.11 08:28:51.081996 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.02.11 08:28:51.082510 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Debug> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Key condition: (column 1 in ['9aed59e2301b', '9aed59e2301b'])
2022.02.11 08:28:51.082735 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Debug> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): MinMax index condition: unknown
2022.02.11 08:28:51.083105 [ 302 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_47855149_47855149_0 with 1 steps
2022.02.11 08:28:51.083125 [ 257 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part cae756435e12a4ce2634f54f910f2224_40480952_40480997_1 with 1 steps
2022.02.11 08:28:51.083998 [ 259 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part cae756435e12a4ce2634f54f910f2224_40480221_40480951_478 with 965 steps
2022.02.11 08:28:51.084550 [ 299 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_47854354_47855101_315 with 1616steps
2022.02.11 08:28:51.088284 [ 247 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_47850760_47854353_356 with 8713steps
2022.02.11 08:28:51.089266 [ 258 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part cae756435e12a4ce2634f54f910f2224_40475341_40480220_659 with 6599steps
2022.02.11 08:28:51.095449 [ 247 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49781100_49788675_526 with 12656 steps
2022.02.11 08:28:51.097757 [ 256 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_47843862_47850759_356 with 14825 steps
2022.02.11 08:28:51.103043 [ 301 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part cae756435e12a4ce2634f54f910f2224_40454264_40475340_728 with 22230 steps
2022.02.11 08:28:51.105517 [ 247 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49805686_49816817_423 with 17969 steps
2022.02.11 08:28:51.106480 [ 247 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49829920_49830709_344 with 1501steps
2022.02.11 08:28:51.106977 [ 247 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49830710_49831137_223 with 815 steps
2022.02.11 08:28:51.107039 [ 247 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49831138_49831143_1 with 1 steps
2022.02.11 08:28:51.107082 [ 247 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49831144_49831144_0 with 1 steps
2022.02.11 08:28:51.107124 [ 247 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49831145_49831145_0 with 1 steps
2022.02.11 08:28:51.107923 [ 262 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_47828524_47843861_531 with 28249 steps
2022.02.11 08:28:51.109541 [ 256 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49816818_49824823_446 with 14055 steps
2022.02.11 08:28:51.111051 [ 301 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49824824_49829919_437 with 9084steps
2022.02.11 08:28:51.111460 [ 258 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49788676_49805685_433 with 25055 steps
2022.02.11 08:28:51.176218 [ 248 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_47435077_47513306_502 with 143748 steps
2022.02.11 08:28:51.259833 [ 246 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_47513307_47625992_468 with 199030 steps
2022.02.11 08:28:51.278622 [ 299 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49620689_49781099_534 with 235365 steps
2022.02.11 08:28:51.278705 [ 259 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49445028_49620688_554 with 262715 steps
2022.02.11 08:28:51.283308 [ 302 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49091724_49239783_488 with 227319 steps
2022.02.11 08:28:51.375165 [ 254 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_47625993_47828523_528 with 463427 steps
2022.02.11 08:28:51.377606 [ 257 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_49239784_49445027_502 with 412473 steps
2022.02.11 08:28:51.431155 [ 261 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_46339664_46729585_1323 with 524744 steps
2022.02.11 08:28:51.789612 [ 255 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_45574931_46339663_1467 with 1200262 steps
2022.02.11 08:28:51.817249 [ 250 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_48439290_49091723_566 with 1166146 steps
2022.02.11 08:28:51.924257 [ 263 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_46729586_47435076_503 with 1329020 steps
2022.02.11 08:28:51.959193 [ 297 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part dd4b2127cfa507a1f259ae392e726364_47855102_48439289_417 with 1144005 steps
2022.02.11 08:28:54.781596 [ 251 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part cae756435e12a4ce2634f54f910f2224_31247028_35840958_753 with 6281482 steps
2022.02.11 08:28:55.006245 [ 252 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part 2d5d627b5f7997c4d035ed471dcd8e07_40480953_45574930_797 with 6626764 steps
2022.02.11 08:28:55.036101 [ 303 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Trace> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Used generic exclusion search over index for part cae756435e12a4ce2634f54f910f2224_35840959_40454263_829 with 6265572 steps
2022.02.11 08:28:55.038053 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Debug> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Selected 34/34 parts by partition key, 34 parts by primary key, 18809030/18814045 marks by primary key, 18809030 marks to read from 2688 ranges
2022.02.11 08:28:55.042633 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Debug> logs.journald_log (81ee16b7-d51b-4fc0-b387-c101fb5fc774) (SelectExecutor): Reading approx. 601766113 rows with 20 streams
2022.02.11 08:29:04.253803 [ 273 ] {7c0c56c3-6a5d-40e0-82b1-d6090e71a902} <Debug> executeQuery: (from [::ffff:127.0.0.1]:58586) kill query where query_id = 'fd54c39c-b34b-4525-81f2-73e65798609e';
2022.02.11 08:29:04.253970 [ 273 ] {7c0c56c3-6a5d-40e0-82b1-d6090e71a902} <Debug> executeQuery: (internal) SELECT query_id, user, query FROM system.processes WHERE query_id = 'fd54c39c-b34b-4525-81f2-73e65798609e'
2022.02.11 08:29:36.681908 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Error> executeQuery: Code: 394. DB::Exception: Query was cancelled. (QUERY_WAS_CANCELLED) (version 22.1.3.7 (official build)) (from [::ffff:127.0.0.1]:58564) (in query: SELECT * FROM journald_log WHERE CONTAINER_ID = '9aed59e2301b' LIMIT 1;), Stack trace (when copying this message, always include the lines below):
2022.02.11 08:29:36.689966 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Error> TCPHandler: Code: 394. DB::Exception: Query was cancelled. (QUERY_WAS_CANCELLED), Stack trace (when copying this message, always include the lines below):
2022.02.11 08:29:36.912626 [ 282 ] {fd54c39c-b34b-4525-81f2-73e65798609e} <Debug> MemoryTracker: Peak memory usage (for query): 4.97 MiB.
```

**Comment by novikd** [comment] 2022-02-11 18:30
@daledude Could you please share `journald_log` table schema with us? Does it contain LowCardinality?

**Comment by daledude** [comment] 2022-02-11 21:15
Thanks @novikd. I don't currently use LowCardinality.

```
CREATE TABLE logs.journald_log
(
    `timestamp` String,
    `message` String,
    `host` String,
    `PRIORITY` String,
    `SYSLOG_IDENTIFIER` String,
    `XEC_ID` String,
    `XEC_ID_SHORT` String,
    `CONTAINER_NAME` String,
    `CONTAINER_ID` String,
    `CONTAINER_ID_SHORT` String,
    `CONTAINER_ID_FULL` String,
    `CONTAINER_TAG` String,
    `REGION` String,
    `DATACENTER` String,
    `PODMAN_TIME` String,
    `PODMAN_ID` String,
    `PODMAN_EVENT` String,
    `PODMAN_TYPE` String,
    `PODMAN_NAME` String,
    `PODMAN_IMAGE` String,
    `PODMAN_LABELS` String,
    `NOMAD_ALLOC_ID` String,
    `NOMAD_ALLOC_ID_SHORT` String,
    `NOMAD_DC` String,
    `NOMAD_REGION` String,
    `NOMAD_JOB_NAME` String,
    `NOMAD_GROUP_NAME` String,
    `NOMAD_TASK_NAME` String,
    `SERVICE_NAME` String,
    `SERVICE_PORT` String,
    `_PID` UInt64,
    `_UID` UInt64,
    `_GID` UInt64,
    `_SYSTEMD_UNIT` String,
    `__MONOTONIC_TIMESTAMP` UInt64,
    `_SYSTEMD_INVOCATION_ID` String,
    `_EXE` String,
    `_COMM` String,
    `_BOOT_ID` String,
    `_CAP_EFFECTIVE` String,
    `_CMDLINE` String,
    `_SYSTEMD_CGROUP` String,
    `_SYSTEMD_SLICE` String
)
ENGINE = MergeTree
PARTITION BY substring(timestamp, 1, 7)
ORDER BY (timestamp, CONTAINER_ID)
SETTINGS index_granularity = 32
```

**Comment by hulb** [comment] 2023-01-09 03:43
> I'm observing this issue with INSERT SELECT queries

Any update on canceling `INSERT INTO xxx SELECT xx` queries? In my case, it seems this kind of query can't be canceled. I notice that there is information like ` <Information> TCPHandler: Query was cancelled.`  though.

**Comment by tbragin** [comment] 2024-05-25 17:15
Closing since question appears answered and per last comment `sleepEachRow()` function is fixed.

**Closed by tbragin** 2024-05-25 17:15 UTC
Labels: question
