### ISSUE TITLE
Valid query fails on Clickhouse parser

### ISSUE THREAD

**Issue by chickony** [ClickHouse/ClickHouse#23900] opened 2021-05-05 16:05 UTC
You have to provide the following information whenever possible.

**Describe the bug**
The following valid query fails on Clickhouse Playground.

`SELECT '2013-07-15' as  EventDate         
FROM `hits_100m_obfuscated` g
WHERE g.EventDate = '2013-07-15'
LIMIT 100;  `

**Does it reproduce on recent release?**
The issue reproduces on recent release

**How to reproduce**
* Which ClickHouse server version to use - 20.8
* Which interface to use, if matters - does not matter
* Non-default settings, if any -irrelevant

**Expected behavior**
The query should returns results, changing the alias name is a workaround

**Error message and/or stacktrace**
Code: 47, e.displayText() = DB::Exception: Unknown identifier: EventDate there are columns: IsEvent (version 20.8.17.25 (official build))

**Additional context**

**Comment by chickony** [comment] 2021-05-19 05:27
@alexey-milovidov 
Why have you marked it as Invalid?
I have just verified again now on latest docker and the following flow still fails

1-
`CREATE TABLE hits_100m_obfuscated (`WatchID` UInt64, `JavaEnable` UInt8, `Title` String, `GoodEvent` Int16, `EventTime` DateTime, `EventDate` Date, `CounterID` UInt32, `ClientIP` UInt32, `RegionID` UInt32, `UserID` UInt64, `CounterClass` Int8, `OS` UInt8, `UserAgent` UInt8, `URL` String, `Referer` String, `Refresh` UInt8, `RefererCategoryID` UInt16, `RefererRegionID` UInt32, `URLCategoryID` UInt16, `URLRegionID` UInt32, `ResolutionWidth` UInt16, `ResolutionHeight` UInt16, `ResolutionDepth` UInt8, `FlashMajor` UInt8, `FlashMinor` UInt8, `FlashMinor2` String, `NetMajor` UInt8, `NetMinor` UInt8, `UserAgentMajor` UInt16, `UserAgentMinor` FixedString(2), `CookieEnable` UInt8, `JavascriptEnable` UInt8, `IsMobile` UInt8, `MobilePhone` UInt8, `MobilePhoneModel` String, `Params` String, `IPNetworkID` UInt32, `TraficSourceID` Int8, `SearchEngineID` UInt16, `SearchPhrase` String, `AdvEngineID` UInt8, `IsArtifical` UInt8, `WindowClientWidth` UInt16, `WindowClientHeight` UInt16, `ClientTimeZone` Int16, `ClientEventTime` DateTime, `SilverlightVersion1` UInt8, `SilverlightVersion2` UInt8, `SilverlightVersion3` UInt32, `SilverlightVersion4` UInt16, `PageCharset` String, `CodeVersion` UInt32, `IsLink` UInt8, `IsDownload` UInt8, `IsNotBounce` UInt8, `FUniqID` UInt64, `OriginalURL` String, `HID` UInt32, `IsOldCounter` UInt8, `IsEvent` UInt8, `IsParameter` UInt8, `DontCountHits` UInt8, `WithHash` UInt8, `HitColor` FixedString(1), `LocalEventTime` DateTime, `Age` UInt8, `Sex` UInt8, `Income` UInt8, `Interests` UInt16, `Robotness` UInt8, `RemoteIP` UInt32, `WindowName` Int32, `OpenerName` Int32, `HistoryLength` Int16, `BrowserLanguage` FixedString(2), `BrowserCountry` FixedString(2), `SocialNetwork` String, `SocialAction` String, `HTTPError` UInt16, `SendTiming` UInt32, `DNSTiming` UInt32, `ConnectTiming` UInt32, `ResponseStartTiming` UInt32, `ResponseEndTiming` UInt32, `FetchTiming` UInt32, `SocialSourceNetworkID` UInt8, `SocialSourcePage` String, `ParamPrice` Int64, `ParamOrderID` String, `ParamCurrency` FixedString(3), `ParamCurrencyID` UInt16, `OpenstatServiceName` String, `OpenstatCampaignID` String, `OpenstatAdID` String, `OpenstatSourceID` String, `UTMSource` String, `UTMMedium` String, `UTMCampaign` String, `UTMContent` String, `UTMTerm` String, `FromTag` String, `HasGCLID` UInt8, `RefererHash` UInt64, `URLHash` UInt64, `CLID` UInt32) ENGINE = MergeTree() PARTITION BY toYYYYMM(EventDate) ORDER BY (CounterID, EventDate, intHash32(UserID), EventTime) SAMPLE BY intHash32(UserID) SETTINGS index_granularity_bytes = 1048576, index_granularity = 8192;`


2-
`SELECT '2013-07-15' as EventDate FROM hits_100m_obfuscated g WHERE g.EventDate = '2013-07-15'`

**Comment by alexey-milovidov** [comment] 2022-03-21 03:14
Minimal reproducing example:

```
SELECT 2 as test, t.test FROM (SELECT 1 AS test) t
```

**Comment by alexey-milovidov** [comment] 2022-03-21 03:14
Duplicate of #23194.

**Closed by alexey-milovidov** 2022-03-21 03:14 UTC
Labels: bug
