### ISSUE TITLE
Only in Rust: clickhouse-local panicked in _ch_rust_skim_rust with 'fd must be in the range 0..FD_SETSIZE'

### ISSUE THREAD

**Issue by markandrus** [ClickHouse/ClickHouse#59374] opened 2024-01-30 11:42 UTC
**Describe what's wrong**

I tried out 24.1 today on Linux. I was playing with clickhouse-local. I ran a command like `system start merges` (I think this part is irrelevant), and then when planning my next command I hit CTRL-R or CTRL-P (not sure). Anyway, clickhouse-local crashed with the following:

```
thread '<unnamed>' panicked at 'fd must be in the range 0..FD_SETSIZE', /rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.24.3/src/sys/select.rs:21:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'panic in ffi function _ch_rust_skim_rust::ffi::skim, aborting.', /rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/cxx-1.0.115/src/unwind.rs:37:9
stack backtrace:
   0:          0x6570747 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd7fc81831607cf60
   1:          0x63dec9f - core::fmt::write::h83c42ba3ca76c4aa
   2:          0x6539186 - std::io::Write::write_fmt::h2430223c04b84a0f
   3:          0x6571fdf - std::sys_common::backtrace::print::h8f55173e6a80d5ad
   4:          0x6571ba0 - std::panicking::default_hook::{{closure}}::heb93e2549b3b187f
   5:          0x6572c28 - std::panicking::rust_panic_with_hook::ha1753497d761687d
   6:          0x6572712 - std::panicking::begin_panic_handler::{{closure}}::h94f1c0e8e158230f
   7:          0x6572676 - std::sys_common::backtrace::__rust_end_short_backtrace::h8f0ed1c8ce3bb685
   8:          0x6572661 - rust_begin_unwind
   9:          0x63ddca2 - core::panicking::panic_fmt::hd946f96734ef59b2
  10:          0x63e7047 - <cxx::unwind::Guard as core::ops::drop::Drop>::drop::h52b06642e6e3c256
  11:          0x63a8466 - core::ptr::drop_in_place<cxx::unwind::Guard>::h051a2e65a414bc34
  12:          0x63a903e - cxxbridge1$skim
  13:          0x63a15bf - _Z4skimRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKNS_6vectorIS5_NS3_IS5_EEEE
  14:         0x12870260 - _ZNSt3__110__function16__policy_invokerIFN6replxx6Replxx13ACTION_RESULTEDiEE11__call_implINS0_20__default_alloc_funcIZN2DB16ReplxxLineReaderC1ERNS9_10LineReader7SuggestERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbNS_6vectorIPKcNSH_ISO_EEEESQ_SO_NS_8functionIFvSL_RNSM_INS3_5ColorENSH_ISS_EEEEEEEE4$_10S5_EEEES4_PKNS0_16__policy_storageEDi
  15:         0x154231a7 - _ZN6replxx6Replxx10ReplxxImpl5inputERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
  16:         0x1286e372 - _ZN2DB16ReplxxLineReader11readOneLineERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
  17:         0x128521fa - _ZN2DB10LineReader8readLineERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_
  18:         0x1280850d - _ZN2DB10ClientBase14runInteractiveEv
  19:          0xc99d92e - _ZN2DB11LocalServer4mainERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE
  20:         0x153b39e6 - _ZN4Poco4Util11Application3runEv
  21:          0xc9aa1cf - _Z24mainEntryClickHouseLocaliPPc
  22:          0x7218b18 - main
  23:     0x7fafb123feb0 - __libc_start_call_main
  24:     0x7fafb123ff60 - __libc_start_main_impl
  25:          0x5f6f22e - _start
thread '<unnamed>' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:          0x6570747 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd7fc81831607cf60
   1:          0x63dec9f - core::fmt::write::h83c42ba3ca76c4aa
   2:          0x6539186 - std::io::Write::write_fmt::h2430223c04b84a0f
   3:          0x6571fdf - std::sys_common::backtrace::print::h8f55173e6a80d5ad
   4:          0x6571ba0 - std::panicking::default_hook::{{closure}}::heb93e2549b3b187f
   5:          0x6572c28 - std::panicking::rust_panic_with_hook::ha1753497d761687d
   6:          0x65726e3 - std::panicking::begin_panic_handler::{{closure}}::h94f1c0e8e158230f
   7:          0x6572676 - std::sys_common::backtrace::__rust_end_short_backtrace::h8f0ed1c8ce3bb685
   8:          0x6572661 - rust_begin_unwind
   9:          0x63df7b9 - core::panicking::panic_nounwind_fmt::hbe93c0c47347e50a
  10:          0x63df82a - core::panicking::panic_nounwind::h94f11a0df883572b
  11:          0x63df7d6 - core::panicking::panic_cannot_unwind::h1fe7cdd7d177fad3
  12:          0x63a9045 - cxxbridge1$skim
  13:          0x63a15bf - _Z4skimRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKNS_6vectorIS5_NS3_IS5_EEEE
  14:         0x12870260 - _ZNSt3__110__function16__policy_invokerIFN6replxx6Replxx13ACTION_RESULTEDiEE11__call_implINS0_20__default_alloc_funcIZN2DB16ReplxxLineReaderC1ERNS9_10LineReader7SuggestERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbNS_6vectorIPKcNSH_ISO_EEEESQ_SO_NS_8functionIFvSL_RNSM_INS3_5ColorENSH_ISS_EEEEEEEE4$_10S5_EEEES4_PKNS0_16__policy_storageEDi
  15:         0x154231a7 - _ZN6replxx6Replxx10ReplxxImpl5inputERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
  16:         0x1286e372 - _ZN2DB16ReplxxLineReader11readOneLineERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
  17:         0x128521fa - _ZN2DB10LineReader8readLineERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_
  18:         0x1280850d - _ZN2DB10ClientBase14runInteractiveEv
  19:          0xc99d92e - _ZN2DB11LocalServer4mainERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE
  20:         0x153b39e6 - _ZN4Poco4Util11Application3runEv
  21:          0xc9aa1cf - _Z24mainEntryClickHouseLocaliPPc
  22:          0x7218b18 - main
  23:     0x7fafb123feb0 - __libc_start_call_main
  24:     0x7fafb123ff60 - __libc_start_main_impl
  25:          0x5f6f22e - _start
thread caused non-unwinding panic. aborting.
Aborted (core dumped)
```

**Comment by alexey-milovidov** [comment] 2024-01-30 11:54
@azat, Rust should throw an exception, not panic. It should not lead to a crash.
If it's not possible to make Rust not crash, we should remove it.

**Comment by alexey-milovidov** [comment] 2024-01-30 11:55
If it uses a "select" function from libc, it is a mistake, because the "select" function is obsolete.

**Comment by azat** [comment] 2024-01-31 21:32
> Rust should throw an exception, not abort. It should not lead to a crash.

It is not possible to fix **all** potential crashes in Rust, see https://github.com/ClickHouse/ClickHouse/issues/52053#issuecomment-1636776243

But we can do at least somehow better - https://github.com/ClickHouse/ClickHouse/pull/59447

**Comment by azat** [comment] 2024-01-31 22:05
Actually https://github.com/ClickHouse/ClickHouse/pull/59447 will not fix it, but just avoids crash, to fix it some reproducer is required

**Comment by alexey-milovidov** [comment] 2024-02-18 05:24
@azat, As long as it no longer crashes the application, closing.

**Closed by alexey-milovidov** 2024-02-18 05:24 UTC
Labels: help wanted, crash
