### ISSUE TITLE
Creating named tuples in the SQL query

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#63524] opened 2024-05-08 14:05 UTC
Right now you can create the tuple inline like 

```
tuple(name, surname, city, birthdate) as t
```

in some cases (with array processing, some aggregate functions etc.) it's exctremely handy. 

But later on you can access the tuple only by positional indexes (t.1 etc) which is not handy & error-prone (when you add new elements to the tuple it's easy to do the mistake). 

There is workaround using `cast`, but that requires from the query author to know / list all the column names twice, know the types etc. and looks really ugly:

```
CAST(tuple(name, surname, city, age), 'Tuple(name String, surname String, city LowCardinality(Sting), birthdate Nullable(Date))') as t
```

## Proposed solution 

```
WITH 
     named_tuple('name', name, 'surname', surname, 'city', city, 'birthdate', birthdate) as t -- names - only constant strings
SELECT 
    toTypeName(t), -- 'Tuple(name String, surname String, city LowCardinality(Sting), birthdate Nullable(Date))'
    tupleElement(t, 'name')
```

**Comment by UnamedRus** [comment] 2024-05-08 14:37
I think,

ClickHouse should be smart enough to deduct names from `tuple(name, surname, city, birthdate) as t`.

And if you want different names, just use `tuple(name as firstname, surname, city, birthdate) as t`

**Comment by alexey-milovidov** [comment] 2024-05-11 01:01
#54881

**Comment by alexey-milovidov** [comment] 2024-05-11 01:03
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/54921

**Closed by alexey-milovidov** 2024-05-11 01:03 UTC
Labels: duplicate, feature, st-in-progress
