### ISSUE TITLE
Segmentation violation in libunwind

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#53151] opened 2023-08-08 09:20 UTC
Version 23.7.3.1, program terminated with signal SIGSEGV, stack trace:

```
#0  0x000000001ba7caff in libunwind::DwarfInstructions<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::getSavedRegister (addressSpace=..., registers=..., cfa=139939689791504, savedReg=...) at ./contrib/libunwind/src/DwarfInstructions.hpp:111
#1  0x000000001ba7bd27 in libunwind::DwarfInstructions<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::stepWithDwarf (addressSpace=..., pc=<optimized out>, fdeStart=<optimized out>, registers=..., isSignalFrame=@0x7f95f357efb1: false)
    at ./contrib/libunwind/src/DwarfInstructions.hpp:265
#2  0x000000001ba7b75e in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::stepWithDwarfFDE (this=0x7f95f357eeb0) at ./contrib/libunwind/src/UnwindCursor.hpp:1002
#3  libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step (this=0x7f95f357eeb0) at ./contrib/libunwind/src/UnwindCursor.hpp:2818
#4  0x000000000f1d36a9 in unw_backtrace (buffer=0x7f95f357f0c8, size=45) at ./contrib/libunwind/src/libunwind.cpp:350
#5  StackTrace::tryCapture (this=0x7f95f357f0b8) at ./src/Common/StackTrace.cpp:286
#6  StackTrace::StackTrace (this=0x7f95f357f0b8, signal_context=...) at ./src/Common/StackTrace.cpp:258
#7  0x000000000f4568be in signalHandler (sig=<optimized out>, info=0x7f95f357f5b0, context=0x7f95f357f480) at ./src/Daemon/BaseDaemon.cpp:150
#8  <signal handler called>
#9  0x000000001ba7caff in libunwind::DwarfInstructions<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::getSavedRegister (addressSpace=..., registers=..., cfa=139939689791504, savedReg=...) at ./contrib/libunwind/src/DwarfInstructions.hpp:111
#10 0x000000001ba7bd27 in libunwind::DwarfInstructions<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::stepWithDwarf (addressSpace=..., pc=<optimized out>, fdeStart=<optimized out>, registers=..., isSignalFrame=@0x7f46b2107af1: false)
    at ./contrib/libunwind/src/DwarfInstructions.hpp:265
#11 0x000000001ba7b75e in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::stepWithDwarfFDE (this=0x7f46b21079f0) at ./contrib/libunwind/src/UnwindCursor.hpp:1002
#12 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step (this=0x7f46b21079f0) at ./contrib/libunwind/src/UnwindCursor.hpp:2818
#13 0x000000000f1d36a9 in unw_backtrace (buffer=0x7f46b2107b78, size=45) at ./contrib/libunwind/src/libunwind.cpp:350
#14 StackTrace::tryCapture (this=0x7f46b2107b68) at ./src/Common/StackTrace.cpp:286
#15 StackTrace::StackTrace (this=0x7f46b2107b68, signal_context=...) at ./src/Common/StackTrace.cpp:258
#16 0x000000000f1f7b6d in DB::(anonymous namespace)::writeTraceInfo (trace_type=DB::TraceType::CPU, info=<optimized out>, context=0x7f46b21080c0) at ./src/Common/QueryProfiler.cpp:74
#17 <signal handler called>
#18 0x0000000013e78826 in DB::transformTypesRecursively(std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > >&, std::__1::function<void (std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > >&, std::__1::unordered_set<DB::TypeIndex, std::__1::hash<DB::TypeIndex>, std::__1::equal_to<DB::TypeIndex>, std::__1::allocator<DB::TypeIndex> >&)>, std::__1::function<void (std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > >&, std::__1::unordered_set<DB::TypeIndex, std::__1::hash<DB::TypeIndex>, std::__1::equal_to<DB::TypeIndex>, std::__1::allocator<DB::TypeIndex> >&)>) (types=..., transform_simple_types=..., transform_complex_types=...) at ./src/DataTypes/transformTypesRecursively.cpp:164
#19 0x0000000013e7b551 in DB::callOnNestedSimpleTypes(std::__1::shared_ptr<DB::IDataType const>&, std::__1::function<void (std::__1::shared_ptr<DB::IDataType const>&)>) (type=..., callback=...) at ./src/DataTypes/transformTypesRecursively.cpp:169
#20 0x0000000015c1b1c9 in DB::setVersionToAggregateFunctions (revision=..., type=..., if_empty=<optimized out>) at ./src/DataTypes/DataTypeAggregateFunction.cpp:262
#21 DB::NativeWriter::write (this=0x7f95ce0f0b80, block=...) at ./src/Formats/NativeWriter.cpp:120
#22 0x0000000015be6980 in DB::TCPHandler::sendData (this=0x7f95f8652e00, block=...) at ./src/Server/TCPHandler.cpp:1925
#23 0x0000000015be3fd3 in DB::TCPHandler::processOrdinaryQueryWithProcessors (this=0x7f95f8652e00) at ./src/Server/TCPHandler.cpp:854
#24 0x0000000015bdaadd in DB::TCPHandler::runImpl (this=0x7f95f8652e00) at ./src/Server/TCPHandler.cpp:443
#25 0x0000000015bf1679 in DB::TCPHandler::run (this=0x7f46b2109998) at ./src/Server/TCPHandler.cpp:2049
#26 0x0000000018c2c2f4 in Poco::Net::TCPServerConnection::start (this=0x7f46b2109998) at ./base/poco/Net/src/TCPServerConnection.cpp:43
#27 0x0000000018c2d51b in Poco::Net::TCPServerDispatcher::run (this=0x7f978a88c100) at ./base/poco/Net/src/TCPServerDispatcher.cpp:115
#28 0x0000000018db7087 in Poco::PooledThread::run (this=0x7f95f878f380) at ./base/poco/Foundation/src/ThreadPool.cpp:188
#29 0x0000000018db4abd in Poco::ThreadImpl::runnableEntry (pThread=0x7f95f878f3b8) at ./base/poco/Foundation/src/Thread_POSIX.cpp:335
#30 0x00007f98ab054ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#31 0x00007f98aaf74a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Version 23.6 working w/o any issue.

**Comment by tavplubix** [comment] 2023-08-08 10:26
Looks like a duplicate of https://github.com/ClickHouse/ClickHouse/issues/33531

**Comment by MaxWk** [comment] 2023-08-08 16:03
same error in 21.3

**Comment by jorisgio** [comment] 2023-08-09 09:36
interestingly, we have two replicas cluster, which are mostly the same run the same load. But in only crash on one of the two clusters, not sure what is the difference. 
Same debian version, same clickhouse binary, same libc... 
Only two obvious difference is that : 
1. the one where it crashes is Zen 4 cpu, with linux 6.1
2. the one that does not crash is Zen 2 cpu, with linux 6.0
But i don't see how it would impact.

**Comment by alexey-milovidov** [comment] 2023-09-06 18:06
> it is a custom build of clickhouse

**Comment by tavplubix** [comment] 2023-09-06 18:07
@alexey-milovidov, we have exactly the same bug in official builds: https://github.com/ClickHouse/ClickHouse/issues/33531

**Closed** 2023-09-06 18:06 UTC
Labels: st-need-info, alternative build, potential bug
