### ISSUE TITLE
200% constant CPU usage while using RabbitMQ intergation on 23.2.4 revision 54461 (docker image)

### ISSUE THREAD

**Issue by vsavkin2018** [ClickHouse/ClickHouse#48103] opened 2023-03-28 11:28 UTC
I reproduce the problem as follows.

1. Start docker image (latest from here https://hub.docker.com/r/clickhouse/clickhouse-server)
docker run -d  --link rabbit1 --hostname clicktest1 clickhouse/clickhouse-server # rabbit1 is a real host with RabbitMQ
docker run -it --rm  --link clicktest1 yandex/clickhouse-client --host clicktest1 # connect with client

The client prints the following about version numbers:
_ClickHouse client version 22.1.3.7 (official build).
Connecting to clicktest1:9000 as user default.
Connected to ClickHouse server version 23.2.4 revision 54461._

2. Create test database and tables:

```
CREATE DATABASE test1;
USE test1;
CREATE TABLE rabbitmq_test ( `test` String ) ENGINE = RabbitMQ SETTINGS rabbitmq_host_port = 'rabbit1:5672', rabbitmq_username='guest', rabbitmq_password='guest',rabbitmq_exchange_name = 'pmacct', rabbitmq_routing_key_list = 'nonexistant', rabbitmq_format = 'JSONEachRow', rabbitmq_exchange_type = 'direct', rabbitmq_num_consumers = 1, rabbitmq_queue_settings_list = 'x-max-length=1048545,x-overflow=reject-publish', rabbitmq_max_block_size = 1024;
CREATE TABLE test_events ( `test` String ) ENGINE = MergeTree ORDER BY (test);
CREATE MATERIALIZED VIEW event_view TO test_events ( `test` String ) AS SELECT `test` FROM rabbitmq_test;
```

3. Immediately after that, I see CPU usage of the `clickhouse-server` process of about 200%, or when using `top` with thread info, two threads with `BgMBSchPool` name using each about 100% CPU. This is with no events, as I use nonexistant routing key. I see the same behavior with production data - it seems to work, but uses two 100% CPU threads for each rabbitmq queue.

Older version ( https://hub.docker.com/r/yandex/clickhouse-server latest) doesn't use any noticeable amount of CPU when there are no events,  so I guess it's a regression.

**Comment by rbeeli** [comment] 2023-04-01 00:24
I can confirm using the following schema on **23.2.4.12** bare metal installation: 

```sql
DROP TABLE IF EXISTS queue_rmq;
CREATE TABLE queue_rmq (
    key UInt64,
    value UInt64
) ENGINE = RabbitMQ
SETTINGS rabbitmq_host_port = 'localhost:5672',
         rabbitmq_exchange_type = 'topic',
         rabbitmq_exchange_name = 'test',
         rabbitmq_routing_key_list = '*',
         rabbitmq_format = 'JSONEachRow',
    	 rabbitmq_flush_interval_ms = 2000;

CREATE TABLE queue (
	key UInt64,
	value UInt64
)
ENGINE = MergeTree() ORDER BY key;


DROP VIEW IF EXISTS queue_MV;
CREATE MATERIALIZED VIEW queue_MV TO queue
AS
SELECT key, value FROM queue_rmq;
```

Deleting the table `queue_rmq` with the `RabbitMQ` engine immediately relieves the CPU load significantly. It looks like one RabbitMQ table fully consumes a core, which looks like a regression to me.

The exchange in RabbitMQ is a durable topic exchange.

**Comment by rbeeli** [comment] 2023-04-01 01:04
https://github.com/ClickHouse/ClickHouse/blob/a0c8d34775d3d1d9862270f707cf6df4a5ea45e5/src/Storages/RabbitMQ/RabbitMQSource.h#L30

Not sure whether related, but that line looks fishy given the naming.

Instead, shouldn't it be:
```cpp
bool queueEmpty() const { return !buffer || !buffer->hasPendingMessages(); }
```

Same here, flipped again:
https://github.com/ClickHouse/ClickHouse/blob/a0c8d34775d3d1d9862270f707cf6df4a5ea45e5/src/Storages/RabbitMQ/ReadBufferFromRabbitMQConsumer.h#L70

Name does not match the meaning, easy to introduce bugs IMO, unless I'm missing something.

**Comment by rbeeli** [comment] 2023-04-01 01:24
Version **22.9.7.34** seems to work correctly.

**Comment by kssenii** [comment] 2023-04-01 09:53
Fixed in https://github.com/ClickHouse/ClickHouse/pull/48311 (cpu usage was indeed worsened starting from 23.2 due to https://github.com/ClickHouse/ClickHouse/pull/44404). Will backport to the affected versions.

**Comment by rbeeli** [comment] 2023-04-01 15:37
Hi @kssenii 
Thanks for the quick reply. Is it possible to implement the waiting for new messages without the additional arbitrary sleep call? After all, the RabbitMQ consumer is real-time using callbacks, not? It's essentially a batched producer/consumer queue with batch size limit OR time limit?

**Comment by kssenii** [comment] 2023-04-01 16:44
@rbeeli, indeed, just did.

**Comment by rbeeli** [comment] 2023-04-02 00:28
@kssenii Magnificent, thank you!

**Comment by kssenii** [comment] 2023-04-04 14:22
> @kssenii Any idea how long it will take to merge and end up in a release? Thank you.

When I fix the one failing test, hopefully today will fix the test and merge today/tomorrow.

**Closed** 2023-04-07 09:44 UTC
Labels: bug, v23.2-affected, v23.3-affected
