### ISSUE TITLE
Flaky `02247_read_bools_as_numbers_json`

### ISSUE THREAD

**Issue by pamarcos** [ClickHouse/ClickHouse#66029] opened 2024-07-03 09:23 UTC
[It's failed a few times lately](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMjI0N19yZWFkX2Jvb2xzX2FzX251bWJlcnNfanNvbicgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIGNoZWNrX3N0YXJ0X3RpbWUsCiAgICBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHByLAogICAgcmVwb3J0X3VybCBhcyByZXBvcnRfdXJsLAogICAgdGVzdF9kdXJhdGlvbl9tcywKRlJPTSBjaGVja3MKV0hFUkUgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAocHVsbF9yZXF1ZXN0X251bWJlciBOT1QgSU4gKAogICAgU0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgQVMgcHJuCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgKHBybiAhPSAwKSBBTkQgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAoY2hlY2tfbmFtZSBJTiAoYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSkKKSkgQU5EIChwb3NpdGlvbih0ZXN0X25hbWUsIG5hbWVfc3Vic3RyKSA+IDApIEFORCAodGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0ZMQUtZJykpCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUK)

In the last instance [it's failed due to an assert in jemalloc](https://s3.amazonaws.com/clickhouse-test-reports/65838/389a86ec059461f20521e4dd2c7888e2b3b37623/stateless_tests__debug__s3_storage__[5_6].html):
```
2024-07-03 09:20:16 <jemalloc>: /build/contrib/jemalloc/src/decay.c:92: Failed assertion: "nstime_compare(&decay->epoch, new_time) <= 0"
2024-07-03 09:20:16 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 64: 63745 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONCompactEachRow')"
2024-07-03 09:20:16 
2024-07-03 09:20:16 stdout:
2024-07-03 09:20:16 x	Nullable(Bool)					
2024-07-03 09:20:16 true
2024-07-03 09:20:16 false
2024-07-03 09:20:16 x	Nullable(Float64)					
2024-07-03 09:20:16 42.42
2024-07-03 09:20:16 0
2024-07-03 09:20:16 x	Nullable(Float64)					
2024-07-03 09:20:16 1
2024-07-03 09:20:16 0.42
2024-07-03 09:20:16 x	Array(Nullable(Float64))					
2024-07-03 09:20:16 [1,0]
2024-07-03 09:20:16 [0.42]
2024-07-03 09:20:16 x	Array(Array(Nullable(Int64)))					
2024-07-03 09:20:16 [[1,2,3],[1,0],[1,1,0]]
2024-07-03 09:20:16 [[1,2,3]]
2024-07-03 09:20:16 c1	Nullable(Bool)					
2024-07-03 09:20:16 true
2024-07-03 09:20:16 false
2024-07-03 09:20:16 c1	Nullable(Float64)					
2024-07-03 09:20:16 42.42
2024-07-03 09:20:16 0
2024-07-03 09:20:16 c1	Nullable(Float64)					
2024-07-03 09:20:16 1
2024-07-03 09:20:16 0.42
2024-07-03 09:20:16 c1	Array(Nullable(Float64))					
2024-07-03 09:20:16 [1,0]
2024-07-03 09:20:16 [0.42]
2024-07-03 09:20:16 c1	Array(Array(Nullable(Int64)))					
2024-07-03 09:20:16 
2024-07-03 09:20:16 
2024-07-03 09:20:16 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 1.0 --prefer_fetch_merged_part_size_threshold 3135711448 --vertical_merge_algorithm_min_rows_to_activate 1 --vertical_merge_algorithm_min_columns_to_activate 1 --allow_vertical_merges_from_compact_to_wide_parts 1 --min_merge_bytes_to_use_direct_io 1044012439 --index_granularity_bytes 9475836 --merge_max_block_size 9146 --index_granularity 40416 --min_bytes_for_wide_part 824419059 --marks_compress_block_size 45700 --primary_key_compress_block_size 69244 --replace_long_file_name_to_hash 1 --max_file_name_length 128 --min_bytes_for_full_part_storage 55985356 --compact_parts_max_bytes_to_buffer 350992591 --compact_parts_max_granules_to_buffer 256 --compact_parts_merge_max_bytes_to_prefetch_part 14064915 --cache_populated_by_fetch 1 --concurrent_part_removal_threshold 100 --old_parts_lifetime 10
2024-07-03 09:20:16 
2024-07-03 09:20:16 Database: test_2qta73pr
```

[Sometimes it's failed with a core dump](https://s3.amazonaws.com/clickhouse-test-reports/65021/441c61e17f33da8e5a2fcf02bb4a776ef0b1e1c0/stateless_tests__coverage__[5_6].html)
```
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 17: 18319 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "desc file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 18: 18320 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 22: 18321 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "desc file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 23: 18322 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 27: 18323 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "desc file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 28: 18324 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 32: 18325 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "desc file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 33: 18326 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 37: 18327 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "desc file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 38: 18328 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 43: 18329 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "desc file('$FILE_NAME', 'JSONCompactEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 44: 18330 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONCompactEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 48: 18331 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "desc file('$FILE_NAME', 'JSONCompactEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 49: 18332 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONCompactEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 53: 18333 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "desc file('$FILE_NAME', 'JSONCompactEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 54: 18334 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONCompactEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 58: 18335 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "desc file('$FILE_NAME', 'JSONCompactEachRow')"
2024-06-11 00:17:03 /usr/share/clickhouse-test/queries/0_stateless/02247_read_bools_as_numbers_json.sh: line 59: 18336 Aborted                 (core dumped) $CLICKHOUSE_CLIENT -q "select * from file('$FILE_NAME', 'JSONCompactEachRow')"
```

**Comment by azat** [comment] 2024-07-08 10:59
This is a duplicate of https://github.com/ClickHouse/ClickHouse/issues/66193 (it has some details)

**Closed by azat** 2024-07-08 10:59 UTC
Labels: flaky test
