### ISSUE TITLE
Can't get query result with mutiple OR 0 = 1  conditions

### ISSUE THREAD

**Issue by allen12921** [ClickHouse/ClickHouse#55288] opened 2023-10-07 09:54 UTC
**Describe what's wrong**

Can't get result with mutiple false OR conditions

**Does it reproduce on recent release?**
yes

**How to reproduce**

* Which ClickHouse server version to use
the latest TLS  23.8.3.48

* `CREATE TABLE` statements for all tables involved
 ```
CREATE TABLE default.forms
(
    `form_id` FixedString(24),
    `text_field` String
)
ENGINE = MergeTree
PRIMARY KEY form_id
ORDER BY form_id
```
* Sample data for all these tables
```
insert into forms values ('5840ead423829c1eab29fa97','this is a test');
```
* Queries to run that lead to unexpected result
```
 select * from forms where text_field like '%this%' or 0 = 1 or 0 = 1  ;
```
**Expected behavior**
Above query should able to get same result as below query
```
select * from forms where text_field like '%this%' or 0 = 1 ;
```

**Comment by nickitat** [comment] 2023-10-07 12:54
`23.7.5.30` - works
`23.8` - don't

**Comment by SaltTan** [comment] 2023-10-09 12:31
It doesn't work in 23.9 either
23.7 https://fiddle.clickhouse.com/a1ae17e3-cd1b-486b-bbbc-507b68be20fd
23.9 https://fiddle.clickhouse.com/ca963c2d-7a30-4209-ba72-c59f7c99ccda
Looks like a duplicate of #54779

**Closed** 2023-10-09 14:49 UTC
Labels: bug, major, v23.8-affected
