### ISSUE TITLE
OPTIIMZE PARTITION without FINAL creates 1 part

### ISSUE THREAD

**Issue by teckatlipoka** [ClickHouse/ClickHouse#60933] opened 2024-03-06 13:31 UTC
I run optimize without final for a large table on 5Tib and 20 parts:
`OPTIMIZE TABLE my_table PARTITION '202401'`

As the result I got a single part for 5Tib. "OPTIMIZE FINAL" should create a single part, but why am I getting 1 part?

Clickhouse 23.8.8.20

I expect clickhouse to optimize parts and create several parts, which won't merge without new data insertion.

**Comment by den-crane** [comment] 2024-03-06 13:41
>OPTIMIZE TABLE my_table PARTITION '202401'

Schedules a new unplaned merge. This new merge produces one or several parts accordingly the part selection algorithm.
It's absolutely valid and expected if 20 parts are merged into one single 5TB part if you trigger unplanned merge even without "final".

**Comment by teckatlipoka** [comment] 2024-03-06 14:02
How to avoid merging all parts of partition into a single part with OPTIMIZE statement?

**Comment by den-crane** [comment] 2024-03-06 14:11
No way. Just don't use OPTIMIZE.
Why do you need to use OPTIMIZE ?

**Comment by teckatlipoka** [comment] 2024-03-07 08:59
I want to prepare cold parts before send it to S3. To be sure there won't be excessive downloads to merge parts.

**Comment by Algunenano** [comment] 2024-03-14 16:40
Do you have a high limit for merges (`max_bytes_to_merge_at_max_space_in_pool`)?

If you call `OPTIMIZE` the parts are, indeed, optimized. By design, CH will try to minimize the number of parts while also limiting how much time is spent merging. If they are old parts and you are forcing a merge, then it's normal that the database prefers to create a single large part (if possible) as it's better all around.

What's the problem in having one 5TB part (if you have enabled this)? It's better than having 5 1TB parts.

**Comment by den-crane** [comment] 2024-03-14 16:59
OPTIMIZE disobeys max_bytes_to_merge_at_max_space_in_pool deliberately

**Comment by den-crane** [comment] 2024-03-18 21:35
>Are you sure about that?

I am not sure. I never checked. Maybe it's false memory.

**Closed** 2024-04-20 01:17 UTC
Labels: st-need-info, unexpected behaviour, close in a month if not active
