### ISSUE TITLE
YouTube videos metadata

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#45739] opened 2023-01-28 22:18 UTC
https://aiven.io/blog/why-you-should-offload-your-pg-analytical-workloads-to-clickhouse

**Comment by alexey-milovidov** [comment] 2023-01-28 22:44
Download:

```
# Create a machine with ~3 TB space on disk.

mkdir files && cd files

curl https://archive.org/download/dislikes_youtube_2021_12_video_json_files | grep -oP 'youtubedislikes.+?\.json\.zst' | sort | uniq > files1.txt
curl https://archive.org/download/dislikes_youtube_2021_12_video_json_files_part2 | grep -oP 'youtubedislikes.+?\.json\.zst' | sort | uniq > files2.txt

wc -l files*.txt 
  6992 files1.txt
     7 files2.txt
  6999 total
  
cat files1.txt | xargs -P10 -I{} wget --continue 'https://archive.org/download/dislikes_youtube_2021_12_video_json_files/{}'
cat files2.txt | xargs -P10 -I{} wget --continue 'https://archive.org/download/dislikes_youtube_2021_12_video_json_files_part2/{}'
```

**Comment by alexey-milovidov** [comment] 2023-01-28 22:58
Works pretty well:

```
$ clickhouse-local --query "SELECT * FROM file('files/*.json.zst', JSONLines) LIMIT 10"
04IV_wmQHvo     20211127173433  20150902        GTA V How to do Daily Objectives #12 Kill a player while Off the Radar  UC_X_UiqFyC2mcviwbhIZ6-g        NIKKO THE GAM3R 308     false   125     0       0       true  false    false   false   true    [{'title':'Grand Theft Auto V','subtitle':'2013','content':'','call':'Browse game','url':'/channel/UCOquqcRMJmURiGfEnaitptg'},{'title':'Gaming','subtitle':'','content':'','call':'Browse all gaming','url':'/gaming'}]        GTA V Online How to do Daily Objectives #12\nKill a player while Off the Radar  []      \N      \N
-OUVMl_2p78     20211127173436  20210425        Libros Para Salir De Un Bloqueo Lector//Libros Recomendados     UCVIHvprQ2beo76hvlTgBatQ        Clío Entre Libros       167     false   45      4       0       true  false    true    false   true    []      Hola mis inmortales!\nBienvenidos a mi canal de  YouTube\nHoy les traigo siete libros para salir de un bloque lector.\nEl bloqueo lector es una molestia para cualquier amante de los libros. Todos hemos pasado por allí. Aquella falta de motivación que te impide volver al hábito de la lectura. Puede ser breve y durar una o dos semanas, o a veces extenderse durante muchos meses. Si estás atravesando dicha situación, aquí te dejo algunos libros que podrían salvarte de esta situación.\n\nEspero que alguno de estos libros les llamen la atención y si es así no se olviden de comentar.\n\n\n★MIS 7 LIBROS PARA SALIR DE UN BLOQUE LECTOR\n- La selección (Kiera Cass)\n- Tan solo un segundo (Virginia S. McKenzie)\n- Cariño, cuanto te odio (Sally Thorne)\n- My Dilemma Is You. Un nuevo amor. O dos... ( Cristina Chiperi)\n- Un paseo para recordar (Nicholas Sparks)\n- Nosotros después de las doce (Laia Soler)\n- Yo estuve aqui (Forman, Gayle)\n\n\nNo olvides seguirme en todas mis redes sociales\nTik Tok: https://www.tiktok.com/@clio.entre_li...\nWattpad:https://www.wattpad.com/user/Clio_Bad...\nInstagram: https://www.instagram.com/clio.libros/ \nGoodreads : https://www.goodreads.com/user/show/1...     []      \N      \N
-s3cRSZY2Sg     20211127173440  20200905        New Template Avee player dj light effects || Whatsapp satus New template || new template 2020   UC-8yPX-iBkW1-tcEOJ6cIwg        Avee template Yunosh    -1      false 62       5       0       true    false   true    false   true    []      #YunoshAveeTemplates,#AveePlayer,#YTCreator\n\n👉Welcome to my channel👈\n\n👉अगर आप मेरे चैनल का और भी टेम्पलेट पाना चाहते है तो आप मेरे चैनल को सब्सक्राइब करें और बेल आइकन को भी दबा दें ताकि आपको वीडियो की नोटिफिकेशन सबसे पहले आप तक पहुंचे|\n\n👉प्लीज आप मेरे वीडियो को पूरा देखें,मेरा वीडियो कोई लंबा नहीं होता है ,तो प्लीज आप मेरे वीडियो को पूरा देखें|\n\n👉 चैनल पर नए हो तो सबस्क्राइब कर लेना\n\n👉 वीडियो अच्छा लगे तो लाइक कर देना\n      \n\n  ✔️👍whatsapp satus maker avee template \n\n ✔👍new template download 2020            \n\n✔️👍1000+Avee Player Temlate\n                                         \n\n✔️👍100 Dj Light Gif Image \n\n   \n\n\n\n\n\n\n👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇\n___________________________________________\n\n                           Template Link\n\n    👉https://www.mediafire.com/download/bo...\n\n___________+++++++++++++++++++________\n\n#navratri template ,#mata template avee ,#template navratri \nNew DJ Name Remix Song Green Screen Video Template Visualizer Video\'s Creation || Copyright Free, New Avee player template background green screen videos DJ remix song |, DJ Naam Music Banane Me Madadgar Video Clip, Audio Spectrum Heart Beat Template | Audio Spectrum Visualizer, Green screen dj effects, Music Note For Music Party dj New Avee player template green screen, Background Musicdj Mihir Santari green screen, Green screen dj remix edited video, Template , #AudioSpectrum\nAvee Player Dj Light Template,New Dj Light Template,Avee Player Full Dj Light Template,Dj Avee Templates,New 2020 Avee Player Template,New Perfect Avee Player Dj Light Template,New Template,New Dj Light Templte,Dj Light Template,New Avee Dj Light Template,New Avee dj Light Template,Dj Light Template,Yunosh Avee Templates,New Dj Light Template,Avee Player,New Template,Yunosh Dj Light Template,New Yunosh Avee Player Dj Light Template,Yunosh avee Player Template,Yunosh Avee Player Template,Avve player Template,New Template New Avee ,New Avee PLAYER TEMPLATES,New Template,New Type Template,New Avee Templates,2020 New Dj Light Template,New Template,Avee Templates,Avee Player Visualizer,New Visualizer Avee Player pro,\nTemplate,Dj Avee Templates,New 2020 Avee Player Template,New Perfect Avee Player Dj Light Template,New Template,New Dj Light Templte,Dj Light Template,New Avee Dj Light Template,New Avee dj Light Template,Dj Light Template,Yunosh avee Templates,New Dj Light Template,Avee Player,New Template,Yunosh Dj Light Template,New Yunosh Avee Player Dj Light Template,Yunosh avee Player Template,yunosh Avee Playeri Template,Avve player Template,New Template New Avee ,New Avee PLAYER TEMPLATES,New Template,New TypeI Template,New Avee Templates,2020 New Dj Light Template,New Template,Avee Templates,Avee Player Visualizer,New Visualizer Avee Player pro\n#AveePlayerYemplate\n#AveePlayerTemplates\n#NewAveePlayerTemplates\n#YunoshAveeTemplates\n\n\n\n☑️subscribe\n\n☑️like \n\n☑️ share \n\n☑️comment \n\n\n________________....................._______________\n\nNew Template, Avee Player Template, New Template, Avee Player New Template, WhatsApp Status Maker Avee Player Template, New Template, yunosh Avee Templates, New Template Dj, Dj light effects\nAvee Player Dj Light Template,New Dj Light Template,Avee Player Full Dj Light Template,Dj Avee Templates,New 2020 Avee Player Template,New Perfect Avee Player Dj Light Template,New Template,New Dj Light Templte,Dj Light Template,New Avee Dj Light Template,New Avee dj Light Template,Dj Light Template,Rk Avee Templates,New Dj Light Template,Avee Player,New Template,yunosh djLight Template,New yunosh Avee Player Dj Light Template,yunosh avee Player Template,yunosh Avee Player Template,Avve player Template,New Template New Avee ,New Avee PLAYER TEMPLATES,New Template,New Type Template,New Avee Templates,2020 New , Light Template,New Template,Avee Templates,Avee Player Visualizer,New Visualizer Avee Player pro,\nTemplate,Dj Avee Templates,New 2020 Avee Player Template,New Perfect Avee Player Dj Light,#ganesh template #mata template New Dj light template, AVEE PLAYER TEMPLATES, New Dj light avee player template, New templte for Avee player, AVEE PLAYER TEMPLATES, New Avee player template 2020, New Avee Player Template, Avee Player Template, dj Light Template, New Template\n\n#template \n#avee player \n#yunosh   [{'text':'#YunoshAveeTemplates','url':'/hashtag/yunoshaveetemplates'},{'text':' ','url':''},{'text':'#AveePlayer','url':'/hashtag/aveeplayer'},{'text':' ','url':''},{'text':'#YTCreator','url':'/hashtag/ytcreator'}] \N      \N
0PiUPUje7SE     20211127173443  20210814        【並木良和さん】並木さんが“石板”を取り出せと言う理由    UC7NnLfef-l5GlhgolPYFX-Q        桜梅桃李        6110    false   4112    241     1       true    false   true  false    true    []      #並木良和 #最新 #石坂\n\n\n【無料プレゼント】\nツインレイが導く最高の愛とあなたの未来を見つける７日間のオンライン動画講座を無料でプレゼント中♪\n→https://syaraku.info/lp/cnc/4jfb\n\n【関連動画】\n\n【並木良和さんのメッセージより】統合ワーク～ダイヤモンドの100の位置に立って本当の自分になる～\nhttps://www.youtube.com/watch?v=XS74e...\n\n\n【今回の動画の概要】\n\n今回は、並木さんが“石板”を取り出せと言う理由をお伝えします。\n\n少しでも役に立った、良かった！と思ったら高評価グッドボタンのクリックをお願いします。今後の運営の活力になります?\n\nコロナ渦で、世界中が激変の時期を迎えてます。あなたにハッピーになってもらうために、随時配信中♪\n\n\n【合わせてご覧になってほしい動画】\n\n\n【並木良和さん　目醒めの話より①】 男性が読んでもわかる　ツインレイと出逢う意味\nhttps://www.youtube.com/watch?v=LX6bd...\n\n【並木良和さん　目醒めの話より②】男性が読んでもわかる　ツインレイと出逢う意味～社会的に認められない関係性で出逢う３つの理由～\nhttps://www.youtube.com/watch?v=Fzj1b...\n\n【ツインレイに出逢う意味③】サイレント期間が起こるまでの男性心理とは？男性が読んでもわかる！\nhttps://www.youtube.com/watch?v=heE40...\n\n【並木良和さん 目醒めの話より④】男性が読んでもわかる！ツインレイと出逢う意味④～闇からの目醒め～\nhttps://www.youtube.com/watch?v=FAnVC...\n\n【並木良和さん　目醒めの話より⑤】男性が読んでもわかる！ツインレイと出逢う意味⑤～本当の目醒めとは～\nhttps://www.youtube.com/watch?v=dqZ_x...\n\n\n【あなたの好転メッセージ】\nあなたの人生が好転する。\nあなたがより豊かになる。\nあなたは変われる。\nあなたをいい方向へ進む。\n\n今日、最近あなたが好転したメッセージをコメントでアウトプットしてみてください。\n\nアウトプットは、あなた自身だけでなく、周りにも好転させる力があります。周りに影響を与える好転メッセージは、あなたに再び戻ってきます。\nあなたが周りを幸せにすることは、あなた自身が幸せになります。\n\nアウトプットは、あなたを幸せにする、一番の近道です。\n\n現在のあなた、過去のあなた、未来のあなた、お金の悩み、病気の悩み、人間関係の悩みを好転させる、あなたのメッセージにはあります。\n\nどんどんアウトプットしてみましょう！\n同じ悩みを持つ人は、たくさんいます。\nあなた一人ではないです。\nだから、思いっきりアウトプットしてみましょう。\n\n私もあなたの質問、悩みに答えていきます。\n\n\n【今日の日記】\n\nみなさん、こんにちは！\n\n日本は今、世界に置いて行かれようとしています。\n\n中国と日本は何が違うのか？\n\n完全に国民の熱量だと思います。\n\nなぜ、日本人は熱量が少なくなったのか？\n\nそれは、政治がどこに向いているか政治家の資質に問題があるような気がします。\n\nもう一つはメディアの責任もあると思います。\n\n政治家は日本の方向性を定め、もっと安心して暮らせる未来図を語ってほしい。\n\nメディアは、あげ足を取るような報道は謹んでほしいです。\n\n政治と報道がいい未来を語り続ける。\n\nすると、10年後、日本の国民は明るい未来を創造する国民性に変わっていくと思います。\n\n子供もたくさん生まれ、日本は再生できる。\n\nけっして、日本は貧乏でも才能がないわけがないです。\n\n日本は、力があります。\n\n世界一の国になっていきましょう！\n\nまず、変わらなければいけないのは私自身。あなた自身です。\n\nひとりひとりが前向きな気持ちになった時に、必ずいい未来を築いていけます。\n\n今日から今から気持ちだけは前向きに変えていきましょう！\n\nもちろん、わたしからスタートです！\n\nそれでは、またです！\n\n\nこれからも、よろしくお願いいたします。\n\n☆桜梅桃李チャンネル登録はこちら\nhttps://www.youtube.com/channel/UC7Nn...\n\n【チャンネル名の意味】\n当チャンネル名は桜梅桃李です。\n桜梅桃李の意味は、桜は桜らしく、梅は梅らしく、桃は桃らしく、杏（あんず）は杏らしく。\nそれぞれ個性があります。その個性を大切にしようという意味が桜梅桃李です。\n他人は羨ましく感じるものです。しかし、人と比べるのではなく、昨日の自分と今日の自分。今日の自分より明日の自分が少しでも成長した。と言える自分になりたいものです。\n\n【人気の動画】\n【並木良和さん最新メッセージ】その裏に隠された新型コロナパンデミックと私達が知らない宇宙の諸事情との関係\nhttps://www.youtube.com/watch?v=IeVDl...\n\n【ツインレイ】サイレント期間を乗り越えツインレイとの再会が訪れる時\nhttps://www.youtube.com/watch?v=4If1j...\n\n【並木良和さん最新メッセージ】そこに隠された現在の新型コロナパンデミックと私達が知らない宇宙の諸事情との関係\nhttps://www.youtube.com/watch?v=JuGWs...\n\n【お金を引き付ける話題】\nhttps://www.youtube.com/watch?v=HNq_U...\nhttps://www.youtube.com/watch?v=uNb2S...\nhttps://www.youtube.com/watch?v=0JgKj...\n\n【健康を引き付ける話題】\nhttps://www.youtube.com/watch?v=GB0DP...\nhttps://www.youtube.com/watch?v=yVfcZ...\nhttps://www.youtube.com/watch?v=pRxGp...\n\n【宇宙のパワーの話題】\nhttps://www.youtube.com/watch?v=jkG8B...\nhttps://www.youtube.com/watch?v=DKwPv...\nhttps://www.youtube.com/watch?v=QPeYb...\n\n【幸せを引き付ける話題】\nhttps://www.youtube.com/watch?v=0H0Iv...\nhttps://www.youtube.com/watch?v=mgk5c...\nhttps://www.youtube.com/watch?v=gpgxw...\n\n【音響】\nYoutubeライブラリー\n魔王魂\n\n#スピリチュアル #潜在意識 #宇宙 #お金 #哲学 #引き寄せの法則 #宗教  #心理学 #覚醒 #並木良和 #最新メッセージ #銀河連合    [{'text':'#並木良和','url':'/hashtag/%E4%B8%A6%E6%9C%A8%E8%89%AF%E5%92%8C'},{'text':' ','url':''},{'text':'#最新','url':'/hashtag/%E6%9C%80%E6%96%B0'},{'text':' ','url':''},{'text':'#石坂','url':'/hashtag/%E7%9F%B3%E5%9D%82'}]   \N       \N
-dwvTuQT9VI     20211127173446  20201003        stockholm syndrome ~ for aldc on your side (mia)        UCa60Hk5XcrgISoh6isLVVlw        Sparkle ALDC    419     false   199     23      0       true    false   false false    true    [{'title':'Suggested by SME','subtitle':'','content':'One Direction - Steal My Girl','call':'','url':'/watch?v=UpsKGvPjAgw'},{'title':'Song','subtitle':'','content':'Stockholm Syndrome','call':'','url':'/watch?v=nGYyTw9RIa8'},{'title':'Artist','subtitle':'','content':'One Direction','call':'','url':'/channel/UCb2HGwORFBo94DmRx4oLzow'},{'title':'Licensed to YouTube by','subtitle':'','content':'SME (on behalf of Syco Music); BMI - Broadcast Music Inc., LatinAutorPerf, UMPG Publishing, UNIAO BRASILEIRA DE EDITORAS DE MUSICA - UBEM, Kobalt Music Publishing, MINT_BMG, LatinAutor - UMPG, AMRA, Abramus Digital, LatinAutor - PeerMusic, BMG Rights Management (US), LLC, CMRRA, ARESA, UMPI, LatinAutor, and 18 Music Rights Societies','call':'','url':''}]     i hope you like ittt :)\n\n𝐡𝐢, 𝐰𝐞𝐥𝐜𝐨𝐦𝐞 𝐭𝐨 ✨𝔰𝔭𝔞𝔯𝔨𝔩𝔢 𝔞𝔩𝔡𝔠 ✨!\n\n𝐭𝐨𝐝𝐚𝐲\'𝐬 𝐬𝐡𝐨𝐮𝐭𝐨𝐮𝐭: aldc on your side\n\n𝐦𝐲 𝐫𝐞𝐪𝐮𝐞𝐬𝐭 𝐟𝐨𝐫𝐦 𝐚𝐧𝐝 𝐜𝐡𝐚𝐧𝐧𝐞𝐥:\nform: https://docs.google.com/forms/d/e/1FA...\nchannel (aldc milk): https://www.youtube.com/channel/UCMfD...\n\n𝐜𝐨𝐧𝐭𝐚𝐜𝐭 𝐦𝐞:\ndiscord: sparkle ✨#1851\npicsart: @sparklealdc\n\n𝐪&𝐚:\n~ what\'s your name?\nmimi!\n~ what are your pronouns?\ni use she/her\n~ what are your favorite colors?\nblue and purple\n~ who made your intro and outro?\nmy intro is made by daydreamer aldc, and my outro is made by aldc planet\n\n𝐭𝐡𝐚𝐧𝐤𝐬 𝐟𝐨𝐫 𝐬𝐮𝐩𝐩𝐨𝐫𝐭𝐢𝐧𝐠 𝐦𝐞! 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮 𝐚𝐥𝐥 ♥️\n\n𝐜𝐨𝐩𝐲𝐫𝐢𝐠𝐡𝐭 𝐢𝐧𝐟𝐨:\nI own nothing; all rights go to Lifetime and A+E Networks.\nCopyright Disclaimer Under Section 107 of the Copyright Act 1976, allowance is made for -fair use- for purposes such as criticism, comment, news reporting, teaching, scholarship, and research. Fair use is a use permitted by copyright statute that might otherwise be infringing. Non-profit, educational or personal use tips the balance in favour of fair use.      [{'text':'#1851','url':'/hashtag/1851'}]        \N      \N
-JsacCLlHrQ     20211127173450  20141020        Daniel encontra o siriguejo     UCaNMbjGp8trFjmNh-CEB6nw        Daniel Tagata   11      false   61      3       0       true    false   false   false   true    []    \N       []      \N      \N
-_hAAQFxG9A     20211127173452  20180507        Berserk and the Band of the Hawk Walkthrough Part 35 PS4 Pro Gameplay   UCWlPpuAbUzHHSkbneYEanvg        Spray gamesTV   22500   false   12      0       0       true  false    true    false   true    [{'title':'Berserk','subtitle':'2016','content':'','call':'Browse game','url':'/channel/UCAMJx-0_3Jds_TXsc6h9pCQ'},{'title':'Gaming','subtitle':'','content':'','call':'Browse all gaming','url':'/gaming'}]   Berserk and the Band of the Hawk Walkthrough PS4 Pro Gameplay\n"Berserk" is one of the most popular and no-doubt one of the darkest fantasy comics, selling more than 40 million copies across the world. The originality of this profound story, told through the lives of fascinating characters and in mind-blowingly complex and detailed drawings has captured the hearts and influenced the lives of many fans not only in Japan, but all over the world as well. The story focuses on the daring and heroic life of Guts, cutting his way through the world of sword, magic and demonic creatures, and contains action, romance, drama and humor - all essential elements of first-class entertainment! \nSlash and Smash Action\nIn this work, the action of cutting through hundreds of enemies, fundamental to the Warriors series, is fused together with the dark and gruesome atmosphere of the world of "Berserk", making various heretofore unseen acts possible, such as using a giant man-sized sword to cut enemies in half, as well as smash or send them flying with the "Slash" and "Smash" actions. Revel in the astounding destructive power capable of cutting through multiple enemies with one blow!\nExtensive and profound story\nIn this game, in addition to the well-known and popular "Golden Age Arc", you will also be able to join Guts and his newest companions on his journey of revenge through "The Hawk of the Millennium Arc". Additionally, the extensive story includes an impressive amount of artwork, including footage from the actual animation movie trilogy and new, original scenes portraying more detailed interactions between the members of the Band of the Hawk and other characters.\nDiverse character selection\nIn addition to the main hero of the story, Guts, you can choose to play as any of a number of characters from all the different parts of the story. Every one of these characters possesses a distinctive set of skills and characteristics to ensure the variety of gameplay is consistent with the world of "Berserk". Furthermore, to deepen immersion into the story, the same familiar cast of Japanese voice actors from the movie trilogy and the new animation series were invited to take part in this project.        []      \N      \N
-ShmsQuXfWk     20211127173455  20191207        2019-20 Canadiens vs Avalanche match#29 UCjKmSbm4abaFdhnXpnpG05A        Manuel Giasson-Léger    69      false   8       0       0       true    false   false   false true     []      \N      []      \N      \N
0FEkWzIyc5M     20211127173458  20111208        "Recovery Room" UCtPPM9R-2X97UnmfQokr91g        Pat Barton      15      false   90      1       0       true    false   false   false   true    []      "Recovery Room" is the epitome of perfection when it comes to carefree beach getaways!  Incredible attention to detail abounds from top to bottom and inside to out of this fantastic beach cottage.  Pirates, parrots and palm trees...  Oh my!  Eclectic beach décor highlights the entire residence, providing a unique theme for every room in this house.  Let the enchanting room themes consume you!\n\nOver the years this home has been lovingly maintained and updated with highlights such as plantation shutters, a 4 zone HVAC system and vinyl cedar shake siding.  Cloudy days are well spent in the first floor rec room.  Grab a tasty treat from the sizable kitchenette with a full sized fridge, microwave and dishwasher then head over to the pool table for some fun!  There\'s plenty of space to relax and enjoy some indoor entertainment.\n\nWind up the spiral staircase to the tropical living area boasting a wood burning fireplace.  Finding Nemo takes on a whole new meaning in the open kitchen.  Bright white cabinets, modern appliances and butcher\'s block counters accent the kitchen.  Become swept away by the whimsy of the Queen Suite and adjoining bath.  Custom murals depicting the serene environment of Back Bay cover the bathroom walls.  Custom tile and a seemingly endless soaring ceiling are finishing touches of this spa-like retreat!\n\nEntertaining is priority in "Recovery Room" and the outdoors is where it\'s at!  Gaze at the Atlantic from the Southeast corner of the expansive deck.  A volleyball net, basketball goal and horseshoes pit are perfect for the days you\'re feeling active.  And on your much appreciated leisurely days you\'re going to love having a hammock, pool and Tiki bar!  The best feature of this remarkable property is the easy beach access!  Take advantage of having an adjoining beach access path allowing you a direct line to the ocean!\n\n"Recovery Room" is absolutely all about having fun and enjoying life every day!      []      \N      \N
070Kl3wCUqM     20211127173500  20210522        Mind fresher video -- as soon as you wake up in the (morning)   UCyJ5KNx9h2SCnA57PvlBQMw        Ancient lotus Yoga      -1      false   32      2       0       true  false    false   false   true    [{'title':'Song','subtitle':'','content':'Angel Guides','call':'','url':'/watch?v=ms7L6HKXZqA'},{'title':'Artist','subtitle':'','content':'Jesse Gallagher','call':'','url':''},{'title':'Album','subtitle':'','content':'Angel Guides','call':'','url':''},{'title':'Licensed to YouTube by','subtitle':'','content':'YouTube Audio Library','call':'','url':''}]     ancient lotus yoga\n\n\n\n\n\n\nWhen waking up in the morning, meditation should be done by taking 10 long breaths. 🧘♀️🧘♀️\n\nMeditation is a medium that inspires us to live a stress free life in a run-of-the-mill life. 🧘♀️🧘♀️\n\nIn the morning, the energy released from your body determines the function of your whole day.🧘♀️🧘♀️\n\nAccording to Bhagavad Gita, if we want to meditate, then we should put all the energy of our body in the center between both the eyes.\n🧘♀️🧘♀️\n\n\n If you liked the video then don\'t forget to subscribe to my channel..... \n.👇👇👇👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtube.com/channel/UCyJ5KNx9...\n\n\n\n\nClick here to see more of my videos 👇👇👇👇👇👇👇👇👇👇👇👇👇\n\nhttps://youtu.be/nxhem6Yy9tY\n\nhttps://youtu.be/lbXmDF1ftRo\n\nhttps://youtu.be/D2RRfKVihAY\n\nhttps://youtu.be/Vo9k7TuTnT8\n\n\nThank you very much for watching my video. 🙏🙏🙏🙏\n\n#mindfreshervideoassoonasyouwakeupinthemorning\n#ancientlotusyoga       [{'text':'#mindfreshervideoassoonasyouwakeupinthemorning','url':'/hashtag/mindfreshervideoassoonasyouwakeupinthemorning'},{'text':' ','url':''},{'text':'#ancientlotusyoga','url':'/hashtag/ancientlotusyoga'}]        \N      \N
```

Contains --paid promotions-- nested JSON.

**Comment by alexey-milovidov** [comment] 2023-01-29 16:38
In about a day, the download finished. The raw data is 1.1T.

**Comment by alexey-milovidov** [comment] 2023-01-29 18:54
```
$ clickhouse-local --query "SELECT count() FROM file('files/*.json.zst', JSONLines)" --progress
4552687234
```

**Comment by alexey-milovidov** [comment] 2023-01-29 20:08
Upload to S3:

`ls -1 files/*.zst | xargs -I{} -P10 aws s3 cp {} s3://clickhouse-public-datasets/youtube/original/{}`

**Comment by alexey-milovidov** [comment] 2023-01-29 23:46
#45763

**Comment by alexey-milovidov** [comment] 2023-01-30 01:13
#45764

**Comment by alexey-milovidov** [comment] 2023-01-30 03:26
https://pastila.nl/?00003cce/3f128d821f2fa08a5098b4e54314f14a.md

**Comment by alexey-milovidov** [comment] 2023-01-31 23:02
#45868

**Comment by gingerwizard** [comment] 2023-03-03 10:14
```
CREATE TABLE youtube
(
    `id` String,
    `fetch_date` DateTime,
    `upload_date` String,
    `title` String,
    `uploader_id` String,
    `uploader` String,
    `uploader_sub_count` Int64,
    `is_age_limit` Bool,
    `view_count` Int64,
    `like_count` Int64,
    `dislike_count` Int64,
    `is_crawlable` Bool,
    `has_subtitles` Bool,
    `is_ads_enabled` Bool,
    `is_comments_enabled` Bool,
    `description` String,
    `rich_metadata` Array(Map(String, String)),
    `super_titles` Array(Map(String, String)),
    `uploader_badges` String,
    `video_badges` String
)
ENGINE = MergeTree
ORDER BY (upload_date, uploader)

INSERT INTO youtube
SETTINGS input_format_null_as_default = 1
SELECT
    id,
    parseDateTimeBestEffort(toString(fetch_date)) AS fetch_date,
    upload_date,
    ifNull(title, '') AS title,
    uploader_id,
    ifNull(uploader, '') AS uploader,
    uploader_sub_count,
    is_age_limit,
    view_count,
    like_count,
    dislike_count,
    is_crawlable,
    has_subtitles,
    is_ads_enabled,
    is_comments_enabled,
    ifNull(description, '') AS description,
    rich_metadata,
    super_titles,
    ifNull(uploader_badges, '') AS uploader_badges,
    ifNull(video_badges, '') AS video_badges
FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/youtube/original/files/*.zst', 'JSONLines')
```

works but needs optimisations. unclear why I need the ifNull despite `input_format_null_as_default=1`

if not I get

```
Code: 349. DB::Exception: Received from awi597fyap.eu-west-1.aws.clickhouse.cloud:9440. DB::Exception: Cannot convert NULL value to non-Nullable type: while converting source column uploader_badges to destination column uploader_badges: while executing 'FUNCTION _CAST(uploader_badges :: 18, String :: 36) -> _CAST(uploader_badges, String) String : 35'. (CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN)
````

Also can't parse the `upload_date` with `parseDateTimeBestEffort` - the format is ok but i get 

```
Received exception from server (version 22.13.1):
Code: 41. DB::Exception: Received from awi597fyap.eu-west-1.aws.clickhouse.cloud:9440. DB::ParsingException. DB::ParsingException: Cannot read DateTime: unexpected word: while executing 'FUNCTION parseDateTimeBestEffort(upload_date :: 2) -> parseDateTimeBestEffort(upload_date) Nullable(DateTime) : 1'. (CANNOT_PARSE_DATETIME
```

**Comment by gingerwizard** [comment] 2023-03-03 10:26
```


┌─table───┬─compressed_size─┬─uncompressed_size─┬─ratio─┐
│ youtube │ 508.59 GiB      │ 1.15 TiB          │  2.32 │
└─────────┴─────────────────┴───────────────────┴───────
```
schema can no doubt be improved - especially the uncompressed size since we use `Int64`

**Comment by azat** [comment] 2023-03-03 12:53
>Code: 349. DB::Exception: Received from awi597fyap.eu-west-1.aws.clickhouse.cloud:9440. DB::Exception: Cannot convert NULL value to non-Nullable type: while converting source column uploader_badges to destination column uploader_badges: while executing 'FUNCTION _CAST(uploader_badges :: 18, String :: 36) -> _CAST(uploader_badges, String) String : 35'. (CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN)

The problem is likely due to those columns was detected as `Nullable(Type)` instead of `Type`, while you `MergeTree` table has just `Type` and it fails during conversion, not parsing.

```sql
6e56712aa85c :) INSERT INTO FUNCTION null('title String') SELECT * FROM file('/data/*.zst', 'JSONLines', 'title Nullable(String)')

INSERT INTO FUNCTION null('title String') SELECT *
FROM file('/data/*.zst', 'JSONLines', 'title Nullable(String)')

Query id: bff438f0-07ab-4ba4-9bb8-32a8441c8b95


0 rows in set. Elapsed: 0.471 sec.

Received exception:
Code: 349. DB::Exception: Cannot convert NULL value to non-Nullable type: while converting source column title to destination column title: while executing 'FUNCTION _CAST(title :: 0, String :: 1) -> _CAST(title, String) String : 2'. (CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN)
```

But I've just checked it and it works in upstream.

```
local :) INSERT INTO FUNCTION null('title String') SELECT * FROM file('*.zst', 'JSONLines', 'title Nullable(String)')

INSERT INTO FUNCTION null('title String') SELECT *
FROM file('*.zst', 'JSONLines', 'title Nullable(String)')

Query id: 726432da-1581-4d50-a67b-602024658309

Ok.

0 rows in set. Elapsed: 0.539 sec. Processed 336.43 thousand rows, 21.13 MB (624.65 thousand rows/s., 39.23 MB/s.)
```

Likely fixed in #46284 (`insertNullAsDefaultIfNeeded`)

**Comment by alexey-milovidov** [comment] 2023-03-04 04:22
I thought I have already loaded this data with no hassle at all.
But I deleted my service in ClickHouse Cloud. Let me find the queries from history.

**Comment by alexey-milovidov** [comment] 2023-03-04 04:25
Not the best table structure:

```
SET input_format_null_as_default = 1;

CREATE TABLE youtube ENGINE = MergeTree ORDER BY ()EMPTY AS SELECT * FROM s3Cluster('default', 'https://clickhouse-public-datasets.s3.amazonaws.com/youtube/original/files/*.zst', 'JSONLines')

INSERT INTO youtube SELECT * FROM s3Cluster('default', 'https://clickhouse-public-datasets.s3.amazonaws.com/youtube/original/files/*.zst', 'JSONLines')
```

Some other attempts:
```
CREATE TABLE youtube(    id String,    fetch_date DateTime,    upload_date String,    title String,    uploader_id String,    uploader String,    uploader_sub_count Int32,    is_age_limit Bool,    view_count UInt64,    like_count UInt32,    dislike_count UInt32,    is_crawlable Bool,    is_live_content Bool,    has_subtitles Bool,    is_ads_enabled Bool,    is_comments_enabled Bool,    description String,    rich_metadata Array(Map(String, String)),    super_titles Array(Map(String, String)),    uploader_badges String,    video_badges String) ENGINE = MergeTree ORDER BY uploader
```

**Comment by rfraposa** [comment] 2023-03-27 02:38
Posted here: https://clickhouse.com/docs/en/getting-started/example-datasets/youtube-dislikes

Closing for now, but if you have any other fun queries to add or more details, just let me know.

**Closed by rfraposa** 2023-03-27 02:38 UTC
Labels: comp-documentation, dataset
