### ISSUE TITLE
Delegate a query as is to MySQL

### ISSUE THREAD

**Issue by RajatGoyal** [ClickHouse/ClickHouse#12478] opened 2020-07-13 19:05 UTC
When using MySQL database engine - is there a way to make a subquery (entirely dependent on MySQL) to run as-is on MySQL.

I have a subquery that joins 3 or more tables (depending upon what user selects on the UI) of MySQL and returns a subset of rows, right now Clickhouse pulls each of these three tables separately into Clickhouse servers and then calculates the result after joining these three and applying predicates, which is not optimum for many use-cases and greatly reduces performance.

The request is for a feature to force a query to run completely on MySQL as is and return results back to CH, without CH trying to parse the query and try to get all data from every table separately in the system. 

Let me know if there is some work done already in this direction, or where would be the right place to start if I had to implement this feature.

**Comment by zhang2014** [comment] 2020-07-14 02:44
> The request is for a feature to force a query to run completely on MySQL as is and return results back to CH, without CH trying to parse the query and try to get all data from every table separately in the system.

This is difficult, for example how we execute functions that don't exists in MySQL is a problem(currently the MySQL engine pushes down some predicates to speed up the query).

BTW: As may be useful to you, in #10851 we will implement the  MaterializeMySQL database engine(In fact, it's mostly done) for real time synchronization with MySQL :)

**Comment by RajatGoyal** [comment] 2020-07-14 03:29
@zhang2014 we could have a syntax like mysql table function which accepts a engine specific query.

For example:

select b.name, a. value from ch.table
inner join on_engine('mysql_database',
select

**Comment by RajatGoyal** [comment] 2020-07-14 03:34
@zhang2014 we could have a syntax like mysql table function which accepts a engine specific query.

```
For example:

select b.name, a. value from ch.table a
inner join on_engine.mysql_database ( external database compatible query ) b
```

Will check out MaterializeMySQL Engine. Would it be able to handle realtime updates?

**Comment by alexey-milovidov** [comment] 2020-07-14 06:40
Allow to specify full query to pass to external data source can be Ok but a few complications exist:
- sometimes the query will not parse by ClickHouse and we will have to put in in quotes (and escaping will be cumbersome);
- we have to derive data types of resulting columns by sending another request.

**Comment by alexey-milovidov** [comment] 2021-06-13 23:28
Duplicate of #1270.

**Comment by R-omk** [comment] 2022-08-09 22:29
@alexey-milovidov, please recheck this issues, most likely it is still not possible for the database engine to perform subqueries and joins on the remote side.

**Comment by alexey-milovidov** [comment] 2022-08-09 23:50
Yes, it was only implemented for dictionaries.
Still to do for table functions and engines.

**Comment by alexey-milovidov** [comment] 2024-01-01 16:39
Duplicate of #46758

**Closed by alexey-milovidov** 2024-01-01 16:39 UTC
Labels: feature, st-discussion
