### ISSUE TITLE
clickhouse-local doesn't work under ubuntu wsl

### ISSUE THREAD

**Issue by gabbello** [ClickHouse/ClickHouse#45219] opened 2023-01-12 11:35 UTC
I've been using the guide from here:  https://clickhouse.com/docs/en/integrations/migration/clickhouse-local/ to install clickhouse-local (also mentioned here: https://clickhouse.com/blog/extracting-converting-querying-local-files-with-sql-clickhouse-local)

Running:
`curl https://clickhouse.com/ | sh`

downloads a clickhouse binary file (shouldn't it be clickhouse-local?)

but then if I try to do:
`xxx@DESKTOP-VNB3DU9:~$ ./clickhouse-local
-bash: ./clickhouse-local: No such file or directory`

and for install i get:
`sudo ./clickhouse install`
`No target executable - decompression only was performed.`

Environment: Ubuntu WSL 1 under Windows 11

**Comment by den-crane** [comment] 2023-01-12 13:32
try `./clickhouse local`

**Comment by gabbello** [comment] 2023-01-12 13:39
I tried that one, but I still get:

`xxx@DESKTOP-VNB3DU9:~$ ./clickhouse local
No target executable - decompression only was performed.`

BTW, what i got downloaded by curl is this package:
` https://builds.clickhouse.com/master/amd64`

**Comment by qoega** [comment] 2023-01-13 00:04
Thank you for report. I just don't have WSL nearby.
Can you check 
1) Size of a binary `du ./clickhouse`
2) `./clickhouse --help`

We have self-extracting archive to minimise downloaded size and I just want to understand if it was already extracted and replaced the original binary or it fails while replacing it.

**Comment by qoega** [comment] 2023-01-13 00:07
Related to #45128, but you have the correct name.

**Comment by gabbello** [comment] 2023-01-13 10:56
```
@DESKTOP-VNB3DU9:~$ du ./clickhouse
518468  ./clickhouse
```

```
@DESKTOP-VNB3DU9:~$ ./clickhouse --help
No target executable - decompression only was performed.
```

**Comment by yakov-olkhovskiy** [comment] 2023-01-13 13:59
@gabbello could you please check if this run of ./clickhouse produces file with name ./clickhouse.decompressed.XXXXXX (where 'XXXXXX' is a random number)? and what's its size? if such file exists, as a workaround, it's a decompressed clickhouse executable - you can rename it to 'clickhouse'

**Comment by gabbello** [comment] 2023-01-13 14:06
I can not execute ./clickhouse
```
DESKTOP-VNB3DU9:~$ ./clickhouse
No target executable - decompression only was performed.
```

There is no other file created:

```
@DESKTOP-VNB3DU9:~$ file clickhouse
clickhouse: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=e397732957072396b0e1f84e3b2c0ba597948320, with debug_info, not stripped
```

**Comment by yakov-olkhovskiy** [comment] 2023-01-13 14:28
@gabbello could you check if there is a file in /tmp directory with some name like 'clickhouse.decompression.xxxx.lock' (xxxx is some number)? if so - delete this file and try run again - it will take some time for decompression (see explanation below) - don't interrupt - it's done only once on the first run

and let me explain what's going on - the file 'clickhouse' you downloaded is a compressed binary - on the first run it should decompress itself, replace original binary and run this decompressed binary with all parameters. Unfortunately all this process as kind of magic that can be affected by some nuances of OS.

**Comment by gabbello** [comment] 2023-01-15 21:33
Sorry for late reply. There were some lock files, i deleted them and run ./clickhouse again, and i still get:
```
DESKTOP-VNB3DU9:~$ ./clickhouse
No target executable - decompression only was performed.
```

note that the error is more or less instant, and my feeling is that there is no decompression performed at all, despite what the error says.

**Comment by yakov-olkhovskiy** [comment] 2023-01-16 03:10
it's very strange - I can't reproduce this error, in my wsl setup it perfectly works... could you please check if the size of /tmp/*.lock file 0 or 1?

**Comment by gabbello** [comment] 2023-01-16 08:13
The size of lock file is 0

**Comment by yakov-olkhovskiy** [comment] 2023-01-16 09:05
that's very strange... looks like compressed binary is corrupted... could you please run `tail -c 16 clickhouse | od -x` and post results here?

**Comment by yakov-olkhovskiy** [comment] 2023-01-16 15:20
hm... seems legit...
could you show me this please:
`tail -c 160 clickhouse | od -t x1`

**Comment by gabbello** [comment] 2023-01-16 15:23
here you go:
```
gp@DESKTOP-VNB3DU9:~$ tail -c 160 clickhouse | od -t x1
0000000 60 dc 42 f6 dd 51 cb f8 84 78 ca 74 ab b0 69 f6
0000020 80 80 77 dc e1 94 bb 28 06 b4 f7 fd 0b 7a d7 4d
0000040 d4 ab f6 fd b2 08 96 75 32 58 1e 63 30 c4 1e 9c
0000060 54 55 02 e3 e2 5f 14 f3 4f 01 03 9b ad 26 c9 3a
0000100 15 26 39 17 da 8e ee dc 2f fe 84 81 e6 59 40 d8
0000120 7d 22 76 99 14 e8 c5 92 00 00 00 00 00 2f 0f a5
0000140 1f 00 00 00 00 0b 00 00 00 00 00 00 00 d8 87 99
0000160 90 00 00 00 00 ed 81 00 00 00 00 00 00 01 00 00
0000200 00 00 00 00 00 63 6c 69 63 6b 68 6f 75 73 65 00
0000220 01 00 00 00 00 00 00 00 2f 0f a5 1f 00 00 00 00
0000240
```

**Comment by den-crane** [comment] 2023-01-16 16:05
BTW which WSL? wsl or wsl2 ?

**Comment by gabbello** [comment] 2023-01-16 16:08
```
 wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         1
````

**Comment by yakov-olkhovskiy** [comment] 2023-01-16 16:16
...and I was able to repro by downgrading wsl to 1...
BTW wsl2 works
thanks, @den-crane

**Comment by yakov-olkhovskiy** [comment] 2023-01-16 17:47
The problem is due to inconsistency in WSL1 - inode reported by `stat` is 64bit number, while inode in `/proc/self/maps` is 32bit number and seems to be just a conversion with lost precision. Solution will be provided soon.

**Comment by yakov-olkhovskiy** [comment] 2023-01-16 21:46
@gabbello you can download it now from CI (not merged yet):
```
wget https://s3.amazonaws.com/clickhouse-builds/45339/c8f635e40bb75c6bbf6dd3ac2bf99da7b91da484/binary_release/clickhouse
chmod +x clickhouse
./clickhouse --help
```

**Comment by gabbello** [comment] 2023-01-17 08:04
Now it works, Thanks a lot, guys!

**Closed** 2023-01-17 13:10 UTC
Labels: comp-install
