### ISSUE TITLE
Lightweight deletes corrupting data parts

### ISSUE THREAD

**Issue by phantom943** [ClickHouse/ClickHouse#47527] opened 2023-03-13 12:03 UTC
It seems that when using lightweight deletes, the data parts become corrupted.

The following query:
```sql
WITH
cte_1 AS 
(
	SELECT     
		field_1,
		field_2, 
		field_3,
		field_4
	FROM       table_1
	WHERE      1 = 1
	AND        date >= DATE '2023-02-01'
	AND        field_4 IN ('value_1')
 ),
cte_2 AS
(
	SELECT    
	           field_1,
	           field_2, 
	           sum(field_3) 
	FROM       cte_1
	where 1=1
--	AND        field_4 IN ('value_1')
	group by   field_1,
	           field_2
)
	SELECT   *
	FROM     cte_2
	WHERE    1 = 1
SETTINGS optimize_move_to_prewhere=1
```
fails with 
```bash
SQL Error [49] [07000]: Code: 49. DB::Exception: Invalid number of rows in Chunk column UInt16 position 1: expected 6657, got 474: While executing MergeTreeThread. (LOGICAL_ERROR) (version 22.11.1.1360 (official build))¶, server ClickHouseNode [uri=http://<host>:<port>/<database>, options={use_server_time_zone=false,use_time_zone=false}]@861048021

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xda0553a in /usr/bin/clickhouse
1. DB::Chunk::checkNumRowsIsConsistent() @ 0x1433f5c3 in /usr/bin/clickhouse
2. DB::MergeTreeBaseSelectProcessor::generate() @ 0x146ce460 in /usr/bin/clickhouse
3. DB::ISource::tryGenerate() @ 0x14350455 in /usr/bin/clickhouse
4. DB::ISource::work() @ 0x1434ffe6 in /usr/bin/clickhouse
5. DB::ExecutionThreadContext::executeTask() @ 0x1436b5c6 in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1436007c in /usr/bin/clickhouse
7. ? @ 0x1436219d in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xdab9e96 in /usr/bin/clickhouse
9. ? @ 0xdabf001 in /usr/bin/clickhouse
10. ? @ 0x7f37ed77e609 in ?
11. __clone @ 0x7f37ed6a3133 in ?
```
However, if I set `SETTINGS optimize_move_to_prewhere=0` - the query returns data successfully. 
Interestingly, same happens if I uncomment `AND field_4 IN ('value_1')` in `cte_2`, which is just strange, because the same filter has been applied in `cte_1`. 
Also, if I comment out the `date >= DATE '2023-02-01'` condition, the query again executes successfully.
Similarly, if I remove `group by field_2` - the query also works fine

I know it's lightweight deletes because `table_1` is a table created from a query, and if I do `create or replace table_1 AS ...` - the same query as above executes without the exception. The problem only occurs after I execute
```sql
delete from table_1 where (date) in (
    select date 
    from table_1_new_data
)
```

`table_1` is defined as follows:
```sql
CREATE TABLE table_1
(
    `date` Date,
    `field_1` String,
    `field_2` String,
    `field_3` String,
    `field_4` UInt64
)
ENGINE = MergeTree
ORDER BY date
SETTINGS index_granularity = 8192
```

I couldn't find a minimal reproducible example, because it seems to be data-dependent. The data samples that I tried do not produce this behaviour.
It seems to be related to data parts, so I dumped the result of 
```sql
select *
from system.parts
where 1=1
and database = 'default'
and table = 'table_1'
and active
```
to a [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1ArzCTdbM5iD8pF6ZRiTNXv6cqSLjTnMwIUtnyfN5wiE/edit?usp=sharing)

Do you think you can diagnose the issue based on the info above? I can provide additional diagnostics upon request.

**Comment by davenger** [comment] 2023-03-13 12:52
@phantom943 I see that you are using version 22.11.1.1360. There was a fix for this problem https://github.com/ClickHouse/ClickHouse/pull/42126 but your version doesn't contain it. Please try using the latest 22.11 build or a newer version. Also, this bug affects query executions but the stored data shouldn't be corrupted.

**Comment by phantom943** [comment] 2023-03-13 14:37
@davenger thanks for this info!
I just copied my data to a server running 23.2.1.2537. It seems to be working just fine.
Thanks, I'll try to update then.

**Closed** 2023-03-15 01:29 UTC
Labels: potential bug

**Comment by davenger** [comment] 2023-03-15 10:11
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/40651
