### ISSUE TITLE
Incompatibility with java.net.http.HttpClient

### ISSUE THREAD

**Issue by darkleaf** [ClickHouse/ClickHouse#45597] opened 2023-01-25 06:47 UTC
I was using HttpClient to connect to Clickhouse in 2022.
And HttpClient was unstable. Then I switched to Apache HttpComponents Client5.
I use http clients manually, without the clickhouse-jdbc.

The same problem has been reported by other people:

1. [JDK-8205684](https://bugs.openjdk.org/browse/JDK-8205684)
2. [8239117](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8239117)
3. [ClickHouse/clickhouse-jdbc/search](https://github.com/ClickHouse/clickhouse-jdbc/search?q=header+parser+received+no+bytes&type=issues)

Could the problem be in Poco Net? It seems that Clickhouse is using very [old version](https://github.com/ClickHouse/poco/tree/4b1c8dd9913d2a16db62df0e509fa598da5c8219/Net/src).

**How to reproduce**
Maybe  we could use [clickhouse-jdbc/clickhouse-benchmark](https://github.com/ClickHouse/clickhouse-jdbc/tree/master/clickhouse-benchmark)

CC: @zhicwu

**Comment by zhicwu** [comment] 2023-01-25 07:39
Hi @darkleaf, from what I saw, besides the stability issue, JDK HttpClient generated too many threads under load(e.g. 400+ threads for 50 concurrent queries in my case). I'm not familiar with both ClickHouse and HttpClient, so I must have done something horribly wrong :)

Back to the issue, my observation is that the underlying socket was forcibly closed by server(due to keep-alive connection?). Unlike Apache HttpClient 4.x and JDK HttpClient, `HttpURLConnection` seems handling the case very well, which is why I use it as the default implementation. Apache HTTP Client 5 seems working fine but to be honest I don't use it very often.

Lastly, to reproduce the issue, the benchmark won't help. You'd better use a stress test tool like JMeter instead. Alternatively, if it's just to reproduce the issue on client side, you may add a test by forcibly shutting down mock server before sending all response back to client.

**Closed** 2024-05-29 12:28 UTC
Labels: question, st-need-repro
