### ISSUE TITLE
Insert data into S3 Engine table

### ISSUE THREAD

**Issue by davidshtian** [ClickHouse/ClickHouse#18868] opened 2021-01-08 11:05 UTC
**Describe the unexpected behavior**
As shown in this [S3 Engine instruction](https://clickhouse.tech/docs/en/engines/table-engines/integrations/s3/), SELECT function works well, while if using the wildcards mode like the one below:
```
https://s3.us-east-1.amazonaws.com/bucket/folder/*
```

If insert data to this table, then there will be a file called '*'.

**How to reproduce**
* Which ClickHouse server version to use: 20.13.1.5591
* Default settings + S3 settings
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE default.s3table
(...)
ENGINE=S3('https://s3.us-east-1.amazonaws.com/bucket/folder/*', CSV)
```
* Queries to run that lead to unexpected result
```
INSERT INTO default.s3table VALUES (...)
```

**Expected behavior**
Should have a required parameter to set which file to write.

**Comment by filimonov** [comment] 2021-01-08 13:41
It was never supported / declared to work. So it's definitely a new feature, it seems it may requere some kind of template format in the s3 path instead of simple glob. 

Do you know how is that problem solved by other DB / frameworks?

**Comment by alexey-milovidov** [comment] 2021-01-09 03:42
Duplicate of #15171.

**Closed by alexey-milovidov** 2021-01-09 03:42 UTC
Labels: comp-s3, duplicate, feature
