### ISSUE TITLE
Views cannot be queried with force_index_by_date

### ISSUE THREAD

**Issue by bobrik** [ClickHouse/ClickHouse#1867] opened 2018-02-07 00:34 UTC
We have a view that filers some columns with PII to present to end users. Users have `force_index_by_date` set to avoid loading tons of data by accident. For some reason, this doesn't work:

```sql
SELECT
    toUnixTimestamp(dateTime) * 1000 AS time_msec,
    count(coloId)
FROM open.foo_limited
WHERE (dateTime >= (now() - (1 * 3600))) AND (date >= toDate(now() - (1 * 3600)))
GROUP BY time_msec
ORDER BY time_msec ASC
FORMAT JSON
```

Here `open.foo_limited` is a `Distributed` table over views like this:

```
CREATE VIEW IF NOT EXISTS r0.foo_limited AS
    SELECT
        date,
        dateTime,
        blahblahblah
    FROM r0.foo;
```

The error we're getting:

```
Code: 277, e.displayText() = DB::Exception: Received from foo.bar,com:9000, f00::123::2. DB::Exception: MinMax index by columns (date) is not used and setting 'force_index_by_date' is set., e.what() = DB::Exception
```

Previously we created view from `Distributed` table, but that did not work because users did not have access to the underlying `Distributed` table. I think that's also not like it should work. Permissions should be checked on view, not on underlying table.

**Comment by alexey-milovidov** [comment] 2018-02-07 10:49
The issue is much worse - WHERE conditions doens't pushed down into view (it is also the same in the case of subqueries) and index is not used.

**Comment by filimonov** [comment] 2019-10-28 21:24
fixed by `enable_optimize_predicate_expression` (enabled by default since 19.5)
```
create table issue1867 ( id UInt64, val String, d Date) Engine=MergeTree() ORDER BY id PARTITION BY toYYYYMM(d);
set force_index_by_date=1;
create view issue1867view as select * from issue1867;
select count() from issue1867view where d = today();
set enable_optimize_predicate_expression = 0;
select count() from issue1867view where d = today(); -- exception
```

**Closed by filimonov** 2019-10-28 21:24 UTC
