### ISSUE TITLE
`LocalObjectStorage` corrupts data

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#48465] opened 2023-04-06 10:29 UTC
https://s3.amazonaws.com/clickhouse-test-reports/47307/c59d7a4bb3831a470d6f8668f5a66080da62fee1/stress_test__debug_/fatal_messages.txt

```
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.565735 [ 21939 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.567419 [ 21939 ] {} <Fatal> BaseDaemon: (version 23.4.1.1, build id: F61B0136645528B00FC955570578C39F2A231470) (from thread 1745) (no query) Received signal Aborted (6)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568164 [ 21939 ] {} <Fatal> BaseDaemon: 
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568411 [ 21939 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f348f6fe00b 0x7f348f6dd859 0x7f348f6dd729 0x7f348f6eefd6 0x2be534d1 0x2bf6bcce 0x2bf69a55 0x2bf692a8 0x2bf71e69 0x2c3eabbd 0x29e12f61 0x29e12a62 0x29e1a758 0x29e1a735 0x29e1a715 0x29e1a6f5 0x29e1a6bd 0x2226f6d6 0x2226ebd5 0x2937d2dd 0x2937f746 0x293807b8 0x29380795 0x29380779 0x293806dd 0x29380600 0x29380575 0x29380555 0x29380535 0x29380500 0x2226f6d6 0x2226ebd5 0x22362f09 0x2236a6c4 0x2236a675 0x2236a59d 0x2236a082 0x7f348f8b5609 0x7f348f7da133
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568651 [ 21939 ] {} <Fatal> BaseDaemon: 4. raise @ 0x7f348f6fe00b in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568792 [ 21939 ] {} <Fatal> BaseDaemon: 5. abort @ 0x7f348f6dd859 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.568932 [ 21939 ] {} <Fatal> BaseDaemon: 6. ? @ 0x7f348f6dd729 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:26.569076 [ 21939 ] {} <Fatal> BaseDaemon: 7. ? @ 0x7f348f6eefd6 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:28.173055 [ 21939 ] {} <Fatal> BaseDaemon: 8. /build/src/Storages/MergeTree/IMergeTreeDataPart.cpp:0: DB::IMergeTreeDataPart::remove() @ 0x2be534d1 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:30.316475 [ 21939 ] {} <Fatal> BaseDaemon: 9. /build/src/Storages/MergeTree/MergeTreeData.cpp:2292: DB::MergeTreeData::clearPartsFromFilesystemImpl(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>> const&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>*)::$_29::operator()() const @ 0x2bf6bcce in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:31.335538 [ 21939 ] {} <Fatal> BaseDaemon: 10. /build/src/Storages/MergeTree/MergeTreeData.cpp:2300: DB::MergeTreeData::clearPartsFromFilesystemImpl(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>> const&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>*) @ 0x2bf69a55 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:32.451100 [ 21939 ] {} <Fatal> BaseDaemon: 11. /build/src/Storages/MergeTree/MergeTreeData.cpp:2265: DB::MergeTreeData::clearPartsFromFilesystem(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>> const&, bool, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>*) @ 0x2bf692a8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:33.521054 [ 21939 ] {} <Fatal> BaseDaemon: 12. /build/src/Storages/MergeTree/MergeTreeData.cpp:2662: DB::MergeTreeData::dropAllData() @ 0x2bf71e69 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:34.303915 [ 21939 ] {} <Fatal> BaseDaemon: 13. /build/src/Storages/StorageMergeTree.cpp:301: DB::StorageMergeTree::drop() @ 0x2c3eabbd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:34.894148 [ 21939 ] {} <Fatal> BaseDaemon: 14. /build/src/Interpreters/DatabaseCatalog.cpp:0: DB::DatabaseCatalog::dropTableFinally(DB::DatabaseCatalog::TableMarkedAsDropped const&) @ 0x29e12f61 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:35.241088 [ 21939 ] {} <Fatal> BaseDaemon: 15. /build/src/Interpreters/DatabaseCatalog.cpp:1076: DB::DatabaseCatalog::dropTableDataTask() @ 0x29e12a62 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:35.618683 [ 21939 ] {} <Fatal> BaseDaemon: 16. /build/src/Interpreters/DatabaseCatalog.cpp:176: DB::DatabaseCatalog::createBackgroundTasks()::$_4::operator()() const @ 0x29e1a758 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:36.054058 [ 21939 ] {} <Fatal> BaseDaemon: 17. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::DatabaseCatalog::createBackgroundTasks()::$_4&>()()) std::__invoke[abi:v15000]<DB::DatabaseCatalog::createBackgroundTasks()::$_4&>(DB::DatabaseCatalog::createBackgroundTasks()::$_4&) @ 0x29e1a735 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:36.435510 [ 21939 ] {} <Fatal> BaseDaemon: 18. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__invoke_void_return_wrapper<void, true>::__call<DB::DatabaseCatalog::createBackgroundTasks()::$_4&>(DB::DatabaseCatalog::createBackgroundTasks()::$_4&) @ 0x29e1a715 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:36.825310 [ 21939 ] {} <Fatal> BaseDaemon: 19. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::DatabaseCatalog::createBackgroundTasks()::$_4, void ()>::operator()[abi:v15000]() @ 0x29e1a6f5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.211942 [ 21939 ] {} <Fatal> BaseDaemon: 20. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::DatabaseCatalog::createBackgroundTasks()::$_4, void ()>>(std::__function::__policy_storage const*) @ 0x29e1a6bd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.280672 [ 21939 ] {} <Fatal> BaseDaemon: 21. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<void ()>::operator()[abi:v15000]() const @ 0x2226f6d6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.364422 [ 21939 ] {} <Fatal> BaseDaemon: 22. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<void ()>::operator()() const @ 0x2226ebd5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.455603 [ 21939 ] {} <Fatal> BaseDaemon: 23. /build/src/Core/BackgroundSchedulePool.cpp:100: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x2937d2dd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.571021 [ 21939 ] {} <Fatal> BaseDaemon: 24. /build/src/Core/BackgroundSchedulePool.cpp:282: DB::BackgroundSchedulePool::threadFunction() @ 0x2937f746 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.668202 [ 21939 ] {} <Fatal> BaseDaemon: 25. /build/src/Core/BackgroundSchedulePool.cpp:161: DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1::operator()() const @ 0x293807b8 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.762945 [ 21939 ] {} <Fatal> BaseDaemon: 26. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&>()()) std::__invoke[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&) @ 0x29380795 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.878386 [ 21939 ] {} <Fatal> BaseDaemon: 27. /build/contrib/llvm-project/libcxx/include/tuple:1789: decltype(auto) std::__apply_tuple_impl[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::tuple<>&, std::__tuple_indices<>) @ 0x29380779 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:37.976371 [ 21939 ] {} <Fatal> BaseDaemon: 28. /build/contrib/llvm-project/libcxx/include/tuple:1798: decltype(auto) std::apply[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::tuple<>&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&, std::tuple<>&) @ 0x293806dd in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.051012 [ 21939 ] {} <Fatal> BaseDaemon: 29. /build/src/Common/ThreadPool.h:227: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'()::operator()() @ 0x29380600 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.146782 [ 21939 ] {} <Fatal> BaseDaemon: 30. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>()()) std::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&) @ 0x29380575 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.242223 [ 21939 ] {} <Fatal> BaseDaemon: 31. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'()&) @ 0x29380555 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.335605 [ 21939 ] {} <Fatal> BaseDaemon: 32. /build/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'(), void ()>::operator()[abi:v15000]() @ 0x29380535 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.430608 [ 21939 ] {} <Fatal> BaseDaemon: 33. /build/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x29380500 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.501374 [ 21939 ] {} <Fatal> BaseDaemon: 34. /build/contrib/llvm-project/libcxx/include/__functional/function.h:848: std::__function::__policy_func<void ()>::operator()[abi:v15000]() const @ 0x2226f6d6 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.562552 [ 21939 ] {} <Fatal> BaseDaemon: 35. /build/contrib/llvm-project/libcxx/include/__functional/function.h:1187: std::function<void ()>::operator()() const @ 0x2226ebd5 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.663955 [ 21939 ] {} <Fatal> BaseDaemon: 36. /build/src/Common/ThreadPool.cpp:396: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x22362f09 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.764426 [ 21939 ] {} <Fatal> BaseDaemon: 37. /build/src/Common/ThreadPool.cpp:180: void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()::operator()() const @ 0x2236a6c4 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.876006 [ 21939 ] {} <Fatal> BaseDaemon: 38. /build/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<void>()()) std::__invoke[abi:v15000]<void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&) @ 0x2236a675 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:38.980545 [ 21939 ] {} <Fatal> BaseDaemon: 39. /build/contrib/llvm-project/libcxx/include/thread:285: void std::__thread_execute[abi:v15000]<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(std::tuple<void, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>&, std::__tuple_indices<>) @ 0x2236a59d in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:39.083840 [ 21939 ] {} <Fatal> BaseDaemon: 40. /build/contrib/llvm-project/libcxx/include/thread:295: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x2236a082 in /usr/bin/clickhouse
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:39.083997 [ 21939 ] {} <Fatal> BaseDaemon: 41. ? @ 0x7f348f8b5609 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:39.084159 [ 21939 ] {} <Fatal> BaseDaemon: 42. clone @ 0x7f348f7da133 in ?
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.06 01:47:39.084303 [ 21939 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
```

**Comment by tavplubix** [comment] 2023-04-06 11:06
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/47408

**Comment by tavplubix** [comment] 2023-04-07 19:23
@kssenii, I suspect that it's actually a bug in `LocalObjectStorage`. Seems like some part of the file just disappeared:
```
1693084:2023.04.04 21:14:13.371994 [ 1715 ] {} <Error> test_p1k2itz1.test_02286 (1a04681b-2330-4361-a1f5-0c7cea63c6e4): File txn_version.txt contains:
1693085-
1693086-creation_csn: 90
1693087-expected:
1693088-version: 1
1693089-creation_tid: (89, 48, 815024e3-5d68-49be-ba02-280e532c301a)
1693090-creation_csn: 90
1693091-lock: 0
1693092-name: all_1_1_0: Code: 27. DB::ParsingException: Cannot parse input: expected 'version: 1' before: '\ncreation_csn: 90'. (CANNOT_PARSE_INPUT_ASSERTION_FAILED), Stack trace (when copying this message, always include the lines below):
1693093-
1693094-0. /build/contrib/llvm-project/libcxx/include/exception:134: std::exception::capture() @ 0x194ae142 in /usr/bin/clickhouse
1693095-1. /build/contrib/llvm-project/libcxx/include/exception:112: std::exception::exception[abi:v15000]() @ 0x194ae10d in /usr/bin/clickhouse
1693096-2. /build/base/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(String const&, int) @ 0x318afd00 in /usr/bin/clickhouse
1693097-3. /build/src/Common/Exception.cpp:89: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x21f2efae in /usr/bin/clickhouse
1693098-4. /build/src/Common/Exception.h:55: DB::Exception::Exception(String&&, int, bool) @ 0x194a144a in /usr/bin/clickhouse
1693099-5. /build/src/Common/Exception.h:174: DB::ParsingException::ParsingException<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x21fc8953 in /usr/bin/clickhouse
1693100-6. /build/src/IO/ReadHelpers.cpp:103: DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) @ 0x21fbbeea in /usr/bin/clickhouse
1693101-7. /build/src/IO/ReadHelpers.cpp:140: DB::assertString(char const*, DB::ReadBuffer&) @ 0x21fbc175 in /usr/bin/clickhouse
1693102-8. /build/src/Interpreters/TransactionVersionMetadata.cpp:344: DB::VersionMetadata::read(DB::ReadBuffer&) @ 0x2acf7eb6 in /usr/bin/clickhouse
1693103-9. /build/src/Storages/MergeTree/IMergeTreeDataPart.cpp:1531: DB::IMergeTreeDataPart::assertHasValidVersionMetadata() const @ 0x2ba62c79 in /usr/bin/clickhouse
1693104-10. /build/src/Storages/MergeTree/IMergeTreeDataPart.cpp:1639: DB::IMergeTreeDataPart::remove() @ 0x2ba633df in /usr/bin/clickhouse
```

It's easy to reproduce: 
```
            <implicit_transaction>1</implicit_transaction>
            <throw_on_unsupported_query_inside_transaction>0</throw_on_unsupported_query_inside_transaction>
```
and run `02286_drop_filesystem_cache`. It's interesting that it does not reproduce with `s3_cache`, only with `local_cache`

**Comment by tavplubix** [comment] 2023-04-07 19:58
Looks like it can be reproduced with `02241_filesystem_cache_on_write_operations` too:
https://s3.amazonaws.com/clickhouse-test-reports/0/bd496654bb86fb2af17a4c96e88de4df4275f16a/stress_test__ubsan_.html

**Comment by tavplubix** [comment] 2023-04-07 20:05
Also, for some reason, the `local_disk` directory was created in my home dir, not inside the server root directory

**Comment by kssenii** [comment] 2023-04-14 13:57
> Also, for some reason, the local_disk directory was created in my home dir, not inside the server root directory

https://github.com/ClickHouse/ClickHouse/pull/48784

**Closed** 2023-05-04 09:47 UTC
Labels: testing
