### ISSUE TITLE
Clickhouse Server 21.9  doesn't start

### ISSUE THREAD

**Issue by suedschwede** [ClickHouse/ClickHouse#29041] opened 2021-09-15 10:47 UTC
After upgrade to 21.9 my clickhouse server doesn't start

```
2021.09.15 12:38:04.821528 [ 47028 ] {} <Error> Application: Caught exception while loading metadata: Code: 59. DB::Exception: Invalid sampling column type in storage parameters: String. Must be one unsigned integer type: Cannot attach table `INTERN`.`phonecalls` from metadata file /var/lib/clickhouse/metadata/INTERN/phonecalls.sql from query ATTACH TABLE INTERN.phonecalls (`uri` String, `startdate` DateTime, `duration` Float64, `incomingnode` String, `route` String, `outgoingnode` String, `sourcenumberinbound` String, `destinationnumberinbound` String, `sourcenumberoutbound` String, `destinationnumberoutbound` String, `callresult` String, `prio` String) ENGINE = ReplacingMergeTree ORDER BY uri SAMPLE BY uri SETTINGS index_granularity = 8192: while loading database `INTERN` from path /var/lib/clickhouse/metadata/INTERN. (ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9366e7a in /usr/bin/clickhouse
1. ? @ 0x11459dfe in /usr/bin/clickhouse
2. DB::MergeTreeData::MergeTreeData(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, bool, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0x114509dc in /usr/bin/clickhouse
3. DB::StorageMergeTree::StorageMergeTree(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, bool, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0x116925e0 in /usr/bin/clickhouse
4. ? @ 0x11687cd7 in /usr/bin/clickhouse
5. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x11100f61 in /usr/bin/clickhouse
6. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0x105ed4c5 in /usr/bin/clickhouse
7. ? @ 0x105eb573 in /usr/bin/clickhouse
8. ? @ 0x105ec5ff in /usr/bin/clickhouse
9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x93aabb8 in /usr/bin/clickhouse
10. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x93ac75f in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x93a7e9f in /usr/bin/clickhouse
12. ? @ 0x93ab783 in /usr/bin/clickhouse
13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
14. __clone @ 0xfe9fd in /usr/lib64/libc-2.17.so
 (version 21.9.2.17 (official build))
2021.09.15 12:38:04.821672 [ 47028 ] {} <Information> Application: Shutting down storages.
2021.09.15 12:38:04.821681 [ 47028 ] {} <Information> Context: Shutdown disk default
2021.09.15 12:38:04.821754 [ 47035 ] {} <Trace> SystemLog (system.query_log): Terminating
2021.09.15 12:38:04.821930 [ 47036 ] {} <Trace> SystemLog (system.query_thread_log): Terminating
2021.09.15 12:38:04.823816 [ 47038 ] {} <Trace> SystemLog (system.trace_log): Terminating
2021.09.15 12:38:04.830383 [ 47028 ] {} <Trace> BackgroundSchedulePool/BgSchPool: Waiting for threads to finish.
2021.09.15 12:38:04.832844 [ 47028 ] {} <Debug> Application: Shut down storages.
2021.09.15 12:38:04.833691 [ 47028 ] {} <Debug> Application: Destroyed global context.
2021.09.15 12:38:04.834944 [ 47028 ] {} <Error> Application: DB::Exception: Invalid sampling column type in storage parameters: String. Must be one unsigned integer type: Cannot attach table `INTERN`.`phonecalls` from metadata file /var/lib/clickhouse/metadata/INTERN/phonecalls.sql from query ATTACH TABLE INTERN.phonecalls (`uri` String, `startdate` DateTime, `duration` Float64, `incomingnode` String, `route` String, `outgoingnode` String, `sourcenumberinbound` String, `destinationnumberinbound` String, `sourcenumberoutbound` String, `destinationnumberoutbound` String, `callresult` String, `prio` String) ENGINE = ReplacingMergeTree ORDER BY uri SAMPLE BY uri SETTINGS index_granularity = 8192: while loading database `INTERN` from path /var/lib/clickhouse/metadata/INTERN
2021.09.15 12:38:04.834973 [ 47028 ] {} <Information> Application: shutting down
2021.09.15 12:38:04.834981 [ 47028 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2021.09.15 12:38:04.835457 [ 47029 ] {} <Trace> BaseDaemon: Received signal -2
2021.09.15 12:38:04.835481 [ 47029 ] {} <Information> BaseDaemon: Stop SignalListener thread
2021.09.15 12:38:04.883521 [ 47027 ] {} <Information> Application: Child process exited normally with code 70.
```

**Comment by CurtizJ** [comment] 2021-09-15 10:55
Duplicate of #29005.

**Closed by CurtizJ** 2021-09-15 10:55 UTC
Labels: backward compatibility
