### ISSUE TITLE
insert scientific form Float64 into MergeTree has different bytes from that inserted by not scientific form

### ISSUE THREAD

**Issue by pzhdfy** [ClickHouse/ClickHouse#42310] opened 2022-10-14 08:43 UTC
```
 select reinterpretAsInt64(1.009E10),reinterpretAsInt64(10090000000.0);

SELECT
    reinterpretAsInt64(10090000000.),
    reinterpretAsInt64(10090000000.)

Query id: a491f71b-b150-4c31-9b73-a87ec5f9e5c2

┌─reinterpretAsInt64(10090000000.)─┬─reinterpretAsInt64(10090000000.)─┐
│              4756587672795873280 │              4756587672795873280 │
└──────────────────────────────────┴──────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```
1.009E10 and 10090000000.0 has same binary

```
CREATE TABLE test
(
    `a` Float64
)
ENGINE = MergeTree
ORDER BY a;
 insert into test values(1.009E10),(10090000000.0);
select reinterpretAsInt64(a) from test;

SELECT reinterpretAsInt64(a)
FROM test

Query id: 7127fc4f-96cb-40b6-be8b-397a9d68617e

┌─reinterpretAsInt64(a)─┐
│   4756587672795873279 │
│   4756587672795873280 │
└───────────────────────┘

2 rows in set. Elapsed: 0.001 sec.
```

but after insert table they are different;

**How to reproduce**

* Which ClickHouse server version to use: All versions;
* Which interface to use, if matters: CLI

**Comment by den-crane** [comment] 2022-10-14 08:59
```
select cast('1.009E10','Float64'), cast('10090000000.0', 'Float64');
┌─CAST('1.009E10', 'Float64')─┬─CAST('10090000000.0', 'Float64')─┐
│          10089999999.999998 │                      10090000000 │
└─────────────────────────────┴──────────────────────────────────┘
```

duplicate of https://github.com/ClickHouse/ClickHouse/issues/18999

**Closed by den-crane** 2022-10-14 08:59 UTC
Labels: question
