### ISSUE TITLE
No sources given to target: tzdata

### ISSUE THREAD

**Issue by wangxi19** [ClickHouse/ClickHouse#14262] opened 2020-08-31 05:49 UTC
version: 20.8
build from Clickhouse source codes.
centos 8.2

The cmake file has a incorrect usage of find command.
./contrib/cctz-cmake/CMakeLists.txt: line 85
' bash -c "cd ${TZDIR} && find * -type f,l ..." '
The type option of find can only contain one parameter, use 'find * -type f' to instead

so, no sources are given to built library tzdata due to failed executing of the above command

**Comment by filimonov** [comment] 2020-08-31 08:04
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/14209

**Closed by filimonov** 2020-08-31 08:04 UTC
Labels: bug
