### ISSUE TITLE
Replica from ZooKeeper was not deleted

### ISSUE THREAD

**Issue by lostclus** [ClickHouse/ClickHouse#20243] opened 2021-02-09 12:41 UTC
The DROP TABLE on replicated table doesn't delete replica entry in ZooKeeper.
Reproduce on v21.2.2.8-stable

**How to reproduce**
```
xps :) CREATE TABLE test (id Int32) ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', '01') ORDER BY id;

CREATE TABLE test
(
    `id` Int32
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', '01')
ORDER BY id

Query id: 2315c572-d7b9-496f-ad1f-8e2589983cab

Ok.

0 rows in set. Elapsed: 0.021 sec. 

xps :) DROP TABLE test;

DROP TABLE test

Query id: 56fa6b38-d30f-42be-a3ae-01df1b5554f6

Ok.

0 rows in set. Elapsed: 0.001 sec. 

xps :) CREATE TABLE test (id Int32) ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', '01') ORDER BY id;

CREATE TABLE test
(
    `id` Int32
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', '01')
ORDER BY id

Query id: 917ec320-3b12-4671-ab59-c1e795e7fa2a


0 rows in set. Elapsed: 0.004 sec. 

Received exception from server (version 21.3.1):
Code: 253. DB::Exception: Received from localhost:9000. DB::Exception: Replica /clickhouse/tables/test/replicas/01 already exists.. 
```

**Expected behavior**
DROP TABLE deletes replica entry from ZooKeeper and sequence of commands CREATE TABLE ...; DROP TABLBE ...; CREATE TABLE works without errors.

**Comment by tavplubix** [comment] 2021-02-09 16:28
Does current database have `Atomic` engine? Looks like a duplicate of #12135. You should use `{uuid}` macro in zookeeper path for `ReplicatedMergeTree` or create table with default zookeeper path (without engine arguments) or use `DROP TABLE test SYNC` or set `database_atomic_wait_for_drop_and_detach_synchronously` setting to 1.

**Closed** 2021-02-11 15:26 UTC
Labels: question, question-answered

**Comment by roman-vynar** [comment] 2021-06-10 14:15
@tavplubix  Thanks a ton for your comment. 
This DROP NO DELAY|SYNC or database_atomic_wait_for_drop_and_detach_synchronously is undocumented or poorly documented.
