### ISSUE TITLE
MaterializedPostgreSQL: Table is skipped from replication stream when using `GENERATED` columns

### ISSUE THREAD

**Issue by larskarbo** [ClickHouse/ClickHouse#57197] opened 2023-11-24 14:10 UTC
With `MaterializedPostgreSQL`, tables are skipped from the replication stream when using `GENERATED` columns.

```
<Warning> PostgreSQLReplicaConsumer(testdb): Table my_table_bool is skipped from replication stream because its structure has changes. Please detach this table and reattach to resume the replication (relation id: 9118494)
```

## How to reproduce

Use latest Clickhouse, and a Postgres DB (I am using Postgres 14).

In Postgres:
```sql
CREATE TABLE my_table (
  id integer PRIMARY KEY,
  num1 integer,
  num2 integer
);

CREATE TABLE my_table_bool (
  id integer PRIMARY KEY,
  num1 integer,
  num2 integer,
  is_equal boolean NOT NULL GENERATED ALWAYS AS (num1 = num2) STORED
);

CREATE TABLE my_table_int (
  id integer PRIMARY KEY,
  num1 integer,
  num2 integer,
  sum integer NOT NULL GENERATED ALWAYS AS (num1 + num2) STORED
);

CREATE TABLE my_table_string (
  id integer PRIMARY KEY,
  num1 integer,
  num2 integer,
  concatenated varchar(255) NOT NULL GENERATED ALWAYS AS (CAST(num1 AS varchar(255)) || CAST(num2 AS varchar(255))) STORED
);
```

In ClickHouse:

```sql
CREATE DATABASE testdb_replica
ENGINE = MaterializedPostgreSQL(
	'host.docker.internal:5432',
	'testdb',
	'lars',
	''
);
```

In Postgres, add a row to each table:

```sql
INSERT INTO my_table (id, num1, num2) VALUES (1, 1, 1);
INSERT INTO my_table_bool (id, num1, num2) VALUES (1, 1, 1);
INSERT INTO my_table_int (id, num1, num2) VALUES (1, 1, 1);
INSERT INTO my_table_string (id, num1, num2) VALUES (1, 1, 1);
```

In the `clickhouse-server.err.log`:

```
2023.11.24 14:09:05.171594 [ 158 ] {} <Warning> PostgreSQLReplicaConsumer(testdb): Table my_table_bool is skipped from replication stream because its structure has changes. Please detach this table and reattach to resume the replication (relation id: 9118494)
2023.11.24 14:09:05.172438 [ 158 ] {} <Warning> PostgreSQLReplicaConsumer(testdb): Table my_table_int is skipped from replication stream because its structure has changes. Please detach this table and reattach to resume the replication (relation id: 9118500)
2023.11.24 14:09:05.172897 [ 158 ] {} <Warning> PostgreSQLReplicaConsumer(testdb): Table my_table_string is skipped from replication stream because its structure has changes. Please detach this table and reattach to resume the replication (relation id: 9118506)
```

Only `my_table` successfully replicates. The others are not syncing.

**Comment by larskarbo** [comment] 2023-11-24 14:11
@slvrtrn

**Comment by kssenii** [comment] 2023-12-06 14:55
This issue is a duplicate of https://github.com/ClickHouse/ClickHouse/issues/40449, therefore closing.
Fix: https://github.com/ClickHouse/ClickHouse/pull/57568.

**Closed by kssenii** 2023-12-06 14:55 UTC
Labels: experimental issue
