### ISSUE TITLE
Failed assertion `Logical error: 'Part all_107_107_0 from table test_n061whyr.alter_table0 (8a48855c-716c-49fa-9280-5ef12faa0dd4) remains in ZooKeeper after DROP_RANGE all_0_107_999999999_999999999'`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67317] opened 2024-07-28 19:24 UTC
https://s3.amazonaws.com/clickhouse-test-reports/67295/13c93cc90cc35e33cad71095fa0300c5f4f1753e/stateless_tests__debug__[2_2].html

**Comment by al13n321** [comment] 2024-08-16 18:52
https://s3.amazonaws.com/clickhouse-test-reports/68313/b3a3d1e7202837e2da45b6775b4ea8c389c881a7/stateless_tests__debug__[2_2].html

**Comment by nikitamikhaylov** [comment] 2024-09-20 18:30
Same here: https://s3.amazonaws.com/clickhouse-test-reports/63151/be2ab4689708d284ad149ea2637dcda90d4097aa/stateless_tests__ubsan__[2_2].html

**Comment by Avogar** [comment] 2024-10-10 02:35
https://s3.amazonaws.com/clickhouse-test-reports/70312/82aeaac9847dc75415bb0f3242524872f7d5cd64/stateless_tests__debug__[2_2]/fatal_messages.txt

**Comment by Avogar** [comment] 2024-10-31 13:31
https://s3.amazonaws.com/clickhouse-test-reports/71193/9ab5f16968cb1c89a8c47b5dae07ea050380327f/stateless_tests__asan__[2_2].html

**Comment by azat** [comment] 2024-11-04 15:52
Looks like duplicate of #56037

**Closed** 2024-12-26 07:01 UTC
Labels: testing
