### ISSUE TITLE
Random crashes after upgrade to 23.8.15

### ISSUE THREAD

**Issue by alexryndin** [ClickHouse/ClickHouse#65779] opened 2024-06-27 15:57 UTC
After upgrade to 23.8 from 23.1 Clickhouse randomly crashed after some queries.
Some traces:
```2024.06.25 19:44:40.400428 [ 47079 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.06.25 19:44:40.400528 [ 47079 ] {} <Fatal> BaseDaemon: (version 23.8.15.35 (official build), build id: 490DD83183A7376BE2DE1B9EF16E86C55C52C59E, git hash: 060ff8e813a4a16a540063127f8c91e2108d9adf) (from thre
ad 42666) Received signal 11
2024.06.25 19:44:40.400594 [ 47079 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.06.25 19:44:40.400614 [ 47079 ] {} <Fatal> BaseDaemon: Address: 0x30. Access: read. Address not mapped to object.
2024.06.25 19:44:40.400653 [ 47079 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000011591ec4 0x0000000013625e8c 0x0000000013624cf2 0x00000000135fcaf6 0x000000001358a82d 0x000000001358974e 0x000000001200af45 0x0000
000012b94d17 0x0000000012ba259d 0x0000000012ba28fc 0x0000000012ba28fc 0x0000000012b8e8b0 0x00000000135a845e 0x00000000135a72a5 0x00000000135fd9fb 0x000000001358a84b 0x000000001358974e 0x0000000011f7f759 0x0000000
0122c5ba8 0x00000000122c8935 0x00000000130e264d 0x00000000130e7049 0x0000000013157fb2 0x0000000015b48634 0x0000000015b49831 0x0000000015c80467 0x0000000015c7e73c 0x00007fb1abe07ea5 0x00007fb1abb309fd
2024.06.25 19:44:40.400677 [ 47079 ] {} <Fatal> BaseDaemon: ########################################
```

```2024.06.25 19:44:40.449544 [ 26552 ] {} <Fatal> BaseDaemon: Address: 0x30. Access: read. Address not mapped to object.
2024.06.25 19:44:40.449551 [ 26552 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000011591ec4 0x0000000013625e8c 0x0000000013624cf2 0x00000000135fcaf6 0x000000001358a82d 0x000000001358974e 0x000000001200af45 0x0000000012b94d17 0x0000000012ba259d 0x0000000012ba28fc 0x0000000012ba28fc 0x0000000012b8e8b0 0x00000000135a845e 0x00000000135a72a5 0x00000000135fd9fb 0x000000001358a84b 0x000000001358974e 0x0000000011f7f759 0x00000000122c5ba8 0x00000000122c8935 0x00000000130e264d 0x00000000130e7049 0x0000000013157fb2 0x0000000015b48634 0x0000000015b49831 0x0000000015c80467 0x0000000015c7e73c 0x00007f951a011ea5 0x00007f9519d3a9fd
2024.06.25 19:44:40.450118 [ 26552 ] {} <Fatal> BaseDaemon: 2. DB::FindOriginalNodeForOutputName::FindOriginalNodeForOutputName(std::shared_ptr<DB::ActionsDAG> const&) @ 0x0000000011591ec4 in /usr/bin/clickhouse
2024.06.25 19:44:40.450631 [ 26552 ] {} <Fatal> BaseDaemon: 3. DB::QueryPlanOptimizations::(anonymous namespace)::compareAggregationKeysWithDistinctColumns(std::vector<String, std::allocator<String>> const&, std::set<std::basic_string_view<char, std::char_traits<char>>, std::less<std::basic_string_view<char, std::char_traits<char>>>, std::allocator<std::basic_string_view<char, std::char_traits<char>>>> const&, std::vector<std::vector<std::shared_ptr<DB::ActionsDAG>, std::allocator<std::shared_ptr<DB::ActionsDAG>>>, std::allocator<std::vector<std::shared_ptr<DB::ActionsDAG>, std::allocator<std::shared_ptr<DB::ActionsDAG>>>>>) @ 0x0000000013625e8c in /usr/bin/clickhouse
2024.06.25 19:44:40.451107 [ 26552 ] {} <Fatal> BaseDaemon: 4. DB::QueryPlanOptimizations::tryRemoveRedundantDistinct(DB::QueryPlan::Node*, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x0000000013624cf2 in /usr/bin/clickhouse
2024.06.25 19:44:40.451565 [ 26552 ] {} <Fatal> BaseDaemon: 5. DB::QueryPlanOptimizations::optimizeTreeFirstPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x00000000135fcaf6 in /usr/bin/clickhouse
2024.06.25 19:44:40.452100 [ 26552 ] {} <Fatal> BaseDaemon: 6. DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x000000001358a82d in /usr/bin/clickhouse
2024.06.25 19:44:40.452116 [ 26552 ] {} <Fatal> BaseDaemon: 7. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x000000001358974e in /usr/bin/clickhouse
2024.06.25 19:44:40.452583 [ 26552 ] {} <Fatal> BaseDaemon: 8. DB::FutureSetFromSubquery::buildOrderedSetInplace(std::shared_ptr<DB::Context const> const&) @ 0x000000001200af45 in /usr/bin/clickhouse
2024.06.25 19:44:40.453062 [ 26552 ] {} <Fatal> BaseDaemon: 9. DB::KeyCondition::extractAtomFromTree(DB::RPNBuilderTreeNode const&, DB::KeyCondition::RPNElement&) @ 0x0000000012b94d17 in /usr/bin/clickhouse
2024.06.25 19:44:40.453585 [ 26552 ] {} <Fatal> BaseDaemon: 10. DB::RPNBuilder<DB::KeyCondition::RPNElement>::traverseTree(DB::RPNBuilderTreeNode const&) @ 0x0000000012ba259d in /usr/bin/clickhouse
2024.06.25 19:44:40.453597 [ 26552 ] {} <Fatal> BaseDaemon: 11. DB::RPNBuilder<DB::KeyCondition::RPNElement>::traverseTree(DB::RPNBuilderTreeNode const&) @ 0x0000000012ba28fc in /usr/bin/clickhouse
2024.06.25 19:44:40.453606 [ 26552 ] {} <Fatal> BaseDaemon: 12. DB::RPNBuilder<DB::KeyCondition::RPNElement>::traverseTree(DB::RPNBuilderTreeNode const&) @ 0x0000000012ba28fc in /usr/bin/clickhouse
2024.06.25 19:44:40.454069 [ 26552 ] {} <Fatal> BaseDaemon: 13. DB::KeyCondition::KeyCondition(std::shared_ptr<DB::ActionsDAG>, std::shared_ptr<DB::Context const>, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::ExpressionActions> const&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>, bool, bool) @ 0x0000000012b8e8b0 in /usr/bin/clickhouse
2024.06.25 19:44:40.454531 [ 26552 ] {} <Fatal> BaseDaemon: 14. DB::buildIndexes(std::optional<DB::ReadFromMergeTree::Indexes>&, std::shared_ptr<DB::ActionsDAG>, DB::MergeTreeData const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryInfo const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x00000000135a845e in /usr/bin/clickhouse
2024.06.25 19:44:40.454985 [ 26552 ] {} <Fatal> BaseDaemon: 15. DB::ReadFromMergeTree::applyFilters() @ 0x00000000135a72a5 in /usr/bin/clickhouse
2024.06.25 19:44:40.455371 [ 26552 ] {} <Fatal> BaseDaemon: 16. DB::QueryPlanOptimizations::optimizeTreeThirdPass(DB::QueryPlan&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x00000000135fd9fb in /usr/bin/clickhouse
2024.06.25 19:44:40.455381 [ 26552 ] {} <Fatal> BaseDaemon: 17. DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x000000001358a84b in /usr/bin/clickhouse
2024.06.25 19:44:40.455390 [ 26552 ] {} <Fatal> BaseDaemon: 18. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x000000001358974e in /usr/bin/clickhouse
2024.06.25 19:44:40.455872 [ 26552 ] {} <Fatal> BaseDaemon: 19. DB::InterpreterSelectWithUnionQuery::execute() @ 0x0000000011f7f759 in /usr/bin/clickhouse
2024.06.25 19:44:40.455888 [ 26552 ] {} <Fatal> BaseDaemon: 20. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000122c5ba8 in /usr/bin/clickhouse
2024.06.25 19:44:40.455906 [ 26552 ] {} <Fatal> BaseDaemon: 21. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x00000000122c8935 in /usr/bin/clickhouse
2024.06.25 19:44:40.455919 [ 26552 ] {} <Fatal> BaseDaemon: 22. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x00000000130e264d in /usr/bin/clickhouse
2024.06.25 19:44:40.455933 [ 26552 ] {} <Fatal> BaseDaemon: 23. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x00000000130e7049 in /usr/bin/clickhouse
2024.06.25 19:44:40.455943 [ 26552 ] {} <Fatal> BaseDaemon: 24. DB::HTTPServerConnection::run() @ 0x0000000013157fb2 in /usr/bin/clickhouse
2024.06.25 19:44:40.455954 [ 26552 ] {} <Fatal> BaseDaemon: 25. Poco::Net::TCPServerConnection::start() @ 0x0000000015b48634 in /usr/bin/clickhouse
2024.06.25 19:44:40.455963 [ 26552 ] {} <Fatal> BaseDaemon: 26. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b49831 in /usr/bin/clickhouse
2024.06.25 19:44:40.456299 [ 26552 ] {} <Fatal> BaseDaemon: 27. Poco::PooledThread::run() @ 0x0000000015c80467 in /usr/bin/clickhouse
2024.06.25 19:44:40.456831 [ 26552 ] {} <Fatal> BaseDaemon: 28. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c7e73c in /usr/bin/clickhouse
2024.06.25 19:44:40.457079 [ 26552 ] {} <Fatal> BaseDaemon: 29. start_thread @ 0x0000000000007ea5 in /usr/lib64/libpthread-2.17.so
2024.06.25 19:44:40.457435 [ 26552 ] {} <Fatal> BaseDaemon: 30. clone @ 0x00000000000fe9fd in /usr/lib64/libc-2.17.so
2024.06.25 19:44:40.466360 [ 112745 ] {} <Trace> TCPSHandlerFactory: TCP Request. Address: [::ffff:10.14.38.110]:36922
```

```
2024.06.27 18:38:28.254251 [ 3208 ] {} <Fatal> BaseDaemon: Address: 0x30. Access: read. Address not mapped to object.
2024.06.27 18:38:28.254257 [ 3208 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000011591ec4 0x0000000013625e8c 0x0000000013624cf2 0x00000000135fcaf6 0x000000001358a82d 0x000000001358974e 0x0000000011f7f759 0x00000000122c5ba8 0x00000000122c8935 0x00000000130e264d 0x00000000130e7049 0x0000000013157fb2 0x0000000015b48634 0x0000000015b49831 0x0000000015c80467 0x0000000015c7e73c 0x00007fe308553ea5 0x00007fe30827c9fd
```

```2024.06.27 18:47:21.665846 [ 8893 ] {} <Fatal> BaseDaemon: Address: 0x30. Access: read. Address not mapped to object.
2024.06.27 18:47:21.665856 [ 8893 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000011591ec4 0x0000000013625e8c 0x0000000013624cf2 0x00000000135fcaf6 0x000000001358a82d 0x000000001358974e 0x0000000011f7f759 0x00000000122c5ba8 0x00000000122c8935 0x00000000130e264d 0x00000000130e7049 0x0000000013157fb2 0x0000000015b48634 0x0000000015b49831 0x0000000015c80467 0x0000000015c7e73c 0x00007f9b30760ea5 0x00007f9b304899fd
2024.06.27 18:47:21.665932 [ 8893 ] {} <Fatal> BaseDaemon: 2. DB::FindOriginalNodeForOutputName::FindOriginalNodeForOutputName(std::shared_ptr<DB::ActionsDAG> const&) @ 0x0000000011591ec4 in /usr/bin/clickhouse
2024.06.27 18:47:21.665972 [ 8893 ] {} <Fatal> BaseDaemon: 3. DB::QueryPlanOptimizations::(anonymous namespace)::compareAggregationKeysWithDistinctColumns(std::vector<String, std::allocator<String>> const&, std::set<std::basic_string_view<char, std::char_traits<char>>, std::less<std::basic_string_view<char, std::char_traits<char>>>, std::allocator<std::basic_string_view<char, std::char_traits<char>>>> const&, std::vector<std::vector<std::shared_ptr<DB::ActionsDAG>, std::allocator<std::shared_ptr<DB::ActionsDAG>>>, std::allocator<std::vector<std::shared_ptr<DB::ActionsDAG>, std::allocator<std::shared_ptr<DB::ActionsDAG>>>>>) @ 0x0000000013625e8c in /usr/bin/clickhouse
2024.06.27 18:47:21.665992 [ 8893 ] {} <Fatal> BaseDaemon: 4. DB::QueryPlanOptimizations::tryRemoveRedundantDistinct(DB::QueryPlan::Node*, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x0000000013624cf2 in /usr/bin/clickhouse
2024.06.27 18:47:21.666011 [ 8893 ] {} <Fatal> BaseDaemon: 5. DB::QueryPlanOptimizations::optimizeTreeFirstPass(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::list<DB::QueryPlan::Node, std::allocator<DB::QueryPlan::Node>>&) @ 0x00000000135fcaf6 in /usr/bin/clickhouse
2024.06.27 18:47:21.666433 [ 8893 ] {} <Fatal> BaseDaemon: 6. DB::QueryPlan::optimize(DB::QueryPlanOptimizationSettings const&) @ 0x000000001358a82d in /usr/bin/clickhouse
2024.06.27 18:47:21.666449 [ 8893 ] {} <Fatal> BaseDaemon: 7. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x000000001358974e in /usr/bin/clickhouse
2024.06.27 18:47:21.666469 [ 8893 ] {} <Fatal> BaseDaemon: 8. DB::InterpreterSelectWithUnionQuery::execute() @ 0x0000000011f7f759 in /usr/bin/clickhouse
2024.06.27 18:47:21.666486 [ 8893 ] {} <Fatal> BaseDaemon: 9. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000122c5ba8 in /usr/bin/clickhouse
2024.06.27 18:47:21.666503 [ 8893 ] {} <Fatal> BaseDaemon: 10. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x00000000122c8935 in /usr/bin/clickhouse
2024.06.27 18:47:21.666524 [ 8893 ] {} <Fatal> BaseDaemon: 11. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x00000000130e264d in /usr/bin/clickhouse
2024.06.27 18:47:21.666534 [ 8893 ] {} <Fatal> BaseDaemon: 12. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x00000000130e7049 in /usr/bin/clickhouse
2024.06.27 18:47:21.666547 [ 8893 ] {} <Fatal> BaseDaemon: 13. DB::HTTPServerConnection::run() @ 0x0000000013157fb2 in /usr/bin/clickhouse
2024.06.27 18:47:21.666567 [ 8893 ] {} <Fatal> BaseDaemon: 14. Poco::Net::TCPServerConnection::start() @ 0x0000000015b48634 in /usr/bin/clickhouse
2024.06.27 18:47:21.666577 [ 8893 ] {} <Fatal> BaseDaemon: 15. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b49831 in /usr/bin/clickhouse
2024.06.27 18:47:21.666594 [ 8893 ] {} <Fatal> BaseDaemon: 16. Poco::PooledThread::run() @ 0x0000000015c80467 in /usr/bin/clickhouse
2024.06.27 18:47:21.666608 [ 8893 ] {} <Fatal> BaseDaemon: 17. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c7e73c in /usr/bin/clickhouse
2024.06.27 18:47:21.666650 [ 8893 ] {} <Fatal> BaseDaemon: 18. start_thread @ 0x0000000000007ea5 in /usr/lib64/libpthread-2.17.so
2024.06.27 18:47:21.666685 [ 8893 ] {} <Fatal> BaseDaemon: 19. clone @ 0x00000000000fe9fd in /usr/lib64/libc-2.17.so
2024.06.27 18:47:21.673566 [ 8548 ] {} <Trace> TCPSHandlerFactory: TCP Request. Address: [::ffff:10.14.38.125]:46842
```

```
2024.06.19 01:02:05.639959 [ 81178 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.06.19 01:02:05.640011 [ 81178 ] {} <Fatal> BaseDaemon: (version 23.8.15.35 (official build), build id: 490DD83183A7376BE2DE1B9EF16E86C55C52C59E, git hash: 060ff8e813a4a16a540063127f8c91e2108d9adf) (from thread 42644) Received signal 11
2024.06.19 01:02:05.640064 [ 81178 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.06.19 01:02:05.640076 [ 81178 ] {} <Fatal> BaseDaemon: Address: 0x48. Access: read. Address not mapped to object.
2024.06.19 01:02:05.640086 [ 81178 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000012c826b4 0x00000000110502da 0x0000000010b1248f 0x000000000c70283e 0x000000000c7062fc 0x000000000c704b44 0x00007fb6e4276ea5 0x00007fb6e3f9f9fd
2024.06.19 01:02:05.640092 [ 81178 ] {} <Fatal> BaseDaemon: ########################################
2024.06.19 01:02:05.640166 [ 81178 ] {} <Fatal> BaseDaemon: (version 23.8.15.35 (official build), build id: 490DD83183A7376BE2DE1B9EF16E86C55C52C59E, git hash: 060ff8e813a4a16a540063127f8c91e2108d9adf) (from thread 42644) (no query) Received signal Segmentation fault (11)
2024.06.19 01:02:05.640179 [ 81178 ] {} <Fatal> BaseDaemon: Address: 0x48. Access: read. Address not mapped to object.
2024.06.19 01:02:05.640185 [ 81178 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000012c826b4 0x00000000110502da 0x0000000010b1248f 0x000000000c70283e 0x000000000c7062fc 0x000000000c704b44 0x00007fb6e4276ea5 0x00007fb6e3f9f9fd
2024.06.19 01:02:05.641594 [ 81178 ] {} <Fatal> BaseDaemon: 2. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTreeData::clearPartsFromFilesystemImpl(std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>> const&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>*)::$_4, void ()>>(std::__function::__policy_storage const*) @ 0x0000000012c826b4 in /usr/bin/clickhouse
2024.06.19 01:02:05.642132 [ 81178 ] {} <Fatal> BaseDaemon: 3. std::__packaged_task_func<std::function<std::future<void> (std::function<void ()>&&, Priority)> DB::threadPoolCallbackRunner<void, std::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, String const&)::'lambda'(std::function<void ()>&&, Priority)::operator()(std::function<void ()>&&, Priority)::'lambda'(), std::allocator<std::function<std::future<void> (std::function<void ()>&&, Priority)> DB::threadPoolCallbackRunner<void, std::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, String const&)::'lambda'(std::function<void ()>&&, Priority)::operator()(std::function<void ()>&&, Priority)::'lambda'()>, void ()>::operator()() @ 0x00000000110502da in /usr/bin/clickhouse
2024.06.19 01:02:05.642157 [ 81178 ] {} <Fatal> BaseDaemon: 4. std::packaged_task<void ()>::operator()() @ 0x0000000010b1248f in /usr/bin/clickhouse
2024.06.19 01:02:05.642643 [ 81178 ] {} <Fatal> BaseDaemon: 5. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c70283e in /usr/bin/clickhouse
2024.06.19 01:02:05.642680 [ 81178 ] {} <Fatal> BaseDaemon: 6. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c7062fc in /usr/bin/clickhouse
2024.06.19 01:02:05.643209 [ 81178 ] {} <Fatal> BaseDaemon: 7. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c704b44 in /usr/bin/clickhouse
2024.06.19 01:02:05.643539 [ 81178 ] {} <Fatal> BaseDaemon: 8. start_thread @ 0x0000000000007ea5 in /usr/lib64/libpthread-2.17.so
2024.06.19 01:02:05.643906 [ 81178 ] {} <Fatal> BaseDaemon: 9. clone @ 0x00000000000fe9fd in /usr/lib64/libc-2.17.so
2024.06.19 01:02:06.392768 [ 81178 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: E458CF4FDFC82BEC79A43457D17F6144)
2024.06.19 01:02:06.392801 [ 81178 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
```

**Does it reproduce on the most recent release?**
yes

**How to reproduce**
i don't know

**Comment by rschu1ze** [comment] 2024-06-27 21:41
This looks like it is associated with / caused by specific queries. It would be helpful if you could identify these from the crashdumps or query log.

**Comment by alexryndin** [comment] 2024-07-17 11:14
@rschu1ze the problem disappeared after upgrade to 24.3
but still present in 23.8
Here is a query which leads to a segfault (all names and ids have been replaced with single-letter):
```WITH
    bm AS
    (
        SELECT
            toUInt64(_a) AS _a,
            _b,
            _c,
            _e,
            _d
        FROM default.tablename
        WHERE (date >= (today() - toIntervalDay(1))) AND (dictGetInt8('A', 'B', _d) = 1)
    ),
    precalc AS
    (
        SELECT
            id,
            _a,
            datetime,
            _b,
            _c,
            _e,
            _d,
            argMin(_g, id) AS _g,
            argMin(_x, id) AS _x
        FROM default.tablename2 AS t2
        RIGHT JOIN bm ON bm._a = t2._a
        WHERE (date >= (today() - toIntervalDay(1))) AND (action = 'create')
        GROUP BY
            id,
            _a,
            datetime,
            _b,
            _c,
            _e,
            _d
    ),
    precalc_2 AS
    (
        SELECT
            precalc.*,
            _b = 0 AS _f,
            multiIf(_g != 10002, _g, NULL) AS _p,
            multiIf((_x != 0) AND (_g != 10002), _g, NULL) AS _j,
            topK(1, 10000.)(_j) OVER (PARTITION BY _c, _b)[1] AS _h,
            topK(1, 10000.)(_p) OVER (PARTITION BY _f, _b)[1] AS _o,
            multiIf(_g != 10002, _g, (_g = 10002) AND (_h != 186) AND (_h != 0), _h, (_g = 10002) AND (_h = 0) AND (_b != 0) AND (_o != 186) AND (_o != 0), _o, _g) AS _z,
            multiIf(_z = _h, 'A', _z = _o, 'C', 'D') AS where_from
        FROM precalc
    )
SELECT DISTINCT
    _a,
    _d,
    _c,
    _g,
    where_from,
    _h,
    _o,
    _z
FROM precalc_2
WHERE _z != _g
FORMAT CSVWithNames
```

**Comment by Algunenano** [comment] 2024-12-10 17:20
23.8 is out of support, so closing this as a mystery about when it was fixed

**Closed by Algunenano** 2024-12-10 17:20 UTC
Labels: st-need-info, potential bug
