### ISSUE TITLE
HDFS integration with Kerberos: Cannot select from hdfs path with signal 13 error.

### ISSUE THREAD

**Issue by myabcc17** [ClickHouse/ClickHouse#40018] opened 2022-08-09 07:34 UTC
i'm create clickhouse server using clickhouse-operator on k8s.
Below config is clickhouse server config for hdfs. And keytab, xml files are successfully mounted on pod.
```
    <yandex>
      <hdfs>
        <libhdfs3_conf>/etc/clickhouse-server/hdfs/hdfs-site.xml</libhdfs3_conf>
        <hadoop_kerberos_keytab>/etc/clickhouse-server/hdfs/A.keytab</hadoop_kerberos_keytab>
        <hadoop_kerberos_principal>A@BLAH.COM</hadoop_kerberos_principal>
        <hadoop_security_authentication>kerberos</hadoop_security_authentication>
      </hdfs>
    </yandex>
```

Execute query this.
```
SELECT *
FROM hdfs('hdfs://<hdfs_url>/<hdfs_path>, 'ORC', 'id1 String, id2 String')
LIMIT 2
```

But. error is occured. Looking at the log, there seems to be no problem with kerberos auth maybe.
What's the problem??
```
2022.08.09 07:12:04.462423 [ 10 ] {7500e000-c725-44ef-a8e0-2f88fa76c59c} <Debug> executeQuery: (from 127.0.0.1:36970) SELECT * FROM hdfs('hdfs://<hdfs_url>/<hdfs_path>', 'ORC', 'id1 String, id2 String') LIMIT 2
2022.08.09 07:12:04.463445 [ 10 ] {7500e000-c725-44ef-a8e0-2f88fa76c59c} <Debug> HDFSClient: running kinit: kinit -R -t "/etc/clickhouse-server/hdfs/A.keytab" -k A@BLAH.COM|| kinit -t "/etc/clickhouse-server/hdfs/A.keytab" -k A@BLAH.COM
2022.08.09 07:12:04.465776 [ 10 ] {7500e000-c725-44ef-a8e0-2f88fa76c59c} <Error> executeQuery: Code: 302, e.displayText() = DB::Exception: Child process was terminated by signal 13 (version 21.8.10.1.altinitystable (altinity build)) (from 127.0.0.1:36970) (in query: SELECT * FROM hdfs('hdfs://<hdfs_url>/<hdfs_path>', 'ORC', 'id1 String, id2 String') LIMIT 2), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8fd5d9a in /usr/bin/clickhouse
1. DB::ShellCommand::tryWait() @ 0x90d5143 in /usr/bin/clickhouse
2. DB::HDFSBuilderWrapper::runKinit() @ 0xfab0fed in /usr/bin/clickhouse
3. DB::createHDFSBuilder(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&) @ 0xfab1857 in /usr/bin/clickhouse
4. DB::StorageHDFS::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfaa6fe2 in /usr/bin/clickhouse
5. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x10958b4e in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x104014fc in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0x103f931c in /usr/bin/clickhouse
8. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x103f8500 in /usr/bin/clickhouse
9. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x105ca7fe in /usr/bin/clickhouse
10. DB::InterpreterSelectWithUnionQuery::execute() @ 0x105cb8d1 in /usr/bin/clickhouse
11. ? @ 0x1078c8a4 in /usr/bin/clickhouse
12. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1078af43 in /usr/bin/clickhouse
13. DB::TCPHandler::runImpl() @ 0x11029d9e in /usr/bin/clickhouse
14. DB::TCPHandler::run() @ 0x1103cd39 in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0x13bb428f in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0x13bb5d1a in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0x13ce7f99 in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x13ce422a in /usr/bin/clickhouse
19. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
20. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

2022.08.09 07:12:04.466084 [ 10 ] {7500e000-c725-44ef-a8e0-2f88fa76c59c} <Error> TCPHandler: Code: 302, e.displayText() = DB::Exception: Child process was terminated by signal 13, Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8fd5d9a in /usr/bin/clickhouse
1. DB::ShellCommand::tryWait() @ 0x90d5143 in /usr/bin/clickhouse
2. DB::HDFSBuilderWrapper::runKinit() @ 0xfab0fed in /usr/bin/clickhouse
3. DB::createHDFSBuilder(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&) @ 0xfab1857 in /usr/bin/clickhouse
4. DB::StorageHDFS::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xfaa6fe2 in /usr/bin/clickhouse
5. DB::IStorage::read(DB::QueryPlan&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryInfo&, std::__1::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0x10958b4e in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x104014fc in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0x103f931c in /usr/bin/clickhouse
8. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x103f8500 in /usr/bin/clickhouse
9. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x105ca7fe in /usr/bin/clickhouse
10. DB::InterpreterSelectWithUnionQuery::execute() @ 0x105cb8d1 in /usr/bin/clickhouse
11. ? @ 0x1078c8a4 in /usr/bin/clickhouse
12. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1078af43 in /usr/bin/clickhouse
13. DB::TCPHandler::runImpl() @ 0x11029d9e in /usr/bin/clickhouse
14. DB::TCPHandler::run() @ 0x1103cd39 in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0x13bb428f in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0x13bb5d1a in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0x13ce7f99 in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x13ce422a in /usr/bin/clickhouse
19. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
20. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

**Comment by melvynator** [comment] 2022-08-10 08:53
@myabcc17 Can you write data to HDFS?

**Comment by myabcc17** [comment] 2022-08-10 09:04
@melvynator An attempt was made to execute insert query, but the same error occurred.
```
CREATE TABLE aa (id1 String, id2 String) ENGINE = HDFS('hdfs://<hdfs_url>/<hdfs_path>', 'ORC')

INSERT INTO aa VALUES ('1', '1')
```

**Comment by melvynator** [comment] 2022-08-10 09:12
I suspect it's a duplicate of: https://github.com/ClickHouse/ClickHouse/issues/34445

**Comment by myabcc17** [comment] 2022-08-10 09:21
@melvynator 
I've already read this article, but I don't see a clear solution.

Was this the solution after all?
> Did you try this without HA auth? If not -- can you please try?

**Comment by melvynator** [comment] 2022-08-10 09:43
We haven't heard back from the user so I'm not really sure. Maybe it's wort keeping the discussion in the same thread. 

> Did you try this without HA auth? If not -- can you please try?

If you can try that and let us know there that would be helpful.

**Comment by alexey-milovidov** [comment] 2022-08-10 17:55
> 21.8.10.1.altinitystable (altinity build)

We don't support alternative builds of ClickHouse.

**Closed by alexey-milovidov** 2022-08-10 17:55 UTC
Labels: question, alternative build, minor, support-services
