### ISSUE TITLE
ReplicatedVersionedCollapsingMergeTree Merge exception

### ISSUE THREAD

**Issue by yanye666** [ClickHouse/ClickHouse#25158] opened 2021-06-10 05:26 UTC
version:20.3.10.75/21.6.3.14

I have a table：

> `create table test
(
    customer_id Int32,
    detail_id   String,
    name        String,
    year        UInt16,
    month       UInt32,
    day         UInt32,
    sign        Int8,
    version     Int64,
    sic_types   Array(String) default []
)
    engine = ReplicatedVersionedCollapsingMergeTree('/clickhouse/tables/1/test', 'test1', sign,
             version) PARTITION BY (year, month) ORDER BY (customer_id, year, month, day, detail_id) SETTINGS index_granularity = 8192;`

Steps to reproduce

- Insert 8192 rows of data with the same version, they are all the same, except for the ‘name’ column, my order by (customer_id, year, month, day, detail_id), my data detail_id column is an empty string.

- execute 
`insert into test select customer_id, detail_id, name, year, month, day, -1, version, sic_types from test;`

- execute 
`select customer_id, year, month, day, detail_id, sign,version, count(1)
from test final
group by customer_id, year, month, day, detail_id, sign,version;`

result:

> 1	2021	202104	20210405	""	-1	1623302545	2
1	2021	202104	20210405	""	1	1623302545	2

It only merges 8190 rows of data, which is strange, is it caused by a large amount of repeated order key data? When I adjust the inserted data to <=8190, it can all be merged.

**Comment by yanye666** [comment] 2021-06-11 01:47
Even if ‘detail_id’ is not an empty string, but the same, there will be this problem

**Comment by KochetovNicolai** [comment] 2021-06-11 12:49
Hi!
It is expected behaviour (or implementation detail, if you wish). It would be very inexpensive to merge all the rows in case you have, like 1 billion same rows with +1 sign, and then 1 billion same rows with -1 sign. Implementation uses a window, it's size about 8192 (minus 3, probably). Only rows are in the same window could be merged.

It works perfectly well for data parts merging, cause you don't have a guarantee that all data will be merged anyway. For FINAL, there is a possible issue, when in your case not rows will be merged. 

I think I am not going to fix it soon.

**Comment by yanye666** [comment] 2021-06-11 13:00
> 你好！
> 这是预期的行为（或实现细节，如果您愿意）。如果您有的话，合并所有行将是非常便宜的，例如 10 亿个带有 +1 符号的相同行，然后是 10 亿个带有 -1 符号的相同行。实现使用一个窗口，它的大小约为 8192（可能是负 3）。只有同一窗口中的行才能合并。
> 
> 它非常适合数据部分合并，因为您无法保证无论如何都会合并所有数据。对于 FINAL，可能存在一个问题，在您的情况下，不会合并行。
> 
> 我想我不会很快修复它。

ok,
How does this window work? In other words, this window always reads data in the background. Only when the data that needs to be merged is read under the same window, will the merge succeed? Is it possible that the 100 million pieces of data will eventually be merged?
Adding a final query is problematic for this kind of result. Do you think this is not a bug? I saw that you deleted the ‘bug’ tag,

**Comment by KochetovNicolai** [comment] 2021-06-11 14:09
How does this window work?

Let's N = 8189
We keep N consecutive rows in memory. We can collapse only those rows. When we collapse any two rows, we read two more new. When there are no rows which can be collapsed, we write first row in window and read another one.
Implementation is here: 
https://github.com/ClickHouse/ClickHouse/blob/v21.5.6.6-stable/src/Processors/Merges/Algorithms/VersionedCollapsingAlgorithm.cpp#L60-L155

> Only when the data that needs to be merged is read under the same window, will the merge succeed? 

Generally, yes.

> Is it possible that the 100 million pieces of data will eventually be merged?

Yes, with several merges.

> Do you think this is not a bug?

It works the way it was intended. Probably, we should mention in documentation about FINAL for this engine.
Also, it is possible to implement separate code for final, which will always merge everything (but probably consume a lot of memory).

**Comment by yanye666** [comment] 2021-06-11 16:05
> 图片这个是如何工作的？
> 
> 让我们 N = 8189
> 我们在内存中保留 N 连续行。我们只能收起那些行。当我们收起任何两行时，我们会写下另外两行。当没有可以收起的行时，我们在窗口中入第一行并读取另一行。
> 实现在这里：[https](https://github.com/ClickHouse/ClickHouse/blob/v21.5.6.6-stable/src/Processors/Merges/Algorithms/VersionedCollapsingAlgorithm.cpp#L60-L155) :
> [//github.com/ClickHouse/ClickHouse/blob/v21.5.6.6-stable/src/Processors/Merges/Algorithms/VersionedCollapsingAlgorithm.cpp#L60- L155](https://github.com/ClickHouse/ClickHouse/blob/v21.5.6.6-stable/src/Processors/Merges/Algorithms/VersionedCollapsingAlgorithm.cpp#L60-L155)
> 
> > 只能在同一个窗口下读取了需要合并的数据，才能合并成功？
> 
> 看，是的。
> 
> > 1亿条数据有没有可能最终合并？
> 
> 是的，有几次合并。
> 
> > 你认为这不是一个错误吗？
> 
> 它按照预期的方式工作。可能，我们应该在有关此引擎的最终文档中提到。
> 此外，可以作为最终实现单独的代码，这将合并所有内容（但可能会消耗大量内存）。

> What level is this window? In other words, does this window serve a group of rows of the same sort key? Still serve this table?
> If it only acts on the rows of the same sort key, then the memory will not be released when the 8189 rows can be merged?
> 

> How does this window work?
> 
> Let's N = 8189
> We keep N consecutive rows in memory. We can collapse only those rows. When we collapse any two rows, we read two more new. When there are no rows which can be collapsed, we write first row in window and read another one.
> Implementation is here:
> https://github.com/ClickHouse/ClickHouse/blob/v21.5.6.6-stable/src/Processors/Merges/Algorithms/VersionedCollapsingAlgorithm.cpp#L60-L155
> 
> > Only when the data that needs to be merged is read under the same window, will the merge succeed?
> 
> Generally, yes.
> 
> > Is it possible that the 100 million pieces of data will eventually be merged?
> 
> Yes, with several merges.
> 
> > Do you think this is not a bug?
> 
> It works the way it was intended. Probably, we should mention in documentation about FINAL for this engine.
> Also, it is possible to implement separate code for final, which will always merge everything (but probably consume a lot of memory).

> What level is this window? In other words, does this window serve a group of rows of the same sort key? Still serve this table?
> If it only acts on the rows of the same sort key, then the memory will not be released when the 8189 rows can be merged?
> ’we can collapse only those rows. When we collapse any two rows, we read two more new.‘ ,,,For this sentence, my understanding is that if the read data can be merged, it will continue to read after the merge? How does this explain that only 8189 lines can be merged? Should he be able to merge forever (or do I understand it incorrectly)?
>''When FINAL is specified, ClickHouse fully merges the data before returning the result and thus performs all data transformations that happen during merges for the given table engine.'',,,I think ‘final’ represents the final result, which is unchangeable. According to what you said, the result of my query may actually be merged, which does not match the description of the document.

**Closed** 2021-06-12 01:39 UTC
Labels: question, question-answered, st-wontfix

**Comment by yanye666** [comment] 2021-06-13 03:31
Hello, if memory is taken into consideration, if you do not modify this implementation, it is recommended to mark the related issues in'final'/'order by'. The value of the same sort key should not exceed 8190 rows, otherwise incorrect results will occur when using'final'  @alexey-milovidov @KochetovNicolai
