### ISSUE TITLE
Invalid json output with FORMAT JSON

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#13369] opened 2020-08-05 10:24 UTC
Easy to reproduce:
### 20.3.13
```
SELECT 1
FORMAT JSON

{
        "meta":
        [
                {
                        "name": "1",
                        "type": "UInt8"
                }
        ],

        "data":
        [
                {
                        "1": 1
                }
        ],

        "rows": 1,

        "statistics":
        {
                "elapsed": 0.000203731,
                "rows_read": 1,
                "bytes_read": 1
        }
}
```

### 20.4.5
```
:) select 1 format JSON

SELECT 1
FORMAT JSON

{
        "meta":
        [
                {
                        "name": "1",
                        "type": "UInt8"
                }
        ],

        "data":
        [
                {
                        "1": 1
>>>>>>>> no closing bracket <<<<<<<<<<
        ],

        "rows": 1,

        "statistics":
        {
                "elapsed": 0.000771732,
                "rows_read": 1,
                "bytes_read": 1
        }
}
```
### master
```

SELECT 1
FORMAT JSON

{
        "meta":
        [
                {
                        "name": "1",
                        "type": "UInt8"
                }
        ],

        "data":
        [
                {
                        "1": 1
>>>>>>>> no closing bracket <<<<<<<<<<
        ],

        "rows": 1,

        "statistics":
        {
                "elapsed": 0.00103364,
                "rows_read": 1,
                "bytes_read": 1
        }
}

```

**Comment by CurtizJ** [comment] 2020-08-05 11:04
Duplicate of #12562

**Closed** 2020-08-05 11:09 UTC
Labels: bug, duplicate
