### ISSUE TITLE
neighbor() function - unexpected behaviour

### ISSUE THREAD

**Issue by radiatorius2048** [ClickHouse/ClickHouse#8975] opened 2020-02-03 15:38 UTC
NULL values in neighbor() function results.

**How to reproduce**

**_select item, num,neighbor(num, -1) as prev_num, updated_at
from (
select item, num,updated_at from test_table 
where item = '382958' 
order by updated_at
)_**
* Which ClickHouse server version to use **v19.17.4.11**
* Which interface to use, if matters **DBeaver v 6.3.3.202001191557**
* `CREATE TABLE` statements for all tables involved

**CREATE TABLE test_table (
`number` UUID DEFAULT generateUUIDv4(),
 `id` UInt32,
 `item` Nullable(String),
 `num` Nullable(Decimal(18,4)),
 `updated_at` DateTime
) ENGINE = MergeTree() PARTITION BY toYYYYMM(updated_at) ORDER BY updated_at SETTINGS index_granularity = 8192**

* Queries to run that lead to unexpected result
**_select item, num,neighbor(num, -1) as prev_num, updated_at
from (
select item, num,updated_at from test_table 
where item = '382958' 
order by updated_at
)_**

**Expected behavior**
**expected result:**
_item | num | prev_num | updated_at
382958 | 11.6600 |   | 2020-01-03 12:13
382958 | 8.6800 | 11.6600 | 2020-01-03 12:41
382958 | 8.6800 | 8.6800 | 2020-01-03 12:41
382958 | 8.6100 | 8.6800 | 2020-01-03 13:38
382958 | 8.6100 | 8.6100 | 2020-01-03 13:38
382958 | 8.6800 | 8.6100 | 2020-01-03 13:41
382958 | 8.6800 | 8.6800 | 2020-01-03 13:41
382958 | 8.6100 | 8.6800 | 2020-01-03 13:42
382958 | 8.6100 | 8.6100 | 2020-01-03 13:42
382958 | 8.6800 | 8.6100 | 2020-01-27 14:37
382958 | 11.6600 | 8.6800 | 2020-01-27 14:38
382958 | 8.6100 | 11.6600 | 2020-01-27 14:40
382958 | 8.6100 | 8.6100 | 2020-01-27 15:36
382958 | 8.6800 | 8.6100 | 2020-01-27 15:41
382958 | 8.6100 | 8.6800 | 2020-01-27 16:36
382958 | 8.6100 | 8.6100 | 2020-01-27 17:40
382958 | 8.6800 | 8.6100 | 2020-01-27 18:40
382958 | 8.6800 | 8.6800 | 2020-01-27 18:43
382958 | 8.4100 | 8.6800 | 2020-01-28 07:10
382958 | 8.4100 | 8.4100 | 2020-01-28 07:11_

**actual result:**
_item | num | prev_num | updated_at
382958 | 11.6600 |   | 2020-01-03 12:13
382958 | 8.6800 | 11.6600 | 2020-01-03 12:41
382958 | 8.6800 | 8.6800 | 2020-01-03 12:41
382958 | 8.6100 |   | 2020-01-03 13:38
382958 | 8.6100 | 8.6100 | 2020-01-03 13:38
382958 | 8.6800 | 8.6100 | 2020-01-03 13:41
382958 | 8.6800 | 8.6800 | 2020-01-03 13:41
382958 | 8.6100 | 8.6800 | 2020-01-03 13:42
382958 | 8.6100 | 8.6100 | 2020-01-03 13:42
382958 | 8.6800 |   | 2020-01-27 14:37
382958 | 11.6600 |   | 2020-01-27 14:38
382958 | 8.6100 | 11.6600 | 2020-01-27 14:40
382958 | 8.6100 |   | 2020-01-27 15:36
382958 | 8.6800 | 8.6100 | 2020-01-27 15:41
382958 | 8.6100 | 8.6800 | 2020-01-27 16:36
382958 | 8.6100 |   | 2020-01-27 17:40
382958 | 8.6800 |   | 2020-01-27 18:40
382958 | 8.6800 |   | 2020-01-27 18:43
382958 | 8.4100 |   | 2020-01-28 07:10
382958 | 8.4100 |   | 2020-01-28 07:11_

**Comment by den-crane** [comment] 2020-02-03 20:57
Check results with `set max_block_size=131072`

https://clickhouse.tech/docs/en/query_language/functions/other_functions/#other_functions-
runningdifference

runningDifference, neighbor, etc -- reset their value with each block.

**Comment by radiatorius2048** [comment] 2020-02-04 10:03
I tried the second option - all right, thanks.

**Comment by den-crane** [comment] 2020-02-04 15:10
Then it's a real bug and should be fixed

**Comment by den-crane** [comment] 2020-02-04 16:40
Though it's not a bug after all.

optimize_read_in_order=1 --  produces many blocks 
optimize_read_in_order=0 --  produces less blocks 

STR:

```
CREATE TABLE test_table (num Nullable(Decimal(18,4)), 
item Nullable(String), updated_at DateTime) 
ENGINE = MergeTree()  PARTITION BY toYYYYMM(updated_at) 
ORDER BY updated_at SETTINGS index_granularity = 8192;

insert into test_table select toDecimal32(number,4), toString(number%101), now()+number from numbers(100000)

select item, num,neighbor(num, -1) as prev_num, updated_at
from (
select item, num,updated_at from test_table
where item = '0'
order by updated_at
) where identity(prev_num) is null

┌─item─┬────num─┬─prev_num─┬──────────updated_at─┐
│ 0    │ 0.0000 │     ᴺᵁᴸᴸ │ 2020-02-04 16:38:56 │
└──────┴────────┴──────────┴─────────────────────┘
┌─item─┬────────num─┬─prev_num─┬──────────updated_at─┐
│ 0    │ 57368.0000 │     ᴺᵁᴸᴸ │ 2020-02-05 08:35:04 │
└──────┴────────────┴──────────┴─────────────────────┘
┌─item─┬────────num─┬─prev_num─┬──────────updated_at─┐
│ 0    │ 98374.0000 │     ᴺᵁᴸᴸ │ 2020-02-05 19:58:30 │
└──────┴────────────┴──────────┴─────────────────────┘


select item, num,neighbor(num, -1) as prev_num, updated_at
from (
select item, num,updated_at from test_table
where item = '0'
order by updated_at
) where identity(prev_num) is null settings optimize_read_in_order=0;
┌─item─┬────num─┬─prev_num─┬──────────updated_at─┐
│ 0    │ 0.0000 │     ᴺᵁᴸᴸ │ 2020-02-04 16:38:56 │
└──────┴────────┴──────────┴─────────────────────┘
```

**Closed by den-crane** 2020-02-04 16:40 UTC
Labels: bug
