### ISSUE TITLE
Clickhouse on ARM spams libunwind: Unsupported .eh_frame_hdr version to the stdout

### ISSUE THREAD

**Issue by yard** [ClickHouse/ClickHouse#15638] opened 2020-10-05 17:57 UTC
**Describe the bug**
ARM build of Clickhouse prints a ton of `libunwind: Unsupported .eh_frame_hdr version`

**How to reproduce**
* Checkout 20.6.7.4 version
* `./configure && make && make install` librdkafka shipped with Clickhouse (couldn't get it in on ARM otherwise)
* Prepare the build `CC=clang-8 CXX=clang++-8 cmake -G Ninja -DCPPKAFKA_CMAKE_VERBOSE=ON -DENABLE_RDKAFKA=ON -DUSE_INTERNAL_RDKAFKA_LIBRARY=OFF -DRDKAFKA_INCLUDE_DIR=/usr/local/include/ ..` (using gcc leads to linker error unless shared build is chosen; the issue reproduces with shared build though)
* Build Clickhouse binary using `ninja`
* Wrap the binary up into a Docker image and start it on an ARM server

**Expected behavior**
The same x86 version (taken from official Docker Hub) does not produce these errors – thus expect the ARM version to be clear of the messages as well.

**Additional context**
The problem seems to be happening in production environment (more load, more queries) more often. As a side note, we noticed that _sometimes_ Clickhouse stops ingesting events from Kafka without anything logged to normal / error log – the only difference we noticed is the mentioned message in the stdout; thus, assuming the correlation but cannot prove direct connection. The restart of the server resumes the ingest.

**Comment by yard** [comment] 2020-10-05 18:21
Update: seems to be related to query profiler - disabling it via setting `query_profiler_real_time_period_ns` / `query_profiler_cpu_time_period_ns` to 0 makes the messages go away.

**Comment by filimonov** [comment] 2020-10-05 21:36
Today i was playing a bit with arm build ( 20.10.1.4844 from [CI](https://clickhouse.tech/docs/en/getting-started/install/#from-binaries-non-linux)) and also saw those exceptions.

**Comment by yard** [comment] 2020-10-06 08:29
I am a bit concerned since can’t this lead to more severe issues like exceptions not handling properly (since stack unwinding is involved there as well)?

**Comment by alexey-milovidov** [comment] 2020-10-06 11:52
What profiler is doing is "asynchronous unwinding" - it's more tricky than unwinding on exception.

Nevertheless, if libunwind prints these messages - it is able to detect that something is wrong with unwind tables.
If it will happen during exception handling, std::terminate will be called and the server will be terminated. It *should* work this way.

But I have to note that we don't run full CI tests for ARM. It means that support for ARM is considered experimental and you should ensure it's readiness by your own.

**Comment by yard** [comment] 2020-10-06 12:19
Thank you for the explanation! Any ideas on what we can try on our end (e.g. specific versions of libunwind, build flags, extra logging etc)? Happy to experiment and help with finding the root cause since we are really want to run our CH instance on ARM in production environment – apart from the above hiccups it seems to be doing a great job.

**Comment by alexey-milovidov** [comment] 2021-04-04 01:55
We will disable query profiler on AArch64.

**Comment by paskal** [comment] 2022-04-23 11:00
To disable it, add a file with the following content into `/etc/clickhouse-server/config.d/clickhouse-issue-15638.xml`:

```
<clickhouse>
    <profiles>
        <default>
            <query_profiler_real_time_period_ns>0</query_profiler_real_time_period_ns>
            <query_profiler_cpu_time_period_ns>0</query_profiler_cpu_time_period_ns>
        </default>
    </profiles>
</clickhouse>
```

**Comment by yard** [comment] 2022-05-05 09:45
Hey guys! Just pulled official ARM image from `clickhouse/clickhouse-server:22.3.5` and the spammy logs are back despite having query profiler disabled – @paskal maybe you know other settings to try out? :)

**Comment by paskal** [comment] 2022-05-05 21:35
Are you 100% sure these settings are in effect for you? Because even newer version doesn't have such errors for me.

**Comment by yard** [comment] 2022-05-06 11:38
Yep seems so:

```
SELECT
    name,
    value
FROM system.settings
WHERE name LIKE '%profiler%'

Query id: 290d4e43-9088-4a87-95b2-29a19f1fbd16

┌─name───────────────────────────────┬─value───┐
│ query_profiler_real_time_period_ns │ 0       │
│ query_profiler_cpu_time_period_ns  │ 0       │
│ memory_profiler_step               │ 4194304 │
│ memory_profiler_sample_probability │ 0       │
└────────────────────────────────────┴─────────┘
```

**Comment by paskal** [comment] 2022-05-08 19:39
I propose you try 22.4.2.1, and if it doesn't work, open a new issue as it's unlikely any further investigation will happen in this closed one. The root cause is likely different from the original.

**Comment by ryanrolds** [comment] 2022-05-17 23:54
Seeing `libunwind: Unsupported .eh_frame_hdr version` in STDOUT with `clickhouse/clickhouse-server:22.4.5.9` Docker image. Confirmed the container is the `amd64` arch image. Also confirmed that `query_profiler_real_time_period_ns` and `query_profiler_cpu_time_period_ns` are 0.

**Comment by paskal** [comment] 2022-05-23 08:33
I've checked the logs, and unfortunately, it's the case even for me after applying the workaround. I think @alexey-milovidov or someone else from the ClickHouse team should reopen the ticket so it would be known that the proposed fix doesn't work.

**Comment by filimonov** [comment] 2022-05-25 16:15
Was able to reproduce it with a simple test:

```sql
-- ClickHouse client version 22.5.1.2079 (official build).

CREATE TABLE arm_unsupported_eh_frame_hdr_on_client
(
    `t` DateTime,
    `id` UInt64
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(t)
ORDER BY id;

INSERT INTO arm_unsupported_eh_frame_hdr_on_client VALUES (now(), rand());

libunwind: Unsupported .eh_frame_hdr version
libunwind: Unsupported .eh_frame_hdr version
```

It looks like now it's reported by the client. It I remove function calls from the client - the problem goes away.

**Comment by myrrc** [comment] 2023-07-12 11:09
Reproduces on 23.5.3.24

**Comment by miensol** [comment] 2023-11-23 12:07
I'm still reproducing it via 23.9.5.29-alpine on 5.10.199-190.747.amzn2.aarch64

**Comment by alexey-milovidov** [comment] 2023-11-23 13:30
We have to close this because the original build is unofficial:

> ./configure && make && make install librdkafka

Feel free to open a new issue.

**Closed by alexey-milovidov** 2023-11-23 13:30 UTC
Labels: usability, st-fixed, comp-aarch64
