### ISSUE TITLE
filesystem error: in rename: Permission denied

### ISSUE THREAD

**Issue by mosinnik** [ClickHouse/ClickHouse#46721] opened 2023-02-22 12:23 UTC
> You have to provide the following information whenever possible.

**Describe what's wrong**

Can't do any insert queries, but creation tables work well

**Does it reproduce on recent release?**

**Enable crash reporting**

**How to reproduce**

0. Win10 + wsl2 + Ubuntu 20.04 LTS
1. install via https://clickhouse.com/docs/ru/getting-started/install/
2. change paths in config.xml 
3. runs CH server
4. open logs and see errors

table creation work well but inserting data to it failed

**Expected behavior**
no errors

**Error message and/or stacktrace**

In clickhouse error log appeared stacktrace:
```
2023.02.22 15:15:38.840100 [ 259 ] {} <Error> void DB::SystemLog<DB::AsynchronousMetricLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::AsynchronousMetricLogElement]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: Permission denied ["/mnt/k/click_wsl_data/store/4bf/4bfea8b3-dab1-42aa-b026-20c2ae92880f/tmp_insert_202302_1_1_0/"] ["/mnt/k/click_wsl_data/store/4bf/4bfea8b3-dab1-42aa-b026-20c2ae92880f/202302_1_1_0/"], Stack trace (when copying this message, always include the lines below):

0. std::__1::system_error::system_error(std::__1::error_code, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x1a352f32 in /usr/bin/clickhouse
1. ? @ 0x1a2f80c4 in /usr/bin/clickhouse
6. ? @ 0x1a2f7e9d in /usr/bin/clickhouse
7. ? @ 0x1a2fa4f0 in /usr/bin/clickhouse
8. std::__1::__fs::filesystem::__rename(std::__1::__fs::filesystem::path const&, std::__1::__fs::filesystem::path const&, std::__1::error_code*) @ 0x1a2feddd in /usr/bin/clickhouse
9. DB::DiskLocal::moveDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x1283758b in /usr/bin/clickhouse
10. DB::DataPartStorageOnDisk::rename(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, Poco::Logger*, bool, bool) @ 0x1402d788 in /usr/bin/clickhouse
11. DB::IMergeTreeDataPart::renameTo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) @ 0x14083d81 in /usr/bin/clickhouse
12. DB::MergeTreeData::preparePartForCommit(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, bool) @ 0x1411bc64 in /usr/bin/clickhouse
13. DB::MergeTreeData::renameTempPartAndReplaceImpl(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>>*) @ 0x1411d000 in /usr/bin/clickhouse
14. DB::MergeTreeData::renameTempPartAndAdd(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, std::__1::unique_lock<std::__1::mutex>&) @ 0x1411d705 in /usr/bin/clickhouse
15. DB::MergeTreeSink::finishDelayedChunk() @ 0x144fce2c in /usr/bin/clickhouse
16. ? @ 0x148b9e59 in /usr/bin/clickhouse
17. DB::ExceptionKeepingTransform::work() @ 0x148b984b in /usr/bin/clickhouse
18. DB::ExecutionThreadContext::executeTask() @ 0x146db366 in /usr/bin/clickhouse
19. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x146d047c in /usr/bin/clickhouse
20. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x146cf148 in /usr/bin/clickhouse
21. DB::SystemLog<DB::AsynchronousMetricLogElement>::flushImpl(std::__1::vector<DB::AsynchronousMetricLogElement, std::__1::allocator<DB::AsynchronousMetricLogElement>> const&, unsigned long) @ 0x1365542c in /usr/bin/clickhouse
22. DB::SystemLog<DB::AsynchronousMetricLogElement>::savingThreadFunction() @ 0x13653840 in /usr/bin/clickhouse
23. ? @ 0xdea8a8f in /usr/bin/clickhouse
24. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xde7de76 in /usr/bin/clickhouse
25. ? @ 0xde831a1 in /usr/bin/clickhouse
26. ? @ 0x7f2ca8e58609 in ?
27. clone @ 0x7f2ca8d7f293 in ?

Cannot print extra info for Poco::Exception (version 23.1.3.5 (official build))                                                                                                                                                                                                     
```

**Additional context**

CH version 23.1.3.5 (official build)
Win10 + wsl2 + Ubuntu 20.04 LTS
In wsl.conf 
```
[automount]
options = "metadata"
```
clickhouse user added to root group, data dir created by clichouse with default rights
```
drwxr-x--- 1 clickhouse clickhouse  512 Feb 22 15:15  click_wsl_data/
```
Change rights to 777 din't change anything

**Comment by nickitat** [comment] 2023-02-22 12:52
it is wsl problem
duplicate of #35036

**Closed by nickitat** 2023-02-22 12:52 UTC
Labels: potential bug
