### ISSUE TITLE
(version 23.1.3.5 (official build), build id: B9F28B1E976685BCAD291257215FC33DE8767678) (from thread 18140) (no query) Received signal Aborted (6)

### ISSUE THREAD

**Issue by JeasGo** [ClickHouse/ClickHouse#50377] opened 2023-05-31 03:33 UTC
A clickhouse  server in my cluster crashed and when I tried to restart it , it had the following error, in the log, I would like to know how I should fix it!

2023.05.31 11:20:22.556369 [ 18448 ] {} <Fatal> BaseDaemon: ########################################
2023.05.31 11:20:22.556440 [ 18448 ] {} <Fatal> BaseDaemon: (version 23.1.3.5 (official build), build id: B9F28B1E976685BCAD291257215FC33DE8767678) (from thread 18140) (no query) Received signal Aborted (6)
2023.05.31 11:20:22.556486 [ 18448 ] {} <Fatal> BaseDaemon: 
2023.05.31 11:20:22.556519 [ 18448 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f2f3c4fc5f7 0x7f2f3c4fdce8 0xe0050dc 0x1a3712c3 0x1a37122e 0x140f9e43 0x1247b0e1 0x1247e80a 0x1247f72e 0xde7de76 0xde831a1 0x7f2f3c88fdc5 0x7f2f3c5bd21d
2023.05.31 11:20:22.556605 [ 18448 ] {} <Fatal> BaseDaemon: 2. gsignal @ 0x355f7 in /usr/lib64/libc-2.17.so
2023.05.31 11:20:22.556629 [ 18448 ] {} <Fatal> BaseDaemon: 3. abort @ 0x36ce8 in /usr/lib64/libc-2.17.so
2023.05.31 11:20:22.556678 [ 18448 ] {} <Fatal> BaseDaemon: 4. ? @ 0xe0050dc in /usr/bin/clickhouse
2023.05.31 11:20:22.556696 [ 18448 ] {} <Fatal> BaseDaemon: 5. ? @ 0x1a3712c3 in /usr/bin/clickhouse
2023.05.31 11:20:22.556721 [ 18448 ] {} <Fatal> BaseDaemon: 6. std::terminate() @ 0x1a37122e in /usr/bin/clickhouse
2023.05.31 11:20:22.556748 [ 18448 ] {} <Fatal> BaseDaemon: 7. DB::MergeTreeData::loadOutdatedDataParts(bool) @ 0x140f9e43 in /usr/bin/clickhouse
2023.05.31 11:20:22.556792 [ 18448 ] {} <Fatal> BaseDaemon: 8. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x1247b0e1 in /usr/bin/clickhouse
2023.05.31 11:20:22.556809 [ 18448 ] {} <Fatal> BaseDaemon: 9. DB::BackgroundSchedulePool::threadFunction() @ 0x1247e80a in /usr/bin/clickhouse
2023.05.31 11:20:22.556833 [ 18448 ] {} <Fatal> BaseDaemon: 10. ? @ 0x1247f72e in /usr/bin/clickhouse
2023.05.31 11:20:22.556859 [ 18448 ] {} <Fatal> BaseDaemon: 11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xde7de76 in /usr/bin/clickhouse
2023.05.31 11:20:22.556877 [ 18448 ] {} <Fatal> BaseDaemon: 12. ? @ 0xde831a1 in /usr/bin/clickhouse
2023.05.31 11:20:22.556922 [ 18448 ] {} <Fatal> BaseDaemon: 13. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
2023.05.31 11:20:22.556942 [ 18448 ] {} <Fatal> BaseDaemon: 14. __clone @ 0xf621d in /usr/lib64/libc-2.17.so
2023.05.31 11:20:22.860765 [ 18448 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 2FDCD92A466BC738A5B7760B94AC828F)

**Comment by tavplubix** [comment] 2023-05-31 10:07
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/47164

You should upgrade to 23.4

**Closed by tavplubix** 2023-05-31 10:07 UTC
Labels: usability
