### ISSUE TITLE
PARTITION BY with VALUES - mutex lock failed: Invalid argument

### ISSUE THREAD

**Issue by mneedham** [ClickHouse/ClickHouse#56680] opened 2023-11-13 14:40 UTC
I'm trying to understand how to export data to files partitioned by a column and I came across this technique - https://github.com/ClickHouse/ClickHouse/issues/39081#issuecomment-1300752280
But if I try it on a local file it throws a weird exception:

$ ./clickhouse local -m
ClickHouse local version 23.11.1.275 (official build).

```
MN :) INSERT INTO TABLE FUNCTION
file('foo_{_partition_id}.csv', 'CSV', 'column1 UInt32, column2 UInt32, column3 UInt32')
PARTITION BY column3 VALUES (1, 2, 3), (3, 2, 1), (78, 43, 45);

INSERT INTO FUNCTION file('foo_{_partition_id}.csv', 'CSV', 'column1 UInt32, column2 UInt32, column3 UInt32') PARTITION BY column3 FORMAT Values

Query id: 4c757c98-8989-4378-b443-2ed77a855449

↘ Progress: 3.00 rows, 36.00 B (1.87 thousand rows/s., 22.49 KB/s.)                                                                                                                                                                                                   (0.0 CPU, 12.29 KB RAM)libc++abi: terminating due to uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
[1]    6425 abort      ./clickhouse local -m
```

**Comment by evillique** [comment] 2023-11-14 23:09
Duplicate of: https://github.com/ClickHouse/ClickHouse/issues/49684

**Closed** 2023-11-16 13:45 UTC
Labels: bug
