### ISSUE TITLE
Error in Encryption at REST in 22.6.1.1985 version

### ISSUE THREAD

**Issue by mit3211** [ClickHouse/ClickHouse#38678] opened 2022-07-01 10:42 UTC
I am using 
Clickhouse 22.6.1.1985

I create a fresh Containerised CH cluster of 4 pods from above CH release .
Enabled Encryption at Rest. Changed my default storage policies to encrypted on.
Created new DB having replicated and distributed tables.
Ingested data.
Running queries like select x,y from Tablename gives me the below exception
```Exception in thread "main" ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 40, host: clickhouse-clickhouse.clickhouse.svc.kubernetes.local, port: 8443; Code: 40. DB::Exception: Checksum doesn't match: corrupted data. Reference: b4cead3e25bfadff2840150300813519. Actual: 8b83bf749382c4f3039dc34e60fcafae. Size of compressed block: 1564: (while reading column lastVisibleTime): While executing MergeTreeInOrder. (CHECKSUM_DOESNT_MATCH) (version 22.6.1.1985 (official build))```
```
clickhouse-clickhouse-1-1-0.clickhouse-clickhouse-1-1.clickhouse.svc.kubernetes.local :) check table **myTableLocal;

CHECK TABLE testTableLocal

Query id: bca1c53e-4470-411d-9dcc-70e558058abc

┌─result─┐
│      1 │
└────────┘

1 row in set. Elapsed: 0.010 sec.

clickhouse-clickhouse-1-1-0.clickhouse-clickhouse-1-1.clickhouse.svc.kubernetes.local :) SET check_query_single_value_result = 0;

SET check_query_single_value_result = 0

Query id: fbc16b05-647b-4868-b1f4-a4a9871788a8

Ok.

0 rows in set. Elapsed: 0.002 sec.


CHECK TABLE testTableLocal

Query id: 6b792f11-c22d-40cf-b563-c8b53b7fa759

┌─part_path──┬─is_passed─┬─message─┐
│ all_0_1_33 │         1 │         │
└────────────┴───────────┴─────────┘

1 row in set. Elapsed: 0.008 sec.

```
**PLEASE FIND MY CONFIGURATIONS**
```
SELECT *
FROM system.disks

Query id: 6f51298e-cfbd-4438-97e2-0f22489d8319

┌─name────┬─path───────────────────────────┬───free_space─┬──total_space─┬─keep_free_space─┬─type──────┬─cache_path─┐
│ default │ /var/lib/clickhouse/           │ 106217193472 │ 107321753600 │               0 │ local     │            │
│ disk1   │ /var/lib/clickhouse/           │ 106217193472 │ 107321753600 │               0 │ local     │            │
│ disk2   │ /var/lib/clickhouse/encrypted/ │ 106217193472 │ 107321753600 │               0 │ encrypted │            │
└─────────┴────────────────────────────────┴──────────────┴──────────────┴─────────────────┴───────────┴────────────┘

3 rows in set. Elapsed: 0.006 sec.

 select * from system.storage_policies;

SELECT *
FROM system.storage_policies

Query id: d12d7e4f-ebf7-462a-8574-54d8479b68d1

┌─policy_name─┬─volume_name─┬─volume_priority─┬─disks─────┬─volume_type─┬─max_data_part_size─┬─move_factor─┬─prefer_not_to_merge─┐
│ default     │ default     │               1 │ ['disk2'] │ JBOD        │                  0 │           0 │
       0 │
└─────────────┴─────────────┴─────────────────┴───────────┴─────────────┴────────────────────┴─────────────┴─────────────────────┘

1 row in set. Elapsed: 0.005 sec.


    <storage_configuration>
        <disks>
            <disk1>
                <type>local</type>
                <path>/var/lib/clickhouse/</path>
            </disk1>
            <disk2>
                <type>encrypted</type>
                <disk>disk1</disk>
                <path>encrypted/</path>
                <algorithm>AES_128_CTR</algorithm>
                <key_hex id="0">XXXXXXXXXXX</key_hex>
                <current_key_id>0</current_key_id>
            </disk2>
        </disks>
        <policies>
            <default>
                <volumes>
                    <default>
                        <disk>disk2</disk>
                    </default>
                </volumes>
            </default>
        </policies>
    </storage_configuration>


```
**MY SAMPLE SCHEMA & QUERY**
```
Schema: 
 CREATE TABLE mydb.testTableLocal
(
    `a` FixedString(150),
    `b` FixedString(150),
    `c` String,
    `d` FixedString(8),
    `e` SimpleAggregateFunction(max, DateTime),
    `f` SimpleAggregateFunction(min, DateTime),
    `g` SimpleAggregateFunction(groupUniqArrayArray, Array(Date)),
    `h` SimpleAggregateFunction(anyLast, Nullable(String)),
    `i` SimpleAggregateFunction(anyLast, Nullable(UInt8)),
    `j` SimpleAggregateFunction(anyLast, Nullable(FixedString(10))),
    `k` SimpleAggregateFunction(sum, Float64)
)
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/clickhouse/mydb/table/testTableLocal/{shard}', '{replica}')
PARTITION BY tuple()
ORDER BY (a, b, d)
SETTINGS index_granularity = 8192
```
the query like ```select * from testTableLocal``` works perfectly.
But query with FINAL does not work with ReplicatedAggregatingMergeTree but I have seen it to be working in other ReplicatedMergeTree engines.
```select * from testTableLocal Final ;```
this is the error I am recieving:
```Code: 40. DB::Exception: Received from clickhouse-clickhouse:9440. DB::Exception: Checksum doesn't match: corrupted data. Reference: 7f4c768284e7500ea61c491e2c610d89. Actual: 792728a992905ad5acfdf7e2bafd7a3f. Size of compressed block: 2855: (while reading column model): While executing MergeTreeInOrder. (CHECKSUM_DOESNT_MATCH)```

**Comment by filimonov** [comment] 2022-07-18 16:07
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/38381

**Closed by filimonov** 2022-07-18 16:07 UTC
Labels: potential bug
