### ISSUE TITLE
ClickHouse inserted a partial block of data and it broke deduplication

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#27667] opened 2021-08-13 21:54 UTC
I was trying to implement deduplication of blocks, and as a test I killed clickhouse-client while it was inserting data from a TSV file using the `input` function.
ClickHouse inserted a partial block of data and it broke deduplication.
```
First (failed) attempt

-- The first block of 103425 rows got inserted
2021.08.13 20:03:19.943839 [ 30177 ] {33b2b70a-7e48-40e3-b431-d3580c5c6735} <Debug> db.table (Replicated OutputStream): Wrote block with ID '20210813_2044325925592136338_224670626381852826', 103425 rows
2021.08.13 20:03:19.977457 [ 30177 ] {33b2b70a-7e48-40e3-b431-d3580c5c6735} <Trace> db.table: Renaming temporary part tmp_insert_20210813_211_211_0 to 20210813_424_424_0.

-- Client has dropped the connection, CANCEL THE QUERY
2021.08.13 20:03:20.717922 [ 30177 ] {33b2b70a-7e48-40e3-b431-d3580c5c6735} <Information> TCPHandler: Client has dropped the connection, cancel the query.

-- However another block of 51715 rows got inserted anyway
2021.08.13 20:03:21.265719 [ 30177 ] {33b2b70a-7e48-40e3-b431-d3580c5c6735} <Debug> db.table (Replicated OutputStream): Wrote block with ID '20210813_12200150366349168987_12358441307174369580', 51715 rows
2021.08.13 20:03:21.296928 [ 30177 ] {33b2b70a-7e48-40e3-b431-d3580c5c6735} <Trace> db.table: Renaming temporary part tmp_insert_20210813_212_212_0 to 20210813_425_425_0.

-- The total number of rows reported by the query is 155140 (two blocks of data)
2021.08.13 20:03:21.510984 [ 30177 ] {33b2b70a-7e48-40e3-b431-d3580c5c6735} <Information> executeQuery: Read 155140 rows, 776.61 MiB in 4.751866542 sec., 32648 rows/sec., 163.43 MiB/sec.

-- Retry

-- The block of 103425 rows got deduplicated
2021.08.13 20:45:05.817280 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Debug> db.table (Replicated OutputStream): Wrote block with ID '20210813_2044325925592136338_224670626381852826', 103425 rows
2021.08.13 20:45:05.822455 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Information> db.table (Replicated OutputStream): Block with ID 20210813_2044325925592136338_224670626381852826 already exists locally as part 20210813_424_424_0; ignoring it.

-- The second block is 103414 rows, not 51715 rows, so it gets inserted successfully
2021.08.13 20:45:09.054894 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Debug> db.table (Replicated OutputStream): Wrote block with ID '20210813_2425217170151591480_6106430219846770241', 103414 rows
2021.08.13 20:45:09.073571 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Trace> db.table: Renaming temporary part tmp_insert_20210813_239_239_0 to 20210813_451_451_0.

-- The third block
2021.08.13 20:45:13.051942 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Debug> db.table (Replicated OutputStream): Wrote block with ID '20210813_16231016785560754596_9804537966436769992', 103379 rows
2021.08.13 20:45:13.065374 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Trace> db.table: Renaming temporary part tmp_insert_20210813_240_240_0 to 20210813_452_452_0.

-- The fourth block
2021.08.13 20:45:16.813489 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Debug> db.table (Replicated OutputStream): Wrote block with ID '20210813_14978609919789150052_6694756734307136853', 103604 rows
2021.08.13 20:45:16.822164 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Trace> db.table: Renaming temporary part tmp_insert_20210813_241_241_0 to 20210813_453_453_0.

-- The fifth block
2021.08.13 20:45:19.335465 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Debug> db.table (Replicated OutputStream): Wrote block with ID '20210813_9047090776261112264_1197278831556285907', 88696 rows
2021.08.13 20:45:19.344424 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Trace> db.table: Renaming temporary part tmp_insert_20210813_242_242_0 to 20210813_454_454_0.

-- The total number of rows reported by the query is 502518 (five blocks of data)
2021.08.13 20:45:19.613576 [ 21749 ] {115638b0-8ee7-45a8-be6a-594f9a00e417} <Information> executeQuery: Read 502518 rows, 2.45 GiB in 17.397894281 sec., 28883 rows/sec., 144.36 MiB/sec.

-- The number of rows in the table is 554233
select count() from db.table;

count()
-------
 554233

554233 = 502518 (the second insert) + 51715 (the partial block from the first insert)

-- The number of rows in the source file is 502518
$ zcat 20210813200003-1.tsv.gz | wc -l
502518
```

ClickHouse client version 21.8.3.44 (official build).
Connected to ClickHouse server version 21.8.3 revision 54449.

**Comment by alexey-milovidov** [comment] 2021-08-15 05:49
Parallel parsing of input data may lead to non-deterministic split of data to blocks.
Does the issue exist if you disable `input_format_parallel_parsing`?

**Comment by SaltTan** [comment] 2021-08-16 00:34
> Does the issue exist if you disable `input_format_parallel_parsing`?

I don't know. I am testing this because I want to use parallel parsing.

> Parallel parsing of input data may lead to non-deterministic split of data to blocks.

I didn't expect this.
I was hoping that if I process the same file without changing any settings I will get the same blocks.
Is it for sure that parallel parsing breaks deduplication?

Anyway, I don't believe my example has anything to do with parallel parsing.
Clickhouse-client may be parsing in parallel, but it sends blocks one after another it seems.

What happened is this case, in my opinion:
The first block got inserted successfully.
I killed the client while it was sending the second block.
The client died in the middle of transferring the data.
The server inserted the second block as if nothing happened (there were no exceptions), even though the server was aware that the client died and the query should have been interrupted (`TCPHandler: Client has dropped the connection, cancel the query.`).

I don't know how to reproduce this. Normally, when I kill clickhouse-client, there is an exception, the insert is interrupted and deduplication works on retry.

**Comment by den-crane** [comment] 2021-08-16 01:03
```
create table dedup_test( A Int64) Engine = ReplicatedMergeTree ('/clickhouse/tables/{table}','{replica}') order by A;

clickhouse-client -q 'select * from numbers(50000000) format TSV' > deduptest.tsv

for i in `seq 1 150`; do echo $i; clickhouse-client --min_chunk_bytes_for_parallel_parsing=1000000 -q 'insert into dedup_test format TSV' <deduptest.tsv ; clickhouse-client -q 'select count() from dedup_test';  done
1
50000000
2
50000000
3
50000000
4
50000000
5
50000000
6
50000000
7
50000000
8
50000000
9
50000000
10
50000000
....

another window:
for i in `seq 1 1500`; do echo $i; kill -9 `ps -ef|grep 'insert into dedup_test'|grep -v grep|awk '{print $2}'`; sleep 3; done

...
30
Killed
50000000
31
50111112
32
50111112
33
Killed
50111112
34
50222224
35
50222224
36
Killed
50222224
37
50333336
38
50333336
...
53
50777784
54
Killed
50777784
55
50888896
56
50888896
57
Killed
50888896
58
51222232
59
51222232
60
```

**Comment by den-crane** [comment] 2021-08-16 01:07
disable input_format_parallel_parsing

```
for i in `seq 1 150`; do echo $i; clickhouse-client --max_insert_block_size=100000 --input_format_parallel_parsing=0 -q 'insert into dedup_test format TSV' <deduptest.tsv ; clickhouse-client -q 'select count() from dedup_test';  done
1
50000000
2
Killed
50000000
3
50700000
4
Killed
50700000
5
51500000
6
Killed
52300000
7
52300000
8
Killed
52300000
9
53200000
10
```

**Comment by den-crane** [comment] 2021-08-16 01:13
the same in CH 18.14.19

**Comment by den-crane** [comment] 2021-08-16 01:25
The same with HTTP

```
for i in `seq 1 150`; do echo $i; curl 'http://localhost:8123/?max_insert_block_size=100000&input_format_parallel_parsing=0&query=insert+into+dedup_test+format+TSV' --data-binary @deduptest.tsv ; clickhouse-client -q 'select count() from dedup_test';  done
1
50000000
2
50000000
3
50000000
4
50000000
5
50000000
6
50000000
7
50000000
8
50000000
9
50000000
10
50000000
11
50000000

---
for i in `seq 1 1500`; do echo $i; kill -9 `ps -ef|grep 'insert+into+dedup_test'|grep -v grep|awk '{print $2}'`; sleep 3; done
---

12
Killed
50000000
13
51049871
14
Killed
51049871
15
51579704
16
Killed
51579704
17
51579704
18
Killed
51579704
19
52256993

```

**Comment by den-crane** [comment] 2021-08-16 01:31
The same with 900k blocks

```
truncate table dedup_test;

clickhouse-client -q 'select * from numbers(900000) format TSV' > deduptest.tsv


for i in `seq 1 1500`; do echo $i; curl 'http://localhost:8123/?input_format_parallel_parsing=0&query=insert+into+dedup_test+format+TSV' --data-binary @deduptest.tsv ; clickhouse-client -q 'select count() from dedup_test';  done
1
900000
2
900000
3
900000
4
900000
5
900000
6
900000
7
900000
8
900000
9
900000
10
900000
11
900000
12
900000
13
900000
14
900000
15
900000
16
900000
17
900000
18
900000
19
900000
20
900000
21
900000
22
900000
23
900000
24
900000
25
900000
26
900000
27
900000
28
900000
29
900000
30
900000
31
900000
32
900000
33
900000
34
900000
35
900000
36
900000
37
900000
38
900000
39
900000
40
900000
41
900000
42
900000
43
900000
44
900000
45
900000
46
900000
47
900000
48
900000
49
900000
50
900000
51
900000
52
900000
53
900000
54
900000
55
900000
56
900000
57
900000
58
900000
59
900000
60
900000
61
900000
62
900000
63
900000
64
900000
65
900000
66
900000
67
900000
68
900000
69
900000
70
900000
71
900000
72
900000
73
900000
74
900000
75
900000
76
900000
77
900000
78
900000
79
900000
80
900000
81
900000
82
900000
83
Killed
900000
84
900000
85
900000
86
900000
87
900000
88
900000
89
900000
90
900000
91
900000
92
900000
93
900000
94
900000
95
900000
----
for i in `seq 1 1500`; do echo $i; kill -9 `ps -ef|grep 'insert+into+dedup_test'|grep -v grep|awk '{print $2}'`;sleep 1; done
----
96
900000
97
Killed
900000
98
1346538
99
1346538
100
1346538
101
1346538
102
1346538
103
1346538
104
1346538
105
1346538
106
1346538
107
1346538
108
1346538
109
1346538
110
1346538
111
Killed
1346538
112
1346538
113
1346538
114
1346538
115
1346538
116
1346538
117
1346538
118
1346538
119
1346538
120
1346538
121
1346538
122
1346538
123
1346538
124
1346538
125
Killed
1346538
126
2083307
127
2083307
128
2083307
129
2083307
130
2083307
131
2083307
132
2083307
133
2083307
134
2083307
135
2083307
136
2083307
137
2083307
138
2083307
139
Killed
2083307
140
2801352
141
2801352
142
2801352
143
2801352
144
2801352
145
2801352
146
2801352
147
2801352
148
2801352
149
2801352
150
2801352
151
2801352
152
2801352
153
2801352
154
2801352
155
2801352
156
2801352
157
2801352
158
2801352
159
2801352
160
2801352
161
2801352
162
2801352
163
2801352
164
2801352
165
2801352
166
Killed
2801352
167
2801352
168
2801352
169
2801352
170
2801352
171
2801352
172
2801352
173
2801352
174
2801352
175
2801352
176
2801352
177
2801352
178
2801352
179
2801352
180
Killed
2801352
181
2801352
182
2801352
183
2801352
184
2801352
185
2801352
186
2801352
187
2801352
188
2801352
189
2801352
190
2801352
191
2801352
192
2801352
193
2801352
194
Killed
2801352
195
3500672
196
3500672
197
3500672
198
3500672
199
3500672
200
3500672
201
3500672
202
3500672
203
3500672
204
3500672
205
3500672
206
3500672
207
3500672
208
Killed
3500672
209
4387238
210
4387238
211
4387238
212
4387238
213
4387238
214
4387238
215
4387238
216
4387238
217
4387238
218
4387238
219
4387238
220
4387238
221
4387238
222
Killed
4387238
223
4852501
224
4852501
225
4852501
226
4852501
227
4852501
228
4852501
229
4852501
230
4852501
231
4852501
232
4852501
233
4852501
234
4852501
235
4852501
236
4852501
237
4852501
238
4852501
239
4852501
240
4852501
241
4852501
```

**Comment by zheyu001** [comment] 2021-12-14 05:31
We are facing similar issue. Just trying to understand the test result from @den-crane: 
Looks like even if input_format_parallel_parsing is disabled (set to 0), duplication will still be introduced? As while interrupting insert, count of lines keeps growing.

**Comment by SaltTan** [comment] 2021-12-14 16:00
I think this might be related to blocks squashing.
Recently I got a block inserted after I killed an INSERT query using KILL QUERY.

**Comment by zheyu001** [comment] 2021-12-15 02:06
> Recently I got a block inserted after I killed an INSERT query using KILL QUERY.

Even this happened, replicated* engine should de-dup automatically if trying to re-insert exactly the same block according to [this doc](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/):
"Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once." 

I think the problem here might be: input is divided into different blocks between the first failed insertion and retry insertion. Ideally this should not happen if the input is always divided in order and given same max_insertion_block_size. But it seems input_format_parallel_parsing will allow input processed without order? Please correct me if my understand is wrong.

**Comment by den-crane** [comment] 2021-12-15 04:27
@zheyu001 your understand is wrong. It's not related to input_format_parallel_parsing. This problem existed 4 years before input_format_parallel_parsing was introduced. It exists from the beginning. 

_**The server inserted the second block as if nothing happened (there were no exceptions), even though the server was aware that the client died and the query should have been interrupted**_

**Comment by zheyu001** [comment] 2021-12-15 05:11
Thanks for the explanation @den-crane ! Just trying the de-dup strategy a little bit further:

> The server inserted the second block as if nothing happened (there were no exceptions), even though the server was aware that the client died and the query should have been interrupted

Even this case, I thought data block de-dup will kick in. (["Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once."](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/)). If not, what blocks de-dup strategy from kicks in? Retry-insertion generates different data blocks?

**Comment by zheyu001** [comment] 2021-12-15 05:32
Forget my last comment. 

I think what you mean is: 

Assuming there's 500 rows in the second block. While first 200 rows written to server, client died. Server will not revert the insertion of the first 200 rows. Retry for second block will bring another 500 rows and will not be de-duplicated. 

Is this what happening here?

**Comment by den-crane** [comment] 2021-12-15 14:35
@zheyu001 forget about the second block. It does not matter which block.
The issue that CH does not treat client's transmit interruption as an error.

So imagine we insert 1 mil rows as a single block and the client crashes after transferring 121563 rows, and Clickhouse server inserts 121563 rows as was no error. 
The client does not know how many rows were transferred and repeats the insert with  1 mil rows, and you got 121563 duplicates because checksum of 121563 rows and of repeated 1 mil rows are different.

121563 -- random number. The client crashes on random time.

**Comment by zheyu001** [comment] 2021-12-15 14:39
@den-crane Thanks a lot. That explains the issue clearly. 

Now let's assume: retry didn't kick in, there's 121563 rows in main table. If there's a MatView attached to this table, will 121563 rows trigger select of MatView?

**Comment by den-crane** [comment] 2021-12-15 14:41
> If there's a MatView attached to this table, will 121563 rows trigger select of MatView?

Yes, exactly. MatView will receive 121563 rows.

**Comment by den-crane** [comment] 2021-12-15 14:45
MatView gets blocks from the insert, then processes the blocks. So mativew will receive the block with  121563 rows, executes its query (select count()) evaluates count() = 121563 as number and then will insert into own storage the number 121563. https://stackoverflow.com/a/70365237/11644308

**Comment by zheyu001** [comment] 2021-12-16 05:50
Thanks a lot for the details, @den-crane ! Really helpful!

This basically allows us to use MV to maintain the progress of insertion(count rows of a specific insertion). And our application can use it to skip submitted records. Of course to keep same order of rows within one insertion will sacrifice performance a little bit, which is tolerant-able for now. 

Still, looking forward to the fix of this issue and atomicity of table <> MV, which is already on your roadmap IIRC.

**Comment by zheyu001** [comment] 2021-12-16 16:40
Wait, after a second thought, MV can't ensure the progress it recorded is correct either. 

To step back a little bit, does this partial block issue also means insertion atomicity of main table can't be guaranteed as well?
Besides, I'm also wondering what's the contract between client and server here? Does client needs to wait for a succeed signal or something so that it knows the insertion is done?

**Comment by den-crane** [comment] 2022-02-22 20:34
still valid 22.2.2.1.

**Comment by vigliag** [comment] 2022-11-01 18:31
Hi @den-crane. I used your command to try and reproduce the issue on CH 22.3.

The issue is still there when using curl with no particular option, but I seem to get the correct behavior when forcing it to use HTTP Chunked Encoding:

```
docker run --rm -it -p 8123:8123 clickhouse/clickhouse-server:22.3
 
curl localhost:8123 -d "create table dedup_test( A Int64) Engine = MergeTree() order by A;"
curl localhost:8123 -d 'select * from numbers(50000000) format TSV' > deduptest.tsv
 
timeout -s KILL 4 curl -H "Transfer-Encoding: chunked" -v 'http://localhost:8123/?input_format_parallel_parsing=0&query=insert+into+dedup_test+format+TSV' --data-binary @deduptest.tsv --limit-rate 1M

clickhouse-cli -q 'select count() from dedup_test'
# 0
```

It also results in this stacktrace:
```
2022.11.01 18:14:12.643087 [ 45 ] {8df6da10-4ffd-4b1b-9c4f-7ce17da81ea0} <Error> executeQuery: Code: 3. DB::Exception: Unexpected end of file while reading chunk header of HTTP chunked data: While executing TabSeparatedRowInputFormat. (UNEXPECTED_END_OF_FILE) (version 22.3.14.23 (official build)) (from 172.17.0.1:36898) (in query: insert into dedup_test format TSV ), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb39d29a in /usr/bin/clickhouse
1. DB::HTTPChunkedReadBuffer::readChunkHeader() @ 0x167628c2 in /usr/bin/clickhouse
2. DB::HTTPChunkedReadBuffer::nextImpl() @ 0x16762b7f in /usr/bin/clickhouse
3. DB::wrapReadBufferReference(DB::ReadBuffer&)::ReadBufferWrapper::nextImpl() @ 0x14dd0c4c in /usr/bin/clickhouse
4. DB::wrapReadBufferReference(DB::ReadBuffer&)::ReadBufferWrapper::nextImpl() @ 0x14dd0c4c in /usr/bin/clickhouse
5. DB::ConcatReadBuffer::nextImpl() @ 0x14dd220e in /usr/bin/clickhouse
6. DB::wrapReadBufferReference(DB::ReadBuffer&)::ReadBufferWrapper::nextImpl() @ 0x14dd0c4c in /usr/bin/clickhouse
7. DB::ConcatReadBuffer::nextImpl() @ 0x14dd220e in /usr/bin/clickhouse
8. void DB::readIntTextUnsafe<long, true>(long&, DB::ReadBuffer&) @ 0xb1ec6f1 in /usr/bin/clickhouse
9. DB::SerializationNumber<long>::deserializeText(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&, bool) const @ 0xb1ec586 in /usr/bin/clickhouse
10. bool DB::SerializationNullable::deserializeTextEscapedAndRawImpl<bool, true>(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&, std::__1::shared_ptr<DB::ISerialization const> const&) @ 0x150e8052 in /usr/bin/clickhouse
11. DB::RowInputFormatWithNamesAndTypes::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0x16811fe5 in /usr/bin/clickhouse
12. DB::IRowInputFormat::generate() @ 0x168033f0 in /usr/bin/clickhouse
13. DB::ISource::tryGenerate() @ 0x16793415 in /usr/bin/clickhouse
14. DB::ISource::work() @ 0x16792fda in /usr/bin/clickhouse
15. DB::ExecutionThreadContext::executeTask() @ 0x167b3763 in /usr/bin/clickhouse
16. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x167a71be in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x167a650b in /usr/bin/clickhouse
18. DB::PipelineExecutor::execute(unsigned long) @ 0x167a5dd8 in /usr/bin/clickhouse
19. DB::CompletedPipelineExecutor::execute() @ 0x167a4884 in /usr/bin/clickhouse
20. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x15dd52b3 in /usr/bin/clickhouse
21. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x166e7ae8 in /usr/bin/clickhouse
22. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x166ec292 in /usr/bin/clickhouse
23. DB::HTTPServerConnection::run() @ 0x1675fbbb in /usr/bin/clickhouse
24. Poco::Net::TCPServerConnection::start() @ 0x19a1fb4f in /usr/bin/clickhouse
25. Poco::Net::TCPServerDispatcher::run() @ 0x19a21fa1 in /usr/bin/clickhouse
26. Poco::PooledThread::run() @ 0x19bdf929 in /usr/bin/clickhouse
27. Poco::ThreadImpl::runnableEntry(void*) @ 0x19bdcc80 in /usr/bin/clickhouse
28. ? @ 0x7f121c250609 in ?
29. clone @ 0x7f121c175133 in ?
```

Without "Transfer-Encoding: chunked", it exibits the usual behavior, and produces no stacktrace in the logs

```
timeout -s KILL 4 curl -v 'http://localhost:8123/?input_format_parallel_parsing=0&query=insert+into+dedup_test+format+TSV' --data-binary @deduptest.tsv --limit-rate 1M
clickhouse-cli -q 'select count() from dedup_test'
# 596335
```

If it looks ok to you, I can write a clickhouse test with the commands above and open a PR

**Comment by SaltTan** [comment] 2023-01-16 19:45
I just ran into this on 22.8.12.45
clickhouse-client threw an exception:
```
Error on processing query: Code: 27. DB::ParsingException: Cannot parse input: expected ']' at end of stream.: Buffer has gone, cannot extract information about what has been parsed.: While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from stdin: (in file/uri (fd = 0)): (at row 1836672)
. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 22.8.12.45 (official build))
```
However the query successfully inserted 1,834,740 rows:
```
(Replicated OutputStream): Wrote block with ID '20230113_13255549023755388789_17118446210903778181', 1048735 rows
(Replicated OutputStream): Wrote block with ID '20230113_4596031606807024074_6273115694167143890', 786005 rows
```
I would expect ClickHouse to reject the second block.

**Comment by den-crane** [comment] 2023-01-16 19:56
>I would expect ClickHouse to reject the second block.

AFIAK it's expected with ParallelParsingBlockInputFormat

**Comment by SaltTan** [comment] 2023-10-25 11:04
The fix was released in 23.3, but the problem is still present in 23.4
```
2023.10.16 20:06:47.512139 [ 2128236 ] {dc2cc8fb-1b81-4a10-8b4f-540f11321ce0} <Information> TCPHandler: Change cancellation status from NOT_CANCELLED to FULLY_CANCELLED. Log message: Received 'Cancel' packet from the client, canceling the query.
2023.10.16 20:06:47.532554 [ 2128236 ] {dc2cc8fb-1b81-4a10-8b4f-540f11321ce0} <Trace> db.table (3f56fdea-538e-4d6f-b86a-58c9c22a8b0c): Trying to reserve 315.09 MiB using storage policy from min volume index 0
2023.10.16 20:06:47.532603 [ 2128236 ] {dc2cc8fb-1b81-4a10-8b4f-540f11321ce0} <Trace> DiskLocal: Reserved 315.09 MiB on local disk `default`, having unreserved 24.53 TiB.
2023.10.16 20:06:48.750872 [ 2128236 ] {dc2cc8fb-1b81-4a10-8b4f-540f11321ce0} <Trace> MergedBlockOutputStream: filled checksums 20231016_496193_496193_0 (state Temporary)
2023.10.16 20:06:48.752791 [ 2128236 ] {dc2cc8fb-1b81-4a10-8b4f-540f11321ce0} <Debug> db.table (3f56fdea-538e-4d6f-b86a-58c9c22a8b0c) (Replicated OutputStream): Wrote block with ID '20231016_13197220280118693068_9957001702289942968', 28111 rows
2023.10.16 20:06:48.762106 [ 2128236 ] {dc2cc8fb-1b81-4a10-8b4f-540f11321ce0} <Trace> db.table (3f56fdea-538e-4d6f-b86a-58c9c22a8b0c): Renaming temporary part tmp_insert_20231016_496193_496193_0 to 20231016_6512_6512_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
...
-- the query proceeded with populating the materialized views
...
2023.10.16 20:06:50.040700 [ 486027 ] {dc2cc8fb-1b81-4a10-8b4f-540f11321ce0} <Information> executeQuery: Code: 394. DB::Exception: Query was cancelled or a client has unexpectedly dropped the connection. (QUERY_WAS_CANCELLED) (version 23.4.6.25 (official build)) (from [::1]:40488)
```
Another example for an empty block in the source table:
```
2023.10.16 21:57:03.472334 [ 3845185 ] {12ad49d9-37e3-4572-a730-83a58e242811} <Information> TCPHandler: Change cancellation status from NOT_CANCELLED to FULLY_CANCELLED. Log message: Received 'Cancel' packet from the client, canceling the query.
-- after the cancellation the query proceeded with populating the materialized views
2023.10.16 21:57:03.472396 [ 2880430 ] {12ad49d9-37e3-4572-a730-83a58e242811} <Trace> PushingToViews: Pushing (parallel 7) from db.table (96fe4e51-6cfe-4069-a1e5-c44d0f944c7f) to db.mv1 (0881a17e-30be-4dbb-b5da-7e4261826140) took 0 ms.
2023.10.16 21:57:03.472408 [ 2880430 ] {12ad49d9-37e3-4572-a730-83a58e242811} <Trace> PushingToViews: Pushing (parallel 7) from db.table (96fe4e51-6cfe-4069-a1e5-c44d0f944c7f) to db.mv2 (1fe779b3-37a1-4df0-be4f-48e057e17433) took 0 ms.
2023.10.16 21:57:03.472414 [ 2880430 ] {12ad49d9-37e3-4572-a730-83a58e242811} <Trace> PushingToViews: Pushing (parallel 7) from db.table (96fe4e51-6cfe-4069-a1e5-c44d0f944c7f) to db.mv3 (62632047-d95a-4fb0-90ba-fc2cfbda9db6) took 0 ms.
2023.10.16 21:57:03.472419 [ 2880430 ] {12ad49d9-37e3-4572-a730-83a58e242811} <Trace> PushingToViews: Pushing (parallel 7) from db.table (96fe4e51-6cfe-4069-a1e5-c44d0f944c7f) to db.mv4 (00fd13c9-2404-4c57-bb2e-f8338566837d) took 0 ms.
2023.10.16 21:57:03.472425 [ 2880430 ] {12ad49d9-37e3-4572-a730-83a58e242811} <Trace> PushingToViews: Pushing (parallel 7) from db.table (96fe4e51-6cfe-4069-a1e5-c44d0f944c7f) to db.mv5(c9da19d3-d162-4f62-867b-be3203038fd7) took 0 ms.
2023.10.16 21:57:03.472430 [ 2880430 ] {12ad49d9-37e3-4572-a730-83a58e242811} <Trace> PushingToViews: Pushing (parallel 7) from db.table (96fe4e51-6cfe-4069-a1e5-c44d0f944c7f) to db.mv6 (e52d7279-80bd-4743-abcf-4651658bf2a7) took 0 ms.
2023.10.16 21:57:03.472434 [ 2880430 ] {12ad49d9-37e3-4572-a730-83a58e242811} <Trace> PushingToViews: Pushing (parallel 7) from db.table (96fe4e51-6cfe-4069-a1e5-c44d0f944c7f) to db.mv7 (dfc93f8f-8a5c-4457-94f2-72182cb11ab3) took 0 ms.
2023.10.16 21:57:03.473401 [ 450327 ] {12ad49d9-37e3-4572-a730-83a58e242811} <Information> executeQuery: Code: 394. DB::Exception: Query was cancelled or a client has unexpectedly dropped the connection. (QUERY_WAS_CANCELLED) (version 23.4.6.25 (official build)) (from [::1]:44020)
```

**Comment by tavplubix** [comment] 2023-10-25 13:40
@SaltTan, we have a test (based on the examples from @den-crane) that ensures that it doesn't happen: https://github.com/ClickHouse/ClickHouse/blob/dfff4704ad28568623dc9fd050d8c2740bbd5d6f/tests/queries/0_stateless/02434_cancel_insert_when_client_dies.sh#

I cannot reproduce it in a recent version using examples from this issue. Probably, you insert different blocks on retries.

Please provide a reproducible example, or logs that clearly demonstrate the issue (the logs you provided above do not demonstrate anything)

**Closed by tavplubix** 2023-10-25 13:40 UTC
Labels: bug

**Comment by SaltTan** [comment] 2023-10-25 14:51
The problem is exactly the same as in the first message.
The only difference is how the cancellation event is logged.
21.8: TCPHandler: Client has dropped the connection, cancel the query.
23.4: TCPHandler: Change cancellation status from NOT_CANCELLED to FULLY_CANCELLED. Log message: Received 'Cancel' packet from the client, canceling the query.

**Comment by den-crane** [comment] 2023-10-25 15:24
Interesting, that if I kill a client, there is no message "CANCELLED"

>executeQuery: Code: 210. DB::NetException: Connection reset by peer, while writing to socket
> (127.0.0.1:9000 -> 127.0.0.1:60854). (NETWORK_ERROR) (version 23.9.1.819) (from 127.0.0.1:60854) 
> (in query: insert into dedup_test format TSV), Stack trace (when copying this message, always include the lines below):

In Tatiana last case clickhouse-client failed to parse a text file during the parsing using parallel parsing and wrote incomplete insert, but I think this is expected. Server wrote incomplete insert. But server wrote completed blocks.

It does not match Tatiana's expectations. May be it can be fixed (for Tatiana) by disabling parallel parsing and increasing max_insert_block_size, min_insert_block_bytes. To form a single part and cancel this part due to parsing fail.

**Comment by den-crane** [comment] 2023-10-25 15:40
Though. max_insert_block_size works even with a parallel parsing.

```
create table dedup_test( A Int64) Engine = ReplicatedMergeTree ('/clickhouse/tables/{table}','{replica}') order by A;

clickhouse-client -q 'select * from numbers(2900000) format TSV' > deduptest.tsv
echo -e "a\tb" >> deduptest.tsv
```

```
clickhouse-client --min_chunk_bytes_for_parallel_parsing=1000 --input_format_parallel_parsing=1 -q 'insert into dedup_test format TSV' <deduptest.tsv ; clickhouse-client -q 'select count() from dedup_test';
Code: 27. DB::ParsingException: Cannot parse input: expected '\n' before: 'a\tb\n':

2097062 --<<< rows inserted
```

```
truncate dedup_test;

-- max_insert_block_size=10000000 --min_insert_block_size_rows=100000000 
clickhouse-client --min_chunk_bytes_for_parallel_parsing=1000 --input_format_parallel_parsing=1 --max_insert_block_size=10000000 --min_insert_block_size_rows=100000000 -q 'insert into dedup_test format TSV' <deduptest.tsv ; clickhouse-client -q 'select count() from dedup_test';
Code: 27. DB::ParsingException: Cannot parse input: expected '\n' before: 'a\tb\n':

0 --<<< rows inserted.
```

**Comment by tavplubix** [comment] 2023-10-25 15:44
> The logs that I provided demonstrate the fact that the query is not cancelled properly.

No, the log message about the cancellation status might look suspicious, but it does not mean anything like that.

**Comment by SaltTan** [comment] 2023-10-25 15:58
In my opinion, the suspicious thing is what happened AFTER that log message

**Comment by den-crane** [comment] 2023-11-01 22:09
New repro

```
create table test ( a Int64, b String) 
Engine=ReplicatedMergeTree ('/clickhouse/{cluster}/tables/test123', '{replica}') order by a
settings max_parts_to_merge_at_once =1,parts_to_throw_insert=30000;

clickhouse-client -q "select number+1000000,repeat('a',100) from numbers(6000111) format CSV" > test.csv
echo 1,2,3,4,5>> test.csv

clickhouse-client  -q "insert into test format CSV" < test.csv
Error on processing query: Code: 117. DB::Exception: Expected end of line: (at row 48691)

select count(), _part from test group by _part order by _part;
┌─count()─┬─_part─────┐
│ 1133604 │ all_0_0_0 │
│ 1133604 │ all_1_1_0 │
│ 1133604 │ all_2_2_0 │
│  850203 │ all_3_3_0 │
└─────────┴───────────┘
```

if file is correct (no parsing error)

```
select count(), _part from test group by _part order by _part;
┌─count()─┬─_part─────┐
│ 1133604 │ all_0_0_0 │
│ 1133604 │ all_1_1_0 │
│ 1133604 │ all_2_2_0 │
│ 1133604 │ all_3_3_0 │
│ 1133604 │ all_4_4_0 │
│  332091 │ all_5_5_0 │
└─────────┴───────────┘
```

no input function
```
clickhouse-client   -q "insert into test format CSV" < test.csv
Error on processing query: Code: 117. DB::Exception: Expected end of line: (at row 48691)

select count(), _part from test group by _part order by _part;
┌─count()─┬─_part─────┐
│ 1133604 │ all_0_0_0 │
│ 1133604 │ all_1_1_0 │
│ 1133604 │ all_2_2_0 │
└─────────┴───────────┘
```
