### ISSUE TITLE
Crash on BigDecimal 128 operations

### ISSUE THREAD

**Issue by astudnev** [ClickHouse/ClickHouse#10331] opened 2020-04-17 13:01 UTC
ClickHouse client version 19.9.2.4 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.9.2 revision 54421.

Crash on request like:
```
SELECT
    formatDateTime(tx_date, '%Y-%m') AS `_aq.date.date`,
    median( transfers_currency.value)
FROM transfers_currency
WHERE transfers_currency.currency_id = 408185
GROUP BY `_aq.date.date`
ORDER BY `_aq.date.date` ASC
```

where
transfers_currency.value is value Decimal128(0)

The following request works OK:

```
SELECT
    formatDateTime(tx_date, '%Y-%m') AS `_aq.date.date`,
    median( toFloat64(transfers_currency.value))
FROM transfers_currency
WHERE transfers_currency.currency_id = 408185
GROUP BY `_aq.date.date`
ORDER BY `_aq.date.date` ASC
```

**Comment by astudnev** [comment] 2020-04-17 13:01
[err.txt](https://github.com/ClickHouse/ClickHouse/files/4493030/err.txt)

**Comment by filimonov** [comment] 2020-04-17 13:25
Most probably a duplicate of:
https://github.com/ClickHouse/ClickHouse/issues/6371
https://github.com/ClickHouse/ClickHouse/issues/5825

Please update your ClickHouse.

**Closed by filimonov** 2020-04-17 13:25 UTC
Labels: bug, comp-decimal, duplicate, obsolete-version
