### ISSUE TITLE
Part intersects next part - LOGICAL_ERROR

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#36848] opened 2022-05-02 11:52 UTC
`DB::Exception: Part 9_10_36_1 intersects next part 9_26_26_1. It is a bug or a result of manual intervention in the ZooKeeper data. (LOGICAL_ERROR)`

Stack trace:
```
2022.04.30 05:09:19.567018 [ 390 ] {} <Fatal> BaseDaemon: (version 22.5.1.1, build id: 773A4B80C5AA3134) (from thread 624) Terminate called for uncaught exception:
2022.04.30 05:09:19.567036 [ 390 ] {} <Fatal> BaseDaemon: Code: 49. DB::Exception: Part 9_10_36_1 intersects next part 9_26_26_1. It is a bug or a result of manual intervention in the ZooKeeper data. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
2022.04.30 05:09:19.567049 [ 390 ] {} <Fatal> BaseDaemon:
2022.04.30 05:09:19.567061 [ 390 ] {} <Fatal> BaseDaemon: 0. ./build_docker/../contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2670ff32 in /usr/bin/clickhouse
2022.04.30 05:09:19.567073 [ 390 ] {} <Fatal> BaseDaemon: 1. ./build_docker/../src/Common/Exception.cpp:58: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xfd5040f in /usr/bin/clickhouse
2022.04.30 05:09:19.567088 [ 390 ] {} <Fatal> BaseDaemon: 2. ./build_docker/../contrib/libcxx/include/string:1445: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x145b0057 in /usr/bin/clickhouse
2022.04.30 05:09:19.567105 [ 390 ] {} <Fatal> BaseDaemon: 3. ./build_docker/../src/Storages/MergeTree/ActiveDataPartSet.cpp:0: DB::ActiveDataPartSet::add(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) @ 0x2415833d in /usr/bin/clickhouse
2022.04.30 05:09:19.567126 [ 390 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeQueue::insertUnlocked(std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry> const&, std::__1::optional<long>&, std::__1::lock_guard<std::__1::mutex>&) @ 0x244fba12 in /usr/bin/clickhouse
2022.04.30 05:09:19.567140 [ 390 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../contrib/libcxx/include/string:1445: DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x24504b17 in /usr/bin/clickhouse
2022.04.30 05:09:19.567154 [ 390 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:1965: DB::ReplicatedMergeTreeMergePredicate::ReplicatedMergeTreeMergePredicate(DB::ReplicatedMergeTreeQueue&, std::__1::shared_ptr<zkutil::ZooKeeper>&) @ 0x2451e947 in /usr/bin/clickhouse
2022.04.30 05:09:19.567187 [ 390 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:1603: DB::ReplicatedMergeTreeQueue::getMergePredicate(std::__1::shared_ptr<zkutil::ZooKeeper>&) @ 0x24515e33 in /usr/bin/clickhouse
2022.04.30 05:09:19.567202 [ 390 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:3130: DB::StorageReplicatedMergeTree::mergeSelectingTask() @ 0x23ee4b40 in /usr/bin/clickhouse
2022.04.30 05:09:19.567231 [ 390 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Common/Stopwatch.h:49: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x22556ba0 in /usr/bin/clickhouse
2022.04.30 05:09:19.567247 [ 390 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../contrib/poco/Foundation/include/Poco/AutoPtr.h:90: DB::BackgroundSchedulePool::threadFunction() @ 0x225589be in /usr/bin/clickhouse
2022.04.30 05:09:19.567266 [ 390 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: decltype(static_cast<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&) @ 0x2255943f in /usr/bin/clickhouse
2022.04.30 05:09:19.567284 [ 390 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../contrib/libcxx/include/__functional/function.h:115
2022.04.30 05:09:19.567435 [ 211736 ] {} <Fatal> BaseDaemon: ########################################
2022.04.30 05:09:19.567469 [ 211736 ] {} <Fatal> BaseDaemon: (version 22.5.1.1, build id: 773A4B80C5AA3134) (from thread 624) (no query) Received signal Aborted (6)
2022.04.30 05:09:19.567486 [ 211736 ] {} <Fatal> BaseDaemon:
2022.04.30 05:09:19.567541 [ 211736 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fcd172c103b 0x7fcd172a0859 0x2223d053 0x27a40588 0x27a404f5 0x2450647f 0x2451e947 0x24515e33 0x23ee4b40 0x22556ba0 0x225589be 0x2255943f 0xfe24a5a 0xfe27522 0x7fcd17478609 0x7fcd1739d163
2022.04.30 05:09:19.567571 [ 211736 ] {} <Fatal> BaseDaemon: 3. raise @ 0x7fcd172c103b in ?
2022.04.30 05:09:19.567587 [ 211736 ] {} <Fatal> BaseDaemon: 4. abort @ 0x7fcd172a0859 in ?
2022.04.30 05:09:19.586961 [ 211736 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../base/daemon/BaseDaemon.cpp:443: terminate_handler() @ 0x2223d053 in /usr/bin/clickhouse
2022.04.30 05:09:19.594592 [ 211736 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../contrib/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x27a40588 in /usr/bin/clickhouse
2022.04.30 05:09:19.602886 [ 211736 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../contrib/libcxxabi/src/cxa_handlers.cpp:0: std::terminate() @ 0x27a404f5 in /usr/bin/clickhouse
2022.04.30 05:09:19.698333 [ 211736 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:710: DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x2450647f in /usr/bin/clickhouse
2022.04.30 05:09:19.785502 [ 211736 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:1965: DB::ReplicatedMergeTreeMergePredicate::ReplicatedMergeTreeMergePredicate(DB::ReplicatedMergeTreeQueue&, std::__1::shared_ptr<zkutil::ZooKeeper>&) @ 0x2451e947 in /usr/bin/clickhouse
2022.04.30 05:09:19.900808 [ 211736 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:1603: DB::ReplicatedMergeTreeQueue::getMergePredicate(std::__1::shared_ptr<zkutil::ZooKeeper>&) @ 0x24515e33 in /usr/bin/clickhouse
2022.04.30 05:09:20.179775 [ 211736 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:3130: DB::StorageReplicatedMergeTree::mergeSelectingTask() @ 0x23ee4b40 in /usr/bin/clickhouse
2022.04.30 05:09:20.191859 [ 211736 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../src/Common/Stopwatch.h:49: Stopwatch::elapsedNanoseconds() const
2022.04.30 05:09:20.191885 [ 211736 ] {} <Fatal> BaseDaemon: 12.2. inlined from ../src/Common/Stopwatch.h:51: Stopwatch::elapsedMilliseconds() const
2022.04.30 05:09:20.191911 [ 211736 ] {} <Fatal> BaseDaemon: 12. ../src/Core/BackgroundSchedulePool.cpp:106: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x22556ba0 in /usr/bin/clickhouse
2022.04.30 05:09:20.206310 [ 211736 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/../contrib/poco/Foundation/include/Poco/AutoPtr.h:90: ~AutoPtr
2022.04.30 05:09:20.206337 [ 211736 ] {} <Fatal> BaseDaemon: 13. ../src/Core/BackgroundSchedulePool.cpp:260: DB::BackgroundSchedulePool::threadFunction() @ 0x225589be in /usr/bin/clickhouse
2022.04.30 05:09:20.222535 [ 211736 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: operator()
2022.04.30 05:09:20.222570 [ 211736 ] {} <Fatal> BaseDaemon: 14. ../contrib/libcxx/include/type_traits:3640: decltype(static_cast<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(fp)()) std::__1::__invoke<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&) @ 0x2255943f in /usr/bin/clickhouse
2022.04.30 05:09:20.235535 [ 211736 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/../contrib/libcxx/include/__functional/function.h:1157: std::__1::function<void ()>::operator=(std::nullptr_t)
2022.04.30 05:09:20.235559 [ 211736 ] {} <Fatal> BaseDaemon: 15. ../src/Common/ThreadPool.cpp:284: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xfe24a5a in /usr/bin/clickhouse
2022.04.30 05:09:20.254577 [ 211736 ] {} <Fatal> BaseDaemon: 16. ./build_docker/../src/Common/ThreadPool.cpp:0: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xfe27522 in /usr/bin/clickhouse
2022.04.30 05:09:20.320270 [ 211736 ] {} <Fatal> BaseDaemon: 17. ? @ 0x7fcd17478609 in ?
2022.04.30 05:09:20.321345 [ 211736 ] {} <Fatal> BaseDaemon: 18. clone @ 0x7fcd1739d163 in ?
2022.04.30 05:09:20.685141 [ 211736 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: B8856D6C7BE3F7DA5C2D7AA8D916589E. There is no information about the reference checksum.
2022.04.30 05:09:40.729716 [ 388 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

Was caught in CI tests: https://s3.amazonaws.com/clickhouse-test-reports/36803/cef462f83d846ab7d5ccccf54ceb745ac99fc9db/stateless_tests__ubsan__actions_.html

**Comment by tavplubix** [comment] 2022-05-02 12:17
Duplicate of #36610

**Closed by tavplubix** 2022-05-02 12:17 UTC
Labels: testing, potential bug
