### ISSUE TITLE
Question: How does clickhouse optimize `where` conditions?

### ISSUE THREAD

**Issue by catwang01** [ClickHouse/ClickHouse#36414] opened 2022-04-19 07:59 UTC
Hi Team,

I'm running into something I can't understand while I'm running some simple queries.

Here is how I created my table.

```
CREATE TABLE video_log
(
 `datetime` DateTime, -- 20,000 records per second
 `user_id` UInt64, -- Cardinality == 10,000,000
 `device_id` UInt64, -- Cardinality == 20,000,000
 `video_id` UInt64, -- Cardinality == 10,00000
 `domain` LowCardinality(String), -- Cardinality == 100
 `bytes` UInt64, -- Ranging from 128 to 1152
 `duration` UInt64 -- Ranging from 100 to 400
)
ENGINE = MergeTree
PARTITION BY toDate(datetime) -- Daily partitioning
ORDER BY (user_id, device_id,video_id); -- Can only favor one column here
CREATE TABLE rng
(
 `user_id_raw` UInt64,
 `device_id_raw` UInt64,
 `video_id_raw` UInt64,
 `domain_raw` UInt64,
 `bytes_raw` UInt64,
 `duration_raw` UInt64
)
ENGINE = GenerateRandom(1024);
```

Insert data:

```
INSERT INTO video_log SELECT
     toUnixTimestamp(toDateTime(today()))
     + (rowNumberInAllBlocks() / 20000),
     user_id_raw % 10000000 AS user_id,
     device_id_raw % 20000000 AS device_id,
     video_id_raw % 10000000 AS video_id,
     domain_raw % 100,
     (bytes_raw % 1024) + 128,
     (duration_raw % 300) + 100
FROM rng
LIMIT 200000000;
```

And I ran the following four queries on this `video_log` table:

## query1

```
SELECT
    toStartOfHour(datetime) AS hour,
    sum(bytes),
    avg(duration)
FROM video_log
WHERE (toDate(hour) = today()) AND (device_id = '100')
GROUP BY hour

Query id: 0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174

┌────────────────hour─┬─sum(bytes)─┬─avg(duration)─┐
│ 2022-04-19 00:00:00 │        430 │           140 │
│ 2022-04-19 02:00:00 │        192 │           383 │
│ 2022-04-19 01:00:00 │       5993 │         179.2 │
└─────────────────────┴────────────┴───────────────┘
```

```
3 rows in set. Elapsed: 4.121 sec. Processed 200.00 million rows, 5.60 GB (48.53 million rows/s., 1.36 GB/s.)
2022.04.19 03:19:43.317923 [ 1097 ] {} <Debug> TCP-Session: 77125a79-1a01-47a5-bd35-d8b2aa46a7f6 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2022.04.19 03:19:43.318182 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Debug> executeQuery: (from [::1]:51948) SELECT toStartOfHour(datetime) AS hour, sum(bytes), avg(duration) FROM video_log WHERE (toDate(hour) = today()) AND (device_id = '100') GROUP BY hour
2022.04.19 03:19:43.318610 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "toDate(toStartOfHour(datetime) AS hour) = today()" moved to PREWHERE
2022.04.19 03:19:43.318872 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "toDate(toStartOfHour(datetime)) = today()" moved to PREWHERE
2022.04.19 03:19:43.319117 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> ContextAccess (default): Access granted: SELECT(datetime, device_id, bytes, duration) ON default.video_log
2022.04.19 03:19:43.319312 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> ContextAccess (default): Access granted: SELECT(datetime, device_id, bytes, duration) ON default.video_log
2022.04.19 03:19:43.319367 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.04.19 03:19:43.319593 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Key condition: unknown, (column 1 in [100, 100]), and, unknown, and
2022.04.19 03:19:43.319795 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): MinMax index condition: (toDate(toStartOfHour(column 0)) in [19101, 19101]), unknown, and, (toDate(toStartOfHour(column 0)) in [19101, 19101]), and
2022.04.19 03:19:43.327094 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_1_189_3 with 28809 steps
2022.04.19 03:19:43.327176 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_190_190_0 with 201 steps
2022.04.19 03:19:43.327220 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_191_191_0 with 151 steps
2022.04.19 03:19:43.327250 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Selected 3/3 parts by partition key, 3 parts by primary key, 24415/24415 marks by primary key, 24415 marks to read from 3 ranges
2022.04.19 03:19:43.327344 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_1_189_3, approx. 198175005 rows starting from 0
2022.04.19 03:19:43.327384 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_190_190_0, approx. 1048545 rows starting from 0
2022.04.19 03:19:43.327417 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_191_191_0, approx. 776450 rows starting from 0
2022.04.19 03:19:43.373495 [ 1306 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> AggregatingTransform: Aggregating
2022.04.19 03:19:43.373534 [ 1306 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> Aggregator: Aggregation method: key32
2022.04.19 03:19:44.030807 [ 1146 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 200.46 MiB, peak 1.17 GiB, will set to 199.22 MiB (RSS), difference: -1.24 MiB
2022.04.19 03:19:47.437470 [ 1306 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Debug> AggregatingTransform: Aggregated. 12 to 3 rows (from 240.00 B) in 4.109876952 sec. (2.920 rows/sec., 58.40 B/sec.)
2022.04.19 03:19:47.437510 [ 1306 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Trace> Aggregator: Merging aggregated data
2022.04.19 03:19:47.437795 [ 1097 ] {0a90fc67-4297-4e3a-a2f0-4ee7a3e5d174} <Information> executeQuery: Read 200000000 rows, 5.22 GiB in 4.119562684 sec., 48548842 rows/sec., 1.27 GiB/sec.
```

## query2

```sql
SELECT
    toStartOfHour(datetime) AS hour,
    sum(bytes),
    avg(duration)
FROM video_log
WHERE (toDate(hour) = today()) AND (device_id = 100)
GROUP BY hour

Query id: 89113fc0-916b-4a05-be25-0c054c111ebb

┌────────────────hour─┬─sum(bytes)─┬─avg(duration)─┐
│ 2022-04-19 00:00:00 │        430 │           140 │
│ 2022-04-19 02:00:00 │        192 │           383 │
│ 2022-04-19 01:00:00 │       5993 │         179.2 │
└─────────────────────┴────────────┴───────────────┘

3 rows in set. Elapsed: 1.176 sec. Processed 200.00 million rows, 1.60 GB (170.09 million rows/s., 1.36 GB/s.)
```

```
2022.04.19 03:08:30.379539 [ 1097 ] {} <Debug> TCP-Session: 77125a79-1a01-47a5-bd35-d8b2aa46a7f6 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2022.04.19 03:08:30.379772 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Debug> executeQuery: (from [::1]:51948) SELECT toStartOfHour(datetime) AS hour, sum(bytes), avg(duration) FROM video_log WHERE (toDate(hour) = today()) AND (device_id = 100) GROUP BY hour
2022.04.19 03:08:30.380150 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "device_id = 100" moved to PREWHERE
2022.04.19 03:08:30.380391 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "device_id = 100" moved to PREWHERE
2022.04.19 03:08:30.380594 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> ContextAccess (default): Access granted: SELECT(datetime, device_id, bytes, duration) ON default.video_log
2022.04.19 03:08:30.380772 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> ContextAccess (default): Access granted: SELECT(datetime, device_id, bytes, duration) ON default.video_log
2022.04.19 03:08:30.380819 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.04.19 03:08:30.381021 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Key condition: (column 1 in [100, 100]), unknown, and, (column 1 in [100, 100]), and
2022.04.19 03:08:30.381166 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): MinMax index condition: unknown, (toDate(toStartOfHour(column 0)) in [19101, 19101]), and, unknown, and
2022.04.19 03:08:30.389056 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_1_189_3 with 28809 steps
2022.04.19 03:08:30.389137 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_190_190_0 with 201 steps
2022.04.19 03:08:30.389187 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_191_191_0 with 151 steps
2022.04.19 03:08:30.389204 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Selected 3/3 parts by partition key, 3 parts by primary key, 24415/24415 marks by primary key, 24415 marks to read from 3 ranges
2022.04.19 03:08:30.389277 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_1_189_3, approx. 198175005 rows starting from 0
2022.04.19 03:08:30.389308 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_190_190_0, approx. 1048545 rows starting from 0
2022.04.19 03:08:30.389334 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_191_191_0, approx. 776450 rows starting from 0
2022.04.19 03:08:30.430314 [ 1306 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> AggregatingTransform: Aggregating
2022.04.19 03:08:30.430353 [ 1306 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> Aggregator: Aggregation method: key32
2022.04.19 03:08:31.523733 [ 1306 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Debug> AggregatingTransform: Aggregated. 12 to 3 rows (from 240.00 B) in 1.134252204 sec. (10.580 rows/sec., 211.59 B/sec.)
2022.04.19 03:08:31.523772 [ 1306 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Trace> Aggregator: Merging aggregated data
2022.04.19 03:08:31.524051 [ 1097 ] {6b5e72b8-8d03-4426-9e76-231c5fa0b715} <Information> executeQuery: Read 200000000 rows, 1.49 GiB in 1.144244641 sec., 174787796 rows/sec., 1.30 GiB/sec.
```

## query3

```sql
SELECT
    toStartOfHour(datetime) AS hour,
    sum(bytes),
    avg(duration)
FROM video_log
PREWHERE (toDate(hour) = today()) AND (device_id = '100')
GROUP BY hour

Query id: 4fb5f7f3-9bd1-4427-8683-3052efa1bb29

┌────────────────hour─┬─sum(bytes)─┬─avg(duration)─┐
│ 2022-04-19 00:00:00 │        430 │           140 │
│ 2022-04-19 02:00:00 │        192 │           383 │
│ 2022-04-19 01:00:00 │       5993 │         179.2 │
└─────────────────────┴────────────┴───────────────┘

3 rows in set. Elapsed: 2.042 sec. Processed 200.00 million rows, 2.40 GB (97.94 million rows/s., 1.18 GB/s.)
```

```log
2022.04.19 03:11:28.120198 [ 1097 ] {} <Debug> TCP-Session: 77125a79-1a01-47a5-bd35-d8b2aa46a7f6 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2022.04.19 03:11:28.120505 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Debug> executeQuery: (from [::1]:51948) SELECT toStartOfHour(datetime) AS hour, sum(bytes), avg(duration) FROM video_log PREWHERE (toDate(hour) = today()) AND (device_id = '100') GROUP BY hour
2022.04.19 03:11:28.121340 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> ContextAccess (default): Access granted: SELECT(datetime, device_id, bytes, duration) ON default.video_log
2022.04.19 03:11:28.121555 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> ContextAccess (default): Access granted: SELECT(datetime, device_id, bytes, duration) ON default.video_log
2022.04.19 03:11:28.121622 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.04.19 03:11:28.121837 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Key condition: unknown, (column 1 in [100, 100]), and
2022.04.19 03:11:28.121990 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): MinMax index condition: (toDate(toStartOfHour(column 0)) in [19101, 19101]), unknown, and
2022.04.19 03:11:28.129263 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_1_189_3 with 28809 steps
2022.04.19 03:11:28.129352 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_190_190_0 with 201 steps
2022.04.19 03:11:28.129397 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_191_191_0 with 151 steps
2022.04.19 03:11:28.129421 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Selected 3/3 parts by partition key, 3 parts by primary key, 24415/24415 marks by primary key, 24415 marks to read from 3 ranges
2022.04.19 03:11:28.129613 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_1_189_3, approx. 198175005 rows starting from 0
2022.04.19 03:11:28.129671 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_190_190_0, approx. 1048545 rows starting from 0
2022.04.19 03:11:28.129715 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_191_191_0, approx. 776450 rows starting from 0
2022.04.19 03:11:28.203625 [ 1306 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> AggregatingTransform: Aggregating
2022.04.19 03:11:28.203668 [ 1306 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> Aggregator: Aggregation method: key32
2022.04.19 03:11:29.041764 [ 1146 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 196.45 MiB, peak 1.17 GiB, will set to 198.18 MiB (RSS), difference: 1.73 MiB
2022.04.19 03:11:30.160807 [ 1306 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Debug> AggregatingTransform: Aggregated. 12 to 3 rows (from 240.00 B) in 2.030992309 sec. (5.908 rows/sec., 118.17 B/sec.)
2022.04.19 03:11:30.160843 [ 1306 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Trace> Aggregator: Merging aggregated data
2022.04.19 03:11:30.161091 [ 1097 ] {4fb5f7f3-9bd1-4427-8683-3052efa1bb29} <Information> executeQuery: Read 200000000 rows, 2.24 GiB in 2.040541826 sec., 98013183 rows/sec., 1.10 GiB/sec.
```
## query4

```sql
SELECT
    toStartOfHour(datetime) AS hour,
    sum(bytes),
    avg(duration)
FROM video_log
PREWHERE (toDate(hour) = today()) AND (device_id = 100)
GROUP BY hour

Query id: 1e175652-bd5d-4f26-a9c3-ef0862fed483

┌────────────────hour─┬─sum(bytes)─┬─avg(duration)─┐
│ 2022-04-19 00:00:00 │        430 │           140 │
│ 2022-04-19 02:00:00 │        192 │           383 │
│ 2022-04-19 01:00:00 │       5993 │         179.2 │
└─────────────────────┴────────────┴───────────────┘

3 rows in set. Elapsed: 2.100 sec. Processed 200.00 million rows, 2.40 GB (95.25 million rows/s., 1.14 GB/s.)
```

```
2022.04.19 03:13:08.142491 [ 1097 ] {} <Debug> TCP-Session: 77125a79-1a01-47a5-bd35-d8b2aa46a7f6 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2022.04.19 03:13:08.142733 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Debug> executeQuery: (from [::1]:51948) SELECT toStartOfHour(datetime) AS hour, sum(bytes), avg(duration) FROM video_log PREWHERE (toDate(hour) = today()) AND (device_id = 100) GROUP BY hour
2022.04.19 03:13:08.143401 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> ContextAccess (default): Access granted: SELECT(datetime, device_id, bytes, duration) ON default.video_log
2022.04.19 03:13:08.143585 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> ContextAccess (default): Access granted: SELECT(datetime, device_id, bytes, duration) ON default.video_log
2022.04.19 03:13:08.143637 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2022.04.19 03:13:08.143801 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Key condition: unknown, (column 1 in [100, 100]), and
2022.04.19 03:13:08.143936 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): MinMax index condition: (toDate(toStartOfHour(column 0)) in [19101, 19101]), unknown, and
2022.04.19 03:13:08.150894 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_1_189_3 with 28809 steps
2022.04.19 03:13:08.150972 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_190_190_0 with 201 steps
2022.04.19 03:13:08.151015 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Used generic exclusion search over index for part 20220419_191_191_0 with 151 steps
2022.04.19 03:13:08.151034 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Debug> default.video_log (122826ef-12f7-42a6-9f9a-c6c2cecf314e) (SelectExecutor): Selected 3/3 parts by partition key, 3 parts by primary key, 24415/24415 marks by primary key, 24415 marks to read from 3 ranges
2022.04.19 03:13:08.151128 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_1_189_3, approx. 198175005 rows starting from 0
2022.04.19 03:13:08.151172 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_190_190_0, approx. 1048545 rows starting from 0
2022.04.19 03:13:08.151209 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part 20220419_191_191_0, approx. 776450 rows starting from 0
2022.04.19 03:13:08.220582 [ 1306 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> AggregatingTransform: Aggregating
2022.04.19 03:13:08.220624 [ 1306 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> Aggregator: Aggregation method: key32
2022.04.19 03:13:09.018255 [ 1146 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 196.63 MiB, peak 1.17 GiB, will set to 198.25 MiB (RSS), difference: 1.62 MiB
2022.04.19 03:13:10.240731 [ 1306 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Debug> AggregatingTransform: Aggregated. 12 to 3 rows (from 240.00 B) in 2.089440249 sec. (5.743 rows/sec., 114.86 B/sec.)
2022.04.19 03:13:10.240770 [ 1306 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Trace> Aggregator: Merging aggregated data
2022.04.19 03:13:10.241021 [ 1097 ] {1e175652-bd5d-4f26-a9c3-ef0862fed483} <Information> executeQuery: Read 200000000 rows, 2.24 GiB in 2.098252225 sec., 95317425 rows/sec., 1.07 GiB/sec.
```

These 4 queries are very similar. But their performances are different. I'm trying to understand why their speeds are different.
1. Why did query1 treat  `(toDate(hour) = today())` as perwhere condition while query2 treated `device_id = 100` as perwhere condition? 
2. Why were query3 and query4 slower than query2? I think the manually added prewhere `(toDate(hour) = today()) AND (device_id = 100)` will filter out more data than prewhere  `(device_id = 100)` in query2, which was added by optimizer. But it seemed the prewhere added by optimizer outperformed manually added one .

I'm using clickhouse 22.3.2.1.

Thanks! Look forward to your reply!

**Comment by catwang01** [comment] 2022-04-20 03:55
> but `device_id = 100` != `device_id = '100'`
> 
> It is impossible to use primary index with `device_id = '100'` -- `toUInt64(String)` is not monotonic function. And it's not correct to make `device_id = '100'`-> `device_id = 100` automatically because it will yield incorrect result.

If I understand it correctly, although in this example, both device_id = 100 and device_id = '100' yield the same results, from query analysis perspective, we can't treat device_id = '100' as device_id = 100?

And I don't get it why don't first do conversion `device_id = '100`'-> `device_id = 100` and then check if the index is hit?

Also, it doesn't explain why query2 is faster than query4. Both use `device_id = 100` as prewhere condition, why query4 is slower .

**Comment by den-crane** [comment] 2022-04-21 22:45
>And I don't get it why don't first do conversion device_id = '100'-> device_id = 100 and then check if the index is hit?

All databases forbids such conversion. Because the query result will be incorrect in general.

`where device_id = '0100'` -> have to yield zero rows because left argument should be converted to a string `'100' != '0100'`

If we convert right argument to int the query will return 1 row because `100 == toInt('0100')`

The same behaviour with any database: check mysql , pg, oracle ...

**Comment by catwang01** [comment] 2022-04-22 04:02
> > And I don't get it why don't first do conversion device_id = '100'-> device_id = 100 and then check if the index is hit?
> 
> All databases forbid such optimization. Because the query result will be incorrect in general.
> 
> `where device_id = '0100'` have to yield zero rows because the left argument should be converted to a string and `'100' != '0100'`
> 
> If we convert the right argument to int then the query will return 1 row because `100 == toInt('0100')`
> 
> The same behaviour with any database: check mysql , pg, oracle ...

So, generally, for a condition like `where colA = valueB`, if `colA` and `valueB` have different types, we try to convert `colA` into the same type as `valueB`, instead of converting `valueB` into the same type as `colA`? And this is the reason why we can't do such optimization?

And could you give some hints about why query4 is slower than query2?

**Comment by Algunenano** [comment] 2024-07-03 18:17
This doesn't reproduce anymore. WHERE / PREWHERE has been reworked several times and there are new settings to control some of these optimizations (`move_all_conditions_to_prewhere`, `enable_multiple_prewhere_read_steps`, `move_primary_key_columns_to_end_of_prewhere`).

Should be re-tested with a recent release

**Closed by Algunenano** 2024-07-03 18:17 UTC
Labels: question
