### ISSUE TITLE
Bad comparison of IPv6 to String: toIPv6('::1') != '::1'

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#14567] opened 2020-09-08 03:40 UTC
```
:) select toIPv6('::1') = '::1'

┌─equals(toIPv6('::1'), '::1')─┐
│                            0 │
└──────────────────────────────┘
```

Not sure what's going on. It does some implicit cast, but somehow casts to a wrong type? I would expect an error about implicit cast since we don't do them often, or at least that they compare as equal.

**Comment by tavplubix** [comment] 2021-01-25 16:34
It's because `IPv6` data type implemented as `FixedString(16)` with custom serialization ([link](https://github.com/ClickHouse/ClickHouse/blob/a6f787faeac4ecb1cb2eafa63ea38f0b3734ce0e/src/DataTypes/DataTypeCustomIPv4AndIPv6.cpp#L101)), so `equals` function compares binary representation of `toIPv6('::1')` as `FixedString(16)` with `::1` as `String`. Maybe we should take custom serialization into account when resolving a function overload.

Another funny example:
```
:) select toIPv4('127.0.0.1') = 2.130706433e9 as e

┌─e─┐
│ 1 │
└───┘
```

**Comment by qoega** [comment] 2021-01-26 10:09
Still reproducing.
``` sql
SELECT toTypeName(toIPv6('::1'))

Query id: 0eb293f1-cc3d-4643-abc1-e4924e32f45d

┌─toTypeName(toIPv6('::1'))─┐
│ IPv6                      │
└───────────────────────────┘

1 rows in set. Elapsed: 0.030 sec.
```

`EXPLAIN` shows nothing interesting in this case. We can show whether `'::1'` casts to `IPv6` or otherwise `IPv6('::1)'` casted to String.

**Comment by alexey-milovidov** [comment] 2021-01-26 19:22
I think we need to get rid of "data type domains". See:

```
    /// This is mutable to allow setting custom name and serialization on `const IDataType` post construction.
    mutable DataTypeCustomNamePtr custom_name;
    mutable DataTypeCustomTextSerializationPtr custom_text_serialization;
    mutable DataTypeCustomStreamsPtr custom_streams;
```

This was an ugly hack that should not exist.
We can rewrite IPv4, IPv6 to real data types.

**Comment by alexey-milovidov** [comment] 2021-09-26 01:12
This is a tech debt after introducing "data type domains".
I will assign to @Enmk, maybe he can find a workaround without removing "data type domains",
though I think that they have to be removed.

**Comment by Enmk** [comment] 2022-06-18 06:02
> I think we need to get rid of "data type domains". See:
> 
> ```
>     /// This is mutable to allow setting custom name and serialization on `const IDataType` post construction.
>     mutable DataTypeCustomNamePtr custom_name;
>     mutable DataTypeCustomTextSerializationPtr custom_text_serialization;
>     mutable DataTypeCustomStreamsPtr custom_streams;
> ```
> 
> This was an ugly hack that should not exist. It also affects performance in a range of 10% for serialization / deserialization.
> 
> We can rewrite IPv4, IPv6 to real data types.

Do we have any benchmark that can be used to investigate the performance issue? And, as far as I know, serialization code was refactored at least once since the initial implementation of "domains", is the issue still present?

**Comment by alexey-milovidov** [comment] 2022-06-18 18:11
@Enmk yes, it is still present. Two virtual calls instead of one.
Also, the code is poisoned by these "data type domains", and it is a constant source of bugs like this.
Ask @kitaisreal if you are not convinced.

**Comment by alexey-milovidov** [comment] 2022-07-17 21:03
No reaction from @Enmk

**Comment by alexey-milovidov** [comment] 2022-10-09 02:59
This task requires the removal of "data type domains", erroneously introduced a long time ago.

**Comment by alexey-milovidov** [comment] 2022-10-19 23:31
We still need to remove the "data type domains" to solve this task.

**Comment by alexey-milovidov** [comment] 2022-11-13 23:15
@yakov-olkhovskiy 

Data type domains (or customizations) are represented by the same objects that the existing data types do.
For example, IPv4 is represented by DataTypeUInt32.

They just inject a few hacks inside the existing data type:
- different name;
- different text serialization and deserialization.

It was maybe a good or a bad idea.

The advantages are:
- it was a low-effort change of the code;
- developers adding new "data type domains" easily, such as geographical types, SimpleAggregateFunction, Bool;
- all function overloads for customized data types continue to work as for the based data type;

The disadvantages are:
- it is a too ad-hoc change in code, increasing the number of fragile concepts we did not plan to have;
- all function overloads for customized data types continue to work as for the based data type, but not always supposed to work this way, as shown in this task;

If we will not find a simpler solution, the proposal is to make IPv4 and IPv6 full-featured types instead of "data type domains".
It wouldn't be easy to remove the data type domains completely, as they work almost alright for Geo and Bool types.

**Comment by vdimir** [comment] 2022-11-14 11:12
> all function overloads for customized data types continue to work as for the based data type, but not always supposed to work this way, as shown in this task

Can't we forbid it by default and allow only specified ones?

E.g. in Haskell we can use `type` and `newtype` for introducing type aliases, but `type` is interchangeable with the underlying type, but `newtype` hides it. https://wiki.haskell.org/Type

May we follow `newtype` semantic?

**Comment by alexey-milovidov** [comment] 2022-11-15 01:19
It's convoluted:

- geo types only change the type name (IIRC);
- SimpleAggregateFunction change name and interpreted especially in tables' merging process;
- Bool changes the name and serialization;

**Comment by alexey-milovidov** [comment] 2022-11-15 01:19
See also https://github.com/ClickHouse/ClickHouse/issues/18568

**Closed** 2023-01-07 11:01 UTC
Labels: bug, st-in-progress
