### ISSUE TITLE
Add support for `representAsDateTime64` function

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#13650] opened 2020-08-12 12:04 UTC
**Use case**
There is no way to convert binary data to `DateTime64` data type.

**Describe the solution you'd like**
Similar to the [representAsDateTime](https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/#reinterpretasdatetime) function it would be nice to have `representAsDateTime64` function.

**Comment by alexey-milovidov** [comment] 2021-03-22 19:17
Duplicate of #10672. Fixed.

**Comment by alexey-milovidov** [comment] 2021-03-22 19:18
```
SELECT reinterpret(now64(3), 'UInt64')

┌─reinterpret(now64(3), 'UInt64')─┐
│                   1616440198659 │
└─────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment] 2021-03-22 19:18
```
SELECT reinterpret(1616440198659, 'DateTime64(3)')

┌─reinterpret(1616440198659, 'DateTime64(3)')─┐
│                     2021-03-22 22:09:58.659 │
└─────────────────────────────────────────────┘
```

**Closed by alexey-milovidov** 2021-03-22 19:17 UTC
Labels: comp-datetime, duplicate, feature, st-fixed
