### ISSUE TITLE
support apache pulsar

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/ClickHouse#9615] opened 2020-03-12 04:49 UTC
Aapche Pulsar will be the mainstream message engine in the future.
Transplant Kafka support capability to pulsar.
Pulsar ref:
https://dzone.com/articles/life-beyond-kafka-with-apache-pulsar
https://dzone.com/articles/5-more-reasons-to-choose-apache-pulsar-over-kafka
https://kafkaesque.io/7-reasons-we-choose-apache-pulsar-over-apache-kafka

thanks.
regard.

**Comment by filimonov** [comment] 2020-06-19 07:04
Duplicate of #4226

**Closed by filimonov** 2020-06-19 07:04 UTC
Labels: feature
