### ISSUE TITLE
Hash functions should be checked at table creation, not at sampling time

### ISSUE THREAD

**Issue by 3manuek** [ClickHouse/ClickHouse#822] opened 2017-05-24 04:52 UTC
It is possible to create a table within a non-UInt hash column (i.e. MD5) and insert data, although at query time it complains:

```
ENGINE = MergeTree(normdate,MD5(id), (created_at, id,MD5(id)),8192);
...
Code: 59. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Invalid sampling column type in storage parameters: FixedString(16). Must be unsigned integer type..
```
This probably will be better to check at creation time.

**Comment by dorantor** [comment] 2017-10-17 10:41
BTW, what would be an optimal way to convert/alter table from UUID field(FixedString(16)) as sampling field, to something like `sipHash64(cid)`(or maybe there is a better option?), where `cid` defined as `cid FixedString(16)` and contains UUIDs in binary form from `UUIDStringToNum()`.
I mean, data in table I would like to leave as it is and update/alter only `ENGINE = MergeTree(...)` part.

**Comment by dorantor** [comment] 2017-10-18 06:59
Managed to find a solution. In case somebody else will face it sharing my solution. There is no direct way to change MergeTree() options. You have to CREATE new table, INSERT SELECT data from old table, DROP old one and RENAME newly created. 
I was lucky, I had only 800mil records and I could stop data flow into my Clickhouse for about 20 minutes.
And, BTW, sipHash64() doesn't accept FixedString, only String.

**Comment by 3manuek** [comment] 2017-10-26 17:42
@dorantor, I think it will be better for visibility to open a new issue as this is not directly related with the reported bug. If I'm not mistaken, there must be work being done to fix these things in long term.

Yeah, unfortunately you need to recreate the table with the new options :(

**Comment by alexey-milovidov** [comment] 2019-11-01 17:41
The issue is still relevant.
Test:

```
milovidov-Pro-P30 :) CREATE TABLE test.mt (x UUID) ENGINE = MergeTree ORDER BY tuple(x) SAMPLE BY x

CREATE TABLE test.mt
(
    `x` UUID
)
ENGINE = MergeTree
ORDER BY tuple(x)
SAMPLE BY x

Ok.

0 rows in set. Elapsed: 0.012 sec. 

milovidov-Pro-P30 :) SELECT * FROM test.mt SAMPLE 0.1

SELECT *
FROM test.mt
SAMPLE 1 / 10

Received exception from server (version 19.17.1):
Code: 59. DB::Exception: Received from localhost:9000. DB::Exception: Invalid sampling column type in storage parameters: UUID. Must be unsigned integer type.
```

Currently it isn't assigned to anyone.

**Closed** 2021-07-14 11:16 UTC
Labels: easy task, enhancement
