### ISSUE TITLE
Unexpected behaviour of aes_decrypt_mysql function

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#36494] opened 2022-04-21 14:20 UTC
ClickHouse v.22.3.3.44

Got exсeption when aes_encrypt_mysql got unexpected result as input

`create table test_table
(
    value           Nullable(String),
    encrypted_value Nullable(String)
)
    engine MergeTree order by assumeNotNull(value);

insert into test_table
select 'test_value1', aes_encrypt_mysql('aes-256-ecb', 'test_value1', 'test_key________________________');
insert into test_table
select '', aes_encrypt_mysql('aes-256-ecb', '', 'test_key________________________');
insert into test_table
select null, aes_encrypt_mysql('aes-256-ecb', null, 'test_key________________________');

select aes_decrypt_mysql('aes-256-ecb', value, 'test_key________________________')
from test_table`

got `Failed to decrypt. OpenSSL error code: 503316603: while executing 'FUNCTION aes_decrypt_mysql` as exception

Can we get same result of aes_decrypt_mysql as it work at MySql DB? Can aes_decrypt_mysql return Null instead of exceptioin, if input is unexpected for function for example?

**Comment by alexey-milovidov** [comment] 2022-10-20 02:24
Duplicate of #28131.

**Closed by alexey-milovidov** 2022-10-20 02:24 UTC
Labels: duplicate, unexpected behaviour
