### ISSUE TITLE
Received signal Segmentation fault (11)

### ISSUE THREAD

**Issue by ramun25** [ClickHouse/ClickHouse#6098] opened 2019-07-22 09:01 UTC
ClickHouse client version 19.1.7.
Connected to ClickHouse server version 19.3.5 revision 54415.

2019.07.22 10:39:03.147536 [ 190 ] {} Aggregator: Aggregation method: serialized
2019.07.22 10:39:03.147573 [ 190 ] {} Aggregator: Converting aggregation data to two-level.

--других процессов с номером 190 - нет.

2019.07.22 10:39:18.486403 [ 878 ] {} BaseDaemon: ########################################
2019.07.22 10:39:18.486460 [ 878 ] {} BaseDaemon: (from thread 190) Received signal Segmentation fault (11).
2019.07.22 10:39:18.486470 [ 878 ] {} BaseDaemon: Address: NULL pointer.
2019.07.22 10:39:18.486477 [ 878 ] {} BaseDaemon: Access: read.
2019.07.22 10:39:18.486483 [ 878 ] {} BaseDaemon: Unknown si_code.
2019.07.22 10:39:18.511952 [ 878 ] {} BaseDaemon: 0. clickhouse-server(DB::ColumnVector::deserializeAndInsertFromArena(char const*)+0x16) [0x55ebb66]
2019.07.22 10:39:18.512085 [ 878 ] {} BaseDaemon: 1. clickhouse-server(void DB::Aggregator::convertToBlockImplNotFinal<DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash, HashTableNoState>, DefaultHash, TwoLevelHashTableGrower<8ul>, Allocator, HashMapTable> >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash, HashTableNoState>, DefaultHash, TwoLevelHashTableGrower<8ul>, Allocator > >(DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash, HashTableNoState>, DefaultHash, TwoLevelHashTableGrower<8ul>, Allocator, HashMapTable> >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash, HashTableNoState>, DefaultHash, TwoLevelHashTableGrower<8ul>, Allocator >&, std::vector<COWPtrDB::IColumn::mutable_ptrDB::IColumn, std::allocator<COWPtrDB::IColumn::mutable_ptrDB::IColumn > >&, std::vector<DB::PODArray<char*, 4096ul, Allocator, 15ul, 16ul>, std::allocator<DB::PODArray<char, 4096ul, Allocator, 15ul, 16ul>> >&) const+0x7c) [0x59438cc]
2019.07.22 10:39:18.512185 [ 878 ] {} BaseDaemon: 2. clickhouse-server(DB::Block DB::Aggregator::prepareBlockAndFill<DB::Block DB::Aggregator::convertOneBucketToBlock<DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char, DefaultHash, HashTableNoState>, DefaultHash, TwoLevelHashTableGrower<8ul>, Allocator, HashMapTable> > >(DB::AggregatedDataVariants&, DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash, HashTableNoState>, DefaultHash, TwoLevelHashTableGrower<8ul>, Allocator, HashMapTable> >&, bool, unsigned long) const::{lambda(std::vector<COWPtrDB::IColumn::mutable_ptrDB::IColumn, std::allocator<COWPtrDB::IColumn::mutable_ptrDB::IColumn > >&, std::vector<DB::PODArray<char*, 4096ul, Allocator, 15ul, 16ul>, std::allocator<DB::PODArray<char, 4096ul, Allocator, 15ul, 16ul>> >&, std::vector<COWPtrDB::IColumn::mutable_ptrDB::IColumn, std::allocator<COWPtrDB::IColumn::mutable_ptrDB::IColumn > >&, bool)#1}>(DB::AggregatedDataVariants&, bool, unsigned long, DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char, DefaultHash, HashTableNoState>, DefaultHash, TwoLevelHashTableGrower<8ul>, Allocator, HashMapTable> >&&) const+0x434) [0x5961c34]
2019.07.22 10:39:18.512216 [ 878 ] {} BaseDaemon: 3. clickhouse-server(DB::MergingAndConvertingBlockInputStream::thread(int, std::shared_ptrDB::ThreadGroupStatus)+0x9c0) [0x59b4120]
2019.07.22 10:39:18.512274 [ 878 ] {} BaseDaemon: 4. clickhouse-server(std::_Function_handler<void (), std::_Bind<void (DB::MergingAndConvertingBlockInputStream::(DB::MergingAndConvertingBlockInputStream, int, std::shared_ptrDB::ThreadGroupStatus))(int, std::shared_ptrDB::ThreadGroupStatus)> >::_M_invoke(std::_Any_data const&)+0x50) [0x59238d0]
2019.07.22 10:39:18.512291 [ 878 ] {} BaseDaemon: 5. clickhouse-server(ThreadPoolImpl::worker(std::_List_iterator)+0x199) [0x5da2cb9]
2019.07.22 10:39:18.512325 [ 878 ] {} BaseDaemon: 6. clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl::scheduleImpl(std::function<void ()>, int, std::optional)::{lambda()#3}>(void ThreadPoolImpl::scheduleImpl(std::function<void ()>, int, std::optional)::{lambda()#3}&&)::{lambda()#1}::operator()() const+0x28) [0x5da3108]
2019.07.22 10:39:18.512346 [ 878 ] {} BaseDaemon: 7. clickhouse-server(ThreadPoolImplstd::thread::worker(std::_List_iteratorstd::thread)+0x199) [0x5da11e9]
2019.07.22 10:39:18.512368 [ 878 ] {} BaseDaemon: 8. clickhouse-server() [0x65c572f]
2019.07.22 10:39:18.512382 [ 878 ] {} BaseDaemon: 9. /lib64/libpthread.so.0(+0x7dc5) [0x7ff8b0351dc5]

**Comment by akuzm** [comment] 2019-07-22 10:20
Hi @ramun25, thanks for reporting! Is it a one-time issue or a frequent one? If you can reproduce it reliably, it would be helpful to have a small test case, so that we can reproduce it ourselves and debug the problem.

We recently fixed a similar issue #4402. The fix is in master branch, and is going to be released in 19.12. Maybe it fixes your case as well.

**Comment by Imomoi** [comment] 2019-07-22 13:54
Hi there.

Looks like we have similar issue on 19.9.3.31 (official build) under Ubuntu on AWS EC2.

    2019.07.22 12:46:00.869158 [ 1560 ] {} <Error> BaseDaemon: ########################################
    2019.07.22 12:46:00.869244 [ 1560 ] {} <Error> BaseDaemon: (version 19.9.3.31 (official build)) (from thread 1519) Received signal Segmentation fault (11).
    2019.07.22 12:46:00.869272 [ 1560 ] {} <Error> BaseDaemon: Address: NULL pointer.
    2019.07.22 12:46:00.869289 [ 1560 ] {} <Error> BaseDaemon: Access: read.
    2019.07.22 12:46:00.869322 [ 1560 ] {} <Error> BaseDaemon: Unknown si_code.
    2019.07.22 12:46:01.325007 [ 1560 ] {} <Error> BaseDaemon: 0. /lib/x86_64-linux-gnu/libc.so.6(+0x16eff6) [0x7fed46d9aff6]
    2019.07.22 12:46:01.345662 [ 1560 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x24) [0x39d8b14]
    2019.07.22 12:46:01.345718 [ 1560 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::SyntaxAnalyzer::analyze(std::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<DB::IStorage>) const+0x1510) [0x67bc360]
    2019.07.22 12:46:01.345748 [ 1560 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x49e) [0x66e3fee]
    2019.07.22 12:46:01.345774 [ 1560 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x4a) [0x66e4e4a]
    2019.07.22 12:46:01.345792 [ 1560 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x76f) [0x66f1e4f]
    2019.07.22 12:46:01.345828 [ 1560 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::StorageView::read(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int)+0x48a) [0x6d5725a]
    2019.07.22 12:46:01.345849 [ 1560 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x202a) [0x66def4a]
    2019.07.22 12:46:01.345873 [ 1560 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x6f7) [0x66e25d7]
    2019.07.22 12:46:01.345891 [ 1560 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x4f) [0x66e513f]
    2019.07.22 12:46:01.345900 [ 1560 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x6c) [0x66f069c]
    2019.07.22 12:46:01.345916 [ 1560 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::execute()+0x38) [0x66f0f38]
    2019.07.22 12:46:01.345939 [ 1560 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server() [0x6d05e37]
    2019.07.22 12:46:01.345948 [ 1560 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::LazyBlockInputStream::readImpl()+0x7f) [0x68e29ff]
    2019.07.22 12:46:01.345963 [ 1560 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::IBlockInputStream::read()+0x188) [0x65926e8]
    2019.07.22 12:46:01.345971 [ 1560 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server(DB::CreatingSetsBlockInputStream::createOne(DB::SubqueryForSet&)+0x55c) [0x6b5df9c]
    2019.07.22 12:46:01.345984 [ 1560 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(DB::CreatingSetsBlockInputStream::readPrefixImpl()+0x3f) [0x6b6003f]
    2019.07.22 12:46:01.345993 [ 1560 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x7a) [0x658e56a]
    2019.07.22 12:46:01.346001 [ 1560 ] {} <Error> BaseDaemon: 18. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346018 [ 1560 ] {} <Error> BaseDaemon: 19. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346026 [ 1560 ] {} <Error> BaseDaemon: 20. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346039 [ 1560 ] {} <Error> BaseDaemon: 21. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346048 [ 1560 ] {} <Error> BaseDaemon: 22. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346061 [ 1560 ] {} <Error> BaseDaemon: 23. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346070 [ 1560 ] {} <Error> BaseDaemon: 24. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346082 [ 1560 ] {} <Error> BaseDaemon: 25. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346092 [ 1560 ] {} <Error> BaseDaemon: 26. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346110 [ 1560 ] {} <Error> BaseDaemon: 27. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346119 [ 1560 ] {} <Error> BaseDaemon: 28. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346131 [ 1560 ] {} <Error> BaseDaemon: 29. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346141 [ 1560 ] {} <Error> BaseDaemon: 30. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346153 [ 1560 ] {} <Error> BaseDaemon: 31. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346163 [ 1560 ] {} <Error> BaseDaemon: 32. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346177 [ 1560 ] {} <Error> BaseDaemon: 33. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x157) [0x6ba2c97]
    2019.07.22 12:46:01.346227 [ 1560 ] {} <Error> BaseDaemon: 34. /usr/bin/clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::process()::{lambda()#1}>(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::process()::{lambda()#1}&&)::{lambda()#1}::operator()() const+0x71) [0x6ba3291]
    2019.07.22 12:46:01.346241 [ 1560 ] {} <Error> BaseDaemon: 35. /usr/bin/clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1af) [0x728caef]
    2019.07.22 12:46:01.346249 [ 1560 ] {} <Error> BaseDaemon: 36. /usr/bin/clickhouse-server() [0xb1a369f]
    2019.07.22 12:46:01.346256 [ 1560 ] {} <Error> BaseDaemon: 37. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fed477126ba]

Also I have this partial crash: 
[_usr_bin_clickhouse.0.crash.log](https://github.com/yandex/ClickHouse/files/3417721/_usr_bin_clickhouse.0.crash.log)

**Comment by akuzm** [comment] 2019-07-22 14:15
@Imomoi the call stack is completely different, so it's probably another bug. Could you create a separate issue? The test case would be helpful as well, because from the call stack alone it's hard to understand the reason, so we must reproduce it locally.

**Comment by Imomoi** [comment] 2019-07-22 14:23
@akuzm - registered #6105

**Comment by alexey-milovidov** [comment] 2019-08-21 04:28
@ramun25 Does the issue reproduce in 19.11 or 19.13?

**Closed** 2020-04-20 03:01 UTC
Labels: bug, crash, st-need-info
