### ISSUE TITLE
Support for views in odbc tables and dictionaries

### ISSUE THREAD

**Issue by siradjev** [ClickHouse/ClickHouse#21607] opened 2021-03-10 19:33 UTC
(you don't have to strictly follow this form)

**Use case**
ODBC is one of the main ways in clickhouse for making external integrations for slow changing data or dimensional data. 
Quite frequently data that needs to be brought in is a result of some complex query that may include joins or subqueries. 
Another problem lies in having enormous overhead when only few columns are needed from the wide table, but clickhouse will select all of them. 
Currently the only way to achieve it is to either create some sort of view on remote end, or use ETL to get processed data into Clickhouse. 
Frequently, in real life, the remote data source access is read-only, and does not allow creating objects on remote side, so solution is not really feasible. 

**Describe the solution you'd like**
Allow view() like syntax for odbc data sources when using in dictionaries and tables. 
E.g.
```
CREATE DICTIONARY xxx....
...
SOURCE(
   ODBC(
       CONNECTION_STRING 'DSN=MYSRC' 
       TABLE 'SELECT TBL1.NAME, TBL2.NAME FROM TBL1 JOIN TBL2 ON TBL1.ID=TBLD2.ID' 
        INVALIDATE_QUERY 'SELECT MAX(LAST_DATA) FROM TBL2'
    )
)
...
```

Of course in this case, user creating the query is responsible for matching columns to DDL of dictionary/table properly. 

**Describe alternatives you've considered**
There is no really other alternative except views (unnecessary objects + permissions issue) or custom data processing (huge overhead in terms of point of failures and data inconsistencies for simple task).

**Comment by siradjev** [comment] 2021-03-10 20:18
#19320 has similar request so they probably can be implemented together.

**Comment by filimonov** [comment] 2021-03-11 07:54
Also that remind me https://github.com/ClickHouse/ClickHouse/issues/1270 :)

**Comment by filimonov** [comment] 2021-08-17 10:34
https://github.com/ClickHouse/ClickHouse/issues/19320 ?

**Comment by alexey-milovidov** [comment] 2024-01-01 16:38
Duplicate of #46758

**Closed** 2024-01-01 16:39 UTC
Labels: duplicate, feature, comp-odbc
