### ISSUE TITLE
grant failure

### ISSUE THREAD

**Issue by JiangShangYu1024** [ClickHouse/ClickHouse#56067] opened 2023-10-27 04:47 UTC
clickhouse version 23.8.4.69

CREATE USER test ON CLUSTER 'cluster-sss' IDENTIFIED WITH PLAINTEXT_PASSWORD BY 'test'
CREATE ROLE role1 ON CLUSTER 'cluster-sss'
GRANT ON CLUSTER 'cluster-sss' SELECT ON table1 TO role1
GRANT ON CLUSTER 'cluster-sss' role1 TO test

After I log in with my test account and execute the select statement
The result does not meet expectations（Our cluster is multi node, and some nodes have exceptions）

DB::Exception: test: Not enough privileges. To execute this query, it's necessary to have the grant SELECT(id, age) ON table1 (ACCESS_DENIED)
```[tasklist]
### Tasks
```

**Comment by rkozlo** [comment] 2023-10-27 06:02
Because you only granted role but it is not used
One way to use
SET ROLE role1
or another way is to set all roles to default 
ALTER USER test DEFAULT ROLE role1, role2

**Comment by JiangShangYu1024** [comment] 2023-10-27 07:47
@rkozlo

**Comment by rkozlo** [comment] 2023-10-27 08:13
You granted role without enabling it. Even in linked issue roles are enabled. So it doesn't really related in my opinion.

**Comment by den-crane** [comment] 2023-10-27 13:09
Is it reproducible? What if you restart Clickhouse?

**Comment by JiangShangYu1024** [comment] 2023-10-30 11:12
@den-crane 
Grant failure can be replicated, and restarting the CH cluster has no effect
My CH cluster has a total of 6 nodes, some of which wait for a few hours or days before the grant command takes effect, but some nodes are still not effective.

**Comment by pufit** [comment] 2023-10-31 02:14
Am I understanding correctly that you are facing the error only with particular nodes, and the other nodes are working as expected? In that case, you should provide some additional info (e.g., errors from nodes during execution of your CREATE/GRANT queries).

Also, there are other options for storing access control information in persistent storage, for example, in ClickHouse Keeper/ZooKeeper https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#user_directories

**Comment by lampjian** [comment] 2023-10-31 23:17
It works fine with version 23.8 and earlier on just one server. Maybe there are some exceptions on some instance when using the cluster method.

**Comment by tbragin** [comment] 2024-05-25 17:02
>  In that case, you should provide some additional info (e.g., errors from nodes during execution of your CREATE/GRANT queries).

I see request for additional info above, but none provided. 

Closing this issue. Please comment if you are still seeing this problem persists with ^^

**Closed by tbragin** 2024-05-25 17:02 UTC
Labels: question, comp-rbac
