### ISSUE TITLE
Do we have some mechanism to ensure that subqueries sent from initial node won't be optimized by rewritten.

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#34862] opened 2022-02-24 07:40 UTC
**Use case**
Do we have some mechanism to ensure that subqueries sent from initial node won't be optimized by rewritten. 
This would make sense to reduce the exceptions `Not found column` which happened when initial node didn't optimize by rewritting ast but worker node did it.

**Comment by vdimir** [comment] 2022-02-25 08:56
In some cases we applying optimization only on initial node. Need to check other places if we can perform extra rewrite. 
https://github.com/ClickHouse/ClickHouse/blob/1f92fb5b40c27271c73f023f873e29744d473a6a/src/Interpreters/TreeRewriter.cpp#L1191-L1193

https://github.com/ClickHouse/ClickHouse/blob/1f92fb5b40c27271c73f023f873e29744d473a6a/src/Interpreters/ExpressionAnalyzer.cpp#L350-L352

Do you have any example where it breaks something?

**Comment by taiyang-li** [comment] 2022-03-01 04:22
@vdimir 
When a clickhouse cluster is deployed with both new and old versions. For example old version before https://github.com/ClickHouse/ClickHouse/pull/17041  that doesn't support settings `optimize_rewrite_sum_if_to_count_if` and new version after that pr.  

If `optimize_rewrite_sum_if_to_count_if` is enabled, Then query with sumIf(1, condition) sent from older version will throw exception: Not found column sumIf(1, condition) in block.  Because worker nodes with newer version will rewrite sumIf to countIf,  then initial node will find local block header is not matched with block received from worker nodes.

**Comment by taiyang-li** [comment] 2022-03-01 04:24
If we disable rewrite AST in worker nodes, those issues will be solved easily.

**Comment by vdimir** [comment] 2022-03-01 11:20
Like that? https://github.com/ClickHouse/ClickHouse/pull/34962
First, let's wait CI if something will broken

**Comment by taiyang-li** [comment] 2022-03-02 03:25
@vdimir Yes, but I'am not sure if there are other optimize_XXX settings which rewrite ast.

**Comment by vdimir** [comment] 2022-03-04 11:12
I tried to add test https://github.com/ClickHouse/ClickHouse/pull/35049 but it's not fail locally.

@taiyang-li do you have reproducible example?

**Comment by taiyang-li** [comment] 2022-03-07 03:55
@vdimir  You should test it in clickhouse cluster with some replicas deployed with old version before the pr which brought `optimize_rewrite_sum_if_to_count_if`, and some deployed with new version after that pr. 

1. create table 
```
CREATE TABLE default.table on cluster ck_cluster_preonline 
(

    `reportTime` UInt32,
    `appId` UInt32,
    `platform` UInt16,
    `firstIFrameTs` UInt16,
    `day` Date DEFAULT toDate(rtime),
    `rtime` DateTime DEFAULT toDateTime(reportTime)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/test/table', '{replica}')
PARTITION BY toYYYYMMDD(day)
ORDER BY (rtime, reportTime, appId)
TTL day + toIntervalMonth(3)
SETTINGS index_granularity = 8192 


CREATE TABLE IF NOT EXISTS default.table_all on cluster ck_cluster_preonline AS default.table
ENGINE = Distributed(ck_cluster_preonline, default, table, rand()) 
```

2. insert some data
3. Execute query: 
```
SELECT 
    toStartOfMinute(toDateTime(reportTime)) AS rtime, 
    sumIf(multiIf((firstIFrameTs > 0) AND (firstIFrameTs <= 100), 1, 0), (appId = 60) AND (platform IN (0, 1)) AND (firstIFrameTs > 0)) AS _in1000ms, 
    sumIf(1, (appId = 60) AND (platform IN (0, 1)) AND (firstIFrameTs > 0)) AS total_secondout
FROM default.table_all 
GROUP BY rtime
```

**Comment by vdimir** [comment] 2022-03-07 18:36
@taiyang-li 

Thanks for good test case!

I've tested it and seems it issue not with `optimize_rewrite_sum_if_to_count_if` (I've put test here https://github.com/ClickHouse/ClickHouse/pull/35049, let's wait CI), but with different tuple formatting (`tuple(0, 1)` vs `(0, 1)`) because I got error:

```
Code: 10. DB::Exception: Received from 172.16.1.6:9000. DB::Exception: Not found column sumIf(multiIf(and(greater(firstIFrameTs, 0), lessOrEquals(firstIFrameTs, 100)), 1, 0), and(equals(appId, 60), in(platform, (0, 1)), greater(firstIFrameTs, 0))) in block. There are only columns: toStartOfMinute(toDateTime(reportTime)), sumIf(multiIf(and(greater(firstIFrameTs, 0), lessOrEquals(firstIFrameTs, 100)), 1, 0), and(equals(appId, 60), in(platform, tuple(0, 1)), greater(firstIFrameTs, 0))), sumIf(1, and(equals(appId, 60), in(platform, tuple(0, 1)), greater(firstIFrameTs, 0))): While executing Remote. Stack trace:
```

And if remove `(platform IN (0, 1))` from query it works as is with master and `21.1.9` in cluster.
Issue with tuples I suppose resolved in https://github.com/ClickHouse/ClickHouse/pull/33938

**Comment by taiyang-li** [comment] 2022-03-08 02:57
@vdimir Sorry, I introduce another issue of tuple in this case.  
But the issue of `optimize_rewrite_sum_if_to_count_if ` can be reproduced in my environment.

Execute query in 20.3 clickhouse:
``` sql
SELECT
    toStartOfMinute(toDateTime(reportTime)) AS rtime,
    sumIf(1, (appId = 60) AND (firstIFrameTs > 0))
FROM default.table
GROUP BY rtime
FORMAT TSVWithNamesAndTypes

Query id: 5490a4b6-8bdf-4c1a-acd9-a3a99773939d

rtime	sumIf(1, and(equals(appId, 60), greater(firstIFrameTs, 0)))
DateTime(\'Asia/Shanghai\')	UInt64
Ok. 
```

Execute same query in 21.10 
``` sql 
:) set optimize_rewrite_sum_if_to_count_if  = 0 ;

SET optimize_rewrite_sum_if_to_count_if = 0

Query id: 8dc6a3cc-3679-4f78-89fd-70ef0a10da3a

Ok.

0 rows in set. Elapsed: 0.048 sec. 

:) SELECT　    toStartOfMinute(toDateTime(reportTime)) AS rtime,　    sumIf(1, (appId = 60) AND (firstIFrameTs > 0))　FROM default.`table`　GROUP BY rtime　FORMAT TSVWithNamesAndTypes 

SELECT
    toStartOfMinute(toDateTime(reportTime)) AS rtime,
    sumIf(1, (appId = 60) AND (firstIFrameTs > 0))
FROM default.table
GROUP BY rtime
FORMAT TSVWithNamesAndTypes

Query id: 12bc288f-7077-4a80-9539-098a181ab698

rtime	sumIf(1, and(equals(appId, 60), greater(firstIFrameTs, 0)))
DateTime	UInt64
Ok.

:) set optimize_rewrite_sum_if_to_count_if  =1 ; 

SET optimize_rewrite_sum_if_to_count_if = 1

Query id: fdb1f1ba-6705-41b9-8139-dd299595d675

Ok.

0 rows in set. Elapsed: 0.001 sec. 

:) SELECT　    toStartOfMinute(toDateTime(reportTime)) AS rtime,　    sumIf(1, (appId = 60) AND (firstIFrameTs > 0))　FROM default.`table`　GROUP BY rtime　FORMAT TSVWithNamesAndTypes 

SELECT
    toStartOfMinute(toDateTime(reportTime)) AS rtime,
    sumIf(1, (appId = 60) AND (firstIFrameTs > 0))
FROM default.table
GROUP BY rtime
FORMAT TSVWithNamesAndTypes

Query id: 3ba532e0-d687-4f48-8606-72df278e34e2

rtime	countIf(and(equals(appId, 60), greater(firstIFrameTs, 0)))
DateTime	UInt64
Ok.

0 rows in set. Elapsed: 0.002 sec. 

```

**Comment by vdimir** [comment] 2022-03-09 16:42
Still can't reproduce, test passed (see PR https://github.com/ClickHouse/ClickHouse/pull/35049/files).
It make distributed query for `master` and `21.1.9` ( feature `optimize_rewrite_sum_if_to_count_if` introduced in  `21.2` https://github.com/ClickHouse/ClickHouse/pull/17041)

**Comment by vdimir** [comment] 2022-03-10 15:08
@taiyang-li 
Could you get binary from https://github.com/ClickHouse/ClickHouse/pull/34962 and check if it works for you and fix problem? https://s3.amazonaws.com/clickhouse-builds/34962/159b655f27e656090641c28d2062a53d6520efc5/clickhouse_build_check_(actions)/report.html

**Comment by taiyang-li** [comment] 2022-03-11 06:18
@vdimir Ok.

**Comment by taiyang-li** [comment] 2022-03-11 07:55
@vdimir  I found out why you can't reproduce. In lastest version of clickhouse, optimize will not be executed on non-initial 
 query, see https://github.com/ClickHouse/ClickHouse/pull/28746/files introduced by @amosbird

**Closed** 2022-03-11 07:59 UTC
Labels: feature, comp-optimizers, st-discussion, comp-distributed

**Comment by lucasenabit** [comment] 2022-06-29 22:41
Hi,

Whats version this problem will be resolved ? I get the same error, but using case when in my query. I'm using 22.6.2.12 version in my environment.

Thanks.

**Comment by taiyang-li** [comment] 2022-06-30 06:38
@lucasenabit `TreeOptimizer::apply` is disabled for secondary query in https://github.com/ClickHouse/ClickHouse/pull/28746/files This pr is contained by your 22.6 version. If you still could reproduce similiar cases, pls give us the reproduce steps?
