### ISSUE TITLE
Data duplication

### ISSUE THREAD

**Issue by alniks** [ClickHouse/ClickHouse#972] opened 2017-07-12 08:43 UTC
We have a Distributed table with two-node cluster with ReplicatedMergeTree tables. Once in 3 secs we make an insert to the Distributed table and see that some of the data are duplicated. Why and how we can avoid this?

ClickHouse server version 1.1.54236

**Comment by ipolevoy** [comment] 2017-07-24 04:10
bump, hey good people from Clickhouse, any advice?

**Comment by ipolevoy** [comment] 2017-08-07 03:27
hello?

**Comment by alex-zaitsev** [comment] 2017-08-07 08:59
Please share your cluster configuration. You seem to have one shard and two replicas. The data has to be replicated, so it looks like your Distributed table is not properly configured and thinks there are two shards.

**Comment by SlyderBY** [comment] 2017-08-07 14:25
This is how our cluster configuration looks:
```
    <remote_servers>
        <test>
            <shard>
                <replica>
                    <host>10.1.1.10</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>10.1.1.11</host>
                    <port>9000</port>
                </replica>
            </shard>
        </test>
    </remote_servers>

```

**Comment by alex-zaitsev** [comment] 2017-08-07 14:57
Please also provide an output of 'show create table' for shard tables and distributed table.

But I guess the problem is that you do not have internal_replication for your shard tables:

   <internal_replication>true</internal_replication>

**Comment by SlyderBY** [comment] 2017-08-07 15:15
'show create table' output for one of the tables:
`CREATE TABLE test.campaign_events ( campaign_id UInt64,  contact_id UInt64,  type UInt8,  email String,  user_id UInt64,  user_agent String,  url String,  latitude Float32,  longitude Float32,  ip String,  created_at DateTime,  event_date Date,  merged_url String) ENGINE = Distributed(test, \'test\', \'campaign_events_local\')`

Added '<internal_replication>true</internal_replication>' to the server configuration, will see if it helps.

**Comment by vas-and-tor** [comment] 2017-08-08 16:28
We have similar problem.

Here is our cluster:

```
SELECT *
FROM system.clusters
WHERE cluster = 'logs'

┌─cluster─┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name───┬─host_address────┬─port─┬─is_local─┬─user────┬─default_database─┐
│ logs    │         1 │            1 │           1 │ clickhouse2 │ 127.0.1.1       │ 9000 │        0 │ default │                  │
│ logs    │         1 │            1 │           2 │ clickhouse9 │ 192.168.231.101 │ 9000 │        0 │ default │                  │
│ logs    │         2 │            1 │           1 │ clickhouse3 │ 192.168.231.107 │ 9000 │        0 │ default │                  │
│ logs    │         2 │            1 │           2 │ clickhouse8 │ 192.168.231.102 │ 9000 │        0 │ default │                  │
│ logs    │         3 │            1 │           1 │ clickhouse4 │ 192.168.231.105 │ 9000 │        0 │ default │                  │
│ logs    │         3 │            1 │           2 │ clickhouse7 │ 192.168.231.106 │ 9000 │        0 │ default │                  │
│ logs    │         4 │            1 │           1 │ clickhouse5 │ 192.168.231.6   │ 9000 │        0 │ default │                  │
│ logs    │         4 │            1 │           2 │ clickhouse6 │ 192.168.231.104 │ 9000 │        0 │ default │                  │
└─────────┴───────────┴──────────────┴─────────────┴─────────────┴─────────────────┴──────┴──────────┴─────────┴──────────────────┘
```

Our tables:

```
SHOW CREATE TABLE metrika.tmp_api_logs

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE metrika.tmp_api_logs ( Timestamp DateTime,  HttpMethod String,  HostName String,  UriPath String,  UriParams String,  HttpStatus Int32,  RequestTime Float64,  RequestLength Int64,  BytesSent Int64,  UpstreamResponseTime Float64,  PortalUserId String,  TraceId String,  EventDate Date MATERIALIZED toDate(Timestamp)) ENGINE = MergeTree(EventDate, intHash32(Timestamp), (Timestamp, intHash32(Timestamp)), 8192) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

```
SHOW CREATE TABLE metrika_new.api_logs_local

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE metrika_new.api_logs_local ( Timestamp DateTime,  HttpMethod String,  HostName String,  UriPath String,  UriParams String,  HttpStatus Int32,  RequestTime Float64,  RequestLength Int64,  BytesSent Int64,  UpstreamResponseTime Float64,  PortalUserId String,  TraceId String,  EventDate Date MATERIALIZED toDate(Timestamp)) ENGINE = ReplicatedMergeTree(\'/clickhouse/tables/{logsshard}/metrika/api_logs\', \'{replica}\', EventDate, intHash32(Timestamp), (Timestamp, intHash32(Timestamp)), 8192) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

```
SHOW CREATE TABLE metrika_new.api_logs_insert

┌─statement───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE metrika_new.api_logs_insert ( Timestamp DateTime,  HttpMethod String,  HostName String,  UriPath String,  UriParams String,  HttpStatus Int32,  RequestTime Float64,  RequestLength Int64,  BytesSent Int64,  UpstreamResponseTime Float64,  PortalUserId String,  TraceId String) ENGINE = Distributed(logs, \'metrika_new\', \'api_logs_local\', rand()) │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

```
SELECT count()
FROM metrika.tmp_api_logs
WHERE (EventDate > '2017-01-10') AND (EventDate <= '2017-02-10')

┌────count()─┐
│ 1327505338 │
└────────────┘
```

After I did

```
INSERT INTO metrika_new.api_logs_insert SELECT
    Timestamp,
    HttpMethod,
    HostName,
    UriPath,
    UriParams,
    HttpStatus,
    RequestTime,
    RequestLength,
    BytesSent,
    UpstreamResponseTime,
    PortalUserId,
    TraceId
FROM metrika.tmp_api_logs
WHERE (EventDate > '2017-01-10') AND (EventDate <= '2017-02-10')
```

I expect count() from `metrika_new.api_logs_insert` to be `1327505338`, but I have

```
SELECT count()
FROM metrika_new.api_logs_insert

┌────count()─┐
│ 1709437703 │
└────────────┘
```

```
$ for i in `seq 2 9`; do echo -n "clickhouse$i: " && curl clickhouse$i:8123 -d "select count() from metrika_new.api_logs_local" ; done
clickhouse2: 431643023
clickhouse3: 426589622
clickhouse4: 427823619
clickhouse5: 423381439
clickhouse6: 423381439
clickhouse7: 427823619
clickhouse8: 426589622
clickhouse9: 431643023
```

We have version 1.1.54245

**Comment by vas-and-tor** [comment] 2017-08-10 06:47
I reproduced this problem even with direct inserts to a shard, like this:

```
INSERT INTO metrika_new.api_logs_local SELECT
    Timestamp,
    HttpMethod,
    HostName,
    UriPath,
    UriParams,
    HttpStatus,
    RequestTime,
    RequestLength,
    BytesSent,
    UpstreamResponseTime,
    PortalUserId,
    TraceId
FROM remote('clickhouse2', metrika.tmp_api_logs)
WHERE (cityHash64(*) % 4) = <index of a shard> -- 0, 1, 2 or 3
```

But after I changed `MATERIALIZED` expression for `EventDate` to `DEFAULT` everything seems to be fine. I have same `count()` after insert.

**Comment by alniks** [comment] 2018-08-01 05:09
<internal_replication>true</internal_replication> helped us

**Comment by imvs** [comment] 2019-01-25 08:32
I have duplication to.

Here is configuration

SELECT *
FROM system.clusters
`
┌─cluster─┬─shard_num─┬─shard_weight─┬─replica_num─┬─host_name────────────────────┬─host_address─┬─port─┬─is_local─┬─user────┬─default_database─┐
│ test    │         1 │            1 │           1 │ ch-test02.unix.nspk.ru │ 10.31.25.134 │ 9001 │        0 │ default │                  │
│ test    │         1 │            1 │           2 │ ch-test04.unix.nspk.ru │ 10.31.25.136 │ 9001 │        0 │ default │                  │
│ test    │         2 │            1 │           1 │ ch-test03.unix.nspk.ru │ 10.31.25.135 │ 9001 │        1 │ default │                  │
│ test    │         2 │            1 │           2 │ ch-test05.unix.nspk.ru │ 10.31.25.137 │ 9001 │        1 │ default │                  │
└─────────┴───────────┴──────────────┴─────────────┴──────────────────────────────┴──────────────┴──────┴──────────┴─────────┴──────────────────┘
`
`
   <remote_servers>
    <test>
        <shard>
            
            <weight>1</weight>
            
            <internal_replication>true</internal_replication>
            <replica>
                <host>ch-test02.unix.nspk.ru</host>
                <port>9001</port>
            </replica>
            <replica>
                <host>ch-test04.unix.nspk.ru</host>
                <port>9001</port>
            </replica>
        </shard>
                <shard>
            
            <weight>1</weight>
            
            <internal_replication>true</internal_replication>
            <replica>
                <host>ch-test03.unix.nspk.ru</host>
                <port>9001</port>
            </replica>
            <replica>
                <host>ch-test05.unix.nspk.ru</host>
                <port>9001</port>
            </replica>
        </shard>
    </test>
    </remote_servers>
`


`CREATE TABLE hits ON CLUSTER test
(
    EventDate DateTime,
    CounterID UInt32,
    UserID UInt32
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/hits', '{replica}')
PARTITION BY toYYYYMM(EventDate)
ORDER BY (CounterID, EventDate)
`
`CREATE TABLE hits_all AS hits
    ENGINE = Distributed(test, default, hits, rand());
`
Replacements on each server is:
`
    <macros>
        <shard>01</shard>
        <replica>ch-test02.unix.nspk.ru</replica>
    </macros>
        <macros>
        <shard>02</shard>
        <replica>ch-test03.unix.nspk.ru</replica>
    </macros>
        <macros>
        <shard>01</shard>
        <replica>ch-test04.unix.nspk.ru</replica>
    </macros>
        <macros>
        <shard>02</shard>
        <replica>ch-test05.unix.nspk.ru</replica>
    </macros>
`

Now i execute repeatedly insertion, for example:

`
INSERT INTO hits_all SELECT toDateTime('2019-01-25 23:00:00'),4,1
`

and got duplications:

SELECT *
FROM hits_all

`
┌───────────EventDate─┬─CounterID─┬─UserID─┐
│ 2019-01-25 23:00:00 │         1 │      1 │
│ 2019-01-25 23:00:00 │         2 │      1 │
│ 2019-01-25 23:00:00 │         3 │      1 │
└─────────────────────┴───────────┴────────┘
┌───────────EventDate─┬─CounterID─┬─UserID─┐
│ 2019-01-25 23:00:00 │         4 │      1 │
└─────────────────────┴───────────┴────────┘
┌───────────EventDate─┬─CounterID─┬─UserID─┐
│ 2019-01-25 23:00:00 │         1 │      1 │
│ 2019-01-25 23:00:00 │         3 │      1 │
└─────────────────────┴───────────┴────────┘
┌───────────EventDate─┬─CounterID─┬─UserID─┐
│ 2019-01-25 23:00:00 │         4 │      1 │
└─────────────────────┴───────────┴────────┘
`

**Comment by filimonov** [comment] 2019-10-28 21:46
Closing. @imvs please open new issue if you still need some help with that.

**Closed by filimonov** 2019-10-28 21:46 UTC
Labels: comp-distributed, question

**Comment by lyfzwrthlvng** [comment] 2020-06-22 10:35
@imvs did you open a separate issue? Did you figure out why you were seeing duplicate data? Some days baack we also saw similar issue, unfortunately we restarted and issue was gone, so can't reproduct it since then. Wanted to get better understanding of the issue.

**Comment by PalaceK999** [comment] 2021-09-07 07:32
use  FINAL
