### ISSUE TITLE
_file and _path virtual columns not present in url() and urlCluster() table engines

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#52282] opened 2023-07-18 21:14 UTC
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
`_file` and `_path` virtual columns not present in `url*()` table engines

**How to reproduce**
* Which ClickHouse server version to use

23.6.2 revision 54464

**Expected behavior**

The columns exist

**Error message and/or stacktrace**

```
SELECT
count(), _file
FROM url('https://datasets-documentation.s3.eu-west-3.amazonaws.com/house_parquet/house_{0,1}.parquet')
GROUP BY
_file
LIMIT 10


Code: 8. DB::Exception: Not found field(_file) in arrow schema:price: int64 not null
```

Works fine if you use `s3()` instead

**Additional context**

Based on comment https://github.com/ClickHouse/ClickHouse/discussions/44849#discussioncomment-4575154 s3, file, and url table engines should all have these

**Comment by alexey-milovidov** [comment] 2023-07-18 23:44
The error message is terrible, we missed it in code review: https://github.com/ClickHouse/ClickHouse/pull/52284

**Comment by alexey-milovidov** [comment] 2023-07-18 23:47
Duplicate of #49231

**Closed by alexey-milovidov** 2023-07-18 23:47 UTC
Labels: duplicate, unexpected behaviour
