### ISSUE TITLE
A dictionary with an invalidate query cannot recover after an exception

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#7535] opened 2019-10-29 19:37 UTC
ClickHouse version 19.15.3.6 (official build).
ClickHouse version 19.11.8.46 (official build).

A dictionary with an invalidate query cannot recover after an exception if there are no updates in the source.

**How to reproduce**
Create a table:
```
CREATE TABLE dict_invalidate
ENGINE = Memory AS
SELECT
    dummy,
    toDateTime('2019-10-29 18:51:35') AS last_time
FROM system.one
```
Create a dictionary with an invalidate query that looks at this table:
```
<yandex>
    <dictionary>
        <name>invalidate</name>
        <source>
            <clickhouse>
                <host>localhost</host>
                <port>9000</port>
                <user>default</user>
                <password/>
                <db>default</db>
                <table>dict_invalidate</table>
                <invalidate_query>select max(last_time) from dict_invalidate</invalidate_query>
            </clickhouse>
        </source>
        <lifetime>60</lifetime>
        <layout><flat/></layout>
        <structure>
            <id>
                <name>dummy</name>
            </id>
            <attribute>
                <name>two</name>
                <expression>dummy</expression>
                <type>UInt8</type>
                <null_value>0</null_value>
            </attribute>
        </structure>
    </dictionary>
</yandex>

system reload dictionary invalidate;
```
The dictionary checks for updates every minute:
```
2019.10.29 18:51:46.998773 [ 3 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.10.29 18:51:46.999592 [ 3 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '2019-10-29 18:51:35', previous value: '2019-10-29 18:51:35'

2019.10.29 18:52:47.005796 [ 3 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.10.29 18:52:47.006707 [ 3 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '2019-10-29 18:51:35', previous value: '2019-10-29 18:51:35'
```
Drop the table:
```
drop table dict_invalidate;
```
The invalidate query fails:
```
2019.10.29 18:53:47.012529 [ 3 ] {} <Debug> executeQuery: (internal) select max(last_time) from dict_invalidate
2019.10.29 18:53:47.012779 [ 3 ] {} <Error> ExternalDictionaries: Could not check if external dictionary 'invalidate' was modified: Code: 60, e.displayText() = DB::Exception: Table default.dict_invalidate doesn't exist., Stack trace:
```
CH tries to update the dictionary and this attempt also fails:
```
2019.10.29 18:53:47.013660 [ 65 ] {} <Debug> executeQuery: (internal) SELECT `dummy`, (dummy) AS `two` FROM `default`.`dict_invalidate`;
2019.10.29 18:53:47.013940 [ 65 ] {} <Error> ExternalDictionaries: Could not update external dictionary 'invalidate', leaving the previous version, next update is scheduled at 2019-10-29 18:53:52: Code: 60, e.displayText() = DB::Exception: Table default.dict_invalidate doesn't exist., Stack trace:
```
Create the table back:
```
create table dict_invalidate engine=Memory as select dummy, toDateTime('2019-10-29 18:51:35') as last_time from system.one
```
The invalidate query now works fine:
```
2019.10.29 18:54:07.015614 [ 3 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.10.29 18:54:07.016474 [ 3 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '2019-10-29 18:51:35', previous value: '2019-10-29 18:51:35'
```
The dictionary does not require an update so not updated, and the exception is still there in system.dictionaries:
```
2019.10.29 19:01:53.830349 [ 79 ] {f0737276-855b-4afd-8d70-7c02891205c7} <Debug> executeQuery: (from [::1]:48844) SELECT status, loading_start_time, last_exception FROM system.dictionaries WHERE name = 'invalidate' FORMAT Vertical

SELECT
    status,
    loading_start_time,
    last_exception
FROM system.dictionaries
WHERE name = 'invalidate'
FORMAT Vertical

Row 1:
──────
status:             LOADED
loading_start_time: 2019-10-29 18:53:57
last_exception:     Code: 60, e.displayText() = DB::Exception: Table default.dict_invalidate doesn't exist. (version 19.15.3.6 (official build))
```
Now the dictionary checks for updates every 10 seconds:
```
2019.10.29 19:06:07.158829 [ 3 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.10.29 19:06:07.159686 [ 3 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '2019-10-29 18:51:35', previous value: '2019-10-29 18:51:35'

2019.10.29 19:06:17.160730 [ 3 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.10.29 19:06:17.161554 [ 3 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '2019-10-29 18:51:35', previous value: '2019-10-29 18:51:35'

2019.10.29 19:06:27.162692 [ 3 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.10.29 19:06:27.163663 [ 3 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '2019-10-29 18:51:35', previous value: '2019-10-29 18:51:35'
```
Queries to the dictionary work fine because the previous version was preserved.
The problem is that the dictionary gets updated every 10 seconds, and there is an exception in system.dictionaries.

**Comment by alesapin** [comment] 2019-12-02 13:33
Cannot reproduce:
```
CREATE TABLE default.dict_invalidate                                                                                                                                                                                                            
(                                                                                                                                                                                                                                               
    `dummy` UInt8,                                                                                                                                                                                                                              
    `last_time` DateTime                                                                                                                                                                                                                        
)                                                                                                                                                                                                                                               
ENGINE = MergeTree()                                                                                                                                                                                                                            
ORDER BY dummy;


CREATE DICTIONARY default.invalidate
(
    `dummy` UInt64,
    `two` UInt8 EXPRESSION dummy
)
PRIMARY KEY dummy
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 USER 'default' TABLE 'dict_invalidate' DB 'default' INVALIDATE_QUERY 'select max(last_time) from dict_invalidate'))
LIFETIME(MIN 0 MAX 60)
LAYOUT(FLAT());

INSERT INTO default.dict_invalidate VALUES(3, now());                                                                                                                                    

SELECT dictGetUInt8('default.invalidate', 'two', toUInt64(3));

┌─dictGetUInt8('default.invalidate', 'two', toUInt64(3))─┐
│                                                      3 │
└────────────────────────────────────────────────────────┘

DROP TABLE dict_invalidate;

SELECT * FROM system.dictionaries\G;

Row 1:
──────
database:           default
name:               invalidate
status:             LOADED
origin:             default.invalidate
type:               Flat
key:                UInt64
attribute.names:    ['two']
attribute.types:    ['UInt8']
bytes_allocated:    2168
query_count:        0
hit_rate:           1
element_count:      1
load_factor:        0.0004957858205255329
source:             ClickHouse: default.dict_invalidate
loading_start_time: 2019-12-02 16:27:34
loading_duration:   0
last_exception:     Code: 60, e.displayText() = DB::Exception: Table default.dict_invalidate doesn't exist. (version 19.15.1.1)

CREATE TABLE default.dict_invalidate
(
    `dummy` UInt8, 
    `last_time` DateTime
)
ENGINE = MergeTree()
ORDER BY dummy

... wait some time

select * from system.dictionaries\G

Row 1:
──────
database:           default
name:               invalidate
status:             LOADED
origin:             default.invalidate
type:               Flat
key:                UInt64
attribute.names:    ['two']
attribute.types:    ['UInt8']
bytes_allocated:    2168
query_count:        0
hit_rate:           1
element_count:      0
load_factor:        0
source:             ClickHouse: default.dict_invalidate
loading_start_time: 2019-12-02 16:28:19
loading_duration:   0
last_exception:
```
In logs:
```
2019.12.02 16:26:24.514521 [ 52 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '2019-12-02 16:22:05', previous value: '2019-12-02 16:22:05'
2019.12.02 16:26:54.517537 [ 52 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
...
...
...
2019.12.02 16:27:44.565165 [ 52 ] {} <Error> ExternalDictionariesLoader: Could not check if external dictionary 'default.invalidate' was modified: Code: 60, e.displayText() = DB::Exception: Table default.dict_invalidate doesn't exist.
....
2019.12.02 16:29:59.580874 [ 52 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.12.02 16:30:24.583840 [ 52 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '0000-00-00 00:00:00', previous value: '0000-00-00 00:00:00'
...
2019.12.02 16:30:34.584594 [ 52 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.12.02 16:30:34.585180 [ 52 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '0000-00-00 00:00:00', previous value: '0000-00-00 00:00:00'
2019.12.02 16:31:29.589302 [ 52 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.12.02 16:31:29.589974 [ 52 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '0000-00-00 00:00:00', previous value: '0000-00-00 00:00:00'
2019.12.02 16:32:19.594438 [ 52 ] {} <Trace> ClickHouseDictionarySource: Performing invalidate query
2019.12.02 16:32:19.595017 [ 52 ] {} <Trace> ClickHouseDictionarySource: Invalidate query has returned: '0000-00-00 00:00:00', previous value: '0000-00-00 00:00:00'
```
Looks OK to me. Maybe something fixed in 19.17?
Also I've found another bug near this code https://github.com/ClickHouse/ClickHouse/pull/7983.

**Comment by SaltTan** [comment] 2019-12-03 01:00
I observe the same behaviour in 19.16.6.17 and 19.17.4.11.
I think your test is incorrect.
When you create the source table for the second time it is empty, so the invalidate query returns a different value (in your test '0000-00-00 00:00:00' instead of '2019-12-02 16:22:05') and the dictionary gets reloaded (at 2019-12-02 16:28:19 in your test).
My issue is that the invalidate query returns the same value as before, the dictionary does not get reloaded and the exception stays.

**Comment by alesapin** [comment] 2019-12-04 14:03
Tried to reproduce with test https://github.com/ClickHouse/ClickHouse/pull/8029/files. I think I'm doing something wrong :(

**Comment by alesapin** [comment] 2019-12-04 14:49
Fix https://github.com/ClickHouse/ClickHouse/pull/8029/files

**Closed** 2019-12-15 21:43 UTC
Labels: bug, comp-dictionary, st-accepted
