### ISSUE TITLE
Batch insert of Nullable columns very very slow

### ISSUE THREAD

**Issue by akamensky** [ClickHouse/ClickHouse#28219] opened 2021-08-27 06:16 UTC
**Describe the situation**
We are running real-time data ingest using KafkaConnect (not CH native Kafka source for data structure reasons). Developers added new column to the schema, which in CH translates as `Nullable(Int64)`. This has reduced the ingest performance by 100-fold (hard to even estimate exact number). The data rates in Kafka are about 80k messages per second. Data format is ~10 columns, one `String` (say str_col), one `DateTime64(3)` (say ts_col), the rest are number based (Int64, Float64 etc). Table is MergeTree partitioned by hour of `ts_col` and ordered by `(str_col, ts_col)`.

**How to reproduce**
* Server is: data partition - mdadm raid10 of 8TB SSDs (not saturated), memory - 128 GB RAM, cpu - Intel Xeon D-1581
* `ClickHouse server version 21.5.5 revision 54448`
* KafkaConnect for data ingest using https://github.com/housepower/ClickHouse-Native-JDBC
* Table with good performance looks like:
```
CREATE TABLE tbl
(
    str_col String,
    ts_col DateTime64(3),
    col1 Int64,
    col2 Int64 DEFAULT 0,
    col3 Float64,
    col4 Float64,
    col5 Int64,
    col6 String,
    col7 Int64,
    col8 Float64
)
ENGINE = MergeTree
PARTITION BY toStartOfHour(ts_col)
ORDER BY (str_col, ts_col)
TTL toDateTime(ts_col) + toIntervalDay(2)
```
* Table with absolutely horrible performance looks like:
```
CREATE TABLE tbl
(
    str_col String,
    ts_col DateTime64(3),
    col1 Int64,
    col2 Int64 DEFAULT 0,
    col3 Float64,
    col4 Float64,
    col5 Int64,
    col6 String,
    col7 Int64,
    col8 Float64,
    col9 Nullable(Int64)
)
ENGINE = MergeTree
PARTITION BY toStartOfHour(ts_col)
ORDER BY (str_col, ts_col)
TTL toDateTime(ts_col) + toIntervalDay(2)
```

**Expected performance**
Batch insert time is the time that KC spent inserting single batch into Clickhouse.

With 80k messages per second (total across 20 partitions in kafka) and 20 tasks in KafkaConnect the batch insert time (from KC metrics) is 20ms average and 700 ms worst.

**Actual performance**
After the `Nullable` column added the batch insert time is 1.2 **minutes** average and 1.5 **minutes** worst.

**Additional context**
We are running ingest into Postgres in parallel with ingest to Clickhouse, adding new column had no effect on ingest throughput in Postgres.

**Comment by akamensky** [comment] 2021-08-30 01:43
I've ran the same test as you did above, but with 10mln records (1mln inserts too fast to see any difference). Also note there are significant differences in this test with out setup:

1. KC inserts in batches of 50k in 20 parallel processes. So at any given moment there may be 20 simultaneous batch inserts running.
2. This test does not account for potential NULL values in Nullable column (all values will be numbers in there)

```
production :) CREATE TABLE tbl (    str_col String,    ts_col DateTime64(3),    col1 Int64,    col2 Int64 DEFAULT 0,    col3 Float64,    col4 Float64,    col5 Int64,    col6 String,    col7 Int64,    col8 Float64) ENGINE = MergeTree PARTITION BY toStartOfHour(ts_col) ORDER BY (str_col, ts_col) TTL toDateTime(ts_col) + toIntervalDay(2)

CREATE TABLE tbl
(
    `str_col` String,
    `ts_col` DateTime64(3),
    `col1` Int64,
    `col2` Int64 DEFAULT 0,
    `col3` Float64,
    `col4` Float64,
    `col5` Int64,
    `col6` String,
    `col7` Int64,
    `col8` Float64
)
ENGINE = MergeTree
PARTITION BY toStartOfHour(ts_col)
ORDER BY (str_col, ts_col)
TTL toDateTime(ts_col) + toIntervalDay(2)

Query id: 0bb9c184-29b2-4658-9ca7-2474011e782c

Ok.

0 rows in set. Elapsed: 0.377 sec. 

production :) CREATE TABLE tbl1 (    str_col String,    ts_col DateTime64(3),    col1 Int64,    col2 Int64 DEFAULT 0,    col3 Float64,    col4 Float64,    col5 Int64,    col6 String,    col7 Int64,    col8 Float64,    col9 Nullable(Int64)) ENGINE = MergeTree PARTITION BY toStartOfHour(ts_col) ORDER BY (str_col, ts_col) TTL toDateTime(ts_col) + toIntervalDay(2);

CREATE TABLE tbl1
(
    `str_col` String,
    `ts_col` DateTime64(3),
    `col1` Int64,
    `col2` Int64 DEFAULT 0,
    `col3` Float64,
    `col4` Float64,
    `col5` Int64,
    `col6` String,
    `col7` Int64,
    `col8` Float64,
    `col9` Nullable(Int64)
)
ENGINE = MergeTree
PARTITION BY toStartOfHour(ts_col)
ORDER BY (str_col, ts_col)
TTL toDateTime(ts_col) + toIntervalDay(2)

Query id: fcc18654-7d6c-47d0-94f5-e2158892d9fb

Ok.

0 rows in set. Elapsed: 0.190 sec. 

production :) Bye.
[root@host ~]# clickhouse-client -q 'select toString(number) str_col, now64() ts_col, toInt64(number) col1, toInt64(number%111) col2, number/111 col3, number/1111 col4, toInt64(number%1003) col5, toString(cityHash64(number)) col6, toInt64(1) col7, toFloat64(0) col8 from numbers(10000000) format Native' > test1.native
[root@host ~]# clickhouse-client -q 'select toString(number) str_col, now64() ts_col, toInt64(number) col1, toInt64(number%111) col2, number/111 col3, number/1111 col4, toInt64(number%1003) col5, toString(cityHash64(number)) col6, toInt64(1) col7, toFloat64(0) col8, cast(number%545654 as Nullable(Int64)) col9 from numbers(10000000) format Native' > test2.native
[root@host ~]# clickhouse-client -t -q 'insert into tbl format Native' < test1.native
6.152
[root@host ~]# clickhouse-client -t -q 'insert into tbl1 format Native' < test2.native
7.557
[root@host ~]#
```

**Comment by den-crane** [comment] 2021-08-30 03:58
I don't understand 10 millions rows and 6.152 vs 7.557 ?

In the original message you were stating about  "80k messages per second" and "1.2 minutes average". Now about 10 mil and 7.557 seconds???? The issue is not in the server until you provide the provable example.

**Comment by den-crane** [comment] 2021-08-30 04:19
```
21.9.1.7603.

| => clickhouse-client -t -q 'insert into tbl1 format Native' < test2.native
2.788

| => clickhouse-client -t -q 'insert into tbl format Native' < test1.native
2.658

```

**Comment by akamensky** [comment] 2021-08-30 04:21
I just added the comparison that I was asked for. I also outlined the difference between this test and actual setup.

Yes 6s vs 7.5s doesn't show significant differences between those 2 tests. And it is entirely possible that the driver is doing something dodgy when encounter Nullable columns.

I've also ran the same test where all values for Nullable column were set to NULL. Which did not show any difference really.

One important point I noticed going through our monitoring metrics that during us having this issue Clickhouse CPU usage was way higher than normally. (Basically saturating CPU).

Is there any way to see where this CPU usage coming from (short of generating gdb bts)?

I will dig more into this issue before any real conclusion can be reached.

**Comment by den-crane** [comment] 2021-08-30 04:26
Nullable types are slower and this is expected. Nullable is stored in additional column / file and can be up to 2 times slower https://gist.github.com/den-crane/e43f8d0ad6f67ab9ffd09ea3e63d98aa . And this is expected ( reasonable cause ) 

But in your case the issue probably is not in CH server.

**Comment by den-crane** [comment] 2021-09-11 22:10
no repro. Closing.

**Closed by den-crane** 2021-09-11 22:10 UTC
Labels: st-need-repro
