### ISSUE TITLE
404 While Trying to Read from DeltaLake with multipart checkpoint files

### ISSUE THREAD

**Issue by cmcclure-twilio** [ClickHouse/ClickHouse#71268] opened 2024-10-30 15:42 UTC
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

Twilio

**Describe what's wrong**

We have a few very large delta lake tables, in the PB range, that are generated via databricks.  We're getting 404 errors from S3 when trying to use Delta Lake engine on a delta lake with multipart checkpoint files.  ClickHouse clearly expects a single checkpoint file, from trace logs:
2024.10.29 20:53:45.920655 [ 68 ] {e75d762e-4eb0-4989-baaa-cdcfcd402e99} <Trace> DeltaLakeMetadataParser: Using checkpoint file: warehouse/path/to_data/_delta_log/00000000000001156035.checkpoint.parquet
2024.10.29 20:53:45.931481 [ 68 ] {e75d762e-4eb0-4989-baaa-cdcfcd402e99} <Information> AWSClient: Response status: 404, Not Found
2024.10.29 20:53:45.931526 [ 68 ] {e75d762e-4eb0-4989-baaa-cdcfcd402e99} <Information> AWSClient: AWSXmlClient: HTTP response code: 404

Our actual checkpoint data:
2024-10-29 13:52:13    2294993 00000000000001156035.checkpoint.0000000001.0000000280.parquet
2024-10-29 13:52:13    2162415 00000000000001156035.checkpoint.0000000002.0000000280.parquet
...
2024-10-29 13:52:15   26283602 00000000000001156035.checkpoint.0000000279.0000000280.parquet
2024-10-29 13:52:14   17802888 00000000000001156035.checkpoint.0000000280.0000000280.parquet

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on the most recent release?**

Yes, Using ClickHouse server version 24.8.4

**How to reproduce**

ClickHouse server version 24.8.4
Connected via CLI.
With a delta lake table in S3 with a multipart checkpoint file.
Run a query like:

SELECT count()
FROM deltaLake('https://my-bucket.s3.my-region.amazonaws.com/path/to/data/')
WHERE (id = 'REDACTED') AND (month = '2024-10-01')

**Expected behavior**

Return a count from the delta lake data

**Error message and/or stacktrace**

404 File not found.

**Comment by melvynator** [comment] 2024-11-05 01:51
Seems like a duplicate of https://github.com/ClickHouse/ClickHouse/issues/69303 

There is also a potential workaround listed.

**Closed by melvynator** 2024-11-05 01:51 UTC
Labels: potential bug
