### ISSUE TITLE
Why INNER JOIN ON raise error message?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#54296] opened 2023-09-05 09:32 UTC
I refer to [this](https://clickhouse.com/docs/en/sql-reference/statements/select/join).
I use sql below,

```sql
WITH
    left_table AS (
      SELECT
          `bucket`
      FROM log_local
    ),
    right_table AS (
       SELECT
           `user`,
           `bucket`
       FROM standalone_user_bucket
   )
SELECT
    *
FROM
    left_table
    INNER JOIN
    right_table
    ON left_table.bucket = right_table.bucket
    -- USING (bucket)
```

and it return result successfully,

```text
Row 1:
──────
bucket:             clickhouse-bucket-1
user:               clickhouse-user
right_table.bucket: clickhouse-bucket-1

Row 2:
──────
bucket:             clickhouse-bucket-2
user:               clickhouse-user
right_table.bucket: clickhouse-bucket-2

Row 3:
──────
bucket:             clickhouse-bucket-1
user:               clickhouse-user
right_table.bucket: clickhouse-bucket-1

Row 4:
──────
bucket:             clickhouse-bucket-1
user:               clickhouse-user
right_table.bucket: clickhouse-bucket-1

Row 5:
──────
bucket:             clickhouse-bucket-1
user:               clickhouse-user
right_table.bucket: clickhouse-bucket-1
```

And it raise error message in system.errors table,

```text
SELECT *
FROM system.errors
WHERE name = 'UNKNOWN_IDENTIFIER'

Query id: cc8410fc-f408-4f69-8096-13fdf2e332f9

Row 1:
──────
name:               UNKNOWN_IDENTIFIER
code:               47
value:              63
last_error_time:    2023-09-05 17:11:15
last_error_message: Missing columns: 'right_table.bucket' 'bucket' while processing query: 'bucket = right_table.bucket', required columns: 'bucket' 'right_table.bucket' 'bucket' 'right_table.bucket'
last_error_trace:   [244448311,150697841,339245337,339280791,339779102,339259820,335862226,335829850,336541222,336532019,335531390,339912906,339896270,354912964,355006585,405356852,405361489,406971751,406962076,140572833588745,140572832690483]
remote:             0

1 row in set. Elapsed: 0.001 sec.
```

error message is:

```text
WITH arrayMap(x -> demangle(addressToSymbol(x)), last_error_trace) AS `all`
SELECT
    name,
    arrayStringConcat(`all`, '\n') AS res
FROM system.errors
WHERE name = 'UNKNOWN_IDENTIFIER'
LIMIT 1
SETTINGS allow_introspection_functions = 1

Query id: e36552a2-98c3-4427-97f0-fe50852d2ed3

Row 1:
──────
name: UNKNOWN_IDENTIFIER
res:  DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool)

DB::TreeRewriterResult::collectUsedColumns(std::__1::shared_ptr<DB::IAST> const&, bool, bool)
DB::TreeRewriter::analyze(std::__1::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::IStorage const>, std::__1::shared_ptr<DB::StorageSnapshot> const&, bool, bool, bool, bool) const
DB::evaluateConstantExpression(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&)
DB::TreeRewriter::analyzeSelect(std::__1::shared_ptr<DB::IAST>&, DB::TreeRewriterResult&&, DB::SelectQueryOptions const&, std::__1::vector<DB::TableWithColumnNamesAndTypes, std::__1::allocator<DB::TableWithColumnNamesAndTypes>> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::TableJoin>, bool, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>) const

DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>)
DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)
DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&)
DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&)

DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum)
DB::TCPHandler::runImpl()
DB::TCPHandler::run()
Poco::Net::TCPServerConnection::start()
Poco::Net::TCPServerDispatcher::run()
Poco::PooledThread::run()
Poco::ThreadImpl::runnableEntry(void*)

__clone

1 row in set. Elapsed: 0.077 sec.
```

But when I uncomment the `USING (bucket)` block, sql is:

```sql
WITH
    left_table AS (
      SELECT
          `bucket`
      FROM log_local
    ),
    right_table AS (
       SELECT
           `user`,
           `bucket`
       FROM standalone_user_bucket
   )
SELECT
    *
FROM
    left_table
    INNER JOIN
    right_table
    -- ON left_table.bucket = right_table.bucket
    USING (bucket)
```

It return result successful and raise no error message:

```text
Row 1:
──────
bucket: clickhouse-bucket-2
user:   clickhouse-user

Row 2:
──────
bucket: clickhouse-bucket-2
user:   clickhouse-user

Row 3:
──────
bucket: clickhouse-bucket-2
user:   clickhouse-user

Row 4:
──────
bucket: clickhouse-bucket-1
user:   clickhouse-user

Row 5:
──────
bucket: clickhouse-bucket-1
user:   clickhouse-user
```

May I ask why there is a difference between the two type? Will the first method affect the final result in cases of large data volume or other situations?

Thank you very much!

**Comment by tavplubix** [comment] 2023-09-05 11:15
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/51487

**Closed by tavplubix** 2023-09-05 11:15 UTC
Labels: question
