### ISSUE TITLE
alter table update column with data from json object results in exceptions and continuously high cpu usage

### ISSUE THREAD

**Issue by plewam** [ClickHouse/ClickHouse#54207] opened 2023-09-02 13:49 UTC
**Describe the unexpected behaviour**
I added a new column called "ID" to my table called dataagententitywcsevent. The table contains a json column called "PAYLOAD". Each "PAYLOAD" entry has a json property called "ID" as well. With an alter table update statement I wanted to move the "ID" value to the new outer column.

This was my statement:

alter table dataagententitywcsevent update id = payload.ID

I am now ended up with continuous exceptions (see below) and 100% CPU usage. The error even persists after server restart.

**Expected behavior**
Ideally the PAYLOAD.ID value would have been set to the newly added ID column.

**Error message and/or stacktrace**
```
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c604e57 in /usr/bin/clickhouse
1. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000748ef2d in /usr/bin/clickhouse
2. DB::injectRequiredColumns(DB::IMergeTreeDataPartInfoForReader const&, std::shared_ptr<DB::StorageSnapshot> const&, bool, std::vector<String, std::allocator<String>>&) @ 0x0000000012d75499 in /usr/bin/clickhouse
3. DB::MergeTreeSequentialSource::MergeTreeSequentialSource(DB::MergeTreeData const&, std::shared_ptr<DB::StorageSnapshot> const&, std::shared_ptr<DB::IMergeTreeDataPart const>, std::vector<String, std::allocator<String>>, std::optional<DB::MarkRanges>, bool, bool, bool, bool) @ 0x0000000012d6fff8 in /usr/bin/clickhouse
4. DB::ReadFromPart::initializePipeline(DB::QueryPipelineBuilder&, DB::BuildQueryPipelineSettings const&) @ 0x0000000012d73b54 in /usr/bin/clickhouse
5. DB::ISourceStep::updatePipeline(std::vector<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>, std::allocator<std::unique_ptr<DB::QueryPipelineBuilder, std::default_delete<DB::QueryPipelineBuilder>>>>, DB::BuildQueryPipelineSettings const&) @ 0x000000001353f0ac in /usr/bin/clickhouse
6. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&, DB::BuildQueryPipelineSettings const&) @ 0x0000000013556e2a in /usr/bin/clickhouse
7. DB::MutationsInterpreter::addStreamsForLaterStages(std::vector<DB::MutationsInterpreter::Stage, std::allocator<DB::MutationsInterpreter::Stage>> const&, DB::QueryPlan&) const @ 0x0000000011fd6d93 in /usr/bin/clickhouse
8. DB::MutationsInterpreter::execute() @ 0x0000000011fdafae in /usr/bin/clickhouse
9. DB::MutateTask::prepare() @ 0x0000000012e0084e in /usr/bin/clickhouse
10. DB::MutateTask::execute() @ 0x0000000012dfc7da in /usr/bin/clickhouse
11. DB::MutatePlainMergeTreeTask::executeStep() @ 0x0000000012f4f4b7 in /usr/bin/clickhouse
12. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000012ba3059 in /usr/bin/clickhouse
13. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c6e357e in /usr/bin/clickhouse
14. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c6e703c in /usr/bin/clickhouse
15. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c6e5884 in /usr/bin/clickhouse
16. ? @ 0x00007ff1f0513b43 in ?
17. ? @ 0x00007ff1f05a5a00 in ?
 (version 23.8.1.2992 (official build))
2023.09.02 15:33:10.879471 [ 64988 ] {9d4acdf6-67d2-46e4-8eb8-33eb65e8ec9e::all_1149928_1150201_28_1150384} <Error> MutatePlainMergeTreeTask: Code: 16. DB::Exception: There is no physical column or subcolumn payload.ID in table. (NO_SUCH_COLUMN_IN_TABLE) (version 23.8.1.2992 (official build))
2023.09.02 15:33:10.879487 [ 64999 ] {9d4acdf6-67d2-46e4-8eb8-33eb65e8ec9e::all_1150202_1150330_27_1150384} <Error> virtual bool DB::MutatePlainMergeTreeTask::executeStep(): Code: 16. DB::Exception: There is no physical column or subcolumn payload.ID in table. (NO_SUCH_COLUMN_IN_TABLE), Stack trace (when copying this message, always include the lines below):
```

Any help would be highly appreciated. Is there a way to stop this task/ query?

**Comment by den-crane** [comment] 2023-09-02 14:03
duplicate of https://github.com/ClickHouse/ClickHouse/issues/49307 https://github.com/ClickHouse/ClickHouse/issues/38517

**Comment by plewam** [comment] 2023-09-02 14:17
Thanks @den-crane. I solved the issue for me renaming the table temporarily. This seems to have killed the process...

**Comment by den-crane** [comment] 2023-09-02 19:36
you can use kill mutation

**Closed by den-crane** 2023-09-02 19:36 UTC
Labels: experimental issue
