### ISSUE TITLE
"interval" keyword behaviour differs for local and remote tables

### ISSUE THREAD

**Issue by senior-sigan** [ClickHouse/ClickHouse#1967] opened 2018-02-26 11:38 UTC
Hello.
I faced with a strange behaviour when querying a distributed table.

This query
```
SELECT count() / interval as rps, max(time) - toDateTime(toStartOfMonth(min(time)))  as interval  FROM distributed.logs  WHERE userID = 'SOME_ID' AND  eventDate >= (today() - 30)
```
fails with this exception:
```
Progress: 3.56 million rows, 172.90 MB (33.22 million rows/s., 1.61 GB/s.)  1%Received exception from server (version 1.1.54343):
Code: 62. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from some_ip:9000. DB::Exception: Syntax error: failed at position 106: default.decisions  WHERE (userID = 'SOME_ID') AND (eventDate >= (today() - 30)). Expected one of: alias, AS, token, AND, OR, BETWEEN, SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, YEAR, IS, LIKE, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, Dot, Arrow, QuestionMark.
```
---

**But** this query doesn't fail:
```
SELECT max(time) - toDateTime(toStartOfMonth(min(time)))  as interval, count() / interval as rps  FROM distributed.decisions  WHERE userID = 'SOME_ID' AND  eventDate >= (today() - 30)
```

What's the difference: I changed the order of the elements in the select statement: from `rps`, `interval` to `interval`, `rps`.
And the weirdest part of this issue is that both of these queries works like a charm for the local non-distributed table on all servers of our cluster separately.

Do you know whether it's a bug or predictable behaviour but I just don't know something?

Configuration: 4 servers: 2 shards with 2 replicas inside each.
clickhouse-server version: `1.1.54343`

Anyway, thanks for this awesome product.

**Comment by KochetovNicolai** [comment] 2018-02-26 14:09
Reproduced.

```SQL
SELECT 1 / interval as a, 1 as interval  FROM system.one
┌─a─┬─interval─┐
│ 1 │        1 │
└───┴──────────┘
```

```SQL
SELECT 1 / interval as a, 1 as interval  FROM remote('localhost', system.one)

Received exception from server (version 1.1.54355):
Code: 62. DB::Exception: Received from localhost:9004, ::1. DB::Exception: Received from localhost:9004, ::1. DB::Exception: Syntax error: failed at position 48: system.one . Expected one of: AND, OR, token, alias, AS, IS, BETWEEN, SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, YEAR, LIKE, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, Dot, Arrow, QuestionMark.
```

However, `interval` is the SQL keyword: you can queries like `select today() + interval '10' day`. When I change the `interval` to something else the problem eliminates.

**Comment by blan4** [comment] 2018-02-26 15:25
@KochetovNicolai Thanks for your answer. I got the point that I shouldn't have used the keyword `interval`. I suppose you are definitely right - keyword is the problem - because I didn't catch other exceptions. 
Meanwhile, I think it would be better to either forbid using keywords or to make the behaviour similar in the distributed and local engines.
The issue could be closed.
Thanks.

**Comment by alexey-milovidov** [comment] 2020-04-16 21:07
Fixed in https://github.com/ClickHouse/ClickHouse/pull/9142

**Closed by alexey-milovidov** 2020-04-16 21:07 UTC
Labels: bug
