### ISSUE TITLE
union_default_mode  does not take effect

### ISSUE THREAD

**Issue by jjtjiang** [ClickHouse/ClickHouse#19692] opened 2021-01-27 08:45 UTC
```
75f806f486c5 :) SET union_default_mode = 'DISTINCT';

SET union_default_mode = 'DISTINCT'

Query id: ad5778f8-2c14-47c3-b2a8-e449a5eb5e07

Ok.

0 rows in set. Elapsed: 0.003 sec. 

75f806f486c5 :) SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 2;

Syntax error: failed at position 16 ('SELECT'):

SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 2;

Expected ALL

```

**Comment by ucasFL** [comment] 2021-01-27 13:44
Could you please post your environment? I can't reproduce it on my environment.

**Comment by den-crane** [comment] 2021-01-28 15:52
@jjtjiang show the banner:

```
ClickHouse client version 21.2.1.5790 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.2.1 revision 54447.

```
It seems you have outdated ClickHouse client

**Comment by den-crane** [comment] 2021-02-03 18:19
No repro / proof. Closing.

**Closed by den-crane** 2021-02-03 18:19 UTC
Labels: question, st-need-info
