### ISSUE TITLE
Cannot rename a column using a recently dropped column

### ISSUE THREAD

**Issue by YiuRULE** [ClickHouse/ClickHouse#12450] opened 2020-07-13 03:06 UTC
**Describe the bug**

The table should have enough datas and be part of the `MergeTree` family.

If we have a table similar at `CREATE TABLE test (pk UInt32, foo AggregateFunction(groupBitOr, UInt32)) Engine = ReplacingMergeTree() PRIMARY KEY (pk) ORDER BY pk;`

`ALTER TABLE test ADD COLUMN foo_tmp SimpleAggregateFunction(groupBitOr, UInt32) AFTER foo SETTINGS mutations_sync = 2, replication_alter_partitions_sync = 2`

`ALTER TABLE test UPDATE foo_tmp = finalizeAggregation(foo) WHERE 1 SETTINGS mutations_sync = 2, replication_alter_partitions_sync = 2`

-- Wait now than all mutations are executed, with checking if on the table `system.mutations`, all columns `is_done = 1`

`ALTER TABLE test DROP COLUMN foo SETTINGS mutations_sync = 2, replication_alter_partitions_sync = 2`

`ALTER TABLE test RENAME COLUMN foo_tmp TO foo`

After this line, the mutation will be stuck, and we will have an error similar at
`Code: 424, e.displayText() = DB::ErrnoException: Destination file /srv/clickhouse/data/default/test/tmp_mut_20200318_18062_19364_306_171657//foo.bin is already exist and have different inode., errno: 17, strerror: File exists (version 20.4.6.53 (official build))`

Error seem also to be reproducible after a simple `UPDATE` clause, so not sure if I'm doing something wrong with it.

On clickhouse `20.4`

**Comment by alesapin** [comment] 2020-07-13 10:03
Can you provide full logs?

**Comment by YiuRULE** [comment] 2020-07-13 10:19
@alesapin Yep, here the complete stacktrace
```
Jul 13 12:04:35 nightly clickhouse-server[3757]: 2020.07.13 10:04:35.541800 [ 3778 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 424, e.displayText() = DB::ErrnoException: Destination file /srv/clickhouse/data/default/test/tmp_mut_20200318_19365_19365_0_171660//foo.bin is already exist and have different inode., errno: 17, strerror: File exists, Stack trace (when copying this message, always include the lines below):
                                                 
                                                 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10412fe0 in /usr/bin/clickhouse
                                                 1. DB::ErrnoException::ErrnoException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) @ 0x9013cfb in /usr/bin/clickhouse
                                                 2. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x9011ade in /usr/bin/clickhouse
                                                 3. DB::createHardLink(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xcf7a631 in /usr/bin/clickhouse
                                                 4. DB::DiskLocal::createHardLink(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xcf7151b in /usr/bin/clickhouse
                                                 5. DB::MergeTreeDataMergerMutator::mutatePartToTemporaryPart(DB::FutureMergedMutatedPart const&, DB::MutationCommands const&, DB::MergeListEntry&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, DB::TableStructureReadLockHolder&) @ 0xd8bf848 in /usr/bin/clickhouse
                                                 6. DB::StorageMergeTree::tryMutatePart() @ 0xd6f0cfd in /usr/bin/clickhouse
                                                 7. ? @ 0xd6f15fb in /usr/bin/clickhouse
                                                 8. DB::BackgroundProcessingPool::threadFunction() @ 0xd832b15 in /usr/bin/clickhouse
                                                 9. ? @ 0xd833442 in /usr/bin/clickhouse
                                                 10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9035267 in /usr/bin/clickhouse
                                                 11. ? @ 0x9033753 in /usr/bin/clickhouse
                                                 12. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
                                                 13. __clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so
                                                  (version 20.4.6.53 (official build))
```

I have sadly only this stacktrace:/

**Comment by alesapin** [comment] 2020-09-18 07:26
Have you seen similar errors on the latest clickhouse versions? I cannot reproduce the issue :(

**Comment by alesapin** [comment] 2020-10-21 13:05
I'll close this issue, if you encounter this error again fill free to reopen.

**Closed by alesapin** 2020-10-21 13:05 UTC
Labels: bug
