### ISSUE TITLE
test_move_and_s3_memory_usage is flaky

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#45954] opened 2023-02-02 10:37 UTC
https://s3.amazonaws.com/clickhouse-test-reports/45889/db2aa48c917dbfc7510515ef0e654472ef14ff4a/integration_tests__release__[2/4].html

```
>       assert int(max_usage) < 3e9
E       AssertionError: assert 3308956336 < 3000000000.0
E        +  where 3308956336 = int('3308956336\n')
```

Other flaks -- [query](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X21vdmVfYW5kX3MzX21lbW9yeV91c2FnZSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==)

**Comment by tavplubix** [comment] 2023-02-02 19:03
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/45887

**Closed by tavplubix** 2023-02-02 19:03 UTC
Labels: flaky test
