### ISSUE TITLE
Analyzer: With statements references not working

### ISSUE THREAD

**Issue by jrdi** [ClickHouse/ClickHouse#48460] opened 2023-04-06 08:27 UTC
When using the analyzer I can't reference a CTE from another one. This works when disabling the analyzer:

Analyzer:
```sql
WITH
    test_aliases AS
    (
        SELECT *
        FROM numbers(20)
    ),
    alias2 AS
    (
        SELECT *
        FROM test_aliases
    )
SELECT *
FROM alias2
FORMAT `Null`
SETTINGS allow_experimental_analyzer = 1

0 rows in set. Elapsed: 0.211 sec.

Received exception from server (version 23.4.1):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Unknown table expression identifier 'test_aliases' in scope alias2. (UNKNOWN_TABLE)
```

No analyzer:
```sql
WITH
    test_aliases AS
    (
        SELECT *
        FROM numbers(20)
    ),
    alias2 AS
    (
        SELECT *
        FROM test_aliases
    )
SELECT *
FROM alias2
FORMAT `Null`
SETTINGS allow_experimental_analyzer = 0

Query id: afa5ddf8-8afd-413f-947d-1da914310b40

Ok.
```

Version:
```sql
┌─version()─┐
│ 23.4.1.1  │
└───────────┘
```

Relevant settings:
```sql
┌─name──────────────────────────────────────────┬─value──────┐
│ max_threads                                   │ 16         │
│ use_uncompressed_cache                        │ 0          │
│ compile_aggregate_expressions                 │ 0          │
│ insert_deduplicate                            │ 1          │
│ http_wait_end_of_query                        │ 1          │
│ http_response_buffer_size                     │ 104857600  │
│ joined_subquery_requires_alias                │ 0          │
│ allow_experimental_analyzer                   │ 1          │
│ max_bytes_before_external_group_by            │ 1442450940 │
│ max_execution_time                            │ 0          │
│ max_expanded_ast_elements                     │ 50000      │
│ max_memory_usage                              │ 5000000000 │
│ memory_usage_overcommit_max_wait_microseconds │ 50000      │
│ log_query_threads                             │ 0          │
│ max_partitions_per_insert_block               │ 100        │
│ enable_lightweight_delete                     │ 0          │
│ optimize_monotonous_functions_in_order_by     │ 0          │
│ enable_global_with_statement                  │ 0          │
│ optimize_rewrite_sum_if_to_count_if           │ 0          │
│ insert_keeper_max_retries                     │ 15         │
│ insert_keeper_retry_initial_backoff_ms        │ 100        │
│ insert_keeper_retry_max_backoff_ms            │ 2000       │
│ input_format_null_as_default                  │ 0          │
└───────────────────────────────────────────────┴────────────┘
```

**Comment by tavplubix** [comment] 2023-04-06 11:09
cc: @kitaisreal, @novikd

**Comment by Algunenano** [comment] 2023-08-01 09:52
Still failing in master

**Comment by kitaisreal** [comment] 2023-08-01 15:24
This is not a bug. If setting `enable_global_with_statement` is disabled, then query does not work because table expression inside subquery cannot be resolved into subquery from outer WITH statement.
Here is test https://github.com/ClickHouse/ClickHouse/pull/52875.

**Comment by kitaisreal** [comment] 2023-08-01 15:52
In old analyzer this setting does not work properly because it was hard to implement it in old infrastructure.
In new analyzer this setting is correctly implemented and allows to refer subqueries and expressions from WITH statement only from current scope.
Why disable of `enable_global_with_statement` setting is necessary for your use case ? It seems that it was added in old analyzer to prevent some bugs, and was set to true by default in https://github.com/ClickHouse/ClickHouse/pull/18684 where bugs were solved.

**Comment by Algunenano** [comment] 2023-08-01 16:06
Because `enable_global_with_statement` is terrible for performance as it duplicated all the CTE inside each subquery. `enable_global_with_statement=0` prevents that

**Comment by kitaisreal** [comment] 2023-08-02 08:44
In analyzer `enable_global_with_statement` will not affect performance at all. I am not sure if this setting is necessary in new infrastructure I need to discuss this.
I suspect that we can safely deprecate it with new analyzer, because it does not even mentioned in documentation.

**Closed** 2023-08-25 16:55 UTC
Labels: experimental issue
