### ISSUE TITLE
Filtering JOIN query throws supertype error (20.3/20.4)

### ISSUE THREAD

**Issue by vanzi** [ClickHouse/ClickHouse#11672] opened 2020-06-15 06:35 UTC
**Describe the bug**

Another issue that showed up after upgrading ClickHouse from **19.6.2.11** to **20.3.10.75**, filtering a JOIN query with more than one expression with a single date value throws an unexpected error.

**How to reproduce**
* Which ClickHouse server version to use

20.3.10.75, confirmed also on 20.4.3.16

* Which interface to use, if matters

native client

* Non-default settings, if any

no

* `CREATE TABLE` statements for all tables involved

```sql
CREATE TABLE foo (server_date Date, server_time Datetime, dimension_1 String) ENGINE = MergeTree() PARTITION BY toYYYYMM(server_date) ORDER BY (server_date);
CREATE TABLE bar (server_date Date, dimension_1 String) ENGINE = MergeTree() PARTITION BY toYYYYMM(server_date) ORDER BY (server_date);
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

```sql
INSERT INTO foo VALUES ('2020-01-01', '2020-01-01 12:00:00', 'test1'), ('2020-01-01', '2020-01-01 13:00:00', 'test2');
INSERT INTO bar VALUES ('2020-01-01', 'test2'), ('2020-01-01', 'test3');
```

* Queries to run that lead to unexpected result

```sql
SELECT count()
FROM foo ANY INNER JOIN bar USING (dimension_1)
WHERE (foo.server_date <= '2020-11-07') AND (toDate(foo.server_time, 'Asia/Yekaterinburg') <= '2020-11-07');
```

**Expected behavior**

Expected result from 19.6.2.11:
```sql
┌─count()─┐
│       1 │
└─────────┘

1 rows in set. Elapsed: 0.007 sec.
```

**Error message and/or stacktrace**

```sql
Received exception from server (version 20.3.10):
Code: 386. DB::Exception: Received from clickhouse:9000. DB::Exception: There is no supertype for types Date, String because some of them are String/FixedString and some of them are not. 

0 rows in set. Elapsed: 0.003 sec.
```

**Additional context**

Removing either one of the two conditions makes the query work. Changing the date to any other in the second condition also makes it work. It also works fine in queries without JOIN.

**Comment by filimonov** [comment] 2020-06-15 15:36
```
set optimize_move_to_prewhere = 0;
```
or rewriting `foo.server_date <= '2020-11-07'` to `foo.server_date <= toDate('2020-11-07')`
solves the issue.

**Comment by vanzi** [comment] 2020-06-16 11:12
@filimonov `toDate` does fix it in this place, but it seems that this issue is more global and occurs in different places that throw random errors, using tables from the first example, this query: 

```sql
SELECT toDateTime(foo.server_time, 'UTC')
FROM foo
ANY INNER JOIN bar USING (dimension_1)
WHERE toDate(foo.server_time, 'UTC') <= toDate('2020-04-30')
```

in 19.6.2.11 returns

```sql
┌─toDateTime(server_time, 'UTC')─┐
│            2020-01-01 13:00:00 │
└────────────────────────────────┘

1 rows in set. Elapsed: 0.006 sec.
```

in 20.3.10.75 it throws

```
Received exception from server (version 20.3.10):
Code: 44. DB::Exception: Received from clickhouse:9000. DB::Exception: Illegal type of argument #0 'timezone' of function toDateTime, expected const String, got String. 

0 rows in set. Elapsed: 0.004 sec.
```

For now it seems that `set optimize_move_to_prewhere = 0` is the safer option to avoid these kind of issues :+1:

**Comment by filimonov** [comment] 2020-06-16 11:51
That is definitely a bug that should be fixed. You can use `set optimize_move_to_prewhere = 0`  temporary as a workaround, but it may have negative impact on the performance.

**Comment by filimonov** [comment] 2020-06-16 12:05
20.1 - affected.
19.17 affected (checked 19.17.2 and 19.17.9, forces enabling any_join_distinct_right_table_keys=1)
19.16 works (after enabling any_join_distinct_right_table_keys=1)

It looks like 19.16 moves another condition to PREWHERE:

```
ANALYZE SELECT count()
FROM foo
ANY INNER JOIN bar USING (dimension_1)
WHERE (foo.server_date <= '2020-11-07') AND (toDate(foo.server_time, 'Asia/Yekaterinburg') <= '2020-11-07')

┌─explain───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ SELECT count()
FROM foo
ANY INNER JOIN 
(
    SELECT *
    FROM bar
) AS bar USING (dimension_1)
PREWHERE toDate(server_time, 'Asia/Yekaterinburg') <= '2020-11-07'
WHERE server_date <= '2020-11-07' │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.005 sec. 
```

**Comment by quba** [comment] 2020-07-27 10:11
Hello everyone. Is there any update regarding this issue? Just curious, since we cannot update CH because of that. Thanks and continue the great work on Clickhouse :)

**Comment by filimonov** [comment] 2020-08-31 18:08
Regression....

**Comment by den-crane** [comment] 2020-10-14 17:57
It works in 20.11.1.4897 with any_join_distinct_right_table_keys=1 and any_join_distinct_right_table_keys=0 and  optimize_move_to_prewhere=1

```sql
SELECT toDateTime(foo.server_time, 'UTC')
FROM foo
ANY INNER JOIN bar USING (dimension_1)
WHERE toDate(foo.server_time, 'UTC') <= toDate('2020-04-30')

Query id: a6441905-ffe2-433f-936f-e6198c9c473e

┌─toDateTime(server_time, 'UTC')─┐
│            2020-01-01 13:00:00 │
└────────────────────────────────┘
```

semi join also works

SELECT toDateTime(foo.server_time, 'UTC') FROM foo 
  semi JOIN bar USING (dimension_1) WHERE toDate(foo.server_time, 'UTC') <= toDate('2020-04-30')

**Comment by alexey-milovidov** [comment] 2020-11-23 08:57
The issue does not reproduce in version 20.12.

**Comment by alexey-milovidov** [comment] 2020-11-23 09:40
20.12 Ok,
20.11 Ok,
20.10 Ok,
20.9 Fail.

**Comment by vanzi** [comment] 2020-11-23 09:42
I tested it on 20.11.4.13 and it looked all good! Thanks!

**Comment by alexey-milovidov** [comment] 2020-11-23 16:45
It's not fixed if table contains wide parts.

**Comment by Slind14** [comment] 2020-12-13 10:34
@alexey-milovidov This bug is keeping us stuck at 19.6, since we can't upgrade directly to 20.11 due to backward incompatibility, and disabling optimize_move_to_prewhere is not doable since it increases the query time of important queries by 5 times.

Is there any chance that a fix can be backported?

**Comment by alexey-milovidov** [comment] 2020-12-13 23:45
@Slind14 There is no fix yet.
When we will have the fix, it will be backported to the latest three versions and 20.8-LTS, 20.3-LTS.

**Comment by filimonov** [comment] 2020-12-18 13:50
Minimal test case fo Illegal type of argument #0 'timezone'

```
DROP TABLE IF EXISTS foo;

CREATE TABLE foo ENGINE = MergeTree() ORDER BY tuple() AS
SELECT toDate('2020-01-01 12:00:00') + number as server_time, number
FROM numbers(2); 

SELECT toDate(foo.server_time, 'UTC') FROM foo
ANY LEFT JOIN (SELECT * FROM numbers(1)) as bar USING (number)
PREWHERE server_time <= toDateTime('2030-04-30 00:00:00', 'UTC');
```

It started somewhere here: https://github.com/ClickHouse/ClickHouse/compare/v19.19.1.1976-testing...v19.19.1.2001-testing

**Comment by Slind14** [comment] 2020-12-19 15:27
@alexey-milovidov @filimonov this issue still occurs in 20.11.5.18

```
2020.12.19 15:26:44.619727 [ 133 ] {4394badb-67ad-4677-8df1-21196d67a16d} <Error> DynamicQueryHandler: Code: 44, e.displayText() = DB::Exception: Illegal type of argument #2 'timezone' of function toDate, expected const String, got String: While processing toDate(timestamp, 'Europe/Berlin') AS _date, Stack trace (when copying this message, always include the lines below):

0. ? @ 0xd1ebe2c in /usr/bin/clickhouse
1. DB::FunctionConvert<DB::DataTypeDate, DB::NameToDate, DB::ToDateMonotonicity>::getReturnTypeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x9274d33 in /usr/bin/clickhouse
2. DB::DefaultOverloadResolver::getReturnType(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x916a4f1 in /usr/bin/clickhouse
3. DB::FunctionOverloadResolverAdaptor::getReturnTypeWithoutLowCardinality(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x9198a46 in /usr/bin/clickhouse
4. DB::FunctionOverloadResolverAdaptor::getReturnType(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x919b105 in /usr/bin/clickhouse
5. DB::FunctionOverloadResolverAdaptor::build(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0x919b5d2 in /usr/bin/clickhouse
6. DB::ActionsDAG::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) @ 0xd8db8fc in /usr/bin/clickhouse
7. DB::ScopeStack::addFunction(std::__1::shared_ptr<DB::IFunctionOverloadResolver> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) @ 0xd97c496 in /usr/bin/clickhouse
8. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0xd980694 in /usr/bin/clickhouse
9. DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) @ 0xd95d4b6 in /usr/bin/clickhouse
10. DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0xd95d28f in /usr/bin/clickhouse
11. DB::SelectQueryExpressionAnalyzer::appendGroupBy(DB::ExpressionActionsChain&, bool, bool, std::__1::vector<std::__1::shared_ptr<DB::ExpressionActions>, std::__1::allocator<std::__1::shared_ptr<DB::ExpressionActions> > >&) @ 0xd9635a4 in /usr/bin/clickhouse
12. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterInfo> const&, DB::Block const&) @ 0xd96935d in /usr/bin/clickhouse
13. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0xd914794 in /usr/bin/clickhouse
14. ? @ 0xd90f675 in /usr/bin/clickhouse
15. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xd90ac4b in /usr/bin/clickhouse
16. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd90966d in /usr/bin/clickhouse
17. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xdaabbf3 in /usr/bin/clickhouse
18. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0xd88ad57 in /usr/bin/clickhouse
19. ? @ 0xdc16335 in /usr/bin/clickhouse
20. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xdc19457 in /usr/bin/clickhouse
21. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xe241b5d in /usr/bin/clickhouse
22. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0xe244db5 in /usr/bin/clickhouse
23. Poco::Net::HTTPServerConnection::run() @ 0x109f31f5 in /usr/bin/clickhouse
24. Poco::Net::TCPServerConnection::start() @ 0x10a2971f in /usr/bin/clickhouse
25. Poco::Net::TCPServerDispatcher::run() @ 0x10a2b131 in /usr/bin/clickhouse
26. Poco::PooledThread::run() @ 0x10b58209 in /usr/bin/clickhouse
27. Poco::ThreadImpl::runnableEntry(void*) @ 0x10b5419a in /usr/bin/clickhouse
28. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
29. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 20.11.5.18 (official build))
```

**Comment by filimonov** [comment] 2020-12-22 13:19
@Slind14 I've extracted the discussion about "Illegal type of argument #0 'timezone" to a separate issue #18367

It seems they are related but it's easier to track them separately.

**Closed** 2021-01-14 12:10 UTC
Labels: bug, comp-joins, prio-major, v20.3-affected, v20.4-affected, v20.5-affected
