### ISSUE TITLE
Part 8_0_30_1 intersects part 8_9_9_1. It is a bug or a result of manual intervention in the ZooKeeper data.

### ISSUE THREAD

**Issue by nickitat** [ClickHouse/ClickHouse#44846] opened 2023-01-02 15:19 UTC
https://s3.amazonaws.com/clickhouse-test-reports/44116/c9c8c5bb76c744a7164ea79a74d397e92fe6567a/stateless_tests__release__wide_parts_enabled_.html

```
1439813:2022.12.21 02:04:45.924735 [ 644 ] {} <Fatal> BaseDaemon: (version 22.13.1.297, build id: E74F2B97820118A9202832045C888414B313D526) (from thread 795) Terminate called for uncaught exception:
1439814:2022.12.21 02:04:45.924775 [ 644 ] {} <Fatal> BaseDaemon: Code: 49. DB::Exception: Part 8_0_30_1 intersects part 8_9_9_1. It is a bug or a result of manual intervention in the ZooKeeper data. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
1439815:2022.12.21 02:04:45.924800 [ 644 ] {} <Fatal> BaseDaemon:
1439816:2022.12.21 02:04:45.924815 [ 644 ] {} <Fatal> BaseDaemon: 0. ./build_docker/../src/Common/Exception.cpp:77: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0xd203d5a in /usr/lib/debug/usr/bin/clickhouse.debug
1439817:2022.12.21 02:04:45.924831 [ 644 ] {} <Fatal> BaseDaemon: 1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0x9f5577b in /usr/lib/debug/usr/bin/clickhouse.debug
1439818:2022.12.21 02:04:45.924857 [ 644 ] {} <Fatal> BaseDaemon: 2. ./build_docker/../src/Storages/MergeTree/ActiveDataPartSet.cpp:0: DB::ActiveDataPartSet::add(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>*) @ 0x137c6b23 in /usr/lib/debug/usr/bin/clickhouse.debug
1439819:2022.12.21 02:04:45.924872 [ 644 ] {} <Fatal> BaseDaemon: 3. ./build_docker/../contrib/llvm-project/libcxx/include/__tree:189: DB::ReplicatedMergeTreeQueue::addPartToMutations(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::MergeTreePartInfo const&) @ 0x13acbf9a in /usr/lib/debug/usr/bin/clickhouse.debug
1439820:2022.12.21 02:04:45.924884 [ 644 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: DB::ReplicatedMergeTreeQueue::insertUnlocked(std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry> const&, std::__1::optional<long>&, std::__1::lock_guard<std::__1::mutex>&) @ 0x13aca535 in /usr/lib/debug/usr/bin/clickhouse.debug
1439821:2022.12.21 02:04:45.924901 [ 644 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x13ad4a97 in /usr/lib/debug/usr/bin/clickhouse.debug
1439822:2022.12.21 02:04:45.924914 [ 644 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeMergePredicate::ReplicatedMergeTreeMergePredicate(DB::ReplicatedMergeTreeQueue&, std::__1::shared_ptr<zkutil::ZooKeeper>&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&&) @ 0x13af2bfe in /usr/lib/debug/usr/bin/clickhouse.debug
1439823:2022.12.21 02:04:45.924927 [ 644 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1473: DB::StorageReplicatedMergeTree::mergeSelectingTask() @ 0x1356efb5 in /usr/lib/debug/usr/bin/clickhouse.debug
1439824:2022.12.21 02:04:45.924938 [ 644 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../base/glibc-compatibility/musl/clock_gettime.c:62: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x11e20101 in /usr/lib/debug/usr/bin/clickhouse.debug
1439825:2022.12.21 02:04:45.924949 [ 644 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::BackgroundSchedulePool::threadFunction() @ 0x11e236ca in /usr/lib/debug/usr/bin/clickhouse.debug
1439826:2022.12.21 02:04:45.924965 [ 644 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned
1439828:2022.12.21 02:04:45.934707 [ 319397 ] {} <Fatal> BaseDaemon: ########################################
1439829:2022.12.21 02:04:45.934750 [ 319397 ] {} <Fatal> BaseDaemon: (version 22.13.1.297, build id: E74F2B97820118A9202832045C888414B313D526) (from thread 795) (no query) Received signal Aborted (6)
1439830:2022.12.21 02:04:45.934784 [ 319397 ] {} <Fatal> BaseDaemon:
1439831:2022.12.21 02:04:45.934809 [ 319397 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f53d5d9900b 0x7f53d5d78859 0xd44fadc 0x19590203 0x1959016e 0x13ad6759 0x13af2bfe 0x1356efb5 0x11e20101 0x11e236ca 0x11e245ec 0xd2cd92a 0xd2d29c1 0x7f53d5f50609 0x7f53d5e75133
1439832:2022.12.21 02:04:45.934835 [ 319397 ] {} <Fatal> BaseDaemon: 2. gsignal @ 0x7f53d5d9900b in ?
1439833:2022.12.21 02:04:45.938423 [ 319397 ] {} <Fatal> BaseDaemon: 3. abort @ 0x7f53d5d78859 in ?
1439834:2022.12.21 02:04:45.969915 [ 319397 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../src/Daemon/BaseDaemon.cpp:458: terminate_handler() @ 0xd44fadc in /usr/lib/debug/usr/bin/clickhouse.debug
1439835:2022.12.21 02:04:45.971502 [ 319397 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x19590203 in /usr/lib/debug/usr/bin/clickhouse.debug
1439836:2022.12.21 02:04:45.989596 [ 319397 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/../contrib/llvm-project/libcxxabi/src/cxa_exception_storage.cpp:97: __cxa_get_globals_fast
1439837:2022.12.21 02:04:45.989620 [ 319397 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:79: std::terminate() @ 0x1959016e in /usr/lib/debug/usr/bin/clickhouse.debug
1439842:2022.12.21 02:04:46.062993 [ 319397 ] {} <Fatal> BaseDaemon: 7. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x13ad6759 in /usr/lib/debug/usr/bin/clickhouse.debug
1439846:2022.12.21 02:04:46.158195 [ 319397 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:0: DB::ReplicatedMergeTreeMergePredicate::ReplicatedMergeTreeMergePredicate(DB::ReplicatedMergeTreeQueue&, std::__1::shared_ptr<zkutil::ZooKeeper>&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>&&) @ 0x13af2bfe in /usr/lib/debug/usr/bin/clickhouse.debug
1439875:2022.12.21 02:04:46.476694 [ 319397 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__hash_table:1473: ~__hash_table
1439876:2022.12.21 02:04:46.476732 [ 319397 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/unordered_set:615: ~unordered_set
1439877:2022.12.21 02:04:46.476751 [ 319397 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/StorageReplicatedMergeTree.cpp:3147: DB::StorageReplicatedMergeTree::mergeSelectingTask() @ 0x1356efb5 in /usr/lib/debug/usr/bin/clickhouse.debug
1439878:2022.12.21 02:04:46.487566 [ 319397 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../base/glibc-compatibility/musl/clock_gettime.c:62: clock_gettime
1439879:2022.12.21 02:04:46.487599 [ 319397 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/../src/Common/Stopwatch.h:15: clock_gettime_ns(int)
1439880:2022.12.21 02:04:46.487611 [ 319397 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/../src/Common/Stopwatch.h:24: clock_gettime_ns_adjusted(unsigned long, int)
1439881:2022.12.21 02:04:46.487622 [ 319397 ] {} <Fatal> BaseDaemon: 10.4. inlined from ./build_docker/../src/Common/Stopwatch.h:60: Stopwatch::nanoseconds() const
1439882:2022.12.21 02:04:46.487633 [ 319397 ] {} <Fatal> BaseDaemon: 10.5. inlined from ./build_docker/../src/Common/Stopwatch.h:49: Stopwatch::elapsedNanoseconds() const
1439883:2022.12.21 02:04:46.487643 [ 319397 ] {} <Fatal> BaseDaemon: 10.6. inlined from ./build_docker/../src/Common/Stopwatch.h:51: Stopwatch::elapsedMilliseconds() const
1439884:2022.12.21 02:04:46.487653 [ 319397 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Core/BackgroundSchedulePool.cpp:99: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x11e20101 in /usr/lib/debug/usr/bin/clickhouse.debug
1439887:2022.12.21 02:04:46.504511 [ 319397 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: ~shared_ptr
1439888:2022.12.21 02:04:46.504538 [ 319397 ] {} <Fatal> BaseDaemon: 11. ./build_docker/../src/Core/BackgroundSchedulePool.cpp:298: DB::BackgroundSchedulePool::threadFunction() @ 0x11e236ca in /usr/lib/debug/usr/bin/clickhouse.debug
1439889:2022.12.21 02:04:46.523259 [ 319397 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/../src/Core/BackgroundSchedulePool.cpp:0: operator()
1439890:2022.12.21 02:04:46.523300 [ 319397 ] {} <Fatal> BaseDaemon: 12.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)
1439891:2022.12.21 02:04:46.523327 [ 319397 ] {} <Fatal> BaseDaemon: 12.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'()&)
1439892:2022.12.21 02:04:46.523437 [ 319397 ] {} <Fatal> BaseDaemon: 12.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'(), void ()>::operator()[abi:v15000]()
1439893:2022.12.21 02:04:46.523457 [ 319397 ] {} <Fatal> BaseDaemon: 12. ./build_docker/../contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_2&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x11e245ec in /usr/lib/debug/usr/bin/clickhouse.debug
1439896:2022.12.21 02:04:46.541156 [ 319397 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/../base/base/wide_integer_impl.h:786: bool wide::integer<128ul, unsigned int>::_impl::operator_eq<wide::integer<128ul, unsigned int>>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
1439897:2022.12.21 02:04:46.541198 [ 319397 ] {} <Fatal> BaseDaemon: 13.2. inlined from ./build_docker/../base/base/wide_integer_impl.h:1453: bool wide::operator==<128ul, unsigned int, 128ul, unsigned int>(wide::integer<128ul, unsigned int> const&, wide::integer<128ul, unsigned int> const&)
1439898:2022.12.21 02:04:46.541216 [ 319397 ] {} <Fatal> BaseDaemon: 13.3. inlined from ./build_docker/../base/base/strong_typedef.h:42: StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>::operator==(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&) const
1439899:2022.12.21 02:04:46.541233 [ 319397 ] {} <Fatal> BaseDaemon: 13.4. inlined from ./build_docker/../src/Common/OpenTelemetryTraceContext.h:39: DB::OpenTelemetry::Span::isTraceEnabled() const
1439900:2022.12.21 02:04:46.541245 [ 319397 ] {} <Fatal> BaseDaemon: 13. ./build_docker/../src/Common/ThreadPool.cpp:296: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xd2cd92a in /usr/lib/debug/usr/bin/clickhouse.debug
1439904:2022.12.21 02:04:46.562923 [ 319397 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>::reset[abi:v15000](std::__1::__thread_struct*)
1439905:2022.12.21 02:04:46.562957 [ 319397 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
1439906:2022.12.21 02:04:46.563107 [ 319397 ] {} <Fatal> BaseDaemon: 14.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/tuple:265: ~__tuple_leaf
1439907:2022.12.21 02:04:46.563136 [ 319397 ] {} <Fatal> BaseDaemon: 14.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/tuple:538: ~tuple
1439908:2022.12.21 02:04:46.563169 [ 319397 ] {} <Fatal> BaseDaemon: 14.5. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>::operator()[abi:v15000](std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>*) const
1439909:2022.12.21 02:04:46.563230 [ 319397 ] {} <Fatal> BaseDaemon: 14.6. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::__1::unique_ptr<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>, std::__1::default_delete<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15000](std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>*)
1439910:2022.12.21 02:04:46.563310 [ 319397 ] {} <Fatal> BaseDaemon: 14.7. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
1439911:2022.12.21 02:04:46.563612 [ 319397 ] {} <Fatal> BaseDaemon: 14. ./build_docker/../contrib/llvm-project/libcxx/include/thread:297: void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0xd2d29c1 in /usr/lib/debug/usr/bin/clickhouse.debug
1439912:2022.12.21 02:04:46.563694 [ 319397 ] {} <Fatal> BaseDaemon: 15. ? @ 0x7f53d5f50609 in ?
1439913:2022.12.21 02:04:46.563738 [ 319397 ] {} <Fatal> BaseDaemon: 16. clone @ 0x7f53d5e75133 in ?
1439914:2022.12.21 02:04:46.563756 [ 319397 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
1440776:2022.12.21 02:05:06.427615 [ 642 ] {} <Fatal> Application: Child process was terminated by signal 6.
```

**Comment by tavplubix** [comment] 2023-01-09 19:54
Looks like a duplicate of https://github.com/ClickHouse/ClickHouse/issues/44845

**Closed by tavplubix** 2023-01-09 19:54 UTC
Labels: testing
