### ISSUE TITLE
TRUNCATE query stuck if replica is down

### ISSUE THREAD

**Issue by hackaholic** [ClickHouse/ClickHouse#42051] opened 2022-10-04 11:04 UTC
Truncate query is hung when one of the replica is down.
clickhouse-0.clickhouse.iond.svc.cluster.local :) show processlist format Vertical

SHOW PROCESSLIST
FORMAT Vertical

Query id: c302cdc0-b397-4ce4-906d-e43d4e0e8de0

Row 1:
──────
is_initial_query:     1
user:                 default
query_id:             4fc6bb8c-6411-4e38-8d05-38bbe75f7b88
address:              ::ffff:127.0.0.1
port:                 45576
initial_user:         default
initial_query_id:     4fc6bb8c-6411-4e38-8d05-38bbe75f7b88
initial_address:      ::ffff:127.0.0.1
initial_port:         45576
interface:            1
os_user:
client_hostname:      clickhouse-0.clickhouse.iond.svc.cluster.local
client_name:          ClickHouse
client_revision:      54447
client_version_major: 21
client_version_minor: 3
client_version_patch: 13
http_method:          0
http_user_agent:
http_referer:
forwarded_for:
quota_key:
**elapsed:              6932.399947095**
is_cancelled:         0
read_rows:            0
read_bytes:           0
total_rows_approx:    0
written_rows:         0
written_bytes:        0
memory_usage:         0
peak_memory_usage:    0
query:                TRUNCATE TABLE IF EXISTS device_init_info
thread_ids:           [745]
ProfileEvents.Names:  ['Query','ReadCompressedBytes','CompressedReadBufferBlocks','CompressedReadBufferBytes','IOBufferAllocs','IOBufferAllocBytes','ZooKeeperTransactions','ZooKeeperList','ZooKeeperCreate','ZooKeeperGet','ZooKeeperMulti','ContextLock','RWLockAcquiredWriteLocks']
ProfileEvents.Values: [1,36,1,10,1,89,2320,4,2,2313,1,4,2]
Settings.Names:       ['load_balancing','max_execution_time','max_memory_usage']
Settings.Values:      ['random','10','30000000000']

1 rows in set. Elapsed: 0.010 sec.

**How to reproduce**
Create replicate merge tree table in in clickhouse cluster with 3 replica. 
bring down one of the replica, now rung truncate query on the table.

* Which ClickHouse server version to use
* clickhouse-0.clickhouse.iond.svc.cluster.local :) select version()

SELECT version()

Query id: 452d44a4-e197-4d79-822a-88c455d05586

┌─version()─┐
│ **21.3.13.9** │
└───────────┘

1 rows in set. Elapsed: 0.008 sec.

* `CREATE TABLE` statements
clickhouse-0.clickhouse.iond.svc.cluster.local :) show create table default.device_init_info

SHOW CREATE TABLE default.device_init_info

Query id: e5ee5814-ae68-452c-ac84-a6b0edb973cb

┌─statement────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.device_init_info
(
    `json` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/default/tables/device_init_info/{shard}', '{replica}')
PRIMARY KEY json
ORDER BY json
SETTINGS index_granularity = 8192 │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.003 sec.

* Queries to run that lead to unexpected result

**Expected behavior**
Query should not stuck it should timeout, IN the setting **replication_alter_partitions_sync is set 1** , even the query is waiting for it to execute it on other replica.
clickhouse-0.clickhouse.iond.svc.cluster.local :) select * from system.settings where name like '%replication_alter_partitions_sync%' format Vertical

SELECT *
FROM system.settings
WHERE name LIKE '%replication_alter_partitions_sync%'
FORMAT Vertical

Query id: e764b067-019f-4aea-97c0-6079d9ca4010

Row 1:
──────
name:        replication_alter_partitions_sync
**value:       1**
changed:     0
description: Wait for actions to manipulate the partitions. 0 - do not wait, 1 - wait for execution only of itself, 2 - wait for everyone.
min:         ᴺᵁᴸᴸ
max:         ᴺᵁᴸᴸ
readonly:    0
type:        UInt64

1 rows in set. Elapsed: 0.009 sec.

**Comment by hackaholic** [comment] 2022-10-04 12:34
Looks like this setting is not supported in 21.3.13.9 
clickhouse-0.clickhouse.iond.svc.cluster.local :) select * from system.settings where name like '%replication_wait_for_inactive_replica_timeout%'

SELECT *
FROM system.settings
WHERE name LIKE '%**replication_wait_for_inactive_replica_timeout**%'

Query id: a3f8ad9f-5ecc-4c74-acfb-4c8cbc0d287e

Ok.

0 rows in set. Elapsed: 0.005 sec.

clickhouse-0.clickhouse.iond.svc.cluster.local :)

**Comment by den-crane** [comment] 2022-10-04 12:52
duplicate of https://github.com/ClickHouse/ClickHouse/issues/27178
fixed https://github.com/ClickHouse/ClickHouse/pull/27931

v21.10, 2021-10-16
https://clickhouse.com/docs/en/whats-new/changelog/2021/
Added replication_wait_for_inactive_replica_timeout setting. It allows to specify how long to wait for inactive replicas to execute ALTER/OPTIMZE/TRUNCATE query (default is 120 seconds). If replication_alter_partitions_sync is 2 and some replicas are not active for more than replication_wait_for_inactive_replica_timeout seconds, then UNFINISHED will be thrown. [#27931](https://github.com/ClickHouse/ClickHouse/pull/27931) ([tavplubix](https://github.com/tavplubix)).

**Comment by tavplubix** [comment] 2022-10-04 12:52
Fixed in https://github.com/ClickHouse/ClickHouse/pull/27931
Version 21.3 is obsolete, you should upgrade to supported version.

**Closed by tavplubix** 2022-10-04 12:52 UTC
Labels: obsolete-version, potential bug
