### ISSUE TITLE
packages.clickhouse.com is unreliable

### ISSUE THREAD

**Issue by pavel-odintsov** [ClickHouse/ClickHouse#41420] opened 2022-09-16 16:47 UTC
Hello!

I did my best to check for duplicates. Sorry if it was already reported.

Since 15th of September we noticed multiple reports from our customers about issues with installing Clickhouse from official repositories. 

We can see exactly same error from multiple places globally:
```
manager: E: Failed to fetch https://packages.clickhouse.com/deb/pool/stable/clickhouse-client_22.8.5.29_amd64.deb  429  Too Many Requests [IP: 172.66.40.249 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
 output: Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  clickhouse-common-static
Suggested packages:
  clickhouse-common-static-dbg
The following NEW packages will be installed:
  clickhouse-client clickhouse-common-static
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 265 MB of archives.
After this operation, 773 MB of additional disk space will be used.
Get:1 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-common-static amd64 22.8.5.29 [265 MB]
Err:2 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-client amd64 22.8.5.29
  429  Too Many Requests [IP: 172.66.40.249 443]
Fetched 265 MB in 4s (73.0 MB/s)
```

And we can see very same behavior from our AWS based Circle CI deployment.

We may run 2-3 concurrent requests from our CI but definitely not more.

From our customer reported failure they do not run any concurrent installations and do one installation per IP which should not trigger any limitation about umber of IPs.

It feels as some kind of concurrency misconfiguration.

Our CI is public and you can check exact errors here: https://app.circleci.com/pipelines/github/FastNetMon/fastnetmon-advanced-packages?branch=main

We can see that it happens only with Debian and Ubuntu. For some reasons CentOS  RedHat's is not affected.

Would you mind checking it?

Thank you!

**Comment by Felixoid** [comment] 2022-09-19 18:25
It should be relatively better now, but generally, it's a protection against ddosing us from some Chinese consumers who bypass the cache and request a lot from the backend.

I hope we'll migrate to another scheme relatively soon since the current solution is unsuitable for the existing loads.

**Comment by pavel-odintsov** [comment] 2022-09-21 13:33
Thank you for feedback!

Unfortunately, we still see lots of failures in all locations ;(

**Comment by Felixoid** [comment] 2022-09-21 14:08
The next system is in progress

**Comment by Felixoid** [comment] 2022-09-22 14:08
So, the new system was deployed a couple of hours ago. I already received feedback that it works.

The new system is built on top of cloudflare r2+workers, so it should be very stable.

In case of new issues, you are free to spin another ticket or reopen this.

**Comment by cfrietschy** [comment] 2022-09-22 14:30
The GPG key has also changed, contrary to the documentation. An apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 3E4AD4719DDE9A38 fixes the error on my end.

**Comment by Felixoid** [comment] 2022-09-22 14:50
strange.. I've thought a subkey will work :thinking:

**Comment by pavel-odintsov** [comment] 2022-09-22 23:02
Thank you so much for fixing it. It works fine now.

**Comment by alexeyrusnak** [comment] 2022-09-30 11:45
Hi! Problems again


ClickHouse - Stable Repository                                                                                                                                                                3.7 kB/s | 8.6 kB     00:02
Errors during downloading metadata for repository 'clickhouse-stable':
  - Status code: 500 for https://packages.clickhouse.com/rpm/stable/repodata/f442d62d2d177ed149970166955072cd0d43087af315f329272cd410ac2b572f-primary.xml.gz (IP: 188.114.99.202)
  - Status code: 500 for https://packages.clickhouse.com/rpm/stable/repodata/7f7538c7f62521372188b9c2adef7e355e84b1375e48eb24ddfcf0afa8ddb4c6-filelists.xml.gz (IP: 188.114.99.202)
Error: Failed to download metadata for repo 'clickhouse-stable': Yum repo downloading error: Downloading error(s): repodata/f442d62d2d177ed149970166955072cd0d43087af315f329272cd410ac2b572f-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/7f7538c7f62521372188b9c2adef7e355e84b1375e48eb24ddfcf0afa8ddb4c6-filelists.xml.gz - Cannot download, all mirrors were already tried without success
Adding repo from: https://packages.clickhouse.com/rpm/clickhouse.repo

**Comment by Felixoid** [comment] 2022-10-04 11:28
Thanks for the report, I've fixed it on Friday. The issue was in a stale repomd.xml

Besides that, there was an issue with 500 instead of 404 for mentioned pages, it is fixed today with https://github.com/ClickHouse/clickhouse-website-worker/pull/176 and https://github.com/ClickHouse/clickhouse-website-worker/pull/177

**Comment by CVanF5** [comment] 2022-10-26 17:28
I know this is closed, but in case anyone is watching I think there's issues with RHEL-7 based packages. (Tried centos-7, oracle-7).  RHEL-8 seems to be fine!
```
sudo yum install -y clickhouse-common-static clickhouse-server
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                                                                                                                              |  21 kB  00:00:00     
 * base: mirror.keystealth.org
 * epel: ftp-osl.osuosl.org
 * extras: or-mirror.iwebfusion.net
 * updates: centos.mirror.shastacoe.net
base                                                                                                                                                              | 3.6 kB  00:00:00     
clickhouse-lts/signature                                                                                                                                          |  833 B  00:00:00     
clickhouse-lts/signature                                                                                                                                          | 3.0 kB  00:00:00 !!! 
extras                                                                                                                                                            | 2.9 kB  00:00:00     
updates                                                                                                                                                           | 2.9 kB  00:00:00     
clickhouse-lts/primary_db      FAILED                                          
https://packages.clickhouse.com/rpm/lts/repodata/bd8ec1088bf4a8df522d8190265e424947b02ba7cd003920f11e6fd911983d9d-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found--:--:-- ETA 
Trying other mirror.
To address this issue please refer to the below wiki article 
```

**Comment by Felixoid** [comment] 2022-10-27 11:52
Yes, thank you and sorry, it's fixed in #42706

**Comment by pavel-odintsov** [comment] 2022-10-29 15:04
We saw following issue from multiple locations this night 4:08 AM (GMT), 29th October:
```
Err:11 https://packages.clickhouse.com/deb stable InRelease
  400  Bad Request [IP: 172.66.40.249 443]
```

It happened from Amazon AWS IPs: 54.198.183.230, 54.162.243.194

**Comment by Felixoid** [comment] 2022-10-29 18:46
I see 404 requests in the statistics. But I need more info to investigate it.

The best would be, of course, a complete request, if you can get it

**Comment by pavel-odintsov** [comment] 2022-10-31 13:48
Sorry but I have no detailed information from http headers. We can capture only errors as they reported by APT itself.

**Comment by Felixoid** [comment] 2022-11-01 12:08
Nevertheless, try the solution from https://github.com/ClickHouse/ClickHouse/pull/42859

**Comment by Felixoid** [comment] 2022-11-03 09:36
@pavel-odintsov did it work out?

**Comment by pavel-odintsov** [comment] 2022-11-04 13:39
It did not happen again. I'll keep you updated if it happens again.

**Comment by djuarezg** [comment] 2022-11-21 09:03
Seems to be inconsistent again
```
Failed to download metadata for repo 'clickhouse-stable': Yum repo downloading error: Downloading error(s): repodata/2de1439e4d663f6b43d3352250c72db96fce90324427ebf3399d29d73c883a0c-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/8903f1f8e5ea21c7100c688d8bd87647bb3e453ab51e90e654bbdd3202ee7cb9-filelists.xml.gz - Cannot download, all mirrors were already tried without success
```

**Comment by Felixoid** [comment] 2022-11-21 12:34
Thanks, it's not a normal state to have eventual inconsistency. I'll spend additional time to find how I can make repos reliable

**Comment by Felixoid** [comment] 2022-11-23 11:42
And it's fixed on the storage side! :tada: 

See https://github.com/yandex-cloud/geesefs/issues/57#issuecomment-1324888246

**Closed by Felixoid** 2022-11-23 11:42 UTC
Labels: major, bug on website

**Comment by pavel-odintsov** [comment] 2022-11-27 16:44
I'm sorry to bring bad news but it happened again from Argentina.

```
apt-get update 
Hit:1 http://ar.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 https://packages.grafana.com/oss/deb stable InRelease
Hit:3 http://ar.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://ar.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 http://ar.archive.ubuntu.com/ubuntu bionic-security InRelease
Ign:6 http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/6.0 InRelease
Hit:7 http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/6.0 Release
Hit:9 https://repos.influxdata.com/ubuntu bionic InRelease
Get:10 https://packages.clickhouse.com/deb stable InRelease [2484 B]
Hit:11 http://repo.fastnetmon.com/fastnetmon_ubuntu_bionic bionic InRelease
Hit:12 https://nginx.org/packages/ubuntu bionic InRelease
Reading package lists...

E: Repository 'https://packages.clickhouse.com/deb stable InRelease' changed its 'Origin' value from 'Artifactory' to 'ClickHouse'
E: Repository 'https://packages.clickhouse.com/deb stable InRelease' changed its 'Label' value from 'Artifactory' to 'ClickHouse'
```

When we tried to install then we got following error:
```
sudo apt-get -y -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef install clickhouse-client
Got following stdout output Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  clickhouse-common-static
Suggested packages:
  clickhouse-common-static-dbg
The following NEW packages will be installed:
  clickhouse-client clickhouse-common-static
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 265 MB of archives.
After this operation, 773 MB of additional disk space will be used.
Err:1 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-common-static amd64 22.8.5.29
  404  Not Found [IP: 172.66.40.249 443]
Err:2 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-client amd64 22.8.5.29
  404  Not Found [IP: 172.66.40.249 443]

E: Failed to fetch https://packages.clickhouse.com/deb/pool/stable/clickhouse-common-static_22.8.5.29_amd64.deb  404  Not Found [IP: 172.66.40.249 443]
E: Failed to fetch https://packages.clickhouse.com/deb/pool/stable/clickhouse-client_22.8.5.29_amd64.deb  404  Not Found [IP: 172.66.40.249 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by Felixoid** [comment] 2022-11-28 09:24
It's a broken local apt state. Follow the [troubleshooting](https://clickhouse.com/docs/en/faq/troubleshooting/#you-get-different-warnings-with-apt-get-update)

**Comment by youssefqarri** [comment] 2023-08-09 18:47
Hello,

The issue is happening again on Ubuntu 22

```
root@SERVER ~ # apt update
Hit:1 http://mirror.hetzner.com/ubuntu/packages jammy InRelease
Hit:2 http://mirror.hetzner.com/ubuntu/packages jammy-updates InRelease
Hit:3 http://mirror.hetzner.com/ubuntu/packages jammy-backports InRelease
Hit:4 http://mirror.hetzner.com/ubuntu/packages jammy-security InRelease
Hit:5 http://de.archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:9 https://repo.clickhouse.com/deb/stable main/ InRelease
Err:10 https://repo.clickhouse.com/deb/stable main/ Release
  404  Not Found [IP: 172.66.40.249 443]
Reading package lists... Done
E: The repository 'https://repo.clickhouse.com/deb/stable main/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by Felixoid** [comment] 2023-08-09 19:56
Just tried the commands from https://clickhouse.com/docs/en/install#setup-the-debian-repository

```
root@bcdcb4efd71c:/# GNUPGHOME=$(mktemp -d)
sudo GNUPGHOME="$GNUPGHOME" gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754
sudo rm -r "$GNUPGHOME"
sudo chmod +r /usr/share/keyrings/clickhouse-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update
gpg: keybox '/usr/share/keyrings/clickhouse-keyring.gpg' created
gpg: /tmp/tmp.oMQ5FZwGXR/trustdb.gpg: trustdb created
gpg: key 8919F6BD2B48D754: public key "ClickHouse Inc. Repositories Key <packages@clickhouse.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 https://packages.clickhouse.com/deb stable InRelease [2484 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:6 https://packages.clickhouse.com/deb stable/main amd64 Packages [81.1 kB]
Fetched 83.6 kB in 1s (135 kB/s)
Reading package lists... Done
```

Please, check again

**Comment by Felixoid** [comment] 2023-08-09 19:56
Oh, `repo.clickhouse.com`. It's dead for good

**Comment by youssefqarri** [comment] 2023-08-09 19:59
I installed Ubuntu 20 instead of 22. It's working properly now.

**Comment by Felixoid** [comment] 2023-08-09 20:21
The repository hosted on repo.clickhouse.com is heavily outdated. It has the same packages as https://packages.clickhouse.com/repo-archive/deb/stable/main/

Use it at your own risk. Better is migrating to the https://clickhouse.com/docs/en/install#setup-the-debian-repository

**Comment by centralhardware** [comment] 2023-12-21 20:31
still not fixed? same error from OVH Poland datacenter

**Comment by youssefqarri** [comment] 2023-12-21 23:07
Install clickhouse using the command line from the official website. It will work for you

**Comment by Felixoid** [comment] 2023-12-22 09:57
> still not fixed? same error from OVH Poland datacenter

there are plenty of messages with so many different errors. Could you be a little bit more specific, please?
