### ISSUE TITLE
Setting max_result_rows only works for certain tables

### ISSUE THREAD

**Issue by cyber-moon** [ClickHouse/ClickHouse#39972] opened 2022-08-08 08:05 UTC
**Describe the unexpected behaviour**
max_result_rows should limit the number of rows returned for _any_ request on _any_ Clickhouse-Table (see [this example](https://clickhouse.com/docs/en/operations/settings/query-complexity/#result-overflow-mode)).
However, the limitation only works for certain tables. For example, the limitation works on `system.tables` but does not work on `system.settings`. Similarly, it works on `numbers_mt(1000)` but does not work on a copy (MergeTree-engine) of `numbers_mt(1000)`.

**How to reproduce**
Clickhouse-Server: clickhouse/clickhouse-server:22.3.10.22 (Docker)

**Correctly working examples:**
- Ex. 1:
`SELECT * FROM system.tables SETTINGS result_overflow_mode='break', max_result_rows=2, max_block_size=3`
&rarr; 3 rows are returned, as expected.
- Ex. 2:
`SELECT * FROM numbers_mt(1000) SETTINGS result_overflow_mode='break', max_result_rows=13, max_block_size=10, max_threads=1`
&rarr; 20 rows are returned, as expected.

**Unexpected behaviour:**
- Ex. 3:
`SELECT * FROM system.settings SETTINGS result_overflow_mode='break', max_result_rows=2, max_block_size=3`
&rarr; 535 rows are returned, expected 3.
- Ex. 4:
`CREATE TABLE custom_numbers ENGINE=MergeTree ORDER BY number AS SELECT * FROM numbers_mt(1000)`
`SELECT * FROM custom_numbers SETTINGS result_overflow_mode='break', max_result_rows=13, max_block_size=10, max_threads=1`
&rarr; 1000 rows are returned, expected 20.

**Expected behavior**
I expect the `max_result_rows` setting to work on all tables, no matter of which engine they have. If this is not guaranteed, I'd expect this to be mentioned in the documentation.

**Comment by UnamedRus** [comment] 2022-08-08 08:11
Duplicate https://github.com/ClickHouse/ClickHouse/issues/29895

**Comment by alexey-milovidov** [comment] 2022-10-20 02:33
@UnamedRus this is not a duplicate of https://github.com/ClickHouse/ClickHouse/issues/29895

**Comment by alexey-milovidov** [comment] 2022-10-20 02:36
@cyber-moon the setting `max_result_rows` does not provide a strict limit on the result size. It stops producing the result on the next block of data if the number of produced records is larger than the threshold. But it does not split blocks of data into smaller pieces.

**Closed by alexey-milovidov** 2022-10-20 02:36 UTC
Labels: invalid, unexpected behaviour
