### ISSUE TITLE
Can't build on arm64 (invalid bfd target)

### ISSUE THREAD

**Issue by rubentorresbonet** [ClickHouse/ClickHouse#14002] opened 2020-08-24 11:41 UTC
**Operating system**
armbian (equivalent to ubuntu server 20.04) kernel 5.6
odroid n2 (similar to rpi4)

**Cmake version**
3.16.3

**Ninja version**
1.10.0

**Compiler name and version**
gcc & gg++: 9.3.0

**Full cmake and/or ninja output**
ruben@odroidn2:~/ClickHouse/build$ ninja
[0/2] Re-checking globbed directories...
[1/6151] Generating America_Guayaquil.o
FAILED: contrib/cctz-cmake/America_Guayaquil.o
cd /home/ruben/ClickHouse/build/contrib/cctz-cmake && cd /home/ruben/ClickHouse/contrib/cctz/testdata/zoneinfo && /usr/bin/objcopy -I binary -O elf64-aarch64 -B aarch64 America/Guayaquil /home/ruben/ClickHouse/build/contrib/cctz-cmake/America_Guayaquil.o && /usr/bin/objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents /home/ruben/ClickHouse/build/contrib/cctz-cmake/America_Guayaquil.o /home/ruben/ClickHouse/build/contrib/cctz-cmake/America_Guayaquil.o
/usr/bin/objcopy: /home/ruben/ClickHouse/build/contrib/cctz-cmake/America_Guayaquil.o: invalid bfd target
[2/6151] Generating America_Guyana.o
FAILED: contrib/cctz-cmake/America_Guyana.o
cd /home/ruben/ClickHouse/build/contrib/cctz-cmake && cd /home/ruben/ClickHouse/contrib/cctz/testdata/zoneinfo && /usr/bin/objcopy -I binary -O elf64-aarch64 -B aarch64 America/Guyana /home/ruben/ClickHouse/build/contrib/cctz-cmake/America_Guyana.o && /usr/bin/objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents /home/ruben/ClickHouse/build/contrib/cctz-cmake/America_Guyana.o /home/ruben/ClickHouse/build/contrib/cctz-cmake/America_Guyana.o
/usr/bin/objcopy: /home/ruben/ClickHouse/build/contrib/cctz-cmake/America_Guyana.o: invalid bfd target

**Comment by filimonov** [comment] 2020-08-24 12:24
https://github.com/ClickHouse/ClickHouse/pull/10425

**Comment by rubentorresbonet** [comment] 2020-08-24 12:30
As extra info: I got the source from the master repository today.

**Comment by rubentorresbonet** [comment] 2020-08-26 12:37
Any update on this? Clickhouse doesn't run on arm at all because of this.

**Comment by akuzm** [comment] 2020-08-26 16:17
Some workarounds that might help:

1. Don't build it at all, download a pre-built binary from the CI as described here: https://clickhouse.tech/docs/en/development/build/#you-dont-have-to-build-clickhouse
The configuration you need is `clang-10-aarch64`.

2. Use `clang-10`. This is the way ClickHouse is compiled for AArch64 in CI, so it has better chance of success.

3. Use `lld` linker with `gcc`. Apparently the problem is that the `bfd` linker that is chosen by default with `gcc` complains about some of the more special commands that are used to build timezone data.

**Comment by code-snail** [comment] 2020-09-03 12:45
I  have the same problem in arm64

/usr/bin/objcopy:Zulu.o: Invalid bfd target

**Comment by alexey-milovidov** [comment] 2020-09-25 05:44
You have to install `llvm-objcopy`, it will be used instead of `objcopy`.

**Comment by alexey-milovidov** [comment] 2020-09-25 05:44
Fixed in this commit: https://github.com/ClickHouse/ClickHouse/pull/13528/commits/8d616444e4fa723e6cb5e70d2189cb005c6b5d9e

**Closed by alexey-milovidov** 2020-09-25 05:44 UTC
Labels: alternative build, build
