### ISSUE TITLE
error install clickhouse-server deb repo 

### ISSUE THREAD

**Issue by it-forever** [ClickHouse/ClickHouse#65229] opened 2024-06-13 14:16 UTC
**Company or project name**

Put your company name or project description here

**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors

**Installation type**
DEB
Packages, docker, single binary, curl?
Packages error
```
 sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.MhA2M2C8MF/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
gpg: key 8919F6BD2B48D754: "ClickHouse Inc. Repositories Key <packages@clickhouse.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@clickhouse-server:~# apt update
Hit:1 http://ru.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://ru.archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]                                     
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                              
Hit:4 http://ru.archive.ubuntu.com/ubuntu jammy-backports InRelease 
Get:5 https://packages.clickhouse.com/deb stable InRelease [2490 B]
Get:6 https://packages.clickhouse.com/deb stable/main amd64 Packages [130 kB]
Err:6 https://packages.clickhouse.com/deb stable/main amd64 Packages
  File has unexpected size (131346 != 130457). Mirror sync in progress? [IP: 188.114.99.233 443]
  Hashes of expected file:
   - Filesize:130457 [weak]
   - SHA256:0d3f191a5bfa709300afd5002525f0c43430878bff3d7b1b0740f1589a33f82e
   - SHA1:e4b6d69ef6979ea6cb476e26bf8a20b2043b04cb [weak]
   - MD5Sum:db3da8d69af37e27b9dbdb2ffd9e0764 [weak]
  Release file created at: Fri, 07 Jun 2024 10:57:43 +0000
Fetched 128 kB in 1s (102 kB/s)
Reading package lists... Done
W: https://packages.clickhouse.com/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/clickhouse.list:1 and /etc/apt/sources.list.d/packages_clickhouse_com_deb.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/clickhouse.list:1 and /etc/apt/sources.list.d/packages_clickhouse_com_deb.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/clickhouse.list:1 and /etc/apt/sources.list.d/packages_clickhouse_com_deb.list:1
E: Failed to fetch https://packages.clickhouse.com/deb/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (131346 != 130457). Mirror sync in progress? [IP: 188.114.99.233 443]
   Hashes of expected file:
    - Filesize:130457 [weak]
    - SHA256:0d3f191a5bfa709300afd5002525f0c43430878bff3d7b1b0740f1589a33f82e
    - SHA1:e4b6d69ef6979ea6cb476e26bf8a20b2043b04cb [weak]
    - MD5Sum:db3da8d69af37e27b9dbdb2ffd9e0764 [weak]
   Release file created at: Fri, 07 Jun 2024 10:57:43 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/clickhouse.list:1 and /etc/apt/sources.list.d/packages_clickhouse_com_deb.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/clickhouse.list:1 and /etc/apt/sources.list.d/packages_clickhouse_com_deb.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/clickhouse.list:1 and /etc/apt/sources.list.d/packages_clickhouse_com_deb.list:1
```
**Source of the ClickHouse**

A link to the source. Or the command you've tried

**Expected result**
not update repo. gpg error
What you expected

**The actual result**

What you get

**How to reproduce**

sudo apt-get install -y apt-transport-https ca-certificates dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754

echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update

* For Linux-based operating systems: provide a script for clear docker container from the official image
Ubuntu22.04
* For anything else: steps to reproduce on as much as possible clear system

**Comment by MikhailBurdukov** [comment] 2024-06-13 14:52
Got the same problem.
```
16.59 E: Failed to fetch https://packages.clickhouse.com/deb/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (131346 != 130457). Mirror sync in progress? 
```
https://github.com/yandex/ch-backup/pull/160

**Comment by Bluefissure** [comment] 2024-06-13 17:01
I think the `Packages.gz` from https://packages.clickhouse.com/deb/dists/stable/main/binary-amd64/Packages.gz doesn't match https://packages.clickhouse.com/deb/dists/stable/Release but matches https://packages.clickhouse.com/deb/dists/stable/Release.new

**Comment by alexey-milovidov** [comment] 2024-06-13 17:32
Reproduced: https://pastila.nl/?00464bb2/efc11f64e7f31aeaf149e5b8d7528afe#YDn0TqFkyTfNktrxNArMvw==

**Comment by Felixoid** [comment] 2024-06-13 18:21
The issue is fixed by the index regenerating. `reprepro --keepdirectories --keepunreferencedfiles --verbose --export=force export`

I hope a simple `apt update` should work

If not, the [troubleshooting](https://clickhouse.com/docs/en/guides/troubleshooting#you-get-different-warnings-with-apt-get-update) will definitely fix it

**Comment by alexey-milovidov** [comment] 2024-06-13 18:43
Fixed, here is the test:

```
docker run -it --rm ubuntu bash -c "apt update -y; apt install -y sudo gnupg ca-certificates; apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754; echo 'deb https://packages.clickhouse.com/deb stable main' | tee /etc/apt/sources.list.d/clickhouse.list; apt update -y; apt-get install -y clickhouse-client"
```

**Comment by Felixoid** [comment] 2024-06-13 18:46
The issue is reported to the geesefs repository

**Comment by hamshiva** [comment] 2024-07-01 10:46
Hi, I do get into the same issue. Following the troubleshooting guidelines didn't help.

`Err:4 https://packages.clickhouse.com/deb stable/main amd64 Packages
  File has unexpected size (135329 != 134428). Mirror sync in progress? [IP: 172.66.43.7 443]
`

Is the repo broken again ?

Regards,

**Comment by SpecialK118** [comment] 2024-07-01 11:08
I get the same error

**Comment by alifirat** [comment] 2024-07-01 11:19
Same.

**Comment by antodorosh** [comment] 2024-07-01 12:47
SAME

**Comment by hamshiva** [comment] 2024-07-01 12:53
Maybe @alexey-milovidov could reopen the issue ?

**Comment by antodorosh** [comment] 2024-07-01 12:57
Temporary fix that worked for me is using this installation: 
LTS instead of stable.

`sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | sudo gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb **lts** main" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update`

**Comment by keltia** [comment] 2024-07-12 18:06
I'm sorry but the issue still exist.

**Comment by Felixoid** [comment] 2024-07-13 22:56
The script from https://github.com/ClickHouse/ClickHouse/issues/65229#issuecomment-2166537378 works, and clickhouse is installed in docker

```
After this operation, 514 MB of additional disk space will be used.
Get:1 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-common-static amd64 24.6.2.17 [145 MB]
Get:2 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-client amd64 24.6.2.17 [59.0 kB]
Fetched 145 MB in 12s (12.1 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package clickhouse-common-static.
(Reading database ... 5261 files and directories currently installed.)
Preparing to unpack .../clickhouse-common-static_24.6.2.17_amd64.deb ...
Unpacking clickhouse-common-static (24.6.2.17) ...
Selecting previously unselected package clickhouse-client.
Preparing to unpack .../clickhouse-client_24.6.2.17_amd64.deb ...
Unpacking clickhouse-client (24.6.2.17) ...
Setting up clickhouse-common-static (24.6.2.17) ...
Setting up clickhouse-client (24.6.2.17) ...
```

Please follow the https://clickhouse.com/docs/en/guides/troubleshooting#you-get-different-warnings-with-apt-get-update to clean the dirty cache

**Closed** 2024-07-13 22:57 UTC
Labels: comp-install, blocker
