### ISSUE TITLE
ALTER fails without meaningful error info

### ISSUE THREAD

**Issue by Fullstop000** [ClickHouse/ClickHouse#16800] opened 2020-11-09 05:39 UTC
(you don't have to strictly follow this form)

**Describe the issue**
Executing `ALTER...UPDATE` on a table whose `data` and `metadata` are removed leads to an error `Cannot execute replicated DDL query on leader ` without more error info. 

Demo error log:
```
2020.11.09 03:36:25.124893 [ 239 ] {9d8691fe-78ee-4d6b-adb8-e356c218066a} <Error> executeQuery: Code: 48, e.displayText() = DB::Exception: There was an error on [10.168.0.62:9000]: Cannot execute replicated DDL query on leader (version 20.6.3.28 (official build)) (from 127.0.0.1:37668) (in query: ALTER TABLE test.test_table__local ON CLUSTER '{cluster}' UPDATE is_dev = 1 WHERE id = '49b30797-c87a-46fb-8c16-207fe5119b85'), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x12405650 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xa2423fd in /usr/bin/clickhouse
2. DB::DDLQueryStatusInputStream::readImpl() @ 0xefd9f8b in /usr/bin/clickhouse
3. DB::IBlockInputStream::read() @ 0xedf3d1d in /usr/bin/clickhouse
4. DB::AsynchronousBlockInputStream::calculate() @ 0xede9b77 in /usr/bin/clickhouse
5. ? @ 0xede9fd8 in /usr/bin/clickhouse
6. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa271a57 in /usr/bin/clickhouse
7. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const @ 0xa2721ca in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa270f67 in /usr/bin/clickhouse
9. ? @ 0xa26f4a3 in /usr/bin/clickhouse
10. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
11. clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
``` 
The `test.test_table__local`'s `data` and `metadata` are removed but its table info is not detached. 
Not like other cases such as updating the primary column value, this doesn't produce any information to users. If we executing a `DROP TABLE`, the error will be `File not found: ***.sql`, which is exactly the root cause and should be included in the stack trace above.

* Which ClickHouse server version to use
v20.6.3.28-stable

**Comment by filimonov** [comment] 2020-11-09 08:57
Duplicate of #9259 

P.S. Please update to 20.8 (20.6 is not supported anymore).

**Closed by filimonov** 2020-11-09 08:57 UTC
Labels: comp-dddl, usability
