### ISSUE TITLE
HashJoin uses much more memory than uncompressed data size

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#10409] opened 2020-04-21 15:06 UTC
```
create table t1 (f0 UInt64, f1 UInt64, f2 Float64, f3 UInt64) Engine=MergeTree order by f0;
insert into t1 select number, number, number/4345345, intDiv(number,4345345) from numbers(100000000);


select column, formatReadableSize(sum(column_data_compressed_bytes) as x) compresssize, 
      formatReadableSize(sum(column_data_uncompressed_bytes)) uncompressedsize
, database,table, column
from system.parts_columns where active = 1 and table = 't1'
group by database,table,column
order by column;

┌─column─┬─compresssize─┬─uncompressedsize─┬─database─┬─table─┬─column─┐
│ f0     │ 167.21 MiB   │ 762.94 MiB       │ dw       │ t1    │ f0     │
│ f1     │ 167.21 MiB   │ 762.94 MiB       │ dw       │ t1    │ f1     │
│ f2     │ 645.40 MiB   │ 762.94 MiB       │ dw       │ t1    │ f2     │
│ f3     │ 1.29 MiB     │ 762.94 MiB       │ dw       │ t1    │ f3     │
└────────┴──────────────┴──────────────────┴──────────┴───────┴────────┘


SET join_algorithm = 'hash';
SET send_logs_level = 'debug';

f0 = 762.94 MiB

select distinct t1.* from (select toUInt64(666) as f0) as t0 join (select f0 from t1) as t1 using f0 limit 1;
MemoryTracker: Peak memory usage (for query): 8.04 GiB.


f0 + f1 + f2 + f4 = 3051.76 MiB
select distinct t1.* from (select toUInt64(666) as f0) as t0 join (select * from t1) as t1 using f0 limit 1;
MemoryTracker: Peak memory usage (for query): 11.02 GiB.

```

**Comment by alexey-milovidov** [comment] 2020-04-21 23:19
#10423

**Comment by 4ertus2** [comment] 2020-04-22 09:17
The case when we have most data in hash table slightly improved here #10416. It can be improved further only with another kind of hash table: [Perfect hashing](https://en.wikipedia.org/wiki/Perfect_hash_function). We could make StorageJoin with perfect hashing and then make JOIN with it.

Another place for optimization is shrink to fit memory buffers in joined blocks #10423 and use compressed blocks with decompression on demand and decompressed blocks cache.

**Comment by alexey-milovidov** [comment] 2021-06-22 20:45
I don't see how perfect hashing can be applied.

**Comment by alexey-milovidov** [comment] 2021-06-22 20:46
Duplicate of #21047.

**Closed by alexey-milovidov** 2021-06-22 20:46 UTC
Labels: comp-joins, memory, usability
