### ISSUE TITLE
Test `test_distributed_queries_stress/test.py::test_stress_distributed` is flaky

### ISSUE THREAD

**Issue by nickitat** [ClickHouse/ClickHouse#43811] opened 2022-11-29 17:20 UTC
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIyLTExLTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJXRlc3Rfc3RyZXNzX2Rpc3RyaWJ1dGVkJScgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj

**Comment by tavplubix** [comment] 2022-11-29 18:39
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/41776

**Closed by tavplubix** 2022-11-29 18:39 UTC
Labels: flaky test
