### ISSUE TITLE
Integration test `test_executable_input_slow_python` is flaky

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#67462] opened 2024-07-30 13:57 UTC
https://s3.amazonaws.com/clickhouse-test-reports/0/4f67fbd127413e44b35b0f63870dbd685eeac1df/integration_tests__release__[1_4].html

https://s3.amazonaws.com/clickhouse-test-reports/0/da81588d424efd6de9d8c4dd8395df1f887f1a74/integration_tests__aarch64__[3_6].html

https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBsaWtlICcldGVzdF9leGVjdXRhYmxlX2lucHV0X3Nsb3dfcHl0aG9uJScKICAgIEFORCBjaGVja19zdGFydF90aW1lID4gbm93KCkgLSBpbnRlcnZhbCA2IG1vbnRoCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l

**Comment by nickitat** [comment] 2024-07-30 15:52
duplicate of #67002

**Closed** 2024-07-30 15:52 UTC
Labels: testing, flaky test
