### ISSUE TITLE
SSL Exception during handshake in 20.1.2.4

### ISSUE THREAD

**Issue by kung-foo** [ClickHouse/ClickHouse#8886] opened 2020-01-28 21:24 UTC
**Describe the bug or unexpected behaviour**
After upgrading to 20.1.2.4, access to the HTTP interface via TLS fails after about an hour.

**How to reproduce**
* Install 20.1.2.4
* `watch curl -sk https://localhost:8443`

After a while (about an hour on an unloaded box), TLS handshakes will begin to fail.

**Error message and/or stacktrace**
```
2020.01.28 21:10:26.583446 [ 42 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = SSL Exception: error:2400006E:random number generator::error retrieving entropy0. 0xbc3a63c Poco::IOException::IOException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x9ba0579 Poco::Net::NetException::NetException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x9d18dd9 Poco::Net::SSLException::SSLException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
3. 0x9d1f698 Poco::Net::SecureSocketImpl::handleError(int)  in /usr/bin/clickhouse
4. 0x9d1fc43 Poco::Net::SecureSocketImpl::completeHandshake()  in /usr/bin/clickhouse
5. 0x9d201a0 Poco::Net::SecureSocketImpl::receiveBytes(void*, int, int)  in /usr/bin/clickhouse
6. 0x9b93664 Poco::Net::HTTPSession::receive(char*, int)  in /usr/bin/clickhouse
7. 0x9b936cb Poco::Net::HTTPSession::get()  in /usr/bin/clickhouse
8. 0x9b8d602 Poco::Net::HTTPHeaderStreamBuf::readFromDevice(char*, long)  in /usr/bin/clickhouse
9. 0x9b8d4b8 Poco::BasicBufferedStreamBuf<char, std::__1::char_traits<char>, Poco::Net::HTTPBufferAllocator>::underflow()  in /usr/bin/clickhouse
10. 0xc64d03a std::__1::basic_streambuf<char, std::__1::char_traits<char> >::uflow()  in /usr/bin/clickhouse
11. 0xc654226 std::__1::basic_istream<char, std::__1::char_traits<char> >::get()  in /usr/bin/clickhouse
12. 0x9b8fee3 Poco::Net::HTTPRequest::read(std::__1::basic_istream<char, std::__1::char_traits<char> >&)  in /usr/bin/clickhouse
13. 0x9b92b21 Poco::Net::HTTPServerRequestImpl::HTTPServerRequestImpl(Poco::Net::HTTPServerResponseImpl&, Poco::Net::HTTPServerSession&, Poco::Net::HTTPServerParams*)  in /usr/bin/clickhouse
14. 0x9bb8cc1 Poco::Net::HTTPServerConnection::run()  in /usr/bin/clickhouse
15. 0x9bb5677 Poco::Net::TCPServerConnection::start()  in /usr/bin/clickhouse
16. 0x9bb5a6d Poco::Net::TCPServerDispatcher::run()  in /usr/bin/clickhouse
17. 0xbca44ff Poco::PooledThread::run()  in /usr/bin/clickhouse
18. 0xbca15c8 Poco::ThreadImpl::runnableEntry(void*)  in /usr/bin/clickhouse
19. 0xbca2e69 ?  in /usr/bin/clickhouse
```

**Additional context**
```
$ clickhouse-server -V
ClickHouse server version 20.1.2.4 (official build).
$ uname -a
Linux clickhouse-demo2 5.0.0-1028-azure #30~18.04.1-Ubuntu SMP Fri Dec 6 11:47:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

Previous we had been running 18.10.3, then a short period (with no issue) at 19.17.6.36, before upgrading to 20.1.2.4.

**Comment by filimonov** [comment] 2020-01-28 21:36
#8573

**Comment by filimonov** [comment] 2020-02-24 11:53
Some progress and discussions in https://github.com/ClickHouse/ClickHouse/pull/8956

**Comment by alexey-milovidov** [comment] 2020-02-25 10:56
I cannot reproduce with
`for i in {1..10000}; do curl -k https://localhost:8443; done`

**Comment by alexey-milovidov** [comment] 2020-02-25 11:07
Will try on VM...

**Comment by alexey-milovidov** [comment] 2020-02-25 11:21
Will wait for an hour...

**Comment by alexey-milovidov** [comment] 2020-02-25 18:25
It has reproduced on version 20.1.4:

```
for i in {1..1000000}; do echo -n "$i " && curl -k https://localhost:8443; done
```

```
...
173929 Ok.
173930 curl: (56) OpenSSL SSL_read: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error, errno 0
173931 curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
...
```

**Comment by alexey-milovidov** [comment] 2020-02-25 21:52
It is also reproduced with the version from #8956 
What is interesting is that at the time when issue started to reproduce, ssh connection is reset.

**Comment by alexey-milovidov** [comment] 2020-02-26 18:15
Found the issue, will fix.

**Comment by alexey-milovidov** [comment] 2020-02-27 12:08
The issue is fixed in https://github.com/ClickHouse/ClickHouse/pull/8956

**Closed** 2020-03-03 02:54 UTC
Labels: bug, comp-net, v20.1
