### ISSUE TITLE
undesired information in system.errors

### ISSUE THREAD

**Issue by vkrot-innio** [ClickHouse/ClickHouse#53268] opened 2023-08-10 09:34 UTC
**Describe what's wrong**
Potentially a bug, not sure 100%
`system.errors` contains errors which are not reported to logs and i don't get during query execution. 

Here is the error from `system.errors`:
```
SELECT
    name,
    code,
    value,
    last_error_message,
    arrayStringConcat(arrayMap(x -> demangle(addressToSymbol(x)), last_error_trace), '\n') AS trace
FROM system.errors
ORDER BY value DESC
LIMIT 1
SETTINGS allow_introspection_functions = 1
FORMAT Vertical

Query id: cedea01d-3e11-47d5-abc9-ed7c5960cb5e

Row 1:
──────
name:               UNKNOWN_IDENTIFIER
code:               47
value:              1318585
last_error_message: Missing columns: 'data_time' 'remaining.data_time' 'remaining.device_id' 'data_item_id' 'device_id' 'remaining.data_item_id' while processing query: '(remaining.device_id = device_id) AND (remaining.data_item_id = data_item_id) AND (toStartOfMonth(remaining.data_time) = toStartOfMonth(data_time))', required columns: 'remaining.data_item_id' 'device_id' 'data_item_id' 'remaining.device_id' 'remaining.data_time' 'data_time' 'remaining.data_item_id' 'device_id' 'data_item_id' 'remaining.device_id' 'remaining.data_time' 'data_time'
trace:              DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool)

DB::TreeRewriterResult::collectUsedColumns(std::__1::shared_ptr<DB::IAST> const&, bool, bool)
DB::TreeRewriter::analyze(std::__1::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::IStorage const>, std::__1::shared_ptr<DB::StorageSnapshot> const&, bool, bool, bool, bool) const
DB::evaluateConstantExpression(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const> const&)
DB::TreeRewriter::analyzeSelect(std::__1::shared_ptr<DB::IAST>&, DB::TreeRewriterResult&&, DB::SelectQueryOptions const&, std::__1::vector<DB::TableWithColumnNamesAndTypes, std::__1::allocator<DB::TableWithColumnNamesAndTypes>> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::TableJoin>, bool, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>) const

DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>)
DB::buildPushingToViewsChain(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ThreadStatusesHolder>, std::__1::atomic<unsigned long>*, DB::Block const&)
DB::InterpreterInsertQuery::buildChainImpl(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&, std::__1::shared_ptr<DB::ThreadStatusesHolder>, std::__1::atomic<unsigned long>*)
DB::InterpreterInsertQuery::buildChain(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::ThreadStatusesHolder>, std::__1::atomic<unsigned long>*)
DB::buildPushingToViewsChain(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ThreadStatusesHolder>, std::__1::atomic<unsigned long>*, DB::Block const&)
DB::InterpreterInsertQuery::buildChainImpl(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&, std::__1::shared_ptr<DB::ThreadStatusesHolder>, std::__1::atomic<unsigned long>*)
DB::InterpreterInsertQuery::execute()

DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (DB::QueryResultDetails const&)>, std::__1::optional<DB::FormatSettings> const&)
DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&)
DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&)
DB::HTTPServerConnection::run()
Poco::Net::TCPServerConnection::start()
Poco::Net::TCPServerDispatcher::run()
Poco::PooledThread::run()
Poco::ThreadImpl::runnableEntry(void*)

__clone
```
I cannot find any related information in `clickhouse-server.err.log`. 

This error could potentially happen on materialized views update, here is table and mat views:
```
CREATE DATABASE IF NOT EXISTS myplant;

CREATE TABLE IF NOT EXISTS myplant.ts_data_double_raw 
(
    `device_id` UInt32 NOT NULL CODEC(ZSTD),
    `data_item_id` UInt32 NOT NULL CODEC(ZSTD),
    `data_time` DateTime64(3, 'UTC') NOT NULL CODEC(Delta, ZSTD),
    `data_value` Float64 NOT NULL CODEC(Delta, ZSTD),
    `is_deleted` Bool CODEC(ZSTD),
    `ingestion_time` DateTime64(3, 'UTC') NOT NULL CODEC(Delta, ZSTD)
    )
    ENGINE = ReplacingMergeTree()
    PARTITION BY toYYYYMM(data_time)
    ORDER BY (device_id, data_item_id, data_time)
    SETTINGS index_granularity = 8192;

-- null table used just for materialized views. mat view triggered by insert to this table
-- can join ts_data_double table
CREATE TABLE IF NOT EXISTS myplant.null_ts_data_double 
(
    `device_id` UInt32 NOT NULL,
    `data_item_id` UInt32 NOT NULL,
    `data_time` DateTime64(3, 'UTC') NOT NULL,
    `data_value` Float64 NOT NULL,
    `is_deleted` Bool,
    `ingestion_time` DateTime64(3, 'UTC') NOT NULL,
    )
    ENGINE = Null;

CREATE TABLE myplant.idx_ts_data_double_daily (
    `device_id` UInt32 NOT NULL CODEC(ZSTD),
    `data_item_id` UInt32 NOT NULL CODEC(ZSTD),
    `data_time` Date CODEC(ZSTD),
    `has_data` Bool CODEC(ZSTD)
    )
    ENGINE = ReplacingMergeTree()
    PARTITION BY tuple()
    ORDER BY (device_id, data_item_id, data_time);

CREATE MATERIALIZED VIEW myplant.idx_ts_data_double_daily_positive_mv 
            TO myplant.idx_ts_data_double_daily
AS SELECT
              device_id,
              data_item_id,
              toDate(toStartOfDay(data_time)) data_time,
              true as has_data
   FROM myplant.ts_data_double_raw
   WHERE is_deleted = 0
;

-- insert deleted row - first pipe to null
CREATE MATERIALIZED VIEW myplant.idx_ts_data_double_montly_negative_to_null 
            TO myplant.null_ts_data_double AS
SELECT
    *
FROM myplant.ts_data_double_raw
WHERE is_deleted = 1;


CREATE MATERIALIZED VIEW myplant.idx_ts_data_double_daily_negative
            TO myplant.idx_ts_data_double_daily
AS SELECT
              device_id,
              data_item_id,
              toDate(toStartOfDay(data_time)) data_time,
              if(max(remaining.device_id) > 0, true, false) as has_data
   FROM myplant.null_ts_data_double
              LEFT ANY JOIN (
     select device_id, data_item_id, toDate(toStartOfDay(data_time)) data_time from myplant.ts_data_double_raw FINAL
        where (device_id, data_item_id, toStartOfDay(data_time)) in (
            select device_id, data_item_id, toStartOfDay(data_time) from myplant.null_ts_data_double
        ) and is_deleted = 0
   ) remaining on remaining.device_id = null_ts_data_double.device_id
              and remaining.data_item_id = null_ts_data_double.data_item_id
              and toStartOfDay(remaining.data_time) = toStartOfDay(null_ts_data_double.data_time)
   WHERE null_ts_data_double.is_deleted = 1
   GROUP BY device_id, data_item_id, data_time
;
```

But i actually see that these views work as expected, data in target table is updated. Insert queries do not throw any errors. Error log file doesn't show any errors as well. 

Counter in system.errors is constantly growing (with each insert). 
Is it really an error and something doesn't work as i expect or is it more information? If that is info - it should not reported in `system.errrors`

**Does it reproduce on recent release?**
Yes, verified on `23.7.4.5`

**How to reproduce**
Create schema given above.
Run inserts:
```
insert into myplant.ts_data_double_raw values (1,1, now(), 1, false, now());
insert into myplant.ts_data_double_raw values (1,1, now(), 1, true, now());
```
Check `value` column in `system.errors` - it's growing with every insert.
Errors log is empty, inserts do not fail, target mat view table `myplant.idx_ts_data_double_daily` gets updated correctly.

* Which ClickHouse server version to use
`23.7.4.5`
 
**Expected behavior**
Not see this error in `system.errors`

**Comment by tavplubix** [comment] 2023-08-10 11:35
Looks like a duplicate of https://github.com/ClickHouse/ClickHouse/issues/51487

**Closed by tavplubix** 2023-08-10 11:35 UTC
Labels: potential bug
