### ISSUE TITLE
Crash in MergeTreeRangeReader

### ISSUE THREAD

**Issue by 4ertus2** [ClickHouse/ClickHouse#9064] opened 2020-02-10 14:08 UTC
```
2020.02.10 16:08:10.340353 [ 70 ] {} <Fatal> BaseDaemon: ########################################
2020.02.10 16:08:10.340480 [ 70 ] {} <Fatal> BaseDaemon: (version 20.1.3.7 (official build)) (from thread 60) (query_id: e3ad3aef-c6fb-4f93-aafc-9ac8182f7cc1) Received signal Segmentation fault (11).
2020.02.10 16:08:10.340559 [ 70 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2020.02.10 16:08:10.340604 [ 70 ] {} <Fatal> BaseDaemon: Stack trace: 0x8e5378e 0x97a27f5 0x97a5f3f 0x97684c6 0x9769cc3 0x91a4c87 0x91d6e84 0x91d70a3 0x8a6d24f 0x94a6871 0x8a6d24f 0x949c1c8 0x8a6d24f 0x94e9580 0x94e9b05 0x4fa3a77 0x4fa202f 0x7f80b7a84fa3 0x7f80b79a64cf
2020.02.10 16:08:10.434034 [ 70 ] {} <Fatal> BaseDaemon: 3. 0x8e5378e DB::ColumnVector<long>::filter(DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, long) const  in /usr/bin/clickhouse
2020.02.10 16:08:10.434106 [ 70 ] {} <Fatal> BaseDaemon: 4. 0x97a27f5 DB::MergeTreeRangeReader::filterColumns(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&, DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const  in /usr/bin/clickhouse
2020.02.10 16:08:10.620361 [ 70 ] {} <Fatal> BaseDaemon: 5. 0x97a5f3f DB::MergeTreeRangeReader::read(unsigned long, std::__1::vector<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&)  in /usr/bin/clickhouse
2020.02.10 16:08:10.620406 [ 70 ] {} <Fatal> BaseDaemon: 6. 0x97684c6 DB::MergeTreeBaseSelectProcessor::readFromPartImpl()  in /usr/bin/clickhouse
2020.02.10 16:08:10.620426 [ 70 ] {} <Fatal> BaseDaemon: 7. 0x9769cc3 DB::MergeTreeBaseSelectProcessor::generate()  in /usr/bin/clickhouse
2020.02.10 16:08:10.620452 [ 70 ] {} <Fatal> BaseDaemon: 8. 0x91a4c87 DB::ISource::work()  in /usr/bin/clickhouse
2020.02.10 16:08:10.751008 [ 70 ] {} <Fatal> BaseDaemon: 9. 0x91d6e84 DB::TreeExecutorBlockInputStream::execute()  in /usr/bin/clickhouse
2020.02.10 16:08:10.751049 [ 70 ] {} <Fatal> BaseDaemon: 10. 0x91d70a3 DB::TreeExecutorBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.10 16:08:10.839856 [ 70 ] {} <Fatal> BaseDaemon: 11. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.10 16:08:10.982566 [ 70 ] {} <Fatal> BaseDaemon: 12. 0x94a6871 DB::FilterBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.10 16:08:10.982608 [ 70 ] {} <Fatal> BaseDaemon: 13. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.10 16:08:10.982628 [ 70 ] {} <Fatal> BaseDaemon: 14. 0x949c1c8 DB::ExpressionBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.10 16:08:10.982647 [ 70 ] {} <Fatal> BaseDaemon: 15. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.10 16:08:10.982676 [ 70 ] {} <Fatal> BaseDaemon: 16. 0x94e9580 DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)  in /usr/bin/clickhouse
2020.02.10 16:08:10.982727 [ 70 ] {} <Fatal> BaseDaemon: 17. 0x94e9b05 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::'lambda'()::operator()() const  in /usr/bin/clickhouse
2020.02.10 16:08:11.105574 [ 70 ] {} <Fatal> BaseDaemon: 18. 0x4fa3a77 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhouse
2020.02.10 16:08:11.172058 [ 70 ] {} <Fatal> BaseDaemon: 19. 0x4fa202f ?  in /usr/bin/clickhouse
2020.02.10 16:08:11.172139 [ 70 ] {} <Fatal> BaseDaemon: 20. 0x7fa3 start_thread  in /lib/x86_64-linux-gnu/libpthread-2.28.so
2020.02.10 16:08:11.172176 [ 70 ] {} <Fatal> BaseDaemon: 21. 0xf94cf __clone  in /lib/x86_64-linux-gnu/libc-2.28.so
```

Schema
```
CREATE TABLE yad_auto.yad_stats_b (`date` Date, `client` String, `cid` Int64, `bid` Int64, `gid` Int64, `type` UInt8, `device` UInt8, `slot` UInt8, `shows` Int32, `clicks` Int32, `sum` Float64, `trans` Float64, `trans_mcf` Int32, `val` Float64, `marg` Float64, `calls` Int32, `bcalls` Int32, `goal1` Int32, `goal2` Int32, `goal3` Int32, `goal4` Int32, `goal5` Int32, `goal6` Int32, `goal7` Int32, `goal8` Int32, `goal9` Int32, `goal10` Int32, `goal11` Int32, `goal12` Int32, `goal13` Int32, `goal14` Int32, `goal15` Int32, `goal16` Int32, `goal17` Int32, `goal18` Int32, `goal19` Int32, `goal20` Int32, `newUsers` Int32, `bounces` Int32, `sessions` Int32, `timeOnPage` Int32, `pageviews` Int32, `exits` Int32, `pageDepthOnSession` Int32, `avg_show_pos` Float64, `avg_click_pos` Float64, `clicks_avr` Int32, `shows_avr` Int32, `val_mcf` Float64 DEFAULT 0.) ENGINE = ReplicatedSummingMergeTree('/clickhouse_perftest/tables/{shard}/yad_stats_b', '{replica}', date, (client, cid, bid, gid, device, date, type, slot), 8192)
```

Affected query
```
SELECT
date,
client,
 
SUM(shows) AS sshows,
SUM(clicks) AS clicks,
SUM(sum) AS sum,
 
SUM(trans) AS trans,
SUM(val) AS val,
SUM(marg) AS marg,
SUM(trans_mcf) AS trans_mcf,
SUM(val_mcf) AS val_mcf,
 
SUM(calls) AS calls,
SUM(bcalls) AS bcalls,
 
SUM(goal1) AS goal1,
SUM(goal2) AS goal2,
SUM(goal3) AS goal3,
SUM(goal4) AS goal4,
SUM(goal5) AS goal5,
SUM(goal6) AS goal6,
SUM(goal7) AS goal7,
SUM(goal8) AS goal8,
SUM(goal9) AS goal9,
SUM(goal10) AS goal10,
SUM(goal11) AS goal11,
SUM(goal12) AS goal12,
SUM(goal13) AS goal13,
SUM(goal14) AS goal14,
SUM(goal15) AS goal15,
SUM(goal16) AS goal16,
SUM(goal17) AS goal17,
SUM(goal18) AS goal18,
SUM(goal19) AS goal19,
SUM(goal20) AS goal20,
 
SUM(newUsers) AS newUsers,
SUM(bounces) AS bounces,
SUM(sessions) AS sessions,
SUM(timeOnPage) AS timeOnPage,
SUM(pageviews) AS pageviews,
SUM(exits) AS exits,
 
SUM(avg_click_pos) AS avg_click_pos,
SUM(avg_show_pos) AS avg_show_pos,
SUM(shows_avr) AS shows_pos,
SUM(clicks_avr) AS clicks_pos,
 
sumIf(shows, slot=0) as shows_premium,
sumIf(shows, slot=1) as shows_other
FROM `yad_stats_b`
WHERE ( (client='pro-vseinstrumenti' and cid !=0 ) ) and (date BETWEEN '2019-01-01' AND '2020-06-02') and (cid+bid > 0)
GROUP BY date, client
ORDER BY date asc
```

Query is OK if replace `cid !=0` with `cid> 0`

**Comment by akuzm** [comment] 2020-02-10 14:28
Looks like a duplicate of #8997

**Comment by grootman2007** [comment] 2020-02-10 14:47
crashes even with this query:
SELECT
    date,
    client,
    
  SUM(shows) AS sshows,
  SUM(clicks) AS clicks,
  SUM(sum) AS sum,

  SUM(trans) AS trans,
  SUM(val) AS val,
  SUM(marg) AS marg,
  SUM(trans_mcf) AS trans_mcf,
  SUM(val_mcf) AS val_mcf

   FROM yad_auto.`yad_stats_b`
   WHERE ( (client='pro-vseinstrumenti'  and cid !=0  ) ) and (date BETWEEN '2019-06-01' AND '2019-06-01') 
  GROUP BY date, client

**Comment by CurtizJ** [comment] 2020-02-10 16:53
I'm not sure, that it's the same issue. please, can you try to reproduce on 20.1.4?

**Comment by grootman2007** [comment] 2020-02-13 10:50
@CurtizJ I tried version 20.1.2.4 (cause could not find 20.1.4) - it has the same problem:


<pre><code>

 2020.02.13 13:38:04.612055 [ 106 ] {} <Fatal> BaseDaemon: ########################################
2020.02.13 13:38:04.612147 [ 106 ] {} <Fatal> BaseDaemon: (version 20.1.2.4 (official build)) (from thread 55) (query_id: f448f6d0-8639-4748-a1b2-3e534482dbe7) Received signal Segmentation fault (11).
2020.02.13 13:38:04.612188 [ 106 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2020.02.13 13:38:04.612215 [ 106 ] {} <Fatal> BaseDaemon: Stack trace: 0x8e537ce 0x97a2495 0x97a5bdf 0x9768166 0x9769963 0x91a4c27 0x91d6e24 0x91d7043 0x8a6d32f 0x94a6811 0x8a6d32f 0x949c168 0x8a6d32f 0x94e9520 0x94e9aa5 0x4fa3b77 0x4fa212f 0x7f3c7905cfa3 0x7f3c78f7e4cf
2020.02.13 13:38:04.661587 [ 106 ] {} <Fatal> BaseDaemon: 3. 0x8e537ce DB::ColumnVector<long>::filter(DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, long) const  in /usr/bin/clickhouse
2020.02.13 13:38:04.661649 [ 106 ] {} <Fatal> BaseDaemon: 4. 0x97a2495 DB::MergeTreeRangeReader::filterColumns(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&, DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const  in /usr/bin/clickhouse
2020.02.13 13:38:04.661710 [ 106 ] {} <Fatal> BaseDaemon: 5. 0x97a5bdf DB::MergeTreeRangeReader::read(unsigned long, std::__1::vector<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&)  in /usr/bin/clickhouse
2020.02.13 13:38:04.661733 [ 106 ] {} <Fatal> BaseDaemon: 6. 0x9768166 DB::MergeTreeBaseSelectProcessor::readFromPartImpl()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661753 [ 106 ] {} <Fatal> BaseDaemon: 7. 0x9769963 DB::MergeTreeBaseSelectProcessor::generate()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661778 [ 106 ] {} <Fatal> BaseDaemon: 8. 0x91a4c27 DB::ISource::work()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661802 [ 106 ] {} <Fatal> BaseDaemon: 9. 0x91d6e24 DB::TreeExecutorBlockInputStream::execute()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661820 [ 106 ] {} <Fatal> BaseDaemon: 10. 0x91d7043 DB::TreeExecutorBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661853 [ 106 ] {} <Fatal> BaseDaemon: 11. 0x8a6d32f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661880 [ 106 ] {} <Fatal> BaseDaemon: 12. 0x94a6811 DB::FilterBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661899 [ 106 ] {} <Fatal> BaseDaemon: 13. 0x8a6d32f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661917 [ 106 ] {} <Fatal> BaseDaemon: 14. 0x949c168 DB::ExpressionBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661934 [ 106 ] {} <Fatal> BaseDaemon: 15. 0x8a6d32f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.13 13:38:04.661956 [ 106 ] {} <Fatal> BaseDaemon: 16. 0x94e9520 DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)  in /usr/bin/clickhouse
2020.02.13 13:38:04.661998 [ 106 ] {} <Fatal> BaseDaemon: 17. 0x94e9aa5 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::'lambda'()::operator()() const  in /usr/bin/clickhouse
2020.02.13 13:38:04.662038 [ 106 ] {} <Fatal> BaseDaemon: 18. 0x4fa3b77 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhouse
2020.02.13 13:38:04.662057 [ 106 ] {} <Fatal> BaseDaemon: 19. 0x4fa212f ?  in /usr/bin/clickhouse
2020.02.13 13:38:04.662077 [ 106 ] {} <Fatal> BaseDaemon: 20. 0x7fa3 start_thread  in /lib/x86_64-linux-gnu/libpthread-2.28.so
2020.02.13 13:38:04.662100 [ 106 ] {} <Fatal> BaseDaemon: 21. 0xf94cf clone  in /lib/x86_64-linux-gnu/libc-2.28.so
</code></pre>

**Comment by CurtizJ** [comment] 2020-02-13 11:28
Here you can find version 20.1.4.14
https://repo.yandex.ru/clickhouse/deb/stable/main/

**Comment by grootman2007** [comment] 2020-02-13 11:36
@CurtizJ same output with 20.1.4.14:

<code><pre>
2020.02.13 14:33:48.410856 [ 126 ] {} <Fatal> BaseDaemon: ########################################
2020.02.13 14:33:48.472786 [ 126 ] {} <Fatal> BaseDaemon: (version 20.1.4.14 (official build)) (from thread 100) (query_id: 622a74cc-6bd6-40cf-85bb-446c6eef5db9) Received signal Segmentation fault (11).
2020.02.13 14:33:48.472851 [ 126 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2020.02.13 14:33:48.472881 [ 126 ] {} <Fatal> BaseDaemon: Stack trace: 0x8e55ede 0x97a6605 0x97a9d7f 0x976c2d6 0x976dad3 0x91a7ef7 0x91da0f4 0x91da313 0x8a6f42f 0x94a9a11 0x8a6f42f 0x949f368 0x8a6f42f 0x94ec720 0x94ecca5 0x4fa4fd7 0x4fa358f 0x7f7366c0cfa3 0x7f7366b2e4cf
2020.02.13 14:33:49.488277 [ 127 ] {} <Fatal> BaseDaemon: ########################################
2020.02.13 14:33:49.488387 [ 127 ] {} <Fatal> BaseDaemon: (version 20.1.4.14 (official build)) (from thread 68) (query_id: 622a74cc-6bd6-40cf-85bb-446c6eef5db9) Received signal Segmentation fault (11).
2020.02.13 14:33:49.488461 [ 127 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2020.02.13 14:33:49.488484 [ 127 ] {} <Fatal> BaseDaemon: Stack trace: 0x8e55ede 0x97a6605 0x97a9d7f 0x976c2d6 0x976dad3 0x91a7ef7 0x91da0f4 0x91da313 0x8a6f42f 0x94a9a11 0x8a6f42f 0x949f368 0x8a6f42f 0x94ec720 0x94ecca5 0x4fa4fd7 0x4fa358f 0x7f7366c0cfa3 0x7f7366b2e4cf
2020.02.13 14:33:51.231817 [ 126 ] {} <Fatal> BaseDaemon: 3. 0x8e55ede DB::ColumnVector<long>::filter(DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, long) const  in /usr/bin/clickhouse
2020.02.13 14:33:51.231817 [ 127 ] {} <Fatal> BaseDaemon: 3. 0x8e55ede DB::ColumnVector<long>::filter(DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, long) const  in /usr/bin/clickhouse
2020.02.13 14:33:51.231878 [ 126 ] {} <Fatal> BaseDaemon: 4. 0x97a6605 DB::MergeTreeRangeReader::filterColumns(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&, DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const  in /usr/bin/clickhouse
2020.02.13 14:33:51.231885 [ 127 ] {} <Fatal> BaseDaemon: 4. 0x97a6605 DB::MergeTreeRangeReader::filterColumns(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&, DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> const&) const  in /usr/bin/clickhouse
2020.02.13 14:33:51.268662 [ 126 ] {} <Fatal> BaseDaemon: 5. 0x97a9d7f DB::MergeTreeRangeReader::read(unsigned long, std::__1::vector<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&)  in /usr/bin/clickhouse
2020.02.13 14:33:51.268685 [ 127 ] {} <Fatal> BaseDaemon: 5. 0x97a9d7f DB::MergeTreeRangeReader::read(unsigned long, std::__1::vector<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&)  in /usr/bin/clickhouse
2020.02.13 14:33:51.268694 [ 126 ] {} <Fatal> BaseDaemon: 6. 0x976c2d6 DB::MergeTreeBaseSelectProcessor::readFromPartImpl()  in /usr/bin/clickhouse
2020.02.13 14:33:51.268734 [ 127 ] {} <Fatal> BaseDaemon: 6. 0x976c2d6 DB::MergeTreeBaseSelectProcessor::readFromPartImpl()  in /usr/bin/clickhouse
2020.02.13 14:33:51.268749 [ 126 ] {} <Fatal> BaseDaemon: 7. 0x976dad3 DB::MergeTreeBaseSelectProcessor::generate()  in /usr/bin/clickhouse
2020.02.13 14:33:51.268750 [ 127 ] {} <Fatal> BaseDaemon: 7. 0x976dad3 DB::MergeTreeBaseSelectProcessor::generate()  in /usr/bin/clickhouse
2020.02.13 14:33:51.398847 [ 127 ] {} <Fatal> BaseDaemon: 8. 0x91a7ef7 DB::ISource::work()  in /usr/bin/clickhouse
2020.02.13 14:33:51.398847 [ 126 ] {} <Fatal> BaseDaemon: 8. 0x91a7ef7 DB::ISource::work()  in /usr/bin/clickhouse
2020.02.13 14:33:51.523972 [ 126 ] {} <Fatal> BaseDaemon: 9. 0x91da0f4 DB::TreeExecutorBlockInputStream::execute()  in /usr/bin/clickhouse
2020.02.13 14:33:51.523973 [ 127 ] {} <Fatal> BaseDaemon: 9. 0x91da0f4 DB::TreeExecutorBlockInputStream::execute()  in /usr/bin/clickhouse
2020.02.13 14:33:51.524006 [ 126 ] {} <Fatal> BaseDaemon: 10. 0x91da313 DB::TreeExecutorBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.13 14:33:51.524021 [ 127 ] {} <Fatal> BaseDaemon: 10. 0x91da313 DB::TreeExecutorBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.13 14:33:51.587953 [ 126 ] {} <Fatal> BaseDaemon: 11. 0x8a6f42f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.13 14:33:51.587964 [ 127 ] {} <Fatal> BaseDaemon: 11. 0x8a6f42f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.13 14:33:51.697405 [ 126 ] {} <Fatal> BaseDaemon: 12. 0x94a9a11 DB::FilterBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.13 14:33:51.697429 [ 127 ] {} <Fatal> BaseDaemon: 12. 0x94a9a11 DB::FilterBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.13 14:33:51.697437 [ 126 ] {} <Fatal> BaseDaemon: 13. 0x8a6f42f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.13 14:33:51.697479 [ 127 ] {} <Fatal> BaseDaemon: 13. 0x8a6f42f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.13 14:33:51.697495 [ 126 ] {} <Fatal> BaseDaemon: 14. 0x949f368 DB::ExpressionBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.13 14:33:51.697495 [ 127 ] {} <Fatal> BaseDaemon: 14. 0x949f368 DB::ExpressionBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.02.13 14:33:51.697520 [ 126 ] {} <Fatal> BaseDaemon: 15. 0x8a6f42f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.13 14:33:51.697529 [ 127 ] {} <Fatal> BaseDaemon: 15. 0x8a6f42f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.02.13 14:33:51.697542 [ 126 ] {} <Fatal> BaseDaemon: 16. 0x94ec720 DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)  in /usr/bin/clickhouse
2020.02.13 14:33:51.697549 [ 127 ] {} <Fatal> BaseDaemon: 16. 0x94ec720 DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)  in /usr/bin/clickhouse
2020.02.13 14:33:51.697592 [ 126 ] {} <Fatal> BaseDaemon: 17. 0x94ecca5 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::'lambda'()::operator()() const  in /usr/bin/clickhouse
2020.02.13 14:33:51.697598 [ 127 ] {} <Fatal> BaseDaemon: 17. 0x94ecca5 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::'lambda'()::operator()() const  in /usr/bin/clickhouse
2020.02.13 14:33:51.837077 [ 126 ] {} <Fatal> BaseDaemon: 18. 0x4fa4fd7 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhouse
2020.02.13 14:33:51.837077 [ 127 ] {} <Fatal> BaseDaemon: 18. 0x4fa4fd7 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhouse
2020.02.13 14:33:51.837131 [ 126 ] {} <Fatal> BaseDaemon: 19. 0x4fa358f ?  in /usr/bin/clickhouse
2020.02.13 14:33:51.837136 [ 127 ] {} <Fatal> BaseDaemon: 19. 0x4fa358f ?  in /usr/bin/clickhouse
2020.02.13 14:33:51.837155 [ 126 ] {} <Fatal> BaseDaemon: 20. 0x7fa3 start_thread  in /lib/x86_64-linux-gnu/libpthread-2.28.so
2020.02.13 14:33:51.837155 [ 127 ] {} <Fatal> BaseDaemon: 20. 0x7fa3 start_thread  in /lib/x86_64-linux-gnu/libpthread-2.28.so
2020.02.13 14:33:51.837178 [ 126 ] {} <Fatal> BaseDaemon: 21. 0xf94cf __clone  in /lib/x86_64-linux-gnu/libc-2.28.so
2020.02.13 14:33:51.837184 [ 127 ] {} <Fatal> BaseDaemon: 21. 0xf94cf __clone  in /lib/x86_64-linux-gnu/libc-2.28.so
</pre></code>

**Comment by CurtizJ** [comment] 2020-02-13 11:48
Well then, it's a new issue. Thanks.

**Closed** 2020-02-14 14:59 UTC
Labels: bug, crash
