### ISSUE TITLE
Merge table skip missing columns for underlying tables.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#18681] opened 2021-01-01 16:44 UTC
**Use case**
Give the ability for the user to skip missing columns when querying the Merge table engine and some underlying tables have missing columns.
It's possible to populate them with Null values (in case Nullable columns) or default values for certain data type.

Poor man dynamic table structure.

**Describe the solution you'd like**
setting (table engine setting?)

**Describe alternatives you've considered**
Use condition in WHERE with _table virtual column.

**Additional context**
```
CREATE TABLE test_table_1
(
    `key` UInt32,
    `value_1` UInt32,
    `value_2` UInt32
)
ENGINE = MergeTree
PARTITION BY tuple()
ORDER BY key

CREATE TABLE test_table_2
(
    `key` UInt32,
    `value_3` UInt32,
    `value_4` UInt32
)
ENGINE = MergeTree
PARTITION BY tuple()
ORDER BY key

INSERT INTO test_table_1 SELECT
    number,
    rand(),
    rand()
FROM numbers(100)

INSERT INTO test_table_2 SELECT
    number,
    rand(),
    rand()
FROM numbers(100)

CREATE TABLE test_table_2
(
    `key` UInt32,
    `value_1` UInt32,
    `value_2` UInt32,
    `value_3` UInt32,
    `value_4` UInt32
)
ENGINE = Merge(test, test_table)

SELECT *
FROM merge_table

Query id: 982f624d-7b95-4d8c-b1c9-b07f0eb0809f


Received exception from server (version 20.13.1):
Code: 16. DB::Exception: Received from localhost:9000. DB::Exception: There is no column with name `value_3` in table test.test_table_1 (20cd2ece-8b22-4f3d-9d17-a24939b5028f). There are columns: key, value_1, value_2, _part, _part_index, _partition_id, _sample_factor.


SELECT
    key,
    value_1,
    value_2
FROM merge_table
WHERE _table = 'test_table_1'

┌─key─┬────value_1─┬────value_2─┐
│   0 │ 2824904617 │ 2824904617 │
│   1 │ 2636881554 │ 2636881554 │
│   2 │ 2923242285 │ 2923242285 │
│   3 │ 1406688622 │ 1406688622 │
└─────┴────────────┴────────────┘
```

**Comment by den-crane** [comment] 2021-01-01 19:15
https://github.com/ClickHouse/ClickHouse/issues/9684

**Comment by UnamedRus** [comment] 2021-01-01 19:22
I tried to search related issues, but did not succeed in that.
Let's close my issue then?

**Comment by raladev** [comment] 2023-08-28 09:10
Good day, got the same case and 9684 does not help to solve it

Is there any convenient way for now to merge tables with different columns WITHOUT creating new physical table and adding columns to old once?

**Comment by alexey-milovidov** [comment] 2024-09-21 20:07
Duplicate of #64864

**Closed by alexey-milovidov** 2024-09-21 20:07 UTC
Labels: feature
