### ISSUE TITLE
Openssl now work in Rhel 

### ISSUE THREAD

**Issue by lavasser** [ClickHouse/ClickHouse#35747] opened 2022-03-30 09:04 UTC
Hello!

There is RHEL 8, Clickhouse 22.2.2.1
For openssl I generated and signed by the created CA. (method 2 from https://altinity.com/blog/2019/3/5/clickhouse-networking-part-2 )

**CA certificate added to trusted:**
cp ca.crt /etc/pki/ca-trust/anchors
update-ca-etrust extract

**Connection verification via openssl is successful:**
openssl s_client -connect $HOSTNAME:9440 < /dev/null
Verify return code: 0 (ok)

**But connecting via clickhouse-client I get error:**
"The certificate yielded the error: unable to get the issuer certificate" and 
"... unable to verify the first certificate"
(you don't have to strictly follow this form)

**I try to add path to trust store certificates, but not help:**
\<caConfig>/etc/pki/ca-trust/\</caConfig>
\<caConfig>/usr/share/pki/ca-trust-source\</caConfig>

How can I configure openssl on RHEL?
It works fine in Ubuntu.
![image](https://user-images.githubusercontent.com/16194498/160792714-4e09f3b6-7cba-431f-b2d0-e8e74048b4ab.png)

**Comment by alexey-milovidov** [comment] 2022-03-30 10:42
Duplicate of #17803.

**Closed by alexey-milovidov** 2022-03-30 10:42 UTC
Labels: usability

**Comment by lavasser** [comment] 2022-04-15 07:39
The problem was solved by adding a configuration file for clickhouse-client.
I did it according to the instructions:
https://kb.altinity.com/altinity-kb-setup-and-maintenance/ssl-connection-unexpectedly-closed/#clickhouse-client
