### ISSUE TITLE
Flaky `test_backward_compatibility` integration tests

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#56190] opened 2023-11-01 09:59 UTC
`test_backward_compatibility` has a lot of [ERRORs](https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTA5LTAxJyBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2JhY2t3YXJkX2NvbXBhdGliaWxpdHklJyBhbmQgc3RhdHVzIGluICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpCm9yZGVyIGJ5IGNoZWNrX3N0YXJ0X3RpbWUgZGVzYw==) lately.

**Comment by zvonand** [comment] 2023-11-01 10:01
E.g. https://s3.amazonaws.com/clickhouse-test-reports/55841/c97bfbeb92ee0f9b2b8238e607176c0cd37012b7/integration_tests__asan__analyzer__[2_6]/integration_run_parallel0_0.log :
```____________________ ERROR at setup of test_two_level_merge ____________________
[gw4] linux -- Python 3.10.12 /usr/bin/python3

    @pytest.fixture(scope="module")
    def start_cluster():
        try:
>           cluster.start()

test_backward_compatibility/test_aggregate_fixed_key.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
helpers/cluster.py:2663: in start
    run_and_check(images_pull_cmd)
helpers/cluster.py:104: in run_and_check
    res = subprocess.run(
/usr/lib/python3.10/subprocess.py:505: in run
    stdout, stderr = process.communicate(input, timeout=timeout)
/usr/lib/python3.10/subprocess.py:1154: in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
/usr/lib/python3.10/subprocess.py:2021: in _communicate
    ready = selector.select(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selectors.PollSelector object at 0x7f43ff53bbb0>, timeout = 3774

    def select(self, timeout=None):
        # This is shared between poll() and epoll().
        # epoll() has a different signature and handling of timeout parameter.
        if timeout is None:
            timeout = None
        elif timeout <= 0:
            timeout = 0
        else:
            # poll() has a resolution of 1 millisecond, round away from
            # zero to wait *at least* timeout seconds.
            timeout = math.ceil(timeout * 1e3)
        ready = []
        try:
>           fd_event_list = self._selector.poll(timeout)
E           Failed: Timeout >900.0s

/usr/lib/python3.10/selectors.py:416: Failed
---------------------------- Captured stdout setup -----------------------------
Copy common default production configuration from /clickhouse-config. Files: config.xml, users.xml
Copy common default production configuration from /clickhouse-config. Files: config.xml, users.xml
Copy common default production configuration from /clickhouse-config. Files: config.xml, users.xml
---------------------------- Captured stderr setup -----------------------------

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (139930201531968) ~~~~~~~~~~~~~~~~~~~~~
  File "/usr/local/lib/python3.10/dist-packages/execnet/gateway_base.py", line 361, in _perform_spawn
    reply.run()
  File "/usr/local/lib/python3.10/dist-packages/execnet/gateway_base.py", line 296, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/execnet/gateway_base.py", line 1049, in _thread_receiver
    msg = Message.from_io(io)
  File "/usr/local/lib/python3.10/dist-packages/execnet/gateway_base.py", line 507, in from_io
    header = io.read(9)  # type 1, channel 4, payload 4
  File "/usr/local/lib/python3.10/dist-packages/execnet/gateway_base.py", line 474, in read
    data = self._read(numbytes - len(buf))
Traceback (most recent call last):
  File "/ClickHouse/tests/integration/helpers/cluster.py", line 2663, in start
    run_and_check(images_pull_cmd)
  File "/ClickHouse/tests/integration/helpers/cluster.py", line 104, in run_and_check
    res = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2021, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/usr/local/lib/python3.10/dist-packages/pytest_timeout.py", line 264, in handler
    timeout_sigalrm(item, settings)
  File "/usr/local/lib/python3.10/dist-packages/pytest_timeout.py", line 448, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % settings.timeout)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/outcomes.py", line 198, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Timeout >900.0s
```

**Comment by tavplubix** [comment] 2023-11-01 12:21
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/56108

**Closed by tavplubix** 2023-11-01 12:21 UTC
