### ISSUE TITLE
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Expected relative path. (LOGICAL_ERROR)

### ISSUE THREAD

**Issue by shenhaifeng22** [ClickHouse/ClickHouse#42551] opened 2022-10-21 03:09 UTC
hi, an error occurred while I was executing sql

`INSERT INTO ods.ods_ths_balance_sheet_ns select * from s3('http://192.168.137.43:9000/ods/ods_ths_balance_sheet_ns/ods_ths_balance_sheet_ns_*.parquet','Parquet');`

0. ./build_docker/../src/Storages/MergeTree/MergePlainMergeTreeTask.cpp:0: DB::MergePlainMergeTreeTask::executeStep() @ 0x158b1e52 in /usr/bin/clickhouse
11. ./build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:137: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xa3dbabb in /usr/bin/clickhouse
12. ./build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:0: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xa3db4f0 in /usr/bin/clickhouse
13. ./build_docker/../base/base/../base/wide_integer_impl.h:772: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xa4b5716 in /usr/bin/clickhouse
14. ./build_docker/../src/Common/ThreadPool.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xa4b86b7 in /usr/bin/clickhouse
15. ./build_docker/../base/base/../base/wide_integer_impl.h:772: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4b2436 in /usr/bin/clickhouse
16. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:312: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0xa4b6ffd in /usr/bin/clickhouse
17. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
18. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 22.9.1.1555 (official build))
2022.10.21 10:51:00.508914 [ 11814 ] {cbe1ae72-ed0a-4c43-80bb-a1bd7e0334da} <Error> executeQuery: Code: 49. DB::Exception: Expected relative path. (LOGICAL_ERROR) (version 22.9.1.1555 (official build)) (from [::ffff:127.0.0.1]:34046) (in query: INSERT INTO ods.ods_ths_balance_sheet_ns select * from s3('http://192.168.137.43:9000/ods/ods_ths_balance_sheet_ns/ods_ths_balance_sheet_ns_*.parquet','Parquet');), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../src/Common/Exception.cpp:69: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa41119a in /usr/bin/clickhouse
1. ./build_docker/../src/Common/Exception.h:0: DB::DiskObjectStorageMetadata::addObject(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) @ 0x145c1789 in /usr/bin/clickhouse
2. ./build_docker/../src/Disks/ObjectStorages/MetadataStorageFromDisk.cpp:0: DB::MetadataStorageFromDiskTransaction::createMetadataFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) @ 0x145bee2a in /usr/bin/clickhouse
3. ./build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:816: void std::__1::__function::__policy_invoker<void (unsigned long)>::__call_impl<std::__1::__function::__default_alloc_func<DB::DiskObjectStorageTransaction::writeFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, DB::WriteMode, DB::WriteSettings const&, bool)::$_5, void (unsigned long)> >(std::__1::__function::__policy_storage const*, unsigned long) @ 0x1459340a in /usr/bin/clickhouse
4. ./build_docker/../src/IO/WriteBuffer.h:126: DB::WriteBuffer::finalize() @ 0xa418508 in /usr/bin/clickhouse
5. ./build_docker/../contrib/libcxx/include/__tree:184: DB::MergeTreeDataPartWriterWide::finishDataSerialization(bool) @ 0x159906b3 in /usr/bin/clickhouse
6. ./build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp:613: DB::MergeTreeDataPartWriterWide::finish(bool) @ 0x1599079f in /usr/bin/clickhouse
7. ./build_docker/../src/Storages/MergeTree/MergedBlockOutputStream.cpp:0: DB::MergedBlockOutputStream::Finalizer::finish() @ 0x15a71fd7 in /usr/bin/clickhouse
8. ./build_docker/../contrib/libcxx/include/__iterator/wrap_iter.h:100: DB::MergeTreeSink::finishDelayedChunk() @ 0x15a55959 in /usr/bin/clickhouse
9. ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:103: DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) @ 0x15f434d9 in /usr/bin/clickhouse
10. ./build_docker/../contrib/libcxx/include/__functional/function.h:813: DB::ExceptionKeepingTransform::work() @ 0x15f42e5c in /usr/bin/clickhouse
11. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x15d6cb8a in /usr/bin/clickhouse
12. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15d6119b in /usr/bin/clickhouse
13. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x15d63a39 in /usr/bin/clickhouse
14. ./build_docker/../base/base/../base/wide_integer_impl.h:772: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4b2436 in /usr/bin/clickhouse
15. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:312: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0xa4b6ffd in /usr/bin/clickhouse
16. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
17. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so

2022.10.21 10:51:04.029334 [ 11814 ] {cbe1ae72-ed0a-4c43-80bb-a1bd7e0334da} <Error> DiskObjectStorageTransaction: An error occurred while executing transaction's operation #0 (RemoveManyObjectStorageOperation (paths size: 771, keep all batch false, files to keep )): Code: 107. DB::Exception: Metadata path 'store/5c8/5c80b75f-a8bd-4a70-b3a6-3f8b4dfc17ba/delete_tmp_tmp_insert_all_957_957_0/SPECIAL_EXPLAIN.mrk2' doesn't exist. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../src/Common/Exception.cpp:69: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa41119a in /usr/bin/clickhouse
1. ./build_docker/../contrib/libcxx/include/string:1445: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xa42bd18 in /usr/bin/clickhouse
2. ./build_docker/../src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp:176: DB::(anonymous namespace)::RemoveManyObjectStorageOperation::execute(std::__1::shared_ptr<DB::IMetadataTransaction>) @ 0x14592be4 in /usr/bin/clickhouse
3. ./build_docker/../src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp:705: DB::DiskObjectStorageTransaction::commit() @ 0x1458e0fe in /usr/bin/clickhouse
4. ./build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:702: DB::DiskObjectStorage::removeSharedFiles(std::__1::vector<DB::RemoveRequest, std::__1::allocator<DB::RemoveRequest> > const&, bool, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1456f218 in /usr/bin/clickhouse
5. ./build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:816: DB::DataPartStorageOnDisk::clearDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeDataPartChecksums const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, DB::MergeTreeDataPartState, Poco::Logger*, bool) const @ 0x15822f3e in /usr/bin/clickhouse
6. ./build_docker/../src/Storages/MergeTree/DataPartStorageOnDisk.cpp:318: DB::DataPartStorageOnDisk::remove(bool, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeDataPartChecksums const&, std::__1::list<DB::IDataPartStorage::ProjectionChecksums, std::__1::allocator<DB::IDataPartStorage::ProjectionChecksums> >, bool, DB::MergeTreeDataPartState, Poco::Logger*) const @ 0x1581fde1 in /usr/bin/clickhouse
7. ./build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.cpp:1463: DB::IMergeTreeDataPart::remove() const @ 0x1587267c in /usr/bin/clickhouse
8. ./build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.cpp:530: DB::IMergeTreeDataPart::removeIfNeeded() @ 0x15871410 in /usr/bin/clickhouse
9. ./build_docker/../src/Storages/MergeTree/MergeTreeDataPartWide.cpp:168: DB::MergeTreeDataPartWide::~MergeTreeDataPartWide() @ 0x1597bbd3 in /usr/bin/clickhouse
10. ./build_docker/../contrib/libcxx/src/include/atomic_support.h:74: DB::MergeTreeDataWriter::TemporaryPart::~TemporaryPart() @ 0x15a57451 in /usr/bin/clickhouse
11. ./build_docker/../src/Storages/MergeTree/MergeTreeSink.cpp:0: DB::MergeTreeSink::~MergeTreeSink() @ 0x15a552f8 in /usr/bin/clickhouse
12. ./build_docker/../contrib/libcxx/src/include/atomic_support.h:74: DB::QueryPipeline::~QueryPipeline() @ 0x140e7eaf in /usr/bin/clickhouse
13. ./build_docker/../src/QueryPipeline/QueryPipeline.cpp:539: DB::QueryPipeline::reset() @ 0x140ecb10 in /usr/bin/clickhouse
14. ./build_docker/../src/Server/TCPHandler.cpp:434: DB::TCPHandler::runImpl() @ 0x15cfe729 in /usr/bin/clickhouse
15. ./build_docker/../src/Server/TCPHandler.cpp:1881: DB::TCPHandler::run() @ 0x15d11559 in /usr/bin/clickhouse
16. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x18a88f13 in /usr/bin/clickhouse
17. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:54: Poco::Net::TCPServerDispatcher::run() @ 0x18a8a26d in /usr/bin/clickhouse
18. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x18c4c2a9 in /usr/bin/clickhouse
19. ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::ThreadImpl::runnableEntry(void*) @ 0x18c49b62 in /usr/bin/clickhouse
20. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
21. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 22.9.1.1555 (official build))
2022.10.21 10:51:04.029548 [ 11814 ] {cbe1ae72-ed0a-4c43-80bb-a1bd7e0334da} <Error> ods.ods_ths_balance_sheet_ns (5c80b75f-a8bd-4a70-b3a6-3f8b4dfc17ba): Cannot quickly remove directory /var/lib/clickhouse/disks/s3_minio/store/5c8/5c80b75f-a8bd-4a70-b3a6-3f8b4dfc17ba/delete_tmp_tmp_insert_all_957_957_0 by removing files; fallback to recursive removal. Reason: Code: 107. DB::Exception: Metadata path 'store/5c8/5c80b75f-a8bd-4a70-b3a6-3f8b4dfc17ba/delete_tmp_tmp_insert_all_957_957_0/SPECIAL_EXPLAIN.mrk2' doesn't exist. (FILE_DOESNT_EXIST) (version 22.9.1.1555 (official build))
2022.10.21 10:51:04.487422 [ 11814 ] {cbe1ae72-ed0a-4c43-80bb-a1bd7e0334da} <Error> DiskObjectStorageTransaction: An error occurred while executing transaction's operation #0 (RemoveManyObjectStorageOperation (paths size: 771, keep all batch false, files to keep )): Code: 107. DB::Exception: Metadata path 'store/5c8/5c80b75f-a8bd-4a70-b3a6-3f8b4dfc17ba/delete_tmp_tmp_insert_all_948_948_0/TOTAL_HOLDERS_EQUITY.null.mrk2' doesn't exist. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../src/Common/Exception.cpp:69: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa41119a in /usr/bin/clickhouse
1. ./build_docker/../contrib/libcxx/include/string:1445: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xa42bd18 in /usr/bin/clickhouse
2. ./build_docker/../src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp:176: DB::(anonymous namespace)::RemoveManyObjectStorageOperation::execute(std::__1::shared_ptr<DB::IMetadataTransaction>) @ 0x14592be4 in /usr/bin/clickhouse
3. ./build_docker/../src/Disks/ObjectStorages/DiskObjectStorageTransaction.cpp:705: DB::DiskObjectStorageTransaction::commit() @ 0x1458e0fe in /usr/bin/clickhouse
4. ./build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:702: DB::DiskObjectStorage::removeSharedFiles(std::__1::vector<DB::RemoveRequest, std::__1::allocator<DB::RemoveRequest> > const&, bool, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1456f218 in /usr/bin/clickhouse
5. ./build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:816: DB::DataPartStorageOnDisk::clearDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeDataPartChecksums const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, DB::MergeTreeDataPartState, Poco::Logger*, bool) const @ 0x15822f3e in /usr/bin/clickhouse
6. ./build_docker/../src/Storages/MergeTree/DataPartStorageOnDisk.cpp:318: DB::DataPartStorageOnDisk::remove(bool, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeDataPartChecksums const&, std::__1::list<DB::IDataPartStorage::ProjectionChecksums, std::__1::allocator<DB::IDataPartStorage::ProjectionChecksums> >, bool, DB::MergeTreeDataPartState, Poco::Logger*) const @ 0x1581fde1 in /usr/bin/clickhouse
7. ./build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.cpp:1463: DB::IMergeTreeDataPart::remove() const @ 0x1587267c in /usr/bin/clickhouse
8. ./build_docker/../src/Storages/MergeTree/IMergeTreeDataPart.cpp:530: DB::IMergeTreeDataPart::removeIfNeeded() @ 0x15871410 in /usr/bin/clickhouse
9. ./build_docker/../src/Storages/MergeTree/MergeTreeDataPartWide.cpp:168: DB::MergeTreeDataPartWide::~MergeTreeDataPartWide() @ 0x1597bbd3 in /usr/bin/clickhouse
10. ./build_docker/../contrib/libcxx/src/include/atomic_support.h:74: DB::MergeTreeDataWriter::TemporaryPart::~TemporaryPart() @ 0x15a57451 in /usr/bin/clickhouse
11. ./build_docker/../src/Storages/MergeTree/MergeTreeSink.cpp:0: DB::MergeTreeSink::~MergeTreeSink() @ 0x15a552f8 in /usr/bin/clickhouse
12. ./build_docker/../contrib/libcxx/src/include/atomic_support.h:74: DB::QueryPipeline::~QueryPipeline() @ 0x140e7eaf in /usr/bin/clickhouse
13. ./build_docker/../src/QueryPipeline/QueryPipeline.cpp:539: DB::QueryPipeline::reset() @ 0x140ecb10 in /usr/bin/clickhouse
14. ./build_docker/../src/Server/TCPHandler.cpp:434: DB::TCPHandler::runImpl() @ 0x15cfe729 in /usr/bin/clickhouse
15. ./build_docker/../src/Server/TCPHandler.cpp:1881: DB::TCPHandler::run() @ 0x15d11559 in /usr/bin/clickhouse
16. ./build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x18a88f13 in /usr/bin/clickhouse
17. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:54: Poco::Net::TCPServerDispatcher::run() @ 0x18a8a26d in /usr/bin/clickhouse
18. ./build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x18c4c2a9 in /usr/bin/clickhouse
19. ./build_docker/../contrib/poco/Foundation/include/Poco/SharedPtr.h:277: Poco::ThreadImpl::runnableEntry(void*) @ 0x18c49b62 in /usr/bin/clickhouse
20. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
21. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 22.9.1.1555 (official build))
2022.10.21 10:51:04.487644 [ 11814 ] {cbe1ae72-ed0a-4c43-80bb-a1bd7e0334da} <Error> ods.ods_ths_balance_sheet_ns (5c80b75f-a8bd-4a70-b3a6-3f8b4dfc17ba): Cannot quickly remove directory /var/lib/clickhouse/disks/s3_minio/store/5c8/5c80b75f-a8bd-4a70-b3a6-3f8b4dfc17ba/delete_tmp_tmp_insert_all_948_948_0 by removing files; fallback to recursive removal. Reason: Code: 107. DB::Exception: Metadata path 'store/5c8/5c80b75f-a8bd-4a70-b3a6-3f8b4dfc17ba/delete_tmp_tmp_insert_all_948_948_0/TOTAL_HOLDERS_EQUITY.null.mrk2' doesn't exist. (FILE_DOESNT_EXIST) (version 22.9.1.1555 (official build))
2022.10.21 10:51:04.901975 [ 11814 ] {cbe1ae72-ed0a-4c43-80bb-a1bd7e0334da} <Error> TCPHandler: Code: 49. DB::Exception: Expected relative path. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../src/Common/Exception.cpp:69: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa41119a in /usr/bin/clickhouse
1. ./build_docker/../src/Common/Exception.h:0: DB::DiskObjectStorageMetadata::addObject(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) @ 0x145c1789 in /usr/bin/clickhouse
2. ./build_docker/../src/Disks/ObjectStorages/MetadataStorageFromDisk.cpp:0: DB::MetadataStorageFromDiskTransaction::createMetadataFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) @ 0x145bee2a in /usr/bin/clickhouse
3. ./build_docker/../contrib/libcxx/include/__memory/shared_ptr.h:816: void std::__1::__function::__policy_invoker<void (unsigned long)>::__call_impl<std::__1::__function::__default_alloc_func<DB::DiskObjectStorageTransaction::writeFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, DB::WriteMode, DB::WriteSettings const&, bool)::$_5, void (unsigned long)> >(std::__1::__function::__policy_storage const*, unsigned long) @ 0x1459340a in /usr/bin/clickhouse
4. ./build_docker/../src/IO/WriteBuffer.h:126: DB::WriteBuffer::finalize() @ 0xa418508 in /usr/bin/clickhouse
5. ./build_docker/../contrib/libcxx/include/__tree:184: DB::MergeTreeDataPartWriterWide::finishDataSerialization(bool) @ 0x159906b3 in /usr/bin/clickhouse
6. ./build_docker/../src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp:613: DB::MergeTreeDataPartWriterWide::finish(bool) @ 0x1599079f in /usr/bin/clickhouse
7. ./build_docker/../src/Storages/MergeTree/MergedBlockOutputStream.cpp:0: DB::MergedBlockOutputStream::Finalizer::finish() @ 0x15a71fd7 in /usr/bin/clickhouse
8. ./build_docker/../contrib/libcxx/include/__iterator/wrap_iter.h:100: DB::MergeTreeSink::finishDelayedChunk() @ 0x15a55959 in /usr/bin/clickhouse
9. ./build_docker/../src/Processors/Transforms/ExceptionKeepingTransform.cpp:103: DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) @ 0x15f434d9 in /usr/bin/clickhouse
10. ./build_docker/../contrib/libcxx/include/__functional/function.h:813: DB::ExceptionKeepingTransform::work() @ 0x15f42e5c in /usr/bin/clickhouse
11. ./build_docker/../src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x15d6cb8a in /usr/bin/clickhouse
12. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:228: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15d6119b in /usr/bin/clickhouse
13. ./build_docker/../src/Processors/Executors/PipelineExecutor.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::PipelineExecutor::spawnThreads()::$_0>(DB::PipelineExecutor::spawnThreads()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x15d63a39 in /usr/bin/clickhouse
14. ./build_docker/../base/base/../base/wide_integer_impl.h:772: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4b2436 in /usr/bin/clickhouse
15. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:312: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0xa4b6ffd in /usr/bin/clickhouse
16. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
17. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so

**Comment by tavplubix** [comment] 2022-10-21 11:00
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/41246
Fixed in https://github.com/ClickHouse/ClickHouse/pull/41297

**Closed by tavplubix** 2022-10-21 11:00 UTC
Labels: question

**Comment by shenhaifeng22** [comment] 2022-10-24 08:12
@tavplubix   Thank you. The ck version was upgraded from 22.9.1 to 22.9.3. This problem was solved
