### ISSUE TITLE
20.3 Segmentation fault during query with mysql() & GLOBAL JOIN

### ISSUE THREAD

**Issue by millin** [ClickHouse/ClickHouse#11479] opened 2020-06-05 20:11 UTC
**Describe the bug**
When query contains mysql() table function & GLOBAL JOIN segmentation fault may occur.

**How to reproduce**
* ClickHouse server version 20.3.9.70

**Error message and/or stacktrace**
```
2020.06.05 14:50:53.014570 [ 3744 ] {} <Fatal> BaseDaemon: ########################################
2020.06.05 14:50:53.014707 [ 3744 ] {} <Fatal> BaseDaemon: (version 20.3.9.70 (official build)) (from thread 953) (query_id: 160A038829104004) Received signal Segmentation fault (11).
2020.06.05 14:50:53.014771 [ 3744 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2020.06.05 14:50:53.014816 [ 3744 ] {} <Fatal> BaseDaemon: Stack trace: 0x1060397b 0x103f68b5 0x103f8621 0xdb561f9 0xce48ccf 0xdeed484 0xdb9ac1b 0xdeed365 0xdbe264e 0xdbe3e27 0xce48ccf 0xd27448a 0xce48ccf 0xd27448a 0xce48ccf 0xd2e8cbe 0xd2eac67 0xce475ea 0xce878b1 0xd554297 0x8fed706 0x8ff0bc3 0xe37c6f4 0xe3ac69b 0xe3acb1d 0x105c3317 0x105bf11c 0x105c0abd 0x7f793cd326db
2020.06.05 14:50:53.014980 [ 3744 ] {} <Fatal> BaseDaemon: 3. mysql_errno @ 0x1060397b in /usr/bin/clickhouse
2020.06.05 14:50:53.015101 [ 3744 ] {} <Fatal> BaseDaemon: 4. mysqlxx::checkError(st_mysql*) @ 0x103f68b5 in /usr/bin/clickhouse
2020.06.05 14:50:53.015134 [ 3744 ] {} <Fatal> BaseDaemon: 5. mysqlxx::UseQueryResult::fetch() @ 0x103f8621 in /usr/bin/clickhouse
2020.06.05 14:50:53.015206 [ 3744 ] {} <Fatal> BaseDaemon: 6. DB::MySQLBlockInputStream::readImpl() @ 0xdb561f9 in /usr/bin/clickhouse
2020.06.05 14:50:53.015268 [ 3744 ] {} <Fatal> BaseDaemon: 7. DB::IBlockInputStream::read() @ 0xce48ccf in /usr/bin/clickhouse
2020.06.05 14:50:53.015367 [ 3744 ] {} <Fatal> BaseDaemon: 8. DB::SourceFromInputStream::generate() @ 0xdeed484 in /usr/bin/clickhouse
2020.06.05 14:50:53.015427 [ 3744 ] {} <Fatal> BaseDaemon: 9. DB::ISource::work() @ 0xdb9ac1b in /usr/bin/clickhouse
2020.06.05 14:50:53.015462 [ 3744 ] {} <Fatal> BaseDaemon: 10. DB::SourceFromInputStream::work() @ 0xdeed365 in /usr/bin/clickhouse
2020.06.05 14:50:53.015512 [ 3744 ] {} <Fatal> BaseDaemon: 11. DB::TreeExecutorBlockInputStream::execute(bool, bool) @ 0xdbe264e in /usr/bin/clickhouse
2020.06.05 14:50:53.015545 [ 3744 ] {} <Fatal> BaseDaemon: 12. DB::TreeExecutorBlockInputStream::readImpl() @ 0xdbe3e27 in /usr/bin/clickhouse
2020.06.05 14:50:53.015580 [ 3744 ] {} <Fatal> BaseDaemon: 13. DB::IBlockInputStream::read() @ 0xce48ccf in /usr/bin/clickhouse
2020.06.05 14:50:53.015638 [ 3744 ] {} <Fatal> BaseDaemon: 14. DB::ExpressionBlockInputStream::readImpl() @ 0xd27448a in /usr/bin/clickhouse
2020.06.05 14:50:53.015668 [ 3744 ] {} <Fatal> BaseDaemon: 15. DB::IBlockInputStream::read() @ 0xce48ccf in /usr/bin/clickhouse
2020.06.05 14:50:53.015755 [ 3744 ] {} <Fatal> BaseDaemon: 16. DB::ExpressionBlockInputStream::readImpl() @ 0xd27448a in /usr/bin/clickhouse
2020.06.05 14:50:53.015791 [ 3744 ] {} <Fatal> BaseDaemon: 17. DB::IBlockInputStream::read() @ 0xce48ccf in /usr/bin/clickhouse
2020.06.05 14:50:53.016789 [ 3744 ] {} <Fatal> BaseDaemon: 18. DB::CreatingSetsBlockInputStream::createOne(DB::SubqueryForSet&) @ 0xd2e8cbe in /usr/bin/clickhouse
2020.06.05 14:50:53.016860 [ 3744 ] {} <Fatal> BaseDaemon: 19. DB::CreatingSetsBlockInputStream::readPrefixImpl() @ 0xd2eac67 in /usr/bin/clickhouse
2020.06.05 14:50:53.016894 [ 3744 ] {} <Fatal> BaseDaemon: 20. DB::IBlockInputStream::readPrefix() @ 0xce475ea in /usr/bin/clickhouse
2020.06.05 14:50:53.016937 [ 3744 ] {} <Fatal> BaseDaemon: 21. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0xce878b1 in /usr/bin/clickhouse
2020.06.05 14:50:53.017033 [ 3744 ] {} <Fatal> BaseDaemon: 22. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xd554297 in /usr/bin/clickhouse
2020.06.05 14:50:53.017075 [ 3744 ] {} <Fatal> BaseDaemon: 23. DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x8fed706 in /usr/bin/clickhouse
2020.06.05 14:50:53.017117 [ 3744 ] {} <Fatal> BaseDaemon: 24. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x8ff0bc3 in /usr/bin/clickhouse
2020.06.05 14:50:53.017156 [ 3744 ] {} <Fatal> BaseDaemon: 25. Poco::Net::HTTPServerConnection::run() @ 0xe37c6f4 in /usr/bin/clickhouse
2020.06.05 14:50:53.017192 [ 3744 ] {} <Fatal> BaseDaemon: 26. Poco::Net::TCPServerConnection::start() @ 0xe3ac69b in /usr/bin/clickhouse
2020.06.05 14:50:53.017229 [ 3744 ] {} <Fatal> BaseDaemon: 27. Poco::Net::TCPServerDispatcher::run() @ 0xe3acb1d in /usr/bin/clickhouse
2020.06.05 14:50:53.017257 [ 3744 ] {} <Fatal> BaseDaemon: 28. Poco::PooledThread::run() @ 0x105c3317 in /usr/bin/clickhouse
2020.06.05 14:50:53.017309 [ 3744 ] {} <Fatal> BaseDaemon: 29. Poco::ThreadImpl::runnableEntry(void*) @ 0x105bf11c in /usr/bin/clickhouse
2020.06.05 14:50:53.017338 [ 3744 ] {} <Fatal> BaseDaemon: 30. ? @ 0x105c0abd in /usr/bin/clickhouse
2020.06.05 14:50:53.017424 [ 3744 ] {} <Fatal> BaseDaemon: 31. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
```

**Comment by 4ertus2** [comment] 2020-06-05 23:44
It looks like we have `mysqlxx::checkError(conn->getDriver())` when connection is destroyed earlier then `CreatingSetsBlockInputStream` finished.

@KochetovNicolai don't you remember the case with totals + early query exit. Could it be the same issue here?

**Comment by KochetovNicolai** [comment] 2020-06-06 13:38
Well, it's probably because connection pool is owned by `StorageMySQL`:
https://github.com/ClickHouse/ClickHouse/blob/e230632645a29d917a934a1b46d2b8a81a5bb9d1/src/TableFunctions/TableFunctionMySQL.cpp#L120-L122
This storage is temporary and could possible be destroyed too early.

**Comment by millin** [comment] 2020-06-07 11:25
I'm not sure, but looks like issue disappeared in v20.4.4.18

**Comment by 4ertus2** [comment] 2020-06-08 11:24
If it's really fixed in 20.4 `set experimental_use_processors = 1` could be a workaround for 20.3.

**Comment by millin** [comment] 2020-06-08 19:19
In my opinion this still needs to be fixed for the LTS branch which is 20.3

**Comment by 4ertus2** [comment] 2020-06-16 12:13
Could you print here your query and schema here. I've tryed to reproduce the issue and it seems to be not supported at all. I've got LOGICAL_ERROR on 20.3 for this case

```
CREATE TABLE source_table1 (a Int32, b String) ENGINE = Memory;
CREATE TABLE distributed_table1 AS source_table1
ENGINE = Distributed('test_shard_localhost', currentDatabase(), source_table1);

INSERT INTO source_table1 VALUES (2, 'src');

SELECT t1.a as t1_a, t2.a as t2_a FROM distributed_table1 AS t1
GLOBAL JOIN mysql('127.0.0.1:3306', 'test', 't', 'user', 'password') AS t2
ON t1_a = t2_a LIMIT 0;
```

Most probably you use a case that is not fully supported and tested. If you don't want to face with this issue in future we need make a test for your case.

**Comment by millin** [comment] 2020-06-17 20:18
On versions 19.14-19.17 such kind of queries worked fine.
`tbl_distributed` is Distributed table with 3 shard * 2 replicas.
```
SELECT toTime(toStartOfHour(dttm)) AS dt
     , name
     , avg(distance) AS avg_distance
FROM tbl_distributed
         GLOBAL ANY
         LEFT JOIN
     (
         SELECT id
              , name
         FROM mysql(...)
         ) AS gt USING id
WHERE (dttm > (now() - toIntervalWeek(1)))
GROUP BY dt, name
ORDER BY dt ASC;
```

**Comment by 4ertus2** [comment] 2020-06-29 19:55
Still cannot reproduce.

**Comment by millin** [comment] 2020-06-29 20:37
@4ertus2 I noticed that segmentation fault occurs only at high load on the server.
When the load is light, the request simply fails with error like:
```
Poco::Exception. Code: 1000, e.code() = 224265568, e.displayText() = mysqlxx::Exception:  (H��H[]A\A]A^A_�f.�:224316616) (version 20.3.8.53 (official build))
```

**Comment by alexey-milovidov** [comment] 2020-10-21 23:46
Fixed in recent versions including recent LTS version 20.8.
Workaround for version 20.3 also exists.

**Closed by alexey-milovidov** 2020-10-21 23:46 UTC
Labels: bug, comp-joins, crash, st-need-repro, v20.3-affected
