### ISSUE TITLE
s3 function doesn't switch to non-default region

### ISSUE THREAD

**Issue by AndrewNik** [ClickHouse/ClickHouse#14736] opened 2020-09-11 10:10 UTC
**Describe the bug**
I try to load data from bucket in non-default region (like this 'https://s3.eu-central-1.amazonaws.com/test-bucket/test-folder/test.csv',) and receive error message:

" ... The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'..."

It's correctly work when bucket in us-east-1 region, but i need other region.

ClickHouse server version: version 20.8.2.3 (official build)

**Comment by den-crane** [comment] 2020-09-11 16:10
It's not a bug. It's by design.

**Comment by alexey-milovidov** [comment] 2020-10-21 22:58
Fixed in https://github.com/ClickHouse/ClickHouse/pull/15646

**Comment by alexey-milovidov** [comment] 2020-10-21 22:59
@den-crane Don't think it was by design.

**Closed by alexey-milovidov** 2020-10-21 22:58 UTC
Labels: feature
