### ISSUE TITLE
Send variables in HTTP body 

### ISSUE THREAD

**Issue by divelgrom** [ClickHouse/ClickHouse#8759] opened 2020-01-21 09:35 UTC
At the moment, variables can be passed in the url string.

I use templates for queries and just substitute the necessary variables.
I faced a problem when I need to make a request for 1000 records. Transferring such a quantity to the URL does not seem to be the right decision. I ask you to implement the ability to transfer the request template to the URL and a set of variables in the body.

**Comment by alexey-milovidov** [comment] 2022-08-10 08:13
Duplicate of #8842.

**Closed by alexey-milovidov** 2022-08-10 08:13 UTC
Labels: duplicate, feature, comp-http
