### ISSUE TITLE
Excessive dictionary memory preallocating

### ISSUE THREAD

**Issue by m1khal3v** [ClickHouse/ClickHouse#41985] opened 2022-10-01 09:03 UTC
This bug is reproduced on any version ( 22.1.3.7 , 22.3.11.12 , 22.9.3)

**How to reproduce** 
*(cant reproduce well on fiddle, but easy locally or on production)*

**NOT OK (with preallocate)**
```
CREATE TABLE default.oom_table (key String) ENGINE = MergeTree() ORDER BY tuple();

INSERT INTO default.oom_table SELECT hex(sipHash128(toString(number % 100))) FROM numbers(1000000000);

CREATE VIEW default.oom_view AS SELECT xxHash32(key) hash, key FROM default.oom_table GROUP BY key;

CREATE DICTIONARY default.oom_dict (hash UInt32, key String) PRIMARY KEY hash SOURCE(CLICKHOUSE(host 'localhost' user 'default' port 9000 db 'default' table 'oom_view')) LAYOUT (HASHED(PREALLOCATE 1)) LIFETIME (600);

SELECT * FROM dictionary('default.oom_dict');
```

**Error**
```
Code: 241. DB::Exception: Received from clickhouse-server:9000. DB::Exception: Memory limit (total) exceeded: would use 48.48 GiB (attempt to allocate chunk of 51540792506 bytes), maximum: 13.50 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker.. (MEMORY_LIMIT_EXCEEDED)

```

**OK (without preallocate)**
```
CREATE TABLE default.oom_table (key String) ENGINE = MergeTree() ORDER BY tuple();

INSERT INTO default.oom_table SELECT hex(sipHash128(toString(number % 100))) FROM numbers(1000000000);

CREATE VIEW default.oom_view AS SELECT xxHash32(key) hash, key FROM default.oom_table GROUP BY key;

CREATE DICTIONARY default.oom_dict (hash UInt32, key String) PRIMARY KEY hash SOURCE(CLICKHOUSE(host 'localhost' user 'default' port 9000 db 'default' table 'oom_view')) LAYOUT (HASHED()) LIFETIME (600);

SELECT * FROM dictionary('default.oom_dict');
```

**Comment by alexey-milovidov** [comment] 2022-10-01 17:12
@azat I didn't know that ClickHouse has the "preallocate" option.
No idea why we need it. Let's revert #23979?

**Comment by alexey-milovidov** [comment] 2022-10-01 17:14
@m1khal3v read https://github.com/ClickHouse/ClickHouse/pull/23979#issuecomment-835831199 and stop using "PREALLOCATE" option, as it helps to improve loading speed only by 30%.

**Comment by m1khal3v** [comment] 2022-10-01 17:30
@alexey-milovidov already stopped, thanks

**Comment by azat** [comment] 2022-10-01 21:33
>No idea why we need it. Let's revert https://github.com/ClickHouse/ClickHouse/pull/23979?

@alexey-milovidov let's wait until I will rethink #40003 (it is another way of improving the performance of the dictionary load)

**Comment by azat** [comment] 2022-10-01 21:38
An about this issue the problem is in VIEW, `PREALLOCATE` can be used only for simple queries, i.e. `select * from table`, for `GROUP BY` the number of keys will be incorrect, since there is no way to get them (`PREALLOCATE` relies on `progress.total_rows_to_read`)

**Comment by m1khal3v** [comment] 2022-10-01 21:59
@azat I guess. it would be nice to add it to the documentation

**Closed** 2023-01-20 11:51 UTC
Labels: unexpected behaviour
