### ISSUE TITLE
00992_system_parts_race_condition_zookeeper_long timeout

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#51599] opened 2023-06-29 12:57 UTC
example in master 
https://s3.amazonaws.com/clickhouse-test-reports/0/c66ff09627b43756b84cc8c1c5a82b1a905cb4d2/stateless_tests__ubsan__[2_2].html

Stats:
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMDk5Ml9zeXN0ZW1fcGFydHNfcmFjZV9jb25kaXRpb25fem9va2VlcGVyX2xvbmclJyBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=

**Comment by tavplubix** [comment] 2023-06-29 14:50
duplicate of https://github.com/ClickHouse/ClickHouse/issues/50434

**Closed by tavplubix** 2023-06-29 14:50 UTC
Labels: flaky test
