### ISSUE TITLE
MySQL compatibility: FROM_DAYS function

### ISSUE THREAD

**Issue by larskarbo** [ClickHouse/ClickHouse#56179] opened 2023-10-31 18:09 UTC
Using the MySQL connector, when using Tableau’s default Week Number date granularity, it requires the use of the `FROM_DAYS` function.

It fails:

```
Code: 46. DB::Exception: Unknown function FROM_DAYS.
```

The whole error:

```
Error Code:B19090E0
[MySQL][ODBC 8.1(w) Driver][mysqld-23.10.1.1795-ClickHouse]Code: 46. DB::Exception: Unknown function FROM_DAYS. Maybe you meant: ['TO_DAYS']: While processing addDate(FROM_DAYS(toDaysSinceYearZero(createdAt) - (((7 + toDayOfWeek(createdAt)) - 2)  7)), toIntervalSecond(0)) AS twk_createdAt_ok. (UNKNOWN_FUNCTION) (version 23.10.1.1795 (official build))
SELECT COUNT(DISTINCT `QuestCompletion`.`id`) AS `ctd_id_ok`,
  ADDDATE(FROM_DAYS( TO_DAYS(`QuestCompletion`.`createdAt`) - ((7 + DAYOFWEEK(`QuestCompletion`.`createdAt`) - 2) % 7) ), INTERVAL 0 SECOND ) AS `twk_createdAt_ok`
FROM `QuestCompletion`
GROUP BY 2
```

**How to reproduce**

- Which ClickHouse server version to use: latest master
- Which interface to use, if matters: MySQL

Run this in the console:

```
SELECT FROM_DAYS(730669);
```

**Expected behavior**

FROM_DAYS function works like in MySQL

**Comment by slvrtrn** [comment] 2023-11-10 21:41
Duplicate of #55308

**Closed by slvrtrn** 2023-11-10 21:41 UTC
Labels: potential bug
