### ISSUE TITLE
PostgreSQL scram-sha-256 auth method is not supported

### ISSUE THREAD

**Issue by vialorn** [ClickHouse/ClickHouse#24526] opened 2021-05-26 12:15 UTC
**Describe the unexpected behaviour**
I try to access PostgreSQL data with a query like
```sql
SELECT * FROM postgresql('some_host:5432', 'some_database', 'some_table', 'some_user', 'some_password', 'some_schema');
```
and get the error below
```
Received exception from server (version 21.4.7): Code: 1001. DB::Exception: Received from localhost:9000. 
DB::Exception: pqxx::broken_connection: FATAL:  password authentication failed for user "some_user".
```
while have in PostgreSQL instance `pg_hba.conf` a line similar to
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

host  some_database  some_user 172.0.0.0/8  scram-sha-256
```
When I change `scram-sha-256` to `md5` I get data with the query above without any error.

**Comment by tavplubix** [comment] 2021-05-26 17:27
#24516
#24543

**Comment by vdimir** [comment] 2021-05-27 12:18
Closing as duplicate of https://github.com/ClickHouse/ClickHouse/issues/24516

**Closed** 2021-05-27 12:18 UTC
Labels: comp-postgre, duplicate, unfinished code
