### ISSUE TITLE
Notify systemd about successful startup

### ISSUE THREAD

**Issue by mnacharov** [ClickHouse/ClickHouse#8685] opened 2020-01-16 13:28 UTC
**Use case**
I have a service which starts after `clickhouse-server.service` startup, but `clickhouse-server.service` considered started right after fork called by systemd (Type=simple).
This causes connection errors to database at server startup.
I tried to use option `--daemon` and `Type=forking`, but clickhouse forks before start listening http ([Http Interface](https://clickhouse.yandex/docs/en/interfaces/http/)).

**Describe the solution you'd like**
Using [systemd/sd-notify](https://www.freedesktop.org/software/systemd/man/sd_notify.html) will allow us to using `Type=notify`.
I suggest to sent notification if `--notify` arg specified .

**Describe alternatives you've considered**
Refactoring `--daemon` arg, to fork after database is ready to use.

**Comment by mnach** [comment] 2020-01-22 15:23
Is it valid decision to add systemd as subrepo, and describe which sources to compile in `systemd-cmake/CMakeLists.txt`?

**Comment by alexey-milovidov** [comment] 2020-07-10 20:21
@mnach Yes, it's totally alright.

(Also ClickHouse should continue to work when there is no systemd in the system).

**Comment by socketpair** [comment] 2022-05-06 15:22
This is the patch:

```diff
--- a/programs/server/Server.cpp
+++ b/programs/server/Server.cpp
@@ -88,6 +88,7 @@
 #include <Interpreters/AsynchronousInsertQueue.h>
 #include <Compression/CompressionCodecEncrypted.h>
 #include <filesystem>
+#include <systemd/sd-daemon.h>
 
 #include "config_core.h"
 #include "Common/config_version.h"
@@ -1484,6 +1485,8 @@
             tryLogCurrentException(log, "Caught exception while starting cluster discovery");
         }
 
+        ::sd_notify(1, "READY=1");
+
         SCOPE_EXIT_SAFE({
             LOG_DEBUG(log, "Received termination signal.");
             LOG_DEBUG(log, "Waiting for current connections to close.");
```

Actually, it's also require `export LDFLAGS=$(pkg-config --libs libsystemd)`

And internal watchdog MUST be switched off because every child it runs (after child death) will report to systemd. And it's not expected by systemd, and also useless because systemd has `Restart=on-failure`.

Also I vote for disabling watchdog by default.

I think there should be CMake build option that add linker flag, library dependency and enables this 1 line of code (using `#ifdef` ?).

**Comment by socketpair** [comment] 2022-05-06 15:32
@alexey-milovidov are there any chances this will be fixed ? I'm not into CMake and ClickHouse build system, so I can not make correct PR.

**Comment by alexey-milovidov** [comment] 2022-05-06 20:10
As it requires linking with yet another library there is almost zero chance it will be fixed.
We only allow static linking and building every library from sources.

**Comment by alexey-milovidov** [comment] 2022-05-06 20:12
We have strict guidelines for our code base:
- don't use source codes or libraries from OS or repositories;
- build everything from source code;
- use fixed versions of the libraries, no automatic updates;
- all source code of third-party dependencies is checked out;
- all the code can be built with sanitizers and hardening;
- no known memory safety issues exist;
- reproducible (byte-identical), hermetic builds;
- all the code can be cross-compiled;
- minimize the supply chain;
- minimize runtime dependencies on the files on the target machine;
- single-binary distribution;
- static linking;
- no foreign code or plugins can run in the program address space;

**Comment by socketpair** [comment] 2022-05-06 20:20
@alexey-milovidov The protocol with communication with systemd is documented and is VERY simple. (just write string to a socket whose FD got from environment variable). Please reopen. I can show how to notify systemd without extra libraries.

**Comment by alexey-milovidov** [comment] 2022-05-07 14:13
That's good, if we can avoid dependencies, let's do it!

**Comment by socketpair** [comment] 2022-11-19 18:36
https://github.com/ClickHouse/ClickHouse/pull/43400

**Closed** 2022-11-22 17:07 UTC
Labels: help wanted, feature, comp-packaging
