### ISSUE TITLE
TTL doen't work with ReplicatedReplacingMergeTree

### ISSUE THREAD

**Issue by mobydi** [ClickHouse/ClickHouse#7401] opened 2019-10-21 08:53 UTC
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
TTL and ReplicatedReplacingMergeTree doesn't work 

**How to reproduce**
* Which ClickHouse server version to use
```19.14.6.12```

* Which interface to use, if matters
```clickhouse-client```

* Non-default settings, if any
default settings in place 

* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE test.ht_repl ON CLUSTER 'one_shard_three_replicas' (
`cm_mac_address` String, 
`last_updated` DateTime, 
`cabinet` Nullable(String), 
`node` Nullable(String)) 
ENGINE = ReplicatedReplacingMergeTree('{zookeeper_path_prefix}/ht_repl', '{shard}', last_updated) 
PARTITION BY toYYYYMMDD(last_updated) 
PRIMARY KEY cm_mac_address 
ORDER BY cm_mac_address 
TTL last_updated + toIntervalDay(1) 
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result
```
SELECT last_updated
FROM test.ht_repl
GROUP BY last_updated
ORDER BY last_updated ASC

┌────────last_updated─┐
│ 2019-10-14 23:00:00 │
│ 2019-10-17 11:00:00 │
│ 2019-10-17 13:00:00 │
│ 2019-10-17 14:00:00 │
│ 2019-10-17 21:00:00 │
│ 2019-10-17 23:00:00 │
│ 2019-10-18 00:00:00 │
│ 2019-10-18 07:00:00 │
└─────────────────────┘
```

**Expected behavior**

The data was inserted a couple of days ago, I expect that it should be deleted automatically by schedule. 

```
SELECT last_updated
FROM test.ht_repl
GROUP BY last_updated
ORDER BY last_updated ASC

┌────────last_updated─┐
│ 2019-10-18 00:00:00 │
│ 2019-10-18 07:00:00 │
└─────────────────────┘
```

If I run manually, data will be deleted. 
```OPTIMIZE TABLE test.ht_repl FINAL```

```
SELECT last_updated
FROM test.ht_repl
GROUP BY last_updated
ORDER BY last_updated ASC

Ok.

0 rows in set. Elapsed: 0.002 sec. 
```

Looks like there is an issue TTL with ReplicatedReplacingMergeTree and scheduler  

**Error message and/or stacktrace**

**Additional context**

**Comment by mobydi** [comment] 2019-10-22 15:00
I also noticed that after ```OPTIMIZE TABLE test.ht_repl FINAL ```
It doesn't delete parts and I see them in ```SELECT partition FROM system.parts ...```

**Comment by den-crane** [comment] 2020-10-15 03:30
It's not the relevant issue anymore. 
TTL has been improved.
And no provable info for reproduction.

>It doesn't delete parts and I see them in SELECT partition FROM system.parts ...

It's expected behavior (by design) -- empty parts (after TTL) it will be addressed.

**Comment by mateng0915** [comment] 2020-10-23 10:01
Actually i also find the similar issue, the ttl does not work until i execute the optimize TABLE Final then the expired data will be deleted. However i have another issue.
I have the 20201005 folder which save my data part, but only one data part has the ttl.txt file. others does not have
![image](https://user-images.githubusercontent.com/26053753/96990358-96ba5a80-1559-11eb-9d7a-e2d2e2a4f127.png)
![image](https://user-images.githubusercontent.com/26053753/96990382-9e79ff00-1559-11eb-829b-24feb354ec99.png)
![image](https://user-images.githubusercontent.com/26053753/96990414-a9cd2a80-1559-11eb-8db6-d5b9d8a20a87.png)

Which looks only the max_number highest folder have the ttl.txt file

**Comment by den-crane** [comment] 2020-10-27 22:20
It's not the relevant issue anymore. I am closing It.

**Closed by den-crane** 2020-10-27 22:20 UTC
Labels: bug, comp-ttl
