### ISSUE TITLE
global in not work for Merge table engine

### ISSUE THREAD

**Issue by timmy21** [ClickHouse/ClickHouse#66414] opened 2024-07-12 04:16 UTC
clickhouse version: 23.8.15.35

**How to reproduce**

```
CREATE DATABASE test

CREATE TABLE test.t_1
(
    a String,
    b String
) ENGINE = MergeTree ORDER BY (a, b)

CREATE TABLE test.t_2
(
    a String,
    b String
) ENGINE = MergeTree ORDER BY (a, b)

CREATE TABLE test.dist_t_1 (a String, b String) ENGINE = Distributed('default', 'test', 't_1')

CREATE TABLE test.dist_t_2 (a String, b String) ENGINE = Distributed('default', 'test', 't_2')

CREATE TABLE test.m ENGINE = Merge('test', '^dist_')

INSERT INTO test.t_1 (a, b) VALUES
('a1', 'b1'),
('a2', 'b2'),
('a3', 'b3')

INSERT INTO test.t_2 (a, b) VALUES
('a1', 'b1'),
('a2', 'b2'),
('a4', 'b4')

SELECT
  a,
  b,
  count()
FROM test.m
WHERE (a) GLOBAL IN (
    SELECT a
    FROM test.m
    GROUP BY a
    LIMIT 500
  )
GROUP BY
  a,
  b
```

expected 4 rows, but got 0 rows 

if i use below query, the result is right
```
SELECT
  a,
  b,
  count()
FROM test.dist_t_1
WHERE (a) GLOBAL IN (
    SELECT a
    FROM test.m
    GROUP BY a
    LIMIT 500
  )
GROUP BY
  a,
  b
```

I guess is that the Merge table engine is causing the problem？

I try it on clickhouse 24.3.5.46，the result is right!

but i can't upgrade to 24.3.5.46, because query is very slow after upgrade(maybe other issue for Merge table Engine?).

**Comment by den-crane** [comment] 2024-07-12 15:08
duplicate of https://github.com/ClickHouse/ClickHouse/issues/64211

you can use `WHERE identity(a) GLOBAL IN (` `identity` as a workaround or upgrade to 24.3

https://fiddle.clickhouse.com/59b85bd3-058d-40e1-8e1c-d6643e12d1cd

**Comment by timmy21** [comment] 2024-07-12 15:19
> duplicate of #64211
> 
> you can use `WHERE identity(a) GLOBAL IN (` `identity` as a workaround or upgrade to 24.3
> 
> https://fiddle.clickhouse.com/59b85bd3-058d-40e1-8e1c-d6643e12d1cd

thanks！

by the way, is there any issue about performance issue on 24.3 for Merge table engine？

**Comment by den-crane** [comment] 2024-07-12 15:29
yes https://github.com/ClickHouse/ClickHouse/issues/51846
it was fixed in 23.11, not backported 

v23.11.1.2711-stable.md:* Fixed filtering by `IN(...)` condition for `Merge` table engine. [#54905](https://github.com/ClickHouse/ClickHouse/pull/54905) ([Nikita Taranov](https://github.com/nickitat)).

**Comment by timmy21** [comment] 2024-07-12 15:38
oh, no.
use identity solve my fake case above. but production real case also not work

**Comment by den-crane** [comment] 2024-07-12 15:41
There is no issues with engine merge in 24.3 , upgrade to 24.3.5.46

**Comment by timmy21** [comment] 2024-07-14 01:50
> There is no issues with engine merge in 24.3 , upgrade to 24.3.5.46

when i upgrade clickhouse docker image from 23.8.15.35 to 24.3.5.46，the  I/O usage reaches 100%

Is there any backgroud task running after upgrade?

**Comment by timmy21** [comment] 2024-07-14 12:17
I new another issue to report this performance issue: https://github.com/ClickHouse/ClickHouse/issues/66492

**Closed** 2024-07-27 01:27 UTC
Labels: potential bug
