### ISSUE TITLE
Not a valid log level

### ISSUE THREAD

**Issue by makorne** [ClickHouse/ClickHouse#54104] opened 2023-08-31 07:55 UTC
> You have to provide the following information whenever possible.

**Describe what's wrong**

Does not restart after changing default password from empty  in config.xml 
And after changing back. 
And after updating clickhouse to current version.
And after changing log lever to error, debug, tracing.

> A clear and concise description of what works not as it is supposed to.
clickhouse start

**Does it reproduce on recent release?**
Yes

**Error message and/or stacktrace**
```

Logging debug to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Poco::Exception. Code: 1000, e.code() = 0, Invalid argument: Not a valid log level, Stack trace (when copying this message, always include the lines below):

0. Poco::Logger::parseLevel(String const&) @ 0x00000000183ed473 in /usr/bin/clickhouse
1. Loggers::buildLoggers(Poco::Util::AbstractConfiguration&, Poco::Logger&, String const&) @ 0x000000000ebeaa70 in /usr/bin/clickhouse
2. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000ebc81e9 in /usr/bin/clickhouse
3. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000e9b7478 in /usr/bin/clickhouse
4. Poco::Util::Application::run() @ 0x00000000182aa79a in /usr/bin/clickhouse
5. DB::Server::run() @ 0x000000000e9b723e in /usr/bin/clickhouse
6. Poco::Util::ServerApplication::run(int, char**) @ 0x00000000182bded9 in /usr/bin/clickhouse
7. mainEntryClickHouseServer(int, char**) @ 0x000000000e9b3f0a in /usr/bin/clickhouse
8. main @ 0x0000000008f8cecf in /usr/bin/clickhouse
9. __libc_start_main @ 0x0000000000023d0a in /usr/lib/x86_64-linux-gnu/libc-2.31.so
10. _start @ 0x000000000829bdee in /usr/bin/clickhouse
 (version 23.7.5.30 (official build))
Logging error to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Poco::Exception. Code: 1000, e.code() = 0, Invalid argument: Not a valid log level, Stack trace (when copying this message, always include the lines below):

0. Poco::Logger::parseLevel(String const&) @ 0x00000000183ed473 in /usr/bin/clickhouse
1. Loggers::buildLoggers(Poco::Util::AbstractConfiguration&, Poco::Logger&, String const&) @ 0x000000000ebeaa70 in /usr/bin/clickhouse
2. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000ebc81e9 in /usr/bin/clickhouse
3. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000e9b7478 in /usr/bin/clickhouse
4. Poco::Util::Application::run() @ 0x00000000182aa79a in /usr/bin/clickhouse
5. DB::Server::run() @ 0x000000000e9b723e in /usr/bin/clickhouse
6. Poco::Util::ServerApplication::run(int, char**) @ 0x00000000182bded9 in /usr/bin/clickhouse
7. mainEntryClickHouseServer(int, char**) @ 0x000000000e9b3f0a in /usr/bin/clickhouse
8. main @ 0x0000000008f8cecf in /usr/bin/clickhouse
9. __libc_start_main @ 0x0000000000023d0a in /usr/lib/x86_64-linux-gnu/libc-2.31.so
10. _start @ 0x000000000829bdee in /usr/bin/clickhouse
 (version 23.7.5.30 (official build))
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Poco::Exception. Code: 1000, e.code() = 0, Invalid argument: Not a valid log level, Stack trace (when copying this message, always include the lines below):

0. Poco::Logger::parseLevel(String const&) @ 0x00000000183ed473 in /usr/bin/clickhouse
1. Loggers::buildLoggers(Poco::Util::AbstractConfiguration&, Poco::Logger&, String const&) @ 0x000000000ebeaa70 in /usr/bin/clickhouse
2. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000ebc81e9 in /usr/bin/clickhouse
3. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000e9b7478 in /usr/bin/clickhouse
4. Poco::Util::Application::run() @ 0x00000000182aa79a in /usr/bin/clickhouse
5. DB::Server::run() @ 0x000000000e9b723e in /usr/bin/clickhouse
6. Poco::Util::ServerApplication::run(int, char**) @ 0x00000000182bded9 in /usr/bin/clickhouse
7. mainEntryClickHouseServer(int, char**) @ 0x000000000e9b3f0a in /usr/bin/clickhouse
8. main @ 0x0000000008f8cecf in /usr/bin/clickhouse
```

> Add any other context about the problem here.

**Comment by cangyin** [comment] 2023-08-31 08:37
```xml
<clickhouse>
    <logger>
        <!-- Possible levels [1]:

          - none (turns off logging)
          - fatal
          - critical
          - error
          - warning
          - notice
          - information
          - debug
          - trace
          - test (not for production usage)

            [1]: https://github.com/pocoproject/poco/blob/poco-1.9.4-release/Foundation/include/Poco/Logger.h#L105-L114
        -->
        <level>trace</level>
    </logger>
</clickhouse>
```

say if you wanted ClickHouse to print all logs with level **higher than** debug, just write:

```xml
        <level>debug</level>
```

**Comment by makorne** [comment] 2023-08-31 09:41
With `trace` and even `none` it's the same

```
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Poco::Exception. Code: 1000, e.code() = 0, Invalid argument: Not a valid log level, Stack trace (when copying this message, always include the lines below):

0. Poco::Logger::parseLevel(String const&) @ 0x00000000183ed473 in /usr/bin/clickhouse
1. Loggers::buildLoggers(Poco::Util::AbstractConfiguration&, Poco::Logger&, String const&) @ 0x000000000ebeaa70 in /usr/bin/clickhouse
2. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000ebc81e9 in /usr/bin/clickhouse
3. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000e9b7478 in /usr/bin/clickhouse
4. Poco::Util::Application::run() @ 0x00000000182aa79a in /usr/bin/clickhouse
5. DB::Server::run() @ 0x000000000e9b723e in /usr/bin/clickhouse
6. Poco::Util::ServerApplication::run(int, char**) @ 0x00000000182bded9 in /usr/bin/clickhouse
7. mainEntryClickHouseServer(int, char**) @ 0x000000000e9b3f0a in /usr/bin/clickhouse
8. main @ 0x0000000008f8cecf in /usr/bin/clickhouse
9. __libc_start_main @ 0x0000000000023d0a in /usr/lib/x86_64-linux-gnu/libc-2.31.so
10. _start @ 0x000000000829bdee in /usr/bin/clickhouse
 (version 23.7.5.30 (official build))
Logging error to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Poco::Exception. Code: 1000, e.code() = 0, Invalid argument: Not a valid log level, Stack trace (when copying this message, always include the lines below):

0. Poco::Logger::parseLevel(String const&) @ 0x00000000183ed473 in /usr/bin/clickhouse
1. Loggers::buildLoggers(Poco::Util::AbstractConfiguration&, Poco::Logger&, String const&) @ 0x000000000ebeaa70 in /usr/bin/clickhouse
2. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000ebc81e9 in /usr/bin/clickhouse
3. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000e9b7478 in /usr/bin/clickhouse
4. Poco::Util::Application::run() @ 0x00000000182aa79a in /usr/bin/clickhouse
5. DB::Server::run() @ 0x000000000e9b723e in /usr/bin/clickhouse
6. Poco::Util::ServerApplication::run(int, char**) @ 0x00000000182bded9 in /usr/bin/clickhouse
7. mainEntryClickHouseServer(int, char**) @ 0x000000000e9b3f0a in /usr/bin/clickhouse
8. main @ 0x0000000008f8cecf in /usr/bin/clickhouse
9. __libc_start_main @ 0x0000000000023d0a in /usr/lib/x86_64-linux-gnu/libc-2.31.so
10. _start @ 0x000000000829bdee in /usr/bin/clickhouse
 (version 23.7.5.30 (official build))
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Poco::Exception. Code: 1000, e.code() = 0, Invalid argument: Not a valid log level, Stack trace (when copying this message, always include the lines below):
```

**Comment by makorne** [comment] 2023-08-31 13:26
[config.xml.zip](https://github.com/ClickHouse/ClickHouse/files/12486520/config.xml.zip)

Why not marked as bug?
Your error log system is useless !

**Comment by cangyin** [comment] 2023-08-31 23:41
@makorne You left log level empty for text_log:
```xml
      <text_log>
        <database>system</database>
        <table>text_log</table>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        <ttl>event_date + INTERVAL 3 DAY DELETE </ttl>
       <level></level>
    </text_log>
```
A mis-configuration.

**Comment by makorne** [comment] 2023-09-01 09:37
Yes, this helped thank you.
But this shows even 2 clickhouse bugs.
   
**Bug 1.** Log system works incorrectly and does not provide the right source of the error. 
 If it had showed a string in config where in a 75KB file!!! did it find a a wrong log level - the issue would have been resolved in minutes instead of hours and without wasting your and my time.
 
 **Bug 2.** No default-value for level property what can crash the entire server.
 Why not use 'none' or 'error' level value in case it is wrong???

**Comment by makorne** [comment] 2023-09-01 15:15
>  there is no log level name printed, which reveals that you provided an empty level name.

Nobody from clickhouse github pointed to that when I wrote about this issue. 
And if you look at the top of file you will  see that I set `none` and tried many different right levels without success. 
Who could guess, it's not written that  the main field of log level in the top of config does nothing! 
 
> Anyway, restarting the server with a default config.xml always helps.

This results is loss of all settings and then, in the process of copying settings  in small pieces from old settings, multiple restarts are required and all the while the server will be inaccessible

> Server won't crash if the config file is modified during runtime. But it refuses to start with a wrong configuration.

And nobody knows how to start it for several hours!! Because it's log system doesn't say what it doesn't like... 

Why do you ignore these bugs and don't want to make your server better?

**Comment by filimonov** [comment] 2023-09-01 23:58
> But this shows even 2 clickhouse bugs.

Those are not the bugs, it's just a minor usability issues - not being very user-friendly / foolproof.

You can find more of those, and if it disturbs you - remember that clickhouse is and open-source project and you can easily make such tiny improvements. Contributions are welcomed!

**Comment by cangyin** [comment] 2023-09-02 05:01
> Nobody from clickhouse github pointed to that when I wrote about this issue.

And nobody knowns that you modified a log level name else where.

> This results is loss of all settings

A good practice should be that leave the config.xml as default and write your non-default values in config.d directory.

> make your server better

It's not yours or mine. ClickHouse is open-sourced by yandex developers and now a community project (In other word, you don't have to pay for it).

**Comment by makorne** [comment] 2023-09-02 07:05
> A good practice should be that leave the config.xml as default and write your non-default values in config.d directory. 

First of all, a good practice is not to ignore bugs.  
Anyway config.d directory cant resolve this issue.

> It's not yours or mine. ClickHouse is open-sourced by yandex developers and now a community project (In other word, you don't have to pay for it).

That sounds naive.   
Now it is a project of the billionaire company Clickhouse.inc. And from their About:
`ClickHouse is proud to have employees in over 10 countries.` 

So billionaire just want to get bigger profit and save money on support and developers.
Just one developer from their over 10 countries  can resolve this bug  in an hour or less.
We have already wasted more time on this issue than it takes to resolve it. 

Just looks like a billionaire company is not interested in solving even such simple bugs because they want to push all users to their costly cloud service. 

Many users do free work by testing and reporting their issues and make their tool better. 
I just think if somebody makes billions on some tool he should provide enough devs to resolve bugs.

**Comment by cangyin** [comment] 2023-09-02 09:10
> a good practice is not to ignore bugs.

This is not a bug. It's about wrong usage or mis-configuration. But you just reported it as a bug before trying a default config file, and claimed "Your error log system is useless !"

> So billionaire just want to get bigger profit and save money on support and developers.

That's naive. You use it for free and earn money with it with almost zero-cost for it, and blame it for a minor usage problem ?

> Many users do free work by testing and reporting their issues and make their tool better.

Yes we all welcome such bug report, and explore the issues page with "bug" label, those bug reports are all respected. But apparently this is not this kind of issue.

PS. developers can close it any time, before which I can reply to this issue all the day.

**Comment by Tiaonmmn** [comment] 2023-09-02 09:25
>So billionaire just want to get bigger profit and save money on support and developers.
Just one developer from their over 10 countries can resolve this bug in an hour or less.
Why don't you use ClickHouse Cloud service?It has good support.This is open source repository of ClickHouse, noone should pay for your question.

**Comment by makorne** [comment] 2023-09-03 07:58
> This is not a bug. It's about wrong usage or mis-configuration. But you just reported it as a bug before trying a default config file, and claimed "Your error log system is useless !"

This is a bug because it's not written anywhere that their top 'log level' does nothing in such a case and you should try to find another log level in their gigantic 75kb config file... 

And their log system is so incorrectly developed that does not even report the number of the line in the file where it finds the configuration wrong... 

That's the main oldest basis of any log system - writing the number of the line where the error is detected, isn't it?? 
Why do they ignore the basic principle of a log system???   
We and many other users waste time only because of this ridiculous bug. 

If they resolve the bug with line number, many configuration issues will be resolved easily. 
But looks like billionaires not want to resolve ridiculous usability bugs of their tool.

**Comment by cangyin** [comment] 2023-09-03 08:29
>  you should try to find another log level in their gigantic 75kb config file...

You won't remember what you modified ?

Quote Chinese: "巨婴"。

**Comment by cangyin** [comment] 2023-09-03 08:47
> Log system works incorrectly and does not provide the right source of the error.
> 
> Clearly you modified configuration file, which should be easy enough for a user to remember what modification can possibly be the cause. And if you try a wrong log level like 'debug-xyz', the exception will be Invalid argument: Not a valid log level: debug-xyz, so reading the exception message you provided, there is no log level name printed, which reveals that you provided an empty level name.

> Nobody from clickhouse github pointed to that when I wrote about this issue.
> 
> And nobody knowns that you modified a log level name else where.
> 
> This results is loss of all settings
> 
> A good practice should be that leave the config.xml as default and write your non-default values in config.d directory.


You issue has been solved, but you keeps venting your bad emotions just because of a mis-configuration, insisting that this is a bug, for ClickHouse not reporting which line in file you modified to a wrong value. But actually it already tells it got an empty log level name, which is enough for one to debug. If you think this is exception message is still not clear, go write a PR!

> If they resolve the bug with line number, many configuration issues will be resolved easily.

I don't think so, a name in configuration is already clear enough. Because xml files can be written without line breaks.

But looks like billionaires not want to resolve ridiculous usability bugs of their tool.

> But looks like billionaires not want to resolve ridiculous usability bugs of their tool.

Yes, ridiculous.

**Comment by makorne** [comment] 2023-09-03 09:01
> Why don't you use ClickHouse Cloud service?It has good support.This is open source repository of ClickHouse, no one should take responsibility for your question.

They asked for contribution.
I made my contribution - found and documented them 2 bugs for free.
Even though normal software companies usually have paid testers and it is their paid job. 
But looks like I wasted my time, really they don't want to resolve even simple bugs. 

There are 3083!!! open issues, even projects with just a the couple developers often resolve issues faster than that billionaire company

I'm not a billioner to waste my money for their cloud and make them multi-billioners.
Even despite the fact that is looks like they purposefully make their tool not user-friendly and hide the number of the error line.

**Comment by filimonov** [comment] 2023-09-03 23:02
> I made my contribution - found and documented them 2 bugs for free.

According to our definitions those are not bugs. Bug = user do correct thing, software do incorrect. Here user did incorrect thing and software was not ready for that. (example: If you hit the your monitor with a hammer and the image will be bad after that - is it the bug of the screen manufacturer?). 

> There are 3083!!! open issues

Do you know what "Backlog" means? Did you check what kind of issues those are? Did you check how many pull requests are merged weekly? Did you ever heard of such thing as "priorities" and minor/major issues?how would you estimate the importance of YOUR issue compared to 3082 of other open issues? Did you check the number of open issues and tempo of merging the PRs in other big open source projects? 

> Even despite the fact that is looks like they purposefully make their tool not user-friendly and hide the number of the error line.

Calm down. Billionaires does not read the github issues :) We are just developers. And we have a lot of other different work to do. If you need it fast - there is a clear way to achieve that: contribute (and you can prove if it's really an hour of work). If you want somebody to fix it for you - be patient, eventually it will be fixed (not by billionaires again, but by usual devs)

**Comment by filimonov** [comment] 2023-09-03 23:07
>  that is looks like they purposefully make their tool not user-friendly and hide the number of the error line

https://en.m.wikipedia.org/wiki/Hanlon%27s_razor ;)

**Closed** 2023-09-06 18:02 UTC
Labels: question
