### ISSUE TITLE
Server crashes using S3 as table backend

### ISSUE THREAD

**Issue by Pipboyguy** [ClickHouse/ClickHouse#47718] opened 2023-03-19 14:17 UTC
Using S3 table:

```sql
CREATE TABLE uk_price_paid_s3
(
    price UInt32,
    date Date,
    year UInt16 MATERIALIZED toYear(date),
    postcode1 LowCardinality(String),
    postcode2 LowCardinality(String),
    type Enum8('terraced' = 1, 'semi-detached' = 2, 'detached' = 3, 'flat' = 4, 'other' = 0),
    is_new UInt8,
    duration Enum8('freehold' = 1, 'leasehold' = 2, 'unknown' = 0),
    addr1 String,
    addr2 String,
    street LowCardinality(String),
    locality LowCardinality(String),
    town LowCardinality(String),
    district LowCardinality(String),
    county LowCardinality(String)
)
ENGINE = S3('https://modin-datasets.s3.us-east-005.***', '***', '***', 'Parquet', 'ZSTD')
PARTITION BY (year);
```

Following the official clickhouse docs, I insert into this table:

```sql
INSERT INTO uk_price_paid_s3
WITH
   splitByChar(' ', postcode) AS p
SELECT
    toUInt32(price_string) AS price,
    parseDateTimeBestEffortUS(time) AS date,
    p[1] AS postcode1,
    p[2] AS postcode2,
    transform(a, ['T', 'S', 'D', 'F', 'O'], ['terraced', 'semi-detached', 'detached', 'flat', 'other']) AS type,
    b = 'Y' AS is_new,
    transform(c, ['F', 'L', 'U'], ['freehold', 'leasehold', 'unknown']) AS duration,
    addr1,
    addr2,
    street,
    locality,
    town,
    district,
    county
FROM file(
    'pp-complete.csv',
    'CSV',
    'uuid_string String,
    price_string String,
    time String,
    postcode String,
    a String,
    b String,
    c String,
    addr1 String,
    addr2 String,
    street String,
    locality String,
    town String,
    district String,
    county String,
    d String,
    e String'
);
```

The server abruptly crashes:

```logs
[psod5na8b] 2023.03.19 14:06:42.929159 [ 76511 ] <Fatal> BaseDaemon: 
[psod5na8b] 2023.03.19 14:06:42.929198 [ 76511 ] <Fatal> BaseDaemon: Stack trace: 0x7fa76b9f400b 0x7fa76b9d3859 0xe3cb59c 0x1a4a36e3 0x1a4a364e 0x89e174b 0x10afa615 0x141e7a3b 0x129a88c1 0x129ab01a 0x129b00bb 0x1496617c 0x1497a839 0x17888b94 0x17889dbb 0x17a11647 0x17a0f07d 0x7fa76bbab609 0x7fa76bad0133
[psod5na8b] 2023.03.19 14:06:42.929243 [ 76511 ] <Fatal> BaseDaemon: 2. gsignal @ 0x7fa76b9f400b in ?
[psod5na8b] 2023.03.19 14:06:42.929262 [ 76511 ] <Fatal> BaseDaemon: 3. abort @ 0x7fa76b9d3859 in ?
[psod5na8b] 2023.03.19 14:06:42.944971 [ 76511 ] <Fatal> BaseDaemon: 4. ./build_docker/../src/Daemon/BaseDaemon.cpp:466: terminate_handler() @ 0xe3cb59c in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:42.946671 [ 76511 ] <Fatal> BaseDaemon: 5. ./build_docker/../contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:61: std::__terminate(void (*)()) @ 0x1a4a36e3 in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:42.968724 [ 76511 ] <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/../contrib/llvm-project/libcxxabi/src/cxa_exception_storage.cpp:97: __cxa_get_globals_fast
[psod5na8b] 2023.03.19 14:06:42.968801 [ 76511 ] <Fatal> BaseDaemon: 6. ./build_docker/../contrib/llvm-project/libcxxabi/src/cxa_handlers.cpp:79: std::terminate() @ 0x1a4a364e in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:43.650453 [ 76511 ] <Fatal> BaseDaemon: 7. ? @ 0x89e174b in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.320591 [ 76511 ] <Fatal> BaseDaemon: 8. ? @ 0x10afa615 in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.424644 [ 76511 ] <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/optional:260: ~__optional_destruct_base
[psod5na8b] 2023.03.19 14:06:44.424725 [ 76511 ] <Fatal> BaseDaemon: 9. ./build_docker/../src/Storages/StorageS3.cpp:758: DB::StorageS3Sink::~StorageS3Sink() @ 0x141e7a3b in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.448083 [ 76511 ] <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/src/include/atomic_support.h:74: std::__shared_weak_count::__release_shared[abi:v15000]()
[psod5na8b] 2023.03.19 14:06:44.448148 [ 76511 ] <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702: ~shared_ptr
[psod5na8b] 2023.03.19 14:06:44.448174 [ 76511 ] <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:63: void std::__destroy_at[abi:v15000]<std::shared_ptr<DB::IProcessor>, 0>(std::shared_ptr<DB::IProcessor>*)
[psod5na8b] 2023.03.19 14:06:44.448188 [ 76511 ] <Fatal> BaseDaemon: 10.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:88: void std::destroy_at[abi:v15000]<std::shared_ptr<DB::IProcessor>, 0>(std::shared_ptr<DB::IProcessor>*)
[psod5na8b] 2023.03.19 14:06:44.448228 [ 76511 ] <Fatal> BaseDaemon: 10.5. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317: void std::allocator_traits<std::allocator<std::shared_ptr<DB::IProcessor>>>::destroy[abi:v15000]<std::shared_ptr<DB::IProcessor>, void, void>(std::allocator<std::shared_ptr<DB::IProcessor>>&, std::shared_ptr<DB::IProcessor>*)
[psod5na8b] 2023.03.19 14:06:44.448255 [ 76511 ] <Fatal> BaseDaemon: 10.6. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/vector:833: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::__base_destruct_at_end[abi:v15000](std::shared_ptr<DB::IProcessor>*)
[psod5na8b] 2023.03.19 14:06:44.448284 [ 76511 ] <Fatal> BaseDaemon: 10.7. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/vector:827: std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>::__clear[abi:v15000]()
[psod5na8b] 2023.03.19 14:06:44.448303 [ 76511 ] <Fatal> BaseDaemon: 10.8. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/vector:436: ~vector
[psod5na8b] 2023.03.19 14:06:44.448320 [ 76511 ] <Fatal> BaseDaemon: 10.9. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:63: void std::__destroy_at[abi:v15000]<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, 0>(std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>*)
[psod5na8b] 2023.03.19 14:06:44.448341 [ 76511 ] <Fatal> BaseDaemon: 10.10. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/construct_at.h:88: void std::destroy_at[abi:v15000]<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, 0>(std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>*)
[psod5na8b] 2023.03.19 14:06:44.448370 [ 76511 ] <Fatal> BaseDaemon: 10.11. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317: void std::allocator_traits<std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::destroy[abi:v15000]<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, void, void>(std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>&, std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>*)
[psod5na8b] 2023.03.19 14:06:44.448393 [ 76511 ] <Fatal> BaseDaemon: 10. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:309: std::__shared_ptr_emplace<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>, std::allocator<std::vector<std::shared_ptr<DB::IProcessor>, std::allocator<std::shared_ptr<DB::IProcessor>>>>>::__on_zero_shared() @ 0x129a88c1 in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.463400 [ 76511 ] <Fatal> BaseDaemon: 11.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/src/include/atomic_support.h:74: long std::(anonymous namespace)::__libcpp_atomic_load[abi:v15000]<long>(long const*, int)
[psod5na8b] 2023.03.19 14:06:44.463456 [ 76511 ] <Fatal> BaseDaemon: 11.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/src/memory.cpp:108: std::__shared_weak_count::__release_weak()
[psod5na8b] 2023.03.19 14:06:44.463485 [ 76511 ] <Fatal> BaseDaemon: 11.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:216: std::__shared_weak_count::__release_shared[abi:v15000]()
[psod5na8b] 2023.03.19 14:06:44.463514 [ 76511 ] <Fatal> BaseDaemon: 11.4. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702: ~shared_ptr
[psod5na8b] 2023.03.19 14:06:44.463536 [ 76511 ] <Fatal> BaseDaemon: 11. ./build_docker/../src/QueryPipeline/QueryPipeline.cpp:41: DB::QueryPipeline::~QueryPipeline() @ 0x129ab01a in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.482324 [ 76511 ] <Fatal> BaseDaemon: 12. ./build_docker/../src/QueryPipeline/QueryPipeline.cpp:567: DB::QueryPipeline::reset() @ 0x129b00bb in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.517909 [ 76511 ] <Fatal> BaseDaemon: 13. ./build_docker/../src/Server/TCPHandler.cpp:515: DB::TCPHandler::runImpl() @ 0x1496617c in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.570621 [ 76511 ] <Fatal> BaseDaemon: 14. ./build_docker/../src/Server/TCPHandler.cpp:2013: DB::TCPHandler::run() @ 0x1497a839 in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.572709 [ 76511 ] <Fatal> BaseDaemon: 15. ./build_docker/../base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x17888b94 in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.575577 [ 76511 ] <Fatal> BaseDaemon: 16.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<Poco::Net::TCPServerConnection>::operator()[abi:v15000](Poco::Net::TCPServerConnection*) const
[psod5na8b] 2023.03.19 14:06:44.575637 [ 76511 ] <Fatal> BaseDaemon: 16.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
[psod5na8b] 2023.03.19 14:06:44.575660 [ 76511 ] <Fatal> BaseDaemon: 16.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
[psod5na8b] 2023.03.19 14:06:44.575674 [ 76511 ] <Fatal> BaseDaemon: 16. ./build_docker/../base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x17889dbb in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.579080 [ 76511 ] <Fatal> BaseDaemon: 17. ./build_docker/../base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x17a11647 in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.582180 [ 76511 ] <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/../base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::get()
[psod5na8b] 2023.03.19 14:06:44.582237 [ 76511 ] <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/../base/poco/Foundation/include/Poco/SharedPtr.h:139: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::assign(Poco::Runnable*)
[psod5na8b] 2023.03.19 14:06:44.582258 [ 76511 ] <Fatal> BaseDaemon: 18.3. inlined from ./build_docker/../base/poco/Foundation/include/Poco/SharedPtr.h:180: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::operator=(Poco::Runnable*)
[psod5na8b] 2023.03.19 14:06:44.582274 [ 76511 ] <Fatal> BaseDaemon: 18. ./build_docker/../base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x17a0f07d in /usr/bin/clickhouse
[psod5na8b] 2023.03.19 14:06:44.582307 [ 76511 ] <Fatal> BaseDaemon: 19. ? @ 0x7fa76bbab609 in ?
[psod5na8b] 2023.03.19 14:06:44.582346 [ 76511 ] <Fatal> BaseDaemon: 20. __clone @ 0x7fa76bad0133 in ?
[psod5na8b] 2023.03.19 14:06:44.736025 [ 76511 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 8824F31A4B3F865A6B24588FCEB7ED45)
```

**Comment by Pipboyguy** [comment] 2023-03-19 15:52
@alexey-milovidov Which data do I need to add? Thank you

**Comment by den-crane** [comment] 2023-03-19 17:50
@Pipboyguy pp-complete.csv 

If it reproduce with any file, it worth to mention it.

**Comment by alexey-milovidov** [comment] 2023-03-20 01:29
I have seen a similar bug report (std::terminate after an unhandled exception in the destructor of a write buffer), and I remember @Avogar did something in this regard. But I don't see the version info in this bug report.

**Comment by alexey-milovidov** [comment] 2023-03-20 01:36
Maybe this is relevant: https://github.com/ClickHouse/ClickHouse/pull/39424

**Comment by tavplubix** [comment] 2023-03-20 11:17
Related to https://github.com/ClickHouse/ClickHouse/issues/47620

**Comment by alexey-milovidov** [comment] 2023-06-24 04:34
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/47620.

**Closed by alexey-milovidov** 2023-06-24 04:34 UTC
Labels: duplicate, st-need-info, potential bug
