### ISSUE TITLE
Asynchronous INSERTs mode

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18282] opened 2020-12-21 05:33 UTC
**Use case**
Thousands of clients concurrently sending data to clickhouse-server for insertion.
Every client sending a small batch of data but the total traffic can be large.

This scenario is popular for logs and metrics.
Alternatives: clickhouse-bulk, kittenhouse.

**Describe the solution you'd like**
Provide a setting (0/1) to enable asynchronous inserts.

If the setting is enabled, a queue of buffers will be maintained for every distinct INSERT query (distincted by query text without data, e.g. `INSERT INTO table FORMAT TSV`) and user. Also we can introduce a setting to differentiate and make multiple queues for identical INSERTS (like internal sharding).

The data sent by client will be read into a buffer without parsing and put to the queue. If the queue does not exist, the INSERT query will be parsed and interpreted (syntax is checked, table is found, data streams are prepared).

A thread pool will run tasks for every queue. A task will parse data (see `RowInputFormat::resetParser` and its usage in `StorageKafka` to parse multiple small buffers) and form blocks for insertion when specified thresholds are met (see `IRowInputFormat`) and perform INSERT. If queue is empty for specified amount of time, it will be destroyed (so, we will not indefinitely "hold" tables, that were dropped).

Another setting (0/1) to control whether client will wait for query result or not.
If set to 1, client will setup a "future" and wait for it. When data will be inserted (possibly accumulated together with data from other connections), client will be notified about the result (success or exception). Parsing errors should be sent back to the corresponding clients and only the erroneous parts of data will be skipped. Insertion errors may happen due to the data of another clients and reported to multiple clients. CONSTRAINTs checking may be performed on per-client data but it's unnecessarily.

The asynchronous mode should have it's own thresholds to form inserted block by amount of bytes, records and time.

**How it's better than Buffer tables**
We will only do memcpy and a little amount of synchronization per client request.
The overhead of query parsing and interpretation is shared among multiple client requests.

**Desired result**
I expect up to 5 mln inserted records per second and up to 20 k opened and closed connections per second (the latter is limited by the implementation of HTTP server).

**Comment by json-lrj** [comment] 2021-01-27 03:19
i have do some similar works, i implement a file based insert log queue behind distributed engine, and all shard insert requests are group committed to this log queue by a leader request。by default, requests will block until insert data is flushed into log queue file. and every insert log queue has a working thread, just do group sync log queue to remote shard. data format in log queue file  is similar to distributed .bin file, and insert logs can do group sync based on their insert header / settings.

**Comment by abyss7** [comment] 2021-02-10 18:46
Additional consideration about access rights: in practice they can change for an user between inserts. But checking them too often will beat the whole idea. So the point is to check them not too often for each user - maybe the interval should be adjustable via setting.

**Comment by abyss7** [comment] 2021-02-12 15:44
Also discussed following details:

- Setting is per-query based, it's not a special server mode. Each distinct insert query may be async and may be not.
- If sync insert query matches any queue from async insert, the queue is left untouched - no forced flush.
- Because insert queries are distinguished on syntax-based query hashing, potentially earlier inserted values may be stored after the later ones for a single table. It's expected behavior. E.g. `INSERT INTO t FORMAT TSV` vs. `INSERT INTO t FORMAT CSV`.

**Comment by azat** [comment] 2021-06-17 09:55
>i have do some similar works, i implement a file based insert log queue behind distributed engine, and all shard insert requests are group committed to this log queue by a leader request。by default, requests will block until insert data is flushed into log queue file. and every insert log queue has a working thread, just do group sync log queue to remote shard. data format in log queue file is similar to distributed .bin file, and insert logs can do group sync based on their insert header / settings.

@json-lrj but INSERT into Distributed already can do batching, does using the following settings differs from your approach?

- `distributed_directory_monitor_batch_inserts=1`
- `distributed_directory_monitor_sleep_time_ms=300000`
- `distributed_directory_monitor_max_sleep_time_ms=300000`

**Comment by CurtizJ** [comment] 2021-09-20 17:17
Implemented in #20557 and #27537.

**Closed** 2021-09-20 17:17 UTC
Labels: feature
