### ISSUE TITLE
Replicated databases and pre-created tables on shared disks

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#47283] opened 2023-03-06 23:57 UTC
**Use case**

If I have a disk with a pre-created table on the **Ordinary** database, I can ATTACH it using the table name exactly as it was created. This is inconvenient because: - I cannot change the table name; - Ordinary database engine is deprecated.

If I have a disk with a pre-created table on the **Atomic** database, I can ATTACH it to either the **Atomic** or **Replicated** database, specifying the table's UUID.

But in the case of the **Replicated** database, it stops working on adding new replicas, as the database engine tries to create all the existing tables on the new replica, replacing the ATTACH query to CREATE query, and the CREATE query does not work with explicit UUID.

**How to reproduce**

Create a security group in AWS EC2 that allows inbound connections to ports 2181 and 9000 within the same security group and ssh from your machine.

Prepare two scripts:

```
$ cat install-keeper.sh
#!/bin/sh

export DEBIAN_FRONTEND=noninteractive
curl https://clickhouse.com/ | sh
./clickhouse install

echo "
keeper_server:
    tcp_port: 2181
    server_id: 1
    log_storage_path: '/var/lib/clickhouse/coordination/log'
    snapshot_storage_path: '/var/lib/clickhouse/coordination/snapshots'

    coordination_settings:
        operation_timeout_ms: 10000
        session_timeout_ms: 30000
        raft_logs_level: trace

    raft_configuration:
        server:
            id: 1
            hostname: '127.0.0.1'
            port: 9444

zookeeper:
    node:
        port: 2181
        host: '127.0.0.1'
" > /etc/clickhouse-server/config.d/keeper.yaml

echo "
listen_host: '::'
" > /etc/clickhouse-server/config.d/listen.yaml

clickhouse start
```

```
$ cat install-clickhouse.sh.in
#!/bin/sh

export DEBIAN_FRONTEND=noninteractive
curl https://clickhouse.com/ | sh
./clickhouse install

echo "
zookeeper:
    node:
        port: 2181
        host: '{keeper_host}'
" > /etc/clickhouse-server/config.d/keeper.yaml

echo "
listen_host: '::'
" > /etc/clickhouse-server/config.d/listen.yaml

echo "
macros:
    shard: 'default'
    replica: '"$(hostname)"'
" > /etc/clickhouse-server/config.d/macros.yaml

clickhouse start

while true
do
    clickhouse-client --allow_experimental_database_replicated true --multiquery --query "
        DROP DATABASE default;
        CREATE DATABASE default ENGINE = Replicated('/clickhouse/databases/default', '{shard}', '{replica}')
    " && break
    sleep 1
done
```

Run Keeper instance:

```
aws ec2 run-instances --count 1 --image-id ami-0d1ddd83282187d18 --instance-type t3.small --key-name milovidov --security-group-ids sg-03db98dfea5faae3e --instance-initiated-shutdown-behavior terminate --user-data file://install-keeper.sh | tee keeper.json | jq --raw-output --join-output '.Instances[].PrivateIpAddress' > keeper_host.txt
```

Run any number of worker instances:

```
sed "s/{keeper_host}/$(cat keeper_host.txt)/" install-clickhouse.sh.in > install-clickhouse.sh

aws ec2 run-instances --count 10 --image-id ami-0d1ddd83282187d18 --instance-type t3.small --key-name milovidov --security-group-ids sg-03db98dfea5faae3e --instance-initiated-shutdown-behavior terminate --user-data file://install-clickhouse.sh
```

Go to any worker instance and attach a table:
```
ATTACH TABLE github_events UUID '127f4241-4a9b-4ecd-8a84-846b88069cb5'
(
    `file_time` DateTime,
    `event_type` Enum8('CommitCommentEvent' = 1, 'CreateEvent' = 2, 'DeleteEvent' = 3, 'ForkEvent' = 4, 'GollumEvent' = 5, 'IssueCommentEvent' = 6, 'IssuesEvent' = 7, 'MemberEvent' = 8, 'PublicEvent' = 9, 'PullRequestEvent' = 10, 'PullRequestReviewCommentEvent' = 11, 'PushEvent' = 12, 'ReleaseEvent' = 13, 'SponsorshipEvent' = 14, 'WatchEvent' = 15, 'GistEvent' = 16, 'FollowEvent' = 17, 'DownloadEvent' = 18, 'PullRequestReviewEvent' = 19, 'ForkApplyEvent' = 20, 'Event' = 21, 'TeamAddEvent' = 22),
    `actor_login` LowCardinality(String),
    `repo_name` LowCardinality(String),
    `created_at` DateTime,
    `updated_at` DateTime,
    `action` Enum8('none' = 0, 'created' = 1, 'added' = 2, 'edited' = 3, 'deleted' = 4, 'opened' = 5, 'closed' = 6, 'reopened' = 7, 'assigned' = 8, 'unassigned' = 9, 'labeled' = 10, 'unlabeled' = 11, 'review_requested' = 12, 'review_request_removed' = 13, 'synchronize' = 14, 'started' = 15, 'published' = 16, 'update' = 17, 'create' = 18, 'fork' = 19, 'merged' = 20),
    `comment_id` UInt64,
    `body` String,
    `path` String,
    `position` Int32,
    `line` Int32,
    `ref` LowCardinality(String),
    `ref_type` Enum8('none' = 0, 'branch' = 1, 'tag' = 2, 'repository' = 3, 'unknown' = 4),
    `creator_user_login` LowCardinality(String),
    `number` UInt32,
    `title` String,
    `labels` Array(LowCardinality(String)),
    `state` Enum8('none' = 0, 'open' = 1, 'closed' = 2),
    `locked` UInt8,
    `assignee` LowCardinality(String),
    `assignees` Array(LowCardinality(String)),
    `comments` UInt32,
    `author_association` Enum8('NONE' = 0, 'CONTRIBUTOR' = 1, 'OWNER' = 2, 'COLLABORATOR' = 3, 'MEMBER' = 4, 'MANNEQUIN' = 5),
    `closed_at` DateTime,
    `merged_at` DateTime,
    `merge_commit_sha` String,
    `requested_reviewers` Array(LowCardinality(String)),
    `requested_teams` Array(LowCardinality(String)),
    `head_ref` LowCardinality(String),
    `head_sha` String,
    `base_ref` LowCardinality(String),
    `base_sha` String,
    `merged` UInt8,
    `mergeable` UInt8,
    `rebaseable` UInt8,
    `mergeable_state` Enum8('unknown' = 0, 'dirty' = 1, 'clean' = 2, 'unstable' = 3, 'draft' = 4),
    `merged_by` LowCardinality(String),
    `review_comments` UInt32,
    `maintainer_can_modify` UInt8,
    `commits` UInt32,
    `additions` UInt32,
    `deletions` UInt32,
    `changed_files` UInt32,
    `diff_hunk` String,
    `original_position` UInt32,
    `commit_id` String,
    `original_commit_id` String,
    `push_size` UInt32,
    `push_distinct_size` UInt32,
    `member_login` LowCardinality(String),
    `release_tag_name` String,
    `release_name` String,
    `review_state` Enum8('none' = 0, 'approved' = 1, 'changes_requested' = 2, 'commented' = 3, 'dismissed' = 4, 'pending' = 5)
)
ENGINE = MergeTree
ORDER BY (event_type, repo_name, created_at)
SETTINGS disk = disk(type = 'web', endpoint = 'https://clickhouse-public-datasets.s3.amazonaws.com/web/');
```

Everything works perfectly so far.

Then add more worker replicas by running the same command as above, and it breaks.

**Comment by alexey-milovidov** [comment] 2023-03-07 00:05
Option 1 (simple):
- if the query has explicit UUID, don't convert it to CREATE query while creating a new database replica.

Option 2 (advanced):
- allow specifying per-disk path overrides for tables.

Example: 

`SETTINGS path = 'test'`
or
`SETTINGS paths = [('disk1', 'test'), ('disk2', 'a/b/c')]`

(the paths are related to the disk's root)

This will allow avoiding specifying the UUID and having a rigid skeleton directory structure on disk (store/xx/...)

**Comment by tavplubix** [comment] 2023-03-07 16:43
> But in the case of the Replicated database, it stops working on adding new replicas, as the database engine tries to create all the existing tables on the new replica, replacing the ATTACH query to CREATE query, and the CREATE query does not work with explicit UUID.

Seems like the problem is that MergeTree tries to create a data directory for the new table on CREATE, but finds out that the directory already exists. It's related to UUIDs, and there's the same problem with `Ordinary` database: it's impossible to CREATE a table using a `web` disk.

> Option 1 (simple):
>    if the query has explicit UUID, don't convert it to CREATE query while creating a new database replica.

It always has an explicit UUID because Replicated database takes the query from metadata that must contain an explicit UUID.

> Option 2 (advanced):
>    allow specifying per-disk path overrides for tables.

It will bring all disadvantages of `Ordinary` engine back. We can allow that `path` setting for `web` disks only and ignore it for other disks, but then we will have different paths on different disks (`*MergeTree` is not ready for that). And even with custom `path` CREATE queries will fail with the same error: the directory exists.

So I think that the correct way to fix it is to support CREATE queries with `web` disks properly and do not throw the exception because it's expected that the directory on `web` disk already exists.

**Comment by UnamedRus** [comment] 2023-03-07 22:43
> We can allow that path setting for web disks only and ignore it for other disks, but then we will have different paths on different disks (*MergeTree is not ready for that). And even with custom path CREATE queries will fail with the same error: the directory exists.

s3_plain disk currently is far from user friendly, they want table to have the exact same name and database, which is usually what people don't want to be. (IE you created backup to s3_plain and want to restore it to another table or db)

**Comment by alexey-milovidov** [comment] 2023-03-07 23:11
@UnamedRus for backup to s3 you should write `BACKUP ... TO S3`, it works perfectly, instead of `BACKUP TO Disk(s3_plain)`.

**Comment by UnamedRus** [comment] 2023-03-07 23:16
> BACKUP ... TO S3,

Can you attach this backup at table without restoring of backup? 

AFAIK no, so it's not replacement for s3_plain.

**Comment by alexey-milovidov** [comment] 2023-03-08 00:14
> Can you attach this backup at table without restoring of backup?

There is no such feature (yet).
We are looking forward to implementing it.

**Comment by UnamedRus** [comment] 2023-03-27 08:36
> There is no such feature (yet).

You kinda can do that with BACKUP deduplication=0 & s3_plain disk.

**Comment by tavplubix** [comment] 2023-06-02 13:19
Fixed by https://github.com/ClickHouse/ClickHouse/pull/50244

**Closed by tavplubix** 2023-06-02 13:19 UTC
Labels: feature
