### ISSUE TITLE
SummingMergeTree with ORDER BY tuple() does not collapse rows

### ISSUE THREAD

**Issue by absorbb** [ClickHouse/ClickHouse#41697] opened 2022-09-22 15:05 UTC
**Describe what's wrong**

It is possible to create ReplacingMergeTree table without primary and sorting key using the `ORDER BY tuple()` clause.
In this case, ClickHouse stores data in the order of inserting. 
It works for sequence of single row inserts. But if insert data using `INSERT ... SELECT` all row collapses into one.
I'm sure that this is not the way it supposed to work.
>If you want to save data order when inserting data by INSERT ... SELECT queries, set [max_insert_threads = 1](https://clickhouse.com/docs/en/operations/settings/settings#settings-max-insert-threads).

I understand that rows order is not guaranteed in case of `INSERT ... SELECT` 
but i'm sure that it must not cause loss of data.

SummingMergeTree or AggregatingMergeTree works properly - all rows get inserted into table.

**Does it reproduce on recent release?**

Yes.  clickhouse/clickhouse-server:22.8-alpine docker image 

**How to reproduce**

```sql
CREATE TEMPORARY TABLE tmp_table  ("id" Int64,"name" String) ;
insert into tmp_table values (1,'a');
insert into tmp_table values (2,'b');
insert into tmp_table values (3,'c');

CREATE TABLE test8 ("id" Int64,"name" String) ENGINE = ReplacingMergeTree  ORDER BY tuple();
INSERT INTO test8 SELECT * from tmp_table;

select * from test8;
```

**Expected behavior**

1,a
2,b
3,c

**Actual Result**

3,c

**Additional context**

Everything works as expected with SummingMergeTree or AggregatingMergeTree

**Comment by den-crane** [comment] 2022-09-22 16:18
`ORDER BY tuple()` defines collapsing KEY (rule). 

Because all rows in the table have the same KEY, they are collapsed into one row.

**Comment by den-crane** [comment] 2022-09-22 16:25
>Everything works as expected with SummingMergeTree or AggregatingMergeTree

This is the REAL issue, BTW.

**Comment by den-crane** [comment] 2022-09-22 16:28
```
CREATE TABLE test8 ("id" Int64,"name" String, x Int64) ENGINE = SummingMergeTree  ORDER BY tuple() as select * from values ((1,'a', 1), (2,'b',1), (3,'c',1));

optimize table test8 final;

select * from test8;
┌─id─┬─name─┬─x─┐
│  1 │ a    │ 1 │
│  2 │ b    │ 1 │
│  3 │ c    │ 1 │
└────┴──────┴───┘
```

**Comment by absorbb** [comment] 2022-09-22 16:52
A little bit more context:
I need replicated table but without deduplication of repeated IDs.
Only MergeTree engines can be Replicated.
I suppose the `ORDER BY tuple()` solution offered in the [documentation](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#selecting-the-primary-key) is the only viable way to achieve that.
That is why i believe SummingMergeTree and AggregatingMergeTree work as intended.

**Comment by den-crane** [comment] 2022-09-22 17:12
>That contradicts the [documentation](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#selecting-the-primary-key):

It's not. It's stored in order of insertion. But during MERGE rows are collapsed by key, KEY is the same.

**Comment by den-crane** [comment] 2022-09-22 17:13
>Only MergeTree engines can be Replicated.

No. Of course not. All engines are Replicated.

**Comment by den-crane** [comment] 2022-09-22 17:16
May be you need

```
CREATE TABLE test8 ("id" Int64,"name" String) ENGINE = ReplicatedMergeTree  ORDER BY (id ...);
```

**Comment by absorbb** [comment] 2022-09-22 17:22
>CREATE TABLE test8 ("id" Int64,"name" String) ENGINE = ReplicatedMergeTree  ORDER BY (id ...);
I considered that. But won't it be much slower? 
And it still won't allow completely identical rows

**Comment by den-crane** [comment] 2022-09-22 17:49
>I considered that. But won't it be much slower?

No, it will be faster because of compression.

>And it still won't allow completely identical rows

? You misunderstood something. For MergeTree table ORDER BY section defines how to sort data in the table.

**Comment by absorbb** [comment] 2022-09-22 17:57
>? You misunderstood something. For MergeTree table ORDER BY section defines how to sort data in the table.

Yes i did. I didn't realize that MergeTree is not only engine family name but also an engine.
Thank you helping with that.
I guess `ENGINE = MergeTree  ORDER BY tuple()` is what i'm looking for

**Comment by den-crane** [comment] 2022-09-22 18:05
Hint: ORDER BY is really important for CH performance. It defines how data will be ordered and which columns will be included into PRIMARY INDEX. It improves insert/select performance drastically, because the right order improves compression rate and allows to write and read less data. https://kb.altinity.com/engines/mergetree-table-engine-family/pick-keys/

**Comment by canhld94** [comment] 2022-09-23 11:34
> ```sql
> CREATE TABLE test8 ("id" Int64,"name" String, x Int64) ENGINE = SummingMergeTree  ORDER BY tuple() 
> as select * from values ((1,'a', 1), (2,'b',1), (3,'c',1));
> 
> optimize table test8 final;
> 
> select * from test8;
> ┌─id─┬─name─┬─x─┐
> │  1 │ a    │ 1 │
> │  2 │ b    │ 1 │
> │  3 │ c    │ 1 │
> └────┴──────┴───┘
> ```
@den-crane in this example, column name cannot be sum, so what is your expected result?
From the doc:
```
If `columns` not specified, ClickHouse summarizes the values in all columns with a numeric data type that are not in the primary key.
```
If we follow this rule, then the correct result should be:
```
 ┌─id─┬─name─┬─x─┐
 │  6 │ a    │ 3 │
 │  6 │ b    │ 3 │
 │  6 │ c    │ 3 │
 └────┴──────┴───┘
```
Nevertheless, I feel it's doesn't make any sense to have a SummingMergeTree with ORDER BY tuple(). There's also another option to prevent creating tables like that.

**Comment by den-crane** [comment] 2022-09-23 13:52
@canhld94 

I expect 

```
 ┌─id─┬─name─┬─x─┐
 │  6 │ с    │ 3 │ name=any(name) a or b or c
 └────┴──────┴───┘
```
You may check it with

```
CREATE TABLE test8 (artificial_key Int8, "id" Int64,"name" String, x Int64) ENGINE = SummingMergeTree  ORDER BY artificial_key as select * from values ((1, 1,'a', 1), (1, 2,'b',1), (1, 3,'c',1));
```

>Nevertheless, I feel it's doesn't make any sense to have a SummingMergeTree with ORDER BY tuple(). There's also another option to prevent creating tables like that.

It's not about sense, it's about code generalization and documentation consistency. I knew about this unexpected behaviour for years, and I don't care. But I prefer to document or fix all unexpected behaviours.

**Comment by tavplubix** [comment] 2022-09-23 14:10
> Nevertheless, I feel it's doesn't make any sense to have a SummingMergeTree with ORDER BY tuple()

Also I suppose it makes sense for materialized views with `partition by` key to calculate some aggregate for each partition

**Comment by alexey-milovidov** [comment] 2022-09-24 10:29
Let's do nothing about this task.

**Closed by alexey-milovidov** 2022-09-24 10:29 UTC
Labels: minor
