### ISSUE TITLE
JSONEachRow-Import to Array(Object)-Type fails 

### ISSUE THREAD

**Issue by inkrement** [ClickHouse/ClickHouse#36865] opened 2022-05-03 08:56 UTC
I created a table with a `Array(JSON)` column and tried to import using the JSONEachRow FORMAT:

```sql
CREATE TABLE mydb.tbl (
    id UInt64,
    creator JSON, -- works
    tracks Array(JSON) -- does not work
)
ENGINE = MergeTree()
ORDER BY (id);
```

```sh
$  cat data.jsonl | clickhouse-client -q "INSERT INTO mydb.tbl FORMAT JSONEachRow"
```
However, it fails with following error:
> Code: 49. DB::Exception: Cannot write non-finalized ColumnObject: data for INSERT was parsed from stdin: (in query: INSERT INTO mydb.tbl FORMAT JSONEachRow). (LOGICAL_ERROR)

The import works for another JSON-column (creator), but as soon as I add the Array(Object) type it fails. I also tried to deactivate parallel parsing (--input_format_parallel_parsing=0), without success.

Release: 22.4.2 revision 54455

**Comment by CurtizJ** [comment] 2022-05-04 11:12
It's known. Currently `Array(JSON)` is not supported. Duplicate of #36557.

**Closed by CurtizJ** 2022-05-04 11:12 UTC
Labels: potential bug
