### ISSUE TITLE
Live views aren't removed after disconnection (HTTP)

### ISSUE THREAD

**Issue by loyd** [ClickHouse/ClickHouse#22996] opened 2021-04-12 17:46 UTC
**Description**
If the `WATCH` statement is used via HTTP interface for live views with a timeout, the live view isn't removed after disconnection.

**Steps to reproduce the bug**
1. Create a live view:
```
echo 'CREATE LIVE VIEW lv_http WITH TIMEOUT AS SELECT 1' | curl 'http://127.0.0.1:8123/?allow_experimental_live_view=1' --data-binary @-
```
2. Watch it:
```
echo 'WATCH lv_http' | curl 'http://127.0.0.1:8123/?allow_experimental_live_view=1' --data-binary @-
1        1
```
3. Send SIGINT.
4. Check tables after at least 15s:
```
6c59ef6be4f2 :) SHOW TABLES;
┌─name────┐
│ lv_http │
└─────────┘
```

**Which ClickHouse server version to use?**
Checked `21.2.2.8`.

**Expected behavior**
The live view should be removed after a timeout.

**Comment by vzakaznikov** [comment] 2021-04-12 17:55
This most likely means that the HTTP connection is not closed on the server and the live output stream never gets destroyed.

**Comment by vzakaznikov** [comment] 2021-04-12 18:00
@loyd, could you please try specifying `JSONEachRowWithProgress` as the output format? This will force the connection use heartbeats to keep HTTP connection alive. When client abruptly disappears it will force a fault on the next hearbeat and the output stream should close. So the max expected time for the table to be deleted will be `heartbeat period + timeout period`.

**Comment by loyd** [comment] 2021-04-12 18:20
Yep, with `JSONEachRowWithProgress` it works as expected.

I write a library based on HTTP + `RowBinary`. I can switch to `JSONEachRowWithProgress` for `WATCH`, but it's not very convenient. Maybe I should `shutdown` the connection?

**Comment by loyd** [comment] 2021-04-12 18:22
But emergencies are still possible, so the use of `JSONEachRowWithProgress` seems to be a more reliable method.

**Comment by vzakaznikov** [comment] 2021-04-12 20:52
> But emergencies are still possible, so the use of `JSONEachRowWithProgress` seems to be a more reliable method.

Yes, you should only use `JSONEachRowWithProgress` format for `WATCH` queries over the HTTP connection. First, because HTTP connection needs heartbeat messages send periodically from the server to the client, and second, that's the only way the server can detect abruptly terminated client connections.

**Comment by vzakaznikov** [comment] 2021-04-12 20:53
@alexey-milovidov, we can close this issue as the behavior is not a bug in LIVE VIEW tables. The only potential issue is the inability of the ClickHouse server to detect dropped HTTP connections.

**Closed** 2021-04-12 22:05 UTC
Labels: bug experimental, comp-liveview

**Comment by loyd** [comment] 2023-11-12 16:26
After https://github.com/ClickHouse/ClickHouse/pull/42173 it's cannot be removed event with `JSONEachRowWithProgress`.

Should we reopen the issue or create a new one?

**Comment by vzakaznikov** [comment] 2023-11-15 14:45
Hi @loyd, the `WITH TIMEOUT` has been removed and temporary LIVE VIEWs are not supported anymore.
That decision was made by the core team. I have looked if you can use TEMPORARY TABLEs instead however, original WITH TIMEOUT live views were not session dependent and would be only automatically removed when there was no active WATCH queries.   

https://github.com/ClickHouse/ClickHouse/pull/42173
https://github.com/ClickHouse/ClickHouse/pull/52333

**Comment by loyd** [comment] 2023-11-25 06:44
@vzakaznikov, thx for the response. Do you know whether WINDOW VIEW can be used to emulate the semantic of LIVE VIEW?
