### ISSUE TITLE
clickhouse-client doesn't load the host/port config from disk anymore

### ISSUE THREAD

**Issue by cyberhuman** [ClickHouse/ClickHouse#34785] opened 2022-02-21 07:31 UTC
**Describe what's wrong**

Since the upgrade to `v22.2.2.1` the host/port configuration for the `clickhouse-client` is not loaded from disk anymore.

**Does it reproduce on recent release?**
Reproduces on v22.2.2.1.

**How to reproduce**

* Which ClickHouse server version to use
v22.2.2.1

* Which interface to use, if matters
`clickhouse-client`

* Non-default settings, if any
```
cat /etc/clickhouse-client/conf.d/clickhouse-local.xml
<config>
  <host>12.34.56.78</host>
  <port>9876</port>
</config>
```

**Expected behavior**
running `clickhouse-client` uses the `host` / `port` from the config file.

**Error message and/or stacktrace**
```
$ clickhouse-client
ClickHouse client version 22.2.2.1.
Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)
```

**Additional context**
After some investigation, the reason is this functionality was removed in the commit e780c1292d837b03365f4e210d3a270e66257c4f (why?)

**Comment by tavplubix** [comment] 2022-02-21 11:51
Duplicate of #34776

**Closed by tavplubix** 2022-02-21 11:51 UTC
Labels: potential bug

**Comment by vdimir** [comment] 2022-02-21 12:09
@cyberhuman
Thank you for such verbose report!
