### ISSUE TITLE
Code: 252, e.displayText() = DB::Exception: Too many parts (300). Parts cleaning are processing significantly slower than inserts: while write prefix to view src.xxxxx, Stack trace (when copying this message, always include the lines below)

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#23178] opened 2021-04-16 06:45 UTC
hi，

here`s the error messages:
```
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x88b64ca in /usr/bin/clickhouse
1. DB::Exception::Exception<unsigned long&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&) @ 0x8902322 in /usr/bin/clickhouse
2. DB::MergeTreeData::delayInsertOrThrowIfNeeded(Poco::Event*) const @ 0xfd8f51e in /usr/bin/clickhouse
3. DB::PushingToViewsBlockOutputStream::writePrefix() @ 0xf3d044b in /usr/bin/clickhouse
4. DB::PushingToViewsBlockOutputStream::writePrefix() @ 0xf3d046a in /usr/bin/clickhouse
5. DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*) @ 0xf035534 in /usr/bin/clickhouse
6. DB::StorageKafka::streamToViews() @ 0xfc71821 in /usr/bin/clickhouse
7. DB::StorageKafka::threadFunc(unsigned long) @ 0xfc70618 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xf250840 in /usr/bin/clickhouse
9. DB::BackgroundSchedulePool::threadFunction() @ 0xf252837 in /usr/bin/clickhouse
10. ? @ 0xf253602 in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x88f65af in /usr/bin/clickhouse
12. ? @ 0x88fa043 in /usr/bin/clickhouse
13. start_thread @ 0x82de in /usr/lib64/libpthread-2.28.so
14. __clone @ 0xfbe83 in /usr/lib64/libc-2.28.so
 (version 21.4.3.21 (official build))
2021.04.16 14:40:06.118138 [ 3239175 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): Code: 252, e.displayText() = DB::Exception: Too many parts (300). Parts cleaning are processing significantly slower than inserts: while write prefix to view src.src_xxxx, Stack trace (when copying this message, always include the lines below):
```

my config.xml
```
<max_partitions_per_insert_block>0</max_partitions_per_insert_block>
<inactive_parts_to_throw_insert>0</inactive_parts_to_throw_insert>
```

i each insert / drop partition to one partitions,but client cancel query ,is still show in system.progress , and is_cancel=0.

**Comment by melvynator** [comment] 2022-03-01 14:05
This too many insert issues often occurs when you are doing a lot of small insert without batching them, each insert is going to lead to the creation of one part and you are going to quickly end up with too many parts. We recently developed a few new feature to avoid this kind of issue, the async insert: https://clickhouse.com/docs/en/operations/settings/settings/#async-insert

There is also the buffer table that could help you with such a task: https://clickhouse.com/docs/en/engines/table-engines/special/buffer/

**Comment by melvynator** [comment] 2022-03-28 12:23
Closing since I feel like the issue is being addressed by the comment above. Feel free to reopen if not.

**Closed by melvynator** 2022-03-28 12:23 UTC
Labels: question, support-services
