### ISSUE TITLE
Show secondary index sizes?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#17357] opened 2020-11-24 10:49 UTC
**Use case**

This is either a feature or documentation request... I've searched around in `system.` a bit but can't find anything obvious to do this.

It would be great to be able to see the amount of space (both compressed & uncompressed) used by secondary indexes on a table (eg `bloom_filter()` over single or multiple columns). Especially when trying different ngram settings this would be very useful to compare performance vs space used.

**Comment by filimonov** [comment] 2020-11-25 09:22
Duplicate of #7659

**Closed by filimonov** 2020-11-25 09:22 UTC
Labels: comp-skipidx, feature
