### ISSUE TITLE
Error 'Part was found on disk `local_cache` which is not defined in the storage policy' in BC check

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#43688] opened 2022-11-25 17:43 UTC
https://s3.amazonaws.com/clickhouse-test-reports/43297/79d5759da990c0cd2bbb7cbbb60c254de0da0e39/stress_test__msan_.html
```
2022.11.24 01:22:51.283077 [ 257366 ] {} <Error> Application: Caught exception while loading metadata: Code: 479. DB::Exception: Part `all_1_1_0` (`data/test_7/test/all_1_1_0/`) was found on disk `local_cache` which is not defined in the storage policy (defined disks: s3, wrapped disks: ): Cannot attach table `test_7`.`test` from metadata file /var/lib/clickhouse/metadata/test_7/test.sql from query ATTACH TABLE test_7.test (`id` Int32, `key` String) ENGINE = MergeTree ORDER BY tuple() SETTINGS index_granularity = 8192. (UNKNOWN_DISK), Stack trace (when copying this message, always include the lines below):
2022.11.24 01:22:57.269461 [ 257366 ] {} <Error> Application: Code: 479. DB::Exception: Part `all_1_1_0` (`data/test_7/test/all_1_1_0/`) was found on disk `local_cache` which is not defined in the storage policy (defined disks: s3, wrapped disks: ): Cannot attach table `test_7`.`test` from metadata file /var/lib/clickhouse/metadata/test_7/test.sql from query ATTACH TABLE test_7.test (`id` Int32, `key` String) ENGINE = MergeTree ORDER BY tuple() SETTINGS index_granularity = 8192. (UNKNOWN_DISK), Stack trace (when copying this message, always include the lines below):
```

**Comment by Avogar** [comment] 2022-11-25 17:43
@kssenii maybe you can look?

**Comment by tavplubix** [comment] 2022-11-25 18:11
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/41218

**Closed by tavplubix** 2022-11-25 18:11 UTC
Labels: testing
