### ISSUE TITLE
Segfault in 18.16.1 (select from view)

### ISSUE THREAD

**Issue by greenwolf-nsk** [ClickHouse/ClickHouse#4263] opened 2019-02-04 17:36 UTC
Getting segmentation fault ~5-10 times a day when selecting from view (actually, the exact query is a result of joining several views similar to one listed below). 

OS
```
4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux
```

Query is executed every minute.
```sql
create view main_page_views as (
	select dtm, dictGetString('apps', 'name', toUInt64(coalesce(app, -1))) as platform, engine, engine_version, coalesce(position, 100) as position, count() as views 
	from 
		(select x, app, engine, engine_version, position from main_page_block_shows where event_datetime > now() - 24 * 60 * 60)
		all inner join
		(select x, toStartOfMinute(event_datetime) as dtm from item_views where toStartOfMinute(event_datetime) = toStartOfMinute(now()) - 120 )
		using(x)
	group by dtm, platform, engine, engine_version, position
	order by dtm, platform, engine, engine_version, position
)
```
Table schemas: 
```sql
CREATE TABLE item_views (
    user_id Nullable(UInt64),
    microcat_id UInt64,
    item_id UInt64,
    shop_id Nullable(UInt64),
    owner_id UInt64,
    location_id UInt64,
    metro_id Nullable(UInt64),
    x Nullable(String),
    life_time UInt64,
    owner_is_company UInt8,
    category_id UInt64,
    event_date Date,
    event_datetime DateTime,
    event_id UInt64,
    src_id Nullable(UInt8),
    cookie_id Nullable(String),
    app Nullable(UInt8)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(event_date)
ORDER BY event_datetime


CREATE TABLE main_page_block_shows (
    microcategoryid Nullable(UInt64),
    x String,
    srcp String,
    position Nullable(UInt64),
    engine_version String,
    engine String,
    categoryid Nullable(UInt64),
    event_date Date,
    event_datetime DateTime,
    event_id UInt64,
    src_id Nullable(UInt8),
    cookie_id Nullable(String),
    app Nullable(UInt8)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(event_date)
ORDER BY event_datetime
```

clickhouse-sever.log
```
2019.02.04 18:36:01.926645 [ 55 ] {12023ea8-4334-48a2-9da8-280758f750a7} <Debug> executeQuery: Query pipeline:
Union
 Converting
  Expression
   Expression
    Materializing
     Expression
      MergeSorting
       PartialSorting
        CreatingSets
         Lazy
         Expression
          Expression
           Materializing
            Expression
             MergeSorting
              PartialSorting
               Expression
                ParallelAggregating
                 Expression × 27
                  MergeTreeThread
 Converting
  Expression
   Expression
    Materializing
     Expression
      MergeSorting
       PartialSorting
        CreatingSets
         Lazy
         Expression
          Expression
           Materializing
            Expression
             MergeSorting
              PartialSorting
               Expression
                ParallelAggregating
                 Expression × 29
                  MergeTreeThread
2019.02.04 18:36:01.926880 [ 7718 ] {12023ea8-4334-48a2-9da8-280758f750a7} <Trace> CreatingSetsBlockInputStream: Creating join.
2019.02.04 18:36:01.926924 [ 7719 ] {12023ea8-4334-48a2-9da8-280758f750a7} <Trace> CreatingSetsBlockInputStream: Creating join.
2019.02.04 18:36:01.928430 [ 7719 ] {12023ea8-4334-48a2-9da8-280758f750a7} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition `toStartOfMinute(event_datetime) = (toStartOfMinute(now()) - 120)` moved to PREWHERE
2019.02.04 18:36:01.928430 [ 7718 ] {12023ea8-4334-48a2-9da8-280758f750a7} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition `toStartOfMinute(event_datetime) = (toStartOfMinute(now()) - 120)` moved to PREWHERE
2019.02.04 18:36:01.929821 [ 7718 ] {12023ea8-4334-48a2-9da8-280758f750a7} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition `toStartOfMinute(event_datetime) = (toStartOfMinute(now()) - 120)` moved to PREWHERE
2019.02.04 18:36:01.929833 [ 2 ] {} <Error> BaseDaemon: ########################################
2019.02.04 18:36:01.929890 [ 2 ] {} <Error> BaseDaemon: (from thread 7719) Received signal Segmentation fault (11).
2019.02.04 18:36:01.929900 [ 2 ] {} <Error> BaseDaemon: Address: 0x3f800008
2019.02.04 18:36:01.929907 [ 2 ] {} <Error> BaseDaemon: Access: write.
2019.02.04 18:36:01.929913 [ 2 ] {} <Error> BaseDaemon: Address not mapped to object.
```

clickhouse-server.err.log
```
2019.02.04 18:36:01.929890 [ 2 ] {} <Error> BaseDaemon: (from thread 7719) Received signal Segmentation fault (11).
2019.02.04 18:36:01.929900 [ 2 ] {} <Error> BaseDaemon: Address: 0x3f800008
2019.02.04 18:36:01.929907 [ 2 ] {} <Error> BaseDaemon: Access: write.
2019.02.04 18:36:01.929913 [ 2 ] {} <Error> BaseDaemon: Address not mapped to object.
2019.02.04 18:36:02.022218 [ 2 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(std::__cxx11::_List_base<DB::NameAndTypePair, std::allocator<DB::NameAndTypePair> >::_M_clear()+0x4b) [0x32c7a4b]
2019.02.04 18:36:02.023174 [ 2 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::SyntaxAnalyzer::analyze(std::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned long) const+0x3c1a) [0x6f9d50a]
2019.02.04 18:36:02.023228 [ 2 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::QueryProcessingStage::Enum, unsigned long, bool)+0x416) [0x6ed2676]
2019.02.04 18:36:02.023250 [ 2 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::QueryProcessingStage::Enum, unsigned long, bool)+0x56) [0x6ed3706]
2019.02.04 18:36:02.023273 [ 2 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::QueryProcessingStage::Enum, unsigned long, bool)+0x7e7) [0x6edf3f7]
2019.02.04 18:36:02.023293 [ 2 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::shared_ptr<DB::IAST> const&, DB::Context const&)+0x12a) [0x6ee08da]
2019.02.04 18:36:02.023310 [ 2 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::getNamesAndTypeListFromTableExpression(DB::ASTTableExpression const&, DB::Context const&)+0x62) [0x744e042]
2019.02.04 18:36:02.023331 [ 2 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::SyntaxAnalyzer::analyze(std::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned long) const+0xc12) [0x6f9a502]
2019.02.04 18:36:02.023356 [ 2 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::QueryProcessingStage::Enum, unsigned long, bool)+0x416) [0x6ed2676]
2019.02.04 18:36:02.023387 [ 2 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::QueryProcessingStage::Enum, unsigned long, bool)+0x56) [0x6ed3706]
2019.02.04 18:36:02.023406 [ 2 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::QueryProcessingStage::Enum, unsigned long, bool)+0x7e7) [0x6edf3f7]
2019.02.04 18:36:02.023438 [ 2 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::StorageView::read(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int)+0x2d0) [0x74eb050]
2019.02.04 18:36:02.023458 [ 2 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x1685) [0x6eceb75]
2019.02.04 18:36:02.023491 [ 2 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x41e) [0x6ed0e4e]
2019.02.04 18:36:02.023511 [ 2 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x4e) [0x6ed3a5e]
2019.02.04 18:36:02.023527 [ 2 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x6c) [0x6ede3bc]
2019.02.04 18:36:02.023542 [ 2 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::execute()+0x38) [0x6ede688]
2019.02.04 18:36:02.023556 [ 2 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server() [0x74704a2]
2019.02.04 18:36:02.023572 [ 2 ] {} <Error> BaseDaemon: 18. /usr/bin/clickhouse-server(DB::LazyBlockInputStream::readImpl()+0x7f) [0x70afcaf]
2019.02.04 18:36:02.023587 [ 2 ] {} <Error> BaseDaemon: 19. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6d6ac6a]
2019.02.04 18:36:02.023599 [ 2 ] {} <Error> BaseDaemon: 20. /usr/bin/clickhouse-server(DB::CreatingSetsBlockInputStream::createOne(DB::SubqueryForSet&)+0x14db) [0x72fb1fb]
2019.02.04 18:36:02.023611 [ 2 ] {} <Error> BaseDaemon: 21. /usr/bin/clickhouse-server(DB::CreatingSetsBlockInputStream::readPrefixImpl()+0x4f) [0x72fde6f]
2019.02.04 18:36:02.023626 [ 2 ] {} <Error> BaseDaemon: 22. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::readPrefix()+0x7a) [0x6d630fa]
2019.02.04 18:36:02.023641 [ 2 ] {} <Error> BaseDaemon: 23. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::readPrefix()+0x59) [0x6d630d9]
2019.02.04 18:36:02.023663 [ 2 ] {} <Error> BaseDaemon: 24. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::readPrefix()+0x59) [0x6d630d9]
2019.02.04 18:36:02.023679 [ 2 ] {} <Error> BaseDaemon: 25. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::readPrefix()+0x59) [0x6d630d9]
2019.02.04 18:36:02.023696 [ 2 ] {} <Error> BaseDaemon: 26. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::readPrefix()+0x59) [0x6d630d9]
2019.02.04 18:36:02.023710 [ 2 ] {} <Error> BaseDaemon: 27. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::readPrefix()+0x59) [0x6d630d9]
2019.02.04 18:36:02.023727 [ 2 ] {} <Error> BaseDaemon: 28. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::readPrefix()+0x59) [0x6d630d9]
2019.02.04 18:36:02.023744 [ 2 ] {} <Error> BaseDaemon: 29. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::readPrefix()+0x59) [0x6d630d9]
2019.02.04 18:36:02.023762 [ 2 ] {} <Error> BaseDaemon: 30. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x15d) [0x6edc9dd]
2019.02.04 18:36:02.023798 [ 2 ] {} <Error> BaseDaemon: 31. /usr/bin/clickhouse-server(std::thread::_State_impl<std::thread::_Invoker<std::tuple<DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::process()::{lambda()#1}> > >::_M_run()+0x4f) [0x6edcf6f]
2019.02.04 18:36:02.023813 [ 2 ] {} <Error> BaseDaemon: 32. /usr/bin/clickhouse-server() [0xa94e40f]
2019.02.04 18:36:02.023826 [ 2 ] {} <Error> BaseDaemon: 33. /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7f085dad8494]
```

**Comment by vitlibar** [comment] 2019-02-05 16:24
Can you please install `clickhouse-common-static-dbg` and `binutils` and then show what output the following two lines produce: 
```
addr2line -iCe /usr/bin/clickhouse-server 0x32c7a4b
addr2line -iCe /usr/bin/clickhouse-server 0x6f9d50a
```

**Comment by greenwolf-nsk** [comment] 2019-02-05 19:08
>addr2line -iCe /usr/bin/clickhouse-server 0x32c7a4b
```
/usr/include/c++/7/bits/shared_ptr_base.h:151
/usr/include/c++/7/bits/shared_ptr_base.h:684
/usr/include/c++/7/bits/shared_ptr_base.h:1123
/usr/include/c++/7/bits/shared_ptr.h:93
/tmp/buildd/clickhouse-18.16.1/build/../dbms/src/Core/NamesAndTypes.h:16
/usr/include/c++/7/ext/new_allocator.h:140
/usr/include/c++/7/bits/alloc_traits.h:487
/usr/include/c++/7/bits/list.tcc:76
```

> addr2line -iCe /usr/bin/clickhouse-server 0x6f9d50a
```
/usr/include/c++/7/bits/stl_list.h:442
/usr/include/c++/7/bits/stl_list.h:733
/tmp/buildd/clickhouse-18.16.1/build/../dbms/src/Core/NamesAndTypes.h:37
/tmp/buildd/clickhouse-18.16.1/build/../dbms/src/Interpreters/SyntaxAnalyzer.cpp:267
/tmp/buildd/clickhouse-18.16.1/build/../dbms/src/Interpreters/SyntaxAnalyzer.cpp:142
```

**Comment by greenwolf-nsk** [comment] 2019-02-05 19:11
Also, there are several different addresses appearing in segfaults:
> grep "Received signal Segmentation fault" -A 3  clickhouse-server.err.log
```
2019.02.05 17:12:01.536792 [ 2 ] {} <Error> BaseDaemon: (from thread 115263) Received signal Segmentation fault (11).
2019.02.05 17:12:01.536815 [ 2 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.02.05 17:12:01.536822 [ 2 ] {} <Error> BaseDaemon: Access: read.
2019.02.05 17:12:01.536828 [ 2 ] {} <Error> BaseDaemon: Unknown si_code.
--
2019.02.05 19:43:02.061100 [ 2 ] {} <Error> BaseDaemon: (from thread 44282) Received signal Segmentation fault (11).
2019.02.05 19:43:02.061108 [ 2 ] {} <Error> BaseDaemon: Address: 0x3f800008
2019.02.05 19:43:02.061114 [ 2 ] {} <Error> BaseDaemon: Access: write.
2019.02.05 19:43:02.061119 [ 2 ] {} <Error> BaseDaemon: Address not mapped to object.
--
2019.02.05 20:05:01.724331 [ 2 ] {} <Error> BaseDaemon: (from thread 16500) Received signal Segmentation fault (11).
2019.02.05 20:05:01.724341 [ 2 ] {} <Error> BaseDaemon: Address: 0x20000000c
2019.02.05 20:05:01.724347 [ 2 ] {} <Error> BaseDaemon: Access: read.
2019.02.05 20:05:01.724353 [ 2 ] {} <Error> BaseDaemon: Address not mapped to object.
--
2019.02.05 20:31:01.677897 [ 2 ] {} <Error> BaseDaemon: (from thread 19822) Received signal Segmentation fault (11).
2019.02.05 20:31:01.677905 [ 2 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.02.05 20:31:01.677911 [ 2 ] {} <Error> BaseDaemon: Access: read.
2019.02.05 20:31:01.677917 [ 2 ] {} <Error> BaseDaemon: Unknown si_code.
--
2019.02.05 20:37:01.851773 [ 2 ] {} <Error> BaseDaemon: (from thread 4191) Received signal Segmentation fault (11).
2019.02.05 20:37:01.851784 [ 2 ] {} <Error> BaseDaemon: Address: 0x3f800008
2019.02.05 20:37:01.851791 [ 2 ] {} <Error> BaseDaemon: Access: write.
2019.02.05 20:37:01.851797 [ 2 ] {} <Error> BaseDaemon: Address not mapped to object.
--
2019.02.05 20:59:01.447341 [ 2 ] {} <Error> BaseDaemon: (from thread 16354) Received signal Segmentation fault (11).
2019.02.05 20:59:01.447349 [ 2 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.02.05 20:59:01.447355 [ 2 ] {} <Error> BaseDaemon: Access: read.
2019.02.05 20:59:01.447360 [ 2 ] {} <Error> BaseDaemon: Unknown si_code.
--
2019.02.05 21:34:01.895659 [ 2 ] {} <Error> BaseDaemon: (from thread 26430) Received signal Segmentation fault (11).
2019.02.05 21:34:01.895672 [ 2 ] {} <Error> BaseDaemon: Address: 0x78
2019.02.05 21:34:01.895695 [ 2 ] {} <Error> BaseDaemon: Access: read.
2019.02.05 21:34:01.895709 [ 2 ] {} <Error> BaseDaemon: Address not mapped to object.
```

**Comment by alexey-milovidov** [comment] 2019-11-11 09:22
This looks relevant to https://github.com/ClickHouse/ClickHouse/pull/7601
@azat FYI

**Comment by azat** [comment] 2019-11-11 10:05
Yep, but there is no `PushingToViewsBlockOutputStream` in the stacktrace, either because of the optimizations or lack of debug symbols.

@greenwolf-nsk can you get the stacktrace with the debug symbols installed? (also note that you need to install them before starting clickhouse-server, since stacktrace resolving is cached).

**Comment by alexey-milovidov** [comment] 2020-01-20 20:04
Dangling references to Context were fixed.

But the root cause (bad code structure around passing Context) is not fixed.

**Closed by alexey-milovidov** 2020-01-20 20:04 UTC
Labels: crash
