### ISSUE TITLE
Connection reset by peer: While executing HDFS

### ISSUE THREAD

**Issue by jiangdaokun** [ClickHouse/ClickHouse#29287] opened 2021-09-23 09:17 UTC
ClickHouse server version: 21.8.3.44
I want to use HDFS engine on Clickhouse, Here is the configuration information I added:
<hdfs>
        <hadoop_kerberos_keytab>/etc/hdfs1/conf/hdfs.keytab</hadoop_kerberos_keytab>
        <hadoop_kerberos_principal>hdfs/tdh1@TDHTEST</hadoop_kerberos_principal>
        <hadoop_security_authentication>kerberos</hadoop_security_authentication>
        <hadoop_kerberos_kinit_command>kinit</hadoop_kerberos_kinit_command>
        <libhdfs3_conf>/etc/clickhouse-server/hdfs-site.xml</libhdfs3_conf>
</hdfs>

If my table on hive is empty, the query is OK ; but, if I insert into the hive table, the query will report an error:

Fail to read from HDFS: hdfs://127.0.0.1:8020, file path: /inceptor1/user/hive/warehouse/da.db/hbpangkun/base_agent_info/000000_0. Error: HdfsIOException: InputStreamImpl: cannot read file: /inceptor1/user/hive/warehouse/da.db/hbpangkun/base_agent_info/000000_0, from position 0, size: 1048576.	Caused by: HdfsIOException: InputStreamImpl: all nodes have been tried and no valid replica can be read for Block: [block pool ID: BP-1374395306-127.0.0.1-1593786532593 block ID 1081074342_7334015].		Caused by: HdfsNetworkException: Read 8 bytes failed from "172.30.83.204:50010": (errno: 104) Connection reset by peer: While executing HDFS (version 21.8.3.44 (official build))

**Comment by kssenii** [comment] 2021-09-23 09:23
I don't think this info is enough to reproduce the issue. Your info only says you have kerberos auth for hdfs and we have [tests](https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_storage_kerberized_hdfs/test.py) with kerberos hdfs auth and it works.

**Comment by jiangdaokun** [comment] 2021-09-23 09:39
hive server version: TDH-6.0.2

This is my create table sql.
hive:
CREATE  TABLE da.base_agent_info_oper(
  agent_no string , 
  agent_name string , 
  agent_type string , 
  phoneno string , 
  hdatasign string , 
  hloadtime string , 
  hbatchdate string , 
  hdatasrc string 
)
COMMENT 'test'
CLUSTERED BY ( 
  agent_no) 
INTO 1 BUCKETS
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS ORC TBLPROPERTIES('ORC.COMPRESSION'='SNAPPY');

ck:
CREATE TABLE da.base_agent_info_oper_hdfs
(
    `agent_no` String,
    `agent_name` String,
    `agent_type` String,
    `phoneno` String,
    `hdatasign` String,
    `hloadtime` String,
    `hbatchdate` String,
    `hdatasrc` String
)
ENGINE = HDFS('hdfs://127.0.0.1:8020/inceptor1/user/hive/warehouse/da.db/hbxyoper/base_agent_info_oper/*', 'ORC');

**Comment by kssenii** [comment] 2021-09-23 09:46
> TBLPROPERTIES('ORC.COMPRESSION'='SNAPPY');

Probably it fails because snappy is not supported yet, will be introduced here: https://github.com/ClickHouse/ClickHouse/pull/28628

**Comment by jiangdaokun** [comment] 2021-09-23 10:04
I tried to rebuild hive's table， but I still received the same error

CREATE  TABLE da.base_agent_info_oper(
  agent_no string , 
  agent_name string , 
  agent_type string , 
  phoneno string , 
  hdatasign string , 
  hloadtime string , 
  hbatchdate string , 
  hdatasrc string 
)
COMMENT 'test'
CLUSTERED BY ( 
  agent_no) 
INTO 1 BUCKETS
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' STORED AS ORC ;

**Comment by alexey-milovidov** [comment] 2024-04-27 02:24
We don't support HDFS.

**Closed by alexey-milovidov** 2024-04-27 02:24 UTC
Labels: unexpected behaviour, comp-hdfs
