### ISSUE TITLE
DB::Exception: CREATE AS SELECT is not supported with Replicated databases

### ISSUE THREAD

**Issue by guykoh** [ClickHouse/ClickHouse#37467] opened 2022-05-23 18:14 UTC
select version();
┌─version()┐
 │ 22.5.1.2079 │
└─────┘

create table default.actor_summary
    engine = MergeTree()
    order by ((updated_at, id, name))
    as (
      SELECT id,
      concat(first_name, ' ', last_name) as actor_name
      FROM default.actors
      GROUP BY id
   )

Received exception from server (cloud instance - version 22.5.1.2079):
Code: 344. DB::Exception: CREATE AS SELECT is not supported with Replicated databases. Use separate CREATE and INSERT queries. (SUPPORT_IS_DISABLED)

**Comment by tavplubix** [comment] 2022-05-23 18:29
Duplicate of #35408

**Closed by tavplubix** 2022-05-23 18:29 UTC
Labels: question
