### ISSUE TITLE
<Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below)

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/ClickHouse#24879] opened 2021-06-02 12:55 UTC
2021.06.02 12:53:41.924881 [ 50 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11d0c84e in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x11d0eac6 in /usr/bin/clickhouse
2. DB::ReadBufferFromPocoSocket::ReadBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) @ 0xe8de1ad in /usr/bin/clickhouse
3. DB::TCPHandler::runImpl() @ 0xf64c6be in /usr/bin/clickhouse
4. DB::TCPHandler::run() @ 0xf65f879 in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x11d138af in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x11d152c1 in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0x11e4b9e9 in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x11e4784a in /usr/bin/clickhouse
9. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
10. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.3.12.2 (official build))
2021.06.02 12:53:42.805405 [ 51 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11d0c84e in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x11d0eac6 in /usr/bin/clickhouse
2. DB::HTTPServerRequest::HTTPServerRequest(DB::Context const&, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0xf669c64 in /usr/bin/clickhouse
3. DB::HTTPServerConnection::run() @ 0xf668ad4 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x11d138af in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x11d152c1 in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x11e4b9e9 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x11e4784a in /usr/bin/clickhouse
8. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
9. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.3.12.2 (official build))

**Comment by intfish123** [comment] 2021-06-02 12:55
What's wrong? How can i fix it?

**Comment by den-crane** [comment] 2021-06-03 21:02
Is it reproducible ?

**Comment by intfish123** [comment] 2021-06-06 03:49
Yes, clickhouse server print this error infomation every second.
And I deploy clickhouse sever inside kubernetes with clickhouse-operator.
There are 2 `LoadBalancer` services in k8s, I think 2 `LoadBalancer` services caused this error, but how can i fix it.

**Comment by clowdrgn** [comment] 2021-07-29 09:54
I'm using HaProxy in front of clickhouse having same problem, lot of error logs, How can i fix it? Or just ignore

**Comment by filimonov** [comment] 2022-01-21 12:11
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/23858

**Closed by filimonov** 2022-01-21 12:11 UTC
Labels: question
