### ISSUE TITLE
Update table to date fields using toDateOrNull generates unexpected behaviour

### ISSUE THREAD

**Issue by calebeaires** [ClickHouse/ClickHouse#14227] opened 2020-08-28 19:26 UTC
**Describe the unexpected behaviour**

I have this table with a field `Nullable(my_date)`. I intend to update some field with another date, but sometimes this date may not be set. So, using the query above does change the field value, but with not the expected one.

---
```sql
alter table
  my_db.my_table
update
  my_field = toDateOrNull('2020-08-02')
where name = 'some_name_here'
```
---
**Result**
|  name | dt  |  val |
|---|---|---|
|   Car | 2027-12-08  | Missan  |

---
**Expected Result**
|  name | dt  |  val |
|---|---|---|
|   Car | 2020-08-02  | Missan  |
---
**The problem here** seems to be OrNull word. The result of the update field is `2027-12-08`, but when I use just toDate [`my_field = toDate('2020-08-02')`] the field value is the correct one

**Comment by amosbird** [comment] 2020-08-29 13:48
Your query is invalid (without a where clause). And I cannot reproduce it with current master.

**Comment by calebeaires** [comment] 2020-08-29 16:13
hey @amosbird , thanks for quick answer... about the query:  I've updated the query.

**Comment by amosbird** [comment] 2020-08-29 16:17
Please share a minimal reproduceable case starting with `create table;  insert into; ...`

**Comment by calebeaires** [comment] 2020-08-29 17:24
Here it is

### ClickHouse version = 20.6.4.44

1. Create
```sql
drop table my_table;
create table my_table (
   dt Nullable(Date),
   name Nullable(String)
) engine MergeTree order by tuple();
```
---
2. Insert data: dt field will get TODAY
```sql
insert into my_table (name, dt) values ('car', today());
```
---

3. Select to see what we get
```sql
select * from my_table;
```
Result
name | dt 
-- | -- 
car |2020-08-29 
---
4. Try to update using toDateOrNull (OR NULL)

```sql
alter table
  my_table
update
  dt = toDateOrNull('2020-08-02')
where name = 'car';
```

5. Select:  **a unexpected value 2021-01-05**, not the desired 2020-08-02
```sql
select * from my_table;
```
Result
name | dt 
-- | -- 
car |2021-01-05

**Comment by den-crane** [comment] 2020-08-29 17:50
It seems all CH version affected. And not only Date type.

```
create table my_table ( i Nullable(UInt64),name Nullable(String)
) engine MergeTree order by tuple();

insert into my_table (name, i) values ('car', 111);

alter table my_table update  i = toUInt64OrNull('333') where name = 'car';

select * from my_table
┌─────────i─┬─name─┐
│ 166990656 │ car  │
└───────────┴──────┘
```

**Comment by amosbird** [comment] 2020-08-29 18:06
I cannot reproduce with current master. Some bisecting is needed...

**Comment by den-crane** [comment] 2020-08-29 18:25
it's actually duplicate of https://github.com/ClickHouse/ClickHouse/issues/13634

**Comment by den-crane** [comment] 2020-08-29 18:28
I can reproduce it with 20.8.1.4497 (gcc)

**Comment by den-crane** [comment] 2020-09-19 17:49
Fixed in https://github.com/ClickHouse/ClickHouse/pull/14646

**Closed by den-crane** 2020-09-19 17:49 UTC
Labels: bug, comp-mutations, duplicate
