### ISSUE TITLE
HTTP Interface fails to parse binary data that begins with certain bytes

### ISSUE THREAD

**Issue by djmarcin** [ClickHouse/ClickHouse#21851] opened 2021-03-18 07:19 UTC
**Describe the unexpected behaviour**
When binary data begins with certain bytes -- such as 0x2c which is also ASCII comma (,) -- the HTTP interface does not treat it as binary data and fails to parse.

**How to reproduce**
Example query:
```
INSERT INTO t FORMAT Protobuf SETTINGS format_schema='storage:TableSchema'
<binary data starting in 2c>
```

**Expected behavior**
Clickhouse should read the binary data as binary data instead of continuing to parse as ASCII. 

**Error message and/or stacktrace**
```
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 97 ('') (line 3, col 1): <binary data after 0x2c>
```

**Additional context**
Is there a delimiter we can pass at the end of our query to indicate that all following bytes are binary data? Or a header we can send on the HTTP interface that would indicate to parse the body as binary and not text? We tried `Content-Type: application/octet-stream` but it had no effect.

**Comment by vdimir** [comment] 2021-03-18 14:38
Could you provide table schema and sample data?

**Comment by filimonov** [comment] 2021-03-18 16:33
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/20343#issuecomment-778065373

Workaround - remove SETTINGS clause, pass settings via URL, i.e.
http://clickhouse:8123/?format_schema=storage:TableSchema&query=INSERT%20INTO%20t%20FORMAT%20Protobuf

**Closed by filimonov** 2021-03-18 16:33 UTC
Labels: comp-http, unexpected behaviour

**Comment by djmarcin** [comment] 2021-03-18 18:27
I should have mentioned that this also fails for whitespace characters such as 0x20 and 0xa. While the comma case is apparently fixed by this workaround, the space cases do not appear to be.

This is successful:
```
(echo -n -e "\x0b\xa2\x06\x08\x20\x20\x20\x20\x20\x20\x20\x20") | curl "http://metawork:metawork@localhost:8123/?format_schema=storage:TestRow&query=INSERT%20INTO%20test%20FORMAT%20Protobuf" -d @-
```

But this, where the initial byte is now 0x0a, or newline, is not:
```
$ (echo -n -e "\x0a\xa2\x06\x07\x20\x20\x20\x20\x20\x20\x20") | curl "http://metawork:metawork@localhost:8123/?format_schema=storage:TestRow&query=INSERT%20INTO%20test%20FORMAT%20Protobuf" -d @-
Code: 444, e.displayText() = DB::Exception: Protobuf messages are corrupted or don't match the provided schema. Please note that Protobuf stream is length-delimited: every message is prefixed by its length in varint. (version 21.3.2.5 (official build))
```

**Comment by djmarcin** [comment] 2021-03-18 18:36
Our current workaround which seems to work is to pad any initial proto that is smaller than 128 bytes to greater than 128 bytes with a dummy field so that the initial byte of the initial length delimiter is always outside the ASCII range.

**Comment by djmarcin** [comment] 2021-03-18 18:57
Some more info:
If I add an additional newline character to the query in the URL, then the data starting with 0x0a (newline) starts working, but that causes the data starting with 0x20 (space) to _stop_ working, so it seems like there's still something wonky going on with the parser.

```
$ (echo -n -e "\x0a\xa2\x06\x07\x20\x20\x20\x20\x20\x20\x20") | curl "http://localhost:8123/?format_schema=storage:TestRow&query=INSERT%20INTO%20test%20FORMAT%20Protobuf%0a" -d @-
$
```


```
$ (echo -n -e "\x20\xa2\x06\x1d\x42\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x42") | curl "http://localhost:8123/?format_schema=storage:TestRow&query=INSERT%20INTO%20test%20FORMAT%20Protobuf%0a" -d @-
Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 21.3.2.5 (official build))
```

**Comment by vdimir** [comment] 2021-03-22 14:45
> But this, where the initial byte is now 0x0a, or newline, is not:

This case works with `curl --data-binary` instead of `curl -d`. In `-d` case newline chars trimmed by `curl`

```
$ (echo -n -e "\x0a\xa2\x06\x07\x20\x20\x20\x20\x20\x20\x20") | curl "http://localhost:8123/?format_schema=storage:TestRow&query=INSERT%20INTO%20test%20FORMAT%20Protobuf" --data-binary @-
$
```

**Comment by djmarcin** [comment] 2021-03-22 20:46
@vdimir

🤦 Thanks for catching that. With `--data-binary` it seems to work for all cases.
