### ISSUE TITLE
PostgreSQL non-default schemas are unsupported

### ISSUE THREAD

**Issue by vialorn** [ClickHouse/ClickHouse#21701] opened 2021-03-13 16:30 UTC
**Describe the unexpected behaviour**
I try to access PostgreSQL data with a query like
```sql
SELECT * FROM postgresql('some_host:5432', 'some_database', 'topology.flat_struct', 'some_user', 'some_password');
```
and get the error below
```
Received exception from server (version 21.2.2):
Code: 1001. DB::Exception: Received from ***.com:9000. DB::Exception: pqxx::undefined_table: ERROR:  relation "topology.flat_struct" does not exist
LINE 1: ...t_id", "port_name", "queue_id", "queue_name" FROM "topology....
```
As I can see, column names were extracted.
Also, I see quotes around, presumably, fully qualified (`topology.flat_struct`) relation name.
PostgreSQL syntax is `select * from "topology"."flat_struct"` not `select * from "topology.flat_struct"`

I ran the query
```sql
created view public.topology_flat_struct
as
select * from topology.flat_struct;
```
on PostgreSQL side and after that the query
```
SELECT * FROM postgresql('some_host:5432', 'some_database', 'topology_flat_struct', 'some_user', 'some_password');
```
on ClickHouse side works just fine.

The query
```sql
select * from "topology.flat_struct";
```
on PostgreSQL side leads to the exception
```
ERROR:  relation "topology.flat_struct" does not exist
LINE 1: select * from "topology.flat_struct";
                      ^
SQL state: 42P01
```

**How to reproduce**
* Which ClickHouse server version to use: `21.2.2`

**Comment by vialorn** [comment] 2021-03-13 16:36
@kssenii

**Comment by nshah14285** [comment] 2021-03-16 08:06
May, I know, when this fix will release?

**Comment by kssenii** [comment] 2021-03-16 09:57
@nshah14285, till the end of this day will be in master.

**Comment by nshah14285** [comment] 2021-03-16 10:23
@kssenii
so when it will be release on stable version? As I am using clickhouse stable version.

**Comment by kssenii** [comment] 2021-03-16 10:27
@nshah14285, it is not a bug fix, so it will not be backported to previos versions. It will be only in master and all futher releases.

**Comment by alexey-milovidov** [comment] 2021-03-16 10:35
> so when it will be release on stable version?

They are released once a month - the next release 21.4 will be in April.

**Comment by nshah14285** [comment] 2021-03-16 10:42
@kssenii 

Thank You.

**Comment by vialorn** [comment] 2021-03-16 19:55
> it is not a bug fix, so it will not be backported to previos versions

Do I get it right - the 21.3 LTS release (mentioned at the online-meetup a few days ago) won't get the fix?

**Closed** 2021-03-16 23:10 UTC
Labels: comp-postgre, unfinished code

**Comment by kssenii** [comment] 2021-03-17 07:11
@vialorn, yes, it won't, it will be in 21.4.

**Comment by vialorn** [comment] 2021-03-17 18:47
@kssenii , thanks a lot!

**Comment by keepflooding** [comment] 2021-04-16 08:56
21.4.3.21 - schema quotation is still wrong when creating dictionary with postgresql source.

**Create query**
```
CREATE DICTIONARY dicts.zones
(
    `id` UInt64,
    `channel_id` UInt64 DEFAULT 0,
    `timezone` String DEFAULT '',
    `timezone_seconds` Int64 DEFAULT 0
)
PRIMARY KEY id
SOURCE(POSTGRESQL(
    port 5432
    host 'XXX'
    user 'clickhouse_reader'
    password 'XXX'
    db 'stat'
    table 'clickhouse_dicts.zones'
    invalidate_query 'select max(etl_updated_at) from clickhouse_dicts.zones'
))
LIFETIME(MIN 300 MAX 600)
LAYOUT(HASHED())
```

**Log-entries on pg-server**
```
2021-04-16 15:47:28.512 +07 [16264] clickhouse_reader@stat ERROR:  relation "clickhouse_dicts.zones" does not exist at character 70
2021-04-16 15:47:28.512 +07 [16264] clickhouse_reader@stat STATEMENT:  COPY (SELECT "id", "channel_id", "timezone", "timezone_seconds" FROM "clickhouse_dicts.zones") TO STDOUT
```

**Comment by kssenii** [comment] 2021-04-16 09:11
@keepflooding, because it was added only for table engine / table function. Ok, I'll add for dictionary source also.

**Comment by theonedemon** [comment] 2021-05-24 11:23
@kssenii any news ?

**Comment by kssenii** [comment] 2021-05-24 11:28
@theonedemon, it is available only in 21.3 or all later than 21.5.

**Comment by theonedemon** [comment] 2021-05-24 11:29
no support schema parameter in dictionary config , i tryed 2.1.4 version - not working

**Comment by kssenii** [comment] 2021-05-24 11:31
It is `not` present in 21.4 and 21.5, only in 21.3 and 21.6.

**Comment by vialorn** [comment] 2021-05-26 12:22
@theonedemon , we used a view in `default` schema aiming to the related one in non-default. works just fine, granted there are no security restrictions.
