### ISSUE TITLE
Rewrite `DatabaseFactory` to allow independent registration of database engines

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#56557] opened 2023-11-10 04:45 UTC
Similarly to other factories.

Implement `system.database_engines` similarly to `system.table_engines`.

**Comment by tavplubix** [comment] 2023-11-13 19:15
Looks like a duplicate of https://github.com/ClickHouse/ClickHouse/issues/9136

**Comment by alexey-milovidov** [comment] 2023-11-14 02:46
It indicates how many times I want it :)

**Comment by Kelvinyu1117** [comment] 2023-11-25 20:48
I can probably help, I have briefly skimmed the code and one question in my mind is that which caller should call `registerDatabaseEngine()`?

**Comment by alexey-milovidov** [comment] 2023-11-25 22:11
@Kelvinyu1117, Thank you!
We should do it similarly to `registerStorages`: `registerDatabases` - a function that will be called once in the initialization of ClickHouse client, server, local...

**Comment by Nishchay1571999** [comment] 2023-12-22 09:50
Is this feature still open  to work on? @alexey-milovidov

**Comment by alexey-milovidov** [comment] 2023-12-22 15:17
@Nishchay1571999, yes, it is open to work!

**Closed** 2023-12-30 23:56 UTC
Labels: easy task, development
