### ISSUE TITLE
Orphans file on S3 bucket when using S3 disk as storage for the MergeTree Engines.

### ISSUE THREAD

**Issue by alifirat** [ClickHouse/ClickHouse#54912] opened 2023-09-22 07:15 UTC
**Describe what's wrong**

We have a cluster setup with 2 shards using the S3 disk as storage and we have observed a significant difference between the data reported by ClickHouse (30TB) and the data displayed on AWS (45TB, indicating an additional 15TB).

```sql
SELECT formatReadableSize(sum(total_bytes))
FROM cluster('mycluster', system.tables)
SETTINGS distributed_group_by_no_merge = 0
FORMAT TSV

Query id: f5c31251-32ec-4887-b758-11769e2d4a78

28.37 TiB
```

**Does it reproduce on recent release?**

This issue appears in:
- 22.8 
- 23.3 

**Enable crash reporting**

N/A

**How to reproduce**

See #52393

**Expected behavior**

The amount of total returned by ClickHouse system tables must match the amount of data in the S3 bucket.

**Error message and/or stacktrace**

I see a lot of errors like: 
```
Cannot quickly remove directory /data/disk_00/clickhouse/disks/mydisk/store/c1b/c1b00b75-1ef4-4e19-90bc-4a29a70e7b16/delete_tmp_20230822_736304_736304_0 by removing files; fallback to recursive removal. Reason: Poco::Exception. Code: 1000, e.code() = 104, Connection reset by peer (version 22.8.4.7 (official build))
```
The previous error is also on S3. 

**Additional context**
This bug has been reported by multiple users from the OSS version: 
- #52393 
- #52387 
- #36048
- #52015

**Comment by CheSema** [comment] 2023-09-22 13:48
It is hard to provide any comment here, because I do not see any logs to make a conclusion here.
But you have collected similar issues, where I was able to provide comment. I think your problem has the similar traits.

**Comment by alexey-milovidov** [comment] 2023-09-22 13:49
Does it use "zero-copy replication"?

**Comment by alexey-milovidov** [comment] 2023-09-22 13:57
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/52393

**Comment by alifirat** [comment] 2023-09-25 13:41
Hey @alexey-milovidov 

Can you help to figure how many PUT should I expect for a single insert:
- with N columns 
- that generates M parts 

In the `system.query_log` table I would like to match with the theorical number of PUT that I should expect.

**Comment by den-crane** [comment] 2023-09-25 17:39
@alifirat check s3 bucket for objects with unfinished mulitpart uploads, https://aws.amazon.com/blogs/aws-cloud-financial-management/discovering-and-deleting-incomplete-multipart-uploads-to-lower-amazon-s3-costs/

(you can configure automatic removal of them in s3 bucket configs (expired >2 days)

**Comment by den-crane** [comment] 2023-09-25 17:41
>Can you help me to figure how many PUT should I expect for a single insert:
>    with N columns
>    that generates M parts

it depends on column types and part types.

Compact part stores all columns using 2 files(objects), data.bin, data.mrk
Wide part stores at least 2 files(objects) (up to 8 files(objects)) per column.

**Comment by den-crane** [comment] 2023-09-25 17:47
>Why it can go up to 8 files per column for the Wide part?

right,  6 files , for modern Clickhouse

```
A Array(LowCardinality(Nullable(String)))

A.bin
A.cmrk2
A.dict.bin
A.dict.cmrk2
A.size0.bin
A.size0.cmrk2
```

**Comment by den-crane** [comment] 2023-09-25 17:49
>Already did and it doesn't explain the gap of 15TB between ClickHouse and AWS.

No idea then, I would look for orphans by comparing AWS s3 objects with `system.remote_data_paths`

**Comment by alifirat** [comment] 2023-09-25 17:58
`remote_data_paths` is refering to the active data in your ClickHouse, not the orphans files on S3.

**Comment by den-crane** [comment] 2023-09-25 18:00
> `remote_data_paths` is refering to the active data in your ClickHouse cluster, not the orphans files on S3.

I meant make a list of all objects from bucket and compare it with `remote_data_paths` from all servers, I understand that it's impossible task, but I don't know other way.

**Comment by den-crane** [comment] 2023-09-25 18:06
at least you can compare number of objects

**Comment by alifirat** [comment] 2023-09-25 18:07
You can do it with AWS Athena to detect the files that are referenced on S3 (using the AWS S3 inventory) but not anymore on ClickHouse metadata.

**Comment by den-crane** [comment] 2023-09-25 18:21
@alifirat do use freeze? backups?

alter table test_s3 freeze;

alter table test_s3 drop partition '2023-01-01';

select count() from test_s3;
┌─count()─┐
│       0 │
└─────────┘

select * from system.remote_data_paths;
0 rows in set. Elapsed: 0.003 sec.



I am not sure (I have zero knowledge about it) but I think this should help https://clickhouse.com/docs/en/sql-reference/statements/alter/partition#unfreeze-partition

```
/usr/local/bin/aws s3 ls --recursive  s3://xxxx/denis/s3cached/|wc -l
84

alter table test_s3 unfreeze WITH NAME '4';

/usr/local/bin/aws s3 ls --recursive  s3://xxxx/denis/s3cached/|wc -l
0

**Comment by alifirat** [comment] 2023-09-25 18:23
On this cluster, we never used a such operation.

**Comment by alexey-milovidov** [comment] 2023-09-25 18:32
Just in case: https://github.com/ClickHouse/clickhouse-docs/issues/1385 (this is unfinished list of items)

**Comment by alifirat** [comment] 2023-09-25 18:37
On AWS, I've activated multiple dashboard to track any potentials errors and I would come back with the details, to help a bit the next people in this situation.

**Comment by alifirat** [comment] 2023-09-27 10:09
Hi, I'm coming back with more details about the issue. 

This is the number of PUT made my ClickHouse cluster: 

<img width="1179" alt="Screenshot 2023-09-27 at 09 34 23" src="https://github.com/ClickHouse/ClickHouse/assets/5478865/23c42e8c-a083-4383-86a4-00a2c22fd16a">

This is the number of 5XX errors on the same time range (a SlowDown must be part of it) 
<img width="1179" alt="Screenshot 2023-09-27 at 09 35 46" src="https://github.com/ClickHouse/ClickHouse/assets/5478865/24a91ae6-0e7f-49b2-9aa3-6a03a21469fe">

This is the number of POST request made, that corresponds to the `DeleteObjects` 
<img width="1179" alt="Screenshot 2023-09-27 at 09 42 01" src="https://github.com/ClickHouse/ClickHouse/assets/5478865/6e0cfd60-3389-4348-9f46-8ff9fb9b70cf">

As you can see, Clickhouse is indeed deleting some files, with very few 5XX errors and while the number of PUT may high, we can compute the number of active partition by looking to the `remote_data_path`. 
```sql
SELECT uniqExact(splitByChar('/', remote_path)[2]) AS partition
FROM system.remote_data_paths
ORDER BY partition ASC

Query id: 16fc4ec3-bff9-433c-9574-17e12e3fa039

┌─partition─┐
│     17576 │
└───────────┘
```

Using the same tables, we can count the number of active object in the S3 bucket: 
```
SELECT count(1)
FROM system.remote_data_paths

Query id: 66feb800-cbe2-42d2-a3ae-15a41b75f1e8

┌─count()─┐
│  470961 │
└─────────┘
```

Now let's compare the previous number with the total objects on the S3 buckets
<img width="516" alt="Screenshot 2023-09-27 at 11 58 33" src="https://github.com/ClickHouse/ClickHouse/assets/5478865/3c23defc-5103-4e61-b8f9-63af399bd6f7">

I have almost 20 times more of objects that are orphans file not deleting by ClickHouse. Let's zoom on a specific file: 

```
aws s3 ls s3://mybucket/mypathaaa/qpgpgshmafqiruwdrwipogmpailne
2023-09-26 07:58:09    2716217 qpgpgshmafqiruwdrwipogmpailne

SELECT
    local_path,
    remote_path
FROM system.remote_data_paths
WHERE remote_path = 'mypath/aaa/qpgpgshmafqiruwdrwipogmpailne'

Query id: ed129668-35aa-40b8-b451-8b4b457104bb

Ok.
```

As you can see, Clickhouse is not referencing anymore the object in the metadata. Let's try to see if we can grep it in the `/disks/{my_disk}` folder. 

```
sudo grep "aaa/qpgpgshmafqiruwdrwipogmpailne" /data/disk_00/clickhouse/disks/mybucket -ri
grep: /data/disk_00/clickhouse/disks/databucket/store/343/343a7ca0-fc7d-4bde-af44-221a91f4b83b/delete_tmp_20230928_47_47_0: No such file or directory
```
About the last one, I'm suspecting that is data was leak on S3 resulting to a merge that didn't drop the file. 

Finally, let's see if we are able to find something in the logs. 

```
cd /var/log/clickhouse
sudo grep -i "qpgpgshmafqiruwdrwipogmpailne" clickhouse-server.err.log result to nothing
sudo grep -i "qpgpgshmafqiruwdrwipogmpailne" clickhouse-server.log result to nothing
sudo zgrep -i "qpgpgshmafqiruwdrwipogmpailne" clickhouse-server.log.0.gz result to nothing 
sudo zgrep -i "qpgpgshmafqiruwdrwipogmpailne" clickhouse-server.err.log.0.gz
```

As you can see, I've 0 trace for this file so I have no idea of:
- where it comes from? 
- why it has not been removed. 

Also, I take the time to look the issues and I've added 2 new ones related to the issue so I think there is really something wrong on the data removal from the s3 bucket.

**Comment by CheSema** [comment] 2023-09-27 11:17
As I mention in https://github.com/ClickHouse/ClickHouse/issues/52387 23.3 had an issue
details:
https://github.com/ClickHouse/ClickHouse/issues/52387#issuecomment-1731389173

Do you observe such behaviour on 23.8 as well? Are there some steps to reproduce it?

**Comment by alifirat** [comment] 2023-09-27 11:25
I'll try to reproduce on the 23.8 and come back to you

**Comment by alifirat** [comment] 2023-09-27 11:30
Just @CheSema do I need to activate this setting s3_strict_upload_part_size?

**Comment by tavplubix** [comment] 2023-09-27 11:55
> Just @CheSema do I need to activate this setting s3_strict_upload_part_size?

@alifirat, probably yes, see https://github.com/ClickHouse/ClickHouse/issues/52387.

> How to reproduce
> See https://github.com/ClickHouse/ClickHouse/issues/52393

So it's a duplicate of https://github.com/ClickHouse/ClickHouse/issues/52393. Let's close this and continue in See https://github.com/ClickHouse/ClickHouse/issues/52393. 

If you believe that it's another issue, then please provide relevant logs demonstrating the issue. From the information you provided above I see that some blobs remained on s3, but this information is not useful because it does not explain why. We need some logs/diagnostics that show why orphaned blobs remain on s3.

> I see a lot of errors like:
> Cannot quickly remove directory /data/disk_00/clickhouse/disks/mydisk/store/c1b/c1b00b75-1ef4-4e19-90bc-4a29a70e7b16/delete_tmp_20230822_736304_736304_0 by removing files; fallback to recursive removal. Reason: Poco::Exception. Code: 1000, e.code() = 104, Connection reset by peer (version 22.8.4.7 (official build))

The stacktrace is missing.

> version 22.8.4.7

This version is obsolete. 22.8 is not supported anymore. Moreover, 22.8.**4** does not contain important bugfixes, the latest version in the 22.8 branch is 22.8.**21**.

**Closed by tavplubix** 2023-09-27 11:55 UTC
Labels: duplicate, st-need-info, comp-s3, potential bug

**Comment by alifirat** [comment] 2023-09-27 12:00
@tavplubix 

I'm going to give a try to the latest release (I have clear plan to test) and come back to you guys. 

Note that I try to provide enough informations that I have in my hands and if I don't, it's because I haven't :-) 

Otherwise I'll be happy to share relevants logs / stack trace so see in few days with I hope some good news!

**Comment by den-crane** [comment] 2023-09-27 18:40
>>Just @CheSema do I need to activate this setting s3_strict_upload_part_size?
> @alifirat, probably yes, see https://github.com/ClickHouse/ClickHouse/issues/52387.

Why?

`s3_strict_upload_part_size / All non-trailing parts must have the same length.` is related to Cloudflare R2, not AWS S3
