### ISSUE TITLE
Wrong result for query with minimal timestamp 1970-01-01 00:00:00

### ISSUE THREAD

**Issue by markheger** [ClickHouse/ClickHouse#33592] opened 2022-01-13 11:18 UTC
During evaluation if `v21.12.3.32` is compatible with our current used release `v20.12.8.2` we observed that some queries does not return the expected rows anymore.

**Version**
```
SELECT version()
┌─version()──┐
│ 21.12.3.32 │
└────────────┘
```

**How to reproduce**

```
CREATE TABLE Test.A
(
    `timestamp` DateTime('UTC'),
    `a` Int
)
ENGINE = MergeTree
PARTITION BY toStartOfWeek(toDateTime(timestamp, 'UTC'))
ORDER BY timestamp
```

```
CREATE TABLE Test.B
(
    `timestamp` DateTime('UTC'),
    `a` Int
)
ENGINE = MergeTree
PARTITION BY toStartOfWeek(toDateTime(timestamp, 'UTC'))
ORDER BY timestamp
```

```
INSERT INTO Test.A VALUES (toDateTime(1559952000,'UTC'), 1)
```

**Expect** one returned row, but none is returned:
```
SELECT toUInt32(timestamp) AS ts
FROM
(
    SELECT DISTINCT timestamp
    FROM Test.A
)
ALL LEFT JOIN
(
    SELECT DISTINCT
        timestamp,
        1 AS exists
    FROM Test.B
) USING (timestamp)
WHERE (exists = 0) AND (timestamp >= '1970-01-01 00:00:00')

Query id: bbea4bca-fbf6-4b00-816a-54f85e3a63bc

Ok.

0 rows in set. Elapsed: 0.018 sec. 
```

**Unexpected workaround**:  Use '1970-01-**04** 00:00:00' instead of '1970-01-01 00:00:00' 
```
SELECT toUInt32(timestamp) AS ts
FROM
(
    SELECT DISTINCT timestamp
    FROM Test.A
)
ALL LEFT JOIN
(
    SELECT DISTINCT
        timestamp,
        1 AS exists
    FROM Test.B
) USING (timestamp)
WHERE (exists = 0) AND (timestamp >= '1970-01-04 00:00:00')

Query id: f0338a9c-64db-4b3d-9c70-93314393233d

┌─────────ts─┐
│ 1559952000 │
└────────────┘

1 rows in set. Elapsed: 0.034 sec. 
```

**Expected behavior**

Should work in the same way as in clickhouse release v20 with minimal timestamp 0 ('1970-01-01 00:00:00')
since we determine the minimum timestamp by the following query:
```
SELECT min(timestamp)
FROM Test.B

┌──────min(timestamp)─┐
│ 1970-01-01 00:00:00 │
└─────────────────────┘
```

**Comment by den-crane** [comment] 2022-01-13 13:46
Can you share `select timezone()` and `select name, value from system.settings where changed`


```
21.12.2.17

SELECT toUInt32(timestamp),timestamp  AS ts
FROM
(
    SELECT DISTINCT timestamp
    FROM Test.A
)
ALL LEFT JOIN
(
    SELECT DISTINCT
        timestamp,
        1 AS exists
    FROM Test.B
) USING (timestamp)
WHERE (exists = 0) AND (timestamp >= '1970-01-04 00:00:00')

┌─toUInt32(timestamp)─┬──────────────────ts─┐
│          1559952000 │ 2019-06-08 00:00:00 │
└─────────────────────┴─────────────────────┘

SELECT toUInt32(timestamp) AS ts
FROM
(
    SELECT DISTINCT timestamp
    FROM Test.A
)
ALL LEFT JOIN
(
    SELECT DISTINCT
        timestamp,
        1 AS exists
    FROM Test.B
) USING (timestamp)
WHERE (exists = 0) AND (timestamp >= '1970-01-04 00:00:00')
┌─────────ts─┐
│ 1559952000 │
└────────────┘

```

**Comment by markheger** [comment] 2022-01-13 15:50
```
SELECT timezone()

┌─timezone()─┐
│ UTC        │
└────────────┘
```

```
SELECT
    name,
    value
FROM system.settings
WHERE changed

┌─name───────────────────────────────┬─value───────┐
│ load_balancing                     │ random      │
│ any_join_distinct_right_table_keys │ 1           │
│ joined_subquery_requires_alias     │ 0           │
│ max_memory_usage                   │ 10000000000 │
└────────────────────────────────────┴─────────────┘
```

###  1970-01-01 00:00:00
This is the query where row > 0 is expected (using '1970-**01-01** 00:00:00'):
```
SELECT toUInt32(timestamp) AS ts
FROM
(
    SELECT DISTINCT timestamp
    FROM Test.A
)
ALL LEFT JOIN
(
    SELECT DISTINCT
        timestamp,
        1 AS exists
    FROM Test.B
) USING (timestamp)
WHERE (exists = 0) AND (timestamp >= '1970-01-01 00:00:00')

Query id: bbea4bca-fbf6-4b00-816a-54f85e3a63bc

Ok.

0 rows in set. Elapsed: 0.018 sec. 
```

**Comment by den-crane** [comment] 2022-01-13 18:00
somehow it's related to partition pruning and PARTITION BY toStartOfWeek 

```
select toStartOfWeek(toDateTime('1970-01-01 00:00:00'));
┌─toStartOfWeek(toDateTime('1970-01-01 00:00:00'))─┐
│                                       2149-06-03 │
└──────────────────────────────────────────────────┘

select toStartOfWeek(toDateTime('1970-01-04 00:00:00'));
┌─toStartOfWeek(toDateTime('1970-01-04 00:00:00'))─┐
│                                       1970-01-04 │
└──────────────────────────────────────────────────┘
```

minimized example:

```sql
CREATE TABLE A(timestamp DateTime)
ENGINE = MergeTree
PARTITION BY toStartOfWeek(timestamp)
ORDER BY tuple();

INSERT INTO A VALUES (1559952000);

select l.*, r.*
FROM ( SELECT  timestamp FROM A ) l
LEFT JOIN ( SELECT toDateTime(0) timestamp1 where 0) r on (timestamp = timestamp1)
WHERE l.timestamp >= '1970-01-01 00:00:00';
0 rows in set. Elapsed: 0.002 sec.

-- with materialize, the expected result

select l.*, r.*
FROM ( SELECT  timestamp FROM A ) l
LEFT JOIN ( SELECT toDateTime(0) timestamp1 where 0) r on (timestamp = timestamp1)
WHERE l.timestamp >= materialize(toDateTime('1970-01-01 00:00:00'))
┌───────────timestamp─┬──────────timestamp1─┐
│ 2019-06-08 00:00:00 │ 1970-01-01 00:00:00 │
└─────────────────────┴─────────────────────┘
```

**Comment by alexey-milovidov** [comment] 2022-01-13 19:32
21.13 is ok:

```
$ clickhouse-local 
ClickHouse local version 21.13.1.1.

milovidov-desktop :) CREATE TABLE Test.A
                     (
                         `timestamp` DateTime('UTC'),
                         `a` Int
                     )
                     ENGINE = MergeTree
                     PARTITION BY toStartOfWeek(toDateTime(timestamp, 'UTC'))
                     ORDER BY timestamp
                     

CREATE TABLE Test.A
(
    `timestamp` DateTime('UTC'),
    `a` Int
)
ENGINE = MergeTree
PARTITION BY toStartOfWeek(toDateTime(timestamp, 'UTC'))
ORDER BY timestamp

Query id: dd9e7379-43af-4b6e-b5e1-5095dcf41ced


0 rows in set. Elapsed: 0.222 sec. 

Received exception:
Code: 81. DB::Exception: Database Test doesn't exist. (UNKNOWN_DATABASE)

milovidov-desktop :) CREATE TABLE Test.A
                     (
                         `timestamp` DateTime('UTC'),
                         `a` Int
                     )
                     ENGINE = MergeTree
                     PARTITION BY toStartOfWeek(toDateTime(timestamp, 'UTC'))
milovidov-desktop :) CREATE DATABASE Test

CREATE DATABASE Test

Query id: 88ff1f9a-93d6-46d9-9fd0-adbd08e9b153

Ok.

0 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) CREATE TABLE Test.A
                     (
                         `timestamp` DateTime('UTC'),
                         `a` Int
                     )
                     ENGINE = MergeTree
                     PARTITION BY toStartOfWeek(toDateTime(timestamp, 'UTC'))
                     ORDER BY timestamp

CREATE TABLE Test.A
(
    `timestamp` DateTime('UTC'),
    `a` Int
)
ENGINE = MergeTree
PARTITION BY toStartOfWeek(toDateTime(timestamp, 'UTC'))
ORDER BY timestamp

Query id: 17d221b7-25d4-445c-9509-e7284fddd6e7

Ok.

0 rows in set. Elapsed: 0.011 sec. 

milovidov-desktop :) CREATE TABLE Test.B
                     (
                         `timestamp` DateTime('UTC'),
                         `a` Int
                     )
                     ENGINE = MergeTree
                     PARTITION BY toStartOfWeek(toDateTime(timestamp, 'UTC'))
                     ORDER BY timestamp

CREATE TABLE Test.B
(
    `timestamp` DateTime('UTC'),
    `a` Int
)
ENGINE = MergeTree
PARTITION BY toStartOfWeek(toDateTime(timestamp, 'UTC'))
ORDER BY timestamp

Query id: cd390f4f-d075-45e7-aa32-564651067cc3

Ok.

0 rows in set. Elapsed: 0.002 sec. 

milovidov-desktop :) INSERT INTO Test.A VALUES (toDateTime(1559952000,'UTC'), 1)

INSERT INTO Test.A FORMAT Values

Query id: 8a3337c9-0737-49f9-b861-592b7524e4a7

Ok.

1 rows in set. Elapsed: 0.004 sec. 

milovidov-desktop :) SELECT toUInt32(timestamp) AS ts
                     FROM
                     (
                         SELECT DISTINCT timestamp
                         FROM Test.A
                     )
                     ALL LEFT JOIN
                     (
                         SELECT DISTINCT
                             timestamp,
                             1 AS exists
                         FROM Test.B
                     ) USING (timestamp)
                     WHERE (exists = 0) AND (timestamp >= '1970-01-01 00:00:00')

SELECT toUInt32(timestamp) AS ts
FROM
(
    SELECT DISTINCT timestamp
    FROM Test.A
)
ALL LEFT JOIN
(
    SELECT DISTINCT
        timestamp,
        1 AS exists
    FROM Test.B
) USING (timestamp)
WHERE (exists = 0) AND (timestamp >= '1970-01-01 00:00:00')

Query id: 7bc76b39-0a36-4b0c-ac75-a1ea8ca9bbe8


0 rows in set. Elapsed: 0.011 sec. 

Received exception:
Code: 206. DB::Exception: No alias for subquery or table function in JOIN (set joined_subquery_requires_alias=0 to disable restriction). While processing ' (SELECT DISTINCT timestamp FROM Test.A)'. (ALIAS_REQUIRED)

milovidov-desktop :) SELECT toUInt32(timestamp) AS ts
                     FROM
                     (
                         SELECT DISTINCT timestamp
                         FROM Test.A
                     ) a
                     ALL LEFT JOIN
                     (
                         SELECT DISTINCT
                             timestamp,
                             1 AS exists
                         FROM Test.B
                     ) b USING (timestamp)
                     WHERE (exists = 0) AND (timestamp >= '1970-01-01 00:00:00')

SELECT toUInt32(timestamp) AS ts
FROM
(
    SELECT DISTINCT timestamp
    FROM Test.A
) AS a
ALL LEFT JOIN
(
    SELECT DISTINCT
        timestamp,
        1 AS exists
    FROM Test.B
) AS b USING (timestamp)
WHERE (exists = 0) AND (timestamp >= '1970-01-01 00:00:00')

Query id: 999247de-964b-47fe-b655-e7a652796b18

┌─────────ts─┐
│ 1559952000 │
└────────────┘

1 rows in set. Elapsed: 0.005 sec. 

milovidov-desktop :)
```

**Comment by alexey-milovidov** [comment] 2022-01-13 19:35
Yes, most likely it is related to partition pruning and evaluation of monotonic functions around the zero.
CC @amosbird, please validate my thoughts. Looks like the issue is fixed by #29953.

Let's disable partition pruning in all past releases?

**Comment by den-crane** [comment] 2022-01-13 20:28
ah, I made some mistake. No need for a join.

```sql
CREATE TABLE A(timestamp DateTime)
ENGINE = MergeTree
PARTITION BY toStartOfWeek(timestamp)
ORDER BY tuple();

INSERT INTO A VALUES (1559952000);

select * FROM A WHERE timestamp >= toDateTime('1970-01-01 00:00:00');
0 rows in set. Elapsed: 0.004 sec.

select * FROM A WHERE identity(timestamp) >= toDateTime('1970-01-01 00:00:00');
┌───────────timestamp─┐
│ 2019-06-08 00:00:00 │
└─────────────────────┘
```

**Comment by alexey-milovidov** [comment] 2022-01-13 22:10
@den-crane Let's commit this test.

**Comment by amosbird** [comment] 2022-01-15 06:02
> Yes, most likely it is related to partition pruning and evaluation of monotonic functions around the zero. CC @amosbird, please validate my thoughts. Looks like the issue is fixed by #29953. Let's add a test.
> 

It's because the implementation of toStartOf* all have monotonicity set to **always true**, which is not the case before #29953.

Unfortunately, we still have similar issue related to `toDateTime`:

```
SELECT
    1100000000000000000 AS time,
    11000000000000000000 AS time2,
    toDateTime(time),
    toTypeName(time),
    toDateTime(time2),
    toTypeName(time2)
FORMAT Vertical

Row 1:
──────
time:                             1100000000000000000
time2:                            11000000000000000000
toDateTime(1100000000000000000):  2106-02-07 09:28:15
toTypeName(1100000000000000000):  UInt64
toDateTime(11000000000000000000): 1996-03-17 15:05:20
toTypeName(11000000000000000000): UInt64
```

> Let's disable partition pruning in all past releases?

Maybe we should fix the functions' monotonicity property instead.

**Closed** 2022-01-15 13:31 UTC
Labels: bug, st-fixed, comp-optimizers, v21.12-affected

**Comment by den-crane** [comment] 2022-01-15 14:08
>Maybe we should fix the functions' monotonicity property instead.

I suspect this issue existed starting from 20.10 ( I did not check, but it seems no issue in 20.8, and the issue exist in 21.3), and nobody noticed it, so I don't think it is important.

**Comment by markheger** [comment] 2022-01-17 14:18
We are using clickhouse version `20.12.8.2` for long time and want to upgrade to a newer version, but this bug blocks us and prevents upgrading.

Is there any workaround or recommended version to use for our upgrade?

**Comment by amosbird** [comment] 2022-01-17 14:30
> Is there any workaround

You can try what @den-crane did with `identity` but it will slows down queries drastically.

> recommended version to use for our upgrade

#29953 should be in the upcoming release.

**Comment by markheger** [comment] 2022-01-17 14:45
> #29953 should be in the upcoming release.

Upcoming release will 21.12.x.x?
Is there any scheduled release date?
