### ISSUE TITLE
STD_EXCEPTION when trying to remove a table, but not on creation

### ISSUE THREAD

**Issue by alexon1234** [ClickHouse/ClickHouse#51654] opened 2023-06-30 08:51 UTC
**Describe the unexpected behaviour**

I got the error `STD_EXCEPTION` when trying to remove a table containing a long name. 

```
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in rename: File name too long ["clickhouse-server-1/data/store/54a/54ac5549-494f-49c2-b92d-7ee1b378eb93/djAAaHR0cDovL3dhZHVzNDo2MDgxAGRfY2RiNGFhAHRfOGQ4ZjNhZTIyNjZlNGM4ZTkzMjcyMmY4MGNkODI3ZWUAX192YWx1ZSwgX190b3BpYywgX19wYXJ0aXRpb24sIF9fb2Zmc2V0LCBfX3RpbWVzdGFtcCwgX19rZXksIGZhdm9yaXRlX2NvbG9yLCBuYW1lLCBmYXZvcml0ZV9udW1iZXI%3D.sql"] ["/home/alejandro/common-data/clickhouse-server-1/data/metadata_dropped/test.djAAaHR0cDovL3dhZHVzNDo2MDgxAGRfY2RiNGFhAHRfOGQ4ZjNhZTIyNjZlNGM4ZTkzMjcyMmY4MGNkODI3ZWUAX192YWx1ZSwgX190b3BpYywgX19wYXJ0aXRpb24sIF9fb2Zmc2V0LCBfX3RpbWVzdGFtcCwgX19rZXksIGZhdm9yaXRlX2NvbG9yLCBuYW1lLCBmYXZvcml0ZV9udW1iZXI%3D.19cf5580-881f-468c-8140-14ed14faf900.sql"]. (STD_EXCEPTION)
```

I would expect that the exception to be raised on the creation of the table to avoid introducing. Also, as I can not remove it using `DROP TABLE`, I need to do a manual operation to remove the table

**How to reproduce**

```sql
DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
CREATE TABLE test.`djAAaHR0cDovL3dhZHVzNDo2MDgxAGRfY2RiNGFhAHRfOGQ4ZjNhZTIyNjZlNGM4ZTkzMjcyMmY4MGNkODI3ZWUAX192YWx1ZSwgX190b3BpYywgX19wYXJ0aXRpb24sIF9fb2Zmc2V0LCBfX3RpbWVzdGFtcCwgX19rZXksIGZhdm9yaXRlX2NvbG9yLCBuYW1lLCBmYXZvcml0ZV9udW1iZXI=` (number Int64) ENGINE=MergeTree() order by number;
DROP DATABASE test;
```

* Which ClickHouse server version to use

23.3.1

**Comment by tavplubix** [comment] 2023-06-30 12:18
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/37119
See also https://github.com/ClickHouse/ClickHouse/pull/50612

**Closed by tavplubix** 2023-06-30 12:18 UTC
Labels: unexpected behaviour
