### ISSUE TITLE
Bug----->Attempt to read after eof: while converting source column

### ISSUE THREAD

**Issue by jinyan2049** [ClickHouse/ClickHouse#12065] opened 2020-06-30 17:48 UTC
Dear All
my clickhouse version :

SELECT version()

┌─version()─┐
│ 20.4.6.53 │
└───────────┘

and when i want to insert some data from mysql,

The field types on both sides are the same. Focus on this field --->**actualAmount**

Is this a sensitive word? I try to change it to the same field type as mysql, and the display has been successful, but there is an error in inserting data

The following is a detailed error information, please help me, thank you

######################
p-db06 :) alter table BorrowOrders modify column actualAmount Nullable(Decimal(16, 2));

ALTER TABLE BorrowOrders
MODIFY COLUMN
actualAmount Nullable(Decimal(16, 2))

Ok.

0 rows in set. Elapsed: 0.007 sec.

p-db06 :) insert into trade.BorrowOrders SELECT * FROM mysql('10.63.0.3:3306', 'trade', 'BorrowOrders', 'sync', 'aabb1122') limit 1;

INSERT INTO trade.BorrowOrders SELECT *
FROM mysql('10.63.0.3:3306', 'trade', 'BorrowOrders', 'sync', 'aabb1122')
LIMIT 1

Received exception from server (version 20.4.6):
**Code: 32. DB::Exception: Received from localhost:9000. DB::Exception: Attempt to read after eof: while converting source column actualAmount to destination column actualAmount.**

0 rows in set. Elapsed: 0.010 sec.
##########################

**Comment by filimonov** [comment] 2020-06-30 17:58
Please use search first

Duplicate of #4954
Duplicate of #7690

**Closed by filimonov** 2020-06-30 17:58 UTC
Labels: bug
