### ISSUE TITLE
Ubuntu 22.04 clickhouse-client segfault 

### ISSUE THREAD

**Issue by bdoubrovine** [ClickHouse/ClickHouse#47446] opened 2023-03-10 16:10 UTC
OS: ubuntu 22.04 5.15.0-67-generic x86_64
Package version: 23.2.3.17

Symptom : 
```
clickhouse-client --ask-password
Aborted (core dumped)
```

GDB result :
```
Starting program: /usr/bin/clickhouse-client
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5223a3d in ldap_int_client_controls () from /lib/x86_64-linux-gnu/libldap-2.5.so.0
```

**Comment by tavplubix** [comment] 2023-03-10 23:54
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/43933

**Closed by tavplubix** 2023-03-10 23:54 UTC
Labels: potential bug

**Comment by bdoubrovine** [comment] 2023-03-11 09:52
Hello,

to add context, pam-ldap is used on this server.
