### ISSUE TITLE
Failed assertion in jemalloc

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#66193] opened 2024-07-07 21:37 UTC
https://s3.amazonaws.com/clickhouse-test-reports/66126/d685c062a38ddfd605b5c72870ef164396764b12/stateless_tests__debug__[3_5].html

**Describe the bug**
```
2024-07-07 12:55:24 <jemalloc>: /build/contrib/jemalloc/src/decay.c:92: Failed assertion: "nstime_compare(&decay->epoch, new_time) <= 0"
2024-07-07 12:55:24 Aborted (core dumped)
```

**How to reproduce**
No idea, maybe related to the jemalloc profiler added recently. CC @antonio2368

**Comment by alexey-milovidov** [comment] 2024-07-07 22:04
It is something related to the profiler - let's revert it: https://github.com/ClickHouse/ClickHouse/pull/65702

**Comment by antonio2368** [comment] 2024-07-08 06:36
As it only happens for `client` and `local` I disabled profiler and background threads for debug build: https://github.com/ClickHouse/ClickHouse/pull/66041

After this gets merged I will enable it back and investigate https://github.com/ClickHouse/ClickHouse/pull/61109

**Comment by antonio2368** [comment] 2024-07-08 06:40
I checked binary and couple of other failures and it actually doesn't seem related to the profiler changes if it happens after I disabled everything for debug build.
https://s3.amazonaws.com/clickhouse-test-reports/0/7b712918ed46e11483348cf41195d6050e9374e8/stateless_tests__debug__s3_storage__[1_6].html

:thinking:

**Comment by azat** [comment] 2024-07-09 14:46
@antonio2368 Maybe it will be easier to add core dumps into artifacts for stateless tests instead?

**Comment by antonio2368** [comment] 2024-07-09 14:47
I thought about that but I don't think it's worth the effort because we will finish this soon https://github.com/ClickHouse/ClickHouse/pull/61109
It's much better option.

**Comment by azat** [comment] 2024-07-10 12:56
The underlying issue looks like non-monotonic `CLOCK_MONOTONIC` clock, there was issues like this in the past - https://github.com/ClickHouse/ClickHouse/pull/49819, and replacing it with `CLOCK_MONOTONIC_RAW` fixes it, but I decided to play `CLOCK_MONOTONIC` first - https://gist.github.com/azat/7ea7f50ed75591b1af2d675a240ea94c (it has even a mode that emulates clock adjustments, like NTP client does)

The only way I could fail the monotonicity - in case of multi-threads, and indeed the clock is not guaranteed to be synced across the CPU cores, and AFAIU it is possible to break it even in non-multi-threaded env, in case of task migrations, and I've tried to reproduce this by creating tons of threads - no luck.

But, back to jemalloc, the only thing that pops up in my mind is that jemalloc tries to compare `CLOCK_MONOTONIC` from various threads (since this function - `decay_maybe_update_time` - is called with a mutex eventually), which leads to this situation.
Enabling of `background_thread` can be the culprit, but I can't say for sure.

**Comment by antonio2368** [comment] 2024-07-10 13:00
> Enabling of background_thread can be the culprit, but I can't say for sure.

As I said background threads are disabled for debug build for some time now https://github.com/ClickHouse/ClickHouse/pull/66041/files

And I checked the binary itself that failed, background threads are not used.

**Comment by azat** [comment] 2024-07-10 13:15
>As I said background threads are disabled for debug build for some time now

@antonio2368 thanks, forgot about this.

Enabling jemalloc profiler by default indeed looks related, so maybe all recent changes to jemalloc should be reverted, also it does not make sense to enable it by default since you can always enable it on fly - https://github.com/ClickHouse/ClickHouse/pull/65702#issuecomment-2220478177

By "recent changes" I mean:
- https://github.com/ClickHouse/ClickHouse/pull/66041
- https://github.com/ClickHouse/ClickHouse/pull/66028
- https://github.com/ClickHouse/ClickHouse/pull/65834
- https://github.com/ClickHouse/ClickHouse/pull/65702

**Comment by antonio2368** [comment] 2024-07-10 13:20
Profiling cannot be enabled during runtime, only the activity of profiler
check `opt.prof` and `opt.prof_active` https://jemalloc.net/jemalloc.3.html

If we connect it to the time of merges, the [problem](https://play.clickhouse.com/play?user=play#c2VsZWN0IApjaGVja19zdGFydF90aW1lIGQsIHJlcG9ydF91cmwsIHB1bGxfcmVxdWVzdF9udW1iZXIKZnJvbSBjaGVja3MKd2hlcmUKICAgICcyMDI0LTA1LTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X2NvbnRleHRfcmF3IGlsaWtlICclamVtYWxsb2M+JW5zdGltZSUnIGFuZCBjaGVja19uYW1lIGlsaWtlICclc3RhdGVsZXNzJWRlYnVnJScgCiAgICBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJywgJ0VSUk9SJykKb3JkZXIgYnkgZCBkZXNj) started occurring after https://github.com/ClickHouse/ClickHouse/pull/65702 so it's the only suspect PR

**Comment by antonio2368** [comment] 2024-07-10 13:26
Also on the topic of background threads, I really don't know why we are avoiding it so hard if it's the recommended way of running jemalloc and is disabled by default because of some corner cases 

https://github.com/jemalloc/jemalloc/issues/956#issuecomment-316224733 
https://dl.acm.org/doi/10.1145/2742580.2742807

**Comment by azat** [comment] 2024-07-10 13:46
@antonio2368 BTW does https://github.com/ClickHouse/ClickHouse/pull/66041 helps to avoid this assertion temporary?

**Comment by antonio2368** [comment] 2024-07-10 13:47
No it doesn't https://github.com/ClickHouse/ClickHouse/issues/66193#issuecomment-2213162317

You can download the debug binary from that run and you'll see prof is disabled and no background threads are created.

**Comment by antonio2368** [comment] 2024-07-11 06:40
@azat we have a core dump!
https://s3.amazonaws.com/clickhouse-test-reports/66281/ccffc056818c70cf16531f680ae7531bca1b376e/stateless_tests__debug__s3_storage__[1_2].html

**Comment by azat** [comment] 2024-07-11 09:26
@antonio2368 I can't find binary for it, there is no such CI job yet, and I tried to generate URL based on a template - without luck

**Comment by antonio2368** [comment] 2024-07-11 09:28
@azat you can go to https://github.com/ClickHouse/ClickHouse/actions/runs/9875422241/job/27285915750
and at the beginning under run you have:
```
INFO:build_download_helper:The build report for package_debug contains the next URLs: 
```
with list of all URLs

**Comment by azat** [comment] 2024-07-11 09:29
Thanks! Hm, it uses `24.7` prefix, instead of `PRs`.

**Closed** 2024-07-15 07:13 UTC
Labels: testing
