### ISSUE TITLE
Bug #1370 for distributed tables (column hidden by alias) 

### ISSUE THREAD

**Issue by TheRoSS** [ClickHouse/ClickHouse#5300] opened 2019-05-16 08:12 UTC
The bug is still here for distributed tables (19.5.3.8)
(original: https://github.com/yandex/ClickHouse/issues/1370 )

```
> CREATE TABLE gb_refs.currencyRateShard (`date` Date, `base` FixedString(3), `code` FixedString(3), `src` Int8, `rate` Decimal(18, 6)) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/gb_refs/currencyRateShard', '{replica}') PARTITION BY toYYYYMM(date) ORDER BY (date, base, code, src) SETTINGS index_granularity = 8192

> CREATE TABLE gb_refs.currencyRate (`date` Date, `base` FixedString(3), `code` FixedString(3), `src` Int8, `rate` Decimal(18, 6)) ENGINE = Distributed(gamebeat, gb_refs, currencyRateShard, toYYYYMM(date))

> SELECT base,code,MAX(`date`) AS `date` FROM currencyRateShard WHERE `currencyRateShard`.`date`<='2019-03-01' GROUP BY base,code

┌─base─┬─code─┬───────date─┐
│ USD  │ XPT  │ 2019-02-28 │
...

> # The same query but currencyRateShard replaced with currencyRate
> SELECT base,code,MAX(`date`) AS `date` FROM currencyRate WHERE `currencyRate`.`date`<='2019-03-01' GROUP BY base,code

Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.5.3):
Code: 184. DB::Exception: Received from ch-dev-n1.a:9000, 10.0.37.65. DB::Exception: Received from ch-dev-n4.a:9000, 10.0.89.228. DB::Exception: Aggregate function MAX(date) is found in WHERE or PREWHERE in query. 
```

**Comment by 4ertus2** [comment] 2020-10-01 16:26
Reproduced on master
```
CREATE TABLE currencyRateShard (`date` Date, `base` FixedString(3)) ENGINE = MergeTree ORDER BY (date);
CREATE TABLE currencyRate AS currencyRateShard ENGINE = Distributed(test_cluster_two_shards_localhost, currentDatabase(), currencyRateShard);

INSERT INTO currencyRateShard VALUES (0, 'aaa');
INSERT INTO currencyRateShard VALUES (0, 'bbb');

SELECT base, MAX(`date`) AS `date` FROM currencyRateShard WHERE date = toDate(0) GROUP BY base ORDER BY base;
```

**Comment by alexey-milovidov** [comment] 2021-01-09 02:51
Duplicate of #9715.

**Closed by alexey-milovidov** 2021-01-09 02:51 UTC
Labels: duplicate, unexpected behaviour
