### ISSUE TITLE
Projection race condition on check table (errno: 2, strerror: No such file or directory. (FILE_DOESNT_EXIST))

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/ClickHouse#34759] opened 2022-02-19 20:52 UTC
This is hard to reproduce but I will try my best. 

version- `22.2.2.1`

1. Create any replicated merge tree table with 2-3 columns
2. Create a few projections 
3. start writing to the replicated table via some kafka queue connected to a mv 
4. run command `check table` and you will see that _sometimes_ it gives value 0 and the log shows this- 
```
2022.02.19 20:41:53.811855 [ 117 ] {4a266056-05e7-4b83-8c52-db182d32e92a} <Error> default.data (ReplicatedMergeTreePartCheckThread): DB::CheckResult DB::ReplicatedMergeTreePartCheckThread::checkPart(const DB::String &): Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/store/088/088edbb2-2d72-40b0-a9f5-ef4d943899fa/ea01da1bfff9c399d15c28ff390ae152_34_34_0/p_1.proj/<COLUMN_NAME_GOES_HERE>dict.bin, errno: 2, strerror: No such file or directory. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xaebed1a in /usr/bin/clickhouse
1. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0xaec010a in /usr/bin/clickhouse
2. DB::OpenedFile::open(int) @ 0xb08beab in /usr/bin/clickhouse
3. DB::OpenedFileCache::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xb08a435 in /usr/bin/clickhouse
4. DB::ReadBufferFromFilePReadWithDescriptorsCache::ReadBufferFromFilePReadWithDescriptorsCache(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, int, char*, unsigned long, std::__1::optional<unsigned long>) @ 0xb08a070 in /usr/bin/clickhouse
5. ? @ 0xb089a4c in /usr/bin/clickhouse
6. DB::createReadBufferFromFileBase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReadSettings const&, std::__1::optional<unsigned long>, std::__1::optional<unsigned long>, int, char*, unsigned long) @ 0xb089985 in /usr/bin/clickhouse
7. DB::DiskLocal::readFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ReadSettings const&, std::__1::optional<unsigned long>, std::__1::optional<unsigned long>) const @ 0x14548f88 in /usr/bin/clickhouse
8. ? @ 0x15694e3e in /usr/bin/clickhouse
9. ? @ 0x15695b65 in /usr/bin/clickhouse
10. DB::ISerialization::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x14423d91 in /usr/bin/clickhouse
11. DB::SerializationLowCardinality::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x14442403 in /usr/bin/clickhouse
12. DB::ISerialization::enumerateStreams(std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamPath&) const @ 0x14424144 in /usr/bin/clickhouse
13. DB::ISerialization::enumerateStreams(std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&) const @ 0x152de665 in /usr/bin/clickhouse
14. ? @ 0x15693856 in /usr/bin/clickhouse
15. DB::checkDataPart(std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::shared_ptr<DB::IDisk> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::NamesAndTypesList const&, DB::MergeTreeDataPartType const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, std::__1::function<bool ()>) @ 0x15692243 in /usr/bin/clickhouse
16. DB::checkDataPart(std::__1::shared_ptr<DB::IMergeTreeDataPart const>, bool, std::__1::function<bool ()>) @ 0x15695885 in /usr/bin/clickhouse
17. DB::ReplicatedMergeTreePartCheckThread::checkPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15633a62 in /usr/bin/clickhouse
```

I was not able to reproduce the issue when you just insert the data in bulk using CLI (likely due to it being very fast) but when you insert data in batches, you will see the above exception. 

CH will end up removing the data part and the queries return wrong results (I am not sure if there is data loss or not):
```
2022.02.19 20:41:53.811995 [ 117 ] {4a266056-05e7-4b83-8c52-db182d32e92a} <Error> default.data (ReplicatedMergeTreePartCheckThread): Part ea01da1bfff9c399d15c28ff390ae152_34_34_0 looks broken. Removing it and will try to fetch.
2022.02.19 20:41:53.812027 [ 117 ] {4a266056-05e7-4b83-8c52-db182d32e92a} <Information> default.data (088edbb2-2d72-40b0-a9f5-ef4d943899fa): Renaming ea01da1bfff9c399d15c28ff390ae152_34_34_0 to broken_ea01da1bfff9c399d15c28ff390ae152_34_34_0 and forgetting it.
2022.02.19 20:41:53.812308 [ 117 ] {4a266056-05e7-4b83-8c52-db182d32e92a} <Warning> default.data (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part ea01da1bfff9c399d15c28ff390ae152_34_34_0 or covering part.
2022.02.19 20:41:53.815658 [ 117 ] {4a266056-05e7-4b83-8c52-db182d32e92a} <Error> default.data (ReplicatedMergeTreePartCheckThread): No replica has part covering ea01da1bfff9c399d15c28ff390ae152_34_34_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2022.02.19 20:41:53.815717 [ 117 ] {4a266056-05e7-4b83-8c52-db182d32e92a} <Warning> default.data (ReplicatedMergeTreePartCheckThread): Part ea01da1bfff9c399d15c28ff390ae152_34_34_0 exists in ZooKeeper but not locally and not found on other replica. Removing it from ZooKeeper.
2022.02.19 20:41:53.818468 [ 117 ] {4a266056-05e7-4b83-8c52-db182d32e92a} <Information> default.data (088edbb2-2d72-40b0-a9f5-ef4d943899fa): Going to replace lost part ea01da1bfff9c399d15c28ff390ae152_34_34_0 with empty part
2022.02.19 20:41:53.818689 [ 117 ] {4a266056-05e7-4b83-8c52-db182d32e92a} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 147.22 GiB.
2022.02.19 20:41:53.824820 [ 117 ] {4a266056-05e7-4b83-8c52-db182d32e92a} <Information> default.data (088edbb2-2d72-40b0-a9f5-ef4d943899fa): Created empty part ea01da1bfff9c399d15c28ff390ae152_34_34_0 instead of lost part
```
cc @amosbird

**Comment by gauravphoenix** [comment] 2022-02-19 22:17
Here are some additional details to help with the debugging- 

I have two projections on this table, they are of the form - 
1. `select * order by col1,col2`
2. `select max(col),foo group by foo`

if I remove the second type (aggregate projection), I do NOT see issues with `check table` command. So it is possible that something is up when aggregation is used in projections. 

I am not 100% sure though, this is just a quick observation based upon limited data.

**Comment by gauravphoenix** [comment] 2022-02-20 04:02
I can confirm that the issue reproduces only when you use aggregates in the projection. I now have 100s of millions of rows and projections without aggregations (i.e. simple select order by col) work just fine and `check table` shows the value `1`. As soon as I add an aggregation-based projection, after adding 10-20k rows, I start seeing errors (file not found) when I run `check table`.

**Comment by amosbird** [comment] 2022-02-20 04:31
I did some checks and unfortunately cannot reproduce this issue.

>  start writing to the replicated table via some kafka queue connected to a mv

Is kafka queue/mv necessary to reproduce this issue?

>  I was not able to reproduce the issue when you just insert the data in bulk using CLI (likely due to it being very fast) but when you insert data in batches, you will see the above exception.

I'm not sure how there are different.

I also notice there is `SerializationLowCardinality` in the stacktrace. Is LowCardinality necessary to reproduce?

**Comment by gauravphoenix** [comment] 2022-02-20 04:37
in my setup I could only see this issue when I was using kafka. I will get back to you see if I can provide you a ready to use test case

**Comment by aderouineau** [comment] 2022-03-15 00:47
Hello,

I am able to reproduce the issue with the following schema and data on version 22.2:

```
CREATE TABLE test
(
  `a` LowCardinality(String),
  `b` DateTime64,
  `c` String,
  PROJECTION proj
  (
    SELECT a, COUNT(*) AS nb
    GROUP BY a
  )
) ENGINE = ReplacingMergeTree()
PARTITION BY tuple()
ORDER BY (a, b, c);


INSERT INTO test
SELECT
  hex(SHA1(hex(rand() % 100))),
  date_sub(second, rand() % 2592000, NOW()),
  hex(randomString(10))
FROM numbers(10000000);


CHECK TABLE test;

┌─part_path───┬─is_passed─┬─message───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ all_1_6_1   │         0 │ Cannot open file /home/clickhouse/data/clickhouse-data/store/fbc/fbc2b059-963d-4a49-8596-26b2dfe2a26b/all_1_6_1/proj.proj/a.dict.bin, errno: 2, strerror: No such file or directory   │
│ all_7_7_0   │         0 │ Cannot open file /home/clickhouse/data/clickhouse-data/store/fbc/fbc2b059-963d-4a49-8596-26b2dfe2a26b/all_7_7_0/proj.proj/a.dict.bin, errno: 2, strerror: No such file or directory   │
│ all_8_8_0   │         0 │ Cannot open file /home/clickhouse/data/clickhouse-data/store/fbc/fbc2b059-963d-4a49-8596-26b2dfe2a26b/all_8_8_0/proj.proj/a.dict.bin, errno: 2, strerror: No such file or directory   │
│ all_9_9_0   │         0 │ Cannot open file /home/clickhouse/data/clickhouse-data/store/fbc/fbc2b059-963d-4a49-8596-26b2dfe2a26b/all_9_9_0/proj.proj/a.dict.bin, errno: 2, strerror: No such file or directory   │
│ all_10_10_0 │         0 │ Cannot open file /home/clickhouse/data/clickhouse-data/store/fbc/fbc2b059-963d-4a49-8596-26b2dfe2a26b/all_10_10_0/proj.proj/a.dict.bin, errno: 2, strerror: No such file or directory │
└─────────────┴───────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by amosbird** [comment] 2022-03-29 10:55
It should be fixed by https://github.com/ClickHouse/ClickHouse/pull/35667

**Closed by amosbird** 2022-03-29 10:55 UTC
Labels: comp-projections, potential bug
