### ISSUE TITLE
Possible data curruption (?) with s3 zero copy replication 

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/ClickHouse#45346] opened 2023-01-17 03:03 UTC
## Cluster Information

Base version: 22.3
Shard number: 1
Replica number: 4
Storage Policy: s3
Zero Copy: enabled

There were some MERGE stuck problems, such as #43816, #10368, but the case here is different. Not sure if it's related to zero copy.

## Replication Queue Status

Following is the stuck merge entry from the system.replication_queue on each replica.

replica 1

```
replica_name:           replica1
position:               9
node_name:              queue-0005631171
type:                   MERGE_PARTS
create_time:            2023-01-13 15:42:37
required_quorum:        0
source_replica:         replica4
new_part_name:          20230113_277225_277260_2
parts_to_merge:         ['20230113_277225_277225_0','20230113_277226_277226_0','20230113_277227_277232_1','20230113_277233_277238_1','20230113_277239_277245_1','20230113_277246_277252_1','20230113_277253_277260_1']
is_detach:              0
is_currently_executing: 0
num_tries:              2210016
last_exception:         Code: 33. DB::Exception: Cannot read all data. Bytes read: 58587. Bytes expected: 60085.: (while reading column endTimeUs): (while reading from part /mnt/disk/0/clickhouse/data/disks/s3/data/xxx/xxx/20230113_277227_277232_1/ from mark 38 with max_rows_to_read = 7727): While executing MergeTreeSequentialSource. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):
last_attempt_time:      2023-01-16 17:18:08
num_postponed:          1948
postpone_reason:        Not executing log entry queue-0005631171 of type MERGE_PARTS for part 20230113_277225_277260_2 because source parts size (70.32 MiB) is greater than the current maximum (19.80 MiB).
last_postpone_time:     2023-01-14 06:34:18
merge_type:             REGULAR
```

replica 2:

```
replica_name:           replica2
position:               15
node_name:              queue-0005632293
type:                   MERGE_PARTS
create_time:            2023-01-13 15:42:37
required_quorum:        0
source_replica:         replica4
new_part_name:          20230113_277225_277260_2
parts_to_merge:         ['20230113_277225_277225_0','20230113_277226_277226_0','20230113_277227_277232_1','20230113_277233_277238_1','20230113_277239_277245_1','20230113_277246_277252_1','20230113_277253_277260_1']
is_detach:              0
is_currently_executing: 1
num_tries:              1175605
last_exception:         Code: 33. DB::Exception: Cannot read all data. Bytes read: 58587. Bytes expected: 60085.: (while reading column endTimeUs): (while reading from part /mnt/disk/0/clickhouse/data/disks/s3/data/xxx/xxx/detached/broken_20230113_277227_277232_1/ from mark 38 with max_rows_to_read = 7727): While executing MergeTreeSequentialSource. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):
last_attempt_time:      2023-01-16 17:19:54
num_postponed:          603
postpone_reason:        Not executing merge/mutation for the part 20230113_277225_277260_2, waiting other replica to execute it and will fetch after.
last_postpone_time:     2023-01-13 15:43:05
merge_type:             REGULAR
```

replica 3
```
replica_name:           replica3
position:               11
node_name:              queue-0005640976
type:                   MERGE_PARTS
create_time:            2023-01-13 15:42:37
required_quorum:        0
source_replica:         replica4
new_part_name:          20230113_277225_277260_2
parts_to_merge:         ['20230113_277225_277225_0','20230113_277226_277226_0','20230113_277227_277232_1','20230113_277233_277238_1','20230113_277239_277245_1','20230113_277246_277252_1','20230113_277253_277260_1']
is_detach:              0
is_currently_executing: 1
num_tries:              1033025
last_exception:         Code: 33. DB::Exception: Cannot read all data. Bytes read: 58587. Bytes expected: 60085.: (while reading column endTimeUs): (while reading from part /mnt/disk/0/clickhouse/data/disks/s3/data/xxx/xxx/20230113_277227_277232_1/ from mark 38 with max_rows_to_read = 7727): While executing MergeTreeSequentialSource. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):
last_attempt_time:      2023-01-16 17:20:58
num_postponed:          716
postpone_reason:        Not executing merge/mutation for the part 20230113_277225_277260_2, waiting other replica to execute it and will fetch after.
last_postpone_time:     2023-01-13 15:43:26
merge_type:             REGULAR
```

```
replica_name:           replica4
position:               7
node_name:              queue-0005633113
type:                   MERGE_PARTS
create_time:            2023-01-13 15:42:37
required_quorum:        0
source_replica:         replica4
new_part_name:          20230113_277225_277260_2
parts_to_merge:         ['20230113_277225_277225_0','20230113_277226_277226_0','20230113_277227_277232_1','20230113_277233_277238_1','20230113_277239_277245_1','20230113_277246_277252_1','20230113_277253_277260_1']
is_detach:              0
is_currently_executing: 1
num_tries:              4732052
last_exception:         Code: 33. DB::Exception: Cannot read all data. Bytes read: 58587. Bytes expected: 60085.: (while reading column endTimeUs): (while reading from part /mnt/disk/0/clickhouse/data/disks/s3/data/xxx/xxx/20230113_277227_277232_1/ from mark 38 with max_rows_to_read = 7727): While executing MergeTreeSequentialSource. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):
last_attempt_time:      2023-01-16 17:24:00
num_postponed:          2039
postpone_reason:        Not executing merge/mutation for the part 20230113_277225_277260_2, waiting other replica to execute it and will fetch after.
last_postpone_time:     2023-01-13 15:43:26
merge_type:             REGULAR
```

If checking the logs of all 4 replicas, the output for the new part are all the same as follows

```
2023.01.16 15:10:00.125796 [ 244 ] {} <Warning> xxx.xxx (ReplicatedMergeTreePartCheckThread): Checking part 20230113_277225_277260_2
2023.01.16 15:10:00.127379 [ 244 ] {} <Trace> xxx.xxx (ReplicatedMergeTreePartCheckThread): Part 20230113_277225_277260_2 in zookeeper: false, locally: false
2023.01.16 15:10:00.127406 [ 244 ] {} <Warning> xxx.xxx (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part 20230113_277225_277260_2 or covering part.
2023.01.16 15:10:00.145069 [ 244 ] {} <Warning> xxx.xxx (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 20230113_277225_277260_2 on replica replica3. Hoping that it will eventually appear as a result of a merge.
2023.01.16 15:10:00.201719 [ 47 ] {} <Trace> MergeFromLogEntryTask: Executing log entry to merge parts 20230113_277225_277225_0, 20230113_277226_277226_0, 20230113_277227_277232_1, 20230113_277233_277238_1, 20230113_277239_277245_1, 20230113_277246_277252_1, 20230113_277253_277260_1 to 20230113_277225_277260_2
2023.01.16 15:10:00.201759 [ 47 ] {} <Debug> MergeFromLogEntryTask: Don't have all parts for merge 20230113_277225_277260_2; will try to fetch it instead
```

Based on the log, the stuck merge is caused by a missing part. The missed part for the merge is `20230113_277227_277232_1` by using following SQL.

```
select * from (
    select arrayJoin(parts_to_merge) as p from system.replication_queue
    where table = 'xxx'
    and new_part_name = '20230113_277225_277260_2'
) AS A
left join system.parts
on A.p = name

┌─p────────────────────────┬─partition─┬─name─────────────────────┬─uuid─────────────────────────────────┬─part_type─┬─
│ 20230113_277225_277225_0 │ 20230113  │ 20230113_277225_277225_0 │ 00000000-0000-0000-0000-000000000000 │ Wide      │ 
│ 20230113_277226_277226_0 │ 20230113  │ 20230113_277226_277226_0 │ 00000000-0000-0000-0000-000000000000 │ Wide      │ 
│ 20230113_277227_277232_1 │           │                          │ 00000000-0000-0000-0000-000000000000 │           │ 
│ 20230113_277233_277238_1 │ 20230113  │ 20230113_277233_277238_1 │ 00000000-0000-0000-0000-000000000000 │ Wide      │ 
│ 20230113_277239_277245_1 │ 20230113  │ 20230113_277239_277245_1 │ 00000000-0000-0000-0000-000000000000 │ Wide      │ 
│ 20230113_277246_277252_1 │ 20230113  │ 20230113_277246_277252_1 │ 00000000-0000-0000-0000-000000000000 │ Wide      │ 
│ 20230113_277253_277260_1 │ 20230113  │ 20230113_277253_277260_1 │ 00000000-0000-0000-0000-000000000000 │ Wide      │ 
└──────────────────────────┴───────────┴──────────────────────────┴──────────────────────────────────────┴───────────┴─
```

If we check the part_log for the missed part `20230113_277227_277232_1` on all 4 replicas, we can see the logs as following:

```
select FQDN(), * from clusterAllReplicas('cluster_xxx', system.part_log) where part_name = '20230113_277227_277232_1'

┌─FQDN()──────────────┬─query_id─┬─event_type───┬─event_date─┬──────────event_time─┬────event_time_microseconds─┬─duration_ms─┬─database─┬─table─────────┬─part_name────────────────┬─partition_id─┬─part_type─┬─disk_name─┬─path_on_disk────────────────────────────────────────────────────────────────┬───rows─┬─size_in_bytes─┬─merged_from─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─bytes_uncompressed─┬─read_rows─┬─read_bytes─┬─peak_memory_usage─┬─error─┬─exception─┐
│ replica4            │          │ MergeParts   │ 2023-01-13 │ 2023-01-13 15:42:22 │ 2023-01-13 15:42:22.496510 │        6006 │ xxx      │ xxx           │ 20230113_277227_277232_1 │ 20230113     │ Wide      │ s3        │ /mnt/disk/0/clickhouse/data/disks/s3/data/xxx/xxx/20230113_277227_277232_1/ │ 356629 │      14486163 │ ['20230113_277227_277227_0','20230113_277228_277228_0','20230113_277229_277229_0','20230113_277230_277230_0','20230113_277231_277231_0','20230113_277232_277232_0'] │          245411840 │    356629 │  116658000 │          84965849 │     0 │           │
│ replica3            │          │ DownloadPart │ 2023-01-13 │ 2023-01-13 15:42:22 │ 2023-01-13 15:42:22.841771 │         215 │ xxx      │ xxx           │ 20230113_277227_277232_1 │ 20230113     │ Wide      │ s3        │ /mnt/disk/0/clickhouse/data/disks/s3/data/xxx/xxx/20230113_277227_277232_1/ │ 356629 │      14486163 │ ['20230113_277227_277227_0','20230113_277228_277228_0','20230113_277229_277229_0','20230113_277230_277230_0','20230113_277231_277231_0','20230113_277232_277232_0'] │                  0 │         0 │          0 │                 0 │     0 │           │
│ replica2            │          │ DownloadPart │ 2023-01-13 │ 2023-01-13 15:42:22 │ 2023-01-13 15:42:22.932852 │         289 │ xxx      │ xxx           │ 20230113_277227_277232_1 │ 20230113     │ Wide      │ s3        │ /mnt/disk/0/clickhouse/data/disks/s3/data/xxx/xxx/20230113_277227_277232_1/ │ 356629 │      14486163 │ ['20230113_277227_277227_0','20230113_277228_277228_0','20230113_277229_277229_0','20230113_277230_277230_0','20230113_277231_277231_0','20230113_277232_277232_0'] │                  0 │         0 │          0 │                 0 │     0 │           │
│ replica1            │          │ DownloadPart │ 2023-01-13 │ 2023-01-13 15:42:22 │ 2023-01-13 15:42:22.780626 │         234 │ xxx      │ xxx           │ 20230113_277227_277232_1 │ 20230113     │ Wide      │ s3        │ /mnt/disk/0/clickhouse/data/disks/s3/data/xxx/xxx/20230113_277227_277232_1/ │ 356629 │      14486163 │ ['20230113_277227_277227_0','20230113_277228_277228_0','20230113_277229_277229_0','20230113_277230_277230_0','20230113_277231_277231_0','20230113_277232_277232_0'] │                  0 │         0 │          0 │                 0 │     0 │           │
└─────────────────────┴──────────┴──────────────┴────────────┴─────────────────────┴────────────────────────────┴─────────────┴──────────┴───────────────┴──────────────────────────┴──────────────┴───────────┴───────────┴─────────────────────────────────────────────────────────────────────────-───┴────────┴───────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┴───────────┴────────────┴───────────────────┴───────┴───────────┘
```

On ZooKeeper, all 4 replicas exists under the `/clickhouse/zero_copy/zero_copy_s3/{table_id}/20230113_277227_277232_1/{key}`, while there're no such part under the table replica path.

The question here is how could the part `20230113_277227_277232_1` for merge be missed? from the part_log, we don't see there's a REMOVE for that part.

**Comment by tavplubix** [comment] 2023-01-17 13:50
last_exception:         Code: 33. DB::Exception: Cannot read all data. Bytes read: 58587. Bytes expected: 60085.: (while reading column endTimeUs): (while reading from part /mnt/disk/0/clickhouse/data/disks/s3/data/xxx/xxx/20230113_277227_277232_1/ from mark 38 with max_rows_to_read = 7727): While executing MergeTreeSequentialSource. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):


It may (or may not) be data corruption. Please provide more information:
 - Stacktrace of this exception (you can find it in text logs)
 - Table CREATE statement 
 - Does `select * from table_name where where _part='20230113_277227_277232_1'` work?
 - Do you have any non-default settings? (`select * from system.settings where changed`, `select * from system.merge_tree_settings where changed`)

**Comment by den-crane** [comment] 2023-01-17 20:41
it could be a duplicate of https://github.com/ClickHouse/ClickHouse/issues/36687

@FrankChen021 provide `select version()` output

**Comment by FrankChen021** [comment] 2023-01-18 02:30
Hello @tavplubix 

I think it may not be due to data corruption because the last exception of this merge entry is

```
Code: 999. Coordination::Exception: Connection loss, path: /clickhouse/tables/cluster_scs_online-0/xxx.xxx/replicas/replica1/parts. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below)
```

This is because we switched the connected zookeeper yesterday manually (by a SYSTEM command that we implement) in order for balanced zookeeper connections.

And the original stack trace can't be found in the text log because we only keep the logs for 1 day.

## Table CREATE Statement

```sql
CREATE TABLE xxx.xxx ON CLUSTER cluster_scs_online
(
    `timestamp` DateTime64(3),
    `appName` String,
    `instanceName` String,
    `name` String,
    `clazz` String,
    `method` String,
    `traceId` String,
    `spanId` String,
    `parentSpanId` String,
    `kind` String,
    `costTimeMs` Int64,
    `startTimeUs` Int64,
    `endTimeUs` Int64,
    `tags` String,
    `normalizedUrl` String,
    `status` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/xxx.xxx', '{replica}')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (toStartOfHour(timestamp), appName, instanceName, traceId)
SETTINGS storage_policy = 's3'
```

The storage policy configuration template is:

```xml
       <storage_configuration>
           <disks>
               <s3>
                   <type>s3</type>
                    <endpoint>{{ .Values.bucket }}</endpoint>
                    <use_environment_credentials>false</use_environment_credentials>
                   <access_key_id>{{ .Values.access_key_id }}</access_key_id>
                   <secret_access_key>{{ .Values.secret_access_key }}</secret_access_key>
               </s3>
           </disks>
           <policies>
               <s3>
                   <volumes>
                       <main>
                           <disk>s3</disk>
                       </main>
                   </volumes>
               </s3>
           </policies>
       </storage_configuration>
```

## Non-default settings

```text
┌─name──────────────────────────────┬─value───────┬─changed─┬
│ s3_min_upload_part_size           │ 268435456   │       1 │
│ s3_max_single_part_upload_size    │ 268435456   │       1 │
│ use_uncompressed_cache            │ 0           │       1 │
│ background_pool_size              │ 38          │       1 │
│ background_fetches_pool_size      │ 16          │       1 │
│ load_balancing                    │ random      │       1 │
│ skip_unavailable_shards           │ 1           │       1 │
│ log_queries                       │ 1           │       1 │
│ distributed_product_mode          │ local       │       1 │
│ send_progress_in_http_headers     │ 1           │       1 │
│ http_headers_progress_interval_ms │ 1000000     │       1 │
│ max_execution_time                │ 0           │       1 │
│ max_memory_usage                  │ 20000000000 │       1 │
│ max_memory_usage_for_user         │ 0           │       1 │
│ log_query_threads                 │ 0           │       1 │
│ parallel_view_processing          │ 1           │       1 │
│ max_partitions_per_insert_block   │ 1000        │       1 │
│ default_database_engine           │ Ordinary    │       1 │
└───────────────────────────────────┴─────────────┴─────────┴
```

## Non-default table settings

```
┌─name──────────────────────────────────┬─value─┬─changed─┬─
│ parts_to_throw_insert                 │ 600   │       1 │ 
│ max_suspicious_broken_parts           │ 5     │       1 │ 
│ allow_remote_fs_zero_copy_replication │ 1     │       1 │ 
└───────────────────────────────────────┴───────┴─────────┴─
```

## Does select * from table_name where _part='20230113_277227_277232_1' work?

This returns 0 rows.

**Comment by alexey-milovidov** [comment] 2023-04-09 04:48
22.3 is a very old version, that is not supported anymore.

By the way, "zero-copy replication" is still a non-production feature.
ClickHouse prints a huge warning when you try to use it.
The docs also advises against its usage: https://clickhouse.com/docs/en/operations/storing-data#zero-copy

**Closed by alexey-milovidov** 2023-04-09 04:48 UTC
Labels: experimental issue
