### ISSUE TITLE
Unexpected part name: <projection name>

### ISSUE THREAD

**Issue by 2b1q** [ClickHouse/ClickHouse#49913] opened 2023-05-16 11:34 UTC
**INPUTS**
- `ReplicatedMergeTree` table projections (works fine)
- CH ver `23.1.6.42`
- system.mutations for `MATERIALIZE projection` has `is_done` equals to `0` for unexists parts

**Unexpected behaviour**
Hanging MATERIALIZE projection MUTATION in system.mutations for unexists parts

**Expected behavior**
0 system.mutations. 

**Additional info**

1. create particular table projections
2. MATERIALIZE them
3. wait a bit and check system.mutations
```sql
select mutation_id, command, is_done, parts_to_do, parts_to_do_names, latest_fail_reason from system.mutations where is_done=0
┌─mutation_id─┬─command───────────────────────────────────────────┬─is_done─┬─parts_to_do─┬─parts_to_do_names─────────────────────────────────────────────────────────────────────┬─latest_fail_reason─┐
│ 0000000005  │ MATERIALIZE PROJECTION device_agregation          │       0 │           2 │ ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'] │                    │
│ 0000000006  │ MATERIALIZE PROJECTION users_agregation           │       0 │           2 │ ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'] │                    │
│ 0000000007  │ MATERIALIZE PROJECTION messages_agregation        │       0 │           2 │ ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'] │                    │
│ 0000000008  │ MATERIALIZE PROJECTION overlay_session_agregation │       0 │           2 │ ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'] │                    │
└─────────────┴───────────────────────────────────────────────────┴─────────┴─────────────┴───────────────────────────────────────────────────────────────────────────────────────┴────────────────────┘
```
4. check CH tasks/processes
```sql
SELECT * FROM system.processes WHERE query not like 'SELECT%' LIMIT 10 FORMAT Vertical
Ok.

0 rows in set. Elapsed: 0.003 sec. 
```
5.  get part info for stucked parts
```sql
select partition, name, marks, rows, modification_time from system.parts where name IN('b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1')
Ok.

0 rows in set. Elapsed: 0.010 sec. Processed 3.64 thousand rows, 324.88 KB (357.75 thousand rows/s., 31.97 MB/s.)
```
6.  check if there any parts in this partition
```sql
select partition, name, marks, rows, modification_time from system.parts where partition_id IN('b0d8617590929340bbb5fb58cf52bce4', 'b9186c325b4cfa4ca55dcba0e78fd4a3')
┌─partition──┬─name─────────────────────────────────────────────┬─marks─┬───rows─┬───modification_time─┐
│ 20230410PM │ b0d8617590929340bbb5fb58cf52bce4_0_11_2_75       │    75 │ 592459 │ 2023-05-16 09:50:37 │
│ 20230410PM │ b0d8617590929340bbb5fb58cf52bce4_12_17_1_75      │    52 │ 409492 │ 2023-05-16 09:50:37 │
│ 20230410PM │ b0d8617590929340bbb5fb58cf52bce4_18_59_7_75      │    70 │ 561446 │ 2023-05-16 09:50:37 │
│ 20230410PM │ b0d8617590929340bbb5fb58cf52bce4_60_64_1         │    32 │ 250081 │ 2023-05-11 14:17:26 │
│ 20230410PM │ b0d8617590929340bbb5fb58cf52bce4_65_65_0         │     2 │    377 │ 2023-05-11 14:17:25 │
│ 20230410PM │ b0d8617590929340bbb5fb58cf52bce4_66_66_0_75      │     2 │    159 │ 2023-05-16 09:50:37 │
│ 20230512AM │ b9186c325b4cfa4ca55dcba0e78fd4a3_0_0_0           │     2 │   7950 │ 2023-05-12 06:59:15 │
│ 20230512AM │ b9186c325b4cfa4ca55dcba0e78fd4a3_1_1_0           │     2 │      2 │ 2023-05-12 07:19:39 │
│ 20230512AM │ b9186c325b4cfa4ca55dcba0e78fd4a3_2_2_0           │     2 │      3 │ 2023-05-12 07:19:50 │
│ 20230512AM │ b9186c325b4cfa4ca55dcba0e78fd4a3_3_3_0           │     2 │      1 │ 2023-05-12 07:19:50 │
│ 20230512AM │ b9186c325b4cfa4ca55dcba0e78fd4a3_4_4_0           │     2 │      3 │ 2023-05-12 07:20:00 │
│ 20230512AM │ b9186c325b4cfa4ca55dcba0e78fd4a3_5_5_0           │     2 │      2 │ 2023-05-12 07:20:04 │
│ 20230512AM │ b9186c325b4cfa4ca55dcba0e78fd4a3_6_3855_763_3860 │     2 │   7493 │ 2023-05-16 09:50:40 │
└────────────┴──────────────────────────────────────────────────┴───────┴────────┴─────────────────────┘
```
7. materialize device_agregation projection once again and grab some parts to check whether they are exists or not
```sql
ALTER TABLE analytics_local MATERIALIZE projection device_agregation
select parts_to_do, parts_to_do_names from system.mutations where is_done=0

-- 1864, '1e8ea56ef92907db5039c205765fda33_17_17_0_26','1ebc42839fc25ba80c59f25c930876bd_0_0_0_9','1eeded7867995ae3bf35178ebae6a49a_0_0_0_9',...

select partition, name, marks, rows, modification_time from system.parts where name IN('1e8ea56ef92907db5039c205765fda33_17_17_0_26','1ebc42839fc25ba80c59f25c930876bd_0_0_0_9')

┌─partition──┬─name────────────────────────────────────────┬─marks─┬─rows─┬───modification_time─┐
│ 20220307AM │ 1e8ea56ef92907db5039c205765fda33_17_17_0_26 │     2 │   10 │ 2023-05-16 09:49:30 │
│ 20210714AM │ 1ebc42839fc25ba80c59f25c930876bd_0_0_0_9    │     2 │ 1830 │ 2023-05-16 09:49:30 │
└────────────┴─────────────────────────────────────────────┴───────┴──────┴─────────────────────┘
```
8. wait a bit and check `system.mutations`
```sql
select mutation_id, command, is_done, parts_to_do, parts_to_do_names, latest_fail_reason from system.mutations where is_done=0

┌─mutation_id─┬─command───────────────────────────────────────────┬─is_done─┬─parts_to_do─┬─parts_to_do_names─────────────────────────────────────────────────────────────────────┬─latest_fail_reason─┐
│ 0000000005  │ MATERIALIZE PROJECTION device_agregation          │       0 │           2 │ ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'] │                    │
│ 0000000006  │ MATERIALIZE PROJECTION users_agregation           │       0 │           2 │ ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'] │                    │
│ 0000000007  │ MATERIALIZE PROJECTION messages_agregation        │       0 │           2 │ ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'] │                    │
│ 0000000008  │ MATERIALIZE PROJECTION overlay_session_agregation │       0 │           2 │ ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'] │                    │
│ 0000000009  │ MATERIALIZE PROJECTION device_agregation          │       0 │           2 │ ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'] │                    │
└─────────────┴───────────────────────────────────────────────────┴─────────┴─────────────┴───────────────────────────────────────────────────────────────────────────────────────┴────────────────────┘
```

```sql
SELECT version()
┌─version()─┐
│ 23.1.6.42 │
└───────────┘
```

** Work Around ** 
As we dont have any procs/tasks related to particular mutations we can just kill mutations
```sql
KILL MUTATION ON CLUSTER '{cluster}' WHERE mutation_id IN(select mutation_id from system.mutations where is_done=0)
```

**Comment by tavplubix** [comment] 2023-05-16 12:28
`select * from system.replication_queue where table='your_table'` would be really helpful, but it may not show anything since you killed the mutation.

> parts_to_do_names
> ['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1']

The mutation has to mutate two parts that are not ready yet. 

> system.parts
> b0d8617590929340bbb5fb58cf52bce4_60_64_1
> b0d8617590929340bbb5fb58cf52bce4_65_65_0

These parts are going to be merged into `b0d8617590929340bbb5fb58cf52bce4_60_65_2`

> system.parts
> b9186c325b4cfa4ca55dcba0e78fd4a3_0_0_0
> b9186c325b4cfa4ca55dcba0e78fd4a3_2_2_0
> ...
> b9186c325b4cfa4ca55dcba0e78fd4a3_5_5_0

And these parts are going to be merged into `b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1`

And the mutation was waiting for these merges, and the root cause may be unrelated to mutations and projections at all. Please check `system.replication_queue`, you will find the reason if the merges are still there

**Comment by 2b1q** [comment] 2023-05-16 12:57
Thanks. 
I've chacked `system.replication_queue` you mantioned. 
The root cause is `Code: 233. BAD_DATA_PART_NAME` for all new upcoming parts in `parts_to_do_names` that been stucked in `system.mutations`:
```
['b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1']
```

```
Row 1:
──────
replica_name:           chi-clickhouse-analytics-0-0
position:               0
node_name:              queue-0000062230
type:                   MERGE_PARTS
create_time:            2023-05-12 07:23:40
required_quorum:        0
new_part_name:          b0d8617590929340bbb5fb58cf52bce4_60_65_2
parts_to_merge:         ['b0d8617590929340bbb5fb58cf52bce4_60_64_1','b0d8617590929340bbb5fb58cf52bce4_65_65_0']
is_detach:              0
is_currently_executing: 1
num_tries:              2422595
last_exception:         Code: 233. DB::Exception: Unexpected part name: device_agregation for format version: 1. (BAD_DATA_PART_NAME) (version 23.1.6.42 (official build))
last_attempt_time:      2023-05-16 12:39:30
num_postponed:          0
postpone_reason:        
last_postpone_time:     1970-01-01 00:00:00
merge_type:             Regular

Row 2:
──────
replica_name:           chi-clickhouse-analytics-0-0
position:               1
node_name:              queue-0000062167
type:                   MERGE_PARTS
create_time:            2023-05-12 07:20:05
required_quorum:        0
new_part_name:          b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1
parts_to_merge:         ['b9186c325b4cfa4ca55dcba0e78fd4a3_0_0_0','b9186c325b4cfa4ca55dcba0e78fd4a3_1_1_0','b9186c325b4cfa4ca55dcba0e78fd4a3_2_2_0','b9186c325b4cfa4ca55dcba0e78fd4a3_3_3_0','b9186c325b4cfa4ca55dcba0e78fd4a3_4_4_0','b9186c325b4cfa4ca55dcba0e78fd4a3_5_5_0']
is_detach:              0
is_currently_executing: 0
num_tries:              4088672
last_exception:         Code: 233. DB::Exception: Unexpected part name: device_agregation for format version: 1. (BAD_DATA_PART_NAME) (version 23.1.6.42 (official build))
last_attempt_time:      2023-05-16 12:39:30
num_postponed:          0
postpone_reason:        
last_postpone_time:     1970-01-01 00:00:00
merge_type:             Regular
```

**Comment by tavplubix** [comment] 2023-05-16 13:05
This exception looks weird. Please find the stacktrace:
`grep -A50 -Fa "Unexpected part name: device_agregation for format version" /var/log/clickhouse-server/clickhouse-server.log`

**Comment by 2b1q** [comment] 2023-05-16 13:10
```
2023.05.16 12:08:11.849732 [ 75 ] {analytics.analytics_local::b0d8617590929340bbb5fb58cf52bce4_60_65_2} <Debug> MergeTreeSequentialSource: Reading 2 marks from part device_agregation, total 1 rows starting from the beginning of the part
2023.05.16 12:08:11.850132 [ 75 ] {} <Error> analytics.analytics_local::b0d8617590929340bbb5fb58cf52bce4_60_65_2 (MergeFromLogEntryTask): virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 233. DB::Exception: Unexpected part name: device_agregation for format version: 1. (BAD_DATA_PART_NAME), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xddd7ab5 in /usr/bin/clickhouse
1. ? @ 0x1429466c in /usr/bin/clickhouse
2. DB::MergeTreePartInfo::fromPartName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, StrongTypedef<unsigned int, DB::MergeTreeDataFormatVersionTag>) @ 0x14294143 in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::enqueuePartForCheck(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, long) @ 0x13d9345d in /usr/bin/clickhouse
4. DB::MergeTreeReaderCompact::MergeTreeReaderCompact(std::__1::shared_ptr<DB::IMergeTreeDataPartInfoForReader>, DB::NamesAndTypesList, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::UncompressedCache*, DB::MarkCache*, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>, DB::MergeTreeReaderSettings, ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>*, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, double>>>, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, int) @ 0x142a775a in /usr/bin/clickhouse
5. DB::MergeTreeDataPartCompact::getReader(DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>> const&, DB::UncompressedCache*, DB::MarkCache*, DB::MergeTreeReaderSettings const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, double>>> const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&) const @ 0x141d7813 in /usr/bin/clickhouse
6. DB::MergeTreeSequentialSource::MergeTreeSequentialSource(DB::MergeTreeData const&, std::__1::shared_ptr<DB::StorageSnapshot> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>, std::__1::optional<std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange>>>, bool, bool, bool, bool) @ 0x142ba7b4 in /usr/bin/clickhouse
7. DB::createMergeTreeSequentialSource(DB::MergeTreeData const&, std::__1::shared_ptr<DB::StorageSnapshot> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>, bool, bool, bool, std::__1::shared_ptr<std::__1::atomic<unsigned long>>) @ 0x142bb91b in /usr/bin/clickhouse
8. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::createMergedStream() @ 0x14111c7e in /usr/bin/clickhouse
9. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() @ 0x1410fba4 in /usr/bin/clickhouse
10. bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()>>(std::__1::__function::__policy_storage const*) @ 0x1411d929 in /usr/bin/clickhouse
11. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x14114aeb in /usr/bin/clickhouse
12. DB::MergeTask::execute() @ 0x14119fda in /usr/bin/clickhouse
13. bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::MergeProjectionsStage::subtasks::'lambda0'(), bool ()>>(std::__1::__function::__policy_storage const*) @ 0x1411dbed in /usr/bin/clickhouse
14. DB::MergeTask::MergeProjectionsStage::execute() @ 0x1411a58b in /usr/bin/clickhouse
15. DB::MergeTask::execute() @ 0x14119fda in /usr/bin/clickhouse
16. DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x1443d3ec in /usr/bin/clickhouse
17. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x1443c4e2 in /usr/bin/clickhouse
18. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0x883440c in /usr/bin/clickhouse
19. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0x8833e4c in /usr/bin/clickhouse
20. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xdea8616 in /usr/bin/clickhouse
21. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0xdeaaeb5 in /usr/bin/clickhouse
22. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xdea4b36 in /usr/bin/clickhouse
23. ? @ 0xdea9e61 in /usr/bin/clickhouse
24. ? @ 0x7f9d141d8609 in ?
25. clone @ 0x7f9d140fd133 in ?
 (version 23.1.6.42 (official build))
2023.05.16 12:08:11.851325 [ 75 ] {} <Debug> MemoryTracker: Peak memory usage to apply mutate/merge in analytics.analytics_local::b0d8617590929340bbb5fb58cf52bce4_60_65_2: 83.05 MiB.
```

**Comment by tavplubix** [comment] 2023-05-16 14:34
Well, it's a bug in projections. Related to https://github.com/ClickHouse/ClickHouse/issues/46413

cc: @amosbird 

I don't know a good workaround, but it makes sense to drop these projections. If it does not help, then the table can be recovered manually like this:
 - detach affected partitions
 - remove all `*.proj` subdirs and `checksums.txt` files from the detached parts (`/path_to_table_data/detached/part_name/`)
 - attach partitions back

**Comment by amosbird** [comment] 2023-05-16 15:46
I have some ideas on how to fix this problem. Will try to make a PR this week.

**Comment by 2b1q** [comment] 2023-05-17 11:35
Seems it works as should. 
what was done
1. had dropped `device_agregation` projection which rises MERGE PARTS exceptions. And got new stucked mutation `DROP PROJECTION device_agregation`  with same parts `'b0d8617590929340bbb5fb58cf52bce4_60_65_2','b9186c325b4cfa4ca55dcba0e78fd4a3_0_5_1'`
2. had dropped partitions with stucked MERGE PARTS in `system.replication_queue`
```sql
ALTER TABLE <table> ON CLUSTER '{cluster}' DROP PARTITION '<partition_with_stucked_merge_parts>' 
-- checked system.replication_queue and system.mutations
-- 0 rows
```
3. had restored data related to <partition_with_stucked_merge_parts> (copied from backuped table)
4. had materialized the rest three projections I had in my table with new resored parts
```sql
ALTER TABLE <t> ON CLUSTER '{cluster}' MATERIALIZE projection users_agregation 
OK (system.mutations: 0, system.replication_queue: 0)
-//-//- MATERIALIZE projection messages_agregation
OK (system.mutations: 0, system.replication_queue: 0)
-//-//- MATERIALIZE projection overlay_session_agregation
OK (system.mutations: 0, system.replication_queue: 0)
```
5. created `device_agregation` projection once again and materialized it
6. have checked system.mutations, system.replication_queue some time later. Zero and Zero. 
7. had checked whether my query hit `device_agregation` projection
```sql
EXPLAIN json = 1, indexes = 1  <base select from t1 with device_agregation projection>
[
  {
    "Plan": {
      "Node Type": "Expression",
      "Description": "(Projection + Before ORDER BY)",
      "Plans": [
        {
          "Node Type": "ReadFromStorage",
          "Description": "MergeTree(with Aggregate projection device_agregation)"
        }
      ]
    }
  }
] 
+ EXPLAIN ESTIMATE 
(SelectExecutor): Choose complete Aggregate projection device_agregation
(SelectExecutor): projection required columns: eventId, organizationId, uniqExact(deviceId)
(SelectExecutor): Selected 1890/1890 parts by partition key, 392 parts by primary key, 392/1890 marks by primary key, 392 marks to read from 392 ranges
(SelectExecutor): Reading approx. 5270 rows with 16 streams
```
8. same as 7 from t2 (same data set and DDL excluding projections)
```
(SelectExecutor): Selected 6/896 parts by partition key, 6 parts by primary key, 57310/57310 marks by primary key, 57310 marks to read from 6 ranges
(SelectExecutor): Reading approx. 466460237 rows with 16 streams
```

**Closed** 2023-05-22 11:20 UTC
Labels: bug, comp-projections
