### ISSUE TITLE
DELETE mutation leaves empty parts on disk

### ISSUE THREAD

**Issue by keliss** [ClickHouse/ClickHouse#14899] opened 2020-09-17 07:30 UTC
Hello. I've noticed that when I'm trying to delete all the data for some period of time using the DELETE query, empty parts still remain on disk. I'd expect them to be removed as well since there's no sense in storing this data. We use partitioning by hour if it is important.

**Comment by alesapin** [comment] 2020-09-17 07:41
It's not a bug and intended behavior. MergeTree relies on the order of blocks stored in parts, so we cannot easily remove any part from disk. BTW, empty parts should be merged soon with normal ones.

**Comment by keliss** [comment] 2020-09-17 07:44
But they don't get merged. We have such parts for over half a year. And if it is intended behaviour and the order matters, will there be any problems if we just use DROP PARTITION instead?

**Comment by alesapin** [comment] 2020-09-17 07:46
> But they don't get merged. We have such parts for over half a year. And if it is intended behaviour and the order matters, will there be any problems if we just use DROP PARTITION instead?

It's strange that they don't get merged, but it's possible if already existing non-empty parts is large enough. There will be no problems with `DROP PARTITION`, it's a much cheaper and effective operation than `ALTER DELETE`.

**Comment by keliss** [comment] 2020-09-17 09:12
Ok, thank you.

**Closed** 2020-09-17 10:45 UTC
Labels: question, question-answered

**Comment by den-crane** [comment] 2020-09-17 12:28
related https://github.com/ClickHouse/ClickHouse/issues/5491
