### ISSUE TITLE
`SELECT max(elapsed) FROM system.processes` slow when long query will produce a lot of `thread_ids`

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#44989] opened 2023-01-06 16:10 UTC
**Describe the situation**
What exactly works slower than expected?

I have long running queries which produce lot of `thread_ids` (million items) in `system.processes`

```sql
SELECT query, elapsed, length(thread_ids) FROM system.processes ORDER BY length(thread_ids) DESC LIMIT 10 FORMAT Vertical;

Row 1:
──────
query:              SELECT x.* FROM `default`.RawEvent1 x
ORDER BY x.`_timestamp`
LIMIT 0, 200
elapsed:            20501.256211112
length(thread_ids): 19039934

Row 2:
──────
query:              SELECT x.* FROM `default`.RawEvent1 x
ORDER BY x.`_timestamp` DESC
LIMIT 0, 200
elapsed:            20492.321420429
length(thread_ids): 18919381

Row 3:
──────
query:              SELECT timestamp AS timestamp,
       device_uuid AS device_uuid,
       max("xxx") AS "MAX(xxx)"
FROM raw_data.vehicle_raw_data
WHERE timestamp >= '2022-12-30 00:00:00.000000'
  AND timestamp < '2023-01-06 00:00:00.000000'
  AND "XXX_Count" > '0'
GROUP BY timestamp, device_uuid
ORDER BY "MAX(xxx)" DESC
LIMIT 1000
elapsed:            20758.026389037
length(thread_ids): 15127956

Row 4:
──────
query:              SELECT timestamp AS timestamp,
       max("xxx") AS "MAX(xxx)"
FROM raw_data.xxx_raw_data
WHERE timestamp >= '2022-12-30 00:00:00.000000'
  AND timestamp < '2023-01-06 00:00:00.000000'
  AND "XXX_Count" > '0'
GROUP BY timestamp
ORDER BY "MAX(xxx)" DESC
LIMIT 50000
elapsed:            19308.610186221
length(thread_ids): 14966843

Row 5:
──────
query:              SELECT timestamp AS timestamp,
       count("xxx") AS "COUNT(xxx)"
FROM raw_data.vehicle_raw_data
WHERE timestamp >= '2022-12-30 00:00:00.000000'
  AND timestamp < '2023-01-06 00:00:00.000000'
  AND "XXX_Count" > '0'
GROUP BY timestamp
ORDER BY "COUNT(xxx)" DESC
LIMIT 50000
elapsed:            19112.395190881
length(thread_ids): 14857253

Row 6:
──────
query:              SELECT timestamp AS timestamp,
       device_uuid AS device_uuid,
       max("xxx") AS "MAX(xxx)"
FROM raw_data.xxx_raw_data
WHERE timestamp >= '2022-12-30 00:00:00.000000'
  AND timestamp < '2023-01-06 00:00:00.000000'
  AND "XXX_Count" > '0'
GROUP BY timestamp, device_uuid
ORDER BY "MAX(xxx)" DESC
LIMIT 50000
elapsed:            20629.304786307
length(thread_ids): 14781021

Row 7:
──────
query:              SELECT timestamp AS timestamp,
       max("xxx") AS "MAX(xxx)"
FROM raw_data.xxx_raw_data
WHERE timestamp >= '2022-12-30 00:00:00.000000'
  AND timestamp < '2023-01-06 00:00:00.000000'
  AND "XXX_Count" > '0'
GROUP BY timestamp
ORDER BY "MAX(xxx)" DESC
LIMIT 50000
elapsed:            20524.125588518
length(thread_ids): 13902622

Row 8:
──────
query:              SELECT timestamp AS timestamp,
       count("xxx") AS "COUNT(xxx)"
FROM raw_data.vehicle_raw_data
WHERE timestamp >= '2022-12-30 00:00:00.000000'
  AND timestamp < '2023-01-06 00:00:00.000000'
  AND "XXX_Count" > '0'
GROUP BY timestamp
ORDER BY "COUNT(XXX_count)" DESC
LIMIT 50000
elapsed:            19392.13435384
length(thread_ids): 12463475

Row 9:
───────
query:              select `timestamp` , device_uuid, uniqCombined('XXX_VehState', 'XXX_ErrorCode') 
from raw_data.xxx_raw_data vrd
where toDate(`timestamp`) = '2023-01-06'
group by `timestamp` , device_uuid
LIMIT 0, 200
elapsed:            10424.885868025
length(thread_ids): 1460179

```

`SELECT max(elapsed) FROM system.processes` executed more than 60 seconds
look to flamegraph
```bash
clickhouse-client --time --echo --progress -q "SELECT * FROM system.processes FORMAT Vertical SETTINGS query_profiler_real_time_period_ns=100000000" --query_id "slow_system_processes";    

clickhouse-client -q "SELECT arrayStringConcat(arrayReverse(arrayMap(x -> concat( demangle(addressToSymbol(x)), '#', addressToLine(x) ), trace)), ';') stack, count() FROM system.trace_log WHERE trace_type='Real' AND event_date=today() AND query_id='slow_system_processes' GROUP BY stack FORMAT TabSeparatedRaw SETTINGS allow_introspection_functions=1"
```
![flamegraph](https://user-images.githubusercontent.com/105560/211051293-d955028b-bc5c-4ab8-ab5c-974809e64ef4.svg)

Look like `thread_ids` filled even when is not used in SELECT queries

```bash
clickhouse-client --time --echo --progress -q "SELECT max(elapsed) FROM system.processes FORMAT Vertical SETTINGS query_profiler_real_time_period_ns=100000000" --query_id "slow_system_processes_3";

clickhouse-client -q "SELECT arrayStringConcat(arrayReverse(arrayMap(x -> concat( demangle(addressToSymbol(x)), '#', addressToLine(x) ), trace)), ';') stack, count() FROM system.trace_log WHERE trace_type='Real' AND event_date=today() AND query_id='slow_system_processes_3' GROUP BY stack FORMAT TabSeparatedRaw SETTINGS allow_introspection_functions=1"
```
![flamegraph_3](https://user-images.githubusercontent.com/105560/211051329-6e41413a-b591-45f4-9eac-439cefff34e7.svg)

**Expected performance**
fast performance when calculate max(elapsed)

**Comment by den-crane** [comment] 2023-01-06 17:16
clickhouse version 22.8.11.15

**Comment by UnamedRus** [comment] 2023-01-06 19:19
Related fix? https://github.com/ClickHouse/ClickHouse/pull/42180

**Comment by alexey-milovidov** [comment] 2023-01-07 01:28
Yes, the problem is fixed by https://github.com/ClickHouse/ClickHouse/pull/42180

**Closed by alexey-milovidov** 2023-01-07 01:28 UTC
Labels: performance, st-fixed
