### ISSUE TITLE
`Not found address of host` error should not make ClickHouse return code 500

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#46556] opened 2023-02-18 21:07 UTC
When a node in ClickHouse cluster fails, we expect distributed queries be sent to healthy replicas by initial node.

But with the error `Not found address of host`, ClickHouse server simply returns code 500, even there are healthy replicas in the same shard.

```
An error occurred while processing the query 'SELECT * FROM business.http_log WHERE (tenant = '20000199') AND hasToken(requestHead, 'ASPSESSIONIDCCSBDBAQ') ORDER BY recordTimestamp ASC LIMIT 100': Code: 198. DB::Exception: Received from localhost:9000. DB::Exception: Not found address of host: chi-datalake-ck-cluster-0-1: While executing Delayed. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3dbe3a in /usr/bin/clickhouse
1. ? @ 0xa4e550a in /usr/bin/clickhouse
2. ? @ 0xa4e35e4 in /usr/bin/clickhouse
3. ? @ 0xa4e3a36 in /usr/bin/clickhouse
4. DB::DNSResolver::resolveAddressList(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned short) @ 0xa4e4a53 in /usr/bin/clickhouse
5. DB::Connection::connect(DB::ConnectionTimeouts const&) @ 0x15b6e2e3 in /usr/bin/clickhouse
6. DB::Connection::getServerRevision(DB::ConnectionTimeouts const&) @ 0x15b7103e in /usr/bin/clickhouse
7. DB::ConnectionEstablisher::run(PoolWithFailoverBase<DB::IConnectionPool>::TryResult&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0x15b925ad in /usr/bin/clickhouse
8. ? @ 0x15b8dcb6 in /usr/bin/clickhouse
9. PoolWithFailoverBase<DB::IConnectionPool>::getMany(unsigned long, unsigned long, unsigned long, unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x15b8baaf in /usr/bin/clickhouse
10. DB::ConnectionPoolWithFailover::getManyImpl(DB::Settings const*, DB::PoolMode, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&) @ 0x15b8b3e8 in /usr/bin/clickhouse
11. ? @ 0x16088085 in /usr/bin/clickhouse
12. DB::DelayedSource::work() @ 0x16091dea in /usr/bin/clickhouse
13. DB::ExecutionThreadContext::executeTask() @ 0x15cf39ea in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15ce7f5b in /usr/bin/clickhouse
15. ? @ 0x15cea7f9 in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa49fb08 in /usr/bin/clickhouse
17. ? @ 0xa4a2d1d in /usr/bin/clickhouse
18. ? @ 0x7fc7915f1609 in ?
19. clone @ 0x7fc791516133 in ?
. (DNS_ERROR) (version 22.9.1.2603 (official build))
```

**Comment by cangyin** [comment] 2023-02-18 21:22
Although it seems like a client side error.

**Comment by alexey-milovidov** [comment] 2023-02-19 01:08
Duplicate of #45683

**Closed by alexey-milovidov** 2023-02-19 01:08 UTC
Labels: usability
