### ISSUE TITLE
`test_distributed_load_balancing` flaky

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#49097] opened 2023-04-24 11:07 UTC
Example link: https://s3.amazonaws.com/clickhouse-test-reports/49078/f4bd5a0667597134e3bc01b6dabd6691095c721d/integration_tests__release__[3/4].html
CIDB: https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgNDggSE9VUgogICAgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHBvc2l0aW9uKHRlc3RfbmFtZSwgJ3Rlc3RfZGlzdHJpYnV0ZWRfbG9hZF9iYWxhbmNpbmcnKSA+IDAKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZQ==

**Comment by serxa** [comment] 2023-05-16 11:09
There are multiple places of failure, but reason looks the same: 
```
_________________________ test_load_balancing_default __________________________
[gw0] linux -- Python 3.8.10 /usr/bin/python3

    def test_load_balancing_default():
        unique_nodes = set()
        for _ in range(0, queries):
            unique_nodes.add(get_node(n1, settings={"load_balancing": "random"}))
>       assert len(unique_nodes) == nodes, unique_nodes
E       AssertionError: {'n2', 'n3'}
E       assert 2 == 3
E        +  where 2 = len({'n2', 'n3'})
```
Another one:
```
_____________________ test_load_balancing_first_or_random ______________________
[gw0] linux -- Python 3.8.10 /usr/bin/python3

    def test_load_balancing_first_or_random():
        unique_nodes = set()
        for _ in range(0, queries):
            unique_nodes.add(get_node(n1, settings={"load_balancing": "first_or_random"}))
>       assert len(unique_nodes) == 1, unique_nodes
E       AssertionError: {'n2', 'n3'}
E       assert 2 == 1
E        +  where 2 = len({'n2', 'n3'})
```
Next:
```
_________________________ test_load_balancing_in_order _________________________
[gw0] linux -- Python 3.8.10 /usr/bin/python3

    def test_load_balancing_in_order():
        unique_nodes = set()
        for _ in range(0, queries):
            unique_nodes.add(get_node(n1, settings={"load_balancing": "in_order"}))
        assert len(unique_nodes) == 1, unique_nodes
>       assert unique_nodes == set(["n1"])
E       AssertionError: assert {'n2'} == {'n1'}
E         Extra items in the left set:
E         'n2'
E         Extra items in the right set:
E         'n1'
E         Full diff:
E         - {'n1'}
E         ?    ^
E         + {'n2'}
E         ?    ^
```
Last:
```
_____________________ test_load_balancing_nearest_hostname _____________________
[gw0] linux -- Python 3.8.10 /usr/bin/python3

    def test_load_balancing_nearest_hostname():
        unique_nodes = set()
        for _ in range(0, queries):
            unique_nodes.add(get_node(n1, settings={"load_balancing": "nearest_hostname"}))
>       assert len(unique_nodes) == 1, unique_nodes
E       AssertionError: {'n2', 'n3'}
E       assert 2 == 1
E        +  where 2 = len({'n2', 'n3'})
```

**Comment by serxa** [comment] 2023-05-16 19:25
It looks like sometimes "advice" provided by `load_balancing` setting is ignored. And implementation of `PoolWithFailover` is indeed uses pool priorities (which are based on `load_balancing` value) only after error count. Checking the code...

**Comment by serxa** [comment] 2023-05-19 14:55
Let's consider why `"load_balancing": "first_or_random"` does not always select the first replica. In test we have 30 requests (`query_id`s [list](https://pastila.nl/?32b52ce6/0772e294294288a0eb87878238bff5f8)). Only the first (n2) and the second (n3) are not local, while the other 28 are local (n1). Also, not the test automatically adds `"prefer_localhost_replica":0` setting.

According to `query_log` during the integration test, ProfileEvents for the first are:
```
{'Query':1,'SelectQuery':1,'ReadCompressedBytes':120,'CompressedReadBufferBlocks':3,'CompressedReadBufferBytes':41,'IOBufferAllocs':4,'IOBufferAllocBytes':2097563,'NetworkReceiveElapsedMicroseconds':238,'NetworkSendElapsedMicroseconds':196,'NetworkReceiveBytes':1111,'NetworkSendBytes':2567,'SuspendSendingQueryToShard':1,'ContextLock':37,'RWLockAcquiredReadLocks':2,'RealTimeMicroseconds':14119,'UserTimeMicroseconds':1552,'SystemTimeMicroseconds':3244,'SoftPageFaults':342,'OSCPUWaitMicroseconds':24,'OSCPUVirtualTimeMicroseconds':4796,'OSWriteBytes':4096,'OSReadChars':907,'OSWriteChars':838,'LogTrace':3,'LogDebug':2}
```
For the second are:
```
{'Query':1,'SelectQuery':1,'ReadCompressedBytes':120,'CompressedReadBufferBlocks':3,'CompressedReadBufferBytes':41,'IOBufferAllocs':4,'IOBufferAllocBytes':2097563,'NetworkReceiveElapsedMicroseconds':286,'NetworkSendElapsedMicroseconds':210,'NetworkReceiveBytes':1111,'NetworkSendBytes':2557,'SuspendSendingQueryToShard':1,'ContextLock':37,'RWLockAcquiredReadLocks':2,'RealTimeMicroseconds':15054,'UserTimeMicroseconds':5631,'SoftPageFaults':448,'OSCPUVirtualTimeMicroseconds':5630,'OSWriteBytes':4096,'OSReadChars':907,'OSWriteChars':838,'LogTrace':3,'LogDebug':2}
```
For the third are:
```
{'Query':1,'SelectQuery':1,'ReadCompressedBytes':36,'CompressedReadBufferBlocks':1,'CompressedReadBufferBytes':10,'IOBufferAllocs':2,'IOBufferAllocBytes':1048776,'NetworkReceiveElapsedMicroseconds':278,'NetworkSendElapsedMicroseconds':175,'NetworkReceiveBytes':831,'NetworkSendBytes':2215,'SuspendSendingQueryToShard':1,'ContextLock':37,'RWLockAcquiredReadLocks':2,'RealTimeMicroseconds':13183,'UserTimeMicroseconds':2572,'SystemTimeMicroseconds':2048,'SoftPageFaults':234,'OSCPUVirtualTimeMicroseconds':4619,'OSReadChars':908,'OSWriteChars':788,'LogTrace':3,'LogDebug':2}
```

**Comment by serxa** [comment] 2023-05-19 18:28
I fixed a couple of minor bugs and one major bug around load balancing logic https://github.com/ClickHouse/ClickHouse/pull/50036. It was found just through reading the code, so I'm still not convinced that these bugfixes will make this test not flaky. Thus, I'm going to add some ProfileEvents to be able to diagnose load-balancing decisions in tests and in production as well.

**Comment by serxa** [comment] 2023-05-21 12:21
I hope this PR https://github.com/ClickHouse/ClickHouse/pull/50051 will help us to get a little bit of insight into distributed connection establishment.

**Comment by azat** [comment] 2023-05-21 21:16
Doesn't #49921 fixes this?

**Comment by serxa** [comment] 2023-05-21 22:23
Maybe it helps in some cases, but not always. I was [investigating](https://github.com/ClickHouse/ClickHouse/issues/49097#issuecomment-1554713710) a case where no "ConnectionPoolWithFailover: Connection failed" warnings were in logs, but connection targets were still wrong.

**Comment by serxa** [comment] 2023-05-21 22:40
There was also a bug in the implementation of `distributed_replica_max_ignored_errors`, that lead to an overflow of `error_count`. Overall behavior in case of a small amount (<distributed_replica_max_ignored_errors) of error was just: ignore value `distributed_replica_max_ignored_errors` as it was zero. In case of a high amount of errors (>distributed_replica_max_ignored_errors), good connections were ignored instead of good ones. Fixed in https://github.com/ClickHouse/ClickHouse/pull/50036

**Comment by serxa** [comment] 2023-05-22 10:59
Anyways, I might be wrong because it did not reproduce since May 15, so let's close and reopen if it reproduces.

**Closed by serxa** 2023-05-22 10:59 UTC
Labels: flaky test
