### ISSUE TITLE
Unknown column 'DATETIME_PRECISION' when try to select from mysql

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#42671] opened 2022-10-26 07:47 UTC
CH: 22.8.6.71
MySql: 5.5.58-0+deb8u1-log

When i try to select data from mysql table:
`select id from mysql('.....');`
Get an error
`Poco::Exception. Code: 1000, e.code() = 1054, mysqlxx::BadQuery: Unknown column 'DATETIME_PRECISION' in 'field list'`

**Comment by alexey-milovidov** [comment] 2022-10-26 09:19
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/21335

**Closed by alexey-milovidov** 2022-10-26 09:19 UTC
Labels: potential bug
