### ISSUE TITLE
Update specific partition ddl influence  all  partition in table？

### ISSUE THREAD

**Issue by kaynewu** [ClickHouse/ClickHouse#47239] opened 2023-03-04 03:53 UTC
clickhouse version： 22.9

CREATE TABLE IF NOT EXISTS default.test
(
    `type` String,
    `flag` UInt8,
    `create_time` DateTime DEFAULT now()
)
ENGINE = MergeTree
PARTITION BY type
ORDER BY create_time

insert into default.test(type,flag) values('A',1)
insert into default.test(type,flag) values('B',0)

![image](https://user-images.githubusercontent.com/5574794/222874634-37eb2c22-7263-4f86-a1c7-2885ab6c9ff8.png)

update:
ALTER TABLE default.test
    UPDATE flag = 1 IN PARTITION 'B' WHERE flag = 0

all partition and part is changed：
![image](https://user-images.githubusercontent.com/5574794/222874826-f1e2806d-0c3d-4915-868c-bbdf3d360299.png)

If  there are thousands of  partitions  and parts changing only specific partitions is more performant !!!

**Comment by den-crane** [comment] 2023-03-04 13:40
related https://github.com/ClickHouse/ClickHouse/issues/25882#issuecomment-1420849234  https://github.com/ClickHouse/ClickHouse/pull/40589

**Comment by tavplubix** [comment] 2023-03-04 15:51
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/46594

**Closed by tavplubix** 2023-03-04 15:51 UTC
Labels: feature
