### ISSUE TITLE
Probably a final mistake

### ISSUE THREAD

**Issue by handgunman** [ClickHouse/ClickHouse#63315] opened 2024-05-03 00:52 UTC
There's a table 
ENGINE = ReplacingMergeTree(__data_transfer_commit_time)
PARTITION BY toYYYYMM(datecommit)
ORDER BY (shopindex, item, erpcode, datecommit, id)

if you check the number of identifiers with and without final there is a difference of 2 records

SELECT uniqExact(id)
FROM cheks
UNION ALL
SELECT uniqExact(id)
FROM cheks
FINAL

   ┌─uniqExact(id)─┐
1. │      68844463 │ -- 68.84 million
   └───────────────┘
   ┌─uniqExact(id)─┐
2. │      68844461 │ -- 68.84 million
   └───────────────┘

and then I find the difference

SELECT id
FROM cheks
WHERE id NOT IN (
    SELECT id
    FROM cheks
    FINAL
)

   ┌────────id─┐
1. │ 382358892 │
2. │ 382358894 │
   └───────────┘
   
   But these records don't have duplicates
   SELECT
    shopindex,
    item,
    erpcode,
    datecommit,
    id
FROM cheks
WHERE id IN (382358892, 382358894)
FORMAT Vertical

Row 1:
──────
shopindex:  42035
item:       121073
erpcode:    УТ-00015914
datecommit: 2024-04-30 10:47:23.410000
id:         382358892

Row 2:
──────
shopindex:  42035
item:       121073
erpcode:    УТ-00015914
datecommit: 2024-04-30 10:47:24.076000
id:         382358894

2 rows in set. Elapsed: 0.219 sec. Processed 68.84 million rows, 275.38 MB (315.05 million rows/s., 1.26 GB/s.)
Peak memory usage: 775.62 KiB.

What could be the cause?

version: 24.3.2.23

**Comment by Algunenano** [comment] 2024-05-03 09:18
There have been several bug (and bug fixes) lately around FINAL. Can you test with the latest 24.4 or provide a reproducer to verify it please?

**Comment by handgunman** [comment] 2024-05-03 09:38
I can't update the version at the moment.
And I don't really understand how to reproduce this problem.

I tried to make the same table in fiddle and transfer these 2 records and one more to it, but the situation is not reproduced.

**Comment by nickitat** [comment] 2024-05-03 10:40
there are few flags that could be tweaked:

```
split_intersecting_parts_ranges_into_layers_final
split_parts_ranges_into_intersecting_and_non_intersecting_final
enable_vertical_final
```

**Comment by handgunman** [comment] 2024-05-03 10:55
at the moment new data has been added to the table and there is no discrepancy for the previously specified identifiers.
but there are new ones.
When selecting data with one of them with the split_intersecting_parts_ranges_into_layers_final  setting, everything is correct

split_parts_ranges_into_intersecting_and_non_intersecting_final doesn't - change the result
enable_vertical_final - doesn't change the result

All of these settings are set to 1 and I changed them to 0

**Comment by nickitat** [comment] 2024-05-03 11:01
could you pls share `explain pipeline SELECT uniqExact(id) FROM cheks FINAL` with default settings

**Comment by handgunman** [comment] 2024-05-03 11:04
please see in file
[check.txt](https://github.com/ClickHouse/ClickHouse/files/15199075/check.txt)

**Comment by nickitat** [comment] 2024-05-03 11:10
looks like https://github.com/ClickHouse/ClickHouse/pull/62268

backport was merged on Apr 8

you're using a build April 3 
from https://github.com/ClickHouse/ClickHouse/releases/tag/v24.3.2.23-lts

**Comment by handgunman** [comment] 2024-05-03 11:13
Ok, we'll have to wait until the update is available on the cloud service.

**Comment by nickitat** [comment] 2024-05-03 11:20
there is also a subtle problem that 

``` sql
SELECT id
FROM cheks
WHERE id NOT IN (
SELECT id
FROM cheks
FINAL
)
```

isn't 100% reliable, because theoretically the subquery and outer query read from different snapshots.

**Closed by nickitat** 2024-05-03 11:20 UTC
Labels: potential bug
