### ISSUE TITLE
Frequent DB::Exception: Memory limit (total) exceeded while inserting

### ISSUE THREAD

**Issue by PHameete** [ClickHouse/ClickHouse#22437] opened 2021-04-01 11:43 UTC
**Describe the unexpected behaviour**

I frequently get the following error when inserting records:

```
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 241, host: node-1.clickhouse.bx.internal, port: 8123; Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 13.84 GiB (attempt to allocate chunk of 4217652 bytes), maximum: 13.84 GiB (version 20.8.12.2)
```

I am inserting using [clickhouse-jdbc](https://github.com/ClickHouse/clickhouse-jdbc) to insert into 3 different tables. 

My current approach has 1 thread per table, that reads records from Kafka and inserts in batch every 10K rows, or after 1 second. Currently there are never 10K rows per 1 second, so this is 3 relatively small batch inserts per second.

Can anyone help me understand why I am getting out of memory errors while doing small inserts (~100 rows at a time) and roughly 3 inserts per second. Hopefully we can also find a solution for this either by finding a good approach for inserting, or by changing ClickHouse server configuration.

A clear and concise description of what works not as it is supposed to.

**How to reproduce**

* Which ClickHouse server version to use

Version 20.8.12.2

* Which interface to use, if matters

[clickhouse-jdbc](https://github.com/ClickHouse/clickhouse-jdbc)

* Non-default settings, if any

Server is all default settings. 
For clickhouse-jdbc I have increased max query size to 10MB.

* `CREATE TABLE` statements for all tables involved

```
CREATE TABLE IF NOT EXISTS measurements (
    project_id UUID,
    subject_id UUID,
    metric_id UUID,
    date DateTime64(3),
    received_date DateTime64(3),
    value Decimal128(8)
)
ENGINE = ReplacingMergeTree()
PARTITION BY (project_id, toYYYYMM(date))
ORDER BY (metric_id, subject_id, date);
```

**Expected behavior**

Can insert 100 rows per second into three different tables without out of memory exceptions.

**Error message and/or stacktrace**

```
at java.base/java.lang.Thread.run(Thread.java:832)
	Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 241, host: node-1.clickhouse.bx.internal, port: 8123; Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 13.84 GiB (attempt to allocate chunk of 4217604 bytes), maximum: 13.84 GiB (version 20.8.12.2)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:59)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:29)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1052)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:1022)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:991)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:984)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:373)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:350)
	at com.bx.clickhouse_writer.clickhouse.ClickHouseService.writeMeasurements(ClickHouseService.java:129)
	... 11 common frames omitted
	Caused by: java.lang.Throwable: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 13.84 GiB (attempt to allocate chunk of 4217604 bytes), maximum: 13.84 GiB (version 20.8.12.2)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:54)
	... 19 common frames omitted
```

**Comment by den-crane** [comment] 2021-04-01 12:04
Check the real memory consuming of Clickhouse in linux.
top / htop  -- RES column.
20.8 calculates memory usage incorrectly.
Just set max_server_memory_usage_to_ram_ratio=10 or 100

never merged  https://github.com/ClickHouse/ClickHouse/pull/16121 into 20.8
duplicate of https://github.com/ClickHouse/ClickHouse/issues/15932

**Closed by den-crane** 2021-04-01 12:04 UTC
Labels: unexpected behaviour
