### ISSUE TITLE
build failed, by clang 8.0.0

### ISSUE THREAD

**Issue by songhtdo** [ClickHouse/ClickHouse#5316] opened 2019-05-17 08:54 UTC
hi,  Thank you for your work.
I compiled in stable version (19.5.3.8 stable) wrong.
first, Download the code from LLVM and copy the code from the driver directory to compiler_8.0.0 and compiler_8.0.0svn.
second, The build code.
 failed message:
CMake Error at dbms/programs/clang/Compiler-8.0.0svn/CMakeLists.txt:32 (add_clang_tool):
  Unknown CMake command "add_clang_tool".

**Comment by alexey-milovidov** [comment] 2019-05-17 08:59
> and copy the code from the driver directory to compiler_8.0.0

Verbatim copy wont work.

**Comment by excitoon** [comment] 2019-06-22 08:43
This is a duplicate of  #5169

**Comment by Felixoid** [comment] 2019-06-28 08:33
Looks like it was fixed. Maybe in #5368

Is it still broken for you, @excitoon ?

**Closed** 2019-11-19 12:28 UTC
Labels: build
