### ISSUE TITLE
argMax and Nullables

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#16400] opened 2020-10-26 15:41 UTC
Continuation of #13598

```
SELECT
    materialize([1, 2, 3, 4, NULL][number + 1]) AS x,
    toTypeName(x) AS type,
    now() + (number * 2) AS ts
FROM numbers(5)

┌────x─┬─type────────────┬──────────────────ts─┐
│    1 │ Nullable(UInt8) │ 2020-10-26 15:39:04 │
│    2 │ Nullable(UInt8) │ 2020-10-26 15:39:06 │
│    3 │ Nullable(UInt8) │ 2020-10-26 15:39:08 │
│    4 │ Nullable(UInt8) │ 2020-10-26 15:39:10 │
│ ᴺᵁᴸᴸ │ Nullable(UInt8) │ 2020-10-26 15:39:12 │
└──────┴─────────────────┴─────────────────────┘
```

```
WITH argMaxState(x, ts) AS state
SELECT
    toTypeName(state),
    finalizeAggregation(state),
    any(type)
FROM 
(
    SELECT
        materialize([1, 2, 3, 4, NULL][number + 1]) AS x,
        toTypeName(x) AS type,
        now() + (number * 2) AS ts
    FROM numbers(5)
) AS t

Row 1:
──────
toTypeName(state):          AggregateFunction(argMax, Nullable(UInt8), DateTime('UTC'))
finalizeAggregation(state): 4
any(type):                  Nullable(UInt8)
```
questionable (not clear how to get the last state - accepting Null as a valid value). 

```
WITH argMaxOrNullState(x, ts) AS state
SELECT
    toTypeName(state),
    finalizeAggregation(state),
    any(type)
FROM 
(
    SELECT
        materialize([1, 2, 3, 4, NULL][number + 1]) AS x,
        toTypeName(x) AS type,
        now() + (number * 2) AS ts
    FROM numbers(5)
) AS t

Row 1:
──────
toTypeName(state):          AggregateFunction(argMaxOrNull, Nullable(UInt8), DateTime('UTC'))
finalizeAggregation(state): 0
any(type):                  Nullable(UInt8)

1 rows in set. Elapsed: 0.005 sec. 
```
That just looks wrong.

**Comment by filimonov** [comment] 2020-10-26 15:53
>= 20.5  
toTypeName(state): AggregateFunction(argMax, Nullable(UInt8), DateTime('UTC'))

<= 20.4
toTypeName(state): AggregateFunction(argMax, UInt8, DateTime('UTC'))


That sounds like a potential compatibility issue for MVs:
```
Conversion from AggregateFunction(argMax, Nullable(UInt8), DateTime) to AggregateFunction(argMax, UInt8, DateTime) is not supported
```

**Comment by filimonov** [comment] 2020-10-26 16:39
Oracle allows adjusting that behavior 

https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions073.htm
If the last value in the set is null, then the function returns NULL unless you specify IGNORE NULLS.

**Comment by filimonov** [comment] 2020-10-26 16:45
Similar - any / anyLast ignore Nulls.

**Comment by alexey-milovidov** [comment] 2020-10-26 17:13
> Similar - any / anyLast ignore Nulls.

It's totally alright.

**Comment by alexey-milovidov** [comment] 2020-11-04 15:17
> Oracle allows adjusting that behavior

Oracle does not support argMin and argMax functions.

**Comment by filimonov** [comment] 2020-11-05 11:19
> > Oracle allows adjusting that behavior
> 
> Oracle does not support argMin and argMax functions.

It have LAST_VALUE(...) OVER.

**Comment by filipbacic** [comment] 2020-11-25 13:47
Hi,
I have the same problem with argMax function, it does not take NULL values into account:

Reproducible code:
```
CREATE TABLE test.argMax_test (
inserted_on DateTime DEFAULT now(),
 string_column String,
 nullable_string_column Nullable(String)
) ENGINE = Log;

INSERT INTO test.argMax_test (string_column, nullable_string_column)
VALUES ('2', 'example');

SELECT * FROM test.argMax_test;

INSERT INTO test.argMax_test (string_column, nullable_string_column)
VALUES ('1', NULL);

SELECT * FROM test.argMax_test;

SELECT max(inserted_on), argMax(string_column, inserted_on) as non_nullable_column, argMax(nullable_string_column, inserted_on) as nullable_column_current, 
nullIf(argMax(ifNull(nullable_string_column, 'null'), inserted_on), 'null') as nullable_column_wanted FROM test.argMax_test amt;

DROP TABLE test.argMax_test;
```

So it looks like this:
```
SELECT *
FROM test.argMax_test

┌─────────inserted_on─┬─string_column─┬─nullable_string_column─┐
│ 2020-11-25 13:08:22 │ 2             │ example                │
└─────────────────────┴───────────────┴────────────────────────┘
┌─────────inserted_on─┬─string_column─┬─nullable_string_column─┐
│ 2020-11-25 13:08:44 │ 1             │ ᴺᵁᴸᴸ                   │
└─────────────────────┴───────────────┴────────────────────────┘


SELECT 
    max(inserted_on), 
    argMax(string_column, inserted_on) AS non_nullable_column, 
    argMax(nullable_string_column, inserted_on) AS nullable_column_current, 
    nullIf(argMax(ifNull(nullable_string_column, 'null'), inserted_on), 'null') AS nullable_column_wanted
FROM test.argMax_test AS amt

┌────max(inserted_on)─┬─non_nullable_column─┬─nullable_column_current─┬─nullable_column_wanted─┐
│ 2020-11-25 13:08:44 │ 1                   │ example                 │ ᴺᵁᴸᴸ                   │
└─────────────────────┴─────────────────────┴─────────────────────────┴────────────────────────┘
```

Do you think that it is a bug or expected behaviour?
For me it is unexpected so I would appreciate if you have some advice how to fix this other than using my secret value (like 'null' in the example above) for mapping those. 

I have tried it on 20.8.7 revision 54438 and 19.11.12 revision 54423 versions.

Best regards,

Filip

**Comment by den-crane** [comment] 2020-11-25 16:51
```sql
SELECT
    max(inserted_on),
    argMax(string_column, inserted_on) AS non_nullable_column,
    argMax(tuple(nullable_string_column), inserted_on).1 AS nullable_column_current
FROM test.argMax_test AS amt

┌────max(inserted_on)─┬─non_nullable_column─┬─nullable_column_current─┐
│ 2020-11-25 17:47:22 │ 1                   │ ᴺᵁᴸᴸ                    │
└─────────────────────┴─────────────────────┴─────────────────────────┘
```

**Comment by den-crane** [comment] 2020-11-25 17:00
the same with other agg functions

```
select groupArray(x) from (select 1 as x union all select null)
┌─groupArray(x)─┐
│ [1]           │
└───────────────┘

select groupArray(tuple(x)) from (select 1 as x union all select null)
┌─groupArray(tuple(x))─┐
│ [(1),(NULL)]         │
└──────────────────────┘
```

**Comment by filipbacic** [comment] 2020-11-25 18:08
@den-crane Thank you, definitely more elegant and accurate than my solution.

Will this be fixed in the future so that there is no need for those kinds of workarounds?

**Comment by den-crane** [comment] 2020-11-25 18:27
> @den-crane Thank you, definitely more elegant and accurate than my solution.
> 
> Will this be fixed in the future so that there is no need for those kinds of workarounds?

It's nothing to fix. It's a natural behaviour for agg. functions against NULLs.

```
select count(x) from (select 1 as x union all select null)
┌─count(x)─┐
│        1 │
└──────────┘
```

I think CH needs some other functions or modifiers or settings. 
something like `settings agg_treat_nulls_as_value`

**Comment by filipbacic** [comment] 2020-11-25 19:15
> > @den-crane Thank you, definitely more elegant and accurate than my solution.
> > Will this be fixed in the future so that there is no need for those kinds of workarounds?
> 
> It's nothing to fix. It's a natural behaviour for agg. functions against NULLs.
> 
> ```
> select count(x) from (select 1 as x union all select null)
> ┌─count(x)─┐
> │        1 │
> └──────────┘
> ```
> 
> I think CH needs some other functions or modifiers or settings.
> something like `settings agg_treat_nulls_as_value`

I agree, but I would say that in this case aggregate function (max) is performed on non-null column (in my example inserted_on).
Like it says here https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/argmax/, "Calculates the arg value for a **maximum val** value." Maximum val value, not maximum arg value.
For example, this is ok:
```SELECT 
    max(x), 
    argMax(y, x)
FROM 
(
    SELECT 
        1 AS x, 
        'a' AS y
    UNION ALL
    SELECT 
        NULL AS x, 
        NULL AS y
)

┌─max(x)─┬─argMax(y, x)─┐
│      1 │ a            │
└────────┴──────────────┘
```
But it should return whatever there is in arg value in a record where maximum val value is. I don't know if I wrote that clearly enough. :)

**Comment by den-crane** [comment] 2020-11-25 19:26
@filipbacic it's another agg. function -- sortof-any,  not max. 

select argMax(x,y) from (select 1 x, 2 y union all select 2 x, 2 y)
--
1

y = 2 for both of x , so using any we show any(x)=1.

```
select any(x), anyLast(x) from (select null x union all select 1)
┌─any(x)─┬─anyLast(x)─┐
│      1 │          1 │
└────────┴────────────┘
```

**Comment by filipbacic** [comment] 2020-11-25 19:43
@den-crane I would say that any() comes after max, first max(y) is performed (in argMax(x,y)) and then for all records which have y = max(y) any(x) is performed. So if there is just one record with y = max(y) then whatever there is in x it should be returned (in other words any(x) = x when there is just one record).

**Comment by mcgrawia** [comment] 2021-05-26 01:52
Hi,

I just wanted to check if any progress has been made on this issue? It is also causing problems for our use case where we are using a "last point query" materialized view as described in the Altinity blog post [here](https://altinity.com/blog/clickhouse-continues-to-crush-time-series). In our use case we rely on NULL values to show metrics that are no longer relevant in the most recent record, but this bug is causing all of the NULLs to be hidden by stale data.

It seems we have a few work-arounds with the Tuple option above as well as potentially substituting NULLs for negative numbers in our use case, but it would be very helpful for us to see this supported.

I agree with @filipbacic that it seems like `max` should be taken first on the arg column, then any ties should be broken with `any`. Right now, this function does not return correct results when the most recent arg column is NULL, because it returns a value from another row, which is not the corresponding value maximum.

**Comment by alexey-milovidov** [comment] 2022-07-24 22:17
The behavior of argMin, argMax, any, anyLast is exactly as it should be, and it should not be changed to avoid compatibility issues.

**Closed by alexey-milovidov** 2022-07-24 22:17 UTC
Labels: st-wontfix

**Comment by aimfeld** [comment] 2022-11-29 15:37
> I agree with @filipbacic that it seems like `max` should be taken first on the arg column, then any ties should be broken with `any`. Right now, this function does not return correct results when the most recent arg column is NULL, because it returns a value from another row, which is not the corresponding value maximum.

I agree, I'd expect to get NULL in that case. The the current argMax behaviour is very confusing.

**Comment by karthikv2k** [comment] 2023-04-27 21:19
The current argMax/Min behavior is totally confusing and we introduced a prod bug because of it. CH should at least clarify this behavior in docs and provide another function like argMaxWithNulls or something. Other DWH I worked with does handle nulls correctly.
Presto example:
```
trino> WITH sales_data (product_id, sales_amount, region) AS (
    ->     VALUES
    ->         (1, 150.0, 'North America'),
    ->         (2, 300.0, 'North America'),
    ->         (null, 500.0, 'North America'))
    ->
    -> SELECT    max_by(product_id, sales_amount) AS max_sales_product_id
    -> FROM
    ->     sales_data;
 max_sales_product_id
----------------------
                 NULL
(1 row)
```

**Comment by den-crane** [comment] 2023-04-28 02:21
@karthikv2k Yes, Clickhouse does not met your expectations. 

This behavior is possible with Clickhouse without `argMaxWithNulls` https://fiddle.clickhouse.com/c81c0115-bc71-457b-9df4-126042d41949


```sql
WITH sales_data AS
    (
        SELECT *
        FROM VALUES('product_id Nullable(Int64), sales_amount Float64, region String', (1, 150., 'North America'), (2, 300., 'North America'), (NULL, 500., 'North America'))
    )
SELECT argMax(tuple(product_id), sales_amount).1 AS max_sales_product_id
FROM sales_data

Query id: 8d07f167-f850-435d-9ba4-6ed27532dbd4

┌─max_sales_product_id─┐
│                 ᴺᵁᴸᴸ │
└──────────────────────┘
```

**Comment by xoelop** [comment] 2026-05-14 10:27
Hi @den-crane, cool that the tuple workaround works, but seems a bit unintuitive. Would it make sense to support something like `[RESPECT NULLS]` that `any` and [anyLast](https://clickhouse.com/docs/sql-reference/aggregate-functions/reference/anylast) support?
