### ISSUE TITLE
Cannot define `SETTINGS` for `MATERIALIZED VIEW` (with S3 table engine)

### ISSUE THREAD

**Issue by mdonkers** [ClickHouse/ClickHouse#37125] opened 2022-05-11 14:23 UTC
**Describe what's wrong**

I'm trying to create a `MATERIALIZED VIEW` backed by the `S3` table engine, to get data automatically exported to S3 in CSV format (we need CSV so it can be ingested by other tools). A materialized view is more convenient compared to `INSERT INTO` with S3 table engine because this `INSERT` would need to be repeated regularly e.g. from some script.

However creating the `MATERIALIZED VIEW` does not work as only a single file gets created and all other inserts fail with:

```
Object in bucket <bucket> with key metrics/export.csv already exists. If you want to overwrite it, enable setting s3_truncate_on_insert, if you want to create a new file on each insert, enable setting s3_create_new_file_on_insert.
```

I've tried adding the `SETTINGS` as defined in the error message:

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS s3_samples_export (
      date Date,
      series_id UInt64,
      ts DateTime,
      val Float64
)
ENGINE = S3('https://s3.us-west-2.amazonaws.com/<bucket>/metrics/export.csv', 'CSV')
AS SELECT date, series_id, ts, val FROM default.samples
SETTINGS s3_create_new_file_on_insert=1
```

but while the `CREATE MATERIALIZED VIEW` succeeds, I'm still seeing the same error. So perhaps the `SETTINGS` are not parsed for the `VIEW` but for the `SELECT` ?
Though wrapping the `SELECT` in brackets like `...AS (SELECT date, series_id, ts, val FROM default.samples) SETTINGS ...` does not make a difference as the console shows these brackets get stripped when parsing.

Please let me know if there's some way to provide the `SETTINGS` correctly for the `VIEW`, or whether parsing needs to be fixed.

Additionally, but this is less important; while the S3 table function allows defining `PARTITIONED BY`  and with a wildcard `_partition_id` in the name, this is not possible with the S3 table engine. This would be convenient as then we can create a single file per day for example, instead of a single file per insert.

**Does it reproduce on recent release?**

Happens at least on: ClickHouse server version 22.5.1 revision 54455

**How to reproduce**

- Create regular table (**MergeTree)
- Create S3 bucket to which ClickHouse is allowed to write
- Create view similar to the SQL above
- Do some inserts on the regular table, which should get inserted into the view as well
- Verify only a single csv file gets created in S3 and error messages appear in log

**Expected behavior**

Multiple files get created in S3, which include all inserts done in the base table.

**Comment by Avogar** [comment] 2022-05-11 15:52
The problem is that `s3_create_new_file_on_insert` is a query setting, not the storage setting. The value of this setting is taken from local context of an insert query, and insert query is created when we insert to nested table default.samples , so if we insert into `default.samples` without using `s3_create_new_file_on_insert=1` then insert query into s3 will be also without `s3_create_new_file_on_insert`. So there are several possible solutions. First - enable `s3_create_new_file_on_insert` on each insert into default.samples . Second - enable `s3_create_new_file_on_insert` for every query for specified user (for example in config). Third - change the code and somehow check `s3_create_new_file_on_insert` while creating s3 table and use it every insert in this table, but maybe it will require introducing special storage settings for S3 table engine, I will think how to do it better

**Comment by mdonkers** [comment] 2022-05-12 15:43
Update: indeed when setting `s3_create_new_file_on_insert=1` as general setting for the user, and then creating the view, it works as expected.

**Comment by mdonkers** [comment] 2023-04-18 08:41
@Avogar as there is a work-around and clear why the initial setup didn't work, I guess we can close this as unplanned? Won't be picked up as bug, right?

**Comment by Avogar** [comment] 2023-04-18 10:41
Yes, let's close it. We don't want to change this behaviour.

**Closed by Avogar** 2023-04-18 10:41 UTC
Labels: potential bug
