### ISSUE TITLE
Data compressed with different methods (CANNOT_DECOMPRESS)

### ISSUE THREAD

**Issue by luvs** [ClickHouse/ClickHouse#35181] opened 2022-03-10 13:04 UTC
I have 3 ch servers with replication (without sharding) - 2 main ch servers + 1 for experiments with encryption. 

Main servers 22.2.2.1, encrypted 22.2.3.1.

Storage config for encrypted server
```
<yandex>
    <storage_configuration>
        <disks>
            <local>
                <type>local</type>
                <path>/var/lib/clickhouse/</path>
            </local>
            <encrypted_local>
                <type>encrypted</type>
                <disk>local</disk>
                <path>encrypted/</path>
                <algorithm>AES_256_CTR</algorithm>
                <key_hex id="0">1111111111111111111111111111111111111111111111111111111111111111</key_hex>
                <key_hex id="1">2222222222222222222222222222222222222222222222222222222222222222</key_hex>
                <key_hex id="2">3333333333333333333333333333333333333333333333333333333333333333</key_hex>
                <key_hex id="3">4444444444444444444444444444444444444444444444444444444444444444</key_hex>
                <key_hex id="4">5555555555555555555555555555555555555555555555555555555555555555</key_hex>
                <key_hex id="5">6666666666666666666666666666666666666666666666666666666666666666</key_hex>
                <key_hex id="6">7777777777777777777777777777777777777777777777777777777777777777</key_hex>
                <key_hex id="7">8888888888888888888888888888888888888888888888888888888888888888</key_hex>
                <current_key_id>0</current_key_id>
            </encrypted_local>
        </disks>
        <policies>
            <default>
                <volumes>
                    <encrypted>
                        <disk>encrypted_local</disk>
                    </encrypted>
                </volumes>
            </default>
        </policies>
    </storage_configuration>
</yandex>
```

After full sync I get error for this query

```
SELECT
    count(),
    subtractDays(now(), 1) AS date
FROM websites_events
WHERE (UAName = 'IE') AND (EventType = 'checkoutCharge') AND (EventDate >= (today() - 1)) AND (EventTime > subtractDays(now(), 1))
LIMIT 1
FORMAT JSON
```

Error:
```
2022.03.10 12:54:07.946494 [ 204505 ] {755f5830-0217-4750-a746-60604fab13ff} <Error> TCPHandler: Code: 271. DB::Exception: Data compressed with different methods, given method byte 0x4a, previous method byte 0x82: (while reading column UAName): (while reading from part /var/lib/clickhouse/encrypted/data/fundraiseup_production/websites_events/202203_4709777_4762709_384/ from mark 6 with max_rows_to_read = 4256): While executing MergeTreeThread. (CANNOT_DECOMPRESS), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xaebee1a in /usr/bin/clickhouse
1. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0x142633d8 in /usr/bin/clickhouse
2. DB::CompressedReadBufferFromFile::nextImpl() @ 0x14264ab5 in /usr/bin/clickhouse
3. ? @ 0x1445eb21 in /usr/bin/clickhouse
4. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x144259f5 in /usr/bin/clickhouse
5. DB::MergeTreeReaderWide::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&, bool) @ 0x1558ebef in /usr/bin/clickhouse
6. DB::MergeTreeReaderWide::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x1558db6b in /usr/bin/clickhouse
7. DB::MergeTreeRangeReader::DelayedStream::finalize(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0x15d2746e in /usr/bin/clickhouse
8. DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult&, unsigned long&) @ 0x15d2b32a in /usr/bin/clickhouse
9. DB::MergeTreeRangeReader::read(unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&) @ 0x15d2a5d3 in /usr/bin/clickhouse
10. DB::MergeTreeBaseSelectProcessor::readFromPartImpl() @ 0x15d204e8 in /usr/bin/clickhouse
11. DB::MergeTreeBaseSelectProcessor::readFromPart() @ 0x15d215ed in /usr/bin/clickhouse
12. DB::MergeTreeBaseSelectProcessor::generate() @ 0x15d1fd60 in /usr/bin/clickhouse
13. DB::ISource::tryGenerate() @ 0x15a41f35 in /usr/bin/clickhouse
14. DB::ISource::work() @ 0x15a41afa in /usr/bin/clickhouse
15. DB::SourceWithProgress::work() @ 0x15c93bc2 in /usr/bin/clickhouse
16. DB::ExecutionThreadContext::executeTask() @ 0x15a61e03 in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15a55cde in /usr/bin/clickhouse
18. ? @ 0x15a575c8 in /usr/bin/clickhouse
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xaf62937 in /usr/bin/clickhouse
20. ? @ 0xaf663fd in /usr/bin/clickhouse
21. ? @ 0x7f3e80c48609 in ?
22. clone @ 0x7f3e80b6d163 in ?
```

**Comment by alesapin** [comment] 2022-03-10 13:54
@FArthur-cmd, @vitlibar, please, take a look.

**Comment by alexey-milovidov** [comment] 2022-10-24 17:35
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/38381, fixed.

**Closed by alexey-milovidov** 2022-10-24 17:35 UTC
Labels: potential bug
