### ISSUE TITLE
DB::Exception: There was an error on [10.162.xx.xx:9000]: Cannot execute replicated DDL query on leader

### ISSUE THREAD

**Issue by lxswbr** [ClickHouse/ClickHouse#23020] opened 2021-04-13 02:28 UTC
This exception message often appears when truncate cluster table data is executed, and it can be determined that no SQL is using the table. What is the reason for this?

**Comment by tavplubix** [comment] 2021-04-13 21:46
What version of ClickHouse do you use?

**Comment by mjh568412187** [comment] 2021-04-19 13:47
> What version of ClickHouse do you use?

I also encountered the same problem
I am executing optimize table xxx on cluster yyyy and truncate table xxx on cluster yyyy error: Caused by: java.lang.Throwable: Code: 48, e.displayText() = DB::Exception: There was an error on [yh- clickhouse-host06:9000]: Cannot execute replicated DDL query on leader (version 20.3.12.112)

The version of clickhouse is: version 20.3.12.112

**Comment by tavplubix** [comment] 2021-04-19 14:08
I'm asking about version because the issue looks like duplicate of #6704. It was fixed in #13450, but the fix was not backported to versions older than 20.5. We also have fixed a lot of other issues related to `ON CLUSTER` queries recently, so I recommend to upgrade to newer ClickHouse version, because 20.3 is no longer supported. 

I will close this issue, feel free to reopen it or create new one if similar errors will appear on 21.* versions.

**Closed** 2021-04-19 14:08 UTC
Labels: question

**Comment by baofengzhouyu** [comment] 2021-07-07 06:09
I have the same error on  version 20.8.18.32  lts
