### ISSUE TITLE
Query gets wrong results

### ISSUE THREAD

**Issue by EscaperLL** [ClickHouse/ClickHouse#36608] opened 2022-04-25 10:00 UTC
version:v22.3.2.2-lts

DESKTOP-4CGBK1J :)  select '123' as a from test02 t group by a order by a ;

SELECT '123' AS a
FROM test02 AS t
GROUP BY a
ORDER BY a ASC

Query id: 32478c9b-77d4-4db1-aaaa-5bea13b8edbe

Ok.

0 rows in set. Elapsed: 0.020 sec.

**Comment by den-crane** [comment] 2022-04-25 12:18
provide 
1. `show create table test02`
2. `insert into test02 values ...`
3. `select version()`
4. `expected result`

**Comment by EscaperLL** [comment] 2022-04-26 01:36
@den-crane

**Comment by genzgd** [comment] 2022-04-28 02:48
Why are you running a GROUP BY query with a single constant?  This is not a real world use case.

**Comment by EscaperLL** [comment] 2022-04-28 06:20
@genzgd In some cases, you only need to know the number of scene columns in the table. [https://github.com/ClickHouse/ClickHouse/issues/36728](url)

**Comment by genzgd** [comment] 2022-04-28 10:47
What do you mean, 'scene' (maybe you mean 'seen') columns.  Whatever you are trying to do there must be a more sensible way to find that information.

**Comment by den-crane** [comment] 2022-05-02 19:55
```sql
create table test(A Int64) Engine=MergeTree order by A as select 1 a;

select 'a' x from test group by x;
0 rows in set. Elapsed: 0.004 sec.

set allow_experimental_projection_optimization=0;

select 'a' x from test group by x;
┌─x─┐
│ a │
└───┘
```

**Comment by tavplubix** [comment] 2022-05-02 20:40
Duplicate of #36728

**Closed by tavplubix** 2022-05-02 20:40 UTC
Labels: bug, comp-projections
