### ISSUE TITLE
array join + using join

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#27935] opened 2021-08-20 20:50 UTC
Not sure that it valid case in general because of ambiguous naming (I found this in telegram)

```sql
21.3
select * from (select [1,2,3,4] arr) t array join arr as arr join (select  1 arr) s using arr;
┌─arr─┐
│   1 │
└─────┘

21.8.4
select * from (select [1,2,3,4] arr) t array join arr as arr join (select  1 arr) s using arr;
 DB::Exception: Type mismatch of columns to JOIN by: arr: Array(UInt8) at left, s.arr: UInt8 at right.
```

WA replace `using` with `on` ?

```sql
select * from (select [1,2,3,4] arr) t array join arr as arr join (select  1 arr) s on t.arr = s.arr
┌─arr─┬─s.arr─┐
│   1 │     1 │
└─────┴───────┘
```

**Comment by Trundle** [comment] 2021-08-30 16:44
I think this issue is a duplicate of #25612

**Comment by vdimir** [comment] 2021-09-10 08:48
Closed via https://github.com/ClickHouse/ClickHouse/pull/25734

**Closed by vdimir** 2021-09-10 08:48 UTC
Labels: backward compatibility, comp-joins, v21.8-affected
