### ISSUE TITLE
Constant value 0(Int8) is regarded as positional argument and cause out-of-range exception

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#42669] opened 2022-10-26 06:19 UTC
> You have to provide the following information whenever possible.
```SQL
--- T1 table can be any MergeTree table
select 0 as $col1 from T1 group by $col1;
```
then you will get an exception
`Code: 43. DB::Exception: Received from localhost:9101. DB::Exception: Positional argument out of bounds: 0 (exprected in range [1, 1]. (ILLEGAL_TYPE_OF_ARGUMENT)`

It should be caused by the reason: `group by $col1` is replaced by `group by 0` and `0` is regarded as a positional argument.

**Does it reproduce on recent release?**
22.8.5.x

**Comment by alexey-milovidov** [comment] 2022-11-02 01:06
Does not reproduce: https://fiddle.clickhouse.com/fa398280-18cd-4453-8778-64ad75f6774a

**Comment by Alex-Cheng** [comment] 2022-11-30 09:08
The table engine need to be MergeTree. 

I can reproduce it at https://fiddle.clickhouse.com/2741cf80-a441-4af9-8aac-4ff63b3804c1

**Comment by Alex-Cheng** [comment] 2022-11-30 09:08
```SQL
CREATE TABLE t (x UInt8, y String) engine=MergeTree() order by x;
INSERT INTO t VALUES (123, 'Hello');
select 0 as $col1 from t group by $col1;
```

**Comment by Alex-Cheng** [comment] 2022-11-30 09:11
@alexey-milovidov I cannot reopen it. Please take care of the issue. It should be a bug.

**Comment by den-crane** [comment] 2022-12-08 21:25
Also found this issue after upgrade to 22.8
WA: enable_positional_arguments=0

**Comment by alexey-milovidov** [comment] 2022-12-08 23:08
22.8 has this problem: https://fiddle.clickhouse.com/2bcf48f9-13ae-44b8-86f3-2bfccc231b9d
The latest stable version does not have it: https://fiddle.clickhouse.com/354bbbea-22f6-45b0-a6ab-6a359ab416b8

@den-crane maybe we can find a pull request where it was fixed?

**Comment by den-crane** [comment] 2022-12-08 23:24
fix https://github.com/ClickHouse/ClickHouse/pull/41189

This issue is a duplicate of https://github.com/ClickHouse/ClickHouse/issues/40634

**Closed** 2022-12-13 13:03 UTC
Labels: bug, duplicate, st-fixed, v22.8-affected
