### ISSUE TITLE
XML config for user doesn't support names with dots.

### ISSUE THREAD

**Issue by CherkashinSergey** [ClickHouse/ClickHouse#27069] opened 2021-08-02 04:05 UTC
You cannot create a user with XML config  if username contains a dot. But SQL access management allows it.

**How to reproduce**
Cretate a file `some_new_user.xml` in `/etc/clickhouse-server/users.d` and put there following content:
```
<?xml version="1.0"?>
<yandex>
    <users>
        <vasya.pupkin>
		<password>1</password>
        </vasya.pupkin>
    </users>
</yandex>

```
Clickhouse-server will crash and put following message in error log:
```
2021.08.02 06:59:54.256008 [ 12747 ] {} <Error> Application: DB::Exception: Either 'password' or 'password_sha256_hex' or 'password_double_sha1_hex' or 'no_password' or 'ldap' or 'kerberos' must be specified for user vasya.pupkin.
```
* Which ClickHouse server version to use *
21.7.5.29

**SQL to create a user with a dot in a name**
```
CREATE USER vasya.pupkin HOST IP '0.0.0.0', '::/0' IDENTIFIED WITH no_password
```

**Comment by filimonov** [comment] 2021-08-02 08:03
It's a known limitation of XML parser used.

Duplicate of https://github.com/ClickHouse/ClickHouse/issues/6111

**Closed by filimonov** 2021-08-02 08:03 UTC
Labels: bug

**Comment by demurgos** [comment] 2024-03-17 19:03
I don't get why it was marked as duplicate: this issue is specifically about supporting creating users with dots through the XML config file. The linked issue #6111 is a more general issue.

If it's an issue with your parser library, could you link to the relevant issue in the parser library? After a quick look, I think you're using the Poco XML parser, but I did not find any relevant ticket on their GitHub repo.

I'd also add that the situation is actually a bit stranger than "no support": Clickhouse actually creates a user! Using the example from the original post, Clickhouse creates a user named `vasya\.pupkin` (with an antislash in the name).

Clickhouse should either create the user with the right name, or report the error and not create the user. The current situation of creating a user with a broken name is a bug. Could you please re-open this ticket until it is fixed?

**Comment by filimonov** [comment] 2025-01-03 10:22
> I'd also add that the situation is actually a bit stranger than "no support": Clickhouse actually creates a user! Using the example from the original post, Clickhouse creates a user named vasya\.pupkin (with an antislash in the name).

It's true since 24.1, see https://github.com/ClickHouse/ClickHouse/pull/58354 

```
cat <<'EOF' > /etc/clickhouse-server/users.d/some_new_user.xml 
<?xml version="1.0"?>
<clickhouse>
    <users>
        <vasya.pupkin>
            <password>1</password>
        </vasya.pupkin>
    </users>
</clickhouse>
EOF

clickhouse-client --user=vasya\\.pupkin --password=1
```
