### ISSUE TITLE
toString(Date32) works correctly only with the limited range of values

### ISSUE THREAD

**Issue by victor-sushko** [ClickHouse/ClickHouse#31924] opened 2021-11-28 07:28 UTC
The function `toSting` doesn't work correctly with an argument of the type `Date32` if the value of the argument is outside of the range [1970-01-01, 2149-06-06].

**How to reproduce**

ClickHouse server version 21.11.3 revision 54450.
ClickHouse client version 21.11.3.6 (official build).

Run the query:
```SQL
SELECT T.d date, toString(T.d) dateStr
FROM
(
  SELECT '1925-01-01'::Date32 d
  UNION ALL SELECT '1969-12-31'::Date32
  UNION ALL SELECT '1970-01-01'::Date32
  UNION ALL SELECT '2149-06-06'::Date32
  UNION ALL SELECT '2149-06-07'::Date32
  UNION ALL SELECT '2283-11-11'::Date32
 ) AS T
 ORDER BY T.d
```

Rows returned by the query:
```
┌───────date─┬─dateStr────┐
│ 1925-01-01 │ 2104-06-07 │
│ 1969-12-31 │ 2149-06-06 │
│ 1970-01-01 │ 1970-01-01 │
│ 2149-06-06 │ 2149-06-06 │
│ 2149-06-07 │ 1970-01-01 │
│ 2283-11-11 │ 2104-06-06 │
└────────────┴────────────┘
```

**Expected behavior**

Values in the columns **date** and **dateStr** should be the same.
For example, `toString('1969-12-31'::Date32)` should return the string "1969-12-31", but it returns "2149-06-06".

**Comment by alexey-milovidov** [comment] 2021-11-28 13:31
Help wanted from @liuneng1994

**Comment by MaxWk** [comment] 2021-12-02 15:04
@alexey-milovidov assign it to me

**Comment by liuneng1994** [comment] 2022-04-20 03:02
Sorry, I just saw this notice, I checked, the problem still seems to exist, I will spend time to fix the problem.

**Comment by liuneng1994** [comment] 2022-06-02 09:02
> Help wanted from @liuneng1994

I have fixed this problem, which was caused by a low-level error in my implementation of Date32

**Closed** 2022-06-02 13:40 UTC
Labels: help wanted, unfinished code
