### ISSUE TITLE
use_compact_format_in_distributed_parts_names problems

### ISSUE THREAD

**Issue by dregor** [ClickHouse/ClickHouse#11133] opened 2020-05-22 10:24 UTC
Hello, i added two new replicas in my cluster and got this error:

` [ 23165 ] {5a41e916-458e-4372-9f94-e327b725daa1} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 36, e.displayText() = Bad path syntax: /var/lib/clickhouse/data/database/test.....`

because path name was too long, then i try to change password and replication user name to shorter, but it was not enough. And i gon new error :

`020.05.22 10:00:33.133395 [ 65534 ] {bd6c4607-4d19-443d-878b-1a26846b0cbd} <Error> executeQuery: Code: 192, e.displayText() = DB::Exception: replicator: User has been dropped (version 20.4.2.9 (official build)) (from 178.63.41.77:64310) (`

I leve old replication users on servers with the same password but error still was. I found `use_compact_format_in_distributed_parts_names`, update clickhouse, add option, all works, but error about `User has been dropped` still here, and directories with old names still here `/var/lib/clickhouse/data/database/test/replicator:password@ch%2Ds03%2Dr1%2Edomain%2Ecom:9000,replicator:password@ch%2Ds03%2Dr2%2Edomain%2Ecom:9000/`, i try to find them and drop, but gon many new errors :

`2020.05.22 09:44:52.584465 [ 26357 ] {} <Error> database.test DirectoryMonitor: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /var/lib/clickhouse/data/database/test/replicator:password@ch%2Ds03%2Dr1%2Edomain%2Ecom:9000,replicator:password@ch%2Ds03%2Dr2%2Edomain%2Ecom:9000/, Stack trace (when copying this message, always include the lines below): 7. DB::BackgroundSchedulePoolTaskcom::execute() @ 0xcfd91f9 in /usr/bin/clickhouse
`
`(version 20.4.2.9 (official build)) 5. DB::StorageDistributedDirectoryMonitor::processFiles() @ 0xd811886 in /usr/bin/clickhouse 6. DB::StorageDistributedDirectoryMonitor::run() @ 0xd812160 in /usr/bin/clickhouse 0. Poco::FileNotFoundException::FileNotFoundException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10410790 in /usr/bin/clickhouse 8. DB::BackgroundSchedulePool::threadFunction() @ 0xcfd9822 in /usr/bin/clickhouse 0. Poco::FileNotFoundException::FileNotFoundException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10410790 in /usr/bin/clickhouse 8. DB::BackgroundSchedulePool::threadFunction() @ 0xcfd9822 in /usr/bin/clickhouse 0. Poco::FileNotFoundException::FileNotFoundException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10410790 in /usr/bin/clickhouse 8. DB::BackgroundSchedulePool::threadFunction() @ 0xcfd9822 in /usr/bin/clickhouse 0. Poco::FileNotFoundException::FileNotFoundException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10410790 in /usr/bin/clickhouse 8. `

How can i drop info bout this old data from clickhouse ?

**Comment by azat** [comment] 2020-10-30 08:22
>[ 23165 ] {5a41e916-458e-4372-9f94-e327b725daa1} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 36, e.displayText() = Bad path syntax: /var/lib/clickhouse/data/database/test.....
>because path name was too long, then i try to change password and replication user name to shorter, but it was not enough. And i gon new error :

It is hard to say w/o stacktrace is it the expected behavior or not

>020.05.22 10:00:33.133395 [ 65534 ] {bd6c4607-4d19-443d-878b-1a26846b0cbd} <Error> executeQuery: Code: 192, e.displayText() = DB::Exception: replicator: User has been dropped (version 20.4.2.9 (official build)) (from 178.63.41.77:64310) (

Yes, because the credentials is stored in the directory name and they will not be read from the config (sigh)

> I leve old replication users on servers with the same password but error still was. I found use_compact_format_in_distributed_parts_names, update clickhouse, add option, all works, but error about User has been dropped still here, and directories with old names still here /var/lib/clickhouse/data/database/test/replicator:password@ch%2Ds03%2Dr1%2Edomain%2Ecom:9000,replicator:password@ch%2Ds03%2Dr2%2Edomain%2Ecom:9000/, i try to find them and drop, but gon many new errors :

Yes, this is the expected behavior since existing paths are not converted, so it is better to change this setting only after there are no more pending async distributed sends

>How can i drop info bout this old data from clickhouse ?

So the rules for setting use_compact_format_in_distributed_parts_names are:
- `system flush distributed [ on cluster] dist_table`
- stop the server
- `rmdir` old directories (`rmdir` over `rm -r` to avoid removing directories with pending files, or just ignore and `rm -r`)
- set `use_compact_format_in_distributed_parts_names=1`
- start the server

You need some extra steps for two reasons basically:
- use_compact_format_in_distributed_parts_names=1 does not convert existing files (unlikely will be fixed)
- distributed engine does not remove already existing empty directories, and this is pretty easy to fix, and is on my todo list, and this will help in your case, but if and only if, those directories are empty.

**Closed** 2020-11-03 23:21 UTC
Labels: comp-distributed, question

**Comment by azat** [comment] 2020-11-05 21:14
>distributed engine does not remove already existing empty directories, and this is pretty easy to fix, and is on my todo list, and this will help in your case, but if and only if, those directories are empty.

There are some complexity to do this by TTL, but at server start it was done in #16729
