### ISSUE TITLE
set index is broken 

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#17865] opened 2020-12-07 13:05 UTC
when I run this sql, it is not ok:
```
SELECT
    formatDateTime(TS_T_1_.dt, '%Y%m%d') AS T_0_2_,
    sum(room_act_duration) AS T_1_3_,
    countDistinct(room_id) AS T_2_4_,
    countDistinct(if(room_is_exposed = 1, room_id, NULL)) AS T_3_5_
FROM
(
    SELECT
        dt,
        room_id,
        multiIf(room_property = 'business', '商业房', room_property = 'fleet', '家族房', '个人房') AS room_property,
        room_channel,
        room_is_exposed,
        arraySum(groupArray(duration)) + arraySum(arrayFilter(x -> (x < 0), arrayDifference(arrayFlatten(arraySort(x -> (x[1]), groupArray([start_time, end_time])))))) AS room_act_duration
    FROM dws_oversea.ads_anu_onmic_user_room_di_dis
    WHERE (channel_name IN ('af_Social_facebook', 'af_asm_440644258')) AND (multiIf(gender = 1, '男', gender = 2, '女', '未知') IN ('未知', '男')) AND ('BI' = 'BI') AND ('BI' = 'BI') AND ('BI' = 'BI')
    GROUP BY
        dt,
        room_id,
        room_property,
        room_channel,
        room_is_exposed
) AS TS_T_1_
GROUP BY formatDateTime(TS_T_1_.dt, '%Y%m%d')
LIMIT 1000

Received exception from server (version 20.3.10):
Code: 49. DB::Exception: Received from xxxx.xxxx.com:3306. DB::Exception: ColumnUInt8 expected as Set index condition result..
```

but when I remove all the condition that return true(always return true), and it is ok:
```
SELECT
    formatDateTime(TS_T_1_.dt, '%Y%m%d') AS T_0_2_,
    sum(room_act_duration) AS T_1_3_,
    countDistinct(room_id) AS T_2_4_,
    countDistinct(if(room_is_exposed = 1, room_id, NULL)) AS T_3_5_
FROM
(
    SELECT
        dt,
        room_id,
        multiIf(room_property = 'business', '商业房', room_property = 'fleet', '家族房', '个人房') AS room_property,
        room_channel,
        room_is_exposed,
        arraySum(groupArray(duration)) + arraySum(arrayFilter(x -> (x < 0), arrayDifference(arrayFlatten(arraySort(x -> (x[1]), groupArray([start_time, end_time])))))) AS room_act_duration
    FROM dws_oversea.ads_anu_onmic_user_room_di_dis
    WHERE (channel_name IN ('af_Social_facebook', 'af_asm_440644258')) AND (multiIf(gender = 1, '男', gender = 2, '女', '未知') IN ('未知', '男'))
    GROUP BY
        dt,
        room_id,
        room_property,
        room_channel,
        room_is_exposed
) AS TS_T_1_
GROUP BY formatDateTime(TS_T_1_.dt, '%Y%m%d')
LIMIT 1000

┌─T_0_2_───┬─T_1_3_─┬─T_2_4_─┬─T_3_5_─┐
│ 20201204 │  57640 │     24 │     24 │
│ 20201205 │ 116610 │     37 │     37 │
│ 20201202 │ 141527 │     36 │     35 │
│ 20201203 │ 104846 │     24 │     24 │
│ 20201206 │ 160710 │     39 │     39 │
└──────────┴────────┴────────┴────────┘

5 rows in set. Elapsed: 0.049 sec. Processed 2.09 million rows, 210.72 MB (42.97 million rows/s., 4.33 GB/s.)
```

this makes me confused~~  when set index condition used with `and 1 = 1 ` it is broken.

**Comment by Tasselmi** [comment] 2020-12-07 13:14
this is always broken:
```
SELECT *
FROM dws_oversea.ads_anu_onmic_user_room_di_dis
WHERE (dt = '2020-12-02') AND (channel_name IN ('af_Social_facebook', 'af_asm_440644258')) AND (1 = 1)
LIMIT 10

Received exception from server (version 20.3.10):
Code: 49. DB::Exception: Received from xxx.com:3306. DB::Exception: ColumnUInt8 expected as Set index condition result..

0 rows in set. Elapsed: 0.008 sec.
```

**Comment by den-crane** [comment] 2020-12-07 15:45
show create table `dws_oversea.ads_anu_onmic_user_room_di_dis`

**Comment by den-crane** [comment] 2020-12-07 15:51
```
create table set_test(test String , index x1(test) type set(2000) GRANULARITY 1) Engine=MergeTree order by tuple();
insert into set_test select toString(number) from numbers(1000);

SELECT *
FROM set_test
WHERE (test IN ('1', '2')) AND (1 = 1)
LIMIT 10

Query id: 3c9ba27e-449e-42b3-a139-63f9aa2396d4

┌─test─┐
│ 1    │
│ 2    │
└──────┘

2 rows in set. Elapsed: 0.001 sec. Processed 1.00 thousand rows, 11.89 KB (943.91 thousand rows/s., 11.22 MB/s.)
```

**Comment by Tasselmi** [comment] 2020-12-08 03:15
> `show create table dws_oversea.ads_anu_onmic_user_room_di_dis`

```
CREATE TABLE IF NOT EXISTS `dws_oversea`.`ads_anu_onmic_user_room_di_rep` ON CLUSTER `default` (
    `dt` Date,
    `uid` Int64,
    `room_id` Int64,
    `gender` Int32,
    `is_new` Int32,
    `app_id` Int32,
    `vip_level` Int32,
    `r_level` Int32,
    `channel_id` String,
    `channel_name` String,
    `parent_channel_id` String,
    `parent_channel_name` String,
    `room_property` String,
    `room_tag` String,
    `room_types` String,
    `room_channel` String,
    `room_is_exposed` Int32,
    `role` String,
    `start_time` Int64,
    `end_time` Int64,
    `duration` Int64,
    `position` Int32,
    `region_name` String,
    INDEX gender_idx(gender) TYPE minmax GRANULARITY 6,
    INDEX is_new_idx(is_new) TYPE minmax GRANULARITY 6,
    INDEX parent_channel_name_idx(parent_channel_name) TYPE set(2000) GRANULARITY 6,
    INDEX channel_name_idx(channel_name) TYPE set(2000) GRANULARITY 6,
    INDEX room_property_idx(room_property) TYPE set(500) GRANULARITY 6,
    INDEX room_channel_idx(room_channel) TYPE set(500) GRANULARITY 6
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(dt)
ORDER BY (app_id, room_id, uid)
TTL dt + toIntervalDay(1000);


CREATE TABLE IF NOT EXISTS `dws_oversea`.`ads_anu_onmic_user_room_di_dis` ON CLUSTER `default` AS `dws_oversea`.`ads_anu_onmic_user_room_di_rep`
ENGINE = Distributed(default, dws_oversea, ads_anu_onmic_user_room_di_rep, rand());
```

**Comment by jingwangfei** [comment] 2020-12-16 02:29
I ran into the same problem.
When i remove '1 = 1' condition ,  it can run.
confused~~~

**Comment by den-crane** [comment] 2020-12-18 20:15
20.3.21.2_all.deb

**Comment by den-crane** [comment] 2020-12-18 20:25
I cannot reproduce:

```sql
CREATE TABLE x  (
    `dt` Date,
    `uid` Int64,
    `room_id` Int64,
    `gender` Int32,
    `is_new` Int32,
    `app_id` Int32,
    `vip_level` Int32,
    `r_level` Int32,
    `channel_id` String,
    `channel_name` String,
    `parent_channel_id` String,
    `parent_channel_name` String,
    `room_property` String,
    `room_tag` String,
    `room_types` String,
    `room_channel` String,
    `room_is_exposed` Int32,
    `role` String,
    `start_time` Int64,
    `end_time` Int64,
    `duration` Int64,
    `position` Int32,
    `region_name` String,
    INDEX gender_idx(gender) TYPE minmax GRANULARITY 6,
    INDEX is_new_idx(is_new) TYPE minmax GRANULARITY 6,
    INDEX parent_channel_name_idx(parent_channel_name) TYPE set(2000) GRANULARITY 6,
    INDEX channel_name_idx(channel_name) TYPE set(2000) GRANULARITY 6,
    INDEX room_property_idx(room_property) TYPE set(500) GRANULARITY 6,
    INDEX room_channel_idx(room_channel) TYPE set(500) GRANULARITY 6
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(dt)
ORDER BY (app_id, room_id, uid);

INSERT INTO x (channel_name) SELECT 'af_Social_facebook'　FROM numbers(1000000);

SELECT *
FROM x
WHERE (dt = '1970-01-01') AND (channel_name IN ('af_Social_facebook', 'af_asm_440644258')) AND (1 = 1)
LIMIT 10
FORMAT Null

Ok.

**Comment by akuzm** [comment] 2021-02-03 06:14
maybe this one is related https://github.com/ClickHouse/ClickHouse/issues/20019

**Comment by amosbird** [comment] 2021-02-03 14:32
It's already fixed in https://github.com/ClickHouse/ClickHouse/pull/13793 .

**Closed by amosbird** 2021-02-03 14:32 UTC
Labels: bug, st-need-repro
