### ISSUE TITLE
High amount of ZooKeeper requests/CPU Load after upgrade to 22.11.1 from 22.3

### ISSUE THREAD

**Issue by timson** [ClickHouse/ClickHouse#43647] opened 2022-11-25 08:34 UTC
We are using clickhouse-operator for our clickhouse cluster. We have 5 shards, 2 replicas each. Also we have one raw table and 5 MV (TO) with aggregation. Each table has no more than 10 columns. After upgrade from clickhouse version 22.3 to 22.11, we see huge difference in Zookeeper CPU consumption,  and also amount of ZooKeeper requests. Even if I stop data ingestion, I see significant  > 50% cpu usage on Zookeeper Nodes.

<img width="408" alt="Screenshot 2022-11-25 at 10 20 17" src="https://user-images.githubusercontent.com/1760560/203936538-d5645881-ff4c-414f-bc40-2207bdd37854.png">

<img width="408" alt="Screenshot 2022-11-25 at 10 27 23" src="https://user-images.githubusercontent.com/1760560/203936559-9d8afa2f-62d1-44c0-a0cb-eaf5cac71170.png">

I tried to downgrade from 22.11 to 22.10.3.37 but with no luck, zookeeper cpu consumption and amount of requests was the same.

SELECT *
FROM system.events
WHERE event ILIKE '%zoo%'

Query id: 2059d338-c985-45f7-a497-b41516fed7ae

```
┌─event─────────────────────┬─────────value─┬─description───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ZooKeeperInit             │             1 │ Number of times connection with ZooKeeper has been established.                                                                       │
│ ZooKeeperTransactions     │      62272213 │ Number of ZooKeeper operations, which include both read and write operations as well as multi-transactions.                           │
│ ZooKeeperList             │      59566267 │ Number of 'list' (getChildren) requests to ZooKeeper.                                                                                 │
│ ZooKeeperCreate           │         47371 │ Number of 'create' requests to ZooKeeper.                                                                                             │
│ ZooKeeperRemove           │        163665 │ Number of 'remove' requests to ZooKeeper.                                                                                             │
│ ZooKeeperExists           │        566333 │ Number of 'exists' requests to ZooKeeper.                                                                                             │
│ ZooKeeperGet              │       1333409 │ Number of 'get' requests to ZooKeeper.                                                                                                │
│ ZooKeeperMulti            │        595168 │ Number of 'multi' requests to ZooKeeper (compound transactions).                                                                      │
│ ZooKeeperWatchResponse    │        141901 │ Number of times watch notification has been received from ZooKeeper.                                                                  │
│ ZooKeeperWaitMicroseconds │ 2370348154687 │ Number of microseconds spent waiting for responses from ZooKeeper after creating a request, summed across all the requesting threads. │
│ ZooKeeperBytesSent        │    7371458424 │ Number of bytes send over network while communicating with ZooKeeper.                                                                 │
│ ZooKeeperBytesReceived    │    9085809562 │ Number of bytes received over network while communicating with ZooKeeper.                                                             │
└───────────────────────────┴───────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘ 
```

It looks like we start to send a lot of `ZooKeeperList` requests, is it normal behaviour?

**Comment by tavplubix** [comment] 2022-11-25 11:46
It may be caused by https://github.com/ClickHouse/ClickHouse/pull/42878

Do you have too granular partitioning or/and a lot of old partitions that were dropped or cleaned up by TTL? And do you have a lot of replicated tables with low ingestion rate?

Each time a table tries to select parts to merge it creates `ReplicatedMergeTreeMergePredicate` to determine which parts actually can be merged. It lists all partitions to obtain block numbers of INSERTs that are currently in progress. The difference is that before https://github.com/ClickHouse/ClickHouse/pull/42878 it used to list partitions only if there's at least one INSERT in progress. And now it makes extra requests if there are no INSERTs.

When using Apache ZooKeeper, the number of extra list requests equals to the number of partitions registered in ZooKeeper (it includes all partitions you ever had, empty and dropped partitions are never cleaned up). When using ClickHouse Keeper, all list requests are batched into one `MultiRead` request which is much more efficient.

Possible fixes:
 - Apache ZooKeeper supports `MultiRead` requests since version 3.6. We can try to use it in our ZooKeeper client.
 - Add some optimization to avoid listing block numbers in old/empty partitions when constructing `ReplicatedMergeTreeMergePredicate`

Temporary workaround:
1. Ensure that all servers in a cluster are downgraded and you do not have servers with 22.11 or newer version
2. Manually remove `/table_path_in_zk/temp/abandonable_lock-insert` and `/table_path_in_zk/temp/abandonable_lock-other` nodes from ZooKeeper for each table.
Or try to switch to ClickHouse Keeper.

**Comment by timson** [comment] 2022-11-25 12:41
> It may be caused by #42878
> 
> Do you have too granular partitioning or/and a lot of old partitions that were dropped or cleaned up by TTL? And do you have a lot of replicated tables with low ingestion rate?

We are using partitioning per day, and we keep data for 30 days, but for some tables, we keep data for one year (on cold storage). So, maybe yes, we have too many partitions. Also, we don't use TTL,  we just use drop/move partition from cronjobs.

> Possible fixes:
> 
> * Apache ZooKeeper supports `MultiRead` requests since version 3.6. We can try to use it in our ZooKeeper client.
> * Add some optimization to avoid listing block numbers in old/empty partitions when constructing `ReplicatedMergeTreeMergePredicate`
> 
> Temporary workaround:
> 
> 1. Ensure that all servers in a cluster are downgraded and you do not have servers with 22.11 or newer version
> 2. Manually remove `/table_path_in_zk/temp/abandonable_lock-insert` and `/table_path_in_zk/temp/abandonable_lock-other` nodes from ZooKeeper for each table.

Thanks a lot! It helps me. Now all metrics are back to normal and ZooKeeper CPU usage is significantly lower.

>    Or try to switch to ClickHouse Keeper.

We will think about it, but we need to plan and test it first.

**Comment by den-crane** [comment] 2022-11-25 14:48
<img width="1130" alt="Screen Shot 2022-11-25 at 10 44 03 AM" src="https://user-images.githubusercontent.com/19737682/204008689-cfe411dc-5e1d-4d52-a221-4258d2327c39.png">
ZK list operations before/after upgrade from 22.10 to 22.11

**Comment by den-crane** [comment] 2022-11-25 15:35
<img width="1033" alt="Screen Shot 2022-11-25 at 11 34 05 AM" src="https://user-images.githubusercontent.com/19737682/204017069-a89af483-d1df-42f6-b3ab-576ebd0ef356.png">

after removing 8000 znodes with block_numbers for old (TTL-ed) partitions.

```sql
with 'mydb.mytable' as tbl 
select 'rm '|| path||name from system.zookeeper 
where path = ( select zookeeper_path||'/block_numbers/' from system.replicas where database||'.'||table = tbl )
and name not in (select distinct partition_id from system.parts where database||'.'||table = tbl )　
and ctime < now() - interval 30 day and mtime < now() - interval 30 day  
format TSVRaw;
```

**Closed** 2022-11-29 14:55 UTC
Labels: unexpected behaviour, v22.11-affected

**Comment by sdarshil** [comment] 2022-12-15 10:50
I am getting into some kind of same issue as further described , 
My current zookeeper wait time is 7-9 seconds on and average 

I am using grafana to monitor my zookeeper !

<img width="1643" alt="image" src="https://user-images.githubusercontent.com/31997374/207840210-0f965102-f106-4363-92fb-86515623d2f0.png">


I am using clickhouse with 22.11.2 version
i have arround 700-750 replicated merge tree tables 
Zookeeper have 4 Gb ram with best available disk of azure

**Comment by tavplubix** [comment] 2022-12-15 16:48
Ref: https://github.com/ClickHouse/ClickHouse/issues/44263

**Comment by techkuz** [comment] 2023-03-23 08:20
same here from 21.8 to 22.8

**Comment by tavplubix** [comment] 2023-03-23 11:42
> same here from 21.8 to 22.8, ZK

There's no way you could face the same issue after upgrading to 22.8 because 22.8 is not affected by this issue.

**Comment by raosong** [comment] 2023-06-11 01:27
I understand that this issue has been fixed. We recently setup a ClickHouse cluster with version 23.2.4.12, but it looks like we are still seeing this issue.  Any ideas?

![image](https://github.com/ClickHouse/ClickHouse/assets/17915039/c278d576-9255-4d76-b67c-018807a1a9ec)

**Comment by tavplubix** [comment] 2023-06-12 10:07
https://github.com/ClickHouse/ClickHouse/pull/49637 and https://github.com/ClickHouse/ClickHouse/pull/50107 will reduce the number of requests

**Comment by raosong** [comment] 2023-06-19 20:33
Thanks for your reply.  We downgraded from 23.2 to 22.8, but we see this issue too, although it is not as severe as 23.2. It is still  unacceptable high to us.

Our observation is that there were some changes between 21.11 and 22.8 that caused the number of ZK requests significantly higher. And then between 22.8 and 23.2, there was another change making the the number of ZK requests 3 times worse. 

Will your fixes cover all of them? Do you know anything else that can help us reduce the number of requests in 22.8 ? 

Here are the details:

Our ZooKeeper max outstanding requests is 10,000,

We were using 21.11.11 with merge_selecting_sleep_ms = 5,000. The number of ZK outstanding requests was **under 100**. 

We first upgraded to 23.2.4 with merge_selecting_sleep_ms=120,000. The number of ZK outstanding requests was **around 7,500**  with less than 1/3 of the data.

We then downgraded to 22.8 with merge_selecting_sleep_ms=120,000. The number of ZK outstanding requests was **around 2,500** with less than 1/3 of the data. We  started with the sleep ms  as 5,000, but the ZK stopped working because of too many requests. That is why we had to use 120,000 even with 22.8.

Thank you.
