### ISSUE TITLE
optimize table on cluster error

### ISSUE THREAD

**Issue by Zhangft-M** [ClickHouse/ClickHouse#52979] opened 2023-08-03 10:34 UTC
```
CREATE` TABLE `local_test_table` ON CLUSTER `test_cluster`
(

    `id` Int32,
    `day` Int32,
    `time` DateTime DEFAULT now()
)
    ENGINE = ReplicatedMergeTree
    PARTITION BY toYYYYMM(time)
    PRIMARY KEY day
    ORDER BY day;

CREATE TABLE test_table ON CLUSTER test_cluster
AS local_test_table
    ENGINE = Distributed('test_cluster',
                         'test',
                         'local_test_table ',
                         sipHash64(id,day));`
```

and then I execute optimize delete duplicate rows like this
```
OPTIMIZE TABLE `local_test_table ` ON CLUSTER test_cluster PARTITION ID '201910' FINAL
        DEDUPLICATE BY *;
```

there has an error
Coordination::Exception: Transaction failed (No node): Op #0, path: /clickhouse/tables/01/test/local_test_table /block_numbers/201910

I guess there are some errors caused by no partition data on the shard, how to solve this problem?

**Comment by tavplubix** [comment] 2023-08-03 11:45
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/49201

**Closed by tavplubix** 2023-08-03 11:45 UTC
Labels: question
