### ISSUE TITLE
Multi-table JOIN Code: 47, e.displayText() = DB::Exception: Missing columns

### ISSUE THREAD

**Issue by guoqlin** [ClickHouse/ClickHouse#30721] opened 2021-10-27 02:12 UTC
Here are the steps to redo the problem

First built table
create DATABASE if not exists smartbimpp;
create table `smartbimpp`.`avhnzf9rr2vuyesdvryc6w`(`B商品名称` Nullable(String),`B订单数` Nullable(Int64)) Engine=Log;
create table `smartbimpp`.`m1nckbdef438o9em38zepg`(`A商品名称` Nullable(String),`B商品名称` Nullable(String),`同时购买A和B订单数` Nullable(Int64),`总订单数` Nullable(Int64)) Engine=Log;
create table `smartbimpp`.`3qcnfud0fy4lbircffaduw`(`A商品名称` Nullable(String),`A订单数` Nullable(Int64)) Engine=Log;

Then execute the following statement

SELECT
	`m1nckbdef438o9em38zepg`.`B商品名称` AS `B商品名称`,
	`m1nckbdef438o9em38zepg`.`同时购买A和B订单数` AS `同时购买A和B订单数2`
FROM
	`smartbimpp`.`3qcnfud0fy4lbircffaduw` `3qcnfud0fy4lbircffaduw` 
RIGHT JOIN `smartbimpp`.`m1nckbdef438o9em38zepg` `m1nckbdef438o9em38zepg` ON
	`3qcnfud0fy4lbircffaduw`.`A商品名称` = `m1nckbdef438o9em38zepg`.`A商品名称`
LEFT JOIN `smartbimpp`.`avhnzf9rr2vuyesdvryc6w` `avhnzf9rr2vuyesdvryc6w` ON
	`m1nckbdef438o9em38zepg`.`B商品名称` = `avhnzf9rr2vuyesdvryc6w`.`B商品名称`

ClickHouse exception, code: 47, host: 10.10.111.129, port: 8123; Code: 47, e.displayText() = DB::Exception: Missing columns: '同时购买A和B订单数' while processing query: 'SELECT A商品名称 AS --3qcnfud0fy4lbircffaduw.A商品名称, 同时购买A和B订单数, m1nckbdef438o9em38zepg.A商品名称 AS --m1nckbdef438o9em38zepg.A商品名称, B商品名称 AS --m1nckbdef438o9em38zepg.B商品名称 FROM smartbimpp.3qcnfud0fy4lbircffaduw AS 3qcnfud0fy4lbircffaduw ALL RIGHT JOIN
smartbimpp.m1nckbdef438o9em38zepg AS m1nckbdef438o9em38zepg ON --3qcnfud0fy4lbircffaduw.A商品名称 = --m1nckbdef438o9em38zepg.A商品名称', required columns: 'A商品名称' '同时购买A和B订单数' 'm1nckbdef438o9em38zepg.A商品名称' 'B商品名称', maybe you meant: '['A商品名称']' '['A商品名称']', joined columns: 'm1nckbdef438o9em38zepg.A商品名称' 'B商品名称' 'm1nckbdef438o9em38zepg.同时购买A和B订单数' 'm1nckbdef438o9em38zepg.总订单数' (version 21.9.5.16 (official build))

**Comment by nikitamikhaylov** [comment] 2024-04-09 19:41
There is no reproducible example, but looks like the problem should be fixed in `24.3` with new Analyzer enabled by default.

**Closed by nikitamikhaylov** 2024-04-09 19:41 UTC
Labels: comp-joins, st-hold, potential bug
