### ISSUE TITLE
Part already exists (state commited). Code 235. Fluentbit

### ISSUE THREAD

**Issue by invis87** [ClickHouse/ClickHouse#20964] opened 2021-02-19 12:22 UTC
**Describe the bug**
A lot of errors in logs. Also user-level errors in zookeeper.

**Versions**
clickhouse version: `20.5.3.27`
zookeeper version: `3.4.13-2`
fluentbit version: `1.6.8`

**How to reproduce**
* Which interface to use, if matters

We have several servers where docker containers runs. On each server there is one fluentbit container which gather logs from containers and send them to Clickhouse.
Fluentbit config:
```
[OUTPUT]
    Name  http
    Match *
    Host {{ clickhouse_host }}
    Port {{ clickhouse_http_port }}
    URI /?query=INSERT+INTO+{{ clickhouse_log_db }}.log+FORMAT+JSONEachRow
    Format json_stream
    Json_date_key time
    Json_Date_format epoch
    Retry_Limit False
```
So all writes come to one CH replica.

* `CREATE TABLE` statements for all tables involved

```
CREATE TABLE IF NOT EXISTS log
(
    time DateTime64(3),
    level String,
    name String,
    version String,
    msg String,
    container_name String,
    container_id String,
    hostname String,
    req_id String,
    global_req_id String,
    fields String,
    fields_name Array(String),
    fields_value Array(String),
    location String,
    INDEX idx_container_id container_id TYPE set(0) GRANULARITY 1,
    INDEX idx_req_id req_id TYPE set(0) GRANULARITY 1,
    INDEX idx_global_req_id global_req_id TYPE set(0) GRANULARITY 1
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/{database}/log6', '{replica}') 
PARTITION BY toYYYYMMDD(time)
ORDER BY (time, name, level);
```

**Error message and/or stacktrace**
```
2021.02.19 15:13:32.516213 [ 10058 ] {} <Error> fluentbit.log: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 235, e.displayText() = DB::Exception: Part 20210219_1152105_1152111_1 (state Committed) already exists, Stack trace (when copying this message, always
 include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10f1e130 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x95f82cd in /usr/bin/clickhouse
2. ? @ 0xe45d1e3 in /usr/bin/clickhouse
3. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*) @ 0xe4495dc in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long) @ 0xe30471d in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&) @ 0xe3078a3 in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0xe308ed1 in /usr/bin/clickhouse
7. ? @ 0xe3092bd in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0xe5f7e12 in /usr/bin/clickhouse
9. DB::StorageReplicatedMergeTree::queueTask() @ 0xe2bc52e in /usr/bin/clickhouse
10. DB::BackgroundProcessingPool::workLoopFunc() @ 0xe3edba3 in /usr/bin/clickhouse
11. ? @ 0xe3ee4d2 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9625f47 in /usr/bin/clickhouse
13. ? @ 0x9624433 in /usr/bin/clickhouse
14. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
15. __clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so
 (version 20.5.3.27 (official build))
2021.02.19 15:13:34.509317 [ 10062 ] {} <Error> fluentbit.log: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 235, e.displayText() = DB::Exception: Part 20210219_1152150_1152156_1 (state Committed) already exists, Stack trace (when copying this message, always include the lines below):
```
~10 above exceptions per minute

---

Not sure if it correlates with Clickhouse errors, but here is the Zookeeper user-level errors that appears sometimes (not in same times and rarely then CH error above):
```
2021-02-16 13:21:11,735 - INFO  [ProcessThread(sid:3 cport:-1)::PrepRequestProcessor@596] - Got user-level KeeperException when processing sessionid:0x300a3aa3f560000 type:multi cxid:0x13d88 zxid:0xd0000c094 txntype:-1 reqpath:n/a aborting remaining multi ops. Error Path:/clickhouse/tables/01/fluentbit/log6/log Error:K
eeperErrorCode = BadVersion for /clickhouse/tables/01/fluentbit/log6/log
2021-02-16 13:21:12,972 - INFO  [ProcessThread(sid:3 cport:-1)::PrepRequestProcessor@596] - Got user-level KeeperException when processing sessionid:0x100a3d416a00000 type:multi cxid:0xf72c zxid:0xd0000c67e txntype:-1 reqpath:n/a aborting remaining multi ops. Error Path:/clickhouse/tables/01/fluentbit/log6/log Error:Ke
eperErrorCode = BadVersion for /clickhouse/tables/01/fluentbit/log6/log
2021-02-16 13:21:15,010 - INFO  [ProcessThread(sid:3 cport:-1)::PrepRequestProcessor@596] - Got user-level KeeperException when processing sessionid:0x300a3aa3f560000 type:multi cxid:0x14edb zxid:0xd0000c946 txntype:-1 reqpath:n/a aborting remaining multi ops. Error Path:/clickhouse/tables/01/fluentbit/log6/replicas/re
plica2/parts/20210216_1037228_1037308_15 Error:KeeperErrorCode = NodeExists for /clickhouse/tables/01/fluentbit/log6/replicas/replica2/parts/20210216_1037228_1037308_15
```

---

**Additional context**
We have 3 clickhouse replicas and 3 zookeepers. Only one shard.
```
<macros>
    <shard>01</shard>
    <replica>replica{{ clickhouse_id }}</replica>
</macros>
```
clickhouse_id = `01` or `02` or `03`

I heard that this problem can appears when using `Distributed*` engines, but we dont use it.

**Comment by den-crane** [comment] 2021-02-20 00:29
Upgrade all replicas to 20.5.5.74
Check that all replicas have the same CH version.

If error still happen then after the error "DB::Exception: Part xxxx (state Committed)" grep clickhouse-server.log for xxxxx
`grep 20210219_1152105_1152111_1  /var/log/clickhouse-server/clickhouse-server.log  `
at all servers.

Post grep reply here.

Gather `echo stat | nc <zookeeper ip> 2181|grep Mode` from all ZK.

Post grep reply here.

**Comment by invis87** [comment] 2021-02-20 14:12
### Upgrade
 All 3 replicas have same version: `20.5.5.74`

### Partition grep

`k3`:
```
root@k3-video:/home/ansible# grep 20210220_1350044_1350049_1 /var/log/clickhouse-server/clickhouse-server.err.log
root@k3-video:/home/ansible#
```

`k5`:
```
root@k5-video:/home/ansible# grep 20210220_1350044_1350049_1 /var/log/clickhouse-server/clickhouse-server.err.log
2021.02.20 17:03:08.735262 [ 76912 ] {} <Error> fluentbit.log: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 235, e.displayText() = DB::Exception: Part 20210220_1350044_1350049_1 (state Committed) already exists, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x11b61920 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x9f332cd in /usr/bin/clickhouse
2. ? @ 0xf09d09d in /usr/bin/clickhouse
3. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*) @ 0xf0893fc in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long) @ 0xef439cd in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&) @ 0xef46b33 in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0xef48161 in /usr/bin/clickhouse
7. ? @ 0xef4854d in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0xf238462 in /usr/bin/clickhouse
9. DB::StorageReplicatedMergeTree::queueTask() @ 0xeefcb5e in /usr/bin/clickhouse
10. DB::BackgroundProcessingPool::workLoopFunc() @ 0xf02d283 in /usr/bin/clickhouse
11. ? @ 0xf02dbb2 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9f60f47 in /usr/bin/clickhouse
13. ? @ 0x9f5f433 in /usr/bin/clickhouse
14. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so
15. clone @ 0xf94cf in /usr/lib/x86_64-linux-gnu/libc-2.28.so
 (version 20.5.5.74 (official build))
```

`k7`:
```
root@k7-video:/home/ansible# grep 20210220_1350044_1350049_1 /var/log/clickhouse-server/clickhouse-server.err.log
root@k7-video:/home/ansible#
```

### Partition zoo state

`k3`:
```
root@k3-video:/home/ansible# echo stat | nc localhost 2181|grep Mode
Mode: follower
```

`k5`:
```
root@k5-video:/home/ansible# echo stat | nc localhost 2181|grep Mode
Mode: leader
```

`k7`:
```
root@k7-video:/home/ansible# echo stat | nc localhost 2181|grep Mode
Mode: follower
```

**Comment by den-crane** [comment] 2021-02-20 15:04
>clickhouse-server.err.log

err.log has ZERO information about part creation.

I asked clickhouse-server.log

**Comment by invis87** [comment] 2021-02-20 16:02
Ok, sorry.

### Partition grep

`k3`:
```
root@k3-video:/home/ansible# zgrep 20210220_1350044_1350049_1 /var/log/clickhouse-server/clickhouse-server.log*
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.688374 [ 738 ] {} <Debug> fluentbit.log: Fetching part 20210220_1350044_1350049_1 from /clickhouse/tables/01/fluentbit/log6/replicas/replica3
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.704444 [ 744 ] {} <Information> fluentbit.log: Will not fetch part 20210220_1350044_1350049_1 covering 20210220_1350046_1350046_0. Not executing log entry for part 20210220_1350044_1350049_1 because another log entry for the same part is being processed. This shouldn't happen often.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.706474 [ 744 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350044_1350049_1 because another log entry for the same part is being processed. This shouldn't happen often.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.706492 [ 744 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350046_1350046_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.706503 [ 744 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350047_1350047_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.706514 [ 744 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350048_1350048_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.706540 [ 744 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350049_1350049_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.706584 [ 738 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://k7-video.kol.wb.ru:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01%2Ffluentbit%2Flog6%2Freplicas%2Freplica3&part=20210220_1350044_1350049_1&client_protocol_version=2&compress=false
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.712259 [ 738 ] {} <Trace> fluentbit.log: Renaming temporary part tmp_fetch_20210220_1350044_1350049_1 to 20210220_1350044_1350049_1.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.713144 [ 748 ] {} <Information> fluentbit.log: Will not fetch part 20210220_1350044_1350049_1 covering 20210220_1350044_1350044_0. Not executing log entry for part 20210220_1350044_1350049_1 because another log entry for the same part is being processed. This shouldn't happen often.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.714627 [ 748 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350044_1350049_1 because another log entry for the same part is being processed. This shouldn't happen often.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.714643 [ 748 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350044_1350044_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.714656 [ 748 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350046_1350046_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.714667 [ 748 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350047_1350047_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.714678 [ 748 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350048_1350048_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.714688 [ 748 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350049_1350049_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.714784 [ 738 ] {} <Debug> fluentbit.log: Fetched part 20210220_1350044_1350049_1 from /clickhouse/tables/01/fluentbit/log6/replicas/replica3
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.716549 [ 738 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350044_1350049_1 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.717361 [ 743 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350044_1350044_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.717384 [ 743 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350046_1350046_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.717395 [ 743 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350047_1350047_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.717421 [ 743 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350048_1350048_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.717431 [ 743 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350049_1350049_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.717938 [ 738 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350044_1350044_0 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.719163 [ 738 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350046_1350046_0 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.720818 [ 738 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350047_1350047_0 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.729742 [ 751 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350048_1350048_0 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.729759 [ 738 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350049_1350049_0 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.966336 [ 747 ] {} <Trace> fluentbit.log: Executing log entry to merge parts 20210220_1349973_1350043_15, 20210220_1350044_1350049_1, 20210220_1350050_1350050_0, 20210220_1350051_1350051_0, 20210220_1350052_1350052_0 to 20210220_1349973_1350052_16
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.967241 [ 747 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 20210220_1350044_1350049_1, total 684 rows starting from the beginning of the part
```

`k5`:
```
root@k5-video:/home/ansible# zgrep 20210220_1350044_1350049_1 /var/log/clickhouse-server/clickhouse-server.log*
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.659263 [ 76905 ] {} <Debug> fluentbit.log: Fetching part 20210220_1350044_1350049_1 from /clickhouse/tables/01/fluentbit/log6/replicas/replica3
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.664267 [ 76905 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://k7-video.kol.wb.ru:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01%2Ffluentbit%2Flog6%2Freplicas%2Freplica3&part=20210220_1350044_1350049_1&client_protocol_version=2&compress=false
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.669290 [ 76905 ] {} <Trace> fluentbit.log: Renaming temporary part tmp_fetch_20210220_1350044_1350049_1 to 20210220_1350044_1350049_1.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.673238 [ 76917 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350047_1350047_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.673277 [ 76917 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350048_1350048_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.673292 [ 76917 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350049_1350049_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.673302 [ 76917 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350044_1350049_1 because another log entry for the same part is being processed. This shouldn't happen often.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.677662 [ 76907 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350047_1350047_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.677684 [ 76907 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350048_1350048_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.677693 [ 76905 ] {} <Debug> fluentbit.log: Part 20210220_1350044_1350044_0 is rendered obsolete by fetching part 20210220_1350044_1350049_1
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.677695 [ 76907 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350049_1350049_0 because it is covered by part 20210220_1350044_1350049_1 that is currently executing
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.677734 [ 76905 ] {} <Debug> fluentbit.log: Fetched part 20210220_1350044_1350049_1 from /clickhouse/tables/01/fluentbit/log6/replicas/replica3
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.677752 [ 76907 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350044_1350049_1 because another log entry for the same part is being processed. This shouldn't happen often.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.679190 [ 76905 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350047_1350047_0 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.680488 [ 76905 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350048_1350048_0 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.681601 [ 76905 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350049_1350049_0 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.701108 [ 76905 ] {} <Trace> fluentbit.log (ReplicatedMergeTreeQueue): Not merging into part 20210220_1350044_1350049_1 because part 20210220_1350046_1350046_0 is not ready yet (log entry for that part is being processed).
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.717250 [ 76919 ] {} <Trace> fluentbit.log (ReplicatedMergeTreeQueue): Not merging into part 20210220_1350044_1350049_1 because part 20210220_1350046_1350046_0 is not ready yet (log entry for that part is being processed).
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.720596 [ 76918 ] {} <Trace> fluentbit.log (ReplicatedMergeTreeQueue): Not merging into part 20210220_1350044_1350049_1 because part 20210220_1350046_1350046_0 is not ready yet (log entry for that part is being processed).
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.722952 [ 76912 ] {} <Debug> fluentbit.log: Fetching part 20210220_1350044_1350049_1 from /clickhouse/tables/01/fluentbit/log6/replicas/replica3
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.731367 [ 76909 ] {} <Debug> fluentbit.log (ReplicatedMergeTreeQueue): Not executing log entry for part 20210220_1350044_1350049_1 because another log entry for the same part is being processed. This shouldn't happen often.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.732122 [ 76912 ] {} <Trace> fluentbit.log: Found local part 20210220_1350044_1350049_1 with the same checksums as 20210220_1350044_1350049_1
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.732217 [ 76912 ] {} <Debug> fluentbit.log: Cloning part /var/lib/clickhouse/data/fluentbit/log/20210220_1350044_1350049_1/ to /var/lib/clickhouse/data/fluentbit/log/tmp_clone_20210220_1350044_1350049_1
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.734006 [ 76912 ] {} <Trace> fluentbit.log: Renaming temporary part tmp_clone_20210220_1350044_1350049_1 to 20210220_1350044_1350049_1.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.735262 [ 76912 ] {} <Error> fluentbit.log: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 235, e.displayText() = DB::Exception: Part 20210220_1350044_1350049_1 (state Committed) already exists, Stack trace (when copying this message, always include the lines below):
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.772564 [ 76918 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350044_1350049_1 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.773917 [ 76918 ] {} <Debug> fluentbit.log: Skipping action for part 20210220_1350046_1350046_0 because part 20210220_1350044_1350049_1 already exists.
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.962472 [ 76915 ] {} <Trace> fluentbit.log: Executing log entry to merge parts 20210220_1349973_1350043_15, 20210220_1350044_1350049_1, 20210220_1350050_1350050_0, 20210220_1350051_1350051_0, 20210220_1350052_1350052_0 to 20210220_1349973_1350052_16
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2021.02.20 17:03:08.963514 [ 76915 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 20210220_1350044_1350049_1, total 684 rows starting from the beginning of the part
```

`k7`:
```
root@k7-video:/home/ansible# zgrep 20210220_1350044_1350049_1 /var/log/clickhouse-server/clickhouse-server.log*
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2021.02.20 17:03:08.607996 [ 27903 ] {} <Trace> fluentbit.log: Created log entry /clickhouse/tables/01/fluentbit/log6/log/log-0066738490 for merge 20210220_1350044_1350049_1
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2021.02.20 17:03:08.611161 [ 27880 ] {} <Trace> fluentbit.log: Executing log entry to merge parts 20210220_1350044_1350044_0, 20210220_1350045_1350045_0, 20210220_1350046_1350046_0, 20210220_1350047_1350047_0, 20210220_1350048_1350048_0, 20210220_1350049_1350049_0 to 20210220_1350044_1350049_1
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2021.02.20 17:03:08.621784 [ 27880 ] {} <Trace> fluentbit.log: Renaming temporary part tmp_merge_20210220_1350044_1350049_1 to 20210220_1350044_1350049_1.
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2021.02.20 17:03:08.663438 [ 28727 ] {} <Trace> InterserverIOHTTPHandler: Request URI: ?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01%2Ffluentbit%2Flog6%2Freplicas%2Freplica3&part=20210220_1350044_1350049_1&client_protocol_version=2&compress=false
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2021.02.20 17:03:08.663465 [ 28727 ] {} <Trace> fluentbit.log (Replicated PartsService): Sending part 20210220_1350044_1350049_1
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2021.02.20 17:03:08.707022 [ 31232 ] {} <Trace> InterserverIOHTTPHandler: Request URI: ?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F01%2Ffluentbit%2Flog6%2Freplicas%2Freplica3&part=20210220_1350044_1350049_1&client_protocol_version=2&compress=false
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2021.02.20 17:03:08.707054 [ 31232 ] {} <Trace> fluentbit.log (Replicated PartsService): Sending part 20210220_1350044_1350049_1
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2021.02.20 17:03:08.930697 [ 27871 ] {} <Trace> fluentbit.log: Executing log entry to merge parts 20210220_1349973_1350043_15, 20210220_1350044_1350049_1, 20210220_1350050_1350050_0, 20210220_1350051_1350051_0, 20210220_1350052_1350052_0 to 20210220_1349973_1350052_16
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2021.02.20 17:03:08.931621 [ 27871 ] {} <Trace> MergeTreeSequentialSource: Reading 2 marks from part 20210220_1350044_1350049_1, total 684 rows starting from the beginning of the part
```

**Comment by den-crane** [comment] 2021-02-20 16:52
не хватает все равно логов, надо все файлы целиком.

я думаю есть какой-то рейс, сервера видят новые парты, но не видят задания на мерж этих партов.
возможно проблема из-за того что зукиперы тоже на этих хостах и поэтому тормозят.

k7 смержил парт ( все _0 парты тоже на нем )
k5 увидел новый парт _1 и скачал
k5 увидел задание на мерж, но _0 партов почему-то у него нет, поэтому он решил скачать результат, тот же самый _1
k5 после скачки обнаружилось что такой парт уже есть и запись в зукипере о нем тоже есть, вывалил ошибку.

**Comment by alexey-milovidov** [comment] 2021-02-21 12:56
Does the issue reproduce on recent releases? The current stable release is 21.2.

**Comment by invis87** [comment] 2021-02-24 10:44
Update to `(version 21.2.4.6 (official build))` didn't help.

---

So the last idea is to move Zookeepers away from Clickhouse nodes?

**Comment by EvgenyVinogradov** [comment] 2021-04-06 17:59
I have exactly same issue with 21.4.3.25. ZK is away from Clickhouse nodes.

**Comment by UnamedRus** [comment] 2021-04-21 14:08
@EvgenyVinogradov 

How many replicas do you have, and in how much replicas do you insert your data?

**Comment by filimonov** [comment] 2021-04-23 15:42
We saw that issue few times in different scenarios recently. 

@EvgenyVinogradov can you also try to disable `optimize_on_insert` ?

**Closed** 2021-06-13 21:46 UTC
Labels: obsolete-version, st-need-info

**Comment by buptzjj** [comment] 2022-03-01 10:07
i met same problem, and i don't known if it is related to zk high pressure,because we insert data into ch in a high speed, nearly 200MB/s。We use ReplicatedMergeTree engine and two replicas，our ch version is 21.9.2.1。
