### ISSUE TITLE
TCPHandler: Code: 53, e.displayText() = DB::Exception: Cannot convert: String to Nullable(String)

### ISSUE THREAD

**Issue by SerapSun** [ClickHouse/ClickHouse#19609] opened 2021-01-26 09:31 UTC
I set up a cluster environment with three shards and one copy. When I write to the distributed table through the clickhouse driver, it is not saved, but the clickhouse log is always saved. What is the reason?

TCPHandler: Code: 53, e.displayText() = DB::Exception: Cannot convert: String to Nullable(String), Stack trace:

0. DB::recursiveTypeConversion(COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) @ 0xd940984 in /usr/bin/clickhouse
1. DB::NativeBlockInputStream::readImpl() @ 0xdf412c9 in /usr/bin/clickhouse
2. DB::IBlockInputStream::read() @ 0xd8a0715 in /usr/bin/clickhouse
3. DB::TCPHandler::receiveData(bool) @ 0xe7408f1 in /usr/bin/clickhouse
4. DB::TCPHandler::receivePacket() @ 0xe739ddc in /usr/bin/clickhouse
5. DB::TCPHandler::readDataNext(unsigned long const&, int const&) @ 0xe73b56f in /usr/bin/clickhouse
6. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0xe73a31e in /usr/bin/clickhouse
7. DB::TCPHandler::runImpl() @ 0xe735929 in /usr/bin/clickhouse
8. DB::TCPHandler::run() @ 0xe741c47 in /usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x10eebb1f in /usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x10eed531 in /usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x1101ab09 in /usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x11016a9a in /usr/bin/clickhouse
13. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
14. __clone @ 0x12171f in /lib/x86_64-linux-gnu/libc-2.27.so
收起

**Comment by alexey-milovidov** [comment] 2021-01-26 19:30
It indicated that there is some mismatch between table definitions.
Could you please share the definitions of all related tables? Also please tell, what "clickhouse driver" do you use and how exactly?

**Comment by SerapSun** [comment] 2021-01-27 01:33
clickhouse driver:
 <dependency>
          <groupId>ru.yandex.clickhouse</groupId>
          <artifactId>clickhouse-jdbc</artifactId>
          <version>0.2.4</version>
   </dependency>

CREATE TABLE genie_report_statistics.order_item ON CLUSTER ch_cluster (
id String,
merchant_id String,
channel_id String,
shop_id String,
order_id String,
external_shop_id String,
external_order_sn String,
external_order_item_id String,
external_product_id Nullable(String),
external_variation_id Nullable(String),
external_status Nullable(String),
spu Nullable(String),
sku Nullable(String),
product_name Nullable(String),
product_image Nullable(String),
variation_name Nullable(String),
quantity UInt32,
actual_price decimal(20,6),
original_price decimal(20,6),
original_total_price decimal(20,6),
discounted_price  decimal(20,6),
actual_total_price decimal(20,6),
cancel_reason Nullable(String),
logistics_id Nullable(String),
package_id  Nullable(String),
invoice_number Nullable(String),
delivery_type Nullable(String),
delivery_method Nullable(String),
logistics_provider_id Nullable(String),
logistics_provider_name Nullable(String),
logistics_tracking_number Nullable(String),
cancel_reason_note Nullable(String),
cancel_by Nullable(String),
cancel_operator Nullable(String),
last_sync_datetime DateTime,
external_create_datetime DateTime,
external_update_datetime DateTime,
external_create_datetime_hour DateTime,
create_datetime DateTime,
partition_code UInt16
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/genie_report_statistics/{layer}-{shard}/order_item', '{replica}',external_update_datetime)
partition by (partition_code) 
order by (id) 
primary key id;

CREATE TABLE genie_report_statistics.order_item_all ON CLUSTER ch_cluster AS genie_report_statistics.order_item ENGINE = Distributed(ch_cluster, genie_report_statistics, order_item, partition_code);

**Comment by ogerasymenko** [comment] 2021-02-25 14:22
same for me
```ClickHouse client version 20.8.12.2 (official build).
Connecting to 127.0.0.1:9000 as user analytics.
Connected to ClickHouse server version 20.8.12 revision 54438.```

<Error> executeQuery: Code: 53, e.displayText() = DB::Exception: Cannot convert: Nullable(String) to String (version 20.8.12.2 (official build))

**Comment by alexey-milovidov** [comment] 2021-06-13 21:50
@azat Any clue?

**Comment by azat** [comment] 2021-06-16 21:26
> <Error> executeQuery: Code: 53, e.displayText() = DB::Exception: Cannot convert: Nullable(String) to String (version 20.8.12.2 (official build))

@ogerasymenko I guess you have different table structure on remote nodes, and 20.8 does not includes #19947.

Can you do the following please:
- hare full exception with the stacktrace? (you can run client like this `clickhouse-client --stacktrace ...`)
- check latest stable
- share the reproducer (if you will be able to reproduce this with the latest stable version)

**Comment by azat** [comment] 2021-06-16 21:26
> ru.yandex.clickhouse clickhouse-jdbc 0.2.4

Can this be an issue in jdbc? @SerapSun can you reproduce the error using native clickhouse-client?

**Comment by den-crane** [comment] 2021-06-16 22:41
>TCPHandler: 

BUT ru.yandex.clickhouse clickhouse-jdbc 0.2.4 works over http and uses `insert into ... values ()()()`
It's possible to use RowBinary or Native using jdbc, but in this case you form a RowBinary stream yourself, and it's up to you to use correct types.

>Cannot convert: String to Nullable(String),
>Cannot convert: Nullable(String) to String

Not the same.

I would close this because of NO INFO. Most probably it's a human error.

**Closed** 2021-06-16 23:05 UTC
Labels: question, st-need-info
