### ISSUE TITLE
funcion  plus() error (NOT_FOUND_COLUMN_IN_BLOCK) in 23.3.1.2823

### ISSUE THREAD

**Issue by joaozandonadatacosmos** [ClickHouse/ClickHouse#48721] opened 2023-04-12 15:30 UTC
After upgrading my cluster to version 23.3.1.2823, I noticed that some views stopped working, and the error displayed is: `SQL Error [10] [07000]: Code: 10. DB::Exception: Not found column plus(created_at, toIntervalDay(3)) in block id Int32 Int32(size = 0), users_id Int32 Int32(size = 0), hwid String String(size = 0), created_at DateTime UInt32(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK) (version 23.3.1.2823 (official build))`

*error when try to use view `mybase.trials_vw`*

Create View DLL: 
```
CREATE VIEW mybase.trials_vw
AS
SELECT
    t.id,
    t.users_id AS user_id,
    t.hwid,
    t.created_at AS trial_start,
    t.created_at + toIntervalDay(3) AS trial_end,
    if((now() >= t.created_at) AND (now() >= (t.created_at + toIntervalDay(3))), 0, 1) AS during_trial
FROM mybasel.trials_mysql_copy AS t;
```
Create Table DDL
```
CREATE TABLE mybase.trials_mysql_copy
(
    `id` Int32,
    `users_id` Int32,
    `hwid` String,
    `created_at` DateTime
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/db_uuid/{uuid}', '{replica}')
PARTITION BY tuple()
ORDER BY id
SETTINGS index_granularity = 8192;
```
I have the same scenario running on version 22.12.3.5 perfectly.

**Expected behavior**
when execute `select plus(now(),toIntervalDay(3))` the function plus works
`select plus(toDateTime('2023-04-15 15:18:00'), toIntervalDay(3))` works too

![image](https://user-images.githubusercontent.com/126915819/231504264-5509ed8a-c2bd-4a56-a933-a58c02f3b626.png)

**Comment by joaozandonadatacosmos** [comment] 2023-04-12 15:42
same error
```
clickhouse01 :) select plus(toDateTime(`created_at`),toIntervalDay(3)) from mytable.login SETTINGS query_plan_read_in_order = 0

SELECT toDateTime(created_at) + toIntervalDay(3)
FROM mytable.login
SETTINGS query_plan_read_in_order = 0

Query id: 0f1b7f2f-cb8d-4ee9-b36a-7e3b7db14d34


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 23.3.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column plus(toDateTime(created_at), toIntervalDay(3)) in block created_at DateTime UInt32(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK)
```

**Comment by joaozandonadatacosmos** [comment] 2023-04-12 17:17
Sorry for confusing the tables, login is another table that also encounters the issue. 'created_at' is used in the view as 'trial_start', I add 3 more days to 'created_at' to obtain 'trial_end', and 'during_trial' is just to check if the current date is within this interval. That's why I used it in the last test.

I re-ran the tests above using only the tables I mentioned at the beginning.

![image](https://user-images.githubusercontent.com/126915819/231532769-22349f60-d82a-4e7c-9946-e68dc79a39d7.png)

And these tests, using version 22.12.3, the same queries are working without any errors.

![image](https://user-images.githubusercontent.com/126915819/231533738-a98ee7e4-d1d5-4cab-82b5-db34a55ce85c.png)

**Comment by den-crane** [comment] 2023-04-12 17:24
you mean something like this https://fiddle.clickhouse.com/78529f04-99ba-46e4-ad69-a787a8416353 
fails for you ?

**Comment by den-crane** [comment] 2023-04-12 17:26
try drop and create view again. It could be because of upgrade, definitions of the view is incompatible.

**Comment by joaozandonadatacosmos** [comment] 2023-04-12 17:46
> you mean something like this https://fiddle.clickhouse.com/78529f04-99ba-46e4-ad69-a787a8416353 fails for you ?

yes, i have done this https://fiddle.clickhouse.com/423602c8-bdf5-42ea-b61c-151cf0f829b2 using the data that i have on table and still not working for me, on fiddle works perfectly


> try drop and create view again. It could be because of upgrade, definitions of the view is incompatible.

actually the problem its not the view, just `SELECT created_at + toIntervalDay(3) AS trial FROM greenball.trials_mysql_copy;` shows that error.
the problems happens when i try to use plus() function, like that

![image](https://user-images.githubusercontent.com/126915819/231538975-8c414668-03f2-484f-a1e8-bdbf3b7736b4.png)

i've tried without the alias too `SELECT created_at + toIntervalDay(3) FROM greenball.trials_mysql_copy;`


****One of my nodes is on version 23.1.3 revision 54461 and is functioning properly, while the other 2 nodes on version 23.1.3 revision 54462 are encountering this error, im using ReplicatedReplacingMergeTree ENGINE, would it be possible to test on Fiddle using this revision version?****

**Comment by den-crane** [comment] 2023-04-12 17:59
>One of my nodes is on version 23.1.3 revision 54461 and is functioning properly, while the other 2 nodes on version 23.1.3 revision 54462 are encountering this error, im using ReplicatedReplacingMergeTree ENGINE, would it be possible to test on Fiddle using this revision version?

Do you mean you have a cluster with different versions of Clickhouse?

I don't understand where did you get 2 different revisions of 23.1.3.

Can you share `select name,value from system.settings where changed` ?

**Comment by joaozandonadatacosmos** [comment] 2023-04-12 18:06
> Do you mean you have a cluster with different versions of Clickhouse?

yes, i've updated them together, i have no idea why this difference.
clickhouse01 - 23.3.1 revision 54462. 
clickhouse02 - 23.3.1 revision 54462.
clickhouse03 - 23.3.1 revision 54461.

> Can you share select name,value from system.settings where changed ?

Sure!
```
clickhouse01 :) select name,value from system.settings where changed

SELECT
    name,
    value
FROM system.settings
WHERE changed

Query id: 56206542-dd14-4b03-ad31-1485fd6f27a7

┌─name────────────────────────────────────────────────┬─value─────┐
│ max_block_size                                      │ 1024      │
│ aggregation_memory_efficient_merge_threads          │ 1         │
│ allow_experimental_parallel_reading_from_replicas   │ 1         │
│ async_insert_deduplicate                            │ 0         │
│ allow_suspicious_codecs                             │ 1         │
│ cancel_http_readonly_queries_on_client_close        │ 1         │
│ deduplicate_blocks_in_dependent_materialized_views  │ 1         │
│ optimize_skip_merged_partitions                     │ 1         │
│ allow_experimental_database_replicated              │ 1         │
│ async_insert                                        │ 1         │
│ wait_for_async_insert                               │ 0         │
│ wait_for_async_insert_timeout                       │ 5000      │
│ async_insert_max_data_size                          │ 100000000 │
│ async_insert_max_query_number                       │ 1000      │
│ async_insert_busy_timeout_ms                        │ 15000     │
│ load_marks_asynchronously                           │ 1         │
│ allow_asynchronous_read_from_io_pool_for_merge_tree │ 1         │
│ max_streams_for_merge_tree_reading                  │ 16        │
│ insert_keeper_max_retries                           │ 200       │
│ insert_keeper_retry_max_backoff_ms                  │ 10        │
│ allow_experimental_projection_optimization          │ 1         │
└─────────────────────────────────────────────────────┴───────────┘

21 rows in set. Elapsed: 0.001 sec.

```

**Comment by den-crane** [comment] 2023-04-12 18:09
│ allow_experimental_parallel_reading_from_replicas   │ 1 


https://fiddle.clickhouse.com/e764ffb4-60a7-4f8a-b09c-6543ad8db306

duplicate of https://github.com/ClickHouse/ClickHouse/issues/48367

**Comment by den-crane** [comment] 2023-04-12 18:10
Disable allow_experimental_parallel_reading_from_replicas, it is experimental and never worked properly.

**Closed** 2023-04-12 18:10 UTC
Labels: unexpected behaviour
