### ISSUE TITLE
current database is not propagated with on_cluster in AS clause

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#39500] opened 2022-07-22 14:59 UTC
```sql
create database test on cluster c1;
use test;
create table test on cluster c1 (A Int64) Engine=Log;

create  table d on cluster c1 as test Engine=Distributed('c1', currentDatabase(), test);
Code: 60. DB::Exception: Table dw.test doesn't exist. (UNKNOWN_TABLE) (version 22.6.3.35 (official build))

create  table d on cluster c1 as test.test Engine=Distributed('c1', currentDatabase(), test);
OK
```

it fails because `as test`  is looked in a default database (`dw` is default in my case).

**Comment by tavplubix** [comment] 2022-07-22 16:46
Duplicate of #37318

**Closed by tavplubix** 2022-07-22 16:46 UTC
Labels: feature, usability
