### ISSUE TITLE
Dropping a view and immediately restarting the server -> error when inserting into the source table

### ISSUE THREAD

**Issue by tom-clickhouse** [ClickHouse/ClickHouse#37297] opened 2022-05-17 15:21 UTC
**Describe the unexpected behaviour**

There is a source table Ts, a materialized view MV, and a destination table Td.
Ts -> MV -> Td.

No replication or sharding.

When MV is dropped and the ClickHouse server is immediately restarted, then inserting into Ts fails with an error message saying that MV no longer exists.

**How to reproduce**

### Preparation

```
Start server
```

Prepare tables and view

```
CREATE TABLE t (v UInt32) ENGINE MergeTree ORDER BY v;
CREATE TABLE t_mv (v_sqr UInt32) ENGINE MergeTree ORDER BY v_sqr;
INSERT INTO t VALUES (1);
SELECT * FROM t; -- 1, as expected
SELECT * FROM t_mv; -- nothing, as expected

CREATE MATERIALIZED VIEW mv TO t_mv AS SELECT v*v AS v_sqr FROM t;
INSERT INTO t VALUES (2);
SELECT * FROM t; -- 1, 2, as expected
SELECT * FROM t_mv; -- 4, as expected
```

### Actual issue

Now drop view and restart server to trigger actual issue

```
DROP VIEW mv;
INSERT INTO t VALUES (3);
SELECT * FROM t; -- 1, 2, 3, as expected
SELECT * FROM t_mv; -- 4, as expected

Restart server

INSERT INTO t VALUES (4);
```

### Actual behavior

Last insert fails with
`-- Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table [default.mv](https://default.mv/) (7a8c9afe-b959-4d71-954b-820884bb7453) doesn't exist. (UNKNOWN_TABLE)`

### Expected behavior

Last inserts successfully adds new row to `t`.

## Workarounds

When running `DROP VIEW mv NO DELAY;` instead of regular DROP everything works as expected.

## Notes

When waiting for 8 minutes after restart ([default value](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#database_atomic_delay_before_drop_table_sec) for `database_atomic_delay_before_drop_table_sec` parameter) inserts are working as expected.

Right after issuing DROP there is line in logs that says
`DatabaseCatalog: Not found any suitable tables to drop, still have 1 tables in drop queue (0 of them are in use). Will check again after 480 seconds`

And during restart there's this line:
`DatabaseCatalog: Found 1 partially dropped tables. Will load them and retry removal.`

**Which ClickHouse server version to use** 
22.3.6.5
22.4.5.9
22.5.1.348

**Comment by tavplubix** [comment] 2022-06-02 18:13
Looks like duplicate of #37237, fixed in #37243

**Closed by tavplubix** 2022-06-02 18:13 UTC
Labels: unexpected behaviour
