### ISSUE TITLE
ORC Format Parsing – Out-of-Bounds Access in Protobuf Messages

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#33797] opened 2022-01-19 17:36 UTC
**Describe the unexpected behaviour**
When processing ORC data in ClickHouse , what happens if type.fieldnames_size()  is less than the type.subtypes_size(). The type.fieldnames(i) will be invalid access. 

File name :  TypeImpl.cc
```
case proto::Type_Kind_STRUCT: {
TypeImpl* result = new TypeImplSTRUCT);
uint64_t size = static_cast<uint64_t>(type.subtypes_size());
std::vector<Type*> typeList(size);
std::vector<std::string> fieldList(size);
for(int i=0; i < type.subtypes_size(); ++i)
{ result->addStructField(type.fieldnames(i), convertType(footer.types(static_cast<int> (type.subtypes(i))),footer)); }
return std::unique_ptr<Type>(result);
```
* Which ClickHouse server version to use -Affects all Clickhouse-versions.

**Comment by Avogar** [comment] 2022-01-19 17:52
If I understand correctly, you found a bug in orc library, but it's not clear how it affects ClickHouse, dou you have an example when parsing ORC file in ClickHouse causes and error/crash/unexpected result?

**Comment by HeenaBansal2009** [comment] 2022-01-19 18:48
> If I understand correctly, you found a possible bug in orc library, but it's not clear how it affects ClickHouse. Do you have an example when parsing ORC file in ClickHouse causes error/crash/unexpected result?

Hi @Avogar , I don't have particular use case to parse corrupted ORC file in clickhouse server.
However, I reproduced the same issue with ORC library testcase. I created a Protobuf message where I add 3 subtypes but 2 fieldnames. it created crash on Apache ORC. 
Is there any way we can try to feed the same to clickhouse-server . What is your opinion about this ?

**Comment by alexey-milovidov** [comment] 2022-01-19 20:09
`clickhouse-local --input-format ORC --query "SELECT * FROM table" < data.orc`

If we will prove that ORC is insecure, we can add a setting to disable it by default.

**Comment by Avogar** [comment] 2022-01-19 20:33
I will try to create an ORC file with corrupted footer to reproduce this bug.

> If we will prove that ORC is insecure, we can add a setting to disable it by default.

It would be better to just fix this bug, because it's not so difficult.

**Comment by HeenaBansal2009** [comment] 2022-01-19 20:37
> 



> I will try to create an ORC file with corrupted footer to reproduce this bug.
> 
> > If we will prove that ORC is insecure, we can add a setting to disable it by default.
> 
> It would be better to just fix this bug, because it's not so difficult.

Thanks @Avogar.  We can add a fix for this bug, That is more relevant than disabling ORC by default.

**Comment by Avogar** [comment] 2022-01-25 10:26
Yes, I was able to create a file that causes segfault while parsing it in ClickHouse

**Comment by Avogar** [comment] 2022-01-25 10:54
I will create a bugfix in our orc fork untill  https://github.com/apache/orc/pull/1023 will be merged and we will be able to update our fork with upstream.

**Comment by HeenaBansal2009** [comment] 2022-01-27 18:50
apache/orc#1023  is merged.

**Closed** 2022-01-28 09:03 UTC
Labels: development, unexpected behaviour
