### ISSUE TITLE
inactive DROP (ed) PARTITION (parts) are resurrected after CH failure and restart

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#15742] opened 2020-10-07 19:46 UTC
```
create table xxx(A Int64, S String) Engine=MergeTree partition by A order by S;
insert into xxx select 1, toString(number) from numbers(10000000);
alter table xxx drop partition 1;

select count() from xxx
┌─count()─┐
│       0 │
└─────────┘

system kill;

sudo /etc/init.d/clickhouse-server restart

select count() from xxx
┌─count()─┐
│ 6291270 │
└─────────┘

```

related: https://github.com/ClickHouse/ClickHouse/issues/8584

alter table xxx drop partition 1  --- removes from a disk active parts and leaves inactive.

by design.

**Comment by filimonov** [comment] 2021-02-01 17:40
still there on 20.11.

> by design.

Not sure... For ReplicatedMergeTree it seems it removes inactive parts at the moment of partition drop.

**Comment by filimonov** [comment] 2021-02-01 17:51
Replicated
https://github.com/ClickHouse/ClickHouse/blob/4ee96869a2500fa3e75575c767631aa9fbfef732/src/Storages/StorageReplicatedMergeTree.cpp#L1889-L1913

vs non-replicated:
https://github.com/ClickHouse/ClickHouse/blob/8276a1c8d23190426cd34c4d5cf81c6fff56b098/src/Storages/StorageMergeTree.cpp#L1176-L1186

**Comment by alexey-milovidov** [comment] 2022-01-17 18:44
More info: valid for non-replicated MergeTree.

**Comment by alexey-milovidov** [comment] 2022-01-17 18:44
@melvynator If you do normal server restart instead of KILL, does it still happen?

**Comment by alexey-milovidov** [comment] 2022-01-17 18:59
> removes from a disk active parts and leaves inactive

Looks like it can be easy to solve...

**Comment by den-crane** [comment] 2022-01-17 19:06
It's solved for normal server restart , that solution create huge pile of problems with lost parts for the last 2 years.

**Comment by melvynator** [comment] 2022-01-17 19:06
It does not reproduce when there is a normal server restart

**Comment by den-crane** [comment] 2022-01-17 19:07
see https://github.com/ClickHouse/ClickHouse/issues/8584
https://github.com/ClickHouse/ClickHouse/pull/8602
https://github.com/ClickHouse/ClickHouse/pull/26716

**Comment by den-crane** [comment] 2022-01-17 19:10
My dream is too invent a time trevel machine and prevent the merge of https://github.com/ClickHouse/ClickHouse/pull/8602
We spending hours & hours for lost part problem for many our client.

**Comment by den-crane** [comment] 2022-01-17 19:19
also see https://github.com/ClickHouse/ClickHouse/issues/33457

**Comment by tavplubix** [comment] 2022-11-25 13:23
Resolved in https://github.com/ClickHouse/ClickHouse/pull/41145

**Closed by tavplubix** 2022-11-25 13:23 UTC
Labels: usability, support-services
