### ISSUE TITLE
clickhouse pod keep restarting in aarch64 environment

### ISSUE THREAD

**Issue by zqzzq** [ClickHouse/ClickHouse#51177] opened 2023-06-20 07:56 UTC
> You have to provide the following information whenever possible.

**Describe what's wrong**
my k8s cluster is aarch64 architecture：
![45aadf4320b6d5b8b7965d0b4c6be0e2](https://github.com/ClickHouse/ClickHouse/assets/47209065/c644df47-d8a1-4e1c-83ba-5a0909fc37e2)

the clickhouse pod is in CrashLoopBackOff status and restart, the err log：
![5D7A4950FBF201DE5EE33C24A384DF62](https://github.com/ClickHouse/ClickHouse/assets/47209065/3c003c68-88cc-4f49-b5c4-84f1f6bf7b9a)

**Does it reproduce on recent release?**

yes

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
  22.9.5.25
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

The pod is running normally

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by tavplubix** [comment] 2023-06-20 09:40
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/49814
See also https://github.com/ClickHouse/ClickHouse/issues/49878

**Closed by tavplubix** 2023-06-20 09:40 UTC
Labels: potential bug
