### ISSUE TITLE
Malformed MySQL packet

### ISSUE THREAD

**Issue by m0003r** [ClickHouse/ClickHouse#11382] opened 2020-06-02 14:25 UTC
Sometimes ClickHouse forms invalid MySQL packet, and it crashes my Grafana instance (since it currently can't setup alerts via ClickHouse plugin I have to use MySQL interface)

Related issue in Go MySQL client:
https://github.com/go-sql-driver/mysql/issues/1124

**How to reproduce**
- ClickHouse server version 20.4.4.18 (official build)
- MySQL interface
Failed query and result (via MySQL client):
```
SELECT
    intDiv(toInt32(datetime), 1000 / 1000.) * (1000 / 1000.) AS time,
    countIf(http_reply LIKE '5%%') AS `5xx`
FROM traf
WHERE (datetime >= 1591104676) AND (datetime <= 1591104696)
GROUP BY time
ORDER BY time ASC

Query OK, 99 rows affected, 29806 warnings (0.01 sec)
```

It's important to select datetime interval where no rows exist. According to ClickHouse log:
```
2020.06.02 16:42:01.391612 [ 2915 ] {} <Trace> ContextAccess (readonly): Access granted: SELECT(datetime, http_reply) ON default.traf
2020.06.02 16:42:01.392901 [ 2915 ] {} <Debug> default.traf (SelectExecutor): Key condition: (column 0 in [1591105301, +inf)), (column 0 in (-inf, 1591105321]), and
2020.06.02 16:42:01.392936 [ 2915 ] {} <Debug> default.traf (SelectExecutor): MinMax index condition: (column 0 in [1591105301, +inf)), (column 0 in (-inf, 1591105321]), and
2020.06.02 16:42:01.392952 [ 2915 ] {} <Debug> default.traf (SelectExecutor): Selected 0 parts by date, 0 parts by key, 0 marks to read from 0 ranges
2020.06.02 16:42:01.393059 [ 2915 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2020.06.02 16:42:01.393851 [ 2915 ] {} <Trace> AggregatingTransform: Aggregated. 0 to 0 rows (from 0.000 MiB) in 0.000 sec. (0.000 rows/sec., 0.000 MiB/sec.)
2020.06.02 16:42:01.393886 [ 2915 ] {} <Trace> Aggregator: Merging aggregated data
2020.06.02 16:42:01.410842 [ 2915 ] {} <Error> MySQLHandler: DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.
```

MySQL packet:
```
05 00 00 01 fe 00 00 00 00
```

and according to WireShark it is wrong:

```
MySQL Protocol
    Packet Length: 5
    Packet Number: 1
    EOF marker: 254
        [Expert Info (Warning/Protocol): EOF Marker found while connection in wrong state.]
            [EOF Marker found while connection in wrong state.]
            [Severity level: Warning]
            [Group: Protocol]
```

**Comment by m0003r** [comment] 2020-06-02 14:50
Temporarily fixed my case via adding `UNION ALL 0, 0` to query to ensure at least 1 row in result.

**Comment by alexey-milovidov** [comment] 2021-08-14 20:49
Duplicate of #10735, fixed.

**Closed by alexey-milovidov** 2021-08-14 20:49 UTC
Labels: bug, duplicate, st-fixed, st-accepted, comp-mysql
