### ISSUE TITLE
Issue running client from MacOS Aarch64 (Apple Silicon) binary

### ISSUE THREAD

**Issue by senekis** [ClickHouse/ClickHouse#41017] opened 2022-09-05 22:30 UTC
Hi,

I'm running the ClickHouse binary, I downloaded it with the command

```bash
curl -O 'https://builds.clickhouse.com/master/macos-aarch64/clickhouse' && chmod a+x ./clickhouse
```

But when I run `./clickhouse client` I got the following error:

```
$ ./clickhouse client
open maps: No such file or directory
Unable to obtain inode.
```

Any ideas of how to solve the issue?

**Comment by yakov-olkhovskiy** [comment] 2022-09-05 23:55
Issue is caused by attempt to protect decompression from race condition - unfortunately required functionality is not available on MacOS and FreeBSD - we are going to disable it now for these platforms. Fix will be in production after PR #41006 is merged.

**Closed** 2022-09-06 01:45 UTC
Labels: question
