### ISSUE TITLE
"fire and forget" mode for `insert ... select`

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#28896] opened 2021-09-11 15:46 UTC
Special setting to fire long-running `insert... select` or `create table... as select` asynchronously, without waiting query to finish. 

That waiting locks the connection, which anyway may be timeouted and the status of the result is checked in system processes / query_log.

**Comment by alexey-milovidov** [comment] 2022-10-20 03:27
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/33919

**Closed by alexey-milovidov** 2022-10-20 03:27 UTC
Labels: duplicate, feature
