### ISSUE TITLE
PROTOBUF_FIELD_NOT_REPEATED when ingesting from Kafka

### ISSUE THREAD

**Issue by vincentbernat** [ClickHouse/ClickHouse#41971] opened 2022-09-30 13:21 UTC
**Describe what's wrong**

With a protobuf schema using a repeated message, setting up Kafka to use this schema to import into a table leads to the `PROTOBUF_FIELD_NOT_REPEATED` error. This does not happen when ingesting from `clickhouse-client`.

**Does it reproduce on recent release?**

Reproduced on 22.8.5.29.

**How to reproduce**

Using the 22.8 Docker image:
1. put `flow-3.proto` in `/var/lib/clickhouse/format_schemas`
2. create the Kafka table and one consumer, no need to get messages from Kafka

```protobuf
syntax = "proto3";
package decoder;

message FlowMessagev3 {
  uint64 TimeReceived = 2;
  repeated LargeCommunity DstLargeCommunities = 37;
  message LargeCommunity {
    uint32 ASN = 1;
    uint32 LocalData1 = 2;
    uint32 LocalData2 = 3;
  }
}
```

```sql
CREATE TABLE default.flows_3_raw
(
    `TimeReceived` DateTime CODEC(DoubleDelta, LZ4),
    `DstLargeCommunities.ASN` Array(UInt32),
    `DstLargeCommunities.LocalData1` Array(UInt32),
    `DstLargeCommunities.LocalData2` Array(UInt32)
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka:9092', kafka_topic_list = 'flows-v3', kafka_group_name = 'clickhouse', kafka_format = 'Protobuf', kafka_schema = 'flow-3.proto:FlowMessagev3', kafka_num_consumers = 1, kafka_thread_per_consumer = 1

CREATE TABLE default.flows
(
    `TimeReceived` DateTime CODEC(DoubleDelta, LZ4),
    `DstLargeCommunities.ASN` Array(UInt32),
    `DstLargeCommunities.LocalData1` Array(UInt32),
    `DstLargeCommunities.LocalData2` Array(UInt32)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDDhhmmss(toStartOfInterval(TimeReceived, toIntervalSecond(25920)))
ORDER BY TimeReceived
TTL TimeReceived + toIntervalSecond(1296000)
SETTINGS index_granularity = 8192

CREATE MATERIALIZED VIEW default.flows_3_raw_consumer TO default.flows
AS SELECT * FROM default.flows_3_raw
```

Then, check `system.errors`. I get:

```
name:               PROTOBUF_FIELD_NOT_REPEATED
code:               437
value:              440
last_error_time:    2022-09-30 13:20:34
last_error_message: The field 'decoder.FlowMessagev3.LargeCommunity.ASN' must be repeated in the protobuf schema to match the column `ASN`
last_error_trace:   [171727226,366135675,366093641,366067646,366064173,366058066,366045826,366464972,366468882,364681438,337788230,337801743,364844405,364843206,364960586,364912827,364908569,364908061,364902892,337747165,337739135,333703256,333713718,333717100,172520264,172533085,140334772680201,140334771781939]
remote:             0
```

**Expected behavior**

No error in `system.errors`.

**Additional context**

It should be noted that sending messages work, including when they have a `DstLargeCommunity` field. They appear in the `flows` table without any issue.

cc @lesandie

**Comment by hileef** [comment] 2024-07-22 21:13
To add to this description, I can reproduce it with ClickHouse master ( at time of writing )

---

If I understand correctly, this is related to the current implementation using an exception based flow when attempting to ser/de a `Nested(Array(___))` from/into `message { repeated message { ___ } }` .

The code causing this behaviour is here : https://github.com/ClickHouse/ClickHouse/blob/33268f81441512c87d8cbd38976acea1a325630d/src/Formats/ProtobufSerializer.cpp#L3402

➡️  **It first tries to ser/de as a _single_ item, and if the PROTOBUF_FIELD_NOT_REPEATED is thrown, then catches it and attempts as a series of _multiple_ messages _instead_.**

The fact the exception is generated in the first place (even though it is caught afterwards) is why we can find it in the counters of `system.errors`. 

---

I have been playing around with switching this logic around, ( adding an if checking that all mathcing nested columns are of type array, and attempting ser/de as multiple messages right away ) and it appears to behave without generating exceptions ( and ser/de correctly my test data 🙌  )

I will open a PR with these changes to see if it is of interest of the maintainers in the coming days ( as soon as I can get a proper functional test for this ( _I'm facing some weird networking issues in the containers of the functional tests so I can't run them yet_ ))

I believe the reason it does not appear with clickhouse-client is the same reason I need a functional test rather than a simple stateless one : clickhouse-client probably operates the ser/de internally before sending it to the server. So I believe the error is generated, but not server-side, client side instead. And unless I'm missing something, error counters from the client are not visible/accessible.

---

The reason I ended up here is mostly one of performance. ♨️ 

Since an equivalent of ( https://github.com/ClickHouse/ClickHouse/pull/59482 cc. https://github.com/ClickHouse/ClickHouse/issues/65297 ) hasn't been reached yet, this error is going to be thrown for **_EVERY_** protobuf message being received from the Kafka engine ( matching schema described above ).

 I have been observing on a test cluster (with `perf`) that clickhouse was spending **_ABOVE 40% OF CPU TIME_** in `libunwind::*` generating stack traces for this error 🤯 , so this behaviour is quite the performance bottleneck in the current implementation in ClickHouse master.
 
Hopefully if I get a first PR to address this topic merged in, we might already see some perf winnings before clickhouse gets the reuse of the deserializer impl working in tip-top shape 👌

**Closed** 2024-09-27 13:17 UTC
Labels: comp-kafka, potential bug
