### ISSUE TITLE
Troubles with starting clickhouse in docker

### ISSUE THREAD

**Issue by AndriiOpryshko** [ClickHouse/ClickHouse#2987] opened 2018-08-29 11:52 UTC
When I run clickhouse in docker, I get error

**Run docker command:**
docker run -d --name def_click --ulimit nofile=262144:262144 yandex/clickhouse-server

**Docker logs output:**
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Include not found: networks
Include not found: networks
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression

**err.log output:**
2018.08.29 11:14:34.165112 [ 1 ] <Error> Application: Listen [::]: 0: DNS error: EAI: -9  If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>

When I run with custom config with <listen_host>0.0.0.0</listen_host> have the same problem

Was changed ownder of config.xml (chmod 105:106 ..) (saw it here https://github.com/yandex/ClickHouse/issues/2690), but nothing changed.

What did I do wrong?

**Comment by yvlasenko** [comment] 2018-09-21 22:20
@AndriiOpryshko from the command above it doesn't look like you provided CH config file. It should be mounted from the host machine.

**Comment by filimonov** [comment] 2019-03-12 08:33
Nothing is wrong actually. Just misleading error message (ipv6 is disabled, so it it uses only ipv4).

Duplicate of #4406

**Comment by alexey-milovidov** [comment] 2020-06-15 20:25
The server will print this error message and continue to work with IPv4. This is as expected.

**Closed by alexey-milovidov** 2020-06-15 20:25 UTC
Labels: operations, st-wontfix
