### ISSUE TITLE
"There is no query" exception in LIVE VIEW with subqueries

### ISSUE THREAD

**Issue by Vxider** [ClickHouse/ClickHouse#7773] opened 2019-11-14 09:38 UTC
LIVE VIEW dose not support select data from a sub sql query. 

For example, create a LIVE VIEW table like:

```
CREATE LIVE VIEW test AS
SELECT
    id,
    name
FROM
(
    SELECT
        A.id,
        B.name
    FROM A
    , B
    WHERE A.id = B.id
)
```
The query `select * from test` will cause this exception:

```
Code: 393. DB::Exception: Received from localhost:9000. DB::Exception: There is no query.
```

**Comment by den-crane** [comment] 2019-11-14 13:23
cc @vzakaznikov

**Comment by filimonov** [comment] 2019-11-14 14:09
I bet it's caused by subquery,

**Comment by vzakaznikov** [comment] 2019-11-15 01:47
Adding a simple test case to reproduce.

```
user-node :) CREATE TABLE myints (a Int32) Engine=Memory;

CREATE TABLE myints
(
    `a` Int32
)
ENGINE = Memory

Ok.

0 rows in set. Elapsed: 0.009 sec. 

user-node :) CREATE LIVE VIEW lv AS SELECT a FROM (SELECT a FROM myints)

CREATE LIVE VIEW lv AS
SELECT a
FROM 
(
    SELECT a
    FROM myints
)

Ok.

0 rows in set. Elapsed: 0.010 sec. 

user-node :) select * from lv

SELECT *
FROM lv

Received exception from server (version 19.16.3):
Code: 393. DB::Exception: Received from localhost:9000. DB::Exception: There is no query. 
```

**Comment by vzakaznikov** [comment] 2019-12-06 00:42
This issue should fixed by https://github.com/ClickHouse/ClickHouse/pull/7792.

**Comment by vzakaznikov** [comment] 2020-01-30 19:49
This issue should be closed as it is fixed in the latest release.

**Closed** 2020-01-30 21:33 UTC
Labels: feature
