### ISSUE TITLE
OR in where part of a query does not allow to rewrite CROSS JOIN to INNER JOIN

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#70140] opened 2024-09-30 18:45 UTC
```
SELECT sum(a + b)
FROM
(
    SELECT number * 100 AS a
    FROM numbers(100)
) AS l,
(
    SELECT number * 10 AS b
    FROM numbers(100)
) AS r
WHERE ((a = b) AND (a > 10)) OR ((a = b) AND (b < 10))
SETTINGS cross_to_inner_join_rewrite = 2

Query id: 157fbf42-9ad8-4850-9554-0f7e1fa07f3b


Elapsed: 0.046 sec.

Received exception from server (version 24.8.1):
Code: 80. DB::Exception: Received from k6h3pxyvrj.eu-west-1.aws.clickhouse-staging.com:9440. DB::Exception: Failed to rewrite ', ...' to INNER JOIN: no equi-join conditions found in WHERE clause. You may set setting `cross_to_inner_join_rewrite` to `1` to allow slow CROSS JOIN for this case. (INCORRECT_QUERY)
```

If we just take common part in brackets it works:

```
SELECT sum(a + b)
FROM
(
    SELECT number * 100 AS a
    FROM numbers(100)
) AS l,
(
    SELECT number * 10 AS b
    FROM numbers(100)
) AS r
WHERE ((a > 10) OR (b < 10)) AND (a = b)
SETTINGS cross_to_inner_join_rewrite = 2

Query id: 7f8ff6fc-8f31-4adc-bcf6-322d5bfb3d6c

   ┌─sum(plus(a, b))─┐
1. │            9000 │
   └─────────────────┘
```

**Comment by rschu1ze** [comment] 2024-10-22 13:36
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/70802

**Closed by rschu1ze** 2024-10-22 13:36 UTC
Labels: unfinished code
