### ISSUE TITLE
(only with S3 VFS) ClickHouse not starting up: Failed to read metadata file

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#41566] opened 2022-09-20 11:30 UTC
ClickHouse server failed to start with the following errors in server logs:

```
2022.09.09 10:31:52.010319 [ 3619128 ] {} <Error> auto DB::MergeTreeData::loadDataPartsFromDisk(DB::MergeTreeData::DataPartsVector &, DB::MergeTreeData::DataPartsVector &, Thread
Pool &, size_t, std::queue<std::vector<std::pair<String, DiskPtr>>> &, bool, const DB::MergeTreeSettingsPtr &)::(anonymous class)::operator()(const DB::String &, const DB::DiskPt
r &) const: Code: 32. DB::Exception: Attempt to read after eof. (ATTEMPT_TO_READ_AFTER_EOF), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3c367a in /usr/bin/clickhouse
1. DB::throwReadAfterEOF() @ 0xa3ca5e0 in /usr/bin/clickhouse
2. void DB::readIntTextImpl<unsigned int, void, (DB::ReadIntTextCheckOverflow)0>(unsigned int&, DB::ReadBuffer&) @ 0xa576a37 in /usr/bin/clickhouse
3. DB::DiskObjectStorageMetadata::deserialize(DB::ReadBuffer&) @ 0x142eb7a3 in /usr/bin/clickhouse
4. DB::MetadataStorageFromDisk::readMetadataUnlocked(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_lock<std::__1:
:shared_mutex>&) const @ 0x142e6bb8 in /usr/bin/clickhouse
5. DB::MetadataStorageFromDisk::getFileSize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x142e6786 in /usr/bin/clickhous
e
6. DB::DiskRestartProxy::getFileSize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x14337171 in /usr/bin/clickhouse
7. DB::MergeTreeDataPartChecksum::checkSize(std::__1::shared_ptr<DB::IDisk> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
const @ 0x1563fc23 in /usr/bin/clickhouse
8. DB::MergeTreeDataPartChecksums::checkSizes(std::__1::shared_ptr<DB::IDisk> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&
) const @ 0x1564040d in /usr/bin/clickhouse
9. DB::DataPartStorageOnDisk::checkConsistency(DB::MergeTreeDataPartChecksums const&) const @ 0x154f343e in /usr/bin/clickhouse
10. DB::IMergeTreeDataPart::checkConsistencyBase() const @ 0x1555877e in /usr/bin/clickhouse
11. DB::MergeTreeDataPartWide::checkConsistency(bool) const @ 0x15651ab8 in /usr/bin/clickhouse
12. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x15549916 in /usr/bin/clickhouse
13. ? @ 0x1562ccd4 in /usr/bin/clickhouse
14. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa487726 in /usr/bin/clickhouse
15. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<Th
readFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::_
_policy_storage const*) @ 0xa489077 in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa485048 in /usr/bin/clickhouse
17. ? @ 0xa48825d in /usr/bin/clickhouse
18. start_thread @ 0x76db in /lib/x86_64-linux-gnu/[libpthread-2.27.so](https://libpthread-2.27.so/)
19. clone @ 0x12161f in /lib/x86_64-linux-gnu/[libc-2.27.so](https://libc-2.27.so/)
(version 22.8.4.7 (official build))
```

```
2022.09.09 10:32:00.747419 [ 3618741 ] {} <Error> Application: Caught exception while loading metadata: Code: 32. DB::Exception: Attempt to read after eof: Cannot attach table `m
db`.`mysql_audit_part` from metadata file /var/lib/clickhouse/metadata/mdb/mysql_audit_part.sql from query ATTACH TABLE mdb.mysql_audit_part (`cluster` LowCardinality(String), `c
ommand_class` String, `connection_id` UInt32, `connection_type` String, `db` String, `hostname` LowCardinality(String), `origin` LowCardinality(String), `ip` String, `timestamp`
DateTime CODEC(DoubleDelta, LZ4), `ms` UInt16 DEFAULT 0, `mysql_version` String, `name` String, `os_login` LowCardinality(String), `os_user` LowCardinality(String), `os_version`
String, `priv_user` String, `proxy_user` String, `record` String, `server_id` String, `sqltext` String, `startup_optionsi` String, `status` UInt32, `status_code` UInt32, `user` S
tring, `version` LowCardinality(String), `insert_time` DateTime DEFAULT now() CODEC(DoubleDelta, LZ4), `log_format` LowCardinality(String), `datetime` DateTime CODEC(DoubleDelta,
LZ4), `raw` String CODEC(ZSTD(1)), `_timestamp` DateTime CODEC(DoubleDelta, LZ4), `_partition` LowCardinality(String), `_offset` UInt64, `_idx` UInt32, `_rest` String CODEC(ZSTD
(1))) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/mdb_mysql_audit_part', '{replica}') PARTITION BY toDate(timestamp, 'UTC') ORDER BY (cluster, timestamp, ms) TTL toD
ate(timestamp) + toIntervalMonth(1), toDate(timestamp) + toIntervalWeek(1) TO DISK 'object_storage' SETTINGS ttl_only_drop_parts = 1, index_granularity = 8192. (ATTEMPT_TO_READ_A
FTER_EOF), Stack trace (when copying this message, always include the lines below):
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3c367a in /usr/bin/clickhouse
1. DB::throwReadAfterEOF() @ 0xa3ca5e0 in /usr/bin/clickhouse
2. void DB::readIntTextImpl<unsigned int, void, (DB::ReadIntTextCheckOverflow)0>(unsigned int&, DB::ReadBuffer&) @ 0xa576a37 in /usr/bin/clickhouse
3. DB::DiskObjectStorageMetadata::deserialize(DB::ReadBuffer&) @ 0x142eb7a3 in /usr/bin/clickhouse
4. DB::MetadataStorageFromDisk::readMetadataUnlocked(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_lock<std::__1:
:shared_mutex>&) const @ 0x142e6bb8 in /usr/bin/clickhouse
5. DB::MetadataStorageFromDisk::getFileSize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x142e6786 in /usr/bin/clickhous
e
6. DB::DiskRestartProxy::getFileSize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x14337171 in /usr/bin/clickhouse
7. ? @ 0x154f1bcd in /usr/bin/clickhouse
8. DB::DataPartStorageOnDisk::calculateTotalSizeOnDisk() const @ 0x154f1738 in /usr/bin/clickhouse
9. ? @ 0x1562e4dd in /usr/bin/clickhouse
10. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa487726 in /usr/bin/clickhouse
11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<Th
readFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::_
_policy_storage const*) @ 0xa489077 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa485048 in /usr/bin/clickhouse
13. ? @ 0xa48825d in /usr/bin/clickhouse
14. start_thread @ 0x76db in /lib/x86_64-linux-gnu/[libpthread-2.27.so](https://libpthread-2.27.so/)
15. clone @ 0x12161f in /lib/x86_64-linux-gnu/[libc-2.27.so](https://libc-2.27.so/)
(version 22.8.4.7 (official build))
```

Removing the broken file resolved the situation but ClickHouse should do that by itself. The expected behavior: broken files are moved to detached/ and clickhouse-server is started up. 

The user is using S3 backed merge tree. 

Similar to: https://github.com/ClickHouse/ClickHouse/issues/36905 but this time zero-replication is not in used.

**Comment by tavplubix** [comment] 2022-09-20 18:53
Looks like duplicate of https://github.com/ClickHouse/ClickHouse/issues/41409

**Closed** 2023-04-09 04:51 UTC
Labels: duplicate, potential bug
