### ISSUE TITLE
"age" function does not work correctly for DateTime64

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#48372] opened 2023-04-04 07:21 UTC
version 23.2.4.12

query:
`select age('second', toDateTime64('2023-03-01 19:18:36.999', 3), toDateTime64('2023-03-01 19:18:41.001', 3));`

result:
`5`

expected result:
`4`

**Comment by rschu1ze** [comment] 2023-04-06 11:06
@rvasin If you have time, would you like to take a first look?

**Comment by rvasin** [comment] 2023-04-06 11:20
@rschu1ze OK. I will take a first look.

**Comment by rvasin** [comment] 2023-04-06 13:53
Robert, after a first look - it seems like I confirm that issue and I even found it in the code. I will probably correct it tomorrow.

**Comment by rvasin** [comment] 2023-04-06 14:11
While now I think the returned result 5 is correct. And 4 is incorrect result.
So there is no issue with `age()`.

In the [documentation](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#age) we state:

> The difference is calculated using a precision of 1 second.

It means that we truncate 2023-03-01 19:18:36.999 to 2023-03-01 19:18:36.000
and 2023-03-01 19:18:41.001 to 2023-03-01 19:18:41.000 and we do all the calculations in seconds. We don't consider milliseconds etc.
In this case 41-36 = 5.

BTW see the request #46160 to support higher than seconds precision for `date_diff` and `age`.

**Comment by rschu1ze** [comment] 2023-04-06 14:34
That makes sense, thanks for checking, let me mark this as Duplicate of #46160

**Closed by rschu1ze** 2023-04-06 14:34 UTC
Labels: unexpected behaviour
