### ISSUE TITLE
Server should send settings to the client (Setting output_format_json_quote_64bit_integers to 0 in users.xml is not respected).

### ISSUE THREAD

**Issue by pdrtrifork** [ClickHouse/ClickHouse#3489] opened 2018-10-29 16:01 UTC
I have this in my users.xml:

        <profiles>
                <default>
                    ...
                    <output_format_json_quote_64bit_integers>0</output_format_json_quote_64bit_integers>
                </default>
        ...
        </profiles>

But I still get quoted 64-bit integers:

    :) SELECT toInt64(0) FORMAT JSON

    {
	    "meta":
	    [
		    {
		    	"name": "toInt64(0)",
		    	"type": "Int64"
		    }
	    ],

    	"data":
    	[
    		{
    		    "toInt64(0)": "0"
    		}
    	],

    	"rows": 1,

    	"statistics":
    	{
    		"elapsed": 0.0010454,
    		"rows_read": 1,
    		"bytes_read": 1
    	}
    }

The setting is recognised:

    :) SELECT value FROM system.settings WHERE name = 'output_format_json_quote_64bit_integers'

    ┌─value─┐
    │ 0     │
    └───────┘

If I manually set the value using

    :) SET output_format_json_quote_64bit_integers = 0

I get the correct output:

    :) SELECT toInt64(0) FORMAT JSON

    {
    	"meta":
    	[
    		{
    			"name": "toInt64(0)",
    			"type": "Int64"
    		}
    	],

    	"data":
    	[
    		{
    			"toInt64(0)": 0
    		}
    	],

    	"rows": 1,
    
    	"statistics":
    	{
    		"elapsed": 0.001716436,
    		"rows_read": 1,
    		"bytes_read": 1
    	}
    }

This is using:
- ClickHouse client version 18.14.11.
- Connected to ClickHouse server version 18.14.11 revision 54409.

**Comment by alexey-milovidov** [comment] 2018-11-01 13:53
Confirmed.

Client does formatting of data, but it does not receive default settings from the server.
You can also add this setting to the client configuration file (in root level).

**Comment by mikekytyzov** [comment] 2020-12-01 20:01
Is this issue still relevant ? 
I have absolutely the same issue on 20.3.19.4 version

Adding this setting to `config.xml` or `users.xml` do not affect on result.

**Comment by alexey-milovidov** [comment] 2020-12-02 09:36
Yes, it's relevant.

**Comment by alexey-milovidov** [comment] 2024-02-20 10:08
Duplicate of #56976.

**Closed by alexey-milovidov** 2024-02-20 10:08 UTC
Labels: usability, st-hold
