### ISSUE TITLE
Storing subqueries to variables or aliasing

### ISSUE THREAD

**Issue by dmitry-brazhenko** [ClickHouse/ClickHouse#11929] opened 2020-06-24 18:42 UTC
Sometimes I have to create multistage SQL-queries. For example
`select *
from 
(select * 
 from some_table
 where column = 1) a`

There can few subqueries. It can look awful. 
It would be nice if I could type smth like this:

```
a = (select * 
 from some_table
 where column = 1);

select * 
from a
```

Maybe it could be just an alias, but this alias is much easier to read than the initial one.

**Comment by akuzm** [comment] 2020-06-24 19:01
This is a `WITH` clause, currently it is supported for scalar subqueries:
```
with (select 1) as a
select a;
```
There is a feature request to support it for non-scalar subqueries as well https://github.com/ClickHouse/ClickHouse/issues/4967
Is this what you need?

**Comment by dmitry-brazhenko** [comment] 2020-06-24 19:05
Seems that it is exactly what I need :)

**Comment by dmitry-brazhenko** [comment] 2020-06-24 19:12
Seems like it is what I need. 

But I would like this feature to work recursively. For example,
```
with (select * from table_name) as a;

with (select * from a where column = 1) as b;

select * from b
```

**Comment by filimonov** [comment] 2020-06-24 22:54
Duplicate of #4967

**Closed by filimonov** 2020-06-24 22:54 UTC
Labels: duplicate, feature
