### ISSUE TITLE
column ALIAS + column MATERIALIZED, cannot insert 

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#9700] opened 2020-03-17 06:33 UTC
**How to reproduce**
```sql
CREATE TABLE test1
(
    col             UInt64,
    aliasCol        ALIAS col * col,
    materializedCol UInt64 MATERIALIZED aliasCol * aliasCol
) ENGINE = MergeTree PARTITION BY tuple() ORDER BY tuple();

INSERT INTO test1(col) VALUES (1), (2), (3), (4), (5);
```
* Which ClickHouse server version to use
20.3.1
**Expected behavior**
Successfull insert

**Error message and/or stacktrace**
```
Code: 47, e.displayText() = DB::Exception: Missing columns: 'aliasCol' while processing query: 'CAST(aliasCol * aliasCol, 'UInt64') AS materializedCol', required columns: 'aliasCol', source columns: 'col' (version 20.3.1.2564 (official build))
```

**Comment by Slach** [comment] 2020-03-17 08:40
also related to https://github.com/ClickHouse/ClickHouse/issues/3140

**Comment by filimonov** [comment] 2020-03-17 08:43
That should be fixed in  #9489 (i will check your sample)

**Comment by filimonov** [comment] 2020-03-17 08:46
Works on master (and also should on 20.3)

select *, materializedCol from test1;
```sql
SELECT 
    *, 
    materializedCol
FROM test1

┌─col─┬─materializedCol─┐
│   1 │               1 │
│   2 │              16 │
│   3 │              81 │
│   4 │             256 │
│   5 │             625 │
└─────┴─────────────────┘
```

**Closed by filimonov** 2020-03-17 08:46 UTC
Labels: bug

**Comment by filimonov** [comment] 2020-03-17 08:49
It's a duplicate of #2283
