### ISSUE TITLE
UNKNOWN_IDENTIFIER on Select from subselect with more than 2 joins and identical column name

### ISSUE THREAD

**Issue by kostyukeviche** [ClickHouse/ClickHouse#62785] opened 2024-04-19 09:09 UTC
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

Select from subselect with more than 2 joins with identical column name (i.e. see example below) 

> A clear and concise description of what works not as it is supposed to.

DDL used in test: 
```
create table default.TEST_JOIN1
(
    REF1 Nullable(String),
    SAME Nullable(String)
)
    engine = Memory;
```

This Select gives UNKNOWN_IDENTIFIER error
`SELECT SAME FROM (SELECT t1.* FROM TEST_JOIN1 t1 JOIN TEST_JOIN1 t2 ON t1.REF1 = t2.REF1 JOIN TEST_JOIN1 t3 ON t1.REF1 = t3.REF1);
`
This Select executed successfully 
`SELECT SAME FROM (SELECT t1.* FROM TEST_JOIN1 t1 JOIN TEST_JOIN1 t2 ON t1.REF1 = t2.REF1);`

Root cause goes to what aliases used in t1.* in subselects, i.e.: 
- for 2 joins CH gives: 
![image](https://github.com/ClickHouse/ClickHouse/assets/144101160/4886ed4c-b97e-485b-a311-456a429e749e)
- for more than 2 joins CH gives: 
![image](https://github.com/ClickHouse/ClickHouse/assets/144101160/da6f0bd5-b43c-4b44-9886-7a31fbf9a527)

Workaround is to assign alias manually to subselect query or use alias from subselect table directly (i.e. see example from fiddle) 

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).
https://fiddle.clickhouse.com/f1e6f21e-09b8-4d32-b8c7-4df8a2ee22e0
Workarounds: 
https://fiddle.clickhouse.com/782ee38a-5eff-4203-9eff-2d489cc10a7f

**Does it reproduce on the most recent release?**
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment] 2024-04-19 12:48
duplicate of https://github.com/ClickHouse/ClickHouse/issues/34697

**Closed** 2024-04-19 12:51 UTC
Labels: duplicate, potential bug
