### ISSUE TITLE
CREATE TABLE with PostgreSQL table engine or postgresql table function results in zombie idle connections growth

### ISSUE THREAD

**Issue by ThomasSertorio** [ClickHouse/ClickHouse#65797] opened 2024-06-27 21:28 UTC
**Situation**
The unexpected behaviour happens when a query is performed against a table defined either via a `PostgreSQL` Table engine or via a `postgresql` table function. Basically, when the query is executed:
- a connection to the distant Postgresql database is opened
- once the query is performed, the connection evolves to an idle `COMMIT` state
- ... and stays in this idle state forever without being re-used or closed
This result in connections to the distant PostgreSQL growing to the max number of connection to the database and crashing.
This seems related to https://github.com/ClickHouse/ClickHouse/issues/26088

**How to reproduce**
I'm using ClickHouse Cloud version 24.5.1.22724 (official build) with the default settings.
To reproduce:
- Create a table with PostgreSQL Table engine or postgresql table function:
```SQL
-- CREATE TABLE with PostgreSQL Table engine to a distant DB
CREATE TABLE cars
ENGINE = PostgreSQL('host:port', 'db', 'cars', 'user', 'password');
-- Or CREATE TABLE with postgresql table function to a distant DB
-- CREATE TABLE cars AS postgresql('host:port', 'db', 'cars', 'user', 'password');
-- Query
SELECT cars.* FROM cars LIMIT 1;
```
- Check the number of connections on the distant Postgresql
```SQL
SELECT datname, usename, count(*) 
FROM pg_stat_activity 
GROUP BY datname, usename;
```
The connection from ClickHouse will never be closed/freed.

**Expected behavior**
I'm expecting the connection to be closed after a certain delay. But no timeout settings seems to have any effect.

**Error message and/or stacktrace**
<img width="1005" alt="Screenshot 2024-06-27 at 23 25 38" src="https://github.com/ClickHouse/ClickHouse/assets/12392239/e23b4d6d-f4fd-46a1-abf4-49af4b6d45b3">
☝️We can see idle connections piling up for several minutes while no query being performed anymore.

**Comment by nikitamikhaylov** [comment] 2024-07-30 13:55
@max-vostrikov Let's write an integration test to reproduce this issue?

**Comment by max-vostrikov** [comment] 2024-08-06 17:03
I did a bit investigation on this issue, and it seems that it works as expected.
Clickhouse indeed do not close the connections - because there is a pool of connection for every table. The saze of the pool determined by `postgresql_connection_pool_size`, and connections stay open even if there is no queries.
The `postgresql_connection_pool_size` is determined per table, so if you have several tables each of them will create at least one idle connection.

I've tried to get a scenario where I could find more connections than expected with reducing `postgresql_connection_pool_size` (the default value is 16). But I was not able to do that- it seems all that "zombie" connections are not zombie but just idle and they do get reused on next select.

It would make sense to have an option to close those connections with a timeout, but it look more like a new feature than unexpected behavior. Also there obviously will be some performance considerations for this feature.

**Comment by max-vostrikov** [comment] 2024-08-07 09:47
After a bit of discussions, we've decided to close this one.
I did additionally checked that it works the same with table function, and the connections get closed when the tables get dropped.

The behaviour is expected and we do reuse those connections, so they are not "zombie".
If you think that there should be some timeouts there, please create a new feature request with some use case when it would be useful - so we can build a new feature with that use case in mind.

**Closed by max-vostrikov** 2024-08-07 09:47 UTC
Labels: feature
