### ISSUE TITLE
Unexpected behavior of config substitutions from ZooKeeper

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#9547] opened 2020-03-06 22:19 UTC
I would like to use ZK as an optional storage for CH settings.
The idea is that I would put files with the 'default' settings on the server into /etc/clickhouse-server, and if I want to change something (probably temporarily) I would make the change in ZK.
I couldn't make this work though (I tested on 20.1.4.14).

1. without replace="true" CH does not even read ZK
```
/etc/clickhouse-server/users.d$  cat test.xml
<yandex>
<profiles>
    <default from_zk="/max_memory">
        <max_memory_usage>10000000001</max_memory_usage>
    </default>
</profiles>
</yandex>

ZK: create max_memory "<max_memory_usage>10000000002</max_memory_usage>"

preprocessed:
<yandex>
    <!-- Profiles of settings. -->
    <profiles>
        <!-- Default settings. -->
        <default>
            <!-- Maximum memory usage for processing single query, in bytes. -->
            <max_memory_usage>10000000001</max_memory_usage>
...
The znode is not even mentioned in the preprocessed file's header ('This file was generated automatically...').
```
2. With replace="true" CH deletes the whole section even if there is no znode in ZK.
It's easy to delete the whole profile or users section and this can lead to CH being unusable.
If the znode exists, the replace works a little strange:
```
/etc/clickhouse-server/users.d$  cat test.xml
<yandex>
<profiles>
    <default>
	    <max_memory_usage replace="true" from_zk="/max_memory">10000000001</max_memory_usage>
    </default>
</profiles>
</yandex>

ZK: set max_memory "10000000002"

preprocessed:
        <default>
            <!-- Maximum memory usage for processing single query, in bytes. -->
            <max_memory_usage>1000000000110000000002</max_memory_usage>
```

**Comment by pufit** [comment] 2023-02-09 04:31
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/46131.
https://github.com/ClickHouse/ClickHouse/pull/46144 should fix this.

**Closed by pufit** 2023-02-09 04:31 UTC
Labels: bug, st-accepted
