### ISSUE TITLE
Clickhouse crashes calling UDF

### ISSUE THREAD

**Issue by yandooo** [ClickHouse/ClickHouse#43825] opened 2022-11-30 10:31 UTC
**Describe the unexpected behaviour**

CH instance crashes processing response from UDF.

It does not happen consistently. Most of the time UDF <-> CH works perfectly fine. 
It might be related to large inputs to the executable (~300MB of serialized json data) or inconsistency in returned values (executable work with u64 data vs definition expects u32), but that's just an assumption.

At least expectation for CH to not crash unexpectedly as it leads to data loss/inconsistencies.

ClickHouse v22.6.9.11
Runs on Graviton powered EC2

UDF definition:

```xml
<functions>
    <function>
        <type>executable</type>
        <name>estimator</name>
	    <return_type>Map(String,Float64)</return_type>
        <return_name>result</return_name>
        <argument>
            <type>Array(Tuple( bins Tuple(k Array(Int32), n Array(UInt32)),count UInt32,min Float64,max Float64,sum Float64 ))</type>
            <name>s</name>
        </argument>
        <argument>
            <type>Array(Float64)</type>
            <name>q</name>
        </argument>
        <format>JSONEachRow</format>
        <execute_direct>1</execute_direct>
        <command>estimator</command>
    </function>
</functions>
```

CH crash log message:

```
'2. raise @ 0x33d78 in /usr/lib/aarch64-linux-gnu/libc-2.31.so'
'3. abort @ 0x20aac in /usr/lib/aarch64-linux-gnu/libc-2.31.so'
'4. ThreadFromGlobalPool::~ThreadFromGlobalPool() @ 0xa0f872c in /usr/bin/clickhouse'
'5. ? @ 0x10dc9658 in /usr/bin/clickhouse'
'6. DB::ShellCommandSourceCoordinator::createPipe(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<DB::Pipe, std::__1::allocator<DB::Pipe> >&&, DB::Block, std::__1::shared_ptr<DB::Context const>, DB::ShellCommandSourceConfiguration const&) @ 0x1405cfec in /usr/bin/clickhouse'
'7. DB::UserDefinedFunction::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x132902b0 in /usr/bin/clickhouse'
'8.DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x122e4228 in /usr/bin/clickhouse'
'9. DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x122e4c18 in /usr/bin/clickhouse'
'10. DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x122e6264 in /usr/bin/clickhouse'
'11. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x12bce464 in /usr/bin/clickhouse'
'12. DB::ExpressionTransform::transform(DB::Chunk&) @ 0x13fda1e8 in /usr/bin/clickhouse'
'13. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x106d3020 in /usr/bin/clickhouse'
'14. DB::ISimpleTransform::work() @ 0x13dfeff0 in /usr/bin/clickhouse'
'15. DB::ExecutionThreadContext::executeTask() @ 0x13e1c34c in /usr/bin/clickhouse'
'16. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x13e11a7c in /usr/bin/clickhouse'
'17. ? @ 0x13e138c4 in /usr/bin/clickhouse'
'18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa0f5bb0 in /usr/bin/clickhouse'
'19. ? @ 0xa0f8d04 in /usr/bin/clickhouse'
'20. start_thread @ 0x7624 in /usr/lib/aarch64-linux-gnu/libpthread-2.31.so'
'21. ? @ 0xd149c in /usr/lib/aarch64-linux-gnu/libc-2.31.so'] 
│ ClickHouse 22.6.9.11
```

**Comment by yandooo** [comment] 2023-01-09 09:39
Would it be possible to share steps to trace/debug this issue further?

**Comment by kitaisreal** [comment] 2023-01-09 12:58
@yandooo could you please emulate crash using some simple script and some test data ?

**Comment by kitaisreal** [comment] 2023-01-09 13:00
@yandooo could you please try to reproduce issue on current master ? If it reproduces, then can you try to send some simple reproducible scenario with executable script and some sample data ?

**Comment by alexey-milovidov** [comment] 2023-06-20 13:35
I expect this issue to be a duplicate of another, and it has been resolved in the latest versions.

**Closed by alexey-milovidov** 2023-06-20 13:35 UTC
Labels: st-need-info, crash, unexpected behaviour
