### ISSUE TITLE
Coordination::Exception: Can't get data for node: node doesn't exist (No node). (KEEPER_EXCEPTION)

### ISSUE THREAD

**Issue by myrrc** [ClickHouse/ClickHouse#53748] opened 2023-08-23 13:02 UTC
**Describe the unexpected behaviour**

Inserting into a replicated table yields a Keeper error

**How to reproduce**
* Clickhouse version: `23.3.8.21`
* Cluster setup: 1 shard, 3 hosts, 3 ZooKeeper hosts
* Zookeeper version: `3.8.1-1`
* Non-default setting: `allow_remote_fs_zero_copy_replication`

```sql

 CREATE TABLE test ON CLUSTER 'cluster' (
    `time` DateTime64(9) DEFAULT now(),
    `num` UInt64
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', '{replica}')
ORDER BY (time, num) PARTITION BY num % 100
TTL toDateTime(time) + INTERVAL 15 MINUTE TO DISK 'object_storage'
SETTINGS ttl_only_drop_parts = 1;

insert into test (num) select number % 100 from numbers_mt(500000000)
```

yields an error

```
0 rows in set. Elapsed: 38.615 sec. Processed 29.36 million rows, 234.85 MB (760.24 thousand rows/s., 6.08 MB/s.)

Received exception from server (version 23.3.8):
Code: 999. DB::Exception: Received from XXX. Coordination::Exception. Coordination::Exception: Can't get data for node /clickhouse/tables/test/blocks/55_6809467586927519111_8716827004816686597: node doesn't exist (No node). (KEEPER_EXCEPTION)
```

**Expected behavior**

The insert query finished without an error.

**Error message and/or stacktrace**

```
Code: 999. Coordination::Exception: Can't get data for node /clickhouse/tables/test/blocks/55_6809467586927519111_8716827004816686597: node doesn't exist (No node). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe22f215 in /usr/lib/debug/usr/bin/clickhouse.debug
1. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: Coordination::Exception::Exception(String const&, Coordination::Error, int) @ 0x1504c830 in /usr/lib/debug/usr/bin/clickhouse.debug
2. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: Coordination::Exception::Exception(String const&, Coordination::Error) @ 0x1504cb58 in /usr/lib/debug/usr/bin/clickhouse.debug
3. ./build_docker/./src/Common/ZooKeeper/ZooKeeper.cpp:0: zkutil::ZooKeeper::get(String const&, Coordination::Stat*, std::shared_ptr<Poco::Event> const&) @ 0x15056713 in /usr/lib/debug/usr/bin/clickhouse.debug
4. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:781: DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::shared_ptr<DB::IMergeTreeDataPart>&, String const&, unsigned long, bool)::'lambda'()::operator()() const @ 0x148eff18 in /usr/lib/debug/usr/bin/clickhouse.debug
5. ./build_docker/./src/Storages/MergeTree/ZooKeeperRetries.h:0: DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::shared_ptr<DB::IMergeTreeDataPart>&, String const&, unsigned long, bool) @ 0x148e2bc8 in /usr/lib/debug/usr/bin/clickhouse.debug
6. ./build_docker/./contrib/llvm-project/libcxx/include/vector:434: DB::ReplicatedMergeTreeSinkImpl<false>::finishDelayedChunk(std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&) @ 0x148df71e in /usr/lib/debug/usr/bin/clickhouse.debug
7. ./build_docker/./contrib/llvm-project/libcxx/include/vector:951: DB::ReplicatedMergeTreeSinkImpl<false>::consume(DB::Chunk) @ 0x148dd83f in /usr/lib/debug/usr/bin/clickhouse.debug
8. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::SinkToStorage::onConsume(DB::Chunk) @ 0x14db2ec2 in /usr/lib/debug/usr/bin/clickhouse.debug
9. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x14ce302b in /usr/lib/debug/usr/bin/clickhouse.debug
10. ./build_docker/./src/Processors/Transforms/ExceptionKeepingTransform.cpp:103: DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x14ce2d79 in /usr/lib/debug/usr/bin/clickhouse.debug
11. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:818: DB::ExceptionKeepingTransform::work() @ 0x14ce265f in /usr/lib/debug/usr/bin/clickhouse.debug
12. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x14afd94a in /usr/lib/debug/usr/bin/clickhouse.debug
13. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:246: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14af29bb in /usr/lib/debug/usr/bin/clickhouse.debug
14. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::PipelineExecutor::executeImpl(unsigned long) @ 0x14af1b11 in /usr/lib/debug/usr/bin/clickhouse.debug
15. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:274: DB::PipelineExecutor::execute(unsigned long) @ 0x14af17b1 in /usr/lib/debug/usr/bin/clickhouse.debug
16. ./build_docker/./src/Processors/Executors/CompletedPipelineExecutor.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x14af054d in /usr/lib/debug/usr/bin/clickhouse.debug
17. ./build_docker/./base/base/../base/wide_integer_impl.h:789: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe2fe553 in /usr/lib/debug/usr/bin/clickhouse.debug
18. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0xe3041c1 in /usr/lib/debug/usr/bin/clickhouse.debug
19. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
20. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so

```

**Comment by tavplubix** [comment] 2023-08-23 13:08
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/47604

**Closed by tavplubix** 2023-08-23 13:08 UTC
Labels: unexpected behaviour
