### ISSUE TITLE
Deadlock on simultaneous insert, select and partition drop

### ISSUE THREAD

**Issue by keliss** [ClickHouse/ClickHouse#15173] opened 2020-09-22 21:02 UTC
Hi. I've encountered a strange issue and couldn't find the cause yet. Maybe you'll guide me in the right direction. Here's some context: we have lots of simultaneous batch inserts coming to our CH cluster, and we have a script that cleans up the old data hourly. The table is partitioned by hour and is distributed, though we are running the script against each shard separately. The script basically runs these two queries using the CH CLI:
`select distinct partition from system.parts where table = 'table_shard' and rows > 0 and toDateTime(partition) < now() - interval 24 hour order by partition` to fetch the required old partitions and
`alter table db.table_shard drop partition '$partition'` in a loop to drop the partitions.
At some point, the cluster stuck. Script drop queries started to get rejected with this message:
`Code: 473. DB::Exception: Received from localhost:9000. DB::Exception: WRITE locking attempt on "db.table_shard" has timed out! (120000ms) Possible deadlock avoided. Client should retry..`
Selects didn't work as well. The last exceptions in the error log (the first one may be unrelated, however):

```
2020.09.22 17:00:06.153973 [ 331822 ] {} <Error> ServerErrorHandler: Code: 101, e.displayText() = DB::NetException: Unexpected packet from client, Stack trace (when copying this message, always include the lines below):
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x104191d0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8fff8ad in /usr/bin/clickhouse
2. ? @ 0x91083e1 in /usr/bin/clickhouse
3. DB::TCPHandler::runImpl() @ 0x9105bd7 in /usr/bin/clickhouse
4. DB::TCPHandler::run() @ 0x9107650 in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x10304f4b in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x103053db in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0x104b2fa6 in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x104ae260 in /usr/bin/clickhouse
9. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
10. __clone @ 0xfebad in /usr/lib64/libc-2.17.so
 (version 20.4.4.18 (official build))


2020.09.22 17:02:04.866019 [ 381206 ] {871d7ba7-9962-41f3-9acc-f72c63d58e04} <Error> executeQuery: Code: 473, e.displayText() = DB::Exception: WRITE locking attempt on "db.table_shard" has timed out! (120000ms) Possible deadlock avoided. Client should retry. (version 20.4.4.18 (official build)) (from [::1]:47402) (in query: ALTER TABLE db.table_shard DROP PARTITION '2020-09-21 16:00:00' ), Stack trace (when copying this message, always include the lines below):
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x104191d0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8fff8ad in /usr/bin/clickhouse
2. ? @ 0xd651b8a in /usr/bin/clickhouse
3. DB::IStorage::lockExclusively(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::SettingTimespan<(DB::SettingTimespanIO)1> const&) @ 0xd64eea4 in /usr/bin/clickhouse
4. DB::StorageMergeTree::dropPartition(std::__1::shared_ptr<DB::IAST> const&, bool, DB::Context const&) @ 0xd6edbea in /usr/bin/clickhouse
5. DB::StorageMergeTree::alterPartition(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<DB::PartitionCommand, std::__1::allocator<DB::PartitionCommand> > const&, DB::Context const&) @ 0xd6f3e11 in /usr/bin/clickhouse
6. DB::InterpreterAlterQuery::execute() @ 0xd1bc205 in /usr/bin/clickhouse
7. ? @ 0xd5499f9 in /usr/bin/clickhouse
8. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) @ 0xd54d025 in /usr/bin/clickhouse
9. DB::TCPHandler::runImpl() @ 0x9106678 in /usr/bin/clickhouse
10. DB::TCPHandler::run() @ 0x9107650 in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x10304f4b in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x103053db in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0x104b2fa6 in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x104ae260 in /usr/bin/clickhouse
15. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
16. __clone @ 0xfebad in /usr/lib64/libc-2.17.so


2020.09.22 17:02:04.966753 [ 228014 ] {bf966e1c-9b53-4d1b-b5b7-c94badfe7701} <Error> executeQuery: Code: 473, e.displayText() = DB::Exception: READ locking attempt on "db.table_shard" has timed out! (120000ms) Possible deadlock avoided. Client should retry. (version 20.4.4.18 (official build)) (from [::ffff:10.130.129.10]:48278) (in query: SELECT sum(col1), sum(col2)  FROM db.table_shard WHERE (time < now()) AND (time > (now() - 1800)) HAVING (col1 = 0) OR (col2 = 0)), Stack trace (when copying this message, always include the lines below):
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x104191d0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8fff8ad in /usr/bin/clickhouse
2. ? @ 0xd651b8a in /usr/bin/clickhouse
3. DB::IStorage::lockStructureForShare(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::SettingTimespan<(DB::SettingTimespanIO)1> const&) @ 0xd64e6f3 in /usr/bin/clickhouse
4. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd2395da in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd23afe9 in /usr/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xd40c421 in /usr/bin/clickhouse
7. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0xd1a8804 in /usr/bin/clickhouse
8. ? @ 0xd54951e in /usr/bin/clickhouse
9. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) @ 0xd54d025 in /usr/bin/clickhouse
10. DB::TCPHandler::runImpl() @ 0x9106678 in /usr/bin/clickhouse
11. DB::TCPHandler::run() @ 0x9107650 in /usr/bin/clickhouse
12. Poco::Net::TCPServerConnection::start() @ 0x10304f4b in /usr/bin/clickhouse
13. Poco::Net::TCPServerDispatcher::run() @ 0x103053db in /usr/bin/clickhouse
14. Poco::PooledThread::run() @ 0x104b2fa6 in /usr/bin/clickhouse
15. Poco::ThreadImpl::runnableEntry(void*) @ 0x104ae260 in /usr/bin/clickhouse
16. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
17. __clone @ 0xfebad in /usr/lib64/libc-2.17.so
```

And one more about "too many simultaneous requests" as a result of all this. Exactly the same exceptions exist on all shards. I suspect that we caught a deadlock despite the message and there's something wrong with dropping partitions at the same time with inserts, because there were no cases like that before when we used the DELETE mutation for cleanup, and the number of inserts didn't change at all. However, I didn't notice any suspicious hanging queries in the system.processes table. I'd be glad to hear your ideas, or if someone else has encountered that before.

Thanks.

**Comment by den-crane** [comment] 2020-09-22 21:20
>20.4.4.18

"Possible deadlock avoided." has been fixed in 20.6
You need to upgrade at least to 20.6 (though it's not supported anymore). 
Supported versions 20.7 , 20.8 , 20.9

**Comment by simo-lineate** [comment] 2020-09-25 16:08
@den-crane Thanks for the update. You're suggesting to upgrade to 20.7+. However, 2.3 is marked as the current LTS in your docs. Are the docs a little behind? My team is trying to update to the most stable version in production, not necessarily the latest version. What version would you suggest to upgrade to as of this date?

**Comment by den-crane** [comment] 2020-09-26 22:25
@simo-lineate "Possible deadlock avoided." -- not a bug. 
It's a special safe-limiter to prevent deadlocks. This limiter throws alerts "Possible deadlock avoided."
This issue was solved in 20.6. No alerts anymore.
It will be never solved in 20.3 (LTS). Because it's not a bug.

Currently supported versions are 20.7 , 20.8 , 20.9 and 20.3 (LTS).

>What version would you suggest to upgrade to as of this date?

I suggest to test any CH version for at least for 6 months at your stage environment.

**Comment by keliss** [comment] 2020-09-27 09:00
Do I understand correctly that ALTER queries were synchronous in versions prior to 20.6, and it could cause a deadlock? The issue I'm interested in is not the message, but the cause itself.

**Comment by den-crane** [comment] 2020-09-27 13:38
@keliss it's not about only ALTER. And it's about memory structures and mutexes. (CH does not database level locks)

Deadlock was possible before 19.14. 
AFAIK even for 2 concurrent queries `select ... from system.tables` & `drop table`. To solve this deadlock a check "Possible deadlock avoided." was implemented.

**Comment by keliss** [comment] 2020-09-27 14:06
I see, but as you've already noticed, we're running 20.4.4.18 and the issue was very similar to a deadlock: at the time of the incident, the RWLockReadersWaitMilliseconds metric was increasing infinitely until the restart of the CH cluster, while normally it is zero. Can you please tell if this is still possible to catch such behavior even on the newer versions and how we can avoid this?

**Comment by den-crane** [comment] 2020-09-28 19:25
@keliss Can you reproduce a CH hanging or the error "Possible deadlock avoided" with 20.7+ ?

**Comment by keliss** [comment] 2020-09-28 19:30
I'm not ready to tell just yet, the upgrade to 20.7+ is to be done. But I'll certainly let you know in this case.

**Comment by keliss** [comment] 2020-10-17 11:02
@den-crane Hi, we've upgraded to 20.9.3.45-2, and this behavior seems to be somewhat alleviated and no complete deadlock happens (at least, we haven't encountered it yet), but here's what I was able to reproduce:
```
2020.10.17 10:50:27.754895 [ 232093 ] {dd1f198e-b13b-4fbb-af0b-2c6874f40694} <Error> executeQuery: Code: 159, e.displayText() = DB::Exception: Timeout while waiting for already running merges (version 20.9.3.45 (official build)) (from [::ffff:ip]:60332) (in query: alter table db.table drop partition '2020-10-15 01:00:00'), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe736dad in /usr/bin/clickhouse
2. DB::StorageMergeTree::stopMergesAndWait() @ 0x160285a7 in /usr/bin/clickhouse
3. DB::StorageMergeTree::dropPartition(std::__1::shared_ptr<DB::IAST> const&, bool, DB::Context const&) @ 0x16028c34 in /usr/bin/clickhouse
4. DB::StorageMergeTree::alterPartition(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<DB::PartitionCommand, std::__1::allocator<DB::PartitionCommand> > const&, DB::Context const&) @ 0x16030d28 in /usr/bin/clickhouse
5. DB::InterpreterAlterQuery::execute() @ 0x15ab5192 in /usr/bin/clickhouse
6. ? @ 0x15e2fdd2 in /usr/bin/clickhouse
7. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0x15e31b59 in /usr/bin/clickhouse
8. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x1647cdd9 in /usr/bin/clickhouse
9. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x1648088b in /usr/bin/clickhouse
10. Poco::Net::HTTPServerConnection::run() @ 0x18cfafb3 in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x18d391cb in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x18d3965b in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0x18eb8136 in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x18eb3530 in /usr/bin/clickhouse
15. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
16. __clone @ 0xfebad in /usr/lib64/libc-2.17.so
```
```
2020.10.17 10:50:27.770810 [ 232093 ] {dd1f198e-b13b-4fbb-af0b-2c6874f40694} <Error> DynamicQueryHandler: Code: 159, e.displayText() = DB::Exception: Timeout while waiting for already running merges, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe736dad in /usr/bin/clickhouse
2. DB::StorageMergeTree::stopMergesAndWait() @ 0x160285a7 in /usr/bin/clickhouse
3. DB::StorageMergeTree::dropPartition(std::__1::shared_ptr<DB::IAST> const&, bool, DB::Context const&) @ 0x16028c34 in /usr/bin/clickhouse
4. DB::StorageMergeTree::alterPartition(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<DB::PartitionCommand, std::__1::allocator<DB::PartitionCommand> > const&, DB::Context const&) @ 0x16030d28 in /usr/bin/clickhouse
5. DB::InterpreterAlterQuery::execute() @ 0x15ab5192 in /usr/bin/clickhouse
6. ? @ 0x15e2fdd2 in /usr/bin/clickhouse
7. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0x15e31b59 in /usr/bin/clickhouse
8. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x1647cdd9 in /usr/bin/clickhouse
9. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x1648088b in /usr/bin/clickhouse
10. Poco::Net::HTTPServerConnection::run() @ 0x18cfafb3 in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x18d391cb in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x18d3965b in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0x18eb8136 in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x18eb3530 in /usr/bin/clickhouse
15. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
16. __clone @ 0xfebad in /usr/lib64/libc-2.17.so
 (version 20.9.3.45 (official build))
```
The query just hanged and was canceled due to timeout.

**Comment by keliss** [comment] 2020-10-17 11:11
And it happened again now. In system.merges I can see that the part being dropped is also being merged at the same time. It seems to me pointless to continue merging a part when it is no longer needed. And according to the logs, CH tries to stop the merges but looks like it fails to do so, which causes timeouts.

**Comment by keliss** [comment] 2020-10-17 11:14
And one more message goes along with the above ones:
```
2020.10.17 11:06:34.097839 [ 266902 ] {} <Error> DynamicQueryHandler: Code: 373, e.displayText() = DB::Exception: Session is locked by a concurrent client., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe736dad in /usr/bin/clickhouse
2. DB::NamedSessions::acquireSession(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >, bool) @ 0x15876506 in /usr/bin/clickhouse
3. DB::Context::acquireNamedSession(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >, bool) @ 0x15860348 in /usr/bin/clickhouse
4. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x1647bc99 in /usr/bin/clickhouse
5. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x1648088b in /usr/bin/clickhouse
6. Poco::Net::HTTPServerConnection::run() @ 0x18cfafb3 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x18d391cb in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x18d3965b in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x18eb8136 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x18eb3530 in /usr/bin/clickhouse
11. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
12. __clone @ 0xfebad in /usr/lib64/libc-2.17.so
 (version 20.9.3.45 (official build))
```

**Comment by den-crane** [comment] 2020-10-21 22:06
> And it happens way too often. In system.merges I can see that the part being dropped is also being merged at the same time. It seems to me pointless to continue merging a part when it is no longer needed. And according to the logs, CH tries to stop the merges but looks like it fails to do so, which causes timeouts.

@alesapin What do you think? I know that `alter table` should cancel the current merge. But is it true for `drop partition` ?

**Comment by keliss** [comment] 2020-11-21 11:32
@alesapin Hi, any updates on this?

**Comment by jiakai908** [comment] 2020-12-14 01:52
> > 20.4.4.18
> 
> "Possible deadlock avoided." has been fixed in 20.6
> You need to upgrade at least to 20.6 (though it's not supported anymore).
> Supported versions are 20.7 , 20.8 , 20.9

1.
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 473, host: 172.0.0,1, port: 8123; Code: 473, e.displayText() = DB::Exception: WRITE locking attempt on "xxxxxx" has timed out! (120000ms) Possible deadlock avoided. Client should retry. (version 20.7.2.30 (official build))
2.
drop table if exists dw_list_form_task_dept_subject_result_all_quota2;
create table dw_list_form_task_dept_subject_result_all_quota2 engine = AggregatingMergeTree() ORDER BY uuid as
select xxxx; in (version 20.7.2.30 (official build))

it still happens.i have two same machines enviroment. the other one have not this problem.

**Comment by jiakai908** [comment] 2020-12-14 02:14
i find this issue. i have a select statment hang 3 days that block it.

**Comment by alexey-milovidov** [comment] 2021-01-05 23:12
Does it reproduce on recent versions (20.12 or newer)?

**Comment by keliss** [comment] 2021-01-06 01:32
No, I didn't encounter this after the upgrade.

**Closed** 2021-01-06 02:08 UTC
Labels: invalid, obsolete-version, st-need-info

**Comment by fastio** [comment] 2021-01-27 07:53
> Does it reproduce on recent versions (20.12 or newer)?

Hi  @alexey-milovidov , It still happens in version 20.7 .

stack trace:
 2021.01.27 15:03:10.721002 [ 374507 ] {} <Information> ClusterCopier: Number of nodes that executed ALTER query successfully : 4
2021.01.27 15:07:19.728826 [ 374528 ] {} <Information> ClusterCopier: Code: 473, e.displayText() = DB::Exception: Received from 10.5.132.123:9000. DB::Exception: WRITE locking attempt on "dal_local.oa_bi_profile_singerid_d_2" has timed out! (120000ms) Possible deadlock avoided. Client should retry.. (version 20.7.2.30)
2021.01.27 15:07:19.728935 [ 374507 ] {} <Information> ClusterCopier: There was an error while executing ALTER on each node. Query was executed on 5 nodes. But had to be executed on 36
2021.01.27 15:07:19.728959 [ 374507 ] {} <Information> ClusterCopier: Number of nodes that executed ALTER query successfully : 5
2021.01.27 15:12:19.830195 [ 374525 ] {} <Information> ClusterCopier: Code: 209, e.displayText() = DB::NetException: Timeout exceeded while reading from socket (10.5.133.123:9000): while receiving packet from 10.5.123.130:9000 (version 20.7.2.30)
2021.01.27 15:14:19.831292 [ 374525 ] {} <Information> ClusterCopier: Code: 473, e.displayText() = DB::Exception: Received from 10.5.132.236:9000. DB::Exception: WRITE locking attempt on "dal_local.oa_bi_profile_singerid_d_2" has timed out! (120000ms) Possible deadlock avoided. Client should retry.. (version 20.7.2.30)
2021.01.27 15:14:19.831390 [ 374507 ] {} <Information> ClusterCopier: There was an error while executing ALTER on each node. Query was executed on 4 nodes. But had to be executed on 42
2021.01.27 15:14:19.831418 [ 374507 ] {} <Information> ClusterCopier: Number of nodes that executed ALTER query successfully : 4
2021.01.27 15:19:19.933166 [ 374528 ] {} <Information> ClusterCopier: Code: 209, e.displayText() = DB::NetException: Timeout exceeded while reading from socket (10.5.133.130:9000): while receiving packet from 10.5.133.130:9000 (version 20.7.2.30)
2021.01.27 15:21:19.934381 [ 374528 ] {} <Information> ClusterCopier: Code: 473, e.displayText() = DB::Exception: Received from 10.5.132.236:9000. DB::Exception: WRITE locking attempt on "dal_local.oa_bi_profile_singerid_d_2" has timed out! (120000ms) Possible deadlock avoided. Client should retry.. (version 20.7.2.30)
2021.01.27 15:21:19.934518 [ 374507 ] {} <Information> ClusterCopier: There was an error while executing ALTER on each node. Query was executed on 4 nodes. But had to be executed on 48
2021.01.27 15:21:19.934546 [ 374507 ] {} <Information> ClusterCopier: Number of nodes that executed ALTER query successfully : 4
2021.01.27 15:23:19.936949 [ 374526 ] {} <Information> ClusterCopier: Code: 473, e.displayText() = DB::Exception: Received from 10.5.132.236:9000. DB::Exception: WRITE locking attempt on "dal_local.oa_bi_profile_singerid_d_2" has timed out! (120000ms) Possible deadlock avoided. Client should retry.. (version 20.7.2.30)
2021.01.27 15:25:19.938181 [ 374526 ] {} <Information> ClusterCopier: Code: 473, e.displayText() = DB::Exception: Received from 10.5.133.130:9000. DB::Exception: WRITE locking attempt on "dal_local.oa_bi_profile_singerid_d_2" has timed out! (120000ms) Possible deadlock avoided. Client should retry.. (version 20.7.2.30)
2021.01.27 15:25:19.938308 [ 374507 ] {} <Information> ClusterCopier: There was an error while executing ALTER on each node. Query was executed on 4 nodes. But had to be executed on 54
2021.01.27 15:25:19.938332 [ 374507 ] {} <Information> ClusterCopier: Number of nodes that executed ALTER query successfully : 4
