### ISSUE TITLE
Corrupted data in projections (Code: 40. DB::Exception: Checksum mismatch for uncompressed file)

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/ClickHouse#34744] opened 2022-02-19 05:04 UTC
STR:

1. Create table- 
```sql
CREATE TABLE default.data
(
    `col1` LowCardinality(String),
    `col2` UInt8 CODEC(T64, Default),
    `col3` UInt32,
    `col4` UInt32,
    PROJECTION p1
    (
        SELECT *
        ORDER BY (col3, col4)
    )
)
ENGINE = ReplicatedMergeTree('/data', 'ch')
ORDER BY col1
```

2. Download and insert data (I am making anonymized data available for this bug report) from [this](https://drive.google.com/file/d/19kJBeRm4SkY8ue2GOE-_cF76Rkj41VdX/view) link. It is a CSV file (less than 5 MB)
```bash
cat ./ch-test/* | clickhouse-client -q "insert into data format CSV"
```

3. Run command `check table` and you will see this in logs- 
```
2022.02.19 04:53:00.008536 [ 128 ] {37024151-9f04-41f9-b161-fda84b51d25f} <Error> default.data (ReplicatedMergeTreePartCheckThread): DB::CheckResult DB::ReplicatedMergeTreePartCheckThread::checkPart(const DB::String &): Code: 40. DB::Exception: Checksum mismatch for uncompressed file col4.bin in data part. (CHECKSUM_DOESNT_MATCH), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::MergeTreeDataPartChecksum::checkEqual(DB::MergeTreeDataPartChecksum const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x142f9b13 in /usr/bin/clickhouse
2. DB::MergeTreeDataPartChecksums::checkEqual(DB::MergeTreeDataPartChecksums const&, bool) const @ 0x142fa434 in /usr/bin/clickhouse
3. DB::checkDataPart(std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::shared_ptr<DB::IDisk> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::NamesAndTypesList const&, DB::MergeTreeDataPartType const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, std::__1::function<bool ()>) @ 0x14498220 in /usr/bin/clickhouse
4. DB::checkDataPart(std::__1::shared_ptr<DB::IMergeTreeDataPart const>, bool, std::__1::function<bool ()>) @ 0x1449b7e5 in /usr/bin/clickhouse
5. DB::ReplicatedMergeTreePartCheckThread::checkPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x14445e79 in /usr/bin/clickhouse
6. DB::StorageReplicatedMergeTree::checkData(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1402fae0 in /usr/bin/clickhouse
7. DB::InterpreterCheckQuery::execute() @ 0x13a13c52 in /usr/bin/clickhouse

```

version (run via `yandex/clickhouse-server:22.1.3` docker image running on mac os with apple silicon chip)-

```

┌─version()─┐
│ 22.1.3.7  │
└───────────┘
```

cc @amosbird

**Comment by amosbird** [comment] 2022-02-19 05:16
Thanks for the detailed bug report. I cannot reproduce it with current master. It's most likely fixed by https://github.com/ClickHouse/ClickHouse/pull/33774 . Please check if it's still an issue.

**Closed by amosbird** 2022-02-19 05:16 UTC
Labels: potential bug

**Comment by gauravphoenix** [comment] 2022-02-19 18:03
I can confirm that the issue is resolved on the master branch
