### ISSUE TITLE
PROXYv1 improvements

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#24796] opened 2021-05-31 11:04 UTC
We have right now support for the PROXYv1 protocol for unencrypted TCP protocol - which can be enabled on a separate port. 
And for HTTP we have support for X-Forwarded-For header. See https://github.com/ClickHouse/ClickHouse/pull/17707 and https://github.com/ClickHouse/ClickHouse/issues/17268 

In both cases, the original IP is stored 'aside' as a 'forwarder_for' field. 

What we need:
1) support for all possible ports/protocols including SSL/http/mysql/postgres (not only TCP). 
   - we don't want to have a separate port each time, 
   - we also don't want to enable PROXYv1 for the port globally (otherwise intercluster/local connections will also require PROXYv1)
   - we want that PROXYv1 to be used ONLY when the client IP = known load balancer IP. 
2) 'trust' relations with the load balancer: when the connection comes from 'whitelisted' load balancer IP - use passed IP inside address (not in `forwarded_for`).
3) for HTTP - we need to support both option HTTP wrapped in PROXYv1, or HTTP with X-Forwarded-For extra header. 

Proposed config:

```xml
<!-- once the section exists the connection from load balancer will be processed differently - clickhouse will allow PROXYv1 for it by default -->
<loadbalancer>
    <!--
        List of networks, same way as used inside users.xml for users.
        Support <ip> (also with cidr), <host> or <host_regexp>
    -->
    <networks>
        <ip>10.0.1.2</ip>
    </networks>
    <!--
        if enabled, then passed IP is stored inside address, and loadbalancer address is not stored at all.  
        if disabled then passed IP is stored inside forwarded_for and loadbalancer address is stored in address
    -->
    <respect_passed_ip_as_main_address>1</respect_passed_ip_as_main_address>

    <!--
        if enabled then HTTP ports (http / http_secure /interserver_http) also use PROXYv1, X-Forwarded-For otherwise
    -->
    <http_uses_proxy_v1>1</http_uses_proxy_v1>
<loadbalancer>
```

Some other notes: https://drive.google.com/file/d/1P8J5At0g0qlj3s_sy1HSMmn-IPpUuebP/view?usp=sharing

**Comment by filimonov** [comment] 2021-06-01 07:30
Similar concept - use PROXY protocol for SOME whitelisted ips - in Percona / MariaDB
https://mariadb.com/kb/en/server-system-variables/#proxy_protocol_networks
https://www.percona.com/doc/percona-server/8.0/flexibility/proxy_protocol_support.html 

In Apache it's opposite - PROXY enabled by default, and certain IPs can be used to connect w/o proxy.
https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html#remoteipproxyprotocolexceptions

The concept of 'trusted proxies' - i.e. when target system respect/trust IP passed by them also exists in different systems:
- nginx  https://nginx.org/en/docs/stream/ngx_stream_realip_module.html
- apache https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html#remoteiptrustedproxy

**Comment by traceon** [comment] 2021-06-09 15:32
As a suggestion (with a flexible listening interface configuration in mind):
```xml
<proxies>
    <my_proxy> <!-- Arbitrary name, to refer this config in interfaces config, for logging, etc. -->
        <addresses> <!-- Any connection from this range will be treated as a proxied connection, from a tructed proxy. -->
            <ip>10.0.1.2</ip>
            <net>10.0.1.3/32</net>
            <net>10.0.2.0/24</net>
        </addresses>
        <version>1</versions>
        <transparent>1</transparent> <!-- Change the IP to the forwarded IP of the client and hide the proxy completely. -->
        <allow_http_x_forwarded_for>1</allow_http_x_forwarded_for>
    </my_proxy>
</proxies>
```

Then, something like this in a specific listening interface configuration:
```xml
<listen>
    <default_native_unencrypted> <!-- Arbitrary name, for logging, etc. -->
        <protocol>tcp_native<protocol>
        <addresses>  <!-- What addresses to bind to. All IPv4/IPv6 should be bound to if host is specified... -->
            <ip>10.0.0.1</ip>
            <host>localhost</host>
        </addresses>
        <port>8123</port>
        <allow_direct>1</allow_direct> <!-- Allow "unproxied" connections - the standard. -->
        <allow_proxies> <!-- Allow "proxied" connections, but only for the listed proxies (and adjusted configs). -->
            <my_proxy>
                <!-- Any param that will overwrite the original my_proxy config value. -->
            </my_proxy>
        </allow_proxies>
    </default_native_unencrypted>
</listen>
```

Ip/net/host may be too verbose, a single section should be enough for parsing.

**Comment by alexey-milovidov** [comment] 2022-06-24 20:37
Duplicate of #38411.

**Closed by alexey-milovidov** 2022-06-24 20:37 UTC
Labels: feature, comp-net, st-discussion
