### ISSUE TITLE
Cluster without tcp_port can't start

### ISSUE THREAD

**Issue by Farfaday** [ClickHouse/ClickHouse#3033] opened 2018-09-04 14:18 UTC
Hi,
I am trying to use
`<tcp_ssl_port>9440</tcp_ssl_port> `
with version 1.1.54388 but I could not find much documentation about that feature.

I am also using 
```
    <https_port>8443</https_port>
    <!-- Used with https_port and tcp_ssl_port. Full ssl options list: https://github.com/ClickHouse-Extras/poco/blob/master/NetSSL_OpenSSL/include/Poco/Net/SSLManager.h#L71 -->
    <openSSL>
        <server> <!-- Used for https server AND secure tcp port -->
            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
            <privateKeyFile>/etc/clickhouse-server/server.key</privateKeyFile>
            <!-- openssl dhparam -out /etc/clickhouse-server/dhparam.pem 4096 -->
            <dhParamsFile>/etc/clickhouse-server/dhparam.pem</dhParamsFile>
            <verificationMode>none</verificationMode>
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
        </server>

        <client> <!-- Used for connecting to https dictionary source -->
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
            <!-- Use for self-signed: <verificationMode>none</verificationMode> -->
            <invalidCertificateHandler>
                <!-- Use for self-signed: <name>AcceptCertificateHandler</name> -->
                <name>RejectCertificateHandler</name>
            </invalidCertificateHandler>
        </client>
    </openSSL>

```
which is working, I can connect to https/myhost:8443 with HTTPS.

I tried removing
` <tcp_port>9000</tcp_port>` but then I get 

```
2018.09.04 12:44:48.560618 [ 37 ] <Error> raw_events.Event_Tracking (ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestartingThread::run(): Poco::Exceptio
n. Code: 1000, e.code() = 0, e.displayText() = Not found: tcp_port, e.what() = Not found
```
Having both entries 
```
<tcp_port>9000</tcp_port>
<tcp_ssl_port>9440</tcp_ssl_port>
```
seems to do nothing, port 9440 does not appear in netstat or in clickhouse's log files.

Do you have any hints ?
Many Thanks !

**Comment by proller** [comment] 2018-09-04 14:33
tcp_ssl_port was renamed to tcp_port_secure

**Comment by Farfaday** [comment] 2018-09-04 15:37
Many thanks !
(but i could not find the string tcp_port_secure in the documentation at https://clickhouse.yandex/docs/en/ )

**Comment by proller** [comment] 2018-09-04 15:41
But it described in default config https://github.com/yandex/ClickHouse/blob/master/dbms/programs/server/config.xml#L18

**Comment by Farfaday** [comment] 2018-09-04 17:42
Could it be possible to use tcp_port_secure only and not tcp_port anymore ?
When I tried that, I am getting 

`<Error> raw_events_masterdata.Channel_Adgroup_UserId (ReplicatedMergeTreeRestartingThread): void DB::ReplicatedMergeTreeRestartingThread::run(): Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Not found: tcp_port, e.what() = Not found`
In clickhouse-server.err.log

Thanks !

**Comment by alexey-milovidov** [comment] 2019-02-13 00:30
The issue is still relevant. You have to enable some tcp port for server to work. It's recommended to use some firewalled port that's only available from localhost.

**Comment by fessmage** [comment] 2019-02-18 14:27
Got this too - when i define config with only tcp_port_secure on single server - its fine. But when i added cluster config with zookeeper section - server wont start, with `<Error> Application: Not found: tcp_port` in log. its good that this error can be mitigated by define tcp_port and closing it with firewall, but question is - will it be fixed ?

**Comment by alexey-milovidov** [comment] 2022-10-20 23:35
I remember something like this and most likely it is fixed.

**Closed by alexey-milovidov** 2022-10-20 23:35 UTC
Labels: unexpected behaviour
