### ISSUE TITLE
Unexpected behaviour when working with Decimal and NULL or nullable fields.

### ISSUE THREAD

**Issue by aberrier** [ClickHouse/ClickHouse#23076] opened 2021-04-14 14:38 UTC
We started to use `toDecimal64OrNull` on our Clickhouse database to put `NULL` on invalid data instead of raising.
However, we found that `NULL` was overly present.
With a small test, we saw that `toDecimalNNOrNull` was giving a `NULL` value in some case, where it shouldn't be :

```
SELECT toDecimal64OrNull('6.24994', 4);
>> null
SELECT toDecimal64('6.24994', 4);
>> 6.2499
```
This seems to be directly linked to the scale given. If the number of decimals > S, `NULL` is returned.
Is this the expected behaviour or the decimal truncate made by `toDecimal6NN` isn't ?

PS: We are using `21.4.3.21` version

**Comment by aberrier** [comment] 2021-04-14 18:33
I found another issue related to this one.
It seems that even `toDecimal` will works or not 'correctly' depending if you query a nullable field or not.

```
SELECT toDecimal64('6.24994', 4),
       toDecimal64('5.294345454499999', 4),
       toDecimal64(toNullable('6.24994'), 4),
       toDecimal64(toNullable('5.294345454499999'), 4);
```
gives

| toDecimal64\('6.24994', 4\) | toDecimal64\('5.294345454499999', 4\) | toDecimal64\(toNullable\('6.24994'\), 4\) | toDecimal64\(toNullable\('5.294345454499999'\), 4\) |
| :--- | :--- | :--- | :--- |
| 6.2499 | 5.2943 | NULL | NULL |

This currently makes the use of Decimal with Nullable fields almost impossible.

**Comment by kozlek** [comment] 2021-04-19 09:50
Hello ! 🙂
I'm also experiencing some issues with Decimal and Nullable(Decimal).

`SELECT toDecimal64OrNull('TEST', 4)` -> NULL
which is the expected behaviour

`SELECT toDecimal64OrNull('TEST', 4), 42 / toDecimal64OrNull('TEST', 4);` -> Division By Zero 
which is not the expected behaviour, as `42 / NULL -> NULL`

This seems deeply related to the way DecimalField is implemented as it doesn't crash using Int8:
`SELECT toInt8OrNull('TEST'), 42 / toInt8OrNull('TEST');` -> NULL | NULL 

The same inconsistent behaviour between Integer and Decimal is also observed with dictGetOrNull, and seems to be mentioned in #22621, #7509.

As of today, using Decimal in Clickhouse requires a lot of pre-check to ensure that we won't be stuck by an incorrect behaviour 😕

How can we help you to fix the Decimal field ?

**Comment by alexey-milovidov** [comment] 2021-06-17 03:09
It happens because you have excessive number of digits for Decimal.

`SELECT toDecimal64OrNull('6.24994', 4);`

6.24994 cannot be represented in Decimal with 4 digits after point, because truncation will occur.

`SELECT toDecimal64OrNull('6.24994', 5);`

Works.

**Comment by alexey-milovidov** [comment] 2021-06-17 03:10
It is possible to just return the truncated result instead of NULL.

**Comment by alexey-milovidov** [comment] 2021-08-15 04:07
Duplicate of #23076.

**Closed by alexey-milovidov** 2021-08-15 04:07 UTC
Labels: unexpected behaviour, comp-nullable, comp-decimal
