### ISSUE TITLE
Delete rows bug for JSON column type

### ISSUE THREAD

**Issue by Kev1ntan** [ClickHouse/ClickHouse#40990] opened 2022-09-05 08:08 UTC
clickhouse version 22.8
doesn't delete row from table using alter table delete command

create table query:
```
CREATE TABLE logs
(
    datetime DEFAULT now() Codec(DoubleDelta, LZ4),
    message JSON
)
ENGINE = MergeTree
order by datetime;
```

insert query:
```
INSERT INTO logs(message) VALUES ('{"a": 2, "b": { "c": 22, "d": [12, 122, 13] }, "f": "a"}');
```

delete query:
```
alter table logs delete where message.f = 'a';
```

error from select * from system.mutations;
```
Code: 47. DB::Exception: Missing columns: 'message.f' while processing query: 'SELECT count() WHERE (message.f = 'a') OR (message.f = 'a')', required columns: 'message.f', maybe you meant: ['message']. (UNKNOWN_IDENTIFIER) (version 22.3.8.40.altinitystable (altinity build))
```

**Comment by Avogar** [comment] 2022-09-05 11:34
Seems like a general problem with subcolumns, not only with JSON type (same problem if we will use named Tuple). Let's ask @CurtizJ if it's something known

**Comment by Kev1ntan** [comment] 2022-09-06 15:04
update also not working

**Comment by rsaphala** [comment] 2022-09-08 07:28
any updates on this? not being able to update / delete rows is a pretty heavy limitation for our use case

**Comment by Kev1ntan** [comment] 2022-09-08 09:32
is there any CH version that support update / delete with json column table?

**Comment by Kev1ntan** [comment] 2022-09-09 04:03
@shacuros another issue is try alter delete for primitive column also not working according to https://github.com/ClickHouse/ClickHouse/issues/40990#issuecomment-1238279181 change the alter to delete, alter table trydelete delete where int = 1, error ```Code: 16. DB::Exception: There is no physical column or subcolumn message in table: While executing MergeTreeInOrder. (NO_SUCH_COLUMN_IN_TABLE) (version 22.3.8.40.altinitystable (altinity build))```

**Comment by shacuros** [comment] 2022-09-09 07:33
@Kev1ntan i cannot reproduce your update problem on 22.8.

**Comment by Kev1ntan** [comment] 2022-09-13 04:03
@shacuros i try ```ALTER TABLE logs DELETE WHERE JSONExtractString(toJSONString(message), 'f') = 'a'``` but not working 
```
Code: 47. DB::Exception: Missing columns: 'message.a' while processing query: 'SELECT count() WHERE (message.a = 2) OR (message.a = 2) OR (JSONExtractString(toJSONString(message), 'f') = 'a')', required columns: 'message.a' 'message', maybe you meant: ['message','message']. (UNKNOWN_IDENTIFIER) (version 22.8.4.7 (official build))
```

**Comment by Kev1ntan** [comment] 2022-09-13 04:18
@shacuros just found the way to reproduce the issue

```
CREATE TABLE tryupdate
(
    datetime DEFAULT now() Codec(DoubleDelta, LZ4),
    message JSON,
    str String,
    int Int64
)
ENGINE = MergeTree
order by datetime;

INSERT INTO tryupdate(message,str,int) VALUES ('{"a": 2, "b": { "c": 22, "d": [12, 122, 13] }, "f": "a"}','a',1);

alter table tryupdate update int = 10 where message.a = 2; (Code: 47. DB::Exception: Missing columns: 'message.a' while processing query: 'SELECT count() WHERE message.a = 2', required columns: 'message.a', maybe you meant: ['message']. (UNKNOWN_IDENTIFIER) (version 22.8.4.7 (official build)))

then try to update using :
ALTER TABLE tryupdate update int = 10 WHERE JSONExtractString(toJSONString(message), 'f') = 'a' (Code: 47. DB::Exception: Missing columns: 'message.a' while processing query: 'SELECT count() WHERE (message.a = 2) OR (JSONExtractString(toJSONString(message), 'f') = 'a')', required columns: 'message.a' 'message', maybe you meant: ['message','message']. (UNKNOWN_IDENTIFIER) (version 22.8.4.7 (official build)))
```

**Comment by alexey-milovidov** [comment] 2023-01-08 06:23
JSON data type should not be used; it is under development.

**Comment by tavplubix** [comment] 2023-09-19 11:19
The fix was reverted, so we should reopen this

**Comment by alexey-milovidov** [comment] 2023-09-30 01:49
> version 22.3.8.40.altinitystable (altinity build)

This is not the official build.

We *strongly* do not recommend using alternative builds from third-party companies.

Read this on why you can't expect any support for "altinity": https://clickhouse.com/docs/knowledgebase/difference_between_official_builds_and_3rd_party

**Comment by tavplubix** [comment] 2023-09-30 18:05
It's a good point, but we have exactly the same bug in official builds

**Comment by alexey-milovidov** [comment] 2023-09-30 20:43
We are going to deprecate the experimental JSON object type - closing.

**Closed by alexey-milovidov** 2023-09-30 20:43 UTC
Labels: experimental issue
