### ISSUE TITLE
Unexpected error `Aggregate function any(number) is found in WHERE` in 20.6.3

### ISSUE THREAD

**Issue by iammapping** [ClickHouse/ClickHouse#13912] opened 2020-08-20 10:47 UTC
**Describe the bug**
aggregate the expression defined in with clause causing error while the expression also used in where.

**How to reproduce**

run query
```sql
WITH number * number AS n
SELECT
    number,
    any(n)
FROM numbers(10)
WHERE n = 4
GROUP BY number
```
failed with error:
```
Received exception from server (version 20.6.3):
Code: 184. DB::Exception: Received from localhost:9234. DB::Exception: Aggregate function any(number) is found in WHERE in query.
```

**Expected behavior**
return the fellowing result as version 20.4.4
```
┌─number─┬─any(n)─┐
│      2 │      4 │
└────────┴────────┘
```

**Comment by alexey-milovidov** [comment] 2020-11-09 00:26
Duplicate of #16708.

**Closed by alexey-milovidov** 2020-11-09 00:26 UTC
Labels: bug, comp-optimizers, duplicate
