### ISSUE TITLE
Unable to restore database from backup

### ISSUE THREAD

**Issue by chhetripradeep** [ClickHouse/ClickHouse#45687] opened 2023-01-27 06:27 UTC
**Describe the unexpected behaviour**
I tried to took backup from a database and then restore that backup. 

**How to reproduce**
```
❯ sudo mkdir /var/lib/clickhouse

❯ sudo chmod 0777 /var/lib/clickhouse/

❯ ~/gh/ClickHouse/docker/test/stateful/s3downloader --url-prefix https://clickhouse-datasets.s3.amazonaws.com --dataset-names hits visits
INFO:root:Will fetch following datasets: hits, visits
INFO:root:Processing hits
INFO:root:Downloading from https://clickhouse-datasets.s3.amazonaws.com/hits/partitions/hits_v1.tar to temp path /var/folders/tt/r0909hrn6877hwz0s6l_jr8m0000gn/T/61si_bzv
INFO:root:Content length is 1271623680 bytes
[==================================================] 100%
INFO:root:Downloading finished
INFO:root:Will unpack data from temp path /var/folders/tt/r0909hrn6877hwz0s6l_jr8m0000gn/T/61si_bzv to clickhouse db /var/lib/clickhouse/
INFO:root:Unpack finished
INFO:root:Will remove downloaded file /var/folders/tt/r0909hrn6877hwz0s6l_jr8m0000gn/T/61si_bzv from filesystem if it exists
INFO:root:Processing of hits finished
INFO:root:Processing visits
INFO:root:Downloading from https://clickhouse-datasets.s3.amazonaws.com/visits/partitions/visits_v1.tar to temp path /var/folders/tt/r0909hrn6877hwz0s6l_jr8m0000gn/T/1wfsy9yv
INFO:root:Content length is 563968000 bytes
[==================================================] 100%
INFO:root:Downloading finished
INFO:root:Will unpack data from temp path /var/folders/tt/r0909hrn6877hwz0s6l_jr8m0000gn/T/1wfsy9yv to clickhouse db /var/lib/clickhouse/
INFO:root:Unpack finished
INFO:root:Will remove downloaded file /var/folders/tt/r0909hrn6877hwz0s6l_jr8m0000gn/T/1wfsy9yv from filesystem if it exists
INFO:root:Processing of visits finished
INFO:root:Fetch finished, enjoy your tables!

❯ docker run -d --rm -p8123:8123 -p9000:9000 -p9363:9363  --name clickhouse -v /var/lib/clickhouse:/var/lib/clickhouse --ulimit nofile=262144:262144 clickhouse/clickhouse-server:23.1
f04b4bbe1580: Already exists
9fc95c38ef75: Pull complete
c33676575932: Pull complete
c8091d78269e: Pull complete
b638315b2bf0: Pull complete
3a8d5e411b2e: Pull complete
422b3e2a79a2: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:4e9121320b69a1718286c8ebc2164b90662d0aaaa9db1257062a6c83b503358f
Status: Downloaded newer image for clickhouse/clickhouse-server:23.1
5da01b1d39f33a0ba05b4cb757044c328ef4bac126e7971052e6c41a1520a914

❯ docker exec -it clickhouse /bin/bash
5da01b1d39f3 :) ATTACH DATABASE IF NOT EXISTS datasets ENGINE = Ordinary;

ATTACH DATABASE IF NOT EXISTS datasets
ENGINE = Ordinary

Query id: 6b07f6dc-b146-47e8-8af6-1796cd0f0b0a

Ok.

0 rows in set. Elapsed: 0.103 sec.

5da01b1d39f3 :) show tables in datasets;

SHOW TABLES FROM datasets

Query id: b3871fa5-792b-4253-b294-dc6b2b20ee7c

┌─name──────┐
│ hits_v1   │
│ visits_v1 │
└───────────┘

2 rows in set. Elapsed: 0.008 sec.

5da01b1d39f3 :) select count(*) from datasets.hits_v1;

SELECT count(*)
FROM datasets.hits_v1

Query id: d3ca5635-a7dc-4af0-a4ac-63e597a2bae0

┌─count()─┐
│ 8873898 │
└─────────┘

1 row in set. Elapsed: 0.005 sec.

5da01b1d39f3 :) select count(*) from datasets.visits_v1;

SELECT count(*)
FROM datasets.visits_v1

Query id: c0cea06c-5751-4760-84ef-ae3f0028c634

┌─count()─┐
│ 1676861 │
└─────────┘

1 row in set. Elapsed: 0.008 sec.

5da01b1d39f3 :) BACKUP database datasets to Disk('backups', 'full.zip');

BACKUP DATABASE datasets TO Disk('backups', 'full.zip')

Query id: 91c220c6-057c-42a0-9302-b4b6ee799dc3

┌─id───────────────────────────────────┬─status─────────┐
│ 7b73077b-44c9-4302-b6b5-994d2971a25d │ BACKUP_CREATED │
└──────────────────────────────────────┴────────────────┘

1 row in set. Elapsed: 52.718 sec.

5da01b1d39f3 :) SET allow_deprecated_database_ordinary=1

SET allow_deprecated_database_ordinary = 1

Query id: 1343b4ff-91ca-4393-9ee0-365b2a498f2f

Ok.

0 rows in set. Elapsed: 0.005 sec.

5da01b1d39f3 :) SET allow_deprecated_syntax_for_merge_tree=1

SET allow_deprecated_syntax_for_merge_tree = 1

Query id: 82aa7593-cf8a-4583-b5fd-56073d4ac4ad

Ok.

0 rows in set. Elapsed: 0.005 sec.

5da01b1d39f3 :) RESTORE DATABASE datasets AS datasets_bkp FROM Disk('backups', 'full.zip');

RESTORE DATABASE datasets AS datasets_bkp FROM Disk('backups', 'full.zip')

Query id: 38215114-c5f8-452a-8783-21dff327a77a


0 rows in set. Elapsed: 13.746 sec.

Received exception from server (version 23.1.1):
Code: 233. DB::Exception: Received from localhost:9000. DB::Exception: Trying to get part name in new format for old format version. Either some new feature is incompatible with deprecated *MergeTree definition syntax or it's a bug.. (BAD_DATA_PART_NAME)

5da01b1d39f3 :) show tables in datasets_bkp;

SHOW TABLES FROM datasets_bkp

Query id: f0fcd648-f0ad-4416-912c-d84cd6b662f7

┌─name──────┐
│ hits_v1   │
│ visits_v1 │
└───────────┘

2 rows in set. Elapsed: 0.010 sec.

5da01b1d39f3 :) select count(*) from datasets_bkp.hits_v1;

SELECT count(*)
FROM datasets_bkp.hits_v1

Query id: d224c94c-e96b-4f78-8011-ed5692b6877e

┌─count()─┐
│ 8873898 │
└─────────┘

1 row in set. Elapsed: 0.013 sec.

5da01b1d39f3 :) select count(*) from datasets_bkp.visits_v1;

SELECT count(*)
FROM datasets_bkp.visits_v1

Query id: 8260f80e-9252-47d0-92fa-2115b28f9d0d

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.016 sec.
```

**Expected behavior**
As we can see datasets_bkp.visits_v1 didn't restore properly and has zero rows. In my opinion, if there is some data corruption or some issue due to old vs new format, it should fail during backup time rather than failing during restoration time.

**Error message and/or stacktrace**
https://pastila.nl/?02c2d401/e2097a3612a3278bf85eb1fc182338fa

**Comment by chhetripradeep** [comment] 2023-01-27 12:07
cc @vitlibar

**Comment by tavplubix** [comment] 2023-01-27 12:19
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/43971

**Closed by tavplubix** 2023-01-27 12:19 UTC
Labels: unexpected behaviour
