### ISSUE TITLE
LIVE VIEW evaluate now() at run time

### ISSUE THREAD

**Issue by knoguchi** [ClickHouse/ClickHouse#15640] opened 2020-10-05 20:47 UTC
**Use case**
I would like to create a live view that select rows based on the current time.
The current LIVE VIEW implementation seems to be evaluating `now()` at the time of CREATE LIVE VIEW, which is useless because the time in the view is constant.

**Describe the solution you'd like**
Evaluate `now()` function every time INSERT happens  (or whatever the currently implemented triggers) to the table while running WATCH.

**Additional context**
I didn't think about adverse effect.   It's possible that LIVE VIEW was not designed for a query like this.

**Comment by vzakaznikov** [comment] 2020-10-22 23:58
You might get this to work using sub-queries. Just don't use now() in the inner most sub-query. For example,

```bash
ser-host :) CREATE TABLE test.mt (a Int32) Engine=MergeTree order by tuple()

CREATE TABLE test.mt
(
    `a` Int32
)
ENGINE = MergeTree
ORDER BY tuple()

Query id: 676bd32d-11f8-48c3-93b7-471f65836aa6

Ok.

0 rows in set. Elapsed: 0.020 sec. 

user-host :) CREATE LIVE VIEW test.lv AS SELECT now(), sum FROM ( SELECT sum(a) AS sum FROM test.mt )

CREATE LIVE VIEW test.lv AS
SELECT
    now(),
    sum
FROM 
(
    SELECT sum(a) AS sum
    FROM test.mt
)

Query id: 2fdc68c4-19c1-4ed7-b183-c1006428b998

Ok.

0 rows in set. Elapsed: 0.013 sec. 

user-host :) WATCH test.lv

WATCH test.lv

Query id: 4940ce47-023f-405e-8cf1-fc89cda865c2

┌───────────────now()─┬─sum─┬─_version─┐
│ 2020-10-22 19:55:51 │   0 │        1 │
└─────────────────────┴─────┴──────────┘
┌───────────────now()─┬─sum─┬─_version─┐
│ 2020-10-22 19:56:11 │   3 │        2 │
└─────────────────────┴─────┴──────────┘
┌───────────────now()─┬─sum─┬─_version─┐
│ 2020-10-22 19:56:13 │   6 │        3 │
└─────────────────────┴─────┴──────────┘
┌───────────────now()─┬─sum─┬─_version─┐
│ 2020-10-22 19:56:15 │   9 │        4 │
└─────────────────────┴─────┴──────────┘
Cancelling query.
Query was cancelled.

4 rows in set. Elapsed: 26.163 sec. 

user-host :) 


```

**Comment by knoguchi** [comment] 2020-10-23 00:29
That's a clever trick. That's sufficient for now to keep going.  Thank you.

**Comment by vzakaznikov** [comment] 2020-10-23 00:29
@KochetovNicolai, Hi Nicolai, is there a way to re-evaluate the stored `mergeable_query` so that functions like `now()` will get re-evaluated?

 https://github.com/ClickHouse/ClickHouse/blob/10d2070fbefdc4b51dd34f02109fab41508bf348/src/Storages/LiveView/StorageLiveView.cpp#L110

**Comment by vzakaznikov** [comment] 2020-10-23 01:40
The problem is that we cache the analyzed query in https://github.com/ClickHouse/ClickHouse/blob/e53909cafc8f2c24f2220d3dbd9a487218a97745/src/Storages/LiveView/StorageLiveView.cpp#L308 and this causes `now()` not be evaluated each time we run the query.

**Comment by loyd** [comment] 2021-08-30 19:57
Does it seem to be fixed now?

```sql
CREATE TABLE test2 (a Int32) Engine=MergeTree order by tuple()
CREATE LIVE VIEW test2_lv AS SELECT now(), sum(a) AS sum FROM test2
WATCH test2_lv

┌───────────────now()─┬─sum─┬─_version─┐
│ 2021-08-30 19:55:23 │   0 │        1 │
└─────────────────────┴─────┴──────────┘
┌───────────────now()─┬─sum─┬─_version─┐
│ 2021-08-30 19:55:35 │   5 │        2 │
└─────────────────────┴─────┴──────────┘
┌───────────────now()─┬─sum─┬─_version─┐
│ 2021-08-30 19:55:37 │  12 │        3 │
└─────────────────────┴─────┴──────────┘
┌───────────────now()─┬─sum─┬─_version─┐
│ 2021-08-30 19:55:39 │  20 │        4 │
└─────────────────────┴─────┴──────────┘
```

**Comment by alexey-milovidov** [comment] 2021-08-30 20:06
I don't remember any particular fix.
Ok, let's close.

**Closed by alexey-milovidov** 2021-08-30 20:06 UTC
Labels: feature
