### ISSUE TITLE
Column X is not under aggregate function and not in GROUP BY

### ISSUE THREAD

**Issue by loyd** [ClickHouse/ClickHouse#32744] opened 2021-12-14 10:13 UTC
After upgrading to `21.11.6.7` from `21.6.6.51` some of our `INSERT`s start failing with the following error:
```
2021.12.14 09:54:05.538718 [ 373 ] {} <Error> void DB::StorageBuffer::backgroundFlush(): Code: 215. DB::Exception: Column `name` is not under aggregate function and not in GROUP BY: While processing name, toStartOfInterval(platform_time, toIntervalHour(1)) AS platform_time, anyLastSimpleState(publisher) AS publisher, if((sumSimpleStateIf(1, isFinite(value)) AS count) > 0, argMinStateIf(value, platform_time, isFinite(value)), argMinState(nan, fromUnixTimestamp64Nano(CAST(9223372036854775807, 'Int64')))) AS open, if(count > 0, argMaxStateIf(value, platform_time, isFinite(value)), argMaxState(nan, fromUnixTimestamp64Nano(CAST(0, 'Int64')))) AS close, coalesce(minSimpleStateOrNullIf(value, isFinite(value)), inf) AS min, coalesce(maxSimpleStateOrNullIf(value, isFinite(value)), -inf) AS max, sumSimpleStateIf(value, isFinite(value)) AS sum, sumSimpleStateIf(value * value, isFinite(value)) AS sum_of_squares, count, sumSimpleStateIf(1, NOT isFinite(value)) AS non_finite_count, argMaxState(NOT isFinite(value), platform_time) AS ends_with_non_finite. (NOT_AN_AGGREGATE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9b722d4 in /usr/bin/clickhouse
1. DB::ActionsMatcher::visit(DB::ASTIdentifier const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x120cd5f1 in /usr/bin/clickhouse
2. DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x120d5318 in /usr/bin/clickhouse
3. DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) @ 0x120a46b7 in /usr/bin/clickhouse
4. DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0x120a44cb in /usr/bin/clickhouse
5. DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0x120aef09 in /usr/bin/clickhouse
6. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0x120b3b70 in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x1233a78d in /usr/bin/clickhouse
8. ? @ 0x123332e4 in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >) @ 0x1232dd47 in /usr/bin/clickhouse
10. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1232c6d4 in /usr/bin/clickhouse
11. DB::buildPushingToViewsChain(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&, bool, DB::ThreadStatus*, std::__1::atomic<unsigned long>*, DB::Block const&) @ 0x13362587 in /usr/bin/clickhouse
12. DB::InterpreterInsertQuery::buildChainImpl(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block const&, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) @ 0x12312b7b in /usr/bin/clickhouse
13. DB::InterpreterInsertQuery::execute() @ 0x12314f89 in /usr/bin/clickhouse
14. DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::__1::shared_ptr<DB::IStorage>) @ 0x12be8091 in /usr/bin/clickhouse
15. DB::StorageBuffer::flushBuffer(DB::StorageBuffer::Buffer&, bool, bool, bool) @ 0x12be5667 in /usr/bin/clickhouse
16. DB::StorageBuffer::backgroundFlush() @ 0x12be8e85 in /usr/bin/clickhouse
17. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x11f0eb6e in /usr/bin/clickhouse
18. DB::BackgroundSchedulePool::threadFunction() @ 0x11f11547 in /usr/bin/clickhouse
19. ? @ 0x11f124b3 in /usr/bin/clickhouse
20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x9bb4397 in /usr/bin/clickhouse
21. ? @ 0x9bb7d9d in /usr/bin/clickhouse
22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
23. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.11.6.7 (official build))
```

Maybe related to https://github.com/ClickHouse/ClickHouse/pull/28502

### indicator_log_buffer
The table that handles `INSERT`s.
```sql
CREATE TABLE indicator_log_buffer AS indicator_log
    ENGINE = Buffer(
        currentDatabase(), indicator_log,
        /* num_layers */ 1,
        /* min_time/max_time (sec) */ 1, 1,
        /* min_rows/max_rows */ 1000000, 1000000,
        /* min_bytes/max_bytes */ 100000000, 100000000
    );
```

### indicator_log
The underlying table of `indicator_log_buffer`.
```sql
CREATE TABLE indicator_log (
    name                    String,
    platform_time           DateTime64(9),
    trace_id                UInt64,
    value                   Float64,
    publisher               LowCardinality(String),

    INDEX trace_id_index trace_id TYPE minmax GRANULARITY 3
)
    ENGINE = ReplacingMergeTree
    PARTITION BY toYYYYMM(platform_time)
    ORDER BY (name, platform_time);
```

### indicator_xxx_log
The aggregated table. 
```sql
CREATE TABLE indicator_1sec_log (
    name                    LowCardinality(String),
    platform_time           DateTime64(9),
    publisher               SimpleAggregateFunction(anyLast, LowCardinality(String)),

    open                    AggregateFunction(argMin, Float64, DateTime64(9)),
    close                   AggregateFunction(argMax, Float64, DateTime64(9)),
    min                     SimpleAggregateFunction(min, Float64),
    max                     SimpleAggregateFunction(max, Float64),
    sum                     SimpleAggregateFunction(sum, Float64),
    sum_of_squares          SimpleAggregateFunction(sum, Float64),
    count                   SimpleAggregateFunction(sum, UInt64),
    non_finite_count        SimpleAggregateFunction(sum, UInt64),
    ends_with_non_finite    AggregateFunction(argMax, UInt8, DateTime64(9))
)
    ENGINE = AggregatingMergeTree
    PARTITION BY toYYYYMM(platform_time)
    ORDER BY (name, platform_time);

CREATE MATERIALIZED VIEW indicator_1sec_log_handler TO indicator_1sec_log
AS SELECT
    name, -- << ERROR
    toStartOfInterval(platform_time, INTERVAL 1 second) AS platform_time,
    anyLastSimpleState(publisher) AS publisher,

    count > 0 ? argMinStateIf(value, indicator_log.platform_time, isFinite(value))
              : argMinState(nan, fromUnixTimestamp64Nano(CAST(9223372036854775807, 'Int64'))) AS open,

    count > 0 ? argMaxStateIf(value, indicator_log.platform_time, isFinite(value))
              : argMaxState(nan, fromUnixTimestamp64Nano(CAST(0, 'Int64'))) AS close,

    coalesce(minSimpleStateOrNullIf(value, isFinite(value)), inf) AS min,
    coalesce(maxSimpleStateOrNullIf(value, isFinite(value)), -inf) AS max,
    sumSimpleStateIf(value, isFinite(value)) AS sum,
    sumSimpleStateIf(value * value, isFinite(value)) AS sum_of_squares,
    sumSimpleStateIf(1, isFinite(value)) AS count,
    sumSimpleStateIf(1, NOT isFinite(value)) AS non_finite_count,
    argMaxState(NOT isFinite(value), indicator_log.platform_time) AS ends_with_non_finite
FROM indicator_log
GROUP BY (name, platform_time);
```

**Comment by SaltTan** [comment] 2021-12-19 00:27
Similar to #32668

Try to replace

GROUP BY (name, platform_time);

with

GROUP BY name, platform_time;

**Comment by alexey-milovidov** [comment] 2021-12-20 00:56
@azat told me that this is going to be fixed in #32751.

**Closed** 2021-12-20 12:47 UTC
Labels: potential bug

**Comment by matiasdominguez** [comment] 2022-09-03 00:24
The error is still happening to me in 22.8.2.11. Fixed it by removing the parens.

**Comment by FrankChen021** [comment] 2022-11-08 08:37
@azat We're based on the latest 22.3, and suffer this problem when altering a distributed table that has a MV.

```text
Code: 215. DB::Exception: Column `timestamp` is not under aggregate function and not in GROUP BY: While processing any(track_id) AS track_id, toStartOfHour(toDateTime(intDiv(timestamp, 1000000000))) AS timestamp, toInt32(extract(source, 'MGK([0-9]+)_')) AS task_id, vendor, countState() AS volume. (NOT_AN_AGGREGATE) (version vSClickhouse-22.3-010)
```

Here is the stack trace of above exception.

```text
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x16ecf8cc in /home/clickhouse/programs/clickhouse-server
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb347ada in /home/clickhouse/programs/clickhouse-server
2. DB::ActionsMatcher::visit(DB::ASTIdentifier const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x1375bb68 in /home/clickhouse/programs/clickhouse-server
3. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x1375c645 in /home/clickhouse/programs/clickhouse-server
4. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x1375c645 in /home/clickhouse/programs/clickhouse-server
5. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x1375c645 in /home/clickhouse/programs/clickhouse-server
6. DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x1376132d in /home/clickhouse/programs/clickhouse-server
7. DB::InDepthNodeVisitor<DB::ActionsMatcher, true, false, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) @ 0x13746475 in /home/clickhouse/programs/clickhouse-server
8. DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0x13738758 in /home/clickhouse/programs/clickhouse-server
9. DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0x1373f6b5 in /home/clickhouse/programs/clickhouse-server
10. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterDAGInfo> const&, DB::Block const&) @ 0x13743422 in /home/clickhouse/programs/clickhouse-server
11. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x13a1aaa4 in /home/clickhouse/programs/clickhouse-server
12. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >, std::__1::shared_ptr<DB::IAST> const&)::$_1::operator()(bool) const @ 0x13a156f7 in /home/clickhouse/programs/clickhouse-server
13. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SubqueryForSet, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::SubqueryForSet> > >, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >, std::__1::shared_ptr<DB::IAST> const&) @ 0x13a1152e in /home/clickhouse/programs/clickhouse-server
14. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::IAST> const&) @ 0x13a0fa26 in /home/clickhouse/programs/clickhouse-server
15. DB::IStorage::getDependentViewsByColumn(std::__1::shared_ptr<DB::Context const>) const @ 0x140d78a4 in /home/clickhouse/programs/clickhouse-server
16. DB::StorageDistributed::checkAlterIsPossible(DB::AlterCommands const&, std::__1::shared_ptr<DB::Context const>) const @ 0x14102ac4 in /home/clickhouse/programs/clickhouse-server
17. DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x139ac7b4 in /home/clickhouse/programs/clickhouse-server
18 ...
```

The table that is being altered is:
```sql
CREATE TABLE event_all
(
    `partition_time` DateTime,
    `timestamp` Int64 DEFAULT 0,
    `track_id` String DEFAULT '',
    `message_id` Nullable(String),
    `task_name` Nullable(String),
    `user_id` Nullable(Int64),
    `event` LowCardinality(String),
    `recipient` String,
    `source` Nullable(String) DEFAULT '',
    `vendor` Nullable(String) DEFAULT '',
    `provider` Nullable(String) DEFAULT '',
    `error_code` Int32 DEFAULT 0,
    `description` Nullable(String) DEFAULT '',
    `task_id` Nullable(Int32),
    `phone_num_region` Nullable(String),
    `user_region` Nullable(String)
)
ENGINE = Distributed('cluster1', 'default', 'event_local', sipHash64(track_id)) 
```

And the dependent MV is:
```sql
CREATE MATERIALIZED VIEW voice_transmitted_volume_hourly_mv TO hourly_all
(
    `track_id` String,
    `timestamp` DateTime,
    `task_id` Int32,
    `vendor` String,
    `volume` AggregateFunction(count)
) AS
SELECT
    any(track_id) AS track_id,
    toStartOfHour(toDateTime(intDiv(timestamp, 1000000000))) AS timestamp,
    toInt32(extract(source, 'MGK([0-9]+)_')) AS task_id,
    vendor,
    countState() AS volume
FROM event_all
WHERE event = 'tran'
GROUP BY (timestamp, task_id, vendor) 
```

The ALTER ddl only adds some new fields.
```sql
ALTER TABLE
  event_all
ADD
  COLUMN IF NOT EXISTS ` task_id ` Nullable(Int32),
ADD
  COLUMN IF NOT EXISTS ` phone_num_region ` Nullable(String) AFTER task_id,
ADD
  COLUMN IF NOT EXISTS ` user_region ` Nullable(String) AFTER phone_num_region
```

What is strange is that when we use the above schemas in the another cluster with the same version, the problem is not reproduced, but this problem can be reproduced by re-executing ALTER ddl in the cluster that the table is originally created on.

**Comment by den-crane** [comment] 2022-11-08 09:16
@FrankChen021
You need to remove ( ) from group by

GROUP BY timestamp, task_id, vendor

**Comment by FrankChen021** [comment] 2022-11-08 09:20
@den-crane 

I don't think this is the problem. The parenthesis has already removed, but the problem still lays there.

What I found out is it's related to ON CLUSTER clause even though I don't why it results in this problem.

For the same ALTER DDL, if ON CLUSTER is specified, it fails. If ON CLUSTER is removed, it successes.

**Comment by FrankChen021** [comment] 2022-11-08 09:28
![image](https://user-images.githubusercontent.com/6525742/200526280-e71861b5-a968-479a-b642-98a12027d731.png)

![image](https://user-images.githubusercontent.com/6525742/200527199-a34b03d5-181f-423e-8d89-6e5768fc11be.png)

I'm 100% sure that the SQLs being executed from the tracing logs are identical.

**Comment by FrankChen021** [comment] 2022-11-08 10:10
@den-crane You‘re right. The workaround is to remove the parenthesis from the GROUP-BY expression. 
The comments I just left was confusion that we were executing on wrong tables, so I deleted them.

**Comment by makeavish** [comment] 2022-11-28 04:11
@den-crane but same DDL operations work in non-distributed setup. Are parens `()` not expected in clickhouse DDL operations for ORDER BY or GROUP BY?
