### ISSUE TITLE
python aborted in kazoo

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#45960] opened 2023-02-02 12:42 UTC
It looks like a big portion of tests inside one group are failed

https://s3.amazonaws.com/clickhouse-test-reports/45889/db2aa48c917dbfc7510515ef0e654472ef14ff4a/integration_tests__release__[4/4].html

here is the reason
https://s3.amazonaws.com/clickhouse-test-reports/0/683b1b7dbb5bdc0e89cdd5203f82595a9de05cc2/integration_tests__release__[2/2]/integration_run_parallel7_0.log
```
test_server_reload/test.py::test_remove_http_port Fatal Python error: Aborted

Thread 0x00007f2b467fc700 (most recent call first):
  File "/usr/lib/python3.8/selectors.py", line 468 in select
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/utils.py", line 380 in selector_select
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/threading.py", line 172 in select
```

It seems like kazoo fails as part of test_server_reload.
Usually affects test_row_policy tests as tests inside the same group.

**Comment by alexey-milovidov** [comment] 2023-02-12 03:11
Looks duplicate of https://github.com/ClickHouse/ClickHouse/issues/45367

**Closed by alexey-milovidov** 2023-02-12 03:11 UTC
Labels: duplicate
