### ISSUE TITLE
one table with 5000 columns  after insert 10k rows per/s cost 13GB memory

### ISSUE THREAD

**Issue by chenzhiping007** [ClickHouse/ClickHouse#22843] opened 2021-04-08 10:36 UTC
(you don't have to strictly follow this form)

**Describe the situation**

i have a table with 5000 columns，and insert 10k rows per/s cost 13GB memory, only insert 10 rows ,other 4990 row are empty

4990 rows defined with nullable(String)

Errors:

2021.04.08 13:32:27.367365 [ 7549 ] {91262159-b159-436d-b9ef-c5742c340fba} <Error> TCPHandler: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 13.96 GiB (attempt to allocate chunk of 4219188 bytes), maximum: 13.96 GiB, Stack trace:

Quest:

why  Clickhouse insert cost so many memory with huge columns in one table

**Comment by den-crane** [comment] 2021-04-08 13:42
It's the expected behavior.

Each column use 2 MB RAM on Insert.  5000*2 = 10GB.

Clickhouse documentation suggests to have  up to 1000 columns

**Comment by filimonov** [comment] 2021-04-08 18:38
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/6943

**Closed** 2021-04-08 18:48 UTC
Labels: question, question-answered

**Comment by chenzhiping007** [comment] 2021-04-11 15:06
what is "enabling/disabling compact parts for a table" ,which setting variables related to

**Comment by DerekChia** [comment] 2022-08-11 11:35
> what is "enabling/disabling compact parts for a table" ,which setting variables related to

You are probably referring to the fact that data parts can be stored in `Wide` or `Compact` format. Here are the definition extracted from the documentation. 

> Data parts can be stored in Wide or Compact format. In Wide format each column is stored in a separate file in a filesystem, in Compact format all columns are stored in one file. Compact format can be used to increase performance of small and frequent inserts.

Basically, you can control the `Wide` or `Compact` through the `min_bytes_for_wide_part` and `min_rows_for_wide_part` setting. This is also described in the same documentation page, extracted below. 

> Data storing format is controlled by the min_bytes_for_wide_part and min_rows_for_wide_part settings of the table engine. If the number of bytes or rows in a data part is less then the corresponding setting's value, the part is stored in Compact format. Otherwise it is stored in Wide format. If none of these settings is set, data parts are stored in Wide format.

Reference: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#mergetree-data-storage

However, do note the difference in performance when using the different format. You can see the experiment done here - https://github.com/ClickHouse/ClickHouse/issues/12737#issuecomment-663195357
