### ISSUE TITLE
Flaky 00180_no_seek_avoiding_when_reading_from_cache

### ISSUE THREAD

**Issue by pufit** [ClickHouse/ClickHouse#66190] opened 2024-07-07 20:20 UTC
https://pastila.nl/?01a1b379/66dac6d9422a20898de9e72882c733d5.link

**Comment by nickitat** [comment] 2024-07-09 12:32
let's close until reproduction. the last failure was on 5th of July. maybe smth relevant was rolled back.

**Comment by alexey-milovidov** [comment] 2024-07-25 17:39
Duplicate of #66683

**Closed by alexey-milovidov** 2024-07-25 17:39 UTC
Labels: duplicate, testing, flaky test
