### ISSUE TITLE
Invalid number of rows in Chunk column UInt32 position 1: expected 6806, got 3802: While executing MergeTreeThread. (LOGICAL_ERROR)

### ISSUE THREAD

**Issue by eqinox76** [ClickHouse/ClickHouse#43441] opened 2022-11-21 12:48 UTC
**Describe what's wrong**

After updating to ClickHouse server version 22.11.1 revision 54460 we enabled the `allow_experimental_lightweight_delete` feature. Tests on our staging system looked very good.

Sadly we now see something that looks like a corrupt table
```
SELECT count(*)
FROM marketdata.ticks
WHERE (security_id = 1357) AND (venue_id = 12)

Query id: abbdc6b9-8832-4300-8bcf-5202b954b25d


0 rows in set. Elapsed: 0.022 sec.

Received exception from server (version 22.11.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Invalid number of rows in Chunk column UInt32 position 1: expected 6806, got 3802: While executing MergeTreeThread. (LOGICAL_ERROR)
```

Table Definition:
``` 
DESCRIBE TABLE marketdata.ticks

Query id: 7bdf9a8a-59fa-4456-8cc9-76d14ccc73d7

┌─name───────────┬─type─────────────────────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─────┬─ttl_expression─┐
│ security_id    │ UInt32                           │              │                    │         │                      │                │
│ venue_id       │ UInt16                           │              │                    │         │                      │                │
│ timestamp      │ DateTime64(3)                    │              │                    │         │ DoubleDelta, ZSTD(1) │                │
│ price          │ Float64                          │              │                    │         │ ZSTD(1)              │                │
│ volume         │ UInt64                           │              │                    │         │ T64, ZSTD(1)         │                │
│ exclude        │ UInt8                            │              │                    │         │                      │                │
│ condition_code │ LowCardinality(Nullable(String)) │              │                    │         │                      │                │
└────────────────┴──────────────────────────────────┴──────────────┴────────────────────┴─────────┴──────────────────────┴────────────────┘
```

Simpler queries are still working fine:
```
SELECT count(*)
FROM marketdata.ticks
WHERE security_id = 1357

Query id: d5ba38d6-a940-4bdd-939e-33b6b010ad03

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 0.014 sec. Processed 34.37 million rows, 36.19 MB (2.45 billion rows/s., 2.58 GB/s.)
```

**Does it reproduce on recent release?**

Yes.

**How to reproduce**

* 22.11.1 revision 54460 
* allow_experimental_lightweight_delete
* delete some data via the new `DELETE FROM ...` syntax
   * mutations: `UPDATE _row_exists = 0 WHERE security_id IN (1357, 895, 183, 74392, 1124, 86185, 9941, 105125)`
* query the table.

**Expected behavior**

Quick deletion of some data.

**Error Message**
```
2022.11.21 11:48:08.492130 [ 2167309 ] {5f8b701f-9739-4e5a-b03a-face19609dee} <Error> executeQuery: Code: 49. DB::Exception: Invalid number of rows in Chunk column UInt32 position 1: expected 6806, got 3802: While executing MergeTreeThread. (LOGICAL_ERROR) (version 22.11.1.1360 (official build)) (from [::ffff:192.168.138.25]:39282) (in query: select count(*) from marketdata.ticks where security_id = 1357 and venue_id = 12 and timestamp between '2018-07-02 01:00:00.000' and '2022-10-31 23:59:59.999'), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xda0553a in /usr/bin/clickhouse
1. DB::Chunk::checkNumRowsIsConsistent() @ 0x1433f5c3 in /usr/bin/clickhouse
2. DB::MergeTreeBaseSelectProcessor::generate() @ 0x146ce460 in /usr/bin/clickhouse
3. DB::ISource::tryGenerate() @ 0x14350455 in /usr/bin/clickhouse
4. DB::ISource::work() @ 0x1434ffe6 in /usr/bin/clickhouse
5. DB::ExecutionThreadContext::executeTask() @ 0x1436b5c6 in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1436007c in /usr/bin/clickhouse
7. ? @ 0x1436219d in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xdab9e96 in /usr/bin/clickhouse
9. ? @ 0xdabf001 in /usr/bin/clickhouse
10. ? @ 0x7f3afeb40609 in ?
11. __clone @ 0x7f3afea65163 in ?
```

**Comment by nickitat** [comment] 2022-11-21 15:42
duplicate of #40651

**Closed by nickitat** 2022-11-21 15:42 UTC
Labels: potential bug
