### ISSUE TITLE
Consuming big amount of memory when loading via ODBC bridge.

### ISSUE THREAD

**Issue by jhettler** [ClickHouse/ClickHouse#23778] opened 2021-04-29 21:14 UTC
> Question is, is it usual that it consumes such a big amount of memory?

No.

_Originally posted by @filimonov in https://github.com/ClickHouse/ClickHouse/issues/23719#issuecomment-829587018_

Hey guys,
I try to load the table from Snowflake via ODBC bridge to ClickHouse and in different topic I had a question above. If it's usual that the load of the table with 62 milion rows consumes 52 GB of RAM and the answer was no. 

So what could be wrong? 

I have cluster with one shard and 3 replicas - it's development environment so I have one server for Zookeepers and another for Clickhouses - 3 instances each.

There is unixODBC and Snowflake ODBC driver on the server installed and I try to do.

```sql
-- DETAIL VIEWS --
create or replace table snowflake.DETAIL_VIEWS (
DATE_VALID Datetime,
COMPANY_G2ID Int64,
VACANCY_G2ID Int64,
VACANCY_EXTERNAL_NAME	String,
VACANCY_INTERNAL_NAME	String,
RECRUITMENT_PROCESS_G2ID Int64,
RECRUITER_G2ID Int64,
FIRST_PUBLISHED_AT DateTime,
ACTIVE_FLAG Int8,
ALL_DETAIL_CNT Int8
)
ENGINE = ODBC('DSN=snowflake', 'T_STATS_OUT', 'DETAIL_VIEWS');


CREATE TABLE clickhouse.DETAIL_VIEWS (
DATE_VALID Datetime,
COMPANY_G2ID Int64,
VACANCY_G2ID Int64,
VACANCY_EXTERNAL_NAME	String,
VACANCY_INTERNAL_NAME	String,
RECRUITMENT_PROCESS_G2ID Int64,
RECRUITER_G2ID Int64,
FIRST_PUBLISHED_AT DateTime,
ACTIVE_FLAG Int8,
ALL_DETAIL_CNT Int8
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/01/DETAIL_VIEWS', 'test_replica3')
PARTITION BY toYYYYMM(DATE_VALID)
ORDER BY (DATE_VALID, COMPANY_G2ID);

INSERT INTO clickhouse.DETAIL_VIEWS select
DATE_VALID,
COMPANY_G2ID,
VACANCY_G2ID,
VACANCY_EXTERNAL_NAME,
VACANCY_INTERNAL_NAME,
RECRUITMENT_PROCESS_G2ID,
RECRUITER_G2ID,
FIRST_PUBLISHED_AT,
ACTIVE_FLAG,
ALL_DETAIL_CNT from snowflake.DETAIL_VIEWS;
```
Everything works fine, except when I start inserting the data from ODBC bridge table into clickhouse table it consumes around 52 GB of RAM.

What am I doing wrong?
Thanks!
Jakub

**Comment by filimonov** [comment] 2021-04-30 12:32
1) clickhouse version (odbc  bridge was reworker just a month ago, so try the latest clickhouse version)
2) share the list of OS processes and their RAM usage.
3) do `set send_logs_level='trace'` before the `INSERT ... SELECT ...` query and share the result.

**Comment by filimonov** [comment] 2021-04-30 14:17
Yes. So it is clickhouse-odbc process eats RAM (not clickhouse-server). 
It can be a fault of the odbc driver used (it is loaded in the clickhouse-odbc process), 

>  I am using the latest docker image server version ClickHouse server version 21.4.5 revision 54447.

Not new enough :)  https://github.com/ClickHouse/ClickHouse/pull/21972 - will be released in 21.5. :) 

Try to do the following
1) inside container run:
```
echo "deb https://repo.clickhouse.tech/deb/prestable/ main/" | tee /etc/apt/sources.list.d/clickhouse.list
apt-get update && apt-get upgrade 
```
2) restart container.

/cc @kssenii

**Comment by jhettler** [comment] 2021-04-30 15:02
Cool, I will try it later today and let you know! Really looking forward if it works properly, after spending some time asking our DevOps guys for more and more resources :)

Thanks so far!

**Comment by jhettler** [comment] 2021-04-30 22:27
The memory consumption looks much better, unfortunately I am back with the same issues where I came from.

```
clickhouse1 :) INSERT INTO clickhouse.DETAIL_VIEWS select　DATE_VALID,　COMPANY_G2ID,　VACANCY_G2ID,　VACANCY_EXTERNAL_NAME,　VACANCY_INTERNAL_NAME,　RECRUITMENT_PROCESS_G2ID,　RECRUITER_G2ID,　FIRST_PUBLISHED_AT,　ACTIVE_FLAG,　ALL_DETAIL_CNT from snowflake.DETAIL_VIEWS;

INSERT INTO clickhouse.DETAIL_VIEWS SELECT
    DATE_VALID,
    COMPANY_G2ID,
    VACANCY_G2ID,
    VACANCY_EXTERNAL_NAME,
    VACANCY_INTERNAL_NAME,
    RECRUITMENT_PROCESS_G2ID,
    RECRUITER_G2ID,
    FIRST_PUBLISHED_AT,
    ACTIVE_FLAG,
    ALL_DETAIL_CNT
FROM snowflake.DETAIL_VIEWS

Query id: b897dfb7-a56d-4606-b8af-1d8bc7cdcad3

← Progress: 27.26 million rows, 3.52 GB (55.45 thousand rows/s., 7.15 MB/s.)
0 rows in set. Elapsed: 494.800 sec. Processed 27.26 million rows, 3.52 GB (55.10 thousand rows/s., 7.11 MB/s.)

Received exception from server (version 21.5.2):
Code: 33. DB::Exception: Received from clickhouse1:9000. DB::Exception: Cannot read all data. Bytes read: 18. Bytes expected: 53.: (at row 27262175)
: While executing ODBC.
```
stack trace
```
[clickhouse1] 2021.04.30 22:23:37.235181 [ 50 ] {0aeec32f-2fab-4abd-8b86-92a62e2aae21} <Error> executeQuery: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 18. Bytes expected: 53.: (at row 27262175)
: While executing ODBC (version 21.5.2.25 (official build)) (from 172.26.0.5:55944) (in query: INSERT INTO clickhouse.DETAIL_VIEWS select DATE_VALID, COMPANY_G2ID, VACANCY_G2ID, VACANCY_EXTERNAL_NAME, VACANCY_INTERNAL_NAME, RECRUITMENT_PROCESS_G2ID, RECRUITER_G2ID, FIRST_PUBLISHED_AT, ACTIVE_FLAG, ALL_DETAIL_CNT from snowflake.DETAIL_VIEWS;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x87977ba in /usr/bin/clickhouse
1. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0x87d280d in /usr/bin/clickhouse
2. DB::SerializationString::deserializeBinary(DB::IColumn&, DB::ReadBuffer&) const @ 0xedb03de in /usr/bin/clickhouse
3. DB::BinaryRowInputFormat::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0xfe42921 in /usr/bin/clickhouse
4. DB::IRowInputFormat::generate() @ 0xfe381e8 in /usr/bin/clickhouse
5. DB::ISource::tryGenerate() @ 0xfdc7115 in /usr/bin/clickhouse
6. DB::ISource::work() @ 0xfdc6cfa in /usr/bin/clickhouse
7. DB::InputStreamFromInputFormat::readImpl() @ 0xd5a761f in /usr/bin/clickhouse
8. DB::IBlockInputStream::read() @ 0xecc0cf5 in /usr/bin/clickhouse
9. DB::AddingDefaultsBlockInputStream::readImpl() @ 0xecb8024 in /usr/bin/clickhouse
10. DB::IBlockInputStream::read() @ 0xecc0cf5 in /usr/bin/clickhouse
11. ? @ 0xf90f373 in /usr/bin/clickhouse
12. DB::ISource::tryGenerate() @ 0xfdc7115 in /usr/bin/clickhouse
13. DB::ISource::work() @ 0xfdc6cfa in /usr/bin/clickhouse
14. DB::SourceWithProgress::work() @ 0xff77b2a in /usr/bin/clickhouse
15. ? @ 0xfe00cdd in /usr/bin/clickhouse
16. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xfdfd871 in /usr/bin/clickhouse
17. DB::PipelineExecutor::executeImpl(unsigned long) @ 0xfdfb8ad in /usr/bin/clickhouse
18. DB::PipelineExecutor::execute(unsigned long) @ 0xfdfb68d in /usr/bin/clickhouse
19. ? @ 0xfe0891f in /usr/bin/clickhouse
20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x87d7a3f in /usr/bin/clickhouse
21. ? @ 0x87db643 in /usr/bin/clickhouse
22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
23. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so


0 rows in set. Elapsed: 497.051 sec. Processed 27.26 million rows, 3.52 GB (54.85 thousand rows/s., 7.07 MB/s.)

Received exception from server (version 21.5.2):
Code: 33. DB::Exception: Received from clickhouse1:9000. DB::Exception: Cannot read all data. Bytes read: 18. Bytes expected: 53.: (at row 27262175)
: While executing ODBC.
```

Any ideas? Thanks!

**Comment by filimonov** [comment] 2021-05-01 05:29
Hm. Can you also try to enable odbc bridge logs like here:
https://github.com/ClickHouse/ClickHouse/blob/9f5cd35a6963cc556a51218b46b0754dcac7306a/tests/integration/test_odbc_interaction/configs/odbc_logging.xml

**Comment by jhettler** [comment] 2021-05-01 17:45
Hi, 

clikhouse-odbc-bridge.log
```
2021.05.01 17:32:14.367364 [ 102 ] {} <Information> : Starting ClickHouse 21.5.2.25 with revision 54450, , PID 102
2021.05.01 17:32:14.380166 [ 102 ] {} <Information> SentryWriter: Sending crash reports is disabled
2021.05.01 17:32:14.380324 [ 102 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2021.05.01 17:32:14.382017 [ 102 ] {} <Debug> ApplicationStartup: Initializing subsystem: Logging Subsystem
2021.05.01 17:32:14.384605 [ 102 ] {} <Information> ApplicationStartup: Starting up ODBCBridge on host: 127.0.0.1, port: 9018
2021.05.01 17:32:14.386189 [ 102 ] {} <Information> ApplicationStartup: Listening http://127.0.0.1:9018
2021.05.01 17:32:14.410829 [ 104 ] {} <Trace> ODBCRequestHandlerFactory-factory: Request URI: /ping
2021.05.01 17:32:14.413465 [ 105 ] {} <Trace> ODBCRequestHandlerFactory-factory: Request URI: /ping
2021.05.01 17:32:14.413934 [ 105 ] {} <Trace> ODBCRequestHandlerFactory-factory: Request URI: /identifier_quote?connection_string=DSN%3Dsnowflake
2021.05.01 17:32:14.414049 [ 105 ] {} <Trace> IdentifierQuoteHandler: Request URI: /identifier_quote?connection_string=DSN%3Dsnowflake
2021.05.01 17:33:12.218312 [ 105 ] {} <Trace> ODBCRequestHandlerFactory-factory: Request URI: /?connection_string=DSN%3Dsnowflake&max_block_size=1048545
2021.05.01 17:33:12.242208 [ 105 ] {} <Trace> ODBCHandler: Request URI: /?connection_string=DSN%3Dsnowflake&max_block_size=1048545
2021.05.01 17:33:12.242283 [ 105 ] {} <Trace> ODBCHandler: Connection string: 'DSN=snowflake'
2021.05.01 17:33:12.243862 [ 105 ] {} <Trace> ODBCHandler: Query: SELECT "DATE_VALID", "COMPANY_G2ID", "VACANCY_G2ID", "VACANCY_EXTERNAL_NAME", "VACANCY_INTERNAL_NAME", "RECRUITMENT_PROCESS_G2ID", "RECRUITER_G2ID", "FIRST_PUBLISHED_AT", "ACTIVE_FLAG", "ALL_DETAIL_CNT" FROM "TEAMIO_STATS_OUT"."DETAIL_VIEWS"
2021.05.01 17:40:53.020517 [ 105 ] {} <Error> ODBCHandler: std::exception. Code: 1001, type: std::range_error, e.what() = from_string argument out of range, Stack trace (when copying this message, always include the lines below):

0. ? @ 0x3a245d3 in /usr/bin/clickhouse-odbc-bridge
1. ? @ 0x2b89a82 in /usr/bin/clickhouse-odbc-bridge
2. ? @ 0x2b8926d in /usr/bin/clickhouse-odbc-bridge
3. ? @ 0x2bd683c in /usr/bin/clickhouse-odbc-bridge
4. ? @ 0x2be5cad in /usr/bin/clickhouse-odbc-bridge
5. ? @ 0x2b82c3b in /usr/bin/clickhouse-odbc-bridge
6. ? @ 0x39c1570 in /usr/bin/clickhouse-odbc-bridge
7. ? @ 0x52b996f in /usr/bin/clickhouse-odbc-bridge
8. ? @ 0x52bb3da in /usr/bin/clickhouse-odbc-bridge
9. ? @ 0x5f4bd39 in ?
10. ? @ 0x5f487aa in ?
11. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
12. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.5.2.25 (official build))
```
nothing special in other log files

**Comment by filimonov** [comment] 2021-05-03 06:40
@jhettler, your help is very useful, thanks! :+1:

It seems like we have 2 issues here:

1) exception inside clickhouse-odbc-bridge during sending the data. @kssenii can you try to understand what was the reason of that exception? here is the stack trace:

```
root@a8db08d64b81:/# addr2line -afiCe /usr/bin/clickhouse-odbc-bridge 0x3a245d3 0x2b89a82 0x2b8926d 0x2bd683c 0x2be5cad 0x2b82c3b 0x39c1570 0x52b996f 0x52bb3da 0x5f4bd39 0x5f487aa 
0x0000000003a245d3
range_error
./obj-x86_64-linux-gnu/../contrib/libcxx/include/stdexcept:178
auto nanodbc::detail::from_string<short, 0>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, short)
./obj-x86_64-linux-gnu/../contrib/nanodbc/nanodbc/nanodbc.cpp:3393
short nanodbc::from_string<short>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
./obj-x86_64-linux-gnu/../contrib/nanodbc/nanodbc/nanodbc.cpp:3401
void nanodbc::result::result_impl::get_ref_from_string_column<short, 0>(short, short&) const
./obj-x86_64-linux-gnu/../contrib/nanodbc/nanodbc/nanodbc.cpp:3428
void nanodbc::result::result_impl::get_ref_impl<short, 0>(short, short&) const
./obj-x86_64-linux-gnu/../contrib/nanodbc/nanodbc/nanodbc.cpp:3473
0x0000000002b89a82
short nanodbc::result::result_impl::get<short>(short) const
./obj-x86_64-linux-gnu/../contrib/nanodbc/nanodbc/nanodbc.cpp:2685
short nanodbc::result::get<short>(short) const
./obj-x86_64-linux-gnu/../contrib/nanodbc/nanodbc/nanodbc.cpp:5270
DB::ODBCBlockInputStream::insertValue(DB::IColumn&, std::__1::shared_ptr<DB::IDataType const>, DB::ExternalResultDescription::ValueType, nanodbc::result&, unsigned long)
./obj-x86_64-linux-gnu/../programs/odbc-bridge/ODBCBlockInputStream.cpp:101
0x0000000002b8926d
addr2line: DWARF error: mangled line number section (bad file number)
addr2line: DWARF error: invalid abstract instance DIE ref
DB::ODBCBlockInputStream::readImpl()
??:?
0x0000000002bd683c
memcpy
??:?
0x0000000002be5cad
std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >::size() const
./obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:658
DB::Block::columns() const
./obj-x86_64-linux-gnu/../src/Core/Block.h:100
DB::Block::operator bool() const
./obj-x86_64-linux-gnu/../src/Core/Block.h:111
void DB::copyDataImpl<DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*)::$_1&, void (&)(DB::Block const&)>(DB::IBlockInputStream&, DB::IBlockOutputStream&, DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*)::$_1&, void (&)(DB::Block const&))
./obj-x86_64-linux-gnu/../src/DataStreams/copyData.cpp:26
DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::__1::atomic<bool>*)
./obj-x86_64-linux-gnu/../src/DataStreams/copyData.cpp:72
0x0000000002b82c3b
~ODBCBlockInputStream
./obj-x86_64-linux-gnu/../programs/odbc-bridge/ODBCBlockInputStream.h:13
DB::ODBCHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&)
./obj-x86_64-linux-gnu/../programs/odbc-bridge/MainHandler.cpp:153
0x00000000039c1570
Poco::AutoPtr<Poco::Net::HTTPServerParams>::operator->()
./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/AutoPtr.h:215
DB::HTTPServerConnection::run()
./obj-x86_64-linux-gnu/../src/Server/HTTP/HTTPServerConnection.cpp:49
0x00000000052b996f
Poco::Net::TCPServerConnection::start()
./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57
0x00000000052bb3da
Poco::Net::TCPServerDispatcher::run()
./obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:114
0x0000000005f4bd39
ScopedLock
./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/ScopedLock.h:36
Poco::PooledThread::run()
./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:213
0x0000000005f487aa
Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156
Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
./obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:208
Poco::ThreadImpl::runnableEntry(void*)
./obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:360
```

2. When an exception happens in the middle of sending the data - it seems odbc-brigde just outputs the exception text in the middle of the RawBinary stream, so clickhouse for sure can not process that situation currently. It is a general problem of the HTTP protocol, maybe some architectural change is needed here - like changing the protocol, or introduce some kind of RawBinaryFramed format.

**Comment by filimonov** [comment] 2021-05-03 06:59
@jhettler 
1) please check - the moment of exception how much ram do `clickhouse-odbc-bridge` use? 
2) There are chances that [this simple workaround](https://github.com/ClickHouse/ClickHouse/issues/23719#issuecomment-831057420) will help you.

**Comment by jhettler** [comment] 2021-05-03 07:13
I will check this around 10.

**Comment by jhettler** [comment] 2021-05-04 14:39
I am sorry, a bit late, but here it is ...

It starts with network usage - I expect that this is data loading from Snowflake to Clikhouse server

![image](https://user-images.githubusercontent.com/6342027/117020461-c1e6e900-acf6-11eb-9941-9d425f4b6df2.png)

but there is nearly no usage of memory (this is last 15 minutes windows around INSERT statement)

![image](https://user-images.githubusercontent.com/6342027/117020914-2609ad00-acf7-11eb-9053-56cbbe0bfe97.png)

**Comment by jhettler** [comment] 2021-05-13 09:24
Hi everyone, just a kind question, do we have any news on this?
Thank you and have a nice day!

**Comment by PhantomPhreak** [comment] 2021-06-21 10:32
I have similar problem with `clickhouse-odbc-bridge` - it consumes a lot of RAM and it can't be controlled.

When user running
```select * from <mysql_table> limit 100```, where `<mysql_table>` is a table, connected via `clickhouse-odbc-bridge` having 100GB data in it,  ClickHouse actually execute `select * from <mysql_table>`, and seems like all the data cached in a memory of `clickhouse-odbc-bridge` process, which is consuming 100GB ram and triggering OOM on the server.
I tried to apply some query complexity rules for such queries, like `max_network_bytes` or `max_bytes_to_read` - it doesn't work.
It may be possible to spawn `clickhouse-odbc-bridge` manually (via systemd, as daemon) with mem limits defined, but there are no way to disable spawning this process by ClickHouse server, which is possibly racy: ClickHouse may spawn it's own process without any limits set, when "manually" spawned `clickhouse-odbc-bridge` is dead.

Is there any way to apply query complexity settings to the queries, executed via `clickhouse-odbc-bridge`? Or any way to set a simple safety limits for it, such as memory consumption?
CkickHouse v21.3.9.1

Thanks

**Comment by alexey-milovidov** [comment] 2021-06-21 10:50
Fixed in https://github.com/ClickHouse/ClickHouse/pull/25280, will be released in version 21.7.

**Comment by alexey-milovidov** [comment] 2021-06-21 10:51
@PhantomPhreak Also you should connect to MySQL with `mysql` table function instead of `odbc`.

**Closed by alexey-milovidov** 2021-06-21 10:50 UTC
Labels: comp-odbc, memory

**Comment by PhantomPhreak** [comment] 2021-06-21 10:55
@alexey-milovidov yes, we're switched to this approach after having OOM problem caused by odbc-bridge.
 Unfortunately, with MySQL table engine everybody can obtain a mysql host, username and password by running "SHOW CREATE TABLE" clause. Thus, we tried to use ODBC to hide MySQL's credentials from users.

**Comment by hdhoang** [comment] 2021-06-22 03:31
FWIW we also used ODBC bridge for TLS+mysql protocol transport, but now we can connect `mysql` table securely using another way.

**Comment by xjewer** [comment] 2021-08-24 00:08
seems related https://github.com/nanodbc/nanodbc/pull/269 ?
