### ISSUE TITLE
Implement equalNullSafe function which will returns true instead of null when inputs are null 

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#59321] opened 2024-01-29 08:32 UTC
> (you don't have to strictly follow this form)

**Use case**

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by UnamedRus** [comment] 2024-01-29 08:53
> isNotDistinctFrom ?

implementation is basically, tuple(a.id) = tuple(b.id)

```
WITH x AS
    (
        SELECT arrayJoin([NULL, 1]) AS id
    )
SELECT *
FROM x AS a
INNER JOIN x AS b ON isNotDistinctFrom(a.id, b.id)

Query id: 6e839f96-d3ef-4a7c-bfe4-61331e846f78

┌───id─┬─b.id─┐
│ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │
│    1 │    1 │
└──────┴──────┘

```

**Comment by taiyang-li** [comment] 2024-01-29 09:02
@UnamedRus It seems exactly what I need. But current isNotDistinctFrom doesn't support being executed as a regular expression in SELECT list. Previous pr: https://github.com/ClickHouse/ClickHouse/pull/53755

**Comment by UnamedRus** [comment] 2024-01-29 09:05
Yes, this part of pr

>  Implement function to support execution of operator as a regular expression in SELECT list

**Comment by taiyang-li** [comment] 2024-01-29 09:09
I'd like to finish it. It seems not difficult.

**Comment by alexey-milovidov** [comment] 2024-01-30 07:45
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/3889

**Closed by alexey-milovidov** 2024-01-30 07:45 UTC
Labels: feature
