### ISSUE TITLE
(Experimental Annoy Index) LOGICAL_ERROR while reading from table with annoy index 

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#62468] opened 2024-04-10 02:22 UTC
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

```
SET allow_experimental_annoy_index = 1;

CREATE TABLE tab__fuzz_17 (`id` UInt8, `vec` Array(Float32), INDEX idx vec TYPE annoy GRANULARITY 100000000) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity_bytes = 0, min_rows_for_wide_part = 0, min_bytes_for_wide_part = 0, index_granularity = 8192;

INSERT INTO tab__fuzz_17 SELECT number, [toFloat32(number), 0.] FROM numbers(10000);

WITH  [1., 0.] AS reference_vec SELECT L2Distance(vec, reference_vec) FROM tab__fuzz_17 PREWHERE materialize(toLowCardinality(12)) ORDER BY L2Distance(vec, reference_vec) DESC NULLS FIRST LIMIT 1048577;


Received exception from server (version 24.3.2):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: RangeReader read 10000 rows, but 16384 expected.: While executing MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder). (LOGICAL_ERROR)
(query: WITH  [1., 0.] AS reference_vec SELECT L2Distance(vec, reference_vec) FROM tab__fuzz_17 PREWHERE materialize(toLowCardinality(12)) ORDER BY L2Distance(vec, reference_vec) DESC NULLS FIRST LIMIT 1048577;)
```

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

https://fiddle.clickhouse.com/df8c3bba-de32-4977-adaf-e02fd341e242

**Does it reproduce on the most recent release?**

Yes

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Comment by novikd** [comment] 2024-04-11 17:04
Duplicate of #56640.

**Closed** 2024-04-11 17:04 UTC
Labels: bug, experimental feature
