### ISSUE TITLE
Very slow on implicit JOIN at TPCH benchmark

### ISSUE THREAD

**Issue by auxten** [ClickHouse/ClickHouse#52794] opened 2023-07-31 04:41 UTC
Some benchmarks like TPCH_SF05 and TPCH_SF0.1 got bad results on chDB (also for clickhouse-local 23.6). After some investigation. I find it mainly occurred in "implicit JOIN" cases.

Like:

```sql
select
sum(l_extendedprice* (1 - l_discount)) as revenue
    from file("./0.1/lineitem/*.parquet") as line,
    file("./0.1/part/*.parquet") as part
where ( p_partkey = l_partkey
        and p_brand = 'Brand#12'
        and p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
        and l_quantity >= 1 and l_quantity <= 1 + 10
        and p_size between 1 and 5
        and l_shipmode in ('AIR', 'AIR REG')
        and l_shipinstruct = 'DELIVER IN PERSON'
    ) or ( p_partkey = l_partkey
        and p_brand = 'Brand#23'
        and p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
        and l_quantity >= 10 and l_quantity <= 10 + 10
        and p_size between 1 and 10
        and l_shipmode in ('AIR', 'AIR REG')
        and l_shipinstruct = 'DELIVER IN PERSON'
    ) or ( p_partkey = l_partkey
        and p_brand = 'Brand#34'
        and p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
        and l_quantity >= 20 and l_quantity <= 20 + 10
        and p_size between 1 and 15
        and l_shipmode in ('AIR', 'AIR REG')
        and l_shipinstruct = 'DELIVER IN PERSON'
    );
```
It takes about 100s on a 100 cores host, but little modification making JOIN explicit turns out 0.3s

```sql
select
--Query19
sum(l_extendedprice* (1 - l_discount)) as revenue
from 
file("./0.1/lineitem/*.parquet") as line
join
file("./0.1/part/*.parquet") as part
ON p_partkey = l_partkey
where ( 
        p_brand = 'Brand#12'
        and p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
        and l_quantity >= 1 and l_quantity <= 1 + 10
        and p_size between 1 and 5
        and l_shipmode in ('AIR', 'AIR REG')
        and l_shipinstruct = 'DELIVER IN PERSON'
    ) or ( p_partkey = l_partkey
        and p_brand = 'Brand#23'
        and p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
        and l_quantity >= 10 and l_quantity <= 10 + 10
        and p_size between 1 and 10
        and l_shipmode in ('AIR', 'AIR REG')
        and l_shipinstruct = 'DELIVER IN PERSON'
    ) or ( p_partkey = l_partkey
        and p_brand = 'Brand#34'
        and p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
        and l_quantity >= 20 and l_quantity <= 20 + 10
        and p_size between 1 and 15
        and l_shipmode in ('AIR', 'AIR REG')
        and l_shipinstruct = 'DELIVER IN PERSON'
    );
```

There is chDB Colabs demo the data preparation and benchmark:
- https://colab.research.google.com/drive/1MTSBp9qbki6-uBNM2HH3M2Fc-qFOSSWl#scrollTo=j0FRDEVybRXx
- https://colab.research.google.com/drive/1OhuO2Lyey3IEoT-Tg_kmBRd72DvRVW0R#scrollTo=yhK-lBCrH2tZ

Related issue on chDB:
- https://github.com/chdb-io/chdb/issues/73
- https://github.com/chdb-io/chdb/issues/76

**Comment by den-crane** [comment] 2023-07-31 12:35
it's expected behaviour (known issue).
not actionable.

**Comment by vdimir** [comment] 2023-08-03 10:45
We need to have more heuristics in `CrossToInnerJoinPass`. E.g. for this case to identify the common sub-expression on WHERE section and then apply the distributive law.

**Comment by rschu1ze** [comment] 2024-11-04 10:08
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/70802

**Closed by rschu1ze** 2024-11-04 10:08 UTC
Labels: performance, comp-joins
