### ISSUE TITLE
00992_system_parts_race_condition_zookeeper_long

### ISSUE THREAD

**Issue by serxa** [ClickHouse/ClickHouse#48665] opened 2023-04-11 15:51 UTC
Flaky test [Report](https://s3.amazonaws.com/clickhouse-test-reports/48516/54d7a412ec85fdedaf0ac2ce4ebdce05d0026868/stateless_tests__release_.html)

Not often but it fails [Link](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBMSUtFICclMDA5OTJfc3lzdGVtX3BhcnRzX3JhY2VfY29uZGl0aW9uX3pvb2tlZXBlcl9sb25nJScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBkZXNjLCBjaGVja19uYW1lLCB0ZXN0X25hbWU=)

**Comment by tavplubix** [comment] 2023-04-11 18:25
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/43946

**Closed by tavplubix** 2023-04-11 18:25 UTC
Labels: flaky test
