### ISSUE TITLE
Consistent segfault during S3 backup on ECS

### ISSUE THREAD

**Issue by gusostow** [ClickHouse/ClickHouse#49969] opened 2023-05-17 19:36 UTC
> You have to provide the following information whenever possible.

I am running clickhouse on ECS with S3 environment credentials enabled. I get a segfault every time I try to backup a table without explicitly setting credentials in the backup command. I tried multiple methods of sourcing credential from the environment, but it segfaults no matter what.

I'm sure it's the ECS credential process because I was able to reproduce the segfault in a manually started container on the same container instance by connecting to the ECS docker network and setting `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/v2/credentials/6c78911f-a27d-4969-b6fe-03d5e830b028`.

**Does it reproduce on recent release?**
.
I am running `docker.io/clickhouse/clickhouse-server:23.4.2`

**Enable crash reporting**

This is a reliably produced issue so I won't enable this unless specifically requested.

**How to reproduce**

* Which ClickHouse server version to use: 23.4.2

* Which interface to use, if matters: I'm using clickhouse-client

* Non-default settings, if any

```
<clickhouse>
    <s3>
    <use_environment_credentials>true</use_environment_credentials>
    </s3>
     <!-- Listen wildcard address to allow accepting connections from other containers and host network. -->
    <listen_host>::</listen_host>
    <listen_host>0.0.0.0</listen_host>
    <listen_try>1</listen_try>

    <!--
    <logger>
        <console>1</console>
    </logger>
    -->

</clickhouse>
```
* Queries to run that lead to unexpected result

```
BACKUP DATABASE default
TO S3('https://bucket.s3.amazonaws.com/prefix')
```

**Expected behavior**

Not to crash.

**Error message and/or stacktrace**

```
[93b6418fc3d4] 2023.05.17 19:22:29.369822 [ 322 ] <Fatal> BaseDaemon: ########################################
[93b6418fc3d4] 2023.05.17 19:22:29.369908 [ 322 ] <Fatal> BaseDaemon: (version 23.4.2.11 (official build), build id: CB00FF1352DDBA096F95C86E890588C10074E9A1) (from thread 47) (query_id: 88736b65-9a3d-4b9b-99a5-b5c85d7e8156) (query: BACKUP DATABASE default TO S3('https://bucket.s3.amazonaws.com/prefix')) Received signal Segmentation fault (11)
[93b6418fc3d4] 2023.05.17 19:22:29.369932 [ 322 ] <Fatal> BaseDaemon: Address: 0x45bd6e0. Access: read. Attempted access has violated the permissions assigned to the memory area.
[93b6418fc3d4] 2023.05.17 19:22:29.369952 [ 322 ] <Fatal> BaseDaemon: Stack trace: 0xe6117d1 0x7f2aada4c520
[93b6418fc3d4] 2023.05.17 19:22:29.370003 [ 322 ] <Fatal> BaseDaemon: 0. ? @ 0xe6117d1 in /usr/bin/clickhouse
[93b6418fc3d4] 2023.05.17 19:22:29.370028 [ 322 ] <Fatal> BaseDaemon: 1. ? @ 0x7f2aada4c520 in ?
[93b6418fc3d4] 2023.05.17 19:22:29.648768 [ 322 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 44E5DAC9EB00A923CBC1231B0DC242A8)
```

**Additional context**

**Comment by alexey-milovidov** [comment] 2023-05-17 20:04
Looks like a duplicate of #33771

**Comment by alexey-milovidov** [comment] 2023-07-31 07:07
Let's continue in https://github.com/ClickHouse/ClickHouse/issues/33771

**Closed by alexey-milovidov** 2023-07-31 07:07 UTC
Labels: duplicate, potential bug
