### ISSUE TITLE
Need to disable optimize_move_to_prewhere if query has FINAL.

### ISSUE THREAD

**Issue by m1khal3v** [ClickHouse/ClickHouse#8684] opened 2020-01-16 12:04 UTC
On version 19.17.4, queries return different results, on version 19.15.2 everything works fine. The engines of both tables - ReplicatedReplacingMergeTree([updated_at])

```
SELECT g.item_id                               
FROM gmc_item_distributed AS g                
FINAL                                         
LEFT JOIN                                     
(                                             
    SELECT                                    
       item_id AS i_item_id             
     FROM item_distributed AS is               
    FINAL                                     
    WHERE toDate(updated_at) >= toDate('2020-01-02') 
) AS i ON g.item_id = i.i_item_id                   
WHERE (i.i_item_id = 0) AND (g.flag = 1)            
GROUP BY g.item_id  
```

```
SELECT g.item_id                               
FROM gmc_item_distributed AS g                
FINAL                                         
LEFT JOIN                                     
(                                             
    SELECT                                    
        item_id AS i_item_id             
    FROM item_distributed AS is               
    FINAL                                     
    WHERE toDate(updated_at) < toDate('2020-01-02') 
) AS i ON g.item_id = i.i_item_id                   
WHERE (i.i_item_id <> 0) AND (g.flag = 1)            
GROUP BY g.item_id 
```

**Comment by aslojno** [comment] 2020-01-16 12:05
On version 19.17.4, in the first case, 0 rows are returned

**Comment by 4ertus2** [comment] 2020-01-16 13:54
It's very hard to say anything without data. Could you make a reproducable test with sample data?

**Comment by aslojno** [comment] 2020-01-20 13:45
The problem is not in the version. Transferred all the data to version 19.17.4 and got absolutely identical behavior. Before that, there was a different data set, but the structure was identical. However, it turned out that the problem is reproduced only when specific two tables are joined, that is, if you replace item_distributed with shipping_distributed, the result will be normal. 

We tried to execute several more queries, for example, these two return the same result - one row

```SELECT DISTINCT g.item_id                                                           
FROM                                                                                
(                                                                                   
    SELECT gs.item_id                                                               
    FROM gmc_item_distributed AS gs                                                 
    FINAL                                                                           
    WHERE gs.flag = 1                                                               
) AS g                                                                              
INNER JOIN                                                                          
(                                                                                   
    SELECT                                                                          
        is.item_id AS item_id_in_items,                                             
        is.updated_at AS isua                                                       
    FROM item_distributed AS is                                                     
    FINAL                                                                           
) AS i ON g.item_id = i.item_id_in_items                                         
WHERE (i.isua < toDateTime('2020-01-02 00:00:00')) AND (g.item_id = 122478784742)   

SELECT DISTINCT g.item_id                                                           
FROM                                                                                
(                                                                                   
    SELECT gs.item_id                                                               
    FROM gmc_item_distributed AS gs                                                 
    FINAL                                                                           
    WHERE gs.flag = 1                                                               
) AS g                                                                              
INNER JOIN                                                                          
(                                                                                   
    SELECT                                                                          
        is.item_id AS item_id_in_items,                                             
        is.updated_at AS isua                                                       
    FROM item_distributed AS is                                                     
    FINAL                                                                           
) AS i ON g.item_id = i.item_id_in_items                                         
WHERE (i.isua > toDateTime('2020-01-02 00:00:00')) AND (g.item_id = 122478784742)```

while we have this

```SELECT                                                               
    item_id,                                                         
    updated_at                                                       
FROM item_distributed                                                
FINAL                                                                
WHERE item_id = 122478784742                                         
                                                                     
┌──────item_id─┬──────────updated_at─┐                               
│ 122478784742 │ 2020-01-09 16:26:28 │                               
└──────────────┴─────────────────────┘                               
```

and this

```SELECT                                                                              
    item_id,                                                                        
    updated_at                                                                      
FROM item_distributed                                                               
WHERE item_id = 122478784742                                                        
                                                                                    
┌──────item_id─┬──────────updated_at─┐                                              
│ 122478784742 │ 2020-01-09 16:26:28 │                                              
└──────────────┴─────────────────────┘                                              
┌──────item_id─┬──────────updated_at─┐                                              
│ 122478784742 │ 2019-12-19 11:11:08 │                                              
└──────────────┴─────────────────────┘                                              
```

Unfortunately, I can’t imagine how we can make a test data set, because we have several tens of gigabytes of data distributed over 3 shards with 2 nodes each and the problem is reproduced on this data set

**Comment by 4ertus2** [comment] 2020-01-20 15:14
```
SELECT                                                                              
    item_id,                                                                        
    updated_at                                                                      
FROM item_distributed                                                               
WHERE item_id = 122478784742
```
It's OK to have two results here in several cases:
- ReplacingMergeTree is not optimized (not fully merged), so it has 2 records with same `item_id`
- records with the same `item_id` are in different partitions and wouldn't be merged ever
- recods with same `item_id` present on different nodes

There's nothing strange here. But it's interesting which case do you have?

I think the problem is we first select data using predicate `i.isua < toDateTime('2020-01-02 00:00:00')` and only then apply FINAL. So FINAL is not applyed correctly. Could you check in log what query do you have on nodes (distributed table generates them to select data from nodes)? I think they would have predicates to reduce selected rows.

**Comment by aslojno** [comment] 2020-01-21 09:50
The second option is our case, because we have partitioning by toRelativeWeekNum(updated_at). The shard key in all tables with column item_id is (item_id % 3), so the same item_id will be on the same shard. In the logs we have this

```
executeQuery: (from *) SELECT DISTINCT g.item_id FROM (SELECT gs.item_id FROM gmc_item_distributed AS gs FINAL WHERE gs.flag = 1) AS g INNER JOIN (SELECT is.item_id AS item_id_in_items, is.updated_at AS isua FROM item_distributed AS is FINAL) AS i ON g.item_id = i.item_id_in_items WHERE (i.isua > toDateTime('2020-01-02 00:00:00')) AND (g.item_id = 122478784742)
executeQuery: Query pipeline:
Expression
 Distinct
  CreatingSets
   Lazy
   Union
    Distinct × 2
     Expression
      Filter
       Expression
        Expression
         Remote
    Distinct
     Expression
      Filter
       Expression
        Expression
         Expression
          Filter
           ReplacingSorted
            Expression × 15
             MergeTree
```

**Comment by aslojno** [comment] 2020-01-21 10:22
The logs from the previous comment relate to the node on which the request was made. On the other node we see the following
```
SELECT item_id FROM default.gmc_item AS gs FINAL WHERE (item_id = 122478784742) AND (flag = 1)
Expression
 Filter
  ReplacingSorted
   Expression × 23
    MergeTree


SELECT item_id AS item_id_in_items, updated_at AS isua FROM default.item AS is FINAL WHERE isua > toDateTime('2020-01-02 00:00:00')
Expression
 Filter
  ReplacingSorted
   Expression × 10
    MergeTree
```

**Comment by 4ertus2** [comment] 2020-01-21 10:35
OK. And what's the result of the query
```
SELECT item_id AS item_id_in_items, updated_at AS isua FROM default.item AS is FINAL WHERE isua > toDateTime('2020-01-02 00:00:00')
```
if you run it manually. Would it possible to get old value (that should be overriden by FINAL) with some WHERE predicate?

**Comment by aslojno** [comment] 2020-01-21 10:39
Yes, it's possible
```
SELECT 
    item_id AS item_id_in_items, 
    updated_at AS isua
FROM default.item AS is
FINAL
WHERE (isua < toDateTime('2020-01-02 00:00:00')) AND (item_id = 122478784742)

┌─item_id_in_items─┬────────────────isua─┐
│     122478784742 │ 2019-12-19 11:11:08 │
└──────────────────┴─────────────────────┘           

SELECT 
    item_id AS item_id_in_items, 
    updated_at AS isua
FROM default.item AS is
FINAL
WHERE (isua > toDateTime('2020-01-02 00:00:00')) AND (item_id = 122478784742)

┌─item_id_in_items─┬────────────────isua─┐
│     122478784742 │ 2020-01-09 16:26:28 │
└──────────────────┴─────────────────────┘
```

**Comment by alexey-milovidov** [comment] 2020-01-21 11:11
We have to disable PREWHERE optimization if FINAL is present.

PS. Internal discussion:
```
Artem Zuikov, [21.01.20 13:42]
вот тут у нас ожидаемое поведение в последнем запросе (преликат из WHERE применяется раньше FINAL) или баг? https://github.com/ClickHouse/ClickHouse/issues/8684

Alexey Milovidov, [21.01.20 14:10]
[In reply to Artem Zuikov]
Такое поведение было раньше всегда, потому что оно корректно работает с CollapsingMergeTree, пока не включаешь Sign в WHERE. Для Replacing - понятно, что сложнее. Для исправления придётся отключить перенос в PREWHERE при наличии FINAL. Тривиально.
```

**Comment by 4ertus2** [comment] 2020-01-21 11:25
@aslojno, you may try to make queries with `optimize_move_to_prewhere = 0`

**Comment by aslojno** [comment] 2020-01-21 13:23
We tried to register the setting in the yandex -> profiles -> default block, tried to tie it to the session using the set, but this did not give any result. But also we tried to transfer all the data from the partitioned table to the identical one without partitioning and this helped due to the fact that the data merged.

**Comment by alexey-milovidov** [comment] 2021-07-01 23:11
This task is worth doing, but I'm slightly afraid that someone will argue about performance degradations in some cases.
Let's introduce another setting `optimize_move_to_prewhere_if_final`, zero by default.

If query has FINAL, the optimization "move to PREWHERE" will be enabled only if both `optimize_move_to_prewhere` and `optimize_move_to_prewhere_if_final` are enabled.

So, it will be safe by default, but someone may enable `optimize_move_to_prewhere_if_final` to get previous behaviour.

**Closed** 2021-07-04 08:33 UTC
Labels: bug, easy task
