### ISSUE TITLE
test_storage_hdfs LeakSanitizer warning

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#57854] opened 2023-12-14 09:32 UTC
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/57749/2a0a5f755c166604ca67901559afa50261556222/integration_tests__asan__[3_4]/integration_run_parallel5_0.log

**Error message and/or stacktrace**
https://pastila.nl/?000e8c37/424f3d30d8d41efc14a61becb1909043#gkH+5S334K5LkrtsWYXdIQ==

**Comment by tavplubix** [comment] 2023-12-14 16:20
Probably was introduced in https://github.com/ClickHouse/ClickHouse/pull/56141

cc: @zvonand, @rschu1ze

**Comment by zvonand** [comment] 2023-12-14 16:22
duplicate of #57819

**Closed** 2023-12-14 16:39 UTC
Labels: testing
