### ISSUE TITLE
MySQL compatibility: Illegal column Int64 of argument of function concat. (ILLEGAL_COLUMN)

### ISSUE THREAD

**Issue by larskarbo** [ClickHouse/ClickHouse#56590] opened 2023-11-10 14:17 UTC
Using the MySQL connector, when using Tableau’s default Quarterly Number date granularity, it fails with this error message:

```
Unable to complete action
Bad Connection: Tableau could not connect to the data source.
Error Code: B19090E0
[MySQL][ODBC 8.1(w) Driver][mysqld-23.11.1.349-ClickHouse]Code: 44. DB::Exception: Illegal column Int64 of argument of function concat. (ILLEGAL_COLUMN) (version 23.11.1.349 (official build))
SELECT COUNT(DISTINCT `transacting_events`.`id`) AS `ctd_id_ok`,
  ADDDATE( CONCAT( DATE_FORMAT( `transacting_events`.`createdAt`, '%Y-' ), (3*(QUARTER(`transacting_events`.`createdAt`)-1)+1), '-01 00:00:00' ), INTERVAL 0 SECOND ) AS `tqr_createdAt_ok`
FROM `transacting_events`
GROUP BY 2
```

**How to reproduce**

- Which ClickHouse server version to use: latest master
- Which interface to use, if matters: MySQL

Select Quarterly as a number granularity in Tableau.

**Expected behavior**

That Tableau connected to Clickhouse with the MySQL connector can show quarterly views without errors.

**Comment by larskarbo** [comment] 2023-11-10 15:12
Most likely related to https://github.com/ClickHouse/ClickHouse/issues/55993

**Comment by slvrtrn** [comment] 2023-11-10 15:14
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/55993

**Closed by slvrtrn** 2023-11-10 15:14 UTC
Labels: duplicate
