### ISSUE TITLE
Temporary remove Azure Blob Storage support, because a test has failed.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#42638] opened 2022-10-25 03:10 UTC
See https://github.com/Azure/azure-sdk-for-cpp/issues/4047

Note: there is no intent to remove the Azure Blob Storage support from ClickHouse.
But after upgrading to LLVM-15, it starts to complain about this issue, and we need to eliminate it to simply move forward.

**Comment by azat** [comment] 2022-10-25 06:29
Duplicate of #42638, will close referenced issue then.

**Comment by alexey-milovidov** [comment] 2022-10-25 06:41
@azat by the way, I did not check the code.
Maybe we simply need to update the Azure SDK?
Maybe we are using it in the wrong way?

**Comment by azat** [comment] 2022-10-25 06:42
> I did not check the code.

Me neither

**Comment by alexey-milovidov** [comment] 2022-10-25 07:31
Memory leak in XML parsing: https://github.com/ClickHouse/ClickHouse/issues/41104

**Comment by alexey-milovidov** [comment] 2022-10-25 07:32
Flaky test: https://github.com/ClickHouse/ClickHouse/issues/39700

**Comment by alexey-milovidov** [comment] 2022-10-26 04:11
@jkuklis just to clarify - we don't want to remove it,
we just need to address these failed checks... and before it will happen, we can just temporarily remove it.

**Comment by KochetovNicolai** [comment] 2022-10-28 11:20
Another one thread leak
https://s3.amazonaws.com/clickhouse-test-reports/42681/f04f6638189bd4a0f9c9defdb43c66b3e8c5ef37/stress_test__tsan_/stderr.log

**Comment by Algunenano** [comment] 2022-11-04 15:35
This keeps hitting the CI multiple times daily. I'm not sure if dropping it temporarily is the best option, but it seems like a valid option.

**Comment by alexey-milovidov** [comment] 2022-11-04 18:41
Unfortunately, the "thread leak" also appeared in HDFS.
And it is not necessarily a leak as we can terminate the application with `syscall(SYS_exit...`

**Comment by alexey-milovidov** [comment] 2022-11-04 18:44
`sudo DEBIAN_FRONTEND=noninteractive ./clickhouse install`

**Closed** 2022-11-07 19:20 UTC
Labels: feature, make it worse
