### ISSUE TITLE
MaterializeMySQL data inconsistency between MySQL and CH when  ClickHouse restart OR MySQL restart normally OR MySQL killed

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#15179] opened 2020-09-23 03:49 UTC
**Describe the bug**
CH version: 20.10.1.4699
 1. I got data inconsistency between MySQL and CH when ch  restart during the batch transaction is executing
 2. I got error "Master maybe lost" and data inconsistency between MySQL and CH when MySQL restart during the batch    transaction is executing
 3. I got error "Cannot read all data. Bytes read: 0. Bytes expected: 3" and data inconsistency between MySQL and CH when  MySQL killed during the batch transaction is executing
**How to reproduce**
1.First situation:CH restart
 1)Establish real time synchronization between MySQL and CH
  checked that  MySQL and CH data are consistent, as below
mysql> select count(1) from mobile_belong_test where province='北京';
+----------+
| count(1) |
+----------+
|   290000 |
+----------+
1 row in set (3.32 sec)
 test-1-118.raipeng.com :) select count(1) from mobile_belong_test where province='北京';
SELECT count(1)
FROM mobile_belong_test
WHERE province = '北京'
┌─count(1)─┐
│   290000 │
└──────────┘
1 rows in set. Elapsed: 0.468 sec. Processed 14.83 million rows, 489.49 MB (31.66 million rows/s., 1.04 GB/s.) 
 2)Execute procedure to update data in batch transaction in MySQL, and restart CH during procedure runtime
   MySQL:
   mysql>call batch_update()       
   clickhouse:
   [root@test-1-118 ~]# kill -9 17913 (kill CH process) and start 
 3)checked data between MySQL and CH,MySQL have data 11934004 updated,CH have data 11930200 updated,  so data inconsistency
 mysql> select count(1) from mobile_belong_test where province='北京';
+----------+
| count(1) |
+----------+
| 11934004 |
+----------+
1 row in set (3.53 sec)
test-1-118.raipeng.com :) select count(1) from mobile_belong_test where province='北京';
SELECT count(1)
FROM mobile_belong_test
WHERE province = '北京'
┌─count(1)─┐
│ 11930200 │
└──────────┘
1 rows in set. Elapsed: 0.690 sec. Processed 26.47 million rows, 873.62 MB (38.36 million rows/s., 1.27 GB/s.) 
 Remark: Not only update, insert and delete have the same problem
2.Second situation:MySQL restart normally
 1)Establish real time synchronization between MySQL and CH
 2)Execute procedure to update data in batch transaction in MySQL, and restart MySQL during procedure runtime
 3)Can not access CH because CH show error "Master maybe lost" ,  so I restarted CH
 4)check data between MySQL and CH, and found data inconsistency.
3.Third situation: MySQL killed 
 1)Establish real time synchronization between MySQL and CH
 2)Execute procedure to update data in batch transaction in MySQL, and kill MySQL during procedure runtime
 3)Can not access CH because CH show error "Cannot read all data. Bytes read: 0. Bytes expected: 3.. " ,  so I restarted CH
 SELECT count(1)
 FROM mobile_belong_test
 Received exception from server (version 20.10.1):
 Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 3.. 
 0 rows in set. Elapsed: 0.007 sec.
 4)check data between MySQL and CH, and found data inconsistency.

**Comment by chang0391** [comment] 2020-09-23 05:59
@BohuTANG @zhang2014

**Comment by zhang2014** [comment] 2020-09-24 06:40
I will trying to fix it.

**Comment by chang0391** [comment] 2020-09-25 01:35
@zhang2014 
   Thanks

**Comment by chang0391** [comment] 2020-09-29 01:21
@zhang2014 
   How is the bug handling going on ?

**Comment by chang0391** [comment] 2020-10-30 09:14
@zhang2014
    have you already began to fix the issue?

**Comment by tavplubix** [comment] 2020-10-30 10:30
> data inconsistency between MySQL and CH

Looks like duplicate of #14829. There is no actual data inconsistency, just `select count()` returns wrong result. You can check it by explicitly executing `select count() from materialize_mysql_db.table final where _sign=1` instead of simple `select count() from materialize_mysql_db.table`. Fixed in #15767, now simple `select count()` should work fine.

>  "Cannot read all data. Bytes read: 0. Bytes expected: 3" when MySQL killed

Looks like expected behaviour. MySQL sends some data to ClickHouse, then we kill MySQL, it suddenly stops to send data, ClickHouse cannot receive whole packet and throws an exception.

**Comment by chang0391** [comment] 2020-11-16 07:27
The two issues have nothing to do with each other

**Comment by chang0391** [comment] 2020-12-02 00:47
@zhang2014 
    Can you take care of this issue?
@tavplubix 
    this issue should not be closed, it‘s always existential

**Comment by tavplubix** [comment] 2020-12-02 10:13
So it's still reproducible with v20.13.1.5273-testing, right?

**Comment by chang0391** [comment] 2020-12-03 06:17
yes, the issue is still exist

**Closed** 2021-08-12 20:34 UTC
Labels: st-wontfix, comp-mysql, bug experimental
