### ISSUE TITLE
Memory is not released.

### ISSUE THREAD

**Issue by HooliBox** [ClickHouse/ClickHouse#11841] opened 2020-06-21 14:41 UTC
**Describe the bug**
I ran the same query couple times. The first couple time, the query works file, but after that, it will start to fail.
```python
rom sqlalchemy import create_engine, Column, MetaData, literal
from clickhouse_sqlalchemy import Table, make_session, get_declarative_base, types, engines
import pandas as pd
import numpy as np

uri = 'clickhouse://default@192.168.10.9/'
engine = create_engine(uri)
metadata = MetaData()

sql = """
SELECT toYYYYMMDD(trade_datetime) AS trade_dt, s_info_windcode, SUM(volume) AS volume FROM minute_bar
WHERE toInt64(toYYYYMMDDhhmmss(trade_datetime)) - toInt64(toYYYYMMDD(trade_datetime)) * 1000000 > 94500
AND toInt64(toYYYYMMDDhhmmss(trade_datetime)) - toInt64(toYYYYMMDD(trade_datetime)) * 1000000 < 141500
GROUP BY toYYYYMMDD(trade_datetime), s_info_windcode"""

for i in range(10):
    res = engine.execute(sql)
    data = res.fetchall()
    print(i, data[0])
```
the except is the following:
```
0 ('20191025', '603915.SH', '2157700')
1 ('20130208', '002059.SZ', '1159964')
2 ('20191025', '603915.SH', '2157700')
3 ('20130208', '002059.SZ', '1159964')
4 ('20130208', '002059.SZ', '1159964')
5 ('20191025', '603915.SH', '2157700')
---------------------------------------------------------------------------
DatabaseException                         Traceback (most recent call last)
<ipython-input-2-d1cd821b006b> in <module>
      7 
      8 for i in range(10):
----> 9     res = engine.execute(sql)
     10     data = res.fetchall()
     11     print(i, data[0])

/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py in execute(self, statement, *multiparams, **params)
   2242 
   2243         connection = self._contextual_connect(close_with_result=True)
-> 2244         return connection.execute(statement, *multiparams, **params)
   2245 
   2246     def scalar(self, statement, *multiparams, **params):

/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py in execute(self, object_, *multiparams, **params)
   1010         """
   1011         if isinstance(object_, util.string_types[0]):
-> 1012             return self._execute_text(object_, multiparams, params)
   1013         try:
   1014             meth = object_._execute_on_connection

/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py in _execute_text(self, statement, multiparams, params)
   1185             parameters,
   1186             statement,
-> 1187             parameters,
   1188         )
   1189         if self._has_events or self.engine._has_events:

/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1322         except BaseException as e:
   1323             self._handle_dbapi_exception(
-> 1324                 e, statement, parameters, cursor, context
   1325             )
   1326 

/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1519                 )
   1520             else:
-> 1521                 util.raise_(exc_info[1], with_traceback=exc_info[2])
   1522 
   1523         finally:

/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/compat.py in raise_(***failed resolving arguments***)
    176 
    177         try:
--> 178             raise exception
    179         finally:
    180             # credit to

/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1282                 if not evt_handled:
   1283                     self.dialect.do_execute(
-> 1284                         cursor, statement, parameters, context
   1285                     )
   1286 

/opt/conda/lib/python3.7/site-packages/clickhouse_sqlalchemy/drivers/base.py in do_execute(self, cursor, statement, parameters, context)
    874 
    875     def do_execute(self, cursor, statement, parameters, context=None):
--> 876         cursor.execute(statement, parameters, context=context)
    877 
    878     def _check_unicode_returns(self, connection, additional_tests=None):

/opt/conda/lib/python3.7/site-packages/clickhouse_sqlalchemy/drivers/http/connector.py in execute(self, operation, parameters, context)
    115         response_gen = transport.execute(raw_sql, params=params)
    116 
--> 117         self._process_response(response_gen)
    118         self._end_query()
    119 

/opt/conda/lib/python3.7/site-packages/clickhouse_sqlalchemy/drivers/http/connector.py in _process_response(self, response)
    214         response = iter(response)
    215 
--> 216         self._columns = next(response, None)
    217         self._types = next(response, None)
    218         self._response = response

/opt/conda/lib/python3.7/site-packages/clickhouse_sqlalchemy/drivers/http/transport.py in execute(self, query, params)
     89         there is nothing to return.
     90         """
---> 91         r = self._send(query, params=params, stream=True)
     92         lines = r.iter_lines()
     93         try:

/opt/conda/lib/python3.7/site-packages/clickhouse_sqlalchemy/drivers/http/transport.py in _send(self, data, params, stream)
    135             orig = HTTPException(r.text)
    136             orig.code = r.status_code
--> 137             raise DatabaseException(orig)
    138         return r

DatabaseException: Orig exception: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 52.74 GiB (attempt to allocate chunk of 4718592 bytes), maximum: 52.73 GiB: While executing AggregatingTransform (version 20.4.5.36 (official build))
```
 

**How to reproduce**
CentOS 7
Clickhouse 20.4.5.36

I posted the log file here: https://gist.github.com/HooliBox/7c2c80712403e47b975a1e8d219ce549

**Comment by den-crane** [comment] 2020-06-21 14:57
Can you provide 

1.  linux kernel version `uname -a`
2. `nproc --all` 
3. `show create table minute_bar`
4. `cat /proc/sys/vm/overcommit_memory`
5. Data sample from minute_bar would be nice to have to make reproducible example.

**Comment by HooliBox** [comment] 2020-06-21 15:06
1. linux kernel
`Linux clickhouse 5.4.34-1-pve #1 SMP PVE 5.4.34-2 (Thu, 07 May 2020 10:02:02 +0200) x86_64 x86_64 x86_64 GNU/Linux`
2. nproc --all `64`
3. show create table minute_bar
```
CREATE TABLE quant.minute_bar
(
    `trade_datetime` DateTime,
    `s_info_windcode` String,
    `open` Float64,
    `high` Float64,
    `low` Float64,
    `close` Float64,
    `volume` Float64,
    `amount` Float64,
    `num_trades` Float64
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(trade_datetime)
ORDER BY (trade_datetime, s_info_windcode)
SETTINGS index_granularity = 8192;
```
4. cat /proc/sys/vm/overcommit_memory
`0`
5. A data sample of minute_bar would be nice to have to make reproducible example
I shall not put real data here. The data is simple and explained here: https://www.investopedia.com/terms/o/ohlcchart.asp
the difference being what the web showed is daily data and I am using minute data.

**Comment by den-crane** [comment] 2020-06-21 15:34
hm, it's rather not memory leak. 
Can you show 
```
select name,value from system.settings where name like '%mem%'
select name,value from system.settings where name like '%group%'
```


first execution :

2020.06.21 14:20:59.067416 [ 480 ] {dc6cf0de-74ff-4c1a-9e47-09a401755aff} <Debug> MemoryTracker: Peak memory usage (for query): 6.14 GiB.


second execution the same query:

2020.06.21 14:21:11.858249 [ 426 ] {a700ec5c-4255-4012-b522-2a31ab368df9} <Debug> MemoryTracker: Current memory usage (for query): 18.00 GiB.
2020.06.21 14:21:12.270053 [ 480 ] {a700ec5c-4255-4012-b522-2a31ab368df9} <Error> executeQuery: Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 18.63 GiB (attempt to allocate chunk of 4227918 bytes), maximum: 18.63 GiB

**Comment by HooliBox** [comment] 2020-06-21 15:38
```
SELECT 
    name, 
    value
FROM system.settings
WHERE name LIKE '%mem%'

┌─name───────────────────────────────────────┬─value───────┐
│ distributed_aggregation_memory_efficient   │ 0           │
│ aggregation_memory_efficient_merge_threads │ 0           │
│ memory_tracker_fault_probability           │ 0           │
│ max_memory_usage                           │ 20000000000 │
│ max_memory_usage_for_user                  │ 0           │
│ memory_profiler_step                       │ 0           │
│ max_memory_usage_for_all_queries           │ 0           │
└────────────────────────────────────────────┴─────────────┘
```
```
SELECT 
    name, 
    value
FROM system.settings
WHERE name LIKE '%group%'

┌─name───────────────────────────────────────┬─value─────┐
│ group_by_two_level_threshold               │ 100000    │
│ group_by_two_level_threshold_bytes         │ 100000000 │
│ distributed_group_by_no_merge              │ 0         │
│ optimize_distributed_group_by_sharding_key │ 0         │
│ output_format_parquet_row_group_size       │ 1000000   │
│ max_rows_to_group_by                       │ 0         │
│ group_by_overflow_mode                     │ throw     │
│ max_bytes_before_external_group_by         │ 0         │
```

I thought it was the issue that it didn't release memory to os after the query is done.

**Comment by den-crane** [comment] 2020-06-21 15:49
as workaround try to change `max_bytes_before_external_group_by='6G'`

>I thought it was the issue that it didn't release memory to os after the query is done.

CH never release memory immediately because of jemalloc tries to save CPU on allocations/deallocations.

**Comment by den-crane** [comment] 2020-06-21 15:57
>PARTITION BY toYYYYMMDD(trade_datetime)
>ORDER BY (trade_datetime, s_info_windcode)
>WHERE toInt64(toYYYYMMDDhhmmss(trade_datetime)) - toInt64(toYYYYMMDD(trade_datetime)) * 1000000 > 94500
> AND toInt64(toYYYYMMDDhhmmss(trade_datetime)) - toInt64(toYYYYMMDD(trade_datetime)) * 1000000 < 141500

BTW, Table/query misdesign , pruning does not work, primary key does not work.

**Comment by HooliBox** [comment] 2020-06-21 16:10
thanks. with this setting max_bytes_before_external_group_by, the issue seems to be gone. 
Do you mean I should use daily partition?  but on a daily basis, there are actually not that much of data.

**Comment by den-crane** [comment] 2020-06-21 16:43
> Do you mean I should use daily partition? but on a daily basis, there are actually not that much of data.

I meant that your query process excessive data because of `WHERE`
Probably it has sense to store a number of seconds from the date start (time w/o date) in a dedicated column and avoid a computation toInt64(toYYYYMMDDhhmmss(

`time UInt32 materialized trade_datetime - toStartOfDay(trade_datetime)`
and filter by that new column `where time between (9*3600+45*60) and (14*3600+15*60)`

And change table's ORDER BY to (s_info_windcode, trade_datetime) for a better compression.

**Comment by den-crane** [comment] 2020-06-21 17:47
Can you show an output of `select uniq(s_info_windcode) from quant.minute_bar` I mean some approximate number of possible s_info_windcode ?

**Comment by HooliBox** [comment] 2020-06-21 23:10
there are about 2000 distinct s_info_windcode. 
Thanks, the suggestion make a lot of sense.

**Comment by den-crane** [comment] 2020-06-22 14:21
I could not reproduce it with debian10 - 4.19.0-6  / CH 20.4.5.36  /  nproc --all - 16

**Comment by azat** [comment] 2020-10-18 19:45
The problem is memory accounting, memory does released.

@HooliBox can you check latest version? 20.9 should be fine, I cannot find anything that may affect this between 20.9 and upstream/master

**Comment by den-crane** [comment] 2020-10-28 02:25
No info. No repro. I am closing it.
Please reopen / open a new issue if the issue is persists for versions 20.9+

**Closed by den-crane** 2020-10-28 02:25 UTC
Labels: bug, memory, st-need-info, st-need-repro, v20.4-affected
