### ISSUE TITLE
Cannot perform a multi-line insert with clickhouse-client

### ISSUE THREAD

**Issue by bgranvea** [ClickHouse/ClickHouse#14698] opened 2020-09-10 13:08 UTC
**Describe the unexpected behaviour**
Exception when executing a multi-line insert contained in a SQL file with clickhouse-client.

**How to reproduce**

```
# clickhouse-client -n -m
ClickHouse client version 20.5.4.40 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.5.4 revision 54435.

chhost1 :) create table test (value Float64) ENGINE=MergeTree ORDER BY tuple();
chhost1 :) insert into test values
:-] (1),
:-] (2);

Ok.

# cat test.sql
insert into test values
(1),
(2);

# clickhouse-client -n -m < test.sql
Code: 62. DB::Exception: Syntax error: failed at position 2 (line 1, col 2): 2);

. Expected one of: SELECT subquery, SELECT query, SELECT, list of elements, WITH, SELECT query, possibly with UNION, SELECT query, subquery, possibly with UNION
```

It is very annoying because refactoring all the INSERT in my SQL script to single line statements would make them very hard to read for a human.

**Comment by den-crane** [comment] 2020-09-10 13:34
```
clickhouse-client  -m < test.sql

SELECT *
FROM test

┌─value─┐
│     1 │
│     2 │
└───────┘
```

**Comment by bgranvea** [comment] 2020-09-10 14:17
> ```
> clickhouse-client  -m < test.sql
> 
> SELECT *
> FROM test
> 
> ┌─value─┐
> │     1 │
> │     2 │
> └───────┘
> ```

my test case is too simple but my real use case has several queries. 

BTW, the behaviour in this case seems also strange (no error although there are several statements and first multi-line insert works):

```
# clickhouse-client
ClickHouse client version 20.5.4.40 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.5.4 revision 54435.

chhost1 :) truncate table test

Ok.

# cat test.sql
insert into test values
(1),
(2);

insert into test values
(3),
(4);

# clickhouse-client -m < test.sql
# clickhouse-client
ClickHouse client version 20.5.4.40 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.5.4 revision 54435.

chhost1 :) select * from test

SELECT *
FROM test

┌─value─┐
│     1 │
│     2 │
└───────┘
```

**Comment by den-crane** [comment] 2020-09-10 14:34
@bgranvea
 
Yes. I know.
This behavior is from the beginning of CH. And everybody aware of this. It's not "unexpected".
Probably it's more a feature request.

**Comment by amosbird** [comment] 2020-09-10 15:32
It's possible to relax the condition of "end of insert data"  in  https://github.com/ClickHouse/ClickHouse/blob/master/programs/client/Client.cpp#L945   (for instance to check `;\n`)
but who knows what consequences it might bring

**Comment by bgranvea** [comment] 2020-09-11 07:45
> It's possible to relax the condition of "end of insert data" in https://github.com/ClickHouse/ClickHouse/blob/master/programs/client/Client.cpp#L945 (for instance to check `;\n`)
> but who knows what consequences it might bring

there is an explicit comment "/// INSERT data is ended by the end of line, not ';'.", not sure to understand the reason.

to maintain backward compatibility, the check for ';\n' could be enabled as an option (--multilineinsert)?

**Comment by alexey-milovidov** [comment] 2022-08-04 03:37
We can parse INSERT statement until either `;\n` or `\n\n`.

**Comment by amosbird** [comment] 2022-08-04 13:49
> We can parse INSERT statement until either `;\n` or `\n\n`. @amosbird WDYT?

I think it's better to only look for `;\n`. We need a semicolon to start next query anyway.

And it's better than `\n` because query files are unlikely to contain something like this:

```
insert into test format CSV
1
2; select 1;
```

**Comment by alexey-milovidov** [comment] 2022-08-05 05:11
There will be still more ambiguity than we want...

**Comment by Kricket** [comment] 2023-03-09 08:32
Would really like to see this implemented! We insert static data that can run for hundreds of lines. It's bizarre because the `CREATE TABLE` statement can run on several lines without any problem:

```
-- No problem with this multiline statement
CREATE TABLE blabla (
col1 String,
col2 Int64
)
ENGINE = MergeTree()
ORDER BY(col1);

-- But this fails
INSERT INTO blabla(col1, col2) VALUES
('abc', 123),
('def', 456);
```

Why not just use the semicolon as the statement terminator? Isn't that pretty standard?
(Or if it's too dangerous due to backwards compatibility, how about introducing a directive like `SET TERMINATOR`?)

**Comment by ethack** [comment] 2023-10-12 13:06
I'll chime in and say I'd really like multi-line inserts as well. I've spent a few hours between past and recent debugging trying to massage my insert syntax to be just right. Only now did I think to search Github issues and find this. 

I'd consider this is unexpected behavior for these reasons:
* All other types of SQL statements I've worked with in ClickHouse or other DBs have not cared about whitespace and are terminated by a semi-colon rather than a newline (with the `-m` and `-n` flag combination at least).
* I couldn't find anything in the [`INSERT` doc](https://clickhouse.com/docs/en/sql-reference/statements/insert-into) to indicate that inserts should be on one line. Many examples are on a single line, but there are a couple that are multi-line and it's not clear how tricky that line is to walk.
* Googling for general SQL help with syntax brings up many examples with multi-line INSERT VALUES statements. This adds to confusion when trying to find the problem without knowing that clickhouse-client is different in this regard to other DBs.

Here are the examples from the documentation that do seem to allow multi-line inserts.

```sql
INSERT INTO t FORMAT TabSeparated
11  Hello, world!
22  Qwerty
```

```sql
INSERT INTO TABLE FUNCTION remote('localhost', default.simple_table)
    VALUES (100, 'inserted via remote()');
```

My current use case is to mimic ClickHouse's unit test suite for my own schema tests.  I have similar files to [this](https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02115_map_contains.sql) with multiple statements in them, but I also try to keep long statements readable with multiple lines.

**Comment by maxjustus** [comment] 2023-10-20 00:25
Plus one! Was very confused that this wasn't working until I came across this issue..

**Comment by Daniel-Robbins** [comment] 2024-01-06 04:52
Run into same issue:
this works
```sql
INSERT INTO mytable (
    day,
    energyType,
    standingCharge,
    unitRate,
    startDate,
    endDate
) VALUES 
('2024-01-01', 'electricity', 0.2, 0.1, '2024-01-01', '2024-01-31'),('2024-01-02', 'gas', 0.3, 0.2, '2024-01-01', '2024-01-31');
```
but this not
```sql
INSERT INTO mytable (
    day,
    energyType,
    standingCharge,
    unitRate,
    startDate,
    endDate
) VALUES 
('2024-01-01', 'electricity', 0.2, 0.1, '2024-01-01', '2024-01-31'),
('2024-01-02', 'gas', 0.3, 0.2, '2024-01-01', '2024-01-31');
```

**Comment by alexey-milovidov** [comment] 2024-01-06 15:01
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/58436.

**Comment by alexey-milovidov** [comment] 2024-09-21 22:14
Fixed.

**Closed by alexey-milovidov** 2024-09-21 22:14 UTC
Labels: duplicate, feature, st-discussion
