### ISSUE TITLE
TTL, waring reserve space on disk, there is not enough space

### ISSUE THREAD

**Issue by Oinari** [ClickHouse/ClickHouse#21340] opened 2021-03-01 11:58 UTC
We are using table with TTL
TTL datetime TO DISK 'default', datetime + toIntervalDay(7) TO DISK 'disk_hdd', datetime + toIntervalMonth(3)

/var/log/clickhouse-server/clickhouse-server.err.log
`<Warning> default.TABLENAME: Would like to reserve space on disk 'default' by TTL rule of table 'default.TABLENAME' but there is not enough space`

Another strange symptoms - the accumulation of data in the 'moving' directory 
du -sh /var/lib/clickhouse/data/default/TABLENAME/moving/
431G

Found information here 
https://github.com/ClickHouse/ClickHouse/commit/efd3126b5d7979da7ff79f380fa2ee46c2d54c36
but I don't see data about these partitions in system.parts.

storage_configuration:
```
    <storage_configuration>
        <default>
            <keep_free_space_bytes>21474836480</keep_free_space_bytes>
        </default>
        <disks>
            <disk_hdd>
                <path>/srv/hdd/metrics/clickhouse/</path>
            </disk_hdd>
        </disks>
        <policies>
            <default>
                <volumes>
                    <default>
                        <disk>default</disk>
                    </default>
                    <disk_hdd_volume1>
                        <disk>disk_hdd</disk>
                    </disk_hdd_volume1>
                </volumes>
            </default>
        </policies>
    </storage_configuration>
```

df -h /
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/md125      921G  779G  143G  85% /
```

**Comment by filimonov** [comment] 2021-03-01 15:42
It may be caused by merges currently running. 
Check  `metrics.DiskSpaceReservedForMerge`

**Comment by Oinari** [comment] 2021-03-01 16:10
This is it 
DiskSpaceReservedForMerge │ 930866379664 │ Disk space reserved for currently running background merges. It is slightly more than the total size of currently merging parts.

Why so much? How much should be reserved? And how can they be reduced at the moment? 
SYSTEM STOP TTL MERGES ?

**Comment by Oinari** [comment] 2021-03-02 05:08
I guess I misunderstand the logic behind the TTL tables.

Expectation:
Just move the partition to another disk after a specified time in TTL, without cloning to moving dir.
Reality:
Complex operations on each record with merging, requiring x2-x3 partition sizes on the disk?

Disabling TTL MOVE and setting 'move_factor' in storage policies will help?

**Comment by filimonov** [comment] 2021-03-02 05:57
> Complex operations on each record with merging, requiring x2-x3 partition sizes on the disk?

It is wrong. Clickhouse always (w/o ttl too) reserve double disk space of src part set size during the merge.

Running moves/mutations also do disk reservations.

So for ex. if merge of 5 parts which overall size is 100 Gb have just started, it will create reservation for 200 GB on a disk with 210Gb free space. And next merge (of 20Gb) will not be able to put the result on the same disk, despite the fact it (still) have 205Gb of free disk space. 

TTL moves require one small file to exists in every part storing min and max for ttl expressions. 

When you do alter ttl creating those files (materialize ttl) require to run mutation on all parts. It is one-time operation, for new parts/inserts ttl files are calculate automatically.

Check system.mutations & system.merges.

**Comment by Oinari** [comment] 2021-03-02 14:29
>reserve double disk space of src part set size
Thank. Changing partitioning key and reducing partition size is my way.

Another question about the directory moving.
It looks like duplicates of clones have accumulated there.
How can I clean it safely?

I try before manually moving to temporary storage
```
check system.parts
lsof +D ./moving/20210222_1776809_1789856_8
grep 20210222_1776809_1789856_8 /var/log/clickhouse-server/clickhouse-server.log
```

**Comment by melvynator** [comment] 2024-06-05 00:38
The initial question has been answered and I doubt the last question is still relevant (as in the most recent version of ClickHouse you will not have to do any type of cleanup), @Oinari please let us know if you have any additional question, otherwise I will close this issue.

**Closed** 2024-07-09 09:33 UTC
Labels: question, comp-multidisk, close in a month if not active
