### ISSUE TITLE
Asynchronous write error on file during merge.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#14093] opened 2020-08-26 06:17 UTC
```
void DB::BackgroundProcessingPool::threadFunction(): Code: 275, e.displayText() = DB::Exception: Asynchronous write error on file
/var/lib/clickhouse/data/db/table/tmp_merge_20200315_14266_31488_5/utc_datetime.bin, Stack trace (when copying this message, always include the lines below):
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbb8cd1c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x500a679 in /usr/bin/clickhouse
2. ? @ 0x4d7d170 in /usr/bin/clickhouse
3. DB::WriteBufferAIO::nextImpl() @ 0x9a865b9 in /usr/bin/clickhouse
4. DB::HashingWriteBuffer::nextImpl() @ 0x8ec7d24 in /usr/bin/clickhouse
5. DB::CompressedWriteBuffer::nextImpl() @ 0x8929f5f in /usr/bin/clickhouse
6. DB::HashingWriteBuffer::nextImpl() @ 0x8ec7d24 in /usr/bin/clickhouse
7. ? @ 0x8f64c39 in /usr/bin/clickhouse
8. DB::MergeTreeDataPartWriterWide::writeColumn(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::IDataType const&, DB::IColumn const&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) @ 0x8f63db2 in /usr/bin/clickhouse
9. DB::MergeTreeDataPartWriterWide::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*, DB::Block const&, DB::Block const&) @0x8f646eb in /usr/bin/clickhouse
10. DB::MergedBlockOutputStream::writeImpl(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0x8fdee72 in /usr/bin/clickhouse
11. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, DB::MergeListEntry&, DB::TableStructureReadLockHolder&, long, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool, bool) @ 0x8f2fd45 in /usr/bin/clickhouse
12. DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) @ 0x8deaff1 in /usr/bin/clickhouse
13. DB::StorageMergeTree::mergeMutateTask() @ 0x8df1d1d in /usr/bin/clickhouse
14. DB::BackgroundProcessingPool::threadFunction() @ 0x8ec1481 in /usr/bin/clickhouse
15. ? @ 0x8ec1e2d in /usr/bin/clickhouse
16. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x5013ead in /usr/bin/clickhouse
17. ? @ 0x501251f in /usr/bin/clickhouse
18. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
19. __clone @ 0xfdead in /usr/lib64/libc-2.17.so
(version 20.3.11.97)
```

Column definition is:
```
`utc_datetime` UInt64 CODEC(T64, LZ4),
```
Part sizes which were merged are ~20Gb each. `CHECK TABLE` shows no errors.

Fixed by detaching one of the parts. 

Not too much extra info for now.

**Comment by UnamedRus** [comment] 2020-08-26 11:16
A little correction: looks like a certain combination of parts being merged raises that issue, not a certain part itself.

**Comment by UnamedRus** [comment] 2020-08-28 15:55
I tried to repeat error.

ClickHouse server version 20.3.11
```
executeQuery: Code: 236, e.displayText() = DB::Exception: Cancelled merging parts (version 20.3.11.97 (official build)) (from 127.0.0.1:37906) (in query: OPTIMIZE TABLE bat2.quote FINAL), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1051b3a0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f5172d in /usr/bin/clickhouse
2. ? @ 0xd918a93 in /usr/bin/clickhouse
3. DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) @ 0xd70b634 in /usr/bin/clickhouse
4. DB::StorageMergeTree::optimize(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::IAST> const&, bool, bool, DB::Context const&) @ 0xd70c238 in /usr/bin/clickhouse
5. DB::InterpreterOptimizeQuery::execute() @ 0xd11316f in /usr/bin/clickhouse
6. ? @ 0xd53ae58 in /usr/bin/clickhouse
7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) @ 0xd53da91 in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0x90337d9 in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0x90347c0 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0xe39269b in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0xe392b1d in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x105a9507 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x105a530c in /usr/bin/clickhouse
14. ? @ 0x105a6cad in /usr/bin/clickhouse
15. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
16. __clone @ 0x122103 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

ClickHouse server version 20.3.17

Merge is working fine.

**Comment by alexey-milovidov** [comment] 2020-08-28 19:09
@filimonov Does the error repeat on every merge attemt?
Do you see any related messages in `dmesg`?
Write failure may indicate hardware error with the underlying device.

BTW, you can disable AIO for merges completely.

**Comment by filimonov** [comment] 2020-08-28 21:12
> @filimonov Does the error repeat on every merge attemt?

Yes. Very determenistic. @UnamedRus was debugging that, if i understand correctly when certain 2 source  parts were being merged, it was failing. Of only one of them were processed (with others from that partition) - it were working fine.

> Write failure may indicate hardware error with the underlying device.

Some hw failure is possible (and Afair they there mentioning some hard restart before that), but it rather looks like source parts vere damaged in some strange way. 

@UnamedRus message above relates to his attempt to do the merges of those problematic parts (shared by client) on other environment. 

> BTW, you can disable AIO for merges completely.

I also thoght so, but didn't find the setting. What was that?

**Comment by alexey-milovidov** [comment] 2020-08-28 21:22
`min_merge_bytes_to_use_direct_io` in MergeTreeSettings.

**Comment by filimonov** [comment] 2020-08-28 23:17
> `min_merge_bytes_to_use_direct_io` in MergeTreeSettings.

OK. So actually  aio = direct io here (was messed by naming). BTW - did you ever try/consider `posix_fadvise` instead o_direct?

**Comment by UnamedRus** [comment] 2020-09-03 19:54
Disabling  `min_merge_bytes_to_use_direct_io=0` fixed async write error and merging issue.

**Comment by filimonov** [comment] 2020-09-10 07:11
Most probably it's related to filesystem used (Lustre)

**Closed** 2020-10-05 06:15 UTC
Labels: st-need-repro

**Comment by alexey-milovidov** [comment] 2020-10-05 06:16
We need help reproducing this error with Lustre:
- to report a bug for them;
- to add a check in ClickHouse that O_DIRECT must be disabled if the filesystem is Lustre.

**Comment by filimonov** [comment] 2020-10-05 07:03
Most probably it relates to async io: 

https://bugzilla.lustre.org/show_bug.cgi?id=11719
https://lustre-discuss.lustre.narkive.com/zwcvyEEY/asynchronous-posix-i-o-with-lustre
