### ISSUE TITLE
Default storage reaching inode limit

### ISSUE THREAD

**Issue by tiagokrebs** [ClickHouse/ClickHouse#33310] opened 2021-12-29 21:59 UTC
**Describe what's wrong**
Even though I use a specific storage policy and dedicated disks in all my tables, the number of inodes used on the path `/var/lib/clickhouse` is too big and is reaching the limit.
![image](https://user-images.githubusercontent.com/55988677/147705921-1d4748ce-92f7-424c-b7e5-a5f623c8fa50.png)

```
$/var/lib/clickhouse# du --inodes --max-depth 1
9	./access
1	./dictionaries_lib
61	./data
8	./preprocessed_configs
1	./flags
7	./metadata
1	./metadata_dropped
25820	./store
25	./user_files
3198729	./tmp
1	./format_schemas
3224665	.
```
Especially `tmp/store` as you can see above.

**Does it reproduce on recent release?**
I don't know. The version is 21.4.4.30.

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**
There is no crash, yet.

**How to reproduce**

* Which ClickHouse server version to use
21.4.4.30
* Which interface to use, if matters
JBOD storage policy method.

**Expected behavior**
Not used inodes should be released at some point.

**Error message and/or stacktrace**
There is no exception happening.

**Additional context**
I have this cluster that receives ~1MM inserts per second. I store this as raw data for a couple of days and in another aggregated table for some weeks. I use this `three_tier` storage policy for all tables:
```
<yandex>
    <storage_configuration>
        <!-- adding new disks demands clickhouse-server restart -->
        <disks>
            <default>
                <keep_free_space_bytes>1048576</keep_free_space_bytes>
            </default>
            <!-- hot layer disks -->
            <data_hot_0>
                <path>/data_hot_0/</path>
                <keep_free_space_bytes>1073741824</keep_free_space_bytes>
            </data_hot_0>
            <data_hot_1>
                <path>/data_hot_1/</path>
                <keep_free_space_bytes>1073741824</keep_free_space_bytes>
            </data_hot_1>
        </disks>
        <policies>
            <!-- Tiered storage with several volumes and disks -->
            <three_tier>
                <volumes>
                    <hot_volume>
                        <disk>data_hot_0</disk>
                        <disk>data_hot_1</disk>
                    </hot_volume>
                </volumes>
            </three_tier>
        </policies>
    </storage_configuration>
</yandex>
```
The inserts are made through a Kafka Engine table and a materialized view. The cluster has 6 servers and plenty of resources.

So, if all my tables are using the same storage policy, why can this be happening on the default store? Before thinking about any type of inode increase I would appreciate some help to understand if this is really a bug or a misconfiguration on my part.

**Comment by den-crane** [comment] 2021-12-29 22:09
21.4 is out support. Supported versions are 21.8, 21.11, 21.12 

Probably this the duplicate of https://github.com/ClickHouse/ClickHouse/issues/26471

**Closed by den-crane** 2021-12-29 22:09 UTC
Labels: obsolete-version, potential bug

**Comment by den-crane** [comment] 2021-12-29 22:11
try as workaroud `cd /var/lib/clickhouse/tmp/data/ && find . -type d  -empty -ctime +1 -name 'tmp_*' -delete`

**Comment by tiagokrebs** [comment] 2021-12-30 00:23
Thanks, @den-crane. This helps.

From who may be interested, this is indeed a bug in the version I'm using (21.4.4.30). Clickhouse leaves a lot of empty folders on the default storage. With time (months probably) the number of maximum inodes is reached and you start to see `no space left on device` errors.

I use this to delete the empty folders:
```

find /var/lib/clickhouse/tmp/store/ -empty -type d -delete
```

Deleting them will give you time to upgrade your version. I have another cluster in the last LTS version at this moment (21.8.10.19) where I don't have this problem.
