### ISSUE TITLE
pointInPolygon function does not work with arrayMap when array contains polygons

### ISSUE THREAD

**Issue by emakarov** [ClickHouse/ClickHouse#7937] opened 2019-11-27 03:52 UTC
**How to reproduce**
```
ubuntu :) select arrayMap(x -> pointInPolygon((3, 3), x), [ [(6, 0), (8, 4), (5, 8), (0, 2)], [(6, 0), (8, 4), (5, 8), (0, 2)] ]) AS res;

SELECT arrayMap(x -> pointInPolygon((3, 3), x), [[(6, 0), (8, 4), (5, 8), (0, 2)], [(6, 0), (8, 4), (5, 8), (0, 2)]]) AS res

Received exception from server (version 19.4.1):
Code: 44. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Argument 2 for function pointInPolygon must be constant array of tuples..

0 rows in set. Elapsed: 0.003 sec.

ubuntu :) select arrayFilter(x -> pointInPolygon((3, 3), x), [ [(6, 0), (8, 4), (5, 8), (0, 2)], [(6, 0), (8, 4), (5, 8), (0, 2)] ]) AS res;

SELECT arrayFilter(x -> pointInPolygon((3, 3), x), [[(6, 0), (8, 4), (5, 8), (0, 2)], [(6, 0), (8, 4), (5, 8), (0, 2)]]) AS res

Received exception from server (version 19.4.1):
Code: 44. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Argument 2 for function pointInPolygon must be constant array of tuples..

0 rows in set. Elapsed: 0.105 sec.
```
* Which ClickHouse server version to use
version 19.4.1

**Expected behavior**
Expected behaviour is that pointInPolygon function should be applied to every polygon in the array and be usable with arrayFilter and arrayMap functions

**Additional context**
some user wanted such possibility -
https://t.me/clickhouse_en/16789

**Comment by alexey-milovidov** [comment] 2020-06-15 19:09
It is implemented in a series of pull requests:

#10623
#11144
#11421

And available in master and in version 20.5 (testing).

Duplicate of #9002.

**Closed by alexey-milovidov** 2020-06-15 19:09 UTC
Labels: comp-geo, feature
