### ISSUE TITLE
Flaky 00002_log_and_exception_messages_formatting

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#51460] opened 2023-06-27 07:08 UTC
https://s3.amazonaws.com/clickhouse-test-reports/51407/e92035072b7b3367da12089b28041893eb90e636/stateless_tests__debug__s3_storage__[5_6].html

```
2023-06-26 19:32:58 -number of noisy messages	10
2023-06-26 19:32:58 +number of noisy messages	11
```

**Comment by tavplubix** [comment] 2023-06-27 09:55
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/51200

**Closed by tavplubix** 2023-06-27 09:55 UTC
Labels: flaky test
