### ISSUE TITLE
create table ... as select () can‘t execute on a cluster

### ISSUE THREAD

**Issue by sunshup** [ClickHouse/ClickHouse#43215] opened 2022-11-14 11:11 UTC
Tested with latest version on play.clickhouse.com (22.10.1.1875)
In two replica clusters, use zookeeper for data synchronization. 
I execute on clickhouse-client.

Below is the query: 
```
CREATE TABLE case11 ON CLUSTER 'CH-SIT'
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/{uuid}', '{replica}')
ORDER BY ID
AS SELECT number as ID, toString(number) as case_id from numbers(1000) SETTINGS insert_quorum_parallel=0;
```

I expect tables to be created and data inserted at each node of the cluster.
And  error messages are not unique. 

The first error is as follows：
```
Loads all the time.

node1:
Code: 286. DB::Exception: Quorum for previous write has not been satisfied yet. Status: version: 1
part_name: all_0_0_0
required_number_of_replicas: 2
actual_number_of_replicas: 1
replicas:
node2
. (UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE) (version 22.10.1.1875)

-- I see the error message from node2 through zookeeper(prettyzoo)
node2: Code: 319. DB::Exception: Unknown status, client must retry. Reason: Code: 159. DB::Exception: Timeout while waiting for quorum. (TIMEOUT_EXCEEDED) (version 22.10.1.1875). (UNKNOWN_STATUS_OF_INSERT)
```

The second error is as follows：
```
Exception: Received from localhost:9000. DB::Exception: There was an error on [node02:9000]: Code: 286. DB::Exception: Another quorum insert has been already started. (UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE) (version 22.10.1.1875). (UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE)

node1: succeed
node2: Code: 286. DB::Exception: Another quorum insert has been already started. (UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE)(version 22.10.1.1875)
```

**Comment by tavplubix** [comment] 2022-11-14 14:59
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/34735
See also https://github.com/ClickHouse/ClickHouse/issues/41538

**Closed by tavplubix** 2022-11-14 14:59 UTC
Labels: potential bug
