### ISSUE TITLE
Error in parsing parameters in parameterized view

### ISSUE THREAD

**Issue by hedgy** [ClickHouse/ClickHouse#47248] opened 2023-03-05 01:33 UTC
Clickhouse 23.2.2.20. Under load I got strange exceptions when try to select from parameterized views. Without load these errors don't reproduce.

Here are exceptions with stack traces:

2023.03.04 21:40:12.392398 [ 744692 ] {90df5786-7094-4aab-846d-7fc67326e342} <Error> executeQuery: Code: 130. DB::Exception: Array does not start with '[' character. (CANNOT_READ_ARRAY_FROM_TEXT) (version 23.2.2.20 (official build)) (from 10.137.89.100:40094) (in query: select product_id, leftover, orders, revenue from sales_report_totals(period=30, product_ids=[91590681,137913516,138224634,117716514,140318648,140621251,137824513,137722493,140848526,137913515]) FORMAT JSONEachRow), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c6655 in /usr/bin/clickhouse
1. ? @ 0x8962316 in /usr/bin/clickhouse
2. DB::SerializationArray::deserializeText(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&, bool) const @ 0x1295d6ab in /usr/bin/clickhouse
3. DB::ReplaceQueryParameterVisitor::visitQueryParameter(std::__1::shared_ptr<DB::IAST>&) @ 0x1396bb86 in /usr/bin/clickhouse
4. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
5. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
6. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
7. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
8. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
9. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
10. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
11. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
12. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
13. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
14. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
15. ? @ 0x135c9f92 in /usr/bin/clickhouse
16. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char,
 std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x135c
6759 in /usr/bin/clickhouse
17. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<ch
ar>, std::__1::allocator<char>>>> const&) @ 0x13658602 in /usr/bin/clickhouse
18. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std:
:__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x136565aa in /usr/bin/clickhouse
19. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x13580110 in /usr/bin/clickhouse
20. ? @ 0x1397aa00 in /usr/bin/clickhouse
21. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::al
locator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x13980c72 in /usr/bin/cl
ickhouse
22. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x146aa356 in /usr/bin/clickhouse
23. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x146ae52c in /usr/bin/clickhouse
24. DB::HTTPServerConnection::run() @ 0x1471bafd in /usr/bin/clickhouse
25. Poco::Net::TCPServerConnection::start() @ 0x17613dd4 in /usr/bin/clickhouse
26. Poco::Net::TCPServerDispatcher::run() @ 0x17614ffb in /usr/bin/clickhouse
27. Poco::PooledThread::run() @ 0x1779c387 in /usr/bin/clickhouse
28. Poco::ThreadImpl::runnableEntry(void*) @ 0x17799dbd in /usr/bin/clickhouse
29. ? @ 0x7f7c95ec9b43 in ?
30. ? @ 0x7f7c95f5ba00 in ?

2023.03.04 22:18:54.127028 [ 1426183 ] {e177bce5-f5cd-4a09-8593-bd90a0953b97} <Error> executeQuery: Code: 457. DB::Exception: Value [143543897] cannot be parsed as UInt8 for query parameter 'period' because it isn't parsed completely: only 0 of 11 bytes was parsed: . (BAD_QUERY_PARAMETER) (version 23.2.2.20 (official build)) (from 10.137.89.100:52150) (in query: select leftover, orders, revenue from sales_report_totals_add(period=30, product_ids=[143543897]) FORMAT JSONEachRow), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c6655 in /usr/bin/clickhouse
1. ? @ 0x1396c5d4 in /usr/bin/clickhouse
2. DB::ReplaceQueryParameterVisitor::visitQueryParameter(std::__1::shared_ptr<DB::IAST>&) @ 0x1396bf5e in /usr/bin/clickhouse
3. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
4. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
5. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
6. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
7. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
8. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
9. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
10. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
11. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
12. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
13. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
14. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
15. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
16. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
17. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
18. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
19. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
20. ? @ 0x135c9f92 in /usr/bin/clickhouse
21. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x135c6759 in /usr/bin/clickhouse
22. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x13658602 in /usr/bin/clickhouse
23. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x136565aa in /usr/bin/clickhouse
24. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x13580110 in /usr/bin/clickhouse
25. ? @ 0x1397aa00 in /usr/bin/clickhouse
26. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x13980c72 in /usr/bin/clickhouse
27. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x146aa356 in /usr/bin/clickhouse
28. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x146ae52c in /usr/bin/clickhouse
29. DB::HTTPServerConnection::run() @ 0x1471bafd in /usr/bin/clickhouse
30. Poco::Net::TCPServerConnection::start() @ 0x17613dd4 in /usr/bin/clickhouse
31. Poco::Net::TCPServerDispatcher::run() @ 0x17614ffb in /usr/bin/clickhouse

2023.03.04 22:17:54.007411 [ 1390093 ] {e3eaa96f-c6b5-474f-9885-dd4613d1893c} <Error> executeQuery: Code: 456. DB::Exception: Substitution `period` is not set. (UNKNOWN_QUERY_PARAMETER) (version 23.2.2.20 (official build)) (from 10.137.89.100:43982) (in query: select leftover, orders,
 revenue from sales_report_totals_add(period=30, product_ids=[66124309]) FORMAT JSONEachRow), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c6655 in /usr/bin/clickhouse
1. ? @ 0x893d784 in /usr/bin/clickhouse
2. DB::ReplaceQueryParameterVisitor::getParamValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x1396c49a in /usr/bin/clickhouse
3. DB::ReplaceQueryParameterVisitor::visitQueryParameter(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b579 in /usr/bin/clickhouse
4. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
5. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
6. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
7. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
8. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
9. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
10. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
11. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
12. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
13. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
14. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
15. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
16. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
17. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
18. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
19. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
20. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x1396b4eb in /usr/bin/clickhouse
21. ? @ 0x135c9f92 in /usr/bin/clickhouse
22. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char,
 std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x135c
6759 in /usr/bin/clickhouse
23. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<ch
ar>, std::__1::allocator<char>>>> const&) @ 0x13658602 in /usr/bin/clickhouse
24. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std:
:__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x136565aa in /usr/bin/clickhouse
25. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x13580110 in /usr/bin/clickhouse
26. ? @ 0x1397aa00 in /usr/bin/clickhouse
27. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::al
locator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x13980c72 in /usr/bin/cl
ickhouse
28. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x146aa356 in /usr/bin/clickhouse
29. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x146ae52c in /usr/bin/clickhouse
30. DB::HTTPServerConnection::run() @ 0x1471bafd in /usr/bin/clickhouse
31. Poco::Net::TCPServerConnection::start() @ 0x17613dd4 in /usr/bin/clickhouse

Here are views:

CREATE VIEW sales_report_totals
(
    `product_id` UInt32,
    `leftover` UInt32,
    `orders` UInt32,
    `revenue` UInt32
) AS
SELECT
    product_id,
    argMax(leftover, sale_date) AS leftover,
    sum(orders) AS orders,
    sum(revenue) AS revenue
FROM sale_stock_stat
WHERE (sale_date >= toDate(now() - toIntervalDay({period:UInt8}))) AND (product_id IN ({product_ids:Array(UInt32)}))
GROUP BY product_id

CREATE VIEW sales_report_totals_add
(
    `product_id` UInt32,
    `leftover` UInt32,
    `orders` UInt32,
    `revenue` UInt32
) AS
SELECT
    product_id,
    argMax(leftover, sale_date) + argMax(leftover_add, sale_date) AS leftover,
    sum(orders) + sum(orders_add) AS orders,
    sum(revenue) + sum(revenue_add) AS revenue
FROM sale_stock_stat
WHERE (sale_date >= toDate(now() - toIntervalDay({period:UInt8}))) AND (product_id IN ({product_ids:Array(UInt32)}))
GROUP BY product_id

If additional info needed I'll provide it.

**Comment by kssenii** [comment] 2023-03-05 12:58
cc @SmitaRKulkarni

**Comment by den-crane** [comment] 2023-03-05 21:45
It seems the implementation of parameterized views is not threadsafe

repro:

```sql
CREATE VIEW v AS SELECT 1::UInt32 x FROM system.one WHERE x IN ({xx:Array(UInt32)});

select * from v(xx=[1,2,3]);
┌─x─┐
│ 1 │
└───┘


clickhouse-benchmark --ignore-error -c 100 <<< 'select * from v(xx=[1,2,3])'

An error occurred while processing the query 'select * from v(xx=[1,2,3])': Code: 456. DB::Exception: Received from localhost:9000. DB::Exception: Substitution `xx` is not set. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xba0b024 in /usr/bin/clickhouse
1. ? @ 0x7c9ca50 in /usr/bin/clickhouse
2. DB::ReplaceQueryParameterVisitor::getParamValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x104e1214 in /usr/bin/clickhouse
3. DB::ReplaceQueryParameterVisitor::visitQueryParameter(std::__1::shared_ptr<DB::IAST>&) @ 0x104e0544 in /usr/bin/clickhouse
4. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x104e04d8 in /usr/bin/clickhouse
5. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x104e04d8 in /usr/bin/clickhouse
6. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x104e04d8 in /usr/bin/clickhouse
7. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x104e04d8 in /usr/bin/clickhouse
8. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x104e04d8 in /usr/bin/clickhouse
9. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x104e04d8 in /usr/bin/clickhouse
10. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x104e04d8 in /usr/bin/clickhouse
11. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x104e04d8 in /usr/bin/clickhouse
12. DB::ReplaceQueryParameterVisitor::visit(std::__1::shared_ptr<DB::IAST>&) @ 0x104e04d8 in /usr/bin/clickhouse
13. ? @ 0x101c1044 in /usr/bin/clickhouse
14. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x101be0e0 in /usr/bin/clickhouse
15. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x102368ac in /usr/bin/clickhouse
16. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x10234dbc in /usr/bin/clickhouse
17. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x1017ecc8 in /usr/bin/clickhouse
18. ? @ 0x104edbe8 in /usr/bin/clickhouse
19. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x104eb324 in /usr/bin/clickhouse
20. DB::TCPHandler::runImpl() @ 0x1106598c in /usr/bin/clickhouse
21. DB::TCPHandler::run() @ 0x11077704 in /usr/bin/clickhouse
22. Poco::Net::TCPServerConnection::start() @ 0x11c88ba4 in /usr/bin/clickhouse
23. Poco::Net::TCPServerDispatcher::run() @ 0x11c8a0c0 in /usr/bin/clickhouse
24. Poco::PooledThread::run() @ 0x11e3d39c in /usr/bin/clickhouse
25. Poco::ThreadImpl::runnableEntry(void*) @ 0x11e3ac64 in /usr/bin/clickhouse
26. start_thread @ 0x7624 in /usr/lib/aarch64-linux-gnu/libpthread-2.31.so
27. ? @ 0xd149c in /usr/lib/aarch64-linux-gnu/libc-2.31.so
. (UNKNOWN_QUERY_PARAMETER) (version 23.3.1.252)
Code: 456. DB::Exception: Received from localhost:9000. DB::Exception: Substitution `xx` is not set. (UNKNOWN_QUERY_PARAMETER) (version 23.3.1.252)
```

**Comment by den-crane** [comment] 2023-03-05 21:56
eventually got segfault.

**Comment by den-crane** [comment] 2023-03-05 21:58
duplicate of https://github.com/ClickHouse/ClickHouse/issues/47247

**Closed** 2023-03-05 22:46 UTC
Labels: bug, duplicate
