### ISSUE TITLE
DB::Exception: Cannot write to ostream

### ISSUE THREAD

**Issue by nickitat** [ClickHouse/ClickHouse#49341] opened 2023-04-29 16:44 UTC
https://s3.amazonaws.com/clickhouse-test-reports/49236/ada4ec55fe3581368abc2d3c0ad9b9baed24a35d/stress_test__ubsan_/fatal_messages.txt

**Comment by tavplubix** [comment] 2023-05-01 10:15
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/45890

**Closed by tavplubix** 2023-05-01 10:15 UTC
Labels: testing
