### ISSUE TITLE
Wrong schema detected while uploading CSV file

### ISSUE THREAD

**Issue by shabir1** [ClickHouse/ClickHouse#52006] opened 2023-07-10 09:51 UTC
> Wrong schema detected while uploading CSV file.

I have a Float column in the CSV file that contains few STRING values but the clickhouse detects it as Float instead of STRING.

Query:
`DESCRIBE file('abc.csv')`
or 
`DESCRIBE ( SELECT * FROM file('abc.csv') )`

If any column contains a STRING value it should be type of STRING or the SELECT query shouldn't be throws Parse error on that STRING value.

**Comment by UnamedRus** [comment] 2023-07-10 10:06
You can use hints

```
│ schema_inference_hints                                                         │       │       0 │ The list of column names and types to use in schema inference for formats without column names. The format: 'column_name1 column_type1, column_name2 column_type2, ...' │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ String │         │           │
```

ClickHouse make guess on possible values when it reads some sample from start of file.

**Comment by Avogar** [comment] 2023-07-10 10:09
Can you provide the sample of your file?

**Comment by shabir1** [comment] 2023-07-11 07:22
@Avogar I am not able to Set `input_format_max_rows_to_read_for_schema_inference` settings via the java JDBC client.

**Comment by shabir1** [comment] 2023-07-11 07:26
I tried the below query it worked via UI but it didn't work via the JDBC client
`DESCRIBE file('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=1000000`
And `Set input_format_max_rows_to_read_for_schema_inference=1000000` query didn't work at all.

**Comment by shabir1** [comment] 2023-07-11 07:35
@Avogar @den-crane will you please help me here.

**Comment by Avogar** [comment] 2023-07-11 08:12
If row with String value is less then 1000000, `DESCRIBE file('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=1000000` should work. If it doesn't work, please, provide the sample of the data with Stirng value and Float values.
You can also use setting `schema_inference_hints ` to set the desired data type for this column.
For example if the probmematic column is `c5`, you can use `schema_inference_hints='c5 Float64'`.
You can also disable inferring numbers/any complex types at all disabling setting `input_format_csv_use_best_effort_in_schema_inference`.
And you always can specify the structure manually and don't rely on schema inference:
`select * from file(abc.csv, CSV, 'c1 String, c2 Float64, ...')`
Sometimes schema inference cannot infer real data types, because it reads only subset of the data. It's not a bug, it just works like this.

**Comment by shabir1** [comment] 2023-07-11 08:36
@Avogar I think you didn't understand the problem. 
There is nothing with the dataset, I am not able to set the `input_format_max_rows_to_read_for_schema_inference` setting.
I tried `Set input_format_max_rows_to_read_for_schema_inference=<n_rows>` it didn't work, where n_rows is any positive integer value.

**Comment by shabir1** [comment] 2023-07-11 08:39
@Avogar 
I tried 2 ways to set it
1. `Set input_format_max_rows_to_read_for_schema_inference=10` (Not worked, response is OK but the setting is not setted to the new number)
2. `DESCRIBE() SETTINGS input_format_max_rows_to_read_for_schema_inference=10` worked via UI but not via JDBC.

**Comment by Avogar** [comment] 2023-07-11 08:47
I don't know much about JDBC driver, maybe you can ask question in java client repository https://github.com/ClickHouse/clickhouse-java.

> Set input_format_max_rows_to_read_for_schema_inference=10 (Not worked, response is OK but the setting is not setted to the new number)

Most likely it's because the setting is set for the current client session and in JDBC each query creates a new session, so the next query doesn't see the changes.

> DESCRIBE('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=10 worked via UI but not via JDBC.

I guess you ment `DESCRIBE file('abc.csv') SETTINGS ...`. We can check if the setting is set using smth like 
```
select * from (select value, changed from system.settings where name='input_format_max_rows_to_read_for_schema_inference') SETTINGS input_format_max_rows_to_read_for_schema_inference=1000000
```

**Comment by shabir1** [comment] 2023-07-11 08:58
@Avogar 
Query:
`DESCRIBE file('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=10`

Error:
```
cc.blynk.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: null, port: 0; Code: 62. DB::Exception: Syntax error: failed at position 132 ('FORMAT'): FORMAT TabSeparatedWithNamesAndTypes
. Expected end of query. (SYNTAX_ERROR) (version 23.6.2.18 (official build))
```

**Comment by shabir1** [comment] 2023-07-11 08:58
@Avogar Is there any other way to update `input_format_max_rows_to_read_for_schema_inference` settings

**Comment by Avogar** [comment] 2023-07-11 09:04
> DB::Exception: Syntax error: failed at position 132 ('FORMAT'): FORMAT TabSeparatedWithNamesAndTypes. Expected end of query. (SYNTAX_ERROR)

This means that JDBC driver adds `FORMAT TabSeparatedWithNamesAndTypes` to the end of the each query. And query
```
DESCRIBE file('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=10 FORMAT TabSeparatedWithNamesAndTypes
```
Has incorrect syntax (SETTINGS should be set after FORMAT clause). Maybe there is a way to disable adding `FORMAT TabSeparatedWithNamesAndTypes` to the end of the query

**Comment by Avogar** [comment] 2023-07-11 09:14
BTW, this will work:
```
SELECT * FROM file('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=10 FORMAT TabSeparatedWithNamesAndTypes
```
In SELECT we support SETTINGS before FORMAT. It will be also supported for DESCRIBE after https://github.com/ClickHouse/ClickHouse/pull/51899

**Comment by shabir1** [comment] 2023-07-11 09:22
@Avogar Sorry, It didn't work
```
`DESCRIBE file('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=10 FORMAT CSV`

 INFO [main] (ClickHouseDriver.java:36) - Driver registered
cc.blynk.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: null, port: 0; Code: 62. DB::Exception: Syntax error: failed at position 129 ('FORMAT'): FORMAT CSV
. Expected end of query. (SYNTAX_ERROR) (version 23.6.2.18 (official build))
```

**Comment by Avogar** [comment] 2023-07-11 09:28
> Sorry, It didn't work

It's just the same but with different format name at the end... This query has incorrect syntax.

Do you add `FORMAT ...` after `DESCRIBE file('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=10` manually or JDBC driver does it?

**Comment by shabir1** [comment] 2023-07-11 10:24
@Avogar Yes, I tried every possible way.
Is there any other way to update input_format_max_rows_to_read_for_schema_inference settings

**Comment by Avogar** [comment] 2023-07-11 10:30
Can you please answer my question. Do you add `FORMAT ... after DESCRIBE file('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=10` manually or JDBC driver does it?
How `FORMAT ...` appeares in your query?

**Comment by shabir1** [comment] 2023-07-11 10:50
I tried both ways, add Format and without add format but the error is same always

**Comment by Avogar** [comment] 2023-07-11 10:59
> without add format but the error is same always

So, you query is just `DESCRIBE file('file.csv') SETTINGS input_format_max_rows_to_read_for_schema_inference=10` and it fails with syntax error about FORMAT. It means that JDBC driver adds FORMAT after your query automatically. Do you why it added FORMAT and is it possible to not do it?

What your java code looks like?

I looked through JDBC driver code and found `connectWithCustomSettings`, maybe you can use it to set the setting

**Comment by Avogar** [comment] 2023-07-17 12:14
No other information provided, I close it

**Closed by Avogar** 2023-07-17 12:14 UTC
Labels: potential bug

**Comment by den-crane** [comment] 2023-07-31 23:32
`cc.blynk.clickhouse` - alternative outdated JDBC driver.
