### ISSUE TITLE
Format settings from SETTINGS clause of INSERT query are not applied

### ISSUE THREAD

**Issue by surovenko** [ClickHouse/ClickHouse#44348] opened 2022-12-18 21:24 UTC
After update clickhouse-server from 22.2.2.1 to 22.12.1.1752 versions I got the following error:
Code: 36. DB::Exception: The format Protobuf requires a schema. The corresponding setting should be set. (BAD_ARGUMENTS) (version 22.12.1.1752 (official build))

Usually I upload my Protobuf schema to /var/lib/clickhouse/format_schemas/<myfile.proto>
And currently I have this file as in other servers, but only updated server not working with that message.
There's no any other actions, only update to new version.

**Comment by alexey-milovidov** [comment] 2022-12-19 02:25
It might be a table was set up with a non-existent schema, and it has been checked at startup.
The full server logs will help to understand what is the reason for this error.

**Comment by surovenko** [comment] 2022-12-19 15:25
Here's my clickhouse-server.err.log lines:
```
2022.12.19 15:22:45.983167 [ 262 ] {4e6c6bb6-739c-404a-8ee3-78a27b8d7a4b} <Error> executeQuery: Code: 36. DB::Exception: The format Protobuf requires a schema. The corresponding setting should be set. (BAD_ARGUMENTS) (version 22.12.1.1752 (official build)) (from 172.18.0.1:65208) (in query: INSERT INTO <mytable> FORMAT Protobuf ), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0xe74c47a in /usr/bin/clickhouse
1. ? @ 0x7eb1f2d in /usr/bin/clickhouse
2. DB::FormatSchemaInfo::FormatSchemaInfo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x154a0a62 in /usr/bin/clickhouse
3. ? @ 0x1556d96a in /usr/bin/clickhouse
4. DB::FormatFactory::getInputFormat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::ReadBuffer&, DB::Block const&, std::__1::shared_ptr<DB::Context const>, unsigned long, std::__1::optional<DB::FormatSettings> const&) const @ 0x153aa03e in /usr/bin/clickhouse
5. DB::FormatFactory::getInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::ReadBuffer&, DB::Block const&, std::__1::shared_ptr<DB::Context const>, unsigned long, std::__1::optional<DB::FormatSettings> const&) const @ 0x153a74b5 in /usr/bin/clickhouse
6. DB::Context::getInputFormat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::ReadBuffer&, DB::Block const&, unsigned long, std::__1::optional<DB::FormatSettings> const&) const @ 0x13932f49 in /usr/bin/clickhouse
7. DB::getInputFormatFromASTInsertQuery(std::__1::shared_ptr<DB::IAST> const&, bool, DB::Block const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&) @ 0x15668040 in /usr/bin/clickhouse
8. DB::getSourceFromASTInsertQuery(std::__1::shared_ptr<DB::IAST> const&, bool, DB::Block const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IAST> const&) @ 0x1566896a in /usr/bin/clickhouse
9. DB::InterpreterInsertQuery::execute() @ 0x13ff37d2 in /usr/bin/clickhouse
10. ? @ 0x1468c610 in /usr/bin/clickhouse
11. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x14690ccb in /usr/bin/clickhouse
12. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x1531a4d6 in /usr/bin/clickhouse
13. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1531e60e in /usr/bin/clickhouse
14. DB::HTTPServerConnection::run() @ 0x1539e9d4 in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0x1820feb4 in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0x1821185b in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0x183a0947 in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x1839e37d in /usr/bin/clickhouse
19. ? @ 0x7fe1b1039609 in ?
20. __clone @ 0x7fe1b0f5e133 in ?
```

**Comment by surovenko** [comment] 2022-12-19 22:33
@tavplubix Can you share the link to this setting? Can't find it. But I still confused why it's broke after update? Is that new setting that have to be in new versions?

**Comment by tavplubix** [comment] 2022-12-19 22:44
```
select * from system.settings where name='format_schema'
```
This setting exists for more than 3 years already

**Comment by surovenko** [comment] 2022-12-20 00:26
Yes, as mentioned in [format_schema Doc](https://clickhouse.com/docs/en/interfaces/formats/#formatschema) I set [format_schema_path](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#server_configuration_parameters-format_schema_path) because I using [HTTP interface](https://clickhouse.com/docs/en/interfaces/http) for inserting.

**Comment by tavplubix** [comment] 2022-12-20 12:25
The question is about `format_schema`, not about `format_schema_path`

**Comment by surovenko** [comment] 2022-12-20 13:39
@tavplubix Yes, I have fill this settings. My query: `INSERT INTO event FORMAT Protobuf SETTINGS format_schema='event.proto:Event'`

And it stopped working just after update. If it worked before, I expect it to continue to work.

**Comment by tavplubix** [comment] 2022-12-20 13:55
Thank you, now it's clear. For some reason the setting from `SETTINGS` clause of `INSERT` query is not applied, so `format_schema` remains empty:
https://github.com/ClickHouse/ClickHouse/blob/9990abb76afad4ac7c65895976d777ded0ca9d1c/src/Formats/FormatSchemaInfo.cpp#L32-L34

Workaround: pass the setting through request parameters:
```
[tavplubix@dell9510 tests]$ echo "INSERT INTO test FORMAT Protobuf" | curl -Ssg "http://127.0.0.1:8123/?query" -d @-
Code: 36. DB::Exception: The format Protobuf requires a schema. The corresponding setting should be set. (BAD_ARGUMENTS) (version 22.12.1.1)
[tavplubix@dell9510 tests]$ echo "INSERT INTO test FORMAT Protobuf SETTINGS format_schema='test42'" | curl -Ssg "http://127.0.0.1:8123/?query" -d @-
Code: 36. DB::Exception: The format Protobuf requires a schema. The corresponding setting should be set. (BAD_ARGUMENTS) (version 22.12.1.1)
[tavplubix@dell9510 tests]$ echo "INSERT INTO test FORMAT Protobuf" | curl -Ssg "http://127.0.0.1:8123/?query&format_schema=test42" -d @-
Code: 36. DB::Exception: Format schema requires the 'format_schema' setting to have the 'schema_file:message_name' format, e.g. 'schema.proto:Message'. Got 'test42'. (BAD_ARGUMENTS) (version 22.12.1.1)
[tavplubix@dell9510 tests]$ echo "INSERT INTO test FORMAT Protobuf" | curl -Ssg "http://127.0.0.1:8123/?query&format_schema=event.proto:Event" -d @-
Code: 434. DB::Exception: Cannot parse 'event.proto' file, found an error at line -1, column 0, File not found. (CANNOT_PARSE_PROTOBUF_SCHEMA) (version 22.12.1.1)
```

**Comment by Avogar** [comment] 2022-12-20 16:00
It's not a bug, we forbidded using `SETTINGS` clause after `FORMAT` clause, because all data after `FORMAT` clause should be interpreted as data in specifyed format.
So you should use query:
```
INSERT INTO event SETTINGS format_schema='event.proto:Event'  FORMAT Protobuf
```

See https://github.com/ClickHouse/ClickHouse/pull/35883.

**Comment by tavplubix** [comment] 2022-12-20 16:36
Yep, you're right, thanks for the help. But it's misleading that it's just silently ignored, it would be great to have some warning about that (we can check if `FORMAT` is followed by `SETTINGS` without extracting `SETTINGS` from the buffer)

**Comment by Avogar** [comment] 2022-12-20 16:39
>  it would be great to have some warning about that 

Agree, but it's not obvious, because we cannot distinguish `SETTINGS ...` from actual data.
For example:
```
avogar-dev :) create table test (x String) engine=Memory

CREATE TABLE test
(
    `x` String
)
ENGINE = Memory

Query id: 3b69e0a7-8e02-44a6-ae53-8ed1a0ba7ede

Ok.

0 rows in set. Elapsed: 0.001 sec.

avogar-dev :) insert into test format TSV SETTINGS format_schema='event.proto:Event'

INSERT INTO test FORMAT TSV

Query id: da149c54-a479-4d3e-87fe-41dccac4800a

Ok.

1 row in set. Elapsed: 0.017 sec.

avogar-dev :) select * from test

SELECT *
FROM test

Query id: 00ea9ccd-88d3-435b-9161-d0aaa144dcda

┌─x──────────────────────────────────────────┐
│ SETTINGS format_schema='event.proto:Event' │
└────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

And even when we have data from stdin, we allow inserting both from query and from stdin:

```
$ echo "Hello, world!" | ch-client -q "insert into test format TSV Hello, World!"
$ ch-client -q "select * from test"
Hello, World!
Hello, world!
```

**Comment by Avogar** [comment] 2022-12-20 16:41
Or you ment just add a warning in server log and still parse this part of query as data?
This is make sense, it will be good to do

**Comment by tavplubix** [comment] 2022-12-20 16:46
Yep, there are two options:
 - Print a warning in server log unconditionally (I don't care about false positives when data actually starts with "SETTINGS")
 - Introduce a setting like `allow_suspicious_data_after_format_clause` (disabled by default). Throw exception if the setting is disabled and data starts with "SETTINGS"

The second option is better, but it's too late for it, we should have implemented it initially in https://github.com/ClickHouse/ClickHouse/pull/35883. For now I would prefer the first one. 

cc: @azat, @vitlibar

**Comment by surovenko** [comment] 2022-12-20 18:52
Thanks! Works for me now. But my current 22.2.2.1 version can't work with new query as new version can't work with my previous query. Strange, but ok. I'll manage it

**Comment by Avogar** [comment] 2022-12-20 18:55
I just checked that PR one more time and it contains a setting that allows previous behaviour: `allow_settings_after_format_in_insert`

**Comment by surovenko** [comment] 2022-12-20 20:47
@Avogar yes, this settings works! Thanks!
Just leave it here in case someone will google it, because there's no mention about this setting in Docs.
The setting `<allow_settings_after_format_in_insert>true</allow_settings_after_format_in_insert>` need to be fill in **users.xml** in your profile section, like **yandex.profile.default**

**Comment by Avogar** [comment] 2022-12-20 21:02
> no mention about this setting in Docs

That's interesting. There is a documentation in the PR, but it was accidentally deleted in https://github.com/ClickHouse/ClickHouse/pull/36297, I guess just because of bad resolving of merge conflict.
I will add this documentation back.

**Comment by tavplubix** [comment] 2023-02-01 11:21
It's a bit confusing that for SELECT queries it works the opposite way: https://github.com/ClickHouse/ClickHouse/issues/45880

**Comment by azat** [comment] 2023-02-03 09:32
>It's a bit confusing that for SELECT queries it works the opposite way: https://github.com/ClickHouse/ClickHouse/issues/45880

@tavplubix for SELECT should work both

```sql
:) SELECT 1 FORMAT Values SETTINGS max_ast_depth=1

SELECT 1
FORMAT Values
SETTINGS max_ast_depth = 1

Query id: 3593874a-9610-41d8-a4e6-f8611886b475


0 rows in set. Elapsed: 0.000 sec.

Received exception:
Code: 167. DB::Exception: AST is too deep. Maximum: 1. (TOO_DEEP_AST)

:) SELECT 1 SETTINGS max_ast_depth=1 FORMAT Values

SELECT 1
SETTINGS max_ast_depth = 1
FORMAT Values

Query id: 1c4b8ba3-59d5-4adb-a708-74e16f28745a


0 rows in set. Elapsed: 0.000 sec.

Received exception:
Code: 167. DB::Exception: AST is too deep. Maximum: 1. (TOO_DEEP_AST)
```

But the thing with FORMAT is different.

**Closed** 2023-12-14 19:04 UTC
Labels: unexpected behaviour
