### ISSUE TITLE
generateUUIDv4 with subquery or CTE

### ISSUE THREAD

**Issue by thedanwinner** [ClickHouse/ClickHouse#38172] opened 2022-06-17 09:06 UTC
UUID is duplicated, like it's calculated in CTE.
I expected distinct uuid for each row. 

I found such behavior using array join and generateUUIDv4 in a same query.

Why it happens and how to counter this?

Query: 
```
with cte as (
	select 1 as val, 
	[1,2,3] as arr
)
select *, generateUUIDv4()
from cte
array join arr
```
Query and output:
![image](https://user-images.githubusercontent.com/73415498/174263870-99d2851c-5383-42e5-a7de-cc73ebabbb09.png)

Clickhouse version 22.1.3.7

**Comment by tavplubix** [comment] 2022-06-17 10:14
Duplicate of #37366

**Closed by tavplubix** 2022-06-17 10:14 UTC
Labels: unexpected behaviour

**Comment by den-crane** [comment] 2022-06-17 11:27
22.6
```sql
with cte as (
	select 1 as val, 
	[1,2,3] as arr
)
select *, generateUUIDv4(arr)
from cte
array join arr 

┌─val─┬─arr─┬─generateUUIDv4(arr)──────────────────┐
│   1 │   1 │ 0ce7dd84-2ed3-4e92-b875-18a653219145 │
│   1 │   2 │ f9085dc2-7e30-420c-8a52-c2b95cc8d24d │
│   1 │   3 │ 1d960cea-30fd-46f4-950e-f1eaef58a9e4 │
└─────┴─────┴──────────────────────────────────────┘


```
