### ISSUE TITLE
wrongly convert datetime for 1970-01-01 08:00:00

### ISSUE THREAD

**Issue by hellflame** [ClickHouse/ClickHouse#12377] opened 2020-07-10 05:52 UTC
**Describe the bug**

can not convert datetime string '1970-01-01 08:00:00' to correct datetime value

```
SELECT toDateTime('1970-01-01 08:00:00', 'Asia/Shanghai')

┌─toDateTime('1970-01-01 08:00:00', 'Asia/Shanghai')─┐
│                                0000-00-00 00:00:00 │
└────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec.
```

and 1 second later

```
SELECT toDateTime('1970-01-01 08:00:01', 'Asia/Shanghai')

┌─toDateTime('1970-01-01 08:00:01', 'Asia/Shanghai')─┐
│                                1970-01-01 08:00:01 │
└────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec.
```

**How to reproduce**
* Which ClickHouse server version to use: 20.4.6.53 (official build) | ClickHouse server version 20.4.6 revision 54434
* Which interface to use, if matters : clickhouse-client
* Non-default settings, if any: default
* Queries to run that lead to unexpected result

```sql
select toDateTime('1970-01-01 08:00:00', 'Asia/Shanghai')
```

**Expected behavior**

should be `1970-01-01 08:00:00`

it will be great if timezone info is displayed or returned

and when the time is ahead of 1970-01-01 or the time is out of range, the convert will be 

```
┌─toDateTime('1970-01-01 07:00:01', 'Asia/Shanghai')─┐
│                                2106-02-07 13:28:17 │
└────────────────────────────────────────────────────┘
```

converting to `0000-00-00 00:00:00` is considerably a better acceptable choice, much easier to be marked as exception

**Comment by alexey-milovidov** [comment] 2020-07-10 06:16
The unix timespamp for 1970-01-01 08:00:00 in Asia/Shanghai is zero.
And we print zero value as all-zeros: `0000-00-00 00:00:00`.

**Comment by hellflame** [comment] 2020-07-10 08:48
`1970-01-01 08:00:00` and `1970-01-01 08:00:01` 
printed out to be 2 thousands years away, which is really unexpected =.=

**Comment by filimonov** [comment] 2020-07-10 12:00
Duplicate of #9277 #7316 #3470 #1756 etc.

**Closed by filimonov** 2020-07-10 12:00 UTC
Labels: comp-datetime, unexpected behaviour
