### ISSUE TITLE
How to use Table Functions postgresql()

### ISSUE THREAD

**Issue by ecc256** [ClickHouse/ClickHouse#29549] opened 2021-09-30 02:16 UTC
A simple query result in error:
`SQL Error [1002]: ClickHouse exception, code: 1002, host: , port: 8123; std::exception. Code: 1001, type: pqxx::feature_not_supported, e.what() = Unsupported server version; 9.0 is the minimum. (version 21.9.4.35 (official build))`
The postgresql version is 13.3, it's definitely above minimum 9.0...
How do I fix it?

**Comment by kssenii** [comment] 2021-09-30 06:14
Hi, I also checked 
```
postgres=# select version();
 PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
```
And both selects and inserts with ch postgresql table function work fine. Are you sure your version in 13.3?

**Comment by ecc256** [comment] 2021-09-30 14:24
Kseniia,
It's AWS RDS PostgreSQL (running on **aarch64**):
```
select version();
PostgreSQL 13.3 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit
```

**Comment by kssenii** [comment] 2021-11-24 21:39
Looks like this issue is because of the fact `libpq` library has some details for postgres server version discovery for different os, so with yours `AWS RDS PostgreSQL on aarch64` this results in incorrect postgres server version check, because `libpq` was detached manually from postgres repo and some defines might be unused.

I don't think this issue will be fixed, because searching libpq library (and most likely parts of it, which were not extracted from postgres repo) for the place which is the cause of this error is too much for this issue.

**Closed by kssenii** 2021-11-24 21:39 UTC
Labels: unexpected behaviour
