### ISSUE TITLE
Not able to connect clickhouse over TLS

### ISSUE THREAD

**Issue by avinash-ghadshi** [ClickHouse/ClickHouse#35270] opened 2022-03-14 14:03 UTC
**ERROR:**

#clickhouse-client --secure --port '9440' --password 'XXXXXXX' -u'clickuser' --host server1.xxxxxx.net
ClickHouse client version 22.2.3.1.
Connecting to server1.xxxxxx.net:9440 as user clickuser.
Code: 210. DB::NetException: SSL Exception: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED (server1.xxxxxxx.net:9440). (NETWORK_ERROR)

```
2022.03.14 18:48:58.192085 [ 12459 ] {} <Error> ServerErrorHandler: Code: 210. DB::NetException: SSL Exception: error:10000418:SSL routines:OPENSSL_internal:TLSV1_ALERT_UNKNOWN_CA, while reading from socket (192.168.0.101:48762). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xaebee1a in /usr/bin/clickhouse
1. DB::ReadBufferFromPocoSocket::nextImpl() @ 0x1436851a in /usr/bin/clickhouse
2. DB::TCPHandler::runImpl() @ 0x159ef871 in /usr/bin/clickhouse
3. DB::TCPHandler::run() @ 0x15a04579 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x18668b6f in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x1866afc1 in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x1881b6a9 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x18818da0 in /usr/bin/clickhouse
8. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
9. __clone @ 0xfe96d in /usr/lib64/libc-2.17.so
 (version 22.2.3.1)

```

**SETTINGS FROM /etc/clickhouse-server/config.xml**

```
    <!-- Native interface with TLS.
         You have to configure certificate to enable this interface.
         See the openSSL section below.
    -->
    <tcp_port_secure>9440</tcp_port_secure>

    <openSSL>
        <server> <!-- Used for https server AND secure tcp port -->
            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
            <certificateFile>/etc/clickhouse-server/ssl/WILDCARD_CERT/all.crt</certificateFile>
            <privateKeyFile>/etc/clickhouse-server/ssl/WILDCARD_CERT/test_ou.key</privateKeyFile>
            <caConfig>/etc/clickhouse-server/ssl/WILDCARD_CERT/intermediate.crt</caConfig>
            <!-- dhparams are optional. You can delete the <dhParamsFile> element.
                 To generate dhparams, use the following command:
                  openssl dhparam -out /etc/clickhouse-server/dhparam.pem 4096
                 Only file format with BEGIN DH PARAMETERS is supported.
              -->
           <!-- <dhParamsFile>/etc/nginx/ssl/WILDCARD_CERT/postfix.dh.param</dhParamsFile> -->
           <dhParamsFile>/etc/clickhouse-server/ssl/WILDCARD_CERT/postfix.dh.param</dhParamsFile>
            <!--<verificationMode>none</verificationMode>-->
            <verificationMode>none</verificationMode>
            <loadDefaultCAFile>false</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <!--<disableProtocols>sslv2,sslv3</disableProtocols>-->
            <preferServerCiphers>true</preferServerCiphers>
        </server>

        <client> <!-- Used for connecting to https dictionary source and secured Zookeeper communication -->
            <loadDefaultCAFile>false</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <!--<disableProtocols>sslv2,sslv3</disableProtocols>-->
            <preferServerCiphers>true</preferServerCiphers>
            <!-- Use for self-signed: <verificationMode>none</verificationMode> -->
            <invalidCertificateHandler>
                <!-- Use for self-signed: <name>AcceptCertificateHandler</name> -->
                <name>RejectCertificateHandler</name>
            </invalidCertificateHandler>
        </client>
    </openSSL>

    <listen_host>127.0.0.1</listen_host>
    <listen_host>server1.xxxxxx.net</listen_host>
```

**SETTINGS FROM /etc/clickhouse-client/config.xml**
```
    <openSSL>
        <client> <!-- Used for connection to server's secure tcp port -->
            <loadDefaultCAFile>false</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
            <!-- Use for self-signed: <verificationMode>none</verificationMode> -->
            <invalidCertificateHandler>
                <!-- Use for self-signed: <name>AcceptCertificateHandler</name> -->
                <name>RejectCertificateHandler</name>
            </invalidCertificateHandler>
        </client>
    </openSSL>
```

**Comment by avinash-ghadshi** [comment] 2022-03-14 14:05
I am able to connect using openssl on same 9440 port
but not through clickhouse-client

**Comment by alexey-milovidov** [comment] 2022-03-14 23:58
Maybe duplicate of #17803 if you use CentOS or Amazon Linux.

**Comment by mlex** [comment] 2022-04-10 19:59
Can you run `openssl version -d` on your client machine? It should give you the directory with ca certificates. For example on RHEL it would be something like `OPENSSLDIR: "/etc/pki/tls"`. Append a `cert.pem` to this directory and add it as `<caConfig>` to your `/etc/clickhouse-client/config.xml`. For example
```
<openSSL>
        <client>
            <caConfig>/etc/pki/tls/cert.pem</caConfig>
            ...
```

Does this work?

**Comment by alexey-milovidov** [comment] 2022-04-19 18:07
No answer.

**Closed by alexey-milovidov** 2022-04-19 18:07 UTC
Labels: unexpected behaviour
