### ISSUE TITLE
DB::Exception: Existing table metadata in ZooKeeper differs in TTL

### ISSUE THREAD

**Issue by erste** [ClickHouse/ClickHouse#10177] opened 2020-04-10 14:50 UTC
**Describe the bug**
Performed the update from version 20.1.2.4 to 20.3.5.21, after restart clickhouse does not start.
Tried to upgrade to 20.1.6.30 or 20.1.9.54 versions, clickhouse also does not start but errors changed.

**How to reproduce**
* Version: 20.1.2.4
* OS Version: Ubuntu 18.04.1 LTS
* `CREATE TABLE` statements for all tables involved
```
CREATE DATABASE database ENGINE = Ordinary;
CREATE TABLE database.table_rpl ('mdate' Date) ENGINE = ReplicatedMergeTree('/clickhouse/tables/database/{shard}/table_rpl', '{replica}') PARTITION BY mdate ORDER BY mdate TTL mdate + toIntervalMonth(6) TO VOLUME 'old_data_volume' SETTINGS storage_policy = 'main_policy', index_granularity = 8192;
```
* Update according to documentation: https://clickhouse.tech/docs/en/operations/update/#clickhouse-update

**Expected behavior**
Clickhouse updated and restarted.

**Error message and/or stacktrace**
After update from 20.1.2.4 to 20.3.5.21:
```
2020.04.10 16:49:40.116410 [ 6785 ] {} <Error> Application: DB::Exception: Existing table metadata in ZooKeeper differs in TTL. Stored in ZooKeeper: , local: mdate + toIntervalMonth(6) TO VOLUME 'old_data_volume': Cannot attach table `database`.`table_rpl` from metadata file /var/lib/clickhouse/metadata/database/table_rpl.sql from query ATTACH TABLE table_rpl (`mdate` Date) ENGINE = ReplicatedMergeTree('/clickhouse/tables/database/{shard}/table_rpl', '{replica}') PARTITION BY mdate ORDER BY mdate TTL mdate + toIntervalMonth(6) TO VOLUME 'old_data_volume' SETTINGS storage_policy = 'main_policy', index_granularity = 8192
```
And from 20.1.2.4 to 20.1.6.30 or 20.1.9.54:
```
2020.04.10 16:46:04.323697 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 62, e.displayText() = DB::Exception: Empty query, Stack trace (when copying this message, always include the lines below):
2020.04.10 16:46:05.238882 [ 1 ] {} <Error> Application: DB::Exception: Empty query
```
Full logs: https://gist.github.com/erste/75c06f232225e03ae6fe29e1ba796381

**Additional context**
Clickhouse cluster configuration:
```
    <remote_servers incl="clickhouse_remote_servers" >
        <production>
            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>10.1.200.1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>10.1.200.2</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>10.1.200.3</host>
                    <port>9000</port>
                </replica>
            </shard>
        </production>
    </remote_servers>

    <zookeeper>
      <node index="1">
        <host>10.1.200.4</host>
        <port>2181</port>
      </node>
    </zookeeper>

    <macros>
        <replica>clickhouse1</replica>
        <shard>1</shard>
    </macros>
```
Zookeeper configuration:
```
tickTime=2000
initLimit=30000
syncLimit=10
dataDir=/var/lib/zookeeper
clientPort=2181
server.1=10.1.200.4:2888:3888
preAllocSize=131072
snapCount=3000000
leaderServes=yes
maxClientCnxns=2000
maxSessionTimeout=60000000
autopurge.snapRetainCount=10
autopurge.purgeInterval=1
standaloneEnabled=false
```

Zookeeper metadata:
```
[zk: localhost:2181(CONNECTED) 16] get /clickhouse/tables/database/1/table_rpl/replicas/clickhouse1/metadata
metadata format version: 1
date column:
sampling expression:
index granularity: 8192
mode: 0
sign column:
primary key: mdate
data format version: 1
partition key: mdate
move ttl: mdate + toIntervalMonth(6) TO VOLUME 'old_data_volume'
granularity bytes: 10485760
```

**Comment by Zer0Divis0r** [comment] 2020-05-10 23:34
@filimonov , could you please give a brief explanation of this issue? I am having a similar problem, wondering if this is somehow related.

In my case I have performed ALTER TABLE MODIFY TTL on a replica. For reasons not worth mentioning, I made DROP TABLE on that replica, and then made CRATE TABLE again to have it pulled from other replicas. But no matter what I specify in CREATE TABLE's TTL clause, it says: 

`Existing table metadata in ZooKeeper differs in TTL. Stored in ZooKeeper: reporting_date + toIntervalMonth(3) TO VOLUME 'cold', local: .`
...as if I specified and empty value in my CREATE TABLE query. CH version is 20.3.8.53.

**Comment by filimonov** [comment] 2020-05-11 05:54
I hope @excitoon can do that.

**Comment by shuttie** [comment] 2020-06-04 14:54
Experienced the same issue while upgrading from 20.1.4.14. We also did ALTER TABLE MODIFY TTL, but never dropped and recreated tables afterwards.

**Comment by oik741** [comment] 2020-06-30 21:56
Faced the same problem after upgrade from 20.1 to 20.3.10.75

**Comment by PhantomPhreak** [comment] 2020-07-27 10:52
v20.5, also have thin problem after running
```
alter table <table> MODIFY TTL <column> + interval 6 month;
```

**Comment by PhantomPhreak** [comment] 2020-07-28 05:50
I found a root cause of the problem:
in my example 
```
alter table <table> MODIFY TTL <column> + interval 6 month;
```
table `<table>` have been created using old (deprecated syntax), when TTL setting supported when using new syntax only.
I've re-created that table using new syntax with TTL and it works.

Currently, this bug causing unability of `clickhouse-server` to start up, which is quite bad (can be pretty surprising) and require manual hacks.
This can be fixed by supporting TTL expressions for tables, created in the old format, or explicitly forbidding to add TTL expressions for them.

**Comment by Zer0Divis0r** [comment] 2020-08-25 17:05
@PhantomPhreak , that's a great finding! when you say you have recreated the table, how exactly was that done? 
Let's say I want to "convert" the table and preserve the data, will that be possible without having to do INSERT FROM SELECT?

**Comment by PhantomPhreak** [comment] 2020-08-25 17:12
@Zer0Divis0r AFAIK, it’s impossible without re-inserting a data. So, i just created a new one, using new syntax, and then copied the table’s content.

**Comment by oik741** [comment] 2020-08-27 09:22
@PhantomPhreak checked my table, according to `show create table` it was created using new syntax
I think that it's more related to _format_version_ of table
In my case format_version is 1, according to code latest is 4

**Comment by simPod** [comment] 2020-09-02 06:44
@oik741 how do you find table `format_version` and how to eventually bump it?

**Comment by oik741** [comment] 2020-09-08 08:30
@simPod sry mate, my assumption was wrong, just created new MergeTree table - format_version is 1, looks like other version dedicated for something else
btw answer on your question: in data folder (eg `/var/lib/clickhouse/DB_NAME/TABLE_NAME/format_version.txt`) or in ZK metadata(example in issue description)

**Comment by filimonov** [comment] 2020-12-08 13:57
Was debugging similar issue today:
```
2020.12.08 03:19:56.018261 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 49, e.displayText() = DB::Exception: ALTER MODIFY ORDER BY of default-partitioned tables is not supported, Stack trace:
0. 0x3503c40 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x350de6f DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
2. 0x63bd388 ? /usr/bin/clickhouse
3. 0x679dc3a DB::DatabaseOrdinary::alterTable(DB::Context const&, std::string const&, DB::ColumnsDescription const&, DB::IndicesDescription const&, DB::ConstraintsDescription const&, std::function<void (DB::IAST&)> const&) /usr/bin/clickhouse
4. 0x63d66da DB::StorageReplicatedMergeTree::setTableStructure(DB::ColumnsDescription, DB::ReplicatedMergeTreeTableMetadata::Diff const&) /usr/bin/clickhouse
5. 0x63d6d0e ? /usr/bin/clickhouse
6. 0x63c1a5d DB::StorageReplicatedMergeTree::startup() /usr/bin/clickhouse
7. 0x679bc0a ? /usr/bin/clickhouse
8. 0x3546e33 ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::_List_iterator<ThreadFromGlobalPool>) /usr/bin/clickhouse
9. 0x3548c08 ThreadFromGlobalPool::ThreadFromGlobalPool<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}>(ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}&&)::{lambda()#1}::operator()() const /usr/bin/clickhouse
10. 0x3545ec3 ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/bin/clickhouse
11. 0x78c857f ? /usr/bin/clickhouse
12. 0x7fcf5a949e25 start_thread /usr/lib64/libpthread-2.17.so
13. 0x7fcf5a47334d __clone /usr/lib64/libc-2.17.so
 (version 19.16.12.49)
```

Table created in the old syntax. State in zookeeper:

```
/clickhouse/path_to_table/metadata
----------------------
metadata format version: 1
date column: logged_date
sampling expression: 
index granularity: 8192
mode: 0
sign column: 
primary key: ip, code
ttl: logged + toIntervalYear(2)


clickhouse/path_to_table/replicas/replicaname
-----------------------------------
metadata	metadata format version: 1
date column: logged_date
sampling expression: 
index granularity: 8192
mode: 0
sign column: 
primary key: ip, code
```

**Comment by OmarBazaraa** [comment] 2020-12-31 15:00
I am facing a similar issue when I try to drop an existing index:

```
DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. Cannot alter.
```

**Comment by erste** [comment] 2021-01-19 14:21
Looks like renaming **move ttl** to just **ttl** in zookeeper metadata fixes the problem:
```
[zk: localhost:2181(CONNECTED) 16] get /clickhouse/tables/database/1/table_rpl/metadata
metadata format version: 1
date column:
sampling expression:
index granularity: 8192
mode: 0
sign column:
primary key: mdate
data format version: 1
partition key: mdate
ttl: mdate + toIntervalMonth(6) TO VOLUME 'old_data_volume'
granularity bytes: 10485760
```
At least I managed to update.

**Comment by filimonov** [comment] 2021-02-11 16:37
Adding TTLs to tables created in old syntax is forbidden now: #20282 #17904 #19064

If you face that issue on the versions where it was not forbidden - most probably you will need to fix the metadata in zookeeper by editing zookeer node with some external tool (zkCli.sh / go-zkcli / zookeepercli / Zkui / ZooInspector)

**Closed** 2021-02-11 16:39 UTC
Labels: bug, comp-ttl

**Comment by laowangriji** [comment] 2021-12-03 09:45
I have the same probem. just restart the service ,then, it's ok,nice

**Comment by 11104359** [comment] 2023-10-24 09:31
what's differnt between new syntax and old one?

**Comment by 11104359** [comment] 2023-10-24 09:32
> I found a root cause of the problem: in my example
> 
> ```
> alter table <table> MODIFY TTL <column> + interval 6 month;
> ```
> 
> table `<table>` have been created using old (deprecated) syntax, when TTL setting supported when using new syntax only. I've re-created that table using new syntax with TTL and it works.
> 
> Currently, this bug causing unability of `clickhouse-server` to start up, which is quite bad (can be pretty surprising) and require manual hacks. This can be fixed by supporting TTL expressions for tables, created in the old format, or explicitly forbidding to add TTL expressions for them.

what's differnt between new syntax and old one?
