### ISSUE TITLE
encoding problem:import data from mysql with utf8 String(contains emoji) has error encode

### ISSUE THREAD

**Issue by Brucecarl** [ClickHouse/ClickHouse#18398] opened 2020-12-23 08:11 UTC
I use the official guide to import data from mysql:
``` sql
insert into test.user2
select *
from mysql('**', '**', 'user', '**', '**')
```
But it converts the UTC-8 column with error encoding。

**The clomunn value in mysql is：`颕🍬` (\u9895\uD83C\uDF6C) ,while the value in clickhouse is `颕?` (\u9895?) .** 
It seems that the value is cutted because of the emoji value. How can I fix this problem?
[Clickhouse Version] : 20.3.10.75

**Comment by alexey-milovidov** [comment] 2021-06-15 04:04
Fixed, duplicate of #19795.

**Closed by alexey-milovidov** 2021-06-15 04:04 UTC
Labels: bug
