### ISSUE TITLE
[Maybe a bug]Syntax error: Refreshable Materialized View ('append')

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#69381] opened 2024-09-09 10:36 UTC
### Question

When I use `APPEND` for refreshable_materialized_view, it threw error:

```
Hua-Lenovo-DT. :) select version()

SELECT version()

Query id: 30fb7216-b944-4ff7-b2cd-9a740ba2dbe6

   ┌─version()─┐
1. │ 24.8.4.13 │
   └───────────┘

1 row in set. Elapsed: 0.002 sec.

Hua-Lenovo-DT. :) create materialized view k refresh every 10 year append (x Int64) engine Memory empty as select x*10 as x from src

Syntax error: failed at position 50 ('append'):

create materialized view k refresh every 10 year append (x Int64) engine Memory empty as select x*10 as x from src

Expected one of: number, OFFSET, RANDOMIZE FOR, DEPENDS ON, SETTINGS, TO INNER UUID, TO, token, OpeningRoundBracket, storage definition, ENGINE, PARTITION BY, PRIMARY KEY, ORDER BY, SAMPLE BY, TTL, POPULATE, EMPTY, sql security, DEFINER, SQL SECURITY, AS

Hua-Lenovo-DT. :)
```

The version is 24.8.4.13.

When I run it at `v24.9.1.232`, it's OK. But the newest LTS docker image version is `v24.8.4.13`.

```
Hua-ASUS-PC. :) create materialized view k refresh every 10 year append (x Int64) engine Memory empty as select x*10 as x from src settings allow_experimental_refreshable_materialized_view=1

CREATE MATERIALIZED VIEW k
REFRESH EVERY 10 YEAR APPEND
(
    `x` Int64
)
ENGINE = Memory EMPTY
AS SELECT x * 10 AS x
FROM src
SETTINGS allow_experimental_refreshable_materialized_view = 1

Query id: a000d5c6-9e66-4cec-a8e9-00ff013e1b0f

Ok.

0 rows in set. Elapsed: 0.259 sec.

Hua-ASUS-PC. :) select version()

SELECT version()

Query id: 0d038757-6c7a-4b51-828d-e8f518a057e4

   ┌─version()──┐
1. │ 24.9.1.232 │
   └────────────┘

1 row in set. Elapsed: 0.005 sec.

Hua-ASUS-PC. :)
```

It's maybe a BUG.

**Comment by Algunenano** [comment] 2024-09-09 11:09
Not a bug, the feature was added in https://github.com/ClickHouse/ClickHouse/pull/58934, which will be released in 24.9

**Closed by Algunenano** 2024-09-09 11:09 UTC
Labels: question

**Comment by LGDHuaOPER** [comment] 2024-09-09 14:09
Thank you very much!

**Comment by LGDHuaOPER** [comment] 2024-09-09 14:15
Thank you very much!
