### ISSUE TITLE
get_mempolicy: Operation not permitted while running ClickHouse Server Docker Image 

### ISSUE THREAD

**Issue by f1rstone** [ClickHouse/ClickHouse#70960] opened 2024-10-23 09:54 UTC
**Describe the unexpected behaviour**
Container log is filled with "get_mempolicy: Operation not" while running ClickHouse Server Docker Image

**How to reproduce**
Just follow the steps from https://hub.docker.com/r/clickhouse/clickhouse-server/ :
1. docker pull clickhouse/clickhouse-server
2. docker run -d --name some-clickhouse-server --ulimit nofile=262144:262144 clickhouse/clickhouse-server
3. docker logs some-clickhouse-server

**Which ClickHouse server version to use:**
24.9.2.42 is being pulled with latest tag at this moment

**Expected behavior**
No error messages in the log

**Error message and/or stacktrace**
```
root@server:~# docker logs some-clickhouse-server 
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
get_mempolicy: Operation not permitted
```

**Additional context**
If you set capabilities for the container with "--cap-add=SYS_NICE --cap-add=NET_ADMIN --cap-add=IPC_LOCK" then there will be no errors. However, the [documentation](https://hub.docker.com/r/clickhouse/clickhouse-server/) says that they are optional:

![image](https://github.com/user-attachments/assets/dda7499e-1f91-4e86-89ec-ddf6e0000bcb)

 So I don't expect the log being flooded with error messages while running ClickHouse Server Docker Image without optional arguments

**Comment by oserde** [comment] 2024-10-28 11:40
Hi @f1rstone . This seems a duplicate of #68747 , which seems to be fixed by recently merged #70900

**Closed** 2024-11-10 01:42 UTC
Labels: unexpected behaviour
