### ISSUE TITLE
alter statement does not work

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#18938] opened 2021-01-11 14:10 UTC
@den-crane Hi, for Example_2, the configuration means it's a table with two shards: 
shard1: 172.16.8.151
shard2: 172.16.8.96
```xml
<clickhouse_remote_servers>
    <dtstack>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>172.16.8.151</host>
                <port>9000</port>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>172.16.8.96</host>
                <port>9000</port>
            </replica>
        </shard>
    </dtstack>
</clickhouse_remote_servers>
```

why the alter statement does not work in this kind of settings/topology?

_Originally posted by @kymtwyf in https://github.com/ClickHouse/ClickHouse/issues/16179#issuecomment-757826963_

**Comment by den-crane** [comment] 2021-01-11 14:11
1. CH version?
2. Exact error?

**Comment by kymtwyf** [comment] 2021-01-12 06:29
@den-crane 
there is a mistake in my query. I created the table via 
```sql
CREATE TABLE ep.can_not_alter on cluster 'ch' (
  `id` UInt64,
  `src_code` Nullable(String),
  `event_dt` Date
) ENGINE = ReplicatedMergeTree(
  '/clickhouse/tables/{shard}/{database}/can_not_alter',
  '{replica}'
) PARTITION BY event_dt
ORDER BY
  tuple() SETTINGS index_granularity = 8192
```
then I am trying to add column after a **wrong name**:

```
ALTER TABLE ep.can_not_alter ON CLUSTER 'ch' 
ADD COLUMN `age` Nullable(UInt64) AFTER `src_cd`
```

where the `src_code` is wrongly typed as `src_cd` and causing the error:
```
ch-3	9000	48	Cannot execute replicated DDL query	5	4
ch-5	9000	48	Cannot execute replicated DDL query	4	4
ch-2	9000	48	Cannot execute replicated DDL query	3	3
ch-4	9000	48	Cannot execute replicated DDL query	2	2
ch-1	9000	48	Cannot execute replicated DDL query	1	1
ch-0	9000	48	Cannot execute replicated DDL query	0	0
Code: 48, e.displayText() = DB::Exception: There was an error on [ch-3:9000]: Cannot execute replicated DDL query (version 20.6.5.8)
```

I think the error message is not clear enough about the root cause.  As for what is mentioned in Example_2 in https://github.com/ClickHouse/ClickHouse/issues/16179#issue-725232093 I am not able to reproduce that.

**Comment by filimonov** [comment] 2021-01-12 06:51
Do it's a duplicate of usability issue #9259

**Closed** 2021-01-12 15:01 UTC
Labels: duplicate, usability
