### ISSUE TITLE
Potential flaky behavior of inverted index with Ordinary database

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#56998] opened 2023-11-20 15:14 UTC
Flaky test contains test cases for Ordinary databases. Inverted index can be flaky in such cases.

- With Ordinary database, `Error` message returned:
  https://fiddle.clickhouse.com/5fb9d58e-aed4-4bbd-8b84-974ee87834b8

- With Atomic database, `Error` message only printed in server log:
  https://fiddle.clickhouse.com/166be7f7-782a-44f7-91f7-1fed62b39ecc

This is because DROP TABLE in Atomic databases is essentially asynchronous, the [logger does not get a thread_group](https://github.com/ClickHouse/ClickHouse/blob/0eaf83b02edbba1b99394ee566de0c5eea23bb76/src/Common/logger_useful.h#L66), thus the `Error` log is hidden from client.

**Comment by rschu1ze** [comment] 2023-11-23 20:20
Thanks for reporting. This is more or less a duplicate of #47696.

**Closed by rschu1ze** 2023-11-23 20:20 UTC
Labels: question, experimental issue
