### ISSUE TITLE
The Merge engine for tables with different columns lists

### ISSUE THREAD

**Issue by aallagulov** [ClickHouse/ClickHouse#9684] opened 2020-03-16 14:39 UTC
Hey!

We use **SummingMergeTree** for storing aggregates of our stats.
Now we need to add a new key column and looks like it's a big problem (https://github.com/ClickHouse/ClickHouse/issues/3054)

We checked the docs and found that there is the **Merge engine**, that could be used for simultaneous reads from some tables which could be useful for us (we wanted just to create a new table with a new key column and read from both old and new tables).
But it seems that it is possible to use **Merge engine** for identical tables only (or it produces exceptions like _'DB::Exception: Unknown identifier: %s'_ OR _'There is no column with name %s in table.'_)

What do you think about adding an ability from the subject?
For non-existent columns, a default value could be returned.

**Comment by den-crane** [comment] 2020-03-16 15:16
it's not a problem for a long time. CH able to extend "ORDER BY" without changing INDEX "(PRIMARY KEY)". But you need to pass `add column` and `modify order by` within single `alter`
.


create table TESTSM (A Int64, B Float64) Engine=SummingMergeTree order by A;

alter table TESTSM add column C Int64 after A, modify order by (A,C);

SHOW CREATE TABLE TESTSM

CREATE TABLE dw.TESTSM 
(`A` Int64, `C` Int64, `B` Float64) 
ENGINE = SummingMergeTree 
**PRIMARY KEY A** 
**ORDER BY (A, C)** 
SETTINGS index_granularity = 8192

!!! the index has not changed! PRIMARY KEY A
!!! ORDER BY (A, B) changed - fields by which SummingMergeTree collapses records.
!!! and this is good, long indexes of 20 fields are not needed, reduce performance and consume memory

**Comment by alexey-milovidov** [comment] 2024-09-21 20:08
Duplicate of #64864

**Closed by alexey-milovidov** 2024-09-21 20:08 UTC
Labels: duplicate, feature
