### ISSUE TITLE
Arguments of function jsonMergePatch must be strings. (ILLEGAL_COLUMN)

### ISSUE THREAD

**Issue by everkhoturov** [ClickHouse/ClickHouse#57392] opened 2023-11-30 16:39 UTC
I have table with String column **params** with valid JSON content

SQL-request reports about **Arguments of function jsonMergePatch must be strings**

```sql
clickhouse :) select jsonMergePatch(params, '{"booking": 1}') from staging.stat_bookings where toYYYYMM(timestamp) = 202309 and event_type = 'create' order by timestamp limit 1;

SELECT jsonMergePatch(params, '{"booking": 1}')
FROM staging.stat_bookings
WHERE (toYYYYMM(timestamp) = 202309) AND (event_type = 'create')
ORDER BY timestamp ASC
LIMIT 1

Query id: 203c019f-5502-49b0-9d6d-b3737b422dd3


Elapsed: 0.045 sec. 

Received exception from server (version 23.10.5):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Arguments of function jsonMergePatch must be strings. (ILLEGAL_COLUMN)
```
Contents of the **clickhouse-server.err.log**:

2023.11.30 16:37:26.131620 [ 603541 ] {43ab8eeb-fae6-4350-94d7-86b35bab3ffa} <Error> executeQuery: Code: 44. DB::Exception: Arguments of function jsonMergePatch must be strings. (ILLEGAL_COLUMN) (version 23.10.5.20 (official build)) (from 127.0.0.1:34898) (in query: select jsonMergePatch(params, '{"booking": 1}') from staging.stat_bookings where toYYYYMM(timestamp) = 202309 and event_type = 'create' order by timestamp limit 1;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cdce617 in /usr/bin/clickhouse
1. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x00000000073bb7ed in /usr/bin/clickhouse
2. DB::(anonymous namespace)::FunctionjsonMergePatch::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000a2caa7b in /usr/bin/clickhouse
3. DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000073bce2a in /usr/bin/clickhouse
4. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000073bc3ce in /usr/bin/clickhouse
5. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001146167f in /usr/bin/clickhouse
6. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000114623a2 in /usr/bin/clickhouse
7. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000011463909 in /usr/bin/clickhouse
8. DB::ActionsDAG::evaluatePartialResult(std::unordered_map<DB::ActionsDAG::Node const*, DB::ColumnWithTypeAndName, std::hash<DB::ActionsDAG::Node const*>, std::equal_to<DB::ActionsDAG::Node const*>, std::allocator<std::pair<DB::ActionsDAG::Node const* const, DB::ColumnWithTypeAndName>>>&, std::vector<DB::ActionsDAG::Node const*, std::allocator<DB::ActionsDAG::Node const*>> const&, bool) @ 0x0000000011e0f209 in /usr/bin/clickhouse
9. DB::ActionsDAG::updateHeader(DB::Block) const @ 0x0000000011e0dded in /usr/bin/clickhouse
10. DB::ExpressionTransform::transformHeader(DB::Block, DB::ActionsDAG const&) @ 0x0000000013d80ae4 in /usr/bin/clickhouse
11. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::shared_ptr<DB::ActionsDAG> const&) @ 0x0000000013ee256e in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::executeExpression(DB::QueryPlan&, std::shared_ptr<DB::ActionsDAG> const&, String const&) @ 0x00000000127d86c7 in /usr/bin/clickhouse
13. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x00000000127c4b57 in /usr/bin/clickhouse
14. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000127bead4 in /usr/bin/clickhouse
15. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000128668f6 in /usr/bin/clickhouse
16. DB::InterpreterSelectWithUnionQuery::execute() @ 0x000000001286784d in /usr/bin/clickhouse
17. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000012be259d in /usr/bin/clickhouse
18. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000012bdc41a in /usr/bin/clickhouse
19. DB::TCPHandler::runImpl() @ 0x0000000013aa15e9 in /usr/bin/clickhouse
20. DB::TCPHandler::run() @ 0x0000000013ab6059 in /usr/bin/clickhouse
21. Poco::Net::TCPServerConnection::start() @ 0x000000001658d8b4 in /usr/bin/clickhouse
22. Poco::Net::TCPServerDispatcher::run() @ 0x000000001658eab1 in /usr/bin/clickhouse
23. Poco::PooledThread::run() @ 0x000000001669a1c7 in /usr/bin/clickhouse
24. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001669845c in /usr/bin/clickhouse
25. ? @ 0x00007f84801b2ac3 in ?
26. ? @ 0x00007f8480244a40 in ?

2023.11.30 16:37:26.132492 [ 603541 ] {43ab8eeb-fae6-4350-94d7-86b35bab3ffa} <Error> TCPHandler: Code: 44. DB::Exception: Arguments of function jsonMergePatch must be strings. (ILLEGAL_COLUMN), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cdce617 in /usr/bin/clickhouse
1. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x00000000073bb7ed in /usr/bin/clickhouse
2. DB::(anonymous namespace)::FunctionjsonMergePatch::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000a2caa7b in /usr/bin/clickhouse
3. DB::IFunction::executeImplDryRun(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000073bce2a in /usr/bin/clickhouse
4. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000073bc3ce in /usr/bin/clickhouse
5. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000001146167f in /usr/bin/clickhouse
6. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x00000000114623a2 in /usr/bin/clickhouse
7. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000011463909 in /usr/bin/clickhouse
8. DB::ActionsDAG::evaluatePartialResult(std::unordered_map<DB::ActionsDAG::Node const*, DB::ColumnWithTypeAndName, std::hash<DB::ActionsDAG::Node const*>, std::equal_to<DB::ActionsDAG::Node const*>, std::allocator<std::pair<DB::ActionsDAG::Node const* const, DB::ColumnWithTypeAndName>>>&, std::vector<DB::ActionsDAG::Node const*, std::allocator<DB::ActionsDAG::Node const*>> const&, bool) @ 0x0000000011e0f209 in /usr/bin/clickhouse
9. DB::ActionsDAG::updateHeader(DB::Block) const @ 0x0000000011e0dded in /usr/bin/clickhouse
10. DB::ExpressionTransform::transformHeader(DB::Block, DB::ActionsDAG const&) @ 0x0000000013d80ae4 in /usr/bin/clickhouse
11. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::shared_ptr<DB::ActionsDAG> const&) @ 0x0000000013ee256e in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::executeExpression(DB::QueryPlan&, std::shared_ptr<DB::ActionsDAG> const&, String const&) @ 0x00000000127d86c7 in /usr/bin/clickhouse
13. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x00000000127c4b57 in /usr/bin/clickhouse
14. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000127bead4 in /usr/bin/clickhouse
15. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000128668f6 in /usr/bin/clickhouse
16. DB::InterpreterSelectWithUnionQuery::execute() @ 0x000000001286784d in /usr/bin/clickhouse
17. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000012be259d in /usr/bin/clickhouse
18. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000012bdc41a in /usr/bin/clickhouse
19. DB::TCPHandler::runImpl() @ 0x0000000013aa15e9 in /usr/bin/clickhouse
20. DB::TCPHandler::run() @ 0x0000000013ab6059 in /usr/bin/clickhouse
21. Poco::Net::TCPServerConnection::start() @ 0x000000001658d8b4 in /usr/bin/clickhouse
22. Poco::Net::TCPServerDispatcher::run() @ 0x000000001658eab1 in /usr/bin/clickhouse
23. Poco::PooledThread::run() @ 0x000000001669a1c7 in /usr/bin/clickhouse
24. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001669845c in /usr/bin/clickhouse
25. ? @ 0x00007f84801b2ac3 in ?
26. ? @ 0x00007f8480244a40 in ?

**Comment by evillique** [comment] 2023-11-30 16:54
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/56384, will be fixed in https://github.com/ClickHouse/ClickHouse/pull/57379

**Closed by evillique** 2023-11-30 16:54 UTC
Labels: potential bug
