### ISSUE TITLE
I think the merge operation will be excute when i insert、alter or optimize, Besides will the merging be executed regularly when the storage start up？And how often？ 

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21974] opened 2021-03-22 12:59 UTC

**Comment by tavplubix** [comment] 2021-04-21 11:54
Merges are executed regularly even when there are no writing queries (such as INSERT, ALTER or OPTIMIZE). There are several kinds of merges (ordinary merges, TTL merges, recompression merges) and a lot of heuristics are used to determine if some parts should be merged or not, so it's hard to tell how often background merges are executed, because it depends. If you are interested in implementation details, you can start from `MergeTreeDataMergerMutator::selectPartsToMerge(...)`.

**Comment by tavplubix** [comment] 2021-04-21 11:59
Duplicate of #21554 and #21555 and #21625

Please, do not create duplicate issues.

**Closed** 2021-04-21 12:02 UTC
Labels: duplicate, question
