### ISSUE TITLE
clickhouse select is not effect when the condition contains fixstring field

### ISSUE THREAD

**Issue by thomasbryant1024** [ClickHouse/ClickHouse#12324] opened 2020-07-09 09:53 UTC
the SQL doesn't query any data but the table has the project data ：

* select * from access_log where entity_type = 'project';

By the way, all the fixString field isn't effect.

My clickhouse version is  19.17.9.60

**Comment by filimonov** [comment] 2020-07-10 05:22
It looks like duplicate of https://github.com/ClickHouse/ClickHouse/issues/9272

**Comment by filimonov** [comment] 2020-07-10 05:24
Update to 20.4 or pad/cast the strings manually

**Closed by filimonov** 2020-07-10 05:24 UTC
Labels: duplicate, sql-compatibility, st-fixed, v19.17
