### ISSUE TITLE
Errors on building QPL Library

### ISSUE THREAD

**Issue by Tiaonmmn** [ClickHouse/ClickHouse#47877] opened 2023-03-22 09:11 UTC
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.
openSUSE 15.4
**Cmake version**
cmake version 3.25.2
**Ninja version**
1.11.1
**Compiler name and version**
clang version 15.0.7
Target: x86_64-suse-linux
Thread model: posix
InstalledDir: /usr/bin
**Full cmake and/or ninja output**
cmake config:
``` bash
cmake -D ENABLE_QPL=ON -D ENABLE_AVX2=ON -D ENABLE_AVX512=ON -D PARALLEL_COMPILE_JOBS=192 -D PARALLEL_LINK_JOBS=192 -D WERROR=OFF -D ENABLE_AVX=ON -D ENABLE_BMI=ON -D ENABLE_BMI2=ON -D ENABLE_AVX2_FOR_SPEC_OP=ON -D ENABLE_AVX512_FOR_SPEC_OP=ON -D ENABLE_SENTRY=OFF -D ENABLE_CLICKHOUSE_TEST=ON ..
```
Errors occured on building QPL library:
```
[116/3977] Building CXX object contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util/awaiter.cpp.o
FAILED: contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util/awaiter.cpp.o 
/usr/bin/ccache /usr/bin/clang++ --target=x86_64-linux-gnu --sysroot=/home/nomad/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DQPL_BADARG_CHECK -DQPL_LIB -DQPL_VERSION=\"1.0.0\" -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/home/nomad/ClickHouse/contrib/qpl-cmake -I/home/nomad/ClickHouse/contrib/qpl/sources/middle-layer -I/home/nomad/ClickHouse/contrib/qpl/include -I/home/nomad/ClickHouse/base/glibc-compatibility/memcpy -I/home/nomad/ClickHouse/contrib/qpl/sources/core-sw/include -I/home/nomad/ClickHouse/contrib/qpl/sources/core-sw/src/include -I/home/nomad/ClickHouse/contrib/qpl/sources/core-sw/src/compression/include -I/home/nomad/ClickHouse/contrib/qpl/sources/isal/include -I/home/nomad/ClickHouse/contrib/qpl/sources/isal/igzip -I/home/nomad/ClickHouse/contrib/qpl/sources/core-iaa/include -isystem /home/nomad/ClickHouse/contrib/llvm-project/libcxx/include -isystem /home/nomad/ClickHouse/contrib/llvm-project/libcxxabi/include -isystem /home/nomad/ClickHouse/contrib/libunwind/include --gcc-toolchain=/home/nomad/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -mavx -mavx2 -mavx512f -mavx512bw -mavx512vl -mbmi -mbmi2 -fasynchronous-unwind-tables -ffile-prefix-map=/home/nomad/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie   -D OS_LINUX -nostdinc++ -std=c++2b -MD -MT contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util/awaiter.cpp.o -MF contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util/awaiter.cpp.o.d -o contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util/awaiter.cpp.o -c /home/nomad/ClickHouse/contrib/qpl/sources/middle-layer/util/awaiter.cpp
In file included from /home/nomad/ClickHouse/contrib/qpl/sources/middle-layer/util/awaiter.cpp:14:
/usr/lib64/clang/15.0.7/include/intrin.h:12:15: fatal error: 'intrin.h' file not found
#include_next <intrin.h>
              ^~~~~~~~~~
1 error generated.
```

**Comment by rschu1ze** [comment] 2023-03-23 09:59
Like to check https://clickhouse.com/docs/en/sql-reference/statements/create/table#deflate_qpl and https://clickhouse.com/docs/en/development/building_and_benchmarking_deflate_qpl#Build-Clickhouse-with-DEFLATE_QPL? (both documents were added only [yesterday](https://github.com/ClickHouse/ClickHouse/pull/47745)).

**Comment by rschu1ze** [comment] 2023-03-23 12:55
@jinjunzh could you maybe help out?

**Comment by jinjunzh** [comment] 2023-03-24 02:38
> 

It probably Clang15 related because I never saw it on Clickhouse with Clang14 several months ago. Let me try to reproduce this issue and update it by then.

**Comment by jinjunzh** [comment] 2023-03-25 10:46
From the code snippet as below, it should run into the line of "<x86intrin.h>". I just wonder why the macro: linux is not defined since your OS is suse-linux:

#if defined(linux)
#include <x86intrin.h>
#else
#include <intrin.h>
#include <emmintrin.h>
#endif

**Comment by jinjunzh** [comment] 2023-03-25 14:15
The macro 'linux' probably be obsolete for  openSUSE, I need push QPL to investigate more precise macro for Linux based kernel.
As a workaround, could you try to add a compile option as below:
./ClickHouse/contrib/qpl-cmake/CMakeLists.txt
```
......
target_compile_definitions(core_iaa PRIVATE QPL_BADARG_CHECK
        PRIVATE $<$<BOOL:${BLOCK_ON_FAULT}>: BLOCK_ON_FAULT_ENABLED>
        PRIVATE $<$<BOOL:${LOG_HW_INIT}>:LOG_HW_INIT>
        PRIVATE **linux**)
......
target_compile_definitions(middle_layer_lib
        PUBLIC QPL_VERSION="${QPL_VERSION}"
        PUBLIC $<$<BOOL:${LOG_HW_INIT}>:LOG_HW_INIT>
        PUBLIC $<$<BOOL:${EFFICIENT_WAIT}>:QPL_EFFICIENT_WAIT>
        PUBLIC QPL_BADARG_CHECK
        PRIVATE **linux**)
......
```

**Comment by Tiaonmmn** [comment] 2023-03-25 15:26
I think I got it.
First,use `clang -x c++ /dev/null -dM -E` to check clang predefined macros,`linux` appeared:
```c
...
#define __x86_64 1
#define __x86_64__ 1
#define linux 1
#define unix 1
```
Second,use `clang -x c++ /dev/null -dM -E -std=c++2b ` to check clang predefined macros on C++20 ,`linux` disappeared:
```c
...
#define __x86_64 1
#define __x86_64__ 1
```
Third,use `cmake -D ENABLE_QPL=ON -D CMAKE_VERBOSE_MAKEFILE=TRUE ..` to generate full build.ninja file.Then check QPL awaiter.cpp build command line:
```
build contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util/awaiter.cpp.o: CXX_COMPILER__middle_layer_lib_unscanned_RelWithDebInfo /home/nomad/ClickHouse/contrib/qpl/sources/middle-layer/util/awaiter.cpp || cmake_object_order_depends_target_middle_layer_lib
  DEFINES = -DQPL_BADARG_CHECK -DQPL_LIB -DQPL_VERSION=\"1.0.0\" -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS
  DEP_FILE = contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util/awaiter.cpp.o.d
  FLAGS = --gcc-toolchain=/home/nomad/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -mavx -mavx2 -mavx512f -mavx512bw -mavx512vl -mbmi -mbmi2 -fasynchronous-unwind-tables -ffile-prefix-map=/home/nomad/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie -std=c++2b   -D OS_LINUX -nostdinc++
  INCLUDES = -I/home/nomad/ClickHouse/contrib/qpl-cmake -I/home/nomad/ClickHouse/contrib/qpl/sources/middle-layer -I/home/nomad/ClickHouse/contrib/qpl/include -I/home/nomad/ClickHouse/base/glibc-compatibility/memcpy -I/home/nomad/ClickHouse/contrib/qpl/sources/core-sw/include -I/home/nomad/ClickHouse/contrib/qpl/sources/core-sw/src/include -I/home/nomad/ClickHouse/contrib/qpl/sources/core-sw/src/compression/include -I/home/nomad/ClickHouse/contrib/qpl/sources/isal/include -I/home/nomad/ClickHouse/contrib/qpl/sources/isal/igzip -I/home/nomad/ClickHouse/contrib/qpl/sources/core-iaa/include -isystem /home/nomad/ClickHouse/contrib/llvm-project/libcxx/include -isystem /home/nomad/ClickHouse/contrib/llvm-project/libcxxabi/include -isystem /home/nomad/ClickHouse/contrib/libunwind/include
  OBJECT_DIR = contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir
  OBJECT_FILE_DIR = contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util
```
It appears that ClickHouse is using clang c++2b extension to build file.And the predefined `linux` macro is undefined on c++2b language extension,

**Comment by Tiaonmmn** [comment] 2023-03-25 15:32
And after I add PRIVATE linux to qpl-cmake/CMakeFiles.txt,compile succeed.

**Comment by jinjunzh** [comment] 2023-03-27 01:45
It looks the build command line may differ from build setup. 
I checked my build.ninja file as well. It use '-std=gnu++2b' which means macro:linux is defined

> clang -x c++ /dev/null -dM -E -std=gnu++2b | grep linux
> ......
> #define linux 1

await.cpp in my build.ninja:
`build contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util/awaiter.cpp.o: CXX_COMPILER__middle_layer_lib_RelWithDebInfo /home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl/sources/middle-layer/util/awaiter.cpp || cmake_object_order_depends_target_middle_layer_lib
  DEFINES = -DHAS_RESERVED_IDENTIFIER -DLINUX_MACRO_TEST -DQPL_BADARG_CHECK -DQPL_LIB -DQPL_VERSION=\"1.0.0\" -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS
  DEP_FILE = contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util/awaiter.cpp.o.d
  FLAGS = --gcc-toolchain=/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -mavx -mavx2 -mavx512f -mavx512bw -mavx512vl -mbmi -mbmi2 -fasynchronous-unwind-tables -ffile-prefix-map=/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie   -D OS_LINUX -nostdinc++ -std=gnu++2b
  INCLUDES = -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl-cmake -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl/sources/middle-layer -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl/include -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/base/glibc-compatibility/memcpy -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl/sources/core-sw/include -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl/sources/core-sw/src/include -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl/sources/core-sw/src/compression/include -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl/sources/isal/include -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl/sources/isal/igzip -I/home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/qpl/sources/core-iaa/include -isystem /home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/llvm-project/libcxx/include -isystem /home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/llvm-project/libcxxabi/include -isystem /home/jasper/src_clickhouse/ups_doc_clickhouse/ClickHouse/contrib/libunwind/include
  OBJECT_DIR = contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir
  OBJECT_FILE_DIR = contrib/qpl-cmake/CMakeFiles/middle_layer_lib.dir/__/qpl/sources/middle-layer/util`

**Comment by jinjunzh** [comment] 2023-03-27 01:53
@rschu1ze do you have any more suggestions on this issue?

**Comment by rschu1ze** [comment] 2023-03-28 19:53
Sorry for the delay. In general, when I run `clang -x c++ /dev/null -dM -E`,
- with `-std=c++14` (`c++17`/`c++20`), *no* `linux` define exists,
- with `-std=gnu++14` (`gnu++17`/`gnu++20`), the `linux` define *does* exists,
- w/o further arguments, the "gnu" behavior is assumed, meaning the `linux` define *does* exist.

In general, `__linux__` (which is defined in all cases) seems the recommended way of checking for Linux (see [here](https://stackoverflow.com/a/4605893) and [here](https://stackoverflow.com/a/5920028)). So that would need to be fixed in QPL \+ pushed as a submodule update to ClickHouse (@jinjunzh would you like to do that). Until then, aforementioned workaround can be used.

> It looks the build command line may differ from build setup. I checked await.cpp in my build.ninja file as well. It uses '-std=gnu++2b' instead of '-std=c++2b' which means macro:linux is defined
> 
> > clang -x c++ /dev/null -dM -E -std=gnu++2b | grep linux
> > ......
> > #define linux 1

I am pretty sure this is caused by #47651 which compiles everything with `-std=c++2b` instead of `-std=gnu++2b`. So to make things work for you, you could roll back this PR locally as well.

**Comment by jinjunzh** [comment] 2023-03-29 03:58
QPL developer is working on fix this issue by using __linux__ instead. Once ready, I will create PR to update QPL submodule.

**Closed** 2023-04-26 21:31 UTC
Labels: build

**Comment by Tiaonmmn** [comment] 2023-04-28 02:30
I don't think it's finished.Recently ClickHouse add ISA-L library to support HDFS erasure codec,which conflict with QPL

**Comment by jinjunzh** [comment] 2023-04-28 03:03
> I don't think it's finished.Recently ClickHouse add ISA-L library to support HDFS erasure codec,which conflict with QPL

Thanks for your feedback, I'll look into it further

**Comment by rschu1ze** [comment] 2023-04-28 09:39
I opened #49296 for the new issue. The original problem is fixed.
