### ISSUE TITLE
query zstd parquet file error

### ISSUE THREAD

**Issue by mofei920** [ClickHouse/ClickHouse#53028] opened 2023-08-04 06:11 UTC
clickhouse-local version: ClickHouse local version 23.7.1.2470 (official build)
mysql: 8.0.28

```sql
CREATE TABLE archive_test (
  id bigint unsigned NOT NULL,
  c1 bigint NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

INSERT INTO `archive_test` (`id`, `c1`)
VALUES
	(1, 11),
	(2, 12),
	(3, 13);
```

export data into parquet file in s3 successfully.
```
# clickhouse-local -q "SET output_format_parquet_row_group_size = 10240, output_format_parquet_compression_method='zstd'; INSERT INTO FUNCTION s3('http://bucket_name.oss_addr/mysql_archive.parquet', 'ak', 'sk') select id, c1 from mysql('mysql_hostname:3306','dbtest','archive_test','username','password')"
```
query from the parquet file。
```
# clickhouse-local -q "select count(*) FROM s3('http://bucket_name.oss_addr/mysql_archive.parquet', 'ak', 'sk')"
```
I get the error as below. but it's no problem when use output_format_parquet_compression_method=lz4. is it a bug？
```
Code: 33. DB::ParsingException: Error while reading Parquet data: IOError: ZSTD decompression failed: Restored data doesn't match checksum: While executing ParquetBlockInputFormat: While executing OSS. (CANNOT_READ_ALL_DATA)
```

**Comment by alexey-milovidov** [comment] 2023-08-04 11:52
How to reproduce?

**Comment by mofei920** [comment] 2023-08-04 12:01
export into outfile, and query the file, get the same error.
```
# clickhouse-local -q "SET output_format_parquet_row_group_size = 10240, output_format_parquet_compression_method='zstd'; select id, c1 from mysql('mysql_hostname:3306','dbtest','archive_test','username','password') into outfile 'mysql_archive.parquet'"

# clickhouse-local -q "select count(*) FROM file('mysql_archive.parquet')"
Code: 33. DB::ParsingException: Error while reading Parquet data: IOError: ZSTD decompression failed: Restored data doesn't match checksum: While executing ParquetBlockInputFormat: While executing File. (CANNOT_READ_ALL_DATA)
```

**Comment by Avogar** [comment] 2023-08-04 12:09
Can you check if this file can be read by other tool like pythin arrow? Maybe the problem is in custom encoder added recently, try to disable `output_format_parquet_use_custom_encoder` while generating the file

**Comment by Avogar** [comment] 2023-08-04 13:35
> Do I need to enable output_format_parquet_use_custom_encoder in the future clickhouse version? Have a plan?

It was added recently, so it can contain some bugs. But it improves output Parquet performance a lot. I think any found bugs will be fixed and backported quite fast by @al13n321.

**Comment by al13n321** [comment] 2023-08-04 21:45
https://github.com/ClickHouse/ClickHouse/pull/53064 should fix it, thanks for reporting!

**Closed** 2023-08-05 10:35 UTC
Labels: st-need-info, potential bug
