### ISSUE TITLE
Partition pruning not working as expected

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#7948] opened 2019-11-27 16:59 UTC
**How to reproduce**
* Which ClickHouse server version to use: v19.17.2.4-testing

```sql
DROP TABLE IF EXISTS test_partition_filtering;

CREATE TABLE test_partition_filtering (
    `timestamp` DateTime,
    zoneId UInt64
) ENGINE = MergeTree() 
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (zoneId, timestamp);

INSERT INTO test_partition_filtering
SELECT
  toUInt64(now())-1000*number/1000 as timestamp,
  number/1000 as zone
FROM numbers(1000000);

OPTIMIZE TABLE test_partition_filtering final;

SELECT count() FROM test_partition_filtering WHERE toDate(toStartOfDay(timestamp)) = today() and zoneId=42;
SELECT count() FROM test_partition_filtering WHERE toDate(timestamp) = today() AND zoneId = 42;
```

**Expected behavior**
Expect both SELECTS to prune partitions and to read just a single part.

**Actual behavior**
First query reads one part. Second query reads 12 parts.

**Logs**

```
executeQuery: (from 127.0.0.1:48812) SELECT count() FROM test_partition_filtering WHERE (toDate(toStartOfDay(timestamp)) = today()) AND (zoneId = 42)
InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "toDate(toStartOfDay(timestamp)) = today()" moved to PREWHERE
default.test_partition_filtering (SelectExecutor): Key condition: (column 0 in [42, 42]), (toDate(toStartOfDay(column 1)) in [18227, 18227]), and
default.test_partition_filtering (SelectExecutor): MinMax index condition: unknown, (toDate(toStartOfDay(column 0)) in [18227, 18227]), and
default.test_partition_filtering (SelectExecutor): Selected 1 parts by date, 1 parts by key, 1 marks to read from 1 ranges



executeQuery: (from 127.0.0.1:48812) SELECT count() FROM test_partition_filtering WHERE (toDate(timestamp) = today()) AND (zoneId = 42)
InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "toDate(timestamp) = today()" moved to PREWHERE
default.test_partition_filtering (SelectExecutor): Key condition: (column 0 in [42, 42]), (toDate(column 1) in [18227, 18227]), and
default.test_partition_filtering (SelectExecutor): MinMax index condition: unknown, (toDate(column 0) in [18227, 18227]), and
default.test_partition_filtering (SelectExecutor): Selected 12 parts by date, 1 parts by key, 1 marks to read from 1 ranges
```

**Comment by victor-perov** [comment] 2019-11-27 17:02
Is it reproducible on a stable version as well?

**Comment by nvartolomei** [comment] 2019-11-27 17:36
@victor-perov 19.17.2.4-testing is a stable version even though `system.build_options` reports it as testing.

**Comment by den-crane** [comment] 2019-11-27 18:20
each part has min_max_timestamp.idx file.
This file stores  max & min values of timestamp column over this part.

pruning works with where timestamp > = < 
pruning does not work with function(timestamp) > = <

**Comment by den-crane** [comment] 2019-11-27 19:34
Though maybe I am wrong.

```
CREATE TABLE test_partition_filtering (
    timestamp DateTime) ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY tuple();

INSERT INTO test_partition_filtering SELECT '2019-01-01 10:00:00' FROM numbers(1000000);
INSERT INTO test_partition_filtering SELECT '2019-01-02 10:00:00' FROM numbers(1000000);
INSERT INTO test_partition_filtering SELECT toDateTime(today())+3600 FROM numbers(1000000);

select count() from test_partition_filtering where toDate((timestamp)) = today();
Processed 1.00 million rows,

select count() from test_partition_filtering where toDate((timestamp)) = today();
Processed 1.00 million rows
```

**Comment by victor-perov** [comment] 2019-12-09 13:53
It would be nice to get an update on the issue.

**Comment by hagen1778** [comment] 2020-01-15 11:38
I'm hitting the same issue. Is there any updates?

**Comment by den-crane** [comment] 2020-09-24 23:37
related: https://github.com/ClickHouse/ClickHouse/issues/15255

```
20.10.1.4704.

SELECT count() FROM test_partition_filtering WHERE toDate(timestamp) = today() AND zoneId = 42;
Selected 1 parts by date, 1 parts by key, 1 marks by primary key, 1 marks to read from 1 ranges
Processed 8.19 thousand rows

SELECT count() FROM test_partition_filtering WHERE toDate(timestamp) = today() AND zoneId = 42;
Selected 1 parts by date, 1 parts by key, 1 marks by primary key, 1 marks to read from 1 ranges
Processed 8.19 thousand rows

```

**Comment by amosbird** [comment] 2020-09-25 03:45
It's fixed in https://github.com/ClickHouse/ClickHouse/pull/13497 . And `toDate(timestamp_ms / 1000) ` will also work because of  https://github.com/ClickHouse/ClickHouse/pull/14513 .

**Closed** 2020-09-25 04:02 UTC
Labels: bug, performance

**Comment by vitalvi** [comment] 2021-04-29 04:29
Should partition pruning work with functions comming from CTE, for example:
```
with toDate('2019-01-02') as dt　select count() from test_partition_filtering　where toDate((timestamp)) = dt;

1 rows in set. Elapsed: 0.025 sec. Processed 3.00 million rows, 12.00 MB (120.75 million rows/s., 483.00 MB/s.)

```
Is this expected that 3 million rows have been processed in this case?

**Comment by amosbird** [comment] 2021-04-29 04:35
> Should partition pruning work with functions comming from CTE, for example:
> 
> ```
> with toDate('2019-01-02') as dt　select count() from test_partition_filtering　where toDate((timestamp)) = dt;
> 
> 1 rows in set. Elapsed: 0.025 sec. Processed 3.00 million rows, 12.00 MB (120.75 million rows/s., 483.00 MB/s.)
> ```
> 
> Is this expected that 3 million rows have been processed in this case?

This is not CTE but scalar alias. It should work. Please share a minimal reproduceable test case.

**Comment by vitalvi** [comment] 2021-04-29 05:01
I use the same table definition and data as provided above:
```
CREATE TABLE test_partition_filtering (
    timestamp DateTime) ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY tuple();

INSERT INTO test_partition_filtering SELECT '2019-01-01 10:00:00' FROM numbers(1000000);
INSERT INTO test_partition_filtering SELECT '2019-01-02 10:00:00' FROM numbers(1000000);
INSERT INTO test_partition_filtering SELECT toDateTime(today())+3600 FROM numbers(1000000);

with toDate('2019-01-02') as dt　select count() from test_partition_filtering　where toDate((timestamp)) = dt;

1 rows in set. Elapsed: 0.025 sec. Processed 3.00 million rows, 12.00 MB (120.75 million rows/s., 483.00 MB/s.)
```

**Comment by amosbird** [comment] 2021-04-29 06:05
It's already fixed in https://github.com/ClickHouse/ClickHouse/pull/21766

**Comment by vitalvi** [comment] 2021-04-29 06:27
ohh, pretty new one. Yes, with the latest version it works as expected. Sorry for the noise and thank you @amosbird
