### ISSUE TITLE
ClickHouse crashed (Segmentation fault) and can't start after that

### ISSUE THREAD

**Issue by vklimenkov** [ClickHouse/ClickHouse#16946] opened 2020-11-12 19:17 UTC
Clickhouse-server crashed after use ALTER TABLE on replica. There was network traffic surge, and in log:

> 2020.11.12 12:40:29.895664 [ 26936 ] {} <Fatal> BaseDaemon: ########################################
> 2020.11.12 12:40:29.895884 [ 26936 ] {} <Fatal> BaseDaemon: (version 20.10.3.30 (official build), build id: 4EAF0337F53BC2B4) (from thread 26935) (query_id: 71a0dc3b-9e55-4d49-9312-b8a1
> de6a027e) Received signal Segmentation fault (11)
> 2020.11.12 12:40:29.895951 [ 26936 ] {} <Fatal> BaseDaemon: Address: 0xfffffffffffffff0 Access: read. Address not mapped to object.
> 2020.11.12 12:40:29.896037 [ 26936 ] {} <Fatal> BaseDaemon: Stack trace: 0xdec92a9 0xdec7dbd 0xe568ea6 0xe575ca7 0x10d4dd6f 0x10d4f77e 0x10e80a39 0x10e7c96a 0x7f180ee80fa3 0x7f180eda24c
> f
> 2020.11.12 12:40:29.896135 [ 26936 ] {} <Fatal> BaseDaemon: 2. ? @ 0xdec92a9 in /usr/bin/clickhouse
> 2020.11.12 12:40:29.896234 [ 26936 ] {} <Fatal> BaseDaemon: 3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context
> &, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdec7dbd in /usr/bin/clickhouse
> 2020.11.12 12:40:29.896300 [ 26936 ] {} <Fatal> BaseDaemon: 4. DB::TCPHandler::runImpl() @ 0xe568ea6 in /usr/bin/clickhouse
> 2020.11.12 12:40:29.896362 [ 26936 ] {} <Fatal> BaseDaemon: 5. DB::TCPHandler::run() @ 0xe575ca7 in /usr/bin/clickhouse
> 2020.11.12 12:40:29.896450 [ 26936 ] {} <Fatal> BaseDaemon: 6. Poco::Net::TCPServerConnection::start() @ 0x10d4dd6f in /usr/bin/clickhouse
> 2020.11.12 12:40:29.896526 [ 26936 ] {} <Fatal> BaseDaemon: 7. Poco::Net::TCPServerDispatcher::run() @ 0x10d4f77e in /usr/bin/clickhouse
> 2020.11.12 12:40:29.896590 [ 26936 ] {} <Fatal> BaseDaemon: 8. Poco::PooledThread::run() @ 0x10e80a39 in /usr/bin/clickhouse
> 2020.11.12 12:40:29.896632 [ 26936 ] {} <Fatal> BaseDaemon: 9. Poco::ThreadImpl::runnableEntry(void*) @ 0x10e7c96a in /usr/bin/clickhouse
> 2020.11.12 12:40:29.896706 [ 26936 ] {} <Fatal> BaseDaemon: 10. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
> 2020.11.12 12:40:29.896792 [ 26936 ] {} <Fatal> BaseDaemon: 11. __clone @ 0xf94cf in /lib/x86_64-linux-gnu/libc-2.28.so

After that I can't start it via "sudo service clickhouse-server start", it writes into log:

> 2020.11.12 21:53:41.659345 [ 2427 ] {} <Error> bool DB::(anonymous namespace)::checkPermissionsImpl(): Code: 412, e.displayText() = DB::Exception: Can't receive Netlink response: error -2, Stack trace (when copying this message, always include the lines below):
> 
> 0. ? @ 0x7b7d0a9 in /usr/bin/clickhouse
> 1. ? @ 0x7b7d1e8 in /usr/bin/clickhouse
> 2. DB::TaskStatsInfoGetter::TaskStatsInfoGetter() @ 0x7b7cb67 in /usr/bin/clickhouse
> 3. ? @ 0x7b7c9c6 in /usr/bin/clickhouse
> 4. DB::TaskStatsInfoGetter::checkPermissions() @ 0x7b7c966 in /usr/bin/clickhouse
> 5. DB::TasksStatsCounters::create(unsigned long) @ 0x7b745fd in /usr/bin/clickhouse
> 6. DB::ThreadStatus::initPerformanceCounters() @ 0xde7fcae in /usr/bin/clickhouse
> 7. DB::ThreadStatus::setupState(std::__1::shared_ptr<DB::ThreadGroupStatus> const&) @ 0xde7f8c8 in /usr/bin/clickhouse
> 8. DB::ThreadStatus::initializeQuery() @ 0xde800c0 in /usr/bin/clickhouse
> 9. DB::CurrentThread::initializeQuery() @ 0xde81b0b in /usr/bin/clickhouse
> 10. DB::BackgroundProcessingPool::workLoopFunc() @ 0xe294ef7 in /usr/bin/clickhouse
> 11. ? @ 0xe295683 in /usr/bin/clickhouse
> 12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8963d in /usr/bin/clickhouse
> 13. ? @ 0x7b8d153 in /usr/bin/clickhouse
> 14. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
> 15. __clone @ 0xf94cf in /lib/x86_64-linux-gnu/libc-2.28.so
>  (version 20.10.3.30 (official build))
> 2020.11.12 21:53:41.923581 [ 2418 ] {} <Error> Application: Caught exception while loading metadata: Code: 122, e.displayText() = DB::Exception: Table columns structure in ZooKeeper is different from local table structure: Cannot attach table `default`

And sometime there are <Fatal> errors like the first one, whith message "signal Segmentation fault (11)"

How to fix it and start Clickhouse-Server?

**Comment by filimonov** [comment] 2020-11-12 21:58
1) for segfault - please look for a query which lead to the error - grep 71a0dc3b-9e55-4d49-9312-b8a1
de6a027e

2) for netlink error - may be you run in docker w/o CAP_NET_ADMIN (but Afair it should not be a fatal error)

3) about non-starting clickhouse - it seems there is an issue with loading one of the tables. Try to move somewhere aside metadata file for that table and try to start the server w/o that table (/var/lib/clickhouse/metadata)

**Comment by filimonov** [comment] 2020-11-13 11:18
```
addr2line -afiCe /usr/bin/clickhouse 0xdec92a9 0xdec7dbd 0xe568ea6 0xe575ca7 0x10d4dd6f 0x10d4f77e 0x10e80a39 0x10e7c96a 0x7f180ee80fa3 0x7f180eda24c
0x000000000dec92a9 
DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*)
/build/obj-x86_64-linux-gnu/../contrib/libcxxabi/src/private_typeinfo.cpp:?
DB::QueryPipeline::setProgressCallback(std::__1::function<void (DB::Progress const&)> const&)
/build/obj-x86_64-linux-gnu/../src/Processors/QueryPipeline.cpp:309
DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*)
/build/obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:454

0x000000000dec7dbd
DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool)
/build/obj-x86_64-linux-gnu/../src/Interpreters/executeQuery.cpp:718

0x000000000e568ea6
DB::TCPHandler::runImpl()
/build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:?

0x000000000e575ca7
DB::CurrentThread::getGroup()
/build/obj-x86_64-linux-gnu/../src/Common/CurrentThread.cpp:96
DB::TCPHandler::run()
/build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1313

0x0000000010d4dd6f
Poco::Net::TCPServerConnection::start()
/build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57

0x0000000010d4f77e
int std::__1::__cxx_atomic_fetch_sub<int>(std::__1::__cxx_atomic_base_impl<int>*, int, std::__1::memory_order)
/build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:1036
std::__1::__atomic_base<int, true>::fetch_sub(int, std::__1::memory_order)
/build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:1581
std::__1::__atomic_base<int, true>::operator--()
/build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:1616
Poco::Net::TCPServerDispatcher::endConnection()
/build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:226
Poco::Net::TCPServerDispatcher::run()
/build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115

0x0000000010e80a39
ScopedLock
/build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/ScopedLock.h:36
Poco::PooledThread::run()
/build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/ThreadPool.cpp:213

0x0000000010e7c96a
Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
/build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:156
Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
/build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/SharedPtr.h:208
Poco::ThreadImpl::runnableEntry(void*)
/build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Thread_POSIX.cpp:360

0x00007f180ee80fa3
??
??:0

0x000007f180eda24c
??
??:0
```

**Comment by filimonov** [comment] 2020-11-13 11:23
https://github.com/ClickHouse/ClickHouse/blob/v20.10.3.30-stable/src/Processors/QueryPipeline.cpp#L309
https://github.com/ClickHouse/ClickHouse/blob/v20.10.3.30-stable/src/Interpreters/executeQuery.cpp#L454

**Comment by alesapin** [comment] 2020-11-13 15:42
Possibly related: https://github.com/ClickHouse/ClickHouse/pull/16968

**Comment by vklimenkov** [comment] 2020-11-13 16:19
> 1. for segfault - please look for a query which lead to the error - grep 71a0dc3b-9e55-4d49-9312-b8a1
> de6a027e

I can't find this query in /var/log/clickhouse-server/clickhouse-server.log. And I tried this way:

`select * from system.query_log where query_id='71a0dc3b-9e55-4d49-9312-b8a1de6a027e'\G`

empty result :(

> 3. about non-starting clickhouse - it seems there is an issue with loading one of the tables. Try to move somewhere aside metadata file for that table and try to start the server w/o that table (/var/lib/clickhouse/metadata)

It works! I removed 1 table metadata and ClickHouse started. Thank you.
Do you need some more information about this issue?

**Comment by filimonov** [comment] 2020-11-14 12:33
If you can share the fragment if logs just before the crash it can help us. 

For example 
```
grep '##########' -B 3000 -A 500 /var/log/clickhouse-server/clickhouse-server.log > ~/log_fragment.txt
```

**Comment by vklimenkov** [comment] 2020-11-14 19:31
Log fragment attached
[log_fragment.txt.gz](https://github.com/ClickHouse/ClickHouse/files/5541343/log_fragment.txt.gz)

**Comment by alesapin** [comment] 2020-11-16 13:12
> Log fragment attached
> [log_fragment.txt.gz](https://github.com/ClickHouse/ClickHouse/files/5541343/log_fragment.txt.gz)

Unfortunately log level is too silent, no query which leads to crash, but there are a lot of errors:
```
2020.11.12 12:40:29.860175 [ 24881 ] {} <Error> default.view_tizer: auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 246, e.displayText() = DB::Exception: Bad size of marks file '/var/lib/clickhouse/data/default/view_tizer/20201111_189647_189669_1/data.mrk3': 560, must be: 5712, Stack trace (when copying this message, always include the lines below):

```
cc @CurtizJ

**Comment by alexey-milovidov** [comment] 2021-04-28 04:25
The issue is fixed in recent releases.

**Closed by alexey-milovidov** 2021-04-28 04:25 UTC
Labels: crash, question
