### ISSUE TITLE
SIGSEGV (Address Boundary Error) Encountered with ClickHouse Version 23.x, 24.1.8.22 and 24.3.1.2672

### ISSUE THREAD

**Issue by kython28** [ClickHouse/ClickHouse#62130] opened 2024-04-01 11:23 UTC
Describe what's wrong: The application crashes unexpectedly, showing a SIGSEGV (Segmentation Fault) error. This behavior is not expected under normal operation. Ideally, the application should handle all operations without encountering such critical errors.

Does it reproduce on the most recent release? Yes... Version 24.1.8.22 and 24.3.1.2672

Enable crash reporting: Already done

How to reproduce: I don't have idea.

Expected behavior: Clearly, the expectation is that the application runs without crashing and handles its operations smoothly. Any deviation from this, such as a segmentation fault, is a significant issue that needs addressing.

Additional context: The database has been running smoothly for months under version 23 without any issues. However, it unexpectedly collapsed today. In an attempt to resolve the issue, I upgraded to the latest stable version, but unfortunately, this did not rectify the problem. After that, I restarted the server, and things seemed to work fine for a while, but then it crashed again after some time. It appears the exception occurs when attempting to interact with a specific table.

Here the table's structure:

```SQL
CREATE TABLE <db>.<table>
(
    `token` String,
    `<...>` String,
    `action_type` Enum8('notification' = 1, 'request' = 2),
    `<...>` Enum8('<...>' = 1, '<...>' = 2, '<...>' = 3),
    `created_at` DateTime DEFAULT now(),
    `updated_at` DateTime DEFAULT now(),
    `action_config` Object('json'),
    `<...>` Object('json')
)
ENGINE = MergeTree
PRIMARY KEY tuple(token)
ORDER BY token
SETTINGS index_granularity = 8192
```

Here the first one Exception message:

```
2024.04.01 08:30:09.210899 [ 4091328 ] {} <Trace> BaseDaemon: Received signal 11
2024.04.01 08:30:09.212493 [ 4092052 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.04.01 08:30:09.212628 [ 4092052 ] {} <Fatal> BaseDaemon: (version 24.1.8.22 (official build), build id: E7D70C34BD5A8A71905F967C3B5390736B3AC27C, git hash: 7fb8f96d3da26cbcd42aa967a9f06b8a780de351) (from thread 4091917) Received signal 11
2024.04.01 08:30:09.212684 [ 4092052 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.04.01 08:30:09.212715 [ 4092052 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.04.01 08:30:09.212732 [ 4092052 ] {} <Fatal> BaseDaemon: Stack trace: 0x00000000108d3dd7 0x00000000108d2431 0x00000000123582b3 0x0000000012369769 0x000000001235fd0b 0x0000000012365459 0x0000000012742557 0x0000000012377984 0x000000000c8eee41 0x000000000c8f267a 0x000000000c8f147e 0x00007f9627783ac3 0x00007f9627815850
2024.04.01 08:30:09.212766 [ 4092052 ] {} <Fatal> BaseDaemon: ########################################
2024.04.01 08:30:09.212793 [ 4092052 ] {} <Fatal> BaseDaemon: (version 24.1.8.22 (official build), build id: E7D70C34BD5A8A71905F967C3B5390736B3AC27C, git hash: 7fb8f96d3da26cbcd42aa967a9f06b8a780de351) (from thread 4091917) (query_id: e316a5aa-55b5-46ed-92b5-4b45d69b808c::all_3_9_1_7) (query: ) Received signal Segmentation fault (11)
2024.04.01 08:30:09.212809 [ 4092052 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.04.01 08:30:09.212829 [ 4092052 ] {} <Fatal> BaseDaemon: Stack trace: 0x00000000108d3dd7 0x00000000108d2431 0x00000000123582b3 0x0000000012369769 0x000000001235fd0b 0x0000000012365459 0x0000000012742557 0x0000000012377984 0x000000000c8eee41 0x000000000c8f267a 0x000000000c8f147e 0x00007f9627783ac3 0x00007f9627815850
2024.04.01 08:30:09.213136 [ 4092052 ] {} <Fatal> BaseDaemon: 2. std::__hash_const_iterator<std::__hash_node<std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>, void*>*> std::__hash_table<std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>, std::__unordered_map_hasher<String, std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>, std::hash<String>, std::equal_to<String>, true>, std::__unordered_map_equal<String, std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>, std::equal_to<String>, std::hash<String>, true>, std::allocator<std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>>>::find<String>(String const&) const @ 0x00000000108d3dd7 in /usr/bin/clickhouse
2024.04.01 08:30:09.213248 [ 4092052 ] {} <Fatal> BaseDaemon: 3. DB::SerializationInfoTuple::add(DB::SerializationInfo const&) @ 0x00000000108d2431 in /usr/bin/clickhouse
2024.04.01 08:30:09.213285 [ 4092052 ] {} <Fatal> BaseDaemon: 4. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() @ 0x00000000123582b3 in /usr/bin/clickhouse
2024.04.01 08:30:09.213316 [ 4092052 ] {} <Fatal> BaseDaemon: 5. bool std::__function::__policy_invoker<bool ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()>>(std::__function::__policy_storage const*) @ 0x0000000012369769 in /usr/bin/clickhouse
2024.04.01 08:30:09.213337 [ 4092052 ] {} <Fatal> BaseDaemon: 6. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x000000001235fd0b in /usr/bin/clickhouse
2024.04.01 08:30:09.213388 [ 4092052 ] {} <Fatal> BaseDaemon: 7. DB::MergeTask::execute() @ 0x0000000012365459 in /usr/bin/clickhouse
2024.04.01 08:30:09.213427 [ 4092052 ] {} <Fatal> BaseDaemon: 8. DB::MergePlainMergeTreeTask::executeStep() @ 0x0000000012742557 in /usr/bin/clickhouse
2024.04.01 08:30:09.213456 [ 4092052 ] {} <Fatal> BaseDaemon: 9. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000012377984 in /usr/bin/clickhouse
2024.04.01 08:30:09.213495 [ 4092052 ] {} <Fatal> BaseDaemon: 10. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c8eee41 in /usr/bin/clickhouse
2024.04.01 08:30:09.213527 [ 4092052 ] {} <Fatal> BaseDaemon: 11. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c8f267a in /usr/bin/clickhouse
2024.04.01 08:30:09.213560 [ 4092052 ] {} <Fatal> BaseDaemon: 12. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c8f147e in /usr/bin/clickhouse
2024.04.01 08:30:09.213580 [ 4092052 ] {} <Fatal> BaseDaemon: 13. ? @ 0x00007f9627783ac3
2024.04.01 08:30:09.213591 [ 4092052 ] {} <Fatal> BaseDaemon: 14. ? @ 0x00007f9627815850
```

The second one (After reboot):
```
2024.04.01 11:01:13.174579 [ 8116 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.04.01 11:01:13.174632 [ 8116 ] {} <Fatal> BaseDaemon: (version 24.3.1.2672 (official build), build id: 3BCD08E1FFB4308011B5C207F85AE06411F878AA, git hash: 2c5c589a882ceec35439650337b92db3e76f0081) (from thread 7983) Received signal 11
2024.04.01 11:01:13.175297 [ 8116 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.04.01 11:01:13.176997 [ 8116 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.04.01 11:01:13.177640 [ 8116 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000fdfa897 0x000000000fdf8ef1 0x0000000011d0c4f3 0x0000000011d14a00 0x0000000011d18ef9 0x000000001213b4f8 0x0000000011d2d62d 0x000000000c95b399 0x000000000c95ebfa 0x000000000c95da0d 0x00007f6d611feac3 0x00007f6d61290850
2024.04.01 11:01:13.177659 [ 8116 ] {} <Fatal> BaseDaemon: ########################################
2024.04.01 11:01:13.177676 [ 8116 ] {} <Fatal> BaseDaemon: (version 24.3.1.2672 (official build), build id: 3BCD08E1FFB4308011B5C207F85AE06411F878AA, git hash: 2c5c589a882ceec35439650337b92db3e76f0081) (from thread 7983) (query_id: e316a5aa-55b5-46ed-92b5-4b45d69b808c::all_3_9_1_7) (query: ) Received signal Segmentation fault (11)
2024.04.01 11:01:13.177691 [ 8116 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.04.01 11:01:13.177702 [ 8116 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000fdfa897 0x000000000fdf8ef1 0x0000000011d0c4f3 0x0000000011d14a00 0x0000000011d18ef9 0x000000001213b4f8 0x0000000011d2d62d 0x000000000c95b399 0x000000000c95ebfa 0x000000000c95da0d 0x00007f6d611feac3 0x00007f6d61290850
2024.04.01 11:01:13.177817 [ 8116 ] {} <Fatal> BaseDaemon: 2. std::__hash_const_iterator<std::__hash_node<std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>, void*>*> std::__hash_table<std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>, std::__unordered_map_hasher<String, std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>, std::hash<String>, std::equal_to<String>, true>, std::__unordered_map_equal<String, std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>, std::equal_to<String>, std::hash<String>, true>, std::allocator<std::__hash_value_type<String, std::shared_ptr<DB::SerializationInfo>>>>::find<String>(String const&) const @ 0x000000000fdfa897
2024.04.01 11:01:13.179286 [ 8116 ] {} <Fatal> BaseDaemon: 3. DB::SerializationInfoTuple::add(DB::SerializationInfo const&) @ 0x000000000fdf8ef1
2024.04.01 11:01:13.179413 [ 8116 ] {} <Fatal> BaseDaemon: 4. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() @ 0x0000000011d0c4f3
2024.04.01 11:01:13.180333 [ 8116 ] {} <Fatal> BaseDaemon: 5. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x0000000011d14a00
2024.04.01 11:01:13.180470 [ 8116 ] {} <Fatal> BaseDaemon: 6. DB::MergeTask::execute() @ 0x0000000011d18ef9
2024.04.01 11:01:13.180536 [ 8116 ] {} <Fatal> BaseDaemon: 7. DB::MergePlainMergeTreeTask::executeStep() @ 0x000000001213b4f8
2024.04.01 11:01:13.180594 [ 8116 ] {} <Fatal> BaseDaemon: 8. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000011d2d62d
2024.04.01 11:01:13.180650 [ 8116 ] {} <Fatal> BaseDaemon: 9. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c95b399
2024.04.01 11:01:13.180687 [ 8116 ] {} <Fatal> BaseDaemon: 10. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c95ebfa
2024.04.01 11:01:13.181642 [ 8116 ] {} <Fatal> BaseDaemon: 11. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c95da0d
2024.04.01 11:01:13.181671 [ 8116 ] {} <Fatal> BaseDaemon: 12. ? @ 0x00007f6d611feac3
2024.04.01 11:01:13.181687 [ 8116 ] {} <Fatal> BaseDaemon: 13. ? @ 0x00007f6d61290850
```

**Comment by alexey-milovidov** [comment] 2024-04-03 07:31
The problem is that you've unlocked the experimental feature: `allow_experimental_object_type`.
It is not possible to use the experimental Object data type, and the issue won't be fixed.

**Closed by alexey-milovidov** 2024-04-03 07:31 UTC
Labels: st-wontfix, experimental feature
