### ISSUE TITLE
Unknow function (UDF) after ClickHouse restart

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#44031] opened 2022-12-08 08:35 UTC
v.22.10.3.27 (Docker image)

How to reproduce:
1) Create any UDF by DDL (plus_day for example)
`create function plus_day as (dt) -> dt + interval 1 day;`
2) Create table with kafka engine and MV which work with inserts to kafka table. MV must have UDF
```
CREATE TABLE test_table
(
    `_id`             String,
    `uploadDate`      DateTime,
    `uploadDate_test` DateTime
)
    ENGINE = MergeTree
        PARTITION BY toYYYYMM(uploadDate)
        ORDER BY uploadDate
        SETTINGS index_granularity = 8192;

CREATE TABLE kafka_engine_table
(
    `_id`        String,
    `uploadDate` DateTime
)
    ENGINE = Kafka('kafka_ip:kafka_port', 'kafka-topic', 'queue-test')
        SETTINGS kafka_format = 'JSONEachRow', kafka_skip_broken_messages = 0, kafka_max_block_size = 256;

CREATE MATERIALIZED VIEW test_kafka_mv TO test_table AS
SELECT _id,
       uploadDate,
       plus_day(uploadDate) as uploadDate_test
FROM kafka_engine_table;
```
3) Spam messages by kafka to MV and restart ClickHouse at the same time
4) When Clickhouse is up check error logs (or system.errors), there is you can find errors like 
`{} <Error> void DB::StorageKafka::threadFunc(size_t): Code: 46. DB::Exception: Unknown function plus_day ` at log
`Unknown function plus_day ` at system.errors

**Comment by tavplubix** [comment] 2022-12-08 13:07
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/43005

**Closed by tavplubix** 2022-12-08 13:07 UTC
Labels: potential bug
