### ISSUE TITLE
aggregate funciton unkonwn identifier

### ISSUE THREAD

**Issue by codingdancer** [ClickHouse/ClickHouse#43209] opened 2022-11-14 08:25 UTC
clickhouse version: 21.12.3.32
sql:  
select q * 10, quantileExact(number) over (partition by intDiv(number, 3) rows unbounded preceding) q from numbers(10)
error wiith message :  unkonwn identifier quantileExact(number) over (partition by intDiv(number, 3) rows unbounded preceding ...  
it  seems  like that   it can't  use  the  param of  windown funciton   。
I dont want to use it like this way ， include the sql  like  this  "select * from ( select ....)"
how  to resolve it, plz

**Comment by den-crane** [comment] 2022-11-14 14:26
It was implemented after 22.7 https://fiddle.clickhouse.com/818888dc-2b90-4a53-8831-6b305d9ce6f4


21.12 is out of support , it required a subquery https://fiddle.clickhouse.com/e1995954-cdfe-4fd5-9af9-bec1802a4540

**Comment by den-crane** [comment] 2022-11-14 14:27
duplicate of https://github.com/ClickHouse/ClickHouse/issues/19857
fixed https://github.com/ClickHouse/ClickHouse/pull/37848

**Closed** 2022-11-14 14:26 UTC
Labels: duplicate, comp-window-functions
