### ISSUE TITLE
Flaky `test_ssl_cert_authentication/test.py::test_https_non_ssl_auth`

### ISSUE THREAD

**Issue by serxa** [ClickHouse/ClickHouse#50600] opened 2023-06-05 17:25 UTC
Test is [flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBpbGlrZSAnJXRlc3Rfc3NsX2NlcnRfYXV0aGVudGljYXRpb24vdGVzdC5weTo6dGVzdF9odHRwc19ub25fc3NsX2F1dGglJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIGRlc2MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQ==)

**Comment by tavplubix** [comment] 2023-06-05 18:07
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/49400

**Closed by tavplubix** 2023-06-05 18:07 UTC
Labels: flaky test
