### ISSUE TITLE
Performance degradation when row group size is reduced in parquet file in s3

### ISSUE THREAD

**Issue by timfursov** [ClickHouse/ClickHouse#49477] opened 2023-05-03 21:02 UTC
**Describe the situation**
What exactly works slower than expected?
_- Reading parquet file from s3_

**How to reproduce**
* Which ClickHouse server version to use
_- 23.3.1.30124  clickhouse cloud_
* Non-default settings, if any
``` sql
max_insert_threads=4, max_threads=60, alter_sync=0, enable_memory_bound_merging_of_aggregation_results=1, log_queries=1, log_queries_probability=1, max_http_get_redirects=10, max_bytes_before_external_group_by=128849018880, max_bytes_before_external_sort=128849018880, max_memory_usage=257698037760, max_memory_usage_for_user=257698037760, backup_threads=100, restore_threads=100, cancel_http_readonly_queries_on_client_close=1, max_table_size_to_drop=1000000000000, max_partition_size_to_drop=1000000000000, default_table_engine=ReplicatedMergeTree, mutations_sync=0, optimize_trivial_insert_select=0, allow_experimental_database_replicated=1, database_replicated_allow_only_replicated_engine=1, cloud_mode=1, distributed_ddl_output_mode=none, async_insert_busy_timeout_ms=1000, enable_filesystem_cache_on_write_operations=1, load_marks_asynchronously=1, allow_asynchronous_read_from_io_pool_for_merge_tree=0, max_streams_for_merge_tree_reading=64, insert_keeper_max_retries=20, date_time_input_format=best_effort
```
* `CREATE TABLE` statements for all tables involved
``` sql
-- Just a null-table with 200 String columns for the purity of the experiment
create table null_str (
	s_0 String,s_1 String,s_2 String,s_3 String,s_4 String,s_5 String,s_6 String,s_7 String,s_8 String,s_9 String,s_10 String,s_11 String,s_12 String,s_13 String,s_14 String,s_15 String,s_16 String,s_17 String,s_18 String,s_19 String,s_20 String,s_21 String,s_22 String,s_23 String,s_24 String,s_25 String,s_26 String,s_27 String,s_28 String,s_29 String,s_30 String,s_31 String,s_32 String,s_33 String,s_34 String,s_35 String,s_36 String,s_37 String,s_38 String,s_39 String,s_40 String,s_41 String,s_42 String,s_43 String,s_44 String,s_45 String,s_46 String,s_47 String,s_48 String,s_49 String,s_50 String,s_51 String,s_52 String,s_53 String,s_54 String,s_55 String,s_56 String,s_57 String,s_58 String,s_59 String,s_60 String,s_61 String,s_62 String,s_63 String,s_64 String,s_65 String,s_66 String,s_67 String,s_68 String,s_69 String,s_70 String,s_71 String,s_72 String,s_73 String,s_74 String,s_75 String,s_76 String,s_77 String,s_78 String,s_79 String,s_80 String,s_81 String,s_82 String,s_83 String,s_84 String,s_85 String,s_86 String,s_87 String,s_88 String,s_89 String,s_90 String,s_91 String,s_92 String,s_93 String,s_94 String,s_95 String,s_96 String,s_97 String,s_98 String,s_99 String,s_100 String,s_101 String,s_102 String,s_103 String,s_104 String,s_105 String,s_106 String,s_107 String,s_108 String,s_109 String,s_110 String,s_111 String,s_112 String,s_113 String,s_114 String,s_115 String,s_116 String,s_117 String,s_118 String,s_119 String,s_120 String,s_121 String,s_122 String,s_123 String,s_124 String,s_125 String,s_126 String,s_127 String,s_128 String,s_129 String,s_130 String,s_131 String,s_132 String,s_133 String,s_134 String,s_135 String,s_136 String,s_137 String,s_138 String,s_139 String,s_140 String,s_141 String,s_142 String,s_143 String,s_144 String,s_145 String,s_146 String,s_147 String,s_148 String,s_149 String,s_150 String,s_151 String,s_152 String,s_153 String,s_154 String,s_155 String,s_156 String,s_157 String,s_158 String,s_159 String,s_160 String,s_161 String,s_162 String,s_163 String,s_164 String,s_165 String,s_166 String,s_167 String,s_168 String,s_169 String,s_170 String,s_171 String,s_172 String,s_173 String,s_174 String,s_175 String,s_176 String,s_177 String,s_178 String,s_179 String,s_180 String,s_181 String,s_182 String,s_183 String,s_184 String,s_185 String,s_186 String,s_187 String,s_188 String,s_189 String,s_190 String,s_191 String,s_192 String,s_193 String,s_194 String,s_195 String,s_196 String,s_197 String,s_198 String,s_199 String
)
Engine = Null
```
* Sample data for s3 files
``` sql
-- 40k-rows parquet file with the same 200 String columns
-- !!! output_format_parquet_row_group_size = 4000 !!!
INSERT INTO
	FUNCTION s3('https://S3_BUCKET/str_4000.pq',
	'ID',
	'KEY',
	'Parquet',
	's_0 String,s_1 String,s_2 String,s_3 String,s_4 String,s_5 String,s_6 String,s_7 String,s_8 String,s_9 String,s_10 String,s_11 String,s_12 String,s_13 String,s_14 String,s_15 String,s_16 String,s_17 String,s_18 String,s_19 String,s_20 String,s_21 String,s_22 String,s_23 String,s_24 String,s_25 String,s_26 String,s_27 String,s_28 String,s_29 String,s_30 String,s_31 String,s_32 String,s_33 String,s_34 String,s_35 String,s_36 String,s_37 String,s_38 String,s_39 String,s_40 String,s_41 String,s_42 String,s_43 String,s_44 String,s_45 String,s_46 String,s_47 String,s_48 String,s_49 String,s_50 String,s_51 String,s_52 String,s_53 String,s_54 String,s_55 String,s_56 String,s_57 String,s_58 String,s_59 String,s_60 String,s_61 String,s_62 String,s_63 String,s_64 String,s_65 String,s_66 String,s_67 String,s_68 String,s_69 String,s_70 String,s_71 String,s_72 String,s_73 String,s_74 String,s_75 String,s_76 String,s_77 String,s_78 String,s_79 String,s_80 String,s_81 String,s_82 String,s_83 String,s_84 String,s_85 String,s_86 String,s_87 String,s_88 String,s_89 String,s_90 String,s_91 String,s_92 String,s_93 String,s_94 String,s_95 String,s_96 String,s_97 String,s_98 String,s_99 String,s_100 String,s_101 String,s_102 String,s_103 String,s_104 String,s_105 String,s_106 String,s_107 String,s_108 String,s_109 String,s_110 String,s_111 String,s_112 String,s_113 String,s_114 String,s_115 String,s_116 String,s_117 String,s_118 String,s_119 String,s_120 String,s_121 String,s_122 String,s_123 String,s_124 String,s_125 String,s_126 String,s_127 String,s_128 String,s_129 String,s_130 String,s_131 String,s_132 String,s_133 String,s_134 String,s_135 String,s_136 String,s_137 String,s_138 String,s_139 String,s_140 String,s_141 String,s_142 String,s_143 String,s_144 String,s_145 String,s_146 String,s_147 String,s_148 String,s_149 String,s_150 String,s_151 String,s_152 String,s_153 String,s_154 String,s_155 String,s_156 String,s_157 String,s_158 String,s_159 String,s_160 String,s_161 String,s_162 String,s_163 String,s_164 String,s_165 String,s_166 String,s_167 String,s_168 String,s_169 String,s_170 String,s_171 String,s_172 String,s_173 String,s_174 String,s_175 String,s_176 String,s_177 String,s_178 String,s_179 String,s_180 String,s_181 String,s_182 String,s_183 String,s_184 String,s_185 String,s_186 String,s_187 String,s_188 String,s_189 String,s_190 String,s_191 String,s_192 String,s_193 String,s_194 String,s_195 String,s_196 String,s_197 String,s_198 String,s_199 String'
	, 'none')
SELECT * FROM
	generateRandom(
	's_0 String,s_1 String,s_2 String,s_3 String,s_4 String,s_5 String,s_6 String,s_7 String,s_8 String,s_9 String,s_10 String,s_11 String,s_12 String,s_13 String,s_14 String,s_15 String,s_16 String,s_17 String,s_18 String,s_19 String,s_20 String,s_21 String,s_22 String,s_23 String,s_24 String,s_25 String,s_26 String,s_27 String,s_28 String,s_29 String,s_30 String,s_31 String,s_32 String,s_33 String,s_34 String,s_35 String,s_36 String,s_37 String,s_38 String,s_39 String,s_40 String,s_41 String,s_42 String,s_43 String,s_44 String,s_45 String,s_46 String,s_47 String,s_48 String,s_49 String,s_50 String,s_51 String,s_52 String,s_53 String,s_54 String,s_55 String,s_56 String,s_57 String,s_58 String,s_59 String,s_60 String,s_61 String,s_62 String,s_63 String,s_64 String,s_65 String,s_66 String,s_67 String,s_68 String,s_69 String,s_70 String,s_71 String,s_72 String,s_73 String,s_74 String,s_75 String,s_76 String,s_77 String,s_78 String,s_79 String,s_80 String,s_81 String,s_82 String,s_83 String,s_84 String,s_85 String,s_86 String,s_87 String,s_88 String,s_89 String,s_90 String,s_91 String,s_92 String,s_93 String,s_94 String,s_95 String,s_96 String,s_97 String,s_98 String,s_99 String,s_100 String,s_101 String,s_102 String,s_103 String,s_104 String,s_105 String,s_106 String,s_107 String,s_108 String,s_109 String,s_110 String,s_111 String,s_112 String,s_113 String,s_114 String,s_115 String,s_116 String,s_117 String,s_118 String,s_119 String,s_120 String,s_121 String,s_122 String,s_123 String,s_124 String,s_125 String,s_126 String,s_127 String,s_128 String,s_129 String,s_130 String,s_131 String,s_132 String,s_133 String,s_134 String,s_135 String,s_136 String,s_137 String,s_138 String,s_139 String,s_140 String,s_141 String,s_142 String,s_143 String,s_144 String,s_145 String,s_146 String,s_147 String,s_148 String,s_149 String,s_150 String,s_151 String,s_152 String,s_153 String,s_154 String,s_155 String,s_156 String,s_157 String,s_158 String,s_159 String,s_160 String,s_161 String,s_162 String,s_163 String,s_164 String,s_165 String,s_166 String,s_167 String,s_168 String,s_169 String,s_170 String,s_171 String,s_172 String,s_173 String,s_174 String,s_175 String,s_176 String,s_177 String,s_178 String,s_179 String,s_180 String,s_181 String,s_182 String,s_183 String,s_184 String,s_185 String,s_186 String,s_187 String,s_188 String,s_189 String,s_190 String,s_191 String,s_192 String,s_193 String,s_194 String,s_195 String,s_196 String,s_197 String,s_198 String,s_199 String'
	,1, 30)
limit 40000

settings 
s3_truncate_on_insert=1, 
output_format_parquet_row_group_size=4000,
output_format_parquet_version='2.latest';


-- 40k-rows parquet file with the same 200 String columns
-- !!! output_format_parquet_row_group_size = 8000 !!!
INSERT INTO
	FUNCTION s3('https://S3_BUCKET/str_8000.pq',
	'ID',
	'KEY',
	'Parquet',
	's_0 String,s_1 String,s_2 String,s_3 String,s_4 String,s_5 String,s_6 String,s_7 String,s_8 String,s_9 String,s_10 String,s_11 String,s_12 String,s_13 String,s_14 String,s_15 String,s_16 String,s_17 String,s_18 String,s_19 String,s_20 String,s_21 String,s_22 String,s_23 String,s_24 String,s_25 String,s_26 String,s_27 String,s_28 String,s_29 String,s_30 String,s_31 String,s_32 String,s_33 String,s_34 String,s_35 String,s_36 String,s_37 String,s_38 String,s_39 String,s_40 String,s_41 String,s_42 String,s_43 String,s_44 String,s_45 String,s_46 String,s_47 String,s_48 String,s_49 String,s_50 String,s_51 String,s_52 String,s_53 String,s_54 String,s_55 String,s_56 String,s_57 String,s_58 String,s_59 String,s_60 String,s_61 String,s_62 String,s_63 String,s_64 String,s_65 String,s_66 String,s_67 String,s_68 String,s_69 String,s_70 String,s_71 String,s_72 String,s_73 String,s_74 String,s_75 String,s_76 String,s_77 String,s_78 String,s_79 String,s_80 String,s_81 String,s_82 String,s_83 String,s_84 String,s_85 String,s_86 String,s_87 String,s_88 String,s_89 String,s_90 String,s_91 String,s_92 String,s_93 String,s_94 String,s_95 String,s_96 String,s_97 String,s_98 String,s_99 String,s_100 String,s_101 String,s_102 String,s_103 String,s_104 String,s_105 String,s_106 String,s_107 String,s_108 String,s_109 String,s_110 String,s_111 String,s_112 String,s_113 String,s_114 String,s_115 String,s_116 String,s_117 String,s_118 String,s_119 String,s_120 String,s_121 String,s_122 String,s_123 String,s_124 String,s_125 String,s_126 String,s_127 String,s_128 String,s_129 String,s_130 String,s_131 String,s_132 String,s_133 String,s_134 String,s_135 String,s_136 String,s_137 String,s_138 String,s_139 String,s_140 String,s_141 String,s_142 String,s_143 String,s_144 String,s_145 String,s_146 String,s_147 String,s_148 String,s_149 String,s_150 String,s_151 String,s_152 String,s_153 String,s_154 String,s_155 String,s_156 String,s_157 String,s_158 String,s_159 String,s_160 String,s_161 String,s_162 String,s_163 String,s_164 String,s_165 String,s_166 String,s_167 String,s_168 String,s_169 String,s_170 String,s_171 String,s_172 String,s_173 String,s_174 String,s_175 String,s_176 String,s_177 String,s_178 String,s_179 String,s_180 String,s_181 String,s_182 String,s_183 String,s_184 String,s_185 String,s_186 String,s_187 String,s_188 String,s_189 String,s_190 String,s_191 String,s_192 String,s_193 String,s_194 String,s_195 String,s_196 String,s_197 String,s_198 String,s_199 String'
	, 'none')
SELECT * FROM
	generateRandom(
	's_0 String,s_1 String,s_2 String,s_3 String,s_4 String,s_5 String,s_6 String,s_7 String,s_8 String,s_9 String,s_10 String,s_11 String,s_12 String,s_13 String,s_14 String,s_15 String,s_16 String,s_17 String,s_18 String,s_19 String,s_20 String,s_21 String,s_22 String,s_23 String,s_24 String,s_25 String,s_26 String,s_27 String,s_28 String,s_29 String,s_30 String,s_31 String,s_32 String,s_33 String,s_34 String,s_35 String,s_36 String,s_37 String,s_38 String,s_39 String,s_40 String,s_41 String,s_42 String,s_43 String,s_44 String,s_45 String,s_46 String,s_47 String,s_48 String,s_49 String,s_50 String,s_51 String,s_52 String,s_53 String,s_54 String,s_55 String,s_56 String,s_57 String,s_58 String,s_59 String,s_60 String,s_61 String,s_62 String,s_63 String,s_64 String,s_65 String,s_66 String,s_67 String,s_68 String,s_69 String,s_70 String,s_71 String,s_72 String,s_73 String,s_74 String,s_75 String,s_76 String,s_77 String,s_78 String,s_79 String,s_80 String,s_81 String,s_82 String,s_83 String,s_84 String,s_85 String,s_86 String,s_87 String,s_88 String,s_89 String,s_90 String,s_91 String,s_92 String,s_93 String,s_94 String,s_95 String,s_96 String,s_97 String,s_98 String,s_99 String,s_100 String,s_101 String,s_102 String,s_103 String,s_104 String,s_105 String,s_106 String,s_107 String,s_108 String,s_109 String,s_110 String,s_111 String,s_112 String,s_113 String,s_114 String,s_115 String,s_116 String,s_117 String,s_118 String,s_119 String,s_120 String,s_121 String,s_122 String,s_123 String,s_124 String,s_125 String,s_126 String,s_127 String,s_128 String,s_129 String,s_130 String,s_131 String,s_132 String,s_133 String,s_134 String,s_135 String,s_136 String,s_137 String,s_138 String,s_139 String,s_140 String,s_141 String,s_142 String,s_143 String,s_144 String,s_145 String,s_146 String,s_147 String,s_148 String,s_149 String,s_150 String,s_151 String,s_152 String,s_153 String,s_154 String,s_155 String,s_156 String,s_157 String,s_158 String,s_159 String,s_160 String,s_161 String,s_162 String,s_163 String,s_164 String,s_165 String,s_166 String,s_167 String,s_168 String,s_169 String,s_170 String,s_171 String,s_172 String,s_173 String,s_174 String,s_175 String,s_176 String,s_177 String,s_178 String,s_179 String,s_180 String,s_181 String,s_182 String,s_183 String,s_184 String,s_185 String,s_186 String,s_187 String,s_188 String,s_189 String,s_190 String,s_191 String,s_192 String,s_193 String,s_194 String,s_195 String,s_196 String,s_197 String,s_198 String,s_199 String'
	,1, 30)
limit 40000

settings 
s3_truncate_on_insert=1, 
output_format_parquet_row_group_size=8000,
output_format_parquet_version='2.latest';
```
* Queries to run that lead to slow performance
``` sql
-- Query 1
-- Looks good, RemoteReadThrottlerBytes = 159.95 MiB, query_duration_ms=2640, S3ReadRequestsCount=23
INSERT INTO null_str
select * from s3('https://S3_BUCKET/str_8000.pq',
'ID',
'KEY',
'Parquet',
's_0 String,s_1 String,s_2 String,s_3 String,s_4 String,s_5 String,s_6 String,s_7 String,s_8 String,s_9 String,s_10 String,s_11 String,s_12 String,s_13 String,s_14 String,s_15 String,s_16 String,s_17 String,s_18 String,s_19 String,s_20 String,s_21 String,s_22 String,s_23 String,s_24 String,s_25 String,s_26 String,s_27 String,s_28 String,s_29 String,s_30 String,s_31 String,s_32 String,s_33 String,s_34 String,s_35 String,s_36 String,s_37 String,s_38 String,s_39 String,s_40 String,s_41 String,s_42 String,s_43 String,s_44 String,s_45 String,s_46 String,s_47 String,s_48 String,s_49 String,s_50 String,s_51 String,s_52 String,s_53 String,s_54 String,s_55 String,s_56 String,s_57 String,s_58 String,s_59 String,s_60 String,s_61 String,s_62 String,s_63 String,s_64 String,s_65 String,s_66 String,s_67 String,s_68 String,s_69 String,s_70 String,s_71 String,s_72 String,s_73 String,s_74 String,s_75 String,s_76 String,s_77 String,s_78 String,s_79 String,s_80 String,s_81 String,s_82 String,s_83 String,s_84 String,s_85 String,s_86 String,s_87 String,s_88 String,s_89 String,s_90 String,s_91 String,s_92 String,s_93 String,s_94 String,s_95 String,s_96 String,s_97 String,s_98 String,s_99 String,s_100 String,s_101 String,s_102 String,s_103 String,s_104 String,s_105 String,s_106 String,s_107 String,s_108 String,s_109 String,s_110 String,s_111 String,s_112 String,s_113 String,s_114 String,s_115 String,s_116 String,s_117 String,s_118 String,s_119 String,s_120 String,s_121 String,s_122 String,s_123 String,s_124 String,s_125 String,s_126 String,s_127 String,s_128 String,s_129 String,s_130 String,s_131 String,s_132 String,s_133 String,s_134 String,s_135 String,s_136 String,s_137 String,s_138 String,s_139 String,s_140 String,s_141 String,s_142 String,s_143 String,s_144 String,s_145 String,s_146 String,s_147 String,s_148 String,s_149 String,s_150 String,s_151 String,s_152 String,s_153 String,s_154 String,s_155 String,s_156 String,s_157 String,s_158 String,s_159 String,s_160 String,s_161 String,s_162 String,s_163 String,s_164 String,s_165 String,s_166 String,s_167 String,s_168 String,s_169 String,s_170 String,s_171 String,s_172 String,s_173 String,s_174 String,s_175 String,s_176 String,s_177 String,s_178 String,s_179 String,s_180 String,s_181 String,s_182 String,s_183 String,s_184 String,s_185 String,s_186 String,s_187 String,s_188 String,s_189 String,s_190 String,s_191 String,s_192 String,s_193 String,s_194 String,s_195 String,s_196 String,s_197 String,s_198 String,s_199 String'
, 'none')

/*
query_duration_ms:                                                           2640      
arrayElement(ProfileEvents, 'S3ReadMicroseconds'):                           3363040   
arrayElement(ProfileEvents, 'ReadBufferFromS3InitMicroseconds'):             3280285   
S3ReadRequestsCount:                                                         23        
S3ListObjects:                                                               0         
S3GetObject:                                                                 22        
ReadBufferFromS3Seconds:                                                     6923381   
ReadBufferFromS3InitMicroseconds:                                            3280285   
formatReadableSize(arrayElement(ProfileEvents, 'ReadBufferFromS3Bytes')):    159.95 MiB
formatReadableSize(arrayElement(ProfileEvents, 'RemoteReadThrottlerBytes')): 159.95 MiB
SelectedBytes:                                                               384014124 
SelectedRows:                                                                80000     
NetworkReceiveElapsedMicroseconds:                                           10        
NetworkReceiveBytes:                                                         2698      
formatReadableSize(read_bytes):                                              183.11 MiB
formatReadableSize(written_bytes):                                           183.11 MiB
*/

-- Query 2 
-- NOT OK, RemoteReadThrottlerBytes = 17.61 GiB (???), query_duration_ms=260822, S3ReadRequestsCount=3889
INSERT INTO null_str
select * from s3('https://S3_BUCKET/str_4000.pq',
'ID',
'KEY',
'Parquet',
's_0 String,s_1 String,s_2 String,s_3 String,s_4 String,s_5 String,s_6 String,s_7 String,s_8 String,s_9 String,s_10 String,s_11 String,s_12 String,s_13 String,s_14 String,s_15 String,s_16 String,s_17 String,s_18 String,s_19 String,s_20 String,s_21 String,s_22 String,s_23 String,s_24 String,s_25 String,s_26 String,s_27 String,s_28 String,s_29 String,s_30 String,s_31 String,s_32 String,s_33 String,s_34 String,s_35 String,s_36 String,s_37 String,s_38 String,s_39 String,s_40 String,s_41 String,s_42 String,s_43 String,s_44 String,s_45 String,s_46 String,s_47 String,s_48 String,s_49 String,s_50 String,s_51 String,s_52 String,s_53 String,s_54 String,s_55 String,s_56 String,s_57 String,s_58 String,s_59 String,s_60 String,s_61 String,s_62 String,s_63 String,s_64 String,s_65 String,s_66 String,s_67 String,s_68 String,s_69 String,s_70 String,s_71 String,s_72 String,s_73 String,s_74 String,s_75 String,s_76 String,s_77 String,s_78 String,s_79 String,s_80 String,s_81 String,s_82 String,s_83 String,s_84 String,s_85 String,s_86 String,s_87 String,s_88 String,s_89 String,s_90 String,s_91 String,s_92 String,s_93 String,s_94 String,s_95 String,s_96 String,s_97 String,s_98 String,s_99 String,s_100 String,s_101 String,s_102 String,s_103 String,s_104 String,s_105 String,s_106 String,s_107 String,s_108 String,s_109 String,s_110 String,s_111 String,s_112 String,s_113 String,s_114 String,s_115 String,s_116 String,s_117 String,s_118 String,s_119 String,s_120 String,s_121 String,s_122 String,s_123 String,s_124 String,s_125 String,s_126 String,s_127 String,s_128 String,s_129 String,s_130 String,s_131 String,s_132 String,s_133 String,s_134 String,s_135 String,s_136 String,s_137 String,s_138 String,s_139 String,s_140 String,s_141 String,s_142 String,s_143 String,s_144 String,s_145 String,s_146 String,s_147 String,s_148 String,s_149 String,s_150 String,s_151 String,s_152 String,s_153 String,s_154 String,s_155 String,s_156 String,s_157 String,s_158 String,s_159 String,s_160 String,s_161 String,s_162 String,s_163 String,s_164 String,s_165 String,s_166 String,s_167 String,s_168 String,s_169 String,s_170 String,s_171 String,s_172 String,s_173 String,s_174 String,s_175 String,s_176 String,s_177 String,s_178 String,s_179 String,s_180 String,s_181 String,s_182 String,s_183 String,s_184 String,s_185 String,s_186 String,s_187 String,s_188 String,s_189 String,s_190 String,s_191 String,s_192 String,s_193 String,s_194 String,s_195 String,s_196 String,s_197 String,s_198 String,s_199 String'
, 'none')

/*
query_duration_ms:                                                           260822    
arrayElement(ProfileEvents, 'S3ReadMicroseconds'):                           282326519 
arrayElement(ProfileEvents, 'ReadBufferFromS3InitMicroseconds'):             286746282 
S3ReadRequestsCount:                                                         3889      
S3ListObjects:                                                               0         
S3GetObject:                                                                 3885      
ReadBufferFromS3Seconds:                                                     695287988 
ReadBufferFromS3InitMicroseconds:                                            286746282 
formatReadableSize(arrayElement(ProfileEvents, 'ReadBufferFromS3Bytes')):    17.61 GiB 
formatReadableSize(arrayElement(ProfileEvents, 'RemoteReadThrottlerBytes')): 17.61 GiB 
SelectedBytes:                                                               384014124 
SelectedRows:                                                                80000     
NetworkReceiveElapsedMicroseconds:                                           7         
NetworkReceiveBytes:                                                         2698      
formatReadableSize(read_bytes):                                              183.11 MiB
formatReadableSize(written_bytes):                                           183.11 MiB
*/
```

**Expected performance**
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system?

I didn't expect that lowering row_group_size from 8000 to 4000 for the same data would cause such a huge difference in performance.
query_duration_ms 2640 vs 260822 which is about 100 times slower

**Additional context**
The speed of queries directly depends on the difference in clickhouse cloud and s3 availability zones.
In this experiment, the clickhouse cloud service is located in Ohio (us-east-2) and the s3 bucket is located in N. Virginia (us-east-1).

If you place them even further apart, collecting data from the `str_4000.pq` file will take even longer.

**Comment by alexey-milovidov** [comment] 2023-05-03 21:32
I'll not be surprised if it's fixed in the release 23.4.

**Comment by al13n321** [comment] 2023-05-03 23:41
Wow, it read the file 100 times? Will try to reproduce, but https://github.com/ClickHouse/ClickHouse/pull/47964 almost certainly fixed it.

You can also sanity-check the file metadata (in 23.4):
```
select num_columns, num_rows, num_row_groups, total_uncompressed_size/1e6 as uncompressed_mb, total_compressed_size/1e6 as compressed_mb from s3(..., format=ParquetMetadata)
```

Both 4000 and 8000 seem way too small: that's ~163 KB per column chunk (column in a row group), small for S3. The default settings should be fine here: `min_insert_block_size_bytes` = 256 MB; after https://github.com/ClickHouse/ClickHouse/pull/49325 `output_format_parquet_row_group_size` = 512 MB is used instead (and `output_format_parquet_row_group_size` = 1M, which wouldn't be hit with such chonky rows).

**Comment by al13n321** [comment] 2023-05-04 00:29
Reproduced it, https://github.com/ClickHouse/ClickHouse/pull/47964 fixes it. Didn't investigate what exactly the problem was.

**Closed** 2023-05-04 01:44 UTC
Labels: performance

**Comment by timfursov** [comment] 2023-05-04 10:01
Thanks for checking!
Looking forward for the delivery of these changes to the cloud :slightly_smiling_face:
