### ISSUE TITLE
 isDefaultAt is not implemented for Function

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#55047] opened 2023-09-27 07:07 UTC
v.23.8.2.7

I run the same query on the same data, and sometimes it throws an error, and sometimes it works without problems.

` Code: 48. DB::Exception: isDefaultAt is not implemented for Function: while executing 'FUNCTION Capture[Int64](Int64) -> UInt8(toInt64(prev_id) :: 0) -> __lambda Function(Int64 -> UInt8) : 3'. (NOT_IMPLEMENTED) (version 23.8.2.7 (official build))`

```
drop table if exists test_table;
create table test_table engine MergeTree order by id as
select assumeNotNull(id)              as id,
       arrayCount((cr_id1) -> (toInt64(cr_id1) = toInt64(t.prev_id)),
                   t2.ids) as cnt
from mytable t
         left join (select client_id,
                           groupArray(id)                                   as ids
                    from mytable
                    group by client_id) t2
                   on t.client_id = t2.client_id
limit 100;
```

**Comment by KochetovNicolai** [comment] 2023-09-27 11:57
Could you specify a schema for `mytable`?

**Comment by alexsubota** [comment] 2023-09-27 12:25
```
CREATE TABLE mytable
(
    `id` Int64
)
    ENGINE = MergeTree
        ORDER BY id
        SETTINGS index_granularity = 8192
```

**Comment by nickitat** [comment] 2023-09-27 14:25
> CREATE TABLE mytable
> (
>     `id` Int64
> )
>     ENGINE = MergeTree
>         ORDER BY id
>         SETTINGS index_granularity = 8192

this definition missing `client_id`

**Comment by alexsubota** [comment] 2023-09-27 14:28
my bad, comment was edited

**Comment by nickitat** [comment] 2023-09-27 18:45
cannot reproduce on the current master. pls try update

**Comment by azat** [comment] 2023-10-06 14:19
The problem is with sparse columns, should be fixed by https://github.com/ClickHouse/ClickHouse/pull/55275

For now, you can disable them as a workaround:

```
create table x (key Int) engine=MergeTree() order by tuple() settings ratio_of_defaults_for_sparse_serialization=1
```

**Closed** 2023-10-08 13:27 UTC
Labels: st-need-repro
