### ISSUE TITLE
test_storage_azure_blob_storage/test.py::test_union_schema_inference_mode: Data race in registerStorageAzureBlob

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#60347] opened 2024-02-23 10:15 UTC
https://s3.amazonaws.com/clickhouse-test-reports/60228/b71bdbae1b852ed7361ce09119f41035fc66caf1/integration_tests__tsan__[3_6].html

TSAN report -> https://pastila.nl/?0020b497/94a13ae67c1dfc23317f5087c8275691#cPJZzOdjFOVqZP4YwSjtUQ==

**Comment by nickitat** [comment] 2024-03-06 15:43
I've filed an issue: https://github.com/curl/curl/issues/13065

**Comment by nickitat** [comment] 2024-03-07 20:05
the issue is fixed in upstream. it is going to be released in 3 weeks. idk, seems like it doesn't worth creating a fork just for this fix since the bug is harmless.

**Closed** 2024-04-29 01:02 UTC
Labels: testing
