### ISSUE TITLE
clickhouse-common 404

### ISSUE THREAD

**Issue by relwell** [ClickHouse/ClickHouse#58556] opened 2024-01-05 16:51 UTC
**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors

**Installation type**

debian

**Source of the ClickHouse**
```
GNUPGHOME=$(mktemp -d)
sudo GNUPGHOME="$GNUPGHOME" gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754
sudo rm -r "$GNUPGHOME"
sudo chmod +r /usr/share/keyrings/clickhouse-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update

export DEBIAN_PRIORITY=critical DEBIAN_FRONTEND=noninteractive
sudo apt-get install -y clickhouse-server clickhouse-client -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
```

```
Err:1 https://packages.clickhouse.com/deb stable/main amd64 clickhouse-common-static amd64 23.12.2.59
  404  Not Found [IP: 172.66.43.7 443]
```

**Expected result**
The package should be installable

**The actual result**

Failure to install

**How to reproduce**

I'm using a virtual machine from Vultr located in the NY data center, so I would launch an instance there and attempt to install clickhouse.

**Comment by SaltTan** [comment] 2024-01-05 17:23
clickhouse-common-static-dbg_23.12.2.59_amd64.deb is also absent from https://packages.clickhouse.com/deb/pool/main/c/clickhouse/

**Comment by chollinger93** [comment] 2024-01-05 17:51
Can confirm, `https://packages.clickhouse.com/deb stable main` fails, `https://packages.clickhouse.com/deb lts main` works.

**Comment by Felixoid** [comment] 2024-01-05 20:55
The issue was again with `geesefs`, it stuck and couldn't upload the files.

I manually restarted the release endpoint as following: `curl --silent --data '' --no-buffer localhost:5000/'release/v23.12.2.59-stable?binary=binary_darwin&binary=binary_darwin_aarch64&sync=true&force=true' -v`

It fixed the tgz, but deb repo remained broken. That's the command to check the state of deb repos:

```
reprepro --basedir ~/r2/configs/deb --verbose --export=force --outdir ~/r2/deb --keepdirectories --keepunreferencedfiles checkpool fast
Missing file '/home/ubuntu/r2/deb/pool/main/c/clickhouse/clickhouse-common-static-dbg_23.12.2.59_amd64.deb'!
Missing file '/home/ubuntu/r2/deb/pool/main/c/clickhouse/clickhouse-common-static_23.12.2.59_amd64.deb'!
There have been errors!
```

So I manually copied the files:

`cp ~/ebs/clickhouse-repos-manager/releases/v23.12.2.59-stable/clickhouse-common-static*_23.12.2.59_amd64.deb /home/ubuntu/r2/deb/pool/main/c/clickhouse/`

Now, I'll report the syslogs to geesefs repo after my vacation. And will improve some logging in the repos manager.

The issue is not major anymore, the repos itself is fixed, I've checked it

**Comment by Felixoid** [comment] 2024-01-06 04:38
Please, keep it open for me to investigate the reasons next week

**Comment by Felixoid** [comment] 2024-01-09 10:28
As suggested in https://github.com/yandex-cloud/geesefs/issues/52, I've upgraded the geesefs to 0.40.0

**Comment by Felixoid** [comment] 2024-02-06 10:49
It looks like the R2 + geesefs are much more stable now than before. So I am closing the issue

**Closed by Felixoid** 2024-02-06 10:49 UTC
Labels: st-almost-fixed, comp-install
