### ISSUE TITLE
Couldn't start replication (table will be in readonly mode) on version 23.2.2.20 

### ISSUE THREAD

**Issue by MrSsunlight** [ClickHouse/ClickHouse#47879] opened 2023-03-22 09:21 UTC
```bash
2023.03.22 16:59:48.920117 [ 233 ] {} <Error> db.table (ReplicatedMergeTreeRestartingThread): Couldn't start replication (table will be in readonly mode): Transaction failed (No node): Op #1, path: /clickhouse/tables/cluster_1st-1/db/table/replicas/clickhouse-cluster-1.clickhouse-cluster-headless/host. Code: 999. Coordination::Exception: Transaction failed (No node): Op #1, path: /clickhouse/tables/cluster_1st-1/db/table/replicas/clickhouse-cluster-1.clickhouse-cluster-headless/host. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c6655 in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, Coordination::Error, int) @ 0x14c81a70 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, Coordination::Error) @ 0x14c81d98 in /usr/bin/clickhouse
3. zkutil::KeeperMultiException::KeeperMultiException(Coordination::Error, std::__1::vector<std::__1::shared_ptr<Coordination::Request>, std::__1::allocator<std::__1::shared_ptr<Coordination::Request>>> const&, std::__1::vector<std::__1::shared_ptr<Coordination::Response>, std::__1::allocator<std::__1::shared_ptr<Coordination::Response>>> const&) @ 0x14c98524 in /usr/bin/clickhouse
4. zkutil::KeeperMultiException::check(Coordination::Error, std::__1::vector<std::__1::shared_ptr<Coordination::Request>, std::__1::allocator<std::__1::shared_ptr<Coordination::Request>>> const&, std::__1::vector<std::__1::shared_ptr<Coordination::Response>, std::__1::allocator<std::__1::shared_ptr<Coordination::Response>>> const&) @ 0x14c8d472 in /usr/bin/clickhouse
5. DB::ReplicatedMergeTreeRestartingThread::activateReplica() @ 0x1452f5ee in /usr/bin/clickhouse
6. DB::ReplicatedMergeTreeRestartingThread::tryStartup() @ 0x1452dae3 in /usr/bin/clickhouse
7. DB::ReplicatedMergeTreeRestartingThread::runImpl() @ 0x1452cc01 in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeRestartingThread::run() @ 0x1452bcba in /usr/bin/clickhouse
9. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12666d46 in /usr/bin/clickhouse
10. DB::BackgroundSchedulePool::threadFunction() @ 0x12669d4a in /usr/bin/clickhouse
11. ? @ 0x1266ab8c in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe194dea in /usr/bin/clickhouse
13. ? @ 0xe19a4a1 in /usr/bin/clickhouse
14. ? @ 0x7f59c128a609 in ?
15. __clone @ 0x7f59c11af133 in ?
 (version 23.2.2.20 (official build))
```

create table like this: 
```sql
 CREATE TABLE db.table
(
    `version` UInt8,
    `name` String,
    `start_time` AggregateFunction(min, DateTime),
    `end_time` AggregateFunction(max, DateTime),
    `countpv` AggregateFunction(sum, UInt64)
)
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{layer}-{shard}/db/table', '{replica}')
PARTITION BY version
PRIMARY KEY (version, name)
ORDER BY (version, name)
SETTINGS index_granularity = 8192, merge_with_ttl_timeout = 7200, use_minimalistic_part_header_in_zookeeper = 1, storage_policy = 'hdd_in_order'
```

```sql
:) SELECT * FROM clusterAllReplicas('cluster_1st', 'system.errors') WHERE name = 'KEEPER_EXCEPTION'

┌─name─────────────┬─code─┬─value─┬─────last_error_time─┬─last_error_message───────────┬─last_error_trace──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─remote─┐
│ KEEPER_EXCEPTION │  999 │  6615 │ 2023-03-22 17:09:03 │ Transaction failed (No node) │ [235693653,348658288,348659096,348751140,348705906,340981230,340974307,340970497,340966586,308702534,308714826,308718476,236539370,236561569,140671783749129,140671782850867] │      0 │
└──────────────────┴──────┴───────┴─────────────────────┴──────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────┘
┌─name─────────────┬─code─┬─value─┬─────last_error_time─┬─last_error_message───────────┬─last_error_trace──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─remote─┐
│ KEEPER_EXCEPTION │  999 │  6781 │ 2023-03-22 17:09:03 │ Transaction failed (No node) │ [235693653,348658288,348659096,348751140,348705906,340981230,340974307,340970497,340966586,308702534,308714826,308718476,236539370,236561569,140023469483529,140023468585267] │      0 │
└──────────────────┴──────┴───────┴─────────────────────┴──────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────┘
```
The same as these two problems（[38961](https://github.com/ClickHouse/ClickHouse/pull/38961) and [38529](https://github.com/ClickHouse/ClickHouse/issues/38529)）, but I think the new version appears

No successful solutions have been found yet, including temporary ones like [46820](https://github.com/ClickHouse/ClickHouse/pull/46820)

**Comment by UnamedRus** [comment] 2023-05-19 19:25
Also, ClickHouse can't start replication after upgrade to 23.2

```
Code: 999. Coordination::Exception: Transaction failed (No node): Op #1, path: /clickhouse/xxx-xxx/tables/0/xxxx/xxxx/replicas/chi-xxx-xx-xxxx-xxx-0-0/parts/202304_95474_95474_0. (KEEPER_EXCEPTION) (version 23.2.6.34 (official build)) 
 ```

**Comment by utkarsh2811** [comment] 2023-08-28 11:22
Hi,

I am running clickhouse/clickhouse-server:23.7 and facing exact same issue.

i face the below error and i cannot create any tables anymore in the cluster and my kafka engine has stopped consuming from the topic as it has more than 8 million messages in lag.

`2023.08.28 10:52:15.030971 [ 89 ] {} <Error> time_series.video_stat (ReplicatedMergeTreeRestartingThread): Couldn't start replication (table will be in readonly mode): Transaction failed (No node): Op #0, path: /clickhouse/tables/fd85335c-a1a5-4fc5-9f12-737d05024b1f/0/replicas/service-01-0-0/is_active. Code: 999. Coordination::Exception: Transaction failed (No node): Op #0, path: /clickhouse/tables/fd85335c-a1a5-4fc5-9f12-737d05024b1f/0/replicas/service-01-0-0/is_active. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e91fc37 in /usr/bin/clickhouse
1. Coordination::Exception::Exception(String const&, Coordination::Error, int) @ 0x00000000158ea071 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(String const&, Coordination::Error) @ 0x00000000158ea39f in /usr/bin/clickhouse
3. zkutil::KeeperMultiException::KeeperMultiException(Coordination::Error, std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>> const&) @ 0x0000000015902ae2 in /usr/bin/clickhouse
4. zkutil::KeeperMultiException::check(Coordination::Error, std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>> const&) @ 0x00000000158f6673 in /usr/bin/clickhouse
5. DB::ReplicatedMergeTreeRestartingThread::activateReplica() @ 0x00000000150a330e in /usr/bin/clickhouse
6. DB::ReplicatedMergeTreeRestartingThread::tryStartup() @ 0x00000000150a1806 in /usr/bin/clickhouse
7. DB::ReplicatedMergeTreeRestartingThread::runImpl() @ 0x00000000150a0db7 in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeRestartingThread::run() @ 0x00000000150a02ba in /usr/bin/clickhouse
9. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x0000000013221a80 in /usr/bin/clickhouse
10. DB::BackgroundSchedulePool::threadFunction() @ 0x00000000132255ca in /usr/bin/clickhouse
11. ? @ 0x0000000013226411 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000ea070cf in /usr/bin/clickhouse
13. ? @ 0x000000000ea0d0c1 in /usr/bin/clickhouse
14. ? @ 0x00007f94a948e609 in ?
15. __clone @ 0x00007f94a93b3133 in ?
 (version 23.7.4.5 (official build))`


can version donwngrade fix this issue until bug is resolved?

**Comment by tavplubix** [comment] 2023-08-28 13:06
No logs or reproducible example were provided. This may be a result of `SYSTEM DROP REPLICA` or manual intervention in ZooKeeper data. 

Possible ways to recover:
https://clickhouse.com/docs/en/sql-reference/statements/system#restore-replica
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#recovery-after-complete-data-loss

**Closed by tavplubix** 2023-08-28 13:06 UTC
Labels: question, st-need-info, st-need-repro

**Comment by tavplubix** [comment] 2023-08-28 16:53
Also, the issue might be caused by `clickhouse-operator`: https://github.com/Altinity/clickhouse-operator/blob/ca6113414e898b5b43f67a2fc77696f4e082f316/pkg/controller/chi/worker-chi-reconciler.go#L105

**Comment by UnamedRus** [comment] 2023-08-28 17:05
I don't think that external tool, which does not interact with zookeeper can cause missing of particular zookeeper prefix (for specific part-replica).

**Comment by tavplubix** [comment] 2023-08-28 17:13
> external tool, which does not interact with zookeeper

It does run `SYSTEM DROP REPLICA`, see the link above.

**Comment by UnamedRus** [comment] 2023-08-28 17:26
In that case, table shouldn't have any data on disk (and issue with part name wouldn't pop up) (table data removed before zk cleanup)


And arent it should fail on start, because of `/host` node is missing and not specific part name?

```
        /// Remove "host" node first to mark replica as dropped (the choice is arbitrary,
        /// it could be any node without children that exists since ancient server versions and not re-created on startup)
        [[maybe_unused]] auto code = zookeeper->tryRemove(fs::path(remote_replica_path) / "host");
        assert(code == Coordination::Error::ZOK || code == Coordination::Error::ZNONODE);
````

and AFAIK `is_active` is ephemeral node, and it can be missing and it should be ok?

**Comment by tavplubix** [comment] 2023-08-28 17:52
> table shouldn't have any data on disk 

Why? 

> table data removed before zk cleanup

No, `SYSTEM DROP REPLICA` only removes metadata from ZooKeeper, it does not care about disk.

> And arent it should fail on start, because of /host node is missing and not specific part name?

That's actually a good point, but the existence of /host node is checked on server startup only. It's not checked when `ReplicatedMergeTreeRestartingThread` restarts replication in runtime (after losing ZooKeeper connection, for example)

> and AFAIK is_active is ephemeral node, and it can be missing and it should be ok?

No, you misunderstood the error message. `is_active` is not missing, its parent node is missing so, we cannot create `is_active`. And the error message from your comment actually means that `/clickhouse/xxx-xxx/tables/0/xxxx/xxxx/replicas/chi-xxx-xx-xxxx-xxx-0-0/parts` is missing, not the node with part name.

**Comment by UnamedRus** [comment] 2023-08-28 18:26
> Why?
> No, SYSTEM DROP REPLICA only removes metadata from ZooKeeper, it does not care about disk.

OK, i looked in DROP TABLE.

> And the error message from your comment actually means that /clickhouse/xxx-xxx/tables/0/xxxx/xxxx/replicas/chi-xxx-xx-xxxx-xxx-0-0/parts is missing, not the node with part name.

As i remember (3 months passed), `/parts` node definitely existed.
I also compared `/parts` between main zk path and replicas, and only some replicas didn't have this part name.
(it existed in replica 0, but was missing in replica 1 & 2)

> error message

How i can understand that from message?

For example, if we run zk->exists, it will return different error message for non existing node and non existing root prefix?

https://github.com/ClickHouse/ClickHouse/blob/98e6a6b09b5256731108aac2ff4808cb1783a99f/src/Storages/StorageReplicatedMergeTree.cpp#L3839

**Comment by tavplubix** [comment] 2023-08-28 18:49
> How i can understand that from message?

Sorry, it's indeed unclear from your message because you did not provide enough context (such as stacktrace). I mixed it up with another similar report. But it's obvious for `is_active` node:

> Transaction failed (No node): Op #0, path: /clickhouse/tables/fd85335c-a1a5-4fc5-9f12-737d05024b1f/0/replicas/service-01-0-0/is_active

> 5. DB::ReplicatedMergeTreeRestartingThread::activateReplica()

https://github.com/ClickHouse/ClickHouse/blob/0502a4c73e11f4377ead87f00a60d6806e15d489/src/Storages/MergeTree/ReplicatedMergeTreeRestartingThread.cpp#L293-L303

> As i remember (3 months passed), /parts node definitely existed.

Then it was a harmless self-healing error that could be safely ignored

**Comment by UnamedRus** [comment] 2023-08-28 19:02
> Then it was a harmless self-healing error that could be safely ignored

It wasn't harmless error, it prevented replica from working.
Starting from beginning of 2023 year, i remember 4 different situations with missing part per replica which required manual intervention and running `SYSTEM DROP REPLICA xxx` or using flags. 

Stack trace from another situation

```
Coordination::Exception: Transaction failed (No node): Op #1, path: /xxxxxxxxxxx/replicas/xxxxxxxxxx/parts/all_442743_468180_18091_467800. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe2322d5 in /usr/bin/clickhouse
1. Coordination::Exception::Exception(String const&, Coordination::Error, int) @ 0x1504fe70 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(String const&, Coordination::Error) @ 0x15050198 in /usr/bin/clickhouse
3. zkutil::KeeperMultiException::KeeperMultiException(Coordination::Error, std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>> const&) @ 0x150668c4 in /usr/bin/clickhouse
4. zkutil::KeeperMultiException::check(Coordination::Error, std::vector<std::shared_ptr<Coordination::Request>, std::allocator<std::shared_ptr<Coordination::Request>>> const&, std::vector<std::shared_ptr<Coordination::Response>, std::allocator<std::shared_ptr<Coordination::Response>>> const&) @ 0x1505b7d2 in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::removePartAndEnqueueFetch(String const&, bool) @ 0x1419374f in /usr/bin/clickhouse
6. DB::ReplicatedMergeTreeQueue::createLogEntriesToFetchBrokenParts() @ 0x1488db41 in /usr/bin/clickhouse
7. DB::ReplicatedMergeTreeRestartingThread::tryStartup() @ 0x148c8d97 in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeRestartingThread::runImpl() @ 0x148c7d82 in /usr/bin/clickhouse
9. DB::ReplicatedMergeTreeRestartingThread::run() @ 0x148c6e5a in /usr/bin/clickhouse
10. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12890fc6 in /usr/bin/clickhouse
11. DB::BackgroundSchedulePool::threadFunction() @ 0x12893eaa in /usr/bin/clickhouse
12. ? @ 0x12894cee in /usr/bin/clickhouse
13. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe301613 in /usr/bin/clickhouse
14. ? @ 0xe307281 in /usr/bin/clickhouse
15. ? @ 0x7f7df4d99609 in ?
16. __clone @ 0x7f7df4cbe133 in ?
```

**Comment by tavplubix** [comment] 2023-08-28 19:10
> It wasn't harmless error, it prevented replica from working.

Then, the parent node was missing. I cannot imagine how a missing part node could break replication, see [the code](https://github.com/ClickHouse/ClickHouse/blob/93dac0c8809e99fbbabb2ef4122908ce88308b95/src/Storages/StorageReplicatedMergeTree.cpp#L3832-L3908). The operation would succeed on retry if the parent node was there.

**Comment by utkarsh2811** [comment] 2023-08-30 06:43
Guys,

The solution provided is a manual intervention. cant we have a permanent fix here which doesnt involve manual intervention?  

Also, can we not close the issue since there is no bug fix provided? If you need any more inputs from my side to reproduce the issue, just me know instead.

**Comment by tavplubix** [comment] 2023-08-30 14:14
> cant we have a permanent fix here

No, we cannot, because no diagnostics were provided, and I'm still not sure if a bug in ClickHouse actually exists. Probably there's nothing to fix.

> can we not close the issue since there is no bug fix provided?

I'm 90% sure that the issue you're facing is a result of `SYSTEM DROP REPLICA`, or manual intervention, or misconfiguration, or something like that. If you think it's not - please provide a detailed report that clearly demonstrates that it's a bug in ClickHouse.

**Comment by tavplubix** [comment] 2023-08-30 14:18
> i face the below error and i cannot create any tables anymore in the cluster

@utkarsh2811, what do you mean by "cannot create any tables anymore in the cluster"? What error exactly do you get when you try to create a table? There's no way the `Couldn't start replication` error could lead to the inability to create any tables at all. Maybe you're facing another issue, and `Couldn't start replication` is just a symptom.
