### ISSUE TITLE
Parsing of unsupported dates should raise an error

### ISSUE THREAD

**Issue by nolar** [ClickHouse/ClickHouse#38951] opened 2022-07-07 10:52 UTC
**Describe the unexpected behaviour**

ClickHouse 21.12.3.32:

```sql
select toDateTime64('2999-01-01', 6) as dt;
-- ┌─────────────────────────dt─┐
-- │ 1925-01-01 00:00:00.000000 │
-- └────────────────────────────┘

select toDateTime64('2283-01-01', 6) as dt;
-- ┌─────────────────────────dt─┐
-- │ 2283-01-01 00:00:00.000000 │
-- └────────────────────────────┘

select toDateTime64('2283-12-31', 6) as dt;
-- ┌─────────────────────────dt─┐
-- │ 2283-11-11 00:00:00.000000 │
-- └────────────────────────────┘
```

ClickHouse 22.6.3.35:

```sql
select toDateTime64('2999-01-01', 6) as dt;
-- ┌─────────────────────────dt─┐
-- │ 2283-11-11 00:00:00.000000 │
-- └────────────────────────────┘

select toDateTime64('2283-01-01', 6) as dt;
-- ┌─────────────────────────dt─┐
-- │ 2283-01-01 00:00:00.000000 │
-- └────────────────────────────┘

select toDateTime64('2283-12-31', 6) as dt;
-- ┌─────────────────────────dt─┐
-- │ 2283-11-11 00:00:00.000000 │
-- └────────────────────────────┘
```

**Expected behavior**

An error should be raised for 2999 and 2283-12-31 because they are out of range (and the app should fail). 

Currently, it makes wrong assumptions that might lead to data corruption or app misbehavior.

**Comment by den-crane** [comment] 2022-07-07 10:55
https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#tostartofmonth

The behavior of parsing incorrect dates is implementation specific. ClickHouse may return zero date, throw an exception or do “natural” overflow.

duplicate of

https://github.com/ClickHouse/ClickHouse/issues/21782
https://github.com/ClickHouse/ClickHouse/issues/8031
https://github.com/ClickHouse/ClickHouse/issues/7633

**Closed by den-crane** 2022-07-07 10:55 UTC
Labels: unexpected behaviour

**Comment by den-crane** [comment] 2022-07-07 10:58
can be solved by https://github.com/ClickHouse/ClickHouse/pull/37995
