### ISSUE TITLE
Performance comparison error in `merge_table_streams` 

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#69275] opened 2024-09-04 19:02 UTC
repeated error in performance comparison tests:

e.g. https://s3.amazonaws.com/clickhouse-test-reports/0/938b5ba0ed506e2c1b8dc58e3dcf297aa8631c0d/performance_comparison__release__[4_4]/report.html

**Comment by nickitat** [comment] 2024-09-09 15:24
this is the error:

```
1098072:2024.09.04 19:06:23.659424 [ 1015 ] {042523bb-9dfb-470b-866d-1fcdef5ce0ab} <Debug> executeQuery: (from [::1]:46608) CREATE TABLE merge_table_streams_1 AS hits_100m_single (stage: Complete)
1098073:2024.09.04 19:06:23.665807 [ 1015 ] {042523bb-9dfb-470b-866d-1fcdef5ce0ab} <Error> executeQuery: Code: 42. DB::Exception: With extended storage definition syntax storage MergeTree requires no parameters
1098074-
1098075-Syntax for the MergeTree table engine:
1098076-
1098077-CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
1098078-(
1098079-    name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1] [TTL expr1],
1098080-    name2 [type2] [DEFAULT|MATERIALIZED|ALIAS expr2] [TTL expr2],
1098081-    ...
1098082-    INDEX index_name1 expr1 TYPE type1(...) [GRANULARITY value1],
1098083-    INDEX index_name2 expr2 TYPE type2(...) [GRANULARITY value2]
1098084-) ENGINE = MergeTree()
1098085-ORDER BY expr
1098086-[PARTITION BY expr]
1098087-[PRIMARY KEY expr]
1098088-[SAMPLE BY expr]
1098089-[TTL expr [DELETE|TO DISK 'xxx'|TO VOLUME 'xxx'], ...]
1098090-[SETTINGS name=value, ...]
1098091-[COMMENT 'comment']
1098092-
1098093-See details in documentation: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/. Other engines of the family support different syntax, see details in the corresponding documentation topics.
1098094-
1098095-If you use the Replicated version of engines, see https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/.
1098096-. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH) (version 24.9.1.1839 (official build)) (from [::1]:46608) (in query: CREATE TABLE merge_table_streams_1 AS hits_100m_single), Stack trace (when copying this message, always include the lines below):
1098097-
1098098-0. ./build_docker/./src/Common/Exception.cpp:111: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000db8723b
1098099-1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007e8114c
1098100-2. ./src/Common/Exception.h:128: DB::Exception::Exception<String const&, String&, char const* const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String&>::type, std::type_identity<char const* const&>::type>, String const&, String&, char const* const&) @ 0x0000000012df8b2d
1098101-3. ./build_docker/./src/Storages/MergeTree/registerStorageMergeTree.cpp:507: DB::create(DB::StorageFactory::Arguments const&) @ 0x0000000012df5a6b
1098102-4. ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x000000001246a51b
1098103-5. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1712: DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x0000000011aa5634
1098104-6. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1536: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x0000000011a9d766
1098105-7. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:2036: DB::InterpreterCreateQuery::execute() @ 0x0000000011aac798
1098106-8. ./build_docker/./src/Interpreters/executeQuery.cpp:1238: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011ee8759
1098107-9. ./build_docker/./src/Interpreters/executeQuery.cpp:1404: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000011ee481a
1098108-10. ./build_docker/./src/Server/TCPHandler.cpp:564: DB::TCPHandler::runImpl() @ 0x000000001309cad4
1098109-11. ./build_docker/./src/Server/TCPHandler.cpp:2484: DB::TCPHandler::run() @ 0x00000000130b83f8
1098110-12. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x0000000015ebd107
1098111-13. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000015ebd599
1098112-14. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000015e8a181
1098113-15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015e8873d
1098114-16. ? @ 0x00007fcca97f2ac3
1098115-17. ? @ 0x00007fcca9884850
1098116-
1098117:2024.09.04 19:06:23.665919 [ 1015 ] {042523bb-9dfb-470b-866d-1fcdef5ce0ab} <Error> TCPHandler: Code: 42. DB::Exception: With extended storage definition syntax storage MergeTree requires no parameters
1098118-
1098119-Syntax for the MergeTree table engine:
1098120-
1098121-CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
1098122-(
1098123-    name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1] [TTL expr1],
1098124-    name2 [type2] [DEFAULT|MATERIALIZED|ALIAS expr2] [TTL expr2],
1098125-    ...
1098126-    INDEX index_name1 expr1 TYPE type1(...) [GRANULARITY value1],
1098127-    INDEX index_name2 expr2 TYPE type2(...) [GRANULARITY value2]
1098128-) ENGINE = MergeTree()
1098129-ORDER BY expr
1098130-[PARTITION BY expr]
1098131-[PRIMARY KEY expr]
1098132-[SAMPLE BY expr]
1098133-[TTL expr [DELETE|TO DISK 'xxx'|TO VOLUME 'xxx'], ...]
1098134-[SETTINGS name=value, ...]
1098135-[COMMENT 'comment']
1098136-
1098137-See details in documentation: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/. Other engines of the family support different syntax, see details in the corresponding documentation topics.
1098138-
1098139-If you use the Replicated version of engines, see https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/.
1098140-. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH), Stack trace (when copying this message, always include the lines below):
1098141-
1098142-0. ./build_docker/./src/Common/Exception.cpp:111: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000db8723b
1098143-1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007e8114c
1098144-2. ./src/Common/Exception.h:128: DB::Exception::Exception<String const&, String&, char const* const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String&>::type, std::type_identity<char const* const&>::type>, String const&, String&, char const* const&) @ 0x0000000012df8b2d
1098145-3. ./build_docker/./src/Storages/MergeTree/registerStorageMergeTree.cpp:507: DB::create(DB::StorageFactory::Arguments const&) @ 0x0000000012df5a6b
1098146-4. ./contrib/llvm-project/libcxx/include/__functional/function.h:848: ? @ 0x000000001246a51b
1098147-5. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1712: DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&, DB::LoadingStrictnessLevel) @ 0x0000000011aa5634
1098148-6. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:1536: DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x0000000011a9d766
1098149-7. ./build_docker/./src/Interpreters/InterpreterCreateQuery.cpp:2036: DB::InterpreterCreateQuery::execute() @ 0x0000000011aac798
1098150-8. ./build_docker/./src/Interpreters/executeQuery.cpp:1238: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011ee8759
1098151-9. ./build_docker/./src/Interpreters/executeQuery.cpp:1404: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000011ee481a
1098152-10. ./build_docker/./src/Server/TCPHandler.cpp:564: DB::TCPHandler::runImpl() @ 0x000000001309cad4
1098153-11. ./build_docker/./src/Server/TCPHandler.cpp:2484: DB::TCPHandler::run() @ 0x00000000130b83f8
1098154-12. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x0000000015ebd107
1098155-13. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x0000000015ebd599
1098156-14. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x0000000015e8a181
1098157-15. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015e8873d
1098158-16. ? @ 0x00007fcca97f2ac3
1098159-17. ? @ 0x00007fcca9884850
1098160-
1098161:2024.09.04 19:06:23.665945 [ 1015 ] {042523bb-9dfb-470b-866d-1fcdef5ce0ab} <Debug> TCPHandler: Processed in 0.006743634 sec.
```

the problem is that `hits_100m_single` is not declared with `extended storage definition`:

```
2024-09-04 18:17:46	 default	hits_100m_single	00000000-0000-0000-0000-000000000000	MergeTree	0	['left/db/data/default/hits_100m_single/']	/workspace/left/db/metadata/default/hits_100m_single.sql	2015-05-26 21:30:23	0	[]	[]	CREATE TABLE default.hits_100m_single (`WatchID` UInt64, `JavaEnable` UInt8, `Title` String, `GoodEvent` Int16, `EventTime` DateTime, `EventDate` Date, `CounterID` UInt32, `ClientIP` UInt32, `RegionID` UInt32, `UserID` UInt64, `CounterClass` Int8, `OS` UInt8, `UserAgent` UInt8, `URL` String, `Referer` String, `Refresh` UInt8, `RefererCategoryID` UInt16, `RefererRegionID` UInt32, `URLCategoryID` UInt16, `URLRegionID` UInt32, `ResolutionWidth` UInt16, `ResolutionHeight` UInt16, `ResolutionDepth` UInt8, `FlashMajor` UInt8, `FlashMinor` UInt8, `FlashMinor2` String, `NetMajor` UInt8, `NetMinor` UInt8, `UserAgentMajor` UInt16, `UserAgentMinor` FixedString(2), `CookieEnable` UInt8, `JavascriptEnable` UInt8, `IsMobile` UInt8, `MobilePhone` UInt8, `MobilePhoneModel` String, `Params` String, `IPNetworkID` UInt32, `TraficSourceID` Int8, `SearchEngineID` UInt16, `SearchPhrase` String, `AdvEngineID` UInt8, `IsArtifical` UInt8, `WindowClientWidth` UInt16, `WindowClientHeight` UInt16, `ClientTimeZone` Int16, `ClientEventTime` DateTime, `SilverlightVersion1` UInt8, `SilverlightVersion2` UInt8, `SilverlightVersion3` UInt32, `SilverlightVersion4` UInt16, `PageCharset` String, `CodeVersion` UInt32, `IsLink` UInt8, `IsDownload` UInt8, `IsNotBounce` UInt8, `FUniqID` UInt64, `OriginalURL` String, `HID` UInt32, `IsOldCounter` UInt8, `IsEvent` UInt8, `IsParameter` UInt8, `DontCountHits` UInt8, `WithHash` UInt8, `HitColor` FixedString(1), `LocalEventTime` DateTime, `Age` UInt8, `Sex` UInt8, `Income` UInt8, `Interests` UInt16, `Robotness` UInt8, `RemoteIP` UInt32, `WindowName` Int32, `OpenerName` Int32, `HistoryLength` Int16, `BrowserLanguage` FixedString(2), `BrowserCountry` FixedString(2), `SocialNetwork` String, `SocialAction` String, `HTTPError` UInt16, `SendTiming` UInt32, `DNSTiming` UInt32, `ConnectTiming` UInt32, `ResponseStartTiming` UInt32, `ResponseEndTiming` UInt32, `FetchTiming` UInt32, `SocialSourceNetworkID` UInt8, `SocialSourcePage` String, `ParamPrice` Int64, `ParamOrderID` String, `ParamCurrency` FixedString(3), `ParamCurrencyID` UInt16, `OpenstatServiceName` String, `OpenstatCampaignID` String, `OpenstatAdID` String, `OpenstatSourceID` String, `UTMSource` String, `UTMMedium` String, `UTMCampaign` String, `UTMContent` String, `UTMTerm` String, `FromTag` String, `HasGCLID` UInt8, `RefererHash` UInt64, `URLHash` UInt64, `CLID` UInt32) ENGINE = MergeTree(EventDate, intHash32(UserID), (CounterID, EventDate, intHash32(UserID), EventTime), 8192)	MergeTree(EventDate, intHash32(UserID), (CounterID, EventDate, intHash32(UserID), EventTime), 8192)		toYYYYMM(EventDate)	CounterID, EventDate, intHash32(UserID), EventTime	CounterID, EventDate, intHash32(UserID), EventTime	intHash32(UserID)	default	100000000	10990621246	53127244905	1	1	12208	\N	\N		1	[]	[]	[]	[]
```

we determine it by args:

https://github.com/ClickHouse/ClickHouse/blob/e01a448bcc62a7e292766cddc0c817b9e44558d4/src/Storages/MergeTree/registerStorageMergeTree.cpp#L398

so it looks like smth wrong sometimes happens around that place.

**Comment by Algunenano** [comment] 2024-09-09 15:30
Fixed by https://github.com/ClickHouse/ClickHouse/pull/69268, right?

**Closed** 2024-09-09 15:34 UTC
Labels: testing
