### ISSUE TITLE
Regression from 24.5.4 to 24.6.2 when using subqueries without the new analyzer

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#66333] opened 2024-07-10 11:37 UTC
24.5.4: https://fiddle.clickhouse.com/db264ecd-0966-409f-a95f-9ff91c44e552
24.6.2: https://fiddle.clickhouse.com/f1ebf5c9-9ce9-4f34-a91f-2888c52572b7

In short, filters are not working correctly on 24.6.2 when analyzer is off and a subquery is used to define an inline field (as far as I can tell, at least, hopefully the examples in the links will make it clearer.

Oddly enough, this query fails (returns 0 rows):

```
SELECT
    *,
    multiIf(product_sku IN (
        SELECT 'p1' as someproduct
    ), 'yes', 'no') AS flag,
    multiIf(product_sku  = 'p1', 'EMEA', 'N/A') AS region
FROM
(
    SELECT customer_id, name, product_sku
    FROM temp.bugcheck1
)
WHERE (flag IN ('yes')) AND (region in ('EMEA'))
settings allow_experimental_analyzer=0;
```

where this query succeeds (returns 1 row):
```
SELECT
    *,
    multiIf(product_sku IN (
        SELECT 'p1' as someproduct
    ), 'yes', 'no') AS flag,
    multiIf(product_sku  = 'p1', 'EMEA', 'N/A') AS region
FROM
(
    SELECT customer_id, name, product_sku
    FROM temp.bugcheck1
)
WHERE (flag IN ('yes')) AND (region = ('EMEA'))
settings allow_experimental_analyzer=0;
```

The only difference being an equality operator being used instead of a "in" operator when filtering for the region column. Plans for the two are identicals but obviously something is different "under the hood".

**Comment by max-vostrikov** [comment] 2024-07-10 13:59
it is certainly looks like an analyzer bug. I've narrowed down the difference between those two queries:
https://fiddle.clickhouse.com/035480fc-da19-4e45-8465-73934294b6eb

they look similar enough. one has `WHERE (flag IN ('yes')) AND (region in ('EMEA'))` and the other only `WHERE (region in ('EMEA'))`.

It seems that EXPLAIN givens different results for them:
Broken:
```
Expression
  CreatingSets (Create sets before main query execution)
    Expression ((Projection + Before ORDER BY))
      Expression
        ReadFromMergeTree (temp.bugcheck1)
    CreatingSet (Create set for subquery)
      Expression ((Projection + Before ORDER BY))
        ReadFromStorage (SystemOne)
```
Working:
```
Expression
  CreatingSets (Create sets before main query execution)
    Expression ((Projection + Before ORDER BY))
      CreatingSets (Create sets before main query execution)
        Expression
          ReadFromMergeTree (temp.bugcheck1)
        CreatingSet (Create set for subquery)
          Expression ((Projection + Before ORDER BY))
            ReadFromStorage (SystemOne)
    CreatingSet (Create set for subquery)
      Expression ((Projection + Before ORDER BY))
        ReadFromStorage (SystemOne)
```

In any case, it seems that it is not reproducible on the head version (`24.7.1`). So I assume whatever it was, it should've been fixed in one of recent PRs and will be gone with next upgrade.

Can we close this one, or this behaviour persists in the most recent build too?

**Comment by max-vostrikov** [comment] 2024-07-15 11:38
added the test for this case in https://github.com/ClickHouse/ClickHouse/pull/66432

**Closed by max-vostrikov** 2024-07-15 11:38 UTC
Labels: st-fixed, potential bug
