### ISSUE TITLE
AVX512VBMI implementation of base64Encode / base64Decode

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#41957] opened 2022-09-30 03:14 UTC
I just got to know this library yesterday https://github.com/WojciechMula/base64-avx512. Make some efforts to use it in base64Encode / base64Decode, and the performance on my local test (enable AVX512 and AVX512VBMI) is quite impressive compared to current approach (Turbo)

- Turbo - single thread:

![ZMn1hglDTR](https://user-images.githubusercontent.com/22796953/193181389-390f8253-c23d-4461-99c5-b0fb7dfac910.jpg)

- Mula - single thread:

![i01oe4QAYR](https://user-images.githubusercontent.com/22796953/193181521-b1fb5266-344c-4350-9224-76cb1355137f.jpg)

- Turbo - multi thread:

![zwcBhCEJUf](https://user-images.githubusercontent.com/22796953/193181471-c851620a-f69e-4532-a8b6-c9f89fe604d7.jpg)

- Mula - multi thread:

![gIInamy6ca](https://user-images.githubusercontent.com/22796953/193181561-03609e87-1891-4a13-9988-fb304acb7a94.jpg)

Have you look at this lib before? One of my concern is it's not actively maintained, and the code quality is actually quite bad.
If you think it's good, then I can make a PR with this library.
Thanks.
@rschu1ze

**Comment by rschu1ze** [comment] 2022-09-30 10:20
@canhld94 Thanks for the interesting hint.

I don't know the historical reason why ClickHouse went for [Turbo Base64](https://github.com/powturbo/Turbo-Base64), but there are seemingly a few advantages of Turbo Base64: a) performance is quite good (looking at the benchmarks on their GitHub page) b) they can deal with erroneous inputs (important for untrusted data) c) they provide a runtime dispatch based on CPU capabilities to the fastest SIMD implementation (this removes the need to dispatch manually in ClickHouse) d) in general, the library is intended for real-world usage and not a mere research prototype.

Mula's AVX-512 decoder has impressive performance (ca. twice as fast in above multi-threaded benchmark) but as far as I see, it lacks the automatic CPU dispatch and since it is the byproduct of a research paper, I don't have much hope that this is added in future (there has not been any update in 3 years). So I guess an implementation into ClickHouse would be hacky.

And there is another consideration: I remember bugs in the AVX-512 code of 3rd party libraries (IIRC: json parsing) which could not be found in CI because not all of ClickHouse's CI machines have AVX-512. So in case of a bug in the super-fast AVX-512 path, we'd have a problem. I think that CI machines will be gradually upgraded along ClickHouse's SIMD requirements as we raise them (c.f. #40459).

Overall, I think integrating the [avx-512 base64 library](https://github.com/WojciechMula/base64-avx512) would not be very beneficial at this point. But what I would love to see is that the new algorithms and techniques are integrated into a more established library, e.g. Turbo Base64 😉

**Comment by canhld94** [comment] 2022-09-30 14:10
> Mula's AVX-512 decoder has impressive performance (ca. twice as fast in above multi-threaded benchmark) but as far as I see, it lacks the automatic CPU dispatch and since it is the byproduct of a research paper, I don't have much hope that this is added in future (there has not been any update in 3 years). So I guess an implementation into ClickHouse would be hacky.
And there is another consideration: I remember bugs in the AVX-512 code of 3rd party libraries (IIRC: json parsing) which could not be found in CI because not all of ClickHouse's CI machines have AVX-512. So in case of a bug in the super-fast AVX-512 path, we'd have a problem.

@rschu1ze Yes, I also has same concerns, so I opened this issue for discussions. In addition, I didn't mean to replace the current Turbo Base64 with Mula's library, but rather to provide customized base64 encode/decode functions in ClickHouse based on Mula's code (like many other PRs have done #37588,  #37870, #39586 ...). Of course, this required us to extensively test the correctness and performance of the customized functions.

> But what I would love to see is that the new algorithms and techniques are integrated into a more established library, e.g. Turbo Base64

This will be the best solution. May be @qoega can provide more insights :).

**Comment by alexey-milovidov** [comment] 2022-09-30 21:30
I'm strongly supporting replacing Turbo-Base64 with the library from Wojciech Mula.

We are disappointed with Turbo-Base64 for several reasons:
1. It does not look like a library, more like a bunch of unfinished pieces of code.
2. Some code paths in the library have bugs and were disabled.
3. The author initially changed the license to be ClickHouse compatible, but the [changed it back](https://github.com/powturbo/Turbo-Base64/commit/203ff3aa057e4ee73b3d008abdd36622be74729e) in next revisions.

**Comment by alexey-milovidov** [comment] 2022-10-01 00:51
Duplicate of #31643.

**Comment by rschu1ze** [comment] 2022-10-02 20:20
Good to know, thanks.

@canhld94 If you would like to contribute - replacing [Turbo-Base64](https://github.com/powturbo/Turbo-Base64) with Lemire's [fastbase64](https://github.com/lemire/fastbase64) (not: Mula's [original code](https://github.com/WojciechMula/base64-avx512) which looks abandoned) would be appreciated. I would be pretty curious how both compare against each other ... at least the measurements at the GitHub page of Turbo make fastbase64 look bad.

Let me close this as dup of https://github.com/ClickHouse/ClickHouse/issues/31643.

**Comment by canhld94** [comment] 2022-10-03 06:20
> Good to know, thanks.
> 
> @canhld94 If you would like to contribute - replacing [Turbo-Base64](https://github.com/powturbo/Turbo-Base64) with Lemire's [fastbase64](https://github.com/lemire/fastbase64) (not: Mula's [original code](https://github.com/WojciechMula/base64-avx512) which looks abandoned) would be appreciated. I would be pretty curious how both compare against each other ... at least the measurements at the GitHub page of Turbo make fastbase64 look bad.
> 
> Let me close this as dup of #31643.

@rschu1ze 
[fastbase64](https://github.com/lemire/fastbase64) also looks an abandon project.
In addition, as Alex mentioned above, [Turbo-Base64](https://github.com/powturbo/Turbo-Base64) is now under GPLv3 license, so CH cannot use its newest code anymore.
Other promising one is [base64](https://github.com/aklomp/base64): BSD-2 license, having support for AVX2, SSSE3, SSE4.1, SSE4.2, AVX (there's an ongoing PR for AVX512). But seem that CH used base64 before but changed to Turbo-Base64 for performance reason (#8444).
IMO, I think [base64](https://github.com/aklomp/base64) is a good candidate. It's used by node.js, and looks actively developing.

**Comment by alexey-milovidov** [comment] 2022-10-04 02:47
And we can edit the libraries and even create a chimera-library if needed...

**Closed** 2023-09-09 14:24 UTC
Labels: feature
