### ISSUE TITLE
Setting short_circuit_function_evaluation do not work as expected

### ISSUE THREAD

**Issue by dimkas78** [ClickHouse/ClickHouse#40323] opened 2022-08-18 04:56 UTC
```
select version()

version()|
---------+
22.3.3.44|
```
Settiing _short_circuit_function_evaluation_ is enabled, as it is by default.

```
select name, value from system.settings where name = 'short_circuit_function_evaluation'`

name                             |value |
---------------------------------+------+
short_circuit_function_evaluation|enable|

```
But any of following queries throws an exception "SQL Error [6] [07000]: Code: 6. DB::Exception: Cannot parse string 'x' as Int8: ..."

```
select if(1=1, 1, toInt8('x'));
select multiIf(1=1, 1, 1=2,  toInt8('x'));
select transform(1, 1, 1, 2, toInt8('x'));
select case when 1=1 then 1 else toInt8('x') end;
```
So, I suppose setting _short_circuit_function_evaluation_ don't work as expected

**Comment by ethack** [comment] 2023-01-25 03:16
I had a similar problem and found this related issue https://github.com/ClickHouse/ClickHouse/issues/40622#issuecomment-1227289712 acknowledges the problem and has a helpful workaround.

```
select if(1=1, 1, toInt8(materialize('x')));
```

**Comment by dimkas78** [comment] 2023-01-25 03:24
Thanks for your attention! But there is no workaround needed :)
Expression toInt8('x') was only the way to illustrate the problem of non working _short_circuit_function_evaluation_  option

**Comment by alexey-milovidov** [comment] 2023-06-24 05:43
Duplicate of #37038.

**Closed by alexey-milovidov** 2023-06-24 05:43 UTC
Labels: duplicate, unexpected behaviour
