### ISSUE TITLE
ALTER TABLE MODIFY SETTING merge_with_ttl_timeout hangs

### ISSUE THREAD

**Issue by iameugenejo** [ClickHouse/ClickHouse#13202] opened 2020-08-01 02:07 UTC
clickhouse version: 20.3.13.127

statement: `ALTER TABLE {table} MODIFY SETTING merge_with_ttl_timeout=300;`

insert rate: 2,600,000 / sec, batched

mutations: 0

The statement gets stuck and causes all the insert statements to the table to not proceed.

I have to force restart clickhouse-server to mitigate.

Since I'm using the buffer table, I'm losing millions of rows from this whenever it happens and I need to restart.

Only way to make such alter statement to work is making sure nothing is being inserted during the alter command.

This doesn't happen all the time, but still very occasionally happens.

**Comment by alexey-milovidov** [comment] 2020-08-01 16:32
As I remember, this is fixed in 20.5.

**Comment by iameugenejo** [comment] 2020-08-01 16:50
@alexey-milovidov That's good to know. Since 20.3 is the latest LTS version, could the fix be applied to 20.3 as well?

**Comment by alexey-milovidov** [comment] 2020-08-01 17:43
No.

It's not a fix and the behaviour in 20.3 is not a bug. Just the way how the system works.
The whole ALTER mechanism was completely rewritten to change it.

**Comment by iameugenejo** [comment] 2020-08-01 17:46
I see. Is there a chance of 20.5 becoming an lts version?

**Comment by alexey-milovidov** [comment] 2020-08-01 18:23
No chance.

LTS versions are shipped every half a year.
Please note that there is no advantage of LTS over stable. Usually LTS is less stable and less performant, the only advantage is longer term of support. But this support is limited only to basic bugfixes.

**Comment by iameugenejo** [comment] 2020-08-02 05:53
Okay, I'll switch to 20.5 for the next upgrade. I understand the less performant part, but it seems like LTS serves no purpose when it can be unstable even with the longer support.

**Closed** 2020-08-02 06:34 UTC
Labels: st-fixed
