### ISSUE TITLE
Using mysql cannot execute another command after use database

### ISSUE THREAD

**Issue by sunny19930321** [ClickHouse/ClickHouse#18213] opened 2020-12-18 06:25 UTC
(you don't have to strictly follow this form)

**Describe the bug**
I'm using clickhouse 20.10.6.27 version, mysql 8.0.21 version.
Using mysql to connect to Clickhouse, cannot execute another command after executing this command（use database）

mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    2
Current database: test

ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    3
Current database: test

ERROR 2006 (HY000): MySQL server has gone away

**Comment by dfullerepoch** [comment] 2020-12-19 01:26
Having the same issue as well.  Please advise.

**Comment by epochslee** [comment] 2020-12-19 01:26
same here

**Comment by sunny19930321** [comment] 2020-12-22 02:41
> Having the same issue as well. Please advise.

I plan to fix the problem

**Comment by sunny19930321** [comment] 2020-12-23 09:39
> Having the same issue as well. Please advise.



> (you don't have to strictly follow this form)
> 
> **Describe the bug**
> I'm using clickhouse 20.10.6.27 version.
> Using mysql to connect to Clickhouse, cannot execute another command after executing this command（use database）
> 
> mysql> use test;
> Reading table information for completion of table and column names
> You can turn off this feature to get a quicker startup with -A
> 
> Database changed
> mysql> show tables;
> ERROR 2006 (HY000): MySQL server has gone away
> No connection. Trying to reconnect...
> Connection id: 2
> Current database: test
> 
> ERROR 2006 (HY000): MySQL server has gone away
> No connection. Trying to reconnect...
> Connection id: 3
> Current database: test
> 
> ERROR 2006 (HY000): MySQL server has gone away



> Having the same issue as well. Please advise.



> Having the same issue as well. Please advise.

This problem was found in mysql version 5.7.31 and above，I plan to fix it

**Comment by sunny19930321** [comment] 2020-12-23 09:39
> Having the same issue as well. Please advise.

This problem was found in mysql version 5.7.31 and above，I plan to fix it

**Comment by tavplubix** [comment] 2021-04-17 09:21
Duplicate of #18926, fixed in #20878

**Closed by tavplubix** 2021-04-17 09:21 UTC
Labels: bug
