### ISSUE TITLE
backslashs in `like` patterns are not handled consistently

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#46682] opened 2023-02-21 19:12 UTC
for patterns like `'%abc%'`, it's treated as a simple substring, as determined in function `likePatternIsSubstring` .

simple  patterns are then stored as a new pattern with every other backslash `\` deleted:
https://github.com/ClickHouse/ClickHouse/blob/49330b373c3315008016d444921b5c4bb394b305/src/Functions/MatchImpl.h#L45-L51

whereas non-simple patterns will be translated as regexps.

**here the inconsistency comes: backslash is not treated the same way**.

for example:
1.  `'%abcd\\-%'`  will be converted to 'abcd-', and ClickHouse searchs for  `abcd-` in column data, matching 'XXXabcd-XXX'
2. `'%ab%d\\-%'`  will be translated as regexp `'ab.*d\\-'`, and ClickHouse searchs for  regexp `ab.*d\\-` in column data, **not** matching 'XXXabcd-XXX'

```sql
select 'XXXabcd-XXX' like '%abcd\\-%';
select 'XXXabcd-XXX' like '%ab%d\\-%';

1
0
```

**Comment by cangyin** [comment] 2023-02-21 19:12
related:
#46654 
#46592

**Comment by nickitat** [comment] 2023-02-22 12:50
duplicate of #46592

**Closed by nickitat** 2023-02-22 12:50 UTC
Labels: question
