### ISSUE TITLE
The data writing performance of 23.3&22.3 version is 6 to 8 times worse than that of 21.3 (in materialized view scenarios)

### ISSUE THREAD

**Issue by yej2021** [ClickHouse/ClickHouse#53590] opened 2023-08-19 16:04 UTC
The data writing performance of 23.3&22.3 is 6 to 8 times worse than that of 21.3 (in materialized view scenarios). Aggregation functions of later versions cannot be concurrently executed by multiple threads.

Reproduce use case：
--DROP TABLE base_tab sync;
CREATE TABLE base_tab
(
   time UInt64,
   id Int32,
   c1 Nullable(Float64),
   c2 Nullable(UInt8),
   c3 Nullable(Float64)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/default/base_tab', '{replica}')
PARTITION BY toYYYYMMDD(toDateTime(time))
PRIMARY KEY (id, time)
ORDER BY (id, time)
TTL toDateTime(time) + toIntervalYear(5.)
SETTINGS index_granularity = 8192;

--DROP TABLE mv_tab sync;
CREATE TABLE mv_tab
(
   time UInt64,
   id   Int32,
   c1_sum Nullable(Float64),
   c2_sum Nullable(UInt8),
   c3_sum Nullable(Float64),
   c1_old_sum Nullable(Float64),
   c2_old_sum Nullable(UInt8),
   c3_old_sum Nullable(Float64)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/default/mv_tab', '{replica}')
PARTITION BY toYYYYMMDD(toDateTime(time))
PRIMARY KEY (id, time)
ORDER BY (id, time)
TTL toDateTime(time) + toIntervalYear(5.)
SETTINGS index_granularity = 8192;

--DROP view agg_mv sync;
CREATE MATERIALIZED VIEW IF NOT EXISTS agg_mv
TO mv_tab
AS
SELECT
  id,
  time,
  sum(base_tab.c1), 
  sum(base_tab.c2), 
  sum(base_tab.c3), 
  sum(b.c1_sum),
  sum(b.c2_sum),
  sum(b.c3_sum)
FROM base_tab LEFT JOIN (
  SELECT
    id,
    time,
    sum(c1_sum) as c1_sum,
    sum(c2_sum) as c2_sum,
    sum(c3_sum) as c3_sum
  FROM mv_tab 
  WHERE id in (select id from base_tab) and time in (select time from base_tab)
  GROUP BY id, time
) as b
ON (base_tab.id = b.id) AND (base_tab.time = b.time)
GROUP BY id, time;

SET send_logs_level = 'trace';
INSERT INTO base_tab SELECT rand() % (365 * 24 * 60 / 5), rand() % 1000000, rand(),rand(),rand() from numbers(10000000);

--TRUNCATE TABLE base_tab sync;
--TRUNCATE TABLE mv_tab sync;
--SELECT COUNT(*) FROM base_tab;
--SELECT COUNT(*) FROM mv_tab;

INSERT INTO base_tab select * from base_tab limit 100000;

**trace log:**
[Aggregation scene multi-threaded work(21.3).txt](https://github.com/ClickHouse/ClickHouse/files/12386267/Aggregation.scene.multi-threaded.work.21.3.txt)
[Aggregation scene single-threaded work(22.3).txt](https://github.com/ClickHouse/ClickHouse/files/12386268/Aggregation.scene.single-threaded.work.22.3.txt)

**Comment by den-crane** [comment] 2023-08-20 15:03
duplicate of https://github.com/ClickHouse/ClickHouse/issues/53480

**Comment by den-crane** [comment] 2023-08-20 15:11
It's very funny to use TTL in the test cases. 

```sql
INSERT INTO d_local.base_tab SELECT rand() % (365 * 24 * 60 / 5), rand() % 1000000, rand(),rand(),rand() from numbers(10000000);

0 rows in set. Elapsed: 11.757 sec. Processed 60.67 million rows, 1.17 GB (5.16 million rows/s., 99.51 MB/s.)

select count() from d_local.base_tab;
┌─count()─┐
│       0 │
└─────────┘
```

**Comment by yej2021** [comment] 2023-08-21 04:26
> It's very funny to use TTL and random data in the test cases.
> 
> ```sql
> INSERT INTO d_local.base_tab SELECT rand() % (365 * 24 * 60 / 5), rand() % 1000000, rand(),rand(),rand() from numbers(10000000);
> 
> 0 rows in set. Elapsed: 11.757 sec. Processed 60.67 million rows, 1.17 GB (5.16 million rows/s., 99.51 MB/s.)
> 
> select count() from d_local.base_tab;
> ┌─count()─┐
> │       0 │
> └─────────┘
> ```

I don't know why.

**Comment by den-crane** [comment] 2023-08-21 14:07
rand() produces dates which a way behind 5 years and TTL removes that data.

**Comment by yej2021** [comment] 2023-08-21 14:41
Oh, got it, haven't paid much attention to this one:)

tks.

**Closed** 2023-08-28 17:56 UTC
Labels: performance
