### ISSUE TITLE
Unable to connect to HDFS: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS].

### ISSUE THREAD

**Issue by hcxgit** [ClickHouse/ClickHouse#16920] opened 2020-11-12 08:46 UTC
Recently,when using the hdfs engine to read hdfs data, i got the question,
How does the HDFS engine use kerberos authentication? or Is there any good solution?
Looking forward to your reply！

**Comment by filimonov** [comment] 2020-11-12 12:53
Work is in progress. Check the PR https://github.com/ClickHouse/ClickHouse/pull/16621

You can help the community by testing [builds](https://clickhouse-builds.s3.yandex.net/16621/7f6e6296a1fdcc8e4162ab01da24dfcc9e895ae9/clickhouse_build_check/report.html) from that PR, and sending your feedback.

Or just wait till it will be finished and merged.

**Comment by filimonov** [comment] 2020-11-13 13:49
Duplicate of #5747

**Closed by filimonov** 2020-11-13 13:49 UTC
Labels: duplicate, question
