### ISSUE TITLE
Stress test (ubsan): Not enough space to add ... in file cache

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#49864] opened 2023-05-14 18:42 UTC
[A link to the report](https://s3.amazonaws.com/clickhouse-test-reports/49503/b2dddf7cf89e9b31c88b58b4cb78542432d71773/stress_test__ubsan_.html)

cc @kssenii

**Comment by kssenii** [comment] 2023-05-15 09:35
duplicate of https://github.com/ClickHouse/ClickHouse/issues/49553

**Closed by kssenii** 2023-05-15 09:35 UTC
Labels: testing
