### ISSUE TITLE
Breaking change after 20.5

### ISSUE THREAD

**Issue by iliyanm** [ClickHouse/ClickHouse#19975] opened 2021-02-02 09:28 UTC
I used v20.4.4 on production and decided to upgrade to latest version, then I started having the problem described below. Then I downgraded to v20.5, but the problems persisted, so I believe this issue is introduced in v20.5

Consider the following schema:
```sql
CREATE TABLE IF NOT EXISTS ` + DBName + `.` + TableNameMeasurements + ` (
	Time DateTime,
	LoggerID UInt64,
	RecordingID UInt64,
	HubID UInt64,
	Temperature SimpleAggregateFunction(anyLast, Nullable(Int16))
) engine=ReplicatedAggregatingMergeTree('` + ZookeeperPath + "/" + DBName + "/" + TableNameMeasurements + `','` + ClickHouseNode + `') PARTITION BY toYYYYMM(Time) ORDER BY (LoggerID, RecordingID, Time, HubID);

CREATE TABLE IF NOT EXISTS ` + DBName + `.` + TableNameLastMeasurements + ` (
	LastTime SimpleAggregateFunction(max, DateTime),
	LoggerID UInt64,
	RecordingID UInt64,
	HubID AggregateFunction(argMax, UInt64, DateTime),
	Temperature AggregateFunction(argMaxOrNull, Int16, DateTime)
) engine=ReplicatedAggregatingMergeTree('` + ZookeeperPath + "/" + DBName + "/" + TableNameLastMeasurements + `','` + ClickHouseNode + `') PARTITION BY tuple() ORDER BY (LoggerID, RecordingID);

CREATE MATERIALIZED VIEW IF NOT EXISTS ` + DBName + `.` + TableNameLastMeasurements + `_mv 
TO ` + DBName + `.` + TableNameLastMeasurements + `
AS SELECT 
max(Time) as LastTime,
LoggerID,
RecordingID,
argMaxState(HubID, Time) as HubID,
argMaxOrNullState(Temperature, Time) as Temperature,
FROM ` + DBName + `.` + TableNameMeasurements + `
GROUP BY LoggerID, RecordingID;

CREATE VIEW IF NOT EXISTS ` + DBName + `.` + TableNameLastMeasurements + `_v AS	
SELECT 
max(LastTime) as Time,
LoggerID, 
RecordingID, 
argMaxMerge(HubID) as HubID,
argMaxOrNullMerge(Temperature) as Temperature,
FROM ` + DBName + `.` + TableNameLastMeasurements + `_mv 
GROUP BY LoggerID, RecordingID;
```

so now when I insert new row in `TableNameMeasurements`, we get following error from materialized view:

```
code: 70, message: Conversion from AggregateFunction(argMaxOrNull, SimpleAggregateFunction(anyLast, Nullable(UInt64)), DateTime) to AggregateFunction(argMaxOrNull, UInt64, DateTime) is not supported: while converting source column Temperature to destination column Temperature: while pushing to view (materialized view name here) (c88c33fc-c542-412c-921e-08e08391cf70)
```

I would really appreciate your help with this.

**Comment by filimonov** [comment] 2021-02-02 12:15
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/17237

Try to use workaround listed there (recreate the MV with stripping NULLs).

**Comment by iliyanm** [comment] 2021-02-08 12:37
@filimonov it works, however we cannot have NULLs inside MV anymore... is it possible to maintain NULLs and use version after v20.5 at all?

**Comment by iliyanm** [comment] 2021-02-15 11:56
I found workaround:

```
argMaxOrNullStateIf(Temperature, Time, Temperature IS NOT NULL) as Temperature,
```

**Closed** 2021-05-31 19:57 UTC
Labels: backward compatibility
