### ISSUE TITLE
Stack Trace with Kafka Engine

### ISSUE THREAD

**Issue by tobzsc** [ClickHouse/ClickHouse#20548] opened 2021-02-16 07:45 UTC
Hey together,

I am constantly seeing the following error in our Clickhouse-Server log:

```
2021.02.16 08:33:37.464738 [ 3920 ] {} <Debug> DiskLocal: Reserving 2.56 MiB on disk `default`, having unreserved 3.04 TiB.
2021.02.16 08:33:37.471144 [ 3920 ] {} <Trace> default.flows_5m (3094fa1f-1262-4053-ab33-d48bdca542ea): Renaming temporary part tmp_insert_20210215_5356_5356_0 to 20210215_2377330_2377330_0.
2021.02.16 08:33:37.471319 [ 3920 ] {} <Trace> StorageKafka (flows): Polled offset 1113585 (topic: flows, partition: 0)
2021.02.16 08:33:37.471432 [ 3920 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.16 08:33:37.471528 [ 3920 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.16 08:33:37.471602 [ 3920 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.16 08:33:37.471696 [ 3920 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.16 08:33:37.471777 [ 3920 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.16 08:33:37.471834 [ 3920 ] {} <Trace> StorageKafka (flows): Re-joining claimed consumer after failure
2021.02.16 08:33:37.477668 [ 3920 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): Code: 518, e.displayText() = DB::Exception: All commit attempts failed. Last block was already written to target table(s), but was not committed to Kafka., Stack trace (when copying this message, always include the lines below):

0. DB::ReadBufferFromKafkaConsumer::commit() @ 0xf23ef9a in /usr/bin/clickhouse
1. DB::StorageKafka::streamToViews() @ 0xf232720 in /usr/bin/clickhouse
2. DB::StorageKafka::threadFunc(unsigned long) @ 0xf231488 in /usr/bin/clickhouse
3. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0xe862b30 in /usr/bin/clickhouse
4. DB::BackgroundSchedulePool::threadFunction() @ 0xe864b27 in /usr/bin/clickhouse
5. ? @ 0xe8658f2 in /usr/bin/clickhouse
6. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x84ff90f in /usr/bin/clickhouse
7. ? @ 0x85033a3 in /usr/bin/clickhouse
8. start_thread @ 0x814a in /usr/lib64/libpthread-2.28.so
9. clone @ 0xfcf23 in /usr/lib64/libc-2.28.so
 (version 21.2.3.15 (official build))
2021.02.16 08:33:37.477725 [ 3920 ] {} <Trace> StorageKafka (flows): Execution took 5649 ms.
2021.02.16 08:33:37.587036 [ 15549 ] {} <Trace> MergeTreeSequentialSource: Reading 137 marks from part 20210215_2377326_2377326_0, total 1113585 rows starting from the beginning of the part, column Date
```

I am having the following environment:
CentOS 8
Clickhouse 21.2.3.15-2
Kafka 2.7.0

This error seems to happen every single minute. Is there any way to debug this further?

**Comment by filimonov** [comment] 2021-02-16 21:19
Discussed in slack. Not clear why it have 'no offset stored'...

Will try to look deeper, if you will find some extra info - please let me know.

**Comment by chenziliang** [comment] 2021-02-16 23:18
`No offset stored` is usually not an error if client (`StorageKafka` in this case) doesn't consume any message from Kafka and didn't get the offset updated. I think this is a bug in cppkafka which shall treat this error code (RD_KAFKA_RESP_ERR__NO_OFFSET) as no error https://github.com/mfontanini/cppkafka/blob/master/src/consumer.cpp#L300; https://github.com/mfontanini/cppkafka/blob/master/src/kafka_handle_base.cpp#L264

**Comment by tobzsc** [comment] 2021-02-17 08:00
I just went through some further debugging. @filimonov gave me the advice to check it with a version lower than 21.2 as there was a change with librdkafka. So I checked several lower versions all with the same issue. But here are now some further information:

I enabled sending crashes to sentry in the config and the stack trace slightly changed:

```
2021.02.17 08:51:39.734720 [ 25487 ] {} <Trace> StorageKafka (flows): Polled batch of 65505 messages. Offsets position: [ flows[0:655050] ]
2021.02.17 08:51:40.007169 [ 25487 ] {} <Trace> StorageKafka (flows): Polled batch of 65505 messages. Offsets position: [ flows[0:720555] ]
2021.02.17 08:51:40.279126 [ 25487 ] {} <Trace> StorageKafka (flows): Polled batch of 65505 messages. Offsets position: [ flows[0:786060] ]
2021.02.17 08:51:40.612876 [ 25487 ] {} <Trace> StorageKafka (flows): Polled batch of 65505 messages. Offsets position: [ flows[0:851565] ]
2021.02.17 08:51:40.885628 [ 25487 ] {} <Trace> StorageKafka (flows): Polled batch of 65505 messages. Offsets position: [ flows[0:917070] ]
2021.02.17 08:51:41.158193 [ 25487 ] {} <Trace> StorageKafka (flows): Polled batch of 65505 messages. Offsets position: [ flows[0:982575] ]
2021.02.17 08:51:41.466140 [ 25487 ] {} <Trace> StorageKafka (flows): Polled batch of 65505 messages. Offsets position: [ flows[0:1048080] ]
2021.02.17 08:51:41.766252 [ 25487 ] {} <Trace> StorageKafka (flows): Polled batch of 65505 messages. Offsets position: [ flows[0:1113585] ]
2021.02.17 08:51:42.083018 [ 25487 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2021.02.17 08:51:42.117317 [ 25487 ] {} <Debug> DiskLocal: Reserving 116.82 MiB on disk `default`, having unreserved 3.39 TiB.
2021.02.17 08:51:42.326952 [ 25487 ] {} <Trace> default.flows_raw: Renaming temporary part tmp_insert_20210215_6323_6323_0 to 20210215_6393_6393_0.
2021.02.17 08:51:42.327114 [ 25468 ] {} <Trace> default.flows_raw: Found 5 old parts to remove.
2021.02.17 08:51:42.327153 [ 25468 ] {} <Debug> default.flows_raw: Removing part from filesystem 20210215_6322_6322_0
2021.02.17 08:51:42.327253 [ 25487 ] {} <Trace> StorageKafka (flows): Polled offset 1113585 (topic: flows, partition: 0)
2021.02.17 08:51:42.327411 [ 25487 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.17 08:51:42.327737 [ 25487 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.17 08:51:42.328100 [ 25487 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.17 08:51:42.328359 [ 25487 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.17 08:51:42.328616 [ 25487 ] {} <Error> StorageKafka (flows): Exception during commit attempt: Local: No offset stored
2021.02.17 08:51:42.328872 [ 25487 ] {} <Trace> StorageKafka (flows): Re-joining claimed consumer after failure
2021.02.17 08:51:42.335772 [ 25468 ] {} <Debug> default.flows_raw: Removing part from filesystem 20210215_6323_6323_0
2021.02.17 08:51:42.338674 [ 25487 ] {} <Error> void DB::StorageKafka::threadFunc(): Code: 518, e.displayText() = DB::Exception: All commit attempts failed. Last block was already written to target table(s), but was not committed to Kafka., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18bbe140 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe61432d in /usr/bin/clickhouse
2. ? @ 0x15f2fcaa in /usr/bin/clickhouse
3. DB::KafkaBlockInputStream::commit() @ 0x15f24599 in /usr/bin/clickhouse
4. DB::StorageKafka::streamToViews() @ 0x15f0064c in /usr/bin/clickhouse
5. DB::StorageKafka::threadFunc() @ 0x15f01049 in /usr/bin/clickhouse
6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x15623cf9 in /usr/bin/clickhouse
7. DB::BackgroundSchedulePool::threadFunction() @ 0x15624182 in /usr/bin/clickhouse
8. ? @ 0x156242b2 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe641b47 in /usr/bin/clickhouse
10. ? @ 0xe640093 in /usr/bin/clickhouse
11. start_thread @ 0x814a in /usr/lib64/libpthread-2.28.so
12. __clone @ 0xfcf23 in /usr/lib64/libc-2.28.so
 (version 20.8.7.15 (official build))
2021.02.17 08:51:42.338749 [ 25487 ] {} <Trace> StorageKafka (flows): Execution took 5789 ms.
2021.02.17 08:51:42.343623 [ 25468 ] {} <Debug> default.flows_raw: Removing part from filesystem 20210215_6324_6324_0
2021.02.17 08:51:42.351517 [ 25468 ] {} <Debug> default.flows_raw: Removing part from filesystem 20210215_6325_6325_0
2021.02.17 08:51:42.359296 [ 25468 ] {} <Debug> default.flows_raw: Removing part from filesystem 20210215_6326_6326_0
2021.02.17 08:51:42.838958 [ 25485 ] {} <Debug> StorageKafka (flows): Started streaming to 1 attached views
2021.02.17 08:51:42.840130 [ 25485 ] {} <Trace> StorageKafka (flows): Already subscribed to topics: [flows]
2021.02.17 08:51:42.840181 [ 25485 ] {} <Trace> StorageKafka (flows): Already assigned to: [ flows[0:#] ]
2021.02.17 08:51:42.840467 [ 25485 ] {} <Trace> StorageKafka (flows): Rebalance initiated. Revoking partitions: [ flows[0:#] ]
2021.02.17 08:51:42.842142 [ 25485 ] {} <Trace> StorageKafka (flows): Topics/partitions assigned: [ flows[0:#] ]
2021.02.17 08:51:43.340611 [ 25485 ] {} <Trace> StorageKafka (flows): Polled offset INVALID (topic: flows, partition: 0)
2021.02.17 08:51:43.340649 [ 25485 ] {} <Trace> StorageKafka (flows): Nothing to commit.
2021.02.17 08:51:43.352122 [ 25485 ] {} <Trace> StorageKafka (flows): Stream(s) stalled. Reschedule.
2021.02.17 08:51:43.352180 [ 25485 ] {} <Trace> StorageKafka (flows): Execution took 513 ms.
2021.02.17 08:51:43.688772 [ 25456 ] {} <Debug> DNSResolver: Updating DNS cache
2021.02.17 08:51:43.689221 [ 25456 ] {} <Debug> DNSResolver: Updated DNS cache
2021.02.17 08:51:43.852350 [ 25488 ] {} <Debug> StorageKafka (flows): Started streaming to 1 attached views
2021.02.17 08:51:43.853483 [ 25488 ] {} <Trace> StorageKafka (flows): Already subscribed to topics: [flows]
2021.02.17 08:51:43.853532 [ 25488 ] {} <Trace> StorageKafka (flows): Already assigned to: [ flows[0:#] ]
2021.02.17 08:51:43.896717 [ 25488 ] {} <Trace> StorageKafka (flows): Polled batch of 65505 messages. Offsets position: [ flows[0:65505] ]
```

When I enable kafka debugging `<kafka><debug>all</debug></kafka>` the log looks like the following:
See the following nopaste: https://paste.23m.com/?4700d440387aa73f#DpJWpJeci9ppYJ1EaW2LosUZvfHzJKcap4otvoXMAnPt

I tried to play with the kafka engine options like **max_block_size** and **commit_every_thread**. I even played with the number of partitions. But all lead to the same result.

If you want me to do some further debuging just give me an advice and I will gladly have a look at it.

**Comment by filimonov** [comment] 2021-02-17 13:28
> No offset stored is usually not an error if client (StorageKafka in this case) doesn't consume any message from Kafka and didn't get the offset updated. I think this is probably a bug in cppkafka which shall treat this error code (RD_KAFKA_RESP_ERR__NO_OFFSET) 

That's true, but normally we don't try to do commit unless we did store offset explicitly. 

BUT there is one exception: https://github.com/ClickHouse/ClickHouse/issues/12295 

If you consume several topics - one of the topic can have data, while the other respond with RD_KAFKA_RESP_ERR__NO_OFFSET 

@tobzsc  do you consume single topic?

**Comment by tobzsc** [comment] 2021-02-17 13:45
I consume a single topic. The issue was solved by deleting the complete topic which consisted of two partitions and recreating it again with six partitions. Really weird.

**Comment by filimonov** [comment] 2021-02-17 13:52
OK, strange. And what is number of consumers - inside same clickhouse server / overall?

**Comment by tobzsc** [comment] 2021-02-19 11:06
In this scenario it was a single Kafka broker. A single Clickhouse instance is the only consumer.

**Comment by filimonov** [comment] 2021-02-22 12:38
1) The consumer group exists and was committed at the position 9606141231.
2) then started to fetch it from that position it responded  "Broker: Offset out of range" 
3) then offset reset happen "offset reset (at offset 9606141231) to BEGINNING: Broker: Offset out of range: Broker: Offset out of range" 
4) then consumption continues from the topic start 
```
Topic flows [0] in state active at offset 0 (0/1048545 msgs, 0/65536 kb queued, opv 124) is fetchable
Fetch topic flows [0] at offset 0 (v124)
Topic flows [0] MessageSet size 1048576, error "Success", MaxOffset 76262732, LSO 76262732, Ver 124/124
...
```
5) Later commit attempt happens, but the offset we try to commit is before the commit already committed:
```
[rdk:OFFSET] [thrd:main]: Topic flows [0]: stored offset 1113585, committed offset 9606141231: not including in commit
```

6) and finally we get:
```
[rdk:COMMIT] [thrd:main]: OffsetCommit for 1 partition(s) in join-state steady: manual: returned: Local: No offset stored 
```

More detailed log fragment: https://gist.github.com/filimonov/894f37bc7bf43606180bfc1c8b7eb34c

So it's definitely not a bug (I have no idea how to call that :) ) most probably that happened due to some topic reconfiguration or some topic cleanup. 

>  deleting the complete topic which consisted of two partitions 

According to logs - it looks like it had only one partition. 

> The issue was solved by deleting the complete topic  

The simpler option would be to drop the consumer group. 

Actionable things here:
1) ensure why those 2 lines: 
```
<Debug> StorageKafka (flows): [rdk:OFFSET] [thrd:main]: flows [0]: offset reset (at offset 9606141231) to BEGINNING: Broker: Offset out of range: Broker: Offset out of range
... 
<Debug> StorageKafka (flows): [rdk:OFFSET] [thrd:main]: Topic flows [0]: stored offset 1113585, committed offset 9606141231: not including in commit
```
have so low verbosity. It rather looks like those should be warnings. 

2) consider ignoring RD_KAFKA_RESP_ERR__NO_OFFSET just like https://github.com/ClickHouse/ClickHouse/issues/20548#issuecomment-780180701 proposed (there are some pros / cons).

**Closed** 2021-06-23 13:14 UTC
Labels: comp-kafka, invalid
