### ISSUE TITLE
MaterializedMySQL incomplete DDL handling

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#42341] opened 2022-10-16 07:54 UTC
2022.10.16 15:40:53.319565 [ 30601 ] {c920b1a6-ba64-4ca1-b372-20ef6936e412} <Error> MaterializedMySQLSyncThread(): Query EXTERNAL DDL FROM MySQL(hwsj_im, hwsj_im) create database if not exists hwsj_im_2022 wasn't finished successfully: Code: 62. DB::Exception: Syntax error: failed at position 112 ('database'): database if not exists hwsj_im_2022. Expected one of: TEMPORARY, TABLE. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ec73a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x1626b55f in /usr/bin/clickhouse
2. ? @ 0x1511427f in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x15113e77 in /usr/bin/clickhouse
4. ? @ 0x144fb89b in /usr/bin/clickhouse
5. DB::MaterializedMySQLSyncThread::executeDDLAtomic(DB::MySQLReplication::QueryEvent const&) @ 0x144fabbf in /usr/bin/clickhouse
6. void DB::commitMetadata<std::__1::function<void ()> const&>(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1450ed12 in /usr/bin/clickhouse
7. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x1450eb82 in /usr/bin/clickhouse
8. DB::MaterializedMySQLSyncThread::onEvent(DB::MaterializedMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0x144f4d91 in /usr/bin/clickhouse
9. DB::MaterializedMySQLSyncThread::synchronization() @ 0x144f1dd7 in /usr/bin/clickhouse
10. ? @ 0x145008ac in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4ae1a8 in /usr/bin/clickhouse
12. ? @ 0xa4b13bd in /usr/bin/clickhouse
13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
14. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.8.6.71 (official build))
2022.10.16 15:40:53.319693 [ 30601 ] {} <Error> MaterializedMySQLSyncThread: Code: 62. DB::Exception: Syntax error: failed at position 112 ('database'): database if not exists hwsj_im_2022. Expected one of: TEMPORARY, TABLE: While executing MYSQL_QUERY_EVENT. The query: create database if not exists hwsj_im_2022. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ec73a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x1626b55f in /usr/bin/clickhouse
2. ? @ 0x1511427f in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x15113e77 in /usr/bin/clickhouse
4. ? @ 0x144fb89b in /usr/bin/clickhouse
5. DB::MaterializedMySQLSyncThread::executeDDLAtomic(DB::MySQLReplication::QueryEvent const&) @ 0x144fabbf in /usr/bin/clickhouse
6. void DB::commitMetadata<std::__1::function<void ()> const&>(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1450ed12 in /usr/bin/clickhouse
7. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x1450eb82 in /usr/bin/clickhouse
8. DB::MaterializedMySQLSyncThread::onEvent(DB::MaterializedMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0x144f4d91 in /usr/bin/clickhouse
9. DB::MaterializedMySQLSyncThread::synchronization() @ 0x144f1dd7 in /usr/bin/clickhouse
10. ? @ 0x145008ac in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4ae1a8 in /usr/bin/clickhouse
12. ? @ 0xa4b13bd in /usr/bin/clickhouse
13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
14. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.8.6.71 (official build))

**Comment by alexey-milovidov** [comment] 2022-10-16 20:51
Need help from @stigsb

**Comment by stigsb** [comment] 2022-10-17 08:16
This is caused by incomplete DDL handling in MaterializedMySQL. The fix is to either ignore failing DDL queries (we do that internally), or to extend the parser.

@alexey-milovidov could you rename this to something like "MaterializedMySQL incomplete DDL handling"? Feel free to assign it to me.

**Comment by crqphuaat8833** [comment] 2023-06-14 10:21
DB::Exception: Syntax error: failed at position 126 ('FLUSH'): FLUSH TABLES.
is flush tables supported at the latest version？my version is 22.6.3.35

**Comment by alexey-milovidov** [comment] 2023-09-06 17:58
@stigsb is there any progress?

**Comment by stigsb** [comment] 2023-09-06 18:02
> @stigsb is there any progress?

Yes, I am in the process of breaking up our changes into logical pieces right now, and have started making PRs. Over the next month I expect all them to be submitted.

**Comment by alexey-milovidov** [comment] 2023-12-20 06:57
MaterializedMySQL is not officially supported. Let's close and wait while a pull request from @stigsb appears.

**Closed by alexey-milovidov** 2023-12-20 06:57 UTC
Labels: help wanted, st-need-info, unexpected behaviour
