### ISSUE TITLE
Wrong aggregation result since 21.11

### ISSUE THREAD

**Issue by winter7** [ClickHouse/ClickHouse#31986] opened 2021-11-30 11:10 UTC
**Describe what's wrong**
Since it is not necessarily reproducible in original data set, so I will just describe what it looks like:
```
CREATE TABLE t
(
    id Int64,
    type String,
    values Float64,
    event_date DateTime
)
ENGINE = ReplicatedMergeTree('/{shard}/path', '{replica}')
PARTITION BY (toYYYYMMDD(event_date))
ORDER BY (id);

-- insert some data

SELECT * FROM t
┌──id─┬─type──┬──values─┬──────────event_date─┐
│ 111 │  aaa  │ 23.1234 │ 2021-11-30 00:00:00 │
│ 222 │  bbb  │ 52.1124 │ 2021-11-30 00:00:00 │
└─────┴───────┴─────────┴─────────────────────┘
```
And here is the query like:
```
SELECT
    id, type, sum(values)
FROM t
WHERE type = 'aaa'
GROUP BY id, type
```
The result is expected to be
```
┌──id─┬─type──┬─sum(values)─┐
│ 111 │  aaa  │     23.1234 │
└─────┴───────┴─────────────┘
```
But in version `21.11` I just got result as below:
```
┌──id─┬─type──┬─sum(values)─┐
│ 111 │  aaa  │     23.1234 │
│ 222 │  aaa  │     52.1124 │
└─────┴───────┴─────────────┘
```
It looks like the filter `type = 'aaa'` worked in a strange way that the row with `id = 222` was also selected into the result and the row's `type` field was assigned with the value `'aaa'` where `id = 222` never had `type = 'aaa'`.

Please let me know if I didn't make myself clear.

**Does it reproduce on recent release?**
According to my test, the misbehavior happens in `21.11.2.2`,`21.11.3.6` and `21.11.4.14`.
But it always works as expected in and before `21.10.3.9`.
So I assume it is related to some changes introduced since `21.11`.

**How to reproduce**
It is not necessarily reproducible in original data set. I haven't found a pattern yet. So it's hard to give an exact example. 
The example above is more like a description of this issue. In fact I can't reproduce it by this example in `21.11`.
I firstly found this issue because I was comparing a large number of regression-query result between `21.11` and older version and I got different result rows in some cases.
I'm not sure if this issue happens in your CI regression cases.
But it surely is a bug that under some circumstances, filters misbehaved and rows that was expected to filtered out would be wrongly shown in the result set. 

It is introduced since 21.11, please pay serious attention.

**Error message and/or stacktrace**
No exception was thrown.

**Additional context**
Let me know if you need any more information.

**Comment by nikitamikhaylov** [comment] 2021-11-30 13:05
I can't reproduce this either. Please provide us the result of this query `select * from system.settings where changed` and also try to disable all the settings that start with the word `optimize`

**Comment by den-crane** [comment] 2021-11-30 14:28
Try to check is it the same part for these rows or not 

```
SELECT
    id, type, sum(values), max(_part)
FROM t
WHERE type = 'aaa'
GROUP BY id, type


SELECT
    id, type, sum(values), _part
FROM t
WHERE type = 'aaa'
GROUP BY id, type, _part

```

**Comment by winter7** [comment] 2021-12-01 05:02
Pretty sure it's all about this setting: `optimize_move_to_prewhere = 1` in version `21.11`. 
When I separately execute `set optimize_move_to_prewhere=0`, the query result turns out to be correct.
I will give more details later.

**Comment by winter7** [comment] 2021-12-01 08:54
Hi @nikitamikhaylov , thanks for reminding. 
I tried to disable each setting that starts with prefix `optimize` one by one to find out which one might affect and finally nailed on this setting `optimize_move_to_prewhere`. 
And then I tried to figure out the effects from my original settings by using `select * from system.settings where changed` and disabled them one by one and found this exact setting `use_uncompressed_cache` affected.
**So in short, only when both settings `optimize_move_to_prewhere` and `use_uncompressed_cache` are enabled, this misbehaved issue would happen. Disabling either setting would make the query result turn out to be correct.**
And now all my regression cases passed in these two ways: by disabling `optimize_move_to_prewhere`.

Hi @den-crane , thanks too.
According to your suggestion, I checked the part of the correct rows and wrongly shown rows and found that there is no obvious connection between right-rows and wrong-rows. Some of right-rows and wrong-rows are in same part and some are not. But it is worth pointing out that, the misbehaved filter is low cardinality String field, and the filter is not completely ineffective, which means not all rows in the table are selected into result. Only a few rows are wrongly selected but I really cannot see anything special about these wrongly selected rows.
Hope it helps :( 

Please let me know if you need any more information.

**Comment by CurtizJ** [comment] 2021-12-01 12:39
@winter7 
You mentioned that disabling setting `use_uncompressed_cache` helped you. So, then it's the same issue as in #31449 and #31857 and it have been already fixed in #31826.

**Closed by CurtizJ** 2021-12-01 12:39 UTC
Labels: st-need-repro, potential bug

**Comment by winter7** [comment] 2021-12-02 08:58
@CurtizJ Thanks for your effort! Just wondering would you be able to build a new image in `21.11`?

**Comment by alexey-milovidov** [comment] 2021-12-02 09:03
Yes, it will be backported.
