### ISSUE TITLE
toString fails to handle nullable Enum

### ISSUE THREAD

**Issue by ethframe** [ClickHouse/ClickHouse#26949] opened 2021-07-29 07:51 UTC
**Describe the bug**

`toString` fails to handle `NULL` value in an Enum column.

**Does it reproduce on recent release?**

Yes, reproduces on `ClickHouse 21.7.4.18 with revision 54452` (latest docker image).

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**

Table and data:

```sql
CREATE TABLE t_enum_nullable
(
    x Nullable( Enum8('hello' = 1, 'world' = 2) )
)
ENGINE = TinyLog

INSERT INTO t_enum_nullable Values('hello'),('world'),(NULL)
```

Query:

```sql
SELECT toString(x) FROM t_enum_nullable FORMAT JSONEachRow
```

**Expected behavior**

```
{"toString(x)":"hello"}
{"toString(x)":"world"}
{"toString(x)":null}
```

**Error message and/or stacktrace**

```
Code: 36, e.displayText() = DB::Exception: Unexpected value 0 in enum: while executing 'FUNCTION toString(x :: 0) -> toString(x) Nullable(String) : 1' (version 21.7.4.18 (official build)
```

**Additional context**

I expect `toString` to produce `NULL` in this case since it is consistent with `toInt8` behavior. Query

```sql
SELECT toInt8(x) FROM t_enum_nullable FORMAT JSONEachRow
```
returns
```
{"toInt8(x)":1}
{"toInt8(x)":2}
{"toInt8(x)":null}
```

**Comment by den-crane** [comment] 2021-07-29 12:27
not a bug, never worked.

**Comment by ethframe** [comment] 2021-07-29 13:00
> never worked

Then could this issue be tagged as a feature request?

**Comment by vdimir** [comment] 2021-07-30 06:32
Fixed in master https://github.com/ClickHouse/ClickHouse/pull/26123

**Closed by vdimir** 2021-07-30 06:32 UTC
Labels: unexpected behaviour
