### ISSUE TITLE
AggregatingMergeTree appears to discard some row state when merging

### ISSUE THREAD

**Issue by pgruderman** [ClickHouse/ClickHouse#9374] opened 2020-02-26 00:45 UTC
**Observed Behaviour**
We have a database containing a single table that stores time series data with 190 columns.  We have two materialized views of the base table that aggregate the time series into maximum and average values in hourly and daily buckets.

We have observed that the aggregated values are incorrect in our test environment.  It appears as though the AggregatingMergeTree is skipping some rows.  In the worst cases, the hourly and daily tables end up with the values from the first row in each associated time range.  So if we're aggregating values in the range [12:00, 13:00) say, then the maximum and minimum value in the materialized view are both the value recorded at 12:00.  The remaining values in that range are ignored.

For example, here is some aggregated data pulled from our base table:
```
SELECT
    timestamp,
    avg(cpu_utilization) AS cpu_avg,
    max(cpu_utilization) AS cpu_max
FROM metrics
WHERE uuid = '2ea72a28-aa67-105b-a791-5db4056d985f'
GROUP BY toStartOfHour(timestamp) AS timestamp
ORDER BY timestamp DESC
LIMIT 5

┌───────────timestamp─┬────────────cpu_avg─┬────────────cpu_max─┐
│ 2020-02-26 00:00:00 │  3.910673124449594 │  4.970379829406738 │
│ 2020-02-25 23:00:00 │ 4.3566749632358555 │  6.153926372528076 │
│ 2020-02-25 22:00:00 │  4.434089648723602 │  6.279290199279785 │
│ 2020-02-25 21:00:00 │  4.353091228299025 │ 6.1710381507873535 │
│ 2020-02-25 20:00:00 │  4.393078631162643 │  5.869975566864014 │
└─────────────────────┴────────────────────┴────────────────────┘
```

Now here is the same data pulled from our materialized view:

```
SELECT
    timestamp,
    avgIfMerge(cpu_utilization.1) AS cpu_avg,
    maxIfMerge(cpu_utilization.2) AS cpu_max
FROM metrics_byhour
WHERE uuid = '2ea72a28-aa67-105b-a791-5db4056d985f'
GROUP BY timestamp
ORDER BY timestamp DESC
LIMIT 5

┌───────────timestamp─┬───────────cpu_avg─┬───────────cpu_max─┐
│ 2020-02-26 00:00:00 │ 3.896994948387146 │ 4.204541206359863 │
│ 2020-02-25 23:00:00 │ 4.317551612854004 │ 4.317551612854004 │
│ 2020-02-25 22:00:00 │ 3.134760856628418 │ 3.134760856628418 │
│ 2020-02-25 21:00:00 │  4.41569709777832 │  4.41569709777832 │
│ 2020-02-25 20:00:00 │  4.15779972076416 │  4.15779972076416 │
└─────────────────────┴───────────────────┴───────────────────┘
```

Notice that the average and maximum values are identical except for the most recent bucket.  We have observed that these values continue to change until we get data for the next bucket, at which point they take on incorrect values like the rows below.

We have a number of automated tests that populate the base table with two days worth of random data, and then verify that we pull the expected values out of the materialized views.  These tests all _pass_ when I insert the test data in a single batch.  If I break up the data into 12 separate inserts (with 5 seconds between each), many of the tests fail.  I end up with one or two incorrectly aggregated values in the middle of some sequences.

**How to reproduce**
To reproduce, it is sufficient to create a simple table and materialized view and force it to undergo a large number of merges.  For this test, I created the following table and view:

```
CREATE TABLE main (Timestamp DateTime, Key Int32, Col0 Float64)
ENGINE = MergeTree()
ORDER BY Timestamp

CREATE TABLE main_byhour (Key Int32, Timestamp DateTime, Col0 AggregateFunction(max, Float64))
ENGINE = AggregatingMergeTree()
ORDER BY (Key, Timestamp)

CREATE MATERIALIZED VIEW main_byhour_mv
TO main_byhour (Key Int32, Timestamp DateTime, Col0 AggregateFunction(max, Float64))
AS
  SELECT Key, toStartOfHour(Timestamp) AS Timestamp, maxState(Col0) AS Col0
  FROM MultipartMergeTest.main
  GROUP BY Key, Timestamp
```

To run the test, I insert 3000 rows _one at a time_ into main.  The rows have monotonically increasing timestamps, key = 0, and Col0 set to a random value.  I then compare the contents of the materialized view with the main table (grouped into hourly buckets).  This pretty consistently results in a handful of rows that are aggregated incorrectly.

I ran the test using ClickHouse server 19.17.9.

**Expected behavior**
We expect the contents of the materialized views to match the equivalent queries against the base table.  For max aggregations in particular, there should be no disagreement.

**Comment by den-crane** [comment] 2020-02-26 01:46
>     avgIfMerge(cpu_utilization.1) AS cpu_avg,
>     maxIfMerge(cpu_utilization.2) AS cpu_max

?????????????????? avgIfMerge ? cpu_utilization.1 ???????? 


SELECT
    **toStartOfHour(timestamp) AS timestampXXXXX,**
    avg(cpu_utilization) AS cpu_avg,
    max(cpu_utilization) AS cpu_max
FROM metrics
WHERE uuid = '2ea72a28-aa67-105b-a791-5db4056d985f'
GROUP BY **timestampXXXXX**
ORDER BY **timestampXXXXX** DESC
LIMIT 5

>maxState(**Col0**) AS **Col0**
don't do this if you use Col0 in the same MV or add a table alias `main.Col0`

-----------------------------------------

unable to reproduce

```
drop table if exists main;

drop table if exists main_byhour;

drop table if exists main_byhour_mv;


CREATE TABLE main (Timestamp DateTime, Key Int32, Col0 Float64)
ENGINE = MergeTree()
ORDER BY Timestamp;

CREATE TABLE main_byhour (Key Int32, Timestamp DateTime,
                        Col0m AggregateFunction(max, Float64),
                        Col0a AggregateFunction(avg, Float64),
                        Col0s SimpleAggregateFunction(max, Float64)
                        )
ENGINE = AggregatingMergeTree()
ORDER BY (Key, Timestamp);

CREATE MATERIALIZED VIEW main_byhour_mv
TO main_byhour
AS
SELECT Key, toStartOfHour(Timestamp) AS Timestamp,
       maxState(Col0) AS Col0m,
       avgState(Col0) as Col0a,
       max(Col0) as Col0s
FROM main
GROUP BY Key, Timestamp  ;


insert into main select toDateTime('2020-01-01 00:00:00')+intDiv(number,100), number%101, rand()/12343423767 from numbers(1000000);
insert into main select toDateTime('2020-01-01 00:00:00')+intDiv(number,100), number%101, rand()/12343423767 from numbers(1000000);
insert into main select toDateTime('2020-02-01 00:00:00')+intDiv(number,100), number%101, rand()/12343423767 from numbers(1000000);
insert into main select toDateTime('2020-02-01 00:00:00')+intDiv(number,100), number%101, rand()/12343423767 from numbers(1000000);
insert into main select toDateTime('2020-01-01 00:00:00')+intDiv(number,100), number%101, 0 from numbers(100000);
insert into main select toDateTime('2020-01-01 00:00:00')+intDiv(number,100), number%101, rand()/12343423767 from numbers(10000000);

SELECT
    sum(cpu_max),
    uniqExact(cpu_max),
    sum(cpu_avg),
    uniqExact(cpu_avg)
FROM
(
    SELECT
        toStartOfHour(Timestamp) AS timestamp,
        max(Col0) AS cpu_max,
        avg(Col0) AS cpu_avg
    FROM main
    WHERE Key = 1
    GROUP BY timestamp
    ORDER BY timestamp DESC
)

┌───────sum(cpu_max)─┬─uniqExact(cpu_max)─┬──────sum(cpu_avg)─┬─uniqExact(cpu_avg)─┐
│ 10.783459474335974 │                 31 │ 5.371324389116907 │                 31 │
└────────────────────┴────────────────────┴───────────────────┴────────────────────┘




SELECT
    sum(cpu_maxm),
    uniqExact(cpu_maxm),
    sum(cpu_maxs),
    uniqExact(cpu_maxs),
    sum(cpu_avg),
    uniqExact(cpu_avg)
FROM
(
    SELECT
        Timestamp,
        maxMerge(Col0m) AS cpu_maxm,
        avgMerge(Col0a) AS cpu_avg,
        max(Col0s) AS cpu_maxs
    FROM main_byhour
    WHERE Key = 1
    GROUP BY
        Key,
        Timestamp
    ORDER BY
        Key ASC,
        Timestamp DESC
)

┌──────sum(cpu_maxm)─┬─uniqExact(cpu_maxm)─┬──────sum(cpu_maxs)─┬─uniqExact(cpu_maxs)─┬──────sum(cpu_avg)─┬─uniqExact(cpu_avg)─┐
│ 10.784161970836431 │                  31 │ 10.784161970836431 │                  31 │ 5.365066611717365 │                 31 │
└────────────────────┴─────────────────────┴────────────────────┴─────────────────────┴───────────────────┴────────────────────┘


optimize table main_byhour final;


SELECT
    sum(cpu_maxm),
    uniqExact(cpu_maxm),
    sum(cpu_maxs),
    uniqExact(cpu_maxs),
    sum(cpu_avg),
    uniqExact(cpu_avg)
FROM
(
    SELECT
        Timestamp,
        maxMerge(Col0m) AS cpu_maxm,
        avgMerge(Col0a) AS cpu_avg,
        max(Col0s) AS cpu_maxs
    FROM main_byhour
    WHERE Key = 1
    GROUP BY
        Key,
        Timestamp
    ORDER BY
        Key ASC,
        Timestamp DESC
)

┌──────sum(cpu_maxm)─┬─uniqExact(cpu_maxm)─┬──────sum(cpu_maxs)─┬─uniqExact(cpu_maxs)─┬──────sum(cpu_avg)─┬─uniqExact(cpu_avg)─┐
│ 10.784161970836431 │                  31 │ 10.784161970836431 │                  31 │ 5.365066611717365 │                 31 │
└────────────────────┴─────────────────────┴────────────────────┴─────────────────────┴───────────────────┴────────────────────┘
```

**Comment by pgruderman** [comment] 2020-02-26 12:40
Hi Denis,

Thanks for your reply.  Reproducing this problem is difficult and can't be done with a small number of inserts (as far as I know).  For my repro, I inserted 3000 rows (one at a time over the native protocol).

> ? avgIfMerge ?
> ?cpu_utilization.1 ?
> What is this?
> Why?

In our actual database, we're using NaN to represent missing data points.  When we aggregate into the materialized view, we use `maxIf(column, not isNaN(column))` and `avgIf(column, not isNaN(column))` to remove these.  To keep a lid of the number of columns, we aggregate into tuple colummns.  So cpu_utilization, for example, becomes a tuple of (avg, max).

I don't _think_ these details are relevant to our issue (they aren't needed in the reproduction).

**Comment by mark-angelo** [comment] 2020-02-26 14:19
@den-crane Denis, this issue is blocking a major release and we would be grateful if it can be given priority. Thank you so much!

**Comment by den-crane** [comment] 2020-02-26 16:13
@mark-angelo @pgruderman I have zero relation to CH development. I am just stupid DBA from Canada who are tried to reproduce your issue. 
1. I doubt that this issue exists.
2. I doubt that this issue will be fixed this year if it exists.

**Comment by den-crane** [comment] 2020-02-26 16:21
Storing tuple just making all worse. It still two implicit columns and you just make CH to do
`tupleElement(tuple(x,y)).1` instead of `x`
```

create table X (x Int64, A Tuple(String,String)) Engine=MergeTree order by x;
insert into X values (1, tuple('a','b'));

ls -1 /var/lib/clickhouse/data/default/X/all_1_1_0/
A%2E1.bin                 <------------
A%2E1.mrk2
A%2E2.bin                <------------
A%2E2.mrk2
checksums.txt
columns.txt
count.txt
primary.idx
x.bin
x.mrk2
```

**Comment by den-crane** [comment] 2020-02-26 16:49
Floating points numbers are tricky and the result depends of numbers order. Try to check Int64 / IntDiv

**Comment by den-crane** [comment] 2020-02-28 01:04
Yes, AggregatingMergeTree corrupts data during merge of Tuple(AggregateFunction, AggregateFunction).

All CH versions 18.14.19 -- 20.2

[aggrMTTupleCorruption.zip](https://github.com/ClickHouse/ClickHouse/files/4264779/aggrMTTupleCorruption.zip)

./run.sh

AggregatingMT has 4 columns 
```
  fa            AggregateFunction(avgIf,Float64,UInt8),
  fm            AggregateFunction(maxIf,Float64,UInt8),
  fx     Tuple( AggregateFunction(avgIf,Float64,UInt8),
                AggregateFunction(maxIf,Float64,UInt8)
              )
```
An expectation that `fa` should be equal `fx.1` and `fm=fx.2` 
And they equal before merge and does not after merge. 

This script loads data into AggregatingMT (with stopped merges) and creates many parts (120)
(--max_insert_block_size=500).

Data in aggregated columns without Tuple is consistent with a source table, data in Tuple is not.
For both  AggregateFunction max and avg.

<img width="1077" alt="Screen Shot 2020-02-27 at 8 58 15 PM" src="https://user-images.githubusercontent.com/19737682/75500927-c1411d00-59a4-11ea-9ee7-ebe3cb881632.png">

**Comment by den-crane** [comment] 2020-03-05 17:42
[testx.txt](https://github.com/ClickHouse/ClickHouse/files/4294283/testx.txt)

```
clickhouse-client  -mn <testx.txt
---------------------------------------------------------
DIFF before merge
---------------------------------------------------------
-----------------------sum(avg over all----------------------------------
┌────────sumAvgTable─┬──────sumAvgNotuple─┬────────sumAvgTuple─┐
│ 2.8156029744028492 │ 2.8156029744028483 │ 2.8156029744028483 │
└────────────────────┴────────────────────┴────────────────────┘
-----------------------sum(max over all----------------------------------
┌──────sumMaxTable─┬────sumMaxNotuple─┬──────sumMaxTuple─┐
│ 66.8091354452795 │ 66.8091354452795 │ 66.8091354452795 │
└──────────────────┴──────────────────┴──────────────────┘
---------------------------------------------------------
optimize ....
---------------------------------------------------------
DIFF after merge
┌───────────────────t─┬────────────AvgTuple─┬─────────Avg_noTuple─┬────────────MaxTuple─┬────────Max_noTuple─┬─maxRoundTuple─┬─maxRoundNoTuple─┐
│ 2019-10-08 11:00:00 │ 0.13165837428566718 │ 0.20174498936602595 │  1.3209974714523198 │  3.601055872794574 │             1 │               4 │
│ 2019-10-08 12:00:00 │ 0.07444409159607052 │ 0.09978448900355753 │  0.8736842740753509 │ 2.0004133254012944 │             1 │               2 │
│ 2019-10-08 15:00:00 │ 0.09512271336765157 │   0.267331246360496 │ 0.49272250340636314 │ 10.364540585001619 │             0 │              10 │
│ 2019-10-08 16:00:00 │  0.1558925177925901 │ 0.19424545080840486 │  1.6386859135134022 │  5.410087031529067 │             2 │               5 │
│ 2019-10-08 17:00:00 │ 0.10325748819443843 │ 0.11989062786953672 │  1.0533820748668978 │ 1.9255581528767627 │             1 │               2 │
│ 2019-10-08 20:00:00 │ 0.06252983142367657 │  0.0974346356001857 │ 0.14907547623383302 │ 0.5950759547510195 │             0 │               1 │
│ 2019-10-08 21:00:00 │ 0.06299480780707903 │ 0.18757883438528203 │ 0.40138180664070466 │  7.063365023826849 │             0 │               7 │
│ 2019-10-09 01:00:00 │ 0.05398204324916496 │  0.2061133765036701 │  0.1115879415115554 │  6.749140716276856 │             0 │               7 │
└─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┴────────────────────┴───────────────┴─────────────────┘
---------------------------------------------------------
┌───────────────────t─┬────────────AvgTable─┬──────────AvgNotuple─┬────────────AvgTuple─┬───────────MaxTable─┬─────────MaxNotuple─┬────────────MaxTuple─┐
│ 2019-10-09 01:00:00 │  0.2061133765036701 │  0.2061133765036701 │ 0.05398204324916496 │  6.749140716276856 │  6.749140716276856 │  0.1115879415115554 │
│ 2019-10-08 11:00:00 │ 0.20174498936602597 │ 0.20174498936602595 │ 0.13165837428566718 │  3.601055872794574 │  3.601055872794574 │  1.3209974714523198 │
│ 2019-10-08 20:00:00 │  0.0974346356001857 │  0.0974346356001857 │ 0.06252983142367657 │ 0.5950759547510195 │ 0.5950759547510195 │ 0.14907547623383302 │
│ 2019-10-08 17:00:00 │ 0.11989062786953678 │ 0.11989062786953672 │ 0.10325748819443843 │ 1.9255581528767627 │ 1.9255581528767627 │  1.0533820748668978 │
│ 2019-10-08 16:00:00 │ 0.19424545080840486 │ 0.19424545080840486 │  0.1558925177925901 │  5.410087031529067 │  5.410087031529067 │  1.6386859135134022 │
│ 2019-10-08 21:00:00 │ 0.18757883438528203 │ 0.18757883438528203 │ 0.06299480780707903 │  7.063365023826849 │  7.063365023826849 │ 0.40138180664070466 │
│ 2019-10-08 15:00:00 │ 0.26733124636049593 │   0.267331246360496 │ 0.09512271336765157 │ 10.364540585001619 │ 10.364540585001619 │ 0.49272250340636314 │
│ 2019-10-08 12:00:00 │ 0.09978448900355745 │ 0.09978448900355753 │ 0.07444409159607052 │ 2.0004133254012944 │ 2.0004133254012944 │  0.8736842740753509 │
└─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┴─────────────────────┘
-----------------------sum(avg over all----------------------------------
┌────────sumAvgTable─┬──────sumAvgNotuple─┬──────sumAvgTuple─┐
│ 2.8156029744028492 │ 2.8156029744028483 │ 2.25151403005053 │
└────────────────────┴────────────────────┴──────────────────┘
-----------------------sum(max over all----------------------------------
┌──────sumMaxTable─┬────sumMaxNotuple─┬────────sumMaxTuple─┐
│ 66.8091354452795 │ 66.8091354452795 │ 35.141416244521885 │
└──────────────────┴──────────────────┴────────────────────┘
```

**Comment by den-crane** [comment] 2020-03-05 19:00
```
insert into m values ('2019-10-08 10:10:51','1','1',0) ('2019-10-08 11:10:51','1','1',0);
insert into m values ('2019-10-08 10:10:11','1','1',1) ('2019-10-08 11:10:11','1','1',10);
insert into m values ('2019-10-08 10:10:51','1','1',0) ('2019-10-08 11:10:51','1','1',0);
insert into m values ('2019-10-08 10:10:11','1','1',1) ('2019-10-08 11:10:11','1','1',10);
```

[testx1.txt](https://github.com/ClickHouse/ClickHouse/files/4294611/testx1.txt)
```

clickhouse-client -mn <testx1.txt
---------------------------------------------------------
DIFF before merge
---------------------------------------------------------
-----------------------sum(avg over all----------------------------------
┌─sumAvgTable─┬─sumAvgNotuple─┬─sumAvgTuple─┐
│         5.5 │           5.5 │         5.5 │
└─────────────┴───────────────┴─────────────┘
-----------------------sum(max over all----------------------------------
┌─sumMaxTable─┬─sumMaxNotuple─┬─sumMaxTuple─┐
│          11 │            11 │          11 │
└─────────────┴───────────────┴─────────────┘
---------------------------------------------------------
optimize ....
---------------------------------------------------------
DIFF after merge
┌───────────────────t─┬─AvgTuple─┬─Avg_noTuple─┬─MaxTuple─┬─Max_noTuple─┬─maxRoundTuple─┬─maxRoundNoTuple─┐
│ 2019-10-08 10:00:00 │        0 │         0.5 │        0 │           1 │             0 │               1 │
│ 2019-10-08 11:00:00 │        0 │           5 │        0 │          10 │             0 │              10 │
└─────────────────────┴──────────┴─────────────┴──────────┴─────────────┴───────────────┴─────────────────┘
---------------------------------------------------------
┌───────────────────t─┬─AvgTable─┬─AvgNotuple─┬─AvgTuple─┬─MaxTable─┬─MaxNotuple─┬─MaxTuple─┐
│ 2019-10-08 11:00:00 │        5 │          5 │        0 │       10 │         10 │        0 │
│ 2019-10-08 10:00:00 │      0.5 │        0.5 │        0 │        1 │          1 │        0 │
└─────────────────────┴──────────┴────────────┴──────────┴──────────┴────────────┴──────────┘
-----------------------sum(avg over all----------------------------------
┌─sumAvgTable─┬─sumAvgNotuple─┬─sumAvgTuple─┐
│         5.5 │           5.5 │           0 │
└─────────────┴───────────────┴─────────────┘
-----------------------sum(max over all----------------------------------
┌─sumMaxTable─┬─sumMaxNotuple─┬─sumMaxTuple─┐
│          11 │            11 │           0 │
└─────────────┴───────────────┴─────────────┘

```

**Comment by den-crane** [comment] 2020-03-05 19:26
hmm, it's reproducible on super simple test. Maybe I'm doing smth wrong.

```
drop table if exists byhour;

CREATE TABLE byhour
(
  u      String,
  t      DateTime,
  fa            AggregateFunction(avgIf,Float64,UInt8),
  fm            AggregateFunction(maxIf,Float64,UInt8),
  fx     Tuple( AggregateFunction(avgIf,Float64,UInt8),
                AggregateFunction(maxIf,Float64,UInt8)
              )
)
ENGINE = AggregatingMergeTree ()
ORDER BY (u,t) ;

insert into byhour
SELECT
    u, t,
       avgIfState(f,NOT isNaN (f)) fa,
       maxIfState(f,NOT isNaN (f)) fm,
    (  avgIfState(f,NOT isNaN (f)),
       maxIfState(f,NOT isNaN (f))
    ) AS fx
  from (select '2019-10-08 00:00:00' t, '1' u, 0. f)
  group by u, t;

insert into byhour
SELECT
    u, t,
       avgIfState(f,NOT isNaN (f)) fa,
       maxIfState(f,NOT isNaN (f)) fm,
    (  avgIfState(f,NOT isNaN (f)),
       maxIfState(f,NOT isNaN (f))
    ) AS fx
  from (select '2019-10-08 00:00:00' t, '1' u, 10000000000000. f)
  group by u, t;

OPTIMIZE TABLE byhour FINAL;
SELECT
      t,
      finalizeAggregation(fx.1) AS AvgTuple,
      finalizeAggregation(fa) AS Avg_noTuple,
      finalizeAggregation(fx.2) AS MaxTuple,
      finalizeAggregation(fm) AS Max_noTuple
FROM byhour format PrettyCompactMonoBlock;

┌───────────────────t─┬─AvgTuple─┬───Avg_noTuple─┬─MaxTuple─┬────Max_noTuple─┐
│ 2019-10-08 00:00:00 │        0 │ 5000000000000 │        0 │ 10000000000000 │
└─────────────────────┴──────────┴───────────────┴──────────┴────────────────┘

```

**Comment by alexey-milovidov** [comment] 2020-03-05 19:39
Tuple of AggregateFunction is not an AggregateFunction - it will not aggregate during merge but only select the first value.

**Comment by den-crane** [comment] 2020-03-05 20:30
@alexey-milovidov  so it's not a bug , but expected behavior ? Right?

**Comment by alexey-milovidov** [comment] 2020-03-05 20:39
I did not read all the thread but
if it works as I explained - yes, it is the expected behaviour.

It can be improved.

**Comment by alexey-milovidov** [comment] 2021-08-15 03:26
Yes, there is no point in using Tuples here.

**Closed by alexey-milovidov** 2021-08-15 03:26 UTC
Labels: st-accepted
