### ISSUE TITLE
DB::Exception: Unknown column when expression in ORDER BY but not in SELECT-ed window

### ISSUE THREAD

**Issue by acm15** [ClickHouse/ClickHouse#60057] opened 2024-02-16 10:15 UTC
repro (latest): https://fiddle.clickhouse.com/28d8db53-f686-465d-baaa-7bde0221cd39
```
$ curl https://play.clickhouse.com/?user=explorer --data-binary "WITH x AS (SELECT 'foo' name) SELECT x.name, count() over() AS total_records FROM x ORDER BY length(x.name) ASC"
Code: 47. DB::Exception: Unknown column: length(name), there are only columns name. (UNKNOWN_IDENTIFIER) (version 24.2.1.404 (official build))
```
works if window is ordered: https://fiddle.clickhouse.com/ccdf7617-78ba-4db6-92ba-cd7370e50c0e
```
$ curl https://play.clickhouse.com/?user=explorer --data-binary "WITH x AS (SELECT 'foo' name) SELECT x.name, count() over(ORDER BY length(x.name)) AS total_records FROM x ORDER BY length(x.name) ASC"
foo     1
```

**Comment by den-crane** [comment] 2024-02-22 19:47
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/45535

solved in experimental_analyzer  https://fiddle.clickhouse.com/238c9fb7-482c-41c8-8de5-3d69c6b87d80

**Closed** 2024-02-23 09:46 UTC
Labels: duplicate, st-hold, potential bug
