### ISSUE TITLE
Format Arrow returns empty result set when output_format_arrow_low_cardinality_as_dictionary=1 

### ISSUE THREAD

**Issue by lejtmany** [ClickHouse/ClickHouse#27094] opened 2021-08-02 14:36 UTC
You have to provide the following information whenever possible.

**Describe the bug**

When output_format_arrow_low_cardinality_as_dictionary=1 running a query with `Format Arrow` returns no results.
**Does it reproduce on recent release?**
yes. using docker `yandex/clickhouse-server:21.7.5.29`
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**
```
clickhouse-client --query 'CREATE TABLE test(`colA` LowCardinality(String)) ENGINE = MergeTree ORDER BY colA'
clickhouse-client --query "INSERT INTO test(colA) VALUES ('a'), ('b'), ('c'), ('d')"
clickhouse-client --query "SELECT * FROM test FORMAT Arrow" > not_dict.bin"
clickhouse-client --query "SELECT * FROM test FORMAT Arrow SETTINGS output_format_arrow_low_cardinality_as_dictionary=1"  > dict.bin
```
Code to read arrow files:
```javascript
const arrow = require('apache-arrow');
const fs = require('fs')

let notDict = fs.readFileSync("not_dict.bin")
let notDictTable = arrow.Table.from(notDict)
console.log("Not dict schema: " +  notDictTable.schema);
console.log("Not dict count: " +  notDictTable.count());

let dict = fs.readFileSync("dict.bin")
let dictTable = arrow.Table.from(dict)
console.log("Dict schema: " +  dictTable.schema);
console.log("Dict count: " +  dictTable.count());
```
Output:
```
Not dict schema: Schema<{ 0: colA: Binary }>
Not dict count: 4
Dict schema: Schema<{ 0: colA: Dictionary<Int8, Binary> }>
Dict count: 0
```

* Which ClickHouse server version to use
`yandex/clickhouse-server:21.7.5.29`

* Non-default settings, if any
output_format_arrow_low_cardinality_as_dictionary=1

**Expected behavior**
Expected the arrow file to contain the results of the query

**Comment by Avogar** [comment] 2021-08-04 13:46
The problem is known and will be fixed after https://github.com/ClickHouse/ClickHouse/pull/25902

**Closed** 2021-08-17 11:42 UTC
Labels: bug, comp-formats

**Comment by enjoylife** [comment] 2022-04-22 02:16
This bug still persists.
