### ISSUE TITLE
Support kafka client.id parameter? 

### ISSUE THREAD

**Issue by mdianjun** [ClickHouse/ClickHouse#10723] opened 2020-05-07 09:48 UTC
I'm loading data from kafka to ck, and created this table : 
```
CREATE TABLE xxx (
...
) ENGINE = Kafka
  SETTINGS
    kafka_broker_list = 'xxx:9092',
    kafka_topic_list = 'xxx',
    kafka_group_name = 'xxx',
    kafka_format = 'CSV',
    kafka_num_consumers = 1;
```

I have two questions:

1. kafka client.id

Does clickhouse kafka consumer support `client.id` parameter like this: 

`bin/kafka-console-consumer.sh --bootstrap-server ${host}:9092 --topic ${topic} --group ${groupid} --consumer-property client.id=${clientid}`

2. csv delimiter

I want to set csv delimiter ( like `--format_csv_delimiter`)  to '0x01' in the create table statement，how to set this parameter?  '0x01' is an unprintable character.

**Comment by filimonov** [comment] 2020-05-07 10:27
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/7258
Will add that soon

**Comment by mdianjun** [comment] 2020-05-07 12:52
> 2\. format_csv_delimiter = '\x01'

@filimonov do you mean this: 

```
ENGINE = Kafka
  SETTINGS
    kafka_broker_list = 'xxx:9092',
    kafka_topic_list = 'xxx',
    kafka_group_name = 'xxx',
    kafka_format = 'CSV',
    format_csv_delimiter = '\x01', 
    kafka_num_consumers = 1;
```

got an error:

```
Received exception from server (version 20.2.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Unknown setting format_csv_delimiter for storage Kafka.
```

**Comment by filimonov** [comment] 2020-05-07 19:38
No, right now you can only make that change globally in default profile (users.xml)

**Closed** 2020-05-31 15:37 UTC
Labels: comp-kafka, question
