### ISSUE TITLE
MaterializeMySQL: replication does not work for MySQL 5.6.10

### ISSUE THREAD

**Issue by oleg-smith** [ClickHouse/ClickHouse#24097] opened 2021-05-13 15:26 UTC
**Describe the bug**
`CREATE DATABASE mysql_sync ENGINE = MaterializeMySQL('localhost:3306','db','user','password');`
returns the error for **MySQL 5.6.10**

`Code: 537, e.displayText() = DB::Exception: Illegal MySQL variables, the MaterializeMySQL engine requires default_authentication_plugin='mysql_native_password' (version 20.12.4.5 (official build))`

`MaterializeMySQL` requires `default_authentication_plugin` to be set.

However, for this particular MySQL version there is a bug so that this variable is not exposed:
```
show variables like '%default_authentication_plugin%';
=> 0 rows
```

At the same time, correct auth plugin is actually used for all users:

`select * from mysql.user;`

```
plugin:
mysql_native_password
mysql_native_password
mysql_native_password
mysql_native_password
mysql_native_password
```

**Does it reproduce on recent release?**

**How to reproduce**
* Which ClickHouse server version to use
20.12.4.5

* Queries to run that lead to unexpected result
`CREATE DATABASE mysql_sync ENGINE = MaterializeMySQL('localhost:3306','db','user','password');`

**Expected behavior**
Mysql connection is established despite of absence of `default_authentication_plugin` variable

**Error message and/or stacktrace**
`Code: 537, e.displayText() = DB::Exception: Illegal MySQL variables, the MaterializeMySQL engine requires default_authentication_plugin='mysql_native_password' (version 20.12.4.5 (official build))`

**Proposal**
Checking for this variable can be protected by a feature flag, so users of this versions of MySQL can disable it and be able 
 to configure the connection:
[Problem line](https://github.com/ClickHouse/ClickHouse/blob/51fe9fc7717aa649e2242914ba68eda7e9bf2174/src/Databases/MySQL/MaterializeMySQLSyncThread.cpp#L109)

**Comment by oleg-smith** [comment] 2021-05-13 15:32
@TCeason @zhang2014 could you please share your opinion?

**Comment by TCeason** [comment] 2021-05-13 15:45
> @TCeason @zhang2014 could you please share your opinion?

Not support for MySQL 5.6 Now.

https://github.com/ClickHouse/ClickHouse/pull/14564/files

**Comment by tavplubix** [comment] 2021-05-14 13:40
Duplicate of #14524
See https://github.com/ClickHouse/ClickHouse/issues/14524#issuecomment-762169220

**Closed by tavplubix** 2021-05-14 13:40 UTC
Labels: feature

**Comment by oleg-smith** [comment] 2021-05-15 03:21
Could you clarify why it cannot be supported the way described in the proposal?Sent from Yandex.Mail for mobile: http://m.ya.ru/ymail13.05.2021, 08:45, "TCeason" ***@***.***>:

@TCeason @zhang2014 could you please share your opinion?

Not support for MySQL 5.6 Now.
https://github.com/ClickHouse/ClickHouse/pull/14564/files

**Comment by oleg-smith** [comment] 2021-05-15 03:22
Is there a way to know which versions of MySql are supported?Sent from Yandex.Mail for mobile: http://m.ya.ru/ymail14.05.2021, 06:40, "tavplubix" ***@***.***>:
Duplicate of #14524
See #14524 (comment)

**Comment by oleg-smith** [comment] 2021-05-17 04:26
@TCeason could you clarify why it's not going to be supported? It's an easy fix, isn't it?

**Proposal**
Checking for this variable can be protected by a feature flag, so users of this versions of MySQL can disable it and be able
to configure the connection:
Problem line

**Comment by tavplubix** [comment] 2021-05-17 09:46
> Could you clarify why it cannot be supported the way described in the proposal?

As far as I remember, it didn't work for some reason: #14564
Anyway, MySQL 5.6 had reached "end of life" in Feb 2021, so we are not going to support it.

> Is there a way to know which versions of MySql are supported?

`MaterializeMySQL` should work with MySQL 5.7 (except some minor versions, see https://github.com/ClickHouse/ClickHouse/issues/4006#issuecomment-817861267) and 8.0.
