### ISSUE TITLE
Add information about all tables used in query to system.query_log

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#9099] opened 2020-02-13 10:28 UTC
**Use case**
To determine trivially which tables were used in query without query parsing. 
**Describe the solution you'd like**
Nested structure (database String, table String) in system.query_log

**Comment by alexey-milovidov** [comment] 2020-02-13 11:31
Maybe it can be trivially implemented with hook in getTable method in query context, that will store this data in the query context. Thoughts @tavplubix ?

**Comment by alexey-milovidov** [comment] 2020-02-13 13:01
@tavplubix said that it's better to extract them in AST level.

**Comment by filimonov** [comment] 2020-02-13 19:23
> @tavplubix said that it's better to extract them in AST level.

Engine=Merge, distributed - too?

**Comment by alexey-milovidov** [comment] 2020-04-22 04:05
We decided to extract tables in AST level. It will work for tables that are mentioned in SQL query, not for tables that are actually used.

**Comment by alexey-milovidov** [comment] 2020-04-22 04:45
Duplicate of #9030

**Closed by alexey-milovidov** 2020-04-22 04:45 UTC
Labels: duplicate, feature
