### ISSUE TITLE
Why does an error occur when there are duplicate conditions in the where condition?

### ISSUE THREAD

**Issue by xiaochaoren1** [ClickHouse/ClickHouse#54571] opened 2023-09-13 09:20 UTC
> You have to provide the following information whenever possible.

**Describe what's wrong**
![image](https://github.com/ClickHouse/ClickHouse/assets/42240939/071ecd92-5c78-4369-89f1-bccfb9b45796)
Why does an error occur when there are duplicate conditions in the where condition?

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
version is v23.8.2
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment] 2023-09-13 12:09
Please share as TEXT show create table and a query

**Comment by tavplubix** [comment] 2023-09-14 14:05
Looks like a duplicate of https://github.com/ClickHouse/ClickHouse/issues/54617

**Closed by tavplubix** 2023-09-14 14:05 UTC
Labels: st-need-info, potential bug

**Comment by den-crane** [comment] 2023-09-14 15:20
* https://github.com/ClickHouse/ClickHouse/pull/53492
