### ISSUE TITLE
Deleting using QUALIFY operator deletes all the rows in the table

### ISSUE THREAD

**Issue by italodamato** [ClickHouse/ClickHouse#64596] opened 2024-05-29 16:03 UTC
Deleting using QUALIFY operator deletes all the rows in the table. The following example should delete only one row.
logs: [downloaded-logs-20240529-165631.csv](https://github.com/ClickHouse/ClickHouse/files/15487174/downloaded-logs-20240529-165631.csv)

version: 24.4.1.2088

Steps to reproduce:

```sql
drop table if exists default.test_qualify;
create table default.test_qualify (number Int64) ENGINE = MergeTree ORDER BY (number);
insert into default.test_qualify SELECT * FROM numbers(100);
select count() from default.test_qualify; -- 100
select * from default.test_qualify qualify row_number() over (order by number) = 50; -- 49
delete from default.test_qualify where number in (select number from default.test_qualify qualify row_number() over (order by number) = 50);
select count() from default.test_qualify; -- 0
```

**Comment by italodamato** [comment] 2024-05-29 16:18
It also happens on alter delete/update queries. The query behaves as if the QUALIFY condition wasn't there. I wonder if that's because it's using the legacy analyzer (from the logs).

**Comment by melvynator** [comment] 2024-05-30 00:23
Doesn't seem like it, it seems to reproduce when using the new analyzer too: https://fiddle.clickhouse.com/243a3ed3-5fc5-4052-a476-f57d4a08b61a

**Comment by italodamato** [comment] 2024-05-30 09:00
> Doesn't seem like it, it seems to reproduce when using the new analyzer too: [fiddle.clickhouse.com/243a3ed3-5fc5-4052-a476-f57d4a08b61a](https://fiddle.clickhouse.com/243a3ed3-5fc5-4052-a476-f57d4a08b61a)

does the allow flag force it?

**Comment by nickitat** [comment] 2024-05-31 22:14
```
2024.05.31 23:08:17.094432 [ 64523 ] {8465f036-0aff-4a65-8f6a-2539a5736fc5} <Debug> executeQuery: (from 127.0.0.1:36270) alter table test_qualify UPDATE _row_exists = 0 WHERE number IN (SELECT number FROM default.test_qualify QUALIFY row_number() OVER (ORDER BY number ASC) = 50) (stage: Complete)
2024.05.31 23:08:17.094625 [ 64523 ] {8465f036-0aff-4a65-8f6a-2539a5736fc5} <Debug> MutationsInterpreter(default.test_qualify): Will use old analyzer to prepare mutation
```

and guess what

``` sql
SELECT count()
FROM
(
    SELECT number
    FROM default.test_qualify
    QUALIFY row_number() OVER (ORDER BY number ASC) = 50
)
SETTINGS allow_experimental_analyzer = 1

   ┌─count()─┐
1. │       1 │
   └─────────┘


SELECT count()
FROM
(
    SELECT number
    FROM default.test_qualify
    QUALIFY row_number() OVER (ORDER BY number ASC) = 50
)
SETTINGS allow_experimental_analyzer = 0

   ┌─count()─┐
1. │     100 │
   └─────────┘
```

**Comment by novikd** [comment] 2024-06-03 10:57
It's not a bug but an incomplete implementation.

1. `MutationsInterpreter` currently always uses an old analyzer. We have a separate issue for that: #61563.
2. The `QUALIFY` clause is only supported in the new analyzer. It won't be supported in the old analyzer. We don't modify the previous interpreter anymore (with the exception of crashes and logical errors).

I think we can close this issue as a duplicate of #61563.

**Comment by italodamato** [comment] 2024-06-03 11:14
Thanks for checking. I'd add a note to the docs when things are known to be not fully implemented whenever possible.

**Comment by Algunenano** [comment] 2024-06-03 11:57
> It's not a bug but an incomplete implementation.
> I think we can close this issue as a duplicate of https://github.com/ClickHouse/ClickHouse/issues/61563.

But shouldn't it throw in that case instead of deleting everything? Probably it's an issue with the old interpreter not throwing with `QUALIFY`

**Comment by novikd** [comment] 2024-06-03 12:08
> But shouldn't it throw in that case instead of deleting everything? Probably it's an issue with the old interpreter not throwing with QUALIFY

Yes, that would be a better behavior. The old analyzer just doesn't know about `QUALIFY`.

**Closed** 2024-06-19 09:54 UTC
Labels: bug, unfinished code, analyzer
