### ISSUE TITLE
Table corruption Could not find a column of minimum size in MergeTree, after alter delete

### ISSUE THREAD

**Issue by oleg-savko** [ClickHouse/ClickHouse#10083] opened 2020-04-07 10:21 UTC
**Describe the bug**
After successfully done alter delete mutation table became corrupted

mutation:
`alter table user_behavior_events delete where ts > 1576762967041 and ts < 1576799999503 and length(`headers.key`) = 0;
` 

`select * from user_behavior_events limit 100;`
leads to exception:
`DB::Exception: Could not find a column of minimum size in MergeTree, part /var/lib/clickhouse/data/mx_master/user_behavior_events/201912_0_0_0_229/ (version 19.17.6.36 (official build))`

Table definition:
```
ATTACH TABLE user_behavior_events
(
    `ts` UInt64, 
    `sessionId` String, 
    `registrationId` String, 
    `step` String, 
    `userId` Nullable(String), 
    `url` String, 
    `eventType` Nullable(String), 
    `eventName` Nullable(String), 
    `eventId` Nullable(String), 
    `eventValue` Nullable(String), 
    `deviceOS` String, 
    `deviceOSVersion` String, 
    `browser` String, 
    `browserVersion` String, 
    `formFactor` String, 
    `deviceId` String, 
    `countryCode` Nullable(String), 
    `countryName` Nullable(String), 
    `regionCode` Nullable(String), 
    `regionName` Nullable(String), 
    `city` Nullable(String), 
    `timeZone` Nullable(String), 
    `latitude` Nullable(Float64), 
    `longitude` Nullable(Float64), 
    `ip` String, 
    `headers.key` Array(String), 
    `headers.value` Array(Nullable(String)), 
    `cookies.key` Array(String), 
    `cookies.value` Array(Nullable(String)), 
    `queryParams.key` Array(String), 
    `queryParams.value` Array(Nullable(String))
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}/mx_master.user_behavior_events', '{replica}')
PARTITION BY toYYYYMM(toDateTime(ts / 1000))
ORDER BY (ts, registrationId, sessionId)
SETTINGS index_granularity = 8192
```

columns with `.mrk` and `.mrk2` exists in different parts. 
In clickhouse config `enable_mixed_granularity_parts` is enabled :

```
<merge_tree>
        <max_suspicious_broken_parts>5</max_suspicious_broken_parts>
        <enable_mixed_granularity_parts>1</enable_mixed_granularity_parts>
    </merge_tree>
```

logs: 

```
root@gl-prod-warehouse-sel:~# grep 201912_0_0_0_229 /var/log/clickhouse-server/clickhouse-server.log
2020.04.07 09:16:55.903543 [ 11 ] {} <Trace> mx_master.user_behavior_events: Executing log entry to mutate part 201912_0_0_0 to 201912_0_0_0_229
2020.04.07 09:19:58.101158 [ 11 ] {} <Trace> mx_master.user_behavior_events: Renaming temporary part tmp_mut_201912_0_0_0_229 to 201912_0_0_0_229.
2020.04.07 09:22:03.257359 [ 234 ] {90354f57-9aa1-453f-b74b-63813ea2b2f1} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: Could not find a column of minimum size in MergeTree, part /var/lib/clickhouse/data/mx_master/user_behavior_events/201912_0_0_0_229/ (version 19.17.6.36 (official build)) (from 172.19.0.1:39297) (in query: select toStartOfHour(toDateTime(ts / 1000)) p, count(), min(ts), max(ts), min(toDateTime(ts / 1000)), max(toDateTime(ts / 1000)) from user_behavior_events where length(`headers.key`) > 0   and toDateTime(ts / 1000) between '2019-12-19 12:47:47' and now()   and ts > 1576762595598 group by p order by p limit 10000 FORMAT TabSeparatedWithNamesAndTypes;), Stack trace:
2020.04.07 09:22:03.257658 [ 234 ] {90354f57-9aa1-453f-b74b-63813ea2b2f1} <Error> HTTPHandler: Code: 49, e.displayText() = DB::Exception: Could not find a column of minimum size in MergeTree, part /var/lib/clickhouse/data/mx_master/user_behavior_events/201912_0_0_0_229/, Stack trace:
2020.04.07 09:22:08.983450 [ 234 ] {d73ad518-739a-4a8a-9d3c-a06bbb3edd91} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: Could not find a column of minimum size in MergeTree, part 
```

Alexander Sapin helped me to fix this issue and simple attach/detach table fix the issue and table start work correct:
```

detach table mx_master.user_behavior_events;
attach table mx_master.user_behavior_events;
```

**Comment by alexey-milovidov** [comment] 2020-04-12 14:52
@alesapin Need to check if it's fixed in recent versions.

**Comment by alesapin** [comment] 2020-04-13 13:21
We discussed this problem with @oleg-savko in telegram. And all my assumptions about the root cause of the error were wrong. I have already faced this error when granularity (`.mrk` files extension) in memory differs from actual granularity on disk. But they use `mixed_granularity` for a long time and everything worked as expected. Both `.mrk` and `.mrk2` parts work well. I have no idea what can go wrong after mutation.

**Comment by alesapin** [comment] 2020-07-27 13:21
I think we can close it. If someone encounters the error with more fresh versions (starting from 20.3) just reopen this issue.

**Comment by jackpgao** [comment] 2020-07-31 08:35
```sql
SELECT version()

┌─version()───┐
│ 20.3.12.112 │
└─────────────┘

2020.07.31 16:29:15.446095 [ 19442 ] {4f3b7ca1-9eb0-4b08-a7b4-e0c7c7f98ae6} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: Could not find a column of minimum size in MergeTree, part /data1/clickhouse/data/xxx/xxx_msg/20190228_700983_713697_27_3953449/ (version 20.3.12.112 (official build)) (from :39812) (in query: select 1 from xxx where date = '2019-02-28' limit 1;), Stack trace (when copying this message, always include the lines below):


0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10519be0 in ?
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f5072d in ?
2. ? @ 0xd89ef46 in ?
3. DB::injectRequiredColumns(DB::MergeTreeData const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) @ 0xda0babb in ?
4. DB::getReadTaskColumns(DB::MergeTreeData const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::PrewhereInfo> const&, bool) @ 0xda0c7dc in ?
5. DB::MergeTreeReadPool::fillPerPartInfo(std::__1::vector<DB::RangesInDataPart, std::__1::allocator<DB::RangesInDataPart> >&, bool) @ 0xda00fd4 in ?
6. DB::MergeTreeReadPool::MergeTreeReadPool(unsigned long, unsigned long, unsigned long, std::__1::vector<DB::RangesInDataPart, std::__1::allocator<DB::RangesInDataPart> >, DB::MergeTreeData const&, std::__1::shared_ptr<DB::PrewhereInfo> const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeReadPool::BackoffSettings const&, unsigned long, bool) @ 0xda03cd3 in ?
7. DB::MergeTreeDataSelectExecutor::spreadMarkRangesAmongStreams(std::__1::vector<DB::RangesInDataPart, std::__1::allocator<DB::RangesInDataPart> >&&, unsigned long, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, unsigned long, bool, DB::SelectQueryInfo const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::Settings const&, DB::MergeTreeReaderSettings const&) const @ 0xd997270 in ?
8. DB::MergeTreeDataSelectExecutor::readFromParts(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, unsigned long, unsigned int, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, long> > > const*) const @ 0xd99beb1 in ?
9. DB::MergeTreeDataSelectExecutor::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, unsigned long, unsigned int, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, long> > > const*) const @ 0xd99e673 in ?
10. DB::StorageMergeTree::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xd6ff265 in ?
11. void DB::InterpreterSelectQuery::executeFetchColumns<DB::QueryPipeline>(DB::QueryProcessingStage::Enum, DB::QueryPipeline&, std::__1::shared_ptr<DB::PrewhereInfo> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::QueryPipeline&) @ 0xd15ce70 in ?
12. void DB::InterpreterSelectQuery::executeImpl<DB::QueryPipeline>(DB::QueryPipeline&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, DB::QueryPipeline&) @ 0xd160647 in ?
13. DB::InterpreterSelectQuery::executeWithProcessors() @ 0xd122975 in ?
14. DB::InterpreterSelectWithUnionQuery::executeWithProcessors() @ 0xd3276b8 in ?
15. ? @ 0xd539eba in ?
16. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) @ 0xd53a991 in ?
17. DB::TCPHandler::runImpl() @ 0x90327b9 in ?
18. DB::TCPHandler::run() @ 0x90337a0 in ?
19. Poco::Net::TCPServerConnection::start() @ 0xe390dfb in ?
20. Poco::Net::TCPServerDispatcher::run() @ 0xe39127d in ?
21. Poco::PooledThread::run() @ 0x105a7d47 in ?
22. Poco::ThreadImpl::runnableEntry(void*) @ 0x105a3b4c in ?
23. ? @ 0x105a54ed in ?
24. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
25. __clone @ 0xf773d in /usr/lib64/libc-2.17.so

```

**Comment by alesapin** [comment] 2020-09-18 07:49
> ```sql
> SELECT version()
> 
> ┌─version()───┐
> │ 20.3.12.112 │
> └─────────────┘
> 
> 2020.07.31 16:29:15.446095 [ 19442 ] {4f3b7ca1-9eb0-4b08-a7b4-e0c7c7f98ae6} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: Could not find a column of minimum size in MergeTree, part /data1/clickhouse/data/xxx/xxx_msg/20190228_700983_713697_27_3953449/ (version 20.3.12.112 (official build)) (from :39812) (in query: select 1 from xxx where date = '2019-02-28' limit 1;), Stack trace (when copying this message, always include the lines below):
> 
> 
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10519be0 in ?
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f5072d in ?
> 2. ? @ 0xd89ef46 in ?
> 3. DB::injectRequiredColumns(DB::MergeTreeData const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) @ 0xda0babb in ?
> 4. DB::getReadTaskColumns(DB::MergeTreeData const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::PrewhereInfo> const&, bool) @ 0xda0c7dc in ?
> 5. DB::MergeTreeReadPool::fillPerPartInfo(std::__1::vector<DB::RangesInDataPart, std::__1::allocator<DB::RangesInDataPart> >&, bool) @ 0xda00fd4 in ?
> 6. DB::MergeTreeReadPool::MergeTreeReadPool(unsigned long, unsigned long, unsigned long, std::__1::vector<DB::RangesInDataPart, std::__1::allocator<DB::RangesInDataPart> >, DB::MergeTreeData const&, std::__1::shared_ptr<DB::PrewhereInfo> const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeReadPool::BackoffSettings const&, unsigned long, bool) @ 0xda03cd3 in ?
> 7. DB::MergeTreeDataSelectExecutor::spreadMarkRangesAmongStreams(std::__1::vector<DB::RangesInDataPart, std::__1::allocator<DB::RangesInDataPart> >&&, unsigned long, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, unsigned long, bool, DB::SelectQueryInfo const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::Settings const&, DB::MergeTreeReaderSettings const&) const @ 0xd997270 in ?
> 8. DB::MergeTreeDataSelectExecutor::readFromParts(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, unsigned long, unsigned int, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, long> > > const*) const @ 0xd99beb1 in ?
> 9. DB::MergeTreeDataSelectExecutor::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, unsigned long, unsigned int, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, long> > > const*) const @ 0xd99e673 in ?
> 10. DB::StorageMergeTree::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int) @ 0xd6ff265 in ?
> 11. void DB::InterpreterSelectQuery::executeFetchColumns<DB::QueryPipeline>(DB::QueryProcessingStage::Enum, DB::QueryPipeline&, std::__1::shared_ptr<DB::PrewhereInfo> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::QueryPipeline&) @ 0xd15ce70 in ?
> 12. void DB::InterpreterSelectQuery::executeImpl<DB::QueryPipeline>(DB::QueryPipeline&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, DB::QueryPipeline&) @ 0xd160647 in ?
> 13. DB::InterpreterSelectQuery::executeWithProcessors() @ 0xd122975 in ?
> 14. DB::InterpreterSelectWithUnionQuery::executeWithProcessors() @ 0xd3276b8 in ?
> 15. ? @ 0xd539eba in ?
> 16. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) @ 0xd53a991 in ?
> 17. DB::TCPHandler::runImpl() @ 0x90327b9 in ?
> 18. DB::TCPHandler::run() @ 0x90337a0 in ?
> 19. Poco::Net::TCPServerConnection::start() @ 0xe390dfb in ?
> 20. Poco::Net::TCPServerDispatcher::run() @ 0xe39127d in ?
> 21. Poco::PooledThread::run() @ 0x105a7d47 in ?
> 22. Poco::ThreadImpl::runnableEntry(void*) @ 0x105a3b4c in ?
> 23. ? @ 0x105a54ed in ?
> 24. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
> 25. __clone @ 0xf773d in /usr/lib64/libc-2.17.so
> ```

Any reproduction steps?

**Comment by alexey-milovidov** [comment] 2020-09-18 11:06
If you are using non-Replicated MergeTree, the error can be caused by data corruption in filesystem.

Check the contents of `/data1/clickhouse/data/xxx/xxx_msg/20190228_700983_713697_27_3953449/`, also check the server `uptime` and look for any suspicious messages in `dmesg` and `/var/log/kern.log`.

If you will use ReplicatedMergeTree, data will repair from replicas automatically.

**Closed** 2020-09-20 21:20 UTC
Labels: bug, comp-mutations, st-need-repro, st-unverified
