### ISSUE TITLE
MaterializeMySQL do not support  datatype  enum

### ISSUE THREAD

**Issue by renyb** [ClickHouse/ClickHouse#24238] opened 2021-05-18 09:22 UTC
Code: 50. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Unknown data type family: enum. Maybe you meant: ['Enum','Enum8']: While executing dump MySQL archer.trace_record table data..

MySQl:
 CREATE TABLE `demo_record` (  \
  `id` bigint(20)  NOT NULL , \
  `trace_id` varchar(48) NOT NULL , \
  `request_method` Enum('hello', 'world' ) NOT NULL, \
  PRIMARY KEY (`id`) \
)  ENGINE = engine;

clickhouse 执行:
CREATE DATABASE ch_demo  ENGINE = MaterializeMySQL(':3306', 'db', 'user', 'pwd');

**Comment by tavplubix** [comment] 2021-05-18 11:08
Duplicate of #18310

**Closed by tavplubix** 2021-05-18 11:08 UTC
Labels: comp-mysql, duplicate

**Comment by TCeason** [comment] 2021-06-15 09:56
I will support it.
