### ISSUE TITLE
TTL doesn't drop old parts with Custom Partitioning Key

### ISSUE THREAD

**Issue by mobydi** [ClickHouse/ClickHouse#7435] opened 2019-10-22 15:37 UTC
**Describe the bug or unexpected behaviour**
TTL does NOT drop old parts with Custom Partitioning Key

**How to reproduce**
* Which ClickHouse server version to use
```19.14.6 revision 54425```
* Which interface to use, if matters
```clickhouse-client```

* Non-default settings, if any
default setting 

* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE visits
(
    `ts` DateTime, 
    `mac` String
)
ENGINE = ReplacingMergeTree(ts)
PARTITION BY formatDateTime(ts, '%Y%m%d%H')
ORDER BY mac
TTL ts + toIntervalDay(32)
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
```
INSERT INTO test.visits(ts, mac) VALUES('2019-09-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-10-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-11-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-12-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-08-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-09-12 22:00:00', 'B');
INSERT INTO test.visits(ts, mac) VALUES('2019-12-12 22:00:00', 'B');
```

* Queries to run that lead to unexpected result
```
SELECT 
    partition, 
    name, 
    active
FROM system.parts
WHERE (table = 'visits') AND (database = 'test')
ORDER BY partition ASC

┌─partition──┬─name───────────────────────────────────┬─active─┐
│ 2019081222 │ eae76ed737ba99cdf46f1a8ac4bec0c6_5_5_0 │      1 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_1_0 │      0 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_1_1 │      1 │
│ 2019101222 │ 4fd947f7fa76dae62ad1f577cf7288eb_2_2_0 │      1 │
│ 2019111222 │ 772fa7daaf898503df5471e344203fc7_3_3_0 │      1 │
│ 2019121222 │ 3ab6b6764da08f00c4f6f6166b60ba94_4_4_0 │      1 │
└────────────┴────────────────────────────────────────┴────────┘
```

```
OPTIMIZE TABLE test.visits DEDUPLICATE;
OPTIMIZE TABLE test.visits FINAL;
```
```
SELECT 
    partition, 
    name, 
    active
FROM system.parts
WHERE (table = 'visits') AND (database = 'test')
ORDER BY partition ASC

┌─partition──┬─name───────────────────────────────────┬─active─┐
│ 2019081222 │ eae76ed737ba99cdf46f1a8ac4bec0c6_5_5_0 │      0 │
│ 2019081222 │ eae76ed737ba99cdf46f1a8ac4bec0c6_5_5_1 │      1 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_1_0 │      0 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_1_1 │      0 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_6_2 │      1 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_6_6_0 │      0 │
│ 2019101222 │ 4fd947f7fa76dae62ad1f577cf7288eb_2_2_0 │      0 │
│ 2019101222 │ 4fd947f7fa76dae62ad1f577cf7288eb_2_2_1 │      1 │
│ 2019111222 │ 772fa7daaf898503df5471e344203fc7_3_3_0 │      0 │
│ 2019111222 │ 772fa7daaf898503df5471e344203fc7_3_3_1 │      1 │
│ 2019121222 │ 3ab6b6764da08f00c4f6f6166b60ba94_4_4_0 │      0 │
│ 2019121222 │ 3ab6b6764da08f00c4f6f6166b60ba94_4_7_1 │      1 │
│ 2019121222 │ 3ab6b6764da08f00c4f6f6166b60ba94_7_7_0 │      0 │
└────────────┴────────────────────────────────────────┴────────┘
```

**Expected behavior**
I expected that old parts should be deleted 

**Error message and/or stacktrace**

**Additional context**

The same with Merge tree 
```
CREATE TABLE visits
(
    ts DateTime,
    mac String
)
ENGINE = MergeTree()
PARTITION BY formatDateTime(ts, '%Y%m%d%H') 
ORDER BY mac
TTL ts + toIntervalDay(32);


INSERT INTO test.visits(ts, mac) VALUES('2019-09-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-10-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-11-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-12-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-08-12 22:00:00', 'A');
INSERT INTO test.visits(ts, mac) VALUES('2019-09-12 22:00:00', 'B');
INSERT INTO test.visits(ts, mac) VALUES('2019-12-12 22:00:00', 'B');
```

```
SELECT 
    partition, 
    name, 
    active
FROM system.parts
WHERE (table = 'visits') AND (database = 'test')
ORDER BY partition ASC

┌─partition──┬─name───────────────────────────────────┬─active─┐
│ 2019081222 │ eae76ed737ba99cdf46f1a8ac4bec0c6_5_5_0 │      1 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_1_0 │      0 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_1_1 │      1 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_6_6_0 │      1 │
│ 2019101222 │ 4fd947f7fa76dae62ad1f577cf7288eb_2_2_0 │      1 │
│ 2019111222 │ 772fa7daaf898503df5471e344203fc7_3_3_0 │      1 │
│ 2019121222 │ 3ab6b6764da08f00c4f6f6166b60ba94_4_4_0 │      1 │
│ 2019121222 │ 3ab6b6764da08f00c4f6f6166b60ba94_7_7_0 │      1 │
└────────────┴────────────────────────────────────────┴────────┘

OPTIMIZE TABLE test.visits DEDUPLICATE;
OPTIMIZE TABLE test.visits FINAL;

SELECT 
    partition, 
    name, 
    active
FROM system.parts
WHERE (table = 'visits') AND (database = 'test')
ORDER BY partition ASC

┌─partition──┬─name───────────────────────────────────┬─active─┐
│ 2019081222 │ eae76ed737ba99cdf46f1a8ac4bec0c6_5_5_0 │      0 │
│ 2019081222 │ eae76ed737ba99cdf46f1a8ac4bec0c6_5_5_1 │      1 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_1_0 │      0 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_1_1 │      0 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_6_2 │      0 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_1_6_3 │      1 │
│ 2019091222 │ 50166ca44dd6cd5f15db48d60861d71d_6_6_0 │      0 │
│ 2019101222 │ 4fd947f7fa76dae62ad1f577cf7288eb_2_2_0 │      0 │
│ 2019101222 │ 4fd947f7fa76dae62ad1f577cf7288eb_2_2_1 │      1 │
│ 2019111222 │ 772fa7daaf898503df5471e344203fc7_3_3_0 │      0 │
│ 2019111222 │ 772fa7daaf898503df5471e344203fc7_3_3_1 │      1 │
│ 2019121222 │ 3ab6b6764da08f00c4f6f6166b60ba94_4_4_0 │      0 │
│ 2019121222 │ 3ab6b6764da08f00c4f6f6166b60ba94_4_7_1 │      1 │
│ 2019121222 │ 3ab6b6764da08f00c4f6f6166b60ba94_7_7_0 │      0 │
└────────────┴────────────────────────────────────────┴────────┘


```

**Comment by filimonov** [comment] 2019-10-23 22:05
Related https://github.com/ClickHouse/ClickHouse/issues/6462

**Comment by alexey-milovidov** [comment] 2019-12-15 21:34
https://github.com/ClickHouse/ClickHouse/issues/8167

**Comment by isp1356** [comment] 2020-02-24 10:43
I have a similar issue here on version `20.1.4.14`, using AggregatingMergeTree and TTL (1 day):
```sql
CREATE TABLE testtable
(
    `__slot` DateTime, 
    `poller` LowCardinality(String)
)
ENGINE = AggregatingMergeTree()
PARTITION BY toYYYYMMDD(toStartOfInterval(__slot, toIntervalDay(1)))
PRIMARY KEY (__slot, intHash32(__slot))
ORDER BY (__slot, intHash32(__slot), poller)
SAMPLE BY intHash32(__slot)
TTL __slot + toIntervalSecond(86400)
SETTINGS index_granularity = 8192
```

The old data is removed but old parts remain:

```sql
SELECT name, partition, active
FROM system.parts
WHERE table = 'testtable'
```

```
┌─name────────────────────┬─partition─┬─active─┐
│ 20200219_1_441_134      │ 20200219  │      1 │
│ 20200220_442_1881_1131  │ 20200220  │      1 │
│ 20200221_1882_3321_1132 │ 20200221  │      1 │
│ 20200222_3322_4760_1135 │ 20200222  │      1 │
│ 20200222_4761_4761_0    │ 20200222  │      1 │
│ 20200223_4762_6200_1122 │ 20200223  │      1 │
│ 20200223_6201_6201_0    │ 20200223  │      1 │
│ 20200224_6202_6822_313  │ 20200224  │      0 │
│ 20200224_6202_6823_314  │ 20200224  │      0 │
│ 20200224_6202_6824_315  │ 20200224  │      0 │
│ 20200224_6202_6825_316  │ 20200224  │      0 │
│ 20200224_6202_6826_317  │ 20200224  │      0 │
│ 20200224_6202_6827_318  │ 20200224  │      0 │
│ 20200224_6202_6828_319  │ 20200224  │      0 │
│ 20200224_6202_6829_320  │ 20200224  │      0 │
│ 20200224_6202_6830_321  │ 20200224  │      1 │
│ 20200224_6823_6823_0    │ 20200224  │      0 │
│ 20200224_6824_6824_0    │ 20200224  │      0 │
│ 20200224_6825_6825_0    │ 20200224  │      0 │
│ 20200224_6826_6826_0    │ 20200224  │      0 │
│ 20200224_6827_6827_0    │ 20200224  │      0 │
│ 20200224_6828_6828_0    │ 20200224  │      0 │
│ 20200224_6829_6829_0    │ 20200224  │      0 │
│ 20200224_6830_6830_0    │ 20200224  │      0 │
│ 20200224_6831_6831_0    │ 20200224  │      1 │
│ 20200224_6832_6832_0    │ 20200224  │      1 │
│ 20200224_6833_6833_0    │ 20200224  │      1 │
│ 20200224_6834_6834_0    │ 20200224  │      1 │
└─────────────────────────┴───────────┴────────┘
```

```sql
SELECT count()
FROM testtable
WHERE __slot < (now() - ((3600 * 24) * 2))
```
```
┌─count()─┐
│       0 │
└─────────┘
```

**Comment by CurtizJ** [comment] 2020-07-13 09:27
The data is deleted, but only empty parts are remaining. Duplicate of #5491.

**Closed by CurtizJ** 2020-07-13 09:27 UTC
Labels: bug, comp-ttl, duplicate
