### ISSUE TITLE
MySQL database engine type is not available on arm64

### ISSUE THREAD

**Issue by gpmcadam** [ClickHouse/ClickHouse#21415] opened 2021-03-03 11:27 UTC
MySQL database engine type is not available on arm64.

When using a schema such as:

```sql
CREATE DATABASE IF NOT EXISTS foo ENGINE = MySQL(...);
```

The following error is shown:

```
DB::Exception: Unknown database engine: ENGINE = MySQL('...
```

This doesn't happen on i386/amd64 etc. just on Apple M1 Silicon arm64.

Is there a reason this engine is not available on that architecture?

**Comment by filimonov** [comment] 2021-03-03 13:13
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/21191

**Closed by filimonov** 2021-03-03 13:13 UTC
Labels: build

**Comment by gpmcadam** [comment] 2021-03-03 13:16
To clarify, this is not building on macOS but on arm64 in Docker/Linux, so I don’t think its a duplicate as described

**Comment by den-crane** [comment] 2021-03-03 16:11
@gpmcadam So you cross-compiled on arm64 in Docker/Linux for arm64 macOS as the target?

**Comment by gpmcadam** [comment] 2021-03-03 16:17
I'm running macOS as the host, but the target is Ubuntu ARM64.

**Comment by den-crane** [comment] 2021-03-03 16:33
Ah, OK. It's not related to MacOS at all but CPU is arm64 (Apple M1).
