### ISSUE TITLE
Request to add RIPEMD-160 hashing algorithm

### ISSUE THREAD

**Issue by araa47** [ClickHouse/ClickHouse#67471] opened 2024-07-30 15:55 UTC
**Use case**

Working with Bitcoin data in ClickHouse currently requires setting up external cloud functions to parse RIPEMD-160 hashes, which is inefficient and adds unnecessary complexity. Adding native support for the RIPEMD-160 hashing algorithm would streamline Bitcoin data analysis workflows directly within ClickHouse.

**Describe the solution you'd like**

Implement native support for the RIPEMD-160 hashing algorithm in ClickHouse. This would involve adding a new function, potentially named ripemd160(), that takes a string input and returns the corresponding RIPEMD-160 hash.

**Describe alternatives you've considered**
- Using external cloud functions to compute RIPEMD-160 hashes.
- Pre-processing data to include RIPEMD-160 hashes before ingesting into ClickHouse.
- Implementing a custom UDF (User Defined Function) for RIPEMD-160 hashing.

**Additional context**

RIPEMD-160 is a critical component in Bitcoin's address generation process and is widely used in blockchain data analysis. Native support in ClickHouse would significantly improve performance and ease of use for blockchain data analytics.
For implementation details, the RIPEMD-160 algorithm is well-documented and can be referenced from sources such as the Bitcoin Wiki. https://en.bitcoin.it/wiki/RIPEMD-160

**Comment by rschu1ze** [comment] 2024-09-26 10:20
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/68176

**Closed by rschu1ze** 2024-09-26 10:20 UTC
Labels: feature
