### ISSUE TITLE
LDAP: changing groups for user makes Clickhouse fail to log in

### ISSUE THREAD

**Issue by Blackmorse** [ClickHouse/ClickHouse#22221] opened 2021-03-28 12:02 UTC
**Describe the bug**
Clickhouse fails to log users after changing groups at LDAP for one user

**Does it reproduce on recent release?**
I've checked It on 21.2.5.5 and 21.3.4.25

**How to reproduce**
E.g. there is LDAP user *user_1* and there are two LDAP groups *role_1* and *role_2*, which are mapped to the Clickhouse roles with the same names. 
At the beginning *user_1* is only at *role_1* group
1. Log *user_1* in by clickhouse-client and check grants:
```
SHOW GRANTS

┌─GRANTS─────────────────────────────────────────┐
│ GRANT role1 TO user_1 │
└────────────────────────────────────────────────┘
```
2. Exclude *user_1* from *role_1* and assign him to the *role_2* group
3.  Try to log him in by clickhouse-client again. Login process  hangs forever. Also other users can't log in too.

**Expected behavior**
User will have updated grants after the re-login

**Error message and/or stacktrace**
I found no logs for that :(

**Additional context**
Clickhouse on CentOS, freeipa as a LDAP

**Comment by traceon** [comment] 2021-03-29 17:49
@Blackmorse I followed your instructions but was unable to reproduce. Can you clarify a few things:
- do you disconnect the first session, when you try to authenticate the second time (with reassigned roles at LDAP side)?
- does `role2` exist in ClickHouse?
- is it reproduced when roles are "empty", i.e., freshly created without anything granted to them?
- can you get the log of LDAP server with the corresponding requests?
- can you send me the `strace` output of ClickHouse captured while at that hanged state? (worth trying with a debug build, I guess)

**Comment by Blackmorse** [comment] 2021-04-01 16:22
@traceon  
 > do you disconnect the first session, when you try to authenticate the second time (with reassigned roles at LDAP side)?
I do the both - result is the same

 > does role2 exist in ClickHouse?
Yes, it does. After rebooting Clickhouse user can log in and correctly gain role_2

 > is it reproduced when roles are "empty", i.e., freshly created without anything granted to them?
Here I've tried to re-create "empty" roles, and again the same

> can you get the log of LDAP server with the corresponding requests?
I've spent some time inspecting LDAP logs... I've found no errors and no strange entries there. 
BTW, it seems important for me, that at the second attempt to log in (which is fail one) ldap doesn't log any request from Clickhouse. Like something stucks at the CH side.
I have no expertise at LDAP, may be you can point me right place to investigate LDAP logs?

 > can you send me the strace output of ClickHouse captured while at that hanged state? (worth trying with a debug build, I guess)
Sorry, I have no debug build :(


Also, when I'm trying to log in first time, I get a bunch of warnings at clickhouse log:
`2021.04.01 16:04:31.056960 [ 12223 ] {} <Warning> Access(ldap): Unable to grant mapped role '<here role name>' to user 'my_user': role not found`
There are about 10 records of this types - because user have a lot of group at the LDAP(and they are not matched by clickhouse mapping), and there is one warning per each role. There is no error about 'role_1' or 'role_2', and user correctly grants one of them.

Second, third and consecutive log in attempts DOES NOT produce that warnings. It means, that CH has cached that roles, right?

**Comment by traceon** [comment] 2021-04-01 18:38
@Blackmorse what does your role mapping config look like?

**Comment by Blackmorse** [comment] 2021-04-02 05:52
@traceon 
```
<role_mapping>
        <base_dn>cn=groups,cn=accounts,dc=company,dc=com</base_dn>
        <scope>subtree</scope>
        <search_filter>(&amp;(member=uid={user_name},cn=users,cn=accounts,dc=company,dc=com))</search_filter>
        <attribute>cn</attribute>
</role_mapping>
```

**Comment by Blackmorse** [comment] 2021-04-07 13:01
@traceon, any updates?

**Comment by traceon** [comment] 2021-04-20 10:16
@Blackmorse I will come back to this shortly.

**Comment by Blackmorse** [comment] 2021-05-17 07:55
@traceon , How does it go?

**Comment by traceon** [comment] 2021-05-17 08:28
Hi @Blackmorse , sorry for the delay. Last time I looked at this, I still wasn't able to reproduce. I will check again.

**Comment by traceon** [comment] 2021-05-23 20:33
> user have a lot of group at the LDAP (and they are not matched by clickhouse mapping)

@Blackmorse they were extracted, all of them were matched and extracted (since you didn't specify any _prefix_), but their local role counterparts were not found. It turned out this was an important detail.

The issue will be solved once #24431 is merged. Thanks for the reporting and sorry for the delay

**Comment by Blackmorse** [comment] 2021-05-24 06:32
@traceon , Thanks for the answer! 
Waiting #24431 to merged...

**Closed** 2021-05-31 19:14 UTC
Labels: bug, comp-rbac, st-need-info, st-need-repro

**Comment by bobelev** [comment] 2023-02-02 14:15
Looks like the same issue #41380 again
