### ISSUE TITLE
Test test_keeper_reconfig_replace_leader/test.py::test_reconfig_replace_leader is flaky

### ISSUE THREAD

**Issue by vitlibar** [ClickHouse/ClickHouse#56850] opened 2023-11-16 10:31 UTC
See [failures](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0ZXN0X25hbWUsIGNoZWNrX3N0YXJ0X3RpbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIHJlcG9ydF91cmwKZnJvbSBjaGVja3Mgd2hlcmUgJzIwMjMtMTEtMDknIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHRlc3RfbmFtZSBsaWtlICcldGVzdF9rZWVwZXJfcmVjb25maWdfcmVwbGFjZV9sZWFkZXIvdGVzdC5weTo6dGVzdF9yZWNvbmZpZ19yZXBsYWNlX2xlYWRlciUnIGFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyPTAgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScp)

```
=================================== FAILURES ===================================
_________________________ test_reconfig_replace_leader _________________________
[gw4] linux -- Python 3.10.12 /usr/bin/python3

started_cluster = <helpers.cluster.ClickHouseCluster object at 0x7fc0656f06a0>

    def test_reconfig_replace_leader(started_cluster):
        """
        Remove leader from a cluster of 3 and add a new node via two commands.
        """
        global zk1, zk2, zk3, zk4
        zk1 = create_client(node1)
        config = ku.get_config_str(zk1)
    
        assert len(config.split("\n")) == 3
        assert "node1" in config
        assert "node2" in config
        assert "node3" in config
        assert "node4" not in config
    
        for i in range(100):
            zk1.create(f"/test_four_{i}", "somedata")
    
        zk2 = create_client(node2)
        zk2.sync("/test_four_0")
        ku.wait_configs_equal(config, zk2)
    
        zk3 = create_client(node3)
        zk3.sync("/test_four_0")
        ku.wait_configs_equal(config, zk3)
    
        for i in range(100):
            assert zk2.exists(f"/test_four_{i}")
            assert zk3.exists(f"/test_four_{i}")
    
        assert ku.is_leader(cluster, node1)
        config = zk2.reconfig(joining=None, leaving="1", new_members=None)
    
        print("After removing 1 (leader)", config)
        assert len(config.split("\n")) == 2
        assert "node1" not in config
        assert "node2" in config
        assert "node3" in config
        assert "node4" not in config
    
        # additional 20s wait before removing leader
>       ku.wait_configs_equal(config, zk2, timeout=50)

test_keeper_reconfig_replace_leader/test.py:87: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
helpers/keeper_utils.py:285: in wait_configs_equal
    get_config_str(right_zk).split("\n")
helpers/keeper_utils.py:275: in get_config_str
    return zk.get("/keeper/config")
helpers/keeper_utils.py:116: in get
    return self.execute_query(f"get {path}", timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <helpers.keeper_utils.KeeperClient object at 0x7fc0656f3430>
query = 'get /keeper/config', timeout = 60.0

    def execute_query(self, query: str, timeout: float = 60.0) -> str:
        output = io.BytesIO()
    
        self.proc.stdin.write(query.encode() + b"\n")
        self.proc.stdin.flush()
    
        events = self.poller.poll(timeout)
        if not events:
            raise TimeoutError(f"Keeper client returned no output")
    
        for fd_num, event in events:
            if event & (select.EPOLLIN | select.EPOLLPRI):
                file = self._fd_nums[fd_num]
    
                if file == self.proc.stdout:
                    while True:
                        chunk = file.readline()
                        if chunk.endswith(self.SEPARATOR):
                            break
    
                        output.write(chunk)
    
                elif file == self.proc.stderr:
                    assert self.proc.stdout.readline() == self.SEPARATOR
>                   raise KeeperException(self.proc.stderr.readline().strip().decode())
E                   helpers.keeper_utils.KeeperException: Coordination error: Connection loss, path /keeper/config

helpers/keeper_utils.py:98: KeeperException
```

**Comment by tavplubix** [comment] 2023-11-16 17:57
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/56177

**Closed by tavplubix** 2023-11-16 17:57 UTC
Labels: testing
