### ISSUE TITLE
LZMA_STREAM_DECODER_FAILED during INSERT from URL table engine

### ISSUE THREAD

**Issue by ArctypeZach** [ClickHouse/ClickHouse#49205] opened 2023-04-26 15:27 UTC
**Describe what's wrong**

Running `INSERT INTO ... SELECT FROM <url table>` appears to intermittently fail on large URL-engine tables (such as the `github_events_url` table described [here](https://ghe.clickhouse.tech/#download-the-dataset-directly-into-clickhouse)) throwing the following exception:

```
Code: 554. DB::Exception: Received from <hostname>. 
DB::Exception: lzma_stream_decoder failed: error code: error codeL 9; lzma version: 5.3.1alpha: 
While executing Native: While executing URL. (LZMA_STREAM_DECODER_FAILED)
```

**Does it reproduce on recent release?**

Reproduceable (at least) on releases `22.11.1` through `23.3.1`

**How to reproduce**

Reproduceable following the steps [here](https://ghe.clickhouse.tech/#download-the-dataset-directly-into-clickhouse)

**Comment by alexey-milovidov** [comment] 2023-04-27 13:48
Maybe duplicate of https://github.com/ClickHouse/ClickHouse/issues/49278

**Comment by ArctypeZach** [comment] 2023-04-27 13:51
@alexey-milovidov looks different.  Not just error message but behavior as well.  gh_events is a single native xz'd file, not a series of gz files.  

```
ENGINE = URL('https://datasets.clickhouse.com/github_events_v2.native.xz', Native);
```

**Comment by alexey-milovidov** [comment] 2023-04-28 18:15
Duplicate of https://github.com/ClickHouse/github-explorer/issues/15#issuecomment-1350004469

**Closed by alexey-milovidov** 2023-04-28 18:15 UTC
Labels: bug, invalid

**Comment by alexey-milovidov** [comment] 2023-04-28 18:20
See https://github.com/ClickHouse/github-explorer/pull/17
