### ISSUE TITLE
Code: 572, e.displayText() = DB::Exception: Too many optimizations applied to query plan. Current limit 10000 (version 21.3.17.2 (official build))

### ISSUE THREAD

**Issue by RoyBellingan** [ClickHouse/ClickHouse#29651] opened 2021-10-01 20:18 UTC
Running an alter table update, over a small numbe of rows (less than 1000) on a ~35M rows table fails 
The sql is as follows

UPDATE osName = 'Android', osVersion = '9', browserName = base64Decode('SGV5VGFwQnJvd3Nlcg=='), browserVersion = '20', device = 'smartphone', brand = 'OPPO' WHERE userAgent = base64Decode('TW96aWxsYS81LjAgKExpbnV4OyBVOyBBbmRyb2lkIDk7IFBDQU0xMCBCdWlsZC9QUFIxLjE4MDYxMC4wMTEpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIFZlcnNpb24vNC4wIENocm9tZS83MC4wLjM1MzguODAgTW9iaWxlIFNhZmFyaS81MzcuMzYgSGV5VGFwQnJvd3Nlci8yMC43LjQuMQ==')

Executed on current stable version 21.3.17.2

**Error message and/or stacktrace**

2021.10.01 20:10:59.470021 [ 22715 ] {} <Error> auto DB::IBackgroundJobExecutor::jobExecutingTask()::(anonymous class)::operator()() const: Code: 572, e.displayText() = DB::Exception: Too many optimizations applied to query plan. Current limit 10000, Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception<unsigned long&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&) @ 0x854842e in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
1. DB::QueryPlanOptimizations::optimizeTree(DB::QueryPlanOptimizationSettings const&, DB::QueryPlan::Node&, std::__1::list<DB::QueryPlan::Node, std::__1::allocator<DB::QueryPlan::Node> >&) @ 0xf8ff4f9 in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
2. DB::QueryPlan::buildQueryPipeline(DB::QueryPlanOptimizationSettings const&) @ 0xf8ef8db in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
3. DB::MutationsInterpreter::addStreamsForLaterStages(std::__1::vector<DB::MutationsInterpreter::Stage, std::__1::allocator<DB::MutationsInterpreter::Stage> > const&, DB::QueryPlan&) const @ 0xedbecc1 in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
4. DB::MutationsInterpreter::execute() @ 0xedbfdad in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
5. DB::MergeTreeDataMergerMutator::mutatePartToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MutationCommands const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, long, DB::Context const&, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0xf402ce3 in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
6. DB::StorageMergeTree::mutateSelectedPart(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::StorageMergeTree::MergeMutateSelectedEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0xf1740ee in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
7. bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::StorageMergeTree::getDataProcessingJob()::$_4, bool ()> >(std::__1::__function::__policy_storage const*) @ 0xf1835d8 in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
8. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::IBackgroundJobExecutor::jobExecutingTask()::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0xf34c4b7 in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x853ea08 in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
10. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() @ 0x854041f in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x853c05f in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
12. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0x853f4d3 in /usr/lib/debug/.build-id/f7/2fb8308dfde931de72a59a50dbd15287eaa52d.debug
13. start_thread @ 0x8744 in /lib64/libpthread-2.22.so
14. clone @ 0xe9d3d in /lib64/libc-2.22.so
 (version 21.3.17.2 (official build))

**Comment by tavplubix** [comment] 2021-10-01 20:20
Looks like duplicate of #25131

**Comment by RoyBellingan** [comment] 2021-10-01 20:25
How is possible I missed something with almost the same title -.-
I will try to apply the suggestion on the other ticket, thank you!

**Closed** 2021-10-01 20:44 UTC
Labels: duplicate, potential bug

**Comment by RoyBellingan** [comment] 2021-10-01 20:51
Just for the record, in my case the query_plan_max_optimizations_to_apply did not worked, so I killed it and I will now try to SLOWLY reapply them.
