### ISSUE TITLE
[24.11] Wrong results returned when using subquery with max(timestamp) and  DateTime64(3, 'UTC') field

### ISSUE THREAD

**Issue by voran** [ClickHouse/ClickHouse#72688] opened 2024-12-02 10:47 UTC
**Company or project name**

Releva.ai

**Describe what's wrong**

Using max(tiemstamp) in subquery causes clickhouse to incorrectly return 0 results when timestamp is a DateTime64(3, 'UTC') field.

[fiddle](https://fiddle.clickhouse.com/cb3fa0b5-7945-4883-83ed-3ab85898e569)
Fails on version 24.11.1.2557-alpine
Works on versions 24.10.3.21-alpine and 4.9.1.3278-alpine

**Does it reproduce on the most recent release?**

**Yes.** Reproduces on version 24.11.1.2557-alpine which is the latest release at the time of reporting.

Does not reproduce on versions 24.10.3.21-alpine and 24.9.1.3278-alpine.

**Enable crash reporting**

N/A as no crash or error logs are observed.

**How to reproduce**

See [fiddle](https://fiddle.clickhouse.com/cb3fa0b5-7945-4883-83ed-3ab85898e569) for 1-click reproducible solution.

Detailed steps:
```
docker run --rm --name clickhouse -it clickhouse/clickhouse-server:24.11.1.2557-alpine

# in a separate terminal
docker exec -it clickhouse clickhouse-client

CREATE TABLE ev_test
(
    profileId String,
    timestamp DateTime64(3, 'UTC'),
)
ENGINE = MergeTree()
ORDER BY (timestamp, profileId)

insert into ev_test (profileId, timestamp) 
VALUES ('1', '2024-12-02 09:50:07.100')
```

Verify that 1 row was inserted:
```
SELECT
    profileId,
    max(timestamp) AS timestamp
FROM ev_test
GROUP BY
    profileId

Query id: 23438719-32ff-48ec-9ddc-1c4ba580c739

   ┌─profileId─┬───────────────timestamp─┐
1. │ 1         │ 2024-12-02 09:50:07.100 │
   └───────────┴─────────────────────────┘
```

Observe the bug
```
 SELECT *
    FROM ev_test
    WHERE (
        (profileId, timestamp) IN (
            SELECT
                profileId,
                max(timestamp) AS timestamp
            FROM ev_test
            GROUP BY
                profileId
        )
    )


Query id: 00c09eea-8db6-4c65-bbb0-80fd37100351

Ok.

0 rows in set. Elapsed: 0.010 sec. 
```

**Expected behavior**

The last query above should clearly return 1 row but it returns 0 rows on the affected verion.

**Error message and/or stacktrace**

No error or warning messages were observed.

**Additional context**

Note that if you replace SELECT * with SELECT count() in the query above, it will return the correct value of '1'

**Comment by Algunenano** [comment] 2024-12-02 10:51
Probably a duplicate of https://github.com/ClickHouse/ClickHouse/issues/72532

**Closed** 2024-12-02 18:07 UTC
Labels: potential bug
