### ISSUE TITLE
Idle Clickhouse Server unresponsive with excessive CPU and Swap usage on MacOS

### ISSUE THREAD

**Issue by mikolajsnioch** [ClickHouse/ClickHouse#33414] opened 2022-01-05 12:33 UTC
Hello,

I noticed that after I let the macbook idle overnight, it gets hot in the morning. Upon inspecting the load with htop, I can see that Clickhouse server, which was not queried by any application or hasn't been doing any work, is under heavy load:
<img width="1587" alt="Screenshot 2022-01-05 at 13 20 49" src="https://user-images.githubusercontent.com/22744577/148217318-c46c72b1-f1c3-4481-8dcc-ae6fb2bcf0b8.png">

If I try to start `clickhouse client` I see the following output:
```
mks@mkss-MBP ~ % clickhouse client
ClickHouse client version 21.12.2.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.12.2 revision 54452.

mkss-MBP :) Cannot load data for command line suggestions: Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (total) exceeded: would use 229.60 TiB (attempt to allocate chunk of 4414670 bytes), maximum: 28.80 GiB. (MEMORY_LIMIT_EXCEEDED) (version 21.12.2.1)
```

To get it to work I need to restart the server, after which it works OK until I leave the computer idle for a few hours again:
```
mks@mkss-MBP ~ % brew services restart clickhouse
Stopping `clickhouse@21.12`... (might take a while)
==> Successfully stopped `clickhouse@21.12` (label: homebrew.mxcl.clickhouse@21.12)
==> Successfully started `clickhouse@21.12` (label: homebrew.mxcl.clickhouse@21.12)
mks@mkss-MBP ~ % clickhouse client
ClickHouse client version 21.12.2.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.12.2 revision 54452.

mkss-MBP :) 
```

Clickhouse version, as seen on the snippets above, is 21.12.2.1 installed with brew. The computer is Macbook Pro M1 Max, 32 GB RAM, macOS Monterey 12.1

**Comment by dearkarm** [comment] 2022-01-05 12:54
Not sure if relevant, but I also noticed fseventsd is at 233% CPU and uses 36GB of swap.

**Comment by filimonov** [comment] 2022-01-05 12:56
Support for mac / arm is still experimental. 
Please keep monitoring it.

The first place to look - are clickhouse logs, they may have information about what's happening. 

The other place - is clickhouse internal debugging tools:
```
SELECT * FROM system.merges;
SELECT * FROM system.processes;
SET allow_introspection_functions = 1
WITH arrayMap(x -> demangle(addressToSymbol(x)), trace) AS all SELECT groupArray(thread_id), count(),  arrayStringConcat(all, '\n') AS res FROM system.stack_trace GROUP BY res ORDER BY count() DESC;
```

After that you can trace the clickhouse process with system tools: https://stackoverflow.com/questions/23200704/install-perf-on-mac

> fseventsd 

means that there is a huge pressure on a filesystem.

**Comment by dearkarm** [comment] 2022-01-05 14:20
> Look at the line beginning :) `2022.01.05 12:20:06.511689` etc.

Ha, I probably need another coffee.

I am setting up tracing, is there anything else I could provide that would help narrow down the problem?

**Comment by den-crane** [comment] 2022-01-05 14:33
>That look very strange. Most probably it is some bug - either in logic, either in memory tracking.

I think it's alternative compiler/build issue. 

@dearkarm how you install using brew? Did you build CH or you use binaries bottle?

**Comment by alexey-milovidov** [comment] 2022-01-05 16:01
`brew` support for ClickHouse is from third-party and is not supported.

I recommend to install ClickHouse from the official website: https://clickhouse.com/#quick-start

**Comment by dearkarm** [comment] 2022-01-05 21:02
> @dearkarm how you install using brew? Did you build CH or you use binaries bottle?

```
mks@mkss-MBP ~ % brew info clickhouse
altinity/clickhouse/clickhouse@21.12: stable 21.12.2.17 (bottled), HEAD
Free analytics DBMS for big data with SQL interface
https://clickhouse.com
/opt/homebrew/Cellar/clickhouse@21.12/21.12.2.17 (25 files, 313.4MB) *
  Poured from bottle on 2021-12-30 at 14:53:52
From: https://github.com/altinity/homebrew-clickhouse/blob/HEAD/Formula/clickhouse@21.12.rb
License: Apache-2.0
```

I will compile and see if that resolves the problem.

**Comment by dearkarm** [comment] 2022-01-06 17:36
The link to the official MacOS build does not work:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Resource>/master/macos-aarch64/</Resource>
<RequestId>3411384e12df8369</RequestId>
</Error>
```

**Comment by den-crane** [comment] 2022-01-06 17:46
@dearkarm try 

```
wget 'https://builds.clickhouse.com/master/macos/clickhouse'
chmod a+x ./clickhouse
./clickhouse
```

https://clickhouse.com/#quick-start

**Comment by dearkarm** [comment] 2022-01-06 17:52
```
mks@mkss-MBP ~ % wget 'https://builds.clickhouse.com/master/macos/clickhouse'
--2022-01-06 18:52:03--  https://builds.clickhouse.com/master/macos/clickhouse
Resolving builds.clickhouse.com (builds.clickhouse.com)... 172.66.40.249, 172.66.43.7
Connecting to builds.clickhouse.com (builds.clickhouse.com)|172.66.40.249|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-06 18:52:04 ERROR 404: Not Found.
```

**Comment by qoega** [comment] 2022-01-06 18:13
I remember the issue was present even 1 or 2 years ago. Linux version can get current anon rss size from system and update free memory, but macOS version can have leaking memory usage. Probably it was not fixed yet

**Comment by den-crane** [comment] 2022-01-06 19:07
so it could be reproducible with any MacOs, even not M1 ? I'll check.

**Comment by dearkarm** [comment] 2022-01-06 23:29
I compiled following the documentation. The server and the client work, but when I try to attach Insturments profiler I get an error: `Failed to gain authorization`. Instruments also prints to the console: `This process won't be able to run remote lookup service`. This happens regardless of whether I run clickhouse server as root or as a regular user. The same is true for Instruments run as root and as a regular user.

Do I need to compile clickhouse with a specific flag to enable profiling?

P.S. I ran queries @filimonov suggested, the last one produces an exception:
`Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table system.stack_trace doesn't exist. (UNKNOWN_TABLE)`

**Comment by den-crane** [comment] 2022-01-07 14:26
Right, the same problem with x86 macos

**Comment by den-crane** [comment] 2022-01-07 16:44
@dearkarm I suggest to switch to Clickhouse in docker. I think the problem is exactly which @qoega described.

**Comment by zhixiangyuan** [comment] 2022-02-03 03:44
I also encountered this problem, can this problem be fixed in the next version?

**Comment by alexey-milovidov** [comment] 2022-03-13 17:59
@FArthur-cmd started to investigate this issue, he installed the latest official ClickHouse build for mac OS as following:
```
curl https://clickhouse.com/ | sh
```

Then started it and left for a while. No issue exists.

**Closed by alexey-milovidov** 2022-03-13 17:59 UTC
Labels: alternative build, comp-darwin

**Comment by mikolajsnioch** [comment] 2022-09-16 16:10
The issue definitely exists. It happened to me again today. This time it's easier for me to say that this is not related to anything I have been doing, because:

- I have no database or tables created on that instance (running locally on my laptop)
- The server has been running in the background and it's been five days since I run the last query (calling an External UDF with data provided in the query, something to the effect of SELECT my_fun(1, 2, 3))

The error is as follows:
```
2022.09.16 02:16:51.871081 [ 3527264 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 28.80 GiB (attempt to allocate chunk of 4223488 bytes), maximum: 28.80 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero.: (while reading column CurrentMetric_BackgroundDistributedSchedulePoolTask): (while reading from part /opt/clickhouse/data/store/67d/67d94ccd-02b8-458d-bfb7-3a1934768ea4/202209_59218_60688_294/ from mark 3 with max_rows_to_read = 2127): While executing MergeTreeSequentialSource. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

<Empty trace>
 (version 22.9.1.1632 (official build))
```

And it just repeats endlessly. I noticed the laptop was getting hot, looking at the logs it kept asking for more memory for about 14 hours, using 28 out of 32 gb of memory and additional 16 gb of swap. There's also over 400 gb of data written to the disk over the last 12 hours, so there's that...

I think there is a memory leak that happens during the merge of clickhouse own log table. That's the only process that has been running for 5 days.
