### ISSUE TITLE
MaterilizMySQL Attempt to read after eof: while receiving packet from localhost:9000

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#14572] opened 2020-09-08 05:35 UTC
**Describe the bug**
When I execute insert into mobile_belong2 select *from  mobile_belong, I got the issue as blow
mysql> insert into mobile_belong2 select *from mobile_belong;

test-1-118.raipeng.com :) select count(1) from mobile_belong2
SELECT count(1)
FROM mobile_belong2
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000
Connecting to database just at localhost:9000 as user root.
Connected to ClickHouse server version 20.8.1 revision 54438.

**How to reproduce**
step 1:
mysql>show create table mobile_belong
CREATE TABLE `mobile_belong` (
  `section` varchar(7) NOT NULL COMMENT '号段',
  `provinceId` varchar(10) DEFAULT NULL COMMENT '省份编码ID',
  `province` varchar(30) DEFAULT NULL COMMENT '省份',
  `cityId` varchar(10) DEFAULT NULL COMMENT '城市编码ID',
  `city` varchar(30) DEFAULT NULL COMMENT '城市',
  `sign` int(11) DEFAULT NULL COMMENT '中国电信0 中国移动1 中国联通2 虚拟卡 -1',
  `name` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`section`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='号段省份表'
mysql>select count(1) from mobile_belong
4391280（this table need a lot of data,otherwrise, the issue will not be reproduce）
mysql>create table mobile_belong2 like mobile_belong
step2:
mysql>insert into mobile_belong2  select *from mobile_belong
step3:
clickhouse :) select count(1) from mobile_belong2
SELECT count(1)
FROM mobile_belong2
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000
Connecting to database just at localhost:9000 as user root.
Connected to ClickHouse server version 20.8.1 revision 54438.

**Comment by chang0391** [comment] 2020-09-08 06:05
When I  got this issue, I can not access other tables , all the other tables show same issue as below

SELECT count(1)
FROM mobile_belong2
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000

Connecting to database just at localhost:9000 as user root.
Connected to ClickHouse server version 20.8.1 revision 54438.
test-1-118.raipeng.com :) select count(1) from aaa;
SELECT count(1)
FROM aaa
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000
Connecting to database just at localhost:9000 as user root.
Connected to ClickHouse server version 20.8.1 revision 54438.
test-1-118.raipeng.com :) ^C
test-1-118.raipeng.com :) select count(1) from bbb;
SELECT count(1)
FROM bbb
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000

Connecting to database just at localhost:9000 as user root.
Connected to ClickHouse server version 20.8.1 revision 54438.

**Comment by chang0391** [comment] 2020-09-08 07:22
below is error.log:
2020.09.08 15:17:34.476418 [ 31922 ] {d8d30b12-f09c-4062-acf5-a0908ed9cef7} <Error> executeQuery: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 4518 bytes, while 3678 bytes are in buffer. (version 20.8.1.4513 (official build)) (from [::1]:34988) (in query: select count(1) from mobile_belong3), Stack trace (when copying this message, always include the lines below):

0. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1a807d30 in /usr/lib/debug/usr/bin/clickhouse
1. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:37: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xff9e75d in /usr/lib/debug/usr/bin/clickhouse
2. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/string:2134: DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) (.cold) @ 0x173be810 in /usr/lib/debug/usr/bin/clickhouse
3. /build/obj-x86_64-linux-gnu/../src/Core/MySQL/PacketEndpoint.cpp:50: DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x173cb227 in /usr/lib/debug/usr/bin/clickhouse
4. /build/obj-x86_64-linux-gnu/../src/Core/MySQL/MySQLClient.cpp:162: DB::MySQLClient::readOneBinlogEvent(unsigned long) @ 0x173c8891 in /usr/lib/debug/usr/bin/clickhouse
5. /build/obj-x86_64-linux-gnu/../src/Databases/MySQL/MaterializeMySQLSyncThread.cpp:179: DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x173a04d0 in /usr/lib/debug/usr/bin/clickhouse
6. /build/obj-x86_64-linux-gnu/../src/Common/ThreadPool.h:170: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::MaterializeMySQLSyncThread::startSynchronization()::'lambda'()>(DB::MaterializeMySQLSyncThread::startSynchronization()::'lambda'()&&)::'lambda'()::operator()() const @ 0x173a08d6 in /usr/lib/debug/usr/bin/clickhouse
7. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffce517 in /usr/lib/debug/usr/bin/clickhouse
8. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xffccb53 in /usr/lib/debug/usr/bin/clickhouse
9. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfe8dd in /usr/lib64/libc-2.17.so

2020.09.08 15:17:34.477155 [ 31922 ] {} <Error> ServerErrorHandler: Code: 99, e.displayText() = DB::Exception: Packet payload is not fully read. Stopped after 4518 bytes, while 3678 bytes are in buffer., Stack trace (when copying this message, always include the lines below):

**Comment by chang0391** [comment] 2020-09-08 08:10
just  now, I executed this  sentence  “update mobile_belong set province=' 你好'” ，the  table  have several million rows，
It also report  the same issue as  below, so I think it's bacause rows too big to cause binlog huge, and, binlog too huge to cause the issue.
SELECT count(1)
FROM mobile_belong
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000
Connecting to database just at localhost:9000 as user root.
Connected to ClickHouse server version 20.8.1 revision 54438.

**Comment by chang0391** [comment] 2020-09-09 02:48
@BohuTANG    @zhang2014 
      I created the function as below,  when I executed the SQL "call  bulk_insert()" in mysql, I can got correct result in MySQL, but I   got the same issue "Attempt to read after eof: while receiving packet from localhost:9000"  in CH
    by the way, the table have one hundred rows data
step1: 
CREATE TABLE `mobile_belong` (
  `section` bigint(20) NOT NULL,
  `provinceId` varchar(10) DEFAULT NULL COMMENT '省份编码ID',
  `province` varchar(30) DEFAULT NULL COMMENT '省份',
  `cityId` varchar(10) DEFAULT NULL COMMENT '城市编码ID',
  `city` varchar(30) DEFAULT NULL COMMENT '城市',
  `sign` int(11) DEFAULT NULL COMMENT '中国电信0 中国移动1 中国联通2 虚拟卡 -1',
  `name` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`section`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='号段省份表'

CREATE TABLE `mobile_belong_test` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `section` int(11) DEFAULT NULL,
  `provinceId` varchar(10) DEFAULT NULL,
  `province` varchar(30) DEFAULT NULL,
  `cityId` varchar(10) DEFAULT NULL,
  `city` varchar(30) DEFAULT NULL,
  `sign` int(11) DEFAULT NULL,
  `name` varchar(10) DEFAULT NULL,
  `section2` int(11) DEFAULT NULL,
  `provinceId2` varchar(10) DEFAULT NULL,
  `province2` varchar(30) DEFAULT NULL,
  `cityId2` varchar(10) DEFAULT NULL,
  `city2` varchar(30) DEFAULT NULL,
  `sign2` int(11) DEFAULT NULL,
  `name2` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=457954 DEFAULT CHARSET=utf8mb4

step2:

CREATE PROCEDURE bulk_insert()
BEGIN 
DECLARE rn int default 1;
DECLARE rn2 int default 0;
DECLARE rm int default 0;
SELECT MAX(section) into rm FROM just.mobile_belong;
SELECT Min(section) into rn FROM just.mobile_belong;
WHILE (rn <=rm) DO
SET rn2 = rn + 5000; 
insert into mobile_belong_test(section,provinceId,province,cityId,city,sign,name,section2,provinceId2,province2,cityId2,city2,sign2,name2)
select a.section,a.provinceId,a.province,a.cityId,a.city,a.sign,a.name,b.section,b.provinceId,b.province,b.cityId,b.city,b.sign,b.name 
from mobile_belong a,mobile_belong b where a.section=b.section and a.section >=rn and a.section<rn2; 
SET rn = rn + 5000; 
commit;
END WHILE;
END

step3:
mysql> call  bulk_insert()

**Comment by chang0391** [comment] 2020-09-09 05:46
@zhang2014 @BohuTANG 
  这个问题应该是一个事务对应的数据量大，那么一个GTID所对应的SQL语句就多，似乎是buffer或者数组什么的不够造成的，另外还发现像这样用 procedure循环insert，也会出现这样的问题。

**Comment by zhang2014** [comment] 2020-09-09 16:44
Bad parse protocol. @BohuTANG is trying to fix it.

**Comment by liangli1213** [comment] 2020-09-09 23:56
Thanks @zhang2014 @BohuTANG for your effort, hope you can fix it.

**Comment by tavplubix** [comment] 2020-09-10 13:37
Duplicate of #14251

**Closed** 2020-09-11 12:10 UTC
Labels: bug, comp-mysql, duplicate
