### ISSUE TITLE
Update ClickHouse for M1 Mac Support

### ISSUE THREAD

**Issue by dimonnot** [ClickHouse/ClickHouse#22712] opened 2021-04-06 15:06 UTC
ClickHouse build failed on M1 Mac

**Operating system**
Mac OS Big Sur 11.2.3

**Cmake version**
cmake version 3.20.0

**Compiler name and version**
AppleClang compiler

**Full cmake and/or ninja output**
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
CMake Error at cmake/arch.cmake:14 (message):
  32bit platforms are not supported
Call Stack (most recent call first):
  CMakeLists.txt:44 (include)

Docker images is failed too:

runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc
runtime stack:
runtime.throw(0x4cb21f, 0x9)
/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc420028000, 0xc420037fc0)
/usr/local/go/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x4d6db8, 0x0)
/usr/local/go/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
/usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x53ae00)
/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
/usr/local/go/src/runtime/proc.go:1079
goroutine 1 [running]:
runtime.systemstack_switch()
/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760
runtime.main()
/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0
Configuration file '' isn't readable by user with id '101'

**Comment by filimonov** [comment] 2021-04-07 06:36
Duplicate of #20245

https://github.com/ClickHouse/ClickHouse/pull/21639

**Closed by filimonov** 2021-04-07 06:36 UTC
Labels: build
