### ISSUE TITLE
`allow_nondeterministic_mutations` does not work on mutations with subqueries

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#43237] opened 2022-11-15 06:47 UTC
After upgrading to `clickhouse-server v22.3.13.80`, our mutations stopped working because ClickHouse started to consider it as non-deterministic mutations. But even after setting `allow_nondeterministic_mutations=1`, we still get the following error:

```
Code: 36. DB::Exception: ALTER UPDATE/ALTER DELETE statement with subquery may be nondeterministic, see allow_nondeterministic_mutations setting. (BAD_ARGUMENTS) (version 22.3.13.80 (official build)). (BAD_ARGUMENTS) (version 22.3.13.80 (official build))
```

Can you please help me with this issue?

Thanks

## Appendix

Here is how we defined the settings:

```XML
<yandex>
    <profiles>
        <default>
            ...
        </default>

        <management>
            <profile>default</profile>

            <allow_nondeterministic_mutations>1</allow_nondeterministic_mutations>
        </management>
    </profiles>
</yandex>
```

```SQL
CREATE USER IF NOT EXISTS my_management_user
ON CLUSTER clickhouse_cluster
IDENTIFIED WITH SHA256_PASSWORD BY '{{secret}}'
HOST ANY
SETTINGS PROFILE 'management';
```

And to verify that the settings were read correctly by ClickHouse, I ran the following...

```SQL
SELECT *
FROM system.settings_profile_elements
WHERE profile_name LIKE '%management%' OR user_name LIKE '%management%'

┌─profile_name─┬─user_name──────────────┬─role_name─┬─index─┬─setting_name───────────────────────┬─value───────────┬─min──┬─max──┬─readonly─┬─inherit_profile─┐
│ ᴺᵁᴸᴸ         │ my_management_user     │ ᴺᵁᴸᴸ      │     0 │ ᴺᵁᴸᴸ                               │ ᴺᵁᴸᴸ            │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │     ᴺᵁᴸᴸ │ management      │
│ management   │ ᴺᵁᴸᴸ                   │ ᴺᵁᴸᴸ      │     0 │ ᴺᵁᴸᴸ                               │ ᴺᵁᴸᴸ            │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │     ᴺᵁᴸᴸ │ default         │
│ management   │ ᴺᵁᴸᴸ                   │ ᴺᵁᴸᴸ      │     1 │ allow_nondeterministic_mutations   │ 1               │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │     ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ            │
└──────────────┴────────────────────────┴───────────┴───────┴────────────────────────────────────┴─────────────────┴──────┴──────┴──────────┴─────────────────┘```
```

And here is our mutation...

```SQL
ALTER TABLE my_db.my_table
ON CLUSTER clickhouse_replica_set
DELETE
WHERE
    Date BETWEEN '{{start_date}}' AND '{{end_date}}'
    AND (UserId, SessionId) GLOBAL NOT IN (
        SELECT UserId, SessionId
        FROM my_db.my_another_table
    );
```

**Comment by tavplubix** [comment] 2022-11-15 14:59
> After upgrading to clickhouse-server v22.3.13.80

From what version? I suppose it was 21.10 or older, because mutations with subqueries are considered as non-deterministic since 21.11 (see https://github.com/ClickHouse/ClickHouse/pull/29495)

> But even after setting allow_nondeterministic_mutations=1, we still get the following error

It's because mutations are processed in background with settings from default profile. User/session/query settings are not passed to mutations. See https://github.com/ClickHouse/ClickHouse/pull/37022

**Comment by tavplubix** [comment] 2022-11-15 15:10
> It's because mutations are processed in background with settings from default profile. User/session/query settings are not passed to mutations. See https://github.com/ClickHouse/ClickHouse/pull/37022

Hm, no, it's not correct, actually `allow_nondeterministic_mutations` should be checked before creating a mutation. And we have some tests for it: https://github.com/ClickHouse/ClickHouse/blob/fb249aca621e009c0bc283ac4231933b7df8bfcd/tests/queries/0_stateless/01162_strange_mutations.sh

The difference is that you use ON CLUSTER. So probably it's duplicate of https://github.com/ClickHouse/ClickHouse/issues/6107. Try to set `distributed_ddl_entry_format_version` to 2

**Closed by tavplubix** 2022-11-15 15:10 UTC
Labels: unexpected behaviour

**Comment by OmarBazaraa** [comment] 2022-11-24 15:53
Thanks @tavplubix! Adding `distributed_ddl_entry_format_version=2` fixed the problem indeed.
