### ISSUE TITLE
ClickHouse 20.1+ clickhouse-client secure login server error 

### ISSUE THREAD

**Issue by snowzjy** [ClickHouse/ClickHouse#9317] opened 2020-02-23 08:26 UTC
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
use tcp secure can't login server after server started 1 hour 

**How to reproduce**
config openSSL in server and start server, you can login server by secure now
wait for 1 hour
can not login to server by secure

* Which ClickHouse server version to use
20.1.4 or 20.2.4

**Expected behavior**
login to server by secure

**Error message and/or stacktrace**
╰─$ clickhouse-client -u default --secure --host=xxxx --ask-password                                                                                             
ClickHouse client version 20.1.4.14 (official build).
Password for user (default): 
Connecting to xxxx:9440 as user default.
Code: 210. DB::NetException: SSL Exception: error:14004438:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert internal error (xxxx:9440)

and check log in server:
2020.02.23 16:10:23.194289 [ 46 ] {} <Error> ServerErrorHandler: Code: 210, e.displayText() = DB::NetException: SSL Exception: error:2400006E:random number generator::error retrieving entropy, while reading from socket (111.201.235.201:17751), Stack trace (when copying this message, always include the lines below):

0. 0xbc34d6c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x4f6e129 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x4cfdf66 ?  in /usr/bin/clickhouse
3. 0x4ff1611 DB::TCPHandler::runImpl()  in /usr/bin/clickhouse
4. 0x4ff225c DB::TCPHandler::run()  in /usr/bin/clickhouse
5. 0x9bb87b7 Poco::Net::TCPServerConnection::start()  in /usr/bin/clickhouse
6. 0x9bb8bad Poco::Net::TCPServerDispatcher::run()  in /usr/bin/clickhouse
7. 0xbca74cf Poco::PooledThread::run()  in /usr/bin/clickhouse
8. 0xbca4598 Poco::ThreadImpl::runnableEntry(void*)  in /usr/bin/clickhouse
9. 0xbca5e39 ?  in /usr/bin/clickhouse
10. 0x76db start_thread  in /lib/x86_64-linux-gnu/libpthread-2.27.so
11. 0x12188f __GI___clone /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so
 (version 20.1.4.14 (official build))

**Comment by filimonov** [comment] 2020-02-24 11:51
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/8886

**Closed by filimonov** 2020-02-24 11:51 UTC
Labels: bug, comp-net, duplicate
