### ISSUE TITLE
Setting enable_optimize_predicate_expression does not work for subquery with FINAL

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#5695] opened 2019-06-20 09:29 UTC
**Describe the bug**

* reproduce

1
 add setting in user.xml

<enable_optimize_predicate_expression>1</enable_optimize_predicate_expression>
 <optimize_move_to_prewhere>1</optimize_move_to_prewhere>

2 create  table 'test' with MergeTree

3 execute any sql from the table 'test'

4 once I delete the setting, It works well

*  version 
ClickHouse 18.16.1 with revision 54412

* Which interface to use, if matters
http api

* Non-default settings, if any
in user.xml
 <enable_optimize_predicate_expression>1</enable_optimize_predicate_expression>
 <optimize_move_to_prewhere>1</optimize_move_to_prewhere>
            
* Queries to run that lead to unexpected result
execute any sql

**Expected behavior**
return the right data with sql but failed

**Error message and/or stacktrace**

in the error.log file
[error.log](https://github.com/yandex/ClickHouse/files/3309741/error.log)

**Comment by peaksnail** [comment] 2019-06-20 09:42
When I put the setting in config.xml , I select * from system.setting find that I not work for me 

It will work when I execute set enable_optimize_predicate_expression=1 in clickhouse-client session

**Comment by filimonov** [comment] 2019-06-20 09:58
Most of 18.6 issues were fixed in later versions. Please update to latest clickhouse version.

**Comment by peaksnail** [comment] 2019-06-20 10:13
when I set enable_optimize_predicate_expression=1 in config.xml ,then i select * from system.settings where name='enable_optimize_predicate_expression' , the value =0 ,It not work, is there something wrong?

**Comment by den-crane** [comment] 2019-06-20 14:19
enable_optimize_predicate_expression should be users.xml not in config.xml

enable_optimize_predicate_expression became stable in 19.5 and it's still has issues with SQL results.

**Comment by 4ertus2** [comment] 2019-06-20 16:23
Need reproduction on newer version.

**Comment by peaksnail** [comment] 2019-07-04 03:05
I have upgrade to version 19.9.2.4 ,I found enable_optimize_predicate_expression not work

I create view name bill_determine_view as `create view bill_determine_view as select * from bill final`

there is 2.14 million row in the table 

when I select count() from bill where storeId='519d8248-14f3-4c71-bebf-24ddb1f2d273', the trace show that 

 `1 rows in set. Elapsed: 0.006 sec. Processed 87.00 thousand rows, 3.91 MB (14.86 million rows/s., 668.60 MB/s.)
`

but I get 
`1 rows in set. Elapsed: 1.675 sec. Processed 2.14 million rows, 262.96 MB (1.28 million rows/s., 157.02 MB/s.) ` 
when I select count() from bill_determine_view where storeId='519d8248-14f3-4c71-bebf-24ddb1f2d273',  select in view will processed all data

**Comment by alexey-milovidov** [comment] 2019-07-22 15:56
Confirmed. It doesn't work at all:

```
CREATE TABLE bill (storeId String) ENGINE = ReplacingMergeTree ORDER BY storeId;
INSERT INTO bill SELECT generateUUIDv4() FROM numbers(1000000);
SELECT * FROM bill ORDER BY rand() LIMIT 10;

│ ba1534cc-a9cb-46e8-8715-9236fc6189f6 │
...

create view bill_determine_view as select * from bill final;

SELECT * FROM bill_determine_view WHERE storeId = 'ba1534cc-a9cb-46e8-8715-9236fc6189f6'

Processed 1.00 million rows
```

**Comment by alexey-milovidov** [comment] 2019-07-22 16:01
Probably it should not because of FINAL modifier?

```
milovidov-Pro-P30 :) SELECT * FROM (SELECT * FROM bill) WHERE storeId = '079912d5-b297-4634-a2b5-c7adb5dec5f4'

SELECT *
FROM 
(
    SELECT *
    FROM bill
)
WHERE storeId = '079912d5-b297-4634-a2b5-c7adb5dec5f4'

┌─storeId──────────────────────────────┐
│ 079912d5-b297-4634-a2b5-c7adb5dec5f4 │
└──────────────────────────────────────┘

Processed 8.19 thousand rows

milovidov-Pro-P30 :) SELECT * FROM (SELECT * FROM bill FINAL) WHERE storeId = '079912d5-b297-4634-a2b5-c7adb5dec5f4'

SELECT *
FROM 
(
    SELECT *
    FROM bill
    FINAL
)
WHERE storeId = '079912d5-b297-4634-a2b5-c7adb5dec5f4'

┌─storeId──────────────────────────────┐
│ 079912d5-b297-4634-a2b5-c7adb5dec5f4 │
└──────────────────────────────────────┘

Processed 1.00 million rows
```

**Comment by alexey-milovidov** [comment] 2019-07-22 19:41
It was disabled intentionally:

https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/PredicateExpressionsOptimizer.cpp#L141

We should figure out what wrong can happen if we will enable it...

**Comment by alexey-milovidov** [comment] 2019-07-22 19:41
I think that nothing wrong can happen, because FINAL is evaluated before WHERE.

**Comment by alexey-milovidov** [comment] 2019-07-22 19:42
CC @zhang2014

**Comment by alexey-milovidov** [comment] 2019-07-22 19:45
It was specified by me:
https://github.com/yandex/ClickHouse/pull/2015#issuecomment-374283452

**Comment by alexey-milovidov** [comment] 2019-07-22 19:45
We can simply remove restriction on FINAL.

**Comment by alexey-milovidov** [comment] 2019-12-09 23:29
This issue is trivial to fix.

**Closed** 2019-12-09 23:30 UTC
Labels: comp-optimizers, easy task, unfinished code
