### ISSUE TITLE
Clickhorse server has been frequently restarted recently. Sometimes it runs several hours after it breaks down

### ISSUE THREAD

**Issue by wdp598** [ClickHouse/ClickHouse#31251] opened 2021-11-10 15:20 UTC
2021.11.10 16:55:18.036576 [ 12834 ] {} <Trace> shop.shop_sk_game_order (ReplicatedMergeTreeQueue): Adding mutation 0001047209 for partition 9acaaa3e06ded08bb72dd8cc9d8c01e2 for all block numbers less than 1046914
2021.11.10 16:55:18.036586 [ 12834 ] {} <Trace> shop.shop_sk_game_order (ReplicatedMergeTreeQueue): Adding mutation 0001047209 for partition 9af72a5f3fe6ccac14195ca8f8f059a9 for all block numbers less than 8131
2021.11.10 16:55:18.036599 [ 12834 ] {} <Trace> shop.shop_sk_game_order (ReplicatedMergeTreeQueue): Adding mutation 0001047209 for partition 9b3fc6295832a526e78fb26a747ba4a4 for all block numbers less than 1047119
2021.11.10 16:55:18.036607 [ 12834 ] {} <Trace> shop.shop_sk_game_order (ReplicatedMergeTreeQueue): Adding mutation 0001047209 for partition 9b81529227e47c7bc8e859f432862d59 for all block numbers less than 1046914
2021.11.10 16:55:18.036614 [ 12834 ] {} <Trace> shop.shop_sk_game_order (ReplicatedMergeTreeQueue): Adding mutation 0001047209 for partition 9ba98e02440aae1c8ed7c77f627a3641 for all block numbers less than 686520
...skipping...
2021.11.10 16:56:06.386963 [ 12981 ] {} <Fatal> BaseDaemon: ########################################
2021.11.10 16:56:06.387001 [ 12981 ] {} <Fatal> BaseDaemon: (version 21.10.2.15 (official build), build id: 6699B86599A2121E78E0D42DD67791ABD9AE5265) (from thread 12817) (no query) Received signal Segmentation fault (11)
2021.11.10 16:56:06.387029 [ 12981 ] {} <Fatal> BaseDaemon: Address: 0x7fd562469fb8 Access: write. Attempted access has violated the permissions assigned to the memory area.
2021.11.10 16:56:06.387067 [ 12981 ] {} <Fatal> BaseDaemon: Stack trace: 0x1199e0b5 0x119d6cbb 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209 0x119d6adc 0x119d7209
2021.11.10 16:56:06.387514 [ 12981 ] {} <Fatal> BaseDaemon: 1. DB::ISimpleTransform::prepare() @ 0x1199e0b5 in /usr/bin/clickhouse
2021.11.10 16:56:06.387551 [ 12981 ] {} <Fatal> BaseDaemon: 2. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x119d6cbb in /usr/bin/clickhouse
2021.11.10 16:56:06.387580 [ 12981 ] {} <Fatal> BaseDaemon: 3. DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long) @ 0x119d6adc in /usr/bin/clickhouse
2021.11.10 16:56:06.387600 [ 12981 ] {} <Fatal> BaseDaemon: 4. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x119d7209 in /usr/bin/clickhouse
2021.11.10 16:56:06.387629 [ 12981 ] {} <Fatal> BaseDaemon: 5. DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long) @ 0x119d6adc in /usr/bin/clickhouse
2021.11.10 16:56:06.387648 [ 12981 ] {} <Fatal> BaseDaemon: 6. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x119d7209 in /usr/bin/clickhouse
2021.11.10 16:56:06.387672 [ 12981 ] {} <Fatal> BaseDaemon: 7. DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long) @ 0x119d6adc in /usr/bin/clickhouse
2021.11.10 16:56:06.387688 [ 12981 ] {} <Fatal> BaseDaemon: 8. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x119d7209 in /usr/bin/clickhouse
2021.11.10 16:56:06.387706 [ 12981 ] {} <Fatal> BaseDaemon: 9. DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long) @ 0x119d6adc in /usr/bin/clickhouse
2021.11.10 16:56:06.387724 [ 12981 ] {} <Fatal> BaseDaemon: 10. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x119d7209 in /usr/bin/clickhouse
2021.11.10 16:56:06.387739 [ 12981 ] {} <Fatal> BaseDaemon: 11. DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long) @ 0x119d6adc in /usr/bin/clickhouse
2021.11.10 16:56:06.387762 [ 12981 ] {} <Fatal> BaseDaemon: 12. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x119d7209 in /usr/bin/clickhouse
2021.11.10 16:56:06.387779 [ 12981 ] {} <Fatal> BaseDaemon: 13. DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long) @ 0x119d6adc in /usr/bin/clickhouse

**Comment by tavplubix** [comment] 2021-11-11 15:13
Looks like duplicate of #23503

**Closed** 2021-12-09 16:03 UTC
Labels: crash, potential bug
