### ISSUE TITLE
Encountered "DB::Exception: Not found column equals..." (MaterializeMySQL)

### ISSUE THREAD

**Issue by nickbaba2012** [ClickHouse/ClickHouse#23470] opened 2021-04-22 05:47 UTC
Below is the table structure:
![image](https://user-images.githubusercontent.com/44794448/115661500-1a6dcc00-a370-11eb-88e1-b36f15c23ff2.png)

It's fine if there is only one condition in where clause:
![image](https://user-images.githubusercontent.com/44794448/115661810-9d8f2200-a370-11eb-9fa6-7ea34298775e.png)

but encountered "DB::Exception: Not found column equals..." if there are two or more conditions:
![image](https://user-images.githubusercontent.com/44794448/115662041-f9f24180-a370-11eb-80fb-4ab62f3d8306.png)

below is the details in the error log:
2021.04.22 13:44:47.869674 [ 11938 ] {1a222a70-e1d1-48d0-8493-357e18882ba8} <Error> TCPHandler: Code: 10, e.displayText() = DB::Exception: Not found column equals(tenant_code, 'AJIDOU') in block: while executing 'INPUT : 0 -> equals(tenant_code, 'AJIDOU') UInt8 : 0', Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x88b64ca in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x8953053 in /usr/bin/clickhouse
2. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0xf2fca61 in /usr/bin/clickhouse
3. DB::FilterTransform::transformHeader(DB::Block, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) @ 0x1021f891 in /usr/bin/clickhouse
4. DB::FilterStep::FilterStep(DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) @ 0x102af7d2 in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::executeWhere(DB::QueryPlan&, std::__1::shared_ptr<DB::ActionsDAG> const&, bool) @ 0xf3fdb70 in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>) @ 0xf3f1d77 in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf3efbdb in /usr/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0xf716713 in /usr/bin/clickhouse
9. DB::InterpreterSelectWithUnionQuery::execute() @ 0xf71789e in /usr/bin/clickhouse
10. ? @ 0xf8b98c2 in /usr/bin/clickhouse
11. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xf8b8203 in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0x1006ce3d in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0x1007f3b9 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x12739e8f in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x1273b8a1 in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x12871fc9 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x1286de2a in /usr/bin/clickhouse
18. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
19. __clone @ 0xf834d in /usr/lib64/libc-2.17.so

**Comment by tavplubix** [comment] 2021-04-22 10:02
Duplicate of #22432, fixed in #23200

**Closed by tavplubix** 2021-04-22 10:02 UTC
Labels: bug
