### ISSUE TITLE
Cannot use an aggregation result in select columns (ILLEGAL_AGGREGATION)

### ISSUE THREAD

**Issue by SergeyKotyushkin** [ClickHouse/ClickHouse#46268] opened 2023-02-10 12:18 UTC
**Describe what's wrong**

The usage of an aggregation result in select columns leads to ILLEGAL_AGGREGATION error.
https://fiddle.clickhouse.com/fde0d48f-c4d8-4253-af81-ecb94a1e7c50

**Does it reproduce on recent release?**

v22.3.17.13 - lts
v22.8.13.20 - lts
v23.1.3.5

**How to reproduce**

```sql
CREATE TABLE t (a Int8, b Int8)
ENGINE = MergeTree()
ORDER BY a;

INSERT INTO t (a, b)
VALUES (1, 2), (1, 3);

SELECT max(b) AS b, b AS b1
FROM t
GROUP BY a;
```

Gets error:
```
Received exception from server (version 22.8.13):
Code: 184. DB::Exception: Received from localhost:9000. DB::Exception: Aggregate function max(b) is found inside another aggregate function in query: While processing max(b) AS b. (ILLEGAL_AGGREGATION)
(query: SELECT max(b) AS b, b AS b1
FROM t
GROUP BY a;)
```

**Expected behavior**

Select completes without error.
`b=3, b1=3`

**Additional context**

1. We have similar code in our project and it worked well. But I could not find any CH version that executes this scenario without errors now.
2. When EXPLAIN SYNTAX is used it shows that `b` replaces with `max(b)` (that may explain error but not sure):
```
Received exception from server (version 22.8.13):
Code: 184. DB::Exception: Received from localhost:9000. DB::Exception: Aggregate function max(b) is found inside another aggregate function in query: While processing max(b) AS b: While processing SELECT max(b) AS b, max(b) AS b1 FROM t GROUP BY a LIMIT 10. (ILLEGAL_AGGREGATION)
(query: EXPLAIN SYNTAX
SELECT max(b) AS b, b AS b1
FROM t
GROUP BY a
LIMIT 10;)
```
3. The problem solves when the additional cast is added:
```sql
SELECT max(b) AS b, b::Int8 AS b1
FROM t
GROUP BY a;
```

**Comment by UnamedRus** [comment] 2023-02-10 12:22
What about?

```
SELECT max(b) AS b, b AS b1
FROM t
GROUP BY a
SETTINGS prefer_column_name_to_alias = 1
```

It's "feature" of ClickHouse SQL, you can reuse aliases anywhere.

**Comment by SergeyKotyushkin** [comment] 2023-02-10 12:24
Thanks,
I've tried this before. It leads to another problem:
```
Received exception from server (version 22.8.13):
Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column `b` is not under aggregate function and not in GROUP BY. Have columns: ['max(b)','a']: While processing max(b), b. (NOT_AN_AGGREGATE)
(query: SELECT max(b) AS b, b AS b1
FROM t
GROUP BY a
LIMIT 10
SETTINGS prefer_column_name_to_alias = 1;)
```

**Comment by SergeyKotyushkin** [comment] 2023-02-13 12:21
@alexey-milovidov, hello, could you please clarify what does `invalid` label mean? Is it correspond to my use case or functionality?

I think my scenario is correct.
My goal is to use aggregation result in the following calculations that do not require aggregation.

**Comment by den-crane** [comment] 2023-02-14 16:37
@SergeyKotyushkin Your task is unclear. Can you provide a better example? Do you need to address a column from the table or the result of the aggregation? Did you try to use a subquery?

**Comment by SergeyKotyushkin** [comment] 2023-02-15 08:33
> @SergeyKotyushkin Your task is unclear. Can you provide a better example? Do you need to address a column from the table or the result of the aggregation? Did you try to use a subquery?

I have some queries that look like next one where I try to round fractional number to closest integer:
[clickhouse-fiddle](https://fiddle.clickhouse.com/ad0bb2c9-eb87-4f8c-860d-5863984cc347)
```sql
CREATE TABLE t (k Int8, v Float64)
ENGINE = MergeTree()
ORDER BY k;

INSERT INTO t (k, v) VALUES (1, 1.3), (1, 1.4), (2, 2.1), (2, 2.7);

SELECT
  k,
  max(v) as v,
  ((floor(v) as floored) + if(v - floored < 0.5, 0, 1)) as r
FROM t
GROUP BY k
SETTINGS prefer_column_name_to_alias = 0;

-- expects
-- 1  1.4  1
-- 2  2.7  3
```

What I do in query:
1. Group rows by `k` column
2. Calculate max value for `v` and give it `v` alias
3. Calculate `r` value by using `v` alias found at previous step

The `r` calculation does not include any aggregation functions. It just does arithmetic operations with already calculated aggregated values.

I understand that my example can be fixed by many approaches but I do not understand why this example does not work. How to fix:
1. Change alias of `v` to something different from column name.
2. Do not use `floored` alias and duplicate `floor(v)`

I also know that this query works well some time ago.

In my original post I tried to find minimal scenario to reproduce the problem. Maybe it was too far from real one examples and that's why it was unclear.

**Comment by den-crane** [comment] 2023-02-15 14:20
works with experimental_analyzer

https://fiddle.clickhouse.com/06f8bf1e-ad18-4b75-aea9-affdb39eb859

**Comment by Algunenano** [comment] 2023-02-16 11:38
Coming from https://github.com/ClickHouse/ClickHouse/issues/46273.

This seems like the same issue:

```
CREATE TABLE ttttttt
(
    `timestamp` DateTime,
    `col1` Float64,
    `col2` Float64,
    `col3` Float64,
)
ENGINE = MergeTree()
ORDER BY tuple()


SELECT
    argMax(col1, timestamp) AS col1,
    argMax(col2, timestamp) AS col2,
    col1 / col2 AS final_col
FROM ttttttt AS vault_metrics_mv
GROUP BY
    col3
ORDER BY final_col DESC;

Received exception:
Code: 184. DB::Exception: Aggregate function argMax(col1, timestamp) is found inside another aggregate function in query: While processing argMax(col1, timestamp). (ILLEGAL_AGGREGATION)
```

It worked fine with 22.7 but fails with 22.8+

**Comment by Algunenano** [comment] 2023-02-16 12:00
To summarize the problem I'm seeing. I'd expect these 2 queries to be equivalent in CH:

```
SELECT
    argMax(col1, timestamp) AS col1,
    argMax(col2, timestamp) AS col2,
    col1 / col2 AS final_col
FROM ttttttt
GROUP BY col3
ORDER BY final_col DESC
```

```
SELECT
    *,
    col1 / col2 AS final_col
FROM
(
    SELECT
        argMax(col1, timestamp) AS col1,
        argMax(col2, timestamp) AS col2
    FROM ttttttt
    GROUP BY col3
)
ORDER BY final_col DESC
```

In 22.7 they both worked. In 22.8 the first one stopped working

**Comment by Algunenano** [comment] 2023-02-20 15:09
I've been looking at this and you don't even need a `GROUP BY` to reproduce it, just use the result twice:

```
CREATE TABLE ttttttt
(
    `timestamp` DateTime,
    `col1` Float64,
    `col2` Float64,
    `col3` Float64
)
ENGINE = MergeTree()
ORDER BY tuple();

SELECT
    argMax(col1, timestamp) AS col1,
    col1 / 10 AS final_col,
    final_col + 1 AS final_col2
FROM ttttttt
GROUP BY col3
```


The problem is that before the change to use clone the new node would not be visited (as the previous one was marked as `finished_asts`) but now the clone is not there, so the replace happens again and you end up with `argMax(argMax...`

**Comment by Algunenano** [comment] 2023-02-22 11:07
A PR with a tentative fix at https://github.com/ClickHouse/ClickHouse/pull/46609

It'd be nice to have it reviewed and, once clear, backported so stable / LTS releases where this type of queries used to work without issues can do the minor/major upgrades. We've seen multiple instances of this in production when validating upgrades, thus forcing us to adapt the queries manually or block the upgrades.

**Closed** 2023-02-25 23:03 UTC
Labels: st-wontfix, backward compatibility, unexpected behaviour
