### ISSUE TITLE
HDFS table engine triggers crash

### ISSUE THREAD

**Issue by likang-github** [ClickHouse/ClickHouse#22460] opened 2021-04-01 16:16 UTC
![image](https://user-images.githubusercontent.com/43307989/113323506-9f089400-9348-11eb-9460-3325d48d9f9e.png)

**Comment by filimonov** [comment] 2021-04-01 21:55
Normally that should not happen. Core file is created when the process segfault. 

It is alway a sign of some bug. 

To invistigate it we need clickhouse version and fragment of clickhouse logs (see /var/log/clickhouse-server/clickhouse-server.log) - lines around '####'.

Optionally the coredump files can also be used to debug the issue.

**Comment by likang-github** [comment] 2021-04-02 01:50
how can i  specify the core.* file generation path through the config.xml

**Comment by alexey-milovidov** [comment] 2021-04-02 03:46
Do you use the official ClickHouse release binaries?

**Comment by likang-github** [comment] 2021-04-02 04:39
yes version 20.12.3.3

**Comment by filimonov** [comment] 2021-04-02 05:51
Please do

```
grep '####' -C50 /var/log/clickhouse-server/clickhouse-server.log
```

**Comment by likang-github** [comment] 2021-04-02 06:07
![image](https://user-images.githubusercontent.com/43307989/113386373-b5e8ce00-93bc-11eb-94e0-da40db6e862d.png)

**Comment by likang-github** [comment] 2021-04-02 06:22
[users.txt](https://github.com/ClickHouse/ClickHouse/files/6248005/users.txt)
[config.txt](https://github.com/ClickHouse/ClickHouse/files/6248006/config.txt)

**Comment by likang-github** [comment] 2021-04-02 06:24
![image](https://user-images.githubusercontent.com/43307989/113387563-1ed14580-93bf-11eb-8ff8-59d059157fb6.png)

**Comment by likang-github** [comment] 2021-04-02 06:41
[clickhouse-server.zip](https://github.com/ClickHouse/ClickHouse/files/6248084/clickhouse-server.zip)

**Comment by alexey-milovidov** [comment] 2021-04-02 06:52
It's related to HDFS, the issue is duplicate of:

#22115
#13406

**Comment by likang-github** [comment] 2021-04-02 07:27
change table engine？ use  MergeTree？

**Comment by alexey-milovidov** [comment] 2021-04-19 23:38
@likang-github 

@kssenii are trying to reproduce this issue with HDFS Docker image but is not being able to reproduce it yet.
Any help with reproducing example is appreciated.

**Comment by alexey-milovidov** [comment] 2021-04-28 04:20
Duplicate #13406.

**Closed by alexey-milovidov** 2021-04-28 04:20 UTC
Labels: comp-hdfs, crash, question, st-need-info, v20.12-affected
