### ISSUE TITLE
Issue inserting data from compressed Parquet file into ClickHouse table.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#42971] opened 2022-11-04 17:46 UTC
**Describe the unexpected behaviour**
I have a Parquet file generated using pyarrow and compressed with gzip. I can read this file using pyarrow, but when I try to insert from the file into a ClickHouse table, I get the following exception `Error on processing query: Code: 117. DB::Exception: Not a Parquet file: While executing ParquetBlockInputFormat: While executing File: data for INSERT was parsed from file. (INCORRECT_DATA) (version 22.8.6.71 (official build))` 

**How to reproduce**
version: 22.8.6.71
`CREATE TABLE x (uint8 UInt8) ENGINE=Memory`
`INSERT INTO table x FROM INFILE '/var/lib/clickhouse/user_files/comp_test.parquet.gzip' COMPRESSION 'gzip' FORMAT Parquet`

I included the file inside the zip because github does not support parquet files.
[comp_test.parquet.gzip.zip](https://github.com/ClickHouse/ClickHouse/files/9940871/comp_test.parquet.gzip.zip)

**Comment by Avogar** [comment] 2022-11-04 17:58
Thank you for the report! I will fix it

**Comment by Avogar** [comment] 2022-11-15 15:56
Hm, looks like this is not a ClickHouse problem:
```py
>>> import zlib
>>> import pyarrow as pa
>>> import pyarrow.parquet as pq
>>> table = pa.table({'number' : [1,2,3]})
>>> pq.write_table(table, 'data.parquet.gzip', compression='gzip')
>>> zlib.decompress(open('data.parquet.gzip', 'rb').read(), 16+zlib.MAX_WBITS)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
zlib.error: Error -3 while decompressing data: incorrect header check
```
If we create similar file using ClickHouse, not pyarrow:
```
$ ch-client -q "insert into function file(ch_data.parquet.gzip) select * from numbers(3) format Parquet"
```
```py
>>> zlib.decompress(open('ch_data.parquet.gzip', 'rb').read(), 16+zlib.MAX_WBITS)
b'PAR1\x15\x04\x150\x15,L\x15\x06\x15\x04\x12\x00\x00\x18\x00\x00\r\x01<\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x15\x00\x15\x08\x15\x0c,\x15\x06\x15\x04\x15\x06\x15\x06\x1c6\x00(\x08\x02\x00\x00\x00\x00\x00\x00\x00\x18\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x0c\x02\x03$\x00&\xae\x01\x1c\x15\x04\x195\x04\x00\x06\x19\x18\x06number\x15\x02\x16\x06\x16\xa6\x01\x16\xa6\x01&P&\x08\x1c6\x00(\x08\x02\x00\x00\x00\x00\x00\x00\x00\x18\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x19,\x15\x04\x15\x04\x15\x02\x00\x15\x00\x15\x04\x15\x02\x00\x00\x00\x15\x02\x19,5\x00\x18\x06schema\x15\x02\x00\x15\x04%\x00\x18\x06number%\x1cL\xac\x13@\x12\x00\x00\x00\x16\x06\x19\x1c\x19\x1c&\xae\x01\x1c\x15\x04\x195\x04\x00\x06\x19\x18\x06number\x15\x02\x16\x06\x16\xa6\x01\x16\xa6\x01&P&\x08\x1c6\x00(\x08\x02\x00\x00\x00\x00\x00\x00\x00\x18\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x19,\x15\x04\x15\x04\x15\x02\x00\x15\x00\x15\x04\x15\x02\x00\x00\x00\x16\xa6\x01\x16\x06&\x08\x16\xa6\x01\x14\x00\x00("parquet-cpp version 1.5.1-SNAPSHOT\x19\x1c\x1c\x00\x00\x00\xb0\x00\x00\x00PAR1
```

Seems like the problem is either in zlib or in pyarrow.

**Comment by Avogar** [comment] 2022-11-15 16:08
```
$ gunzip comp_test.parquet.gzip --suffix='gzip'

gzip: comp_test.parquet.gzip: not in gzip format
```

**Comment by Avogar** [comment] 2022-11-15 16:08
I cannot decompress file generated using pyarrow...

**Comment by MyroTk** [comment] 2022-11-15 16:16
How odd. I am able to read the file back using both pyarrow and parquet-tools.

```
parquet-tools inspect comp_test.parquet.gzip 

############ file meta data ############
created_by: parquet-cpp-arrow version 9.0.0
num_columns: 1
num_rows: 3
num_row_groups: 1
format_version: 2.6
serialized_size: 355


############ Columns ############
uint8

############ Column(uint8) ############
name: uint8
path: uint8
max_definition_level: 1
max_repetition_level: 0
physical_type: INT32
logical_type: Int(bitWidth=8, isSigned=false)
converted_type (legacy): UINT_8
compression: GZIP (space_saved: -54%)
```

**Comment by Avogar** [comment] 2022-11-15 16:27
Or without renaming, just use `none` compression method:
```
$ clickhouse-local -q "select * from file(comp_test.parquet.gzip, auto, auto, 'none')"
1
2
3
```

**Comment by Avogar** [comment] 2022-11-15 16:27
It will be decompressed inside Parquet file reading

**Comment by Avogar** [comment] 2022-11-15 16:40
@MyroTk I guess there is no issue here, can we close it?

**Comment by MyroTk** [comment] 2022-11-15 16:41
Yes looks like it. Thank you.

**Closed** 2022-11-15 16:42 UTC
Labels: unexpected behaviour
