### ISSUE TITLE
build clickhouse error

### ISSUE THREAD

**Issue by nstang01** [ClickHouse/ClickHouse#22162] opened 2021-03-26 13:43 UTC
(you don't have to strictly follow this form)

**Describe the bug**
Get this error,when i build clickhouse on wsl:
../utils/memcpy-bench/memcpy-bench.cpp:303:6: error: ‘always_inline’ function might not be inlinable [-Werror=attributes]
  303 | void memcpy_my_medium_sse(uint8_t * __restrict & dst, const uint8_t * __restrict & src, size_t & size)
      |      ^~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
[41/2159] Building CXX object base/daemon/CMakeFiles/daemon.dir/BaseDaemon.cpp.o
ninja: build stopped: subcommand failed.

**Does it reproduce on recent release?**
yes
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**
* Which ClickHouse server version to use
the latest
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by filimonov** [comment] 2021-03-29 06:41
1) We need more info to debug build issues: https://github.com/ClickHouse/ClickHouse/blob/master/.github/ISSUE_TEMPLATE/50_build-issue.md
2) try building single target `ninja clickhouse`

**Comment by filimonov** [comment] 2021-04-12 11:59
No information. Most probably a duplicate of #22862

**Closed by filimonov** 2021-04-12 11:59 UTC
Labels: alternative build, build, comp-wsl
