### ISSUE TITLE
TTL does not delete the data

### ISSUE THREAD

**Issue by johnatannvmd** [ClickHouse/ClickHouse#10004] opened 2020-04-02 08:03 UTC
ClickHouse server version 20.3.4 revision 54433.

May be connected with #7435

Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz x10(20HT)
MEM: 250GB
`hot` storage placed on nvme

Table:
```SQL
create table internal.table2
(
    ts UInt64,
    field1 LowCardinality(String),
    `field2.key` Array(LowCardinality(String)),
    `field2.value` Array(String),
    `field3.key` Array(LowCardinality(String)),
    `field3.value` Array(Float64)
)
    engine = ReplicatedMergeTree('/clickhouse/internal/tables/{shard}/table2', '{replica}')
    PARTITION BY toStartOfFifteenMinutes(toDateTime(ts))
    ORDER BY (field1, ts)
    TTL toDateTime(ts) + toIntervalMinute(30)
    SETTINGS storage_policy = 'hot', merge_with_ttl_timeout = 900, index_granularity = 8192;
```

Periodically I run query to ensure data are gone:
```SQL
SELECT
       (SELECT toDateTime(min(ts)) FROM internal.table2) as first_point,
       (SELECT toDateTime(max(ts)) FROM internal.table2) as last_point,
       dateDiff('minute', first_point, last_point) as diff_in_mins
```
And `diff_in_mins` does not retain.

After I run `ALTER TABLE internal.table2 MATERIALIZE TTL;` `diff_in_mins` became 30 + some time in partition. And data from disk were deleted.

Modified settings:
```XML
<yandex>
    <uncompressed_cache_size>8589934592</uncompressed_cache_size>
    <mark_cache_size>5368709120</mark_cache_size>
    <max_partitions_per_insert_block>100</max_partitions_per_insert_block>
    <max_connections>4048</max_connections>
    <keep_alive_timeout>3</keep_alive_timeout>
    <send_progress_in_http_headers>1</send_progress_in_http_headers>
    <use_uncompressed_cache>1</use_uncompressed_cache>
    <replace_running_query>1</replace_running_query>
    <insert_quorum>1</insert_quorum>
    <max_block_size>131072</max_block_size>

    <merge_tree>
        <merge_with_ttl_timeout>600</merge_with_ttl_timeout>
        <old_parts_lifetime>300</old_parts_lifetime>
        <merge_max_block_size>16384</merge_max_block_size>
        <temporary_directories_lifetime>3600</temporary_directories_lifetime>
        <max_part_removal_threads>20</max_part_removal_threads>
    </merge_tree>
</yandex>
```

**Comment by alexey-milovidov** [comment] 2020-08-31 11:35
@azat is it fixed by #12982 ?

**Comment by azat** [comment] 2020-08-31 19:35
@alexey-milovidov #12982 indeed looks related, but it is hard to say (since there is no reproducer)
@johnatannvmd can you verify (preferably on some staging) that #12982 helps you? (it has been backported to 20.3, in particular v20.3.17.173-lts and v20.3.16.165-lts)

**Comment by azat** [comment] 2020-11-06 18:24
@alexey-milovidov I guess can be closed? (no details, no interest and there were some changes anyway since then)

**Closed** 2020-11-06 22:40 UTC
Labels: comp-ttl, unexpected behaviour
