### ISSUE TITLE
`MaterializedPostgreSQL` table engine does not support schema specification

### ISSUE THREAD

**Issue by vialorn** [ClickHouse/ClickHouse#29324] opened 2021-09-24 10:31 UTC
I need to use `MaterializedPostgreSQL` table engine for a source PostgreSQL table in a non-default DB schema.
I tried both 6th agrument (as to `postgresql` table function) and fully-qualified table name, but all in vain.

ClickHouse version is `21.9.3`.

```sql
CREATE TABLE some_ch_db.some_replicated_table_name
(
    `element_id` Int64,
    `tag_ids` Array(Int64)
)
ENGINE = MaterializedPostgreSQL('some_host:5432', 'some_source_db_name', 'some_source_table_name', 'connect_username', 'connect_password', 'some_source_schema_name')
PRIMARY KEY element_id
```
```
Received exception from server (version 21.9.3):
Code: 42. DB::Exception: Received from ch1:9000. DB::Exception: Storage MaterializedPostgreSQL requires 5 parameters: PostgreSQL('host:port', 'database', 'table', 'username', 'password'. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)
```

```sql
CREATE TABLE some_ch_db.some_replicated_table_name
(
    `element_id` Int64,
    `tag_ids` Array(Int64)
)
ENGINE = MaterializedPostgreSQL('some_host:5432', 'some_source_db_name', 'some_source_schema_name.some_source_table_name', 'connect_username', 'connect_password')
PRIMARY KEY element_id
```
```
Received exception from server (version 21.9.3):
Code: 1001. DB::Exception: Received from ch1:9000. DB::Exception: pqxx::syntax_error: ERROR:  syntax error at or near "."
LINE 1: CREATE PUBLICATION some_source_db_name_some_source_schema_name.some_source_table_name_ch_publicat...
                                       ^
. (STD_EXCEPTION)
```
@kssenii 

Related to:
* #27166  
  #27198
* #23958  
  #23980
* #21701  
  #21711

**Comment by kssenii** [comment] 2021-09-24 10:45
It is implemented here https://github.com/ClickHouse/ClickHouse/pull/28933, but not yet merged. I come back to this pr today or tomorrow and will finally merge it.

**Closed** 2021-12-01 06:37 UTC
Labels: unfinished code

**Comment by italodamato** [comment] 2024-02-13 16:34
flagging that https://github.com/ClickHouse/ClickHouse/pull/28933 didn't solve this as only the DB type supports a custom schema as far as I understand.

**Comment by kssenii** [comment] 2024-02-13 16:37
@italodamato 
Should be supported for table engine as well. If not - please create a separate issue with reproducing example and the error.

**Comment by italodamato** [comment] 2024-02-13 17:27
@kssenii There's no documentation on how to use here https://clickhouse.com/docs/en/engines/table-engines/integrations/materialized-postgresql. I've tried to set `materialized_postgresql_schema = 'MY_SCHEMA'` but it can't find the table since it's not actually doing anything: `Query 1 ERROR at Line 1: : DB::Exception: pqxx::undefined_table: ERROR:  relation "MY_TABLE" does not exist`.

Opened https://github.com/ClickHouse/ClickHouse/issues/59950
