### ISSUE TITLE
DB::Exception: Serialization is not implemented for data type Nothing when using IN operator with NULL as left operand

### ISSUE THREAD

**Issue by YiuRULE** [ClickHouse/ClickHouse#23432] opened 2021-04-21 11:26 UTC
**Describe the bug**

The bug happened on the optimizer with a nullable column, who optimized a series of multiples `OR` operation similar at `lowerUTF8(column) = 'a' OR lowerUTF8(column) = 'b' OR lowerUTF8(column) = 'c'` and translated to a filter similar at `lowerUTF8(NULL AS column) IN ('a', 'b', 'c')`

**Does it reproduce on recent release?**
Tested on the latest 20.11, 20.12, 21.1, 21.2 and 21.3

**How to reproduce**
`SELECT NULL IN ('othername', 'somename', 'someothername')`

**Expected behavior**
If the column is equal to `NULL`, it should returns the equivalent of `NULL = 'a' OR NULL = 'b' OR NULL = 'c'`

**Error message and/or stacktrace**
```
clickhouse1a_1  | 2021.04.21 11:26:25.854085 [ 146 ] {39b21803-9b14-4670-8093-dcea80ef90cf} <Error> executeQuery: Code: 48, e.displayText() = DB::Exception: Serialization is not implemented for data type Nothing: while converting 'othername' to Nothing: While processing NULL IN ('othername', 'somename', 'someothername') (version 20.12.8.5 (official build)) (from 10.201.0.1:58540) (in query: SELECT NULL IN ('othername', 'somename', 'someothername')), Stack trace (when copying this message, always include the lines below):
clickhouse1a_1  | 
clickhouse1a_1  | 0. DB::IDataTypeDummy::throwNoSerialization() const @ 0xd8abbf8 in /usr/bin/clickhouse
clickhouse1a_1  | 1. ? @ 0xd8abb46 in /usr/bin/clickhouse
clickhouse1a_1  | 2. ? @ 0xe016a01 in /usr/bin/clickhouse
clickhouse1a_1  | 3. DB::convertFieldToType(DB::Field const&, DB::IDataType const&, DB::IDataType const*) @ 0xe015fc4 in /usr/bin/clickhouse
clickhouse1a_1  | 4. DB::createBlockForSet(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, DB::Context const&) @ 0xdc0e878 in /usr/bin/clickhouse
clickhouse1a_1  | 5. DB::makeExplicitSet(DB::ASTFunction const*, DB::ActionsDAG const&, bool, DB::Context const&, DB::SizeLimits const&, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >&) @ 0xdc12ead in /usr/bin/clickhouse
clickhouse1a_1  | 6. DB::ActionsMatcher::makeSet(DB::ASTFunction const&, DB::ActionsMatcher::Data&, bool) @ 0xdc1d900 in /usr/bin/clickhouse
clickhouse1a_1  | 7. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0xdc15b03 in /usr/bin/clickhouse
clickhouse1a_1  | 8. DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0xdc1b10e in /usr/bin/clickhouse
clickhouse1a_1  | 9. DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) @ 0xdbf4fa7 in /usr/bin/clickhouse
clickhouse1a_1  | 10. DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0xdbf4dbc in /usr/bin/clickhouse
clickhouse1a_1  | 11. DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0xdbfc8a6 in /usr/bin/clickhouse
clickhouse1a_1  | 12. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterInfo> const&, DB::Block const&) @ 0xdc01a43 in /usr/bin/clickhouse
clickhouse1a_1  | 13. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0xdba931c in /usr/bin/clickhouse
clickhouse1a_1  | 14. ? @ 0xdba3eda in /usr/bin/clickhouse
clickhouse1a_1  | 15. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xdb9ee72 in /usr/bin/clickhouse
clickhouse1a_1  | 16. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xdb9d74d in /usr/bin/clickhouse
clickhouse1a_1  | 17. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xdeb4fb3 in /usr/bin/clickhouse
clickhouse1a_1  | 18. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0xdb58277 in /usr/bin/clickhouse
clickhouse1a_1  | 19. ? @ 0xe0210a2 in /usr/bin/clickhouse
clickhouse1a_1  | 20. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xe01fe3d in /usr/bin/clickhouse
clickhouse1a_1  | 21. DB::TCPHandler::runImpl() @ 0xe6fa8f6 in /usr/bin/clickhouse
clickhouse1a_1  | 22. DB::TCPHandler::run() @ 0xe706df7 in /usr/bin/clickhouse
clickhouse1a_1  | 23. Poco::Net::TCPServerConnection::start() @ 0x10eb1e6f in /usr/bin/clickhouse
clickhouse1a_1  | 24. Poco::Net::TCPServerDispatcher::run() @ 0x10eb3881 in /usr/bin/clickhouse
clickhouse1a_1  | 25. Poco::PooledThread::run() @ 0x10fe0e59 in /usr/bin/clickhouse
clickhouse1a_1  | 26. Poco::ThreadImpl::runnableEntry(void*) @ 0x10fdcdea in /usr/bin/clickhouse
clickhouse1a_1  | 27. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
clickhouse1a_1  | 28. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
clickhouse1a_1  | 
clickhouse1a_1  | 2021.04.21 11:26:25.854718 [ 146 ] {39b21803-9b14-4670-8093-dcea80ef90cf} <Error> TCPHandler: Code: 48, e.displayText() = DB::Exception: Serialization is not implemented for data type Nothing: while converting 'othername' to Nothing: While processing NULL IN ('othername', 'somename', 'someothername'), Stack trace:
clickhouse1a_1  | 
clickhouse1a_1  | 0. DB::IDataTypeDummy::throwNoSerialization() const @ 0xd8abbf8 in /usr/bin/clickhouse
clickhouse1a_1  | 1. ? @ 0xd8abb46 in /usr/bin/clickhouse
clickhouse1a_1  | 2. ? @ 0xe016a01 in /usr/bin/clickhouse
clickhouse1a_1  | 3. DB::convertFieldToType(DB::Field const&, DB::IDataType const&, DB::IDataType const*) @ 0xe015fc4 in /usr/bin/clickhouse
clickhouse1a_1  | 4. DB::createBlockForSet(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::shared_ptr<DB::IDataType const>, std::__1::allocator<std::__1::shared_ptr<DB::IDataType const> > > const&, DB::Context const&) @ 0xdc0e878 in /usr/bin/clickhouse
clickhouse1a_1  | 5. DB::makeExplicitSet(DB::ASTFunction const*, DB::ActionsDAG const&, bool, DB::Context const&, DB::SizeLimits const&, std::__1::unordered_map<DB::PreparedSetKey, std::__1::shared_ptr<DB::Set>, DB::PreparedSetKey::Hash, std::__1::equal_to<DB::PreparedSetKey>, std::__1::allocator<std::__1::pair<DB::PreparedSetKey const, std::__1::shared_ptr<DB::Set> > > >&) @ 0xdc12ead in /usr/bin/clickhouse
clickhouse1a_1  | 6. DB::ActionsMatcher::makeSet(DB::ASTFunction const&, DB::ActionsMatcher::Data&, bool) @ 0xdc1d900 in /usr/bin/clickhouse
clickhouse1a_1  | 7. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0xdc15b03 in /usr/bin/clickhouse
clickhouse1a_1  | 8. DB::ActionsMatcher::visit(DB::ASTExpressionList&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0xdc1b10e in /usr/bin/clickhouse
clickhouse1a_1  | 9. DB::InDepthNodeVisitor<DB::ActionsMatcher, true, std::__1::shared_ptr<DB::IAST> const>::visit(std::__1::shared_ptr<DB::IAST> const&) @ 0xdbf4fa7 in /usr/bin/clickhouse
clickhouse1a_1  | 10. DB::ExpressionAnalyzer::getRootActions(std::__1::shared_ptr<DB::IAST> const&, bool, std::__1::shared_ptr<DB::ActionsDAG>&, bool) @ 0xdbf4dbc in /usr/bin/clickhouse
clickhouse1a_1  | 11. DB::SelectQueryExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) @ 0xdbfc8a6 in /usr/bin/clickhouse
clickhouse1a_1  | 12. DB::ExpressionAnalysisResult::ExpressionAnalysisResult(DB::SelectQueryExpressionAnalyzer&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool, bool, std::__1::shared_ptr<DB::FilterInfo> const&, DB::Block const&) @ 0xdc01a43 in /usr/bin/clickhouse
clickhouse1a_1  | 13. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0xdba931c in /usr/bin/clickhouse
clickhouse1a_1  | 14. ? @ 0xdba3eda in /usr/bin/clickhouse
clickhouse1a_1  | 15. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xdb9ee72 in /usr/bin/clickhouse
clickhouse1a_1  | 16. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xdb9d74d in /usr/bin/clickhouse
clickhouse1a_1  | 17. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xdeb4fb3 in /usr/bin/clickhouse
clickhouse1a_1  | 18. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0xdb58277 in /usr/bin/clickhouse
clickhouse1a_1  | 19. ? @ 0xe0210a2 in /usr/bin/clickhouse
clickhouse1a_1  | 20. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xe01fe3d in /usr/bin/clickhouse
clickhouse1a_1  | 21. DB::TCPHandler::runImpl() @ 0xe6fa8f6 in /usr/bin/clickhouse
clickhouse1a_1  | 22. DB::TCPHandler::run() @ 0xe706df7 in /usr/bin/clickhouse
clickhouse1a_1  | 23. Poco::Net::TCPServerConnection::start() @ 0x10eb1e6f in /usr/bin/clickhouse
clickhouse1a_1  | 24. Poco::Net::TCPServerDispatcher::run() @ 0x10eb3881 in /usr/bin/clickhouse
clickhouse1a_1  | 25. Poco::PooledThread::run() @ 0x10fe0e59 in /usr/bin/clickhouse
clickhouse1a_1  | 26. Poco::ThreadImpl::runnableEntry(void*) @ 0x10fdcdea in /usr/bin/clickhouse
clickhouse1a_1  | 27. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
clickhouse1a_1  | 28. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

**Comment by tavplubix** [comment] 2021-04-21 12:15
Duplicate of #23353, fixed in #22063, the fix is backported to 21.3.8 (not released yet)

**Closed by tavplubix** 2021-04-21 12:15 UTC
Labels: bug
