### ISSUE TITLE
New errors while reading iceberg files

### ISSUE THREAD

**Issue by eavetisyan** [ClickHouse/ClickHouse#49877] opened 2023-05-15 09:58 UTC
All the queries are run on **CH 23.4.2.11**. We've tried different tables with different field types, and the results are the same

We're trying to select data from **iceberg** files with **parquet** format placed on **S3**, and all our efforts are unsuccessful. Moreover, according to different conditions we have different errors:

**1. For iceberg v2**
```
SELECT *
FROM iceberg(
  '*******URI********',
  '*******AWS_KEY*******',
  '*******AWS_SECRET_KEY*******',
  'parquet',
  'active_zone_name String'
)
LIMIT 100
```

The error is:
`SQL Error [1002] [07000]: std::exception. Code: 1001, type: std::out_of_range, e.what() = vector (version 23.4.2.11 (official build))`

**2. For iceberg v1 with format = parquet (the first letter is in lowercase):**
```
SELECT *
FROM iceberg(
  '*******URI********',
  '*******AWS_KEY*******',
  '*******AWS_SECRET_KEY*******',
  'parquet',
  'active_zone_name String'
)
LIMIT 100
```

The error is UNKNOWN_FORMAT:
`SQL Error [73] [07000]: Code: 73. DB::Exception: Unknown format parquet. (UNKNOWN_FORMAT) (version 23.4.2.11 (official build))`

**3. For iceberg v1 with format = Parquet**
```
SELECT *
FROM iceberg(
  '*******URI********',
  '*******AWS_KEY*******',
  '*******AWS_SECRET_KEY*******',
  'Parquet',
  'active_zone_name String'
)
LIMIT 100
```

The error is 404:
`SQL Error [499] [07000]: Code: 499. DB::Exception: Failed to get object info: No response body.. HTTP response code: 404. (S3_ERROR) (version 23.4.2.11 (official build))`

Using the same S3 bucket to select data from **standard parquet** files (`SELECT * FROM S3(...)`) works **absolutely correct**

**Comment by alifirat** [comment] 2023-05-31 08:30
Hey, you have to wait this PR to be backport to the 23.4 #50232.

**Comment by tavplubix** [comment] 2023-05-31 09:42
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/49958

**Closed by tavplubix** 2023-05-31 09:42 UTC
Labels: potential bug
