### ISSUE TITLE
Exception about attempting to attach MV to system.query_log failed

### ISSUE THREAD

**Issue by dqminh** [ClickHouse/ClickHouse#3622] opened 2018-11-20 16:53 UTC
We have an MV that reads from `system.query_log` like this:

```
CREATE MATERIALIZED VIEW IF NOT EXISTS system.clickhouse_query_stats_by_user ENGINE = SummingMergeTree(dummy_date, (type, user), 8192) POPULATE AS
SELECT
    toDate('1970-01-01') AS dummy_date,
    type,
    initial_user AS user,
    count(initial_user) AS count,
    sum(query_duration_ms) AS query_duration_ms,
    sum(read_rows) AS read_rows,
    sum(read_bytes) AS read_bytes
FROM system.query_log
GROUP BY
    type,
    user;
```

Since upgrade to 18.14.11, we are seeing exceptions that look like:

```
[ 11449 ] {} <Error> void DB::SystemLog<LogElement>::flush(bool) [with LogElement = DB::QueryLogElement]: Code: 49, e.displayText() = DB::Exception: Attempt to attach to nullptr thread group, e.what() = DB::Exception, Stack trace:
0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x92214f6]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x334437f]
2. /usr/bin/clickhouse-server(DB::ThreadStatus::attachQuery(std::shared_ptr<DB::ThreadGroupStatus> const&, bool)+0x2f6) [0x70aaa66]
3. /usr/bin/clickhouse-server(DB::CurrentThread::attachToIfDetached(std::shared_ptr<DB::ThreadGroupStatus> const&)+0x23) [0x70aac63]
4. /usr/bin/clickhouse-server() [0x7395b9e]
5. /usr/bin/clickhouse-server(ThreadPool::worker()+0x12d) [0x9328c9d]
6. /usr/bin/clickhouse-server() [0x9a8f4af]
7. /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7fb4270ba494]
8. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fb4266ecac
```

This looks concerning, does it mean our MV is actually not being applied correctly ?

cc @vavrusa @bocharov @bobrik

**Comment by alexey-milovidov** [comment] 2018-11-21 19:52
Yes, it means that materialized view is not working correctly.
Possible reason is that thread group is not initialized when processing insert into query_log.

**Comment by den-crane** [comment] 2020-10-14 22:40
I could not reproduce the issue with 20.11.1.4897. 
Closing for now.

**Closed by den-crane** 2020-10-14 22:40 UTC
Labels: bug, comp-matview
