### ISSUE TITLE
complex_key_range_hashed

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#26037] opened 2021-07-06 17:58 UTC
range_hashed dictionary supports only UInt64 as a key right now.
I need more complex key  i.e (banner_id UInt64, event_state String)

**Comment by alexey-milovidov** [comment] 2021-07-06 20:12
Ok.

Workaround: hash both keys into single UInt64 key if the number of keys is small (e.g millions) and you can tolerate 1 / 2^64 potential collision probability for every key.

**Comment by vpanfilov** [comment] 2021-07-07 08:17
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/22029

**Closed** 2021-07-07 12:30 UTC
Labels: duplicate, feature
