### ISSUE TITLE
Illegal column in multiIf

### ISSUE THREAD

**Issue by blaird1923** [ClickHouse/ClickHouse#41867] opened 2022-09-28 02:29 UTC
Here is a behavior change between 22.3.2 and 22.8.5.
In 22.8 the query always fails on the 8th row.
The data of the 8th row may be identical to the 7th row.
CREATE TABLE  brian_repro3 (
    logflag Int32,
    lowcard_39 LowCardinality(String)
)
ENGINE = AggregatingMergeTree()
ORDER BY (lowcard_39);

clickhouse-client -q "INSERT INTO siem.brian_repro3 FORMAT JSONEachRow" < brian_repro3

bash# head brian_repro3
{"logflag":1,"lowcard_39":""}
{"logflag":1,"lowcard_39":""}
{"logflag":1,"lowcard_39":""}
{"logflag":1,"lowcard_39":"www.fortiguard.com"}
{"logflag":1,"lowcard_39":"www.fortiguard.com"}
{"logflag":1,"lowcard_39":"www.fortiguard.com"}
{"logflag":1,"lowcard_39":"www.fortiguard.com"}
{"logflag":1,"lowcard_39":"www.fortiguard.com"}
{"logflag":1,"lowcard_39":"www.fortiguard.com"}
{"logflag":1,"lowcard_39":"www.fortiguard.com"}

----- Old Clickhouse version:
FAZVM64-KVM :) select count() from brian_repro3

SELECT count()
FROM brian_repro3

Query id: 887ebc2c-d2ed-4574-8021-3e830a2697d6

┌─count()─┐
│      29 │
└─────────┘

1 rows in set. Elapsed: 0.002 sec. 

FAZVM64-KVM :) select logflag, lowcard_39 AS HOST,
               multiIf(
                   bitTest(logflag, 64) > 0, HOST,
                   is_ip(HOST), HOST,
                   NOT ((position(HOST, '.') > 0) AND
                        (double_position(reverse(HOST), '.') > 0)), HOST,
                   reverse(substring(reverse(HOST), 1, double_position(reverse(HOST), '.') - 1))
               ) AS domain
               from brian_repro3 limit 7
               

SELECT
    logflag,
    lowcard_39 AS HOST,
    multiIf(bitTest(logflag, 64) > 0, HOST, is_ip(HOST), HOST, NOT ((position(HOST, '.') > 0) AND (double_position(reverse(HOST), '.') > 0)), HOST, reverse(substring(reverse(HOST), 1, double_position(reverse(HOST), '.') - 1))) AS domain
FROM brian_repro3
LIMIT 7

Query id: f710ea96-06d8-485c-913f-569763210791

┌─logflag─┬─HOST────────────────┬─domain──────────────┐
│       1 │                     │                     │
│       1 │ 172.17.45.133:5601  │ 172.17.45.133:5601  │
│       1 │ a.clarity.ms        │ a.clarity.ms        │
│       1 │ ap.lijit.com        │ ap.lijit.com        │
│       1 │ apex.go.sonobi.com  │ apex.go.sonobi.com  │
│       1 │ apheleia-a.wbx2.com │ apheleia-a.wbx2.com │
│       1 │ c2shb.ssp.yahoo.com │ c2shb.ssp.yahoo.com │
└─────────┴─────────────────────┴─────────────────────┘

7 rows in set. Elapsed: 0.004 sec. 

FAZVM64-KVM :) select logflag, lowcard_39 AS HOST,
               multiIf(
                   bitTest(logflag, 64) > 0, HOST,
                   is_ip(HOST), HOST,
                   NOT ((position(HOST, '.') > 0) AND
                        (double_position(reverse(HOST), '.') > 0)), HOST,
                   reverse(substring(reverse(HOST), 1, double_position(reverse(HOST), '.') - 1))
               ) AS domain
               from brian_repro3 limit 8

SELECT
    logflag,
    lowcard_39 AS HOST,
    multiIf(bitTest(logflag, 64) > 0, HOST, is_ip(HOST), HOST, NOT ((position(HOST, '.') > 0) AND (double_position(reverse(HOST), '.') > 0)), HOST, reverse(substring(reverse(HOST), 1, double_position(reverse(HOST), '.') - 1))) AS domain
FROM brian_repro3
LIMIT 8

Query id: fa8f24ea-aeed-427b-9673-44a7d6065dcf

┌─logflag─┬─HOST───────────────────────┬─domain─────────────┐
│       1 │                            │                    │
│       1 │ 172.17.45.133:5601         │ 172.17.45.133:5601 │
│       1 │ a.clarity.ms               │ clarity.ms         │
│       1 │ ap.lijit.com               │ lijit.com          │
│       1 │ apex.go.sonobi.com         │ sonobi.com         │
│       1 │ apheleia-a.wbx2.com        │ wbx2.com           │
│       1 │ c2shb.ssp.yahoo.com        │ yahoo.com          │
│       1 │ collector.brandmetrics.com │ brandmetrics.com   │
└─────────┴────────────────────────────┴────────────────────┘

8 rows in set. Elapsed: 0.007 sec. 

---New Clickhouse version:
FAZ3000F-102 :) select logflag, lowcard_39 AS HOST,
                multiIf(
                    bitTest(logflag, 64) > 0, HOST,
                    is_ip(HOST), HOST,
                    NOT ((position(HOST, '.') > 0) AND
                         (double_position(reverse(HOST), '.') > 0)), HOST,
                    reverse(substring(reverse(HOST), 1, double_position(reverse(HOST), '.') - 1))
                ) AS domain
                from brian_repro3 limit 7

SELECT
    logflag,
    lowcard_39 AS HOST,
    multiIf(bitTest(logflag, 64) > 0, HOST, is_ip(HOST), HOST, NOT ((position(HOST, '.') > 0) AND (double_position(reverse(HOST), '.') > 0)), HOST, reverse(substring(reverse(HOST), 1, double_position(reverse(HOST), '.') - 1))) AS domain
FROM brian_repro3
LIMIT 7

Query id: 1c8f1abc-cc4a-457e-bb58-f051776c66e3

┌─logflag─┬─HOST────────────────┬─domain──────────────┐
│       1 │                     │                     │
│       1 │ 172.17.45.133:5601  │ 172.17.45.133:5601  │
│       1 │ a.clarity.ms        │ a.clarity.ms        │
│       1 │ ap.lijit.com        │ ap.lijit.com        │
│       1 │ apex.go.sonobi.com  │ apex.go.sonobi.com  │
│       1 │ apheleia-a.wbx2.com │ apheleia-a.wbx2.com │
│       1 │ c2shb.ssp.yahoo.com │ c2shb.ssp.yahoo.com │
└─────────┴─────────────────────┴─────────────────────┘

7 rows in set. Elapsed: 0.010 sec. 

FAZ3000F-102 :) select logflag, lowcard_39 AS HOST,
                multiIf(
                    bitTest(logflag, 64) > 0, HOST,
                    is_ip(HOST), HOST,
                    NOT ((position(HOST, '.') > 0) AND
                         (double_position(reverse(HOST), '.') > 0)), HOST,
                    reverse(substring(reverse(HOST), 1, double_position(reverse(HOST), '.') - 1))
                ) AS domain
                from brian_repro3 limit 8

SELECT
    logflag,
    lowcard_39 AS HOST,
    multiIf(bitTest(logflag, 64) > 0, HOST, is_ip(HOST), HOST, NOT ((position(HOST, '.') > 0) AND (double_position(reverse(HOST), '.') > 0)), HOST, reverse(substring(reverse(HOST), 1, double_position(reverse(HOST), '.') - 1))) AS domain
FROM brian_repro3
LIMIT 8

Query id: ee17d5de-0968-4b76-9162-e99fa03c8091

0 rows in set. Elapsed: 0.008 sec. 

Received exception from server (version 22.8.5):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Illegal column ColumnLowCardinality of first argument of function if. Must be ColumnUInt8 or ColumnConstUInt8.: while executing 'FUNCTION multiIf(greater(bitTest(logflag, 64), 0) :: 11, lowcard_39 : 1, match(lowcard_39, '^[0-9:\\.\\]\\[]*$') :: 2, lowcard_39 : 1, not(and(greater(position(lowcard_39, '.'), 0), greater(if(greater(position(reverse(lowcard_39), '.'), 0), position(reverse(lowcard_39), '.', plus(position(reverse(lowcard_39), '.'), 1)), 0), 0))) :: 3, lowcard_39 :: 1, reverse(substring(reverse(lowcard_39), 1, minus(if(greater(position(reverse(lowcard_39), '.'), 0), position(reverse(lowcard_39), '.', plus(position(reverse(lowcard_39), '.'), 1)), 0), 1))) :: 12) -> multiIf(greater(bitTest(logflag, 64), 0), lowcard_39, match(lowcard_39, '^[0-9:\\.\\]\\[]*$'), lowcard_39, not(and(greater(position(lowcard_39, '.'), 0), greater(if(greater(position(reverse(lowcard_39), '.'), 0), position(reverse(lowcard_39), '.', plus(position(reverse(lowcard_39), '.'), 1)), 0), 0))), lowcard_39, reverse(substring(reverse(lowcard_39), 1, minus(if(greater(position(reverse(lowcard_39), '.'), 0), position(reverse(lowcard_39), '.', plus(position(reverse(lowcard_39), '.'), 1)), 0), 1)))) String : 10'. (ILLEGAL_COLUMN)

**Comment by siradjev** [comment] 2022-12-26 15:41
See #43603 #44469

**Comment by den-crane** [comment] 2022-12-27 17:00
probably fixed in  https://github.com/ClickHouse/ClickHouse/issues/43603

**Comment by rschu1ze** [comment] 2023-01-02 20:42
Just tried to reproduce this locally but the repro is not self-contained, e.g. functions `is_ip` and `double_position` are missing, and I am unable to continue. Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Sorry, I need to close this issue but I hope the issue is solved for OP - the fix for #43603 should be in the upcoming 23.1 (or current master). If the issue persists, please reopen.

**Closed by rschu1ze** 2023-01-02 20:42 UTC

**Comment by blaird1923** [comment] 2023-02-06 22:30
I've re-tested the condition on version 23.1.2 with the exact same dataset and queries.
The problem was *not* reproduced.
