### ISSUE TITLE
`Could not convert string to m` exception when loading postgres dictionary

### ISSUE THREAD

**Issue by realyota** [ClickHouse/ClickHouse#48649] opened 2023-04-11 13:48 UTC
**Describe what's wrong**

I cannot create a dictionary from the PostgreSQL querysource. It is failing with the exception:

```
SYSTEM RELOAD DICTIONARY plausible_prod.domains_pg_v1

Query id: d1099815-71df-4658-8669-8a66a601ac31


0 rows in set. Elapsed: 0.009 sec.

Received exception from server (version 23.3.1):
Code: 156. DB::Exception: Received from localhost:9000. DB::Exception: Failed to load dictionary 'b9186a0b-3d7b-4890-a6ce-a7bf2fc05e3f': std::exception. Code: 1001, type: pqxx::conversion_error, e.what() = Could not convert string to m: 'DOMAIN'.,. (DICTIONARIES_WAS_NOT_LOADED)
```

**Does it reproduce on recent release?**

Yes. Tested on version `23.3.1`

**How to reproduce**

* Install any newer PostgreSQL instance on your machine
* Create a table source on the PostgreSQL side (using `psql`):
```
CREATE DATABASE test;

CREATE USER test WITH PASSWORD 'test'

\c test

SET ROLE test;

-- no data need to be inserted
CREATE TABLE test (
   id bigserial PRIMARY KEY,
   domain varchar(255),
   time timestamp DEFAULT now()
);
```

* Create a ClickHouse dictionary by querying the PostgreSQL table:
```
CREATE DICTIONARY dictionary_bug (
`id` UInt64,
`site_id` UInt64, 
`domain` String,
`partition` String
) PRIMARY KEY domain
 SOURCE( POSTGRESQL(
	   host 'localhost'
	   port 5432
	   db 'test'
	   user 'test'
	   password 'test' 
    query 'SELECT id as site_id, domain, extract(''Year'' FROM native_stats_start_at)::text || lpad(extract(''Month'' FROM native_stats_start_at)::text, 2, ''0'') as partition from sites ORDER BY native_stats_start_at'
 )
) 
LIFETIME(3600) 
LAYOUT(COMPLEX_KEY_HASHED())
```

* Reload the dictionary
```
SYSTEM RELOAD DICTIONARY dictionary_bug 
```

**Expected behavior**

This should not happen and the exception message is a bit misleading.

**Error message and/or stacktrace**

```
SYSTEM RELOAD DICTIONARY dictionary_bug

Query id: 3dfa54f0-e650-4cc1-bd7a-7c7127489479

[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.749202 [ 10863 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Debug> executeQuery: (from 127.0.0.1:35280)  SYSTEM RELOAD DICTIONARY dictionary_bug (stage: Complete)
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.749370 [ 10863 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Trace> ContextAccess (default): Access granted: SYSTEM RELOAD DICTIONARY ON *.*
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.749584 [ 10863 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Trace> ExternalDictionariesLoader: Will load the object 'b9186a0b-3d7b-4890-a6ce-a7bf2fc05e3f' in background, force = true, loading_id = 45
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.749775 [ 11185 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Trace> ExternalDictionariesLoader: Start loading object 'b9186a0b-3d7b-4890-a6ce-a7bf2fc05e3f'
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.749985 [ 11185 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Trace> PostgreSQLConnectionPool: PostgreSQL connection pool size: 16, connection wait timeout: 5000, max failover tries: 5
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.750047 [ 11185 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Trace> DictionaryFactory: Created dictionary source 'PostgreSQL: test.' for dictionary 'b9186a0b-3d7b-4890-a6ce-a7bf2fc05e3f'
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.750126 [ 11185 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Trace> PostgreSQLDictionarySource: SELECT id as site_id, domain, extract('Year' FROM native_stats_start_at)::text || lpad(extract('Month' FROM native_stats_start_at)::text, 2, '0') as partition from sites ORDER BY native_stats_start_at
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.750145 [ 11185 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Debug> PostgreSQLConnectionPool: New connection to localhost:5434
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.756324 [ 11185 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Debug> PostgreSQLConnection: New connection to localhost:5434   
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.757628 [ 11185 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Trace> ExternalDictionariesLoader: Supposed update time for unspecified object is 2023-04-11 13:50:04 (backoff, 8 errors.
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.757706 [ 11185 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Error> ExternalDictionariesLoader: Could not load external dictionary 'b9186a0b-3d7b-4890-a6ce-a7bf2fc05e3f', next update is scheduled at 2023-04-11 13:50:04: std::exception. Code: 1001, type: pqxx::conversion_error, e.what() = Could not convert string to m: 'DOMAIN'., Stack trace (when copying this message, always include the lines below):

0. pqxx::internal::integral_traits<unsigned long>::from_string(std::basic_string_view<char, std::char_traits<char>>) @ 0x1886d2b1 in /usr/bin/clickhouse       
1. DB::insertPostgreSQLValue(DB::IColumn&, std::basic_string_view<char, std::char_traits<char>>, DB::ExternalResultDescription::ValueType, std::shared_ptr<DB::IDataType const>, std::unordered_map<unsigned long, DB::PostgreSQLArrayInfo, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, DB::PostgreSQLArrayInfo>>>&, unsigned long) @ 0x12d7fcc3 in /usr/bin/clickhouse
2. DB::PostgreSQLSource<pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)0>>::generate() @ 0x8989e39 in /usr/bin/clickhouse
3. DB::ISource::tryGenerate() @ 0x14933695 in /usr/bin/clickhouse
4. DB::ISource::work() @ 0x14933206 in /usr/bin/clickhouse
5. DB::ExecutionThreadContext::executeTask() @ 0x1494ce0a in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14941e7b in /usr/bin/clickhouse
7. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x14941268 in /usr/bin/clickhouse
8. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x14951e57 in /usr/bin/clickhouse
9. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x14952013 in /usr/bin/clickhouse
10. DB::HashedDictionary<(DB::DictionaryKeyType)1, false, false>::loadData() @ 0x10b1be74 in /usr/bin/clickhouse
11. DB::HashedDictionary<(DB::DictionaryKeyType)1, false, false>::HashedDictionary(DB::StorageID const&, DB::DictionaryStructure const&, std::shared_ptr<DB::IDictionarySource>, DB::HashedDictionaryConfiguration const&, std::shared_ptr<DB::Block>) @ 0x10b1b554 in /usr/bin/clickhouse
12. ? @ 0x10d8a090 in /usr/bin/clickhouse
13. ? @ 0x10d8a7a8 in /usr/bin/clickhouse
14. DB::DictionaryFactory::create(String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, bool) const @ 0x12442b6b in /usr/bin/clickhouse
15. DB::ExternalDictionariesLoader::create(String const&, Poco::Util::AbstractConfiguration const&, String const&, String const&) const @ 0x1311fa5b in /usr/bin/clickhouse
16. DB::ExternalLoader::LoadingDispatcher::doLoading(String const&, unsigned long, bool, unsigned long, bool, std::shared_ptr<DB::ThreadGroupStatus>) @ 0x1312c653 in /usr/bin/clickhouse
17. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::ExternalLoader::LoadingDispatcher::*)(String const&, unsigned long, bool, unsigned long, bool, std::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*, String&, unsigned long&, bool&, unsigned long&, bool, std::shared_ptr<DB::ThreadGroupStatus>>(void (DB::ExternalLoader::LoadingDispatcher::*&&)(String const&, unsigned long, bool, unsigned long, bool, std::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*&&, String&, unsigned long&, bool&, unsigned long&, bool&&, std::shared_ptr<DB::ThreadGroupStatus>&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x131324d3 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe25cc73 in /usr/bin/clickhouse
19. ? @ 0xe2628e1 in /usr/bin/clickhouse
20. ? @ 0x7f09f3a69609 in ?
21. __clone @ 0x7f09f398e133 in ?
 (version 23.3.1.2823 (official build))
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.757764 [ 11185 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Trace> ExternalDictionariesLoader: Next update time for 'b9186a0b-3d7b-4890-a6ce-a7bf2fc05e3f' was set to 2023-04-11 13:50:04
[LAPTOP-ASLS2SOJ] 2023.04.11 15:48:01.758002 [ 10863 ] {3dfa54f0-e650-4cc1-bd7a-7c7127489479} <Error> executeQuery: Code: 156. DB::Exception: Failed to load dictionary 'b9186a0b-3d7b-4890-a6ce-a7bf2fc05e3f': std::exception. Code: 1001, type: pqxx::conversion_error, e.what() = Could not convert string to m: 'DOMAIN'., Stack trace (when copying this message, always include the lines below):

0. pqxx::internal::integral_traits<unsigned long>::from_string(std::basic_string_view<char, std::char_traits<char>>) @ 0x1886d2b1 in /usr/bin/clickhouse       
1. DB::insertPostgreSQLValue(DB::IColumn&, std::basic_string_view<char, std::char_traits<char>>, DB::ExternalResultDescription::ValueType, std::shared_ptr<DB::IDataType const>, std::unordered_map<unsigned long, DB::PostgreSQLArrayInfo, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, DB::PostgreSQLArrayInfo>>>&, unsigned long) @ 0x12d7fcc3 in /usr/bin/clickhouse
2. DB::PostgreSQLSource<pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)0>>::generate() @ 0x8989e39 in /usr/bin/clickhouse
3. DB::ISource::tryGenerate() @ 0x14933695 in /usr/bin/clickhouse
4. DB::ISource::work() @ 0x14933206 in /usr/bin/clickhouse
5. DB::ExecutionThreadContext::executeTask() @ 0x1494ce0a in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14941e7b in /usr/bin/clickhouse
7. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x14941268 in /usr/bin/clickhouse
8. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x14951e57 in /usr/bin/clickhouse
9. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x14952013 in /usr/bin/clickhouse
10. DB::HashedDictionary<(DB::DictionaryKeyType)1, false, false>::loadData() @ 0x10b1be74 in /usr/bin/clickhouse
11. DB::HashedDictionary<(DB::DictionaryKeyType)1, false, false>::HashedDictionary(DB::StorageID const&, DB::DictionaryStructure const&, std::shared_ptr<DB::IDictionarySource>, DB::HashedDictionaryConfiguration const&, std::shared_ptr<DB::Block>) @ 0x10b1b554 in /usr/bin/clickhouse
12. ? @ 0x10d8a090 in /usr/bin/clickhouse
13. ? @ 0x10d8a7a8 in /usr/bin/clickhouse
14. DB::DictionaryFactory::create(String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, bool) const @ 0x12442b6b in /usr/bin/clickhouse
15. DB::ExternalDictionariesLoader::create(String const&, Poco::Util::AbstractConfiguration const&, String const&, String const&) const @ 0x1311fa5b in /usr/bin/clickhouse
16. DB::ExternalLoader::LoadingDispatcher::doLoading(String const&, unsigned long, bool, unsigned long, bool, std::shared_ptr<DB::ThreadGroupStatus>) @ 0x1312c653 in /usr/bin/clickhouse
17. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::ExternalLoader::LoadingDispatcher::*)(String const&, unsigned long, bool, unsigned long, bool, std::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*, String&, unsigned long&, bool&, unsigned long&, bool, std::shared_ptr<DB::ThreadGroupStatus>>(void (DB::ExternalLoader::LoadingDispatcher::*&&)(String const&, unsigned long, bool, unsigned long, bool, std::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*&&, String&, unsigned long&, bool&, unsigned long&, bool&&, std::shared_ptr<DB::ThreadGroupStatus>&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x131324d3 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe25cc73 in /usr/bin/clickhouse
19. ? @ 0xe2628e1 in /usr/bin/clickhouse
20. ? @ 0x7f09f3a69609 in ?
21. __clone @ 0x7f09f398e133 in ?
 (version 23.3.1.2823 (official build)). (DICTIONARIES_WAS_NOT_LOADED) (version 23.3.1.2823 (official build)) (from 127.0.0.1:35280) (in query:  SYSTEM RELOAD DICTIONARY dictionary_bug), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe18d895 in /usr/bin/clickhouse
1. ? @ 0x94f619e in /usr/bin/clickhouse
2. DB::ExternalLoader::checkLoaded(DB::ExternalLoader::LoadResult const&, bool) const @ 0x13122a21 in /usr/bin/clickhouse
3. std::shared_ptr<DB::IExternalLoadable const> DB::ExternalLoader::loadOrReload<std::shared_ptr<DB::IExternalLoadable const>, void>(String const&) const @ 0x13123709 in /usr/bin/clickhouse
4. DB::ExternalDictionariesLoader::reloadDictionary(String const&, std::shared_ptr<DB::Context const>) const @ 0x13120248 in /usr/bin/clickhouse
5. DB::InterpreterSystemQuery::execute() @ 0x137feec2 in /usr/bin/clickhouse
6. ? @ 0x13b18da7 in /usr/bin/clickhouse
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13b1634d in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0x148e80ac in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0x148fd859 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x17838054 in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x1783927b in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x179c0b07 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x179be53d in /usr/bin/clickhouse
14. ? @ 0x7f09f3a69609 in ?
15. __clone @ 0x7f09f398e133 in ?


0 rows in set. Elapsed: 0.010 sec.

Received exception from server (version 23.3.1):
Code: 156. DB::Exception: Received from localhost:9000. DB::Exception: Failed to load dictionary 'b9186a0b-3d7b-4890-a6ce-a7bf2fc05e3f': std::exception. Code: 1001, type: pqxx::conversion_error, e.what() = Could not convert string to m: 'DOMAIN'.,. (DICTIONARIES_WAS_NOT_LOADED)
````

**Additional context**

If I create view from query (or table and populate it) and then create ClickHouse dictionary everything is working fine.

**Comment by den-crane** [comment] 2023-04-11 23:29
@realyota you made 1000 typos in your example.

```
SELECT id as site_id, domain, 
    extract(''Year'' FROM native_stats_start_at)::text || lpad(extract(''Month'' FROM native_stats_start_at)::text, 2, ''0'') as partition 
from sites ORDER BY native_stats_start_at
```
There is no `id` column in the query. Table name is not `sites`. There is no column `native_stats_start_at`.

The issue is a duplicate of https://github.com/ClickHouse/ClickHouse/issues/45559

The primary key should the first column of dictionary.

Also you can use `$$  $$` -- [heredoc](https://en.wikipedia.org/wiki/Here_document)

```sql
CREATE DICTIONARY dictionary_bug (
`domain` String,
`site_id` UInt64, 
`partition` String
) PRIMARY KEY domain
 SOURCE( POSTGRESQL(
	   host 'localhost'
	   port 5432
	   db 'test'
	   user 'test'
	   password 'test' 
    query $$SELECT domain, id as site_id, extract('Year' FROM time)::text || lpad(extract('Month' FROM time)::text, 2, '0') as partition from test$$
 )
) 
LIFETIME(3600) 
LAYOUT(COMPLEX_KEY_HASHED())

SELECT * FROM dictionary_bug;

┌─domain─┬─site_id─┬─partition─┐
│ xxx    │       1 │ 202304    │
└────────┴─────────┴───────────┘
```

**Closed by den-crane** 2023-04-11 23:29 UTC
Labels: potential bug
