### ISSUE TITLE
ClickHouse client(or server) can't parse multiline insert query

### ISSUE THREAD

**Issue by uu3474** [ClickHouse/ClickHouse#40832] opened 2022-08-31 10:13 UTC
I have a file with few queries, file name is **r.sql**:
```
CREATE TABLE canon.table (col_Int8 Int8) ENGINE = MergeTree ORDER BY tuple();
INSERT INTO canon.table(col_Int8) VALUES (
  -128
);
```

Trying to execute this file:
```
clickhouse-client --multiline --multiquery --queries-file r.sql
Error on processing query: Code: 32. DB::Exception: Attempt to read after eof: While executing ValuesBlockInputFormat: data for INSERT was parsed from query. (ATTEMPT_TO_READ_AFTER_EOF) (version 22.8.2.11 (official build))
(query: INSERT INTO canon.table(col_Int8) VALUES ()
```

But if insert query is a single line, like:
```
CREATE TABLE canon.table (col_Int8 Int8) ENGINE = MergeTree ORDER BY tuple();
INSERT INTO canon.table(col_Int8) VALUES (-128);
```
Its working fine.

**Comment by alexey-milovidov** [comment] 2024-01-06 15:01
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/58436

**Comment by Alex-Cheng** [comment] 2024-01-23 11:33
I have the same issue, is there any workaround for me to temporarily resolve the issue.

**Comment by alexey-milovidov** [comment] 2024-09-21 22:13
Fixed.

**Closed by alexey-milovidov** 2024-09-21 22:13 UTC
Labels: duplicate, unexpected behaviour
