### ISSUE TITLE
Segfault when altering a dictionary

### ISSUE THREAD

**Issue by SEDAManzana** [ClickHouse/ClickHouse#43171] opened 2022-11-11 13:04 UTC
Hello everyone.

We get a bug.  Then run alter on dictionaries , query failed with error or query canceled, but query not canceled on zookeepers queue.
And after all replicas failed and clickhouse can`t starting.

example:
```
CREATE DICTIONARY db.dict on cluster basic
(`id` UInt64,   `test_column` String)
PRIMARY KEY id
SOURCE(...)
LIFETIME(MIN 900 MAX 1200)
LAYOUT(HASHED())

```
We run 2 types scripts
```
alter table db.dict on cluster basic modify column `test_column` COMMENT `comment_for_test

alter dictionary db.dict on cluster basic modify column `test_column` COMMENT `comment_for_test
```

In logs i see error "**tables in readOnly mode**" then up metadates and error "**Address: 0x18 Access: read. Address not mapped to object**"

When we in manual mode delete this query - replicas auto-restarting. 

How use alter on dictionary? And why canceled query not stoped on ZooKeepers queue? This bug can fix if we update Clickhouse? Current version 21.10.2.15

**Comment by tavplubix** [comment] 2022-11-11 14:58
> Address: 0x18 Access: read. Address not mapped to object

It's segmentation fault. Please provide relevant logs:
```
zgrep -Fa Fatal /ver/log/clockhouse-server/*
```

> 21.10.2.15

This version is obsolete and not supported anymore, you should upgrade.

**Comment by SEDAManzana** [comment] 2022-11-11 15:33
last lines:
2022.11.11 13:25:03.097714 [ 1393 ] {} <Fatal> BaseDaemon: ########################################
2022.11.11 13:25:03.097788 [ 1393 ] {} <Fatal> BaseDaemon: (version 21.10.2.15 (official build), build id: 6699B86599A2121E78E0D42DD67791ABD9AE5265) (from thread 1173) (query_id: 036a5308-7059-44ee-abfd-8c1873a5dbe5) Received signal Segmentation fault (11)
2022.11.11 13:25:03.097819 [ 1393 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2022.11.11 13:25:03.097836 [ 1393 ] {} <Fatal> BaseDaemon: Stack trace: 0x10732603 0x10732112 0x1072cbc0 0x112495f0 0x10a3c993 0x110732e1 0x11076222 0x108b2a21 0x108b15b7 0x108aed93 0x108a829c 0x108bff51 0x948ce7f 0x9490763 0x7fc5368bffa3 0x7fc5367e14cf
2022.11.11 13:25:03.097883 [ 1393 ] {} <Fatal> BaseDaemon: 1. void DB::IAST::replace<DB::ASTExpressionList>(DB::ASTExpressionList*&, std::__1::shared_ptr<DB::IAST> const&) @ 0x10732603 in /usr/bin/clickhouse
2022.11.11 13:25:03.097896 [ 1393 ] {} <Fatal> BaseDaemon: 2. DB::applyMetadataChangesToCreateQuery(std::__1::shared_ptr<DB::IAST> const&, DB::StorageInMemoryMetadata const&) @ 0x10732112 in /usr/bin/clickhouse
2022.11.11 13:25:03.097908 [ 1393 ] {} <Fatal> BaseDaemon: 3. DB::DatabaseOrdinary::alterTable(std::__1::shared_ptr<DB::Context const>, DB::StorageID const&, DB::StorageInMemoryMetadata const&) @ 0x1072cbc0 in /usr/bin/clickhouse
2022.11.11 13:25:03.097926 [ 1393 ] {} <Fatal> BaseDaemon: 4. DB::IStorage::alter(DB::AlterCommands const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0x112495f0 in /usr/bin/clickhouse
2022.11.11 13:25:03.097946 [ 1393 ] {} <Fatal> BaseDaemon: 5. DB::InterpreterAlterQuery::execute() @ 0x10a3c993 in /usr/bin/clickhouse
2022.11.11 13:25:03.097956 [ 1393 ] {} <Fatal> BaseDaemon: 6. ? @ 0x110732e1 in /usr/bin/clickhouse
2022.11.11 13:25:03.097978 [ 1393 ] {} <Fatal> BaseDaemon: 7. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&, std::__1::function<void ()>) @ 0x11076222 in /usr/bin/clickhouse
2022.11.11 13:25:03.097998 [ 1393 ] {} <Fatal> BaseDaemon: 8. DB::DDLWorker::tryExecuteQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x108b2a21 in /usr/bin/clickhouse
2022.11.11 13:25:03.098016 [ 1393 ] {} <Fatal> BaseDaemon: 9. DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x108b15b7 in /usr/bin/clickhouse
2022.11.11 13:25:03.098027 [ 1393 ] {} <Fatal> BaseDaemon: 10. DB::DDLWorker::scheduleTasks(bool) @ 0x108aed93 in /usr/bin/clickhouse
2022.11.11 13:25:03.098038 [ 1393 ] {} <Fatal> BaseDaemon: 11. DB::DDLWorker::runMainThread() @ 0x108a829c in /usr/bin/clickhouse
2022.11.11 13:25:03.098054 [ 1393 ] {} <Fatal> BaseDaemon: 12. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'()::operator()() @ 0x108bff51 in /usr/bin/clickhouse
2022.11.11 13:25:03.098071 [ 1393 ] {} <Fatal> BaseDaemon: 13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x948ce7f in /usr/bin/clickhouse
2022.11.11 13:25:03.098080 [ 1393 ] {} <Fatal> BaseDaemon: 14. ? @ 0x9490763 in /usr/bin/clickhouse
2022.11.11 13:25:03.098095 [ 1393 ] {} <Fatal> BaseDaemon: 15. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
2022.11.11 13:25:03.098108 [ 1393 ] {} <Fatal> BaseDaemon: 16. clone @ 0xf94cf in /lib/x86_64-linux-gnu/libc-2.28.so
2022.11.11 13:25:03.218954 [ 1393 ] {} <Fatal> BaseDaemon: Checksum of the binary: 902F2F159F07FEEC02834AEF44CBFB70, integrity check passed.
2022.11.11 13:25:23.151847 [ 900 ] {} <Fatal> Application: Child process was terminated by signal 11.

**Comment by tavplubix** [comment] 2022-11-11 15:50
> alter dictionary db.dict on cluster basic modify column `test_column` COMMENT `comment_for_test

Hm, but we don't have ALTER DICTIONARY query. Do you use custom build with some patches?

**Comment by tavplubix** [comment] 2022-11-11 15:51
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/33251

**Closed by tavplubix** 2022-11-11 15:51 UTC
Labels: obsolete-version, potential bug
