### ISSUE TITLE
The type "LowCardinality" is not supported for conversion into a Arrow/Parquet data format

### ISSUE THREAD

**Issue by n87** [ClickHouse/ClickHouse#12417] opened 2020-07-11 05:12 UTC
Arrow/ArrowStream/Parquet formats don't seem to work with `LowCardinality` types.

**How to reproduce**
```
CREATE TABLE test (name LowCardinality(String)) ENGINE = Memory
INSERT INTO test VALUES ('a')
SELECT name FROM test FORMAT Arrow
```
**Expected behavior**
I'd expect the raw strings (or whatever other type is wrapped in LowCardinality) to be returned.

**Error message and/or stacktrace**
```
Exception on client:
Code: 50. DB::Exception: The type "LowCardinality" of a column "name" is not supported for conversion into a Arrow data format
```

**Additional context**
```
$ clickhouse-server --version
ClickHouse server version 20.5.2.7 (official build).
```

**Comment by filimonov** [comment] 2020-07-27 08:56
https://github.com/ClickHouse/ClickHouse/issues/12086

**Comment by filimonov** [comment] 2020-07-27 08:57
Duplicate of #12086

**Closed by filimonov** 2020-07-27 08:57 UTC
Labels: bug, comp-formats, comp-lowcardinality
