### ISSUE TITLE
ClickHouse 21.8.2.19-prestable error message of clickhouse-keeper-converter without arguments

### ISSUE THREAD

**Issue by AlmostIvanSidorov** [ClickHouse/ClickHouse#27567] opened 2021-08-11 12:49 UTC
**Describe my observation**

When `clickhouse-keeper-converter` is used without any arguments it shows the uninformative message.

**How to reproduce**
```
~$ clickhouse keeper-converter
std::exception. Code: 1001, type: boost::wrapexcept<boost::bad_any_cast>, e.what() = boost::bad_any_cast: failed conversion using boost::any_cast, Stack trace (when copying this message, always include the lines below):

0. mainEntryClickHouseKeeperConverter(int, char**) @ 0x915803b in /usr/bin/clickhouse
1. main @ 0x8f95c9e in /usr/bin/clickhouse
2. __libc_start_main @ 0x270b3 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
3. _start @ 0x8f60fae in /usr/bin/clickhouse
 (version 21.8.2.19 (official build))
```

**Expected behavior**
Some information message about what is going wrong.

**Comment by alexey-milovidov** [comment] 2021-08-11 16:57
@AlmostIvanSidorov `clickhouse-keeper` is under development and is not used in production.

**Comment by vzakaznikov** [comment] 2021-08-11 23:08
> @AlmostIvanSidorov `clickhouse-keeper` is under development and is not used in production.
> We never advertised the usage of `clickhouse-keeper`.
> 
> See https://clickhouse.tech/docs/en/operations/clickhouse-keeper/
> 
> Also non-informative error message is just a minor usability drawback, not a bug.

@alexey-milovidov, maybe we should have a "bug experimental" option in the https://github.com/ClickHouse/ClickHouse/issues/new/choose?

**Comment by alexey-milovidov** [comment] 2021-08-12 20:23
This is not a bug. You get error message on wrong invocation - as expected.

**Comment by alexey-milovidov** [comment] 2021-08-12 20:25
Let's just close this issue and let @alesapin improve the error message after he will return from his vacation.

**Closed by alexey-milovidov** 2021-08-12 20:25 UTC
Labels: question, question-answered
