### ISSUE TITLE
MaterializedPostgreSQL database query hangs on PostrgeSQL side error

### ISSUE THREAD

**Issue by execreate** [ClickHouse/ClickHouse#41923] opened 2022-09-29 06:19 UTC
Query
```
SHOW TABLES FROM postgres_db;
```
where postgres_db uses MaterializedPostgreSQL engine hangs when Postgres server emits error `ERROR:  permission denied for database`.

Clickhouse version 22.9.

**How to reproduce**

1. Use docker to start PostgreSQL server:
```
docker run \
-e POSTGRESQL_REPLICATION_MODE=master \
-e POSTGRESQL_REPLICATION_USER=repl_user \
-e POSTGRESQL_REPLICATION_PASSWORD=repl_password \
-e POSTGRESQL_USERNAME=my_user \
-e POSTGRESQL_PASSWORD=my_password \
-e POSTGRESQL_DATABASE=my_database \
-d bitnami/postgresql:14.5
```
2. Open `clickhouse-client` and run the following:
```
CREATE DATABASE postgres_db ENGINE = MaterializedPostgreSQL('MY_PG_HOST:PORT', 'my_database', 'repl_user', 'repl_password')
```
3. Then query the tables in `clickhouse-client`:
```
SHOW TABLES FROM postgres_db;
```
4. Your query hangs. Forever. It's not even possible to enter `clickhouse-client` back again after you exit it with CTRL+C unless you restart ClickHouse server to interrupt the request from step 3.

**Expected behavior**

Fail with `DB::Exception: PostgreSQL replication initialization did not finish successfully` or something similar.

**Comment by jpchev** [comment] 2023-12-01 23:49
It seems this is fixed in Clickhouse _23.10.5.20 (official build)_, I can't reproduce the issue with the following docker compose file

`
version: '3.7'

services:
  db:
    container_name: db
    image: postgres:15 
    restart: always
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ./fs-docker/clickhouse/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs-docker/clickhouse/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
`

then
`docker-compose up`

and after opening a bash on clickhouse container 
`docker exec -it <container id> bash`

I enter the client and can create the table without problems
```

clickhouse@clickhouse:/$ clickhouse client
ClickHouse client version 23.10.5.20 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.10.5 revision 54466.

Warnings:
 * Linux is not using a fast clock source. Performance can be degraded. Check /sys/devices/system/clocksource/clocksource0/current_clocksource
 * Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled
 * Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. Check /proc/sys/kernel/task_delayacct

ch :) SET allow_experimental_database_materialized_postgresql=1;

SET allow_experimental_database_materialized_postgresql = 1

Query id: c8de63ef-3536-4b9d-9ca5-ea026a93460a

Ok.

0 rows in set. Elapsed: 0.001 sec.

ch :) CREATE DATABASE postgres_db ENGINE = MaterializedPostgreSQL('db:5432', 'my_database', 'my_user', 'my_password')

CREATE DATABASE postgres_db
ENGINE = MaterializedPostgreSQL('db:5432', 'my_database', 'my_user', 'my_password')

Query id: 5555cc30-a869-4a74-a332-606563580c04

Ok.

0 rows in set. Elapsed: 0.006 sec.

ch :)
```

can we close this issue?

**Comment by kssenii** [comment] 2023-12-05 12:25
Added an integration test covering this issue in https://github.com/ClickHouse/ClickHouse/pull/57515.

**Closed by kssenii** 2023-12-05 12:25 UTC
Labels: experimental issue
