### ISSUE TITLE
Stateless test `01137_order_by_func` is flaky

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#67945] opened 2024-08-06 20:17 UTC
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIwLTAxLTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJTAxMTM3X29yZGVyX2J5X2Z1bmMnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

cc @CurtizJ

**Comment by KochetovNicolai** [comment] 2024-08-12 16:46
Examples
https://s3.amazonaws.com/clickhouse-test-reports/0/bebc5c2e7eacecab3029a2083795893982e79d59/stateless_tests__debug__s3_storage__[2_2].html
https://s3.amazonaws.com/clickhouse-test-reports/0/be80f4e5d046b9f88792ddb1a0a37813d6e1639f/stateless_tests__debug__s3_storage__[2_2].html

**Comment by max-vostrikov** [comment] 2024-08-22 11:44
happens due to https://github.com/ClickHouse/ClickHouse/issues/67788

**Comment by max-vostrikov** [comment] 2024-08-22 12:55
As discussed with @CheSema, closing this as as a duplicate of https://github.com/ClickHouse/clickhouse-private/issues/14209 and https://github.com/ClickHouse/ClickHouse/issues/67788

**Closed** 2024-08-22 13:00 UTC
Labels: testing, flaky test
