### ISSUE TITLE
Random results of minIf function if grouping by Enum

### ISSUE THREAD

**Issue by nem0-z** [ClickHouse/ClickHouse#48968] opened 2023-04-20 09:44 UTC
> You have to provide the following information whenever possible.

Running a minIf (inside of a query that is grouped by column of type Enum) with a condition that is never satisfied in any of the rows, random result will be returned. If I change group by clause to perform grouping by a column of type String for instance, everything will be fine (0 is returned).

> A clear and concise description of what works not as it is supposed to.

minIf (I also reproduced this issue for maxIf as well) should return 0 instead of some random value.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

https://fiddle.clickhouse.com/5485e670-5b52-4624-ba6f-7000be4ec3c8

**Does it reproduce on recent release?**

Yes, on every release including the latest.

**How to reproduce**

- ClickHouse server version: Any version that supports Enum (including latest of course)
- Create table:  
- `CREATE TABLE dummy
(
    num1 Int32,
    num2 Enum8('foo' = 0, 'bar' = 1, 'tar' = 2)
)
ENGINE = MergeTree
ORDER BY num1;
`
- Queries to run:
Few basic insert statements like: `INSERT INTO dummy VALUES(5, 'bar');`
`SELECT minIf(num1, num1 < -500) FROM dummy GROUP BY num2` (NOTE1: It should be run multiple times as it returns different value almost every time, NOTE2: `num1 < -500` is an example of a condition that is never satisfied)

**Expected behavior**

I expected 0 to be returned, as is the case when not grouping by Enum.

**Comment by den-crane** [comment] 2023-04-20 12:54
because of `compile_aggregate_expressions`

https://fiddle.clickhouse.com/0387a1e9-781a-4713-90a2-6dcbc48b9853

duplicate of https://github.com/ClickHouse/ClickHouse/issues/48120

**Closed by den-crane** 2023-04-20 12:54 UTC
Labels: potential bug

**Comment by nem0-z** [comment] 2023-04-20 13:08
> because of `compile_aggregate_expressions`
> 
> https://fiddle.clickhouse.com/0387a1e9-781a-4713-90a2-6dcbc48b9853
> 
> duplicate of #48120

Thanks!
