### ISSUE TITLE
Materialized view breaks inserts to source table

### ISSUE THREAD

**Issue by denisov-vlad** [ClickHouse/ClickHouse#4064] opened 2019-01-15 10:35 UTC
We have source table `local.clickstream_new` with `ReplicatedMergeTree` engine and some materialized views to this table.

I've tried to create another one:

```
CREATE MATERIALIZED VIEW local.view__broadcasts ON CLUSTER sports ( site String,   match_id UInt32, user_type String, event_date Date, views UInt64) ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/view__broadcasts', '{replica}', event_date, (site, match_id), 8192) AS select site, match_id, user_type, event_date, sum(start) as views FROM (select site, path(url) as pt, event_date, argMax(page_id, page_id) as match_id, multiIf(user_is_mobile = 0, 'web-desktop', lower(user_browser_name) LIKE '%view%', 'apps', 'web-mobile') as user_type, count() as start from local.clickstream_new WHERE is_event = 1 AND event_category = 'broadcast' AND event_label = 'click' GROUP BY site, url, user_type, event_date) WHERE match_id > 0 AND user_type IS NOT NULL group by site, match_id, user_type, event_date
```

Then i've executed `INSERT INTO local.view__broadcasts {select from create query above}` and everything inserted succesfully.

After that, the data from some of the shards stopped being inserted. The error log shows this error:
```
<Error> HTTPHandler: Code: 393, e.displayText() = DB::Exception: There is no query: while pushing to view,  
```

**Comment by kaainet** [comment] 2019-05-27 15:10
Stumbled upon the same issue.

**Comment by den-crane** [comment] 2019-05-27 23:02
MVs never supported select from select

**Comment by filimonov** [comment] 2019-12-12 21:40
It is the duplicate of https://github.com/ClickHouse/ClickHouse/issues/5142
Shoule work starting from 19.7

**Closed by filimonov** 2019-12-12 21:40 UTC
Labels: comp-matview
