### ISSUE TITLE
S3 table function generation a misleading error message when no files are matching

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#37792] opened 2022-06-02 12:58 UTC
**Describe the unexpected behaviour**

When using the S3 function, if no files are matching the user will get the following error:

`Code: 636. DB::Exception: All attempts to extract table structure from files failed. Errors:. (CANNOT_EXTRACT_TABLE_STRUCTURE) (version 22.6.1.5299 (official build))`

The error message should be more accurate, currently, it is misleading. 

It is kind of similar to this issue in term of behavior: #36317

**Comment by alexey-milovidov** [comment] 2022-06-22 02:11
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/38298.

**Closed by alexey-milovidov** 2022-06-22 02:11 UTC
Labels: duplicate, unexpected behaviour, support-services
