### ISSUE TITLE
`01602_max_distributed_connections` is flaky

### ISSUE THREAD

**Issue by evillique** [ClickHouse/ClickHouse#56688] opened 2023-11-13 16:54 UTC
https://s3.amazonaws.com/clickhouse-test-reports/56623/a1abf3202ed06d252bbb79e6326a1fa6f285f1bd/stateless_tests__debug__[3_5].html

CI DB: [link](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMTYwMl9tYXhfZGlzdHJpYnV0ZWRfY29ubmVjdGlvbnMnIEFTIG5hbWVfc3Vic3RyLAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cywKICAgICgnU3RhdGVsZXNzIHRlc3RzIChhc2FuKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MpJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcywgYWN0aW9ucyknKSBBUyBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MKU0VMRUNUCiAgICB0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgQVMgZCwKICAgIGNvdW50KCksCiAgICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSBBUyBwcnMsCiAgICBhbnkocmVwb3J0X3VybCkKRlJPTSBjaGVja3MKV0hFUkUgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAocHVsbF9yZXF1ZXN0X251bWJlciBOT1QgSU4gKAogICAgU0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgQVMgcHJuCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgKHBybiAhPSAwKSBBTkQgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAoY2hlY2tfbmFtZSBJTiAoYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSkKKSkgQU5EIChwb3NpdGlvbih0ZXN0X25hbWUsIG5hbWVfc3Vic3RyKSA+IDApIEFORCAodGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0ZMQUtZJykpCkdST1VQIEJZIGQKT1JERVIgQlkgZCBERVNDCg==)

**Comment by tavplubix** [comment] 2023-11-13 20:19
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/56256

**Closed by tavplubix** 2023-11-13 20:19 UTC
Labels: testing
