### ISSUE TITLE
MaterializeMySQLSyncThread: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof

### ISSUE THREAD

**Issue by liangli1213** [ClickHouse/ClickHouse#14786] opened 2020-09-14 07:02 UTC
**Describe the bug**
The bug may not be reproduced on each platform.

**How to reproduce**
* Set up replication relationship between MySQL and ClickHouse
* When data copy has completed and after a while, stop ClickHouse service
* Wait for 0.5 hour, start ClickHouse service, you will get odd error, may different from each time

**Additional comment**
I strongly suspect MySQL replication protocol send abnormal message to ClickHouse, which cause ClickHouse side code unable to parse the message
* Is it possible to print the abnormal message?
* Is there a mechanism to let MySQL resend required binlog message, if the fetch one is abnormal?

**Error message and/or stacktrace**
```
2020.09.14 13:14:28.493063 [ 4737 ] {} <Error> MaterializeMySQLSyncThread: Code: 1002, e.displayText()
 = DB::Exception: ParseRow: Unhandled MySQL field type:0, Stack trace (when copying this message,
 always include the lines below):
```
```
2020.09.14 13:14:04.557507 [ 4721 ] {} <Error> MaterializeMySQLSyncThread: Code: 32, e.displayText()
 = DB::Exception: Attempt to read after eof, Stack trace (when copying this message, always include
the lines below):
```
```
2020.09.14 12:51:54.084817 [ 21290 ] {} <Error> MaterializeMySQLSyncThread: std::exception. Code: 10
01, type: std::length_error, e.what() = basic_string, Stack trace (when copying this message, always
 include the lines below):
```
```
2020.09.14 12:26:44.455515 [ 20389 ] {} <Error> MaterializeMySQLSyncThread: Code: 62, e.displayText(
) = DB::Exception: Syntax error: failed at position 121 ('BE'): BE. Expected one of: RENAME DATABASE
, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY, DETACH, RENAME query, DROP, create query, C
REATE, EXCHANGE TABLES, ALTER TABLE, alter query, Stack trace (when copying this message, always inc
lude the lines below):
```
```
2020.09.14 12:14:25.200499 [ 4794 ] {} <Error> MaterializeMySQLSyncThread: Code: 62, e.displayText()
 = DB::Exception: Syntax error: failed at position 121 ('BEG'): BEG. Expected one of: RENAME DATABAS
E, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY, DETACH, RENAME query, DROP, create query,
CREATE, EXCHANGE TABLES, ALTER TABLE, alter query, Stack trace (when copying this message, always in
clude the lines below):
```

**Comment by liangli1213** [comment] 2020-09-14 07:07
@BohuTANG @zhang2014 , I don't think this is caused by your code, because if I don't restart ClickHouse service after the replication has been setup, the issue won't occur and the replication can keep going on over night, but whenever I restart the service, the issue happens rapidly.

**Comment by liangli1213** [comment] 2020-09-17 14:56
@zhang2014 @BohuTANG , thanks for your effort to fix this bug, here I record how to 100% reproduce this issue, it is a little complex, I believe there are other better methods, but I don't have much time to dig.

1. Setup 2 MySQL server: mysql_a (master) and mysql_b (slave), then make the replication relationship

```
*************************** 1. row ***************************
       Table: timestamp
Create Table: CREATE TABLE `timestamp` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `timestamp` int(11) DEFAULT NULL,
  `content` varchar(9000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1516828 DEFAULT CHARSET=latin1
```

2. Start mysql stress on mysql_a

_test.sql_
```
start transaction;
insert into clickhouse_test.timestamp (timestamp, content) values (111222333, 'The default location for binary log files is the data directory. You can use the --log-bin option to specify an alternative location, by adding a leading absolute path name to the base name to specify a different directory. When the server reads an entry from the binary log index file, which tracks the binary log files that have been used, it checks whether the entry contains a relative path. If it does, the relative part of the path is replaced with the absolute path set using the --log-bin option. An absolute path recorded in the binary log index file remains unchanged; in such a case, the index file must be edited manually to enable a new path or paths to be used. The binary log file base name and any specified path are available as the log_bin_basename system variable. In earlier MySQL versions, binary logging was disabled by default');
commit;
```
_Command:_
`while true; do mysql -h mysql_a -uroot -p<password> < test.sql; sleep 0.01; done`

3. Setup replication between mysql_b and clickhouse

`CREATE DATABASE clickhouse_test ENGINE = MaterializeMySQL('mysql_b:3306', 'clickhouse_test', 'root', '<password>');`

4. Wait for 30 minutes, stop ClickHouse service on clickhouse

5. Wait for 3 hours, start ClickHouse service on clickhouse

6. After 0.5 - 1 hour, you can see below error message:

```
2020.09.17 20:11:01.317775 [ 8552 ] {} <Error> MaterializeMySQLSyncThread: Code:
 62, e.displayText() = DB::Exception: Syntax error: failed at position 121 ('B')
: B. Expected one of: RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAM
E DICTIONARY, DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES,
 ALTER TABLE, alter query, Stack trace (when copying this message, always includ
e the lines below):
```

**Comment by liangli1213** [comment] 2020-09-18 00:01
@BohuTANG @zhang2014 , I just used build 20.10.1.4678, and test with steps I mentioned above, unfortunately, the issue is even worse, when doing step 3, below error occur very sooner:

`2020.09.18 07:56:00.172767 [ 16800 ] {} <Error> MaterializeMySQLSyncThread(): Query EXTERNAL DDL FROM MySQL(clickhouse_test, clickhouse_test) B wasn't finished successfully: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 121 ('B'): B. Expected one of: RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY, DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES, ALTER TABLE, alter query, Stack trace (when copying this message, always include the lines below):`

It seems MaterializeMySQL not work well when replicate from slave node.

**Comment by BohuTANG** [comment] 2020-09-18 03:10
Hello,

Please check your version by 'select version()'.
I have checked the build from master and can't reproduce the issue yet follow your steps.

1. source code:
```
$ git log -2
commit 76a3cc2dae22ea9ebc9b82776ef07ea95a996e0c (HEAD -> master, origin/master, origin/HEAD)
Merge: 6a1e4ccdf9 22bd22702e
Author: alexey-milovidov <milovidov@yandex-team.ru>
Date:   Fri Sep 18 01:24:02 2020 +0300

    Merge pull request #14937 from filimonov/finalizeAggregation_statefullness
    
    Fix enable_optimize_predicate_expression for finalizeAggregation
...
```

2. version:
```
mysql> select version();
+-----------+
| version() |
+-----------+
| 20.10.1.1 |
+-----------+
```

3. bench script:
https://gist.github.com/BohuTANG/4762af73bac65b20043e3564ee1c7ee0

**Comment by liangli1213** [comment] 2020-09-18 03:26
@BohuTANG 

```
bdcdev09.bdcdesign.analog.com :) select version();

SELECT version()

┌─version()────┐
│ 20.10.1.4678 │
└──────────────┘
```
Have you reproduce follow my steps? one important step is, you must setup MySQL Master and Slave first, then ClickHouse sync from Slave.

**Comment by BohuTANG** [comment] 2020-09-18 03:30
Can you try sync from the master and have a check?

**Comment by liangli1213** [comment] 2020-09-18 03:30
Sync from master has no problem, I have tried.

**Comment by BohuTANG** [comment] 2020-09-18 04:43
I can't reproduce it, what's your slave my.cnf?
In principle, syncing from mysql master or slave there is no difference.
Here are some configs related to my mysql:
```
sudo docker network create --subnet=172.18.0.0/16 selnet

sudo docker run --net selnet --ip 172.18.0.3 -d -e MYSQL_ROOT_PASSWORD=123 mysql:5.7 mysqld --datadir=/var/lib/mysql --server-id=3 --log-bin=/var/lib/mysql/mysql-bin.log --gtid-mode=ON --enforce-gtid-consistency --disable-ssl --ssl=0 --log_slave_updates=on

sudo docker run --net selnet --ip 172.18.0.4 -d -e MYSQL_ROOT_PASSWORD=123 mysql:5.7 mysqld --datadir=/var/lib/mysql --server-id=4 --log-bin=/var/lib/mysql/mysql-bin.log --gtid-mode=ON --enforce-gtid-consistency --disable-ssl --ssl=0 --log_slave_updates=on

mysql04>change master to master_host='172.18.0.3', master_user='root', master_password='123', master_auto_position=1;
clickhouse>create database sbtest engine=MaterializeMySQL('172.18.0.4:3306', 'sbtest', 'root', '123');
```

**Comment by liangli1213** [comment] 2020-09-18 06:22
@BohuTANG , it is my fault, I just set binlog_checksum to NONE in slave.

I have restarted the replication from MySQL to ClickHouse on my test server, so far I didn't see any error.

**Comment by zhang2014** [comment] 2020-09-18 07:15
Maybe we can close this issue.

**Comment by liangli1213** [comment] 2020-09-18 07:25
I will close it later, the test is still in progress.

**Closed** 2020-09-19 00:49 UTC
Labels: bug, comp-mysql
