### ISSUE TITLE
Division by zero 

### ISSUE THREAD

**Issue by n00bik** [ClickHouse/ClickHouse#7509] opened 2019-10-28 15:07 UTC
Division by zero

**Describe the bug or unexpected behaviour**
error despite the fact that the denominator is converted to null in case of zero value

**How to reproduce**
`
drop table if EXISTS test_table;
create table test_table
(
  id          int,
  revenue     Decimal(38, 12),
  count_dist  Nullable(UInt64)
) engine MergeTree()
    partition by id
    order by id;
   
  
insert into test_table (id, revenue, count_dist) values (1, 30.54, null);
insert into test_table (id, revenue, count_dist) values (2, 10, 10);
insert into test_table (id, revenue, count_dist) values (3, 50, 0);

select revenue / nullif(count_dist,0) as arpu
  from test_table;
`

* Which ClickHouse server version to use
version 19.15.2.2 (official build)

* Which interface to use, if matters
DB::Exception

**Expected behavior**
calculation of    revenue / nullif(count_dist,0)

**Comment by filimonov** [comment] 2019-10-28 20:11
Confirmed.

```
↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.16.1):
Code: 153. DB::Exception: Received from localhost:9000. DB::Exception: Division by zero. Stack trace:

0. 0x556a4e046d20 StackTrace::StackTrace() /usr/include/c++/9/ext/new_allocator.h:128
1. 0x556a4e046af5 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/include/c++/9/bits/stl_uninitialized.h:82
2. 0x556a4eb02717 COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::DecimalComparison<DB::Decimal<long>, unsigned short, DB::EqualsOp, false, true>::apply<false, true>(COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, long) /usr/lib/debug/usr/bin/clickhouse
3. 0x556a4eb5c233 auto DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true>::executeImpl(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long)::{lambda(auto:1 const&, auto:2 const&)#1}::operator()<DB::DataTypeDecimal<DB::Decimal<__int128> >, DB::DataTypeNumber<unsigned long> >(DB::DataTypeDecimal<DB::Decimal<__int128> > const&, DB::DataTypeNumber<unsigned long> const&) const /usr/lib/debug/usr/bin/clickhouse
4. 0x556a4eaf83f0 COW<DB::IColumn>::immutable_ptr<DB::IColumn> DB::DecimalComparison<unsigned char, DB::Decimal<long>, DB::EqualsOp, true, true>::apply<false, false>(COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, long) /usr/lib/debug/usr/bin/clickhouse
5. 0x556a4eb6fa60 DB::FunctionBinaryArithmetic<DB::DivideFloatingImpl, DB::NameDivide, true>::executeImpl(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long) /usr/lib/debug/usr/bin/clickhouse
6. 0x556a511cd6f8 DB::PreparedFunctionImpl::defaultImplementationForNulls(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) /usr/include/c++/9/bits/stl_uninitialized.h:82
7. 0x556a511cd511 std::__detail::_Hash_node<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, true>* std::__detail::_ReuseOrAllocNode<std::allocator<std::__detail::_Hash_node<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, true> > >::operator()<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > const&>(std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > const&) const /usr/include/c++/9/bits/stl_vector.h:677
8. 0x556a511ce144 void std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_assign<std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_assign_elements<std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> > const&, std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::operator=(std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> > const&)::{lambda(std::__detail::_ReuseOrAllocNode<std::allocator<std::__detail::_Hash_node<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, true> > > const&, std::__detail::_Hash_node<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, true> const*)#2}>(std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> > const&, std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::operator=(std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> > const&)::{lambda(std::__detail::_ReuseOrAllocNode<std::allocator<std::__detail::_Hash_node<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, true> > > const&, std::__detail::_Hash_node<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, true> const*)#2} const&)::{lambda(std::__detail::_Hash_node<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, true>*)#1}>(std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> > const&, std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::operator=(std::_Hashtable<DB::PreparedSetKey, std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, std::allocator<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> > >, std::__detail::_Select1st, std::equal_to<DB::PreparedSetKey>, DB::PreparedSetKey::Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> > const&)::{lambda(std::__detail::_ReuseOrAllocNode<std::allocator<std::__detail::_Hash_node<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, true> > > const&, std::__detail::_Hash_node<std::pair<DB::PreparedSetKey const, std::shared_ptr<DB::Set> >, true> const*)#2} const&) /usr/include/c++/9/bits/hashtable_policy.h:136
9. 0x556a51af7441 DB::ExpressionAction::execute(DB::Block&, bool) const /usr/include/c++/9/ext/atomicity.h:67
10. 0x556a51af8b55 DB::ExpressionActions::execute(DB::Block&, bool) const /usr/include/c++/9/bits/stl_iterator.h:868
11. 0x556a5198a78a DB::ExpressionBlockInputStream::readImpl() /usr/include/c++/9/bits/shared_ptr_base.h:1180
12. 0x556a51259c17 DB::IBlockInputStream::read() /usr/include/c++/9/ext/atomicity.h:49
13. 0x556a5198a76b DB::ExpressionBlockInputStream::readImpl() /usr/include/c++/9/bits/stl_map.h:497
14. 0x556a51259c17 DB::IBlockInputStream::read() /usr/include/c++/9/ext/atomicity.h:49
15. 0x556a513d1442 DB::StorageHDFS::write(std::shared_ptr<DB::IAST> const&, DB::Context const&) /usr/include/c++/9/bits/stl_vector.h:552
16. 0x556a513d1b05 DB::(anonymous namespace)::HDFSBlockOutputStream::getHeader() const /usr/include/c++/9/bits/stl_vector.h:358
17. 0x556a513d247d ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::*)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>*, std::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::*&&)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>*&&, std::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::{lambda()#1}::operator()() const /usr/include/c++/9/bits/stl_vector.h:343
18. 0x556a4e0912cc std::pair<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<GraphiteWriter, std::default_delete<GraphiteWriter> > > >, bool> std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<GraphiteWriter, std::default_delete<GraphiteWriter> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<GraphiteWriter, std::default_delete<GraphiteWriter> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<GraphiteWriter, std::default_delete<GraphiteWriter> > > > >::_M_emplace_unique<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<GraphiteWriter, std::default_delete<GraphiteWriter> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<GraphiteWriter, std::default_delete<GraphiteWriter> >&&) /usr/include/c++/9/bits/stl_tree.h:2088
19. 0x556a53dacba0 ? /usr/lib/debug/usr/bin/clickhouse
20. 0x7f75d39f06db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
21. 0x7f75d330d88f clone /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97


1 rows in set. Elapsed: 0.004 sec. 
```

**Comment by alexey-milovidov** [comment] 2020-08-27 12:26
https://github.com/ClickHouse/ClickHouse/issues/12587

**Comment by kozlek** [comment] 2020-11-21 16:15
Hi, 
I'm also having an issue that seems related to this one.
This can be reproduced without the need of any table.

```sql
SELECT 5 / nullIf(toDecimal32(0, 2), 0);
-- Division by zero ❌
```

I tried different combinations, and I found out my issue seems to be related to Decimal.

```sql
SELECT nullIf(toDecimal32(0, 2), 0);
-- output NULL, so nullIf is working properly with Decimal ✅
```

```sql
SELECT 5 / nullIf(toFloat32(0.00), 0);
-- output NULL, so it's working when using a Float instead of a Decimal
```

```sql
SELECT 5 / nullIf(toFloat32(toDecimal32(0., 2)), 0);
-- output NULL, so it's working when casting the Decimal to a Float
```

Let me know if I can help you resolving this. I haven't done C/C++ for a while, but I'm still able to test patches / build clickhouse.

**Comment by Avogar** [comment] 2021-08-17 11:34
After https://github.com/ClickHouse/ClickHouse/pull/23367 you can avoid this problem by using `if`:
```sql
SELECT if(count_dist = 0 or isNull(count_dist), Null, revenue / count_dis) FROM test_table;
SELECT if(x = 0, Null, 5 / x) from (select materialize(toDecimal32(0, 2)) as x)
```

**Closed by Avogar** 2021-08-17 11:34 UTC
Labels: bug, comp-nullable
