### ISSUE TITLE
Memory limit exceptions

### ISSUE THREAD

**Issue by jaumecastell** [ClickHouse/ClickHouse#59503] opened 2024-02-02 07:51 UTC
I'm facing an issue with latest version of clickhouse of 2023, the 23.12.

I'm having a lot of memory limit exceptions, that never recover, until I restart the clickhouse-server service.
This are my memory user.xml configurations:

<max_memory_usage>160000000000</max_memory_usage> <max_memory_usage_for_user>200000000000</max_memory_usage_for_user>

and my server memory specs:

$ free -b
total
Mem: 270209937408

This has started when I updated the clickhouse version from 23.5 to 23.12.

Also, checking the system.metrics table on clickhouse, for MemoryTracking metric, I see that it never surpasses thr 40Gb of usage.

**Comment by seandhaynes** [comment] 2024-02-02 22:31
Duplicate of: https://github.com/ClickHouse/ClickHouse/issues/59472

**Closed** 2024-02-19 09:43 UTC
Labels: potential bug
