### ISSUE TITLE
Test `03001_restore_from_old_backup_with_matview_inner_table_metadata` is flaky

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#67458] opened 2024-07-30 12:47 UTC
**Describe the bug**

https://s3.amazonaws.com/clickhouse-test-reports/66549/6f16ca02a74a81956b7524958c5f94eb7a2c7bf5/stateless_tests__debug__s3_storage__[2_2].html

**How to reproduce**

Related logs: 

```
❯ rg -Fa '{f6013066-284c-44af-9247-c0bf472fb85e}' clickhouse-server.log
9024:2024.07.29 22:34:04.489207 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> executeQuery: (from [::1]:36814) (comment: 03001_restore_from_old_backup_with_matview_inner_table_metadata.sh) RESTORE DATABASE mydb AS test_naghmrb0 FROM Disk('backups', 'test_naghmrb0/old_backup_with_matview_inner_table_metadata.zip') SETTINGS allow_different_database_def=true (stage: Complete)
9025:2024.07.29 22:34:04.489655 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Information> BackupImpl: Reading backup: Disk('backups', 'test_naghmrb0/old_backup_with_matview_inner_table_metadata.zip')
9032:2024.07.29 22:34:04.495966 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> BackupImpl: Backup Disk('backups', 'test_naghmrb0/old_backup_with_matview_inner_table_metadata.zip'): Reading metadata
9035:2024.07.29 22:34:04.499985 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> BackupImpl: Backup Disk('backups', 'test_naghmrb0/old_backup_with_matview_inner_table_metadata.zip'): Metadata was read
9036:2024.07.29 22:34:04.500682 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Will use paths in backup: "/"
9037:2024.07.29 22:34:04.500774 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Setting stage: finding tables in backup
9038:2024.07.29 22:34:04.500845 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Information> RestorerFromBackup: Will restore 0 databases and 0 tables
9040:2024.07.29 22:34:04.505074 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Setting stage: creating databases
9041:2024.07.29 22:34:04.505167 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Creating database test_naghmrb0: CREATE DATABASE IF NOT EXISTS test_naghmrb0 UUID '2ba1e060-c3d7-42ba-bbdd-98c988816f25' ENGINE = Ordinary
9042:2024.07.29 22:34:04.505307 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Setting stage: creating tables
9043:2024.07.29 22:34:04.505353 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Table test_naghmrb0.src has no dependencies (level 0)
9044:2024.07.29 22:34:04.505389 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Table test_naghmrb0.mv has 1 dependencies: test_naghmrb0.src (level 1)
9046:2024.07.29 22:34:04.505697 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Creating table test_naghmrb0.src: CREATE TABLE IF NOT EXISTS test_naghmrb0.src UUID 'cd3b93e6-9a25-4335-aef6-9d9fa58cfa51' (`Timestamp` DateTime64(9), `c1` String, `c2` String) ENGINE = MergeTree ORDER BY Timestamp SETTINGS index_granularity = 17267, min_bytes_for_wide_part = 0, ratio_of_defaults_for_sparse_serialization = 1., replace_long_file_name_to_hash = 1, max_file_name_length = 22, min_bytes_for_full_part_storage = 9669523, compact_parts_max_bytes_to_buffer = 381972343, compact_parts_max_granules_to_buffer = 1, compact_parts_merge_max_bytes_to_prefetch_part = 27327557, merge_max_block_size = 8954, prefer_fetch_merged_part_size_threshold = 10737418240, vertical_merge_algorithm_min_rows_to_activate = 1, vertical_merge_algorithm_min_columns_to_activate = 1, min_merge_bytes_to_use_direct_io = 10737418240, index_granularity_bytes = 22692628, allow_vertical_merges_from_compact_to_wide_parts = 1, cache_populated_by_fetch = 1, compress_marks = 0, compress_primary_key = 1, marks_compress_block_size = 37746, primary_key_compress_block_size = 60378
9117:2024.07.29 22:34:04.561368 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> test_naghmrb0.src (cd3b93e6-9a25-4335-aef6-9d9fa58cfa51): Loading data parts
9134:2024.07.29 22:34:04.574218 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> test_naghmrb0.src (cd3b93e6-9a25-4335-aef6-9d9fa58cfa51): There are no data parts
9136:2024.07.29 22:34:04.579246 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> AsyncLoader: Prioritize load job 'startup Atomic database test_naghmrb0': BackgrndStartup -> ForegroundLoad
9138:2024.07.29 22:34:04.579302 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> AsyncLoader: Prioritize load job 'startup Ordinary database test_naghmrb0': BackgrndStartup -> ForegroundLoad
9139:2024.07.29 22:34:04.579724 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> DatabaseAtomic (test_naghmrb0): There are 0 detached tables. Start searching non used tables.
9140:2024.07.29 22:34:04.579760 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> DatabaseAtomic (test_naghmrb0): Found 0 non used tables in detached tables.
9151:2024.07.29 22:34:04.582494 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Creating table test_naghmrb0.mv: CREATE MATERIALIZED VIEW IF NOT EXISTS test_naghmrb0.mv UUID 'e2c367fc-17af-4bcd-9af7-63fd2208dba2' TO INNER UUID 'ea3b2bc7-3f13-4243-8a11-fb7156f315ef' (`timestamp` DateTime, `c12` Nullable(String)) ENGINE = MergeTree ORDER BY timestamp SETTINGS index_granularity = 17267, min_bytes_for_wide_part = 0, ratio_of_defaults_for_sparse_serialization = 1., replace_long_file_name_to_hash = 1, max_file_name_length = 22, min_bytes_for_full_part_storage = 9669523, compact_parts_max_bytes_to_buffer = 381972343, compact_parts_max_granules_to_buffer = 1, compact_parts_merge_max_bytes_to_prefetch_part = 27327557, merge_max_block_size = 8954, prefer_fetch_merged_part_size_threshold = 10737418240, vertical_merge_algorithm_min_rows_to_activate = 1, vertical_merge_algorithm_min_columns_to_activate = 1, min_merge_bytes_to_use_direct_io = 10737418240, index_granularity_bytes = 22692628, allow_vertical_merges_from_compact_to_wide_parts = 1, cache_populated_by_fetch = 1, compress_marks = 0, compress_primary_key = 1, marks_compress_block_size = 37746, primary_key_compress_block_size = 60378 AS SELECT Timestamp AS timestamp, concat(c1, c2) AS c12 FROM test_naghmrb0.src
9327:2024.07.29 22:34:04.740388 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> test_naghmrb0.`.inner_id.e2c367fc-17af-4bcd-9af7-63fd2208dba2` (ea3b2bc7-3f13-4243-8a11-fb7156f315ef): Loading data parts
9352:2024.07.29 22:34:04.748654 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> test_naghmrb0.`.inner_id.e2c367fc-17af-4bcd-9af7-63fd2208dba2` (ea3b2bc7-3f13-4243-8a11-fb7156f315ef): There are no data parts
9361:2024.07.29 22:34:04.776240 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> DatabaseAtomic (test_naghmrb0): There are 0 detached tables. Start searching non used tables.
9363:2024.07.29 22:34:04.787822 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> DatabaseAtomic (test_naghmrb0): Found 0 non used tables in detached tables.
9374:2024.07.29 22:34:04.789170 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> DatabaseAtomic (test_naghmrb0): There are 0 detached tables. Start searching non used tables.
9375:2024.07.29 22:34:04.802360 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> DatabaseAtomic (test_naghmrb0): Found 0 non used tables in detached tables.
9377:2024.07.29 22:34:04.804226 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> RestorerFromBackup: Setting stage: inserting data to tables
14095:2024.07.29 22:34:08.529581 [ 2756 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Trace> test_naghmrb0.`.inner_id.e2c367fc-17af-4bcd-9af7-63fd2208dba2` (ea3b2bc7-3f13-4243-8a11-fb7156f315ef): Renaming temporary part tmp_restore_all_1_1_0-c96ad8ee-a206-426b-a6dc-aa4b78dbf6dc to all_1_1_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
18815:2024.07.29 22:34:15.063213 [ 3404 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Error> void DB::MetadataOperationsHolder::commitImpl(SharedMutex &): Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/disks/s3/store/cd3/cd3b93e6-9a25-4335-aef6-9d9fa58cfa51/tmp_restore_all_1_1_0-fe0e3a35-dad9-436e-9f47-7dfba2f24bfa/columns.txt: , errno: 2, strerror: No such file or directory. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
18842:2024.07.29 22:34:15.065563 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Error> BackupsWorker: Failed to restore from backup Disk('backups', 'test_naghmrb0/old_backup_with_matview_inner_table_metadata.zip'): Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/disks/s3/store/cd3/cd3b93e6-9a25-4335-aef6-9d9fa58cfa51/tmp_restore_all_1_1_0-fe0e3a35-dad9-436e-9f47-7dfba2f24bfa/columns.txt: , errno: 2, strerror: No such file or directory: While committing metadata operation #0. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
18869:2024.07.29 22:34:15.066053 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Error> executeQuery: Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/disks/s3/store/cd3/cd3b93e6-9a25-4335-aef6-9d9fa58cfa51/tmp_restore_all_1_1_0-fe0e3a35-dad9-436e-9f47-7dfba2f24bfa/columns.txt: , errno: 2, strerror: No such file or directory: While committing metadata operation #0. (FILE_DOESNT_EXIST) (version 24.8.1.702) (from [::1]:36814) (comment: 03001_restore_from_old_backup_with_matview_inner_table_metadata.sh) (in query: RESTORE DATABASE mydb AS test_naghmrb0 FROM Disk('backups', 'test_naghmrb0/old_backup_with_matview_inner_table_metadata.zip') SETTINGS allow_different_database_def=true), Stack trace (when copying this message, always include the lines below):
18896:2024.07.29 22:34:15.066749 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Error> TCPHandler: Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/disks/s3/store/cd3/cd3b93e6-9a25-4335-aef6-9d9fa58cfa51/tmp_restore_all_1_1_0-fe0e3a35-dad9-436e-9f47-7dfba2f24bfa/columns.txt: , errno: 2, strerror: No such file or directory: While committing metadata operation #0. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
18923:2024.07.29 22:34:15.066929 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> TCPHandler: Processed in 10.580223363 sec.
18924:2024.07.29 22:34:15.067046 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Debug> MemoryTracker: Peak memory usage (for query): 4.29 MiB.
```

Errors with stacktraces: 
```
2024.07.29 22:34:15.063213 [ 3404 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Error> void DB::MetadataOperationsHolder::commitImpl(SharedMutex &): Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/disks/s3/store/cd3/cd3b93e6-9a25-4335-aef6-9d9fa58cfa51/tmp_restore_all_1_1_0-fe0e3a35-dad9-436e-9f47-7dfba2f24bfa/columns.txt: , errno: 2, strerror: No such file or directory. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):

0. /build/contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x00000000160030d2
1. /build/src/Common/Exception.cpp:111: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c3f96f9
2. /build/contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000006dff14c
3. /build/src/Common/Exception.h:0: DB::ErrnoException::ErrnoException<String&>(int, int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000c451ed5
4. /build/src/Common/Exception.h:237: void DB::ErrnoException::throwFromPath<String&>(int, String const&, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000c451b82
5. /build/src/IO/WriteBufferFromFile.cpp:49: DB::WriteBufferFromFile::WriteBufferFromFile(String const&, unsigned long, int, std::shared_ptr<DB::Throttler>, unsigned int, char*, unsigned long) @ 0x000000000c547cbe
6. /build/contrib/llvm-project/libcxx/include/string:1499: std::__unique_if<DB::WriteBufferFromFile>::__unique_single std::make_unique[abi:v15007]<DB::WriteBufferFromFile, std::__fs::filesystem::path, unsigned long&, int&, std::shared_ptr<DB::Throttler> const&>(std::__fs::filesystem::path&&, unsigned long&, int&, std::shared_ptr<DB::Throttler> const&) @ 0x0000000010bf30e7
7. /build/src/Disks/DiskLocal.cpp:341: DB::DiskLocal::writeFile(String const&, unsigned long, DB::WriteMode, DB::WriteSettings const&) @ 0x0000000010bec732
8. /build/src/Disks/ObjectStorages/MetadataStorageFromDiskTransactionOperations.cpp:0: DB::WriteFileOperation::execute(std::unique_lock<DB::SharedMutex>&) @ 0x0000000010c556e1
9. /build/src/Disks/ObjectStorages/MetadataOperationsHolder.cpp:61: DB::MetadataOperationsHolder::commitImpl(DB::SharedMutex&) @ 0x0000000010c5859c
10. /build/contrib/llvm-project/libcxx/include/__functional/function.h:717: ? @ 0x0000000010c29b18
11. /build/src/IO/WriteBuffer.h:131: DB::WriteBuffer::finalize() @ 0x0000000006e15330
12. /build/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: DB::BackupImpl::copyFileToDisk(std::pair<unsigned long, wide::integer<128ul, unsigned int>> const&, std::shared_ptr<DB::IDisk>, String const&, DB::WriteMode) const @ 0x000000001068f9d2
13. /build/contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::BackupImpl::copyFileToDisk(String const&, std::shared_ptr<DB::IDisk>, String const&, DB::WriteMode) const @ 0x000000001068f460
14. /build/src/Storages/MergeTree/MergeTreeData.cpp:5683: DB::MergeTreeData::restorePartFromBackup(std::shared_ptr<DB::MergeTreeData::RestoredPartsHolder>, DB::MergeTreePartInfo const&, String const&, bool) const @ 0x00000000123b3420
15. /build/contrib/llvm-project/libcxx/include/string:1499: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTreeData::restorePartsFromBackup(DB::RestorerFromBackup&, String const&, std::optional<absl::InlinedVector<std::shared_ptr<DB::IAST>, 7ul, std::allocator<std::shared_ptr<DB::IAST>>>> const&)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x00000000123dfcfc
16. /build/contrib/llvm-project/libcxx/include/__functional/function.h:863: ? @ 0x000000001066ce8a
17. /build/contrib/llvm-project/libcxx/include/future:2069: std::packaged_task<void ()>::operator()() @ 0x000000000c927d97
18. /build/base/base/../base/wide_integer_impl.h:817: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000c49ee26
19. /build/src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x000000000c4a2251
20. /build/base/base/../base/wide_integer_impl.h:817: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000c49c3d6
21. /build/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c4a0805
22. ? @ 0x00007f9784442ac3
23. ? @ 0x00007f97844d4850
 (version 24.8.1.702)
2024.07.29 22:34:15.065563 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Error> BackupsWorker: Failed to restore from backup Disk('backups', 'test_naghmrb0/old_backup_with_matview_inner_table_metadata.zip'): Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/disks/s3/store/cd3/cd3b93e6-9a25-4335-aef6-9d9fa58cfa51/tmp_restore_all_1_1_0-fe0e3a35-dad9-436e-9f47-7dfba2f24bfa/columns.txt: , errno: 2, strerror: No such file or directory: While committing metadata operation #0. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):

0. /build/contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x00000000160030d2
1. /build/src/Common/Exception.cpp:111: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c3f96f9
2. /build/contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000006dff14c
3. /build/src/Common/Exception.h:0: DB::ErrnoException::ErrnoException<String&>(int, int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000c451ed5
4. /build/src/Common/Exception.h:237: void DB::ErrnoException::throwFromPath<String&>(int, String const&, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000c451b82
5. /build/src/IO/WriteBufferFromFile.cpp:49: DB::WriteBufferFromFile::WriteBufferFromFile(String const&, unsigned long, int, std::shared_ptr<DB::Throttler>, unsigned int, char*, unsigned long) @ 0x000000000c547cbe
6. /build/contrib/llvm-project/libcxx/include/string:1499: std::__unique_if<DB::WriteBufferFromFile>::__unique_single std::make_unique[abi:v15007]<DB::WriteBufferFromFile, std::__fs::filesystem::path, unsigned long&, int&, std::shared_ptr<DB::Throttler> const&>(std::__fs::filesystem::path&&, unsigned long&, int&, std::shared_ptr<DB::Throttler> const&) @ 0x0000000010bf30e7
7. /build/src/Disks/DiskLocal.cpp:341: DB::DiskLocal::writeFile(String const&, unsigned long, DB::WriteMode, DB::WriteSettings const&) @ 0x0000000010bec732
8. /build/src/Disks/ObjectStorages/MetadataStorageFromDiskTransactionOperations.cpp:0: DB::WriteFileOperation::execute(std::unique_lock<DB::SharedMutex>&) @ 0x0000000010c556e1
9. /build/src/Disks/ObjectStorages/MetadataOperationsHolder.cpp:61: DB::MetadataOperationsHolder::commitImpl(DB::SharedMutex&) @ 0x0000000010c5859c
10. /build/contrib/llvm-project/libcxx/include/__functional/function.h:717: ? @ 0x0000000010c29b18
11. /build/src/IO/WriteBuffer.h:131: DB::WriteBuffer::finalize() @ 0x0000000006e15330
12. /build/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: DB::BackupImpl::copyFileToDisk(std::pair<unsigned long, wide::integer<128ul, unsigned int>> const&, std::shared_ptr<DB::IDisk>, String const&, DB::WriteMode) const @ 0x000000001068f9d2
13. /build/contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::BackupImpl::copyFileToDisk(String const&, std::shared_ptr<DB::IDisk>, String const&, DB::WriteMode) const @ 0x000000001068f460
14. /build/src/Storages/MergeTree/MergeTreeData.cpp:5683: DB::MergeTreeData::restorePartFromBackup(std::shared_ptr<DB::MergeTreeData::RestoredPartsHolder>, DB::MergeTreePartInfo const&, String const&, bool) const @ 0x00000000123b3420
15. /build/contrib/llvm-project/libcxx/include/string:1499: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTreeData::restorePartsFromBackup(DB::RestorerFromBackup&, String const&, std::optional<absl::InlinedVector<std::shared_ptr<DB::IAST>, 7ul, std::allocator<std::shared_ptr<DB::IAST>>>> const&)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x00000000123dfcfc
16. /build/contrib/llvm-project/libcxx/include/__functional/function.h:863: ? @ 0x000000001066ce8a
17. /build/contrib/llvm-project/libcxx/include/future:2069: std::packaged_task<void ()>::operator()() @ 0x000000000c927d97
18. /build/base/base/../base/wide_integer_impl.h:817: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000c49ee26
19. /build/src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x000000000c4a2251
20. /build/base/base/../base/wide_integer_impl.h:817: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000c49c3d6
21. /build/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c4a0805
22. ? @ 0x00007f9784442ac3
23. ? @ 0x00007f97844d4850
 (version 24.8.1.702)
2024.07.29 22:34:15.066053 [ 2659 ] {f6013066-284c-44af-9247-c0bf472fb85e} <Error> executeQuery: Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/disks/s3/store/cd3/cd3b93e6-9a25-4335-aef6-9d9fa58cfa51/tmp_restore_all_1_1_0-fe0e3a35-dad9-436e-9f47-7dfba2f24bfa/columns.txt: , errno: 2, strerror: No such file or directory: While committing metadata operation #0. (FILE_DOESNT_EXIST) (version 24.8.1.702) (from [::1]:36814) (comment: 03001_restore_from_old_backup_with_matview_inner_table_metadata.sh) (in query: RESTORE DATABASE mydb AS test_naghmrb0 FROM Disk('backups', 'test_naghmrb0/old_backup_with_matview_inner_table_metadata.zip') SETTINGS allow_different_database_def=true), Stack trace (when copying this message, always include the lines below):

0. /build/contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x00000000160030d2
1. /build/src/Common/Exception.cpp:111: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c3f96f9
2. /build/contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000006dff14c
3. /build/src/Common/Exception.h:0: DB::ErrnoException::ErrnoException<String&>(int, int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000c451ed5
4. /build/src/Common/Exception.h:237: void DB::ErrnoException::throwFromPath<String&>(int, String const&, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000c451b82
5. /build/src/IO/WriteBufferFromFile.cpp:49: DB::WriteBufferFromFile::WriteBufferFromFile(String const&, unsigned long, int, std::shared_ptr<DB::Throttler>, unsigned int, char*, unsigned long) @ 0x000000000c547cbe
6. /build/contrib/llvm-project/libcxx/include/string:1499: std::__unique_if<DB::WriteBufferFromFile>::__unique_single std::make_unique[abi:v15007]<DB::WriteBufferFromFile, std::__fs::filesystem::path, unsigned long&, int&, std::shared_ptr<DB::Throttler> const&>(std::__fs::filesystem::path&&, unsigned long&, int&, std::shared_ptr<DB::Throttler> const&) @ 0x0000000010bf30e7
7. /build/src/Disks/DiskLocal.cpp:341: DB::DiskLocal::writeFile(String const&, unsigned long, DB::WriteMode, DB::WriteSettings const&) @ 0x0000000010bec732
8. /build/src/Disks/ObjectStorages/MetadataStorageFromDiskTransactionOperations.cpp:0: DB::WriteFileOperation::execute(std::unique_lock<DB::SharedMutex>&) @ 0x0000000010c556e1
9. /build/src/Disks/ObjectStorages/MetadataOperationsHolder.cpp:61: DB::MetadataOperationsHolder::commitImpl(DB::SharedMutex&) @ 0x0000000010c5859c
10. /build/contrib/llvm-project/libcxx/include/__functional/function.h:717: ? @ 0x0000000010c29b18
11. /build/src/IO/WriteBuffer.h:131: DB::WriteBuffer::finalize() @ 0x0000000006e15330
12. /build/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: DB::BackupImpl::copyFileToDisk(std::pair<unsigned long, wide::integer<128ul, unsigned int>> const&, std::shared_ptr<DB::IDisk>, String const&, DB::WriteMode) const @ 0x000000001068f9d2
13. /build/contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::BackupImpl::copyFileToDisk(String const&, std::shared_ptr<DB::IDisk>, String const&, DB::WriteMode) const @ 0x000000001068f460
14. /build/src/Storages/MergeTree/MergeTreeData.cpp:5683: DB::MergeTreeData::restorePartFromBackup(std::shared_ptr<DB::MergeTreeData::RestoredPartsHolder>, DB::MergeTreePartInfo const&, String const&, bool) const @ 0x00000000123b3420
15. /build/contrib/llvm-project/libcxx/include/string:1499: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTreeData::restorePartsFromBackup(DB::RestorerFromBackup&, String const&, std::optional<absl::InlinedVector<std::shared_ptr<DB::IAST>, 7ul, std::allocator<std::shared_ptr<DB::IAST>>>> const&)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x00000000123dfcfc
16. /build/contrib/llvm-project/libcxx/include/__functional/function.h:863: ? @ 0x000000001066ce8a
17. /build/contrib/llvm-project/libcxx/include/future:2069: std::packaged_task<void ()>::operator()() @ 0x000000000c927d97
18. /build/base/base/../base/wide_integer_impl.h:817: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000c49ee26
19. /build/src/Common/ThreadPool.cpp:0: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x000000000c4a2251
20. /build/base/base/../base/wide_integer_impl.h:817: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000c49c3d6
21. /build/contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c4a0805
22. ? @ 0x00007f9784442ac3
23. ? @ 0x00007f97844d4850
```

**Comment by nikitamikhaylov** [comment] 2024-07-30 13:37
Maybe same issue? https://github.com/ClickHouse/ClickHouse/issues/67220

**Comment by vitlibar** [comment] 2024-07-30 19:29
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/67220

**Closed** 2024-07-30 19:30 UTC
Labels: testing, flaky test
