### ISSUE TITLE
The system.trace_log table was not created

### ISSUE THREAD

**Issue by zcw5116** [ClickHouse/ClickHouse#10030] opened 2020-04-03 02:02 UTC
version : 20.1.4

The description of the system.trace_log table in the official document of ClickHouse is as follows:ClickHouse creates this table when the trace_log server configuration section is set。

The default server configuration file `config.xml` contains the following settings section:
``` 

  <trace_log>
        <database>system</database>
        <table>trace_log</table>
        <partition_by>toYYYYMM(event_date)</partition_by>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </trace_log>

```

However， when I query the system.trace_log table, it prompts that this table does not exist。

I don't know what's wrong，thank you.

**Comment by filimonov** [comment] 2020-04-03 15:18
Exact duplicate of https://github.com/ClickHouse/ClickHouse/issues/7767#issuecomment-554306202

**Closed by filimonov** 2020-04-03 15:18 UTC
Labels: duplicate, question
