### ISSUE TITLE
Apply compression (utils/self-extracting-executable/compressor) to clickhouse executable

### ISSUE THREAD

**Issue by yakov-olkhovskiy** [ClickHouse/ClickHouse#38293] opened 2022-06-21 21:17 UTC
**Use case**
To make downloadable file smaller.

**Describe the solution you'd like**
Apply compression either as a build step or on deployment to repository.

**Comment by alexey-milovidov** [comment] 2022-06-22 05:09
Duplicate of #34755.

**Closed** 2022-06-22 05:10 UTC
Labels: duplicate, feature
