### ISSUE TITLE
Distributed Sends got stuck

### ISSUE THREAD

**Issue by wedi-dev** [ClickHouse/ClickHouse#18369] opened 2020-12-22 13:51 UTC
We have big problem in one of our production nodes. The data in Distribution Table is not send to the Data Tables. We had to change weight of shards which consisted of that node and detached that node from LB. We ended with 30GB of data in Distributed Table and it was not send for over 5 days. We investigated that Clickhouse tries to process those files and send them but it ends with "Cannot read all data. Bytes read: 27523. Bytes expected: 35560. (version 20.3.8.53 (official build))"

Then we checked bin files with clickhouse-local using engine=File(Distributed) to open those files and we got same error. There are 1,1mln bin files and 300 of them are broken and freezes Distributed Sends. 

Why Clickhouse does not move those files to the broken Directory but gets stucked?

version 20.3.8.53 (official build)

**Expected behavior**
Broken bin files moved to broken and Distributed Sends continue for valid bin files

**Error message and/or stacktrace**
```
clickhouse-local -q "create table table (date Date) engine=File(Distributed, '76914002.bin'); select * from table limit 1" --format Vertical
Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 27523. Bytes expected: 35560. (version 20.3.8.53 (official build))
```

**Comment by den-crane** [comment] 2020-12-22 14:41
You should upgrade to 20.3.21.2

**Comment by wedi-dev** [comment] 2020-12-22 15:02
We have tested those bin files on ClickHouse server version 20.12.3 revision 54442 with the same result - only manual deletion of broken bin files unlocked Distributed Sends.

**Comment by filimonov** [comment] 2020-12-23 04:47
@azat that's the same issue we were Talking about. We need a checksums checks in the sender side.

**Comment by azat** [comment] 2021-01-02 19:49
>We have big problem in one of our production nodes

Interesting. And you reproduced the problem with 20.12? Or you just upgrade the clickhouse and it starts processing existing files?

>Why Clickhouse does not move those files to the broken Directory but gets stucked?

Can you provide full stacktrace?
Error from the provided logs should mark the file as broken.

>@azat that's the same issue we were talking about. We need checksums checks at the sender side.

Yes, this will help.
But corruption is also a problem, so yes, Distributed engine should support fsync.

**Comment by azat** [comment] 2021-01-03 11:01
>We ended with 30GB of data in Distributed Table and it was not send for over 5 days
> <snip>
>. There are 1,1mln bin files and 300 of them are broken and freezes Distributed Sends.

@wedi-dev Also it looks like you should use `distributed_directory_monitor_batch_inserts` to avoid too much files

>Error from the provided logs should mark the file as broken.

I've verified one more time and even if the initiator/sender does not checks the checksum the remote side should send the exception back and sender will rethrow the same exception, and the batch should be marked as broken.

By the way, in addition to stack trace, can you also send `select name, value from system.settings where changed` (for the system/default profile).

**Comment by filimonov** [comment] 2021-01-03 17:35
> I've verified one more time and even if the initiator/sender does not checks the checksum the remote side should send the exception back and sender will rethrow the same exception, and the batch should be marked as broken.

Reciever never send an exception if sender has file smaller than it should be.

**Comment by wedi-dev** [comment] 2021-01-04 15:26
> Interesting. And you reproduced the problem with 20.12? Or you just upgrade the clickhouse and it starts processing existing files?

We have run temporary cluster with same config and same cluser version (after suggestion about clickhouse version we have tried also with newest version) and copied those .bin files to Distiributed Directory. We've been monitoring opened .bin files by clickhouse-server process, when file was opened longer than X sec. we deleted that file. This way we got list of broken files which freezed Distributed Sends. 

> Can you provide full stacktrace?
> Error from the provided logs should mark the file as broken.

This is an error from target host:

```
2020.12.22 00:55:33.755828 [ 94842 ] {19383d0f-9c0e-40ff-b387-70b015bea7ec} <Error> executeQuery: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 7081. Bytes expected: 8734. (version 20.12.3.3 (official build)) (from [::ffff:XXX.XXX.XXX.XXX]:56450) (in query: INSERT INTO xxxx (<list_of_columns>) VALUES), Stack trace (when copying this message, always include the lines below):

0. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0x7d16ca5 in /usr/bin/clickhouse
1. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&) @ 0xd6645ea in /usr/bin/clickhouse
2. DB::CompressedReadBuffer::nextImpl() @ 0xd663e10 in /usr/bin/clickhouse
3. DB::NativeBlockInputStream::readImpl() @ 0xddccf16 in /usr/bin/clickhouse
4. DB::IBlockInputStream::read() @ 0xd72fa05 in /usr/bin/clickhouse
5. DB::TCPHandler::receiveData(bool) @ 0xe5cb811 in /usr/bin/clickhouse
6. DB::TCPHandler::receivePacket() @ 0xe5c4cfc in /usr/bin/clickhouse
7. DB::TCPHandler::readDataNext(unsigned long const&, int const&) @ 0xe5c648f in /usr/bin/clickhouse
8. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0xe5c523e in /usr/bin/clickhouse
9. DB::TCPHandler::runImpl() @ 0xe5c0849 in /usr/bin/clickhouse
10. DB::TCPHandler::run() @ 0xe5ccb67 in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x10d76a3f in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x10d78451 in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0x10ea5a29 in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x10ea19ba in /usr/bin/clickhouse
15. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
16. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
```

There is no mention which .bin file causes the problem. No error from the host which stores .bin files. So he had no clue which file was a problem.

**Comment by wedi-dev** [comment] 2021-01-04 15:32
> @wedi-dev Also it looks like you should use `distributed_directory_monitor_batch_inserts` to avoid too much files

Thanks we will sure do that.

> I've verified one more time and even if the initiator/sender does not checks the checksum the remote side should send the exception back and sender will rethrow the same exception, and the batch should be marked as broken.

We didn't find any mention about .bin files in error logs on sender neither on remote.

> By the way, in addition to stack trace, can you also send `select name, value from system.settings where changed` (for the system/default profile).

```
┌─name───────────────────┬─value───────┐
│ use_uncompressed_cache │ 0           │
│ load_balancing         │ random      │
│ log_queries            │ 1           │
│ max_memory_usage       │ 10000000000 │
└────────────────────────┴─────────────┘
```

**Comment by azat** [comment] 2021-01-05 15:25
>Reciever never send an exception if sender has file smaller than it should be.

@filimonov Receiver verifies checksum for each block, but yes you may be lucky enough to break on block boundary and in this case it can simply ignore that not all data was sent.
But this will not be solved by checking checksum on the sender.

> We've been monitoring opened .bin files by clickhouse-server process, when file was opened longer than X sec. we deleted that file.

@wedi-dev pretty complex, you can simply do smth like this:

```sql
system stop distributed sends dist_table;
insert into dist_table values (...);
```

```sh
truncate -s$offset /path/to/.bin
```

```sql
system start distributed sends dist_table;
```

>This is an error from target host:

So this is an error from the receiver, and this error should be send back to the sender.

*NOTE: you don't have debug symbols installed, stack traces more verbose and useful with debug symbols, so if you can it worth install `clickhouse-common-static-dbg` package, but this requires server restart for now*

>We didn't find any mention about .bin files in error logs on sender neither on remote.

Indeed, there are no details about which .bin file failed, but there are message smth like `Started processing ...` before an error, can you post the relevant part of the log from the sender? (from `Started processing` to an error message, but note that `Started processing` messages will not be include into the error log)

**Comment by filimonov** [comment] 2021-01-05 20:23
> > Reciever never send an exception if sender has file smaller than it should be.
> 
> @filimonov Receiver verifies checksum for each block, but yes you may be lucky enough to break on block boundary and in this case it can simply ignore that not all data was sent.

It's much simpler. Sender sent everything it had (whole file, which is actually 70% of proper size). Reciever expect more bytes to get after receiving 70% (because file header has length prefix) and wait forever till timeout. Both see only disconnects due timeout and do retries forever.

**Comment by azat** [comment] 2021-01-08 00:35
>because file header has length prefix

No the header, but each compressed block, but yes.

**Comment by filimonov** [comment] 2021-01-15 14:26
Fixed in  #18853

**Closed by filimonov** 2021-01-15 14:26 UTC
Labels: bug, comp-distributed

**Comment by sliontc** [comment] 2021-02-10 02:54
When I use MaterializeMySQL Engine, I also got the error. Any help?

**Comment by azat** [comment] 2021-02-10 04:55
@sliontc What error do you have?
Can you post the error with the stacktrace included? (and also post the structure of the related tables)

**Comment by sliontc** [comment] 2021-02-10 14:25
> @sliontc What error do you have?
> Can you post the error with the stacktrace included? (and also post the structure of the related tables)

I use the MaterializeMySQL Engine to replicate data from MySQL. At the beginning, I can got select query executed and data returned. But later when execute select query, the following error occured:

2021.02.10 16:35:18.176668 [ 37494 ] {e84e9a7c-b5c7-4d9d-afab-57e35cb3c7c1} <Error> DynamicQueryHandler: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 7933. Bytes expected: 11571., Stack trace (when copying this message, always include the lines below):

0. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0x7dc0ca5 in /usr/bin/clickhouse
1. DB::MySQLReplication::RowsEvent::parseRow(DB::ReadBuffer&, boost::dynamic_bitset<unsigned long, std::__1::allocator<unsigned long> >&) @ 0xdca1125 in /usr/bin/clickhouse
2. DB::MySQLReplication::RowsEvent::parseImpl(DB::ReadBuffer&) @ 0xdca057f in /usr/bin/clickhouse
3. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0xdca4b33 in /usr/bin/clickhouse
4. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0xdc8d0e2 in /usr/bin/clickhouse
5. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0xdc8dbd3 in /usr/bin/clickhouse
6. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdcb79e6 in /usr/bin/clickhouse
7. ? @ 0xdcd635a in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7dc5b3d in /usr/bin/clickhouse
9. ? @ 0x7dc96f3 in /usr/bin/clickhouse
10. start_thread @ 0x7dc5 in /usr/lib64/libpthread-2.17.so
11. __clone @ 0xf773d in /usr/lib64/libc-2.17.so

**Comment by azat** [comment] 2021-02-10 20:16
@sliontc this is completely different issue, it is better to create new issue for this problem.
