### ISSUE TITLE
Checksums of parts don't match after update to 19.13 from 19.9

### ISSUE THREAD

**Issue by astudnev** [ClickHouse/ClickHouse#6472] opened 2019-08-13 16:31 UTC
I added 2 servers to cluster where all machines were on 19.9 and installed 19.13 there.

First, there appears to be a lot of such messages in the log of 19.9 machines:

2019.08.13 14:46:24.793856 [ 11 ] {} <Error> ethereum.transfers_flow_from: Code: 40, e.displayText() = DB::Exception: Checksums of parts don't match: hash of uncompressed files doesn't match (version 19.9.2.4 (official build)). Data after merge is not byte-identical to data on another replicas. There could be several reasons: 1. Using newer version of compression library after server update. 2. Using another compression method. 3. Non-deterministic compression algorithm (highly unlikely). 4. Non-deterministic merge algorithm due to logical error in code. 5. Data corruption in memory due to bug in code. 6. Data corruption in memory due to hardware issue. 7. Manual modification of source data after server startup. 8. Manual modification of checksums stored in ZooKeeper. We will download merged part from replica to force byte-identical result.

Second, the ALTER TABLE DELETE WHERE failed on this cluster with messages as

<Error> ethereum.transfers_flow_to: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 226, e.displayText() = DB::Exception: Marks file '/var/lib/clickhouse/data/ethereum/transfers_flow_to/tmp_fetch_all_39936_43139_14/block.mrk' doesn't exist

**Comment by alesapin** [comment] 2019-08-14 11:41
Have you recreated this table on new version?

**Comment by astudnev** [comment] 2019-08-14 11:42
> Have you recreated this table on new version?

no. I downgraded to 19.9 and recreated the table to fix it

**Comment by 360developer** [comment] 2019-08-15 06:49
We also tried to upgrade from 19.4.1.3 to 19.13.1.11 and found the same error in the logs.
2019.08.11 12:56:23.395080 [ 14 ] {} <Error> events.custom_properties_local: Code: 40, e.displayText() = DB::Exception: Checksums of parts don't match: hash of uncompressed files doesn't match (version 19.13.1.11 (official build)). Data after merge is not byte-identical to data on another replicas. There could be several reasons: 1. Using newer version of compression library after server update. 2. Using another compression method. 3. Non-deterministic compression algorithm (highly unlikely). 4. Non-deterministic merge algorithm due to logical error in code. 5. Data corruption in memory due to bug in code. 6. Data corruption in memory due to hardware issue. 7. Manual modification of source data after server startup. 8. Manual modification of checksums stored in ZooKeeper. We will download merged part from replica to force byte-identical result.

**Comment by den-crane** [comment] 2019-08-15 18:43
@360developer 
>We also tried to upgrade from 19.4.1.3 to 19.13.1.11 and found the same error in the logs.

LZ4 compression library were updated in 19.7. 
19.6- & 19.7+ are incompatible because they create different LZ4 binary output with not matching Checksums

**Comment by alexey-milovidov** [comment] 2019-08-18 17:37
> Checksums of parts don't match: hash of uncompressed files doesn't match

This is not an error. No actions required.

**Comment by alexey-milovidov** [comment] 2019-08-18 17:44
`Checksums of parts don't match ... We will download merged part from replica to force byte-identical result.`

No actions required.

**Comment by 360developer** [comment] 2019-08-19 07:41
@alexey-milovidov
> No actions required.
Does this mean that we can update each instance of our cluster separately? Once all nodes have been updated the `Checksum of parts` message should be gone, right?

Thanks a lot. And also many thanks for creating such a wonderful database!

**Comment by xmariachi** [comment] 2019-09-04 15:59
I'm finding this issue too. I have two replicas. One of them is showing it at a rate of 13 occurrences per minute, and the other one at a rate of 15 per hour. 

Servers have different versions (by mistake): 
 -  Connected to ClickHouse server version 19.13.3 revision 54425
 -  Connected to ClickHouse server version 19.5.3 revision 54417.

May it be caused by a different compression library on each? What is the recommended course of action from this point - just upgrading one server to match the newer one? 

```
2019.09.04 15:31:21.746431 [ 3 ] {} <Error> divvit_1.visitors: Code: 40, e.displayText() = DB::Exception: Checksums of parts don't match: hash of uncompressed files doesn't match (version 19.13.3.26 (official build)). Data after merge is not byte-identical to data on another replicas. There could be several reasons: 
1. Using newer version of compression library after server update. 
2. Using another compression method. 
3. Non-deterministic compression algorithm (highly unlikely). 
4. Non-deterministic merge algorithm due to logical error in code. 
5. Data corruption in memory due to bug in code. 
6. Data corruption in memory due to hardware issue. 
7. Manual modification of source data after server startup. 
8. Manual modification of checksums stored in ZooKeeper. We will download merged part from replica to force byte-identical result.
```

**Comment by alexey-milovidov** [comment] 2019-09-04 16:23
@xmariachi Yes, you should upgrade the remaining replicas.

**Comment by xmariachi** [comment] 2019-09-05 17:39
> @xmariachi Yes, you should upgrade the remaining replicas.

Yep, I no longer see the message. Thanks.

**Closed** 2020-04-08 07:40 UTC
Labels: bug, obsolete-version

**Comment by sifan0212** [comment] 2020-10-30 07:16
HI,  I also have this problem, too. My cluster have 2 shards, each shard have 2 replicas. Version of server is v20.9.2.20. (already latest stable version)

2020.10.30 14:52:04.927336 [ 103 ] {} <Error>xxxxxxxx.`.inner.xxxxxxxx`: Code: 40, e.displayText() = DB::Exception: Checksums of parts don't match: hash of uncompressed files doesn't match (version 20.9.2.20 (official build)). Data after merge is not byte-identical to data on another replicas. There could be several reasons: 1. Using newer version of compression library after server update. 2. Using another compression method. 3. Non-deterministic compression algorithm (highly unlikely). 4. Non-deterministic merge algorithm due to logical error in code. 5. Data corruption in memory due to bug in code. 6. Data corruption in memory due to hardware issue. 7. Manual modification of source data after server startup. 8. Manual modification of checksums stored in ZooKeeper. 9. Part format related settings like 'enable_mixed_granularity_parts' are different on different replicas. We will download merged part from replica to force byte-identical result.

What should i do ? 

Thank you.

**Comment by den-crane** [comment] 2020-10-30 13:10
@sifan0212   you should upgrade all nodes to 20.9.2.20

**Comment by sifan0212** [comment] 2020-10-30 13:47
> @sifan0212 you should upgrade all nodes to 20.9.2.20

All nodes start from same docker images and have the same version(20.9.2.20).
