### ISSUE TITLE
"GRANT REMOTE" doesn't work for role

### ISSUE THREAD

**Issue by lavasser** [ClickHouse/ClickHouse#35070] opened 2022-03-05 07:35 UTC
Hello!

Clichouse 22.2.2.1

There is a user **ch_user**
There is a role **ch_role**
Role **ch_role** assigned to user **ch_user**.

I assign privileges to create a table Distributed: **GRANT REMOTE ON \*.\* TO ch_role**. But get exeption "Not enougt privileges".
If I assign privileges to user **GRANT REMOTE ON \*.\* TO ch_user**, then the table is created successfully.

Is this normal behavior?

**Comment by vitlibar** [comment] 2022-03-06 08:52
It works for me. What is the full error message? (Normally it says in the error message which grant is necessary).

**Comment by lavasser** [comment] 2022-03-09 11:11
![image](https://user-images.githubusercontent.com/16194498/157430273-57c1daf1-a55f-4ea3-b87f-b27163f51375.png)

**Comment by kocmuk58** [comment] 2022-03-24 06:49
@vitlibar, I have a similar problem as @lavasser

**Comment by m1khal3v** [comment] 2023-06-30 14:23
Reproduced on 23.3.4.17

```
CREATE ROLE foobar_rw;
GRANT SELECT ON foobar.* TO foobar_rw;
GRANT INSERT ON foobar.* TO foobar_rw;
GRANT CREATE TABLE ON foobar.* TO foobar_rw;
GRANT CREATE VIEW ON foobar.* TO foobar_rw;

GRANT DROP TABLE ON foobar.* TO foobar_rw;
GRANT DROP VIEW ON foobar.* TO foobar_rw;
GRANT ALTER TABLE ON foobar.* TO foobar_rw;
GRANT ALTER VIEW ON foobar.* TO foobar_rw;
GRANT TRUNCATE ON foobar.* TO foobar_rw;

CREATE USER foobar_writer HOST ANY IDENTIFIED WITH plaintext_password BY 'P4$$WORD' DEFAULT ROLE ALL;
GRANT foobar_rw TO foobar_writer;

-- ADD NEW GRANT FOR ROLE

GRANT OPTIMIZE ON foobar.* TO foobar_rw;

OPTIMIZE TABLE foobar.beans

Not enough privileges. To execute this query it's necessary to have grant OPTIMIZE ON foobar.beans
```

**Comment by den-crane** [comment] 2023-06-30 14:28
duplicate of https://github.com/ClickHouse/ClickHouse/issues/34412

**Closed** 2024-09-21 22:13 UTC
Labels: duplicate, unexpected behaviour, comp-rbac
