### ISSUE TITLE
Abort in `Transaction::commit` if table has replica = {shard}_{replica}

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#45938] opened 2023-02-02 01:13 UTC
```sql
cat /etc/clickhouse-server/config.d/macros.xml
<?xml version="1.0" ?>
<clickhouse>
    <macros>
        <cluster>test</cluster>
        <replica>r1</replica>
        <shard>1</shard>
    </macros>
</clickhouse>

CREATE TABLE tt ( d Int32)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/{cluster}/tables/test', '{shard}_{replica}')
ORDER BY (d);

insert into tt select 1;        



[clickhouse] 2023.02.02 01:11:27.913217 [ 2216278 ] <Fatal> BaseDaemon: ########################################
[clickhouse] 2023.02.02 01:11:27.913292 [ 2216278 ] <Fatal> BaseDaemon: (version 23.1.2.9 (official build), build id: 0A67B582AE62368899919CE615BE3F31E773A1A5) (from thread 2216276) (query_id: 024a3926-4178-4a3e-977a-91d2438e26b8) (query: insert into tt select 1;) Received signal Aborted (6)
[clickhouse] 2023.02.02 01:11:27.913322 [ 2216278 ] <Fatal> BaseDaemon:
[clickhouse] 2023.02.02 01:11:27.913342 [ 2216278 ] <Fatal> BaseDaemon: Stack trace: 0xffffa2656d78 0xffffa2643aac 0xaaaaf5eec97c 0xaaaafe144eac 0xaaaafe144e18 0xaaaafb117ef4 0xaaaafb3f53f4 0xaaaafb3e6178 0xaaaafb3e3e4c 0xaaaafb3e2858 0xaaaafb85b830 0xaaaafb775e34 0xaaaafb775b58 0xaaaafb77547c 0xaaaafb5bf280 0xaaaafb5b51ec 0xaaaafb5b4474 0xaaaafb5b416c 0xaaaafb5b3170 0xaaaaf5d9cca8 0xaaaaf5da1868 0xffffa279d624 0xffffa26f449c
[clickhouse] 2023.02.02 01:11:27.913389 [ 2216278 ] <Fatal> BaseDaemon: 2. raise @ 0x33d78 in /usr/lib/aarch64-linux-gnu/libc-2.31.so
[clickhouse] 2023.02.02 01:11:27.913414 [ 2216278 ] <Fatal> BaseDaemon: 3. abort @ 0x20aac in /usr/lib/aarch64-linux-gnu/libc-2.31.so
[clickhouse] 2023.02.02 01:11:27.913442 [ 2216278 ] <Fatal> BaseDaemon: 4. ? @ 0xbd1c97c in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913462 [ 2216278 ] <Fatal> BaseDaemon: 5. ? @ 0x13f74eac in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913483 [ 2216278 ] <Fatal> BaseDaemon: 6. std::terminate() @ 0x13f74e18 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913507 [ 2216278 ] <Fatal> BaseDaemon: 7. DB::MergeTreeData::Transaction::commit(std::__1::unique_lock<std::__1::mutex>*) @ 0x10f47ef4 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913532 [ 2216278 ] <Fatal> BaseDaemon: 8. ? @ 0x112253f4 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913556 [ 2216278 ] <Fatal> BaseDaemon: 9. DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, bool) @ 0x11216178 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913575 [ 2216278 ] <Fatal> BaseDaemon: 10. DB::ReplicatedMergeTreeSinkImpl<false>::finishDelayedChunk(std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&) @ 0x11213e4c in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913605 [ 2216278 ] <Fatal> BaseDaemon: 11. DB::ReplicatedMergeTreeSinkImpl<false>::consume(DB::Chunk) @ 0x11212858 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913641 [ 2216278 ] <Fatal> BaseDaemon: 12. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x1168b830 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913672 [ 2216278 ] <Fatal> BaseDaemon: 13. ? @ 0x115a5e34 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913705 [ 2216278 ] <Fatal> BaseDaemon: 14. ? @ 0x115a5b58 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913736 [ 2216278 ] <Fatal> BaseDaemon: 15. DB::ExceptionKeepingTransform::work() @ 0x115a547c in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913770 [ 2216278 ] <Fatal> BaseDaemon: 16. DB::ExecutionThreadContext::executeTask() @ 0x113ef280 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913803 [ 2216278 ] <Fatal> BaseDaemon: 17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x113e51ec in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913840 [ 2216278 ] <Fatal> BaseDaemon: 18. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x113e4474 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913913 [ 2216278 ] <Fatal> BaseDaemon: 19. DB::PipelineExecutor::execute(unsigned long) @ 0x113e416c in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.913951 [ 2216278 ] <Fatal> BaseDaemon: 20. ? @ 0x113e3170 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.914759 [ 2216278 ] <Fatal> BaseDaemon: 21. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xbbccca8 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.914797 [ 2216278 ] <Fatal> BaseDaemon: 22. ? @ 0xbbd1868 in /usr/bin/clickhouse
[clickhouse] 2023.02.02 01:11:27.914839 [ 2216278 ] <Fatal> BaseDaemon: 23. start_thread @ 0x7624 in /usr/lib/aarch64-linux-gnu/libpthread-2.31.so
[clickhouse] 2023.02.02 01:11:27.914875 [ 2216278 ] <Fatal> BaseDaemon: 24. ? @ 0xd149c in /usr/lib/aarch64-linux-gnu/libc-2.31.so
[clickhouse] 2023.02.02 01:11:27.914903 [ 2216278 ] <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
```

**Comment by den-crane** [comment] 2023-02-02 01:20
I made a mistake it seems.

**Comment by alexey-milovidov** [comment] 2023-02-02 01:21
@den-crane, why closed?

Note: this "abort" is the result of `std::terminate` call that is done as a protection from misconfiguration. Let's copy the exception message from the log a few lines above.

**Comment by den-crane** [comment] 2023-02-02 01:22
I closed it for now. Because I don't understand what is going on.

**Comment by den-crane** [comment] 2023-02-20 21:27
@tavplubix  it seems that 23.1.2.9 crashes if `implicit_transaction=1` and insert is in Replicated table.

```
2023.02.20 21:24:01.578884 [ 2560671 ] {e8eaea58-3ba0-4c7a-b253-42c8335d432d} <Trace> ContextAccess (default): Access granted: INSERT(d) ON default.tt
2023.02.20 21:24:01.579018 [ 2560671 ] {e8eaea58-3ba0-4c7a-b253-42c8335d432d} <Trace> ContextAccess (default): Access granted: SELECT(dummy) ON system.one
2023.02.20 21:24:01.579054 [ 2560671 ] {e8eaea58-3ba0-4c7a-b253-42c8335d432d} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2023.02.20 21:24:01.579857 [ 2560934 ] {e8eaea58-3ba0-4c7a-b253-42c8335d432d} <Trace> default.tt (76e9568f-6150-41f2-91d8-aa4880d2a9a9): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2023.02.20 21:24:01.579895 [ 2560934 ] {e8eaea58-3ba0-4c7a-b253-42c8335d432d} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 153.91 GiB.
2023.02.20 21:24:01.585081 [ 2560934 ] {e8eaea58-3ba0-4c7a-b253-42c8335d432d} <Trace> MergedBlockOutputStream: filled checksums all_2_2_0 (state Temporary)
2023.02.20 21:24:01.585235 [ 2560934 ] {e8eaea58-3ba0-4c7a-b253-42c8335d432d} <Debug> default.tt (76e9568f-6150-41f2-91d8-aa4880d2a9a9) (Replicated OutputStream): Wrote block with ID 'all_8062692066948936483_8663586595462158314', 1 rows
2023.02.20 21:24:01.587934 [ 2560934 ] {e8eaea58-3ba0-4c7a-b253-42c8335d432d} <Trace> default.tt (76e9568f-6150-41f2-91d8-aa4880d2a9a9): Renaming temporary part tmp_insert_all_2_2_0 to all_1_1_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
2023.02.20 21:24:01.590663 [ 2560836 ] {} <Debug> default.tt (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000001 - log-0000000001
2023.02.20 21:24:01.590645 [ 2560934 ] {e8eaea58-3ba0-4c7a-b253-42c8335d432d} <Error> MergeTreeData::DataPartsVector DB::MergeTreeData::Transaction::commit(MergeTreeData::DataPartsLock *): Code: 49. DB::Exception: CreationTID of part all_1_1_0 (table default.tt (76e9568f-6150-41f2-91d8-aa4880d2a9a9)) is set to unexpected value (16339, 689, 48b4e225-75d
a-4cb4-8a5c-91cf62daefef), it's a bug. Current transaction: <none>. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xbb157c4 in /usr/bin/clickhouse
1. ? @ 0x10e9cd2c in /usr/bin/clickhouse
2. DB::IMergeTreeDataPart::assertHasVersionMetadata(DB::MergeTreeTransaction*) const @ 0x10e9cbdc in /usr/bin/clickhouse
3. DB::MergeTreeTransaction::addNewPartAndRemoveCovered(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const>>> const&, DB::MergeTreeTransaction*) @ 0x104efef0 in /us
r/bin/clickhouse
4. DB::MergeTreeData::Transaction::commit(std::__1::unique_lock<std::__1::mutex>*) @ 0x10f46b40 in /usr/bin/clickhouse
5. ? @ 0x112253f4 in /usr/bin/clickhouse
6. DB::ReplicatedMergeTreeSinkImpl<false>::commitPart(std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, bool) @ 0x11216178 in /usr/bin/clickhouse
7. DB::ReplicatedMergeTreeSinkImpl<false>::finishDelayedChunk(std::__1::shared_ptr<DB::ZooKeeperWithFaultInjection> const&) @ 0x11213e4c in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeSinkImpl<false>::consume(DB::Chunk) @ 0x11212858 in /usr/bin/clickhouse
9. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x1168b830 in /usr/bin/clickhouse
10. ? @ 0x115a5e34 in /usr/bin/clickhouse
11. ? @ 0x115a5b58 in /usr/bin/clickhouse
12. DB::ExceptionKeepingTransform::work() @ 0x115a547c in /usr/bin/clickhouse
13. DB::ExecutionThreadContext::executeTask() @ 0x113ef280 in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x113e51ec in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x113e4474 in /usr/bin/clickhouse
16. DB::PipelineExecutor::execute(unsigned long) @ 0x113e416c in /usr/bin/clickhouse
17. ? @ 0x113e3170 in /usr/bin/clickhouse
18. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xbbccca8 in /usr/bin/clickhouse
19. ? @ 0xbbd1868 in /usr/bin/clickhouse
20. start_thread @ 0x7624 in /usr/lib/aarch64-linux-gnu/libpthread-2.31.so
21. ? @ 0xd149c in /usr/lib/aarch64-linux-gnu/libc-2.31.so
 (version 23.1.2.9 (official build))
2023.02.20 21:24:01.590782 [ 2560670 ] {} <Trace> BaseDaemon: Received signal -1
2023.02.20 21:24:01.590826 [ 2560670 ] {} <Fatal> BaseDaemon: (version 23.1.2.9 (official build), build id: 0A67B582AE62368899919CE615BE3F31E773A1A5) (from thread 2560934) Terminate called for uncaught exception:
2023.02.20 21:24:01.590846 [ 2560670 ] {} <Fatal> BaseDaemon: Code: 49. DB::Exception: CreationTID of part all_1_1_0 (table default.tt (76e9568f-6150-41f2-91d8-aa4880d2a9a9)) is set to unexpected value (16339, 689, 48b4e225-75da-4cb4-8a5c-91cf62daefef), it's a bug. Current transaction: <none>. (LOGICAL_ERROR), Stack trace (when copying this message, al
ways include the lines below):
```

**Comment by tavplubix** [comment] 2023-02-20 21:39
`Transaction::commit` is not related to transactions.

As for the `CreationTID of part ...` logical error, it's a duplicate of https://github.com/ClickHouse/ClickHouse/issues/42703

**Closed by tavplubix** 2023-02-20 21:39 UTC
Labels: bug, crash
