### ISSUE TITLE
filesystem* functions produces wrong result in case of distributed queries.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#17937] opened 2020-12-09 16:46 UTC
**Describe the bug**
filesystem* functions in case of remote/distributed queries return results either from local eiter from remote server.

**How to reproduce**
```
SELECT
    hostName() AS host,
    version() AS version,
    now64() AS now,
    formatReadableSize(filesystemFree()) AS free_space,
    formatReadableSize(filesystemCapacity()) AS total_space,
    round(100 * (1 - (filesystemFree() / filesystemCapacity())), 1) AS used_percentage
FROM remote('host_1', system.one)
ORDER BY
    hostName() ASC,
    used_percentage ASC

┌─host──────────────────────┬─version───┬─────────────────────now─┬─free_space─┬─total_space─┬─used_percentage─┐
│ host_1                    │ 20.8.7.15 │ 2020-12-09 16:42:20.457 │ 97.01 GiB  │ 98.31 GiB   │             1.3 │
└───────────────────────────┴───────────┴─────────────────────────┴────────────┴─────────────┴─────────────────┘
explain pipeline:
┌─explain─────────────┐
│ (Converting)        │
│ Converting          │
│   (ReadFromStorage) │
└─────────────────────┘

next execution:

┌─host──────────────────────┬─version───┬─────────────────────now─┬─free_space─┬─total_space─┬─used_percentage─┐
│ host_1                    │ 20.8.7.15 │ 2020-12-09 16:42:19.918 │ 95.25 GiB  │ 98.31 GiB   │             3.1 │
└───────────────────────────┴───────────┴─────────────────────────┴────────────┴─────────────┴─────────────────┘
explain pipeline
┌─explain───────────┐
│ (ReadFromStorage) │
└───────────────────┘
```
https://github.com/ClickHouse/ClickHouse/blob/bac1def5f974564b221a43c5bbc21bf65906774b/src/Functions/hostName.cpp#L47

https://github.com/ClickHouse/ClickHouse/blob/bac1def5f974564b221a43c5bbc21bf65906774b/src/Functions/filesystem.cpp

**Additional context**
It would work correctly if we use materialize() on top of function.

**Comment by den-crane** [comment] 2020-12-09 17:42
duplicate of https://github.com/ClickHouse/ClickHouse/issues/7666 ?

**Comment by UnamedRus** [comment] 2020-12-09 17:54
I would say it's related, right, but it doesn't has GROUP BY in it.
Issue would reproduce only if we have now64() in the query, if we remove it from the query, it would produce the right results.

**Comment by alexey-milovidov** [comment] 2022-10-19 23:04
According to ClickHouse's spec, in the case of Distributed query processing, it is unspecified, on what server each function will be run.

**Closed by alexey-milovidov** 2022-10-19 23:04 UTC
Labels: unexpected behaviour
