### ISSUE TITLE
two Code: 49  error when use a row policy row in filter, "Inconsistent number of columns" and  "Invalid number of rows in Chunk column" 

### ISSUE THREAD

**Issue by danelfedor** [ClickHouse/ClickHouse#42311] opened 2022-10-14 08:55 UTC
clickhouse version is ClickHouse server version 22.8.5 revision 54460 which is a lts version offical build
my table create like :
```
CREATE TABLE db_repo_test.position_test3
(
    query_time DateTime ,
    account_id UInt16 ,
    symbol String ,
    position UInt32 
)
ENGINE = MergeTree
ORDER BY query_time
SETTINGS index_granularity = 8192 
```
the row policy is 	`account_id IN (136, 134, 108, 112, 130, 76)`
sql `select * from db_repo_test.position_test3 where account_id = 108 ;`
will give error 
>Received exception from server (version 22.8.5):
Code: 49. DB::exception: Received from 10.140.2.126:9000. DB::exception: Inconsistent number of columns got from 
MergeTreeRangeReader. Have 10 in sample block and 2 columns in list: While executing MergeTreeInOrder. 

another sql  `select position from db_repo_test.position_test3 where account_id = 108 ;`
will give error 
> Code: 49. DB::exception: Received from 10.140.2.126:9000. DB::exception: Invalid number of rows in Chunk column UInt32 position 1: expected 2481, got 1246: While executing MergeTreeInOrder.

**Comment by ramazanpolat** [comment] 2022-10-14 09:20
@danelfedor Can you please show your command for creating the row policy?

**Comment by danelfedor** [comment] 2022-10-14 09:23
> @danelfedor Can you please show your command for creating the row policy?


`
CREATE ROW POLICY p_stock_position_test3_mdu ON db_trade_repo_test.stock_position_test3 USING account_id in (136, 134, 108, 112, 130, 76) TO mdu`

**Comment by danelfedor** [comment] 2022-10-18 06:11
try version [v22.8.6.71-lts] still have the problem but error code is different
try version [v22.3.13.80-lts] do not have this problem , currnetly  we down grade our version to this one

**Comment by davenger** [comment] 2023-01-10 12:02
@danelfedor, this release https://github.com/ClickHouse/ClickHouse/releases/tag/v22.8.12.45-lts includes the fix for 'Invalid number of rows in Chunk' bug https://github.com/ClickHouse/ClickHouse/pull/42126 which should address the issue with row level policies. I think it might also address the 'Inconsistent number of columns' issue.
Could you please try this release to see if the issue is fixed for you?

**Comment by davenger** [comment] 2023-09-18 10:13
There are no new reports since the fix was merged

**Closed by davenger** 2023-09-18 10:13 UTC
Labels: potential bug
