### ISSUE TITLE
ALTER TABLE UPDATE using data coming from different tables

### ISSUE THREAD

**Issue by hugocatlas** [ClickHouse/ClickHouse#54645] opened 2023-09-14 17:13 UTC
Hello ClickHouse team,

Continuing my task of migrating a Redshift codebase to ClickHouse, I'm facing several problems with ALTER TABLE UPDATEs in ClickHouse

I understand that ClickHouse's design is not oriented to this type of workload, but my focus right now is to get as much as possible of the original code running on ClickHouse before going any further with any optimization.

In Redshift, I have the following query:

```
UPDATE
    bills
SET
    transaction_billed = transaction_id
FROM
    transactions
WHERE
    transactions.created_at >= sysdate - 1
AND
    transactions.username = 'test_account'
AND
    transactions.token = bills.final_token
```

As far as I understand from 
* https://stackoverflow.com/questions/55764093/updating-rows-with-values-from-another-table-in-clickhouse
* #5538
* #17806
* #21099
* https://clickhouse.com/docs/en/sql-reference/statements/alter/update
* https://clickhouse.com/docs/en/sql-reference/functions/other-functions#joinget
* https://clickhouse.com/docs/en/engines/table-engines/special/join

I would expect the following (or variations of) to fulfil my need in ClickHouse:

```
CREATE TABLE transactions_join
ENGINE = Join(ANY, INNER, token)  AS
SELECT
        token, -- also tried `token AS final_token`
        transaction_id
FROM transactions
WHERE (created_at >= (NOW() - toIntervalDay(1)) AND (username = 'test_account')
;

ALTER TABLE bills
UPDATE transaction_billed = joinGet('transactions_join', 'transaction_id', 'token') -- also tried `'final_token`
WHERE 1=1
;

DROP TABLE transactions_join;
```

But I'm getting numerous errors (`joinGet only supports StorageJoin of type Left Any. (INCOMPATIBLE_TYPE_OF_JOIN)`, `StorageJoin doesn't contain column ...`, etc) around which I can't wrap my head around.

Maybe the most striking one that I would consider as an unexpected behavior is the absolute requirement of having a WHERE clause in ALTER TABLE UPDATE statement. In older snippets I've found online, queries seem to work just fine without it, however that doesn't seem to be the case any more (I'm running clickhouse 23.3.13).

The cases where I do find a query that seems to work, the `bills` table remains pristine, and I find the error `Code: 125. DB::Exception: Scalar subquery returned more than one row` in `system.mutations` table.

Could anyone help me find a way out of this loophole, please?

Cheers,

Hugo

**Comment by UnamedRus** [comment] 2023-09-14 17:18
Why not dictionary?

https://kb.altinity.com/altinity-kb-queries-and-syntax/update-via-dictionary/

**Comment by derekmahar** [comment] 2023-09-14 21:08
I've also tried unsuccessfully to compose a similar ALTER TABLE UPDATE operation would update a table column using values from a column in another table.  I was also equally surprised that the WHERE clause was required.  ALTER TABLE UPDATE is quite limited compared to standard SQL UPDATE.

**Comment by hugocatlas** [comment] 2023-09-15 08:31
> Why not dictionary?
> 
> https://kb.altinity.com/altinity-kb-queries-and-syntax/update-via-dictionary/

Pardon my short sight, but I don't get why using a dictionary would be different of using the Join table engine. As far as I get it, both will rely on retrieving the data from the other table when updating the current table, either by using `joinGet` or `dictGet`.

**Comment by hugocatlas** [comment] 2023-09-15 12:53
So, in my quest trying to make this work, I've got something, but now the problem is that, regardless of how I set up the join table, the joinGet returns Null. 
I've replaced the WHERE clause from `1=1` by `final_token in (select token from transactions_join)`
The table gets indeed updated, but all the values are set to Null.

**Comment by derekmahar** [comment] 2023-09-18 17:56
> Why not dictionary?
> 
> https://kb.altinity.com/altinity-kb-queries-and-syntax/update-via-dictionary/

I used your advice to use a dictionary to update a table using another table.  It works, but I find it cumbersome.  I'd really prefer to use a standard SQL `UPDATE` statement.

```
CREATE DICTIONARY domains.DomainsExcludeDict (
  name String,
  eppstatus Int64
)
PRIMARY KEY name
SOURCE(CLICKHOUSE(TABLE 'DomainsExclude'))
LAYOUT(COMPLEX_KEY_DIRECT);

ALTER TABLE domains.DomainsInclude
UPDATE eppstatus = dictGet('domains.DomainsExcludeDict', 'eppstatus', name)
WHERE dictHas('domains.DomainsExcludeDict', name);
```

(See [test source code](https://github.com/ClickHouse/ClickHouse/files/12651829/clickhouse_update_domains.zip).)

**Comment by den-crane** [comment] 2023-09-21 13:16
>SQL UPDATE

it's kinda available in Cloud clickhouse https://clickhouse.com/blog/clickhouse-cloud-boosts-performance-with-sharedmergetree-and-lightweight-updates

----

I am closing it, because all behaviors described here are expected, by design.

**Closed by den-crane** 2023-09-21 13:16 UTC
Labels: unexpected behaviour

**Comment by den-crane** [comment] 2023-09-21 13:19
There is no "update" functionality in Clickhouse.
`alter update` is admin operation, designed to fulfill GDRP requirements. It's implemented as an `alter` specifically to reflect that it's not an `upadate`.
