### ISSUE TITLE
[Question] Best practice for single value update (additional table/workaround)

### ISSUE THREAD

**Issue by Slind14** [ClickHouse/ClickHouse#1661] opened 2017-12-18 16:53 UTC
Hi there,
I have a database which is being populated early on and at a later time there is a single value that can change. In this case whether the content was seen or not.

In databases supporting `update` I just change the default boolean from `false` to `true`.
In Clickhouse my database layout is like this:

```
CREATE TABLE impressions
ENGINE = MergeTree(`date`, (`impressionUUID`, `date`), 8192)
AS SELECT
toFixedString(UUIDStringToNum(`impressionUUID`), 16) AS `impressionUUID`,
toDate(`timestamp`) as `date`,
[...]
```

```
CREATE TABLE impressions_seen
ENGINE = MergeTree(`date`, (`impressionUUID`, `date`), 8192)
AS SELECT
toFixedString(UUIDStringToNum(`impressionUUID`), 16) AS `impressionUUID`,
assumeNotNull(`seen`) AS `seen`,
toDate(`timestamp`) as `date`,
`timestamp`
FROM log
WHERE `seen` = 1;
```
The query would be:
```
SELECT
    language as _group,
    toDate(timestamp) as _date,
    [...]
    COUNT(seen) as seen
FROM impressions
ANY LEFT JOIN impressions_seen USING(impressionUUID)
WHERE `timestamp` BETWEEN '2017-01-01 00:00:00' AND '2017-11-28 00:00:00'
GROUP BY _group, _date;
```

Now I do not know the inner workings of ClickHouse. Does it make sense to set the key on `impressionUUID` for both tables instead of the `timestamp`?
Is MergeTree the best engine for the `seen` table?
Does `date` add any value on the `seen` table? (`seen` is only used in joins)
Is there a way to improve the join, e.g. by counting the hits instead of `seen` which is always `1`?

**Comment by filimonov** [comment] 2017-12-18 20:48
Did you check CollapsingMergeTree or ReplacingMergeTree? Both allows you to put new version of existing row at any time. During background merge process older version of row get replaces/collapsed. If you will add FINAL clause to your selects you will always get freshest row. Without FINAL clause you can get 2 variants of the same row untill background merges will remove older.

**Comment by Slind14** [comment] 2017-12-19 07:39
The update could happen seconds or hours later. My understanding is that merging happens at random times only for non Merged rows. Did I get that wrong?

**Comment by filimonov** [comment] 2017-12-19 12:48
Each insert create it's own part. Later small parts are merged together and bigger parts appear which will also be merged later. That's why it's called MergeTree. During each merge data is sorted according to primary key. If you're using Replacing / Collapsing merge tree - duplicate rows are removed during Merges. If you're using Aggregating / Summing merge tree - rows with same primary key get grouped. 

Parts from  different partitions (by default: months) are never merged. If you get parts of the maximum size already - it's not merged with others.

So if you will insert that new version of the row several hours later, it will be merged with some smaller parts which were inserted recently. Later that bigger parts will be merged to even bigger. At the some moment in time parts containing old version of row and new version of row will be merged and older variant of the row will be removed . 

Look on that picture from [wikipedia](https://en.wikipedia.org/wiki/Log-structured_merge-tree): 

![LSM-Tree](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/LSM_Tree.png/600px-LSM_Tree.png)

If you add FINAL keyword it works like a group by primary key to get freshest variant of the row, so selects with FINAL clause work noticeable slower that regular selects.

**Comment by Slind14** [comment] 2017-12-19 13:13
ok, so in order for it work in real time I would need to use FINAL in the query? Isn't the solution with a second table and join faster, then and especially more accurate?

**Comment by filimonov** [comment] 2017-12-19 13:27
The best way is to try. Each case is different - test on **your** data with **your** requests and **your** load is always the best way to check which approach suits you the best.

If your list of _seen_ records is small - you can even use dictionary for that.

**Comment by Slind14** [comment] 2017-12-19 13:33
Its only the was seen/wasn't seen. I don't think a dictionary would help here. I'm using 0/1 for that or with the join a left join exists.

**Comment by filimonov** [comment] 2017-12-21 20:55
If it's millions and 50% of the records are "seen" dictionary is definitely not an option. 

I still think that CollapsingMergeTree / ReplacingMergeTree will be better for your case. It's more universal (with that engines you can also make other updates), and if you will update only fresh data (as you said: second up to hours) - that means that all older data will stay untouched and ready to use (no need to merge big old parts with small newly inserted), only during merging relatively fresh and relatively small parts collapsing / replacing will happen.

With extra table you will need to make joins and read 2 tables all the time.  On my data joins are usually slower than group by (FINAL clause is kind of group by primary key), so i think it will also be faster.  If you don't need to make reports in realtime you can also run OPTIMIZE TABLE ... before building reports instead of FINAL clause in SELECTs. 

But I repeat: the only correct way to get the answer - is to test. If you don't have real data yet, you can make tests on some dummy data, and some simulated load.

About nest practices and your SELECTs: in clickhouse if you have some typical SELECT pattern - it's better to add columns which are always used in group by to primary key.
So if in your select you're always (or almost always) grouping the data by  language and date, - then if will be nice idea to add them at the begining of your primary key.
Also if you already have `date` column used for partitioning, it's better to always to setup conditions on that date fields, to help clickhouse understand which partitions whould be read. Optimizer in clickhouse if quite simple, and probably it will not understand what toDate(timestamp) as _date is actually the same as date column.

**Comment by Slind14** [comment] 2017-12-21 21:03
Thank you very much. Once I have a big dataset with load I'll do benchmarks with different schemas. Unfortunately that isn't the case yet and therefore  I'm thankful for your guidance which allows me to get the most out of what I have.

A single table also has the advantage that I can use the join for other things without the need of workarounds that probably hurt performance :) 

If the update occurs usually within 5 minutes, will merging be fast? E.g. if I run a realtime query without final, will only the last hour be off, since everything older is very likely to be merged by then?

**Comment by Slind14** [comment] 2017-12-21 21:14
> About best practices and your SELECTs: in clickhouse if you have some typical SELECT pattern - it's better to add columns which are always used in group by to primary key.
So if in your select you're always (or almost always) grouping the data by language and date, - then it will be nice idea to add them at the begining of your primary key.
Also if you already have date column used for partitioning, it's always better to setup conditions on that date fields, to help clickhouse understand which partitions should be read. Optimizer in clickhouse if quite simple, and probably it will not understand what toDate(timestamp) as _date is actually the same as date column, and it will fairly covert timestamps to dates for each row instead of using column where that data is stored ready to use.

I always group by date and one of the variables, but I need timezone support. If I understood you right, it would be better to group and select on the date column used by the mergetree? But I guess this won't work if I need the data grouped in a specific timezone, does it?

The second group is always different, it can be a single column or multiple. Therefore, if needed one table for each group might be helpful? (since disk space is cheaper than computing power)

**Comment by filimonov** [comment] 2017-12-21 21:23
> If the update occurs usually within 5 minutes, will merging be fast? E.g. if I run a realtime query without final, will only the last hour be off, since everything older is very likely to be merged by then?

And there aro no garantee that it will merge the parts as you would expect. So lets say your A parts contains impression, and B parts - "seen" information. 

So they can be inserted like A1-B1-A2-B2-A3-B3, but merged A1B1A2, B2A3, B3. And it appereantly will have duplicates. 

Just try it with a FINAL keyword. Clickhouse is really fast, most probably performance will satisfy your needs. For now it sound like you're doing (premature optimizations)[http://wiki.c2.com/?PrematureOptimization].

> The second group is always different, it can be a single column or multiple. Therefore, if needed one table for each group might be helpful? (since disk space is cheaper than computing power)
Juse start with one table, and don't do too many premature optimizations. Sounds like you didn't try yet, but expecting that it will go slow. Most probably you will be surprized how fast can Clickhouse be, especially if you're switching from MySQL / Postgres :) And if you will not be satisfied - there a lot of options how you can make it even faster, includind materialized views with preaggregation.

**Comment by filimonov** [comment] 2017-12-21 21:38
>Btw. do you know if there is any gain from using NVMe SSDs (4-5 times the iops and seq. read) over SATA SSDs?

Are you asking about CLickhouse or in general? :) In clickhouse disk reads happens only for "cold" data. If you have a lot of memory, and most of parts which are actively used fit in memory - disk speed is not too big problem, as disk reads happens not so often. So if your active 'hot' data can fit into RAM or your selects mostly for random parts - faster disks / storages will improve the performance. We're using regular HDDs for clickhouse. AFAIK Yandex also use HDDs in their Metrika cluster.

**Comment by Slind14** [comment] 2017-12-21 23:11
I see, so I'm better off saving on the disks and putting the savings into memory.
Thank you for all the specific information :)

**Comment by alex-zaitsev** [comment] 2017-12-22 07:38
> Btw. do you know if there is any gain from using NVMe SSDs (4-5 times the iops and seq. read) over SATA SSDs?

It depends on workload. ClickHouse works fine with SATA, especially in RAID. There is definitely the gain when using faster disks. In our experiments, SATA RAID-10 with 10-12 disks is slower than the same setup with SAS disks that comes close to NVMe, but still 1.5 times behind on test queries.

However, for most cases SATA is sufficient (and more affordable).

**Comment by Slind14** [comment] 2017-12-23 14:09
I have been trying to give the CollapsingMergeTree a run. Unfortunately, as soon as I add "FINAL" it doesn't return anything.

```
CREATE TABLE impressions
ENGINE = CollapsingMergeTree(`date`, (`impressionUUID`, `date`), 8192, sign)
AS SELECT
toInt8(-1) AS `sign`,
toFixedString(UUIDStringToNum(`impressionUUID`), 16) AS `impressionUUID`,
`seen`,
toDate(`timestamp`) as `date`,
[...]
```
```
SELECT
    language as _group,
    toDate(timestamp) as _date,
    [...]
    COUNT(seen) as seen
FROM impressions FINAL
WHERE `timestamp` BETWEEN '2017-01-01 00:00:00' AND '2017-11-28 00:00:00'
GROUP BY _group, _date;
```
Am I missing something?
When I get the seen event, I only have the impressionUUID. Does this mean I would need to run a select first (which won't scale)?

**Comment by Slind14** [comment] 2018-04-12 15:59
Unfortunately I still haven't found a way which performs with hundreds of million of rows for real time data. If only the data would be available at the same time and could be written with one query.

I'm seeing upwards 80 million row/s when selecting data from a single table. As soon as I join or or make use of Collapsing/Replacing MergeTrees I'm down to 3 million row/s. 
Materialized views aren't helping either, since we can't update these either when the records of a join change.

@filimonov If you have any more ideas on how I could solve this, I would very much appreciate it.

**Comment by filimonov** [comment] 2018-04-12 18:37
Updates in that scenario cost mostly nothing (as they happen outside of clickhouse). Selects will use external dict before 'fixing' the final value (by OPMIZIE FINAL), so it's more about performance of external dictionary during that time. But that allows you to store outside only limited amount of data (for last day or few) and only one column, so probably you can find some fast solution for that task (if you have a lot of SELECTs for current day and fast UPDATES). 

> Could I use another clickhouse table as data source and decide based on record exists/does not exist? (or would performance not be optimal for these kinds of operations?)
Clickhouse is not good for single row lookup, here the lot of such lookups will be needed.

Generally that can't be used as general purpose updates as it require clearing / rewriting of the whole column for one partition. But in some cases in could be useful, so may by @alexey-milovidov or other developer from Yandex team can adopt it in some way.

**Comment by Slind14** [comment] 2018-04-12 18:52
> Updates in that scenario cost mostly nothing (as they happen outside of clickhouse). Selects will use external dict before 'fixing' the final value (by OPMIZIE FINAL), so it's more about performance of external dictionary during that time. But that allows you to store outside only limited amount of data (for last day or few) and only one column, so probably you can find some fast solution for that task (if you have a lot of SELECTs for current day and fast UPDATES).

hmm, doesn't the merging which happens automatically break non optimized data?
When I run the OPTIMIZE FINAL, is the table able to write while it runs. e.g. if it needs to update 100 million rows with an external dictionary, that is probably going to take some time and I don't want to loose data.

I don't need to update data, I only need to set what was undefined/unknown before, hence when I use another database for temp storage I only have inserts on there.

For the external data source I'm probably good off with mongodb (if the look ups are fast enough, which they should), cassandra or redis. What do you think?

**Comment by filimonov** [comment] 2018-04-12 19:07
> or could we keep the dictionary lookup active for the last n hours/days and do the optimize partition final for older records? So old old partitions would be a single table read and new partitions with the dictionary lookup. I don't know how performance will with this. I have up to 100 million new records per day.

Yes, that's what i've tried to propose, may be my expkanations wasn't clear enought. So last day/or few from dictionary. Older data - materialized and stored in column.

That will allow to keep dictionary relatively small and fast, and also performance downgrade caused by using dictionary will affect only last days or few (older data will be materialized and immutable).

> When I run the OPTIMIZE FINAL, is the table able to write while it runs. e.g. if it needs to update 100 million rows with an external dictionary, that is probably going to take some time and I don't want to loose data.

Yes it is 100% safe, generally optimize final do the same job as normal background merges.

**Comment by Slind14** [comment] 2018-04-12 19:39
> Yes, that's what i've tried to propose, may be my expkanations wasn't clear enought. So last day/or few from dictionary. Older data - materialized and stored in column.

You wrote: 

> if in a meanwhile some background merges will happen they will materialize b again
for merged subrange, so you need to call CLEAR COLUMN after every update of source,
to avoid using some values which were materialized by background merges.

Doesn't this mean, that the latest records are not being read from the dictionary if they haven been merged which happens automatically at random times?

**Comment by derekperkins** [comment] 2018-04-12 19:40
> For the external data source I'm probably good off with mongodb (if the look ups are fast enough, which they should), cassandra or redis

@Slind14 Dictionary lookups aren't done directly against your db, so it doesn't really matter what you use. ClickHouse polls your dictionary for changes and keeps the most recent data in RAM for query-time lookups. Just use whatever db is easiest for you.

**Comment by Slind14** [comment] 2018-04-12 19:47
> @Slind14 Dictionary lookups aren't done directly against your db, so it doesn't really matter what you use. ClickHouse polls your dictionary for changes and keeps the most recent data in RAM for query-time lookups. Just use whatever db is easiest for you.

ahh, I see. @derekperkins is there something I can read on how it does this? E.g. if it checks for changes once an hour I have issues with real time data.

**Comment by derekperkins** [comment] 2018-04-12 19:48
https://clickhouse.yandex/docs/en/dicts/external_dicts_dict_lifetime/

**Comment by filimonov** [comment] 2018-04-12 19:55
> Doesn't this mean, that the latest records are not being read from the dictionary if they haven been merged which happens automatically at random times?

Yes. And It is not true realtime updates. It is some workaround for _some_ updates

Everything depends on concrete usage scenario.

> Dictionary lookups aren't done directly against your db, so it doesn't really matter what you use

That's true if the data stored in dict has less than 1 mln rows. If it's more - perfrormance of dictionary matters.

**Comment by Slind14** [comment] 2018-04-12 20:02
> Clickhouse is not good/optimal for single row lookup, here a lot of such lookups will be needed.

> most recent data in RAM

hmm, when Dictionaries are cached in memory for quick access, why would it do one lookup for every key/value? 

I have a few tables with ~100 million new rows per day, if we work with daily partitions and optimize, wouldn't this mean we have ~200 million data points in the dictionary cache at the end of the day? Considering the amount of tables that exist, I find this difficult to muster in terms of memory required for it.

**Comment by filimonov** [comment] 2018-04-12 20:12
Check that https://clickhouse.yandex/docs/en/dicts/external_dicts_dict_layout/

If flat or hashed will siute your needs - you don't need key/value lookups. For cache (which is slowest, but most universal) - key lookups needed.

**Comment by Slind14** [comment] 2018-04-12 20:32
My keys are binary UUIDs. So I should probably go with hashed?
Now since it states that it is "completely" stored in memory, doesn't this mean that I can use a clickhouse table where I don't have issues with write and read performance as long as writes are batched and the read being one query for all the key/values?

In my case I only need to read the data when the user is requesting it, hence the hit rate on `cache` is probably extremely low, especially on first read.

**Comment by filimonov** [comment] 2018-04-13 06:29
You said that you can have about 100 mln 'seen' records dayly - that means that your dict will ~16Gb size overall for one day. `hashed` or `flat` need to reread *whole* table after change. So in that case after every update of underlying table (and you want to do it each minute) 16Gb of data should be copied from underlying table to memory. Not sure if that solution will be optimal. Rather look on `cache`.

**Comment by filimonov** [comment] 2018-04-13 06:41
Another variant - if that "seen" event can happen only once in short timeframe - may be it would be optimal to you just to store one day of data in some other DB outside of clickhouse, and just copy it to clickchouse after that 'mutable' period? So some external DB like mysql/postgres/whatever will store data for one day, in that case the amount of data will not be too big, even simple mysql can deal quite well with 100 mln rows. And clickhouse will get the final version of data after some time, and will store the whole history.

**Comment by filimonov** [comment] 2018-04-13 06:42
Also you can take a look on that: https://www.percona.com/blog/2018/01/09/updating-deleting-rows-clickhouse-part-1/

**Comment by Slind14** [comment] 2018-04-16 02:47
I'll try it with a union query.
1. table with +2 days old data, with the seen bool as column
2. table with the live data partitioned by day and join to second table with seen records

This is the best I could come up with in terms of keeping it simple, on one database and fast.

**Comment by blinkov** [comment] 2018-07-27 12:56
@Slind14 do you have any further questions?

**Comment by Slind14** [comment] 2018-07-27 12:59
I'm still lacking a proper solution for this use case. I did a lot of work around's which add a lot of points of failure. If there is another better way which we haven't thought of, it would be great.

**Comment by blinkov** [comment] 2018-07-27 13:36
Which solution you ended up with at the moment?

**Comment by Slind14** [comment] 2018-07-29 14:03
I have two datasets, one consistent of two tables with the latest data and one single table with all the data. 
Once a day I write the data from the day before yesterday from the "live" table**s** to the "history" table. 
The issue I'm still facing is with datasets which span around hundred of millions of records per day. Although we have only the latest data across two tables the join is still spanning around massive amounts of data and even with indexed binary UUIDs and 48 cores this takes forever. This also prevents me from using aggregated engines for the "live" data.

**Comment by blinkov** [comment] 2018-07-30 07:43
@Slind14 And why it's just 48 cores? Which hardware setup do you have?

**Comment by Slind14** [comment] 2018-07-30 09:38
@blinkov the CPU power isn't even the bottleneck. A query runs for multiple minutes and the CPU usage stays below 30%. I assume this is due to the join since queries without a join get the CPU to 100%.
The SSDs are sleeping during this process as well and the memory is used 90% for cache. (512GB)

**Comment by Slind14** [comment] 2018-08-16 23:39
@blinkov do you have any idea/suggestion on how we can improve this? Sampling doesn't work either because the joined table is still massive.

**Comment by blinkov** [comment] 2018-08-20 10:44
@Slind14 I see you have tried CollapsingMergeTree earlier, but had some issues with FINAL. Meanwhile the recommended approach is to rewrite queries in a way that FINAL is not needed, like replacing COUNT(*) with SUM(Sign), have you managed to do that?

As of hardware, it sounds like you are using just one server, right?

**Comment by Slind14** [comment] 2018-08-20 10:54
Atm. just one server, yes. Using FINAL has been super slow as well, I could give it another shot but I doubt that it is much faster than what I'm currently doing. It wasn't back then.

**Comment by blinkov** [comment] 2018-08-20 10:58
So have you rewritten your select queries so they return correct result on CollapsingMergeTree **without** FINAL? If not, it's definitely worth giving a shot.

**Comment by Slind14** [comment] 2018-11-15 15:23
So, I revisited the possibility of collapsing and replacing MergeTrees because we are looking at the multi billion records a day.

Due to the amount of requests we receive we have a load balancing setup with a good amount of nodes. Because some requests (updates) are coming in with < 5ms inbetween it seems impossible to work a temp storage for the collapsing merge tree. But initially the data is coming from the client which could cache the old data to send both the old and the new data. In this case we would only have an issue with the data that is collected server side (geo, UA) but this shouldn't change too often. So the only major remaining is the timestamp. The timestamp is generated by the database it self (now()). Is there any solution for this? Ultimately we want the initial timestamp and not the one from the update.

The timestamp is also an issue with the replacing merge tree.

**Comment by Slind14** [comment] 2019-06-06 17:37
I would like to reiterate this topic because there still isn't a solution.

To summarize, we are receiving data for the same object at different times, sometimes delayed by hours. We need the latest, summed or joined data on the spot in real-time including sampling support.

Suggested approaches and their result (using a small database of just 30 million unique objects at 50 million events):

Join (control): +4 seconds
Dictionary: +20 seconds
Replacing Merge Tree: +15 seconds (`PREWHERE (id, version) IN (SELECT id, max(version))`)
Collapsing Merge Tree: +4 seconds (same as join, `GROUP BY id`)
Summing Merge Tree: same as Collapsing Merge Tree

**Comment by MeteHanC** [comment] 2019-08-28 07:30
Why  'Alter table update' was not suggested in this case? Correct me if I am wrong but it says **_'... mutations are intended for heavy operations that change a lot of rows in a table'_** on the offcial [documentation](https://clickhouse.yandex/docs/en/query_language/alter/#alter-mutations). 
It is not that much but have tried 'alter table update' with 1M rows, it was actually pretty fast. (Updated 1K rows of 1M data, elapsed time was 6ms) 

And if you could give further information about the 'alter table update's use case, performance etc,  I would be appreciated @filimonov @blinkov

**Comment by blinkov** [comment] 2019-08-28 07:40
@MeteHanC mutations are done asynchronously, it just got scheduled that fast, not executed. To check how they are going you need to look into `system.mutations` table.

**Comment by MeteHanC** [comment] 2019-08-28 07:52
> mutations are done asynchronously, it just got scheduled that fast, not executed. To check how they are going you need to look into `system.mutations` table.

I understand. I checked it and it is being done in no time. 'done' column was set to '1' immediately and it was also replicated to other CH nodes instantly as well. 

What I am trying to understand is, how does alter mutation work? Is it not reliable and will the mutation take place 'eventually'? (just like Merging process of Merge Tree family) @blinkov

**Comment by blinkov** [comment] 2020-04-01 16:46
@Slind14, do you have any further questions?

**Comment by Slind14** [comment] 2020-04-06 08:52
We still haven't found a solution to achieve this in a way that scales.

**Comment by compasses** [comment] 2020-08-05 11:51
@MeteHanC Hi, I just wonder your test case run against on no replica merge tree? do you have checked the ReplicatedMergeTree, and QPS benchmark? Maybe no problem for one time update, but how about many updates in a short time, hybrid with many selects.
Just want to know the realtime performance of CH, @blinkov do you have any advice? thanks.

**Comment by pavelsc** [comment] 2021-06-03 13:27
Hi guys, any resolutions on this?
What about to create main table as MergeTree and table with updates as CollapsingMergeTree. Then use UNION ALL for two tables with Group By

**Closed** 2022-05-22 22:31 UTC
Labels: question, st-need-info
