### ISSUE TITLE
Logical error: Number of rows in source parts differs from number of bytes written to rows_sources file

### ISSUE THREAD

**Issue by Tiaonmmn** [ClickHouse/ClickHouse#29111] opened 2021-09-17 01:54 UTC
> You have to provide the following information whenever possible.

Clickhouse uses all CPU for long time,and logs report something weired.

> A clear and concise description of what works not as it is supposed to.

When `show processlist;` does not report anything,Clickhouse's CPU should not be too high.
It appears on Clickhouse 21.9.2.17.

**How to reproduce**

I don't know what other information should be provided,please tell me what to provide.

**Error message and/or stacktrace**

2021.09.17 09:40:44.989993 [ 44768 ] {} <Error> auto DB::IBackgroundJobExecutor::execute(DB::JobAndPool)::(anonymous class)::operator()() const: Code: 49. DB::Exception: Number of rows in source parts (3715000) differs from number of bytes written to rows_sources file (1857500). It is a bug. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9366e7a in /usr/bin/clickhouse
1. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, std::__1::shared_ptr<DB::Context const>, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeData::MergingParams const&, DB::IMergeTreeDataPart const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x114d43bd in /usr/bin/clickhouse
2. DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::BackgroundProcessListEntry<DB::MergeListElement, DB::MergeInfo>&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, long, std::__1::shared_ptr<DB::Context const>, std::__1::unique_ptr<DB::IReservation, std::__1::default_delete<DB::IReservation> > const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::MergeTreeData::MergingParams const&, DB::IMergeTreeDataPart const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x114d29b5 in /usr/bin/clickhouse
3. DB::StorageMergeTree::mergeSelectedParts(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::StorageMergeTree::MergeMutateSelectedEntry&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0x116a0904 in /usr/bin/clickhouse
4. ? @ 0x116b1697 in /usr/bin/clickhouse
5. ? @ 0x113dd177 in /usr/bin/clickhouse
6. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x93aabb8 in /usr/bin/clickhouse
7. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x93ac75f in /usr/bin/clickhouse
8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x93a7e9f in /usr/bin/clickhouse
9. ? @ 0x93ab783 in /usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe9fd in /usr/lib64/libc-2.17.so
 (version 21.9.2.17 (official build))

**Comment by Tiaonmmn** [comment] 2021-09-19 15:53
Later,I found the problem table,it seems like:
```sql
create table xxx (
begintime Datetime,
a String,
b Float32,
c String,
projection pj_test(select * order by begintime)
)
ENGINE=MergeTree()
ORDER BY (b)
PARTITION BY toYYYYMM(begintime)
```
with nearly 1 billion rows data.

**Comment by tavplubix** [comment] 2021-09-27 19:14
@amosbird, could you please take a look?

**Comment by amosbird** [comment] 2021-09-28 02:21
It's fixed in https://github.com/ClickHouse/ClickHouse/pull/29337 . However we need backport.

**Comment by tavplubix** [comment] 2021-10-04 09:06
Backported to 21.8: https://github.com/ClickHouse/ClickHouse/commit/9034c6ddbe8354ce8a6086a0e8a83c6080b60449

**Closed by tavplubix** 2021-10-04 09:06 UTC
Labels: bug, comp-projections

**Comment by desertfury** [comment] 2023-07-17 11:17
```2023.07.17 14:10:36.230305 [ 3947378 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 49. DB::Exception: Number of rows in source parts (256704) differs from number of bytes written to rows_sources file (214282). It is a bug. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3c597a in /usr/bin/clickhouse
1. DB::MergeTask::VerticalMergeStage::prepareVerticalMergeForAllColumns() const @ 0x1575b648 in /usr/bin/clickhouse
2. bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::VerticalMergeStage::subtasks::'lambda'(), bool ()> >(std::__1::__function::__policy_storage const*) @ 0x15763b69 in /usr/bin/clickhouse
3. DB::MergeTask::VerticalMergeStage::execute() @ 0x157601ab in /usr/bin/clickhouse
4. DB::MergeTask::execute() @ 0x1575fd7a in /usr/bin/clickhouse
5. DB::MergePlainMergeTreeTask::executeStep() @ 0x1574f592 in /usr/bin/clickhouse
6. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xa39013b in /usr/bin/clickhouse
7. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xa38fb70 in /usr/bin/clickhouse
8. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa489a26 in /usr/bin/clickhouse
9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xa48b377 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa487348 in /usr/bin/clickhouse
11. ? @ 0xa48a55d in /usr/bin/clickhouse
12. ? @ 0x7f0fcb97c609 in ?
13. clone @ 0x7f0fcb8a3103 in ?
 (version 22.8.5.29 (official build))```
we are still able to reproduce bug

**Comment by desertfury** [comment] 2023-07-17 11:37
> @desertfury This doesn't look that the same bug. You need to provide more information. (There is even no exception message)

updated my message, added bold emphasis around exception message

**Comment by amosbird** [comment] 2023-07-17 11:40
What's the definition of the broken table?

**Comment by desertfury** [comment] 2023-07-17 11:43
This is the table schema

```
│ CREATE TABLE charts.points_v1
(
    `task_id` String CODEC(ZSTD(1)),
    `line` String CODEC(ZSTD(1)),
    `file_hash` UInt32 CODEC(DoubleDelta),
    `created_at` DateTime CODEC(Delta(4), ZSTD(1)),
    `seq_num` UInt64 CODEC(DoubleDelta),
    `timestamp` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value` Float64 CODEC(DoubleDelta),
    `meta` String CODEC(ZSTD(1)),
    `seq_num1` UInt64 CODEC(DoubleDelta),
    `timestamp1` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time1` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value1` Float64 CODEC(DoubleDelta),
    `meta1` String CODEC(ZSTD(1)),
    `seq_num2` UInt64 CODEC(DoubleDelta),
    `timestamp2` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time2` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value2` Float64 CODEC(DoubleDelta),
    `meta2` String CODEC(ZSTD(1)),
    `seq_num3` UInt64 CODEC(DoubleDelta),
    `timestamp3` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time3` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value3` Float64 CODEC(DoubleDelta),
    `meta3` String CODEC(ZSTD(1)),
    `seq_num4` UInt64 CODEC(DoubleDelta),
    `timestamp4` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time4` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value4` Float64 CODEC(DoubleDelta),
    `meta4` String CODEC(ZSTD(1)),
    `seq_num5` UInt64 CODEC(DoubleDelta),
    `timestamp5` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time5` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value5` Float64 CODEC(DoubleDelta),
    `meta5` String CODEC(ZSTD(1)),
    `seq_num6` UInt64 CODEC(DoubleDelta),
    `timestamp6` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time6` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value6` Float64 CODEC(DoubleDelta),
    `meta6` String CODEC(ZSTD(1)),
    `seq_num7` UInt64 CODEC(DoubleDelta),
    `timestamp7` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time7` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value7` Float64 CODEC(DoubleDelta),
    `meta7` String CODEC(ZSTD(1)),
    `seq_num8` UInt64 CODEC(DoubleDelta),
    `timestamp8` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time8` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value8` Float64 CODEC(DoubleDelta),
    `meta8` String CODEC(ZSTD(1)),
    `seq_num9` UInt64 CODEC(DoubleDelta),
    `timestamp9` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `receive_time9` DateTime64(6) CODEC(Delta(4), ZSTD(1)),
    `value9` Float64 CODEC(DoubleDelta),
    `meta9` String CODEC(ZSTD(1))
)
ENGINE = ReplacingMergeTree(created_at)
PRIMARY KEY (task_id, file_hash, line, seq_num)
ORDER BY (task_id, file_hash, line, seq_num)
TTL created_at + toIntervalDay(10)
SETTINGS index_granularity = 8192
```

**Comment by amosbird** [comment] 2023-07-17 11:48
@desertfury This is definitely not related because you don't have any projections. You need to open **a new issue** with complete details of your environment setup and how did you end up with this error, etc.

**Comment by simonenkoav** [comment] 2023-07-17 14:23
Created new issue about the problem @desertfury describes: https://github.com/ClickHouse/ClickHouse/issues/52217
