### ISSUE TITLE
`Merge` table engine shouldn't complain about absent columns

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#64581] opened 2024-05-29 14:00 UTC
**Use case**

To make `merge` table engine a little bit more convenient to use let's not complain about some absent columns in particular tables (the most common scenario). 

```
CREATE TABLE users  (uid Int16, name String, age Int16) ENGINE=Memory;
CREATE TABLE users2 (uid Int16, name String) ENGINE = Memory;
CREATE TABLE m ENGINE=Merge('default', '^users*');
SELECT * FROM m;

Received exception from server (version 24.4.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Column `age` not found in table default.users2 (e6779e06-4371-49cf-b711-218ce4309cbd). (NOT_FOUND_COLUMN_IN_BLOCK)
(query: SELECT * FROM m;)
```

https://fiddle.clickhouse.com/9e3e88a8-b833-493e-96c4-dd0d6b630811

**Describe the solution you'd like**

Add a setting to wrap every column in the result set to Nullable and fill Nulls for tables which don't have this column. Maybe we can also use Variant in case when tables have column with the same name or different types.

**Comment by UnamedRus** [comment] 2024-05-30 04:01
Duplicate https://github.com/ClickHouse/ClickHouse/issues/18681 https://github.com/ClickHouse/ClickHouse/issues/9684

**Comment by skyoct** [comment] 2024-06-15 14:15
@nikitamikhaylov Hello, I want to give it a try.

**Comment by nikitamikhaylov** [comment] 2024-06-15 15:06
@skyoct Thank you!

**Comment by alexey-milovidov** [comment] 2024-06-20 11:47
Duplicate of #64864

**Closed by alexey-milovidov** 2024-06-20 11:47 UTC
Labels: feature
