### ISSUE TITLE
use-of-uninitialized-value in QueryCache

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#49478] opened 2023-05-03 21:36 UTC
https://s3.amazonaws.com/clickhouse-test-reports/49426/189f276ff5eada947a375038160a88b2f0f1815f/stress_test__msan_/stderr.log

```
Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'.
==1651==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55ba71b23c1b in LZ4_count build_docker/./contrib/lz4/lib/lz4.c:625:13
    #1 0x55ba71b23c1b in LZ4_compress_generic_validated build_docker/./contrib/lz4/lib/lz4.c:1103:29
    #2 0x55ba71b23c1b in LZ4_compress_generic build_docker/./contrib/lz4/lib/lz4.c:1289:12
    #3 0x55ba71b23c1b in LZ4_compress_fast_extState build_docker/./contrib/lz4/lib/lz4.c:1304:20
    #4 0x55ba71b30c8f in LZ4_compress_fast build_docker/./contrib/lz4/lib/lz4.c:1376:14
    #5 0x55ba71b30c8f in LZ4_compress_default build_docker/./contrib/lz4/lib/lz4.c:1387:12
    #6 0x55ba557f356f in DB::ColumnCompressed::compressBuffer(void const*, unsigned long, bool) build_docker/./src/Columns/ColumnCompressed.cpp:27:27
    #7 0x55ba55b2683c in DB::ColumnVector<unsigned long>::compress() const build_docker/./src/Columns/ColumnVector.cpp:923:23
    #8 0x55ba553170f4 in DB::ColumnArray::compress() const build_docker/./src/Columns/ColumnArray.cpp:939:39
    #9 0x55ba55122d0f in DB::QueryCache::Writer::finalizeWrite() build_docker/./src/Interpreters/Cache/QueryCache.cpp:288:63
    #10 0x55ba59c8159b in DB::StreamInQueryCacheTransform::finalizeWriteInQueryCache() build_docker/./src/Processors/Transforms/StreamInQueryCacheTransform.cpp:27:22
    #11 0x55ba4fc0c199 in DB::QueryPipeline::finalizeWriteInQueryCache() build_docker/./src/QueryPipeline/QueryPipeline.cpp:597:59
    #12 0x55ba54fcb398 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3::operator()(DB::QueryPipeline&) build_docker/./src/Interpreters/executeQuery.cpp:941:36
    #13 0x55ba54fcb398 in decltype(std::declval<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&>()(std::declval<DB::QueryPipeline&>())) std::__1::__invoke[abi:v15000]<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #14 0x55ba54fcb398 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #15 0x55ba54fcb398 in std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #16 0x55ba54fcb398 in void std::__1::__function::__policy_invoker<void (DB::QueryPipeline&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>>(std::__1::__function::__policy_storage const*, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #17 0x55ba4fbb1953 in std::__1::__function::__policy_func<void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #18 0x55ba4fbb1953 in std::__1::function<void (DB::QueryPipeline&)>::operator()(DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #19 0x55ba4fbb1953 in DB::BlockIO::onFinish() build_docker/./src/QueryPipeline/BlockIO.cpp:57:9
    #20 0x55ba58ec87fe in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp
    #21 0x55ba58f0ee83 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2043:9
    #22 0x55ba65870b5d in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #23 0x55ba65871f8f in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #24 0x55ba65fab04b in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #25 0x55ba65fa6501 in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #26 0x55ba65fa2117 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #27 0x7f93ba117608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #28 0x7f93ba03c132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

  Uninitialized value was created by a heap allocation
    #0 0x55ba186cbca0 in malloc (/usr/bin/clickhouse+0xdf89ca0) (BuildId: ab858bb024e9db391407bd4749c2de138960383f)
    #1 0x55ba35a3c45c in Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) build_docker/./src/Common/Allocator.h:237:27
    #2 0x55ba35a3be6c in Allocator<false, false>::alloc(unsigned long, unsigned long) build_docker/./src/Common/Allocator.h:103:16
    #3 0x55ba1874904a in void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 63ul, 64ul>::resize<>(unsigned long) (/usr/bin/clickhouse+0xe00704a) (BuildId: ab858bb024e9db391407bd4749c2de138960383f)
    #4 0x55ba55b187c9 in DB::ColumnVector<unsigned long>::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/./src/Columns/ColumnVector.cpp:475:10
    #5 0x55ba5530a8c4 in DB::ColumnArray::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) build_docker/./src/Columns/ColumnArray.cpp:532:15
    #6 0x55ba58fd1b53 in DB::Chunk::append(DB::Chunk const&, unsigned long, unsigned long) build_docker/./src/Processors/Chunk.cpp:183:36
    #7 0x55ba5512161b in DB::QueryCache::Writer::finalizeWrite() build_docker/./src/Interpreters/Cache/QueryCache.cpp:266:40
    #8 0x55ba59c8159b in DB::StreamInQueryCacheTransform::finalizeWriteInQueryCache() build_docker/./src/Processors/Transforms/StreamInQueryCacheTransform.cpp:27:22
    #9 0x55ba4fc0c199 in DB::QueryPipeline::finalizeWriteInQueryCache() build_docker/./src/QueryPipeline/QueryPipeline.cpp:597:59
    #10 0x55ba54fcb398 in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3::operator()(DB::QueryPipeline&) build_docker/./src/Interpreters/executeQuery.cpp:941:36
    #11 0x55ba54fcb398 in decltype(std::declval<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&>()(std::declval<DB::QueryPipeline&>())) std::__1::__invoke[abi:v15000]<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #12 0x55ba54fcb398 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&>(DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3&, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #13 0x55ba54fcb398 in std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #14 0x55ba54fcb398 in void std::__1::__function::__policy_invoker<void (DB::QueryPipeline&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)::$_3, void (DB::QueryPipeline&)>>(std::__1::__function::__policy_storage const*, DB::QueryPipeline&) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #15 0x55ba4fbb1953 in std::__1::__function::__policy_func<void (DB::QueryPipeline&)>::operator()[abi:v15000](DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #16 0x55ba4fbb1953 in std::__1::function<void (DB::QueryPipeline&)>::operator()(DB::QueryPipeline&) const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #17 0x55ba4fbb1953 in DB::BlockIO::onFinish() build_docker/./src/QueryPipeline/BlockIO.cpp:57:9
    #18 0x55ba58ec87fe in DB::TCPHandler::runImpl() build_docker/./src/Server/TCPHandler.cpp
    #19 0x55ba58f0ee83 in DB::TCPHandler::run() build_docker/./src/Server/TCPHandler.cpp:2043:9
    #20 0x55ba65870b5d in Poco::Net::TCPServerConnection::start() build_docker/./base/poco/Net/src/TCPServerConnection.cpp:43:3
    #21 0x55ba65871f8f in Poco::Net::TCPServerDispatcher::run() build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #22 0x55ba65fab04b in Poco::PooledThread::run() build_docker/./base/poco/Foundation/src/ThreadPool.cpp:188:14
    #23 0x55ba65fa6501 in Poco::(anonymous namespace)::RunnableHolder::run() build_docker/./base/poco/Foundation/src/Thread.cpp:45:11
    #24 0x55ba65fa2117 in Poco::ThreadImpl::runnableEntry(void*) build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:335:27
    #25 0x7f93ba117608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)

```

**Comment by kssenii** [comment] 2023-05-03 21:36
cc @rschu1ze

**Comment by tavplubix** [comment] 2023-05-04 11:13
Duplicate of #48385

**Closed by tavplubix** 2023-05-04 11:13 UTC
Labels: testing
