### ISSUE TITLE
Sometimes got big iowait after upgrade to 21.8

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#29053] opened 2021-09-15 15:45 UTC
prev version 21.3 
current version 21.8 
after upgrading sometimes get big cpu iowait time
example:
[image](https://user-images.githubusercontent.com/4305175/133465166-9dd8cad6-5d55-4c3e-a98d-a8edb9525208.png)

try to set asynchronous_metrics_update_period_s=60
but its doesnt help

**Comment by alexey-milovidov** [comment] 2021-09-15 21:01
Run `sudo perf top` at the time when CPU usage is high and send the results here.

**Comment by alexsubota** [comment] 2021-09-16 09:22
![image](https://user-images.githubusercontent.com/4305175/133586538-99cc10e8-4804-4559-b226-89a7335200b2.png)
![image](https://user-images.githubusercontent.com/4305175/133586619-30f782a4-9561-4057-a990-b5699e12fea1.png)
![image](https://user-images.githubusercontent.com/4305175/133586646-4a8ee68d-42cd-4654-a46f-4382ab69c110.png)

**Comment by oleg-savko** [comment] 2021-09-16 09:57
I work with @alexsubota and now we can catch one example when it happened: 

for example when query has sorting, and its go into _external_sort_ (_limited by max_bytes_before_external_sort_), CH stop response on any query and hanging.  

Cpu graph:
![image](https://user-images.githubusercontent.com/14272376/133591589-747553f1-9dcf-443e-90a0-eda047c91bda.png)

perf top (in comment above)

**Comment by alexey-milovidov** [comment] 2021-09-16 20:01
Version 21.8 does not have function `PartLogElement::createBlock`.
Maybe you somehow still run previous version?

**Comment by alexey-milovidov** [comment] 2021-09-16 20:02
```
for example when query has sorting, and its go into external_sort (limited by max_bytes_before_external_sort), CH stop response on any query and hanging forever.
(and not only this ch, but all others ch on this machine too. after restart all ch start work fine)
```

Looks strange, maybe you have *extremely* slow IO on this server?

**Comment by alexey-milovidov** [comment] 2021-09-16 20:03
So, the issue is about IO wait time, not CPU time?

**Comment by alexey-milovidov** [comment] 2021-09-16 20:03
Maybe external sort started to be activated more frequently on this version?

**Comment by alexandr-subota-idf** [comment] 2021-09-16 20:10
> Version 21.8 does not have function `PartLogElement::createBlock`.
> Maybe you somehow still run previous version?

v.21.8.5.7

**Comment by alexsubota** [comment] 2021-09-16 20:11
> Version 21.8 does not have function `PartLogElement::createBlock`.
> Maybe you somehow still run previous version?

v.21.8.5.7

**Comment by oleg-savko** [comment] 2021-09-16 20:46
> Version 21.8 does not have function `PartLogElement::createBlock`.
> Maybe you somehow still run previous version?

There is several instance of ch in docker on this server, and one of them v21.7.7.47 (but is almost not used at all), another which used frequent have version  21.8.5.7

and we do `perf log` on server not in container (now i upgrade this one instance and when it happened again will provide for you new fresh `perf log`)

> So, the issue is about IO wait time, not CPU time?

The issue more about why on some load:
>CH stop response on any query and hanging forever.
(and not only this ch, but all others ch on this machine too. after restart one ch with problem, all ch start work fine) 

before upgrade all was working fine without problem

**Comment by oleg-savko** [comment] 2021-09-16 21:27
> ```
> for example when query has sorting, and its go into external_sort (limited by max_bytes_before_external_sort), CH stop response on any query and hanging forever.
> (and not only this ch, but all others ch on this machine too. after restart all ch start work fine)
> ```
> 
> Looks strange, maybe you have _extremely_ slow IO on this server?
<img width="1166" alt="Screenshot 2021-09-17 at 00 23 34" src="https://user-images.githubusercontent.com/14272376/133687604-77faefb9-19d1-49e9-a313-05cc82e7c1e0.png">

I don`t know really, how to correct check IO on disk. But after some googling seems likes it looks not bad.

**Comment by den-crane** [comment] 2021-09-17 15:08
try

```
cat /etc/clickhouse-server/config.d/z_log_disable.xml
<?xml version="1.0"?>
<yandex>
    <asynchronous_metric_log remove="1"/>
    <metric_log remove="1"/>
    <part_log remove="1" />
    <query_log remove="1" />
    <query_thread_log remove="1" />
    <text_log remove="1" />
    <trace_log remove="1"/>
</yandex>
```

**Comment by den-crane** [comment] 2021-09-18 15:41
btw, what filesystem do you use? XFS/Ext4?

**Comment by oleg-savko** [comment] 2021-09-20 07:36
> btw, what filesystem do you use? XFS/Ext4?

ext4

**Comment by oleg-savko** [comment] 2021-09-20 12:19
> try
> 
> ```
> cat /etc/clickhouse-server/config.d/z_log_disable.xml
> <?xml version="1.0"?>
> <yandex>
>     <asynchronous_metric_log remove="1"/>
>     <metric_log remove="1"/>
>     <part_log remove="1" />
>     <query_log remove="1" />
>     <query_thread_log remove="1" />
>     <text_log remove="1" />
>     <trace_log remove="1"/>
> </yandex>
> ```

Tried not helped (


Fresh graph and perf log:

![Screenshot 2021-09-20 at 15 14 24](https://user-images.githubusercontent.com/14272376/134000408-8ec78b3f-0720-42d4-9a8d-b316ac0deb6d.png)


<img width="894" alt="Screenshot 2021-09-20 at 15 15 26" src="https://user-images.githubusercontent.com/14272376/134000536-70eda9e6-0d51-4f66-a963-7bcbc566d696.png">
)


Before upgrade this queries worked fine(

**Comment by alexey-milovidov** [comment] 2021-09-20 12:29
Does it reproduce on another machine?
The fact that it started to be reproduced after upgrade can be a coincidence.

**Comment by oleg-savko** [comment] 2021-09-20 15:13
> Does it reproduce on another machine?
> The fact that it started to be reproduced after upgrade can be a coincidence.

Now we execute one more exciting test:

We create on this machine one more docker container with clickhouse version 21.3, and import data for problem query on it.

When we execute this query on clickhouse with version v21.3, it remain be responsive and can execute another query, BUT another clickhouse with v21.8.5.7 on this machine, hanging and become not responsive for n-time until load not become lower or query finished (even if no running query on it). 

Seems like something wrong in v21.8 exists.

**Comment by filimonov** [comment] 2021-09-20 16:04
can you do the following:
1) run single clickhouse only
2) reproduce the problem
3) count syscalls:  `sudo perf stat -e 'syscalls:sys_enter_*' -a sleep 10 ` 
4) count ext4 events: `sudo perf stat -e 'ext4:*' -a sleep 10`
5) record the system profiling data: `perf record -F 99 -ag -- sleep 10` (later open it using `perf report`) 

Repeat steps 3-5 both for version 21.3 (same load, no problem,) and for version 21.8 (when problem is happeining) and share both results.

**Comment by oleg-savko** [comment] 2021-09-20 19:37
> 3\. sudo perf stat -e 'syscalls:sys_enter_*' -a sleep 10

Seems like its also depends on how much instance is working on, when one ch v21.8 running same query executed successfully((

So for reproduce bigger load I repeat query 3 times, and then he become no responsive:
[sys_calls_v21.8.txt](https://github.com/ClickHouse/ClickHouse/files/7198075/sys_calls_v21.8.txt)
[ext4_events_v21.8.txt](https://github.com/ClickHouse/ClickHouse/files/7198076/ext4_events_v21.8.txt)


record the system profiling data also hanging and not finished:
<img width="813" alt="Screenshot 2021-09-20 at 22 02 42" src="https://user-images.githubusercontent.com/14272376/134059501-62d91529-b1fa-4e1e-95eb-2add8ecc4c06.png">

until I stop clickhouse by hand:
<img width="740" alt="Screenshot 2021-09-20 at 22 07 12" src="https://user-images.githubusercontent.com/14272376/134060030-8765bb6d-a54e-46e2-9f7d-cc2b657dc216.png">


The same 3 repeated query on one clikchouse v21.3, server is response and without problem execute another queries:
[sys_calls_v21.3.txt](https://github.com/ClickHouse/ClickHouse/files/7198260/sys_calls_v21.3.txt)
[ext4_events_v21.3.txt](https://github.com/ClickHouse/ClickHouse/files/7198264/ext4_events_v21.3.txt)

 perf report:
<img width="1111" alt="Screenshot 2021-09-20 at 22 33 16" src="https://user-images.githubusercontent.com/14272376/134063121-54da3481-a684-4a69-b6ff-c0f4c285f057.png">

**Comment by azat** [comment] 2021-09-20 22:02
But if this is cpu iowait, then what `perf top` will show? (also note that the `swapper` is not swap, [it is idle task](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f1c6f1a7eed96))
From the ext4 traces I see more filesystem usage (new files and similar), what is the query, I guess it is some heavy query with aggregation?
In between 21.3 and 21.8.5.7 I see that `group_by_two_level_threshold_bytes` had been decreased (in #24058), can you try to set it back to `100000000`.
If this will not help, could you please also attach the query execution log (`set send_logs_level=trace` and attach output here)

**Comment by alexey-milovidov** [comment] 2021-09-21 00:13
> But if this is cpu iowait, then what perf top will show?

I agree, missed it first. Let's call it just "iowait".

**Comment by oleg-savko** [comment] 2021-09-21 09:02
> > But if this is cpu iowait, then what perf top will show?
> 
> I agree, missed it first. Let's call it just "iowait".

I suggest to rename issue to: "Sometimes during load ch become not responsive and freeze after upgrade to 21.8"

because on graph the the situation is pretty the same, but in v21.3 you can use clickhouse under load without problem, but in 21.8 all stoped and hanging when there is load on machine (even if no query running in the instance)

> When we execute this query on clickhouse with version v21.3, it remain be responsive and can execute another query, BUT another clickhouse with v21.8.5.7 on this machine at that time, hanging and become not responsive for n-time until load not become lower or query finished (even if no running query on it).

**Comment by oleg-savko** [comment] 2021-09-21 16:04
Maybe when server under load, something in background jobs dont allow clickhouse to be responsive and freeze it (seems like this peaks match with problem on server)
![Screenshot 2021-09-21 at 18 56 57](https://user-images.githubusercontent.com/14272376/134205090-da362972-509f-4188-9a6a-50be35e3a2be.png)

Maybe you can suggest how to better optimize pool params?

**Comment by azat** [comment] 2021-09-21 20:37
@oleg-savko it is hard to tell just by those settings and the graphs of pool tasks.

Can you provide some logs or at least some details?

- what is the query that hangs everything? can you share logs for it?
- according to graphs above you exceed 128 limit for `backgorund_schedule_pool_size`, this is pretty huge. If I did not miss anything, the only heavy thing there is cleanup thread (that cleanup old parts from zookeeper and filesystem), so the question is how much replicated tables do you have? Also maybe you have suboptimal INSERTs that creates tons of small parts that shortly merged, then you can take a look at `temporary_directories_lifetime`/`cleanup_delay_period`

**Closed** 2021-11-04 20:19 UTC
Labels: question, performance, st-need-info, v21.8-affected
