### ISSUE TITLE
clickhouse-keeper cluster not working

### ISSUE THREAD

**Issue by vhp1360** [ClickHouse/ClickHouse#56392] opened 2023-11-06 18:52 UTC
**Describe what's wrong**
I setup clickhouse cluster on three nodes and setup clickhouse-keeper on the same nodes according to the official documents on three virtual machines.
the version is :
> ClickHouse server version 23.10.1.1976 (official build)
> ClickHouse server version 23.10.1.1976 (official build)

**what works not as it is supposed to.**
the result of `SELECT * FROM system.zookeeper WHERE path IN ('/', '/clickhouse');` is:
> 2023.11.06 15:54:29.902052 [ 4478 ] {} <Error> virtual bool DB::DDLWorker::initializeMainThread(): Code: 999. Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: 1.1.110.1:9181, 1.1.110.3:9181, 1.1.110.2:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.10.1.1976 (official build)), 1.1.110.1:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.10.1.1976 (official build)), 1.1.110.3:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.10.1.1976 (official build)), 1.1.110.2:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.10.1.1976 (official build)), 1.1.110.1:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.10.1.1976 (official build)), 1.1.110.3:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.10.1.1976 (official build)), 1.1.110.2:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.10.1.1976 (official build)), 1.1.110.1:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.10.1.1976 (official build)), 1.1.110.3:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 23.10.1.1976 (official build)), 1.1.110.2:9181
. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):
> 
> 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cdd11b7 in /usr/bin/clickhouse
> 1. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x00000000079a030d in /usr/bin/clickhouse
> 2. Coordination::Exception::Exception<String&>(Coordination::Error, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x0000000013018e4a in /usr/bin/clickhouse
> 3. Coordination::ZooKeeper::ZooKeeper(std::vector<Coordination::ZooKeeper::Node, std::allocator<Coordination::ZooKeeper::Node>> const&, zkutil::ZooKeeperArgs const&, std::shared_ptr<DB::ZooKeeperLog>) @ 0x00000000141aeda9 in /usr/bin/clickhouse
> 4. zkutil::ZooKeeper::init(zkutil::ZooKeeperArgs) @ 0x000000001415f6ab in /usr/bin/clickhouse
> 5. zkutil::ZooKeeper::ZooKeeper(Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::ZooKeeperLog>) @ 0x0000000014162b33 in /usr/bin/clickhouse
> 6. DB::Context::getZooKeeper() const @ 0x0000000011ede78b in /usr/bin/clickhouse
> 7. DB::DDLWorker::getAndSetZooKeeper() @ 0x0000000011f60eed in /usr/bin/clickhouse
> 8. DB::DDLWorker::initializeMainThread() @ 0x0000000011f7151b in /usr/bin/clickhouse
> 9. DB::DDLWorker::runMainThread() @ 0x0000000011f5be20 in /usr/bin/clickhouse
> 10. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000011f72a8c in /usr/bin/clickhouse
> 11. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000cebc6a7 in /usr/bin/clickhouse
> 12. start_thread @ 0x00000000000076db in /lib/x86_64-linux-gnu/libpthread-2.27.so
> 13. ? @ 0x000000000012161f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 23.10.1.1976 (official build))

**Does it reproduce on recent release?**
yes I used the latest verion

**Enable crash reporting**
there isn't crash but keepers are connect to each other.
when I run `ss` command I got:
> tcp     LISTEN       0         64                            127.0.0.1:9181                                               0.0.0.0:*                              users:(("clickhouse-keep",pid=8749,fd=37))                                     
> tcp     LISTEN       0         64                                [::1]:9181                                                  [::]:*                              users:(("clickhouse-keep",pid=8749,fd=36)

**How to reproduce**
I go through the official documents. 

* Which ClickHouse server version to use
ClickHouse keeper version 23.10.1.1976 (official build).
ClickHouse server version 23.10.1.1976 (official build)

* Which interface to use, if matters
I'm on ubuntu 18.04

* Non-default settings, if any

* `CREATE TABLE` statements for all tables involved

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.
my issue nearly the same as [this](https://github.com/ClickHouse/ClickHouse/issues/36750) but I don't use docker.
more:
there isn't any network issue or firewall.

clickhouser-server config is:
```
    <remote_servers>
        <default>
            <shard>
                <replica>
                    <host>localhost</host>
                    <port>9000</port>
                </replica>
            </shard>
        </default>
        <cluster_2>
          <shard>
            <replica>
              <host>clickhouse1</host>
              <port>9000</port>
            </replica>
            <replica>
              <host>clickhouse2</host>
              <port>9000</port>
            </replica>
            <replica>
              <host>clickhouse3</host>
              <port>9000</port>
            </replica>
          </shard>
        </cluster_2>
    </remote_servers>
    <zookeeper>
        <node>
            <host>keeper1</host>
            <port>9181</port>
        </node>
        <node>
            <host>keeper2</host>
            <port>9181</port>
        </node>
        <node>
            <host>keeper3</host>
            <port>9181</port>
        </node>
    </zookeeper>
```
and keeper:
```
    <keeper_server>
            <listen_host>0.0.0.0</listen_host>
            <tcp_port>9181</tcp_port>
            <server_id>1</server_id>
            <log_storage_path>/var/lib/clickhouse/coordination/logs</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
            <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <min_session_timeout_ms>10000</min_session_timeout_ms>
                <session_timeout_ms>100000</session_timeout_ms>
                <raft_logs_level>trace</raft_logs_level>
            </coordination_settings>
            <!-- <hostname_checks_enabled>true</hostname_checks_enabled> -->
            <raft_configuration>
                <server>
                    <id>1</id>
                    <hostname>keeper1</hostname>
                    <port>9234</port>
                </server>

                <server>
                    <id>2</id>
                    <hostname>keeper2</hostname>
                    <port>9234</port>
                </server>
                <server>
                    <id>3</id>
                    <hostname>keeper3</hostname>
                    <port>9234</port>
                </server>
            </raft_configuration>
    </keeper_server>
```
and `/etc/hosts` for all nodes are:
```
1.1.110.1 clickhouse1 keeper1
1.1.110.2 clickhouse1 keeper2
1.1.110.3 clickhouse1 keeper3
```
many thanks for helping.

**Comment by antonio2368** [comment] 2023-11-07 08:42
Can you please provide the config from Keeper nodes to verify that the cluster is in a healthy state?
Even though it listens on port 9181 it can still refuse connections if there is no quorum.

**Comment by antonio2368** [comment] 2023-11-07 12:28
Sorry I meant logs

**Comment by vhp1360** [comment] 2023-11-07 12:32
I found a new one:
At first, I installed clickhouse-server with the command "apt install clickhouse-server" and it was installed.
Then I ran "apt install clickhouse-keeper" on the same machine and it installed.
So, I tried "systemctl start clickhouse-server.service" and got _Unit clickhouse-server.service not found._, weird!
Then I ran "apt install clickhouse-server" again and run the above command and it worked.
After that I tried "apt install clickhouse-keeper" to test, wow, it installed again and then I tried "systemctl start clickhouse-server.service" command again, and I got _Unit clickhouse-server.service not found._ message
I hope this new information helps to solve this problem.

**Comment by vhp1360** [comment] 2023-11-07 15:17
> Sorry I meant logs

log or error? and any specific section you would or whole of the file?

**Comment by antonio2368** [comment] 2023-11-07 15:18
entire logs, and as much as possible is always better
good timeframe would be from startup to right after you try querying it from CH

**Comment by vhp1360** [comment] 2023-11-07 15:19
> I found a new one: At first, I installed clickhouse-server with the command "apt install clickhouse-server" and it was installed. Then I ran "apt install clickhouse-keeper" on the same machine and it installed. So, I tried "systemctl start clickhouse-server.service" and got _Unit clickhouse-server.service not found._, weird! Then I ran "apt install clickhouse-server" again and run the above command and it worked. After that I tried "apt install clickhouse-keeper" to test, wow, it installed again and then I tried "systemctl start clickhouse-server.service" command again, and I got _Unit clickhouse-server.service not found._ message I hope this new information helps to solve this problem.

What do you think about it?

**Comment by antonio2368** [comment] 2023-11-07 15:21
That's really interesting, and should be probably fixed
You checked ports and seems like Keeper is running when you try to query it from CH so I would say it's unrelated to your problem, but again I'm not sure.

**Comment by antonio2368** [comment] 2023-11-07 15:28
Can you send from other 2 nodes?
It's strange how not all logs are printed but `<raft_logs_level>trace</raft_logs_level>` is set correctly.
Seems like node 1 is leader.
Can you also do `echo mntr | nc keeper1 9181` and same for `keeper2` and `keeper3`?

**Comment by vhp1360** [comment] 2023-11-07 15:29
> That's really interesting, and should be probably fixed You checked ports and seems like Keeper is running when you try to query it from CH so I would say it's unrelated to your problem, but again I'm not sure.

but I'm guessing some important files faced problems because of overwritten when installed these two services on the same machine.

**Comment by antonio2368** [comment] 2023-11-07 15:30
Yes, it's possible that config files are overwritten

**Comment by vhp1360** [comment] 2023-11-07 15:46
[clickhouse-keeper-Node1.log](https://github.com/ClickHouse/ClickHouse/files/13282777/clickhouse-keeper.log)
[clickhouse-keeper-Node2.log](https://github.com/ClickHouse/ClickHouse/files/13282886/clickhouse-keeper.log)
[clickhouse-keeper-Node3.log](https://github.com/ClickHouse/ClickHouse/files/13282908/clickhouse-keeper.log)

**Comment by alexey-milovidov** [comment] 2023-11-08 03:14
"Connection refused" means misconfiguration.

**Comment by antonio2368** [comment] 2023-11-08 07:54
Keeper cluster in the end seems to create a quorum and should be running.
Also, where are the configurations located? Be careful that CH server are not starting up embedded Keepers if it's on the same node. You can send logs from the servers also just to verify.

**Comment by vhp1360** [comment] 2023-11-09 06:28
thanks.as I told all CH and keeper on the same machine. I meant:
```
1.1.110.1 clickhouse1 keeper1
1.1.110.2 clickhouse2 keeper2
1.1.110.3 clickhouse3 keeper3
```
you meant I must use 6 machine?

**Comment by vhp1360** [comment] 2023-11-09 07:20
> "Connection refused" means misconfiguration.

I can't find the reason.`nc localhost 9181` correct but `nc clickhouse1 9181` or `nc clickhouse2 9181` or ... not working.
I'm sure there isn't any network or firewall issue.

**Comment by antonio2368** [comment] 2023-11-09 09:04
> you meant I must use 6 machine?

of course not, but you would need to separate a bit the storage for Keeper and ClickHouse and make sure different configs are used.
If you are already running on the same machine a viable option for testing is to use embedded Keeper also which will run as part of the CH process.

> but nc clickhouse1 9181 or nc clickhouse2 9181 or ... not working.
I'm sure there isn't any network or firewall issue.

Try setting in your Keeper config
```xml
<clickhouse>
    <listen_host>::</listen_host>
</clickhouse>
```

**Comment by vhp1360** [comment] 2023-11-09 10:30
could you please give me any link to more details about the 
> but you would need to separate a bit the storage for Keeper and ClickHouse and make sure different configs are used.
sentence.

**Comment by vhp1360** [comment] 2023-11-09 13:13
that's correct.
the result of `SELECT * FROM system.zookeeper WHERE path IN ('/', '/clickhouse');` is OK now.
thanks.
I'm appreciated if you add this to document.

**Comment by vhp1360** [comment] 2023-11-09 13:16
just one things more:
what is 'but you would need to separate a bit the storage for Keeper and ClickHouse and make sure different configs are used.'
and [this](https://github.com/ClickHouse/ClickHouse/issues/56392#issuecomment-1798412482)

**Comment by antonio2368** [comment] 2023-11-09 13:20
I will close the issue because the problem is solved.

> what is 'but you would need to separate a bit the storage for Keeper and ClickHouse and make sure different configs are used.'

CH and Keeper use same config so if you run server and standalone Keeper on the same machine while the same config is accessible for both of them you risk for the server to start embedded Keeper with same configuration as the standalone Keeper.
You should simply make sure that config for standalone Keeper is not in the same folder as the config.xml for the server.

**Closed by antonio2368** 2023-11-09 13:20 UTC
Labels: question
